{
  "abstract": [
    {
      "text": "Reduce the need to manually register for trait changes when you use traits within a method or closure that supports automatic trait tracking.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/app-and-environment"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/appearance-customization"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/automatic-trait-tracking"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Automatic trait tracking"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In iOS 18 and later, automatic trait tracking is a UIKit feature that eliminates the need to manually register for trait changes when you use traits in a supported method or closure. This feature reduces the amount of code you need to write and maintain, improves performance, and encourages the best practice of using traits within the scope of the supported APIs.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A complete list of APIs that support automatic trait tracking appears below.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAdaptivePresentationControllerDelegate": {
      "abstract": [
        {
          "text": "A set of methods that, in conjunction with a presentation controller, determine how to respond to trait changes in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAdaptivePresentationControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAdaptivePresentationControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAdaptivePresentationControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIAdaptivePresentationControllerDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uiadaptivepresentationcontrollerdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/configurationUpdateHandler-swift.property": {
      "abstract": [
        {
          "text": "A closure that executes when the button state changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationUpdateHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIButton",
          "text": "UIButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIButtonConfigurationUpdateHandler",
          "text": "ConfigurationUpdateHandler"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/configurationUpdateHandler-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "configurationUpdateHandler"
        }
      ],
      "role": "symbol",
      "title": "configurationUpdateHandler",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/configurationupdatehandler-swift.property"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/updateConfiguration()": {
      "abstract": [
        {
          "text": "Updates the button configuration in response to a button state change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateConfiguration"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/updateConfiguration()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateConfiguration"
        }
      ],
      "role": "symbol",
      "title": "updateConfiguration()",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/updateconfiguration()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/configurationUpdateHandler-7rqbu": {
      "abstract": [
        {
          "text": "A block for handling updates to the cell’s configuration using the current state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationUpdateHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICollectionViewCell",
          "text": "UICollectionViewCell"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So20UICollectionViewCellC5UIKitE26ConfigurationUpdateHandlera",
          "text": "ConfigurationUpdateHandler"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/configurationUpdateHandler-7rqbu",
      "kind": "symbol",
      "role": "symbol",
      "title": "configurationUpdateHandler",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewcell/configurationupdatehandler-7rqbu"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/configurationUpdateHandler-ajhn": {
      "abstract": [
        {
          "text": "A block for handling updates to the cell’s configuration using the current state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "configurationUpdateHandler"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/configurationUpdateHandler-ajhn",
      "kind": "symbol",
      "role": "symbol",
      "title": "configurationUpdateHandler",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewcell/configurationupdatehandler-ajhn"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/updateConfiguration(using:)": {
      "abstract": [
        {
          "text": "Updates the cell’s configuration using the current state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateConfiguration"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit24UICellConfigurationStateV",
          "text": "UICellConfigurationState"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/updateConfiguration(using:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "updateConfiguration(using:)",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewcell/updateconfiguration(using:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/updateConfigurationUsingState:": {
      "abstract": [
        {
          "text": "Updates the cell’s configuration using the current state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "updateConfigurationUsingState:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/updateConfigurationUsingState:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateConfigurationUsingState:"
        }
      ],
      "role": "symbol",
      "title": "updateConfigurationUsingState:",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewcell/updateconfigurationusingstate:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewCompositionalLayoutSectionProvider": {
      "abstract": [
        {
          "text": "A closure that creates and returns each of the layout’s sections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewCompositionalLayoutSectionProvider"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewCompositionalLayoutSectionProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewCompositionalLayoutSectionProvider"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewCompositionalLayoutSectionProvider",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewcompositionallayoutsectionprovider"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentContainer": {
      "abstract": [
        {
          "text": "A set of methods for adapting the contents of your view controllers to size and trait changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIContentContainer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentContainer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentContainer"
        }
      ],
      "role": "symbol",
      "title": "UIContentContainer",
      "type": "topic",
      "url": "/documentation/uikit/uicontentcontainer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5": {
      "abstract": [
        {
          "text": "A mutable container of traits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIMutableTraits"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIMutableTraits"
        }
      ],
      "role": "symbol",
      "title": "UIMutableTraits",
      "type": "topic",
      "url": "/documentation/uikit/uimutabletraits-13ja5"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIMutableTraits"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIMutableTraits",
      "type": "topic",
      "url": "/documentation/uikit/uimutabletraits-8l00o"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPresentationController/containerViewDidLayoutSubviews()": {
      "abstract": [
        {
          "text": "Notifies the presentation controller when layout ends on the views of the container view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "containerViewDidLayoutSubviews"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPresentationController/containerViewDidLayoutSubviews()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "containerViewDidLayoutSubviews"
        }
      ],
      "role": "symbol",
      "title": "containerViewDidLayoutSubviews()",
      "type": "topic",
      "url": "/documentation/uikit/uipresentationcontroller/containerviewdidlayoutsubviews()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPresentationController/containerViewWillLayoutSubviews()": {
      "abstract": [
        {
          "text": "Notifies the presentation controller that layout is about to begin on the views of the container view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "containerViewWillLayoutSubviews"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPresentationController/containerViewWillLayoutSubviews()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "containerViewWillLayoutSubviews"
        }
      ],
      "role": "symbol",
      "title": "containerViewWillLayoutSubviews()",
      "type": "topic",
      "url": "/documentation/uikit/uipresentationcontroller/containerviewwilllayoutsubviews()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/configurationUpdateHandler-746ya": {
      "abstract": [
        {
          "text": "A block for handling updates to the cell’s configuration using the current state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "configurationUpdateHandler"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/configurationUpdateHandler-746ya",
      "kind": "symbol",
      "role": "symbol",
      "title": "configurationUpdateHandler",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/configurationupdatehandler-746ya"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/configurationUpdateHandler-974": {
      "abstract": [
        {
          "text": "A block for handling updates to the cell’s configuration using the current state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationUpdateHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITableViewCell",
          "text": "UITableViewCell"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So15UITableViewCellC5UIKitE26ConfigurationUpdateHandlera",
          "text": "ConfigurationUpdateHandler"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/configurationUpdateHandler-974",
      "kind": "symbol",
      "role": "symbol",
      "title": "configurationUpdateHandler",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/configurationupdatehandler-974"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/updateConfiguration(using:)": {
      "abstract": [
        {
          "text": "Updates the cell’s configuration using the current state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateConfiguration"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit24UICellConfigurationStateV",
          "text": "UICellConfigurationState"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/updateConfiguration(using:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "updateConfiguration(using:)",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/updateconfiguration(using:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/updateConfigurationUsingState:": {
      "abstract": [
        {
          "text": "Updates the cell’s configuration using the current state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "updateConfigurationUsingState:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/updateConfigurationUsingState:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateConfigurationUsingState:"
        }
      ],
      "role": "symbol",
      "title": "updateConfigurationUsingState:",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcell/updateconfigurationusingstate:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewHeaderFooterView/configurationUpdateHandler-3oji2": {
      "abstract": [
        {
          "text": "A block for handling updates to the view’s configuration using the current state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "configurationUpdateHandler"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewHeaderFooterView/configurationUpdateHandler-3oji2",
      "kind": "symbol",
      "role": "symbol",
      "title": "configurationUpdateHandler",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewheaderfooterview/configurationupdatehandler-3oji2"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewHeaderFooterView/configurationUpdateHandler-49slo": {
      "abstract": [
        {
          "text": "A block for handling updates to the view’s configuration using the current state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationUpdateHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITableViewHeaderFooterView",
          "text": "UITableViewHeaderFooterView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So023UITableViewHeaderFooterB0C5UIKitE26ConfigurationUpdateHandlera",
          "text": "ConfigurationUpdateHandler"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewHeaderFooterView/configurationUpdateHandler-49slo",
      "kind": "symbol",
      "role": "symbol",
      "title": "configurationUpdateHandler",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewheaderfooterview/configurationupdatehandler-49slo"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewHeaderFooterView/updateConfiguration(using:)": {
      "abstract": [
        {
          "text": "Updates the view’s configuration using the current state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateConfiguration"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit24UIViewConfigurationStateV",
          "text": "UIViewConfigurationState"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewHeaderFooterView/updateConfiguration(using:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "updateConfiguration(using:)",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewheaderfooterview/updateconfiguration(using:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewHeaderFooterView/updateConfigurationUsingState:": {
      "abstract": [
        {
          "text": "Updates the view’s configuration using the current state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "updateConfigurationUsingState:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewHeaderFooterView/updateConfigurationUsingState:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateConfigurationUsingState:"
        }
      ],
      "role": "symbol",
      "title": "updateConfigurationUsingState:",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewheaderfooterview/updateconfigurationusingstate:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94": {
      "abstract": [
        {
          "text": "A type that calls your code in reaction to changes in the trait environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITraitChangeObservable"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITraitChangeObservable"
        }
      ],
      "role": "symbol",
      "title": "UITraitChangeObservable",
      "type": "topic",
      "url": "/documentation/uikit/uitraitchangeobservable-67e94"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-7qoet": {
      "abstract": [
        {
          "text": "A type that calls your code in reaction to changes in the trait environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITraitChangeObservable"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-7qoet",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitChangeObservable",
      "type": "topic",
      "url": "/documentation/uikit/uitraitchangeobservable-7qoet"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitCollection": {
      "abstract": [
        {
          "text": "A collection of data that represents the environment for an individual element in your app’s user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITraitCollection"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITraitCollection"
        }
      ],
      "role": "symbol",
      "title": "UITraitCollection",
      "type": "topic",
      "url": "/documentation/uikit/uitraitcollection"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitEnvironment": {
      "abstract": [
        {
          "text": "A set of methods that makes the iOS interface environment available to your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITraitEnvironment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitEnvironment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITraitEnvironment"
        }
      ],
      "role": "symbol",
      "title": "UITraitEnvironment",
      "type": "topic",
      "url": "/documentation/uikit/uitraitenvironment"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/draw(_:)": {
      "abstract": [
        {
          "text": "Draws the view’s image within the passed-in rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "draw"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/draw(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawRect:"
        }
      ],
      "role": "symbol",
      "title": "draw(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiview/draw(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/layoutSubviews()": {
      "abstract": [
        {
          "text": "Lays out subviews.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layoutSubviews"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/layoutSubviews()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layoutSubviews"
        }
      ],
      "role": "symbol",
      "title": "layoutSubviews()",
      "type": "topic",
      "url": "/documentation/uikit/uiview/layoutsubviews()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/updateConstraints()": {
      "abstract": [
        {
          "text": "Updates constraints for the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateConstraints"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/updateConstraints()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateConstraints"
        }
      ],
      "role": "symbol",
      "title": "updateConstraints()",
      "type": "topic",
      "url": "/documentation/uikit/uiview/updateconstraints()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/updateContentUnavailableConfiguration(using:)": {
      "abstract": [
        {
          "text": "Updates the content-unavailable configuration for the provided state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateContentUnavailableConfiguration"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit38UIContentUnavailableConfigurationStateV",
          "text": "UIContentUnavailableConfigurationState"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/updateContentUnavailableConfiguration(using:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "updateContentUnavailableConfiguration(using:)",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/updatecontentunavailableconfiguration(using:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/updateContentUnavailableConfigurationUsingState:": {
      "abstract": [
        {
          "text": "Updates the content-unavailable configuration for the provided state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "updateContentUnavailableConfigurationUsingState:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/updateContentUnavailableConfigurationUsingState:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateContentUnavailableConfigurationUsingState:"
        }
      ],
      "role": "symbol",
      "title": "updateContentUnavailableConfigurationUsingState:",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/updatecontentunavailableconfigurationusingstate:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/updateViewConstraints()": {
      "abstract": [
        {
          "text": "Notifies the view controller when its view needs to update its constraints.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateViewConstraints"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/updateViewConstraints()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateViewConstraints"
        }
      ],
      "role": "symbol",
      "title": "updateViewConstraints()",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/updateviewconstraints()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/viewDidLayoutSubviews()": {
      "abstract": [
        {
          "text": "Notifies the view controller when its view finishes laying out its subviews.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "viewDidLayoutSubviews"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/viewDidLayoutSubviews()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "viewDidLayoutSubviews"
        }
      ],
      "role": "symbol",
      "title": "viewDidLayoutSubviews()",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/viewdidlayoutsubviews()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/viewWillLayoutSubviews()": {
      "abstract": [
        {
          "text": "Notifies the view controller that its view is about to lay out its subviews.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "viewWillLayoutSubviews"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/viewWillLayoutSubviews()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "viewWillLayoutSubviews"
        }
      ],
      "role": "symbol",
      "title": "viewWillLayoutSubviews()",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/viewwilllayoutsubviews()"
    },
    "doc://com.apple.uikit/documentation/UIKit/app-and-environment": {
      "abstract": [
        {
          "text": "Manage life-cycle events and your app’s UI scenes, and get information about traits and the environment in which your app runs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/app-and-environment",
      "kind": "article",
      "role": "collectionGroup",
      "title": "App and environment",
      "type": "topic",
      "url": "/documentation/uikit/app-and-environment"
    },
    "doc://com.apple.uikit/documentation/UIKit/appearance-customization": {
      "abstract": [
        {
          "text": "Add Dark Mode support to your app, customize the appearance of bars, and use appearance proxies to modify your UI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/appearance-customization",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Appearance customization",
      "type": "topic",
      "url": "/documentation/uikit/appearance-customization"
    },
    "doc://com.apple.uikit/documentation/UIKit/responding-to-changing-display-modes-on-apple-tv": {
      "abstract": [
        {
          "text": "Change images and resources dynamically when the screen gamut on your device changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/responding-to-changing-display-modes-on-apple-tv",
      "kind": "article",
      "role": "article",
      "title": "Responding to changing display modes on Apple TV",
      "type": "topic",
      "url": "/documentation/uikit/responding-to-changing-display-modes-on-apple-tv"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Adaptivity",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/responding-to-changing-display-modes-on-apple-tv",
        "doc://com.apple.uikit/documentation/UIKit/UITraitCollection",
        "doc://com.apple.uikit/documentation/UIKit/UITraitEnvironment",
        "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94",
        "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5",
        "doc://com.apple.uikit/documentation/UIKit/UIAdaptivePresentationControllerDelegate",
        "doc://com.apple.uikit/documentation/UIKit/UIContentContainer"
      ],
      "title": "Adaptivity"
    }
  ],
  "topicSections": [
    {
      "abstract": [
        {
          "text": "Views support automatic trait tracking when using traits from the trait collection of the view inside any of the following methods.",
          "type": "text"
        }
      ],
      "anchor": "Views",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIView/layoutSubviews()",
        "doc://com.apple.uikit/documentation/UIKit/UIView/updateConstraints()",
        "doc://com.apple.uikit/documentation/UIKit/UIView/draw(_:)"
      ],
      "title": "Views"
    },
    {
      "abstract": [
        {
          "text": "View controllers support automatic trait tracking for both the trait collection of the view controller and the trait collection of its view inside any of the following methods.",
          "type": "text"
        }
      ],
      "anchor": "View-controllers",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/viewWillLayoutSubviews()",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/viewDidLayoutSubviews()",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/updateViewConstraints()",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/updateContentUnavailableConfiguration(using:)"
      ],
      "title": "View controllers"
    },
    {
      "abstract": [
        {
          "text": "Presentation controllers support automatic trait tracking for both the trait collection of the presentation controller and the trait collection of its container view inside any of the following methods.",
          "type": "text"
        }
      ],
      "anchor": "Presentation-controllers",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPresentationController/containerViewWillLayoutSubviews()",
        "doc://com.apple.uikit/documentation/UIKit/UIPresentationController/containerViewDidLayoutSubviews()"
      ],
      "title": "Presentation controllers"
    },
    {
      "anchor": "Buttons",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIButton/updateConfiguration()",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/configurationUpdateHandler-swift.property"
      ],
      "title": "Buttons"
    },
    {
      "anchor": "Collection-view-cells",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/updateConfiguration(using:)",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/configurationUpdateHandler-7rqbu"
      ],
      "title": "Collection view cells"
    },
    {
      "anchor": "Table-view-cells",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/updateConfiguration(using:)",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/configurationUpdateHandler-974"
      ],
      "title": "Table view cells"
    },
    {
      "anchor": "Table-view-headers-and-footers",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITableViewHeaderFooterView/updateConfiguration(using:)",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewHeaderFooterView/configurationUpdateHandler-49slo"
      ],
      "title": "Table view headers and footers"
    },
    {
      "abstract": [
        {
          "text": "The compositional layout section provider supports automatic trait tracking when using traits from the trait collection of the layout environment in the section provider.",
          "type": "text"
        }
      ],
      "anchor": "Collection-view-compositional-layouts",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewCompositionalLayoutSectionProvider"
      ],
      "title": "Collection view compositional layouts"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "abstract": [
                {
                  "text": "Views support automatic trait tracking when using traits from the trait collection of the view inside any of the following methods.",
                  "type": "text"
                }
              ],
              "anchor": "Views",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIView/layoutSubviews()",
                "doc://com.apple.uikit/documentation/UIKit/UIView/updateConstraints()",
                "doc://com.apple.uikit/documentation/UIKit/UIView/draw(_:)"
              ],
              "title": "Views"
            },
            {
              "abstract": [
                {
                  "text": "View controllers support automatic trait tracking for both the trait collection of the view controller and the trait collection of its view inside any of the following methods.",
                  "type": "text"
                }
              ],
              "anchor": "View-controllers",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/viewWillLayoutSubviews()",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/viewDidLayoutSubviews()",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/updateViewConstraints()",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/updateContentUnavailableConfigurationUsingState:"
              ],
              "title": "View controllers"
            },
            {
              "abstract": [
                {
                  "text": "Presentation controllers support automatic trait tracking for both the trait collection of the presentation controller and the trait collection of its container view inside any of the following methods.",
                  "type": "text"
                }
              ],
              "anchor": "Presentation-controllers",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPresentationController/containerViewWillLayoutSubviews()",
                "doc://com.apple.uikit/documentation/UIKit/UIPresentationController/containerViewDidLayoutSubviews()"
              ],
              "title": "Presentation controllers"
            },
            {
              "anchor": "Buttons",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIButton/updateConfiguration()",
                "doc://com.apple.uikit/documentation/UIKit/UIButton/configurationUpdateHandler-swift.property"
              ],
              "title": "Buttons"
            },
            {
              "anchor": "Collection-view-cells",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/updateConfigurationUsingState:",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/configurationUpdateHandler-ajhn"
              ],
              "title": "Collection view cells"
            },
            {
              "anchor": "Table-view-cells",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/updateConfigurationUsingState:",
                "doc://com.apple.uikit/documentation/UIKit/UITableViewCell/configurationUpdateHandler-746ya"
              ],
              "title": "Table view cells"
            },
            {
              "anchor": "Table-view-headers-and-footers",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITableViewHeaderFooterView/updateConfigurationUsingState:",
                "doc://com.apple.uikit/documentation/UIKit/UITableViewHeaderFooterView/configurationUpdateHandler-3oji2"
              ],
              "title": "Table view headers and footers"
            },
            {
              "abstract": [
                {
                  "text": "The compositional layout section provider supports automatic trait tracking when using traits from the trait collection of the layout environment in the section provider.",
                  "type": "text"
                }
              ],
              "anchor": "Collection-view-compositional-layouts",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewCompositionalLayoutSectionProvider"
              ],
              "title": "Collection view compositional layouts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Adaptivity",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/responding-to-changing-display-modes-on-apple-tv",
                "doc://com.apple.uikit/documentation/UIKit/UITraitCollection",
                "doc://com.apple.uikit/documentation/UIKit/UITraitEnvironment",
                "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-7qoet",
                "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o",
                "doc://com.apple.uikit/documentation/UIKit/UIAdaptivePresentationControllerDelegate",
                "doc://com.apple.uikit/documentation/UIKit/UIContentContainer"
              ],
              "title": "Adaptivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitEnvironment/title",
          "value": "UITraitEnvironment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitEnvironment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITraitEnvironment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitEnvironment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITraitEnvironment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPresentationController~1containerViewDidLayoutSubviews()/title",
          "value": "containerViewDidLayoutSubviews"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPresentationController~1containerViewDidLayoutSubviews()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "containerViewDidLayoutSubviews"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCompositionalLayoutSectionProvider/title",
          "value": "UICollectionViewCompositionalLayoutSectionProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCompositionalLayoutSectionProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewCompositionalLayoutSectionProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCompositionalLayoutSectionProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewCompositionalLayoutSectionProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1updateConfiguration()/title",
          "value": "updateConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1updateConfiguration()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "updateConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1updateViewConstraints()/title",
          "value": "updateViewConstraints"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1updateViewConstraints()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "updateViewConstraints"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPresentationController~1containerViewWillLayoutSubviews()/title",
          "value": "containerViewWillLayoutSubviews"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPresentationController~1containerViewWillLayoutSubviews()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "containerViewWillLayoutSubviews"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1viewDidLayoutSubviews()/title",
          "value": "viewDidLayoutSubviews"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1viewDidLayoutSubviews()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "viewDidLayoutSubviews"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1viewWillLayoutSubviews()/title",
          "value": "viewWillLayoutSubviews"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1viewWillLayoutSubviews()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "viewWillLayoutSubviews"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1configurationUpdateHandler-swift.property/title",
          "value": "configurationUpdateHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1configurationUpdateHandler-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "configurationUpdateHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1draw(_:)/title",
          "value": "drawRect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1draw(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawRect:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAdaptivePresentationControllerDelegate/title",
          "value": "UIAdaptivePresentationControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAdaptivePresentationControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAdaptivePresentationControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAdaptivePresentationControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAdaptivePresentationControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitCollection/title",
          "value": "UITraitCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITraitCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitCollection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITraitCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1updateConstraints()/title",
          "value": "updateConstraints"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1updateConstraints()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "updateConstraints"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1layoutSubviews()/title",
          "value": "layoutSubviews"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1layoutSubviews()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "layoutSubviews"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentContainer/title",
          "value": "UIContentContainer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentContainer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentContainer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentContainer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/automatic-trait-tracking"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/automatic-trait-tracking"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
