{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Type Alias","modules":[{"name":"UIKit"}],"externalID":"c:@T@AXBoolReturnBlock","platforms":[{"name":"iOS","deprecated":false,"beta":false,"unavailable":false},{"name":"iPadOS","deprecated":false,"beta":false,"unavailable":false},{"name":"Mac Catalyst","deprecated":false,"beta":false,"unavailable":false},{"name":"tvOS","deprecated":false,"beta":false,"unavailable":false},{"name":"visionOS","beta":false,"deprecated":false,"unavailable":false}],"symbolKind":"typealias","navigatorTitle":[{"kind":"identifier","text":"AXBoolReturnBlock"}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"AXBoolReturnBlock"}],"title":"AXBoolReturnBlock","role":"symbol"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"AXBoolReturnBlock"},{"kind":"text","text":" = () -> "},{"identifier":"doc://com.externally.resolved.symbol/s:Sb","kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"seeAlsoSections":[{"generated":true,"anchor":"Supporting-types","identifiers":["doc://com.apple.uikit/documentation/UIKit/AXArrayReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXAttributedStringArrayReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXAttributedStringReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXContainerTypeReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXCustomActionsReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXCustomRotorsReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXNavigationStyleReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXObjectReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXPathReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXPointReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXRectReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXStringArrayReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXStringReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXTextualContextReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXTraitsReturnBlock"],"title":"Supporting types"}],"sections":[],"variants":[{"paths":["/documentation/uikit/axboolreturnblock"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/axboolreturnblock"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/AXBoolReturnBlock"},"references":{"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/AXAttributedStringReturnBlock":{"role":"symbol","title":"AXAttributedStringReturnBlock","navigatorTitle":[{"kind":"identifier","text":"AXAttributedStringReturnBlock"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/AXAttributedStringReturnBlock","abstract":[],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"AXAttributedStringReturnBlock"}],"kind":"symbol","type":"topic","url":"/documentation/uikit/axattributedstringreturnblock"},"doc://com.apple.uikit/documentation/UIKit/AXStringArrayReturnBlock":{"navigatorTitle":[{"text":"AXStringArrayReturnBlock","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","title":"AXStringArrayReturnBlock","identifier":"doc://com.apple.uikit/documentation/UIKit/AXStringArrayReturnBlock","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AXStringArrayReturnBlock","kind":"identifier"}],"kind":"symbol","url":"/documentation/uikit/axstringarrayreturnblock"},"doc://com.apple.uikit/documentation/UIKit/AXCustomActionsReturnBlock":{"abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AXCustomActionsReturnBlock","kind":"identifier"}],"role":"symbol","url":"/documentation/uikit/axcustomactionsreturnblock","navigatorTitle":[{"text":"AXCustomActionsReturnBlock","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/AXCustomActionsReturnBlock","type":"topic","title":"AXCustomActionsReturnBlock","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/AXNavigationStyleReturnBlock":{"navigatorTitle":[{"text":"AXNavigationStyleReturnBlock","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","title":"AXNavigationStyleReturnBlock","identifier":"doc://com.apple.uikit/documentation/UIKit/AXNavigationStyleReturnBlock","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AXNavigationStyleReturnBlock","kind":"identifier"}],"kind":"symbol","url":"/documentation/uikit/axnavigationstylereturnblock"},"doc://com.apple.uikit/documentation/UIKit/AXPointReturnBlock":{"role":"symbol","abstract":[],"url":"/documentation/uikit/axpointreturnblock","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AXPointReturnBlock","kind":"identifier"}],"title":"AXPointReturnBlock","navigatorTitle":[{"text":"AXPointReturnBlock","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/AXPointReturnBlock","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/AXObjectReturnBlock":{"abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AXObjectReturnBlock","kind":"identifier"}],"role":"symbol","url":"/documentation/uikit/axobjectreturnblock","navigatorTitle":[{"text":"AXObjectReturnBlock","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/AXObjectReturnBlock","type":"topic","title":"AXObjectReturnBlock","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/AXAttributedStringArrayReturnBlock":{"identifier":"doc://com.apple.uikit/documentation/UIKit/AXAttributedStringArrayReturnBlock","kind":"symbol","navigatorTitle":[{"text":"AXAttributedStringArrayReturnBlock","kind":"identifier"}],"type":"topic","title":"AXAttributedStringArrayReturnBlock","url":"/documentation/uikit/axattributedstringarrayreturnblock","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AXAttributedStringArrayReturnBlock","kind":"identifier"}],"role":"symbol","abstract":[]},"doc://com.apple.uikit/documentation/UIKit/AXTextualContextReturnBlock":{"role":"symbol","abstract":[],"url":"/documentation/uikit/axtextualcontextreturnblock","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AXTextualContextReturnBlock","kind":"identifier"}],"title":"AXTextualContextReturnBlock","navigatorTitle":[{"text":"AXTextualContextReturnBlock","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/AXTextualContextReturnBlock","kind":"symbol"},"doc://com.externally.resolved.symbol/s:Sb":{"role":"symbol","abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"type":"topic","url":"/documentation/Swift/Bool","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Sb","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Bool"}],"title":"Bool"},"doc://com.apple.uikit/documentation/UIKit/AXRectReturnBlock":{"abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AXRectReturnBlock","kind":"identifier"}],"role":"symbol","url":"/documentation/uikit/axrectreturnblock","navigatorTitle":[{"text":"AXRectReturnBlock","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/AXRectReturnBlock","type":"topic","title":"AXRectReturnBlock","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/AXArrayReturnBlock":{"role":"symbol","title":"AXArrayReturnBlock","navigatorTitle":[{"text":"AXArrayReturnBlock","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/AXArrayReturnBlock","abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AXArrayReturnBlock","kind":"identifier"}],"kind":"symbol","type":"topic","url":"/documentation/uikit/axarrayreturnblock"},"doc://com.apple.uikit/documentation/UIKit/AXStringReturnBlock":{"navigatorTitle":[{"text":"AXStringReturnBlock","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","title":"AXStringReturnBlock","identifier":"doc://com.apple.uikit/documentation/UIKit/AXStringReturnBlock","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AXStringReturnBlock","kind":"identifier"}],"kind":"symbol","url":"/documentation/uikit/axstringreturnblock"},"doc://com.apple.uikit/documentation/UIKit/AXContainerTypeReturnBlock":{"abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AXContainerTypeReturnBlock","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/AXContainerTypeReturnBlock","role":"symbol","type":"topic","title":"AXContainerTypeReturnBlock","kind":"symbol","url":"/documentation/uikit/axcontainertypereturnblock","navigatorTitle":[{"text":"AXContainerTypeReturnBlock","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/AXPathReturnBlock":{"navigatorTitle":[{"kind":"identifier","text":"AXPathReturnBlock"}],"abstract":[],"type":"topic","role":"symbol","title":"AXPathReturnBlock","identifier":"doc://com.apple.uikit/documentation/UIKit/AXPathReturnBlock","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"AXPathReturnBlock"}],"kind":"symbol","url":"/documentation/uikit/axpathreturnblock"},"doc://com.apple.uikit/documentation/UIKit/AXCustomRotorsReturnBlock":{"role":"symbol","title":"AXCustomRotorsReturnBlock","navigatorTitle":[{"kind":"identifier","text":"AXCustomRotorsReturnBlock"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/AXCustomRotorsReturnBlock","abstract":[],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"AXCustomRotorsReturnBlock"}],"kind":"symbol","type":"topic","url":"/documentation/uikit/axcustomrotorsreturnblock"},"doc://com.apple.uikit/documentation/UIKit/AXBoolReturnBlock":{"role":"symbol","title":"AXBoolReturnBlock","navigatorTitle":[{"text":"AXBoolReturnBlock","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/AXBoolReturnBlock","abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AXBoolReturnBlock","kind":"identifier"}],"kind":"symbol","type":"topic","url":"/documentation/uikit/axboolreturnblock"},"doc://com.apple.uikit/documentation/UIKit/AXTraitsReturnBlock":{"identifier":"doc://com.apple.uikit/documentation/UIKit/AXTraitsReturnBlock","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"AXTraitsReturnBlock"}],"role":"symbol","title":"AXTraitsReturnBlock","navigatorTitle":[{"kind":"identifier","text":"AXTraitsReturnBlock"}],"type":"topic","abstract":[],"url":"/documentation/uikit/axtraitsreturnblock","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"beta":false,"deprecated":false,"unavailable":false,"name":"iOS"},{"beta":false,"deprecated":false,"unavailable":false,"name":"iPadOS"},{"name":"Mac Catalyst","beta":false,"deprecated":false,"unavailable":false},{"name":"tvOS","beta":false,"deprecated":false,"unavailable":false},{"name":"visionOS","beta":false,"deprecated":false,"unavailable":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Type Alias"},{"path":"/metadata/title","op":"replace","value":"AXBoolReturnBlock"},{"path":"/metadata/symbolKind","value":"typealias","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"identifier","text":"AXBoolReturnBlock"}],"op":"replace"},{"path":"/metadata/navigatorTitle","value":[{"kind":"identifier","text":"AXBoolReturnBlock"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"anchor":"Supporting-types","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/AXArrayReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXAttributedStringArrayReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXAttributedStringReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXContainerTypeReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXCustomActionsReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXCustomRotorsReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXNavigationStyleReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXObjectReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXPathReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXPointReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXRectReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXStringArrayReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXStringReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXTextualContextReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXTraitsReturnBlock"],"title":"Supporting types"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"_Bool (^)(void)","preciseIdentifier":"c:BFb()","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"AXBoolReturnBlock","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXAttributedStringReturnBlock/title","value":"AXAttributedStringReturnBlock"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXAttributedStringReturnBlock/fragments","value":[{"kind":"identifier","text":"AXAttributedStringReturnBlock"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXAttributedStringReturnBlock/navigatorTitle","value":[{"kind":"identifier","text":"AXAttributedStringReturnBlock"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXStringArrayReturnBlock/title","value":"AXStringArrayReturnBlock"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXStringArrayReturnBlock/fragments","value":[{"text":"AXStringArrayReturnBlock","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXStringArrayReturnBlock/navigatorTitle","value":[{"text":"AXStringArrayReturnBlock","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXCustomActionsReturnBlock/title","value":"AXCustomActionsReturnBlock"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXCustomActionsReturnBlock/fragments","value":[{"text":"AXCustomActionsReturnBlock","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXCustomActionsReturnBlock/navigatorTitle","value":[{"text":"AXCustomActionsReturnBlock","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXNavigationStyleReturnBlock/title","value":"AXNavigationStyleReturnBlock"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXNavigationStyleReturnBlock/fragments","value":[{"text":"AXNavigationStyleReturnBlock","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXNavigationStyleReturnBlock/navigatorTitle","value":[{"kind":"identifier","text":"AXNavigationStyleReturnBlock"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXPointReturnBlock/title","value":"AXPointReturnBlock"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXPointReturnBlock/fragments","value":[{"text":"AXPointReturnBlock","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXPointReturnBlock/navigatorTitle","value":[{"text":"AXPointReturnBlock","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXObjectReturnBlock/title","value":"AXObjectReturnBlock"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXObjectReturnBlock/fragments","value":[{"kind":"identifier","text":"AXObjectReturnBlock"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXObjectReturnBlock/navigatorTitle","value":[{"kind":"identifier","text":"AXObjectReturnBlock"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXAttributedStringArrayReturnBlock/title","value":"AXAttributedStringArrayReturnBlock"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXAttributedStringArrayReturnBlock/fragments","value":[{"kind":"identifier","text":"AXAttributedStringArrayReturnBlock"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXAttributedStringArrayReturnBlock/navigatorTitle","value":[{"text":"AXAttributedStringArrayReturnBlock","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXTextualContextReturnBlock/title","value":"AXTextualContextReturnBlock"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXTextualContextReturnBlock/fragments","value":[{"kind":"identifier","text":"AXTextualContextReturnBlock"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXTextualContextReturnBlock/navigatorTitle","value":[{"text":"AXTextualContextReturnBlock","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXRectReturnBlock/title","value":"AXRectReturnBlock"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXRectReturnBlock/fragments","value":[{"text":"AXRectReturnBlock","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXRectReturnBlock/navigatorTitle","value":[{"kind":"identifier","text":"AXRectReturnBlock"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXArrayReturnBlock/title","value":"AXArrayReturnBlock"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXArrayReturnBlock/fragments","value":[{"kind":"identifier","text":"AXArrayReturnBlock"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXArrayReturnBlock/navigatorTitle","value":[{"text":"AXArrayReturnBlock","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXStringReturnBlock/title","value":"AXStringReturnBlock"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXStringReturnBlock/fragments","value":[{"kind":"identifier","text":"AXStringReturnBlock"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXStringReturnBlock/navigatorTitle","value":[{"kind":"identifier","text":"AXStringReturnBlock"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXContainerTypeReturnBlock/title","value":"AXContainerTypeReturnBlock"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXContainerTypeReturnBlock/fragments","value":[{"text":"AXContainerTypeReturnBlock","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXContainerTypeReturnBlock/navigatorTitle","value":[{"text":"AXContainerTypeReturnBlock","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXPathReturnBlock/title","value":"AXPathReturnBlock"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXPathReturnBlock/fragments","value":[{"kind":"identifier","text":"AXPathReturnBlock"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXPathReturnBlock/navigatorTitle","value":[{"kind":"identifier","text":"AXPathReturnBlock"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXCustomRotorsReturnBlock/title","value":"AXCustomRotorsReturnBlock"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXCustomRotorsReturnBlock/fragments","value":[{"text":"AXCustomRotorsReturnBlock","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXCustomRotorsReturnBlock/navigatorTitle","value":[{"kind":"identifier","text":"AXCustomRotorsReturnBlock"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXBoolReturnBlock/title","value":"AXBoolReturnBlock"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXBoolReturnBlock/fragments","value":[{"text":"AXBoolReturnBlock","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXBoolReturnBlock/navigatorTitle","value":[{"text":"AXBoolReturnBlock","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXTraitsReturnBlock/title","value":"AXTraitsReturnBlock"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXTraitsReturnBlock/fragments","value":[{"text":"AXTraitsReturnBlock","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXTraitsReturnBlock/navigatorTitle","value":[{"kind":"identifier","text":"AXTraitsReturnBlock"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}