{
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/AXUITextInputReturnBlock"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@AXUITextInputReturnBlock",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "AXUITextInputReturnBlock"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "AXUITextInputReturnBlock"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.1",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.1",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.1",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "AXUITextInputReturnBlock"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AXUITextInputReturnBlock"
            },
            {
              "kind": "text",
              "text": " = () -> (any "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextInput",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)UITextInput",
              "text": "UITextInput"
            },
            {
              "kind": "text",
              "text": ")?"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/AXArrayReturnBlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXArrayReturnBlock"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/AXArrayReturnBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXArrayReturnBlock"
        }
      ],
      "role": "symbol",
      "title": "AXArrayReturnBlock",
      "type": "topic",
      "url": "/documentation/uikit/axarrayreturnblock"
    },
    "doc://com.apple.uikit/documentation/UIKit/AXAttributedStringArrayReturnBlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXAttributedStringArrayReturnBlock"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/AXAttributedStringArrayReturnBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXAttributedStringArrayReturnBlock"
        }
      ],
      "role": "symbol",
      "title": "AXAttributedStringArrayReturnBlock",
      "type": "topic",
      "url": "/documentation/uikit/axattributedstringarrayreturnblock"
    },
    "doc://com.apple.uikit/documentation/UIKit/AXAttributedStringReturnBlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXAttributedStringReturnBlock"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/AXAttributedStringReturnBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXAttributedStringReturnBlock"
        }
      ],
      "role": "symbol",
      "title": "AXAttributedStringReturnBlock",
      "type": "topic",
      "url": "/documentation/uikit/axattributedstringreturnblock"
    },
    "doc://com.apple.uikit/documentation/UIKit/AXBoolReturnBlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXBoolReturnBlock"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/AXBoolReturnBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXBoolReturnBlock"
        }
      ],
      "role": "symbol",
      "title": "AXBoolReturnBlock",
      "type": "topic",
      "url": "/documentation/uikit/axboolreturnblock"
    },
    "doc://com.apple.uikit/documentation/UIKit/AXContainerTypeReturnBlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXContainerTypeReturnBlock"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/AXContainerTypeReturnBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXContainerTypeReturnBlock"
        }
      ],
      "role": "symbol",
      "title": "AXContainerTypeReturnBlock",
      "type": "topic",
      "url": "/documentation/uikit/axcontainertypereturnblock"
    },
    "doc://com.apple.uikit/documentation/UIKit/AXCustomActionsReturnBlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXCustomActionsReturnBlock"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/AXCustomActionsReturnBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXCustomActionsReturnBlock"
        }
      ],
      "role": "symbol",
      "title": "AXCustomActionsReturnBlock",
      "type": "topic",
      "url": "/documentation/uikit/axcustomactionsreturnblock"
    },
    "doc://com.apple.uikit/documentation/UIKit/AXCustomRotorsReturnBlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXCustomRotorsReturnBlock"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/AXCustomRotorsReturnBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXCustomRotorsReturnBlock"
        }
      ],
      "role": "symbol",
      "title": "AXCustomRotorsReturnBlock",
      "type": "topic",
      "url": "/documentation/uikit/axcustomrotorsreturnblock"
    },
    "doc://com.apple.uikit/documentation/UIKit/AXNavigationStyleReturnBlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXNavigationStyleReturnBlock"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/AXNavigationStyleReturnBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXNavigationStyleReturnBlock"
        }
      ],
      "role": "symbol",
      "title": "AXNavigationStyleReturnBlock",
      "type": "topic",
      "url": "/documentation/uikit/axnavigationstylereturnblock"
    },
    "doc://com.apple.uikit/documentation/UIKit/AXObjectReturnBlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXObjectReturnBlock"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/AXObjectReturnBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXObjectReturnBlock"
        }
      ],
      "role": "symbol",
      "title": "AXObjectReturnBlock",
      "type": "topic",
      "url": "/documentation/uikit/axobjectreturnblock"
    },
    "doc://com.apple.uikit/documentation/UIKit/AXPathReturnBlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXPathReturnBlock"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/AXPathReturnBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXPathReturnBlock"
        }
      ],
      "role": "symbol",
      "title": "AXPathReturnBlock",
      "type": "topic",
      "url": "/documentation/uikit/axpathreturnblock"
    },
    "doc://com.apple.uikit/documentation/UIKit/AXPointReturnBlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXPointReturnBlock"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/AXPointReturnBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXPointReturnBlock"
        }
      ],
      "role": "symbol",
      "title": "AXPointReturnBlock",
      "type": "topic",
      "url": "/documentation/uikit/axpointreturnblock"
    },
    "doc://com.apple.uikit/documentation/UIKit/AXRectReturnBlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXRectReturnBlock"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/AXRectReturnBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXRectReturnBlock"
        }
      ],
      "role": "symbol",
      "title": "AXRectReturnBlock",
      "type": "topic",
      "url": "/documentation/uikit/axrectreturnblock"
    },
    "doc://com.apple.uikit/documentation/UIKit/AXStringArrayReturnBlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXStringArrayReturnBlock"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/AXStringArrayReturnBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXStringArrayReturnBlock"
        }
      ],
      "role": "symbol",
      "title": "AXStringArrayReturnBlock",
      "type": "topic",
      "url": "/documentation/uikit/axstringarrayreturnblock"
    },
    "doc://com.apple.uikit/documentation/UIKit/AXStringReturnBlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXStringReturnBlock"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/AXStringReturnBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXStringReturnBlock"
        }
      ],
      "role": "symbol",
      "title": "AXStringReturnBlock",
      "type": "topic",
      "url": "/documentation/uikit/axstringreturnblock"
    },
    "doc://com.apple.uikit/documentation/UIKit/AXTextualContextReturnBlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXTextualContextReturnBlock"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/AXTextualContextReturnBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXTextualContextReturnBlock"
        }
      ],
      "role": "symbol",
      "title": "AXTextualContextReturnBlock",
      "type": "topic",
      "url": "/documentation/uikit/axtextualcontextreturnblock"
    },
    "doc://com.apple.uikit/documentation/UIKit/AXUITextInputReturnBlock": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXUITextInputReturnBlock"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/AXUITextInputReturnBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AXUITextInputReturnBlock"
        }
      ],
      "role": "symbol",
      "title": "AXUITextInputReturnBlock",
      "type": "topic",
      "url": "/documentation/uikit/axuitextinputreturnblock"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextInput": {
      "abstract": [
        {
          "text": "A set of methods for interacting with the text input system and enabling features in documents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextInput"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextInput"
        }
      ],
      "role": "symbol",
      "title": "UITextInput",
      "type": "topic",
      "url": "/documentation/uikit/uitextinput"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Supporting-types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/AXArrayReturnBlock",
        "doc://com.apple.uikit/documentation/UIKit/AXAttributedStringArrayReturnBlock",
        "doc://com.apple.uikit/documentation/UIKit/AXAttributedStringReturnBlock",
        "doc://com.apple.uikit/documentation/UIKit/AXBoolReturnBlock",
        "doc://com.apple.uikit/documentation/UIKit/AXContainerTypeReturnBlock",
        "doc://com.apple.uikit/documentation/UIKit/AXCustomActionsReturnBlock",
        "doc://com.apple.uikit/documentation/UIKit/AXCustomRotorsReturnBlock",
        "doc://com.apple.uikit/documentation/UIKit/AXNavigationStyleReturnBlock",
        "doc://com.apple.uikit/documentation/UIKit/AXObjectReturnBlock",
        "doc://com.apple.uikit/documentation/UIKit/AXPathReturnBlock",
        "doc://com.apple.uikit/documentation/UIKit/AXPointReturnBlock",
        "doc://com.apple.uikit/documentation/UIKit/AXRectReturnBlock",
        "doc://com.apple.uikit/documentation/UIKit/AXStringArrayReturnBlock",
        "doc://com.apple.uikit/documentation/UIKit/AXStringReturnBlock",
        "doc://com.apple.uikit/documentation/UIKit/AXTextualContextReturnBlock"
      ],
      "title": "Supporting types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.1",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "AXUITextInputReturnBlock"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXUITextInputReturnBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXUITextInputReturnBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Supporting-types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/AXArrayReturnBlock",
                "doc://com.apple.uikit/documentation/UIKit/AXAttributedStringArrayReturnBlock",
                "doc://com.apple.uikit/documentation/UIKit/AXAttributedStringReturnBlock",
                "doc://com.apple.uikit/documentation/UIKit/AXBoolReturnBlock",
                "doc://com.apple.uikit/documentation/UIKit/AXContainerTypeReturnBlock",
                "doc://com.apple.uikit/documentation/UIKit/AXCustomActionsReturnBlock",
                "doc://com.apple.uikit/documentation/UIKit/AXCustomRotorsReturnBlock",
                "doc://com.apple.uikit/documentation/UIKit/AXNavigationStyleReturnBlock",
                "doc://com.apple.uikit/documentation/UIKit/AXObjectReturnBlock",
                "doc://com.apple.uikit/documentation/UIKit/AXPathReturnBlock",
                "doc://com.apple.uikit/documentation/UIKit/AXPointReturnBlock",
                "doc://com.apple.uikit/documentation/UIKit/AXRectReturnBlock",
                "doc://com.apple.uikit/documentation/UIKit/AXStringArrayReturnBlock",
                "doc://com.apple.uikit/documentation/UIKit/AXStringReturnBlock",
                "doc://com.apple.uikit/documentation/UIKit/AXTextualContextReturnBlock"
              ],
              "title": "Supporting types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:BF*Qoobjc(pl)UITextInput()",
                    "text": "id<UITextInput> (^)(void)"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "AXUITextInputReturnBlock"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXPointReturnBlock/title",
          "value": "AXPointReturnBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXPointReturnBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXPointReturnBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXPointReturnBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXPointReturnBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXArrayReturnBlock/title",
          "value": "AXArrayReturnBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXArrayReturnBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXArrayReturnBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXArrayReturnBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXArrayReturnBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXContainerTypeReturnBlock/title",
          "value": "AXContainerTypeReturnBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXContainerTypeReturnBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXContainerTypeReturnBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXContainerTypeReturnBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXContainerTypeReturnBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXStringArrayReturnBlock/title",
          "value": "AXStringArrayReturnBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXStringArrayReturnBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXStringArrayReturnBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXStringArrayReturnBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXStringArrayReturnBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXCustomRotorsReturnBlock/title",
          "value": "AXCustomRotorsReturnBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXCustomRotorsReturnBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXCustomRotorsReturnBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXCustomRotorsReturnBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXCustomRotorsReturnBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXAttributedStringArrayReturnBlock/title",
          "value": "AXAttributedStringArrayReturnBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXAttributedStringArrayReturnBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXAttributedStringArrayReturnBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXAttributedStringArrayReturnBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXAttributedStringArrayReturnBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXRectReturnBlock/title",
          "value": "AXRectReturnBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXRectReturnBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXRectReturnBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXRectReturnBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXRectReturnBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInput/title",
          "value": "UITextInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXCustomActionsReturnBlock/title",
          "value": "AXCustomActionsReturnBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXCustomActionsReturnBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXCustomActionsReturnBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXCustomActionsReturnBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXCustomActionsReturnBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXNavigationStyleReturnBlock/title",
          "value": "AXNavigationStyleReturnBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXNavigationStyleReturnBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXNavigationStyleReturnBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXNavigationStyleReturnBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXNavigationStyleReturnBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXStringReturnBlock/title",
          "value": "AXStringReturnBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXStringReturnBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXStringReturnBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXStringReturnBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXStringReturnBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXTextualContextReturnBlock/title",
          "value": "AXTextualContextReturnBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXTextualContextReturnBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXTextualContextReturnBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXTextualContextReturnBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXTextualContextReturnBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXObjectReturnBlock/title",
          "value": "AXObjectReturnBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXObjectReturnBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXObjectReturnBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXObjectReturnBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXObjectReturnBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXAttributedStringReturnBlock/title",
          "value": "AXAttributedStringReturnBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXAttributedStringReturnBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXAttributedStringReturnBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXAttributedStringReturnBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXAttributedStringReturnBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXBoolReturnBlock/title",
          "value": "AXBoolReturnBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXBoolReturnBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXBoolReturnBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXBoolReturnBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXBoolReturnBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXPathReturnBlock/title",
          "value": "AXPathReturnBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXPathReturnBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXPathReturnBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXPathReturnBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXPathReturnBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXUITextInputReturnBlock/title",
          "value": "AXUITextInputReturnBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXUITextInputReturnBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AXUITextInputReturnBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXUITextInputReturnBlock/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AXUITextInputReturnBlock"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/axuitextinputreturnblock"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/axuitextinputreturnblock"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
