{"sections":[],"seeAlsoSections":[{"anchor":"Supporting-types","title":"Supporting types","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/AXArrayReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXAttributedStringArrayReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXAttributedStringReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXBoolReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXContainerTypeReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXCustomActionsReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXCustomRotorsReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXNavigationStyleReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXObjectReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXPathReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXPointReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXRectReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXStringArrayReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXStringReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXTextualContextReturnBlock"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AXVoidReturnBlock","kind":"identifier"},{"text":" = () -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:s4Voida","preciseIdentifier":"s:s4Voida"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"metadata":{"role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AXVoidReturnBlock","kind":"identifier"}],"platforms":[{"deprecated":false,"name":"iOS","unavailable":false,"beta":false},{"deprecated":false,"name":"iPadOS","unavailable":false,"beta":false},{"deprecated":false,"name":"Mac Catalyst","unavailable":false,"beta":false},{"deprecated":false,"name":"tvOS","unavailable":false,"beta":false},{"deprecated":false,"name":"visionOS","unavailable":false,"beta":false}],"modules":[{"name":"UIKit"}],"externalID":"c:@T@AXVoidReturnBlock","title":"AXVoidReturnBlock","roleHeading":"Type Alias","symbolKind":"typealias","navigatorTitle":[{"text":"AXVoidReturnBlock","kind":"identifier"}]},"variants":[{"paths":["/documentation/uikit/axvoidreturnblock"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/axvoidreturnblock"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/AXVoidReturnBlock"},"references":{"doc://com.apple.uikit/documentation/UIKit/AXAttributedStringReturnBlock":{"role":"symbol","title":"AXAttributedStringReturnBlock","navigatorTitle":[{"kind":"identifier","text":"AXAttributedStringReturnBlock"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/AXAttributedStringReturnBlock","abstract":[],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"AXAttributedStringReturnBlock"}],"kind":"symbol","type":"topic","url":"/documentation/uikit/axattributedstringreturnblock"},"doc://com.apple.uikit/documentation/UIKit/AXContainerTypeReturnBlock":{"abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AXContainerTypeReturnBlock","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/AXContainerTypeReturnBlock","role":"symbol","type":"topic","title":"AXContainerTypeReturnBlock","kind":"symbol","url":"/documentation/uikit/axcontainertypereturnblock","navigatorTitle":[{"text":"AXContainerTypeReturnBlock","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/AXVoidReturnBlock":{"abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AXVoidReturnBlock","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/AXVoidReturnBlock","role":"symbol","type":"topic","title":"AXVoidReturnBlock","kind":"symbol","url":"/documentation/uikit/axvoidreturnblock","navigatorTitle":[{"text":"AXVoidReturnBlock","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/AXStringArrayReturnBlock":{"navigatorTitle":[{"text":"AXStringArrayReturnBlock","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","title":"AXStringArrayReturnBlock","identifier":"doc://com.apple.uikit/documentation/UIKit/AXStringArrayReturnBlock","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AXStringArrayReturnBlock","kind":"identifier"}],"kind":"symbol","url":"/documentation/uikit/axstringarrayreturnblock"},"doc://com.apple.uikit/documentation/UIKit/AXTextualContextReturnBlock":{"role":"symbol","abstract":[],"url":"/documentation/uikit/axtextualcontextreturnblock","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AXTextualContextReturnBlock","kind":"identifier"}],"title":"AXTextualContextReturnBlock","navigatorTitle":[{"text":"AXTextualContextReturnBlock","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/AXTextualContextReturnBlock","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/AXBoolReturnBlock":{"role":"symbol","title":"AXBoolReturnBlock","navigatorTitle":[{"text":"AXBoolReturnBlock","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/AXBoolReturnBlock","abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AXBoolReturnBlock","kind":"identifier"}],"kind":"symbol","type":"topic","url":"/documentation/uikit/axboolreturnblock"},"doc://com.apple.uikit/documentation/UIKit/AXStringReturnBlock":{"navigatorTitle":[{"text":"AXStringReturnBlock","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","title":"AXStringReturnBlock","identifier":"doc://com.apple.uikit/documentation/UIKit/AXStringReturnBlock","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AXStringReturnBlock","kind":"identifier"}],"kind":"symbol","url":"/documentation/uikit/axstringreturnblock"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.externally.resolved.symbol/s:s4Voida":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"Void"},{"kind":"text","text":" = ()"}],"abstract":[{"type":"text","text":"The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`."}],"title":"Void","url":"/documentation/Swift/Void","kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s4Voida"},"doc://com.apple.uikit/documentation/UIKit/AXRectReturnBlock":{"abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AXRectReturnBlock","kind":"identifier"}],"role":"symbol","url":"/documentation/uikit/axrectreturnblock","navigatorTitle":[{"text":"AXRectReturnBlock","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/AXRectReturnBlock","type":"topic","title":"AXRectReturnBlock","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/AXPointReturnBlock":{"role":"symbol","abstract":[],"url":"/documentation/uikit/axpointreturnblock","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AXPointReturnBlock","kind":"identifier"}],"title":"AXPointReturnBlock","navigatorTitle":[{"text":"AXPointReturnBlock","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/AXPointReturnBlock","kind":"symbol"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/AXNavigationStyleReturnBlock":{"navigatorTitle":[{"text":"AXNavigationStyleReturnBlock","kind":"identifier"}],"abstract":[],"type":"topic","role":"symbol","title":"AXNavigationStyleReturnBlock","identifier":"doc://com.apple.uikit/documentation/UIKit/AXNavigationStyleReturnBlock","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AXNavigationStyleReturnBlock","kind":"identifier"}],"kind":"symbol","url":"/documentation/uikit/axnavigationstylereturnblock"},"doc://com.apple.uikit/documentation/UIKit/AXCustomActionsReturnBlock":{"abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AXCustomActionsReturnBlock","kind":"identifier"}],"role":"symbol","url":"/documentation/uikit/axcustomactionsreturnblock","navigatorTitle":[{"text":"AXCustomActionsReturnBlock","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/AXCustomActionsReturnBlock","type":"topic","title":"AXCustomActionsReturnBlock","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/AXArrayReturnBlock":{"role":"symbol","title":"AXArrayReturnBlock","navigatorTitle":[{"text":"AXArrayReturnBlock","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/AXArrayReturnBlock","abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AXArrayReturnBlock","kind":"identifier"}],"kind":"symbol","type":"topic","url":"/documentation/uikit/axarrayreturnblock"},"doc://com.apple.uikit/documentation/UIKit/AXPathReturnBlock":{"navigatorTitle":[{"kind":"identifier","text":"AXPathReturnBlock"}],"abstract":[],"type":"topic","role":"symbol","title":"AXPathReturnBlock","identifier":"doc://com.apple.uikit/documentation/UIKit/AXPathReturnBlock","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"AXPathReturnBlock"}],"kind":"symbol","url":"/documentation/uikit/axpathreturnblock"},"doc://com.apple.uikit/documentation/UIKit/AXAttributedStringArrayReturnBlock":{"identifier":"doc://com.apple.uikit/documentation/UIKit/AXAttributedStringArrayReturnBlock","kind":"symbol","navigatorTitle":[{"text":"AXAttributedStringArrayReturnBlock","kind":"identifier"}],"type":"topic","title":"AXAttributedStringArrayReturnBlock","url":"/documentation/uikit/axattributedstringarrayreturnblock","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AXAttributedStringArrayReturnBlock","kind":"identifier"}],"role":"symbol","abstract":[]},"doc://com.apple.uikit/documentation/UIKit/AXObjectReturnBlock":{"abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AXObjectReturnBlock","kind":"identifier"}],"role":"symbol","url":"/documentation/uikit/axobjectreturnblock","navigatorTitle":[{"text":"AXObjectReturnBlock","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/AXObjectReturnBlock","type":"topic","title":"AXObjectReturnBlock","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/AXCustomRotorsReturnBlock":{"role":"symbol","title":"AXCustomRotorsReturnBlock","navigatorTitle":[{"kind":"identifier","text":"AXCustomRotorsReturnBlock"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/AXCustomRotorsReturnBlock","abstract":[],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"AXCustomRotorsReturnBlock"}],"kind":"symbol","type":"topic","url":"/documentation/uikit/axcustomrotorsreturnblock"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"beta":false,"name":"iOS","unavailable":false,"deprecated":false},{"beta":false,"name":"iPadOS","unavailable":false,"deprecated":false},{"beta":false,"name":"Mac Catalyst","unavailable":false,"deprecated":false},{"beta":false,"name":"tvOS","unavailable":false,"deprecated":false},{"beta":false,"name":"visionOS","unavailable":false,"deprecated":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Type Alias","op":"replace","path":"/metadata/roleHeading"},{"value":"AXVoidReturnBlock","op":"replace","path":"/metadata/title"},{"value":"typealias","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"AXVoidReturnBlock"}],"op":"replace","path":"/metadata/fragments"},{"value":[{"text":"AXVoidReturnBlock","kind":"identifier"}],"op":"replace","path":"/metadata/navigatorTitle"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"op":"replace","path":"/hierarchy"},{"op":"add","value":null,"path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"generated":true,"anchor":"Supporting-types","identifiers":["doc://com.apple.uikit/documentation/UIKit/AXArrayReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXAttributedStringArrayReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXAttributedStringReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXBoolReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXContainerTypeReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXCustomActionsReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXCustomRotorsReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXNavigationStyleReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXObjectReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXPathReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXPointReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXRectReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXStringArrayReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXStringReturnBlock","doc://com.apple.uikit/documentation/UIKit/AXTextualContextReturnBlock"],"title":"Supporting types"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"preciseIdentifier":"c:BFv()","kind":"typeIdentifier","text":"void (^)(void)"},{"kind":"text","text":" "},{"kind":"identifier","text":"AXVoidReturnBlock"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"value":"AXAttributedStringReturnBlock","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXAttributedStringReturnBlock/title"},{"value":[{"kind":"identifier","text":"AXAttributedStringReturnBlock"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXAttributedStringReturnBlock/fragments"},{"value":[{"text":"AXAttributedStringReturnBlock","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXAttributedStringReturnBlock/navigatorTitle"},{"value":"AXContainerTypeReturnBlock","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXContainerTypeReturnBlock/title"},{"value":[{"kind":"identifier","text":"AXContainerTypeReturnBlock"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXContainerTypeReturnBlock/fragments"},{"value":[{"text":"AXContainerTypeReturnBlock","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXContainerTypeReturnBlock/navigatorTitle"},{"value":"AXVoidReturnBlock","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXVoidReturnBlock/title"},{"value":[{"text":"AXVoidReturnBlock","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXVoidReturnBlock/fragments"},{"value":[{"kind":"identifier","text":"AXVoidReturnBlock"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXVoidReturnBlock/navigatorTitle"},{"value":"AXStringArrayReturnBlock","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXStringArrayReturnBlock/title"},{"value":[{"text":"AXStringArrayReturnBlock","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXStringArrayReturnBlock/fragments"},{"value":[{"kind":"identifier","text":"AXStringArrayReturnBlock"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXStringArrayReturnBlock/navigatorTitle"},{"value":"AXTextualContextReturnBlock","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXTextualContextReturnBlock/title"},{"value":[{"kind":"identifier","text":"AXTextualContextReturnBlock"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXTextualContextReturnBlock/fragments"},{"value":[{"text":"AXTextualContextReturnBlock","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXTextualContextReturnBlock/navigatorTitle"},{"value":"AXBoolReturnBlock","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXBoolReturnBlock/title"},{"value":[{"text":"AXBoolReturnBlock","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXBoolReturnBlock/fragments"},{"value":[{"text":"AXBoolReturnBlock","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXBoolReturnBlock/navigatorTitle"},{"value":"AXStringReturnBlock","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXStringReturnBlock/title"},{"value":[{"text":"AXStringReturnBlock","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXStringReturnBlock/fragments"},{"value":[{"text":"AXStringReturnBlock","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXStringReturnBlock/navigatorTitle"},{"value":"AXRectReturnBlock","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXRectReturnBlock/title"},{"value":[{"kind":"identifier","text":"AXRectReturnBlock"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXRectReturnBlock/fragments"},{"value":[{"text":"AXRectReturnBlock","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXRectReturnBlock/navigatorTitle"},{"value":"AXPointReturnBlock","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXPointReturnBlock/title"},{"value":[{"text":"AXPointReturnBlock","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXPointReturnBlock/fragments"},{"value":[{"text":"AXPointReturnBlock","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXPointReturnBlock/navigatorTitle"},{"value":"AXNavigationStyleReturnBlock","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXNavigationStyleReturnBlock/title"},{"value":[{"text":"AXNavigationStyleReturnBlock","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXNavigationStyleReturnBlock/fragments"},{"value":[{"text":"AXNavigationStyleReturnBlock","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXNavigationStyleReturnBlock/navigatorTitle"},{"value":"AXCustomActionsReturnBlock","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXCustomActionsReturnBlock/title"},{"value":[{"kind":"identifier","text":"AXCustomActionsReturnBlock"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXCustomActionsReturnBlock/fragments"},{"value":[{"kind":"identifier","text":"AXCustomActionsReturnBlock"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXCustomActionsReturnBlock/navigatorTitle"},{"value":"AXArrayReturnBlock","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXArrayReturnBlock/title"},{"value":[{"text":"AXArrayReturnBlock","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXArrayReturnBlock/fragments"},{"value":[{"kind":"identifier","text":"AXArrayReturnBlock"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXArrayReturnBlock/navigatorTitle"},{"value":"AXPathReturnBlock","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXPathReturnBlock/title"},{"value":[{"kind":"identifier","text":"AXPathReturnBlock"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXPathReturnBlock/fragments"},{"value":[{"text":"AXPathReturnBlock","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXPathReturnBlock/navigatorTitle"},{"value":"AXAttributedStringArrayReturnBlock","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXAttributedStringArrayReturnBlock/title"},{"value":[{"text":"AXAttributedStringArrayReturnBlock","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXAttributedStringArrayReturnBlock/fragments"},{"value":[{"text":"AXAttributedStringArrayReturnBlock","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXAttributedStringArrayReturnBlock/navigatorTitle"},{"value":"AXObjectReturnBlock","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXObjectReturnBlock/title"},{"value":[{"kind":"identifier","text":"AXObjectReturnBlock"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXObjectReturnBlock/fragments"},{"value":[{"kind":"identifier","text":"AXObjectReturnBlock"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXObjectReturnBlock/navigatorTitle"},{"value":"AXCustomRotorsReturnBlock","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXCustomRotorsReturnBlock/title"},{"value":[{"text":"AXCustomRotorsReturnBlock","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXCustomRotorsReturnBlock/fragments"},{"value":[{"kind":"identifier","text":"AXCustomRotorsReturnBlock"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1AXCustomRotorsReturnBlock/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}