{
  "abstract": [
    {
      "text": "Improve your iPadOS app with Mac Catalyst by supporting native controls, multiple windows, sharing, printing, menus and keyboard shortcuts.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/mac-catalyst"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/printing"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/building-and-improving-your-app-with-mac-catalyst"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Building and improving your app with Mac Catalyst"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "This sample code project is associated with WWDC21 sessions: ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/wwdc21/10052/",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/wwdc21/10053/",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/wwdc21/10056/",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "9d16271f9c77/BuildingAndImprovingYourAppWithMacCatalyst.zip": {
      "checksum": "9d16271f9c775dc359e23c14797f8cb2e7574db52144cbba8789631b5d1da6831955bbcf9abd98178d19f4460909ce75d6f1b4606a6bfb3ee3429f9e2da027d1",
      "identifier": "9d16271f9c77/BuildingAndImprovingYourAppWithMacCatalyst.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/9d16271f9c77/BuildingAndImprovingYourAppWithMacCatalyst.zip"
    },
    "doc://com.apple.documentation/documentation/AppKit/touch-bar": {
      "abstract": [
        {
          "text": "Display interactive content and controls in the Touch Bar.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/touch-bar",
      "kind": "article",
      "role": "article",
      "title": "Touch Bar",
      "type": "topic",
      "url": "/documentation/AppKit/touch-bar"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/displaying-a-checkbox-in-your-mac-app-built-with-mac-catalyst": {
      "abstract": [
        {
          "text": "Present a switch control as a Mac-style checkbox when your app runs in the Mac user interface idiom.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/displaying-a-checkbox-in-your-mac-app-built-with-mac-catalyst",
      "kind": "article",
      "role": "article",
      "title": "Displaying a checkbox in your Mac app built with Mac Catalyst",
      "type": "topic",
      "url": "/documentation/uikit/displaying-a-checkbox-in-your-mac-app-built-with-mac-catalyst"
    },
    "doc://com.apple.uikit/documentation/UIKit/mac-catalyst": {
      "abstract": [
        {
          "text": "Create a version of your iPad app that users can run on a Mac device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/mac-catalyst",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Mac Catalyst",
      "type": "topic",
      "url": "/documentation/uikit/mac-catalyst"
    },
    "doc://com.apple.uikit/documentation/UIKit/printing": {
      "abstract": [
        {
          "text": "Display the system print panels and manage the printing process.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/printing",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Printing",
      "type": "topic",
      "url": "/documentation/uikit/printing"
    },
    "doc://com.apple.uikit/documentation/UIKit/removing-the-title-bar-in-your-mac-app-built-with-mac-catalyst": {
      "abstract": [
        {
          "text": "Display content that fills the entire height of a window by removing the title bar.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/removing-the-title-bar-in-your-mac-app-built-with-mac-catalyst",
      "kind": "article",
      "role": "article",
      "title": "Removing the title bar in your Mac app built with Mac Catalyst",
      "type": "topic",
      "url": "/documentation/uikit/removing-the-title-bar-in-your-mac-app-built-with-mac-catalyst"
    },
    "doc://com.apple.uikit/documentation/UIKit/toolbar": {
      "abstract": [
        {
          "text": "Provide a space for controls under a window’s title bar and above your custom content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/toolbar",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Toolbar",
      "type": "topic",
      "url": "/documentation/uikit/toolbar"
    },
    "doc://com.apple.uikit/documentation/UIKit/uikit-catalog-creating-and-customizing-views-and-controls": {
      "abstract": [
        {
          "text": "Customize your app’s user interface with views and controls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/uikit-catalog-creating-and-customizing-views-and-controls",
      "kind": "article",
      "role": "sampleCode",
      "title": "UIKit Catalog: Creating and customizing views and controls",
      "type": "topic",
      "url": "/documentation/uikit/uikit-catalog-creating-and-customizing-views-and-controls"
    },
    "https://developer.apple.com/wwdc21/10052/": {
      "identifier": "https://developer.apple.com/wwdc21/10052/",
      "title": "10052: What’s New in Mac Catalyst",
      "titleInlineContent": [
        {
          "text": "10052: What’s New in Mac Catalyst",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/wwdc21/10052/"
    },
    "https://developer.apple.com/wwdc21/10053/": {
      "identifier": "https://developer.apple.com/wwdc21/10053/",
      "title": "10053: Qualities of a Great Mac Catalyst App",
      "titleInlineContent": [
        {
          "text": "10053: Qualities of a Great Mac Catalyst App",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/wwdc21/10053/"
    },
    "https://developer.apple.com/wwdc21/10056/": {
      "identifier": "https://developer.apple.com/wwdc21/10056/",
      "title": "10056: Qualities of Great iPad and iPhone Apps on Macs with M1",
      "titleInlineContent": [
        {
          "text": "10056: Qualities of Great iPad and iPhone Apps on Macs with M1",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/wwdc21/10056/"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "9d16271f9c77/BuildingAndImprovingYourAppWithMacCatalyst.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "User-interface",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/uikit-catalog-creating-and-customizing-views-and-controls",
        "doc://com.apple.uikit/documentation/UIKit/displaying-a-checkbox-in-your-mac-app-built-with-mac-catalyst",
        "doc://com.apple.uikit/documentation/UIKit/removing-the-title-bar-in-your-mac-app-built-with-mac-catalyst",
        "doc://com.apple.uikit/documentation/UIKit/toolbar",
        "doc://com.apple.documentation/documentation/AppKit/touch-bar"
      ],
      "title": "User interface"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "User-interface",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/uikit-catalog-creating-and-customizing-views-and-controls",
                "doc://com.apple.uikit/documentation/UIKit/displaying-a-checkbox-in-your-mac-app-built-with-mac-catalyst",
                "doc://com.apple.uikit/documentation/UIKit/removing-the-title-bar-in-your-mac-app-built-with-mac-catalyst",
                "doc://com.apple.uikit/documentation/UIKit/toolbar",
                "doc://com.apple.documentation/documentation/AppKit/touch-bar"
              ],
              "title": "User interface"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/building-and-improving-your-app-with-mac-catalyst"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/building-and-improving-your-app-with-mac-catalyst"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
