{
  "abstract": [
    {
      "text": "Specify the appearance and content of your views and cells using configurations.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/appearance-customization"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/configurations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Configurations"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Configurations provide a lightweight way to apply content and styling to views without having to manage the rendering of the appearance yourself.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Using a configuration, you can obtain system default styling for a variety of different view states and customize that styling as needed. Then, you assign that configuration to a view that supports configurations, like ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", or use it to create a custom content view, like ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". The configuration updates itself when the view’s configuration state changes, causing the view to reflect the new styling for that state.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "There are two types of configurations:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Background configurations, which let you specify background appearance for a view. For more information, see ",
                      "type": "text"
                    },
                    {
                      "code": "UIBackgroundConfiguration",
                      "type": "codeVoice"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Content configurations, which let you specify content (like image and text) and styling for that content (like tint color and padding). For list-based content, ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " defines many customization options.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-c.class": {
      "abstract": [
        {
          "text": "A configuration that describes a specific background appearance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIBackgroundConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIBackgroundConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uibackgroundconfiguration-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct": {
      "abstract": [
        {
          "text": "A configuration that describes a specific background appearance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIBackgroundConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBackgroundConfiguration"
        }
      ],
      "role": "symbol",
      "title": "UIBackgroundConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uibackgroundconfiguration-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellConfigurationState-c.class": {
      "abstract": [
        {
          "text": "An object that encapsulates a cell’s state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UICellConfigurationState"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellConfigurationState-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UICellConfigurationState",
      "type": "topic",
      "url": "/documentation/uikit/uicellconfigurationstate-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellConfigurationState-swift.struct": {
      "abstract": [
        {
          "text": "A structure that encapsulates a cell’s state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICellConfigurationState"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellConfigurationState-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICellConfigurationState"
        }
      ],
      "role": "symbol",
      "title": "UICellConfigurationState",
      "type": "topic",
      "url": "/documentation/uikit/uicellconfigurationstate-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell": {
      "abstract": [
        {
          "text": "A single data item when that item is within the collection view’s visible bounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewCell"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewCell"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewCell",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewcell"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIConfigurationColorTransformer-c.typealias": {
      "abstract": [
        {
          "text": "Generates a modified output color from an input color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIConfigurationColorTransformer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIConfigurationColorTransformer-c.typealias",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIConfigurationColorTransformer",
      "type": "topic",
      "url": "/documentation/uikit/uiconfigurationcolortransformer-c.typealias"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIConfigurationColorTransformer-swift.struct": {
      "abstract": [
        {
          "text": "A transformer that generates a modified output color from an input color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIConfigurationColorTransformer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIConfigurationColorTransformer-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIConfigurationColorTransformer"
        }
      ],
      "role": "symbol",
      "title": "UIConfigurationColorTransformer",
      "type": "topic",
      "url": "/documentation/uikit/uiconfigurationcolortransformer-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-1smq1": {
      "abstract": [
        {
          "text": "The requirements for an object that encapsulates a view’s state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIConfigurationState"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-1smq1",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIConfigurationState",
      "type": "topic",
      "url": "/documentation/uikit/uiconfigurationstate-1smq1"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-8d7pd": {
      "abstract": [
        {
          "text": "The requirements for an object that encapsulates a view’s state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIConfigurationState"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-8d7pd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIConfigurationState"
        }
      ],
      "role": "symbol",
      "title": "UIConfigurationState",
      "type": "topic",
      "url": "/documentation/uikit/uiconfigurationstate-8d7pd"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIConfigurationStateCustomKey": {
      "abstract": [
        {
          "text": "A key that defines a custom state for a view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIConfigurationStateCustomKey"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIConfigurationStateCustomKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIConfigurationStateCustomKey"
        }
      ],
      "role": "symbol",
      "title": "UIConfigurationStateCustomKey",
      "type": "topic",
      "url": "/documentation/uikit/uiconfigurationstatecustomkey"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentConfiguration-2raci": {
      "abstract": [
        {
          "text": "The requirements for an object that provides the configuration for a content view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIContentConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentConfiguration-2raci",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIContentConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uicontentconfiguration-2raci"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentConfiguration-9eib5": {
      "abstract": [
        {
          "text": "The requirements for an object that provides the configuration for a content view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIContentConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentConfiguration-9eib5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentConfiguration"
        }
      ],
      "role": "symbol",
      "title": "UIContentConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uicontentconfiguration-9eib5"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableAlignment": {
      "abstract": [
        {
          "text": "Defines the alignment of views in a content-unavailable view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIContentUnavailableAlignment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableAlignment",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIContentUnavailableAlignment",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailablealignment"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableButtonProperties": {
      "abstract": [
        {
          "text": "Properties configuring the appearance and behavior of a button in a content-unavailable view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIContentUnavailableButtonProperties"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableButtonProperties",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIContentUnavailableButtonProperties",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailablebuttonproperties"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class": {
      "abstract": [
        {
          "text": "A content configuration for a content-unavailable view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIContentUnavailableConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIContentUnavailableConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct": {
      "abstract": [
        {
          "text": "A content configuration for a content-unavailable view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIContentUnavailableConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentUnavailableConfiguration"
        }
      ],
      "role": "symbol",
      "title": "UIContentUnavailableConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfigurationState-c.class": {
      "abstract": [
        {
          "text": "An object that encapsulates state for a content-unavailable view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIContentUnavailableConfigurationState"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfigurationState-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIContentUnavailableConfigurationState",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfigurationstate-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfigurationState-swift.struct": {
      "abstract": [
        {
          "text": "A structure that encapsulates state for a content-unavailable view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIContentUnavailableConfigurationState"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfigurationState-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentUnavailableConfigurationState"
        }
      ],
      "role": "symbol",
      "title": "UIContentUnavailableConfigurationState",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfigurationstate-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableImageProperties": {
      "abstract": [
        {
          "text": "Properties configuring the appearance of images in a content-unavailable view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIContentUnavailableImageProperties"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableImageProperties",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIContentUnavailableImageProperties",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableimageproperties"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableTextProperties": {
      "abstract": [
        {
          "text": "Properties configuring the appearance of text in a content-unavailable view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIContentUnavailableTextProperties"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableTextProperties",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIContentUnavailableTextProperties",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailabletextproperties"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentView-3zu2k": {
      "abstract": [
        {
          "text": "The requirements for a content view that you create using a configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIContentView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentView-3zu2k",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIContentView",
      "type": "topic",
      "url": "/documentation/uikit/uicontentview-3zu2k"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentView-5fh3z": {
      "abstract": [
        {
          "text": "The requirements for a content view that you create using a configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIContentView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentView-5fh3z",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentView"
        }
      ],
      "role": "symbol",
      "title": "UIContentView",
      "type": "topic",
      "url": "/documentation/uikit/uicontentview-5fh3z"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-c.class": {
      "abstract": [
        {
          "text": "A content configuration for a list-based content view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIListContentConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIListContentConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct": {
      "abstract": [
        {
          "text": "A content configuration for a list-based content view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIListContentConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIListContentConfiguration"
        }
      ],
      "role": "symbol",
      "title": "UIListContentConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentView": {
      "abstract": [
        {
          "text": "A content view for displaying list-based content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIListContentView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIListContentView"
        }
      ],
      "role": "symbol",
      "title": "UIListContentView",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-c.class": {
      "abstract": [
        {
          "text": "A structure that encapsulates a view’s state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIViewConfigurationState"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIViewConfigurationState",
      "type": "topic",
      "url": "/documentation/uikit/uiviewconfigurationstate-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-swift.struct": {
      "abstract": [
        {
          "text": "A structure that encapsulates a view’s state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewConfigurationState"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewConfigurationState"
        }
      ],
      "role": "symbol",
      "title": "UIViewConfigurationState",
      "type": "topic",
      "url": "/documentation/uikit/uiviewconfigurationstate-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/appearance-customization": {
      "abstract": [
        {
          "text": "Add Dark Mode support to your app, customize the appearance of bars, and use appearance proxies to modify your UI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/appearance-customization",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Appearance customization",
      "type": "topic",
      "url": "/documentation/uikit/appearance-customization"
    },
    "doc://com.apple.uikit/documentation/UIKit/automatic-trait-tracking": {
      "abstract": [
        {
          "text": "Reduce the need to manually register for trait changes when you use traits within a method or closure that supports automatic trait tracking.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/automatic-trait-tracking",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Automatic trait tracking",
      "type": "topic",
      "url": "/documentation/uikit/automatic-trait-tracking"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Appearance-and-content",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/automatic-trait-tracking"
      ],
      "title": "Appearance and content"
    }
  ],
  "topicSections": [
    {
      "anchor": "Configuration-states",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-swift.struct",
        "doc://com.apple.uikit/documentation/UIKit/UICellConfigurationState-swift.struct",
        "doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-8d7pd",
        "doc://com.apple.uikit/documentation/UIKit/UIConfigurationStateCustomKey"
      ],
      "title": "Configuration states"
    },
    {
      "anchor": "Content-configurations",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct",
        "doc://com.apple.uikit/documentation/UIKit/UIListContentView",
        "doc://com.apple.uikit/documentation/UIKit/UIContentConfiguration-9eib5",
        "doc://com.apple.uikit/documentation/UIKit/UIContentView-5fh3z"
      ],
      "title": "Content configurations"
    },
    {
      "anchor": "Unavailable-content-configurations",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfigurationState-swift.struct"
      ],
      "title": "Unavailable content configurations"
    },
    {
      "anchor": "Background-configurations",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-swift.struct"
      ],
      "title": "Background configurations"
    },
    {
      "anchor": "Color-transformers",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIConfigurationColorTransformer-swift.struct"
      ],
      "title": "Color transformers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Configuration-states",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-c.class",
                "doc://com.apple.uikit/documentation/UIKit/UICellConfigurationState-c.class",
                "doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-1smq1",
                "doc://com.apple.uikit/documentation/UIKit/UIConfigurationStateCustomKey"
              ],
              "title": "Configuration states"
            },
            {
              "anchor": "Content-configurations",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-c.class",
                "doc://com.apple.uikit/documentation/UIKit/UIListContentView",
                "doc://com.apple.uikit/documentation/UIKit/UIContentConfiguration-2raci",
                "doc://com.apple.uikit/documentation/UIKit/UIContentView-3zu2k"
              ],
              "title": "Content configurations"
            },
            {
              "anchor": "Unavailable-content-configurations",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class",
                "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfigurationState-c.class",
                "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableButtonProperties",
                "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableImageProperties",
                "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableTextProperties",
                "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableAlignment"
              ],
              "title": "Unavailable content configurations"
            },
            {
              "anchor": "Background-configurations",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIBackgroundConfiguration-c.class"
              ],
              "title": "Background configurations"
            },
            {
              "anchor": "Color-transformers",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIConfigurationColorTransformer-c.typealias"
              ],
              "title": "Color transformers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Appearance-and-content",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/automatic-trait-tracking"
              ],
              "title": "Appearance and content"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCell/title",
          "value": "UICollectionViewCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIConfigurationStateCustomKey/title",
          "value": "UIConfigurationStateCustomKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIConfigurationStateCustomKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIConfigurationStateCustomKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIConfigurationStateCustomKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIConfigurationStateCustomKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIListContentView/title",
          "value": "UIListContentView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIListContentView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIListContentView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIListContentView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIListContentView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/configurations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/configurations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
