{
  "abstract": [
    {
      "text": "Access the content-hugging elements structure’s implementations of protocol methods.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/views-and-controls",
        "doc://com.apple.uikit/documentation/UIKit/collection-views",
        "doc://com.apple.uikit/documentation/UIKit/layouts",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewCompositionalLayout",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutListConfiguration-swift.struct",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutListConfiguration-swift.struct/ContentHuggingElements-swift.struct"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/contenthuggingelements-protocol-implementations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "title": "Protocol implementations"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutListConfiguration-swift.struct": {
      "abstract": [
        {
          "text": "A configuration for creating a list layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionLayoutListConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutListConfiguration-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionLayoutListConfiguration"
        }
      ],
      "role": "symbol",
      "title": "UICollectionLayoutListConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionlayoutlistconfiguration-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutListConfiguration-swift.struct/ContentHuggingElements-swift.struct": {
      "abstract": [
        {
          "text": "Constants that determine which types of items in a collection view tightly hug their content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ContentHuggingElements"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutListConfiguration-swift.struct/ContentHuggingElements-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ContentHuggingElements"
        }
      ],
      "role": "symbol",
      "title": "UICollectionLayoutListConfiguration.ContentHuggingElements",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionlayoutlistconfiguration-swift.struct/contenthuggingelements-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewCompositionalLayout": {
      "abstract": [
        {
          "text": "A layout object that lets you combine items in highly adaptive and flexible visual arrangements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewCompositionalLayout"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewCompositionalLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewCompositionalLayout"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewCompositionalLayout",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewcompositionallayout"
    },
    "doc://com.apple.uikit/documentation/UIKit/collection-views": {
      "abstract": [
        {
          "text": "Display nested views using a configurable and highly customizable layout.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/collection-views",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Collection views",
      "type": "topic",
      "url": "/documentation/uikit/collection-views"
    },
    "doc://com.apple.uikit/documentation/UIKit/layouts": {
      "abstract": [
        {
          "text": "Arrange your collection view content in a highly configurable layout.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/layouts",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Layouts",
      "type": "topic",
      "url": "/documentation/uikit/layouts"
    },
    "doc://com.apple.uikit/documentation/UIKit/views-and-controls": {
      "abstract": [
        {
          "text": "Present your content onscreen and define the interactions allowed with that content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/views-and-controls",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Views and controls",
      "type": "topic",
      "url": "/documentation/uikit/views-and-controls"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCompositionalLayout/title",
          "value": "UICollectionViewCompositionalLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCompositionalLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewCompositionalLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCompositionalLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewCompositionalLayout"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/contenthuggingelements-protocol-implementations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
