{
  "abstract": [
    {
      "text": "Create, organize, and annotate symbol images using SF Symbols.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/images-and-pdf",
        "doc://com.apple.uikit/documentation/UIKit/UIImage"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/creating-custom-symbol-images-for-your-app"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Creating custom symbol images for your app"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "SF Symbols 4 offers a set of over 4,000 consistent, highly configurable symbol images that you can use in your app. You can apply stylistic traits typically associated with text, such as applying colors, text style, weight, and scale. Symbols contain additional traits that allow them to integrate seamlessly with surrounding text, and adapt to platform features like Dynamic Text and Dark Mode.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can create your own custom symbol images with the same capabilities that SF Symbols provides. To create your custom symbol:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Export an SVG file from the ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://developer.apple.com/sf-symbols/",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " app.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Edit the SVG file in a vector-drawing app.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Export the file from your drawing app as an SVG file.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Validate the SVG file using the SF Symbols app.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Import the custom symbol into the SF Symbols app and organize it into a group.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Add annotations, if necessary.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Export a template file for distribution.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "One way to begin creating your own symbol is by basing it on an existing symbol you find in the SF Symbols app. For example, the circle symbol can give you a great reference point to start working with.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "You can drop an existing symbol — from a previous template version — onto the app, and it automatically converts the symbol to template version 4 and adds it to the current collection.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Tip",
          "style": "tip",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "For design guidance, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/design/human-interface-guidelines/sf-symbols/overview/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Export-a-custom-symbol-template-file",
          "level": 3,
          "text": "Export a custom symbol template file",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Beginning with template version 3, the left-margin and right-margin guidelines have more explicit names that indicate the design variant they correspond to. For additional control over optical alignment, you can add margins to any variant in the template. The template is able to embed information about how a symbol should look in different rendering modes.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "After you locate a symbol image to use as a base for your design, choose File > Duplicate as Custom Symbol. The app creates a new category at the bottom of the categories sidebar where you find your custom symbols. To create an SVG file for your custom symbol, export a symbol template file for design customization by selecting the symbol and choosing File > Export Template.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When exporting a template, you choose between static or variable. Use a static setup if you’re targeting a particular weight and scale, or only plan to design one or two variants of your symbol. The setup contains 27 sets of paths and one set of explicit margins. A variable template setup contains three sets of paths and three sets of margins. If you plan on supporting all design variants, this gives you the minimum number of variants necessary for the system to generate the other 24.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Beginning with template version 3, SF Symbols introduces vector interpolation for symbol variants. By using three sources — ",
                  "type": "text"
                },
                {
                  "code": "Ultralight-S",
                  "type": "codeVoice"
                },
                {
                  "text": ", ",
                  "type": "text"
                },
                {
                  "code": "Regular-S",
                  "type": "codeVoice"
                },
                {
                  "text": ", and ",
                  "type": "text"
                },
                {
                  "code": "Black-S",
                  "type": "codeVoice"
                },
                {
                  "text": " — SF Symbol can dynamically generate the full range of weights and scales you don’t specify.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "After you export a template file, you use a vector-drawing app, such as Adobe Illustrator or Sketch, to begin modifying it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Manage-symbol-image-variants",
          "level": 3,
          "text": "Manage symbol image variants",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Symbols layer contains up to 27 sublayers, each representing a symbol image variant. Identifiers of symbol variants have the form ",
              "type": "text"
            },
            {
              "code": "<weight>-<{S, M, L}>",
              "type": "codeVoice"
            },
            {
              "text": ", where ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "weight",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " corresponds to a weight of the San Francisco system font and ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "S",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "M",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ", or ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "L",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " matches the small, medium, or large symbol scale.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "<g id=\"Symbols\">",
            "    <g id=\"Regular-M\" transform=\"matrix(1 0 0 1 2855.62 1556)\">   ",
            "        <!-- Path and style details for the Regular-M image variant. -->",
            "    </g>",
            "</g> "
          ],
          "syntax": "xml",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "SF Symbols treats a symbol as path-based, rather than stroke-based, if all the shapes within it have solid color fills, and don’t have strokes or other graphical features. Interpolation allows the system to generate variants between compatible paths. A template is interpolatable when:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "It contains the interpolation sources ",
                      "type": "text"
                    },
                    {
                      "code": "Ultralight-S",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", ",
                      "type": "text"
                    },
                    {
                      "code": "Regular-S",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", and ",
                      "type": "text"
                    },
                    {
                      "code": "Black-S",
                      "type": "codeVoice"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The three interpolation sources are path-based.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The three interpolation sources contain the same number of paths and the same number of control points.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "It’s not necessary for a template to contain all 27 variants. You can add as many variants to your template as you want, and if they’re present, the system uses them instead of interpolation. Similar to working with template versions before version 3, you can delete the variants you don’t need, so you can produce as many weights and scales as your app requires.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Organize-the-Guides-layer",
          "level": 3,
          "text": "Organize the Guides layer",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The system uses guides to align your custom symbol image with surrounding text. For example, it uses the provided baseline and cap height information for each of the three font scales to compute the symbol image’s baseline offset and cap height.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The Guides layer contains an uppercase letter ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "A",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " in outline form for each scale in the San Francisco system font as a reference glyph. Use the reference glyphs in the template as guides for how a symbol image looks next to text.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Beginning with template version 3, each image variant of a symbol can have its own margin guides. This allows the margins to vary slightly by weight and scale instead of using a fixed margin for all variants. The explicit margin guides have the form ",
              "type": "text"
            },
            {
              "code": "left-margin-<variant-specifier>",
              "type": "codeVoice"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "code": "right-margin-<variant-specifier>",
              "type": "codeVoice"
            },
            {
              "text": ". The following example represents the left and right guides of the ",
              "type": "text"
            },
            {
              "code": "Regular-S",
              "type": "codeVoice"
            },
            {
              "text": " symbol variant:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "<g id=\"Guides\">",
            "    <line id=\"left-margin-Regular-S\" style=\"fill:none;stroke:#00AEEF;stroke-width:0.5;opacity:1.0;\" x1=\"1403.33\" x2=\"1403.33\" y1=\"600.784\" y2=\"720.121\"/>",
            "    <line id=\"right-margin-Regular-S\" style=\"fill:none;stroke:#00AEEF;stroke-width:0.5;opacity:1.0;\" x1=\"1496.36\" x2=\"1496.36\" y1=\"600.784\" y2=\"720.121\"/>",
            "</g>"
          ],
          "syntax": "xml",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Symbols can contain negative margins to aid with horizontal alignment. If you don’t specify explicit margin guides, the system uses the next available margins it finds — interpolated margins (if the template is interpolatable), ",
              "type": "text"
            },
            {
              "code": "Regular-M",
              "type": "codeVoice"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "code": "Regular-S",
              "type": "codeVoice"
            },
            {
              "text": ", and, finally, any available margins the system can use.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Create-your-custom-symbol-image",
          "level": 3,
          "text": "Create your custom symbol image",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Start creating your custom symbol image by modifying the symbol in the template file you export. If you export a variable template, you need to modify all three symbol configurations so the system can generate the other variants.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When you finish your base variant, copy the existing drawing to the desired layer and adjust from there. This helps you keep the same number of paths across your design variants, which is a requirement if you want to produce a symbol with multicolor or hierarchical data.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use the following scale factors when designing your variants:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "header": "row",
          "rows": [
            [
              [
                {
                  "inlineContent": [],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "<weight>-S",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "<weight>-M",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "<weight>-L",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ],
            [
              [
                {
                  "inlineContent": [
                    {
                      "text": "Scale factor",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "0.783",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "1.0",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ],
              [
                {
                  "inlineContent": [
                    {
                      "text": "1.29",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            ]
          ],
          "type": "table"
        },
        {
          "inlineContent": [
            {
              "text": "The system automatically centers symbols vertically to San Francisco’s cap-height in all the different scales and weights. It’s important to position your custom symbol using the specified guides to make sure it appears correctly in text. When the symbol image appears in text, the system positions it vertically so that the bottom edge of the symbol image is the same distance, scaled by point size, that the symbol image is from the baseline guide in the template file.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "SF Symbols picks up all paths in a variant’s layer — including invisible paths — as part of the symbol outlines. This may lead to unexpected results when working with layers in the SF Symbols app, so don’t use hidden paths.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "When you create a symbol, you work on the monochrome representation. To ensure that your symbol supports rendering modes other than monochrome:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Convert any strokes to paths so the resulting shapes can take on colors or hierarchy groups. Paths make it easier to make minor optical adjustments when a stroke isn’t precise enough.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use standard flat color fills with no additional effects like drop shadows. If these are present they override any multicolor or hierarchical data you create for your symbol.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Check that all shapes in your design have a defined fill area with start and end points that connect.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Annotation data requires the same number of paths across designs. To retain your annotation data when modifying the paths of an annotated symbol, you can add, remove, and adjust points, but removing or reordering whole paths makes your designs go out of sync. In these cases, you need to reannotate the symbol to account for its new path structure.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "Image variants adapt automatically according to the user’s device language, including right-to-left writing systems. If you’re designing for left-to-right and right-to-left writing systems, consider the directionality and overall look of both localized variants. In some cases, some symbols don’t have the intended look when you mirror them. For design guidance, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/design/human-interface-guidelines/right-to-left/overview/introduction/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Preserve-annotations-and-meta-information-in-the-Notes-layer",
          "level": 3,
          "text": "Preserve annotations and meta information in the Notes layer",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Notes layer contains optional annotations and meta information about the template file. The ",
              "type": "text"
            },
            {
              "code": "template-version",
              "type": "codeVoice"
            },
            {
              "text": " layer contains a required version string that indicates the template format version, so you must not remove it; otherwise, SF Symbols can’t read the file. The ",
              "type": "text"
            },
            {
              "code": "artboard",
              "type": "codeVoice"
            },
            {
              "text": " layer makes sure design tools display the template with a convenient canvas size and legible symbols.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The Notes layer includes annotations on the custom symbol template file that can help you understand its contents. These annotations are optional, but it’s a good idea to keep them as-is for your reference.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "You don’t need to modify the contents of the Notes layer. Lock the artboard layer in your vector-drawing app before making any modifications to the file to avoid interacting and moving it.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Export-your-custom-symbol-and-preserve-all-names",
          "level": 3,
          "text": "Export your custom symbol and preserve all names",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you finish designing your symbol, export it from your vector-drawing app as an SVG file with maximum precision. By default, Illustrator generates low-precision SVGs, so export your SVG by changing the default decimal place value to 7 or greater. Confirm that the SVG file preserves all of the identifiers for your symbol variants and guides.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use any of the following methods to validate that your SVG file conforms to the requirements of SF Symbols:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Use the SF Symbols app and choose File > Validate Templates.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Add it to an asset catalog in your Xcode project. Xcode verifies the SVG file and displays error messages if it doesn’t conform to the requirements.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Inspect the SVG file to manually review the XML source code. Understanding the template layout helps you debug validation issues, so keep the original template you import into your vector-drawing app for a reference to compare against.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "When you have a valid template file, you’re ready to begin annotating it. Import your symbol back into the SF Symbols app by dropping it onto your custom symbol.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Annotate-your-custom-symbol",
          "level": 3,
          "text": "Annotate your custom symbol",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you want to control your symbol’s appearance in rendering modes other than monochrome, you can annotate your symbol. SF Symbols applies annotations to individual shape objects in the form of a CSS style, using a class name that has the form ",
              "type": "text"
            },
            {
              "code": "multicolor-<layer index>:<color name>",
              "type": "codeVoice"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "code": "hierarchical-<layer index>:<hierarchy level>",
              "type": "codeVoice"
            },
            {
              "text": ", and starts the layer index at zero. You set the color name to either a system color, a named color from the app’s asset catalog, or any constant that doesn’t dynamically resolve. A shape can have both multicolor and hierarchical annotations, and they don’t have to be in the same layer.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "<style>",
            "    .multicolor-0:systemBlueColor { fill:#007AFF; opacity:1.0 }",
            "    .multicolor-1:white { fill:#FFFFFF; opacity:1.0 }",
            "    .multicolor-2:tintColor { fill:#007AFF; opacity:1.0 }",
            "    .hierarchical-0:tertiary { fill:#8E8E8E }",
            "    .hierarchical-1:primary { fill:#212121 }",
            "</style>",
            "",
            "<g id=\"Symbols\">",
            "    <!-- A variant containing three shapes with multicolor and hierarchical annotations. -->",
            "    <g id=\"Regular-M\" transform=\"matrix(1 0 0 1 2853.78 1556)\">",
            "        <!-- The shape is in the first multicolor layer, whose fill color is systemBlueColor. It’s also in the first layer for hierarchical rendering, and the level is primary. -->",
            "        <path class=\"multicolor-0:systemBlueColor hierarchical-1:primary\" d=\"...\">",
            "   ",
            "        <!-- Two additional shapes. --><path class=\"multicolor-1:white hierarchical-1:primary\" d=\"...\">",
            "        <path class=\"multicolor-2:tintColor hierarchical-0:tertiary\" d=\"...\">",
            "     </g>",
            "</g>"
          ],
          "syntax": "xml",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "To annotate, you use the individual paths that make up your symbol as your building blocks. From there, you create a set of layers for each rendering mode. SF Symbols assigns a color to layers in multicolor mode, and assigns a hierarchy group to layers in hierarchical mode. Layers have an explicit Z-order where the layers on top block the layers below it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In SF Symbols, select your symbol and enter the gallery view by choosing View > As Gallery. Open the color inspector by choosing View > Inspectors > Show Color Sidebar, and then select the rendering mode to start annotating. The center preview lets you interact with all the paths and assign them to layers. You can use a path in any number of layers. In hierarchical mode, you assign groups from primary to tertiary, and the system uses the same data in hierarchical and palette rendering mode.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Use system-provided colors wherever possible because they adapt to changes in the system’s appearance — light, dark, and high-contrast modes — and in different vibrancy contexts.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Tip",
          "style": "tip",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "A common problem with overlapping shapes is that you can see through where paths overlap. In the color inspector, each layer has a toggle to the right of it. If it’s in a disabled state, the transparent layers blend with the layers below. If it’s active, transparent layers clear what’s behind them and render as if the other layers don’t exist.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When you’re done annotating your symbol, you export the symbol for distribution.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Annotate-a-variable-symbol",
          "level": 3,
          "text": "Annotate a variable symbol",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "System and custom symbols can dynamically apply colors by using a percentage value to convey the strength or progress over time. For example, a wireless signal strength symbol can reflect full signal strength at 100% or no signal at 0%. In SF Symbols, select your symbol and open the color inspector. Each layer allows you to activate variable color for it. The vector file contains the thresholds for your symbol.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "<style>",
            "    <!-- A symbol that contains three variable color layers --> ",
            "    .monochrome-0 {fill:#000000}",
            "    .monochrome-1 {fill:#000000}",
            "    .monochrome-2 {fill:#000000;-sfsymbols-variable-threshold:0.0}",
            "    .monochrome-3 {fill:#000000;-sfsymbols-variable-threshold:0.34}",
            "    .monochrome-4 {fill:#000000;-sfsymbols-variable-threshold:0.68}",
            "</style>"
          ],
          "syntax": "xml",
          "type": "codeListing"
        },
        {
          "anchor": "Distribute-your-custom-symbol",
          "level": 3,
          "text": "Distribute your custom symbol",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "There are two options to consider when distributing a symbol. Choose File > Export Symbol to begin. At the bottom left of the screen, version 4 appears by default.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Template version 2 and later removes annotation data and explicit margins. Use this version if you plan to deploy to an older operating system, such as iOS 14. It only contains monochrome, so make sure your symbol makes sense in that mode.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Template version 3 and later embeds all of your multicolor and hierarchical data annotations, as well as any custom margins. It isn’t backward-compatible, so use this version when you’re supporting iOS 15 or later.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Template version 4 embeds your variable color annotations, so use this version when you’re supporting iOS 16 or later.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "None of the versions is a source artifact for editing. Current design tools may not be compatible with the embedded annotation data. If you need to make edits or share it with a colleague, import it back into the SF Symbols app.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "If your minimum deployment target is iOS 15 or later, you only need the version 3 template. If your minimum deployment target is iOS 14, you need to export a version 2, 3, and 4 template, and use the appropriate asset depending on a version check. Use the latest template when sharing with a colleague because they can import it into their SF Symbols app to continue editing and annotating.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following code example shows the latest template version file — preserving identifiers, but omitting pathing details — and includes additional notes for each area:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?>",
            "<!--Generator: Apple Native CoreSVG 168-->",
            "<!DOCTYPE svg",
            "  PUBLIC \"-//W3C//DTD SVG 1.1//EN\"",
            "         \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\">",
            "<svg version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"3300\" height=\"2200\">",
            "",
            "<style>",
            "<!-- ",
            "Class names have the form <rendering mode style>-<layer index>:<color name>. Rendering mode is either hierarchical or multicolor, layer index is an integer between [0...N], and color name is either a system color, a named color from your app's asset catalog, or a constant (in which case it doesn't dynamically resolve).",
            "",
            "If the color name isn't a system color and isn't in the asset catalog, a style can have a fill attribute. You can use an opacity attribute, and a custom attribute `-sfsymbols-clear-behind:true`, which, when present, occludes other shapes in the symbol that you annotate with that style, and blends with anything behind the symbol. The system may ignore other attributes you add.",
            "",
            "Version 4 of the symbol template supports variable color thresholds by using `-sfsymbols-variable-threshold`.",
            "-->",
            "  .multicolor-0:systemBlueColor {fill:#007AFF;-sfsymbols-variable-threshold:0.0}",
            "  .multicolor-1:tertiaryLabelColor {fill:#BDBDBD;-sfsymbols-clear-behind:true}",
            "  .multicolor-2:white {fill:#FFFFFF;opacity:0.4}",
            "  .hierarchical-0:tertiary {fill:#8E8E8E}",
            "  .hierarchical-1:primary {fill:#212121;-sfsymbols-clear-behind:true}",
            "</style>",
            "",
            "<g id=\"Notes\">",
            "<!-- ",
            "The symbol template supports rendering mode annotations and path interpolation.",
            "-->",
            "  <text id=\"template-version\">Template v.3.0</text>",
            "</g>",
            "",
            "<g id=\"Guides\">",
            "  <line id=\"Baseline-S\" x1=\"...\" x2=\"...\" y1=\"...\" y2=\"...\"/>",
            "  <line id=\"Capline-S\" x1=\"...\" x2=\"...\" y1=\"...\" y2=\"...\"/>",
            "  <line id=\"Baseline-M\" x1=\"...\" x2=\"...\" y1=\"1126\" y2=\"...\"/>",
            "  <line id=\"Capline-M\" x1=\"...\" x2=\"...\" y1=\"1055.54\" y2=\"...\"/>",
            "  <line id=\"Baseline-L\" x1=\"...\" x2=\"...\" y1=\"1556\" y2=\"...\"/>",
            "  <line id=\"Capline-L\" x1=\"...\" x2=\"...\" y1=\"1485.54\" y2=\"...\"/>",
            "",
            "  <!-- ",
            "  The symbol template supports explicit margins for each variant.",
            "  -->",
            "  <line id=\"left-margin-Ultralight-S\" x1=\"...\" x2=\"...\" y1=\"...\" y2=\"...\"/>",
            "  <line id=\"right-margin-Ultralight-S\" x1=\"...\" x2=\"...\" y1=\"...\" y2=\"...\"/>",
            "  <line id=\"left-margin-Regular-S\" x1=\"...\" x2=\"...\" y1=\"...\" y2=\"...\"/>",
            "  <line id=\"right-margin-Regular-S\" x1=\"...\" x2=\"...\" y1=\"...\" y2=\"...\"/>",
            "  <line id=\"left-margin-Black-S\" x1=\"...\" x2=\"...\" y1=\"...\" y2=\"...\"/>",
            "  <line id=\"right-margin-Black-S\" x1=\"...\" x2=\"...\" y1=\"...\" y2=\"...\"/>",
            "</g>",
            "",
            "<g id=\"Symbols\">",
            "<!-- ",
            "The symbol template generates variants from the following source variants: Black-S, Regular-S, and Ultralight-S. When you create other variants, the system uses them instead of interpolation for that configuration.",
            "-->",
            "  <g id=\"Black-S\">",
            "  <!-- ",
            "  The system concatenates together all shapes for each rendering mode layer. A shape may be present in many layers. Shapes you nest within other shapes, and have opposite path windings, knock holes through their containing shapes.  ",
            "  -->",
            "    <path class=\"multicolor-0:systemBlueColor hierarchical-0:tertiary\" d=\"...\"/>",
            "    <path class=\"multicolor-1:tertiaryLabelColor hierarchical-1:primary\" d=\"...\"/>",
            "    <path class=\"multicolor-0:systemBlueColor multicolor-1:tertiaryLabelColor hierarchical-1:primary\" d=\"...\"/>",
            "    <path class=\"multicolor-2:white hierarchical-1:primary\" d=\"...\"/>",
            "  </g>",
            "",
            "  <g id=\"Regular-S\">",
            "    <path class=\"multicolor-0:systemBlueColor hierarchical-0:tertiary\" d=\"...\"/>",
            "    <path class=\"multicolor-1:tertiaryLabelColor hierarchical-1:primary\" d=\"...\"/>",
            "    <path class=\"multicolor-0:systemBlueColor multicolor-1:tertiaryLabelColor hierarchical-1:primary\" d=\"...\"/>",
            "    <path class=\"multicolor-2:white hierarchical-1:primary\" d=\"...\"/>",
            "  </g>",
            "  ",
            "  <g id=\"Ultralight-S\">",
            "    <path class=\"multicolor-0:systemBlueColor hierarchical-0:tertiary\" d=\"...\"/>",
            "    <path class=\"multicolor-1:tertiaryLabelColor hierarchical-1:primary\" d=\"...\"/>",
            "    <path class=\"multicolor-0:systemBlueColor multicolor-1:tertiaryLabelColor hierarchical-1:primary\" d=\"...\"/>",
            "    <path class=\"multicolor-2:white hierarchical-1:primary\" d=\"...\"/>",
            "  </g>",
            "</g>",
            "</svg>"
          ],
          "syntax": "xml",
          "type": "codeListing"
        },
        {
          "anchor": "Use-your-custom-symbol-images",
          "level": 3,
          "text": "Use your custom symbol images",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Open your app’s Xcode project and select its asset catalog. In Xcode’s menu bar, select Editor > Add New Asset > Symbol Image Set, and drag your exported SVG file into the Symbol SVG section of the Symbol pane. Xcode validates the SVG file, and displays error messages if the file doesn’t fulfill the requirements. To use the symbol image in your app, follow ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/configuring-and-displaying-symbol-images-in-your-ui",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage": {
      "abstract": [
        {
          "text": "An object that manages image data in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIImage"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImage"
        }
      ],
      "role": "symbol",
      "title": "UIImage",
      "type": "topic",
      "url": "/documentation/uikit/uiimage"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/imageNamed:inBundle:variableValue:withConfiguration:": {
      "abstract": [
        {
          "text": "Creates an image by using the name, configuration, and variable value you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "imageNamed:inBundle:variableValue:withConfiguration:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/imageNamed:inBundle:variableValue:withConfiguration:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageNamed:inBundle:variableValue:withConfiguration:"
        }
      ],
      "role": "symbol",
      "title": "imageNamed:inBundle:variableValue:withConfiguration:",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/imagenamed:inbundle:variablevalue:withconfiguration:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/init(imageLiteralResourceName:)": {
      "abstract": [
        {
          "text": "Returns the image object for the specified resource.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "imageLiteralResourceName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/init(imageLiteralResourceName:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(imageLiteralResourceName:)",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/init(imageliteralresourcename:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/init(named:)": {
      "abstract": [
        {
          "text": "Creates an image object from the specified named asset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "named"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/init(named:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageNamed:"
        }
      ],
      "role": "symbol",
      "title": "init(named:)",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/init(named:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/init(named:in:compatibleWith:)": {
      "abstract": [
        {
          "text": "Creates an image object using the named image asset that’s compatible with the specified trait collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "named"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBundle",
          "text": "Bundle"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "compatibleWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITraitCollection",
          "text": "UITraitCollection"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/init(named:in:compatibleWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageNamed:inBundle:compatibleWithTraitCollection:"
        }
      ],
      "role": "symbol",
      "title": "init(named:in:compatibleWith:)",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/init(named:in:compatiblewith:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/init(named:in:variableValue:configuration:)": {
      "abstract": [
        {
          "text": "Creates an image by using the name, configuration, and variable value you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "named"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBundle",
          "text": "Bundle"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "variableValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "configuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImageConfiguration",
          "text": "Configuration"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/init(named:in:variableValue:configuration:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(named:in:variableValue:configuration:)",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/init(named:in:variablevalue:configuration:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/init(named:in:with:)": {
      "abstract": [
        {
          "text": "Creates an image by using the named image asset that’s compatible with the configuration you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "named"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSBundle",
          "text": "Bundle"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImageConfiguration",
          "text": "Configuration"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/init(named:in:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageNamed:inBundle:withConfiguration:"
        }
      ],
      "role": "symbol",
      "title": "init(named:in:with:)",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/init(named:in:with:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/init(resource:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "resource"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:21DeveloperToolsSupport13ImageResourceV",
          "text": "ImageResource"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/init(resource:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(resource:)",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/init(resource:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/init(systemName:)": {
      "abstract": [
        {
          "text": "Creates an image object that contains a system symbol image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "systemName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/init(systemName:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "systemImageNamed:"
        }
      ],
      "role": "symbol",
      "title": "init(systemName:)",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/init(systemname:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/init(systemName:compatibleWith:)": {
      "abstract": [
        {
          "text": "Creates an image object that contains a system symbol image appropriate for the specified traits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "systemName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "compatibleWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITraitCollection",
          "text": "UITraitCollection"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/init(systemName:compatibleWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "systemImageNamed:compatibleWithTraitCollection:"
        }
      ],
      "role": "symbol",
      "title": "init(systemName:compatibleWith:)",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/init(systemname:compatiblewith:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/init(systemName:variableValue:configuration:)": {
      "abstract": [
        {
          "text": "Creates an image object that contains a system symbol image with the configuration and variable value you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "systemName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "variableValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "configuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImageConfiguration",
          "text": "Configuration"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/init(systemName:variableValue:configuration:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(systemName:variableValue:configuration:)",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/init(systemname:variablevalue:configuration:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/init(systemName:withConfiguration:)": {
      "abstract": [
        {
          "text": "Creates an image object that contains a system symbol image with the specified configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "systemName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withConfiguration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImageConfiguration",
          "text": "Configuration"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/init(systemName:withConfiguration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "systemImageNamed:withConfiguration:"
        }
      ],
      "role": "symbol",
      "title": "init(systemName:withConfiguration:)",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/init(systemname:withconfiguration:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/systemImageNamed:variableValue:withConfiguration:": {
      "abstract": [
        {
          "text": "Creates an image object that contains a system symbol image with the configuration and variable value you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "systemImageNamed:variableValue:withConfiguration:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/systemImageNamed:variableValue:withConfiguration:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "systemImageNamed:variableValue:withConfiguration:"
        }
      ],
      "role": "symbol",
      "title": "systemImageNamed:variableValue:withConfiguration:",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/systemimagenamed:variablevalue:withconfiguration:"
    },
    "doc://com.apple.uikit/documentation/UIKit/building-high-performance-lists-and-collection-views": {
      "abstract": [
        {
          "text": "Improve the performance of lists and collections in your app with prefetching and image preparation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/building-high-performance-lists-and-collection-views",
      "kind": "article",
      "role": "sampleCode",
      "title": "Building high-performance lists and collection views",
      "type": "topic",
      "url": "/documentation/uikit/building-high-performance-lists-and-collection-views"
    },
    "doc://com.apple.uikit/documentation/UIKit/configuring-and-displaying-symbol-images-in-your-ui": {
      "abstract": [
        {
          "text": "Create scalable images that integrate with your app’s text, and adjust the appearance of those images dynamically.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/configuring-and-displaying-symbol-images-in-your-ui",
      "kind": "article",
      "role": "article",
      "title": "Configuring and displaying symbol images in your UI",
      "type": "topic",
      "url": "/documentation/uikit/configuring-and-displaying-symbol-images-in-your-ui"
    },
    "doc://com.apple.uikit/documentation/UIKit/images-and-pdf": {
      "abstract": [
        {
          "text": "Create and manage images, including those that use bitmap and PDF formats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/images-and-pdf",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Images and PDF",
      "type": "topic",
      "url": "/documentation/uikit/images-and-pdf"
    },
    "doc://com.apple.uikit/documentation/UIKit/providing-images-for-different-appearances": {
      "abstract": [
        {
          "text": "Supply image resources appropriate for light and dark appearances and for high-contrast environments.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/providing-images-for-different-appearances",
      "kind": "article",
      "role": "article",
      "title": "Providing images for different appearances",
      "type": "topic",
      "url": "/documentation/uikit/providing-images-for-different-appearances"
    },
    "https://developer.apple.com/design/human-interface-guidelines/right-to-left/overview/introduction/": {
      "identifier": "https://developer.apple.com/design/human-interface-guidelines/right-to-left/overview/introduction/",
      "title": "Human Interface Guidelines > Right to left",
      "titleInlineContent": [
        {
          "text": "Human Interface Guidelines > Right to left",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/design/human-interface-guidelines/right-to-left/overview/introduction/"
    },
    "https://developer.apple.com/design/human-interface-guidelines/sf-symbols/overview/": {
      "identifier": "https://developer.apple.com/design/human-interface-guidelines/sf-symbols/overview/",
      "title": "Human Interface Guidelines > SF Symbols",
      "titleInlineContent": [
        {
          "text": "Human Interface Guidelines > SF Symbols",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/design/human-interface-guidelines/sf-symbols/overview/"
    },
    "https://developer.apple.com/sf-symbols/": {
      "identifier": "https://developer.apple.com/sf-symbols/",
      "title": "SF Symbols",
      "titleInlineContent": [
        {
          "text": "SF Symbols",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/sf-symbols/"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Loading-and-caching-images",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/providing-images-for-different-appearances",
        "doc://com.apple.uikit/documentation/UIKit/configuring-and-displaying-symbol-images-in-your-ui",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/init(named:in:compatibleWith:)",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/init(named:in:with:)",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/init(named:in:variableValue:configuration:)",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/init(named:)",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/init(imageLiteralResourceName:)",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/init(systemName:withConfiguration:)",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/init(systemName:variableValue:configuration:)",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/init(systemName:compatibleWith:)",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/init(systemName:)",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/init(resource:)",
        "doc://com.apple.uikit/documentation/UIKit/building-high-performance-lists-and-collection-views"
      ],
      "title": "Loading and caching images"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Loading-and-caching-images",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/providing-images-for-different-appearances",
                "doc://com.apple.uikit/documentation/UIKit/configuring-and-displaying-symbol-images-in-your-ui",
                "doc://com.apple.uikit/documentation/UIKit/UIImage/init(named:in:compatibleWith:)",
                "doc://com.apple.uikit/documentation/UIKit/UIImage/init(named:in:with:)",
                "doc://com.apple.uikit/documentation/UIKit/UIImage/imageNamed:inBundle:variableValue:withConfiguration:",
                "doc://com.apple.uikit/documentation/UIKit/UIImage/init(named:)",
                "doc://com.apple.uikit/documentation/UIKit/UIImage/init(systemName:withConfiguration:)",
                "doc://com.apple.uikit/documentation/UIKit/UIImage/systemImageNamed:variableValue:withConfiguration:",
                "doc://com.apple.uikit/documentation/UIKit/UIImage/init(systemName:compatibleWith:)",
                "doc://com.apple.uikit/documentation/UIKit/UIImage/init(systemName:)",
                "doc://com.apple.uikit/documentation/UIKit/building-high-performance-lists-and-collection-views"
              ],
              "title": "Loading and caching images"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1init(systemName:)/title",
          "value": "systemImageNamed:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1init(systemName:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "systemImageNamed:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1init(named:in:with:)/title",
          "value": "imageNamed:inBundle:withConfiguration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1init(named:in:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "imageNamed:inBundle:withConfiguration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1init(systemName:compatibleWith:)/title",
          "value": "systemImageNamed:compatibleWithTraitCollection:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1init(systemName:compatibleWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "systemImageNamed:compatibleWithTraitCollection:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1init(named:)/title",
          "value": "imageNamed:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1init(named:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "imageNamed:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1init(systemName:withConfiguration:)/title",
          "value": "systemImageNamed:withConfiguration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1init(systemName:withConfiguration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "systemImageNamed:withConfiguration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/title",
          "value": "UIImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1init(named:in:compatibleWith:)/title",
          "value": "imageNamed:inBundle:compatibleWithTraitCollection:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1init(named:in:compatibleWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "imageNamed:inBundle:compatibleWithTraitCollection:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/creating-custom-symbol-images-for-your-app"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/creating-custom-symbol-images-for-your-app"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
