{
  "abstract": [
    {
      "text": "Customize a view layout by changing the size of cells in the flow or implementing a mosaic style.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/views-and-controls",
        "doc://com.apple.uikit/documentation/UIKit/collection-views",
        "doc://com.apple.uikit/documentation/UIKit/layouts"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/customizing-collection-view-layouts"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "12.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "12.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Customizing collection view layouts"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To lay out UICollectionView cells in a simple grid, you can use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewFlowLayout",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " directly. For more flexibility, you can subclass ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to create advanced layouts.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This sample app demonstrates two custom layout subclasses:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "ColumnFlowLayout",
                      "type": "codeVoice"
                    },
                    {
                      "text": " — A ",
                      "type": "text"
                    },
                    {
                      "code": "UICollectionViewFlowLayout",
                      "type": "codeVoice"
                    },
                    {
                      "text": " subclass that arranges cells in a list format for narrow screens, or as a grid for wider screens. See “For a Simple Grid, Size Cells Dynamically,” below.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "MosaicLayout",
                      "type": "codeVoice"
                    },
                    {
                      "text": " — A ",
                      "type": "text"
                    },
                    {
                      "code": "UICollectionViewLayout",
                      "type": "codeVoice"
                    },
                    {
                      "text": " subclass that lays out cells in a mosaic-style, nonconforming grid. See “For a Complex Grid, Define Cell Sizes Explicitly,” below.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The app opens to the Friends view controller, which uses a column flow layout to display a list of people. Tapping any cell takes you to the Feed view controller, which uses a mosaic layout to display photos from the user’s photo library.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Tapping the cloud icon to the right of the navigation bar demonstrates batched animations for inserting, deleting, moving, and reloading items in the collection view. For more information, see “Perform Batch Updates,” below. Using pull-to-refresh on the collection view resets the data.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "For-a-simple-grid-size-cells-dynamically",
          "level": 3,
          "text": "For a simple grid, size cells dynamically",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "code": "ColumnFlowLayout",
              "type": "codeVoice"
            },
            {
              "text": " is a subclass of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewFlowLayout",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " that uses the size of the collection view to determine the width of its cells. If only one cell fits comfortably horizontally, the layout arranges the cells to occupy the entire width of the collection view. Otherwise, the layout displays multiple columns of cells with a fixed width.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In practice, on iPhone devices in portrait mode, ",
              "type": "text"
            },
            {
              "code": "ColumnFlowLayout",
              "type": "codeVoice"
            },
            {
              "text": " displays a single vertical column of cells. In landscape mode, or on an iPad, it displays a grid layout.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/prepare()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function to compute the available screen width of the device and set the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewFlowLayout/itemSize",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property accordingly.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "override func prepare() {",
            "    super.prepare()",
            "",
            "    guard let collectionView = collectionView else { return }",
            "    ",
            "    let availableWidth = collectionView.bounds.inset(by: collectionView.layoutMargins).width",
            "    let maxNumColumns = Int(availableWidth / minColumnWidth)",
            "    let cellWidth = (availableWidth / CGFloat(maxNumColumns)).rounded(.down)",
            "    ",
            "    self.itemSize = CGSize(width: cellWidth, height: cellHeight)",
            "    self.sectionInset = UIEdgeInsets(top: self.minimumInteritemSpacing, left: 0.0, bottom: 0.0, right: 0.0)",
            "    self.sectionInsetReference = .fromSafeArea",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "For-a-complex-grid-define-cell-sizes-explicitly",
          "level": 3,
          "text": "For a complex grid, define cell sizes explicitly",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If you need more customization than is possible with a subclass of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewFlowLayout",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", subclass ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instead.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "code": "MosaicLayout",
              "type": "codeVoice"
            },
            {
              "text": " is a ",
              "type": "text"
            },
            {
              "code": "UICollectionViewLayout",
              "type": "codeVoice"
            },
            {
              "text": " subclass that displays an arbitrary number of cells with differing sizes and aspect ratios. The ",
              "type": "text"
            },
            {
              "code": "FeedViewController",
              "type": "codeVoice"
            },
            {
              "text": " class uses a mosaic layout to display images from the user’s photo library. Cells are organized into rows in one of four styles, from a single cell to multiple cells in varying layouts.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "CellLayouts",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "inlineContent": [
                {
                  "text": "Calculate cell dimensions",
                  "type": "text"
                }
              ],
              "type": "strong"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/prepare()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method is called whenever a layout is invalidated. Override this method to calculate the position and size of every cell, as well as the total dimensions for the entire layout.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "override func prepare() {",
            "    super.prepare()",
            "    ",
            "    guard let collectionView = collectionView else { return }",
            "",
            "    // Reset cached information.",
            "    cachedAttributes.removeAll()",
            "    contentBounds = CGRect(origin: .zero, size: collectionView.bounds.size)",
            "    ",
            "    // For every item in the collection view:",
            "    //  - Prepare the attributes.",
            "    //  - Store attributes in the cachedAttributes array.",
            "    //  - Combine contentBounds with attributes.frame.",
            "    let count = collectionView.numberOfItems(inSection: 0)",
            "    ",
            "    var currentIndex = 0",
            "    var segment: MosaicSegmentStyle = .fullWidth",
            "    var lastFrame: CGRect = .zero",
            "    ",
            "    let cvWidth = collectionView.bounds.size.width",
            "    ",
            "    while currentIndex < count {",
            "        let segmentFrame = CGRect(x: 0, y: lastFrame.maxY + 1.0, width: cvWidth, height: 200.0)",
            "        ",
            "        var segmentRects = [CGRect]()",
            "        switch segment {",
            "        case .fullWidth:",
            "            segmentRects = [segmentFrame]",
            "            ",
            "        case .fiftyFifty:",
            "            let horizontalSlices = segmentFrame.dividedIntegral(fraction: 0.5, from: .minXEdge)",
            "            segmentRects = [horizontalSlices.first, horizontalSlices.second]",
            "            ",
            "        case .twoThirdsOneThird:",
            "            let horizontalSlices = segmentFrame.dividedIntegral(fraction: (2.0 / 3.0), from: .minXEdge)",
            "            let verticalSlices = horizontalSlices.second.dividedIntegral(fraction: 0.5, from: .minYEdge)",
            "            segmentRects = [horizontalSlices.first, verticalSlices.first, verticalSlices.second]",
            "            ",
            "        case .oneThirdTwoThirds:",
            "            let horizontalSlices = segmentFrame.dividedIntegral(fraction: (1.0 / 3.0), from: .minXEdge)",
            "            let verticalSlices = horizontalSlices.first.dividedIntegral(fraction: 0.5, from: .minYEdge)",
            "            segmentRects = [verticalSlices.first, verticalSlices.second, horizontalSlices.second]",
            "        }",
            "        ",
            "        // Create and cache layout attributes for calculated frames.",
            "        for rect in segmentRects {",
            "            let attributes = UICollectionViewLayoutAttributes(forCellWith: IndexPath(item: currentIndex, section: 0))",
            "            attributes.frame = rect",
            "            ",
            "            cachedAttributes.append(attributes)",
            "            contentBounds = contentBounds.union(lastFrame)",
            "            ",
            "            currentIndex += 1",
            "            lastFrame = rect",
            "        }",
            "",
            "        // Determine the next segment style.",
            "        switch count - currentIndex {",
            "        case 1:",
            "            segment = .fullWidth",
            "        case 2:",
            "            segment = .fiftyFifty",
            "        default:",
            "            switch segment {",
            "            case .fullWidth:",
            "                segment = .fiftyFifty",
            "            case .fiftyFifty:",
            "                segment = .twoThirdsOneThird",
            "            case .twoThirdsOneThird:",
            "                segment = .oneThirdTwoThirds",
            "            case .oneThirdTwoThirds:",
            "                segment = .fiftyFifty",
            "            }",
            "        }",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "inlineContent": [
                {
                  "text": "Provide the content size",
                  "type": "text"
                }
              ],
              "type": "strong"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Override the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/collectionViewContentSize",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property, providing a size for the collection view.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "override var collectionViewContentSize: CGSize {",
            "    return contentBounds.size",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "inlineContent": [
                {
                  "text": "Define the layout attributes",
                  "type": "text"
                }
              ],
              "type": "strong"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Override ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/layoutAttributesForElements(in:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", defining the layout attributes for a geometric region. The collection view calls this function periodically to display items, which is known as ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "querying by geometric region",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "override func layoutAttributesForElements(in rect: CGRect) -> [UICollectionViewLayoutAttributes]? {",
            "    var attributesArray = [UICollectionViewLayoutAttributes]()",
            "    ",
            "    // Find any cell that sits within the query rect.",
            "    guard let lastIndex = cachedAttributes.indices.last,",
            "          let firstMatchIndex = binSearch(rect, start: 0, end: lastIndex) else { return attributesArray }",
            "    ",
            "    // Starting from the match, loop up and down through the array until all the attributes",
            "    // have been added within the query rect.",
            "    for attributes in cachedAttributes[..<firstMatchIndex].reversed() {",
            "        guard attributes.frame.maxY >= rect.minY else { break }",
            "        attributesArray.append(attributes)",
            "    }",
            "    ",
            "    for attributes in cachedAttributes[firstMatchIndex...] {",
            "        guard attributes.frame.minY <= rect.maxY else { break }",
            "        attributesArray.append(attributes)",
            "    }",
            "    ",
            "    return attributesArray",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Also provide the layout attributes for a specific item by implementing ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/layoutAttributesForItem(at:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". The collection view calls this function periodically to display one particular item, which is known as ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "querying by index path",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "override func layoutAttributesForItem(at indexPath: IndexPath) -> UICollectionViewLayoutAttributes? {",
            "    return cachedAttributes[indexPath.item]",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Because these functions are called often, they can affect the performance of your app. To make them as efficient as possible, follow the example code as closely as you can.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "inlineContent": [
                {
                  "text": "Handle bounds changes",
                  "type": "text"
                }
              ],
              "type": "strong"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppKit/NSCollectionViewLayout/shouldInvalidateLayout(forBoundsChange:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function is called for every bounds change from the collection view, or whenever its size or origin changes. This function is also called frequently during scrolling. The default implementation returns ",
              "type": "text"
            },
            {
              "code": "false",
              "type": "codeVoice"
            },
            {
              "text": ", or, if the size and origin change, it returns ",
              "type": "text"
            },
            {
              "code": "true",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "override func shouldInvalidateLayout(forBoundsChange newBounds: CGRect) -> Bool {",
            "    guard let collectionView = collectionView else { return false }",
            "    return !newBounds.size.equalTo(collectionView.bounds.size)",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "For optimum performance, this sample performs a binary search inside ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/layoutAttributesForElements(in:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instead of a linear search of the attributes it needs for each element in a given bounds area.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Perform-batch-updates",
          "level": 3,
          "text": "Perform batch updates",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Tapping the top-right button in the navigation bar triggers the collection view to perform a ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "batch update",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " of multiple animated operations (insert, delete, move, and reload) of its collection view cells all at the same time.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Within a call to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionView/performBatchUpdates(_:completion:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", the system simultaneously animates all insert, delete, move, and reload operations. In this sample, the app batches updates by processing an array of ",
              "type": "text"
            },
            {
              "code": "PersonUpdate",
              "type": "codeVoice"
            },
            {
              "text": " objects, each of which encapsulates one update:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "insert",
                      "type": "codeVoice"
                    },
                    {
                      "text": " with a ",
                      "type": "text"
                    },
                    {
                      "code": "Person",
                      "type": "codeVoice"
                    },
                    {
                      "text": " object and insertion index.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "delete",
                      "type": "codeVoice"
                    },
                    {
                      "text": " with an index.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "move",
                      "type": "codeVoice"
                    },
                    {
                      "text": " from one index to another.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "reload",
                      "type": "codeVoice"
                    },
                    {
                      "text": " with an index.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "First, the ",
              "type": "text"
            },
            {
              "code": "reload",
              "type": "codeVoice"
            },
            {
              "text": " operations are performed without animation because no cell movement is involved:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Perform any cell reloads without animation because there is no movement.",
            "UIView.performWithoutAnimation {",
            "    collectionView.performBatchUpdates({",
            "        for update in remoteUpdates {",
            "            if case let .reload(index) = update {",
            "                people[index].isUpdated = true",
            "                collectionView.reloadItems(at: [IndexPath(item: index, section: 0)])",
            "            }",
            "        }",
            "    })",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Next, the remaining operations are animated:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Animate all other update types together.",
            "collectionView.performBatchUpdates({",
            "    var deletes = [Int]()",
            "    var inserts = [(person:Person, index:Int)]()",
            "",
            "    for update in remoteUpdates {",
            "        switch update {",
            "        case let .delete(index):",
            "            collectionView.deleteItems(at: [IndexPath(item: index, section: 0)])",
            "            deletes.append(index)",
            "            ",
            "        case let .insert(person, index):",
            "            collectionView.insertItems(at: [IndexPath(item: index, section: 0)])",
            "            inserts.append((person, index))",
            "            ",
            "        case let .move(fromIndex, toIndex):",
            "            // Updates that move a person are split into an addition and a deletion.",
            "            collectionView.moveItem(at: IndexPath(item: fromIndex, section: 0),",
            "                                    to: IndexPath(item: toIndex, section: 0))",
            "            deletes.append(fromIndex)",
            "            inserts.append((people[fromIndex], toIndex))",
            "            ",
            "        default: break",
            "        }",
            "    }",
            "    ",
            "    // Apply deletions in descending order.",
            "    for deletedIndex in deletes.sorted().reversed() {",
            "        people.remove(at: deletedIndex)",
            "    }",
            "    ",
            "    // Apply insertions in ascending order.",
            "    let sortedInserts = inserts.sorted(by: { (personA, personB) -> Bool in",
            "        return personA.index <= personB.index",
            "    })",
            "    for insertion in sortedInserts {",
            "        people.insert(insertion.person, at: insertion.index)",
            "    }",
            "    ",
            "    // The update button is enabled only if the list still has people in it.",
            "    navigationItem.rightBarButtonItem?.isEnabled = !people.isEmpty",
            "})"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "CellLayouts": {
      "alt": "Images showing a row of four rectangles, each representing a mosaic style. On the left, a single cell. Second from left, two equal-size cells. Third from left, one cell occupying two-thirds of the area, and two stacked cells to the left of the larger cell. Last, one cell occupying two-thirds of the area, and two stacked cells to the right of the larger cell.",
      "identifier": "CellLayouts",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/cba49a90929a4052e9ce4b671ad41ef7/CellLayouts.png"
        }
      ]
    },
    "doc://com.apple.documentation/documentation/AppKit/NSCollectionViewLayout/shouldInvalidateLayout(forBoundsChange:)": {
      "abstract": [
        {
          "text": "Returns a Boolean indicating whether a bounds change triggers a layout update.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shouldInvalidateLayout"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forBoundsChange"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "newBounds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSCollectionViewLayout/shouldInvalidateLayout(forBoundsChange:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "shouldInvalidateLayout(forBoundsChange:)",
      "type": "topic",
      "url": "/documentation/AppKit/NSCollectionViewLayout/shouldInvalidateLayout(forBoundsChange:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionView/performBatchUpdates(_:completion:)": {
      "abstract": [
        {
          "text": "Animates multiple insert, delete, reload, and move operations as a group.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "performBatchUpdates"
        },
        {
          "kind": "text",
          "text": "((() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionView/performBatchUpdates(_:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "performBatchUpdates:completion:"
        }
      ],
      "role": "symbol",
      "title": "performBatchUpdates(_:completion:)",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionview/performbatchupdates(_:completion:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewFlowLayout": {
      "abstract": [
        {
          "text": "A layout object that organizes items into a grid with optional header and footer views for each section.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewFlowLayout"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewFlowLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewFlowLayout"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewFlowLayout",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewflowlayout"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewFlowLayout/itemSize": {
      "abstract": [
        {
          "text": "The default size to use for cells.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "itemSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewFlowLayout/itemSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "itemSize"
        }
      ],
      "role": "symbol",
      "title": "itemSize",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewflowlayout/itemsize"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewFlowLayoutInvalidationContext": {
      "abstract": [
        {
          "text": "A set of properties for determining whether to recompute the size of items or their position in the layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewFlowLayoutInvalidationContext"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewFlowLayoutInvalidationContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewFlowLayoutInvalidationContext"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewFlowLayoutInvalidationContext",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewflowlayoutinvalidationcontext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout": {
      "abstract": [
        {
          "text": "An abstract base class for generating layout information for a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewLayout"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewLayout"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewLayout",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewlayout"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/collectionViewContentSize": {
      "abstract": [
        {
          "text": "The width and height of the collection view’s contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "collectionViewContentSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/collectionViewContentSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "collectionViewContentSize"
        }
      ],
      "role": "symbol",
      "title": "collectionViewContentSize",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewlayout/collectionviewcontentsize"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/layoutAttributesForElements(in:)": {
      "abstract": [
        {
          "text": "Retrieves the layout attributes for all of the cells and views in the specified rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layoutAttributesForElements"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICollectionViewLayoutAttributes",
          "text": "UICollectionViewLayoutAttributes"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/layoutAttributesForElements(in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layoutAttributesForElementsInRect:"
        }
      ],
      "role": "symbol",
      "title": "layoutAttributesForElements(in:)",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewlayout/layoutattributesforelements(in:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/layoutAttributesForItem(at:)": {
      "abstract": [
        {
          "text": "Retrieves layout information for an item at the specified index path with a corresponding cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layoutAttributesForItem"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation9IndexPathV",
          "text": "IndexPath"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICollectionViewLayoutAttributes",
          "text": "UICollectionViewLayoutAttributes"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/layoutAttributesForItem(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layoutAttributesForItemAtIndexPath:"
        }
      ],
      "role": "symbol",
      "title": "layoutAttributesForItem(at:)",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewlayout/layoutattributesforitem(at:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/prepare()": {
      "abstract": [
        {
          "text": "Tells the layout object to update the current layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prepare"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout/prepare()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "prepareLayout"
        }
      ],
      "role": "symbol",
      "title": "prepare()",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewlayout/prepare()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayoutAttributes": {
      "abstract": [
        {
          "text": "A layout object that manages the layout-related attributes for a given item in a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewLayoutAttributes"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayoutAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewLayoutAttributes"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewLayoutAttributes",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewlayoutattributes"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewTransitionLayout": {
      "abstract": [
        {
          "text": "A special type of layout object that lets you implement behaviors when changing from one layout to another in your collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewTransitionLayout"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewTransitionLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewTransitionLayout"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewTransitionLayout",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewtransitionlayout"
    },
    "doc://com.apple.uikit/documentation/UIKit/collection-views": {
      "abstract": [
        {
          "text": "Display nested views using a configurable and highly customizable layout.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/collection-views",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Collection views",
      "type": "topic",
      "url": "/documentation/uikit/collection-views"
    },
    "doc://com.apple.uikit/documentation/UIKit/layouts": {
      "abstract": [
        {
          "text": "Arrange your collection view content in a highly configurable layout.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/layouts",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Layouts",
      "type": "topic",
      "url": "/documentation/uikit/layouts"
    },
    "doc://com.apple.uikit/documentation/UIKit/views-and-controls": {
      "abstract": [
        {
          "text": "Present your content onscreen and define the interactions allowed with that content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/views-and-controls",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Views and controls",
      "type": "topic",
      "url": "/documentation/uikit/views-and-controls"
    },
    "ebe75d1feb4d/CustomizingCollectionViewLayouts.zip": {
      "checksum": "ebe75d1feb4d7249d65370a55ca9754770b7d25071121cf2f730976858ff823986840b6b3d418fd97b7bb171d09404f88c8315c1aaaf0ec00d5d8e9d4826bd40",
      "identifier": "ebe75d1feb4d/CustomizingCollectionViewLayouts.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/ebe75d1feb4d/CustomizingCollectionViewLayouts.zip"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "ebe75d1feb4d/CustomizingCollectionViewLayouts.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Manual-layouts",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewFlowLayout",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewTransitionLayout",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayoutAttributes",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewFlowLayoutInvalidationContext"
      ],
      "title": "Manual layouts"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Manual-layouts",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewFlowLayout",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewTransitionLayout",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayoutAttributes",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewFlowLayoutInvalidationContext"
              ],
              "title": "Manual layouts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayoutAttributes/title",
          "value": "UICollectionViewLayoutAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayoutAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewLayoutAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayoutAttributes/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewLayoutAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewFlowLayout~1itemSize/title",
          "value": "itemSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewFlowLayout~1itemSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "itemSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayout/title",
          "value": "UICollectionViewLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayout~1layoutAttributesForElements(in:)/title",
          "value": "layoutAttributesForElementsInRect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayout~1layoutAttributesForElements(in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "layoutAttributesForElementsInRect:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSCollectionViewLayout~1shouldInvalidateLayout(forBoundsChange:)/title",
          "value": "shouldInvalidateLayoutForBoundsChange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSCollectionViewLayout~1shouldInvalidateLayout(forBoundsChange:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "shouldInvalidateLayoutForBoundsChange:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSRect",
              "text": "NSRect"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "newBounds"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayout~1layoutAttributesForItem(at:)/title",
          "value": "layoutAttributesForItemAtIndexPath:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayout~1layoutAttributesForItem(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "layoutAttributesForItemAtIndexPath:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayout~1collectionViewContentSize/title",
          "value": "collectionViewContentSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayout~1collectionViewContentSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "collectionViewContentSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewFlowLayout/title",
          "value": "UICollectionViewFlowLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewFlowLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewFlowLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewFlowLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewFlowLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewFlowLayoutInvalidationContext/title",
          "value": "UICollectionViewFlowLayoutInvalidationContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewFlowLayoutInvalidationContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewFlowLayoutInvalidationContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewFlowLayoutInvalidationContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewFlowLayoutInvalidationContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewTransitionLayout/title",
          "value": "UICollectionViewTransitionLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewTransitionLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewTransitionLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewTransitionLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewTransitionLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayout~1prepare()/title",
          "value": "prepareLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayout~1prepare()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "prepareLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1performBatchUpdates(_:completion:)/title",
          "value": "performBatchUpdates:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1performBatchUpdates(_:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "performBatchUpdates:completion:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/customizing-collection-view-layouts"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/customizing-collection-view-layouts"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
