{
  "abstract": [
    {
      "text": "Organize your app’s data and share that data on the pasteboard.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/documents-data-and-pasteboard"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Documents, data, and pasteboard"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDataSourceModelAssociation": {
      "abstract": [
        {
          "text": "A set of methods that defines an interface for providing persistent references to data objects in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDataSourceModelAssociation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDataSourceModelAssociation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDataSourceModelAssociation"
        }
      ],
      "role": "symbol",
      "title": "UIDataSourceModelAssociation",
      "type": "topic",
      "url": "/documentation/uikit/uidatasourcemodelassociation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocument": {
      "abstract": [
        {
          "text": "An abstract base class for managing discrete portions of your app’s data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDocument"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDocument"
        }
      ],
      "role": "symbol",
      "title": "UIDocument",
      "type": "topic",
      "url": "/documentation/uikit/uidocument"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController": {
      "abstract": [
        {
          "text": "A view controller that manages and presents a document stored locally or in the cloud.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDocumentViewController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDocumentViewController"
        }
      ],
      "role": "symbol",
      "title": "UIDocumentViewController",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentviewcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument": {
      "abstract": [
        {
          "text": "A managed document object that integrates with Core Data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIManagedDocument"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIManagedDocument"
        }
      ],
      "role": "symbol",
      "title": "UIManagedDocument",
      "type": "topic",
      "url": "/documentation/uikit/uimanageddocument"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteConfiguration": {
      "abstract": [
        {
          "text": "The interface that an object implements to declare its ability to accept specific data types for pasting and for drag-and-drop activities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPasteConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPasteConfiguration"
        }
      ],
      "role": "symbol",
      "title": "UIPasteConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uipasteconfiguration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteConfigurationSupporting": {
      "abstract": [
        {
          "text": "The interface that determines whether a responder object supports paste configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPasteConfigurationSupporting"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteConfigurationSupporting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPasteConfigurationSupporting"
        }
      ],
      "role": "symbol",
      "title": "UIPasteConfigurationSupporting",
      "type": "topic",
      "url": "/documentation/uikit/uipasteconfigurationsupporting"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteControl": {
      "abstract": [
        {
          "text": "A button that a person taps to place pasteboard contents in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPasteControl"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPasteControl"
        }
      ],
      "role": "symbol",
      "title": "UIPasteControl",
      "type": "topic",
      "url": "/documentation/uikit/uipastecontrol"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteControl/Configuration-swift.class": {
      "abstract": [
        {
          "text": "An object that determines a paste button’s color, corner style, icon, and text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Configuration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteControl/Configuration-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Configuration"
        }
      ],
      "role": "symbol",
      "title": "UIPasteControl.Configuration",
      "type": "topic",
      "url": "/documentation/uikit/uipastecontrol/configuration-swift.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteControl/DisplayMode": {
      "abstract": [
        {
          "text": "Options that determine whether a paste button composes an icon, textual label, or both.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DisplayMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteControl/DisplayMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DisplayMode"
        }
      ],
      "role": "symbol",
      "title": "UIPasteControl.DisplayMode",
      "type": "topic",
      "url": "/documentation/uikit/uipastecontrol/displaymode"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard": {
      "abstract": [
        {
          "text": "An object that helps a user share data from one place to another within your app, and from your app to other apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPasteboard"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPasteboard"
        }
      ],
      "role": "symbol",
      "title": "UIPasteboard",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard"
    },
    "doc://com.apple.uikit/documentation/UIKit/app-and-environment": {
      "abstract": [
        {
          "text": "Manage life-cycle events and your app’s UI scenes, and get information about traits and the environment in which your app runs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/app-and-environment",
      "kind": "article",
      "role": "collectionGroup",
      "title": "App and environment",
      "type": "topic",
      "url": "/documentation/uikit/app-and-environment"
    },
    "doc://com.apple.uikit/documentation/UIKit/app-extensions": {
      "abstract": [
        {
          "text": "Extend your app’s basic functionality to other parts of the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/app-extensions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "App extensions",
      "type": "topic",
      "url": "/documentation/uikit/app-extensions"
    },
    "doc://com.apple.uikit/documentation/UIKit/interprocess-communication": {
      "abstract": [
        {
          "text": "Display activity-based services to people.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/interprocess-communication",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Interprocess communication",
      "type": "topic",
      "url": "/documentation/uikit/interprocess-communication"
    },
    "doc://com.apple.uikit/documentation/UIKit/mac-catalyst": {
      "abstract": [
        {
          "text": "Create a version of your iPad app that users can run on a Mac device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/mac-catalyst",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Mac Catalyst",
      "type": "topic",
      "url": "/documentation/uikit/mac-catalyst"
    },
    "doc://com.apple.uikit/documentation/UIKit/resource-management": {
      "abstract": [
        {
          "text": "Manage the images, strings, storyboards, and nib files that you use to implement your app’s interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/resource-management",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Resource management",
      "type": "topic",
      "url": "/documentation/uikit/resource-management"
    },
    "doc://com.apple.uikit/documentation/UIKit/synchronizing-documents-in-the-icloud-environment": {
      "abstract": [
        {
          "text": "Manage documents across multiple devices to create a seamless editing and collaboration experience.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/synchronizing-documents-in-the-icloud-environment",
      "kind": "article",
      "role": "sampleCode",
      "title": "Synchronizing documents in the iCloud environment",
      "type": "topic",
      "url": "/documentation/uikit/synchronizing-documents-in-the-icloud-environment"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "App-structure",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/app-and-environment",
        "doc://com.apple.uikit/documentation/UIKit/resource-management",
        "doc://com.apple.uikit/documentation/UIKit/app-extensions",
        "doc://com.apple.uikit/documentation/UIKit/interprocess-communication",
        "doc://com.apple.uikit/documentation/UIKit/mac-catalyst"
      ],
      "title": "App structure"
    }
  ],
  "topicSections": [
    {
      "anchor": "Documents",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIDocument",
        "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument",
        "doc://com.apple.uikit/documentation/UIKit/synchronizing-documents-in-the-icloud-environment"
      ],
      "title": "Documents"
    },
    {
      "anchor": "Document-presentation",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController"
      ],
      "title": "Document presentation"
    },
    {
      "anchor": "Data-management",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIDataSourceModelAssociation"
      ],
      "title": "Data management"
    },
    {
      "anchor": "Pasteboard",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPasteControl",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteControl/Configuration-swift.class",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteControl/DisplayMode",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteConfiguration",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteConfigurationSupporting"
      ],
      "title": "Pasteboard"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Documents",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIDocument",
                "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument",
                "doc://com.apple.uikit/documentation/UIKit/synchronizing-documents-in-the-icloud-environment"
              ],
              "title": "Documents"
            },
            {
              "anchor": "Document-presentation",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIDocumentViewController"
              ],
              "title": "Document presentation"
            },
            {
              "anchor": "Data-management",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIDataSourceModelAssociation"
              ],
              "title": "Data management"
            },
            {
              "anchor": "Pasteboard",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPasteControl",
                "doc://com.apple.uikit/documentation/UIKit/UIPasteControl/Configuration-swift.class",
                "doc://com.apple.uikit/documentation/UIKit/UIPasteControl/DisplayMode",
                "doc://com.apple.uikit/documentation/UIKit/UIPasteboard",
                "doc://com.apple.uikit/documentation/UIKit/UIPasteConfiguration",
                "doc://com.apple.uikit/documentation/UIKit/UIPasteConfigurationSupporting"
              ],
              "title": "Pasteboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "App-structure",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/app-and-environment",
                "doc://com.apple.uikit/documentation/UIKit/resource-management",
                "doc://com.apple.uikit/documentation/UIKit/app-extensions",
                "doc://com.apple.uikit/documentation/UIKit/interprocess-communication",
                "doc://com.apple.uikit/documentation/UIKit/mac-catalyst"
              ],
              "title": "App structure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteConfiguration/title",
          "value": "UIPasteConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard/title",
          "value": "UIPasteboard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteControl/title",
          "value": "UIPasteControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteControl/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDataSourceModelAssociation/title",
          "value": "UIDataSourceModelAssociation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDataSourceModelAssociation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDataSourceModelAssociation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDataSourceModelAssociation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDataSourceModelAssociation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteConfigurationSupporting/title",
          "value": "UIPasteConfigurationSupporting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteConfigurationSupporting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteConfigurationSupporting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteConfigurationSupporting/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteConfigurationSupporting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocument/title",
          "value": "UIDocument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocument/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIManagedDocument/title",
          "value": "UIManagedDocument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIManagedDocument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIManagedDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIManagedDocument/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIManagedDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteControl~1DisplayMode/title",
          "value": "UIPasteControlDisplayMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteControl~1DisplayMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteControlDisplayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteControl~1DisplayMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteControlDisplayMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteControl~1Configuration-swift.class/title",
          "value": "UIPasteControlConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteControl~1Configuration-swift.class/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteControlConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteControl~1Configuration-swift.class/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteControlConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController/title",
          "value": "UIDocumentViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocumentViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocumentViewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/documents-data-and-pasteboard"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/documents-data-and-pasteboard"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
