{
  "abstract": [
    {
      "text": "Configure your app’s drawing environment using colors, renderers, draw paths, strings, and shadows.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/drawing"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Drawing"
  },
  "references": {
    "doc://com.apple.documentation/documentation/foundation/nscoder/1624474-string": {
      "abstract": [
        {
          "text": "Returns a string formatted to contain the data from a rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class func "
        },
        {
          "kind": "identifier",
          "text": "string"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": CGRect) -> String"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nscoder/1624474-string",
      "kind": "symbol",
      "role": "symbol",
      "title": "string(for:)",
      "type": "topic",
      "url": "/documentation/foundation/nscoder/1624474-string"
    },
    "doc://com.apple.documentation/documentation/foundation/nscoder/1624476-string": {
      "abstract": [
        {
          "text": "Returns a string formatted to contain the data from a vector data structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class func "
        },
        {
          "kind": "identifier",
          "text": "string"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": CGVector) -> String"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nscoder/1624476-string",
      "kind": "symbol",
      "role": "symbol",
      "title": "string(for:)",
      "type": "topic",
      "url": "/documentation/foundation/nscoder/1624476-string"
    },
    "doc://com.apple.documentation/documentation/foundation/nscoder/1624477-cgpoint": {
      "abstract": [
        {
          "text": "Returns a Core Graphics point structure corresponding to the data in a given string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class func "
        },
        {
          "kind": "identifier",
          "text": "cgPoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": String) -> CGPoint"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nscoder/1624477-cgpoint",
      "kind": "symbol",
      "role": "symbol",
      "title": "cgPoint(for:)",
      "type": "topic",
      "url": "/documentation/foundation/nscoder/1624477-cgpoint"
    },
    "doc://com.apple.documentation/documentation/foundation/nscoder/1624484-cgsize": {
      "abstract": [
        {
          "text": "Returns a Core Graphics size structure corresponding to the data in a given string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class func "
        },
        {
          "kind": "identifier",
          "text": "cgSize"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": String) -> CGSize"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nscoder/1624484-cgsize",
      "kind": "symbol",
      "role": "symbol",
      "title": "cgSize(for:)",
      "type": "topic",
      "url": "/documentation/foundation/nscoder/1624484-cgsize"
    },
    "doc://com.apple.documentation/documentation/foundation/nscoder/1624497-string": {
      "abstract": [
        {
          "text": "Returns a string formatted to contain the data from an affine transform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class func "
        },
        {
          "kind": "identifier",
          "text": "string"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": CGAffineTransform) -> String"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nscoder/1624497-string",
      "kind": "symbol",
      "role": "symbol",
      "title": "string(for:)",
      "type": "topic",
      "url": "/documentation/foundation/nscoder/1624497-string"
    },
    "doc://com.apple.documentation/documentation/foundation/nscoder/1624504-string": {
      "abstract": [
        {
          "text": "Returns a string formatted to contain the data from a point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class func "
        },
        {
          "kind": "identifier",
          "text": "string"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": CGPoint) -> String"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nscoder/1624504-string",
      "kind": "symbol",
      "role": "symbol",
      "title": "string(for:)",
      "type": "topic",
      "url": "/documentation/foundation/nscoder/1624504-string"
    },
    "doc://com.apple.documentation/documentation/foundation/nscoder/1624505-cgaffinetransform": {
      "abstract": [
        {
          "text": "Returns a Core Graphics affine transform structure corresponding to the data in a given string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class func "
        },
        {
          "kind": "identifier",
          "text": "cgAffineTransform"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": String) -> CGAffineTransform"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nscoder/1624505-cgaffinetransform",
      "kind": "symbol",
      "role": "symbol",
      "title": "cgAffineTransform(for:)",
      "type": "topic",
      "url": "/documentation/foundation/nscoder/1624505-cgaffinetransform"
    },
    "doc://com.apple.documentation/documentation/foundation/nscoder/1624508-cgrect": {
      "abstract": [
        {
          "text": "Returns a Core Graphics rectangle structure corresponding to the data in a given string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class func "
        },
        {
          "kind": "identifier",
          "text": "cgRect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": String) -> CGRect"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nscoder/1624508-cgrect",
      "kind": "symbol",
      "role": "symbol",
      "title": "cgRect(for:)",
      "type": "topic",
      "url": "/documentation/foundation/nscoder/1624508-cgrect"
    },
    "doc://com.apple.documentation/documentation/foundation/nscoder/1624513-cgvector": {
      "abstract": [
        {
          "text": "Returns a Core Graphics vector corresponding to the data in a given string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class func "
        },
        {
          "kind": "identifier",
          "text": "cgVector"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": String) -> CGVector"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nscoder/1624513-cgvector",
      "kind": "symbol",
      "role": "symbol",
      "title": "cgVector(for:)",
      "type": "topic",
      "url": "/documentation/foundation/nscoder/1624513-cgvector"
    },
    "doc://com.apple.documentation/documentation/foundation/nscoder/1624514-string": {
      "abstract": [
        {
          "text": "Returns a string formatted to contain the data from a size data structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class func "
        },
        {
          "kind": "identifier",
          "text": "string"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": CGSize) -> String"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nscoder/1624514-string",
      "kind": "symbol",
      "role": "symbol",
      "title": "string(for:)",
      "type": "topic",
      "url": "/documentation/foundation/nscoder/1624514-string"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/CGAffineTransformFromString": {
      "abstract": [
        {
          "text": "Returns a Core Graphics affine transform structure corresponding to the data in a given string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CGAffineTransformFromString"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/CGAffineTransformFromString",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGAffineTransformFromString",
      "type": "topic",
      "url": "/documentation/uikit/cgaffinetransformfromstring"
    },
    "doc://com.apple.uikit/documentation/UIKit/CGPointFromString": {
      "abstract": [
        {
          "text": "Returns a Core Graphics point structure corresponding to the data in a given string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CGPointFromString"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/CGPointFromString",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGPointFromString",
      "type": "topic",
      "url": "/documentation/uikit/cgpointfromstring"
    },
    "doc://com.apple.uikit/documentation/UIKit/CGRectFromString": {
      "abstract": [
        {
          "text": "Returns a Core Graphics rectangle structure corresponding to the data in a given string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CGRectFromString"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/CGRectFromString",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGRectFromString",
      "type": "topic",
      "url": "/documentation/uikit/cgrectfromstring"
    },
    "doc://com.apple.uikit/documentation/UIKit/CGSizeFromString": {
      "abstract": [
        {
          "text": "Returns a Core Graphics size structure corresponding to the data in a given string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CGSizeFromString"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/CGSizeFromString",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGSizeFromString",
      "type": "topic",
      "url": "/documentation/uikit/cgsizefromstring"
    },
    "doc://com.apple.uikit/documentation/UIKit/CGVectorFromString": {
      "abstract": [
        {
          "text": "Returns a Core Graphics vector corresponding to the data in a given string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CGVectorFromString"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/CGVectorFromString",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGVectorFromString",
      "type": "topic",
      "url": "/documentation/uikit/cgvectorfromstring"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSShadow": {
      "abstract": [
        {
          "text": "An object you use to specify attributes to create and style a drop shadow during drawing operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSShadow"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSShadow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSShadow"
        }
      ],
      "role": "symbol",
      "title": "NSShadow",
      "type": "topic",
      "url": "/documentation/uikit/nsshadow"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSStringDrawingContext": {
      "abstract": [
        {
          "text": "An object that manages metrics for drawing attributed strings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStringDrawingContext"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSStringDrawingContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSStringDrawingContext"
        }
      ],
      "role": "symbol",
      "title": "NSStringDrawingContext",
      "type": "topic",
      "url": "/documentation/uikit/nsstringdrawingcontext"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSStringDrawingOptions": {
      "abstract": [
        {
          "text": "Constants that specify the rendering options for drawing a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStringDrawingOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSStringDrawingOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSStringDrawingOptions"
        }
      ],
      "role": "symbol",
      "title": "NSStringDrawingOptions",
      "type": "topic",
      "url": "/documentation/uikit/nsstringdrawingoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSStringFromCGAffineTransform": {
      "abstract": [
        {
          "text": "Returns a string formatted to contain the data from an affine transform.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSStringFromCGAffineTransform"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSStringFromCGAffineTransform",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSStringFromCGAffineTransform",
      "type": "topic",
      "url": "/documentation/uikit/nsstringfromcgaffinetransform"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSStringFromCGPoint": {
      "abstract": [
        {
          "text": "Returns a string formatted to contain the data from a point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSStringFromCGPoint"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSStringFromCGPoint",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSStringFromCGPoint",
      "type": "topic",
      "url": "/documentation/uikit/nsstringfromcgpoint"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSStringFromCGRect": {
      "abstract": [
        {
          "text": "Returns a string formatted to contain the data from a rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSStringFromCGRect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSStringFromCGRect",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSStringFromCGRect",
      "type": "topic",
      "url": "/documentation/uikit/nsstringfromcgrect"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSStringFromCGSize": {
      "abstract": [
        {
          "text": "Returns a string formatted to contain the data from a size data structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSStringFromCGSize"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSStringFromCGSize",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSStringFromCGSize",
      "type": "topic",
      "url": "/documentation/uikit/nsstringfromcgsize"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSStringFromCGVector": {
      "abstract": [
        {
          "text": "Returns a string formatted to contain the data from a vector data structure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSStringFromCGVector"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSStringFromCGVector",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSStringFromCGVector",
      "type": "topic",
      "url": "/documentation/uikit/nsstringfromcgvector"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBaselineAdjustment": {
      "abstract": [
        {
          "text": "Vertical adjustment options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIBaselineAdjustment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBaselineAdjustment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBaselineAdjustment"
        }
      ],
      "role": "symbol",
      "title": "UIBaselineAdjustment",
      "type": "topic",
      "url": "/documentation/uikit/uibaselineadjustment"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBezierPath": {
      "abstract": [
        {
          "text": "A path that consists of straight and curved line segments that you can render in your custom views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIBezierPath"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBezierPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBezierPath"
        }
      ],
      "role": "symbol",
      "title": "UIBezierPath",
      "type": "topic",
      "url": "/documentation/uikit/uibezierpath"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIColor": {
      "abstract": [
        {
          "text": "An object that stores color data and sometimes opacity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIColor"
        }
      ],
      "role": "symbol",
      "title": "UIColor",
      "type": "topic",
      "url": "/documentation/uikit/uicolor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsBeginImageContextWithOptions(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a bitmap-based graphics context with the specified options.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsBeginImageContextWithOptions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsBeginImageContextWithOptions(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsBeginImageContextWithOptions"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsBeginImageContextWithOptions(_:_:_:)",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsbeginimagecontextwithoptions(_:_:_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsGetCurrentContext()": {
      "abstract": [
        {
          "text": "Returns the current graphics context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsGetCurrentContext"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGContextRef",
          "text": "CGContext"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsGetCurrentContext()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsGetCurrentContext"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsGetCurrentContext()",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsgetcurrentcontext()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer": {
      "abstract": [
        {
          "text": "A graphics renderer for creating Core Graphics-backed images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsImageRenderer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsImageRenderer"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsImageRenderer",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsimagerenderer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererContext": {
      "abstract": [
        {
          "text": "The drawing environment for an image renderer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsImageRendererContext"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsImageRendererContext"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsImageRendererContext",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsimagerenderercontext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat": {
      "abstract": [
        {
          "text": "A set of drawing attributes that represents the configuration of an image renderer context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsImageRendererFormat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsImageRendererFormat"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsImageRendererFormat",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsimagerendererformat"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer": {
      "abstract": [
        {
          "text": "A graphics renderer for creating PDFs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsPDFRenderer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsPDFRenderer"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsPDFRenderer",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicspdfrenderer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererContext": {
      "abstract": [
        {
          "text": "The drawing environment for a PDF renderer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsPDFRendererContext"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsPDFRendererContext"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsPDFRendererContext",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicspdfrenderercontext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererFormat": {
      "abstract": [
        {
          "text": "A set of drawing attributes that represents the configuration of a PDF renderer context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsPDFRendererFormat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsPDFRendererFormat"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsPDFRendererFormat",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicspdfrendererformat"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPopContext()": {
      "abstract": [
        {
          "text": "Removes the current graphics context from the top of the stack, restoring the previous context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsPopContext"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPopContext()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsPopContext"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsPopContext()",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicspopcontext()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPushContext(_:)": {
      "abstract": [
        {
          "text": "Makes the specified graphics context the current context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsPushContext"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGContextRef",
          "text": "CGContext"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPushContext(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsPushContext"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsPushContext(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicspushcontext(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRenderer": {
      "abstract": [
        {
          "text": "An abstract base class for creating graphics renderers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsRenderer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsRenderer"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsRenderer",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsrenderer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererContext": {
      "abstract": [
        {
          "text": "The base class for the drawing environments for graphics renderers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsRendererContext"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsRendererContext"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsRendererContext",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsrenderercontext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererFormat": {
      "abstract": [
        {
          "text": "A set of drawing attributes that represents the configuration of a graphics renderer context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsRendererFormat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsRendererFormat"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsRendererFormat",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsrendererformat"
    },
    "doc://com.apple.uikit/documentation/UIKit/UILineBreakMode": {
      "abstract": [
        {
          "text": "Options for wrapping and truncating text.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "UILineBreakMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UILineBreakMode",
      "kind": "symbol",
      "role": "symbol",
      "title": "UILineBreakMode",
      "type": "topic",
      "url": "/documentation/uikit/uilinebreakmode"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIRectClip(_:)": {
      "abstract": [
        {
          "text": "Modifies the current clipping path by intersecting it with the specified rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIRectClip"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIRectClip(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIRectClip"
        }
      ],
      "role": "symbol",
      "title": "UIRectClip(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uirectclip(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIRectFill(_:)": {
      "abstract": [
        {
          "text": "Fills the specified rectangle with the current color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIRectFill"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIRectFill(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIRectFill"
        }
      ],
      "role": "symbol",
      "title": "UIRectFill(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uirectfill(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIRectFillUsingBlendMode(_:_:)": {
      "abstract": [
        {
          "text": "Fills a rectangle with the current fill color using the specified blend mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIRectFillUsingBlendMode"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CGBlendMode",
          "text": "CGBlendMode"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIRectFillUsingBlendMode(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIRectFillUsingBlendMode"
        }
      ],
      "role": "symbol",
      "title": "UIRectFillUsingBlendMode(_:_:)",
      "type": "topic",
      "url": "/documentation/uikit/uirectfillusingblendmode(_:_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIRectFrame(_:)": {
      "abstract": [
        {
          "text": "Draws a frame around the inside of the specified rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIRectFrame"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIRectFrame(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIRectFrame"
        }
      ],
      "role": "symbol",
      "title": "UIRectFrame(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uirectframe(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIRectFrameUsingBlendMode(_:_:)": {
      "abstract": [
        {
          "text": "Draws a frame around the inside of a rectangle using the specified blend mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIRectFrameUsingBlendMode"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CGBlendMode",
          "text": "CGBlendMode"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIRectFrameUsingBlendMode(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIRectFrameUsingBlendMode"
        }
      ],
      "role": "symbol",
      "title": "UIRectFrameUsingBlendMode(_:_:)",
      "type": "topic",
      "url": "/documentation/uikit/uirectframeusingblendmode(_:_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextAlignment": {
      "abstract": [
        {
          "text": "Options for aligning text horizontally.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextAlignment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextAlignment",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextAlignment",
      "type": "topic",
      "url": "/documentation/uikit/uitextalignment"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextAttributeFont": {
      "abstract": [
        {
          "text": "The key to the font in a text attributes dictionary.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextAttributeFont"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextAttributeFont",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextAttributeFont",
      "type": "topic",
      "url": "/documentation/uikit/uitextattributefont"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextAttributeTextColor": {
      "abstract": [
        {
          "text": "The key to the text color in a text attributes dictionary.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextAttributeTextColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextAttributeTextColor",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextAttributeTextColor",
      "type": "topic",
      "url": "/documentation/uikit/uitextattributetextcolor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextAttributeTextShadowColor": {
      "abstract": [
        {
          "text": "The key to the text shadow color in a text attributes dictionary.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextAttributeTextShadowColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextAttributeTextShadowColor",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextAttributeTextShadowColor",
      "type": "topic",
      "url": "/documentation/uikit/uitextattributetextshadowcolor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextAttributeTextShadowOffset": {
      "abstract": [
        {
          "text": "The key to the offset for the text shadow in a text attributes dictionary.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextAttributeTextShadowOffset"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextAttributeTextShadowOffset",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextAttributeTextShadowOffset",
      "type": "topic",
      "url": "/documentation/uikit/uitextattributetextshadowoffset"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase": {
      "abstract": [
        {
          "text": "An object that defines specific phases of the UI update process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIUpdateActionPhase"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUpdateActionPhase"
        }
      ],
      "role": "symbol",
      "title": "UIUpdateActionPhase",
      "type": "topic",
      "url": "/documentation/uikit/uiupdateactionphase"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUpdateInfo": {
      "abstract": [
        {
          "text": "An object that contains detailed information about the current UI update state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIUpdateInfo"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUpdateInfo"
        }
      ],
      "role": "symbol",
      "title": "UIUpdateInfo",
      "type": "topic",
      "url": "/documentation/uikit/uiupdateinfo"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUpdateLink": {
      "abstract": [
        {
          "text": "An object you use to observe, participate in, and affect the UI update process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIUpdateLink"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateLink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUpdateLink"
        }
      ],
      "role": "symbol",
      "title": "UIUpdateLink",
      "type": "topic",
      "url": "/documentation/uikit/uiupdatelink"
    },
    "doc://com.apple.uikit/documentation/UIKit/images-and-pdf": {
      "abstract": [
        {
          "text": "Create and manage images, including those that use bitmap and PDF formats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/images-and-pdf",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Images and PDF",
      "type": "topic",
      "url": "/documentation/uikit/images-and-pdf"
    },
    "doc://com.apple.uikit/documentation/UIKit/printing": {
      "abstract": [
        {
          "text": "Display the system print panels and manage the printing process.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/printing",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Printing",
      "type": "topic",
      "url": "/documentation/uikit/printing"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Graphics-drawing-and-printing",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/images-and-pdf",
        "doc://com.apple.uikit/documentation/UIKit/printing"
      ],
      "title": "Graphics, drawing, and printing"
    }
  ],
  "topicSections": [
    {
      "anchor": "UI-updates",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIUpdateLink",
        "doc://com.apple.uikit/documentation/UIKit/UIUpdateInfo",
        "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase"
      ],
      "title": "UI updates"
    },
    {
      "anchor": "Color",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIColor"
      ],
      "title": "Color"
    },
    {
      "abstract": [
        {
          "text": "Use renderers to turn a set of programmatic drawing commands into a bitmap or PDF image.",
          "type": "text"
        }
      ],
      "anchor": "Graphics-contexts",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRenderer",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererContext",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererFormat",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererContext",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererContext",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererFormat"
      ],
      "title": "Graphics contexts"
    },
    {
      "anchor": "Paths",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIBezierPath",
        "doc://com.apple.uikit/documentation/UIKit/UIRectFill(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIRectFillUsingBlendMode(_:_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIRectFrame(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIRectFrameUsingBlendMode(_:_:)"
      ],
      "title": "Paths"
    },
    {
      "anchor": "Strings",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSStringDrawingContext",
        "doc://com.apple.uikit/documentation/UIKit/NSStringDrawingOptions",
        "doc://com.apple.uikit/documentation/UIKit/UIBaselineAdjustment"
      ],
      "title": "Strings"
    },
    {
      "anchor": "Shadows",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSShadow"
      ],
      "title": "Shadows"
    },
    {
      "abstract": [
        {
          "text": "Manage the current graphics environment using Core Graphics framework types.",
          "type": "text"
        }
      ],
      "anchor": "Graphics-context-primitives",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsGetCurrentContext()",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPushContext(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPopContext()",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsBeginImageContextWithOptions(_:_:_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIRectClip(_:)"
      ],
      "title": "Graphics context primitives"
    },
    {
      "anchor": "Primitive-type-conversions",
      "identifiers": [
        "doc://com.apple.documentation/documentation/foundation/nscoder/1624505-cgaffinetransform",
        "doc://com.apple.documentation/documentation/foundation/nscoder/1624477-cgpoint",
        "doc://com.apple.documentation/documentation/foundation/nscoder/1624508-cgrect",
        "doc://com.apple.documentation/documentation/foundation/nscoder/1624484-cgsize",
        "doc://com.apple.documentation/documentation/foundation/nscoder/1624513-cgvector",
        "doc://com.apple.documentation/documentation/foundation/nscoder/1624497-string",
        "doc://com.apple.documentation/documentation/foundation/nscoder/1624504-string",
        "doc://com.apple.documentation/documentation/foundation/nscoder/1624474-string",
        "doc://com.apple.documentation/documentation/foundation/nscoder/1624514-string",
        "doc://com.apple.documentation/documentation/foundation/nscoder/1624476-string"
      ],
      "title": "Primitive type conversions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "UI-updates",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIUpdateLink",
                "doc://com.apple.uikit/documentation/UIKit/UIUpdateInfo",
                "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase"
              ],
              "title": "UI updates"
            },
            {
              "anchor": "Color",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIColor"
              ],
              "title": "Color"
            },
            {
              "abstract": [
                {
                  "text": "Use renderers to turn a set of programmatic drawing commands into a bitmap or PDF image.",
                  "type": "text"
                }
              ],
              "anchor": "Graphics-contexts",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRenderer",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererContext",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererFormat",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererContext",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererContext",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererFormat"
              ],
              "title": "Graphics contexts"
            },
            {
              "anchor": "Paths",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIBezierPath",
                "doc://com.apple.uikit/documentation/UIKit/UIRectFill(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIRectFillUsingBlendMode(_:_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIRectFrame(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIRectFrameUsingBlendMode(_:_:)"
              ],
              "title": "Paths"
            },
            {
              "anchor": "Strings",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSStringDrawingContext",
                "doc://com.apple.uikit/documentation/UIKit/NSStringDrawingOptions",
                "doc://com.apple.uikit/documentation/UIKit/UIBaselineAdjustment",
                "doc://com.apple.uikit/documentation/UIKit/UILineBreakMode",
                "doc://com.apple.uikit/documentation/UIKit/UITextAlignment",
                "doc://com.apple.uikit/documentation/UIKit/UITextAttributeFont",
                "doc://com.apple.uikit/documentation/UIKit/UITextAttributeTextColor",
                "doc://com.apple.uikit/documentation/UIKit/UITextAttributeTextShadowColor",
                "doc://com.apple.uikit/documentation/UIKit/UITextAttributeTextShadowOffset"
              ],
              "title": "Strings"
            },
            {
              "anchor": "Shadows",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSShadow"
              ],
              "title": "Shadows"
            },
            {
              "abstract": [
                {
                  "text": "Manage the current graphics environment using Core Graphics framework types.",
                  "type": "text"
                }
              ],
              "anchor": "Graphics-context-primitives",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsGetCurrentContext()",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPushContext(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPopContext()",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsBeginImageContextWithOptions(_:_:_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIRectClip(_:)"
              ],
              "title": "Graphics context primitives"
            },
            {
              "anchor": "Primitive-type-conversions",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/CGAffineTransformFromString",
                "doc://com.apple.uikit/documentation/UIKit/CGPointFromString",
                "doc://com.apple.uikit/documentation/UIKit/CGRectFromString",
                "doc://com.apple.uikit/documentation/UIKit/CGSizeFromString",
                "doc://com.apple.uikit/documentation/UIKit/CGVectorFromString",
                "doc://com.apple.uikit/documentation/UIKit/NSStringFromCGAffineTransform",
                "doc://com.apple.uikit/documentation/UIKit/NSStringFromCGPoint",
                "doc://com.apple.uikit/documentation/UIKit/NSStringFromCGRect",
                "doc://com.apple.uikit/documentation/UIKit/NSStringFromCGSize",
                "doc://com.apple.uikit/documentation/UIKit/NSStringFromCGVector"
              ],
              "title": "Primitive type conversions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Graphics-drawing-and-printing",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/images-and-pdf",
                "doc://com.apple.uikit/documentation/UIKit/printing"
              ],
              "title": "Graphics, drawing, and printing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor/title",
          "value": "UIColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSShadow/title",
          "value": "NSShadow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSShadow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSShadow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSShadow/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSShadow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRenderer/title",
          "value": "UIGraphicsPDFRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsPDFRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsPDFRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSStringDrawingOptions/title",
          "value": "NSStringDrawingOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSStringDrawingOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStringDrawingOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSStringDrawingOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStringDrawingOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPushContext(_:)/title",
          "value": "UIGraphicsPushContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPushContext(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsPushContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRendererFormat/title",
          "value": "UIGraphicsImageRendererFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRendererFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsImageRendererFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRendererFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsImageRendererFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsBeginImageContextWithOptions(_:_:_:)/title",
          "value": "UIGraphicsBeginImageContextWithOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsBeginImageContextWithOptions(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsBeginImageContextWithOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateLink/title",
          "value": "UIUpdateLink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateLink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUpdateLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateLink/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUpdateLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRendererContext/title",
          "value": "UIGraphicsRendererContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRendererContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsRendererContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRendererContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsRendererContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRenderer/title",
          "value": "UIGraphicsImageRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsImageRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsImageRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPopContext()/title",
          "value": "UIGraphicsPopContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPopContext()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsPopContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRectFrameUsingBlendMode(_:_:)/title",
          "value": "UIRectFrameUsingBlendMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRectFrameUsingBlendMode(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIRectFrameUsingBlendMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSStringDrawingContext/title",
          "value": "NSStringDrawingContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSStringDrawingContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStringDrawingContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSStringDrawingContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStringDrawingContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsGetCurrentContext()/title",
          "value": "UIGraphicsGetCurrentContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsGetCurrentContext()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsGetCurrentContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateInfo/title",
          "value": "UIUpdateInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUpdateInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUpdateInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRectFillUsingBlendMode(_:_:)/title",
          "value": "UIRectFillUsingBlendMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRectFillUsingBlendMode(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIRectFillUsingBlendMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBezierPath/title",
          "value": "UIBezierPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBezierPath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBezierPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBezierPath/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBezierPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRendererFormat/title",
          "value": "UIGraphicsRendererFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRendererFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsRendererFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRendererFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsRendererFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRendererContext/title",
          "value": "UIGraphicsPDFRendererContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRendererContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsPDFRendererContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRendererContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsPDFRendererContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRectFrame(_:)/title",
          "value": "UIRectFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRectFrame(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIRectFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRectFill(_:)/title",
          "value": "UIRectFill"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRectFill(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIRectFill"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRenderer/title",
          "value": "UIGraphicsRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRendererContext/title",
          "value": "UIGraphicsImageRendererContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRendererContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsImageRendererContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRendererContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsImageRendererContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRectClip(_:)/title",
          "value": "UIRectClip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRectClip(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIRectClip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase/title",
          "value": "UIUpdateActionPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUpdateActionPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUpdateActionPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBaselineAdjustment/title",
          "value": "UIBaselineAdjustment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBaselineAdjustment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBaselineAdjustment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBaselineAdjustment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBaselineAdjustment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRendererFormat/title",
          "value": "UIGraphicsPDFRendererFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRendererFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsPDFRendererFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRendererFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsPDFRendererFormat"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/drawing"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/drawing"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
