{
  "abstract": [
    {
      "text": "Configure text fields and custom views that accept text to handle input from Apple Pencil.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/handwriting-recognition"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Handwriting recognition"
  },
  "references": {
    "doc://com.apple.documentation/documentation/PencilKit/customizing-scribble-with-interactions": {
      "abstract": [
        {
          "text": "Enable writing on a non-text-input view by adding interactions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/PencilKit/customizing-scribble-with-interactions",
      "kind": "article",
      "role": "sampleCode",
      "title": "Customizing Scribble with Interactions",
      "type": "topic",
      "url": "/documentation/PencilKit/customizing-scribble-with-interactions"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteraction-1nfjm": {
      "abstract": [
        {
          "text": "An interaction for using Scribble to enter text by writing on a view that isn’t formally a text input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIIndirectScribbleInteraction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteraction-1nfjm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIIndirectScribbleInteraction"
        }
      ],
      "role": "symbol",
      "title": "UIIndirectScribbleInteraction",
      "type": "topic",
      "url": "/documentation/uikit/uiindirectscribbleinteraction-1nfjm"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteraction-2dap8": {
      "abstract": [
        {
          "text": "An interaction for using Scribble to enter text by writing on a view that isn’t formally a text input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIIndirectScribbleInteraction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteraction-2dap8",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIIndirectScribbleInteraction",
      "type": "topic",
      "url": "/documentation/uikit/uiindirectscribbleinteraction-2dap8"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteractionDelegate-3jmnk": {
      "abstract": [
        {
          "text": "Methods that customize behavior on views that aren’t formally text input views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIIndirectScribbleInteractionDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteractionDelegate-3jmnk",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIIndirectScribbleInteractionDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uiindirectscribbleinteractiondelegate-3jmnk"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteractionDelegate-hdh": {
      "abstract": [
        {
          "text": "Methods that customize behavior on views that aren’t formally text input views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIIndirectScribbleInteractionDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteractionDelegate-hdh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIIndirectScribbleInteractionDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIIndirectScribbleInteractionDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uiindirectscribbleinteractiondelegate-hdh"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteractionDelegate-hdh/ElementIdentifier": {
      "abstract": [
        {
          "text": "A unique identifier for a control that isn’t a text field in a Scribble interaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "associatedtype"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ElementIdentifier"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SH",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteractionDelegate-hdh/ElementIdentifier",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "ElementIdentifier",
      "type": "topic",
      "url": "/documentation/uikit/uiindirectscribbleinteractiondelegate-hdh/elementidentifier"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScribbleElementIdentifier": {
      "abstract": [
        {
          "text": "The element’s unique identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIScribbleElementIdentifier"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScribbleElementIdentifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIScribbleElementIdentifier",
      "type": "topic",
      "url": "/documentation/uikit/uiscribbleelementidentifier"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScribbleInteraction": {
      "abstract": [
        {
          "text": "An interaction for customizing the behavior of Scribble on text input views, or for suppressing it entirely in specific cases.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIScribbleInteraction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScribbleInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIScribbleInteraction"
        }
      ],
      "role": "symbol",
      "title": "UIScribbleInteraction",
      "type": "topic",
      "url": "/documentation/uikit/uiscribbleinteraction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScribbleInteractionDelegate": {
      "abstract": [
        {
          "text": "Methods for customizing or suppressing Scribble behavior within text input views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIScribbleInteractionDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScribbleInteractionDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIScribbleInteractionDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIScribbleInteractionDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uiscribbleinteractiondelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/keyboards-and-input": {
      "abstract": [
        {
          "text": "Configure the system keyboard, create your own keyboards to handle input, or detect key presses on a physical keyboard.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/keyboards-and-input",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Keyboards and input",
      "type": "topic",
      "url": "/documentation/uikit/keyboards-and-input"
    },
    "doc://com.apple.uikit/documentation/UIKit/text-display-and-fonts": {
      "abstract": [
        {
          "text": "Display text, manage fonts, and check spelling.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/text-display-and-fonts",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Text display and fonts",
      "type": "topic",
      "url": "/documentation/uikit/text-display-and-fonts"
    },
    "doc://com.apple.uikit/documentation/UIKit/textkit": {
      "abstract": [
        {
          "text": "Manage text storage and perform custom layout of text-based content in your app’s views.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/textkit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TextKit",
      "type": "topic",
      "url": "/documentation/uikit/textkit"
    },
    "doc://com.apple.uikit/documentation/UIKit/writing-tools": {
      "abstract": [
        {
          "text": "Add support for Writing Tools to your app’s text views.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/writing-tools",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Writing Tools",
      "type": "topic",
      "url": "/documentation/uikit/writing-tools"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Text",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/text-display-and-fonts",
        "doc://com.apple.uikit/documentation/UIKit/textkit",
        "doc://com.apple.uikit/documentation/UIKit/keyboards-and-input",
        "doc://com.apple.uikit/documentation/UIKit/writing-tools"
      ],
      "title": "Text"
    }
  ],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.documentation/documentation/PencilKit/customizing-scribble-with-interactions"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Text-fields",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIScribbleInteraction",
        "doc://com.apple.uikit/documentation/UIKit/UIScribbleInteractionDelegate"
      ],
      "title": "Text fields"
    },
    {
      "anchor": "Custom-views",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteraction-1nfjm",
        "doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteractionDelegate-hdh",
        "doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteractionDelegate-hdh/ElementIdentifier"
      ],
      "title": "Custom views"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.documentation/documentation/PencilKit/customizing-scribble-with-interactions"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "Text-fields",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIScribbleInteraction",
                "doc://com.apple.uikit/documentation/UIKit/UIScribbleInteractionDelegate"
              ],
              "title": "Text fields"
            },
            {
              "anchor": "Custom-views",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteraction-2dap8",
                "doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteractionDelegate-3jmnk",
                "doc://com.apple.uikit/documentation/UIKit/UIScribbleElementIdentifier"
              ],
              "title": "Custom views"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Text",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/text-display-and-fonts",
                "doc://com.apple.uikit/documentation/UIKit/textkit",
                "doc://com.apple.uikit/documentation/UIKit/keyboards-and-input",
                "doc://com.apple.uikit/documentation/UIKit/writing-tools"
              ],
              "title": "Text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScribbleInteraction/title",
          "value": "UIScribbleInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScribbleInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScribbleInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScribbleInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScribbleInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScribbleInteractionDelegate/title",
          "value": "UIScribbleInteractionDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScribbleInteractionDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScribbleInteractionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScribbleInteractionDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScribbleInteractionDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/handwriting-recognition"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/handwriting-recognition"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
