{
  "abstract": [
    {
      "text": "Detect extended duration taps on the screen, and use them to reveal contextually relevant content.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/touches-presses-and-gestures",
        "doc://com.apple.uikit/documentation/UIKit/handling-uikit-gestures"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/handling-long-press-gestures"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Handling long-press gestures"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Long-press (also known as press-and-hold) gestures detect one or more fingers (or a stylus) touching the screen for an extended period of time. You configure the minimum duration required to recognize the press and the number of times the fingers must be touching the screen. (The gesture recognizer is triggered only by the duration of the touches and not by the force associated with them.) You might use a long-press gesture to initiate an action on the object being pressed. For example, you might use it to display a context-sensitive menu.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can attach a gesture recognizer in one of these ways:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Programmatically. Call the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/addGestureRecognizer(_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method of your view.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In Interface Builder. Drag the appropriate object from the library and drop it onto your view.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-3004403",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Long-press gestures are continuous gestures, meaning that your action method may be called multiple times as the state changes. After a person’s fingers have touched the screen for the minimum amount of time, a long-press gesture recognizer enters the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/began",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " state. The gesture recognizer moves to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/changed",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " state if the fingers move or if any other changes occur to the touches. The gesture recognizer remains in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/changed",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " state as long as the fingers remain down, even if those fingers move outside of the initial view. When a person’s fingers lift from the screen, the gesture recognizer enters the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/ended",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " state.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following code shows an action method that displays a context menu on top of the view. It displays the context menu at the beginning of the gesture, while a person’s finger is still on the screen. The view controller that implements this method also sets itself as the first responder so that it can respond to menu actions selected by a person.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "@IBAction func showResetMenu(_ gestureRecognizer: UILongPressGestureRecognizer) {",
            "   if gestureRecognizer.state == .began {",
            "      self.becomeFirstResponder()",
            "      self.viewForReset = gestureRecognizer.view",
            "",
            "      // Configure the menu item to display",
            "      let menuItemTitle = NSLocalizedString(\"Reset\", comment: \"Reset menu item title\")",
            "      let action = #selector(ViewController.resetPiece(controller:))",
            "      let resetMenuItem = UIMenuItem(title: menuItemTitle, action: action)",
            "",
            "      // Configure the shared menu controller",
            "      let menuController = UIMenuController.shared",
            "      menuController.menuItems = [resetMenuItem]",
            "",
            "      // Set the location of the menu in the view.",
            "      let location = gestureRecognizer.location(in: gestureRecognizer.view)",
            "      let menuLocation = CGRect(x: location.x, y: location.y, width: 0, height: 0)",
            "      menuController.setTargetRect(menuLocation, in: gestureRecognizer.view!)",
            "",
            "      // Show the menu.",
            "      menuController.setMenuVisible(true, animated: true)",
            "   }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "If the code for your long-press gesture recognizer isn’t called, check to see if the following conditions are true, and make corrections as needed:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/isUserInteractionEnabled",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property of the view is set to ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/swift/true",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". Image views and labels set this property to ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/swift/false",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " by default.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The tap duration was greater than what is specified in the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UILongPressGestureRecognizer/minimumPressDuration",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The number of taps was equal to the number specified in the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UILongPressGestureRecognizer/numberOfTapsRequired",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The number of fingers was equal to the number specified in the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UILongPressGestureRecognizer/numberOfTouchesRequired",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/swift/false": {
      "abstract": [
        {
          "text": "A false value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/false",
      "kind": "symbol",
      "role": "symbol",
      "title": "false",
      "type": "topic",
      "url": "/documentation/swift/false"
    },
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/began": {
      "abstract": [
        {
          "text": "The gesture recognizer has received touch objects recognized as a continuous gesture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "began"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/began",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGestureRecognizerStateBegan"
        }
      ],
      "role": "symbol",
      "title": "UIGestureRecognizer.State.began",
      "type": "topic",
      "url": "/documentation/uikit/uigesturerecognizer/state-swift.enum/began"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/changed": {
      "abstract": [
        {
          "text": "The gesture recognizer has received touches recognized as a change to a continuous gesture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changed"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/changed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGestureRecognizerStateChanged"
        }
      ],
      "role": "symbol",
      "title": "UIGestureRecognizer.State.changed",
      "type": "topic",
      "url": "/documentation/uikit/uigesturerecognizer/state-swift.enum/changed"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/ended": {
      "abstract": [
        {
          "text": "The gesture recognizer has received touches recognized as the end of a continuous gesture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ended"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/State-swift.enum/ended",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGestureRecognizerStateEnded"
        }
      ],
      "role": "symbol",
      "title": "UIGestureRecognizer.State.ended",
      "type": "topic",
      "url": "/documentation/uikit/uigesturerecognizer/state-swift.enum/ended"
    },
    "doc://com.apple.uikit/documentation/UIKit/UILongPressGestureRecognizer/minimumPressDuration": {
      "abstract": [
        {
          "text": "The minimum time that the user must press on the view for the gesture to be recognized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minimumPressDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UILongPressGestureRecognizer/minimumPressDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "minimumPressDuration"
        }
      ],
      "role": "symbol",
      "title": "minimumPressDuration",
      "type": "topic",
      "url": "/documentation/uikit/uilongpressgesturerecognizer/minimumpressduration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UILongPressGestureRecognizer/numberOfTapsRequired": {
      "abstract": [
        {
          "text": "The number of taps on the view necessary for gesture recognition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfTapsRequired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UILongPressGestureRecognizer/numberOfTapsRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberOfTapsRequired"
        }
      ],
      "role": "symbol",
      "title": "numberOfTapsRequired",
      "type": "topic",
      "url": "/documentation/uikit/uilongpressgesturerecognizer/numberoftapsrequired"
    },
    "doc://com.apple.uikit/documentation/UIKit/UILongPressGestureRecognizer/numberOfTouchesRequired": {
      "abstract": [
        {
          "text": "The number of fingers that must touch the view for gesture recognition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfTouchesRequired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UILongPressGestureRecognizer/numberOfTouchesRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberOfTouchesRequired"
        }
      ],
      "role": "symbol",
      "title": "numberOfTouchesRequired",
      "type": "topic",
      "url": "/documentation/uikit/uilongpressgesturerecognizer/numberoftouchesrequired"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/addGestureRecognizer(_:)": {
      "abstract": [
        {
          "text": "Attaches a gesture recognizer to the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addGestureRecognizer"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIGestureRecognizer",
          "text": "UIGestureRecognizer"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/addGestureRecognizer(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addGestureRecognizer:"
        }
      ],
      "role": "symbol",
      "title": "addGestureRecognizer(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiview/addgesturerecognizer(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/isUserInteractionEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether user events are ignored and removed from the event queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isUserInteractionEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/isUserInteractionEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userInteractionEnabled"
        }
      ],
      "role": "symbol",
      "title": "isUserInteractionEnabled",
      "type": "topic",
      "url": "/documentation/uikit/uiview/isuserinteractionenabled"
    },
    "doc://com.apple.uikit/documentation/UIKit/handling-pan-gestures": {
      "abstract": [
        {
          "text": "Trace the movement of fingers around the screen, and apply that movement to your content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/handling-pan-gestures",
      "kind": "article",
      "role": "article",
      "title": "Handling pan gestures",
      "type": "topic",
      "url": "/documentation/uikit/handling-pan-gestures"
    },
    "doc://com.apple.uikit/documentation/UIKit/handling-pinch-gestures": {
      "abstract": [
        {
          "text": "Track the distance between two fingers and use that information to scale or zoom your content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/handling-pinch-gestures",
      "kind": "article",
      "role": "article",
      "title": "Handling pinch gestures",
      "type": "topic",
      "url": "/documentation/uikit/handling-pinch-gestures"
    },
    "doc://com.apple.uikit/documentation/UIKit/handling-rotation-gestures": {
      "abstract": [
        {
          "text": "Measure the relative rotation of two fingers on the screen, and use that motion to rotate your content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/handling-rotation-gestures",
      "kind": "article",
      "role": "article",
      "title": "Handling rotation gestures",
      "type": "topic",
      "url": "/documentation/uikit/handling-rotation-gestures"
    },
    "doc://com.apple.uikit/documentation/UIKit/handling-swipe-gestures": {
      "abstract": [
        {
          "text": "Detect a horizontal or vertical swipe motion on the screen, and use it to trigger navigation through your content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/handling-swipe-gestures",
      "kind": "article",
      "role": "article",
      "title": "Handling swipe gestures",
      "type": "topic",
      "url": "/documentation/uikit/handling-swipe-gestures"
    },
    "doc://com.apple.uikit/documentation/UIKit/handling-tap-gestures": {
      "abstract": [
        {
          "text": "Use brief taps on the screen to implement button-like interactions with your content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/handling-tap-gestures",
      "kind": "article",
      "role": "article",
      "title": "Handling tap gestures",
      "type": "topic",
      "url": "/documentation/uikit/handling-tap-gestures"
    },
    "doc://com.apple.uikit/documentation/UIKit/handling-uikit-gestures": {
      "abstract": [
        {
          "text": "Use gesture recognizers to simplify touch handling and create a consistent user experience.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/handling-uikit-gestures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Handling UIKit gestures",
      "type": "topic",
      "url": "/documentation/uikit/handling-uikit-gestures"
    },
    "doc://com.apple.uikit/documentation/UIKit/touches-presses-and-gestures": {
      "abstract": [
        {
          "text": "Encapsulate your app’s event-handling logic in gesture recognizers so that you can reuse that code throughout your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/touches-presses-and-gestures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Touches, presses, and gestures",
      "type": "topic",
      "url": "/documentation/uikit/touches-presses-and-gestures"
    },
    "media-3004403": {
      "alt": "A diagram showing a single-finger long-press gesture",
      "identifier": "media-3004403",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/022d87723d9726cc1bc67694ea907abd/media-3004403@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Gestures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/handling-tap-gestures",
        "doc://com.apple.uikit/documentation/UIKit/handling-pan-gestures",
        "doc://com.apple.uikit/documentation/UIKit/handling-swipe-gestures",
        "doc://com.apple.uikit/documentation/UIKit/handling-pinch-gestures",
        "doc://com.apple.uikit/documentation/UIKit/handling-rotation-gestures"
      ],
      "title": "Gestures"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Gestures",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/handling-tap-gestures",
                "doc://com.apple.uikit/documentation/UIKit/handling-pan-gestures",
                "doc://com.apple.uikit/documentation/UIKit/handling-swipe-gestures",
                "doc://com.apple.uikit/documentation/UIKit/handling-pinch-gestures",
                "doc://com.apple.uikit/documentation/UIKit/handling-rotation-gestures"
              ],
              "title": "Gestures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizer~1State-swift.enum~1ended/title",
          "value": "UIGestureRecognizerStateEnded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizer~1State-swift.enum~1ended/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGestureRecognizerStateEnded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILongPressGestureRecognizer~1minimumPressDuration/title",
          "value": "minimumPressDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILongPressGestureRecognizer~1minimumPressDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "minimumPressDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILongPressGestureRecognizer~1numberOfTouchesRequired/title",
          "value": "numberOfTouchesRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILongPressGestureRecognizer~1numberOfTouchesRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfTouchesRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILongPressGestureRecognizer~1numberOfTapsRequired/title",
          "value": "numberOfTapsRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILongPressGestureRecognizer~1numberOfTapsRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfTapsRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizer~1State-swift.enum~1changed/title",
          "value": "UIGestureRecognizerStateChanged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizer~1State-swift.enum~1changed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGestureRecognizerStateChanged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1isUserInteractionEnabled/title",
          "value": "userInteractionEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1isUserInteractionEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "userInteractionEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizer~1State-swift.enum~1began/title",
          "value": "UIGestureRecognizerStateBegan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizer~1State-swift.enum~1began/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGestureRecognizerStateBegan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1addGestureRecognizer(_:)/title",
          "value": "addGestureRecognizer:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1addGestureRecognizer(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addGestureRecognizer:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/handling-long-press-gestures"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/handling-long-press-gestures"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
