{
  "abstract": [
    {
      "text": "Create and manage images, including those that use bitmap and PDF formats.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/images-and-pdf"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Images and PDF"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsAddPDFContextDestinationAtPoint(_:_:)": {
      "abstract": [
        {
          "text": "Creates a jump destination in the current page.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsAddPDFContextDestinationAtPoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsAddPDFContextDestinationAtPoint(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsAddPDFContextDestinationAtPoint"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsAddPDFContextDestinationAtPoint(_:_:)",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsaddpdfcontextdestinationatpoint(_:_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsBeginImageContext(_:)": {
      "abstract": [
        {
          "text": "Creates a bitmap-based graphics context and makes it the current context.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsBeginImageContext"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsBeginImageContext(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsBeginImageContext"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsBeginImageContext(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsbeginimagecontext(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsBeginPDFContextToData(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a PDF graphics context that targets the specified mutable data object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsBeginPDFContextToData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMutableData",
          "text": "NSMutableData"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ", ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsBeginPDFContextToData(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsBeginPDFContextToData"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsBeginPDFContextToData(_:_:_:)",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsbeginpdfcontexttodata(_:_:_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsBeginPDFContextToFile(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a PDF graphics context that targets a file at the specified path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsBeginPDFContextToFile"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ", ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsBeginPDFContextToFile(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsBeginPDFContextToFile"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsBeginPDFContextToFile(_:_:_:)",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsbeginpdfcontexttofile(_:_:_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsBeginPDFPage()": {
      "abstract": [
        {
          "text": "Marks the beginning of a new page in a PDF context and configures it using default values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsBeginPDFPage"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsBeginPDFPage()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsBeginPDFPage"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsBeginPDFPage()",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsbeginpdfpage()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsBeginPDFPageWithInfo(_:_:)": {
      "abstract": [
        {
          "text": "Marks the beginning of a new page in a PDF context and configures it using the specified custom values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsBeginPDFPageWithInfo"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ", ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsBeginPDFPageWithInfo(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsBeginPDFPageWithInfo"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsBeginPDFPageWithInfo(_:_:)",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsbeginpdfpagewithinfo(_:_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsEndImageContext()": {
      "abstract": [
        {
          "text": "Removes the current bitmap-based graphics context from the top of the stack.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsEndImageContext"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsEndImageContext()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsEndImageContext"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsEndImageContext()",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsendimagecontext()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsEndPDFContext()": {
      "abstract": [
        {
          "text": "Closes a PDF graphics context and pops it from the current context stack.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsEndPDFContext"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsEndPDFContext()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsEndPDFContext"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsEndPDFContext()",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsendpdfcontext()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsGetImageFromCurrentImageContext()": {
      "abstract": [
        {
          "text": "Returns an image from the contents of the current bitmap-based graphics context.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsGetImageFromCurrentImageContext"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsGetImageFromCurrentImageContext()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsGetImageFromCurrentImageContext"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsGetImageFromCurrentImageContext()",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsgetimagefromcurrentimagecontext()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsGetPDFContextBounds()": {
      "abstract": [
        {
          "text": "Returns the current page bounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsGetPDFContextBounds"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsGetPDFContextBounds()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsGetPDFContextBounds"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsGetPDFContextBounds()",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsgetpdfcontextbounds()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsSetPDFContextDestinationForRect(_:_:)": {
      "abstract": [
        {
          "text": "Links a rectangular area on the current page to the specified jump destination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsSetPDFContextDestinationForRect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsSetPDFContextDestinationForRect(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsSetPDFContextDestinationForRect"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsSetPDFContextDestinationForRect(_:_:)",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicssetpdfcontextdestinationforrect(_:_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsSetPDFContextURLForRect(_:_:)": {
      "abstract": [
        {
          "text": "Links a rectangular area on the current page to the specified URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsSetPDFContextURLForRect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsSetPDFContextURLForRect(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsSetPDFContextURLForRect"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsSetPDFContextURLForRect(_:_:)",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicssetpdfcontexturlforrect(_:_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage": {
      "abstract": [
        {
          "text": "An object that manages image data in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIImage"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImage"
        }
      ],
      "role": "symbol",
      "title": "UIImage",
      "type": "topic",
      "url": "/documentation/uikit/uiimage"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/Configuration-swift.class": {
      "abstract": [
        {
          "text": "A configuration object that contains the traits that the system uses when selecting the current image variant.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Configuration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/Configuration-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Configuration"
        }
      ],
      "role": "symbol",
      "title": "UIImage.Configuration",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/configuration-swift.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class": {
      "abstract": [
        {
          "text": "An object that contains the specific font, size, style, and weight attributes to apply to a symbol image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SymbolConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SymbolConfiguration"
        }
      ],
      "role": "symbol",
      "title": "UIImage.SymbolConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/symbolconfiguration-swift.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/jpegData(compressionQuality:)": {
      "abstract": [
        {
          "text": "Returns a data object that contains the image in JPEG format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "jpegData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "compressionQuality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/jpegData(compressionQuality:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImageJPEGRepresentation"
        }
      ],
      "role": "symbol",
      "title": "jpegData(compressionQuality:)",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/jpegdata(compressionquality:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/pngData()": {
      "abstract": [
        {
          "text": "Returns a data object that contains the specified image in PNG format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pngData"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/pngData()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImagePNGRepresentation"
        }
      ],
      "role": "symbol",
      "title": "pngData()",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/pngdata()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImageWriteToSavedPhotosAlbum(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Adds the specified image to the user’s Camera Roll album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIImageWriteToSavedPhotosAlbum"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImageWriteToSavedPhotosAlbum(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImageWriteToSavedPhotosAlbum"
        }
      ],
      "role": "symbol",
      "title": "UIImageWriteToSavedPhotosAlbum(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiimagewritetosavedphotosalbum(_:_:_:_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISaveVideoAtPathToSavedPhotosAlbum(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Adds the movie from the specified path to the user’s Camera Roll album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISaveVideoAtPathToSavedPhotosAlbum"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISaveVideoAtPathToSavedPhotosAlbum(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISaveVideoAtPathToSavedPhotosAlbum"
        }
      ],
      "role": "symbol",
      "title": "UISaveVideoAtPathToSavedPhotosAlbum(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/uikit/uisavevideoatpathtosavedphotosalbum(_:_:_:_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreenshotService": {
      "abstract": [
        {
          "text": "An object that coordinates the creation of PDF screenshots of an app’s content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIScreenshotService"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreenshotService",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIScreenshotService"
        }
      ],
      "role": "symbol",
      "title": "UIScreenshotService",
      "type": "topic",
      "url": "/documentation/uikit/uiscreenshotservice"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIVideoAtPathIsCompatibleWithSavedPhotosAlbum(_:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the specified video is compatible to save to the user’s Camera Roll album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIVideoAtPathIsCompatibleWithSavedPhotosAlbum"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIVideoAtPathIsCompatibleWithSavedPhotosAlbum(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIVideoAtPathIsCompatibleWithSavedPhotosAlbum"
        }
      ],
      "role": "symbol",
      "title": "UIVideoAtPathIsCompatibleWithSavedPhotosAlbum(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uivideoatpathiscompatiblewithsavedphotosalbum(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/drawing": {
      "abstract": [
        {
          "text": "Configure your app’s drawing environment using colors, renderers, draw paths, strings, and shadows.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/drawing",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Drawing",
      "type": "topic",
      "url": "/documentation/uikit/drawing"
    },
    "doc://com.apple.uikit/documentation/UIKit/printing": {
      "abstract": [
        {
          "text": "Display the system print panels and manage the printing process.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/printing",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Printing",
      "type": "topic",
      "url": "/documentation/uikit/printing"
    },
    "doc://com.apple.uikit/documentation/UIKit/supporting-hdr-images-in-your-app": {
      "abstract": [
        {
          "text": "​",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "Load, display, edit, and save HDR images using SwiftUI and Core Image.",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "​",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/supporting-hdr-images-in-your-app",
      "kind": "article",
      "role": "sampleCode",
      "title": "Supporting HDR images in your app",
      "type": "topic",
      "url": "/documentation/uikit/supporting-hdr-images-in-your-app"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Graphics-drawing-and-printing",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/drawing",
        "doc://com.apple.uikit/documentation/UIKit/printing"
      ],
      "title": "Graphics, drawing, and printing"
    }
  ],
  "topicSections": [
    {
      "anchor": "Representations",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIImage",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/Configuration-swift.class"
      ],
      "title": "Representations"
    },
    {
      "anchor": "Image-creation",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/supporting-hdr-images-in-your-app",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/jpegData(compressionQuality:)",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/pngData()",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsBeginImageContext(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsGetImageFromCurrentImageContext()",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsEndImageContext()"
      ],
      "title": "Image creation"
    },
    {
      "anchor": "Photo-album",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIImageWriteToSavedPhotosAlbum(_:_:_:_:)",
        "doc://com.apple.uikit/documentation/UIKit/UISaveVideoAtPathToSavedPhotosAlbum(_:_:_:_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIVideoAtPathIsCompatibleWithSavedPhotosAlbum(_:)"
      ],
      "title": "Photo album"
    },
    {
      "anchor": "PDF-creation",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsBeginPDFContextToData(_:_:_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsBeginPDFContextToFile(_:_:_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsEndPDFContext()",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsBeginPDFPage()",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsBeginPDFPageWithInfo(_:_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsGetPDFContextBounds()",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsAddPDFContextDestinationAtPoint(_:_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsSetPDFContextDestinationForRect(_:_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsSetPDFContextURLForRect(_:_:)"
      ],
      "title": "PDF creation"
    },
    {
      "anchor": "PDF-screenshots",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIScreenshotService"
      ],
      "title": "PDF screenshots"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Representations",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIImage",
                "doc://com.apple.uikit/documentation/UIKit/UIImage/SymbolConfiguration-swift.class",
                "doc://com.apple.uikit/documentation/UIKit/UIImage/Configuration-swift.class"
              ],
              "title": "Representations"
            },
            {
              "anchor": "Image-creation",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/supporting-hdr-images-in-your-app",
                "doc://com.apple.uikit/documentation/UIKit/UIImage/jpegData(compressionQuality:)",
                "doc://com.apple.uikit/documentation/UIKit/UIImage/pngData()",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsBeginImageContext(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsGetImageFromCurrentImageContext()",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsEndImageContext()"
              ],
              "title": "Image creation"
            },
            {
              "anchor": "Photo-album",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIImageWriteToSavedPhotosAlbum(_:_:_:_:)",
                "doc://com.apple.uikit/documentation/UIKit/UISaveVideoAtPathToSavedPhotosAlbum(_:_:_:_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIVideoAtPathIsCompatibleWithSavedPhotosAlbum(_:)"
              ],
              "title": "Photo album"
            },
            {
              "anchor": "PDF-creation",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsBeginPDFContextToData(_:_:_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsBeginPDFContextToFile(_:_:_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsEndPDFContext()",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsBeginPDFPage()",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsBeginPDFPageWithInfo(_:_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsGetPDFContextBounds()",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsAddPDFContextDestinationAtPoint(_:_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsSetPDFContextDestinationForRect(_:_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsSetPDFContextURLForRect(_:_:)"
              ],
              "title": "PDF creation"
            },
            {
              "anchor": "PDF-screenshots",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIScreenshotService"
              ],
              "title": "PDF screenshots"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Graphics-drawing-and-printing",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/drawing",
                "doc://com.apple.uikit/documentation/UIKit/printing"
              ],
              "title": "Graphics, drawing, and printing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsBeginPDFContextToFile(_:_:_:)/title",
          "value": "UIGraphicsBeginPDFContextToFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsBeginPDFContextToFile(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsBeginPDFContextToFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsBeginPDFContextToData(_:_:_:)/title",
          "value": "UIGraphicsBeginPDFContextToData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsBeginPDFContextToData(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsBeginPDFContextToData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsAddPDFContextDestinationAtPoint(_:_:)/title",
          "value": "UIGraphicsAddPDFContextDestinationAtPoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsAddPDFContextDestinationAtPoint(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsAddPDFContextDestinationAtPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsEndPDFContext()/title",
          "value": "UIGraphicsEndPDFContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsEndPDFContext()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsEndPDFContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImageWriteToSavedPhotosAlbum(_:_:_:_:)/title",
          "value": "UIImageWriteToSavedPhotosAlbum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImageWriteToSavedPhotosAlbum(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageWriteToSavedPhotosAlbum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/title",
          "value": "UIImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsSetPDFContextDestinationForRect(_:_:)/title",
          "value": "UIGraphicsSetPDFContextDestinationForRect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsSetPDFContextDestinationForRect(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsSetPDFContextDestinationForRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsEndImageContext()/title",
          "value": "UIGraphicsEndImageContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsEndImageContext()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsEndImageContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsBeginImageContext(_:)/title",
          "value": "UIGraphicsBeginImageContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsBeginImageContext(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsBeginImageContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreenshotService/title",
          "value": "UIScreenshotService"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreenshotService/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreenshotService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreenshotService/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreenshotService"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsGetImageFromCurrentImageContext()/title",
          "value": "UIGraphicsGetImageFromCurrentImageContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsGetImageFromCurrentImageContext()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsGetImageFromCurrentImageContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsSetPDFContextURLForRect(_:_:)/title",
          "value": "UIGraphicsSetPDFContextURLForRect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsSetPDFContextURLForRect(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsSetPDFContextURLForRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1jpegData(compressionQuality:)/title",
          "value": "UIImageJPEGRepresentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1jpegData(compressionQuality:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageJPEGRepresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolConfiguration-swift.class/title",
          "value": "UIImageSymbolConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolConfiguration-swift.class/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageSymbolConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1SymbolConfiguration-swift.class/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageSymbolConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsGetPDFContextBounds()/title",
          "value": "UIGraphicsGetPDFContextBounds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsGetPDFContextBounds()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsGetPDFContextBounds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISaveVideoAtPathToSavedPhotosAlbum(_:_:_:_:)/title",
          "value": "UISaveVideoAtPathToSavedPhotosAlbum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISaveVideoAtPathToSavedPhotosAlbum(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISaveVideoAtPathToSavedPhotosAlbum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Configuration-swift.class/title",
          "value": "UIImageConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Configuration-swift.class/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1Configuration-swift.class/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIVideoAtPathIsCompatibleWithSavedPhotosAlbum(_:)/title",
          "value": "UIVideoAtPathIsCompatibleWithSavedPhotosAlbum"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIVideoAtPathIsCompatibleWithSavedPhotosAlbum(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIVideoAtPathIsCompatibleWithSavedPhotosAlbum"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1pngData()/title",
          "value": "UIImagePNGRepresentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1pngData()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImagePNGRepresentation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsBeginPDFPageWithInfo(_:_:)/title",
          "value": "UIGraphicsBeginPDFPageWithInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsBeginPDFPageWithInfo(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsBeginPDFPageWithInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsBeginPDFPage()/title",
          "value": "UIGraphicsBeginPDFPage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsBeginPDFPage()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsBeginPDFPage"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/images-and-pdf"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/images-and-pdf"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
