{"metadata":{"role":"collectionGroup","title":"Layouts","modules":[{"name":"UIKit"}],"roleHeading":"API Collection"},"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/layouts","interfaceLanguage":"swift"},"seeAlsoSections":[{"generated":true,"anchor":"Layouts","title":"Layouts","identifiers":["doc://com.apple.uikit/documentation/UIKit/implementing-modern-collection-views"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/layouts"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/layouts"]}],"abstract":[{"type":"text","text":"Arrange your collection view content in a highly configurable layout."}],"sections":[],"primaryContentSections":[{"kind":"content","content":[{"type":"heading","text":"Overview","anchor":"overview","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"A collection view "},{"inlineContent":[{"text":"layout","type":"text"}],"type":"emphasis"},{"type":"text","text":" defines the visual arrangement of the content in your collection. Layouts are designed to be flexible to let you create any kind of arrangement you need for your content, from simple to complex. The simplest type of collection view layout displays its items in a grid, but you can define layouts to arrange items however you like. For example, you might create a layout where items are arranged in a circle or vary in size. You can also change layouts dynamically at runtime whenever you need to present items differently, such as when a user rotates the device."}]},{"type":"paragraph","inlineContent":[{"text":"Collection view layouts are customizable and highly visual. For example, the App Store app uses a single collection view with custom layouts per section to showcase different kinds of content.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"media-3568662"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"For design guidance, see "},{"type":"reference","isActive":true,"identifier":"https://developer.apple.com/design/human-interface-guidelines/ios/views/collections/"},{"type":"text","text":"."}]}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/views-and-controls","doc://com.apple.uikit/documentation/UIKit/collection-views"]]},"kind":"article","schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"anchor":"Essentials","title":"Essentials","identifiers":["doc://com.apple.uikit/documentation/UIKit/implementing-modern-collection-views","doc://com.apple.uikit/documentation/UIKit/UICollectionViewCompositionalLayout"]},{"anchor":"Components","title":"Components","identifiers":["doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutItem","doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutGroup","doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSection"]},{"anchor":"Size-and-spacing","title":"Size and spacing","identifiers":["doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutDimension","doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSize","doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSpacing","doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutEdgeSpacing","doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutContainer"]},{"anchor":"Configuration","title":"Configuration","identifiers":["doc://com.apple.uikit/documentation/UIKit/UICollectionViewCompositionalLayoutConfiguration","doc://com.apple.uikit/documentation/UIKit/UICollectionViewCompositionalLayoutSectionProvider","doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutEnvironment"]},{"anchor":"Interaction","title":"Interaction","identifiers":["doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingBehavior"]},{"anchor":"Appearance","title":"Appearance","identifiers":["doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutAnchor","doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSupplementaryItem","doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutBoundarySupplementaryItem","doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutDecorationItem"]},{"anchor":"Advanced-layouts","title":"Advanced layouts","identifiers":["doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutGroupCustomItem","doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutGroupCustomItemProvider"]},{"anchor":"Layout-updates","title":"Layout updates","identifiers":["doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem","doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSectionVisibleItemsInvalidationHandler","doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem","doc://com.apple.uikit/documentation/UIKit/UICollectionViewFocusUpdateContext","doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayoutInvalidationContext"]},{"anchor":"Manual-layouts","title":"Manual layouts","identifiers":["doc://com.apple.uikit/documentation/UIKit/customizing-collection-view-layouts","doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout","doc://com.apple.uikit/documentation/UIKit/UICollectionViewFlowLayout","doc://com.apple.uikit/documentation/UIKit/UICollectionViewTransitionLayout","doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayoutAttributes","doc://com.apple.uikit/documentation/UIKit/UICollectionViewFlowLayoutInvalidationContext"]},{"anchor":"Data","title":"Data","identifiers":["doc://com.apple.uikit/documentation/UIKit/NSDiffableDataSourceSnapshot-swift.struct"]}],"references":{"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutGroupCustomItemProvider":{"abstract":[{"type":"text","text":"A closure that creates and returns each of the custom group’s items."}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutGroupCustomItemProvider","title":"NSCollectionLayoutGroupCustomItemProvider","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSCollectionLayoutGroupCustomItemProvider"}],"navigatorTitle":[{"kind":"identifier","text":"NSCollectionLayoutGroupCustomItemProvider"}],"role":"symbol","type":"topic","url":"/documentation/uikit/nscollectionlayoutgroupcustomitemprovider"},"doc://com.apple.uikit/documentation/UIKit/customizing-collection-view-layouts":{"url":"/documentation/uikit/customizing-collection-view-layouts","abstract":[{"text":"Customize a view layout by changing the size of cells in the flow or implementing a mosaic style.","type":"text"}],"type":"topic","role":"sampleCode","identifier":"doc://com.apple.uikit/documentation/UIKit/customizing-collection-view-layouts","title":"Customizing collection view layouts","kind":"article"},"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutGroupCustomItem":{"abstract":[{"type":"text","text":"An item used in a group with a custom layout arrangement."}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutGroupCustomItem","title":"NSCollectionLayoutGroupCustomItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSCollectionLayoutGroupCustomItem"}],"navigatorTitle":[{"kind":"identifier","text":"NSCollectionLayoutGroupCustomItem"}],"role":"symbol","type":"topic","url":"/documentation/uikit/nscollectionlayoutgroupcustomitem"},"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutDimension":{"navigatorTitle":[{"text":"NSCollectionLayoutDimension","kind":"identifier"}],"title":"NSCollectionLayoutDimension","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutDimension","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionLayoutDimension","kind":"identifier"}],"abstract":[{"text":"An individual dimension representing an item’s width or height in a collection view.","type":"text"}],"url":"/documentation/uikit/nscollectionlayoutdimension","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionLayoutVisibleItem","kind":"identifier"}],"url":"/documentation/uikit/nscollectionlayoutvisibleitem","abstract":[{"text":"An item that’s currently visible within the bounds of a section.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem","kind":"symbol","role":"symbol","title":"NSCollectionLayoutVisibleItem","navigatorTitle":[{"text":"NSCollectionLayoutVisibleItem","kind":"identifier"}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewTransitionLayout":{"url":"/documentation/uikit/uicollectionviewtransitionlayout","abstract":[{"text":"A special type of layout object that lets you implement behaviors when changing from one layout to another in your collection view.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewTransitionLayout","title":"UICollectionViewTransitionLayout","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UICollectionViewTransitionLayout","kind":"identifier"}],"navigatorTitle":[{"text":"UICollectionViewTransitionLayout","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/collection-views":{"role":"collectionGroup","title":"Collection views","kind":"article","abstract":[{"text":"Display nested views using a configurable and highly customizable layout.","type":"text"}],"url":"/documentation/uikit/collection-views","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/collection-views"},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayoutAttributes":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"UICollectionViewLayoutAttributes"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UICollectionViewLayoutAttributes"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayoutAttributes","abstract":[{"text":"A layout object that manages the layout-related attributes for a given item in a collection view.","type":"text"}],"url":"/documentation/uikit/uicollectionviewlayoutattributes","title":"UICollectionViewLayoutAttributes"},"doc://com.apple.uikit/documentation/UIKit/views-and-controls":{"url":"/documentation/uikit/views-and-controls","title":"Views and controls","abstract":[{"text":"Present your content onscreen and define the interactions allowed with that content.","type":"text"}],"type":"topic","role":"collectionGroup","kind":"article","identifier":"doc://com.apple.uikit/documentation/UIKit/views-and-controls"},"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutEnvironment":{"abstract":[{"type":"text","text":"A protocol used to provide information about the layout’s container and environment traits, such as size classes and display scale factor."}],"url":"/documentation/uikit/nscollectionlayoutenvironment","identifier":"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutEnvironment","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionLayoutEnvironment","kind":"identifier"}],"role":"symbol","title":"NSCollectionLayoutEnvironment","type":"topic","kind":"symbol","navigatorTitle":[{"text":"NSCollectionLayoutEnvironment","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutDecorationItem":{"abstract":[{"type":"text","text":"An object used to add a background to a section of a collection view."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutDecorationItem","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"NSCollectionLayoutDecorationItem","kind":"identifier"}],"url":"/documentation/uikit/nscollectionlayoutdecorationitem","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionLayoutDecorationItem","kind":"identifier"}],"title":"NSCollectionLayoutDecorationItem","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingBehavior":{"role":"symbol","type":"topic","url":"/documentation/uikit/uicollectionlayoutsectionorthogonalscrollingbehavior","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UICollectionLayoutSectionOrthogonalScrollingBehavior"}],"kind":"symbol","title":"UICollectionLayoutSectionOrthogonalScrollingBehavior","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingBehavior","abstract":[{"type":"text","text":"The scrolling behavior of the layout’s sections in relation to the main layout axis."}],"navigatorTitle":[{"text":"UICollectionLayoutSectionOrthogonalScrollingBehavior","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/NSDiffableDataSourceSnapshotReference":{"abstract":[{"text":"A representation of the state of the data in a view at a specific point in time.","type":"text"}],"type":"topic","title":"NSDiffableDataSourceSnapshotReference","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSDiffableDataSourceSnapshotReference"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSDiffableDataSourceSnapshotReference"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/NSDiffableDataSourceSnapshotReference","url":"/documentation/uikit/nsdiffabledatasourcesnapshotreference","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewFocusUpdateContext":{"abstract":[{"text":"A context object that stores information specific to a focus update in a collection view.","type":"text"}],"url":"/documentation/uikit/uicollectionviewfocusupdatecontext","navigatorTitle":[{"kind":"identifier","text":"UICollectionViewFocusUpdateContext"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UICollectionViewFocusUpdateContext"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewFocusUpdateContext","title":"UICollectionViewFocusUpdateContext","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSectionVisibleItemsInvalidationHandler":{"type":"topic","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSectionVisibleItemsInvalidationHandler","kind":"symbol","title":"NSCollectionLayoutSectionVisibleItemsInvalidationHandler","abstract":[{"text":"A closure called before each layout cycle to allow modification of items in a section immediately before they’re displayed.","type":"text"}],"url":"/documentation/uikit/nscollectionlayoutsectionvisibleitemsinvalidationhandler","navigatorTitle":[{"text":"NSCollectionLayoutSectionVisibleItemsInvalidationHandler","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionLayoutSectionVisibleItemsInvalidationHandler","kind":"identifier"}]},"https://developer.apple.com/design/human-interface-guidelines/ios/views/collections/":{"type":"link","identifier":"https://developer.apple.com/design/human-interface-guidelines/ios/views/collections/","titleInlineContent":[{"text":"Human Interface Guidelines","type":"text"}],"url":"https://developer.apple.com/design/human-interface-guidelines/ios/views/collections/","title":"Human Interface Guidelines"},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCompositionalLayoutSectionProvider":{"url":"/documentation/uikit/uicollectionviewcompositionallayoutsectionprovider","navigatorTitle":[{"text":"UICollectionViewCompositionalLayoutSectionProvider","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCompositionalLayoutSectionProvider","role":"symbol","kind":"symbol","type":"topic","title":"UICollectionViewCompositionalLayoutSectionProvider","abstract":[{"text":"A closure that creates and returns each of the layout’s sections.","type":"text"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UICollectionViewCompositionalLayoutSectionProvider","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewFlowLayoutInvalidationContext":{"role":"symbol","kind":"symbol","url":"/documentation/uikit/uicollectionviewflowlayoutinvalidationcontext","title":"UICollectionViewFlowLayoutInvalidationContext","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewFlowLayoutInvalidationContext","navigatorTitle":[{"kind":"identifier","text":"UICollectionViewFlowLayoutInvalidationContext"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UICollectionViewFlowLayoutInvalidationContext"}],"abstract":[{"text":"A set of properties for determining whether to recompute the size of items or their position in the layout.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewFlowLayout":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewFlowLayout","title":"UICollectionViewFlowLayout","abstract":[{"type":"text","text":"A layout object that organizes items into a grid with optional header and footer views for each section."}],"url":"/documentation/uikit/uicollectionviewflowlayout","navigatorTitle":[{"text":"UICollectionViewFlowLayout","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UICollectionViewFlowLayout","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutBoundarySupplementaryItem":{"type":"topic","title":"NSCollectionLayoutBoundarySupplementaryItem","navigatorTitle":[{"text":"NSCollectionLayoutBoundarySupplementaryItem","kind":"identifier"}],"url":"/documentation/uikit/nscollectionlayoutboundarysupplementaryitem","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionLayoutBoundarySupplementaryItem","kind":"identifier"}],"abstract":[{"text":"An object used to add headers or footers to a collection view.","type":"text"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutBoundarySupplementaryItem","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UICollectionViewLayout"}],"navigatorTitle":[{"kind":"identifier","text":"UICollectionViewLayout"}],"abstract":[{"type":"text","text":"An abstract base class for generating layout information for a collection view."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout","url":"/documentation/uikit/uicollectionviewlayout","type":"topic","title":"UICollectionViewLayout","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/implementing-modern-collection-views":{"role":"sampleCode","abstract":[{"text":"Bring compositional layouts to your app and simplify updating your user interface with diffable data sources.","type":"text"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/implementing-modern-collection-views","title":"Implementing modern collection views","url":"/documentation/uikit/implementing-modern-collection-views","kind":"article"},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCompositionalLayout":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCompositionalLayout","url":"/documentation/uikit/uicollectionviewcompositionallayout","kind":"symbol","title":"UICollectionViewCompositionalLayout","type":"topic","abstract":[{"type":"text","text":"A layout object that lets you combine items in highly adaptive and flexible visual arrangements."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UICollectionViewCompositionalLayout","kind":"identifier"}],"navigatorTitle":[{"text":"UICollectionViewCompositionalLayout","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutEdgeSpacing":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSCollectionLayoutEdgeSpacing"}],"abstract":[{"text":"An object that defines the space around the edges of items in a collection view.","type":"text"}],"title":"NSCollectionLayoutEdgeSpacing","navigatorTitle":[{"kind":"identifier","text":"NSCollectionLayoutEdgeSpacing"}],"url":"/documentation/uikit/nscollectionlayoutedgespacing","kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutEdgeSpacing"},"doc://com.apple.uikit/documentation/UIKit/NSDiffableDataSourceSnapshot-swift.struct":{"role":"symbol","title":"NSDiffableDataSourceSnapshot","navigatorTitle":[{"text":"NSDiffableDataSourceSnapshot","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSDiffableDataSourceSnapshot","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"A representation of the state of the data in a view at a specific point in time.","type":"text"}],"url":"/documentation/uikit/nsdiffabledatasourcesnapshot-swift.struct","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/NSDiffableDataSourceSnapshot-swift.struct"},"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutItem":{"type":"topic","role":"symbol","title":"NSCollectionLayoutItem","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionLayoutItem","kind":"identifier"}],"navigatorTitle":[{"text":"NSCollectionLayoutItem","kind":"identifier"}],"abstract":[{"text":"The most basic component of a collection view’s layout.","type":"text"}],"url":"/documentation/uikit/nscollectionlayoutitem","identifier":"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutItem","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSpacing":{"kind":"symbol","title":"NSCollectionLayoutSpacing","abstract":[{"type":"text","text":"An object that defines the space between or around items in a collection view."}],"url":"/documentation/uikit/nscollectionlayoutspacing","identifier":"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSpacing","type":"topic","navigatorTitle":[{"text":"NSCollectionLayoutSpacing","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionLayoutSpacing","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSupplementaryItem":{"role":"symbol","abstract":[{"type":"text","text":"An object used to add an extra visual decoration to an item in a collection view."}],"navigatorTitle":[{"text":"NSCollectionLayoutSupplementaryItem","kind":"identifier"}],"type":"topic","url":"/documentation/uikit/nscollectionlayoutsupplementaryitem","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSupplementaryItem","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NSCollectionLayoutSupplementaryItem","kind":"identifier"}],"title":"NSCollectionLayoutSupplementaryItem"},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayoutInvalidationContext":{"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayoutInvalidationContext","type":"topic","url":"/documentation/uikit/uicollectionviewlayoutinvalidationcontext","title":"UICollectionViewLayoutInvalidationContext","role":"symbol","navigatorTitle":[{"text":"UICollectionViewLayoutInvalidationContext","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UICollectionViewLayoutInvalidationContext","kind":"identifier"}],"abstract":[{"type":"text","text":"A context object that declares which parts of your layout need to be updated when the layout is invalidated."}]},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCompositionalLayoutConfiguration":{"type":"topic","title":"UICollectionViewCompositionalLayoutConfiguration","navigatorTitle":[{"text":"UICollectionViewCompositionalLayoutConfiguration","kind":"identifier"}],"url":"/documentation/uikit/uicollectionviewcompositionallayoutconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UICollectionViewCompositionalLayoutConfiguration","kind":"identifier"}],"abstract":[{"text":"An object that defines scroll direction, section spacing, and headers or footers for the layout.","type":"text"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCompositionalLayoutConfiguration","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutAnchor":{"title":"NSCollectionLayoutAnchor","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionLayoutAnchor","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"NSCollectionLayoutAnchor","kind":"identifier"}],"abstract":[{"type":"text","text":"An object that defines how to attach a supplementary item to an item in a collection view."}],"url":"/documentation/uikit/nscollectionlayoutanchor","identifier":"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutAnchor"},"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSize":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSCollectionLayoutSize"}],"type":"topic","title":"NSCollectionLayoutSize","url":"/documentation/uikit/nscollectionlayoutsize","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSize","navigatorTitle":[{"kind":"identifier","text":"NSCollectionLayoutSize"}],"abstract":[{"type":"text","text":"The width and the height of an item in a collection view."}],"role":"symbol"},"media-3568662":{"type":"image","identifier":"media-3568662","variants":[{"url":"https://docs-assets.developer.apple.com/published/1bcae7456df55cf8e3407bb9324c0d33/media-3568662@2x.png","traits":["2x","light"]},{"url":"https://docs-assets.developer.apple.com/published/981f0b534b7f4153042bfa97691a1f9b/media-3568662~dark@2x.png","traits":["2x","dark"]}],"alt":"Schematic representation of the App Store app on iOS, showing a collection view with a compositional layout. The layout is composed of two horizontally-scrolling sections that have different layouts. The top section shows one group with one item visible onscreen, with other groups peeking in from the sides of the screen. The bottom section shows one group that’s a column of three cells, each of those cells being an item."},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UICollectionViewUpdateItem"}],"kind":"symbol","title":"UICollectionViewUpdateItem","role":"symbol","abstract":[{"type":"text","text":"An object that describes a single change to make to an item in a collection view."}],"navigatorTitle":[{"kind":"identifier","text":"UICollectionViewUpdateItem"}],"type":"topic","url":"/documentation/uikit/uicollectionviewupdateitem"},"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSection":{"navigatorTitle":[{"kind":"identifier","text":"NSCollectionLayoutSection"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSection","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSCollectionLayoutSection"}],"url":"/documentation/uikit/nscollectionlayoutsection","abstract":[{"type":"text","text":"A container that combines a set of groups into distinct visual groupings."}],"title":"NSCollectionLayoutSection","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutGroup":{"role":"symbol","abstract":[{"text":"A container for a set of items that lays out the items along a path.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"NSCollectionLayoutGroup"}],"type":"topic","url":"/documentation/uikit/nscollectionlayoutgroup","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutGroup","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSCollectionLayoutGroup"}],"title":"NSCollectionLayoutGroup"},"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutContainer":{"title":"NSCollectionLayoutContainer","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSCollectionLayoutContainer"}],"navigatorTitle":[{"kind":"identifier","text":"NSCollectionLayoutContainer"}],"role":"symbol","type":"topic","url":"/documentation/uikit/nscollectionlayoutcontainer","identifier":"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutContainer","kind":"symbol","abstract":[{"text":"A protocol used to provide information about the size and content insets of a layout’s container.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"title":"Essentials","anchor":"Essentials","identifiers":["doc://com.apple.uikit/documentation/UIKit/implementing-modern-collection-views","doc://com.apple.uikit/documentation/UIKit/UICollectionViewCompositionalLayout"]},{"title":"Components","anchor":"Components","identifiers":["doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutItem","doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutGroup","doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSection"]},{"title":"Size and spacing","anchor":"Size-and-spacing","identifiers":["doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutDimension","doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSize","doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSpacing","doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutEdgeSpacing","doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutContainer"]},{"title":"Configuration","anchor":"Configuration","identifiers":["doc://com.apple.uikit/documentation/UIKit/UICollectionViewCompositionalLayoutConfiguration","doc://com.apple.uikit/documentation/UIKit/UICollectionViewCompositionalLayoutSectionProvider","doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutEnvironment"]},{"title":"Interaction","anchor":"Interaction","identifiers":["doc://com.apple.uikit/documentation/UIKit/UICollectionLayoutSectionOrthogonalScrollingBehavior"]},{"anchor":"Appearance","title":"Appearance","identifiers":["doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutAnchor","doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSupplementaryItem","doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutBoundarySupplementaryItem","doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutDecorationItem"]},{"anchor":"Advanced-layouts","title":"Advanced layouts","identifiers":["doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutGroupCustomItem","doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutGroupCustomItemProvider"]},{"anchor":"Layout-updates","title":"Layout updates","identifiers":["doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem","doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSectionVisibleItemsInvalidationHandler","doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem","doc://com.apple.uikit/documentation/UIKit/UICollectionViewFocusUpdateContext","doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayoutInvalidationContext"]},{"anchor":"Manual-layouts","title":"Manual layouts","identifiers":["doc://com.apple.uikit/documentation/UIKit/customizing-collection-view-layouts","doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayout","doc://com.apple.uikit/documentation/UIKit/UICollectionViewFlowLayout","doc://com.apple.uikit/documentation/UIKit/UICollectionViewTransitionLayout","doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayoutAttributes","doc://com.apple.uikit/documentation/UIKit/UICollectionViewFlowLayoutInvalidationContext"]},{"anchor":"Data","title":"Data","identifiers":["doc://com.apple.uikit/documentation/UIKit/NSDiffableDataSourceSnapshotReference"]}],"op":"replace","path":"/topicSections"},{"value":[{"title":"Layouts","anchor":"Layouts","identifiers":["doc://com.apple.uikit/documentation/UIKit/implementing-modern-collection-views"],"generated":true}],"op":"replace","path":"/seeAlsoSections"},{"value":"NSCollectionLayoutGroupCustomItemProvider","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutGroupCustomItemProvider/title"},{"value":[{"kind":"identifier","text":"NSCollectionLayoutGroupCustomItemProvider"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutGroupCustomItemProvider/fragments"},{"value":[{"text":"NSCollectionLayoutGroupCustomItemProvider","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutGroupCustomItemProvider/navigatorTitle"},{"value":"NSCollectionLayoutGroupCustomItem","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutGroupCustomItem/title"},{"value":[{"text":"NSCollectionLayoutGroupCustomItem","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutGroupCustomItem/fragments"},{"value":[{"text":"NSCollectionLayoutGroupCustomItem","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutGroupCustomItem/navigatorTitle"},{"value":"NSCollectionLayoutDimension","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutDimension/title"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutDimension/fragments","op":"replace","value":[{"kind":"identifier","text":"NSCollectionLayoutDimension"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutDimension/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSCollectionLayoutDimension"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutVisibleItem/title","op":"replace","value":"NSCollectionLayoutVisibleItem"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutVisibleItem/fragments","op":"replace","value":[{"text":"NSCollectionLayoutVisibleItem","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutVisibleItem/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSCollectionLayoutVisibleItem"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewTransitionLayout/title","op":"replace","value":"UICollectionViewTransitionLayout"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewTransitionLayout/fragments","op":"replace","value":[{"kind":"identifier","text":"UICollectionViewTransitionLayout"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewTransitionLayout/navigatorTitle","op":"replace","value":[{"text":"UICollectionViewTransitionLayout","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayoutAttributes/title","op":"replace","value":"UICollectionViewLayoutAttributes"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayoutAttributes/fragments","op":"replace","value":[{"text":"UICollectionViewLayoutAttributes","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayoutAttributes/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UICollectionViewLayoutAttributes"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutEnvironment/title","op":"replace","value":"NSCollectionLayoutEnvironment"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutEnvironment/fragments","op":"replace","value":[{"kind":"identifier","text":"NSCollectionLayoutEnvironment"}]},{"op":"replace","value":[{"text":"NSCollectionLayoutEnvironment","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutEnvironment/navigatorTitle"},{"op":"replace","value":"NSCollectionLayoutDecorationItem","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutDecorationItem/title"},{"op":"replace","value":[{"text":"NSCollectionLayoutDecorationItem","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutDecorationItem/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSCollectionLayoutDecorationItem"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutDecorationItem/navigatorTitle"},{"op":"replace","value":"UICollectionLayoutSectionOrthogonalScrollingBehavior","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingBehavior/title"},{"op":"replace","value":[{"kind":"identifier","text":"UICollectionLayoutSectionOrthogonalScrollingBehavior"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingBehavior/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UICollectionLayoutSectionOrthogonalScrollingBehavior"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionLayoutSectionOrthogonalScrollingBehavior/navigatorTitle"},{"op":"replace","value":"NSDiffableDataSourceSnapshot","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSDiffableDataSourceSnapshotReference/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSDiffableDataSourceSnapshot"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSDiffableDataSourceSnapshotReference/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSDiffableDataSourceSnapshot"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSDiffableDataSourceSnapshotReference/navigatorTitle"},{"op":"replace","value":"UICollectionViewFocusUpdateContext","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewFocusUpdateContext/title"},{"op":"replace","value":[{"kind":"identifier","text":"UICollectionViewFocusUpdateContext"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewFocusUpdateContext/fragments"},{"op":"replace","value":[{"text":"UICollectionViewFocusUpdateContext","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewFocusUpdateContext/navigatorTitle"},{"op":"replace","value":"NSCollectionLayoutSectionVisibleItemsInvalidationHandler","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutSectionVisibleItemsInvalidationHandler/title"},{"op":"replace","value":[{"text":"NSCollectionLayoutSectionVisibleItemsInvalidationHandler","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutSectionVisibleItemsInvalidationHandler/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSCollectionLayoutSectionVisibleItemsInvalidationHandler"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutSectionVisibleItemsInvalidationHandler/navigatorTitle"},{"op":"replace","value":"UICollectionViewCompositionalLayoutSectionProvider","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCompositionalLayoutSectionProvider/title"},{"op":"replace","value":[{"text":"UICollectionViewCompositionalLayoutSectionProvider","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCompositionalLayoutSectionProvider/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UICollectionViewCompositionalLayoutSectionProvider"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCompositionalLayoutSectionProvider/navigatorTitle"},{"op":"replace","value":"UICollectionViewFlowLayoutInvalidationContext","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewFlowLayoutInvalidationContext/title"},{"op":"replace","value":[{"text":"UICollectionViewFlowLayoutInvalidationContext","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewFlowLayoutInvalidationContext/fragments"},{"op":"replace","value":[{"text":"UICollectionViewFlowLayoutInvalidationContext","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewFlowLayoutInvalidationContext/navigatorTitle"},{"op":"replace","value":"UICollectionViewFlowLayout","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewFlowLayout/title"},{"op":"replace","value":[{"kind":"identifier","text":"UICollectionViewFlowLayout"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewFlowLayout/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UICollectionViewFlowLayout"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewFlowLayout/navigatorTitle"},{"op":"replace","value":"NSCollectionLayoutBoundarySupplementaryItem","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutBoundarySupplementaryItem/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSCollectionLayoutBoundarySupplementaryItem"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutBoundarySupplementaryItem/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSCollectionLayoutBoundarySupplementaryItem"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutBoundarySupplementaryItem/navigatorTitle"},{"op":"replace","value":"UICollectionViewLayout","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayout/title"},{"op":"replace","value":[{"kind":"identifier","text":"UICollectionViewLayout"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayout/fragments"},{"op":"replace","value":[{"text":"UICollectionViewLayout","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayout/navigatorTitle"},{"op":"replace","value":"UICollectionViewCompositionalLayout","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCompositionalLayout/title"},{"op":"replace","value":[{"kind":"identifier","text":"UICollectionViewCompositionalLayout"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCompositionalLayout/fragments"},{"op":"replace","value":[{"text":"UICollectionViewCompositionalLayout","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCompositionalLayout/navigatorTitle"},{"op":"replace","value":"NSCollectionLayoutEdgeSpacing","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutEdgeSpacing/title"},{"op":"replace","value":[{"text":"NSCollectionLayoutEdgeSpacing","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutEdgeSpacing/fragments"},{"op":"replace","value":[{"text":"NSCollectionLayoutEdgeSpacing","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutEdgeSpacing/navigatorTitle"},{"op":"replace","value":"NSCollectionLayoutItem","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutItem/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSCollectionLayoutItem"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutItem/fragments"},{"op":"replace","value":[{"text":"NSCollectionLayoutItem","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutItem/navigatorTitle"},{"op":"replace","value":"NSCollectionLayoutSpacing","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutSpacing/title"},{"op":"replace","value":[{"text":"NSCollectionLayoutSpacing","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutSpacing/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSCollectionLayoutSpacing"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutSpacing/navigatorTitle"},{"op":"replace","value":"NSCollectionLayoutSupplementaryItem","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutSupplementaryItem/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSCollectionLayoutSupplementaryItem"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutSupplementaryItem/fragments"},{"op":"replace","value":[{"text":"NSCollectionLayoutSupplementaryItem","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutSupplementaryItem/navigatorTitle"},{"op":"replace","value":"UICollectionViewLayoutInvalidationContext","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayoutInvalidationContext/title"},{"op":"replace","value":[{"text":"UICollectionViewLayoutInvalidationContext","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayoutInvalidationContext/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UICollectionViewLayoutInvalidationContext"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayoutInvalidationContext/navigatorTitle"},{"op":"replace","value":"UICollectionViewCompositionalLayoutConfiguration","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCompositionalLayoutConfiguration/title"},{"op":"replace","value":[{"kind":"identifier","text":"UICollectionViewCompositionalLayoutConfiguration"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCompositionalLayoutConfiguration/fragments"},{"op":"replace","value":[{"text":"UICollectionViewCompositionalLayoutConfiguration","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCompositionalLayoutConfiguration/navigatorTitle"},{"op":"replace","value":"NSCollectionLayoutAnchor","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutAnchor/title"},{"op":"replace","value":[{"text":"NSCollectionLayoutAnchor","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutAnchor/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSCollectionLayoutAnchor"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutAnchor/navigatorTitle"},{"op":"replace","value":"NSCollectionLayoutSize","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutSize/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSCollectionLayoutSize"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutSize/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSCollectionLayoutSize"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutSize/navigatorTitle"},{"op":"replace","value":"UICollectionViewUpdateItem","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewUpdateItem/title"},{"op":"replace","value":[{"kind":"identifier","text":"UICollectionViewUpdateItem"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewUpdateItem/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UICollectionViewUpdateItem"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewUpdateItem/navigatorTitle"},{"op":"replace","value":"NSCollectionLayoutSection","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutSection/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSCollectionLayoutSection"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutSection/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSCollectionLayoutSection"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutSection/navigatorTitle"},{"op":"replace","value":"NSCollectionLayoutGroup","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutGroup/title"},{"op":"replace","value":[{"text":"NSCollectionLayoutGroup","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutGroup/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSCollectionLayoutGroup"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutGroup/navigatorTitle"},{"op":"replace","value":"NSCollectionLayoutContainer","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutContainer/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSCollectionLayoutContainer"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutContainer/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSCollectionLayoutContainer"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutContainer/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}