{
  "abstract": [
    {
      "text": "Adopt drag interaction APIs to provide items for dragging.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/drag-and-drop"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/making-a-view-into-a-drag-source"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "11.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "11.0",
        "name": "iPadOS"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Making a view into a drag source"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "By implementing a drag interaction delegate (",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDragInteractionDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ") for a view, you enable that view to function as a drag source in your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextView",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableView",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", and ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionView",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " classes each provide their own, specialized support for creating drag items. See these classes for more information.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Enable-a-view-as-a-drag-source",
          "level": 3,
          "text": "Enable a view as a drag source",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Any instance or subclass of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " can act as a drag source. Your first steps to make this happen are:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create a drag interaction (a ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDragInteraction",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " instance).",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Specify the drag interaction’s delegate (an object that conforms to the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDragInteractionDelegate",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " protocol).",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Add the interaction to the view’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/interactions",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Here’s how to do this using a custom helper method, which you’d typically call within a view controller’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/viewDidLoad()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func customEnableDragging(on view: UIView, dragInteractionDelegate: UIDragInteractionDelegate) {",
            "    let dragInteraction = UIDragInteraction(delegate: dragInteractionDelegate)",
            "    view.addInteraction(dragInteraction)",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Create-a-drag-item",
          "level": 3,
          "text": "Create a drag item",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A drag item encapsulates a source app’s promises for providing a variety of data representations for one model object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To create a drag item, implement the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDragInteractionDelegate/dragInteraction(_:itemsForBeginning:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method in your drag interaction delegate, as shown here in a minimal form:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func dragInteraction(_ interaction: UIDragInteraction, itemsForBeginning session: UIDragSession) -> [UIDragItem] {",
            "    // Cast to NSString is required for NSItemProviderWriting support.",
            "    let stringItemProvider = NSItemProvider(object: \"Hello World\" as NSString)",
            "    return [",
            "        UIDragItem(itemProvider: stringItemProvider)",
            "    ]",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The cast from the Swift ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/Swift/String",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " type to the Foundation ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " class, in the code snippet above, is required because model objects for drag and drop must support the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/foundation/nsitemproviderwriting",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " protocol.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "This implementation uses the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsitemprovider/2888328-init",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " convenience initializer. When you instantiate a drag item, pass an object in your app’s native representation, or in the highest-fidelity representation you support. In general, ensure that the first element in the item provider’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsitemprovider/1403923-registeredtypeidentifiers",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " array represents the highest-fidelity data your drag interaction delegate can deliver.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To add more data representations to a drag item, as you typically would in your app, add them in fidelity order, from highest to lowest. When adding representations, you have choices:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The best option for adding multiple data representations to a drag item, in many cases, is to adopt the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/nsitemproviderwriting",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " protocol in your model class. Using this protocol, you place the code for providing multiple data representations within the model class.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "You can use the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/nsitemprovider/2888321-registerobject",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method, or related methods, from the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/nsitemprovider",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " class, to explicitly register data representations.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Understand-a-drag-source-in-context",
          "level": 3,
          "text": "Understand a drag source in context",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDragInteractionDelegate/dragInteraction(_:itemsForBeginning:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol method, your source app responds to a request from the system. This request is itself triggered by the user starting to drag an item in your app’s UI. The conversation between your app and the system proceeds as shown here:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2903752",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The figure above depicts the steps for constructing a drag item, in context:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The user initiates a drag activity with a long press on a view in your app, followed by moving their finger while still touching the screen. The system instantiates a drag session (an object that conforms to the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDragSession",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " protocol, not shown in the figure) for managing the drag activity.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The system calls the drag interaction delegate’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDragInteractionDelegate/dragInteraction(_:itemsForBeginning:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " protocol method. Your delegate returns one or more drag items.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Finally, the system populates the drag session with your drag items, ready for the user to move the drag session to a destination.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/Swift/String": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Swift/String",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    },
    "doc://com.apple.documentation/documentation/foundation/nsitemprovider": {
      "abstract": [
        {
          "text": "An item provider for conveying data or a file between processes during drag-and-drop or copy-and-paste activities, or from a host app to an app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSItemProvider"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsitemprovider",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSItemProvider",
      "type": "topic",
      "url": "/documentation/foundation/nsitemprovider"
    },
    "doc://com.apple.documentation/documentation/foundation/nsitemprovider/1403923-registeredtypeidentifiers": {
      "abstract": [
        {
          "text": "Returns the array of type identifiers for the item provider, in the same order they were registered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "registeredTypeIdentifiers"
        },
        {
          "kind": "text",
          "text": ": [String]"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsitemprovider/1403923-registeredtypeidentifiers",
      "kind": "symbol",
      "role": "symbol",
      "title": "registeredTypeIdentifiers",
      "type": "topic",
      "url": "/documentation/foundation/nsitemprovider/1403923-registeredtypeidentifiers"
    },
    "doc://com.apple.documentation/documentation/foundation/nsitemprovider/2888321-registerobject": {
      "abstract": [
        {
          "text": "Adds representations of a specified object to an item provider, based on the object’s implementation of the item provider writing protocol, and adhering to a visibility specification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "registerObject"
        },
        {
          "kind": "text",
          "text": "(any NSItemProviderWriting, "
        },
        {
          "kind": "identifier",
          "text": "visibility"
        },
        {
          "kind": "text",
          "text": ": NSItemProviderRepresentationVisibility)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsitemprovider/2888321-registerobject",
      "kind": "symbol",
      "role": "symbol",
      "title": "registerObject(_:visibility:)",
      "type": "topic",
      "url": "/documentation/foundation/nsitemprovider/2888321-registerobject"
    },
    "doc://com.apple.documentation/documentation/foundation/nsitemprovider/2888328-init": {
      "abstract": [
        {
          "text": "Creates a new item provider, employing a specified object’s type identifiers to specify the data representations eligible for the provider to load.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "object"
        },
        {
          "kind": "text",
          "text": ": any NSItemProviderWriting)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsitemprovider/2888328-init",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(object:)",
      "type": "topic",
      "url": "/documentation/foundation/nsitemprovider/2888328-init"
    },
    "doc://com.apple.documentation/documentation/foundation/nsitemproviderwriting": {
      "abstract": [
        {
          "text": "The protocol for implementing a class to allow an item provider to retrieve data from an instance of the class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSItemProviderWriting"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsitemproviderwriting",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSItemProviderWriting",
      "type": "topic",
      "url": "/documentation/foundation/nsitemproviderwriting"
    },
    "doc://com.apple.documentation/documentation/foundation/nsstring": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionView": {
      "abstract": [
        {
          "text": "An object that manages an ordered collection of data items and presents them using customizable layouts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionView"
        }
      ],
      "role": "symbol",
      "title": "UICollectionView",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDragInteraction": {
      "abstract": [
        {
          "text": "An interaction to enable dragging of items from a view, employing a delegate to provide drag items and to respond to calls from the drag session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDragInteraction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDragInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDragInteraction"
        }
      ],
      "role": "symbol",
      "title": "UIDragInteraction",
      "type": "topic",
      "url": "/documentation/uikit/uidraginteraction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDragInteractionDelegate": {
      "abstract": [
        {
          "text": "The interface for configuring and controlling a drag interaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDragInteractionDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDragInteractionDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDragInteractionDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIDragInteractionDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uidraginteractiondelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDragInteractionDelegate/dragInteraction(_:itemsForBeginning:)": {
      "abstract": [
        {
          "text": "Asks the delegate for the array of drag items for an impending drag interaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dragInteraction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDragInteraction",
          "text": "UIDragInteraction"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "itemsForBeginning"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDragSession",
          "text": "UIDragSession"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDragItem",
          "text": "UIDragItem"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDragInteractionDelegate/dragInteraction(_:itemsForBeginning:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dragInteraction:itemsForBeginningSession:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "dragInteraction(_:itemsForBeginning:)",
      "type": "topic",
      "url": "/documentation/uikit/uidraginteractiondelegate/draginteraction(_:itemsforbeginning:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDragSession": {
      "abstract": [
        {
          "text": "The interface for configuring a drag session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDragSession"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDragSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDragSession"
        }
      ],
      "role": "symbol",
      "title": "UIDragSession",
      "type": "topic",
      "url": "/documentation/uikit/uidragsession"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableView": {
      "abstract": [
        {
          "text": "A view that presents data using rows in a single column.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITableView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableView"
        }
      ],
      "role": "symbol",
      "title": "UITableView",
      "type": "topic",
      "url": "/documentation/uikit/uitableview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextView": {
      "abstract": [
        {
          "text": "A scrollable, multiline text region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextView"
        }
      ],
      "role": "symbol",
      "title": "UITextView",
      "type": "topic",
      "url": "/documentation/uikit/uitextview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView": {
      "abstract": [
        {
          "text": "An object that manages the content for a rectangular area on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIView"
        }
      ],
      "role": "symbol",
      "title": "UIView",
      "type": "topic",
      "url": "/documentation/uikit/uiview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/interactions": {
      "abstract": [
        {
          "text": "The array of interactions for the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interactions"
        },
        {
          "kind": "text",
          "text": ": [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIInteraction",
          "text": "UIInteraction"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/interactions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "interactions"
        }
      ],
      "role": "symbol",
      "title": "interactions",
      "type": "topic",
      "url": "/documentation/uikit/uiview/interactions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/viewDidLoad()": {
      "abstract": [
        {
          "text": "Called after the controller’s view is loaded into memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "viewDidLoad"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/viewDidLoad()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "viewDidLoad"
        }
      ],
      "role": "symbol",
      "title": "viewDidLoad()",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/viewdidload()"
    },
    "doc://com.apple.uikit/documentation/UIKit/adopting-drag-and-drop-in-a-custom-view": {
      "abstract": [
        {
          "text": "Demonstrates how to enable drag and drop for a ",
          "type": "text"
        },
        {
          "code": "UIImageView",
          "type": "codeVoice"
        },
        {
          "text": " instance.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/adopting-drag-and-drop-in-a-custom-view",
      "kind": "article",
      "role": "sampleCode",
      "title": "Adopting drag and drop in a custom view",
      "type": "topic",
      "url": "/documentation/uikit/adopting-drag-and-drop-in-a-custom-view"
    },
    "doc://com.apple.uikit/documentation/UIKit/adopting-drag-and-drop-in-a-table-view": {
      "abstract": [
        {
          "text": "Demonstrates how to enable and implement drag and drop for a table view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/adopting-drag-and-drop-in-a-table-view",
      "kind": "article",
      "role": "sampleCode",
      "title": "Adopting drag and drop in a table view",
      "type": "topic",
      "url": "/documentation/uikit/adopting-drag-and-drop-in-a-table-view"
    },
    "doc://com.apple.uikit/documentation/UIKit/drag-and-drop": {
      "abstract": [
        {
          "text": "Bring drag and drop to your app by using interaction APIs with your views.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/drag-and-drop",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Drag and drop",
      "type": "topic",
      "url": "/documentation/uikit/drag-and-drop"
    },
    "doc://com.apple.uikit/documentation/UIKit/making-a-view-into-a-drop-destination": {
      "abstract": [
        {
          "text": "Adopt drop interaction APIs to selectively consume dragged content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/making-a-view-into-a-drop-destination",
      "kind": "article",
      "role": "article",
      "title": "Making a view into a drop destination",
      "type": "topic",
      "url": "/documentation/uikit/making-a-view-into-a-drop-destination"
    },
    "doc://com.apple.uikit/documentation/UIKit/understanding-a-drag-item-as-a-promise": {
      "abstract": [
        {
          "text": "Use drag items to convey data representation promises between a source app and a destination app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/understanding-a-drag-item-as-a-promise",
      "kind": "article",
      "role": "article",
      "title": "Understanding a drag item as a promise",
      "type": "topic",
      "url": "/documentation/uikit/understanding-a-drag-item-as-a-promise"
    },
    "media-2903752": {
      "alt": "APIs for providing drag items from a drag source",
      "identifier": "media-2903752",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/ef04a983c2d83148c7e1929bce5ea101/media-2903752@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/understanding-a-drag-item-as-a-promise",
        "doc://com.apple.uikit/documentation/UIKit/making-a-view-into-a-drop-destination",
        "doc://com.apple.uikit/documentation/UIKit/adopting-drag-and-drop-in-a-custom-view",
        "doc://com.apple.uikit/documentation/UIKit/adopting-drag-and-drop-in-a-table-view"
      ],
      "title": "Essentials"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/understanding-a-drag-item-as-a-promise",
                "doc://com.apple.uikit/documentation/UIKit/making-a-view-into-a-drop-destination",
                "doc://com.apple.uikit/documentation/UIKit/adopting-drag-and-drop-in-a-custom-view",
                "doc://com.apple.uikit/documentation/UIKit/adopting-drag-and-drop-in-a-table-view"
              ],
              "title": "Essentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragInteraction/title",
          "value": "UIDragInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDragInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDragInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsitemprovider~12888328-init/title",
          "value": "initWithObject:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragInteractionDelegate/title",
          "value": "UIDragInteractionDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragInteractionDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDragInteractionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragInteractionDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDragInteractionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragSession/title",
          "value": "UIDragSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDragSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDragSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsstring/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsitemprovider~12888321-registerobject/title",
          "value": "registerObject:visibility:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextView/title",
          "value": "UITextView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView/title",
          "value": "UICollectionView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView/title",
          "value": "UITableView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1interactions/title",
          "value": "interactions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1interactions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "interactions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/title",
          "value": "UIView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1viewDidLoad()/title",
          "value": "viewDidLoad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1viewDidLoad()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "viewDidLoad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragInteractionDelegate~1dragInteraction(_:itemsForBeginning:)/title",
          "value": "dragInteraction:itemsForBeginningSession:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragInteractionDelegate~1dragInteraction(_:itemsForBeginning:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dragInteraction:itemsForBeginningSession:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/making-a-view-into-a-drag-source"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/making-a-view-into-a-drag-source"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
