{
  "abstract": [
    {
      "text": "Adopt drop interaction APIs to selectively consume dragged content.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/drag-and-drop"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/making-a-view-into-a-drop-destination"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "11.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "11.0",
        "name": "iPadOS"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Making a view into a drop destination"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "By implementing a drop interaction delegate (",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ") for a view, you enable that view to accept dropped items.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextView",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableView",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", and ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionView",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " classes each provide their own, specialized support for consuming drag items. See these classes for more information.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Enable-a-view-as-a-drop-destination",
          "level": 3,
          "text": "Enable a view as a drop destination",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Any instance or subclass of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " can act as a drop destination. Your first steps to make this happen are:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create a drop interaction (a ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropInteraction",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " instance).",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Specify the drop interaction’s delegate (an object that conforms to the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " protocol).",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Add the interaction to the view’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/interactions",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Here’s how to do this:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func customEnableDropping(on view: UIView, dropInteractionDelegate: UIDropInteractionDelegate) {",
            "    let dropInteraction = UIDropInteraction(delegate: dropInteractionDelegate)",
            "    view.addInteraction(dropInteraction)",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Consider-accepting-the-drag-items",
          "level": 3,
          "text": "Consider accepting the drag items",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When the user moves the touch point of a drag session over a drop destination, you can immediately refuse it, or you can tell the system to continue its conversation with your delegate object. Provide your response as follows:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func dropInteraction(_ interaction: UIDropInteraction, canHandle session: UIDropSession) -> Bool {",
            "    // Ensure the drop session has an object of the appropriate type",
            "    return session.canLoadObjects(ofClass: UIImage.self)",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "This example assumes that your drop destination can consume only ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects. The method implementation tests for this type in the ",
              "type": "text"
            },
            {
              "code": "return",
              "type": "codeVoice"
            },
            {
              "text": " statement. You can also use this method to refuse a drop session based on the state of your app. The ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "drop session",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " is a system-managed object that conforms to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropSession",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol. You can access a drop session for information about the items being dropped.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:canHandle:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method is your app’s only chance to respond to the system’s question about whether your app will ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "consider",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " accepting the items. For example, you might preemptively reject a drop session if it contains no data representations your app can consume, or if consuming dragged items is inappropriate given your app state. Your app’s definitive opportunity to accept or reject dropped items is in your implementation of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidUpdate:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Provide-the-required-drop-proposal",
          "level": 3,
          "text": "Provide the required drop proposal",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For a view to be eligible to accept the data from a drop session, you ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "must",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " implement the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidUpdate:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol method. In your implementation, return a drop proposal—a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropProposal",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object that specifies the drop operation type, a constant from the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropOperation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " enumeration.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Provide a drop proposal like this:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func dropInteraction(_ interaction: UIDropInteraction, sessionDidUpdate session: UIDropSession) -> UIDropProposal {",
            "        // Propose to the system to copy the item from the source app",
            "        return UIDropProposal(operation: .copy)",
            "}",
            ""
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "If your app instead opts to refuse the dropped items, return the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropOperation/cancel",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " constant.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The system calls this protocol method when the user has moved the touch point of a drag session over a drop-enabled view — as long as the view didn’t already reject the drop by returning ",
              "type": "text"
            },
            {
              "code": "false",
              "type": "codeVoice"
            },
            {
              "text": " in its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:canHandle:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method (see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/making-a-view-into-a-drop-destination#Consider-accepting-the-drag-items",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ").",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Consume-the-data-in-the-drag-items",
          "level": 3,
          "text": "Consume the data in the drag items",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The final step of the conversation between the drop interaction delegate and the system is when your app consumes the data the user has dragged from the source app. Here, your drop interaction delegate asks the drop session to load its drag items:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func dropInteraction(_ interaction: UIDropInteraction, performDrop session: UIDropSession) {",
            "    // Consume drag items (in this example, of type UIImage).",
            "    session.loadObjects(ofClass: UIImage.self) { imageItems in",
            "        let images = imageItems as! [UIImage]",
            "        self.imageView.image = images.first",
            "    }",
            "    // Perform additional UI updates as needed.",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:performDrop:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method is a destination app’s only opportunity to request representations of drag items. Receiving the items is potentially time-consuming and proceeds asynchronously. ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "Don’t",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " wait within this method to receive items; instead, return from this method quickly.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "If you don’t employ the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropSession/loadObjects(ofClass:completion:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " convenience method as shown above, which automatically employs the main thread, explicitly dispatch UI work to the main thread. For example, you can use the ",
                  "type": "text"
                },
                {
                  "code": "DispatchQueue.main.async",
                  "type": "codeVoice"
                },
                {
                  "text": " function.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Understand-a-drop-destination-in-context",
          "level": 3,
          "text": "Understand a drop destination in context",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When the touch point for a drop session moves over a view that you’ve configured as a drop destination, the system initiates a conversation with the drop interaction delegate. This conversation gives your app opportunities to accept or reject the drop, to prepare for consuming the drag items, and to update your model and UI, as shown here:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2903753",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The figure above depicts the steps for consuming a drag item, in context:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The user moves their finger onscreen so the touch point of a drag session is within a configured view in your app. The system instantiates a drop session (an object that conforms to the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropSession",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " protocol, not shown in the figure) for managing the drop activity.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The system calls the drop interaction delegate’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:canHandle:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " protocol method. Check whether your app can, and opts to, consume the drag items.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The system calls the delegate’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidEnter:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " protocol method. Prepare to consume the drag items.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The system calls the delegate’s ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidUpdate:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " protocol method. Your implementation ",
                      "type": "text"
                    },
                    {
                      "inlineContent": [
                        {
                          "text": "must",
                          "type": "text"
                        }
                      ],
                      "type": "emphasis"
                    },
                    {
                      "text": " return a ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropProposal",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " object, or the system ends the session.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If the user confirms their intent to complete the drop, the system calls the delegate’s asynchronous ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:performDrop:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " protocol method. This a destination app’s only opportunity to request representations of drag items.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionView": {
      "abstract": [
        {
          "text": "An object that manages an ordered collection of data items and presents them using customizable layouts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionView"
        }
      ],
      "role": "symbol",
      "title": "UICollectionView",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDropInteraction": {
      "abstract": [
        {
          "text": "An interaction to enable dropping of items onto a view, employing a delegate to instantiate objects and respond to calls from the drop session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDropInteraction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDropInteraction"
        }
      ],
      "role": "symbol",
      "title": "UIDropInteraction",
      "type": "topic",
      "url": "/documentation/uikit/uidropinteraction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate": {
      "abstract": [
        {
          "text": "The interface for configuring and controlling a drop interaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDropInteractionDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDropInteractionDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIDropInteractionDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uidropinteractiondelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:canHandle:)": {
      "abstract": [
        {
          "text": "Asks the delegate whether it can handle the session’s drag items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dropInteraction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDropInteraction",
          "text": "UIDropInteraction"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "canHandle"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDropSession",
          "text": "UIDropSession"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:canHandle:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dropInteraction:canHandleSession:"
        }
      ],
      "role": "symbol",
      "title": "dropInteraction(_:canHandle:)",
      "type": "topic",
      "url": "/documentation/uikit/uidropinteractiondelegate/dropinteraction(_:canhandle:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:performDrop:)": {
      "abstract": [
        {
          "text": "Tells the delegate it can request the item provider data from the session’s drag items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dropInteraction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDropInteraction",
          "text": "UIDropInteraction"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "performDrop"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDropSession",
          "text": "UIDropSession"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:performDrop:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dropInteraction:performDrop:"
        }
      ],
      "role": "symbol",
      "title": "dropInteraction(_:performDrop:)",
      "type": "topic",
      "url": "/documentation/uikit/uidropinteractiondelegate/dropinteraction(_:performdrop:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidEnter:)": {
      "abstract": [
        {
          "text": "Tells the delegate the drop session has moved into the drop interaction’s view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dropInteraction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDropInteraction",
          "text": "UIDropInteraction"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "sessionDidEnter"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDropSession",
          "text": "UIDropSession"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidEnter:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dropInteraction:sessionDidEnter:"
        }
      ],
      "role": "symbol",
      "title": "dropInteraction(_:sessionDidEnter:)",
      "type": "topic",
      "url": "/documentation/uikit/uidropinteractiondelegate/dropinteraction(_:sessiondidenter:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidUpdate:)": {
      "abstract": [
        {
          "text": "Tells the delegate the drop session has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dropInteraction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDropInteraction",
          "text": "UIDropInteraction"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "sessionDidUpdate"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDropSession",
          "text": "UIDropSession"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDropProposal",
          "text": "UIDropProposal"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropInteractionDelegate/dropInteraction(_:sessionDidUpdate:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dropInteraction:sessionDidUpdate:"
        }
      ],
      "role": "symbol",
      "title": "dropInteraction(_:sessionDidUpdate:)",
      "type": "topic",
      "url": "/documentation/uikit/uidropinteractiondelegate/dropinteraction(_:sessiondidupdate:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDropOperation": {
      "abstract": [
        {
          "text": "Operation types that determine how a drag and drop activity resolves when the user drops a drag item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDropOperation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDropOperation"
        }
      ],
      "role": "symbol",
      "title": "UIDropOperation",
      "type": "topic",
      "url": "/documentation/uikit/uidropoperation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDropOperation/cancel": {
      "abstract": [
        {
          "text": "A drop operation type specifying that no data should be transferred, thereby canceling the drag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancel"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropOperation/cancel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDropOperationCancel"
        }
      ],
      "role": "symbol",
      "title": "UIDropOperation.cancel",
      "type": "topic",
      "url": "/documentation/uikit/uidropoperation/cancel"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDropProposal": {
      "abstract": [
        {
          "text": "A configuration for the behavior of a drop interaction, required if a view accepts drop activities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDropProposal"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropProposal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDropProposal"
        }
      ],
      "role": "symbol",
      "title": "UIDropProposal",
      "type": "topic",
      "url": "/documentation/uikit/uidropproposal"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDropSession": {
      "abstract": [
        {
          "text": "The interface for querying a drop session about its state and associated drag items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDropSession"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDropSession"
        }
      ],
      "role": "symbol",
      "title": "UIDropSession",
      "type": "topic",
      "url": "/documentation/uikit/uidropsession"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDropSession/loadObjects(ofClass:completion:)": {
      "abstract": [
        {
          "text": "Creates and loads a new instance of the specified class for each drag item in the session.",
          "type": "text"
        }
      ],
      "defaultImplementations": 1,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadObjects"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ofClass"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSItemProviderReading",
          "text": "NSItemProviderReading"
        },
        {
          "kind": "text",
          "text": ".Type, "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ([any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSItemProviderReading",
          "text": "NSItemProviderReading"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSProgress",
          "text": "Progress"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropSession/loadObjects(ofClass:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadObjectsOfClass:completion:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "loadObjects(ofClass:completion:)",
      "type": "topic",
      "url": "/documentation/uikit/uidropsession/loadobjects(ofclass:completion:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage": {
      "abstract": [
        {
          "text": "An object that manages image data in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIImage"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImage"
        }
      ],
      "role": "symbol",
      "title": "UIImage",
      "type": "topic",
      "url": "/documentation/uikit/uiimage"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableView": {
      "abstract": [
        {
          "text": "A view that presents data using rows in a single column.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITableView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableView"
        }
      ],
      "role": "symbol",
      "title": "UITableView",
      "type": "topic",
      "url": "/documentation/uikit/uitableview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextView": {
      "abstract": [
        {
          "text": "A scrollable, multiline text region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextView"
        }
      ],
      "role": "symbol",
      "title": "UITextView",
      "type": "topic",
      "url": "/documentation/uikit/uitextview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView": {
      "abstract": [
        {
          "text": "An object that manages the content for a rectangular area on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIView"
        }
      ],
      "role": "symbol",
      "title": "UIView",
      "type": "topic",
      "url": "/documentation/uikit/uiview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/interactions": {
      "abstract": [
        {
          "text": "The array of interactions for the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interactions"
        },
        {
          "kind": "text",
          "text": ": [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIInteraction",
          "text": "UIInteraction"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/interactions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "interactions"
        }
      ],
      "role": "symbol",
      "title": "interactions",
      "type": "topic",
      "url": "/documentation/uikit/uiview/interactions"
    },
    "doc://com.apple.uikit/documentation/UIKit/adopting-drag-and-drop-in-a-custom-view": {
      "abstract": [
        {
          "text": "Demonstrates how to enable drag and drop for a ",
          "type": "text"
        },
        {
          "code": "UIImageView",
          "type": "codeVoice"
        },
        {
          "text": " instance.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/adopting-drag-and-drop-in-a-custom-view",
      "kind": "article",
      "role": "sampleCode",
      "title": "Adopting drag and drop in a custom view",
      "type": "topic",
      "url": "/documentation/uikit/adopting-drag-and-drop-in-a-custom-view"
    },
    "doc://com.apple.uikit/documentation/UIKit/adopting-drag-and-drop-in-a-table-view": {
      "abstract": [
        {
          "text": "Demonstrates how to enable and implement drag and drop for a table view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/adopting-drag-and-drop-in-a-table-view",
      "kind": "article",
      "role": "sampleCode",
      "title": "Adopting drag and drop in a table view",
      "type": "topic",
      "url": "/documentation/uikit/adopting-drag-and-drop-in-a-table-view"
    },
    "doc://com.apple.uikit/documentation/UIKit/drag-and-drop": {
      "abstract": [
        {
          "text": "Bring drag and drop to your app by using interaction APIs with your views.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/drag-and-drop",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Drag and drop",
      "type": "topic",
      "url": "/documentation/uikit/drag-and-drop"
    },
    "doc://com.apple.uikit/documentation/UIKit/making-a-view-into-a-drag-source": {
      "abstract": [
        {
          "text": "Adopt drag interaction APIs to provide items for dragging.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/making-a-view-into-a-drag-source",
      "kind": "article",
      "role": "article",
      "title": "Making a view into a drag source",
      "type": "topic",
      "url": "/documentation/uikit/making-a-view-into-a-drag-source"
    },
    "doc://com.apple.uikit/documentation/UIKit/making-a-view-into-a-drop-destination#Consider-accepting-the-drag-items": {
      "abstract": [],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/making-a-view-into-a-drop-destination#Consider-accepting-the-drag-items",
      "kind": "section",
      "title": "Consider accepting the drag items",
      "type": "topic",
      "url": "/documentation/uikit/making-a-view-into-a-drop-destination#Consider-accepting-the-drag-items"
    },
    "doc://com.apple.uikit/documentation/UIKit/understanding-a-drag-item-as-a-promise": {
      "abstract": [
        {
          "text": "Use drag items to convey data representation promises between a source app and a destination app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/understanding-a-drag-item-as-a-promise",
      "kind": "article",
      "role": "article",
      "title": "Understanding a drag item as a promise",
      "type": "topic",
      "url": "/documentation/uikit/understanding-a-drag-item-as-a-promise"
    },
    "media-2903753": {
      "alt": "APIs for consuming data from drag items in a drop destination",
      "identifier": "media-2903753",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/67b275f6dcc278f02bdbad17ff2c6a7e/media-2903753@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/understanding-a-drag-item-as-a-promise",
        "doc://com.apple.uikit/documentation/UIKit/making-a-view-into-a-drag-source",
        "doc://com.apple.uikit/documentation/UIKit/adopting-drag-and-drop-in-a-custom-view",
        "doc://com.apple.uikit/documentation/UIKit/adopting-drag-and-drop-in-a-table-view"
      ],
      "title": "Essentials"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/understanding-a-drag-item-as-a-promise",
                "doc://com.apple.uikit/documentation/UIKit/making-a-view-into-a-drag-source",
                "doc://com.apple.uikit/documentation/UIKit/adopting-drag-and-drop-in-a-custom-view",
                "doc://com.apple.uikit/documentation/UIKit/adopting-drag-and-drop-in-a-table-view"
              ],
              "title": "Essentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView/title",
          "value": "UITableView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextView/title",
          "value": "UITextView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView/title",
          "value": "UICollectionView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1interactions/title",
          "value": "interactions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1interactions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "interactions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:sessionDidUpdate:)/title",
          "value": "dropInteraction:sessionDidUpdate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:sessionDidUpdate:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dropInteraction:sessionDidUpdate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/title",
          "value": "UIView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropOperation~1cancel/title",
          "value": "UIDropOperationCancel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropOperation~1cancel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDropOperationCancel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:sessionDidEnter:)/title",
          "value": "dropInteraction:sessionDidEnter:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:sessionDidEnter:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dropInteraction:sessionDidEnter:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:performDrop:)/title",
          "value": "dropInteraction:performDrop:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:performDrop:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dropInteraction:performDrop:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropOperation/title",
          "value": "UIDropOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDropOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDropOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession/title",
          "value": "UIDropSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDropSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDropSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteraction/title",
          "value": "UIDropInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDropInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDropInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate/title",
          "value": "UIDropInteractionDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDropInteractionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDropInteractionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:canHandle:)/title",
          "value": "dropInteraction:canHandleSession:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropInteractionDelegate~1dropInteraction(_:canHandle:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dropInteraction:canHandleSession:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession~1loadObjects(ofClass:completion:)/title",
          "value": "loadObjectsOfClass:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession~1loadObjects(ofClass:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "loadObjectsOfClass:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/title",
          "value": "UIImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropProposal/title",
          "value": "UIDropProposal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropProposal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDropProposal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropProposal/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDropProposal"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/making-a-view-into-a-drop-destination"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/making-a-view-into-a-drop-destination"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
