{
  "abstract": [
    {
      "text": "Add subtle motion to views to provide a 3D appearance.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/animation-and-haptics"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/motion-effects"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Motion effects"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIInterpolatingMotionEffect": {
      "abstract": [
        {
          "text": "An object that maps the horizontal or vertical tilt of a device to values that you specify so that UIKit can apply those values to your views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIInterpolatingMotionEffect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIInterpolatingMotionEffect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIInterpolatingMotionEffect"
        }
      ],
      "role": "symbol",
      "title": "UIInterpolatingMotionEffect",
      "type": "topic",
      "url": "/documentation/uikit/uiinterpolatingmotioneffect"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMotionEffect": {
      "abstract": [
        {
          "text": "An abstract superclass for defining motion-based modifiers for views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIMotionEffect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMotionEffect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIMotionEffect"
        }
      ],
      "role": "symbol",
      "title": "UIMotionEffect",
      "type": "topic",
      "url": "/documentation/uikit/uimotioneffect"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMotionEffectGroup": {
      "abstract": [
        {
          "text": "A collection of motion effects that you want to apply to a view at the same time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIMotionEffectGroup"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMotionEffectGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIMotionEffectGroup"
        }
      ],
      "role": "symbol",
      "title": "UIMotionEffectGroup",
      "type": "topic",
      "url": "/documentation/uikit/uimotioneffectgroup"
    },
    "doc://com.apple.uikit/documentation/UIKit/animation-and-haptics": {
      "abstract": [
        {
          "text": "Provide feedback to users using view-based animations and haptics.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/animation-and-haptics",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Animation and haptics",
      "type": "topic",
      "url": "/documentation/uikit/animation-and-haptics"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "View-based-effects",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIMotionEffectGroup",
        "doc://com.apple.uikit/documentation/UIKit/UIInterpolatingMotionEffect"
      ],
      "title": "View-based effects"
    },
    {
      "anchor": "Custom-motion-effects",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIMotionEffect"
      ],
      "title": "Custom motion effects"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "View-based-effects",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIMotionEffectGroup",
                "doc://com.apple.uikit/documentation/UIKit/UIInterpolatingMotionEffect"
              ],
              "title": "View-based effects"
            },
            {
              "anchor": "Custom-motion-effects",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIMotionEffect"
              ],
              "title": "Custom motion effects"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInterpolatingMotionEffect/title",
          "value": "UIInterpolatingMotionEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInterpolatingMotionEffect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIInterpolatingMotionEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInterpolatingMotionEffect/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIInterpolatingMotionEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMotionEffectGroup/title",
          "value": "UIMotionEffectGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMotionEffectGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMotionEffectGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMotionEffectGroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMotionEffectGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMotionEffect/title",
          "value": "UIMotionEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMotionEffect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMotionEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMotionEffect/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMotionEffect"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/motion-effects"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/motion-effects"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
