{
  "abstract": [
    {
      "text": "Handle notifications with keys in the user info dictionary.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/accessibility-for-uikit"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/accessibility-for-uikit",
        "doc://com.apple.uikit/documentation/UIKit/uiaccessibility-protocol"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/notification-dictionary-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Notification dictionary keys"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/AssistiveTechnologyIdentifier": {
      "abstract": [
        {
          "text": "Identifiers for assistive apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AssistiveTechnologyIdentifier"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/AssistiveTechnologyIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AssistiveTechnologyIdentifier"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibility.AssistiveTechnologyIdentifier",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/assistivetechnologyidentifier"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/announcementStringValueUserInfoKey": {
      "abstract": [
        {
          "text": "The text of the announcement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "announcementStringValueUserInfoKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/announcementStringValueUserInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityAnnouncementKeyStringValue"
        }
      ],
      "role": "symbol",
      "title": "announcementStringValueUserInfoKey",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/announcementstringvalueuserinfokey"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/announcementWasSuccessfulUserInfoKey": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the announcement is successful.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "announcementWasSuccessfulUserInfoKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/announcementWasSuccessfulUserInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityAnnouncementKeyWasSuccessful"
        }
      ],
      "role": "symbol",
      "title": "announcementWasSuccessfulUserInfoKey",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/announcementwassuccessfuluserinfokey"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/assistiveTechnologyUserInfoKey": {
      "abstract": [
        {
          "text": "The identifier of the assistive app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "assistiveTechnologyUserInfoKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/assistiveTechnologyUserInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityAssistiveTechnologyKey"
        }
      ],
      "role": "symbol",
      "title": "assistiveTechnologyUserInfoKey",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/assistivetechnologyuserinfokey"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/focusedElementUserInfoKey": {
      "abstract": [
        {
          "text": "The element currently in focus by the assistive app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "focusedElementUserInfoKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/focusedElementUserInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityFocusedElementKey"
        }
      ],
      "role": "symbol",
      "title": "focusedElementUserInfoKey",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/focusedelementuserinfokey"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/post(notification:argument:)": {
      "abstract": [
        {
          "text": "Posts a notification to assistive apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "post"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "notification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@UIAccessibility",
          "text": "UIAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityNotifications",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "argument"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/post(notification:argument:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityPostNotification"
        }
      ],
      "role": "symbol",
      "title": "post(notification:argument:)",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/post(notification:argument:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/unfocusedElementUserInfoKey": {
      "abstract": [
        {
          "text": "The element previously in focus by the assistive app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unfocusedElementUserInfoKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/unfocusedElementUserInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityUnfocusedElementKey"
        }
      ],
      "role": "symbol",
      "title": "unfocusedElementUserInfoKey",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/unfocusedelementuserinfokey"
    },
    "doc://com.apple.uikit/documentation/UIKit/accessibility-for-uikit": {
      "abstract": [
        {
          "text": "Make your UIKit apps accessible to everyone who uses iOS and tvOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/accessibility-for-uikit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Accessibility for UIKit",
      "type": "topic",
      "url": "/documentation/uikit/accessibility-for-uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/notification-names": {
      "abstract": [
        {
          "text": "The names of notifications that the accessibility system generates.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/notification-names",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Notification names",
      "type": "topic",
      "url": "/documentation/uikit/notification-names"
    },
    "doc://com.apple.uikit/documentation/UIKit/uiaccessibility-protocol": {
      "abstract": [
        {
          "text": "A set of methods that provides accessibility information about views and controls in an app’s user interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/uiaccessibility-protocol",
      "kind": "article",
      "role": "collectionGroup",
      "title": "UIAccessibility",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility-protocol"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Notifications",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/notification-names",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/post(notification:argument:)"
      ],
      "title": "Notifications"
    }
  ],
  "topicSections": [
    {
      "anchor": "Notification-keys",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/announcementStringValueUserInfoKey",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/announcementWasSuccessfulUserInfoKey",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/focusedElementUserInfoKey",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/unfocusedElementUserInfoKey",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/assistiveTechnologyUserInfoKey",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/AssistiveTechnologyIdentifier"
      ],
      "title": "Notification keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Notification-keys",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/announcementStringValueUserInfoKey",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/announcementWasSuccessfulUserInfoKey",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/focusedElementUserInfoKey",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/unfocusedElementUserInfoKey",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/assistiveTechnologyUserInfoKey",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/AssistiveTechnologyIdentifier"
              ],
              "title": "Notification keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Notifications",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/notification-names",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/post(notification:argument:)"
              ],
              "title": "Notifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1unfocusedElementUserInfoKey/title",
          "value": "UIAccessibilityUnfocusedElementKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1unfocusedElementUserInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityUnfocusedElementKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1post(notification:argument:)/title",
          "value": "UIAccessibilityPostNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1post(notification:argument:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityPostNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1announcementStringValueUserInfoKey/title",
          "value": "UIAccessibilityAnnouncementKeyStringValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1announcementStringValueUserInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityAnnouncementKeyStringValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1focusedElementUserInfoKey/title",
          "value": "UIAccessibilityFocusedElementKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1focusedElementUserInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityFocusedElementKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1announcementWasSuccessfulUserInfoKey/title",
          "value": "UIAccessibilityAnnouncementKeyWasSuccessful"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1announcementWasSuccessfulUserInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityAnnouncementKeyWasSuccessful"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1assistiveTechnologyUserInfoKey/title",
          "value": "UIAccessibilityAssistiveTechnologyKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1assistiveTechnologyUserInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityAssistiveTechnologyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1AssistiveTechnologyIdentifier/title",
          "value": "UIAccessibilityAssistiveTechnologyIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1AssistiveTechnologyIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityAssistiveTechnologyIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1AssistiveTechnologyIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityAssistiveTechnologyIdentifier"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/notification-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/notification-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
