{
  "abstract": [
    {
      "text": "The names of notifications that the accessibility system generates.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/accessibility-for-uikit"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/accessibility-for-uikit",
        "doc://com.apple.uikit/documentation/UIKit/uiaccessibility-protocol"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/notification-names"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Notification names"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/AssistiveTechnologyIdentifier": {
      "abstract": [
        {
          "text": "Identifiers for assistive apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AssistiveTechnologyIdentifier"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/AssistiveTechnologyIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AssistiveTechnologyIdentifier"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibility.AssistiveTechnologyIdentifier",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/assistivetechnologyidentifier"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/announcement": {
      "abstract": [
        {
          "text": "A notification that an app posts when it needs to convey an announcement to the assistive app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "announcement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@UIAccessibility",
          "text": "UIAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityNotifications",
          "text": "Notification"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/announcement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityAnnouncementNotification"
        }
      ],
      "role": "symbol",
      "title": "announcement",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/notification/announcement"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/layoutChanged": {
      "abstract": [
        {
          "text": "A notification that an app posts when the layout of a screen changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layoutChanged"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@UIAccessibility",
          "text": "UIAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityNotifications",
          "text": "Notification"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/layoutChanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityLayoutChangedNotification"
        }
      ],
      "role": "symbol",
      "title": "layoutChanged",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/notification/layoutchanged"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/pageScrolled": {
      "abstract": [
        {
          "text": "A notification that an app posts when a scroll action completes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageScrolled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@UIAccessibility",
          "text": "UIAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityNotifications",
          "text": "Notification"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/pageScrolled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityPageScrolledNotification"
        }
      ],
      "role": "symbol",
      "title": "pageScrolled",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/notification/pagescrolled"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/pauseAssistiveTechnology": {
      "abstract": [
        {
          "text": "A notification that pauses an assistive app’s operations temporarily.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pauseAssistiveTechnology"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@UIAccessibility",
          "text": "UIAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityNotifications",
          "text": "Notification"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/pauseAssistiveTechnology",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityPauseAssistiveTechnologyNotification"
        }
      ],
      "role": "symbol",
      "title": "pauseAssistiveTechnology",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/notification/pauseassistivetechnology"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/resumeAssistiveTechnology": {
      "abstract": [
        {
          "text": "A notification that resumes an assistive app’s operations temporarily.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resumeAssistiveTechnology"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@UIAccessibility",
          "text": "UIAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityNotifications",
          "text": "Notification"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/resumeAssistiveTechnology",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityResumeAssistiveTechnologyNotification"
        }
      ],
      "role": "symbol",
      "title": "resumeAssistiveTechnology",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/notification/resumeassistivetechnology"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/screenChanged": {
      "abstract": [
        {
          "text": "A notification that an app posts when a new view appears that occupies a major portion of the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "screenChanged"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@UIAccessibility",
          "text": "UIAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityNotifications",
          "text": "Notification"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/screenChanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityScreenChangedNotification"
        }
      ],
      "role": "symbol",
      "title": "screenChanged",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/notification/screenchanged"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/announcementDidFinishNotification": {
      "abstract": [
        {
          "text": "A notification that UIKit posts when the system finishes reading an announcement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "announcementDidFinishNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/announcementDidFinishNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityAnnouncementDidFinishNotification"
        }
      ],
      "role": "symbol",
      "title": "announcementDidFinishNotification",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/announcementdidfinishnotification"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/assistiveTouchStatusDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification that indicates a change in the status of AssistiveTouch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "assistiveTouchStatusDidChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/assistiveTouchStatusDidChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityAssistiveTouchStatusDidChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "assistiveTouchStatusDidChangeNotification",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/assistivetouchstatusdidchangenotification"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/boldTextStatusDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification that UIKit posts when the system’s Bold Text setting changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "boldTextStatusDidChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/boldTextStatusDidChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityBoldTextStatusDidChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "boldTextStatusDidChangeNotification",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/boldtextstatusdidchangenotification"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/buttonShapesEnabledStatusDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification that UIKit posts when the system’s Button Shapes setting changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "buttonShapesEnabledStatusDidChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/buttonShapesEnabledStatusDidChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityButtonShapesEnabledStatusDidChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "buttonShapesEnabledStatusDidChangeNotification",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/buttonshapesenabledstatusdidchangenotification"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/closedCaptioningStatusDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification that UIKit posts when the setting for Closed Captions + SDH changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "closedCaptioningStatusDidChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/closedCaptioningStatusDidChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityClosedCaptioningStatusDidChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "closedCaptioningStatusDidChangeNotification",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/closedcaptioningstatusdidchangenotification"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/darkerSystemColorsStatusDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification that UIKit posts when the system’s Increase Contrast setting changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "darkerSystemColorsStatusDidChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/darkerSystemColorsStatusDidChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityDarkerSystemColorsStatusDidChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "darkerSystemColorsStatusDidChangeNotification",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/darkersystemcolorsstatusdidchangenotification"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/elementFocusedNotification": {
      "abstract": [
        {
          "text": "A notification that UIKit posts when an assistive app focuses on an accessibility element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "elementFocusedNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/elementFocusedNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityElementFocusedNotification"
        }
      ],
      "role": "symbol",
      "title": "elementFocusedNotification",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/elementfocusednotification"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/grayscaleStatusDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification that UIKit posts when the system’s Grayscale setting changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "grayscaleStatusDidChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/grayscaleStatusDidChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityGrayscaleStatusDidChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "grayscaleStatusDidChangeNotification",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/grayscalestatusdidchangenotification"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/guidedAccessStatusDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification that indicates when a Guided Access session starts or ends.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "guidedAccessStatusDidChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/guidedAccessStatusDidChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityGuidedAccessStatusDidChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "guidedAccessStatusDidChangeNotification",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/guidedaccessstatusdidchangenotification"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/hearingDevicePairedEarDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification that UIKit posts when there’s a change to the currently paired hearing devices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hearingDevicePairedEarDidChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/hearingDevicePairedEarDidChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityHearingDevicePairedEarDidChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "hearingDevicePairedEarDidChangeNotification",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/hearingdevicepairedeardidchangenotification"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/invertColorsStatusDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification that UIKit posts when the settings for inverted colors change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invertColorsStatusDidChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/invertColorsStatusDidChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityInvertColorsStatusDidChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "invertColorsStatusDidChangeNotification",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/invertcolorsstatusdidchangenotification"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/monoAudioStatusDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification that UIKit posts when system audio changes from stereo to mono.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "monoAudioStatusDidChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/monoAudioStatusDidChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityMonoAudioStatusDidChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "monoAudioStatusDidChangeNotification",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/monoaudiostatusdidchangenotification"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/post(notification:argument:)": {
      "abstract": [
        {
          "text": "Posts a notification to assistive apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "post"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "notification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@UIAccessibility",
          "text": "UIAccessibility"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityNotifications",
          "text": "Notification"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "argument"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/post(notification:argument:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityPostNotification"
        }
      ],
      "role": "symbol",
      "title": "post(notification:argument:)",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/post(notification:argument:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/reduceMotionStatusDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification that UIKit posts when the system’s Reduce Motion setting changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reduceMotionStatusDidChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/reduceMotionStatusDidChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityReduceMotionStatusDidChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "reduceMotionStatusDidChangeNotification",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/reducemotionstatusdidchangenotification"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/reduceTransparencyStatusDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification that UIKit posts when the system’s Reduce Transparency setting changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reduceTransparencyStatusDidChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/reduceTransparencyStatusDidChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityReduceTransparencyStatusDidChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "reduceTransparencyStatusDidChangeNotification",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/reducetransparencystatusdidchangenotification"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/shakeToUndoDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification that UIKit posts when the system’s Shake to Undo setting changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shakeToUndoDidChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/shakeToUndoDidChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityShakeToUndoDidChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "shakeToUndoDidChangeNotification",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/shaketoundodidchangenotification"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/speakScreenStatusDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification that UIKit posts when the system’s Speak Screen setting changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "speakScreenStatusDidChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/speakScreenStatusDidChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilitySpeakScreenStatusDidChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "speakScreenStatusDidChangeNotification",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/speakscreenstatusdidchangenotification"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/speakSelectionStatusDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification that UIKit posts when the system’s Speak Selection setting changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "speakSelectionStatusDidChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/speakSelectionStatusDidChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilitySpeakSelectionStatusDidChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "speakSelectionStatusDidChangeNotification",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/speakselectionstatusdidchangenotification"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/switchControlStatusDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification that UIKit posts when the system’s Switch Control setting changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "switchControlStatusDidChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/switchControlStatusDidChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilitySwitchControlStatusDidChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "switchControlStatusDidChangeNotification",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/switchcontrolstatusdidchangenotification"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/voiceOverStatusDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification that UIKit posts when VoiceOver starts or stops.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "voiceOverStatusDidChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/voiceOverStatusDidChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityVoiceOverStatusDidChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "voiceOverStatusDidChangeNotification",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/voiceoverstatusdidchangenotification"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityVoiceOverStatusChanged": {
      "abstract": [
        {
          "text": "A notification that UIKit posts when VoiceOver starts or stops.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAccessibilityVoiceOverStatusChanged"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityVoiceOverStatusChanged",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityVoiceOverStatusChanged"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityVoiceOverStatusChanged",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityvoiceoverstatuschanged"
    },
    "doc://com.apple.uikit/documentation/UIKit/accessibility-for-uikit": {
      "abstract": [
        {
          "text": "Make your UIKit apps accessible to everyone who uses iOS and tvOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/accessibility-for-uikit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Accessibility for UIKit",
      "type": "topic",
      "url": "/documentation/uikit/accessibility-for-uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/notification-dictionary-keys": {
      "abstract": [
        {
          "text": "Handle notifications with keys in the user info dictionary.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/notification-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Notification dictionary keys",
      "type": "topic",
      "url": "/documentation/uikit/notification-dictionary-keys"
    },
    "doc://com.apple.uikit/documentation/UIKit/uiaccessibility-protocol": {
      "abstract": [
        {
          "text": "A set of methods that provides accessibility information about views and controls in an app’s user interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/uiaccessibility-protocol",
      "kind": "article",
      "role": "collectionGroup",
      "title": "UIAccessibility",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility-protocol"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Notifications",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/notification-dictionary-keys",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/post(notification:argument:)"
      ],
      "title": "Notifications"
    }
  ],
  "topicSections": [
    {
      "anchor": "UI-changes",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/screenChanged",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/layoutChanged",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/pageScrolled",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/switchControlStatusDidChangeNotification",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/elementFocusedNotification",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/reduceTransparencyStatusDidChangeNotification",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/buttonShapesEnabledStatusDidChangeNotification"
      ],
      "title": "UI changes"
    },
    {
      "anchor": "VoiceOver",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/announcement",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/voiceOverStatusDidChangeNotification",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/announcementDidFinishNotification",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityVoiceOverStatusChanged"
      ],
      "title": "VoiceOver"
    },
    {
      "anchor": "Text",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/boldTextStatusDidChangeNotification",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/closedCaptioningStatusDidChangeNotification"
      ],
      "title": "Text"
    },
    {
      "anchor": "Colors",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/darkerSystemColorsStatusDidChangeNotification",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/grayscaleStatusDidChangeNotification",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/invertColorsStatusDidChangeNotification"
      ],
      "title": "Colors"
    },
    {
      "anchor": "Assistive-apps",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/assistiveTouchStatusDidChangeNotification",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/guidedAccessStatusDidChangeNotification",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/pauseAssistiveTechnology",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/resumeAssistiveTechnology",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/AssistiveTechnologyIdentifier"
      ],
      "title": "Assistive apps"
    },
    {
      "anchor": "Audio-and-speech",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/monoAudioStatusDidChangeNotification",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/speakScreenStatusDidChangeNotification",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/speakSelectionStatusDidChangeNotification",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/hearingDevicePairedEarDidChangeNotification"
      ],
      "title": "Audio and speech"
    },
    {
      "anchor": "Motion",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/reduceMotionStatusDidChangeNotification",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/shakeToUndoDidChangeNotification"
      ],
      "title": "Motion"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "UI-changes",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/screenChanged",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/layoutChanged",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/pageScrolled",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/switchControlStatusDidChangeNotification",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/elementFocusedNotification",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/reduceTransparencyStatusDidChangeNotification",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/buttonShapesEnabledStatusDidChangeNotification"
              ],
              "title": "UI changes"
            },
            {
              "anchor": "VoiceOver",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/announcement",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/voiceOverStatusDidChangeNotification",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/announcementDidFinishNotification",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityVoiceOverStatusChanged"
              ],
              "title": "VoiceOver"
            },
            {
              "anchor": "Text",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/boldTextStatusDidChangeNotification",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/closedCaptioningStatusDidChangeNotification"
              ],
              "title": "Text"
            },
            {
              "anchor": "Colors",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/darkerSystemColorsStatusDidChangeNotification",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/grayscaleStatusDidChangeNotification",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/invertColorsStatusDidChangeNotification"
              ],
              "title": "Colors"
            },
            {
              "anchor": "Assistive-apps",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/assistiveTouchStatusDidChangeNotification",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/guidedAccessStatusDidChangeNotification",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/pauseAssistiveTechnology",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/Notification/resumeAssistiveTechnology",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/AssistiveTechnologyIdentifier"
              ],
              "title": "Assistive apps"
            },
            {
              "anchor": "Audio-and-speech",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/monoAudioStatusDidChangeNotification",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/speakScreenStatusDidChangeNotification",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/speakSelectionStatusDidChangeNotification",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/hearingDevicePairedEarDidChangeNotification"
              ],
              "title": "Audio and speech"
            },
            {
              "anchor": "Motion",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/reduceMotionStatusDidChangeNotification",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/shakeToUndoDidChangeNotification"
              ],
              "title": "Motion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Notifications",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/notification-dictionary-keys",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/post(notification:argument:)"
              ],
              "title": "Notifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1grayscaleStatusDidChangeNotification/title",
          "value": "UIAccessibilityGrayscaleStatusDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1grayscaleStatusDidChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityGrayscaleStatusDidChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1guidedAccessStatusDidChangeNotification/title",
          "value": "UIAccessibilityGuidedAccessStatusDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1guidedAccessStatusDidChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityGuidedAccessStatusDidChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1shakeToUndoDidChangeNotification/title",
          "value": "UIAccessibilityShakeToUndoDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1shakeToUndoDidChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityShakeToUndoDidChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1announcementDidFinishNotification/title",
          "value": "UIAccessibilityAnnouncementDidFinishNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1announcementDidFinishNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityAnnouncementDidFinishNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1Notification~1layoutChanged/title",
          "value": "UIAccessibilityLayoutChangedNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1Notification~1layoutChanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityLayoutChangedNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1elementFocusedNotification/title",
          "value": "UIAccessibilityElementFocusedNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1elementFocusedNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityElementFocusedNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1invertColorsStatusDidChangeNotification/title",
          "value": "UIAccessibilityInvertColorsStatusDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1invertColorsStatusDidChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityInvertColorsStatusDidChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1darkerSystemColorsStatusDidChangeNotification/title",
          "value": "UIAccessibilityDarkerSystemColorsStatusDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1darkerSystemColorsStatusDidChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityDarkerSystemColorsStatusDidChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1Notification~1pauseAssistiveTechnology/title",
          "value": "UIAccessibilityPauseAssistiveTechnologyNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1Notification~1pauseAssistiveTechnology/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityPauseAssistiveTechnologyNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1boldTextStatusDidChangeNotification/title",
          "value": "UIAccessibilityBoldTextStatusDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1boldTextStatusDidChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityBoldTextStatusDidChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1switchControlStatusDidChangeNotification/title",
          "value": "UIAccessibilitySwitchControlStatusDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1switchControlStatusDidChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilitySwitchControlStatusDidChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1assistiveTouchStatusDidChangeNotification/title",
          "value": "UIAccessibilityAssistiveTouchStatusDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1assistiveTouchStatusDidChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityAssistiveTouchStatusDidChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1AssistiveTechnologyIdentifier/title",
          "value": "UIAccessibilityAssistiveTechnologyIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1AssistiveTechnologyIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityAssistiveTechnologyIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1AssistiveTechnologyIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityAssistiveTechnologyIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1monoAudioStatusDidChangeNotification/title",
          "value": "UIAccessibilityMonoAudioStatusDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1monoAudioStatusDidChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityMonoAudioStatusDidChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1reduceMotionStatusDidChangeNotification/title",
          "value": "UIAccessibilityReduceMotionStatusDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1reduceMotionStatusDidChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityReduceMotionStatusDidChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1speakScreenStatusDidChangeNotification/title",
          "value": "UIAccessibilitySpeakScreenStatusDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1speakScreenStatusDidChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilitySpeakScreenStatusDidChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1Notification~1resumeAssistiveTechnology/title",
          "value": "UIAccessibilityResumeAssistiveTechnologyNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1Notification~1resumeAssistiveTechnology/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityResumeAssistiveTechnologyNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1Notification~1pageScrolled/title",
          "value": "UIAccessibilityPageScrolledNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1Notification~1pageScrolled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityPageScrolledNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1Notification~1announcement/title",
          "value": "UIAccessibilityAnnouncementNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1Notification~1announcement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityAnnouncementNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1voiceOverStatusDidChangeNotification/title",
          "value": "UIAccessibilityVoiceOverStatusDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1voiceOverStatusDidChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityVoiceOverStatusDidChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1reduceTransparencyStatusDidChangeNotification/title",
          "value": "UIAccessibilityReduceTransparencyStatusDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1reduceTransparencyStatusDidChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityReduceTransparencyStatusDidChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityVoiceOverStatusChanged/title",
          "value": "UIAccessibilityVoiceOverStatusChanged"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityVoiceOverStatusChanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityVoiceOverStatusChanged"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1hearingDevicePairedEarDidChangeNotification/title",
          "value": "UIAccessibilityHearingDevicePairedEarDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1hearingDevicePairedEarDidChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityHearingDevicePairedEarDidChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1speakSelectionStatusDidChangeNotification/title",
          "value": "UIAccessibilitySpeakSelectionStatusDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1speakSelectionStatusDidChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilitySpeakSelectionStatusDidChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1post(notification:argument:)/title",
          "value": "UIAccessibilityPostNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1post(notification:argument:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityPostNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1closedCaptioningStatusDidChangeNotification/title",
          "value": "UIAccessibilityClosedCaptioningStatusDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1closedCaptioningStatusDidChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityClosedCaptioningStatusDidChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1Notification~1screenChanged/title",
          "value": "UIAccessibilityScreenChangedNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1Notification~1screenChanged/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityScreenChangedNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1buttonShapesEnabledStatusDidChangeNotification/title",
          "value": "UIAccessibilityButtonShapesEnabledStatusDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1buttonShapesEnabledStatusDidChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityButtonShapesEnabledStatusDidChangeNotification"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/notification-names"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/notification-names"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
