{
  "abstract": [
    {
      "text": "The attributes you apply to an entire document.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/NSAttributedStringDocumentAttributeKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@NSAttributedStringDocumentAttributeKey",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSAttributedStringDocumentAttributeKey"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSAttributedStringDocumentAttributeKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "NSAttributedStringDocumentAttributeKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typedef"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSString",
              "text": "NSString"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "NSAttributedStringDocumentAttributeKey"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSAttributedStringDocumentAttributeKey",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " type defines attributes that apply to an entire attributed string, and not to specific ranges of characters. You specify these attributes when writing an attributed string to disk, or reading text from a file on disk. Use these attributes to specify metadata about the overall document, including its author or title, page margin details, font-scaling options for cross-platform interchange, and more.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AppKit/NSAppearanceDocumentAttribute": {
      "abstract": [
        {
          "text": "The appearance of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "extern"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAttributedStringDocumentAttributeKey",
          "text": "NSAttributedStringDocumentAttributeKey"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAppearanceDocumentAttribute"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSAppearanceDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAppearanceDocumentAttribute",
      "type": "topic",
      "url": "/documentation/AppKit/NSAppearanceDocumentAttribute"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSAuthorDocumentAttribute": {
      "abstract": [
        {
          "text": "The author of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "extern"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAttributedStringDocumentAttributeKey",
          "text": "NSAttributedStringDocumentAttributeKey"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAuthorDocumentAttribute"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSAuthorDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAuthorDocumentAttribute",
      "type": "topic",
      "url": "/documentation/AppKit/NSAuthorDocumentAttribute"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSBottomMarginDocumentAttribute": {
      "abstract": [
        {
          "text": "The bottom margin of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "extern"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAttributedStringDocumentAttributeKey",
          "text": "NSAttributedStringDocumentAttributeKey"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBottomMarginDocumentAttribute"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSBottomMarginDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSBottomMarginDocumentAttribute",
      "type": "topic",
      "url": "/documentation/AppKit/NSBottomMarginDocumentAttribute"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSCategoryDocumentAttribute": {
      "abstract": [
        {
          "text": "The document’s category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "extern"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAttributedStringDocumentAttributeKey",
          "text": "NSAttributedStringDocumentAttributeKey"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCategoryDocumentAttribute"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSCategoryDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCategoryDocumentAttribute",
      "type": "topic",
      "url": "/documentation/AppKit/NSCategoryDocumentAttribute"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSCommentDocumentAttribute": {
      "abstract": [
        {
          "text": "The document comments.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "extern"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAttributedStringDocumentAttributeKey",
          "text": "NSAttributedStringDocumentAttributeKey"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCommentDocumentAttribute"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSCommentDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCommentDocumentAttribute",
      "type": "topic",
      "url": "/documentation/AppKit/NSCommentDocumentAttribute"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSCompanyDocumentAttribute": {
      "abstract": [
        {
          "text": "The company or organization name associated with the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "extern"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAttributedStringDocumentAttributeKey",
          "text": "NSAttributedStringDocumentAttributeKey"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCompanyDocumentAttribute"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSCompanyDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCompanyDocumentAttribute",
      "type": "topic",
      "url": "/documentation/AppKit/NSCompanyDocumentAttribute"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSConvertedDocumentAttribute": {
      "abstract": [
        {
          "text": "A value that indicates whether a filter service converted the file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "extern"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAttributedStringDocumentAttributeKey",
          "text": "NSAttributedStringDocumentAttributeKey"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSConvertedDocumentAttribute"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSConvertedDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSConvertedDocumentAttribute",
      "type": "topic",
      "url": "/documentation/AppKit/NSConvertedDocumentAttribute"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSCopyrightDocumentAttribute": {
      "abstract": [
        {
          "text": "The document’s copyright information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "extern"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAttributedStringDocumentAttributeKey",
          "text": "NSAttributedStringDocumentAttributeKey"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCopyrightDocumentAttribute"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSCopyrightDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopyrightDocumentAttribute",
      "type": "topic",
      "url": "/documentation/AppKit/NSCopyrightDocumentAttribute"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSCreationTimeDocumentAttribute": {
      "abstract": [
        {
          "text": "The creation date of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "extern"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAttributedStringDocumentAttributeKey",
          "text": "NSAttributedStringDocumentAttributeKey"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCreationTimeDocumentAttribute"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSCreationTimeDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCreationTimeDocumentAttribute",
      "type": "topic",
      "url": "/documentation/AppKit/NSCreationTimeDocumentAttribute"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSEditorDocumentAttribute": {
      "abstract": [
        {
          "text": "The name of person who last edited the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "extern"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAttributedStringDocumentAttributeKey",
          "text": "NSAttributedStringDocumentAttributeKey"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSEditorDocumentAttribute"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSEditorDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSEditorDocumentAttribute",
      "type": "topic",
      "url": "/documentation/AppKit/NSEditorDocumentAttribute"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSExcludedElementsDocumentAttribute": {
      "abstract": [
        {
          "text": "The HTML elements to exclude in generated HTML.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "extern"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAttributedStringDocumentAttributeKey",
          "text": "NSAttributedStringDocumentAttributeKey"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSExcludedElementsDocumentAttribute"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSExcludedElementsDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSExcludedElementsDocumentAttribute",
      "type": "topic",
      "url": "/documentation/AppKit/NSExcludedElementsDocumentAttribute"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSFileTypeDocumentAttribute": {
      "abstract": [
        {
          "text": "The document type for interpreting the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "extern"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAttributedStringDocumentAttributeKey",
          "text": "NSAttributedStringDocumentAttributeKey"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSFileTypeDocumentAttribute"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSFileTypeDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFileTypeDocumentAttribute",
      "type": "topic",
      "url": "/documentation/AppKit/NSFileTypeDocumentAttribute"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSKeywordsDocumentAttribute": {
      "abstract": [
        {
          "text": "The document keywords.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "extern"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAttributedStringDocumentAttributeKey",
          "text": "NSAttributedStringDocumentAttributeKey"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSKeywordsDocumentAttribute"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSKeywordsDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSKeywordsDocumentAttribute",
      "type": "topic",
      "url": "/documentation/AppKit/NSKeywordsDocumentAttribute"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSLeftMarginDocumentAttribute": {
      "abstract": [
        {
          "text": "The left margin of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "extern"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAttributedStringDocumentAttributeKey",
          "text": "NSAttributedStringDocumentAttributeKey"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLeftMarginDocumentAttribute"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSLeftMarginDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLeftMarginDocumentAttribute",
      "type": "topic",
      "url": "/documentation/AppKit/NSLeftMarginDocumentAttribute"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSManagerDocumentAttribute": {
      "abstract": [
        {
          "text": "The name of the author’s manager.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "extern"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAttributedStringDocumentAttributeKey",
          "text": "NSAttributedStringDocumentAttributeKey"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSManagerDocumentAttribute"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSManagerDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSManagerDocumentAttribute",
      "type": "topic",
      "url": "/documentation/AppKit/NSManagerDocumentAttribute"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSModificationTimeDocumentAttribute": {
      "abstract": [
        {
          "text": "The modification date of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "extern"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAttributedStringDocumentAttributeKey",
          "text": "NSAttributedStringDocumentAttributeKey"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSModificationTimeDocumentAttribute"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSModificationTimeDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSModificationTimeDocumentAttribute",
      "type": "topic",
      "url": "/documentation/AppKit/NSModificationTimeDocumentAttribute"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSPrefixSpacesDocumentAttribute": {
      "abstract": [
        {
          "text": "The number of spaces for indenting nested HTML elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "extern"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAttributedStringDocumentAttributeKey",
          "text": "NSAttributedStringDocumentAttributeKey"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPrefixSpacesDocumentAttribute"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSPrefixSpacesDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPrefixSpacesDocumentAttribute",
      "type": "topic",
      "url": "/documentation/AppKit/NSPrefixSpacesDocumentAttribute"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSRightMarginDocumentAttribute": {
      "abstract": [
        {
          "text": "The right margin of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "extern"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAttributedStringDocumentAttributeKey",
          "text": "NSAttributedStringDocumentAttributeKey"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSRightMarginDocumentAttribute"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSRightMarginDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRightMarginDocumentAttribute",
      "type": "topic",
      "url": "/documentation/AppKit/NSRightMarginDocumentAttribute"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSSubjectDocumentAttribute": {
      "abstract": [
        {
          "text": "The subject of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "extern"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAttributedStringDocumentAttributeKey",
          "text": "NSAttributedStringDocumentAttributeKey"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSubjectDocumentAttribute"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSSubjectDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSubjectDocumentAttribute",
      "type": "topic",
      "url": "/documentation/AppKit/NSSubjectDocumentAttribute"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSTextEncodingNameDocumentAttribute": {
      "abstract": [
        {
          "text": "The name of the text encoding to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "extern"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAttributedStringDocumentAttributeKey",
          "text": "NSAttributedStringDocumentAttributeKey"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextEncodingNameDocumentAttribute"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSTextEncodingNameDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextEncodingNameDocumentAttribute",
      "type": "topic",
      "url": "/documentation/AppKit/NSTextEncodingNameDocumentAttribute"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSTitleDocumentAttribute": {
      "abstract": [
        {
          "text": "The document title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "extern"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAttributedStringDocumentAttributeKey",
          "text": "NSAttributedStringDocumentAttributeKey"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTitleDocumentAttribute"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSTitleDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTitleDocumentAttribute",
      "type": "topic",
      "url": "/documentation/AppKit/NSTitleDocumentAttribute"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSTopMarginDocumentAttribute": {
      "abstract": [
        {
          "text": "The top margin of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "extern"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAttributedStringDocumentAttributeKey",
          "text": "NSAttributedStringDocumentAttributeKey"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTopMarginDocumentAttribute"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSTopMarginDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTopMarginDocumentAttribute",
      "type": "topic",
      "url": "/documentation/AppKit/NSTopMarginDocumentAttribute"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSAttributedStringDocumentAttributeKey": {
      "abstract": [
        {
          "text": "The attributes you apply to an entire document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAttributedStringDocumentAttributeKey"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSAttributedStringDocumentAttributeKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAttributedStringDocumentAttributeKey",
      "type": "topic",
      "url": "/documentation/uikit/nsattributedstringdocumentattributekey"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSAttributedStringDocumentType": {
      "abstract": [
        {
          "text": "Constants for the document type document attribute key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAttributedStringDocumentType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSAttributedStringDocumentType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAttributedStringDocumentType",
      "type": "topic",
      "url": "/documentation/uikit/nsattributedstringdocumenttype"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSBackgroundColorDocumentAttribute": {
      "abstract": [
        {
          "text": "The background color of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSBackgroundColorDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSBackgroundColorDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSBackgroundColorDocumentAttribute",
      "type": "topic",
      "url": "/documentation/uikit/nsbackgroundcolordocumentattribute"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSCharacterEncodingDocumentAttribute": {
      "abstract": [
        {
          "text": "The string encoding for the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCharacterEncodingDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSCharacterEncodingDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCharacterEncodingDocumentAttribute",
      "type": "topic",
      "url": "/documentation/uikit/nscharacterencodingdocumentattribute"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSCocoaVersionDocumentAttribute": {
      "abstract": [
        {
          "text": "The version of Cocoa that created the file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCocoaVersionDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSCocoaVersionDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCocoaVersionDocumentAttribute",
      "type": "topic",
      "url": "/documentation/uikit/nscocoaversiondocumentattribute"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSDefaultAttributesDocumentAttribute": {
      "abstract": [
        {
          "text": "The default document attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSDefaultAttributesDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSDefaultAttributesDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDefaultAttributesDocumentAttribute",
      "type": "topic",
      "url": "/documentation/uikit/nsdefaultattributesdocumentattribute"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSDefaultFontExcludedDocumentAttribute": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSDefaultFontExcludedDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSDefaultFontExcludedDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDefaultFontExcludedDocumentAttribute",
      "type": "topic",
      "url": "/documentation/uikit/nsdefaultfontexcludeddocumentattribute"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSDefaultTabIntervalDocumentAttribute": {
      "abstract": [
        {
          "text": "The default tab stop interval for the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSDefaultTabIntervalDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSDefaultTabIntervalDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDefaultTabIntervalDocumentAttribute",
      "type": "topic",
      "url": "/documentation/uikit/nsdefaulttabintervaldocumentattribute"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSDocumentTypeDocumentAttribute": {
      "abstract": [
        {
          "text": "The document type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSDocumentTypeDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSDocumentTypeDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDocumentTypeDocumentAttribute",
      "type": "topic",
      "url": "/documentation/uikit/nsdocumenttypedocumentattribute"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSHyphenationFactorDocumentAttribute": {
      "abstract": [
        {
          "text": "The hyphenation factor of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSHyphenationFactorDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSHyphenationFactorDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSHyphenationFactorDocumentAttribute",
      "type": "topic",
      "url": "/documentation/uikit/nshyphenationfactordocumentattribute"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSPaperMarginDocumentAttribute": {
      "abstract": [
        {
          "text": "The paper margin of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPaperMarginDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSPaperMarginDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPaperMarginDocumentAttribute",
      "type": "topic",
      "url": "/documentation/uikit/nspapermargindocumentattribute"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSPaperSizeDocumentAttribute": {
      "abstract": [
        {
          "text": "The paper size for the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPaperSizeDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSPaperSizeDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPaperSizeDocumentAttribute",
      "type": "topic",
      "url": "/documentation/uikit/nspapersizedocumentattribute"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSReadOnlyDocumentAttribute": {
      "abstract": [
        {
          "text": "An indication of whether the document is read-only.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSReadOnlyDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSReadOnlyDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSReadOnlyDocumentAttribute",
      "type": "topic",
      "url": "/documentation/uikit/nsreadonlydocumentattribute"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSSourceTextScalingDocumentAttribute": {
      "abstract": [
        {
          "text": "The text-scaling mode you used when creating the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSSourceTextScalingDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSSourceTextScalingDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSourceTextScalingDocumentAttribute",
      "type": "topic",
      "url": "/documentation/uikit/nssourcetextscalingdocumentattribute"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutSectionKey": {
      "abstract": [
        {
          "text": "Constants for the text layout sections document attribute key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutSectionKey"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutSectionKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextLayoutSectionKey",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutsectionkey"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutSectionsAttribute": {
      "abstract": [
        {
          "text": "The layout orientations for each section.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutSectionsAttribute"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutSectionsAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextLayoutSectionsAttribute",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutsectionsattribute"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextScalingDocumentAttribute": {
      "abstract": [
        {
          "text": "The text-scaling mode to use when displaying the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextScalingDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextScalingDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextScalingDocumentAttribute",
      "type": "topic",
      "url": "/documentation/uikit/nstextscalingdocumentattribute"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextScalingType": {
      "abstract": [
        {
          "text": "Constants that specify the text scaling.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextScalingType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextScalingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextScalingType"
        }
      ],
      "role": "symbol",
      "title": "NSTextScalingType",
      "type": "topic",
      "url": "/documentation/uikit/nstextscalingtype"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSViewModeDocumentAttribute": {
      "abstract": [
        {
          "text": "The view mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSViewModeDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSViewModeDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSViewModeDocumentAttribute",
      "type": "topic",
      "url": "/documentation/uikit/nsviewmodedocumentattribute"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSViewSizeDocumentAttribute": {
      "abstract": [
        {
          "text": "The view size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSViewSizeDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSViewSizeDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSViewSizeDocumentAttribute",
      "type": "topic",
      "url": "/documentation/uikit/nsviewsizedocumentattribute"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSViewZoomDocumentAttribute": {
      "abstract": [
        {
          "text": "The view zoom.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSViewZoomDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSViewZoomDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSViewZoomDocumentAttribute",
      "type": "topic",
      "url": "/documentation/uikit/nsviewzoomdocumentattribute"
    },
    "doc://com.apple.uikit/documentation/UIKit/document-reading-option-keys": {
      "abstract": [
        {
          "text": "Keys for constructing an attributed string from data on disk.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/document-reading-option-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Document reading option keys",
      "type": "topic",
      "url": "/documentation/uikit/document-reading-option-keys"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-document-wide-attributes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/document-reading-option-keys",
        "doc://com.apple.uikit/documentation/UIKit/NSAttributedStringDocumentType",
        "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutSectionKey",
        "doc://com.apple.uikit/documentation/UIKit/NSTextScalingType"
      ],
      "title": "Getting document-wide attributes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-document-type-keys",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSDocumentTypeDocumentAttribute",
        "doc://com.apple.documentation/documentation/AppKit/NSFileTypeDocumentAttribute",
        "doc://com.apple.documentation/documentation/AppKit/NSTextEncodingNameDocumentAttribute"
      ],
      "title": "Getting document type keys"
    },
    {
      "anchor": "Getting-document-metadata-keys",
      "identifiers": [
        "doc://com.apple.documentation/documentation/AppKit/NSAuthorDocumentAttribute",
        "doc://com.apple.documentation/documentation/AppKit/NSCategoryDocumentAttribute",
        "doc://com.apple.uikit/documentation/UIKit/NSCharacterEncodingDocumentAttribute",
        "doc://com.apple.uikit/documentation/UIKit/NSCocoaVersionDocumentAttribute",
        "doc://com.apple.documentation/documentation/AppKit/NSCommentDocumentAttribute",
        "doc://com.apple.documentation/documentation/AppKit/NSCompanyDocumentAttribute",
        "doc://com.apple.documentation/documentation/AppKit/NSConvertedDocumentAttribute",
        "doc://com.apple.documentation/documentation/AppKit/NSCopyrightDocumentAttribute",
        "doc://com.apple.documentation/documentation/AppKit/NSCreationTimeDocumentAttribute",
        "doc://com.apple.documentation/documentation/AppKit/NSEditorDocumentAttribute",
        "doc://com.apple.documentation/documentation/AppKit/NSKeywordsDocumentAttribute",
        "doc://com.apple.documentation/documentation/AppKit/NSManagerDocumentAttribute",
        "doc://com.apple.documentation/documentation/AppKit/NSModificationTimeDocumentAttribute",
        "doc://com.apple.uikit/documentation/UIKit/NSReadOnlyDocumentAttribute",
        "doc://com.apple.documentation/documentation/AppKit/NSSubjectDocumentAttribute",
        "doc://com.apple.documentation/documentation/AppKit/NSTitleDocumentAttribute"
      ],
      "title": "Getting document metadata keys"
    },
    {
      "anchor": "Getting-document-appearance-keys",
      "identifiers": [
        "doc://com.apple.documentation/documentation/AppKit/NSAppearanceDocumentAttribute",
        "doc://com.apple.uikit/documentation/UIKit/NSBackgroundColorDocumentAttribute",
        "doc://com.apple.documentation/documentation/AppKit/NSBottomMarginDocumentAttribute",
        "doc://com.apple.uikit/documentation/UIKit/NSDefaultFontExcludedDocumentAttribute",
        "doc://com.apple.uikit/documentation/UIKit/NSDefaultTabIntervalDocumentAttribute",
        "doc://com.apple.documentation/documentation/AppKit/NSExcludedElementsDocumentAttribute",
        "doc://com.apple.uikit/documentation/UIKit/NSHyphenationFactorDocumentAttribute",
        "doc://com.apple.documentation/documentation/AppKit/NSLeftMarginDocumentAttribute",
        "doc://com.apple.uikit/documentation/UIKit/NSPaperMarginDocumentAttribute",
        "doc://com.apple.uikit/documentation/UIKit/NSPaperSizeDocumentAttribute",
        "doc://com.apple.documentation/documentation/AppKit/NSPrefixSpacesDocumentAttribute",
        "doc://com.apple.documentation/documentation/AppKit/NSRightMarginDocumentAttribute",
        "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutSectionsAttribute",
        "doc://com.apple.documentation/documentation/AppKit/NSTopMarginDocumentAttribute",
        "doc://com.apple.uikit/documentation/UIKit/NSViewModeDocumentAttribute",
        "doc://com.apple.uikit/documentation/UIKit/NSViewSizeDocumentAttribute",
        "doc://com.apple.uikit/documentation/UIKit/NSViewZoomDocumentAttribute"
      ],
      "title": "Getting document appearance keys"
    },
    {
      "anchor": "Getting-the-font-scaling-options",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSSourceTextScalingDocumentAttribute",
        "doc://com.apple.uikit/documentation/UIKit/NSTextScalingDocumentAttribute"
      ],
      "title": "Getting the font-scaling options"
    },
    {
      "anchor": "Getting-the-default-attributes",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSDefaultAttributesDocumentAttribute"
      ],
      "title": "Getting the default attributes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextScalingType/title",
          "value": "NSTextScalingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextScalingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextScalingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextScalingType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextScalingType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/nsattributedstringdocumentattributekey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
