{
  "abstract": [
    {
      "text": "An action that causes a paragraph break.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterParagraphBreakAction"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@NSControlCharacterZeroAdvancementAction@NSControlCharacterParagraphBreakAction",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSControlCharacterParagraphBreakAction"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSControlCharacterParagraphBreakAction"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "7.0",
        "name": "iOS",
        "renamed": "NSLayoutManager.ControlCharacterAction.paragraphBreak",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "introducedAt": "7.0",
        "name": "iPadOS",
        "renamed": "NSLayoutManager.ControlCharacterAction.paragraphBreak",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "renamed": "NSLayoutManager.ControlCharacterAction.paragraphBreak",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "9.0",
        "name": "tvOS",
        "renamed": "NSLayoutManager.ControlCharacterAction.paragraphBreak",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSControlCharacterParagraphBreakAction"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSControlCharacterParagraphBreakAction"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The value in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSParagraphStyle/firstLineHeadIndent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is used for the following glyph.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterContainerBreakAction": {
      "abstract": [
        {
          "text": "A character that causes a break in layout.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSControlCharacterContainerBreakAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterContainerBreakAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSControlCharacterContainerBreakAction"
        }
      ],
      "role": "symbol",
      "title": "NSControlCharacterContainerBreakAction",
      "type": "topic",
      "url": "/documentation/uikit/nscontrolcharactercontainerbreakaction"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterHorizontalTabAction": {
      "abstract": [
        {
          "text": "An action that inserts a horizontal tab.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSControlCharacterHorizontalTabAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterHorizontalTabAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSControlCharacterHorizontalTabAction"
        }
      ],
      "role": "symbol",
      "title": "NSControlCharacterHorizontalTabAction",
      "type": "topic",
      "url": "/documentation/uikit/nscontrolcharacterhorizontaltabaction"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterLineBreakAction": {
      "abstract": [
        {
          "text": "An action that causes a line break.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSControlCharacterLineBreakAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterLineBreakAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSControlCharacterLineBreakAction"
        }
      ],
      "role": "symbol",
      "title": "NSControlCharacterLineBreakAction",
      "type": "topic",
      "url": "/documentation/uikit/nscontrolcharacterlinebreakaction"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterParagraphBreakAction": {
      "abstract": [
        {
          "text": "An action that causes a paragraph break.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSControlCharacterParagraphBreakAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterParagraphBreakAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSControlCharacterParagraphBreakAction"
        }
      ],
      "role": "symbol",
      "title": "NSControlCharacterParagraphBreakAction",
      "type": "topic",
      "url": "/documentation/uikit/nscontrolcharacterparagraphbreakaction"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterWhitespaceAction": {
      "abstract": [
        {
          "text": "An action that programmatically changes the white space around the glyph.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSControlCharacterWhitespaceAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterWhitespaceAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSControlCharacterWhitespaceAction"
        }
      ],
      "role": "symbol",
      "title": "NSControlCharacterWhitespaceAction",
      "type": "topic",
      "url": "/documentation/uikit/nscontrolcharacterwhitespaceaction"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterZeroAdvancementAction": {
      "abstract": [
        {
          "text": "An action that removes the glyph from layout.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSControlCharacterZeroAdvancementAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterZeroAdvancementAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSControlCharacterZeroAdvancementAction"
        }
      ],
      "role": "symbol",
      "title": "NSControlCharacterZeroAdvancementAction",
      "type": "topic",
      "url": "/documentation/uikit/nscontrolcharacterzeroadvancementaction"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSParagraphStyle/firstLineHeadIndent": {
      "abstract": [
        {
          "text": "The indentation of the first line of the paragraph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "firstLineHeadIndent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSParagraphStyle/firstLineHeadIndent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "firstLineHeadIndent"
        }
      ],
      "role": "symbol",
      "title": "firstLineHeadIndent",
      "type": "topic",
      "url": "/documentation/uikit/nsparagraphstyle/firstlineheadindent"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterContainerBreakAction",
        "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterHorizontalTabAction",
        "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterLineBreakAction",
        "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterWhitespaceAction",
        "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterZeroAdvancementAction"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.0",
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.0",
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSControlCharacterParagraphBreakAction"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSControlCharacterParagraphBreakAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterContainerBreakAction",
                "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterHorizontalTabAction",
                "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterLineBreakAction",
                "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterWhitespaceAction",
                "doc://com.apple.uikit/documentation/UIKit/NSControlCharacterZeroAdvancementAction"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "NSControlCharacterParagraphBreakAction"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSControlCharacterParagraphBreakAction/title",
          "value": "NSControlCharacterParagraphBreakAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSControlCharacterParagraphBreakAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSControlCharacterParagraphBreakAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSParagraphStyle~1firstLineHeadIndent/title",
          "value": "firstLineHeadIndent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSParagraphStyle~1firstLineHeadIndent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "firstLineHeadIndent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSControlCharacterLineBreakAction/title",
          "value": "NSControlCharacterLineBreakAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSControlCharacterLineBreakAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSControlCharacterLineBreakAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSControlCharacterContainerBreakAction/title",
          "value": "NSControlCharacterContainerBreakAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSControlCharacterContainerBreakAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSControlCharacterContainerBreakAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSControlCharacterZeroAdvancementAction/title",
          "value": "NSControlCharacterZeroAdvancementAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSControlCharacterZeroAdvancementAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSControlCharacterZeroAdvancementAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSControlCharacterWhitespaceAction/title",
          "value": "NSControlCharacterWhitespaceAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSControlCharacterWhitespaceAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSControlCharacterWhitespaceAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSControlCharacterHorizontalTabAction/title",
          "value": "NSControlCharacterHorizontalTabAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSControlCharacterHorizontalTabAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSControlCharacterHorizontalTabAction"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/nscontrolcharacterparagraphbreakaction"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/nscontrolcharacterparagraphbreakaction"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
