{"abstract":[{"text":"An item that’s currently visible within the bounds of a section.","type":"text"}],"variants":[{"paths":["/documentation/uikit/nscollectionlayoutvisibleitem"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/nscollectionlayoutvisibleitem"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"NSCollectionLayoutVisibleItem","kind":"identifier"}],"externalID":"c:objc(pl)NSCollectionLayoutVisibleItem","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"NSCollectionLayoutVisibleItem","kind":"identifier"}],"symbolKind":"protocol","title":"NSCollectionLayoutVisibleItem","platforms":[{"name":"iOS","deprecated":false,"introducedAt":"13.0","unavailable":false,"beta":false},{"name":"iPadOS","deprecated":false,"introducedAt":"13.0","unavailable":false,"beta":false},{"name":"Mac Catalyst","deprecated":false,"introducedAt":"13.1","unavailable":false,"beta":false},{"name":"tvOS","deprecated":false,"introducedAt":"13.0","unavailable":false,"beta":false},{"name":"visionOS","deprecated":false,"introducedAt":"1.0","unavailable":false,"beta":false}],"modules":[{"name":"UIKit"}],"roleHeading":"Protocol"},"seeAlsoSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSectionVisibleItemsInvalidationHandler","doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem","doc://com.apple.uikit/documentation/UIKit/UICollectionViewFocusUpdateContext","doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayoutInvalidationContext"],"anchor":"Layout-updates","title":"Layout updates","generated":true}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/name","doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/representedElementKind","doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/representedElementCategory"],"anchor":"Identifying-the-item","title":"Identifying the item"},{"identifiers":["doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/indexPath"],"anchor":"Getting-the-index-path","title":"Getting the index path"},{"identifiers":["doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/alpha","doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/isHidden"],"anchor":"Configuring-appearance","title":"Configuring appearance"},{"identifiers":["doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/frame","doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/bounds","doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/center","doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/transform","doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/transform3D"],"anchor":"Configuring-position","title":"Configuring position"},{"identifiers":["doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/zIndex"],"anchor":"Specifying-stacking-order","title":"Specifying stacking order"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionLayoutVisibleItem","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UIDynamicItem","text":"UIDynamicItem","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDynamicItem"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"},{"content":[{"text":"Overview","anchor":"overview","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"A visible item represents an item in a collection view that’s currently visible onscreen, such as a cell, supplementary view, or decoration. You access a specific section’s visible items in its visible item invalidation handler ("},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSectionVisibleItemsInvalidationHandler","type":"reference"},{"type":"text","text":"), stored in the "},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSection/visibleItemsInvalidationHandler","type":"reference"},{"type":"text","text":" property. The handler is called before each layout cycle, any time an animation occurs in that section due to changes such as adding or removing items, scrolling the section, or rotating the device."}],"type":"paragraph"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem"},"sections":[],"relationshipsSections":[{"identifiers":["doc://com.externally.resolved.symbol/c:objc(pl)NSObject","doc://com.apple.uikit/documentation/UIKit/UIDynamicItem"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"references":{"doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayoutInvalidationContext":{"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayoutInvalidationContext","type":"topic","url":"/documentation/uikit/uicollectionviewlayoutinvalidationcontext","title":"UICollectionViewLayoutInvalidationContext","role":"symbol","navigatorTitle":[{"text":"UICollectionViewLayoutInvalidationContext","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UICollectionViewLayoutInvalidationContext","kind":"identifier"}],"abstract":[{"type":"text","text":"A context object that declares which parts of your layout need to be updated when the layout is invalidated."}]},"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/representedElementCategory":{"abstract":[{"text":"A category that identifies the item, such as decoration or supplementary view.","type":"text"}],"url":"/documentation/uikit/nscollectionlayoutvisibleitem/representedelementcategory","role":"symbol","type":"topic","navigatorTitle":[{"text":"representedElementCategory","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"representedElementCategory","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"ElementCategory","preciseIdentifier":"c:@E@UICollectionElementCategory","kind":"typeIdentifier"}],"kind":"symbol","required":true,"title":"representedElementCategory","identifier":"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/representedElementCategory"},"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/transform3D":{"abstract":[{"text":"The 3D transform applied to the item.","type":"text"}],"url":"/documentation/uikit/nscollectionlayoutvisibleitem/transform3d","role":"symbol","type":"topic","navigatorTitle":[{"text":"transform3D","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transform3D","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CATransform3D","preciseIdentifier":"c:@S@CATransform3D","kind":"typeIdentifier"}],"kind":"symbol","required":true,"title":"transform3D","identifier":"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/transform3D"},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"title":"NSObjectProtocol","type":"topic","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","role":"symbol","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"kind":"symbol","url":"/documentation/objectivec/nsobjectprotocol"},"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/name":{"abstract":[{"text":"The name of the item.","type":"text"}],"url":"/documentation/uikit/nscollectionlayoutvisibleitem/name","role":"symbol","type":"topic","navigatorTitle":[{"text":"name","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"kind":"symbol","required":true,"title":"name","identifier":"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/name"},"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/representedElementKind":{"abstract":[{"text":"A string that identifies the type of item.","type":"text"}],"url":"/documentation/uikit/nscollectionlayoutvisibleitem/representedelementkind","role":"symbol","type":"topic","navigatorTitle":[{"text":"representedElementKind","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"representedElementKind","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","required":true,"title":"representedElementKind","identifier":"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/representedElementKind"},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UICollectionViewUpdateItem"}],"kind":"symbol","title":"UICollectionViewUpdateItem","role":"symbol","abstract":[{"type":"text","text":"An object that describes a single change to make to an item in a collection view."}],"navigatorTitle":[{"kind":"identifier","text":"UICollectionViewUpdateItem"}],"type":"topic","url":"/documentation/uikit/uicollectionviewupdateitem"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/frame":{"abstract":[{"text":"The frame rectangle, which describes the item’s location and size in its section’s coordinate system.","type":"text"}],"url":"/documentation/uikit/nscollectionlayoutvisibleitem/frame","role":"symbol","type":"topic","navigatorTitle":[{"text":"frame","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"frame","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"}],"kind":"symbol","required":true,"title":"frame","identifier":"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/frame"},"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionLayoutVisibleItem","kind":"identifier"}],"url":"/documentation/uikit/nscollectionlayoutvisibleitem","abstract":[{"text":"An item that’s currently visible within the bounds of a section.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem","kind":"symbol","role":"symbol","title":"NSCollectionLayoutVisibleItem","navigatorTitle":[{"text":"NSCollectionLayoutVisibleItem","kind":"identifier"}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/indexPath":{"url":"/documentation/uikit/nscollectionlayoutvisibleitem/indexpath","abstract":[{"text":"The index path of the item.","type":"text"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/indexPath","navigatorTitle":[{"kind":"identifier","text":"indexPath"}],"required":true,"role":"symbol","title":"indexPath","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"}]},"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSection/visibleItemsInvalidationHandler":{"abstract":[{"text":"A closure called before each layout cycle to allow modification of the items in the section immediately before they’re displayed.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"visibleItemsInvalidationHandler"}],"url":"/documentation/uikit/nscollectionlayoutsection/visibleitemsinvalidationhandler","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"visibleItemsInvalidationHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCollectionLayoutSectionVisibleItemsInvalidationHandler","preciseIdentifier":"c:@T@NSCollectionLayoutSectionVisibleItemsInvalidationHandler"},{"kind":"text","text":"?"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSection/visibleItemsInvalidationHandler","title":"visibleItemsInvalidationHandler"},"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/isHidden":{"url":"/documentation/uikit/nscollectionlayoutvisibleitem/ishidden","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isHidden","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","abstract":[{"type":"text","text":"A Boolean value that determines whether the item is hidden."}],"required":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/isHidden","title":"isHidden","navigatorTitle":[{"text":"hidden","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/alpha":{"url":"/documentation/uikit/nscollectionlayoutvisibleitem/alpha","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alpha","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"type":"topic","abstract":[{"type":"text","text":"The transparency of the item."}],"required":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/alpha","title":"alpha","navigatorTitle":[{"text":"alpha","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIDynamicItem":{"url":"/documentation/uikit/uidynamicitem","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIDynamicItem","kind":"identifier"}],"abstract":[{"type":"text","text":"A set of methods that can make a custom object eligible to participate in UIKit Dynamics."}],"kind":"symbol","navigatorTitle":[{"text":"UIDynamicItem","kind":"identifier"}],"type":"topic","role":"symbol","title":"UIDynamicItem","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDynamicItem"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/zIndex":{"abstract":[{"type":"text","text":"The vertical stacking order of the item in relation to other items in the section."}],"url":"/documentation/uikit/nscollectionlayoutvisibleitem/zindex","role":"symbol","type":"topic","navigatorTitle":[{"text":"zIndex","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"zIndex","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"kind":"symbol","required":true,"title":"zIndex","identifier":"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/zIndex"},"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/bounds":{"abstract":[{"type":"text","text":"The bounds rectangle, which describes the item’s location and size in its own coordinate system."}],"url":"/documentation/uikit/nscollectionlayoutvisibleitem/bounds","role":"symbol","type":"topic","navigatorTitle":[{"text":"bounds","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bounds","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"}],"kind":"symbol","required":true,"title":"bounds","identifier":"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/bounds"},"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSectionVisibleItemsInvalidationHandler":{"type":"topic","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSectionVisibleItemsInvalidationHandler","kind":"symbol","title":"NSCollectionLayoutSectionVisibleItemsInvalidationHandler","abstract":[{"text":"A closure called before each layout cycle to allow modification of items in a section immediately before they’re displayed.","type":"text"}],"url":"/documentation/uikit/nscollectionlayoutsectionvisibleitemsinvalidationhandler","navigatorTitle":[{"text":"NSCollectionLayoutSectionVisibleItemsInvalidationHandler","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionLayoutSectionVisibleItemsInvalidationHandler","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/transform":{"abstract":[{"type":"text","text":"The transform applied to the item, relative to the center of its bounds."}],"url":"/documentation/uikit/nscollectionlayoutvisibleitem/transform","role":"symbol","type":"topic","navigatorTitle":[{"text":"transform","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transform","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGAffineTransform","text":"CGAffineTransform","kind":"typeIdentifier"}],"kind":"symbol","required":true,"title":"transform","identifier":"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/transform"},"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/center":{"role":"symbol","abstract":[{"type":"text","text":"The center point of the item’s frame rectangle."}],"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"center","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"}],"url":"/documentation/uikit/nscollectionlayoutvisibleitem/center","navigatorTitle":[{"kind":"identifier","text":"center"}],"title":"center","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/center","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewFocusUpdateContext":{"abstract":[{"text":"A context object that stores information specific to a focus update in a collection view.","type":"text"}],"url":"/documentation/uikit/uicollectionviewfocusupdatecontext","navigatorTitle":[{"kind":"identifier","text":"UICollectionViewFocusUpdateContext"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UICollectionViewFocusUpdateContext"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewFocusUpdateContext","title":"UICollectionViewFocusUpdateContext","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"deprecated":false,"name":"iOS","beta":false,"unavailable":false,"introducedAt":"13.0"},{"deprecated":false,"name":"iPadOS","beta":false,"unavailable":false,"introducedAt":"13.0"},{"deprecated":false,"name":"Mac Catalyst","beta":false,"unavailable":false,"introducedAt":"13.1"},{"deprecated":false,"name":"tvOS","beta":false,"unavailable":false,"introducedAt":"13.0"},{"deprecated":false,"name":"visionOS","beta":false,"unavailable":false,"introducedAt":"1.0"}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Protocol","op":"replace"},{"path":"/metadata/title","value":"NSCollectionLayoutVisibleItem","op":"replace"},{"path":"/metadata/symbolKind","value":"protocol","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"identifier","text":"NSCollectionLayoutVisibleItem"}],"op":"replace"},{"path":"/metadata/navigatorTitle","value":[{"text":"NSCollectionLayoutVisibleItem","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"op":"replace"},{"path":"/topicSections","value":[{"title":"Identifying the item","anchor":"Identifying-the-item","identifiers":["doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/name","doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/representedElementKind","doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/representedElementCategory"]},{"title":"Getting the index path","anchor":"Getting-the-index-path","identifiers":["doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/indexPath"]},{"title":"Configuring appearance","anchor":"Configuring-appearance","identifiers":["doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/alpha","doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/isHidden"]},{"title":"Configuring position","anchor":"Configuring-position","identifiers":["doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/frame","doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/bounds","doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/center","doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/transform","doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/transform3D"]},{"anchor":"Specifying-stacking-order","identifiers":["doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutVisibleItem/zIndex"],"title":"Specifying stacking order"}],"op":"replace"},{"path":"/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc://com.externally.resolved.symbol/c:objc(pl)NSObject","doc://com.apple.uikit/documentation/UIKit/UIDynamicItem"],"type":"inheritsFrom"}],"op":"replace"},{"path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSectionVisibleItemsInvalidationHandler","doc://com.apple.uikit/documentation/UIKit/UICollectionViewUpdateItem","doc://com.apple.uikit/documentation/UIKit/UICollectionViewFocusUpdateContext","doc://com.apple.uikit/documentation/UIKit/UICollectionViewLayoutInvalidationContext"],"anchor":"Layout-updates","generated":true,"title":"Layout updates"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSCollectionLayoutVisibleItem"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIDynamicItem","text":"UIDynamicItem","identifier":"doc://com.apple.uikit/documentation/UIKit/UIDynamicItem"},{"kind":"text","text":">"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayoutInvalidationContext/title","value":"UICollectionViewLayoutInvalidationContext","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayoutInvalidationContext/fragments","value":[{"text":"UICollectionViewLayoutInvalidationContext","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewLayoutInvalidationContext/navigatorTitle","value":[{"text":"UICollectionViewLayoutInvalidationContext","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutVisibleItem~1representedElementCategory/title","value":"representedElementCategory","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutVisibleItem~1representedElementCategory/fragments","value":[{"text":"representedElementCategory","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutVisibleItem~1transform3D/title","value":"transform3D","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutVisibleItem~1transform3D/fragments","value":[{"kind":"identifier","text":"transform3D"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title","value":"NSObject","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutVisibleItem~1name/title","value":"name","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutVisibleItem~1name/fragments","op":"replace","value":[{"text":"name","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutVisibleItem~1representedElementKind/title","op":"replace","value":"representedElementKind"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutVisibleItem~1representedElementKind/fragments","op":"replace","value":[{"text":"representedElementKind","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewUpdateItem/title","op":"replace","value":"UICollectionViewUpdateItem"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewUpdateItem/fragments","op":"replace","value":[{"text":"UICollectionViewUpdateItem","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewUpdateItem/navigatorTitle","op":"replace","value":[{"text":"UICollectionViewUpdateItem","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutVisibleItem~1frame/title","op":"replace","value":"frame"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutVisibleItem~1frame/fragments","op":"replace","value":[{"kind":"identifier","text":"frame"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutVisibleItem/title","op":"replace","value":"NSCollectionLayoutVisibleItem"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutVisibleItem/fragments","op":"replace","value":[{"kind":"identifier","text":"NSCollectionLayoutVisibleItem"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutVisibleItem/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSCollectionLayoutVisibleItem"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutVisibleItem~1indexPath/title","op":"replace","value":"indexPath"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutVisibleItem~1indexPath/fragments","op":"replace","value":[{"text":"indexPath","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutSection~1visibleItemsInvalidationHandler/title","op":"replace","value":"visibleItemsInvalidationHandler"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutSection~1visibleItemsInvalidationHandler/fragments","op":"replace","value":[{"text":"visibleItemsInvalidationHandler","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutVisibleItem~1isHidden/title","op":"replace","value":"hidden"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutVisibleItem~1isHidden/fragments","op":"replace","value":[{"kind":"identifier","text":"hidden"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutVisibleItem~1alpha/title","op":"replace","value":"alpha"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutVisibleItem~1alpha/fragments","op":"replace","value":[{"text":"alpha","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicItem/title","op":"replace","value":"UIDynamicItem"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicItem/fragments","op":"replace","value":[{"kind":"identifier","text":"UIDynamicItem"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicItem/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIDynamicItem"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutVisibleItem~1zIndex/title","op":"replace","value":"zIndex"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutVisibleItem~1zIndex/fragments","op":"replace","value":[{"kind":"identifier","text":"zIndex"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutVisibleItem~1bounds/title","op":"replace","value":"bounds"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutVisibleItem~1bounds/fragments","op":"replace","value":[{"kind":"identifier","text":"bounds"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutSectionVisibleItemsInvalidationHandler/title","op":"replace","value":"NSCollectionLayoutSectionVisibleItemsInvalidationHandler"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutSectionVisibleItemsInvalidationHandler/fragments","op":"replace","value":[{"kind":"identifier","text":"NSCollectionLayoutSectionVisibleItemsInvalidationHandler"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutSectionVisibleItemsInvalidationHandler/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NSCollectionLayoutSectionVisibleItemsInvalidationHandler"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutVisibleItem~1transform/title","op":"replace","value":"transform"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutVisibleItem~1transform/fragments","op":"replace","value":[{"kind":"identifier","text":"transform"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutVisibleItem~1center/title","op":"replace","value":"center"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutVisibleItem~1center/fragments","op":"replace","value":[{"text":"center","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewFocusUpdateContext/title","op":"replace","value":"UICollectionViewFocusUpdateContext"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewFocusUpdateContext/fragments","op":"replace","value":[{"kind":"identifier","text":"UICollectionViewFocusUpdateContext"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewFocusUpdateContext/navigatorTitle","op":"replace","value":[{"text":"UICollectionViewFocusUpdateContext","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}