{
  "abstract": [
    {
      "text": "An object used to add headers or footers to a collection view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutBoundarySupplementaryItem"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSCollectionLayoutBoundarySupplementaryItem",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSCollectionLayoutBoundarySupplementaryItem"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSCollectionLayoutBoundarySupplementaryItem"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NSCollectionLayoutBoundarySupplementaryItem"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutBoundarySupplementaryItem"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A boundary supplementary item is a specialized type of supplementary item (",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSupplementaryItem",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "). You use boundary supplementary items to add headers or footers to a section of a collection view or the entire collection view.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Each type of supplementary item must have a unique element kind. Consider tracking these strings together in a way that makes it straightforward to identify each element, for example:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "struct ElementKind {",
                    "    static let badge = \"badge-element-kind\"",
                    "    static let background = \"background-element-kind\"",
                    "    static let sectionHeader = \"section-header-element-kind\"",
                    "    static let sectionFooter = \"section-footer-element-kind\"",
                    "    static let layoutHeader = \"layout-header-element-kind\"",
                    "    static let layoutFooter = \"layout-footer-element-kind\"",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "NSString* const ELEMENT_KIND_BADGE = @\"badge-element-kind\";",
                    "NSString* const ELEMENT_KIND_BACKGROUND = @\"background-element-kind\";",
                    "NSString* const ELEMENT_KIND_SECTION_HEADER = @\"section-header-element-kind\";",
                    "NSString* const ELEMENT_KIND_SECTION_FOOTER = @\"section-footer-element-kind\";",
                    "NSString* const ELEMENT_KIND_LAYOUT_HEADER = @\"layout-header-element-kind\";",
                    "NSString* const ELEMENT_KIND_LAYOUT_FOOTER = @\"layout-footer-element-kind\";"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "Add boundary supplementary items to a section by setting that section’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSection/boundarySupplementaryItems",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "let section = NSCollectionLayoutSection(group: group)",
                    "",
                    "let headerFooterSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0),",
                    "                                             heightDimension: .estimated(44))",
                    "    ",
                    "let sectionHeader = NSCollectionLayoutBoundarySupplementaryItem(layoutSize: headerFooterSize,",
                    "                                                               elementKind: ElementKind.sectionHeader,",
                    "                                                                 alignment: .top)",
                    "let sectionFooter = NSCollectionLayoutBoundarySupplementaryItem(layoutSize: headerFooterSize,",
                    "                                                               elementKind: ElementKind.sectionFooter,",
                    "                                                                 alignment: .bottom)",
                    "    ",
                    "section.boundarySupplementaryItems = [sectionHeader, sectionFooter]"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "NSCollectionLayoutSection *section = [NSCollectionLayoutSection sectionWithGroup:group];",
                    "",
                    "NSCollectionLayoutSize *headerFooterSize = [NSCollectionLayoutSize sizeWithWidthDimension:[NSCollectionLayoutDimension fractionalWidthDimension:1.0] heightDimension:[NSCollectionLayoutDimension absoluteDimension:44.0]];",
                    "",
                    "NSCollectionLayoutBoundarySupplementaryItem *sectionHeader = [NSCollectionLayoutBoundarySupplementaryItem boundarySupplementaryItemWithLayoutSize: headerFooterSize elementKind: ELEMENT_KIND_SECTION_HEADER alignment: NSRectAlignmentTop];",
                    "",
                    "NSCollectionLayoutBoundarySupplementaryItem *sectionFooter = [NSCollectionLayoutBoundarySupplementaryItem boundarySupplementaryItemWithLayoutSize: headerFooterSize elementKind: ELEMENT_KIND_SECTION_FOOTER alignment: NSRectAlignmentBottom];",
                    "",
                    "[section setBoundarySupplementaryItems: @[sectionHeader, sectionFooter]];"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutAnchor": {
      "abstract": [
        {
          "text": "An object that defines how to attach a supplementary item to an item in a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCollectionLayoutAnchor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutAnchor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionLayoutAnchor"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionLayoutAnchor",
      "type": "topic",
      "url": "/documentation/uikit/nscollectionlayoutanchor"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutBoundarySupplementaryItem": {
      "abstract": [
        {
          "text": "An object used to add headers or footers to a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCollectionLayoutBoundarySupplementaryItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutBoundarySupplementaryItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionLayoutBoundarySupplementaryItem"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionLayoutBoundarySupplementaryItem",
      "type": "topic",
      "url": "/documentation/uikit/nscollectionlayoutboundarysupplementaryitem"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutBoundarySupplementaryItem/alignment": {
      "abstract": [
        {
          "text": "The alignment of the boundary supplementary item relative to the section or layout it’s attached to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alignment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSRectAlignment",
          "text": "NSRectAlignment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutBoundarySupplementaryItem/alignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "alignment"
        }
      ],
      "role": "symbol",
      "title": "alignment",
      "type": "topic",
      "url": "/documentation/uikit/nscollectionlayoutboundarysupplementaryitem/alignment"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutBoundarySupplementaryItem/extendsBoundary": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether a boundary supplementary item extends the content area of the section or layout it’s attached to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extendsBoundary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutBoundarySupplementaryItem/extendsBoundary",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "extendsBoundary"
        }
      ],
      "role": "symbol",
      "title": "extendsBoundary",
      "type": "topic",
      "url": "/documentation/uikit/nscollectionlayoutboundarysupplementaryitem/extendsboundary"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutBoundarySupplementaryItem/init(layoutSize:elementKind:alignment:)": {
      "abstract": [
        {
          "text": "Creates a boundary supplementary item of the specified size and element kind, with an alignment relative to a section or layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "layoutSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCollectionLayoutSize",
          "text": "NSCollectionLayoutSize"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "elementKind"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "alignment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSRectAlignment",
          "text": "NSRectAlignment"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutBoundarySupplementaryItem/init(layoutSize:elementKind:alignment:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "boundarySupplementaryItemWithLayoutSize:elementKind:alignment:"
        }
      ],
      "role": "symbol",
      "title": "init(layoutSize:elementKind:alignment:)",
      "type": "topic",
      "url": "/documentation/uikit/nscollectionlayoutboundarysupplementaryitem/init(layoutsize:elementkind:alignment:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutBoundarySupplementaryItem/init(layoutSize:elementKind:alignment:absoluteOffset:)": {
      "abstract": [
        {
          "text": "Creates a boundary supplementary item of the specified size and element kind, with an alignment relative to a section or layout at an absolute offset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "layoutSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCollectionLayoutSize",
          "text": "NSCollectionLayoutSize"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "elementKind"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "alignment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSRectAlignment",
          "text": "NSRectAlignment"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "absoluteOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutBoundarySupplementaryItem/init(layoutSize:elementKind:alignment:absoluteOffset:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "boundarySupplementaryItemWithLayoutSize:elementKind:alignment:absoluteOffset:"
        }
      ],
      "role": "symbol",
      "title": "init(layoutSize:elementKind:alignment:absoluteOffset:)",
      "type": "topic",
      "url": "/documentation/uikit/nscollectionlayoutboundarysupplementaryitem/init(layoutsize:elementkind:alignment:absoluteoffset:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutBoundarySupplementaryItem/offset": {
      "abstract": [
        {
          "text": "The floating-point value of the boundary supplementary item’s offset from the section or layout it’s attached to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutBoundarySupplementaryItem/offset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "offset"
        }
      ],
      "role": "symbol",
      "title": "offset",
      "type": "topic",
      "url": "/documentation/uikit/nscollectionlayoutboundarysupplementaryitem/offset"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutBoundarySupplementaryItem/pinToVisibleBounds": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether a header or footer is pinned to the top or bottom visible boundary of the section or layout it’s attached to.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pinToVisibleBounds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutBoundarySupplementaryItem/pinToVisibleBounds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pinToVisibleBounds"
        }
      ],
      "role": "symbol",
      "title": "pinToVisibleBounds",
      "type": "topic",
      "url": "/documentation/uikit/nscollectionlayoutboundarysupplementaryitem/pintovisiblebounds"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutDecorationItem": {
      "abstract": [
        {
          "text": "An object used to add a background to a section of a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCollectionLayoutDecorationItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutDecorationItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionLayoutDecorationItem"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionLayoutDecorationItem",
      "type": "topic",
      "url": "/documentation/uikit/nscollectionlayoutdecorationitem"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSection/boundarySupplementaryItems": {
      "abstract": [
        {
          "text": "An array of the supplementary items that are associated with the boundary edges of the section, such as headers and footers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "boundarySupplementaryItems"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCollectionLayoutBoundarySupplementaryItem",
          "text": "NSCollectionLayoutBoundarySupplementaryItem"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSection/boundarySupplementaryItems",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "boundarySupplementaryItems"
        }
      ],
      "role": "symbol",
      "title": "boundarySupplementaryItems",
      "type": "topic",
      "url": "/documentation/uikit/nscollectionlayoutsection/boundarysupplementaryitems"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSupplementaryItem": {
      "abstract": [
        {
          "text": "An object used to add an extra visual decoration to an item in a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCollectionLayoutSupplementaryItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSupplementaryItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionLayoutSupplementaryItem"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionLayoutSupplementaryItem",
      "type": "topic",
      "url": "/documentation/uikit/nscollectionlayoutsupplementaryitem"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSupplementaryItem"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Appearance",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutAnchor",
        "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSupplementaryItem",
        "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutDecorationItem"
      ],
      "title": "Appearance"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-boundary-supplementary-item",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutBoundarySupplementaryItem/init(layoutSize:elementKind:alignment:)",
        "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutBoundarySupplementaryItem/init(layoutSize:elementKind:alignment:absoluteOffset:)"
      ],
      "title": "Creating a boundary supplementary item"
    },
    {
      "anchor": "Specifying-scrolling-behavior",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutBoundarySupplementaryItem/pinToVisibleBounds"
      ],
      "title": "Specifying scrolling behavior"
    },
    {
      "anchor": "Specifying-position",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutBoundarySupplementaryItem/offset",
        "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutBoundarySupplementaryItem/alignment",
        "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutBoundarySupplementaryItem/extendsBoundary"
      ],
      "title": "Specifying position"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSCollectionLayoutBoundarySupplementaryItem"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutBoundarySupplementaryItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutBoundarySupplementaryItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-boundary-supplementary-item",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutBoundarySupplementaryItem/init(layoutSize:elementKind:alignment:)",
                "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutBoundarySupplementaryItem/init(layoutSize:elementKind:alignment:absoluteOffset:)"
              ],
              "title": "Creating a boundary supplementary item"
            },
            {
              "anchor": "Specifying-scrolling-behavior",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutBoundarySupplementaryItem/pinToVisibleBounds"
              ],
              "title": "Specifying scrolling behavior"
            },
            {
              "anchor": "Specifying-position",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutBoundarySupplementaryItem/offset",
                "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutBoundarySupplementaryItem/alignment",
                "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutBoundarySupplementaryItem/extendsBoundary"
              ],
              "title": "Specifying position"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSupplementaryItem"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Appearance",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutAnchor",
                "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSupplementaryItem",
                "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutDecorationItem"
              ],
              "title": "Appearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSCollectionLayoutBoundarySupplementaryItem"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSupplementaryItem",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSCollectionLayoutSupplementaryItem",
                    "text": "NSCollectionLayoutSupplementaryItem"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutBoundarySupplementaryItem~1alignment/title",
          "value": "alignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutBoundarySupplementaryItem~1alignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "alignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutSection~1boundarySupplementaryItems/title",
          "value": "boundarySupplementaryItems"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutSection~1boundarySupplementaryItems/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "boundarySupplementaryItems"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutSupplementaryItem/title",
          "value": "NSCollectionLayoutSupplementaryItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutSupplementaryItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutSupplementaryItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutSupplementaryItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutSupplementaryItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutBoundarySupplementaryItem/title",
          "value": "NSCollectionLayoutBoundarySupplementaryItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutBoundarySupplementaryItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutBoundarySupplementaryItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutBoundarySupplementaryItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutBoundarySupplementaryItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutBoundarySupplementaryItem~1offset/title",
          "value": "offset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutBoundarySupplementaryItem~1offset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "offset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutBoundarySupplementaryItem~1pinToVisibleBounds/title",
          "value": "pinToVisibleBounds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutBoundarySupplementaryItem~1pinToVisibleBounds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pinToVisibleBounds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutBoundarySupplementaryItem~1init(layoutSize:elementKind:alignment:absoluteOffset:)/title",
          "value": "boundarySupplementaryItemWithLayoutSize:elementKind:alignment:absoluteOffset:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutBoundarySupplementaryItem~1init(layoutSize:elementKind:alignment:absoluteOffset:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "boundarySupplementaryItemWithLayoutSize:elementKind:alignment:absoluteOffset:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutAnchor/title",
          "value": "NSCollectionLayoutAnchor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutAnchor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutAnchor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutAnchor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutBoundarySupplementaryItem~1extendsBoundary/title",
          "value": "extendsBoundary"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutBoundarySupplementaryItem~1extendsBoundary/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "extendsBoundary"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutDecorationItem/title",
          "value": "NSCollectionLayoutDecorationItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutDecorationItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutDecorationItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutDecorationItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutDecorationItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutBoundarySupplementaryItem~1init(layoutSize:elementKind:alignment:)/title",
          "value": "boundarySupplementaryItemWithLayoutSize:elementKind:alignment:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutBoundarySupplementaryItem~1init(layoutSize:elementKind:alignment:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "boundarySupplementaryItemWithLayoutSize:elementKind:alignment:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/nscollectionlayoutboundarysupplementaryitem"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/nscollectionlayoutboundarysupplementaryitem"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
