{
  "abstract": [
    {
      "text": "A closure that creates and returns each of the custom group’s items.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutGroupCustomItemProvider"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@NSCollectionLayoutGroupCustomItemProvider",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSCollectionLayoutGroupCustomItemProvider"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSCollectionLayoutGroupCustomItemProvider"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "NSCollectionLayoutGroupCustomItemProvider"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutGroupCustomItemProvider"
            },
            {
              "kind": "text",
              "text": " = (any "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutEnvironment",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSCollectionLayoutEnvironment",
              "text": "NSCollectionLayoutEnvironment"
            },
            {
              "kind": "text",
              "text": ") -> ["
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutGroupCustomItem",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSCollectionLayoutGroupCustomItem",
              "text": "NSCollectionLayoutGroupCustomItem"
            },
            {
              "kind": "text",
              "text": "]"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You use a custom item provider to supply the item arrangement when creating a group using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutGroup/custom(layoutSize:itemProvider:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " initializer.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutEnvironment": {
      "abstract": [
        {
          "text": "A protocol used to provide information about the layout’s container and environment traits, such as size classes and display scale factor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCollectionLayoutEnvironment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutEnvironment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionLayoutEnvironment"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionLayoutEnvironment",
      "type": "topic",
      "url": "/documentation/uikit/nscollectionlayoutenvironment"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutGroup/custom(layoutSize:itemProvider:)": {
      "abstract": [
        {
          "text": "Creates a group of the specified size, with an item provider that creates a custom arrangement for those items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "custom"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "layoutSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCollectionLayoutSize",
          "text": "NSCollectionLayoutSize"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "itemProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSCollectionLayoutGroupCustomItemProvider",
          "text": "NSCollectionLayoutGroupCustomItemProvider"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutGroup/custom(layoutSize:itemProvider:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "customGroupWithLayoutSize:itemProvider:"
        }
      ],
      "role": "symbol",
      "title": "custom(layoutSize:itemProvider:)",
      "type": "topic",
      "url": "/documentation/uikit/nscollectionlayoutgroup/custom(layoutsize:itemprovider:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutGroupCustomItem": {
      "abstract": [
        {
          "text": "An item used in a group with a custom layout arrangement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCollectionLayoutGroupCustomItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutGroupCustomItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionLayoutGroupCustomItem"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionLayoutGroupCustomItem",
      "type": "topic",
      "url": "/documentation/uikit/nscollectionlayoutgroupcustomitem"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutGroupCustomItemProvider": {
      "abstract": [
        {
          "text": "A closure that creates and returns each of the custom group’s items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCollectionLayoutGroupCustomItemProvider"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutGroupCustomItemProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCollectionLayoutGroupCustomItemProvider"
        }
      ],
      "role": "symbol",
      "title": "NSCollectionLayoutGroupCustomItemProvider",
      "type": "topic",
      "url": "/documentation/uikit/nscollectionlayoutgroupcustomitemprovider"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Advanced-layouts",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutGroupCustomItem"
      ],
      "title": "Advanced layouts"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSCollectionLayoutGroupCustomItemProvider"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutGroupCustomItemProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutGroupCustomItemProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Advanced-layouts",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutGroupCustomItem"
              ],
              "title": "Advanced layouts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:BF*Q$objc(cs)NSArray(#*Qoobjc(pl)NSCollectionLayoutEnvironment)",
                    "text": "NSArray<NSCollectionLayoutGroupCustomItem *> *(^)(id<NSCollectionLayoutEnvironment>)"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSCollectionLayoutGroupCustomItemProvider"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutGroup~1custom(layoutSize:itemProvider:)/title",
          "value": "customGroupWithLayoutSize:itemProvider:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutGroup~1custom(layoutSize:itemProvider:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "customGroupWithLayoutSize:itemProvider:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutGroupCustomItemProvider/title",
          "value": "NSCollectionLayoutGroupCustomItemProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutGroupCustomItemProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutGroupCustomItemProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutGroupCustomItemProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutGroupCustomItemProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutEnvironment/title",
          "value": "NSCollectionLayoutEnvironment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutEnvironment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutEnvironment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutEnvironment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutEnvironment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutGroupCustomItem/title",
          "value": "NSCollectionLayoutGroupCustomItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutGroupCustomItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutGroupCustomItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutGroupCustomItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCollectionLayoutGroupCustomItem"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/nscollectionlayoutgroupcustomitemprovider"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/nscollectionlayoutgroupcustomitemprovider"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
