{
  "abstract": [
    {
      "text": "The color of the text.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/NSForegroundColorAttributeName"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSForegroundColorAttributeName",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSForegroundColorAttributeName"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSForegroundColorAttributeName"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSForegroundColorAttributeName"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSAttributedStringKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSAttributedStringKey",
              "text": "NSAttributedStringKey"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSForegroundColorAttributeName"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In macOS, the value of this attribute is an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppKit/NSColor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance. In iOS, tvOS, watchOS, and Mac Catalyst, the value of this attribute is a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIColor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance. Use this attribute to specify the color of the text during rendering. If you don’t specify this attribute, the text renders in black.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AppKit/NSColor": {
      "abstract": [
        {
          "text": "An object that stores color data and sometimes opacity (alpha value).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSColor"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSColor",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSColor",
      "type": "topic",
      "url": "/documentation/AppKit/NSColor"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSBackgroundColorAttributeName": {
      "abstract": [
        {
          "text": "The color of the background behind the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSBackgroundColorAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSBackgroundColorAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSBackgroundColorAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nsbackgroundcolorattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSBaselineOffsetAttributeName": {
      "abstract": [
        {
          "text": "The vertical offset for the position of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSBaselineOffsetAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSBaselineOffsetAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSBaselineOffsetAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nsbaselineoffsetattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSFontAttributeName": {
      "abstract": [
        {
          "text": "The font of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSFontAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSFontAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFontAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nsfontattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSForegroundColorAttributeName": {
      "abstract": [
        {
          "text": "The color of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSForegroundColorAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSForegroundColorAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSForegroundColorAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nsforegroundcolorattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSKernAttributeName": {
      "abstract": [
        {
          "text": "The kerning of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSKernAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSKernAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSKernAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nskernattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLigatureAttributeName": {
      "abstract": [
        {
          "text": "The ligature of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSLigatureAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLigatureAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLigatureAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nsligatureattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSParagraphStyleAttributeName": {
      "abstract": [
        {
          "text": "The paragraph style of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSParagraphStyleAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSParagraphStyleAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSParagraphStyleAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nsparagraphstyleattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSStrikethroughColorAttributeName": {
      "abstract": [
        {
          "text": "The color of the strikethrough.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSStrikethroughColorAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSStrikethroughColorAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSStrikethroughColorAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nsstrikethroughcolorattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSStrikethroughStyleAttributeName": {
      "abstract": [
        {
          "text": "The strikethrough style of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSStrikethroughStyleAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSStrikethroughStyleAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSStrikethroughStyleAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nsstrikethroughstyleattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSStrokeColorAttributeName": {
      "abstract": [
        {
          "text": "The color of the stroke.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSStrokeColorAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSStrokeColorAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSStrokeColorAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nsstrokecolorattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSStrokeWidthAttributeName": {
      "abstract": [
        {
          "text": "The width of the stroke.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSStrokeWidthAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSStrokeWidthAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSStrokeWidthAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nsstrokewidthattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTrackingAttributeName": {
      "abstract": [
        {
          "text": "The amount to modify the default tracking.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTrackingAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTrackingAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTrackingAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nstrackingattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSUnderlineColorAttributeName": {
      "abstract": [
        {
          "text": "The color of the underline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSUnderlineColorAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSUnderlineColorAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUnderlineColorAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nsunderlinecolorattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyleAttributeName": {
      "abstract": [
        {
          "text": "The underline style of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSUnderlineStyleAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyleAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUnderlineStyleAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nsunderlinestyleattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSWritingDirectionAttributeName": {
      "abstract": [
        {
          "text": "The writing direction of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSWritingDirectionAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSWritingDirectionAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSWritingDirectionAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nswritingdirectionattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIColor": {
      "abstract": [
        {
          "text": "An object that stores color data and sometimes opacity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIColor"
        }
      ],
      "role": "symbol",
      "title": "UIColor",
      "type": "topic",
      "url": "/documentation/uikit/uicolor"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSAttributedStringKey": {
      "abstract": [
        {
          "text": "The attributes you apply to ranges of characters in an attributed string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "NSAttributedString.Key"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSAttributedStringKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAttributedString.Key",
      "type": "topic",
      "url": "/documentation/foundation/nsattributedstring/key"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-rendering-attribute-keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSBackgroundColorAttributeName",
        "doc://com.apple.uikit/documentation/UIKit/NSBaselineOffsetAttributeName",
        "doc://com.apple.uikit/documentation/UIKit/NSFontAttributeName",
        "doc://com.apple.uikit/documentation/UIKit/NSKernAttributeName",
        "doc://com.apple.uikit/documentation/UIKit/NSLigatureAttributeName",
        "doc://com.apple.uikit/documentation/UIKit/NSParagraphStyleAttributeName",
        "doc://com.apple.uikit/documentation/UIKit/NSStrikethroughColorAttributeName",
        "doc://com.apple.uikit/documentation/UIKit/NSStrikethroughStyleAttributeName",
        "doc://com.apple.uikit/documentation/UIKit/NSStrokeColorAttributeName",
        "doc://com.apple.uikit/documentation/UIKit/NSStrokeWidthAttributeName",
        "doc://com.apple.uikit/documentation/UIKit/NSTrackingAttributeName",
        "doc://com.apple.uikit/documentation/UIKit/NSUnderlineColorAttributeName",
        "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyleAttributeName",
        "doc://com.apple.uikit/documentation/UIKit/NSWritingDirectionAttributeName"
      ],
      "title": "Getting rendering attribute keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSColor/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSColor"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor/title",
          "value": "UIColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@NSAttributedStringKey/title",
          "value": "NSAttributedStringKey"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/nsforegroundcolorattributename"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
