{"metadata":{"externalID":"c:@NSFontAttributeName","title":"NSFontAttributeName","navigatorTitle":[{"text":"NSFontAttributeName","kind":"identifier"}],"fragments":[{"text":"NSFontAttributeName","kind":"identifier"}],"platforms":[{"unavailable":false,"beta":false,"name":"iOS","introducedAt":"6.0","deprecated":false},{"unavailable":false,"beta":false,"name":"iPadOS","introducedAt":"6.0","deprecated":false},{"unavailable":false,"beta":false,"name":"Mac Catalyst","introducedAt":"13.1","deprecated":false},{"unavailable":false,"beta":false,"name":"tvOS","introducedAt":"9.0","deprecated":false},{"unavailable":false,"introducedAt":"1.0","name":"visionOS","beta":false,"deprecated":false},{"unavailable":false,"introducedAt":"2.0","name":"watchOS","beta":false,"deprecated":false}],"symbolKind":"var","modules":[{"name":"UIKit"}],"roleHeading":"Global Variable","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc://com.externally.resolved.symbol/c:@T@NSAttributedStringKey","text":"NSAttributedStringKey","preciseIdentifier":"c:@T@NSAttributedStringKey","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSFontAttributeName","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The value of this attribute is a "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIFont"},{"type":"text","text":" object. Use this attribute to change the font for a range of text. If you do not specify this attribute, the string uses a 12-point Helvetica(Neue) font by default."}]}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The font of the text."}],"identifier":{"interfaceLanguage":"occ","url":"doc://com.apple.uikit/documentation/UIKit/NSFontAttributeName"},"seeAlsoSections":[{"generated":true,"anchor":"Getting-rendering-attribute-keys","title":"Getting rendering attribute keys","identifiers":["doc://com.apple.uikit/documentation/UIKit/NSBackgroundColorAttributeName","doc://com.apple.uikit/documentation/UIKit/NSBaselineOffsetAttributeName","doc://com.apple.uikit/documentation/UIKit/NSForegroundColorAttributeName","doc://com.apple.uikit/documentation/UIKit/NSKernAttributeName","doc://com.apple.uikit/documentation/UIKit/NSLigatureAttributeName","doc://com.apple.uikit/documentation/UIKit/NSParagraphStyleAttributeName","doc://com.apple.uikit/documentation/UIKit/NSStrikethroughColorAttributeName","doc://com.apple.uikit/documentation/UIKit/NSStrikethroughStyleAttributeName","doc://com.apple.uikit/documentation/UIKit/NSStrokeColorAttributeName","doc://com.apple.uikit/documentation/UIKit/NSStrokeWidthAttributeName","doc://com.apple.uikit/documentation/UIKit/NSTrackingAttributeName","doc://com.apple.uikit/documentation/UIKit/NSUnderlineColorAttributeName","doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyleAttributeName","doc://com.apple.uikit/documentation/UIKit/NSWritingDirectionAttributeName"]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/nsfontattributename"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"references":{"doc://com.apple.uikit/documentation/UIKit/NSStrikethroughColorAttributeName":{"kind":"symbol","type":"topic","title":"NSStrikethroughColorAttributeName","role":"symbol","url":"/documentation/uikit/nsstrikethroughcolorattributename","identifier":"doc://com.apple.uikit/documentation/UIKit/NSStrikethroughColorAttributeName","abstract":[{"text":"The color of the strikethrough.","type":"text"}],"fragments":[{"text":"NSStrikethroughColorAttributeName","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIFont":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIFont"}],"url":"/documentation/uikit/uifont","abstract":[{"text":"An object that provides access to the font’s characteristics.","type":"text"}],"title":"UIFont","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UIFont"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIFont"},"doc://com.apple.uikit/documentation/UIKit/NSFontAttributeName":{"abstract":[{"text":"The font of the text.","type":"text"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/NSFontAttributeName","fragments":[{"text":"NSFontAttributeName","kind":"identifier"}],"title":"NSFontAttributeName","role":"symbol","type":"topic","url":"/documentation/uikit/nsfontattributename"},"doc://com.apple.uikit/documentation/UIKit/NSUnderlineColorAttributeName":{"kind":"symbol","type":"topic","title":"NSUnderlineColorAttributeName","role":"symbol","url":"/documentation/uikit/nsunderlinecolorattributename","identifier":"doc://com.apple.uikit/documentation/UIKit/NSUnderlineColorAttributeName","abstract":[{"text":"The color of the underline.","type":"text"}],"fragments":[{"text":"NSUnderlineColorAttributeName","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/NSParagraphStyleAttributeName":{"kind":"symbol","type":"topic","title":"NSParagraphStyleAttributeName","role":"symbol","url":"/documentation/uikit/nsparagraphstyleattributename","identifier":"doc://com.apple.uikit/documentation/UIKit/NSParagraphStyleAttributeName","abstract":[{"text":"The paragraph style of the text.","type":"text"}],"fragments":[{"text":"NSParagraphStyleAttributeName","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/NSWritingDirectionAttributeName":{"kind":"symbol","type":"topic","title":"NSWritingDirectionAttributeName","role":"symbol","url":"/documentation/uikit/nswritingdirectionattributename","identifier":"doc://com.apple.uikit/documentation/UIKit/NSWritingDirectionAttributeName","abstract":[{"text":"The writing direction of the text.","type":"text"}],"fragments":[{"text":"NSWritingDirectionAttributeName","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/NSStrikethroughStyleAttributeName":{"type":"topic","kind":"symbol","fragments":[{"kind":"identifier","text":"NSStrikethroughStyleAttributeName"}],"title":"NSStrikethroughStyleAttributeName","url":"/documentation/uikit/nsstrikethroughstyleattributename","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/NSStrikethroughStyleAttributeName","abstract":[{"text":"The strikethrough style of the text.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyleAttributeName":{"kind":"symbol","type":"topic","title":"NSUnderlineStyleAttributeName","role":"symbol","url":"/documentation/uikit/nsunderlinestyleattributename","identifier":"doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyleAttributeName","abstract":[{"text":"The underline style of the text.","type":"text"}],"fragments":[{"text":"NSUnderlineStyleAttributeName","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/NSKernAttributeName":{"type":"topic","kind":"symbol","fragments":[{"kind":"identifier","text":"NSKernAttributeName"}],"title":"NSKernAttributeName","url":"/documentation/uikit/nskernattributename","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/NSKernAttributeName","abstract":[{"text":"The kerning of the text.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/NSTrackingAttributeName":{"identifier":"doc://com.apple.uikit/documentation/UIKit/NSTrackingAttributeName","title":"NSTrackingAttributeName","abstract":[{"type":"text","text":"The amount to modify the default tracking."}],"kind":"symbol","fragments":[{"kind":"identifier","text":"NSTrackingAttributeName"}],"role":"symbol","type":"topic","url":"/documentation/uikit/nstrackingattributename"},"doc://com.apple.uikit/documentation/UIKit/NSLigatureAttributeName":{"type":"topic","kind":"symbol","fragments":[{"kind":"identifier","text":"NSLigatureAttributeName"}],"title":"NSLigatureAttributeName","url":"/documentation/uikit/nsligatureattributename","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/NSLigatureAttributeName","abstract":[{"text":"The ligature of the text.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/NSStrokeWidthAttributeName":{"type":"topic","fragments":[{"kind":"identifier","text":"NSStrokeWidthAttributeName"}],"kind":"symbol","role":"symbol","title":"NSStrokeWidthAttributeName","url":"/documentation/uikit/nsstrokewidthattributename","abstract":[{"type":"text","text":"The width of the stroke."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/NSStrokeWidthAttributeName"},"doc://com.apple.uikit/documentation/UIKit/NSForegroundColorAttributeName":{"url":"/documentation/uikit/nsforegroundcolorattributename","type":"topic","abstract":[{"text":"The color of the text.","type":"text"}],"fragments":[{"text":"NSForegroundColorAttributeName","kind":"identifier"}],"role":"symbol","title":"NSForegroundColorAttributeName","identifier":"doc://com.apple.uikit/documentation/UIKit/NSForegroundColorAttributeName","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/NSStrokeColorAttributeName":{"type":"topic","kind":"symbol","fragments":[{"kind":"identifier","text":"NSStrokeColorAttributeName"}],"title":"NSStrokeColorAttributeName","url":"/documentation/uikit/nsstrokecolorattributename","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/NSStrokeColorAttributeName","abstract":[{"text":"The color of the stroke.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/NSBackgroundColorAttributeName":{"kind":"symbol","type":"topic","title":"NSBackgroundColorAttributeName","role":"symbol","url":"/documentation/uikit/nsbackgroundcolorattributename","identifier":"doc://com.apple.uikit/documentation/UIKit/NSBackgroundColorAttributeName","abstract":[{"text":"The color of the background behind the text.","type":"text"}],"fragments":[{"text":"NSBackgroundColorAttributeName","kind":"identifier"}]},"doc://com.externally.resolved.symbol/c:@T@NSAttributedStringKey":{"role":"symbol","abstract":[{"type":"text","text":"The attributes you apply to ranges of characters in an attributed string."}],"type":"topic","url":"/documentation/foundation/nsattributedstring/key","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:@T@NSAttributedStringKey","fragments":[{"kind":"text","text":"struct "},{"kind":"identifier","text":"NSAttributedString.Key"}],"title":"NSAttributedString.Key"},"doc://com.apple.uikit/documentation/UIKit/NSBaselineOffsetAttributeName":{"identifier":"doc://com.apple.uikit/documentation/UIKit/NSBaselineOffsetAttributeName","abstract":[{"type":"text","text":"The vertical offset for the position of the text."}],"fragments":[{"text":"NSBaselineOffsetAttributeName","kind":"identifier"}],"title":"NSBaselineOffsetAttributeName","url":"/documentation/uikit/nsbaselineoffsetattributename","type":"topic","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFont/title","value":"UIFont"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFont/fragments","value":[{"kind":"identifier","text":"UIFont"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFont/navigatorTitle","value":[{"kind":"identifier","text":"UIFont"}]},{"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:@T@NSAttributedStringKey/title","value":"NSAttributedStringKey"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}