{
  "abstract": [
    {
      "text": "Constants that specify alignment to an edge or a set of edges depending on the user interface layout direction.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSRectAlignment",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSRectAlignment"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSRectAlignment"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NSRectAlignment"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSRectAlignment"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSDirectionalEdgeInsets": {
      "abstract": [
        {
          "text": "The inset distances for views, taking the user interface layout direction into account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDirectionalEdgeInsets"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSDirectionalEdgeInsets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDirectionalEdgeInsets"
        }
      ],
      "role": "symbol",
      "title": "NSDirectionalEdgeInsets",
      "type": "topic",
      "url": "/documentation/uikit/nsdirectionaledgeinsets"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge": {
      "abstract": [
        {
          "text": "Constants that specify an edge or a set of edges, taking the user interface layout direction into account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDirectionalRectEdge"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDirectionalRectEdge"
        }
      ],
      "role": "symbol",
      "title": "NSDirectionalRectEdge",
      "type": "topic",
      "url": "/documentation/uikit/nsdirectionalrectedge"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment": {
      "abstract": [
        {
          "text": "Constants that specify alignment to an edge or a set of edges depending on the user interface layout direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSRectAlignment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRectAlignment"
        }
      ],
      "role": "symbol",
      "title": "NSRectAlignment",
      "type": "topic",
      "url": "/documentation/uikit/nsrectalignment"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/bottom": {
      "abstract": [
        {
          "text": "Aligns to the bottom edge.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottom"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/bottom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRectAlignmentBottom"
        }
      ],
      "role": "symbol",
      "title": "NSRectAlignment.bottom",
      "type": "topic",
      "url": "/documentation/uikit/nsrectalignment/bottom"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/bottomLeading": {
      "abstract": [
        {
          "text": "Aligns to the bottom and leading edges.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottomLeading"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/bottomLeading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRectAlignmentBottomLeading"
        }
      ],
      "role": "symbol",
      "title": "NSRectAlignment.bottomLeading",
      "type": "topic",
      "url": "/documentation/uikit/nsrectalignment/bottomleading"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/bottomTrailing": {
      "abstract": [
        {
          "text": "Aligns to the bottom and trailing edges.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottomTrailing"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/bottomTrailing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRectAlignmentBottomTrailing"
        }
      ],
      "role": "symbol",
      "title": "NSRectAlignment.bottomTrailing",
      "type": "topic",
      "url": "/documentation/uikit/nsrectalignment/bottomtrailing"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/nsrectalignment/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/leading": {
      "abstract": [
        {
          "text": "Aligns to the leading edge.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leading"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/leading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRectAlignmentLeading"
        }
      ],
      "role": "symbol",
      "title": "NSRectAlignment.leading",
      "type": "topic",
      "url": "/documentation/uikit/nsrectalignment/leading"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/none": {
      "abstract": [
        {
          "text": "Has no specified alignment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRectAlignmentNone"
        }
      ],
      "role": "symbol",
      "title": "NSRectAlignment.none",
      "type": "topic",
      "url": "/documentation/uikit/nsrectalignment/none"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/top": {
      "abstract": [
        {
          "text": "Aligns to the top edge.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "top"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/top",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRectAlignmentTop"
        }
      ],
      "role": "symbol",
      "title": "NSRectAlignment.top",
      "type": "topic",
      "url": "/documentation/uikit/nsrectalignment/top"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/topLeading": {
      "abstract": [
        {
          "text": "Aligns to the top and leading edges.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topLeading"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/topLeading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRectAlignmentTopLeading"
        }
      ],
      "role": "symbol",
      "title": "NSRectAlignment.topLeading",
      "type": "topic",
      "url": "/documentation/uikit/nsrectalignment/topleading"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/topTrailing": {
      "abstract": [
        {
          "text": "Aligns to the top and trailing edges.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topTrailing"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/topTrailing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRectAlignmentTopTrailing"
        }
      ],
      "role": "symbol",
      "title": "NSRectAlignment.topTrailing",
      "type": "topic",
      "url": "/documentation/uikit/nsrectalignment/toptrailing"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/trailing": {
      "abstract": [
        {
          "text": "Aligns to the trailing edge.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trailing"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/trailing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRectAlignmentTrailing"
        }
      ],
      "role": "symbol",
      "title": "NSRectAlignment.trailing",
      "type": "topic",
      "url": "/documentation/uikit/nsrectalignment/trailing"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAxis": {
      "abstract": [
        {
          "text": "A structure that specifies the layout axes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAxis"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAxis",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAxis"
        }
      ],
      "role": "symbol",
      "title": "UIAxis",
      "type": "topic",
      "url": "/documentation/uikit/uiaxis"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge": {
      "abstract": [
        {
          "text": "Constants that specify an edge or a set of edges, taking the user interface layout direction into account.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDirectionalRectEdge"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDirectionalRectEdge"
        }
      ],
      "role": "symbol",
      "title": "UIDirectionalRectEdge",
      "type": "topic",
      "url": "/documentation/uikit/uidirectionalrectedge"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIEdgeInsets": {
      "abstract": [
        {
          "text": "The inset distances for views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIEdgeInsets"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEdgeInsets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIEdgeInsets"
        }
      ],
      "role": "symbol",
      "title": "UIEdgeInsets",
      "type": "topic",
      "url": "/documentation/uikit/uiedgeinsets"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIOffset": {
      "abstract": [
        {
          "text": "A structure that specifies an amount to offset a position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIOffset"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIOffset"
        }
      ],
      "role": "symbol",
      "title": "UIOffset",
      "type": "topic",
      "url": "/documentation/uikit/uioffset"
    },
    "doc://com.apple.uikit/documentation/UIKit/uikit-macros": {
      "abstract": [
        {
          "text": "Macros that UIKit defines.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/uikit-macros",
      "kind": "article",
      "role": "collectionGroup",
      "title": "UIKit macros",
      "type": "topic",
      "url": "/documentation/uikit/uikit-macros"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIOffset",
        "doc://com.apple.uikit/documentation/UIKit/UIAxis",
        "doc://com.apple.uikit/documentation/UIKit/UIEdgeInsets",
        "doc://com.apple.uikit/documentation/UIKit/NSDirectionalEdgeInsets",
        "doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge",
        "doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge",
        "doc://com.apple.uikit/documentation/UIKit/uikit-macros"
      ],
      "title": "Related types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Alignments",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/none",
        "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/top",
        "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/topLeading",
        "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/leading",
        "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/bottomLeading",
        "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/bottom",
        "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/bottomTrailing",
        "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/trailing",
        "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/topTrailing"
      ],
      "title": "Alignments"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSRectAlignment"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRectAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRectAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Alignments",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/none",
                "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/top",
                "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/topLeading",
                "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/leading",
                "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/bottomLeading",
                "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/bottom",
                "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/bottomTrailing",
                "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/trailing",
                "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment/topTrailing"
              ],
              "title": "Alignments"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIOffset",
                "doc://com.apple.uikit/documentation/UIKit/UIAxis",
                "doc://com.apple.uikit/documentation/UIKit/UIEdgeInsets",
                "doc://com.apple.uikit/documentation/UIKit/NSDirectionalEdgeInsets",
                "doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge",
                "doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge",
                "doc://com.apple.uikit/documentation/UIKit/uikit-macros"
              ],
              "title": "Related types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSRectAlignment"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment~1topTrailing/title",
          "value": "NSRectAlignmentTopTrailing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment~1topTrailing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRectAlignmentTopTrailing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment/title",
          "value": "NSRectAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRectAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRectAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSDirectionalEdgeInsets/title",
          "value": "NSDirectionalEdgeInsets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSDirectionalEdgeInsets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDirectionalEdgeInsets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSDirectionalEdgeInsets/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDirectionalEdgeInsets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment~1none/title",
          "value": "NSRectAlignmentNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRectAlignmentNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSDirectionalRectEdge/title",
          "value": "NSDirectionalRectEdge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSDirectionalRectEdge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDirectionalRectEdge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSDirectionalRectEdge/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDirectionalRectEdge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment~1trailing/title",
          "value": "NSRectAlignmentTrailing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment~1trailing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRectAlignmentTrailing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment~1bottomLeading/title",
          "value": "NSRectAlignmentBottomLeading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment~1bottomLeading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRectAlignmentBottomLeading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDirectionalRectEdge/title",
          "value": "UIDirectionalRectEdge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDirectionalRectEdge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDirectionalRectEdge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDirectionalRectEdge/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDirectionalRectEdge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment~1leading/title",
          "value": "NSRectAlignmentLeading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment~1leading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRectAlignmentLeading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEdgeInsets/title",
          "value": "UIEdgeInsets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEdgeInsets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEdgeInsets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEdgeInsets/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEdgeInsets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAxis/title",
          "value": "UIAxis"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAxis/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAxis"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAxis/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAxis"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIOffset/title",
          "value": "UIOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIOffset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment~1bottom/title",
          "value": "NSRectAlignmentBottom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment~1bottom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRectAlignmentBottom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment~1top/title",
          "value": "NSRectAlignmentTop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment~1top/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRectAlignmentTop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment~1topLeading/title",
          "value": "NSRectAlignmentTopLeading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment~1topLeading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRectAlignmentTopLeading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment~1bottomTrailing/title",
          "value": "NSRectAlignmentBottomTrailing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment~1bottomTrailing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRectAlignmentBottomTrailing"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/nsrectalignment"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/nsrectalignment"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
