{
  "abstract": [
    {
      "text": "A region where text layout occurs.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/NSTextContainer"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSTextContainer",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSTextContainer"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTextContainer"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NSTextContainer"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSTextContainer"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutManager",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " uses ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextContainer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to determine where to break lines, lay out portions of text, and so on. An ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextContainer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object typically defines rectangular regions, but you can define exclusion paths inside the text container to create regions where text doesn’t flow. You can also subclass to create text containers with nonrectangular regions, such as circular regions, regions with holes in them, or regions that flow alongside graphics.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can access instances of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextContainer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutManager",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextStorage",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " classes from threads other than the main thread as long as the app guarantees access from only one thread at a time.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AppKit/NSTextContainer/containerSize": {
      "abstract": [
        {
          "text": "The size of the text container’s bounding rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "containerSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSize",
          "text": "NSSize"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSTextContainer/containerSize",
      "kind": "symbol",
      "role": "symbol",
      "title": "containerSize",
      "type": "topic",
      "url": "/documentation/AppKit/NSTextContainer/containerSize"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSTextContainer/contains(_:)": {
      "abstract": [
        {
          "text": "Queries whether a point lies within the text container’s region or on the region’s edge—not simply within its bounding rectangle.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contains"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "_"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "point"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPoint",
          "text": "NSPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSTextContainer/contains(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "contains(_:)",
      "type": "topic",
      "url": "/documentation/AppKit/NSTextContainer/contains(_:)"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSTextContainer/init(containerSize:)": {
      "abstract": [
        {
          "text": "Initializes a text container with a specified bounding rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "containerSize"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "aContainerSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSSize",
          "text": "NSSize"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSTextContainer/init(containerSize:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(containerSize:)",
      "type": "topic",
      "url": "/documentation/AppKit/NSTextContainer/init(containerSize:)"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSTextContainer/lineFragmentRect(forProposedRect:sweepDirection:movementDirection:remaining:)": {
      "abstract": [
        {
          "text": "Calculates and returns the longest rectangle available in the proposed rectangle for displaying text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineFragmentRect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forProposedRect"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "proposedRect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "sweepDirection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSLineSweepDirection",
          "text": "NSLineSweepDirection"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "movementDirection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSLineMovementDirection",
          "text": "NSLineMovementDirection"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "remaining"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "remainingRect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRectPointer",
          "text": "NSRectPointer"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSTextContainer/lineFragmentRect(forProposedRect:sweepDirection:movementDirection:remaining:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "lineFragmentRect(forProposedRect:sweepDirection:movementDirection:remaining:)",
      "type": "topic",
      "url": "/documentation/AppKit/NSTextContainer/lineFragmentRect(forProposedRect:sweepDirection:movementDirection:remaining:)"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSTextContainer/textView": {
      "abstract": [
        {
          "text": "The text container’s text view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "weak"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextView",
          "text": "NSTextView"
        },
        {
          "kind": "text",
          "text": "? { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSTextContainer/textView",
      "kind": "symbol",
      "role": "symbol",
      "title": "textView",
      "type": "topic",
      "url": "/documentation/AppKit/NSTextContainer/textView"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutManager": {
      "abstract": [
        {
          "text": "An object that coordinates the layout and display of text characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLayoutManager"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLayoutManager"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutManager",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutmanager"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextContainer": {
      "abstract": [
        {
          "text": "A region where text layout occurs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextContainer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextContainer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContainer"
        }
      ],
      "role": "symbol",
      "title": "NSTextContainer",
      "type": "topic",
      "url": "/documentation/uikit/nstextcontainer"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/exclusionPaths": {
      "abstract": [
        {
          "text": "An array of path objects that represents the regions where text doesn’t display in the text container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exclusionPaths"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIBezierPath",
          "text": "UIBezierPath"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/exclusionPaths",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "exclusionPaths"
        }
      ],
      "role": "symbol",
      "title": "exclusionPaths",
      "type": "topic",
      "url": "/documentation/uikit/nstextcontainer/exclusionpaths"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/heightTracksTextView": {
      "abstract": [
        {
          "text": "A Boolean that controls whether the text container adjusts the height of its bounding rectangle when its text view resizes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "heightTracksTextView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/heightTracksTextView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "heightTracksTextView"
        }
      ],
      "role": "symbol",
      "title": "heightTracksTextView",
      "type": "topic",
      "url": "/documentation/uikit/nstextcontainer/heighttrackstextview"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/init(coder:)": {
      "abstract": [
        {
          "text": "Creates a text container from data in an unarchiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "coder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCoder",
          "text": "NSCoder"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/init(coder:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCoder:"
        }
      ],
      "role": "symbol",
      "title": "init(coder:)",
      "type": "topic",
      "url": "/documentation/uikit/nstextcontainer/init(coder:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/init(size:)": {
      "abstract": [
        {
          "text": "Initializes a text container with a specified bounding rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/init(size:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithSize:"
        }
      ],
      "role": "symbol",
      "title": "init(size:)",
      "type": "topic",
      "url": "/documentation/uikit/nstextcontainer/init(size:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/isSimpleRectangularTextContainer": {
      "abstract": [
        {
          "text": "A Boolean that indicates whether the text container’s region is a rectangle with no holes or gaps, and whose edges are parallel to the text view’s coordinate system axes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSimpleRectangularTextContainer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/isSimpleRectangularTextContainer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simpleRectangularTextContainer"
        }
      ],
      "role": "symbol",
      "title": "isSimpleRectangularTextContainer",
      "type": "topic",
      "url": "/documentation/uikit/nstextcontainer/issimplerectangulartextcontainer"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/layoutManager": {
      "abstract": [
        {
          "text": "The text container’s layout manager.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layoutManager"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutManager",
          "text": "NSLayoutManager"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/layoutManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layoutManager"
        }
      ],
      "role": "symbol",
      "title": "layoutManager",
      "type": "topic",
      "url": "/documentation/uikit/nstextcontainer/layoutmanager"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/lineBreakMode": {
      "abstract": [
        {
          "text": "The behavior of the last line inside the text container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineBreakMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSLineBreakMode",
          "text": "NSLineBreakMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/lineBreakMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lineBreakMode"
        }
      ],
      "role": "symbol",
      "title": "lineBreakMode",
      "type": "topic",
      "url": "/documentation/uikit/nstextcontainer/linebreakmode"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/lineFragmentPadding": {
      "abstract": [
        {
          "text": "The value for the text inset within line fragment rectangles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineFragmentPadding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/lineFragmentPadding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lineFragmentPadding"
        }
      ],
      "role": "symbol",
      "title": "lineFragmentPadding",
      "type": "topic",
      "url": "/documentation/uikit/nstextcontainer/linefragmentpadding"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/lineFragmentRect(forProposedRect:at:writingDirection:remaining:)": {
      "abstract": [
        {
          "text": "Returns the bounds of a line fragment rectangle inside the text container for the proposed rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineFragmentRect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forProposedRect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "writingDirection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSWritingDirection",
          "text": "NSWritingDirection"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "remaining"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/lineFragmentRect(forProposedRect:at:writingDirection:remaining:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lineFragmentRectForProposedRect:atIndex:writingDirection:remainingRect:"
        }
      ],
      "role": "symbol",
      "title": "lineFragmentRect(forProposedRect:at:writingDirection:remaining:)",
      "type": "topic",
      "url": "/documentation/uikit/nstextcontainer/linefragmentrect(forproposedrect:at:writingdirection:remaining:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/maximumNumberOfLines": {
      "abstract": [
        {
          "text": "The maximum number of lines that the text container can store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumNumberOfLines"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/maximumNumberOfLines",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumNumberOfLines"
        }
      ],
      "role": "symbol",
      "title": "maximumNumberOfLines",
      "type": "topic",
      "url": "/documentation/uikit/nstextcontainer/maximumnumberoflines"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/replaceLayoutManager(_:)": {
      "abstract": [
        {
          "text": "Replaces the layout manager for the group of text system objects that contains the text container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "replaceLayoutManager"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSLayoutManager",
          "text": "NSLayoutManager"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/replaceLayoutManager(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "replaceLayoutManager:"
        }
      ],
      "role": "symbol",
      "title": "replaceLayoutManager(_:)",
      "type": "topic",
      "url": "/documentation/uikit/nstextcontainer/replacelayoutmanager(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/size": {
      "abstract": [
        {
          "text": "The size of the text container’s bounding rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/size",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "size"
        }
      ],
      "role": "symbol",
      "title": "size",
      "type": "topic",
      "url": "/documentation/uikit/nstextcontainer/size"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/textLayoutManager": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textLayoutManager"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextLayoutManager",
          "text": "NSTextLayoutManager"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/textLayoutManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textLayoutManager"
        }
      ],
      "role": "symbol",
      "title": "textLayoutManager",
      "type": "topic",
      "url": "/documentation/uikit/nstextcontainer/textlayoutmanager"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/widthTracksTextView": {
      "abstract": [
        {
          "text": "A Boolean that controls whether the text container adjusts the width of its bounding rectangle when its text view resizes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "widthTracksTextView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/widthTracksTextView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "widthTracksTextView"
        }
      ],
      "role": "symbol",
      "title": "widthTracksTextView",
      "type": "topic",
      "url": "/documentation/uikit/nstextcontainer/widthtrackstextview"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment": {
      "abstract": [
        {
          "text": "A class that represents the layout fragment typically corresponding to a rendering surface, such as a layer or view subclass.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextLayoutFragment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutFragment"
        }
      ],
      "role": "symbol",
      "title": "NSTextLayoutFragment",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutfragment"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager": {
      "abstract": [
        {
          "text": "The primary class that you use to manage text layout and presentation for custom text displays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextLayoutManager"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutManager"
        }
      ],
      "role": "symbol",
      "title": "NSTextLayoutManager",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutmanager"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutOrientationProvider": {
      "abstract": [
        {
          "text": "A set of methods that define the orientation of text for an object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextLayoutOrientationProvider"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutOrientationProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutOrientationProvider"
        }
      ],
      "role": "symbol",
      "title": "NSTextLayoutOrientationProvider",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutorientationprovider"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLineFragment": {
      "abstract": [
        {
          "text": "A class that represents a line fragment as a single textual layout and rendering unit inside a text layout fragment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextLineFragment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLineFragment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextLineFragment"
        }
      ],
      "role": "symbol",
      "title": "NSTextLineFragment",
      "type": "topic",
      "url": "/documentation/uikit/nstextlinefragment"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextStorage": {
      "abstract": [
        {
          "text": "The fundamental storage mechanism of TextKit that contains the text managed by the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextStorage"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextStorage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextStorage"
        }
      ],
      "role": "symbol",
      "title": "NSTextStorage",
      "type": "topic",
      "url": "/documentation/uikit/nstextstorage"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextViewportLayoutController": {
      "abstract": [
        {
          "text": "Manages the layout process inside the viewport interacting with its delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextViewportLayoutController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextViewportLayoutController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextViewportLayoutController"
        }
      ],
      "role": "symbol",
      "title": "NSTextViewportLayoutController",
      "type": "topic",
      "url": "/documentation/uikit/nstextviewportlayoutcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/display-text-with-a-custom-layout": {
      "abstract": [
        {
          "text": "Lay out text in a custom-shaped container and apply glyph substitutions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/display-text-with-a-custom-layout",
      "kind": "article",
      "role": "sampleCode",
      "title": "Display text with a custom layout",
      "type": "topic",
      "url": "/documentation/uikit/display-text-with-a-custom-layout"
    },
    "doc://com.apple.uikit/documentation/UIKit/using-textkit-2-to-interact-with-text": {
      "abstract": [
        {
          "text": "Interact with text by managing text selection and inserting custom text elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/using-textkit-2-to-interact-with-text",
      "kind": "article",
      "role": "sampleCode",
      "title": "Using TextKit 2 to interact with text",
      "type": "topic",
      "url": "/documentation/uikit/using-textkit-2-to-interact-with-text"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
        "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutOrientationProvider"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Layout",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/using-textkit-2-to-interact-with-text",
        "doc://com.apple.uikit/documentation/UIKit/display-text-with-a-custom-layout",
        "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager",
        "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment",
        "doc://com.apple.uikit/documentation/UIKit/NSTextLineFragment",
        "doc://com.apple.uikit/documentation/UIKit/NSTextViewportLayoutController",
        "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutOrientationProvider"
      ],
      "title": "Layout"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-text-container",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/init(size:)",
        "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/init(coder:)"
      ],
      "title": "Creating a text container"
    },
    {
      "anchor": "Managing-text-components",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/layoutManager",
        "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/textLayoutManager",
        "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/replaceLayoutManager(_:)",
        "doc://com.apple.documentation/documentation/AppKit/NSTextContainer/textView"
      ],
      "title": "Managing text components"
    },
    {
      "anchor": "Defining-the-container-shape",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/size",
        "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/exclusionPaths",
        "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/lineBreakMode",
        "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/widthTracksTextView",
        "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/heightTracksTextView"
      ],
      "title": "Defining the container shape"
    },
    {
      "anchor": "Constraining-text-layout",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/maximumNumberOfLines",
        "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/lineFragmentPadding",
        "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/lineFragmentRect(forProposedRect:at:writingDirection:remaining:)",
        "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/isSimpleRectangularTextContainer"
      ],
      "title": "Constraining text layout"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.documentation/documentation/AppKit/NSTextContainer/init(containerSize:)",
        "doc://com.apple.documentation/documentation/AppKit/NSTextContainer/lineFragmentRect(forProposedRect:sweepDirection:movementDirection:remaining:)",
        "doc://com.apple.documentation/documentation/AppKit/NSTextContainer/contains(_:)",
        "doc://com.apple.documentation/documentation/AppKit/NSTextContainer/containerSize"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTextContainer"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-text-container",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/init(size:)",
                "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/init(coder:)"
              ],
              "title": "Creating a text container"
            },
            {
              "anchor": "Managing-text-components",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/layoutManager",
                "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/textLayoutManager",
                "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/replaceLayoutManager(_:)",
                "doc://com.apple.documentation/documentation/AppKit/NSTextContainer/textView"
              ],
              "title": "Managing text components"
            },
            {
              "anchor": "Defining-the-container-shape",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/size",
                "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/exclusionPaths",
                "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/lineBreakMode",
                "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/widthTracksTextView",
                "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/heightTracksTextView"
              ],
              "title": "Defining the container shape"
            },
            {
              "anchor": "Constraining-text-layout",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/maximumNumberOfLines",
                "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/lineFragmentPadding",
                "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/lineFragmentRect(forProposedRect:at:writingDirection:remaining:)",
                "doc://com.apple.uikit/documentation/UIKit/NSTextContainer/isSimpleRectangularTextContainer"
              ],
              "title": "Constraining text layout"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.documentation/documentation/AppKit/NSTextContainer/init(containerSize:)",
                "doc://com.apple.documentation/documentation/AppKit/NSTextContainer/lineFragmentRect(forProposedRect:sweepDirection:movementDirection:remaining:)",
                "doc://com.apple.documentation/documentation/AppKit/NSTextContainer/contains(_:)",
                "doc://com.apple.documentation/documentation/AppKit/NSTextContainer/containerSize"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
                "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutOrientationProvider"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Layout",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/using-textkit-2-to-interact-with-text",
                "doc://com.apple.uikit/documentation/UIKit/display-text-with-a-custom-layout",
                "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager",
                "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutFragment",
                "doc://com.apple.uikit/documentation/UIKit/NSTextLineFragment",
                "doc://com.apple.uikit/documentation/UIKit/NSTextViewportLayoutController",
                "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutOrientationProvider"
              ],
              "title": "Layout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSTextContainer"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager/title",
          "value": "NSLayoutManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLayoutManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContainer~1lineFragmentRect(forProposedRect:at:writingDirection:remaining:)/title",
          "value": "lineFragmentRectForProposedRect:atIndex:writingDirection:remainingRect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContainer~1lineFragmentRect(forProposedRect:at:writingDirection:remaining:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "lineFragmentRectForProposedRect:atIndex:writingDirection:remainingRect:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContainer~1lineBreakMode/title",
          "value": "lineBreakMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContainer~1lineBreakMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lineBreakMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSTextContainer~1containerSize/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSSize",
              "text": "NSSize"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "containerSize"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContainer~1isSimpleRectangularTextContainer/title",
          "value": "simpleRectangularTextContainer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContainer~1isSimpleRectangularTextContainer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simpleRectangularTextContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSTextContainer~1textView/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "weak"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSTextView",
              "text": "NSTextView"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "textView"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSTextContainer~1contains(_:)/title",
          "value": "containsPoint:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSTextContainer~1contains(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "containsPoint:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSPoint",
              "text": "NSPoint"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "point"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContainer~1textLayoutManager/title",
          "value": "textLayoutManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContainer~1textLayoutManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "textLayoutManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContainer~1heightTracksTextView/title",
          "value": "heightTracksTextView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContainer~1heightTracksTextView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "heightTracksTextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContainer~1lineFragmentPadding/title",
          "value": "lineFragmentPadding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContainer~1lineFragmentPadding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lineFragmentPadding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextViewportLayoutController/title",
          "value": "NSTextViewportLayoutController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextViewportLayoutController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextViewportLayoutController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextViewportLayoutController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextViewportLayoutController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContainer~1size/title",
          "value": "size"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContainer~1size/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "size"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSTextContainer~1init(containerSize:)/title",
          "value": "initWithContainerSize:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSTextContainer~1init(containerSize:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "keyword",
              "text": "instancetype"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "initWithContainerSize:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSSize",
              "text": "NSSize"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "aContainerSize"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager/title",
          "value": "NSTextLayoutManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLineFragment/title",
          "value": "NSTextLineFragment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLineFragment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLineFragment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLineFragment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLineFragment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContainer~1init(coder:)/title",
          "value": "initWithCoder:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContainer~1init(coder:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCoder:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextStorage/title",
          "value": "NSTextStorage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextStorage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextStorage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextStorage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextStorage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutOrientationProvider/title",
          "value": "NSTextLayoutOrientationProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutOrientationProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutOrientationProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutOrientationProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutOrientationProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContainer~1init(size:)/title",
          "value": "initWithSize:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContainer~1init(size:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithSize:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContainer/title",
          "value": "NSTextContainer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContainer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContainer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContainer~1exclusionPaths/title",
          "value": "exclusionPaths"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContainer~1exclusionPaths/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "exclusionPaths"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContainer~1replaceLayoutManager(_:)/title",
          "value": "replaceLayoutManager:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContainer~1replaceLayoutManager(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "replaceLayoutManager:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContainer~1layoutManager/title",
          "value": "layoutManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContainer~1layoutManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "layoutManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutFragment/title",
          "value": "NSTextLayoutFragment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutFragment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutFragment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutFragment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutFragment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContainer~1maximumNumberOfLines/title",
          "value": "maximumNumberOfLines"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContainer~1maximumNumberOfLines/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumNumberOfLines"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContainer~1widthTracksTextView/title",
          "value": "widthTracksTextView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContainer~1widthTracksTextView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "widthTracksTextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSTextContainer~1lineFragmentRect(forProposedRect:sweepDirection:movementDirection:remaining:)/title",
          "value": "lineFragmentRectForProposedRect:sweepDirection:movementDirection:remainingRect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSTextContainer~1lineFragmentRect(forProposedRect:sweepDirection:movementDirection:remaining:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSRect",
              "text": "NSRect"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "lineFragmentRectForProposedRect:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSRect",
              "text": "NSRect"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "proposedRect"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sweepDirection:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSLineSweepDirection",
              "text": "NSLineSweepDirection"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "sweepDirection"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "movementDirection:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSLineMovementDirection",
              "text": "NSLineMovementDirection"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "movementDirection"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "remainingRect:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSRectPointer",
              "text": "NSRectPointer"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "internalParam",
              "text": "remainingRect"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/nstextcontainer"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/nstextcontainer"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
