{
  "abstract": [
    {
      "text": "The text-scaling mode to use when displaying the text.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/NSTextScalingDocumentAttribute"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSTextScalingDocumentAttribute",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSTextScalingDocumentAttribute"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTextScalingDocumentAttribute"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSTextScalingDocumentAttribute"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSAttributedStringDocumentAttributeKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSAttributedStringDocumentAttributeKey",
              "text": "NSAttributedStringDocumentAttributeKey"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSTextScalingDocumentAttribute"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The value of this property is one of the options of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextScalingType",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " type. Some platforms scale fonts to improve their appearance. When saving a document, include this attribute to specify the type of scaling to apply to the text at display time.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSAttributedStringDocumentAttributeKey": {
      "abstract": [
        {
          "text": "The attributes you apply to an entire document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAttributedStringDocumentAttributeKey"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSAttributedStringDocumentAttributeKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAttributedStringDocumentAttributeKey",
      "type": "topic",
      "url": "/documentation/uikit/nsattributedstringdocumentattributekey"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSSourceTextScalingDocumentAttribute": {
      "abstract": [
        {
          "text": "The text-scaling mode you used when creating the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSSourceTextScalingDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSSourceTextScalingDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSourceTextScalingDocumentAttribute",
      "type": "topic",
      "url": "/documentation/uikit/nssourcetextscalingdocumentattribute"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextScalingDocumentAttribute": {
      "abstract": [
        {
          "text": "The text-scaling mode to use when displaying the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextScalingDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextScalingDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextScalingDocumentAttribute",
      "type": "topic",
      "url": "/documentation/uikit/nstextscalingdocumentattribute"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextScalingType": {
      "abstract": [
        {
          "text": "Constants that specify the text scaling.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextScalingType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextScalingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextScalingType"
        }
      ],
      "role": "symbol",
      "title": "NSTextScalingType",
      "type": "topic",
      "url": "/documentation/uikit/nstextscalingtype"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-font-scaling-options",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSSourceTextScalingDocumentAttribute"
      ],
      "title": "Getting the font-scaling options"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextScalingType/title",
          "value": "NSTextScalingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextScalingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextScalingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextScalingType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextScalingType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/nstextscalingdocumentattribute"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
