{
  "abstract": [
    {
      "text": "The layout orientations for each section.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutSectionsAttribute"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSTextLayoutSectionsAttribute",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSTextLayoutSectionsAttribute"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTextLayoutSectionsAttribute"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSTextLayoutSectionsAttribute"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSAttributedStringDocumentAttributeKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSAttributedStringDocumentAttributeKey",
              "text": "NSAttributedStringDocumentAttributeKey"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSTextLayoutSectionsAttribute"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/PropertyLists/OldStylePlists/OldStylePLists.html#//apple_ref/doc/uid/20001012-47205",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " containing ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsdictionary",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects, each dictionary describing a layout orientation section. The dictionary can have two attributes: ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutSectionOrientation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutSectionRange",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". When there is a gap between sections, it’s assumed to have ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/TextLayoutOrientation/horizontal",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AppKit/NSAppearanceDocumentAttribute": {
      "abstract": [
        {
          "text": "The appearance of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "extern"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAttributedStringDocumentAttributeKey",
          "text": "NSAttributedStringDocumentAttributeKey"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSAppearanceDocumentAttribute"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSAppearanceDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAppearanceDocumentAttribute",
      "type": "topic",
      "url": "/documentation/AppKit/NSAppearanceDocumentAttribute"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSBottomMarginDocumentAttribute": {
      "abstract": [
        {
          "text": "The bottom margin of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "extern"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAttributedStringDocumentAttributeKey",
          "text": "NSAttributedStringDocumentAttributeKey"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSBottomMarginDocumentAttribute"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSBottomMarginDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSBottomMarginDocumentAttribute",
      "type": "topic",
      "url": "/documentation/AppKit/NSBottomMarginDocumentAttribute"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSExcludedElementsDocumentAttribute": {
      "abstract": [
        {
          "text": "The HTML elements to exclude in generated HTML.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "extern"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAttributedStringDocumentAttributeKey",
          "text": "NSAttributedStringDocumentAttributeKey"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSExcludedElementsDocumentAttribute"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSExcludedElementsDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSExcludedElementsDocumentAttribute",
      "type": "topic",
      "url": "/documentation/AppKit/NSExcludedElementsDocumentAttribute"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSLeftMarginDocumentAttribute": {
      "abstract": [
        {
          "text": "The left margin of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "extern"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAttributedStringDocumentAttributeKey",
          "text": "NSAttributedStringDocumentAttributeKey"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLeftMarginDocumentAttribute"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSLeftMarginDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLeftMarginDocumentAttribute",
      "type": "topic",
      "url": "/documentation/AppKit/NSLeftMarginDocumentAttribute"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSPrefixSpacesDocumentAttribute": {
      "abstract": [
        {
          "text": "The number of spaces for indenting nested HTML elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "extern"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAttributedStringDocumentAttributeKey",
          "text": "NSAttributedStringDocumentAttributeKey"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPrefixSpacesDocumentAttribute"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSPrefixSpacesDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPrefixSpacesDocumentAttribute",
      "type": "topic",
      "url": "/documentation/AppKit/NSPrefixSpacesDocumentAttribute"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSRightMarginDocumentAttribute": {
      "abstract": [
        {
          "text": "The right margin of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "extern"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAttributedStringDocumentAttributeKey",
          "text": "NSAttributedStringDocumentAttributeKey"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSRightMarginDocumentAttribute"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSRightMarginDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSRightMarginDocumentAttribute",
      "type": "topic",
      "url": "/documentation/AppKit/NSRightMarginDocumentAttribute"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSTopMarginDocumentAttribute": {
      "abstract": [
        {
          "text": "The top margin of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "extern"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAttributedStringDocumentAttributeKey",
          "text": "NSAttributedStringDocumentAttributeKey"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTopMarginDocumentAttribute"
        },
        {
          "kind": "text",
          "text": ";"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSTopMarginDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTopMarginDocumentAttribute",
      "type": "topic",
      "url": "/documentation/AppKit/NSTopMarginDocumentAttribute"
    },
    "doc://com.apple.documentation/documentation/foundation/nsdictionary": {
      "abstract": [
        {
          "text": "An object representing a static collection of key-value pairs, for use instead of a  constant in cases that require reference semantics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSDictionary"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsdictionary",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDictionary",
      "type": "topic",
      "url": "/documentation/foundation/nsdictionary"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSAttributedStringDocumentAttributeKey": {
      "abstract": [
        {
          "text": "The attributes you apply to an entire document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAttributedStringDocumentAttributeKey"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSAttributedStringDocumentAttributeKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAttributedStringDocumentAttributeKey",
      "type": "topic",
      "url": "/documentation/uikit/nsattributedstringdocumentattributekey"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSBackgroundColorDocumentAttribute": {
      "abstract": [
        {
          "text": "The background color of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSBackgroundColorDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSBackgroundColorDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSBackgroundColorDocumentAttribute",
      "type": "topic",
      "url": "/documentation/uikit/nsbackgroundcolordocumentattribute"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSDefaultFontExcludedDocumentAttribute": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSDefaultFontExcludedDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSDefaultFontExcludedDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDefaultFontExcludedDocumentAttribute",
      "type": "topic",
      "url": "/documentation/uikit/nsdefaultfontexcludeddocumentattribute"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSDefaultTabIntervalDocumentAttribute": {
      "abstract": [
        {
          "text": "The default tab stop interval for the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSDefaultTabIntervalDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSDefaultTabIntervalDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSDefaultTabIntervalDocumentAttribute",
      "type": "topic",
      "url": "/documentation/uikit/nsdefaulttabintervaldocumentattribute"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSHyphenationFactorDocumentAttribute": {
      "abstract": [
        {
          "text": "The hyphenation factor of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSHyphenationFactorDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSHyphenationFactorDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSHyphenationFactorDocumentAttribute",
      "type": "topic",
      "url": "/documentation/uikit/nshyphenationfactordocumentattribute"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/TextLayoutOrientation/horizontal": {
      "abstract": [
        {
          "text": "Lines render horizontally, each line following the previous from top to bottom.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "horizontal"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutManager/TextLayoutOrientation/horizontal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutOrientationHorizontal"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutManager.TextLayoutOrientation.horizontal",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutmanager/textlayoutorientation/horizontal"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSPaperMarginDocumentAttribute": {
      "abstract": [
        {
          "text": "The paper margin of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPaperMarginDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSPaperMarginDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPaperMarginDocumentAttribute",
      "type": "topic",
      "url": "/documentation/uikit/nspapermargindocumentattribute"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSPaperSizeDocumentAttribute": {
      "abstract": [
        {
          "text": "The paper size for the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSPaperSizeDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSPaperSizeDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSPaperSizeDocumentAttribute",
      "type": "topic",
      "url": "/documentation/uikit/nspapersizedocumentattribute"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutSectionOrientation": {
      "abstract": [
        {
          "text": "The orientation of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutSectionOrientation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutSectionOrientation",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextLayoutSectionOrientation",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutsectionorientation"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutSectionRange": {
      "abstract": [
        {
          "text": "The character range.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutSectionRange"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutSectionRange",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextLayoutSectionRange",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutsectionrange"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutSectionsAttribute": {
      "abstract": [
        {
          "text": "The layout orientations for each section.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutSectionsAttribute"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutSectionsAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextLayoutSectionsAttribute",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutsectionsattribute"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSViewModeDocumentAttribute": {
      "abstract": [
        {
          "text": "The view mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSViewModeDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSViewModeDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSViewModeDocumentAttribute",
      "type": "topic",
      "url": "/documentation/uikit/nsviewmodedocumentattribute"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSViewSizeDocumentAttribute": {
      "abstract": [
        {
          "text": "The view size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSViewSizeDocumentAttribute"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSViewSizeDocumentAttribute",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSViewSizeDocumentAttribute",
      "type": "topic",
      "url": "/documentation/uikit/nsviewsizedocumentattribute"
    },
    "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/PropertyLists/OldStylePlists/OldStylePLists.html#//apple_ref/doc/uid/20001012-47205": {
      "identifier": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/PropertyLists/OldStylePlists/OldStylePLists.html#//apple_ref/doc/uid/20001012-47205",
      "title": "NSArray",
      "titleInlineContent": [
        {
          "text": "NSArray",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/PropertyLists/OldStylePlists/OldStylePLists.html#//apple_ref/doc/uid/20001012-47205"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-document-appearance-keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/AppKit/NSAppearanceDocumentAttribute",
        "doc://com.apple.uikit/documentation/UIKit/NSBackgroundColorDocumentAttribute",
        "doc://com.apple.documentation/documentation/AppKit/NSBottomMarginDocumentAttribute",
        "doc://com.apple.uikit/documentation/UIKit/NSDefaultFontExcludedDocumentAttribute",
        "doc://com.apple.uikit/documentation/UIKit/NSDefaultTabIntervalDocumentAttribute",
        "doc://com.apple.documentation/documentation/AppKit/NSExcludedElementsDocumentAttribute",
        "doc://com.apple.uikit/documentation/UIKit/NSHyphenationFactorDocumentAttribute",
        "doc://com.apple.documentation/documentation/AppKit/NSLeftMarginDocumentAttribute",
        "doc://com.apple.uikit/documentation/UIKit/NSPaperMarginDocumentAttribute",
        "doc://com.apple.uikit/documentation/UIKit/NSPaperSizeDocumentAttribute",
        "doc://com.apple.documentation/documentation/AppKit/NSPrefixSpacesDocumentAttribute",
        "doc://com.apple.documentation/documentation/AppKit/NSRightMarginDocumentAttribute",
        "doc://com.apple.documentation/documentation/AppKit/NSTopMarginDocumentAttribute",
        "doc://com.apple.uikit/documentation/UIKit/NSViewModeDocumentAttribute",
        "doc://com.apple.uikit/documentation/UIKit/NSViewSizeDocumentAttribute"
      ],
      "title": "Getting document appearance keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsdictionary/abstract",
          "value": [
            {
              "text": "A static collection of objects associated with unique keys.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1TextLayoutOrientation~1horizontal/title",
          "value": "NSTextLayoutOrientationHorizontal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutManager~1TextLayoutOrientation~1horizontal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutOrientationHorizontal"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/nstextlayoutsectionsattribute"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
