{
  "abstract": [
    {
      "text": "An abstract class that defines the interface and a default implementation for managing the text document contents.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)NSTextContentManager",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSTextContentManager"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTextContentManager"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "NSTextContentManager"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSTextContentManager"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.uikit/documentation/UIKit/adding-writing-tools-support-to-a-custom-uiview"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/nsattributedstring": {
      "abstract": [
        {
          "text": "A string of text that manages data, layout, and stylistic information for ranges of characters to support rendering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSAttributedString"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsattributedstring",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAttributedString",
      "type": "topic",
      "url": "/documentation/foundation/nsattributedstring"
    },
    "doc://com.apple.documentation/documentation/foundation/nsmutableattributedstring": {
      "abstract": [
        {
          "text": "A mutable string with associated attributes (such as visual style, hyperlinks, or accessibility data) for portions of its text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSMutableAttributedString"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsmutableattributedstring",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMutableAttributedString",
      "type": "topic",
      "url": "/documentation/foundation/nsmutableattributedstring"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager": {
      "abstract": [
        {
          "text": "An abstract class that defines the interface and a default implementation for managing the text document contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextContentManager"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentManager"
        }
      ],
      "role": "symbol",
      "title": "NSTextContentManager",
      "type": "topic",
      "url": "/documentation/uikit/nstextcontentmanager"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/EnumerationOptions": {
      "abstract": [
        {
          "text": "Values that control the order in which the framework enumerates text elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EnumerationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/EnumerationOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EnumerationOptions"
        }
      ],
      "role": "symbol",
      "title": "NSTextContentManager.EnumerationOptions",
      "type": "topic",
      "url": "/documentation/uikit/nstextcontentmanager/enumerationoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/addTextLayoutManager(_:)": {
      "abstract": [
        {
          "text": "Adds the layout manager you provide to the list of layout managers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addTextLayoutManager"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextLayoutManager",
          "text": "NSTextLayoutManager"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/addTextLayoutManager(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addTextLayoutManager:"
        }
      ],
      "role": "symbol",
      "title": "addTextLayoutManager(_:)",
      "type": "topic",
      "url": "/documentation/uikit/nstextcontentmanager/addtextlayoutmanager(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/automaticallySynchronizesTextLayoutManagers": {
      "abstract": [
        {
          "text": "Determines if the framework should automatically synchronize all text layout managers when exiting an editing transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automaticallySynchronizesTextLayoutManagers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/automaticallySynchronizesTextLayoutManagers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "automaticallySynchronizesTextLayoutManagers"
        }
      ],
      "role": "symbol",
      "title": "automaticallySynchronizesTextLayoutManagers",
      "type": "topic",
      "url": "/documentation/uikit/nstextcontentmanager/automaticallysynchronizestextlayoutmanagers"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/automaticallySynchronizesToBackingStore": {
      "abstract": [
        {
          "text": "Determines whether to automatically synchronize with the backing store when an editing transaction finishes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automaticallySynchronizesToBackingStore"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/automaticallySynchronizesToBackingStore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "automaticallySynchronizesToBackingStore"
        }
      ],
      "role": "symbol",
      "title": "automaticallySynchronizesToBackingStore",
      "type": "topic",
      "url": "/documentation/uikit/nstextcontentmanager/automaticallysynchronizestobackingstore"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/delegate": {
      "abstract": [
        {
          "text": "The delegate for the content manager object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSTextContentManagerDelegate",
          "text": "NSTextContentManagerDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/uikit/nstextcontentmanager/delegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/hasEditingTransaction": {
      "abstract": [
        {
          "text": "Indicates there’s an active editing transaction from the primary text layout manager.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hasEditingTransaction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/hasEditingTransaction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "hasEditingTransaction"
        }
      ],
      "role": "symbol",
      "title": "hasEditingTransaction",
      "type": "topic",
      "url": "/documentation/uikit/nstextcontentmanager/haseditingtransaction"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/init()": {
      "abstract": [
        {
          "text": "Creates a new content manager.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/init()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/uikit/nstextcontentmanager/init()"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/init(coder:)": {
      "abstract": [
        {
          "text": "Creates a new content manager object from data in an unarchiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "coder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCoder",
          "text": "NSCoder"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/init(coder:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCoder:"
        }
      ],
      "role": "symbol",
      "title": "init(coder:)",
      "type": "topic",
      "url": "/documentation/uikit/nstextcontentmanager/init(coder:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/performEditingTransaction(_:)": {
      "abstract": [
        {
          "text": "Performs an editing transaction and invokes a block upon completion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "performEditingTransaction"
        },
        {
          "kind": "text",
          "text": "(() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/performEditingTransaction(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "performEditingTransactionUsingBlock:"
        }
      ],
      "role": "symbol",
      "title": "performEditingTransaction(_:)",
      "type": "topic",
      "url": "/documentation/uikit/nstextcontentmanager/performeditingtransaction(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/primaryTextLayoutManager": {
      "abstract": [
        {
          "text": "The primary text layout manager for this content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "primaryTextLayoutManager"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextLayoutManager",
          "text": "NSTextLayoutManager"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/primaryTextLayoutManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "primaryTextLayoutManager"
        }
      ],
      "role": "symbol",
      "title": "primaryTextLayoutManager",
      "type": "topic",
      "url": "/documentation/uikit/nstextcontentmanager/primarytextlayoutmanager"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/recordEditAction(in:newTextRange:)": {
      "abstract": [
        {
          "text": "Records information about an edit action to the transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "recordEditAction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextRange",
          "text": "NSTextRange"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "newTextRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextRange",
          "text": "NSTextRange"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/recordEditAction(in:newTextRange:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "recordEditActionInRange:newTextRange:"
        }
      ],
      "role": "symbol",
      "title": "recordEditAction(in:newTextRange:)",
      "type": "topic",
      "url": "/documentation/uikit/nstextcontentmanager/recordeditaction(in:newtextrange:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/removeTextLayoutManager(_:)": {
      "abstract": [
        {
          "text": "Removes the layout manager you specifiy from the list of layout managers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeTextLayoutManager"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextLayoutManager",
          "text": "NSTextLayoutManager"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/removeTextLayoutManager(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeTextLayoutManager:"
        }
      ],
      "role": "symbol",
      "title": "removeTextLayoutManager(_:)",
      "type": "topic",
      "url": "/documentation/uikit/nstextcontentmanager/removetextlayoutmanager(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/synchronizeTextLayoutManagers(_:)": {
      "abstract": [
        {
          "text": "Synchronizes changes to all nonprimary text layout managers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "synchronizeTextLayoutManagers"
        },
        {
          "kind": "text",
          "text": "((((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/synchronizeTextLayoutManagers(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "synchronizeTextLayoutManagers:"
        }
      ],
      "role": "symbol",
      "title": "synchronizeTextLayoutManagers(_:)",
      "type": "topic",
      "url": "/documentation/uikit/nstextcontentmanager/synchronizetextlayoutmanagers(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/textElements(for:)": {
      "abstract": [
        {
          "text": "Returns an array of text elements that intersect with the range you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textElements"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextRange",
          "text": "NSTextRange"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextElement",
          "text": "NSTextElement"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/textElements(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textElementsForRange:"
        }
      ],
      "role": "symbol",
      "title": "textElements(for:)",
      "type": "topic",
      "url": "/documentation/uikit/nstextcontentmanager/textelements(for:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/textLayoutManagers": {
      "abstract": [
        {
          "text": "The array of text layout managers associated with this text content manager.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textLayoutManagers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextLayoutManager",
          "text": "NSTextLayoutManager"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/textLayoutManagers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textLayoutManagers"
        }
      ],
      "role": "symbol",
      "title": "textLayoutManagers",
      "type": "topic",
      "url": "/documentation/uikit/nstextcontentmanager/textlayoutmanagers"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextContentManagerDelegate": {
      "abstract": [
        {
          "text": "The optional methods that delegates of content manager objects implement for customizing or validating text elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextContentManagerDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextContentManagerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentManagerDelegate"
        }
      ],
      "role": "symbol",
      "title": "NSTextContentManagerDelegate",
      "type": "topic",
      "url": "/documentation/uikit/nstextcontentmanagerdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextContentStorage": {
      "abstract": [
        {
          "text": "A concrete object for managing your view’s text content and generating the text elements necessary for layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextContentStorage"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextContentStorage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentStorage"
        }
      ],
      "role": "symbol",
      "title": "NSTextContentStorage",
      "type": "topic",
      "url": "/documentation/uikit/nstextcontentstorage"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextElementProvider": {
      "abstract": [
        {
          "text": "A protocol the text content manager and its concrete subclasses conform to, which defines the interface for interacting with custom content types of a text document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextElementProvider"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextElementProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextElementProvider"
        }
      ],
      "role": "symbol",
      "title": "NSTextElementProvider",
      "type": "topic",
      "url": "/documentation/uikit/nstextelementprovider"
    },
    "doc://com.apple.uikit/documentation/UIKit/adding-writing-tools-support-to-a-custom-uiview": {
      "abstract": [
        {
          "text": "Add Writing Tools support, including support for inline replacement animations,",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "to your custom iOS views that contain text.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/adding-writing-tools-support-to-a-custom-uiview",
      "kind": "article",
      "role": "article",
      "title": "Adding Writing Tools support to a custom UIKit view",
      "type": "topic",
      "url": "/documentation/uikit/adding-writing-tools-support-to-a-custom-uiview"
    },
    "doc://com.apple.uikit/documentation/UIKit/textkit-string-attributes": {
      "abstract": [
        {
          "text": "UIKit-specific keys and values for displaying text and managing documents.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/textkit-string-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TextKit string attributes",
      "type": "topic",
      "url": "/documentation/uikit/textkit-string-attributes"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSTextContentStorage"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
        "doc://com.apple.uikit/documentation/UIKit/NSTextElementProvider"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Text-management",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSTextContentStorage",
        "doc://com.apple.documentation/documentation/foundation/nsattributedstring",
        "doc://com.apple.documentation/documentation/foundation/nsmutableattributedstring"
      ],
      "title": "Text management"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-content-manager",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/init()",
        "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/init(coder:)"
      ],
      "title": "Creating a content manager"
    },
    {
      "anchor": "Controlling-backing-store-synchronization",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/automaticallySynchronizesToBackingStore"
      ],
      "title": "Controlling backing store synchronization"
    },
    {
      "anchor": "Performing-transactions",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/hasEditingTransaction",
        "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/performEditingTransaction(_:)",
        "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/recordEditAction(in:newTextRange:)"
      ],
      "title": "Performing transactions"
    },
    {
      "anchor": "Working-with-layout-managers",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/primaryTextLayoutManager",
        "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/textLayoutManagers",
        "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/automaticallySynchronizesTextLayoutManagers",
        "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/addTextLayoutManager(_:)",
        "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/removeTextLayoutManager(_:)",
        "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/synchronizeTextLayoutManagers(_:)"
      ],
      "title": "Working with layout managers"
    },
    {
      "anchor": "Customizing-and-validating-text-elements",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/delegate",
        "doc://com.apple.uikit/documentation/UIKit/NSTextContentManagerDelegate",
        "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/EnumerationOptions"
      ],
      "title": "Customizing and validating text elements"
    },
    {
      "anchor": "Finding-a-specific-text-element",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/textElements(for:)"
      ],
      "title": "Finding a specific text element"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTextContentManager"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-content-manager",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/init()",
                "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/init(coder:)"
              ],
              "title": "Creating a content manager"
            },
            {
              "anchor": "Controlling-backing-store-synchronization",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/automaticallySynchronizesToBackingStore"
              ],
              "title": "Controlling backing store synchronization"
            },
            {
              "anchor": "Performing-transactions",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/hasEditingTransaction",
                "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/performEditingTransaction(_:)",
                "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/recordEditAction(in:newTextRange:)"
              ],
              "title": "Performing transactions"
            },
            {
              "anchor": "Working-with-layout-managers",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/primaryTextLayoutManager",
                "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/textLayoutManagers",
                "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/automaticallySynchronizesTextLayoutManagers",
                "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/addTextLayoutManager(_:)",
                "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/removeTextLayoutManager(_:)",
                "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/synchronizeTextLayoutManagers(_:)"
              ],
              "title": "Working with layout managers"
            },
            {
              "anchor": "Customizing-and-validating-text-elements",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/delegate",
                "doc://com.apple.uikit/documentation/UIKit/NSTextContentManagerDelegate",
                "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/EnumerationOptions"
              ],
              "title": "Customizing and validating text elements"
            },
            {
              "anchor": "Finding-a-specific-text-element",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager/textElements(for:)"
              ],
              "title": "Finding a specific text element"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSTextContentStorage"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
                "doc://com.apple.uikit/documentation/UIKit/NSTextElementProvider"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Text-management",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSTextContentStorage",
                "doc://com.apple.documentation/documentation/foundation/nsattributedstring",
                "doc://com.apple.documentation/documentation/foundation/nsmutableattributedstring",
                "doc://com.apple.uikit/documentation/UIKit/textkit-string-attributes"
              ],
              "title": "Text management"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSTextContentManager"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentManager/title",
          "value": "NSTextContentManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentManager~1automaticallySynchronizesToBackingStore/title",
          "value": "automaticallySynchronizesToBackingStore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentManager~1automaticallySynchronizesToBackingStore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "automaticallySynchronizesToBackingStore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextElementProvider/title",
          "value": "NSTextElementProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextElementProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextElementProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextElementProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextElementProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentManager~1init()/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentManager~1init()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "init"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentManager~1addTextLayoutManager(_:)/title",
          "value": "addTextLayoutManager:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentManager~1addTextLayoutManager(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addTextLayoutManager:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentStorage/title",
          "value": "NSTextContentStorage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentStorage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentStorage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentStorage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentStorage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentManager~1synchronizeTextLayoutManagers(_:)/title",
          "value": "synchronizeTextLayoutManagers:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentManager~1synchronizeTextLayoutManagers(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "synchronizeTextLayoutManagers:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentManager~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentManager~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentManager~1removeTextLayoutManager(_:)/title",
          "value": "removeTextLayoutManager:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentManager~1removeTextLayoutManager(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeTextLayoutManager:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentManager~1performEditingTransaction(_:)/title",
          "value": "performEditingTransactionUsingBlock:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentManager~1performEditingTransaction(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "performEditingTransactionUsingBlock:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentManager~1hasEditingTransaction/title",
          "value": "hasEditingTransaction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentManager~1hasEditingTransaction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "hasEditingTransaction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentManager~1EnumerationOptions/title",
          "value": "NSTextContentManagerEnumerationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentManager~1EnumerationOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentManagerEnumerationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentManager~1EnumerationOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentManagerEnumerationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentManager~1textLayoutManagers/title",
          "value": "textLayoutManagers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentManager~1textLayoutManagers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "textLayoutManagers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentManager~1textElements(for:)/title",
          "value": "textElementsForRange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentManager~1textElements(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textElementsForRange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentManagerDelegate/title",
          "value": "NSTextContentManagerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentManagerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentManagerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentManagerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentManagerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentManager~1automaticallySynchronizesTextLayoutManagers/title",
          "value": "automaticallySynchronizesTextLayoutManagers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentManager~1automaticallySynchronizesTextLayoutManagers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "automaticallySynchronizesTextLayoutManagers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentManager~1recordEditAction(in:newTextRange:)/title",
          "value": "recordEditActionInRange:newTextRange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentManager~1recordEditAction(in:newTextRange:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "recordEditActionInRange:newTextRange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentManager~1init(coder:)/title",
          "value": "initWithCoder:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentManager~1init(coder:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCoder:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentManager~1primaryTextLayoutManager/title",
          "value": "primaryTextLayoutManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentManager~1primaryTextLayoutManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "primaryTextLayoutManager"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/nstextcontentmanager"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/nstextcontentmanager"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
