{
  "abstract": [
    {
      "text": "A set of methods that objects implement to provide data for, and manage text selections.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)NSTextSelectionDataSource",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSTextSelectionDataSource"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTextSelectionDataSource"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "NSTextSelectionDataSource"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSTextSelectionDataSource"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager": {
      "abstract": [
        {
          "text": "The primary class that you use to manage text layout and presentation for custom text displays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextLayoutManager"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutManager"
        }
      ],
      "role": "symbol",
      "title": "NSTextLayoutManager",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutmanager"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource": {
      "abstract": [
        {
          "text": "A set of methods that objects implement to provide data for, and manage text selections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextSelectionDataSource"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextSelectionDataSource"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelectionDataSource",
      "type": "topic",
      "url": "/documentation/uikit/nstextselectiondatasource"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/baseWritingDirection(at:)": {
      "abstract": [
        {
          "text": "Returns the base writing direction at the location you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "baseWritingDirection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSTextLocation",
          "text": "NSTextLocation"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextSelectionNavigation",
          "text": "NSTextSelectionNavigation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextSelectionNavigationWritingDirection",
          "text": "WritingDirection"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/baseWritingDirection(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "baseWritingDirectionAtLocation:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "baseWritingDirection(at:)",
      "type": "topic",
      "url": "/documentation/uikit/nstextselectiondatasource/basewritingdirection(at:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/documentRange": {
      "abstract": [
        {
          "text": "Returns the starting and ending locations for the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextRange",
          "text": "NSTextRange"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/documentRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentRange"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "documentRange",
      "type": "topic",
      "url": "/documentation/uikit/nstextselectiondatasource/documentrange"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/enumerateCaretOffsetsInLineFragment(at:using:)": {
      "abstract": [
        {
          "text": "Enumerates all the insertion point caret offsets from left to right in visual order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enumerateCaretOffsetsInLineFragment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSTextLocation",
          "text": "NSTextLocation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSTextLocation",
          "text": "NSTextLocation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8ObjCBoolV",
          "text": "ObjCBool"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/enumerateCaretOffsetsInLineFragment(at:using:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enumerateCaretOffsetsInLineFragmentAtLocation:usingBlock:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "enumerateCaretOffsetsInLineFragment(at:using:)",
      "type": "topic",
      "url": "/documentation/uikit/nstextselectiondatasource/enumeratecaretoffsetsinlinefragment(at:using:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/enumerateContainerBoundaries(from:reverse:using:)": {
      "abstract": [
        {
          "text": "Enumerates all the container boundaries starting from the location you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enumerateContainerBoundaries"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSTextLocation",
          "text": "NSTextLocation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "reverse"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSTextLocation",
          "text": "NSTextLocation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8ObjCBoolV",
          "text": "ObjCBool"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/enumerateContainerBoundaries(from:reverse:using:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enumerateContainerBoundariesFromLocation:reverse:usingBlock:"
        }
      ],
      "role": "symbol",
      "title": "enumerateContainerBoundaries(from:reverse:using:)",
      "type": "topic",
      "url": "/documentation/uikit/nstextselectiondatasource/enumeratecontainerboundaries(from:reverse:using:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/enumerateSubstrings(from:options:using:)": {
      "abstract": [
        {
          "text": "Enumerates the textual segment boundaries starting at the location you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enumerateSubstrings"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSTextLocation",
          "text": "NSTextLocation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSString",
          "text": "NSString"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSStringEnumerationOptions",
          "text": "EnumerationOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextRange",
          "text": "NSTextRange"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextRange",
          "text": "NSTextRange"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8ObjCBoolV",
          "text": "ObjCBool"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/enumerateSubstrings(from:options:using:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enumerateSubstringsFromLocation:options:usingBlock:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "enumerateSubstrings(from:options:using:)",
      "type": "topic",
      "url": "/documentation/uikit/nstextselectiondatasource/enumeratesubstrings(from:options:using:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/lineFragmentRange(for:inContainerAt:)": {
      "abstract": [
        {
          "text": "Returns the range of the line fragment that contains the point you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineFragmentRange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "inContainerAt"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSTextLocation",
          "text": "NSTextLocation"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextRange",
          "text": "NSTextRange"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/lineFragmentRange(for:inContainerAt:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lineFragmentRangeForPoint:inContainerAtLocation:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "lineFragmentRange(for:inContainerAt:)",
      "type": "topic",
      "url": "/documentation/uikit/nstextselectiondatasource/linefragmentrange(for:incontainerat:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/location(_:offsetBy:)": {
      "abstract": [
        {
          "text": "Returns a new location using the location and offset you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "location"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSTextLocation",
          "text": "NSTextLocation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "offsetBy"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSTextLocation",
          "text": "NSTextLocation"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/location(_:offsetBy:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "locationFromLocation:withOffset:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "location(_:offsetBy:)",
      "type": "topic",
      "url": "/documentation/uikit/nstextselectiondatasource/location(_:offsetby:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/offset(from:to:)": {
      "abstract": [
        {
          "text": "Returns the offset between the two locations you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "offset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSTextLocation",
          "text": "NSTextLocation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSTextLocation",
          "text": "NSTextLocation"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/offset(from:to:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "offsetFromLocation:toLocation:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "offset(from:to:)",
      "type": "topic",
      "url": "/documentation/uikit/nstextselectiondatasource/offset(from:to:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/textLayoutOrientation(at:)": {
      "abstract": [
        {
          "text": "Returns the layout orientation at the location you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textLayoutOrientation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSTextLocation",
          "text": "NSTextLocation"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextSelectionNavigation",
          "text": "NSTextSelectionNavigation"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextSelectionNavigationLayoutOrientation",
          "text": "LayoutOrientation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/textLayoutOrientation(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textLayoutOrientationAtLocation:"
        }
      ],
      "role": "symbol",
      "title": "textLayoutOrientation(at:)",
      "type": "topic",
      "url": "/documentation/uikit/nstextselectiondatasource/textlayoutorientation(at:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/textRange(for:enclosing:)": {
      "abstract": [
        {
          "text": "Returns a text range that corresponds to selection granularity of the enclosing location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textRange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextSelection",
          "text": "NSTextSelection"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextSelectionGranularity",
          "text": "Granularity"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "enclosing"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSTextLocation",
          "text": "NSTextLocation"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextRange",
          "text": "NSTextRange"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/textRange(for:enclosing:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textRangeForSelectionGranularity:enclosingLocation:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "textRange(for:enclosing:)",
      "type": "topic",
      "url": "/documentation/uikit/nstextselectiondatasource/textrange(for:enclosing:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/LayoutOrientation": {
      "abstract": [
        {
          "text": "Values that describe the possible layout orientations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LayoutOrientation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/LayoutOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LayoutOrientation"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelectionNavigation.LayoutOrientation",
      "type": "topic",
      "url": "/documentation/uikit/nstextselectionnavigation/layoutorientation"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/WritingDirection": {
      "abstract": [
        {
          "text": "Values that describe the writing direction inside a text selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WritingDirection"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/WritingDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WritingDirection"
        }
      ],
      "role": "symbol",
      "title": "NSTextSelectionNavigation.WritingDirection",
      "type": "topic",
      "url": "/documentation/uikit/nstextselectionnavigation/writingdirection"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/textSelectionDataSource": {
      "abstract": [
        {
          "text": "The data source associated with this selection navigation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textSelectionDataSource"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSTextSelectionDataSource",
          "text": "NSTextSelectionDataSource"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/textSelectionDataSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textSelectionDataSource"
        }
      ],
      "role": "symbol",
      "title": "textSelectionDataSource",
      "type": "topic",
      "url": "/documentation/uikit/nstextselectionnavigation/textselectiondatasource"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-the-data-source",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/textSelectionDataSource"
      ],
      "title": "Accessing the data source"
    }
  ],
  "topicSections": [
    {
      "anchor": "Range-of-the-selection",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/documentRange"
      ],
      "title": "Range of the selection"
    },
    {
      "anchor": "Enumerating-components-of-the-selection",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/enumerateCaretOffsetsInLineFragment(at:using:)",
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/enumerateContainerBoundaries(from:reverse:using:)",
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/enumerateSubstrings(from:options:using:)"
      ],
      "title": "Enumerating components of the selection"
    },
    {
      "anchor": "Finding-specific-content-in-the-selection",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/location(_:offsetBy:)",
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/lineFragmentRange(for:inContainerAt:)",
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/offset(from:to:)",
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/textRange(for:enclosing:)"
      ],
      "title": "Finding specific content in the selection"
    },
    {
      "anchor": "Changing-the-characteristics-of-the-selection",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/baseWritingDirection(at:)",
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/WritingDirection",
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/textLayoutOrientation(at:)",
        "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/LayoutOrientation"
      ],
      "title": "Changing the characteristics of the selection"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTextSelectionDataSource"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Range-of-the-selection",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/documentRange"
              ],
              "title": "Range of the selection"
            },
            {
              "anchor": "Enumerating-components-of-the-selection",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/enumerateCaretOffsetsInLineFragment(at:using:)",
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/enumerateContainerBoundaries(from:reverse:using:)",
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/enumerateSubstrings(from:options:using:)"
              ],
              "title": "Enumerating components of the selection"
            },
            {
              "anchor": "Finding-specific-content-in-the-selection",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/location(_:offsetBy:)",
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/lineFragmentRange(for:inContainerAt:)",
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/offset(from:to:)",
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/textRange(for:enclosing:)"
              ],
              "title": "Finding specific content in the selection"
            },
            {
              "anchor": "Changing-the-characteristics-of-the-selection",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/baseWritingDirection(at:)",
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/WritingDirection",
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionDataSource/textLayoutOrientation(at:)",
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/LayoutOrientation"
              ],
              "title": "Changing the characteristics of the selection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutManager"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-the-data-source",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSTextSelectionNavigation/textSelectionDataSource"
              ],
              "title": "Accessing the data source"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSTextSelectionDataSource"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionDataSource~1textLayoutOrientation(at:)/title",
          "value": "textLayoutOrientationAtLocation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionDataSource~1textLayoutOrientation(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textLayoutOrientationAtLocation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionDataSource~1baseWritingDirection(at:)/title",
          "value": "baseWritingDirectionAtLocation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionDataSource~1baseWritingDirection(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "baseWritingDirectionAtLocation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionDataSource~1textRange(for:enclosing:)/title",
          "value": "textRangeForSelectionGranularity:enclosingLocation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionDataSource~1textRange(for:enclosing:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textRangeForSelectionGranularity:enclosingLocation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionDataSource~1enumerateCaretOffsetsInLineFragment(at:using:)/title",
          "value": "enumerateCaretOffsetsInLineFragmentAtLocation:usingBlock:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionDataSource~1enumerateCaretOffsetsInLineFragment(at:using:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "enumerateCaretOffsetsInLineFragmentAtLocation:usingBlock:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionNavigation~1LayoutOrientation/title",
          "value": "NSTextSelectionNavigationLayoutOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionNavigation~1LayoutOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigationLayoutOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionNavigation~1LayoutOrientation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigationLayoutOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionDataSource~1offset(from:to:)/title",
          "value": "offsetFromLocation:toLocation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionDataSource~1offset(from:to:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "offsetFromLocation:toLocation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager/title",
          "value": "NSTextLayoutManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextLayoutManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextLayoutManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionDataSource~1enumerateSubstrings(from:options:using:)/title",
          "value": "enumerateSubstringsFromLocation:options:usingBlock:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionDataSource~1enumerateSubstrings(from:options:using:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "enumerateSubstringsFromLocation:options:usingBlock:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionNavigation~1textSelectionDataSource/title",
          "value": "textSelectionDataSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionNavigation~1textSelectionDataSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "textSelectionDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionDataSource~1location(_:offsetBy:)/title",
          "value": "locationFromLocation:withOffset:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionDataSource~1location(_:offsetBy:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "locationFromLocation:withOffset:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionNavigation~1WritingDirection/title",
          "value": "NSTextSelectionNavigationWritingDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionNavigation~1WritingDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigationWritingDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionNavigation~1WritingDirection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionNavigationWritingDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionDataSource~1lineFragmentRange(for:inContainerAt:)/title",
          "value": "lineFragmentRangeForPoint:inContainerAtLocation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionDataSource~1lineFragmentRange(for:inContainerAt:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "lineFragmentRangeForPoint:inContainerAtLocation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionDataSource~1enumerateContainerBoundaries(from:reverse:using:)/title",
          "value": "enumerateContainerBoundariesFromLocation:reverse:usingBlock:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionDataSource~1enumerateContainerBoundaries(from:reverse:using:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "enumerateContainerBoundariesFromLocation:reverse:usingBlock:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionDataSource~1documentRange/title",
          "value": "documentRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionDataSource~1documentRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "documentRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionDataSource/title",
          "value": "NSTextSelectionDataSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionDataSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionDataSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextSelectionDataSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextSelectionDataSource"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/nstextselectiondatasource"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/nstextselectiondatasource"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
