{
  "abstract": [
    {
      "text": "A line of dots.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/patternDot",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/NSUnderlinePatternDot"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@NSUnderlinePatternDot",
    "fragments": [
      {
        "kind": "identifier",
        "text": "NSUnderlinePatternDot"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSUnderlinePatternDot"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.4",
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "18.4",
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "11.4",
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "NSUnderlinePatternDot"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@NSUnderlineStyle",
              "text": "NSUnderlineStyle"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSUnderlinePatternDot"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSUnderlineByWord": {
      "abstract": [
        {
          "text": "A line only beneath or through words, not whitespace.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSUnderlineByWord"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSUnderlineByWord",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUnderlineByWord",
      "type": "topic",
      "url": "/documentation/uikit/nsunderlinebyword"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSUnderlinePatternDash": {
      "abstract": [
        {
          "text": "A line of dashes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSUnderlinePatternDash"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSUnderlinePatternDash",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUnderlinePatternDash",
      "type": "topic",
      "url": "/documentation/uikit/nsunderlinepatterndash"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSUnderlinePatternDashDot": {
      "abstract": [
        {
          "text": "A line of alternating dashes and dots.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSUnderlinePatternDashDot"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSUnderlinePatternDashDot",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUnderlinePatternDashDot",
      "type": "topic",
      "url": "/documentation/uikit/nsunderlinepatterndashdot"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSUnderlinePatternDashDotDot": {
      "abstract": [
        {
          "text": "A line of alternating dashes and two dots.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSUnderlinePatternDashDotDot"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSUnderlinePatternDashDotDot",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUnderlinePatternDashDotDot",
      "type": "topic",
      "url": "/documentation/uikit/nsunderlinepatterndashdotdot"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSUnderlinePatternDot": {
      "abstract": [
        {
          "text": "A line of dots.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSUnderlinePatternDot"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSUnderlinePatternDot",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUnderlinePatternDot",
      "type": "topic",
      "url": "/documentation/uikit/nsunderlinepatterndot"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSUnderlinePatternSolid": {
      "abstract": [
        {
          "text": "A solid line.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSUnderlinePatternSolid"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSUnderlinePatternSolid",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUnderlinePatternSolid",
      "type": "topic",
      "url": "/documentation/uikit/nsunderlinepatternsolid"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle": {
      "abstract": [
        {
          "text": "Constants for the underline style and strikethrough style attribute keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUnderlineStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUnderlineStyle"
        }
      ],
      "role": "symbol",
      "title": "NSUnderlineStyle",
      "type": "topic",
      "url": "/documentation/uikit/nsunderlinestyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/patternDot": {
      "abstract": [
        {
          "text": "Draw a line of dots.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "patternDot"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSUnderlineStyle",
          "text": "NSUnderlineStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/patternDot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUnderlineStylePatternDot"
        }
      ],
      "role": "symbol",
      "title": "patternDot",
      "type": "topic",
      "url": "/documentation/uikit/nsunderlinestyle/patterndot"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSUnderlinePatternSolid",
        "doc://com.apple.uikit/documentation/UIKit/NSUnderlinePatternDash",
        "doc://com.apple.uikit/documentation/UIKit/NSUnderlinePatternDashDot",
        "doc://com.apple.uikit/documentation/UIKit/NSUnderlinePatternDashDotDot",
        "doc://com.apple.uikit/documentation/UIKit/NSUnderlineByWord"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSUnderlineStyle~1patternDot/title",
          "value": "NSUnderlineStylePatternDot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSUnderlineStyle~1patternDot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnderlineStylePatternDot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSUnderlineStyle/title",
          "value": "NSUnderlineStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSUnderlineStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnderlineStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSUnderlineStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnderlineStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/nsunderlinepatterndot"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
