{
  "abstract": [
    {
      "text": "Constants for the underline style and strikethrough style attribute keys.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@NSUnderlineStyle",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSUnderlineStyle"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSUnderlineStyle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "NSUnderlineStyle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSUnderlineStyle"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use these constants to specify the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyleAttributeName",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/NSStrikethroughStyleAttributeName",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " attributes of an attributed string.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSStrikethroughStyleAttributeName": {
      "abstract": [
        {
          "text": "The strikethrough style of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSStrikethroughStyleAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSStrikethroughStyleAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSStrikethroughStyleAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nsstrikethroughstyleattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextEffectStyle": {
      "abstract": [
        {
          "text": "Constants for the type of effect to apply to the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextEffectStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextEffectStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextEffectStyle",
      "type": "topic",
      "url": "/documentation/uikit/nstexteffectstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextHighlightColorScheme": {
      "abstract": [
        {
          "text": "Constants that specify the highlight color to use with the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextHighlightColorScheme"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextHighlightColorScheme",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextHighlightColorScheme",
      "type": "topic",
      "url": "/documentation/uikit/nstexthighlightcolorscheme"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextHighlightStyle": {
      "abstract": [
        {
          "text": "Constants that specify the type of highlight to apply to text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextHighlightStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextHighlightStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextHighlightStyle",
      "type": "topic",
      "url": "/documentation/uikit/nstexthighlightstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSUnderlineByWord": {
      "abstract": [
        {
          "text": "A line only beneath or through words, not whitespace.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSUnderlineByWord"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSUnderlineByWord",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUnderlineByWord",
      "type": "topic",
      "url": "/documentation/uikit/nsunderlinebyword"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSUnderlinePatternDash": {
      "abstract": [
        {
          "text": "A line of dashes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSUnderlinePatternDash"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSUnderlinePatternDash",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUnderlinePatternDash",
      "type": "topic",
      "url": "/documentation/uikit/nsunderlinepatterndash"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSUnderlinePatternDashDot": {
      "abstract": [
        {
          "text": "A line of alternating dashes and dots.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSUnderlinePatternDashDot"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSUnderlinePatternDashDot",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUnderlinePatternDashDot",
      "type": "topic",
      "url": "/documentation/uikit/nsunderlinepatterndashdot"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSUnderlinePatternDashDotDot": {
      "abstract": [
        {
          "text": "A line of alternating dashes and two dots.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSUnderlinePatternDashDotDot"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSUnderlinePatternDashDotDot",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUnderlinePatternDashDotDot",
      "type": "topic",
      "url": "/documentation/uikit/nsunderlinepatterndashdotdot"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSUnderlinePatternDot": {
      "abstract": [
        {
          "text": "A line of dots.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSUnderlinePatternDot"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSUnderlinePatternDot",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUnderlinePatternDot",
      "type": "topic",
      "url": "/documentation/uikit/nsunderlinepatterndot"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSUnderlinePatternSolid": {
      "abstract": [
        {
          "text": "A solid line.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSUnderlinePatternSolid"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSUnderlinePatternSolid",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUnderlinePatternSolid",
      "type": "topic",
      "url": "/documentation/uikit/nsunderlinepatternsolid"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle": {
      "abstract": [
        {
          "text": "Constants for the underline style and strikethrough style attribute keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUnderlineStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUnderlineStyle"
        }
      ],
      "role": "symbol",
      "title": "NSUnderlineStyle",
      "type": "topic",
      "url": "/documentation/uikit/nsunderlinestyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/NSUnderlineStyleNone": {
      "abstract": [
        {
          "text": "Don’t draw a line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSUnderlineStyleNone"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/NSUnderlineStyleNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUnderlineStyleNone",
      "type": "topic",
      "url": "/documentation/uikit/nsunderlinestyle/nsunderlinestylenone"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/NSUnderlineStylePatternSolid": {
      "abstract": [
        {
          "text": "Draw a solid line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSUnderlineStylePatternSolid"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/NSUnderlineStylePatternSolid",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUnderlineStylePatternSolid",
      "type": "topic",
      "url": "/documentation/uikit/nsunderlinestyle/nsunderlinestylepatternsolid"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/byWord": {
      "abstract": [
        {
          "text": "Draw the line only beneath or through words, not whitespace.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "byWord"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSUnderlineStyle",
          "text": "NSUnderlineStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/byWord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUnderlineStyleByWord"
        }
      ],
      "role": "symbol",
      "title": "byWord",
      "type": "topic",
      "url": "/documentation/uikit/nsunderlinestyle/byword"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/double": {
      "abstract": [
        {
          "text": "Draw a double line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "double"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSUnderlineStyle",
          "text": "NSUnderlineStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/double",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUnderlineStyleDouble"
        }
      ],
      "role": "symbol",
      "title": "double",
      "type": "topic",
      "url": "/documentation/uikit/nsunderlinestyle/double"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/init(_:)": {
      "abstract": [
        {
          "text": "Creates a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " from ",
          "type": "text"
        },
        {
          "code": "Text.LineStyle",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4TextV",
          "text": "Text"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4TextV9LineStyleV",
          "text": "LineStyle"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/uikit/nsunderlinestyle/init(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates an underline style with the specified raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/nsunderlinestyle/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/patternDash": {
      "abstract": [
        {
          "text": "Draw a line of dashes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "patternDash"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSUnderlineStyle",
          "text": "NSUnderlineStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/patternDash",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUnderlineStylePatternDash"
        }
      ],
      "role": "symbol",
      "title": "patternDash",
      "type": "topic",
      "url": "/documentation/uikit/nsunderlinestyle/patterndash"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/patternDashDot": {
      "abstract": [
        {
          "text": "Draw a line of alternating dashes and dots.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "patternDashDot"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSUnderlineStyle",
          "text": "NSUnderlineStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/patternDashDot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUnderlineStylePatternDashDot"
        }
      ],
      "role": "symbol",
      "title": "patternDashDot",
      "type": "topic",
      "url": "/documentation/uikit/nsunderlinestyle/patterndashdot"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/patternDashDotDot": {
      "abstract": [
        {
          "text": "Draw a line of alternating dashes and two dots.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "patternDashDotDot"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSUnderlineStyle",
          "text": "NSUnderlineStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/patternDashDotDot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUnderlineStylePatternDashDotDot"
        }
      ],
      "role": "symbol",
      "title": "patternDashDotDot",
      "type": "topic",
      "url": "/documentation/uikit/nsunderlinestyle/patterndashdotdot"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/patternDot": {
      "abstract": [
        {
          "text": "Draw a line of dots.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "patternDot"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSUnderlineStyle",
          "text": "NSUnderlineStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/patternDot",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUnderlineStylePatternDot"
        }
      ],
      "role": "symbol",
      "title": "patternDot",
      "type": "topic",
      "url": "/documentation/uikit/nsunderlinestyle/patterndot"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/single": {
      "abstract": [
        {
          "text": "Draw a single line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "single"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSUnderlineStyle",
          "text": "NSUnderlineStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/single",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUnderlineStyleSingle"
        }
      ],
      "role": "symbol",
      "title": "single",
      "type": "topic",
      "url": "/documentation/uikit/nsunderlinestyle/single"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/thick": {
      "abstract": [
        {
          "text": "Draw a thick line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "thick"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSUnderlineStyle",
          "text": "NSUnderlineStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/thick",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUnderlineStyleThick"
        }
      ],
      "role": "symbol",
      "title": "thick",
      "type": "topic",
      "url": "/documentation/uikit/nsunderlinestyle/thick"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyleAttributeName": {
      "abstract": [
        {
          "text": "The underline style of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSUnderlineStyleAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyleAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUnderlineStyleAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nsunderlinestyleattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSWritingDirectionFormatType": {
      "abstract": [
        {
          "text": "Constants for the writing direction attribute key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWritingDirectionFormatType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSWritingDirectionFormatType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingDirectionFormatType"
        }
      ],
      "role": "symbol",
      "title": "NSWritingDirectionFormatType",
      "type": "topic",
      "url": "/documentation/uikit/nswritingdirectionformattype"
    },
    "doc://com.apple.uikit/documentation/UIKit/textkit-string-attribute-keys": {
      "abstract": [
        {
          "text": "UIKit-specific keys you use to apply attributes to ranges of characters in an attributed string.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/textkit-string-attribute-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TextKit string attribute keys",
      "type": "topic",
      "url": "/documentation/uikit/textkit-string-attribute-keys"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-text-content-attributes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSWritingDirectionFormatType"
      ],
      "title": "Getting text content attributes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-line-style",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/single",
        "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/thick",
        "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/double",
        "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/patternDot",
        "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/patternDash",
        "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/patternDashDot",
        "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/patternDashDotDot",
        "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/byWord"
      ],
      "title": "Getting the line style"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/init(_:)",
        "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSUnderlineStyle"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnderlineStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnderlineStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-the-line-style",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/NSUnderlineStyleNone",
                "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/single",
                "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/thick",
                "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/double",
                "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/NSUnderlineStylePatternSolid",
                "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/patternDot",
                "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/patternDash",
                "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/patternDashDot",
                "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/patternDashDotDot",
                "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle/byWord"
              ],
              "title": "Getting the line style"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/NSUnderlinePatternSolid",
                "doc://com.apple.uikit/documentation/UIKit/NSUnderlinePatternDot",
                "doc://com.apple.uikit/documentation/UIKit/NSUnderlinePatternDash",
                "doc://com.apple.uikit/documentation/UIKit/NSUnderlinePatternDashDot",
                "doc://com.apple.uikit/documentation/UIKit/NSUnderlinePatternDashDotDot",
                "doc://com.apple.uikit/documentation/UIKit/NSUnderlineByWord"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-text-content-attributes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/textkit-string-attribute-keys",
                "doc://com.apple.uikit/documentation/UIKit/NSTextHighlightStyle",
                "doc://com.apple.uikit/documentation/UIKit/NSTextHighlightColorScheme",
                "doc://com.apple.uikit/documentation/UIKit/NSTextEffectStyle",
                "doc://com.apple.uikit/documentation/UIKit/NSWritingDirectionFormatType"
              ],
              "title": "Getting text content attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSUnderlineStyle"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSUnderlineStyle~1double/title",
          "value": "NSUnderlineStyleDouble"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSUnderlineStyle~1double/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnderlineStyleDouble"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSWritingDirectionFormatType/title",
          "value": "NSWritingDirectionFormatType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSWritingDirectionFormatType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingDirectionFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSWritingDirectionFormatType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingDirectionFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSUnderlineStyle~1byWord/title",
          "value": "NSUnderlineStyleByWord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSUnderlineStyle~1byWord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnderlineStyleByWord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSUnderlineStyle~1single/title",
          "value": "NSUnderlineStyleSingle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSUnderlineStyle~1single/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnderlineStyleSingle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSUnderlineStyle~1patternDashDot/title",
          "value": "NSUnderlineStylePatternDashDot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSUnderlineStyle~1patternDashDot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnderlineStylePatternDashDot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSUnderlineStyle~1patternDash/title",
          "value": "NSUnderlineStylePatternDash"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSUnderlineStyle~1patternDash/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnderlineStylePatternDash"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSUnderlineStyle/title",
          "value": "NSUnderlineStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSUnderlineStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnderlineStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSUnderlineStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnderlineStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSUnderlineStyle~1patternDashDotDot/title",
          "value": "NSUnderlineStylePatternDashDotDot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSUnderlineStyle~1patternDashDotDot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnderlineStylePatternDashDotDot"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSUnderlineStyle~1thick/title",
          "value": "NSUnderlineStyleThick"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSUnderlineStyle~1thick/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnderlineStyleThick"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSUnderlineStyle~1patternDot/title",
          "value": "NSUnderlineStylePatternDot"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSUnderlineStyle~1patternDot/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnderlineStylePatternDot"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/nsunderlinestyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/nsunderlinestyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
