{
  "abstract": [
    {
      "text": "Configure your app to appear onscreen.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/app-and-environment",
        "doc://com.apple.uikit/documentation/UIKit/scenes"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/windows-and-screens",
        "doc://com.apple.uikit/documentation/UIKit/scenes"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/app-and-environment",
        "doc://com.apple.uikit/documentation/UIKit/multitasking-on-ipad",
        "doc://com.apple.uikit/documentation/UIKit/scenes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/preparing-your-ui-to-run-in-the-foreground"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "title": "Preparing your UI to run in the foreground"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use foreground transitions to prepare your app’s UI to appear onscreen. An app’s transition to the foreground is usually in response to a user action. For example, when the user taps the app’s icon, the system launches the app and brings it to the foreground. Use a foreground transition to update your app’s UI, acquire resources, and start the services you need to handle user requests.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "All state transitions result in UIKit sending notifications to the appropriate delegate object:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In iOS 13 and later — A ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISceneDelegate",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " object.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In iOS 12 and earlier — The ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " object.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "You can support both types of delegate objects, but UIKit always uses scene delegate objects when they’re available. UIKit notifies only the scene delegate associated with the specific scene that’s entering the foreground. For information about how to configure scene support, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/specifying-the-scenes-your-app-supports",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Update-your-apps-data-model-when-entering-the-foreground",
          "level": 3,
          "text": "Update your app’s data model when entering the foreground",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "At launch time, the system starts your app in the inactive state before transitioning it to the foreground. Use your app’s launch-time methods to perform any work needed at that time. For an app that’s in the background, UIKit moves your app to the inactive state by calling one of the following methods:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "For apps that support scenes — The ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISceneDelegate/sceneWillEnterForeground(_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method of the appropriate scene delegate object.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "For all other apps — The ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationWillEnterForeground(_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "When transitioning from the background to the foreground, use these methods to load resources from disk and fetch data from the network.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For information about how to prepare your app at launch time, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/responding-to-the-launch-of-your-app",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Configure-your-user-interface-and-initial-tasks-at-activation",
          "level": 3,
          "text": "Configure your user interface and initial tasks at activation",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The system moves your app to the active state immediately before displaying the app’s UI. Activation is a good time to configure your app’s UI and runtime behavior; specifically:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Show your app’s windows, if needed.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Change the currently visible view controller, if needed.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Update the data values and state of views and controls.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Display controls to resume a paused game.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Start or resume any dispatch queues that you use to execute tasks.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Update data source objects.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Start timers for periodic tasks.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Put your configuration code in one of the following methods:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "For a scene-based UI — The ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISceneDelegate/sceneDidBecomeActive(_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method of the appropriate scene delegate object.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "For all other apps — The ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationDidBecomeActive(_:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method of your app delegate object.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Activation is also the time to put finishing touches on your UI before displaying it to the user. Don’t run any code that might block your activation method. Instead, make sure you have everything you need in advance. For example, if your data changes frequently outside of the app, use background tasks to fetch updates from the network before your app returns to the foreground. Otherwise, be prepared to display existing data while you fetch changes asynchronously.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Start-UI-specific-tasks-when-your-view-appears",
          "level": 3,
          "text": "Start UI-specific tasks when your view appears",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When your activation method returns, UIKit shows any windows that you made visible. It also notifies any relevant view controllers that their views are about to appear. Use your view controller’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/viewWillAppear(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to perform any final updates to your interface. For example:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Start user interface animations, as appropriate.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Begin playing media files, if auto-play is enabled.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Begin displaying graphics for games and immersive content at their full frame rates.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Don’t try to show a different view controller or make major changes to your user interface. By the time your view controller appears onscreen, your interface should be ready to display.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate": {
      "abstract": [
        {
          "text": "A set of methods to manage shared behaviors for your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIApplicationDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationDidBecomeActive(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the app has become active.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationDidBecomeActive"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIApplication",
          "text": "UIApplication"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationDidBecomeActive(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applicationDidBecomeActive:"
        }
      ],
      "role": "symbol",
      "title": "applicationDidBecomeActive(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationdelegate/applicationdidbecomeactive(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationWillEnterForeground(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the app is about to enter the foreground.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationWillEnterForeground"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIApplication",
          "text": "UIApplication"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationWillEnterForeground(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applicationWillEnterForeground:"
        }
      ],
      "role": "symbol",
      "title": "applicationWillEnterForeground(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationdelegate/applicationwillenterforeground(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISceneDelegate": {
      "abstract": [
        {
          "text": "The core methods you use to respond to life-cycle events occurring within a scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISceneDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISceneDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISceneDelegate"
        }
      ],
      "role": "symbol",
      "title": "UISceneDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uiscenedelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISceneDelegate/sceneDidBecomeActive(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the scene became active and is now responding to user events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sceneDidBecomeActive"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIScene",
          "text": "UIScene"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISceneDelegate/sceneDidBecomeActive(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sceneDidBecomeActive:"
        }
      ],
      "role": "symbol",
      "title": "sceneDidBecomeActive(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiscenedelegate/scenedidbecomeactive(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISceneDelegate/sceneWillEnterForeground(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the scene is about to begin running in the foreground and become visible to the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sceneWillEnterForeground"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIScene",
          "text": "UIScene"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISceneDelegate/sceneWillEnterForeground(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sceneWillEnterForeground:"
        }
      ],
      "role": "symbol",
      "title": "sceneWillEnterForeground(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiscenedelegate/scenewillenterforeground(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/viewWillAppear(_:)": {
      "abstract": [
        {
          "text": "Notifies the view controller that its view is about to be added to a view hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "viewWillAppear"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/viewWillAppear(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "viewWillAppear:"
        }
      ],
      "role": "symbol",
      "title": "viewWillAppear(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/viewwillappear(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/app-and-environment": {
      "abstract": [
        {
          "text": "Manage life-cycle events and your app’s UI scenes, and get information about traits and the environment in which your app runs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/app-and-environment",
      "kind": "article",
      "role": "collectionGroup",
      "title": "App and environment",
      "type": "topic",
      "url": "/documentation/uikit/app-and-environment"
    },
    "doc://com.apple.uikit/documentation/UIKit/multitasking-on-ipad": {
      "abstract": [
        {
          "text": "Implement multitasking APIs to seamlessly integrate your app with iPadOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/multitasking-on-ipad",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Multitasking on iPad",
      "type": "topic",
      "url": "/documentation/uikit/multitasking-on-ipad"
    },
    "doc://com.apple.uikit/documentation/UIKit/preparing-your-ui-to-run-in-the-background": {
      "abstract": [
        {
          "text": "Prepare your app to be suspended.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/preparing-your-ui-to-run-in-the-background",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Preparing your UI to run in the background",
      "type": "topic",
      "url": "/documentation/uikit/preparing-your-ui-to-run-in-the-background"
    },
    "doc://com.apple.uikit/documentation/UIKit/processing-queued-notifications": {
      "abstract": [
        {
          "text": "Respond to notifications when coming out of the suspended state.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/processing-queued-notifications",
      "kind": "article",
      "role": "article",
      "title": "Processing queued notifications",
      "type": "topic",
      "url": "/documentation/uikit/processing-queued-notifications"
    },
    "doc://com.apple.uikit/documentation/UIKit/responding-to-the-launch-of-your-app": {
      "abstract": [
        {
          "text": "Initialize your app’s data structures, prepare your app to run, and respond to any launch-time requests from the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/responding-to-the-launch-of-your-app",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Responding to the launch of your app",
      "type": "topic",
      "url": "/documentation/uikit/responding-to-the-launch-of-your-app"
    },
    "doc://com.apple.uikit/documentation/UIKit/scenes": {
      "abstract": [
        {
          "text": "Manage multiple instances of your app’s UI simultaneously, and direct resources to the appropriate instance of your UI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/scenes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Scenes",
      "type": "topic",
      "url": "/documentation/uikit/scenes"
    },
    "doc://com.apple.uikit/documentation/UIKit/specifying-the-scenes-your-app-supports": {
      "abstract": [
        {
          "text": "Tell the system about your app’s scenes, including the objects you use to manage each scene and its initial user interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/specifying-the-scenes-your-app-supports",
      "kind": "article",
      "role": "article",
      "title": "Specifying the scenes your app supports",
      "type": "topic",
      "url": "/documentation/uikit/specifying-the-scenes-your-app-supports"
    },
    "doc://com.apple.uikit/documentation/UIKit/windows-and-screens": {
      "abstract": [
        {
          "text": "Provide a container for your view hierarchies and other content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/windows-and-screens",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Windows and screens",
      "type": "topic",
      "url": "/documentation/uikit/windows-and-screens"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/preparing-your-ui-to-run-in-the-background"
      ],
      "title": "Essentials"
    }
  ],
  "topicSections": [
    {
      "anchor": "State-change-notifications",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/processing-queued-notifications"
      ],
      "title": "State-change notifications"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "State-change-notifications",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/processing-queued-notifications"
              ],
              "title": "State-change notifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/preparing-your-ui-to-run-in-the-background"
              ],
              "title": "Essentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1viewWillAppear(_:)/title",
          "value": "viewWillAppear:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1viewWillAppear(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "viewWillAppear:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneDelegate/title",
          "value": "UISceneDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISceneDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISceneDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1applicationWillEnterForeground(_:)/title",
          "value": "applicationWillEnterForeground:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1applicationWillEnterForeground(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "applicationWillEnterForeground:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneDelegate~1sceneDidBecomeActive(_:)/title",
          "value": "sceneDidBecomeActive:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneDelegate~1sceneDidBecomeActive(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sceneDidBecomeActive:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneDelegate~1sceneWillEnterForeground(_:)/title",
          "value": "sceneWillEnterForeground:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneDelegate~1sceneWillEnterForeground(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "sceneWillEnterForeground:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate/title",
          "value": "UIApplicationDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1applicationDidBecomeActive(_:)/title",
          "value": "applicationDidBecomeActive:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1applicationDidBecomeActive(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "applicationDidBecomeActive:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/preparing-your-ui-to-run-in-the-foreground"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/preparing-your-ui-to-run-in-the-foreground"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
