{
  "abstract": [
    {
      "text": "Display the system print panels and manage the printing process.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/printing"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Printing"
  },
  "references": {
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UIApplicationSupportsPrintCommand": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the app supports the Command-P keyboard shortcut.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UIApplicationSupportsPrintCommand",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIApplicationSupportsPrintCommand",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/UIApplicationSupportsPrintCommand"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMarkupTextPrintFormatter": {
      "abstract": [
        {
          "text": "An object that lays out HTML text for a multipage print job.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIMarkupTextPrintFormatter"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMarkupTextPrintFormatter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIMarkupTextPrintFormatter"
        }
      ],
      "role": "symbol",
      "title": "UIMarkupTextPrintFormatter",
      "type": "topic",
      "url": "/documentation/uikit/uimarkuptextprintformatter"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter": {
      "abstract": [
        {
          "text": "An abstract base class for print formatters, which are objects that lay out custom printable content that can cross page boundaries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPrintFormatter"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrintFormatter"
        }
      ],
      "role": "symbol",
      "title": "UIPrintFormatter",
      "type": "topic",
      "url": "/documentation/uikit/uiprintformatter"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo": {
      "abstract": [
        {
          "text": "Information about a print job that the system uses when it prints.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPrintInfo"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrintInfo"
        }
      ],
      "role": "symbol",
      "title": "UIPrintInfo",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinfo"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionController": {
      "abstract": [
        {
          "text": "A user interface that manages the printing of documents, images, and other printable content in iOS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPrintInteractionController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrintInteractionController"
        }
      ],
      "role": "symbol",
      "title": "UIPrintInteractionController",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinteractioncontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintPageRenderer": {
      "abstract": [
        {
          "text": "An object that draws pages of content to print, with or without the assistance of print formatters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPrintPageRenderer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintPageRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrintPageRenderer"
        }
      ],
      "role": "symbol",
      "title": "UIPrintPageRenderer",
      "type": "topic",
      "url": "/documentation/uikit/uiprintpagerenderer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintPaper": {
      "abstract": [
        {
          "text": "The size of paper for a print job and the rectangular area that the content prints within.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPrintPaper"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintPaper",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrintPaper"
        }
      ],
      "role": "symbol",
      "title": "UIPrintPaper",
      "type": "topic",
      "url": "/documentation/uikit/uiprintpaper"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintServiceExtension": {
      "abstract": [
        {
          "text": "An extension that locates and sets up a printer without a configuration profile.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPrintServiceExtension"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintServiceExtension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrintServiceExtension"
        }
      ],
      "role": "symbol",
      "title": "UIPrintServiceExtension",
      "type": "topic",
      "url": "/documentation/uikit/uiprintserviceextension"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrinter": {
      "abstract": [
        {
          "text": "A printer on the network.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPrinter"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrinter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrinter"
        }
      ],
      "role": "symbol",
      "title": "UIPrinter",
      "type": "topic",
      "url": "/documentation/uikit/uiprinter"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrinterDestination": {
      "abstract": [
        {
          "text": "A description of a single printer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPrinterDestination"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrinterDestination",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrinterDestination"
        }
      ],
      "role": "symbol",
      "title": "UIPrinterDestination",
      "type": "topic",
      "url": "/documentation/uikit/uiprinterdestination"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerController": {
      "abstract": [
        {
          "text": "A view controller that displays the standard interface for selecting a printer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPrinterPickerController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrinterPickerController"
        }
      ],
      "role": "symbol",
      "title": "UIPrinterPickerController",
      "type": "topic",
      "url": "/documentation/uikit/uiprinterpickercontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISimpleTextPrintFormatter": {
      "abstract": [
        {
          "text": "An object that lays out plain text for printing, possibly over multiple pages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISimpleTextPrintFormatter"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISimpleTextPrintFormatter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISimpleTextPrintFormatter"
        }
      ],
      "role": "symbol",
      "title": "UISimpleTextPrintFormatter",
      "type": "topic",
      "url": "/documentation/uikit/uisimpletextprintformatter"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewPrintFormatter": {
      "abstract": [
        {
          "text": "An object that lays out the drawn content of a view for printing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewPrintFormatter"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewPrintFormatter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewPrintFormatter"
        }
      ],
      "role": "symbol",
      "title": "UIViewPrintFormatter",
      "type": "topic",
      "url": "/documentation/uikit/uiviewprintformatter"
    },
    "doc://com.apple.uikit/documentation/UIKit/building-and-improving-your-app-with-mac-catalyst": {
      "abstract": [
        {
          "text": "Improve your iPadOS app with Mac Catalyst by supporting native controls, multiple windows, sharing, printing, menus and keyboard shortcuts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/building-and-improving-your-app-with-mac-catalyst",
      "kind": "article",
      "role": "sampleCode",
      "title": "Building and improving your app with Mac Catalyst",
      "type": "topic",
      "url": "/documentation/uikit/building-and-improving-your-app-with-mac-catalyst"
    },
    "doc://com.apple.uikit/documentation/UIKit/drawing": {
      "abstract": [
        {
          "text": "Configure your app’s drawing environment using colors, renderers, draw paths, strings, and shadows.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/drawing",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Drawing",
      "type": "topic",
      "url": "/documentation/uikit/drawing"
    },
    "doc://com.apple.uikit/documentation/UIKit/images-and-pdf": {
      "abstract": [
        {
          "text": "Create and manage images, including those that use bitmap and PDF formats.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/images-and-pdf",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Images and PDF",
      "type": "topic",
      "url": "/documentation/uikit/images-and-pdf"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Graphics-drawing-and-printing",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/images-and-pdf",
        "doc://com.apple.uikit/documentation/UIKit/drawing"
      ],
      "title": "Graphics, drawing, and printing"
    }
  ],
  "topicSections": [
    {
      "anchor": "Print-panels",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionController",
        "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerController"
      ],
      "title": "Print panels"
    },
    {
      "anchor": "Renderer",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPrintPageRenderer",
        "doc://com.apple.uikit/documentation/UIKit/building-and-improving-your-app-with-mac-catalyst"
      ],
      "title": "Renderer"
    },
    {
      "anchor": "Job-info",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPrinter",
        "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo",
        "doc://com.apple.uikit/documentation/UIKit/UIPrintPaper"
      ],
      "title": "Job info"
    },
    {
      "anchor": "Formatters",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter",
        "doc://com.apple.uikit/documentation/UIKit/UIViewPrintFormatter",
        "doc://com.apple.uikit/documentation/UIKit/UISimpleTextPrintFormatter",
        "doc://com.apple.uikit/documentation/UIKit/UIMarkupTextPrintFormatter"
      ],
      "title": "Formatters"
    },
    {
      "anchor": "Printer-service-discovery",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPrintServiceExtension",
        "doc://com.apple.uikit/documentation/UIKit/UIPrinterDestination"
      ],
      "title": "Printer service discovery"
    },
    {
      "anchor": "Keyboard-shortcut",
      "identifiers": [
        "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UIApplicationSupportsPrintCommand"
      ],
      "title": "Keyboard shortcut"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Print-panels",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionController",
                "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerController"
              ],
              "title": "Print panels"
            },
            {
              "anchor": "Renderer",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPrintPageRenderer",
                "doc://com.apple.uikit/documentation/UIKit/building-and-improving-your-app-with-mac-catalyst"
              ],
              "title": "Renderer"
            },
            {
              "anchor": "Job-info",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPrinter",
                "doc://com.apple.uikit/documentation/UIKit/UIPrintInfo",
                "doc://com.apple.uikit/documentation/UIKit/UIPrintPaper"
              ],
              "title": "Job info"
            },
            {
              "anchor": "Formatters",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter",
                "doc://com.apple.uikit/documentation/UIKit/UIViewPrintFormatter",
                "doc://com.apple.uikit/documentation/UIKit/UISimpleTextPrintFormatter",
                "doc://com.apple.uikit/documentation/UIKit/UIMarkupTextPrintFormatter"
              ],
              "title": "Formatters"
            },
            {
              "anchor": "Printer-service-discovery",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPrintServiceExtension",
                "doc://com.apple.uikit/documentation/UIKit/UIPrinterDestination"
              ],
              "title": "Printer service discovery"
            },
            {
              "anchor": "Keyboard-shortcut",
              "identifiers": [
                "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UIApplicationSupportsPrintCommand"
              ],
              "title": "Keyboard shortcut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Graphics-drawing-and-printing",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/images-and-pdf",
                "doc://com.apple.uikit/documentation/UIKit/drawing"
              ],
              "title": "Graphics, drawing, and printing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewPrintFormatter/title",
          "value": "UIViewPrintFormatter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewPrintFormatter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewPrintFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewPrintFormatter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewPrintFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo/title",
          "value": "UIPrintInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintPageRenderer/title",
          "value": "UIPrintPageRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintPageRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintPageRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintPageRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintPageRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintServiceExtension/title",
          "value": "UIPrintServiceExtension"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintServiceExtension/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintServiceExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintServiceExtension/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintServiceExtension"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinterPickerController/title",
          "value": "UIPrinterPickerController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinterPickerController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrinterPickerController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinterPickerController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrinterPickerController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintPaper/title",
          "value": "UIPrintPaper"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintPaper/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintPaper"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintPaper/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintPaper"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintFormatter/title",
          "value": "UIPrintFormatter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintFormatter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintFormatter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISimpleTextPrintFormatter/title",
          "value": "UISimpleTextPrintFormatter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISimpleTextPrintFormatter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISimpleTextPrintFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISimpleTextPrintFormatter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISimpleTextPrintFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionController/title",
          "value": "UIPrintInteractionController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintInteractionController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintInteractionController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinter/title",
          "value": "UIPrinter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrinter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrinter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinterDestination/title",
          "value": "UIPrinterDestination"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinterDestination/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrinterDestination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinterDestination/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrinterDestination"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMarkupTextPrintFormatter/title",
          "value": "UIMarkupTextPrintFormatter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMarkupTextPrintFormatter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMarkupTextPrintFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMarkupTextPrintFormatter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMarkupTextPrintFormatter"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/printing"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/printing"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
