{
  "abstract": [
    {
      "text": "Create animations by changing the properties of a view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/animation-and-haptics"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/property-based-animations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Property-based animations"
  },
  "references": {
    "Unifying-your-app-s-animations-PageImage-card.png": {
      "alt": null,
      "identifier": "Unifying-your-app-s-animations-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/3559438f813d2163ecacac3918dbff5f/Unifying-your-app-s-animations-PageImage-card~dark@2x.png"
        },
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/db26bd6bfe171a450c126a68c3bd92d4/Unifying-your-app-s-animations-PageImage-card@2x.png"
        }
      ]
    },
    "doc://com.apple.documentation/documentation/QuartzCore/optimizing-promotion-refresh-rates-for-iphone-13-pro-and-ipad-pro": {
      "abstract": [
        {
          "text": "Provide custom animated content for ProMotion displays.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/QuartzCore/optimizing-promotion-refresh-rates-for-iphone-13-pro-and-ipad-pro",
      "kind": "article",
      "role": "article",
      "title": "Optimizing ProMotion refresh rates for iPhone 13 Pro and iPad Pro",
      "type": "topic",
      "url": "/documentation/QuartzCore/optimizing-promotion-refresh-rates-for-iphone-13-pro-and-ipad-pro"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Unifying-your-app-s-animations": {
      "abstract": [
        {
          "text": "Create a consistent UI animation experience across SwiftUI, UIKit, and AppKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Unifying-your-app-s-animations",
      "images": [
        {
          "identifier": "Unifying-your-app-s-animations-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "article",
      "title": "Unifying your app’s animations",
      "type": "topic",
      "url": "/documentation/SwiftUI/Unifying-your-app-s-animations"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICubicTimingParameters": {
      "abstract": [
        {
          "text": "The timing information for animations in the form of a cubic Bézier curve.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICubicTimingParameters"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICubicTimingParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICubicTimingParameters"
        }
      ],
      "role": "symbol",
      "title": "UICubicTimingParameters",
      "type": "topic",
      "url": "/documentation/uikit/uicubictimingparameters"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISpringTimingParameters": {
      "abstract": [
        {
          "text": "The timing information for animations that mimics the behavior of a spring.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISpringTimingParameters"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISpringTimingParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISpringTimingParameters"
        }
      ],
      "role": "symbol",
      "title": "UISpringTimingParameters",
      "type": "topic",
      "url": "/documentation/uikit/uispringtimingparameters"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider": {
      "abstract": [
        {
          "text": "An interface for providing the timing information needed to perform animations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITimingCurveProvider"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITimingCurveProvider"
        }
      ],
      "role": "symbol",
      "title": "UITimingCurveProvider",
      "type": "topic",
      "url": "/documentation/uikit/uitimingcurveprovider"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewAnimating": {
      "abstract": [
        {
          "text": "An interface for implementing custom animator objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewAnimating"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewAnimating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewAnimating"
        }
      ],
      "role": "symbol",
      "title": "UIViewAnimating",
      "type": "topic",
      "url": "/documentation/uikit/uiviewanimating"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewImplicitlyAnimating": {
      "abstract": [
        {
          "text": "An interface for modifying an animation while it’s running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewImplicitlyAnimating"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewImplicitlyAnimating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewImplicitlyAnimating"
        }
      ],
      "role": "symbol",
      "title": "UIViewImplicitlyAnimating",
      "type": "topic",
      "url": "/documentation/uikit/uiviewimplicitlyanimating"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewPropertyAnimator": {
      "abstract": [
        {
          "text": "A class that animates changes to views and allows the dynamic modification of those animations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewPropertyAnimator"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewPropertyAnimator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewPropertyAnimator"
        }
      ],
      "role": "symbol",
      "title": "UIViewPropertyAnimator",
      "type": "topic",
      "url": "/documentation/uikit/uiviewpropertyanimator"
    },
    "doc://com.apple.uikit/documentation/UIKit/animation-and-haptics": {
      "abstract": [
        {
          "text": "Provide feedback to users using view-based animations and haptics.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/animation-and-haptics",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Animation and haptics",
      "type": "topic",
      "url": "/documentation/uikit/animation-and-haptics"
    },
    "doc://com.apple.uikit/documentation/UIKit/view-controller-transitions": {
      "abstract": [
        {
          "text": "Define custom transitions from one view controller to another.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/view-controller-transitions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "View controller transitions",
      "type": "topic",
      "url": "/documentation/uikit/view-controller-transitions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Content-animations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/view-controller-transitions",
        "doc://com.apple.documentation/documentation/SwiftUI/Unifying-your-app-s-animations",
        "doc://com.apple.documentation/documentation/QuartzCore/optimizing-promotion-refresh-rates-for-iphone-13-pro-and-ipad-pro"
      ],
      "title": "Content animations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIViewPropertyAnimator",
        "doc://com.apple.uikit/documentation/UIKit/UIViewAnimating"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Timing-curves",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider",
        "doc://com.apple.uikit/documentation/UIKit/UISpringTimingParameters",
        "doc://com.apple.uikit/documentation/UIKit/UICubicTimingParameters"
      ],
      "title": "Timing curves"
    },
    {
      "anchor": "In-progress-animations",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIViewImplicitlyAnimating"
      ],
      "title": "In-progress animations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIViewPropertyAnimator",
                "doc://com.apple.uikit/documentation/UIKit/UIViewAnimating"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "Timing-curves",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider",
                "doc://com.apple.uikit/documentation/UIKit/UISpringTimingParameters",
                "doc://com.apple.uikit/documentation/UIKit/UICubicTimingParameters"
              ],
              "title": "Timing curves"
            },
            {
              "anchor": "In-progress-animations",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIViewImplicitlyAnimating"
              ],
              "title": "In-progress animations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Content-animations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/view-controller-transitions",
                "doc://com.apple.documentation/documentation/QuartzCore/optimizing-promotion-refresh-rates-for-iphone-13-pro-and-ipad-pro"
              ],
              "title": "Content animations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewPropertyAnimator/title",
          "value": "UIViewPropertyAnimator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewPropertyAnimator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewPropertyAnimator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewPropertyAnimator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewPropertyAnimator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewAnimating/title",
          "value": "UIViewAnimating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewAnimating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewAnimating/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITimingCurveProvider/title",
          "value": "UITimingCurveProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITimingCurveProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITimingCurveProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITimingCurveProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITimingCurveProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISpringTimingParameters/title",
          "value": "UISpringTimingParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISpringTimingParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISpringTimingParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISpringTimingParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISpringTimingParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICubicTimingParameters/title",
          "value": "UICubicTimingParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICubicTimingParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICubicTimingParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICubicTimingParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICubicTimingParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewImplicitlyAnimating/title",
          "value": "UIViewImplicitlyAnimating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewImplicitlyAnimating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewImplicitlyAnimating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewImplicitlyAnimating/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewImplicitlyAnimating"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/property-based-animations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/property-based-animations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
