{
  "abstract": [
    {
      "text": "Secure personal data, and respect user preferences for how data is used.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/protecting-the-user-s-privacy"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "title": "Protecting the User’s Privacy"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Designing for user privacy is important. Most Apple devices contain personal data that the user doesn’t want to expose to apps or to external entities. If your app accesses or uses data inappropriately, the user might stop using your app and even delete it from their device.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Access user or device data only with the user’s informed consent obtained in accordance with applicable law. In addition, take appropriate steps to protect user and device data, and be transparent about how you use it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Review-Guidelines-from-Government-and-Industry-Sources",
          "level": 3,
          "text": "Review Guidelines from Government and Industry Sources",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Consult these documents:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://www.ftc.gov/sites/default/files/documents/reports/mobile-privacy-disclosures-building-trust-through-transparency-federal-trade-commission-staff-report/130201mobileprivacyreport.pdf",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". The Federal Trade Commission’s report on mobile privacy.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://ec.europa.eu/justice/article-29/documentation/opinion-recommendation/files/2013/wp202_en.pdf",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". The EU Data Protection Commissioners’ opinion on data protection for mobile apps.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "https://oag.ca.gov/sites/all/files/agweb/pdfs/privacy/privacy_on_the_go.pdf",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". The California State Attorney General’s recommendations for mobile privacy.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Smartphone Privacy Initiative (2012) in ",
                      "type": "text"
                    },
                    {
                      "identifier": "http://www.soumu.go.jp/main_sosiki/joho_tsusin/eng/presentation/pdf/Initiative.pdf",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " or ",
                      "type": "text"
                    },
                    {
                      "identifier": "http://www.soumu.go.jp/main_content/000171225.pdf",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " and Smartphone Privacy Initiative II (2013) in ",
                      "type": "text"
                    },
                    {
                      "identifier": "http://www.soumu.go.jp/main_sosiki/joho_tsusin/eng/presentation/pdf/Summary_II.pdf",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " or ",
                      "type": "text"
                    },
                    {
                      "identifier": "http://www.soumu.go.jp/main_content/000247654.pdf",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". The Japanese Ministry of Internal Affairs and Communications’ Smartphone Privacy Initiatives.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Request-Access-Only-When-Your-App-Needs-the-Data",
          "level": 3,
          "text": "Request Access Only When Your App Needs the Data",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Request access to sensitive user or device data—like location, contacts, and photos—at the time your app needs the data. Supply a purpose string (sometimes called a usage description string) in your app’s ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " file that the system can present to a user explaining why your app needs access. Provide reasonable fallback behavior in situations where the user doesn’t grant access to the requested data. For more details, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/requesting-access-to-protected-resources",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Be-Transparent-About-How-Data-Will-Be-Used",
          "level": 3,
          "text": "Be Transparent About How Data Will Be Used",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For example, when you submit your app to the App Store, specify a URL for your privacy policy or statement as part of your App Store Connect metadata. You can also summarize that policy or statement in your app description.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Give-the-User-Control-Over-Data-and-Protect-Data-You-Collect",
          "level": 3,
          "text": "Give the User Control Over Data and Protect Data You Collect",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Respect the user’s preferences, and take reasonable steps to protect the data that you collect in your apps:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Provide settings that allow the user to disable access to sensitive information. The operating system does this automatically for protected system resources—like location, contacts, and health data—through the Privacy menu of the Settings app. Extend this behavior to any data you cache from these sources or collect directly. For example, if your users build a social media profile containing personal information, offer them a way to delete the data (including any server copies you have).",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "When storing files in iOS, use the strongest data protection level that works for your app, as described in ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/encrypting-your-app-s-files",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". Use App Transport Security when sending user or device data over the network, as described in ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/plist/info/NSAppTransportSecurity",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If your app uses the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AdSupport/ASIdentifierManager",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " class, respect the value of its ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AdSupport/ASIdentifierManager/isAdvertisingTrackingEnabled",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property. If the user sets that property to false, then use the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AdSupport/ASIdentifierManager",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " class only for limited advertising purposes, like frequency capping, attribution, conversion events, estimating the number of unique users, advertising fraud detection, and debugging. See the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AdSupport",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " framework for additional information.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If you must identify users persistently, use the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDevice/identifierForVendor",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property of the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDevice",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " class or the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AdSupport/ASIdentifierManager/advertisingIdentifier",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " property of the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/AdSupport/ASIdentifierManager",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " class.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Use-the-Minimum-Amount-of-Data-Required",
          "level": 3,
          "text": "Use the Minimum Amount of Data Required",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Request and use the minimum amount of user or device data needed to accomplish a given task. Don’t seek access to or collect data for unnecessary or non-obvious reasons, or because you think it might be useful later.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If your app supports audio input, configure your audio session for recording only at the point where you actually plan to begin recording. Don’t configure your audio session for recording at launch time if you don’t plan to record right away. The system alerts users when apps configure their audio session for recording and gives the user the option to disable recording for your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/AdSupport": {
      "abstract": [
        {
          "text": "Provide apps with access to an advertising identifier.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AdSupport",
      "kind": "symbol",
      "role": "collection",
      "title": "AdSupport",
      "type": "topic",
      "url": "/documentation/AdSupport"
    },
    "doc://com.apple.documentation/documentation/AdSupport/ASIdentifierManager": {
      "abstract": [
        {
          "text": "The object that contains the advertising identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ASIdentifierManager"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AdSupport/ASIdentifierManager",
      "kind": "symbol",
      "role": "symbol",
      "title": "ASIdentifierManager",
      "type": "topic",
      "url": "/documentation/AdSupport/ASIdentifierManager"
    },
    "doc://com.apple.documentation/documentation/AdSupport/ASIdentifierManager/advertisingIdentifier": {
      "abstract": [
        {
          "text": "The UUID that is specific to a device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "advertisingIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AdSupport/ASIdentifierManager/advertisingIdentifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "advertisingIdentifier",
      "type": "topic",
      "url": "/documentation/AdSupport/ASIdentifierManager/advertisingIdentifier"
    },
    "doc://com.apple.documentation/documentation/AdSupport/ASIdentifierManager/isAdvertisingTrackingEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the user has limited ad tracking enabled.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAdvertisingTrackingEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AdSupport/ASIdentifierManager/isAdvertisingTrackingEnabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "isAdvertisingTrackingEnabled",
      "type": "topic",
      "url": "/documentation/AdSupport/ASIdentifierManager/isAdvertisingTrackingEnabled"
    },
    "doc://com.apple.documentation/documentation/Updates/UIKit": {
      "abstract": [
        {
          "text": "Learn about important changes to UIKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Updates/UIKit",
      "kind": "article",
      "role": "article",
      "title": "UIKit updates",
      "type": "topic",
      "url": "/documentation/Updates/UIKit"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDevice": {
      "abstract": [
        {
          "text": "A representation of the current device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDevice"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDevice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDevice"
        }
      ],
      "role": "symbol",
      "title": "UIDevice",
      "type": "topic",
      "url": "/documentation/uikit/uidevice"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDevice/identifierForVendor": {
      "abstract": [
        {
          "text": "An alphanumeric string that uniquely identifies a device to the app’s vendor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifierForVendor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDevice/identifierForVendor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identifierForVendor"
        }
      ],
      "role": "symbol",
      "title": "identifierForVendor",
      "type": "topic",
      "url": "/documentation/uikit/uidevice/identifierforvendor"
    },
    "doc://com.apple.uikit/documentation/UIKit/about-app-development-with-uikit": {
      "abstract": [
        {
          "text": "Learn about the basic support that UIKit and Xcode provide for your iOS and tvOS apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/about-app-development-with-uikit",
      "kind": "article",
      "role": "article",
      "title": "About App Development with UIKit",
      "type": "topic",
      "url": "/documentation/uikit/about-app-development-with-uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/encrypting-your-app-s-files": {
      "abstract": [
        {
          "text": "Protect the user’s data in iOS by encrypting it on disk.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/encrypting-your-app-s-files",
      "kind": "article",
      "role": "article",
      "title": "Encrypting Your App’s Files",
      "type": "topic",
      "url": "/documentation/uikit/encrypting-your-app-s-files"
    },
    "doc://com.apple.uikit/documentation/UIKit/requesting-access-to-protected-resources": {
      "abstract": [
        {
          "text": "Provide a purpose string that explains to a person why you need access to protected resources on their device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/requesting-access-to-protected-resources",
      "kind": "article",
      "role": "article",
      "title": "Requesting access to protected resources",
      "type": "topic",
      "url": "/documentation/uikit/requesting-access-to-protected-resources"
    },
    "http://www.soumu.go.jp/main_content/000171225.pdf": {
      "identifier": "http://www.soumu.go.jp/main_content/000171225.pdf",
      "title": "Japanese",
      "titleInlineContent": [
        {
          "text": "Japanese",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "http://www.soumu.go.jp/main_content/000171225.pdf"
    },
    "http://www.soumu.go.jp/main_content/000247654.pdf": {
      "identifier": "http://www.soumu.go.jp/main_content/000247654.pdf",
      "title": "Japanese",
      "titleInlineContent": [
        {
          "text": "Japanese",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "http://www.soumu.go.jp/main_content/000247654.pdf"
    },
    "http://www.soumu.go.jp/main_sosiki/joho_tsusin/eng/presentation/pdf/Initiative.pdf": {
      "identifier": "http://www.soumu.go.jp/main_sosiki/joho_tsusin/eng/presentation/pdf/Initiative.pdf",
      "title": "English",
      "titleInlineContent": [
        {
          "text": "English",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "http://www.soumu.go.jp/main_sosiki/joho_tsusin/eng/presentation/pdf/Initiative.pdf"
    },
    "http://www.soumu.go.jp/main_sosiki/joho_tsusin/eng/presentation/pdf/Summary_II.pdf": {
      "identifier": "http://www.soumu.go.jp/main_sosiki/joho_tsusin/eng/presentation/pdf/Summary_II.pdf",
      "title": "English",
      "titleInlineContent": [
        {
          "text": "English",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "http://www.soumu.go.jp/main_sosiki/joho_tsusin/eng/presentation/pdf/Summary_II.pdf"
    },
    "https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/plist/info/NSAppTransportSecurity": {
      "identifier": "https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/plist/info/NSAppTransportSecurity",
      "title": "NSAppTransportSecurity",
      "titleInlineContent": [
        {
          "text": "NSAppTransportSecurity",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/plist/info/NSAppTransportSecurity"
    },
    "https://ec.europa.eu/justice/article-29/documentation/opinion-recommendation/files/2013/wp202_en.pdf": {
      "identifier": "https://ec.europa.eu/justice/article-29/documentation/opinion-recommendation/files/2013/wp202_en.pdf",
      "title": "Opinion 02/2013 on Apps on Smart Devices",
      "titleInlineContent": [
        {
          "text": "Opinion 02/2013 on Apps on Smart Devices",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://ec.europa.eu/justice/article-29/documentation/opinion-recommendation/files/2013/wp202_en.pdf"
    },
    "https://oag.ca.gov/sites/all/files/agweb/pdfs/privacy/privacy_on_the_go.pdf": {
      "identifier": "https://oag.ca.gov/sites/all/files/agweb/pdfs/privacy/privacy_on_the_go.pdf",
      "title": "Privacy on the Go: Recommendations for the Mobile Ecosystem",
      "titleInlineContent": [
        {
          "text": "Privacy on the Go: Recommendations for the Mobile Ecosystem",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://oag.ca.gov/sites/all/files/agweb/pdfs/privacy/privacy_on_the_go.pdf"
    },
    "https://www.ftc.gov/sites/default/files/documents/reports/mobile-privacy-disclosures-building-trust-through-transparency-federal-trade-commission-staff-report/130201mobileprivacyreport.pdf": {
      "identifier": "https://www.ftc.gov/sites/default/files/documents/reports/mobile-privacy-disclosures-building-trust-through-transparency-federal-trade-commission-staff-report/130201mobileprivacyreport.pdf",
      "title": "Mobile Privacy Disclosures: Building Trust Through Transparency",
      "titleInlineContent": [
        {
          "text": "Mobile Privacy Disclosures: Building Trust Through Transparency",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://www.ftc.gov/sites/default/files/documents/reports/mobile-privacy-disclosures-building-trust-through-transparency-federal-trade-commission-staff-report/130201mobileprivacyreport.pdf"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/Updates/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/about-app-development-with-uikit"
      ],
      "title": "Essentials"
    }
  ],
  "topicSections": [
    {
      "anchor": "Supporting-Privacy",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/requesting-access-to-protected-resources",
        "doc://com.apple.uikit/documentation/UIKit/encrypting-your-app-s-files"
      ],
      "title": "Supporting Privacy"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Supporting-Privacy",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/requesting-access-to-protected-resources",
                "doc://com.apple.uikit/documentation/UIKit/encrypting-your-app-s-files"
              ],
              "title": "Supporting Privacy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/about-app-development-with-uikit"
              ],
              "title": "Essentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDevice~1identifierForVendor/title",
          "value": "identifierForVendor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDevice~1identifierForVendor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "identifierForVendor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AdSupport~1ASIdentifierManager/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ASIdentifierManager"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AdSupport~1ASIdentifierManager~1advertisingIdentifier/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSUUID",
              "text": "NSUUID"
            },
            {
              "kind": "text",
              "text": " * "
            },
            {
              "kind": "identifier",
              "text": "advertisingIdentifier"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDevice/title",
          "value": "UIDevice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDevice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDevice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDevice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AdSupport~1ASIdentifierManager~1isAdvertisingTrackingEnabled/title",
          "value": "advertisingTrackingEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AdSupport~1ASIdentifierManager~1isAdvertisingTrackingEnabled/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "kind": "keyword",
              "text": "nonatomic"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "readonly"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "keyword",
              "text": "getter"
            },
            {
              "kind": "text",
              "text": "="
            },
            {
              "kind": "identifier",
              "text": "isAdvertisingTrackingEnabled"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BOOL",
              "text": "BOOL"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "advertisingTrackingEnabled"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/protecting-the-user-s-privacy"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/protecting-the-user-s-privacy"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
