{
  "abstract": [
    {
      "text": "Manage the images, strings, storyboards, and nib files that you use to implement your app’s interface.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/resource-management"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Resource management"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSDataAsset": {
      "abstract": [
        {
          "text": "An object from a data set type stored in an asset catalog.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDataAsset"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSDataAsset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDataAsset"
        }
      ],
      "role": "symbol",
      "title": "NSDataAsset",
      "type": "topic",
      "url": "/documentation/uikit/nsdataasset"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImageAsset": {
      "abstract": [
        {
          "text": "A container for a collection of images that represent multiple ways of describing a single piece of artwork.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIImageAsset"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImageAsset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImageAsset"
        }
      ],
      "role": "symbol",
      "title": "UIImageAsset",
      "type": "topic",
      "url": "/documentation/uikit/uiimageasset"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINib": {
      "abstract": [
        {
          "text": "An object that contains Interface Builder nib files.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UINib"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINib",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UINib"
        }
      ],
      "role": "symbol",
      "title": "UINib",
      "type": "topic",
      "url": "/documentation/uikit/uinib"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIStoryboard": {
      "abstract": [
        {
          "text": "An encapsulation of the design-time view controller graph represented in an Interface Builder storyboard resource file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIStoryboard"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIStoryboard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIStoryboard"
        }
      ],
      "role": "symbol",
      "title": "UIStoryboard",
      "type": "topic",
      "url": "/documentation/uikit/uistoryboard"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIStoryboardSegue": {
      "abstract": [
        {
          "text": "An object that prepares for and performs the visual transition between two view controllers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIStoryboardSegue"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIStoryboardSegue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIStoryboardSegue"
        }
      ],
      "role": "symbol",
      "title": "UIStoryboardSegue",
      "type": "topic",
      "url": "/documentation/uikit/uistoryboardsegue"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIStoryboardUnwindSegueSource": {
      "abstract": [
        {
          "text": "An encapsulation of information about an unwind segue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIStoryboardUnwindSegueSource"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIStoryboardUnwindSegueSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIStoryboardUnwindSegueSource"
        }
      ],
      "role": "symbol",
      "title": "UIStoryboardUnwindSegueSource",
      "type": "topic",
      "url": "/documentation/uikit/uistoryboardunwindseguesource"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIStoryboardViewControllerCreator": {
      "abstract": [
        {
          "text": "A handler block that contains the custom initialization code for a view controller you instantiate from a storyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIStoryboardViewControllerCreator"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIStoryboardViewControllerCreator",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIStoryboardViewControllerCreator",
      "type": "topic",
      "url": "/documentation/uikit/uistoryboardviewcontrollercreator"
    },
    "doc://com.apple.uikit/documentation/UIKit/app-and-environment": {
      "abstract": [
        {
          "text": "Manage life-cycle events and your app’s UI scenes, and get information about traits and the environment in which your app runs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/app-and-environment",
      "kind": "article",
      "role": "collectionGroup",
      "title": "App and environment",
      "type": "topic",
      "url": "/documentation/uikit/app-and-environment"
    },
    "doc://com.apple.uikit/documentation/UIKit/app-extensions": {
      "abstract": [
        {
          "text": "Extend your app’s basic functionality to other parts of the system.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/app-extensions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "App extensions",
      "type": "topic",
      "url": "/documentation/uikit/app-extensions"
    },
    "doc://com.apple.uikit/documentation/UIKit/customizing-the-behavior-of-segue-based-presentations": {
      "abstract": [
        {
          "text": "Pass data between view controllers during a segue, and programmatically control when segues occur.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/customizing-the-behavior-of-segue-based-presentations",
      "kind": "article",
      "role": "article",
      "title": "Customizing the behavior of segue-based presentations",
      "type": "topic",
      "url": "/documentation/uikit/customizing-the-behavior-of-segue-based-presentations"
    },
    "doc://com.apple.uikit/documentation/UIKit/dismissing-a-view-controller-with-an-unwind-segue": {
      "abstract": [
        {
          "text": "Configure an unwind segue in your storyboard file that dynamically chooses the most appropriate view controller to display next.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/dismissing-a-view-controller-with-an-unwind-segue",
      "kind": "article",
      "role": "article",
      "title": "Dismissing a view controller with an unwind segue",
      "type": "topic",
      "url": "/documentation/uikit/dismissing-a-view-controller-with-an-unwind-segue"
    },
    "doc://com.apple.uikit/documentation/UIKit/documents-data-and-pasteboard": {
      "abstract": [
        {
          "text": "Organize your app’s data and share that data on the pasteboard.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/documents-data-and-pasteboard",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Documents, data, and pasteboard",
      "type": "topic",
      "url": "/documentation/uikit/documents-data-and-pasteboard"
    },
    "doc://com.apple.uikit/documentation/UIKit/interprocess-communication": {
      "abstract": [
        {
          "text": "Display activity-based services to people.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/interprocess-communication",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Interprocess communication",
      "type": "topic",
      "url": "/documentation/uikit/interprocess-communication"
    },
    "doc://com.apple.uikit/documentation/UIKit/mac-catalyst": {
      "abstract": [
        {
          "text": "Create a version of your iPad app that users can run on a Mac device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/mac-catalyst",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Mac Catalyst",
      "type": "topic",
      "url": "/documentation/uikit/mac-catalyst"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "App-structure",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/app-and-environment",
        "doc://com.apple.uikit/documentation/UIKit/documents-data-and-pasteboard",
        "doc://com.apple.uikit/documentation/UIKit/app-extensions",
        "doc://com.apple.uikit/documentation/UIKit/interprocess-communication",
        "doc://com.apple.uikit/documentation/UIKit/mac-catalyst"
      ],
      "title": "App structure"
    }
  ],
  "topicSections": [
    {
      "anchor": "Storyboards",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/customizing-the-behavior-of-segue-based-presentations",
        "doc://com.apple.uikit/documentation/UIKit/dismissing-a-view-controller-with-an-unwind-segue",
        "doc://com.apple.uikit/documentation/UIKit/UIStoryboard",
        "doc://com.apple.uikit/documentation/UIKit/UIStoryboardSegue",
        "doc://com.apple.uikit/documentation/UIKit/UIStoryboardUnwindSegueSource"
      ],
      "title": "Storyboards"
    },
    {
      "anchor": "Assets",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIImageAsset",
        "doc://com.apple.uikit/documentation/UIKit/NSDataAsset"
      ],
      "title": "Assets"
    },
    {
      "anchor": "Nib-files",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UINib"
      ],
      "title": "Nib files"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Storyboards",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/customizing-the-behavior-of-segue-based-presentations",
                "doc://com.apple.uikit/documentation/UIKit/dismissing-a-view-controller-with-an-unwind-segue",
                "doc://com.apple.uikit/documentation/UIKit/UIStoryboard",
                "doc://com.apple.uikit/documentation/UIKit/UIStoryboardSegue",
                "doc://com.apple.uikit/documentation/UIKit/UIStoryboardUnwindSegueSource",
                "doc://com.apple.uikit/documentation/UIKit/UIStoryboardViewControllerCreator"
              ],
              "title": "Storyboards"
            },
            {
              "anchor": "Assets",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIImageAsset",
                "doc://com.apple.uikit/documentation/UIKit/NSDataAsset"
              ],
              "title": "Assets"
            },
            {
              "anchor": "Nib-files",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UINib"
              ],
              "title": "Nib files"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "App-structure",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/app-and-environment",
                "doc://com.apple.uikit/documentation/UIKit/documents-data-and-pasteboard",
                "doc://com.apple.uikit/documentation/UIKit/app-extensions",
                "doc://com.apple.uikit/documentation/UIKit/interprocess-communication",
                "doc://com.apple.uikit/documentation/UIKit/mac-catalyst"
              ],
              "title": "App structure"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINib/title",
          "value": "UINib"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINib/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UINib"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINib/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UINib"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStoryboard/title",
          "value": "UIStoryboard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStoryboard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIStoryboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStoryboard/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIStoryboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImageAsset/title",
          "value": "UIImageAsset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImageAsset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImageAsset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStoryboardSegue/title",
          "value": "UIStoryboardSegue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStoryboardSegue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIStoryboardSegue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStoryboardSegue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIStoryboardSegue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStoryboardUnwindSegueSource/title",
          "value": "UIStoryboardUnwindSegueSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStoryboardUnwindSegueSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIStoryboardUnwindSegueSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStoryboardUnwindSegueSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIStoryboardUnwindSegueSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSDataAsset/title",
          "value": "NSDataAsset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSDataAsset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDataAsset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSDataAsset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDataAsset"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/resource-management"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/resource-management"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
