{
  "abstract": [
    {
      "text": "Provide continuity for the user by preserving current activities.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/view-controllers"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/view-controllers",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/app-and-environment",
        "doc://com.apple.uikit/documentation/UIKit/scenes",
        "doc://com.apple.uikit/documentation/UIKit/UISceneDelegate"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/windows-and-screens",
        "doc://com.apple.uikit/documentation/UIKit/scenes",
        "doc://com.apple.uikit/documentation/UIKit/UISceneDelegate"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/app-and-environment",
        "doc://com.apple.uikit/documentation/UIKit/multitasking-on-ipad",
        "doc://com.apple.uikit/documentation/UIKit/scenes",
        "doc://com.apple.uikit/documentation/UIKit/UISceneDelegate"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/app-and-environment",
        "doc://com.apple.uikit/documentation/UIKit/scenes",
        "doc://com.apple.uikit/documentation/UIKit/UIScene",
        "doc://com.apple.uikit/documentation/UIKit/UISceneDelegate"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/windows-and-screens",
        "doc://com.apple.uikit/documentation/UIKit/scenes",
        "doc://com.apple.uikit/documentation/UIKit/UIScene",
        "doc://com.apple.uikit/documentation/UIKit/UISceneDelegate"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/app-and-environment",
        "doc://com.apple.uikit/documentation/UIKit/multitasking-on-ipad",
        "doc://com.apple.uikit/documentation/UIKit/scenes",
        "doc://com.apple.uikit/documentation/UIKit/UIScene",
        "doc://com.apple.uikit/documentation/UIKit/UISceneDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/restoring-your-app-s-state"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Restoring your app’s state"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This sample project demonstrates how to preserve your appʼs state information and restore the app to that previous state on subsequent launches. During a subsequent launch, restoring your interface to the previous interaction point provides continuity for the user, and lets them finish active tasks quickly.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When using your app, the user performs actions that affect the user interface. For example, the user might view a specific page of information, and after the user leaves the app, the operating system might terminate it to free up the resources it holds. The user should be able to return to where they left off — and UI state restoration is a core part of making that experience seamless.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This sample app demonstrates the use of state preservation and restoration for scenarios where the system interrupts the app. The sample project manages a set of products. Each product has a title, an image, and other metadata you can view and edit. The project shows how to preserve and restore a product in its ",
              "type": "text"
            },
            {
              "code": "DetailParentViewController",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The sample supports two state preservation approaches. In iOS 13 and later, apps save the state for each window scene using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsuseractivity",
              "isActive": true,
              "overridingTitle": "NSUserActivity",
              "overridingTitleInlineContent": [
                {
                  "code": "NSUserActivity",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " objects. In iOS 12 and earlier, apps preserve the state of their user interfaces by saving and restoring the configuration of view controllers.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For scene-based apps, UIKit asks each scene to save its state information using an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsuseractivity",
              "isActive": true,
              "overridingTitle": "NSUserActivity",
              "overridingTitleInlineContent": [
                {
                  "code": "NSUserActivity",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " object. ",
              "type": "text"
            },
            {
              "code": "NSUserActivity",
              "type": "codeVoice"
            },
            {
              "text": " is a core part of modern state restoration with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScene",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UISceneDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". In your own apps, you use the activity object to store information needed to recreate your scene’s interface and restore the content of that interface. If your app doesn’t support scenes, use the view-controller-based state restoration process to preserve the state of your interface instead.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For additional information about state restoration, see  ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/preserving-your-app-s-ui-across-launches",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Configure-the-sample-code-project",
          "level": 3,
          "text": "Configure the sample code project",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In Xcode, select your development team on the iOS target’s General tab.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Enable-state-preservation-and-restoration",
          "level": 3,
          "text": "Enable state preservation and restoration",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To provide the necessary activity object, the sample implements the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UISceneDelegate/stateRestorationActivity(for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method of its scene delegate as shown in the example below. Implementing this method tells the system that the sample supports user-activity-based state restoration. The implementation of this method returns the activity object from the scene’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIResponder/userActivity",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property, which the sample populates when the scene becomes inactive.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func stateRestorationActivity(for scene: UIScene) -> NSUserActivity? {",
            "    return scene.userActivity",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "For view-controller-based state restoration, this sample opts in to state preservation and restoration using the app delegate’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:shouldSaveApplicationState:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:shouldRestoreApplicationState:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " methods. Both methods return a ",
              "type": "text"
            },
            {
              "code": "Bool",
              "type": "codeVoice"
            },
            {
              "text": " value that indicates whether the step should occur. This sample returns ",
              "type": "text"
            },
            {
              "code": "true",
              "type": "codeVoice"
            },
            {
              "text": " for both functions.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This example enables the preservation of state for the app:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func application(_ application: UIApplication, shouldSaveSecureApplicationState coder: NSCoder) -> Bool {",
            "    return true",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "This example enables the restoration of state for the app:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func application(_ application: UIApplication, shouldRestoreSecureApplicationState coder: NSCoder) -> Bool {",
            "    return true",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Restore-the-app-state-with-an-activity-object",
          "level": 3,
          "text": "Restore the app state with an activity object",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Scene-based state restoration is the recommended way to restore the app’s user interface. An ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsuseractivity",
              "isActive": true,
              "overridingTitle": "NSUserActivity",
              "overridingTitleInlineContent": [
                {
                  "code": "NSUserActivity",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " object captures the app’s state at the current moment in time. For this sample, the app preserves and restores the product information as the user displays or edits it. The sample app saves the product’s data in an ",
              "type": "text"
            },
            {
              "code": "NSUserActivity",
              "type": "codeVoice"
            },
            {
              "text": " object when the user closes the app or the app enters the background. When the user launches the app again, the sample’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UISceneDelegate/scene(_:willConnectTo:options:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method checks for the presence of an activity object. If one is present, the method configures the detail view controller that the activity object specifies.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Restore-the-app-state-using-view-controllers",
          "level": 3,
          "text": "Restore the app state using view controllers",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This sample preserves its state by saving the state of its view controller hierarchy. View controllers adopt the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIStateRestoring",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol, which defines methods for saving custom state information to an archive and restoring that information later.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The sample specifies which of its view controllers to save, and assigns a restoration identifier to that view controller. A restoration identifier is a string that UIKit uses to identify a view controller or other user interface element. The identifier for each view controller must be unique. The sample assigns the identifiers in Interface Builder, but this can also occur in code.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The sample assigns a restoration ID for each view controller in the storyboard file. This information is available by selecting the view controller and looking at the Identity Inspector. The Storyboard ID for that view controller is usually the same as the Restoration ID.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This sample saves the state information in the detail view controller’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppKit/NSResponder/encodeRestorableState(with:)",
              "isActive": true,
              "overridingTitle": "encodeRestorableState(with:)",
              "overridingTitleInlineContent": [
                {
                  "code": "encodeRestorableState(with:)",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " method, and it restores that state in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppKit/NSResponder/restoreState(with:)",
              "isActive": true,
              "overridingTitle": "restoreState(with:)",
              "overridingTitleInlineContent": [
                {
                  "code": "restoreState(with:)",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " method. Because it already encapsulates the view controller’s state in an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsuseractivity",
              "isActive": true,
              "overridingTitle": "NSUserActivity",
              "overridingTitleInlineContent": [
                {
                  "code": "NSUserActivity",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " object, the implementations of these methods operate on the existing activity object. The sample then calls the required ",
              "type": "text"
            },
            {
              "code": "super",
              "type": "codeVoice"
            },
            {
              "text": " object from these methods, which allows UIKit to restore the rest of the view controller’s inherited state.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This example enables the state preservation of ",
              "type": "text"
            },
            {
              "code": "InfoViewController",
              "type": "codeVoice"
            },
            {
              "text": ":",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "override func encodeRestorableState(with coder: NSCoder) {",
            "    super.encodeRestorableState(with: coder)",
            "",
            "    coder.encode(product?.identifier.uuidString, forKey: InfoViewController.restoreProductKey)",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "This example enables the state restoration of  ",
              "type": "text"
            },
            {
              "code": "InfoViewController",
              "type": "codeVoice"
            },
            {
              "text": ":",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "override func decodeRestorableState(with coder: NSCoder) {",
            "    super.decodeRestorableState(with: coder)",
            "    ",
            "    guard let decodedProductIdentifier =",
            "        coder.decodeObject(forKey: InfoViewController.restoreProductKey) as? String else {",
            "        fatalError(\"A product did not exist in the restore. In your app, handle this gracefully.\")",
            "    }",
            "    product = DataModelManager.sharedInstance.product(fromIdentifier: decodedProductIdentifier)",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Test-state-restoration-on-a-device",
          "level": 3,
          "text": "Test state restoration on a device",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This sample restores the following user interface:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Detail View Controller — Tap a product in the collection view to open its detail information. The app restores the selected product and selected tab.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Detail View Controller’s Edit State — In the detail view, tap Edit. The app restores the edit view and its content.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Secondary Window — (iPad only) Drag a product from the collection view over to the left or right of the device screen to create a second scene window. The app restores that scene and its product. Another way to create the secondary window is to tap and hold a product from the collection view through its contextual menu and select Open New Window.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "When debugging the sample project, the system automatically deletes its preserved state when the user force quits the app. Deleting the preserved state information is a safety precaution. In addition, the system also deletes the preserved state if this app crashes at launch time. To test the sample app’s ability to restore the sample’s state, do not use the app switcher to force quit it during debugging. Instead, use Xcode to stop the app, or stop the app programmatically. One technique is to suspend the sample app using the Home button, and then stop the debugger in Xcode. Launch the sample app again using Xcode, and UIKit initiates the state restoration process.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "a9326fb01c82/RestoringYourAppsState.zip": {
      "checksum": "a9326fb01c82232cdc351f22a1ec91695edc1c568e14637a0bce9b013ac0d29889f56ecf539d17cdf36e9cf41ddd4314eaed61b6162398c826681ca8ea043347",
      "identifier": "a9326fb01c82/RestoringYourAppsState.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/a9326fb01c82/RestoringYourAppsState.zip"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSResponder/encodeRestorableState(with:)": {
      "abstract": [
        {
          "text": "Saves the interface-related state of the responder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "encodeRestorableState"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "coder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCoder",
          "text": "NSCoder"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSResponder/encodeRestorableState(with:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "encodeRestorableState(with:)",
      "type": "topic",
      "url": "/documentation/AppKit/NSResponder/encodeRestorableState(with:)"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSResponder/restoreState(with:)": {
      "abstract": [
        {
          "text": "Restores the interface-related state of the responder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restoreState"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "internalParam",
          "text": "coder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCoder",
          "text": "NSCoder"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSResponder/restoreState(with:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "restoreState(with:)",
      "type": "topic",
      "url": "/documentation/AppKit/NSResponder/restoreState(with:)"
    },
    "doc://com.apple.documentation/documentation/foundation/nsuseractivity": {
      "abstract": [
        {
          "text": "A representation of the state of your app at a moment in time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSUserActivity"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsuseractivity",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUserActivity",
      "type": "topic",
      "url": "/documentation/foundation/nsuseractivity"
    },
    "doc://com.apple.documentation/documentation/swiftui/restoring_your_app_s_state_with_swiftui": {
      "abstract": [
        {
          "text": "Provide app continuity for users by preserving their current activities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swiftui/restoring_your_app_s_state_with_swiftui",
      "kind": "article",
      "role": "sampleCode",
      "title": "Restoring Your App’s State with SwiftUI",
      "type": "topic",
      "url": "/documentation/swiftui/restoring_your_app_s_state_with_swiftui"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:shouldRestoreApplicationState:)": {
      "abstract": [
        {
          "text": "Asks the delegate whether to restore the app’s saved state.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "application"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIApplication",
          "text": "UIApplication"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shouldRestoreApplicationState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCoder",
          "text": "NSCoder"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:shouldRestoreApplicationState:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "application:shouldRestoreApplicationState:"
        }
      ],
      "role": "symbol",
      "title": "application(_:shouldRestoreApplicationState:)",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationdelegate/application(_:shouldrestoreapplicationstate:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:shouldSaveApplicationState:)": {
      "abstract": [
        {
          "text": "Asks the delegate whether to preserve the app’s state.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "application"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIApplication",
          "text": "UIApplication"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shouldSaveApplicationState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCoder",
          "text": "NSCoder"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:shouldSaveApplicationState:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "application:shouldSaveApplicationState:"
        }
      ],
      "role": "symbol",
      "title": "application(_:shouldSaveApplicationState:)",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationdelegate/application(_:shouldsaveapplicationstate:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIObjectRestoration": {
      "abstract": [
        {
          "text": "The interface that restoration classes use to restore preserved objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIObjectRestoration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIObjectRestoration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIObjectRestoration"
        }
      ],
      "role": "symbol",
      "title": "UIObjectRestoration",
      "type": "topic",
      "url": "/documentation/uikit/uiobjectrestoration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIResponder/userActivity": {
      "abstract": [
        {
          "text": "An object encapsulating a user activity supported by this responder.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userActivity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUserActivity",
          "text": "NSUserActivity"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIResponder/userActivity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userActivity"
        }
      ],
      "role": "symbol",
      "title": "userActivity",
      "type": "topic",
      "url": "/documentation/uikit/uiresponder/useractivity"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScene": {
      "abstract": [
        {
          "text": "An object that represents one instance of your app’s user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIScene"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScene",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIScene"
        }
      ],
      "role": "symbol",
      "title": "UIScene",
      "type": "topic",
      "url": "/documentation/uikit/uiscene"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISceneDelegate": {
      "abstract": [
        {
          "text": "The core methods you use to respond to life-cycle events occurring within a scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISceneDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISceneDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISceneDelegate"
        }
      ],
      "role": "symbol",
      "title": "UISceneDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uiscenedelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISceneDelegate/scene(_:willConnectTo:options:)": {
      "abstract": [
        {
          "text": "Tells the delegate about the addition of a scene to the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scene"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIScene",
          "text": "UIScene"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willConnectTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISceneSession",
          "text": "UISceneSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIScene",
          "text": "UIScene"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISceneConnectionOptions",
          "text": "ConnectionOptions"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISceneDelegate/scene(_:willConnectTo:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scene:willConnectToSession:options:"
        }
      ],
      "role": "symbol",
      "title": "scene(_:willConnectTo:options:)",
      "type": "topic",
      "url": "/documentation/uikit/uiscenedelegate/scene(_:willconnectto:options:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISceneDelegate/stateRestorationActivity(for:)": {
      "abstract": [
        {
          "text": "Returns a user activity object encapsulating the current state of the specified scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stateRestorationActivity"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIScene",
          "text": "UIScene"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUserActivity",
          "text": "NSUserActivity"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISceneDelegate/stateRestorationActivity(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stateRestorationActivityForScene:"
        }
      ],
      "role": "symbol",
      "title": "stateRestorationActivity(for:)",
      "type": "topic",
      "url": "/documentation/uikit/uiscenedelegate/staterestorationactivity(for:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIStateRestoring": {
      "abstract": [
        {
          "text": "Methods for adding objects to your state restoration archives.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIStateRestoring"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIStateRestoring",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIStateRestoring"
        }
      ],
      "role": "symbol",
      "title": "UIStateRestoring",
      "type": "topic",
      "url": "/documentation/uikit/uistaterestoring"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController": {
      "abstract": [
        {
          "text": "An object that manages a view hierarchy for your UIKit app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewController"
        }
      ],
      "role": "symbol",
      "title": "UIViewController",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewControllerRestoration": {
      "abstract": [
        {
          "text": "The methods that objects adopt so that they can act as a restoration class for view controllers during state restoration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewControllerRestoration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerRestoration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewControllerRestoration"
        }
      ],
      "role": "symbol",
      "title": "UIViewControllerRestoration",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontrollerrestoration"
    },
    "doc://com.apple.uikit/documentation/UIKit/app-and-environment": {
      "abstract": [
        {
          "text": "Manage life-cycle events and your app’s UI scenes, and get information about traits and the environment in which your app runs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/app-and-environment",
      "kind": "article",
      "role": "collectionGroup",
      "title": "App and environment",
      "type": "topic",
      "url": "/documentation/uikit/app-and-environment"
    },
    "doc://com.apple.uikit/documentation/UIKit/multitasking-on-ipad": {
      "abstract": [
        {
          "text": "Implement multitasking APIs to seamlessly integrate your app with iPadOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/multitasking-on-ipad",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Multitasking on iPad",
      "type": "topic",
      "url": "/documentation/uikit/multitasking-on-ipad"
    },
    "doc://com.apple.uikit/documentation/UIKit/preserving-your-app-s-ui-across-launches": {
      "abstract": [
        {
          "text": "Return your app to its previous state after the system terminates it.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/preserving-your-app-s-ui-across-launches",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Preserving your app’s UI across launches",
      "type": "topic",
      "url": "/documentation/uikit/preserving-your-app-s-ui-across-launches"
    },
    "doc://com.apple.uikit/documentation/UIKit/scenes": {
      "abstract": [
        {
          "text": "Manage multiple instances of your app’s UI simultaneously, and direct resources to the appropriate instance of your UI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/scenes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Scenes",
      "type": "topic",
      "url": "/documentation/uikit/scenes"
    },
    "doc://com.apple.uikit/documentation/UIKit/view-controllers": {
      "abstract": [
        {
          "text": "Manage your interface using view controllers and facilitate navigation around your app’s content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/view-controllers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "View controllers",
      "type": "topic",
      "url": "/documentation/uikit/view-controllers"
    },
    "doc://com.apple.uikit/documentation/UIKit/windows-and-screens": {
      "abstract": [
        {
          "text": "Provide a container for your view hierarchies and other content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/windows-and-screens",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Windows and screens",
      "type": "topic",
      "url": "/documentation/uikit/windows-and-screens"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "a9326fb01c82/RestoringYourAppsState.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Interface-restoration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/swiftui/restoring_your_app_s_state_with_swiftui",
        "doc://com.apple.uikit/documentation/UIKit/preserving-your-app-s-ui-across-launches",
        "doc://com.apple.uikit/documentation/UIKit/UIViewControllerRestoration",
        "doc://com.apple.uikit/documentation/UIKit/UIObjectRestoration",
        "doc://com.apple.uikit/documentation/UIKit/UIStateRestoring"
      ],
      "title": "Interface restoration"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Interface-restoration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.documentation/documentation/swiftui/restoring_your_app_s_state_with_swiftui",
                "doc://com.apple.uikit/documentation/UIKit/preserving-your-app-s-ui-across-launches",
                "doc://com.apple.uikit/documentation/UIKit/UIViewControllerRestoration",
                "doc://com.apple.uikit/documentation/UIKit/UIObjectRestoration",
                "doc://com.apple.uikit/documentation/UIKit/UIStateRestoring"
              ],
              "title": "Interface restoration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScene/title",
          "value": "UIScene"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScene/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScene/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSResponder~1encodeRestorableState(with:)/title",
          "value": "encodeRestorableStateWithCoder:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSResponder~1encodeRestorableState(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "encodeRestorableStateWithCoder:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSCoder",
              "text": "NSCoder"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "coder"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:shouldSaveApplicationState:)/title",
          "value": "application:shouldSaveApplicationState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:shouldSaveApplicationState:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "application:shouldSaveApplicationState:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerRestoration/title",
          "value": "UIViewControllerRestoration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerRestoration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerRestoration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerRestoration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerRestoration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStateRestoring/title",
          "value": "UIStateRestoring"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStateRestoring/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIStateRestoring"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStateRestoring/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIStateRestoring"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneDelegate~1stateRestorationActivity(for:)/title",
          "value": "stateRestorationActivityForScene:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneDelegate~1stateRestorationActivity(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stateRestorationActivityForScene:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIObjectRestoration/title",
          "value": "UIObjectRestoration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIObjectRestoration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIObjectRestoration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIObjectRestoration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIObjectRestoration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController/title",
          "value": "UIViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSResponder~1restoreState(with:)/title",
          "value": "restoreStateWithCoder:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSResponder~1restoreState(with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- ("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:v",
              "text": "void"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "identifier",
              "text": "restoreStateWithCoder:"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSCoder",
              "text": "NSCoder"
            },
            {
              "kind": "text",
              "text": " *) "
            },
            {
              "kind": "internalParam",
              "text": "coder"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponder~1userActivity/title",
          "value": "userActivity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponder~1userActivity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "userActivity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneDelegate~1scene(_:willConnectTo:options:)/title",
          "value": "scene:willConnectToSession:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneDelegate~1scene(_:willConnectTo:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scene:willConnectToSession:options:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneDelegate/title",
          "value": "UISceneDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISceneDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISceneDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:shouldRestoreApplicationState:)/title",
          "value": "application:shouldRestoreApplicationState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:shouldRestoreApplicationState:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "application:shouldRestoreApplicationState:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/restoring-your-app-s-state"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/restoring-your-app-s-state"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
