{
  "abstract": [
    {
      "text": "Add a document browser view controller to your app.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/view-controllers",
        "doc://com.apple.uikit/documentation/UIKit/adding-a-document-browser-to-your-app"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/view-controllers",
        "doc://com.apple.uikit/documentation/UIKit/UIDocumentBrowserViewController",
        "doc://com.apple.uikit/documentation/UIKit/adding-a-document-browser-to-your-app"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/setting-up-a-document-browser-app"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "article",
    "roleHeading": "Article",
    "title": "Setting up a document browser app"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Setting up the document browser is a three-step process:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Set the browser as your app’s root view controller.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Declare document browser support for your app.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Define the type of documents that the document browser can open.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The simplest way to do all three is to create a new project using the Document Based App template.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Create-a-new-document-based-app",
          "level": 3,
          "text": "Create a new document-based app",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To create a new document-based app, open Xcode and choose File > New > Project. In the template chooser, under Application, choose the Document Based App template, and click Next.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2920797",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Continue following the prompts to create a document-based project. The following items appear in your new project:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "code": "Main.storyboard",
                      "type": "codeVoice"
                    },
                    {
                      "text": " contains a document browser view controller as its initial view controller. This storyboard sets the document browser as your app’s root view controller, ensuring that the browser remains in memory throughout your app’s lifetime.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In your app’s ",
                      "type": "text"
                    },
                    {
                      "code": "Info.plist",
                      "type": "codeVoice"
                    },
                    {
                      "text": " file, the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UISupportsDocumentBrowser",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " key is set to ",
                      "type": "text"
                    },
                    {
                      "code": "YES",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", declaring document browser support for your app. Specifically, this key lets other apps open and edit the files stored in your app’s Documents directory. It also lets users set the app’s default save location in Settings. For more information, see ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/iPhoneOSKeys.html#//apple_ref/doc/uid/TP40009252-SW37",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "The app declares that it supports ",
                      "type": "text"
                    },
                    {
                      "code": "public.image",
                      "type": "codeVoice"
                    },
                    {
                      "text": " document types. Users can then select image files in the document browser and share image files from other apps.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Use most of these default values as-is; however, unless you’re making an image-based app, you probably need to update the supported document types.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Set-the-supported-document-types",
          "level": 3,
          "text": "Set the supported document types",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For each document type your app supports, follow these steps in the project editor’s Info pane:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Click the Document Types disclosure triangle, and click the Add button (+) to add a new document type or open an existing document type.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Set the document type’s name and its uniform type identifier (UTI).",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Click the “Additional document type properties” disclosure triangle.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Add the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes/LSHandlerRank",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " key, and set its value to ",
                      "type": "text"
                    },
                    {
                      "code": "Owner",
                      "type": "codeVoice"
                    },
                    {
                      "text": " or ",
                      "type": "text"
                    },
                    {
                      "code": "Alternate",
                      "type": "codeVoice"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Optionally, set the other document type properties.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "For example, for an app that edits text files, use the settings shown in the following image:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2948338",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "These entries set the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key in your app’s ",
              "type": "text"
            },
            {
              "code": "Info.plist",
              "type": "codeVoice"
            },
            {
              "text": " file as shown here:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "<key>CFBundleDocumentTypes</key>",
            "<array>",
            "    <dict>",
            "        <key>CFBundleTypeIconFiles</key>",
            "        <array/>",
            "        <key>CFBundleTypeName</key>",
            "        <string>Text</string>",
            "        <key>LSHandlerRank</key>",
            "        <string>Alternate</string>",
            "        <key>LSItemContentTypes</key>",
            "        <array>",
            "            <string>public.plain-text</string>",
            "        </array>",
            "    </dict>",
            "</array>"
          ],
          "syntax": "xml",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "For more information, see ",
              "type": "text"
            },
            {
              "identifier": "http://help.apple.com/xcode/mac/current/#/devddd273fdd",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes": {
      "abstract": [
        {
          "text": "The document types supported by the bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFBundleDocumentTypes",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes/LSHandlerRank": {
      "abstract": [
        {
          "text": "The ranking of this app among apps that declare themselves as editors or viewers of the given file type.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes/LSHandlerRank",
      "kind": "symbol",
      "role": "symbol",
      "title": "LSHandlerRank",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes/LSHandlerRank"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UISupportsDocumentBrowser": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the app is a document-based app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UISupportsDocumentBrowser",
      "kind": "symbol",
      "role": "symbol",
      "title": "UISupportsDocumentBrowser",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/UISupportsDocumentBrowser"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentBrowserViewController": {
      "abstract": [
        {
          "text": "A view controller for browsing and performing actions on documents that you store locally and in the cloud.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDocumentBrowserViewController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentBrowserViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDocumentBrowserViewController"
        }
      ],
      "role": "symbol",
      "title": "UIDocumentBrowserViewController",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentbrowserviewcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/adding-a-document-browser-to-your-app": {
      "abstract": [
        {
          "text": "Give users access to their local or remote documents from within your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/adding-a-document-browser-to-your-app",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Adding a document browser to your app",
      "type": "topic",
      "url": "/documentation/uikit/adding-a-document-browser-to-your-app"
    },
    "doc://com.apple.uikit/documentation/UIKit/enabling-document-sharing": {
      "abstract": [
        {
          "text": "Give users the ability to import and export documents from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/enabling-document-sharing",
      "kind": "article",
      "role": "article",
      "title": "Enabling document sharing",
      "type": "topic",
      "url": "/documentation/uikit/enabling-document-sharing"
    },
    "doc://com.apple.uikit/documentation/UIKit/presenting-selected-documents": {
      "abstract": [
        {
          "text": "Display user-selected documents over your browser view controller.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/presenting-selected-documents",
      "kind": "article",
      "role": "article",
      "title": "Presenting selected documents",
      "type": "topic",
      "url": "/documentation/uikit/presenting-selected-documents"
    },
    "doc://com.apple.uikit/documentation/UIKit/view-controllers": {
      "abstract": [
        {
          "text": "Manage your interface using view controllers and facilitate navigation around your app’s content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/view-controllers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "View controllers",
      "type": "topic",
      "url": "/documentation/uikit/view-controllers"
    },
    "http://help.apple.com/xcode/mac/current/#/devddd273fdd": {
      "identifier": "http://help.apple.com/xcode/mac/current/#/devddd273fdd",
      "title": "Set supported document types",
      "titleInlineContent": [
        {
          "text": "Set supported document types",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "http://help.apple.com/xcode/mac/current/#/devddd273fdd"
    },
    "https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/iPhoneOSKeys.html#//apple_ref/doc/uid/TP40009252-SW37": {
      "identifier": "https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/iPhoneOSKeys.html#//apple_ref/doc/uid/TP40009252-SW37",
      "title": "UISupportsDocumentBrowser",
      "titleInlineContent": [
        {
          "text": "UISupportsDocumentBrowser",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/iPhoneOSKeys.html#//apple_ref/doc/uid/TP40009252-SW37"
    },
    "media-2920797": {
      "alt": "Xcode’s  project template pane. Both the iOS tab and the Document Based App icon are selected. ",
      "identifier": "media-2920797",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5449c9fe83d4679fb5a76fcab4ee88bd/media-2920797@2x.png"
        }
      ]
    },
    "media-2948338": {
      "alt": "A screenshot showing the document type settings for text files. The file type is set to public-plain.text, and the handler rank is set to Alternate.",
      "identifier": "media-2948338",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/c9bce09b41b8d9073d51f5a13fb28402/media-2948338@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/presenting-selected-documents",
        "doc://com.apple.uikit/documentation/UIKit/enabling-document-sharing"
      ],
      "title": "Configuration"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/presenting-selected-documents",
                "doc://com.apple.uikit/documentation/UIKit/enabling-document-sharing"
              ],
              "title": "Configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentBrowserViewController/title",
          "value": "UIDocumentBrowserViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentBrowserViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocumentBrowserViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentBrowserViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocumentBrowserViewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/setting-up-a-document-browser-app"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/setting-up-a-document-browser-app"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
