{
  "abstract": [
    {
      "text": "Explain the purpose of interface elements by showing a tooltip when a person positions the pointer over the element.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/mac-catalyst"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/showing-help-tags-for-views-and-controls-using-tooltip-interactions"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Showing help tags for views and controls using tooltip interactions"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This sample shows how to display a tooltip (also known as a ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "help tag",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ") that explains the purpose of, or provide additional information about, an interface element such as a view or control without shifting a person’s focus away from the primary interface. A tooltip appears when a person positions the pointer over a view or control for a few seconds. The tooltip remains visible for a few seconds or until the pointer moves away from the interface element.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For guidelines on designing the content of your tooltips, see the ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/design/human-interface-guidelines/macos/user-interaction/help/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " section of the macOS Human Interface Guidelines.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Configure-the-sample-code-project",
          "level": 3,
          "text": "Configure the sample code project",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Tooltips are available in the sample app when running in macOS 12 or later. To build and run the sample app:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Choose Product > Destination > My Mac.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Click Product > Run.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "anchor": "Add-a-tooltip-to-a-view",
          "level": 3,
          "text": "Add a tooltip to a view",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To show a tooltip when the pointer hovers over a view, the sample creates a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIToolTipInteraction",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object and passes in the default tooltip text. Then the sample adds the interaction to a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " using the view’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/addInteraction(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "lazy var viewWithDefaultTooltip: UIView = {",
            "    let view = UIView()",
            "    view.backgroundColor = UIColor.systemGreen",
            "    view.addText(\"Hover the pointer over this view to see its default tooltip.\")",
            "",
            "    let tooltipInteraction = UIToolTipInteraction(defaultToolTip: \"The default tooltip for the view.\")",
            "    view.addInteraction(tooltipInteraction)",
            "",
            "    return view",
            "}()"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The sample uses the same approach for other types of views too, for instance, to add a tooltip to an instance of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UILabel",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ":",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "lazy var labelWithTooltip: UILabel = {",
            "    let label = UILabel()",
            "    label.text = \"Hover the pointer over this label to see its tooltip.\"",
            "    label.numberOfLines = 0",
            "    ",
            "    let tooltipInteraction = UIToolTipInteraction(defaultToolTip: \"The label's tooltip.\")",
            "    label.addInteraction(tooltipInteraction)",
            "    ",
            "    return label",
            "}()"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Add-a-tooltip-to-a-control",
          "level": 3,
          "text": "Add a tooltip to a control",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For interface elements that derive from ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", such as ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", the sample uses the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl/toolTip",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to set the default text that appears in the tooltip instead of adding an interaction to the control.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "lazy var buttonWithTooltip: UIButton = {",
            "    var configuration = UIButton.Configuration.filled()",
            "    configuration.title = \"Buy\"",
            "    configuration.subtitle = \"Only $9.99\"",
            "    configuration.titleAlignment = .center",
            "    ",
            "    let action = UIAction { _ in print(\"Thank you for your purchase.\") }",
            "",
            "    let button = UIButton(configuration: configuration, primaryAction: action)",
            "    button.toolTip = \"Click to buy this item. You'll have a chance to change your mind before confirming your purchase.\"",
            "    button.preferredBehavioralStyle = .pad",
            "    ",
            "    return button",
            "}()"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Change-the-tooltip-text-of-a-view",
          "level": 3,
          "text": "Change the tooltip text of a view",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Setting the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIToolTipInteraction/defaultToolTip",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of a tooltip interaction and setting the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl/toolTip",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of a control are convenient ways to show tooltip text that don’t change while the app runs. However, there may be times when an app needs to determine the contents of the tooltip based on the state of the app or logic specific to the app. For instance, the sample app looks up the name of a view’s background color and displays the name in a tooltip when the pointer hovers over that view.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To show the background color name in a tooltip, the sample creates an instance of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIToolTipInteraction",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and sets its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIToolTipInteraction/delegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to an instance of ",
              "type": "text"
            },
            {
              "code": "ViewWithBackgroundColorTooltip",
              "type": "codeVoice"
            },
            {
              "text": ", which is a custom view that conforms to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIToolTipInteractionDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol. Then the sample adds the interaction to the view.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "lazy var viewWithBackgroundColorTooltip: UIView = {",
            "    let view = ViewWithBackgroundColorTooltip()",
            "    view.backgroundColor = UIColor.systemYellow",
            "    view.addText(\"Hover the pointer over this view to see the name of the view's background color.\")",
            "",
            "    let tooltipInteraction = UIToolTipInteraction()",
            "    tooltipInteraction.delegate = view",
            "    view.addInteraction(tooltipInteraction)",
            "    ",
            "    return view",
            "}()"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Next, ",
              "type": "text"
            },
            {
              "code": "ViewWithBackgroundColorTooltip",
              "type": "codeVoice"
            },
            {
              "text": " implements the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIToolTipInteractionDelegate/toolTipInteraction(_:configurationAt:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method, and returns a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIToolTipConfiguration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object that contains the name of the background color as the text of the tooltip. If the color name isn’t available, the method returns ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ", which prevents the tooltip from displaying.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "class ViewWithBackgroundColorTooltip: UIView, UIToolTipInteractionDelegate {",
            "    ",
            "    func toolTipInteraction(_ interaction: UIToolTipInteraction, configurationAt point: CGPoint) -> UIToolTipConfiguration? {",
            "",
            "        let configuration: UIToolTipConfiguration?",
            "        if let accessibilityName = backgroundColor?.accessibilityName {",
            "            configuration = UIToolTipConfiguration(toolTip: \"The color is \\(accessibilityName).\")",
            "        } else {",
            "            configuration = nil",
            "        }",
            "        ",
            "        return configuration",
            "    }",
            "",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Change-the-tooltip-text-of-a-control",
          "level": 3,
          "text": "Change the tooltip text of a control",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To change the tooltip text of a control like the sample’s shopping cart button, the sample provides a tooltip interaction delegate as it did with the custom view. But instead of creating a tooltip interaction, it sets the button’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl/toolTip",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to the default text. This causes the control to create a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIToolTipInteraction",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object and assign it to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl/toolTipInteraction",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property. The sample then uses the property to assign a delegate to the interaction.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "lazy var shoppingCartButtonWithTooltip: UIButton = {",
            "    var configuration = UIButton.Configuration.filled()",
            "    configuration.title = \"Add to Cart\"",
            "    configuration.image = UIImage(systemName: \"cart.circle\")",
            "    configuration.imagePlacement = NSDirectionalRectEdge.leading",
            "    configuration.imagePadding = 4",
            "    ",
            "    let action = UIAction { [unowned self] _ in self.cartItemCount += 1 }",
            "    ",
            "    let button = UIButton(configuration: configuration, primaryAction: action)",
            "    button.toolTip = \"Click to add the item to your cart. Your cart is empty.\"",
            "    button.toolTipInteraction?.delegate = self",
            "    ",
            "    return button",
            "}()"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The sample also implements the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIToolTipInteractionDelegate/toolTipInteraction(_:configurationAt:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " delegate method, which returns a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIToolTipConfiguration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object that contains the tooltip text describing the purpose of the button and the number of items in the shopping cart.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func toolTipInteraction(_ interaction: UIToolTipInteraction, configurationAt point: CGPoint) -> UIToolTipConfiguration? {",
            "    ",
            "    let text: String",
            "    switch cartItemCount {",
            "    case 0:",
            "        text = \"Click to add the item to your cart. Your cart is empty.\"",
            "    case 1:",
            "        text = \"Click to add the item to your cart. Your cart contains \\(cartItemCount) item.\"",
            "    default:",
            "        text = \"Click to add the item to your cart. Your cart contains \\(cartItemCount) items.\"",
            "    }",
            "    ",
            "    return UIToolTipConfiguration(toolTip: text)",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Specify-the-hover-region",
          "level": 3,
          "text": "Specify the hover region",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In addition to setting the tooltip text in a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIToolTipConfiguration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object, a delegate can specify the region of an interface element where the pointer must hover to trigger the display of the tooltip. The sample app, for example, shows a view that displays a tooltip after positioning the pointer over the top or bottom regions of the view, but not when the pointer is over the middle area.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To determine whether the pointer location is in the top or bottom region of the view, the sample uses the ",
              "type": "text"
            },
            {
              "code": "point",
              "type": "codeVoice"
            },
            {
              "text": " value that the method ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIToolTipInteractionDelegate/toolTipInteraction(_:configurationAt:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " provides. When the pointer is in one of those regions, the delegate method returns a tooltip configuration that contains the tooltip text and the source rectangle, which defines the area of the view that the pointer must hover over to trigger the display of the tooltip.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "class ViewWithTooltipRegion: UIView, UIToolTipInteractionDelegate {",
            "",
            "    func toolTipInteraction(_ interaction: UIToolTipInteraction, configurationAt point: CGPoint) -> UIToolTipConfiguration? {",
            "        ",
            "        var topRect = self.bounds",
            "        var bottomRect = self.bounds",
            "        ",
            "        let partHeight = self.bounds.size.height / 3",
            "        topRect.size.height = partHeight",
            "        bottomRect.size.height = partHeight",
            "        bottomRect.origin.y = partHeight * 2",
            "        ",
            "        // Display the tooltip if the pointer within the top or bottom rects.",
            "        if topRect.contains(point) {",
            "            return UIToolTipConfiguration(toolTip: \"Top area of the view.\", in: topRect)",
            "        } else if bottomRect.contains(point) {",
            "            return UIToolTipConfiguration(toolTip: \"Bottom area of the view.\", in: bottomRect)",
            "        }",
            "        ",
            "        // Pointer is in the middle of the view; don't display a tooltip.",
            "        return nil",
            "    }",
            "    ",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "In another example, the sample uses the source rectangle of a tooltip configuration to specify the region of selected text in a text view. When hovering the pointer over the selected text, a tooltip appears but it doesn’t appear when the pointer hovers over unselected text.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "class TextViewWithTooltip: UITextView, UIToolTipInteractionDelegate {",
            "    ",
            "    func toolTipInteraction(_ interaction: UIToolTipInteraction, configurationAt point: CGPoint) -> UIToolTipConfiguration? {",
            "        ",
            "        guard",
            "            let selectedTextRange = self.selectedTextRange,",
            "            selectedTextRange.isEmpty == false",
            "        else {",
            "            return nil",
            "        }",
            "",
            "        var unionedRect = firstRect(for: selectedTextRange)",
            "        for selectionRect in selectionRects(for: selectedTextRange) {",
            "            unionedRect = unionedRect.union(selectionRect.rect)",
            "        }",
            "        ",
            "        if let selectedText = text(in: selectedTextRange) {",
            "            return UIToolTipConfiguration(toolTip: \"Selected text: \\(selectedText)\", in: unionedRect)",
            "        }",
            "        ",
            "        return nil",
            "    }",
            "    ",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "199a44d512cb/ShowingHelpTagsForViewsAndControlsUsingTooltipInteractions.zip": {
      "checksum": "199a44d512cb9b66e44d45d76c2679e6d99a5cd831e9fb7735e9d846251fb34b23081c894ccde5e84f590cb9fd50ba681bc69520856f9a92abd5f3620c9ff958",
      "identifier": "199a44d512cb/ShowingHelpTagsForViewsAndControlsUsingTooltipInteractions.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/199a44d512cb/ShowingHelpTagsForViewsAndControlsUsingTooltipInteractions.zip"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton": {
      "abstract": [
        {
          "text": "A control that executes your custom code in response to user interactions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIButton"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIButton"
        }
      ],
      "role": "symbol",
      "title": "UIButton",
      "type": "topic",
      "url": "/documentation/uikit/uibutton"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIControl": {
      "abstract": [
        {
          "text": "The base class for controls, which are visual elements that convey a specific action or intention in response to user interactions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIControl"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIControl"
        }
      ],
      "role": "symbol",
      "title": "UIControl",
      "type": "topic",
      "url": "/documentation/uikit/uicontrol"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIControl/toolTip": {
      "abstract": [
        {
          "text": "The default text to display in the control’s tooltip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toolTip"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl/toolTip",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "toolTip"
        }
      ],
      "role": "symbol",
      "title": "toolTip",
      "type": "topic",
      "url": "/documentation/uikit/uicontrol/tooltip"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIControl/toolTipInteraction": {
      "abstract": [
        {
          "text": "The tooltip interaction associated with the control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toolTipInteraction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIToolTipInteraction",
          "text": "UIToolTipInteraction"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIControl/toolTipInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "toolTipInteraction"
        }
      ],
      "role": "symbol",
      "title": "toolTipInteraction",
      "type": "topic",
      "url": "/documentation/uikit/uicontrol/tooltipinteraction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UILabel": {
      "abstract": [
        {
          "text": "A view that displays one or more lines of informational text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UILabel"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UILabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILabel"
        }
      ],
      "role": "symbol",
      "title": "UILabel",
      "type": "topic",
      "url": "/documentation/uikit/uilabel"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIToolTipConfiguration": {
      "abstract": [
        {
          "text": "An object that a tooltip interaction delegate uses to describe the tooltip settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIToolTipConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIToolTipConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIToolTipConfiguration"
        }
      ],
      "role": "symbol",
      "title": "UIToolTipConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uitooltipconfiguration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIToolTipInteraction": {
      "abstract": [
        {
          "text": "An interaction object that makes it possible to show a tooltip when hovering a pointer over a view or control.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIToolTipInteraction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIToolTipInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIToolTipInteraction"
        }
      ],
      "role": "symbol",
      "title": "UIToolTipInteraction",
      "type": "topic",
      "url": "/documentation/uikit/uitooltipinteraction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIToolTipInteraction/defaultToolTip": {
      "abstract": [
        {
          "text": "The text that appears in a tooltip by default.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultToolTip"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIToolTipInteraction/defaultToolTip",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultToolTip"
        }
      ],
      "role": "symbol",
      "title": "defaultToolTip",
      "type": "topic",
      "url": "/documentation/uikit/uitooltipinteraction/defaulttooltip"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIToolTipInteraction/delegate": {
      "abstract": [
        {
          "text": "An object that provides text that a tooltip displays instead of the default text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIToolTipInteractionDelegate",
          "text": "UIToolTipInteractionDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIToolTipInteraction/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/uikit/uitooltipinteraction/delegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIToolTipInteractionDelegate": {
      "abstract": [
        {
          "text": "An interface that provides tooltip settings to an interaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIToolTipInteractionDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIToolTipInteractionDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIToolTipInteractionDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIToolTipInteractionDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uitooltipinteractiondelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIToolTipInteractionDelegate/toolTipInteraction(_:configurationAt:)": {
      "abstract": [
        {
          "text": "Asks the delegate for a tooltip configuration that describes the tooltip settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toolTipInteraction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIToolTipInteraction",
          "text": "UIToolTipInteraction"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "configurationAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIToolTipConfiguration",
          "text": "UIToolTipConfiguration"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIToolTipInteractionDelegate/toolTipInteraction(_:configurationAt:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "toolTipInteraction:configurationAtPoint:"
        }
      ],
      "role": "symbol",
      "title": "toolTipInteraction(_:configurationAt:)",
      "type": "topic",
      "url": "/documentation/uikit/uitooltipinteractiondelegate/tooltipinteraction(_:configurationat:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView": {
      "abstract": [
        {
          "text": "An object that manages the content for a rectangular area on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIView"
        }
      ],
      "role": "symbol",
      "title": "UIView",
      "type": "topic",
      "url": "/documentation/uikit/uiview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/addInteraction(_:)": {
      "abstract": [
        {
          "text": "Adds an interaction to the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addInteraction"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIInteraction",
          "text": "UIInteraction"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/addInteraction(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addInteraction:"
        }
      ],
      "role": "symbol",
      "title": "addInteraction(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiview/addinteraction(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/mac-catalyst": {
      "abstract": [
        {
          "text": "Create a version of your iPad app that users can run on a Mac device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/mac-catalyst",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Mac Catalyst",
      "type": "topic",
      "url": "/documentation/uikit/mac-catalyst"
    },
    "https://developer.apple.com/design/human-interface-guidelines/macos/user-interaction/help/": {
      "identifier": "https://developer.apple.com/design/human-interface-guidelines/macos/user-interaction/help/",
      "title": "Help",
      "titleInlineContent": [
        {
          "text": "Help",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/design/human-interface-guidelines/macos/user-interaction/help/"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "199a44d512cb/ShowingHelpTagsForViewsAndControlsUsingTooltipInteractions.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Tooltips",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIToolTipInteraction",
        "doc://com.apple.uikit/documentation/UIKit/UIToolTipInteractionDelegate"
      ],
      "title": "Tooltips"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Tooltips",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIToolTipInteraction",
                "doc://com.apple.uikit/documentation/UIKit/UIToolTipInteractionDelegate"
              ],
              "title": "Tooltips"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIToolTipConfiguration/title",
          "value": "UIToolTipConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIToolTipConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIToolTipConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIToolTipConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIToolTipConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIToolTipInteraction/title",
          "value": "UIToolTipInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIToolTipInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIToolTipInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIToolTipInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIToolTipInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIToolTipInteractionDelegate/title",
          "value": "UIToolTipInteractionDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIToolTipInteractionDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIToolTipInteractionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIToolTipInteractionDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIToolTipInteractionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1toolTip/title",
          "value": "toolTip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1toolTip/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "toolTip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl/title",
          "value": "UIControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIToolTipInteractionDelegate~1toolTipInteraction(_:configurationAt:)/title",
          "value": "toolTipInteraction:configurationAtPoint:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIToolTipInteractionDelegate~1toolTipInteraction(_:configurationAt:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "toolTipInteraction:configurationAtPoint:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1toolTipInteraction/title",
          "value": "toolTipInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIControl~1toolTipInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "toolTipInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/title",
          "value": "UIView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILabel/title",
          "value": "UILabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UILabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILabel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIToolTipInteraction~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIToolTipInteraction~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/title",
          "value": "UIButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIToolTipInteraction~1defaultToolTip/title",
          "value": "defaultToolTip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIToolTipInteraction~1defaultToolTip/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defaultToolTip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1addInteraction(_:)/title",
          "value": "addInteraction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1addInteraction(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addInteraction:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/showing-help-tags-for-views-and-controls-using-tooltip-interactions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/showing-help-tags-for-views-and-controls-using-tooltip-interactions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
