{
  "abstract": [
    {
      "text": "Apply attributes to text in an attributed string to modify the pronunciation of that text.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/accessibility-for-uikit",
        "doc://com.apple.uikit/documentation/UIKit/uiaccessibility-protocol"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/speech-attributes-for-attributed-strings"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Speech attributes for attributed strings"
  },
  "references": {
    "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/1620188-accessibilityspeechlanguage": {
      "abstract": [
        {
          "text": "A key that indicates the language to use when speaking a string. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "accessibilitySpeechLanguage"
        },
        {
          "kind": "text",
          "text": ": NSAttributedString.Key"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/1620188-accessibilityspeechlanguage",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilitySpeechLanguage",
      "type": "topic",
      "url": "/documentation/foundation/nsattributedstring/key/1620188-accessibilityspeechlanguage"
    },
    "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/1620195-accessibilityspeechpitch": {
      "abstract": [
        {
          "text": "A key that indicates the pitch to apply to spoken content. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "accessibilitySpeechPitch"
        },
        {
          "kind": "text",
          "text": ": NSAttributedString.Key"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/1620195-accessibilityspeechpitch",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilitySpeechPitch",
      "type": "topic",
      "url": "/documentation/foundation/nsattributedstring/key/1620195-accessibilityspeechpitch"
    },
    "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/1620201-accessibilityspeechpunctuation": {
      "abstract": [
        {
          "text": "A key that indicates whether to speak punctuation. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "accessibilitySpeechPunctuation"
        },
        {
          "kind": "text",
          "text": ": NSAttributedString.Key"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/1620201-accessibilityspeechpunctuation",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilitySpeechPunctuation",
      "type": "topic",
      "url": "/documentation/foundation/nsattributedstring/key/1620201-accessibilityspeechpunctuation"
    },
    "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/2865770-accessibilityspeechqueueannounce": {
      "abstract": [
        {
          "text": "A key that indicates whether to queue an announcement behind existing speech or to interrupt it.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "accessibilitySpeechQueueAnnouncement"
        },
        {
          "kind": "text",
          "text": ": NSAttributedString.Key"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/2865770-accessibilityspeechqueueannounce",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilitySpeechQueueAnnouncement",
      "type": "topic",
      "url": "/documentation/foundation/nsattributedstring/key/2865770-accessibilityspeechqueueannounce"
    },
    "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/2890748-accessibilityspeechipanotation": {
      "abstract": [
        {
          "text": "A key that indicates the pronunciation of a specific word or phrase, such as a proper name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "accessibilitySpeechIPANotation"
        },
        {
          "kind": "text",
          "text": ": NSAttributedString.Key"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/2890748-accessibilityspeechipanotation",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilitySpeechIPANotation",
      "type": "topic",
      "url": "/documentation/foundation/nsattributedstring/key/2890748-accessibilityspeechipanotation"
    },
    "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/3333285-accessibilityspeechspellout": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "accessibilitySpeechSpellOut"
        },
        {
          "kind": "text",
          "text": ": NSAttributedString.Key"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/3333285-accessibilityspeechspellout",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilitySpeechSpellOut",
      "type": "topic",
      "url": "/documentation/foundation/nsattributedstring/key/3333285-accessibilityspeechspellout"
    },
    "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/4168159-accessibilityspeechannouncementp": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "accessibilitySpeechAnnouncementPriority"
        },
        {
          "kind": "text",
          "text": ": NSAttributedString.Key"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/4168159-accessibilityspeechannouncementp",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilitySpeechAnnouncementPriority",
      "type": "topic",
      "url": "/documentation/foundation/nsattributedstring/key/4168159-accessibilityspeechannouncementp"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1615192-accessibilitylanguage": {
      "abstract": [
        {
          "text": "The language to use when speaking the accessibility element's label, value, and hint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "accessibilityLanguage"
        },
        {
          "kind": "text",
          "text": ": String?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1615192-accessibilitylanguage",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityLanguage",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1615192-accessibilitylanguage"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1627578-accessibilityheaderelements": {
      "abstract": [
        {
          "text": "An array of elements that serves as the headers for the accessibility element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "accessibilityHeaderElements"
        },
        {
          "kind": "text",
          "text": ": [Any]?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1627578-accessibilityheaderelements",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityHeaderElements",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1627578-accessibilityheaderelements"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/2865913-accessibilityattributedhint": {
      "abstract": [
        {
          "text": "The underlying attributed version of the accessibility hint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "accessibilityAttributedHint"
        },
        {
          "kind": "text",
          "text": ": NSAttributedString?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/2865913-accessibilityattributedhint",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityAttributedHint",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/2865913-accessibilityattributedhint"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/2865944-accessibilityattributedlabel": {
      "abstract": [
        {
          "text": "The underlying attributed version of the accessibility label.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "accessibilityAttributedLabel"
        },
        {
          "kind": "text",
          "text": ": NSAttributedString?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/2865944-accessibilityattributedlabel",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityAttributedLabel",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/2865944-accessibilityattributedlabel"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/2866105-accessibilityattributedvalue": {
      "abstract": [
        {
          "text": "The underlying attributed version of the accessibility value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "accessibilityAttributedValue"
        },
        {
          "kind": "text",
          "text": ": NSAttributedString?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/2866105-accessibilityattributedvalue",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityAttributedValue",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/2866105-accessibilityattributedvalue"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/3075456-accessibilitytextualcontext": {
      "abstract": [
        {
          "text": "A named context that helps identify and classify the type of text inside an element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "accessibilityTextualContext"
        },
        {
          "kind": "text",
          "text": ": UIAccessibilityTextualContext?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/3075456-accessibilitytextualcontext",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityTextualContext",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/3075456-accessibilitytextualcontext"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/3197988-accessibilityattributeduserinput": {
      "abstract": [
        {
          "text": "The underlying attributed versions of the accessibility user input labels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "accessibilityAttributedUserInputLabels"
        },
        {
          "kind": "text",
          "text": ": [NSAttributedString]!"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/3197988-accessibilityattributeduserinput",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityAttributedUserInputLabels",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/3197988-accessibilityattributeduserinput"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/3197989-accessibilityuserinputlabels": {
      "abstract": [
        {
          "text": "An array of localized labels the user provides to refer to the accessibility element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "accessibilityUserInputLabels"
        },
        {
          "kind": "text",
          "text": ": [String]!"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/3197989-accessibilityuserinputlabels",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityUserInputLabels",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/3197989-accessibilityuserinputlabels"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityPriority": {
      "abstract": [
        {
          "text": "Constants that specify priorities for accessibility announcements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAccessibilityPriority"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityPriority",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityPriority"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityPriority",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitypriority"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeAnnouncementPriority": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIAccessibilitySpeechAttributeAnnouncementPriority"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeAnnouncementPriority",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAccessibilitySpeechAttributeAnnouncementPriority",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityspeechattributeannouncementpriority"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeIPANotation": {
      "abstract": [
        {
          "text": "A key that indicates the pronunciation of a specific word or phrase, such as a proper name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIAccessibilitySpeechAttributeIPANotation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeIPANotation",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAccessibilitySpeechAttributeIPANotation",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityspeechattributeipanotation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeLanguage": {
      "abstract": [
        {
          "text": "A key that indicates the language to use when speaking a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIAccessibilitySpeechAttributeLanguage"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeLanguage",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAccessibilitySpeechAttributeLanguage",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityspeechattributelanguage"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributePitch": {
      "abstract": [
        {
          "text": "A key that indicates the pitch to apply to spoken content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIAccessibilitySpeechAttributePitch"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributePitch",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAccessibilitySpeechAttributePitch",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityspeechattributepitch"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributePunctuation": {
      "abstract": [
        {
          "text": "A key that indicates whether to speak punctuation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIAccessibilitySpeechAttributePunctuation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributePunctuation",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAccessibilitySpeechAttributePunctuation",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityspeechattributepunctuation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeQueueAnnouncement": {
      "abstract": [
        {
          "text": "A key that indicates whether to queue an announcement behind existing speech or to interrupt it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIAccessibilitySpeechAttributeQueueAnnouncement"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeQueueAnnouncement",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAccessibilitySpeechAttributeQueueAnnouncement",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityspeechattributequeueannouncement"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeSpellOut": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIAccessibilitySpeechAttributeSpellOut"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeSpellOut",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAccessibilitySpeechAttributeSpellOut",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityspeechattributespellout"
    },
    "doc://com.apple.uikit/documentation/UIKit/accessibility-for-uikit": {
      "abstract": [
        {
          "text": "Make your UIKit apps accessible to everyone who uses iOS and tvOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/accessibility-for-uikit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Accessibility for UIKit",
      "type": "topic",
      "url": "/documentation/uikit/accessibility-for-uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/text-attributes-for-attributed-strings": {
      "abstract": [
        {
          "text": "Apply attributes to text in an attributed string to convey extra information about the text.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/text-attributes-for-attributed-strings",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Text attributes for attributed strings",
      "type": "topic",
      "url": "/documentation/uikit/text-attributes-for-attributed-strings"
    },
    "doc://com.apple.uikit/documentation/UIKit/uiaccessibility-protocol": {
      "abstract": [
        {
          "text": "A set of methods that provides accessibility information about views and controls in an app’s user interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/uiaccessibility-protocol",
      "kind": "article",
      "role": "collectionGroup",
      "title": "UIAccessibility",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility-protocol"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Defining-accessibility-text-and-language",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/text-attributes-for-attributed-strings",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/1627578-accessibilityheaderelements",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/2865913-accessibilityattributedhint",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/2865944-accessibilityattributedlabel",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/1615192-accessibilitylanguage",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/3075456-accessibilitytextualcontext",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/3197989-accessibilityuserinputlabels",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/3197988-accessibilityattributeduserinput",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/2866105-accessibilityattributedvalue"
      ],
      "title": "Defining accessibility text and language"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/1620201-accessibilityspeechpunctuation",
        "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/1620188-accessibilityspeechlanguage",
        "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/1620195-accessibilityspeechpitch",
        "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/2865770-accessibilityspeechqueueannounce",
        "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/2890748-accessibilityspeechipanotation",
        "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/4168159-accessibilityspeechannouncementp",
        "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/3333285-accessibilityspeechspellout",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityPriority"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributePunctuation",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeLanguage",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributePitch",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeQueueAnnouncement",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeIPANotation",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeAnnouncementPriority",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeSpellOut",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityPriority"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Defining-accessibility-text-and-language",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/text-attributes-for-attributed-strings",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/1627578-accessibilityheaderelements",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/2865913-accessibilityattributedhint",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/2865944-accessibilityattributedlabel",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/1615192-accessibilitylanguage",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/3075456-accessibilitytextualcontext",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/3197989-accessibilityuserinputlabels",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/3197988-accessibilityattributeduserinput",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/2866105-accessibilityattributedvalue"
              ],
              "title": "Defining accessibility text and language"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityPriority/title",
          "value": "UIAccessibilityPriority"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityPriority/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityPriority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityPriority/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityPriority"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/speech-attributes-for-attributed-strings"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/speech-attributes-for-attributed-strings"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
