{"sections":[],"kind":"article","metadata":{"title":"Standard colors","modules":[{"name":"UIKit"}],"roleHeading":"API Collection","role":"collectionGroup"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/drawing","doc://com.apple.uikit/documentation/UIKit/UIColor"]]},"variants":[{"paths":["/documentation/uikit/standard-colors"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/standard-colors"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Define standard color objects for specific shades, such as red, blue, green, black, white, and more.","type":"text"}],"seeAlsoSections":[{"anchor":"Getting-existing-colors","generated":true,"title":"Getting existing colors","identifiers":["doc://com.apple.uikit/documentation/UIKit/ui-element-colors","doc://com.apple.uikit/documentation/UIKit/color-creation"]}],"primaryContentSections":[{"kind":"content","content":[{"level":2,"type":"heading","anchor":"overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use the standard color objects when you want to use a specific color shade in your UI. To view swatches of these colors, see "},{"isActive":true,"identifier":"https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/color/#system-colors","type":"reference"},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"text":"The system color objects adapt automatically to Dark Mode changes when you use the provided ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor","isActive":true,"type":"reference"},{"text":" object, but the fixed-shade colors don’t adapt. If you retrieve the color values, either directly or using another type such as ","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/coregraphics/cgcolor","isActive":true,"type":"reference"},{"text":", you must handle Dark Mode changes yourself. For more information about supporting Dark Mode, see ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/supporting-dark-mode-in-your-interface","isActive":true,"type":"reference"},{"text":".","type":"text"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/standard-colors","interfaceLanguage":"swift"},"topicSections":[{"anchor":"Adaptable-colors","title":"Adaptable colors","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIColor/systemBlue","doc://com.apple.uikit/documentation/UIKit/UIColor/systemBrown","doc://com.apple.uikit/documentation/UIKit/UIColor/systemCyan","doc://com.apple.uikit/documentation/UIKit/UIColor/systemGreen","doc://com.apple.uikit/documentation/UIKit/UIColor/systemIndigo","doc://com.apple.uikit/documentation/UIKit/UIColor/systemMint","doc://com.apple.uikit/documentation/UIKit/UIColor/systemOrange","doc://com.apple.uikit/documentation/UIKit/UIColor/systemPink","doc://com.apple.uikit/documentation/UIKit/UIColor/systemPurple","doc://com.apple.uikit/documentation/UIKit/UIColor/systemRed","doc://com.apple.uikit/documentation/UIKit/UIColor/systemTeal","doc://com.apple.uikit/documentation/UIKit/UIColor/systemYellow"]},{"anchor":"Adaptable-gray-colors","title":"Adaptable gray colors","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIColor/systemGray","doc://com.apple.uikit/documentation/UIKit/UIColor/systemGray2","doc://com.apple.uikit/documentation/UIKit/UIColor/systemGray3","doc://com.apple.uikit/documentation/UIKit/UIColor/systemGray4","doc://com.apple.uikit/documentation/UIKit/UIColor/systemGray5","doc://com.apple.uikit/documentation/UIKit/UIColor/systemGray6"]},{"anchor":"Transparent-color","title":"Transparent color","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIColor/clear"]},{"anchor":"Fixed-colors","title":"Fixed colors","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIColor/black","doc://com.apple.uikit/documentation/UIKit/UIColor/blue","doc://com.apple.uikit/documentation/UIKit/UIColor/brown","doc://com.apple.uikit/documentation/UIKit/UIColor/cyan","doc://com.apple.uikit/documentation/UIKit/UIColor/darkGray","doc://com.apple.uikit/documentation/UIKit/UIColor/gray","doc://com.apple.uikit/documentation/UIKit/UIColor/green","doc://com.apple.uikit/documentation/UIKit/UIColor/lightGray","doc://com.apple.uikit/documentation/UIKit/UIColor/magenta","doc://com.apple.uikit/documentation/UIKit/UIColor/orange","doc://com.apple.uikit/documentation/UIKit/UIColor/purple","doc://com.apple.uikit/documentation/UIKit/UIColor/red","doc://com.apple.uikit/documentation/UIKit/UIColor/white","doc://com.apple.uikit/documentation/UIKit/UIColor/yellow"]}],"references":{"doc://com.apple.uikit/documentation/UIKit/UIColor":{"type":"topic","role":"symbol","title":"UIColor","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UIColor","kind":"identifier"}],"navigatorTitle":[{"text":"UIColor","kind":"identifier"}],"abstract":[{"type":"text","text":"An object that stores color data and sometimes opacity."}],"url":"/documentation/uikit/uicolor","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIColor/systemYellow":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"systemYellow","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"systemYellowColor","kind":"identifier"}],"title":"systemYellow","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/systemYellow","type":"topic","url":"/documentation/uikit/uicolor/systemyellow","kind":"symbol","abstract":[{"type":"text","text":"A yellow color that automatically adapts to the current trait environment."}]},"doc://com.apple.uikit/documentation/UIKit/UIColor/systemGreen":{"navigatorTitle":[{"text":"systemGreenColor","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/systemGreen","abstract":[{"type":"text","text":"A green color that automatically adapts to the current trait environment."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"systemGreen","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"url":"/documentation/uikit/uicolor/systemgreen","title":"systemGreen","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIColor/systemMint":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/systemMint","abstract":[{"type":"text","text":"A mint color that automatically adapts to the current trait environment."}],"title":"systemMint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"systemMint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"navigatorTitle":[{"kind":"identifier","text":"systemMintColor"}],"role":"symbol","url":"/documentation/uikit/uicolor/systemmint","kind":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/drawing":{"title":"Drawing","type":"topic","url":"/documentation/uikit/drawing","role":"collectionGroup","identifier":"doc://com.apple.uikit/documentation/UIKit/drawing","kind":"article","abstract":[{"type":"text","text":"Configure your app’s drawing environment using colors, renderers, draw paths, strings, and shadows."}]},"doc://com.apple.uikit/documentation/UIKit/UIColor/magenta":{"type":"topic","role":"symbol","title":"magenta","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"magenta","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"magentaColor","kind":"identifier"}],"abstract":[{"text":"A color object with RGB values of ","type":"text"},{"code":"1.0","type":"codeVoice"},{"text":", ","type":"text"},{"code":"0.0","type":"codeVoice"},{"text":", and ","type":"text"},{"code":"1.0","type":"codeVoice"},{"text":", and an alpha value of ","type":"text"},{"code":"1.0","type":"codeVoice"},{"text":".","type":"text"}],"url":"/documentation/uikit/uicolor/magenta","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/magenta","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIColor/systemGray4":{"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/systemGray4","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"systemGray4Color"}],"title":"systemGray4","url":"/documentation/uikit/uicolor/systemgray4","abstract":[{"type":"text","text":"A fourth-level shade of gray that adapts to the environment."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"systemGray4"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}]},"doc://com.apple.uikit/documentation/UIKit/UIColor/red":{"navigatorTitle":[{"text":"redColor","kind":"identifier"}],"url":"/documentation/uikit/uicolor/red","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"red","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"text":"A color object with RGB values of ","type":"text"},{"code":"1.0","type":"codeVoice"},{"text":", ","type":"text"},{"code":"0.0","type":"codeVoice"},{"text":", and ","type":"text"},{"code":"0.0","type":"codeVoice"},{"text":", and an alpha value of ","type":"text"},{"code":"1.0","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/red","title":"red","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIColor/systemGray6":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/systemGray6","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"systemGray6"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"role":"symbol","title":"systemGray6","navigatorTitle":[{"text":"systemGray6Color","kind":"identifier"}],"type":"topic","abstract":[{"text":"A sixth-level shade of gray that adapts to the environment.","type":"text"}],"url":"/documentation/uikit/uicolor/systemgray6","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIColor/darkGray":{"abstract":[{"text":"A color object with a grayscale value of 1/3 and an alpha value of ","type":"text"},{"code":"1.0","type":"codeVoice"},{"text":".","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"darkGray","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"role":"symbol","url":"/documentation/uikit/uicolor/darkgray","navigatorTitle":[{"text":"darkGrayColor","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/darkGray","type":"topic","title":"darkGray","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIColor/systemTeal":{"url":"/documentation/uikit/uicolor/systemteal","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"systemTeal","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"abstract":[{"text":"A teal color that automatically adapts to the current trait environment.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"systemTealColor","kind":"identifier"}],"type":"topic","role":"symbol","title":"systemTeal","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/systemTeal"},"doc://com.apple.uikit/documentation/UIKit/UIColor/systemGray5":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/systemGray5","title":"systemGray5","url":"/documentation/uikit/uicolor/systemgray5","navigatorTitle":[{"kind":"identifier","text":"systemGray5Color"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"A fifth-level shade of gray that adapts to the environment."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"systemGray5"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}]},"doc://com.apple.uikit/documentation/UIKit/UIColor/lightGray":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lightGray"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"url":"/documentation/uikit/uicolor/lightgray","title":"lightGray","navigatorTitle":[{"kind":"identifier","text":"lightGrayColor"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/lightGray","abstract":[{"type":"text","text":"A color object with a grayscale value of 2/3 and an alpha value of "},{"code":"1.0","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/ui-element-colors":{"title":"UI element colors","url":"/documentation/uikit/ui-element-colors","abstract":[{"type":"text","text":"Choose colors for UI elements such as labels, text, backgrounds, and links."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/ui-element-colors","type":"topic","kind":"article","role":"collectionGroup"},"doc://com.apple.uikit/documentation/UIKit/UIColor/blue":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"blue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"A color object with RGB values of ","type":"text"},{"code":"0.0","type":"codeVoice"},{"text":", ","type":"text"},{"code":"0.0","type":"codeVoice"},{"text":", and ","type":"text"},{"code":"1.0","type":"codeVoice"},{"text":", and an alpha value of ","type":"text"},{"code":"1.0","type":"codeVoice"},{"text":".","type":"text"}],"url":"/documentation/uikit/uicolor/blue","navigatorTitle":[{"text":"blueColor","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/blue","title":"blue"},"doc://com.apple.uikit/documentation/UIKit/UIColor/green":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"green","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"type":"topic","abstract":[{"type":"text","text":"A color object with RGB values of "},{"type":"codeVoice","code":"0.0"},{"type":"text","text":", "},{"type":"codeVoice","code":"1.0"},{"type":"text","text":", and "},{"type":"codeVoice","code":"0.0"},{"type":"text","text":", and an alpha value of "},{"type":"codeVoice","code":"1.0"},{"type":"text","text":"."}],"role":"symbol","navigatorTitle":[{"text":"greenColor","kind":"identifier"}],"kind":"symbol","url":"/documentation/uikit/uicolor/green","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/green","title":"green"},"doc://com.apple.uikit/documentation/UIKit/UIColor/systemPink":{"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"systemPink","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/systemPink","type":"topic","abstract":[{"text":"A pink color that automatically adapts to the current trait environment.","type":"text"}],"url":"/documentation/uikit/uicolor/systempink","title":"systemPink","navigatorTitle":[{"text":"systemPinkColor","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIColor/black":{"navigatorTitle":[{"kind":"identifier","text":"blackColor"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/black","abstract":[{"type":"text","text":"A color object in the sRGB color space with a grayscale value of "},{"type":"codeVoice","code":"0.0"},{"type":"text","text":" and an alpha value of "},{"type":"codeVoice","code":"1.0"},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"black"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"url":"/documentation/uikit/uicolor/black","title":"black","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIColor/white":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/white","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"whiteColor"}],"url":"/documentation/uikit/uicolor/white","title":"white","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"white"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"abstract":[{"type":"text","text":"A color object with a grayscale value of "},{"type":"codeVoice","code":"1.0"},{"type":"text","text":" and an alpha value of "},{"type":"codeVoice","code":"1.0"},{"type":"text","text":"."}]},"doc://com.apple.uikit/documentation/UIKit/UIColor/systemBlue":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/systemBlue","navigatorTitle":[{"text":"systemBlueColor","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"systemBlue","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"type":"topic","kind":"symbol","abstract":[{"text":"A blue color that automatically adapts to the current trait environment.","type":"text"}],"title":"systemBlue","url":"/documentation/uikit/uicolor/systemblue","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIColor/systemGray":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/systemGray","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"systemGray"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"role":"symbol","title":"systemGray","navigatorTitle":[{"text":"systemGrayColor","kind":"identifier"}],"type":"topic","abstract":[{"text":"The standard base gray color that adapts to the environment.","type":"text"}],"url":"/documentation/uikit/uicolor/systemgray","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIColor/purple":{"abstract":[{"type":"text","text":"A color object with RGB values of "},{"code":"0.5","type":"codeVoice"},{"type":"text","text":", "},{"code":"0.0","type":"codeVoice"},{"type":"text","text":", and "},{"code":"0.5","type":"codeVoice"},{"type":"text","text":", and an alpha value of "},{"code":"1.0","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"purple"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"role":"symbol","url":"/documentation/uikit/uicolor/purple","navigatorTitle":[{"kind":"identifier","text":"purpleColor"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/purple","type":"topic","title":"purple","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIColor/systemIndigo":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"systemIndigoColor","kind":"identifier"}],"title":"systemIndigo","url":"/documentation/uikit/uicolor/systemindigo","abstract":[{"type":"text","text":"An indigo color that automatically adapts to the current trait environment."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/systemIndigo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"systemIndigo","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIColor/systemRed":{"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/systemRed","type":"topic","url":"/documentation/uikit/uicolor/systemred","title":"systemRed","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"systemRedColor"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"systemRed"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"abstract":[{"text":"A red color that automatically adapts to the current trait environment.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UIColor/systemCyan":{"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/systemCyan","type":"topic","url":"/documentation/uikit/uicolor/systemcyan","title":"systemCyan","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"systemCyanColor"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"systemCyan"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"A cyan color that automatically adapts to the current trait environment."}]},"doc://com.apple.uikit/documentation/UIKit/UIColor/cyan":{"type":"topic","role":"symbol","title":"cyan","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cyan","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"navigatorTitle":[{"text":"cyanColor","kind":"identifier"}],"abstract":[{"type":"text","text":"A color object with RGB values of "},{"type":"codeVoice","code":"0.0"},{"type":"text","text":", "},{"type":"codeVoice","code":"1.0"},{"type":"text","text":", and "},{"type":"codeVoice","code":"1.0"},{"type":"text","text":", and an alpha value of "},{"type":"codeVoice","code":"1.0"},{"type":"text","text":"."}],"url":"/documentation/uikit/uicolor/cyan","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/cyan","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIColor/brown":{"navigatorTitle":[{"kind":"identifier","text":"brownColor"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/brown","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"brown"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"url":"/documentation/uikit/uicolor/brown","abstract":[{"type":"text","text":"A color object with RGB values of "},{"type":"codeVoice","code":"0.6"},{"type":"text","text":", "},{"type":"codeVoice","code":"0.4"},{"type":"text","text":", and "},{"type":"codeVoice","code":"0.2"},{"type":"text","text":", and an alpha value of "},{"type":"codeVoice","code":"1.0"},{"type":"text","text":"."}],"title":"brown","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIColor/systemBrown":{"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/systemBrown","type":"topic","url":"/documentation/uikit/uicolor/systembrown","title":"systemBrown","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"systemBrownColor"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"systemBrown"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"A brown color that automatically adapts to the current trait environment."}]},"doc://com.apple.uikit/documentation/UIKit/UIColor/systemPurple":{"navigatorTitle":[{"text":"systemPurpleColor","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/systemPurple","abstract":[{"type":"text","text":"A purple color that automatically adapts to the current trait environment."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"systemPurple","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"url":"/documentation/uikit/uicolor/systempurple","title":"systemPurple","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIColor/orange":{"type":"topic","role":"symbol","title":"orange","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"orange","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"navigatorTitle":[{"text":"orangeColor","kind":"identifier"}],"abstract":[{"type":"text","text":"A color object with RGB values of "},{"type":"codeVoice","code":"1.0"},{"type":"text","text":", "},{"type":"codeVoice","code":"0.5"},{"type":"text","text":", and "},{"type":"codeVoice","code":"0.0"},{"type":"text","text":", and an alpha value of "},{"type":"codeVoice","code":"1.0"},{"type":"text","text":"."}],"url":"/documentation/uikit/uicolor/orange","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/orange","kind":"symbol"},"doc://com.apple.documentation/documentation/coregraphics/cgcolor":{"title":"CGColor","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A set of components that define a color, with a color space specifying how to interpret them."}],"fragments":[{"text":"class ","kind":"text"},{"text":"CGColor","kind":"identifier"}],"url":"/documentation/coregraphics/cgcolor","identifier":"doc://com.apple.documentation/documentation/coregraphics/cgcolor","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/color-creation":{"url":"/documentation/uikit/color-creation","role":"collectionGroup","title":"Color creation","kind":"article","identifier":"doc://com.apple.uikit/documentation/UIKit/color-creation","abstract":[{"text":"Load colors from asset catalogs and create colors from raw component values.","type":"text"}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIColor/systemGray3":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/systemGray3","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"systemGray3"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"role":"symbol","title":"systemGray3","navigatorTitle":[{"kind":"identifier","text":"systemGray3Color"}],"type":"topic","abstract":[{"type":"text","text":"A third-level shade of gray that adapts to the environment."}],"url":"/documentation/uikit/uicolor/systemgray3","kind":"symbol"},"https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/color/#system-colors":{"url":"https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/color/#system-colors","title":"System Colors","titleInlineContent":[{"type":"text","text":"System Colors"}],"type":"link","identifier":"https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/color/#system-colors"},"doc://com.apple.uikit/documentation/UIKit/UIColor/systemOrange":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/systemOrange","abstract":[{"type":"text","text":"An orange color that automatically adapts to the current trait environment."}],"title":"systemOrange","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"systemOrange","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"systemOrangeColor","kind":"identifier"}],"role":"symbol","url":"/documentation/uikit/uicolor/systemorange","kind":"symbol","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIColor/clear":{"title":"clear","navigatorTitle":[{"kind":"identifier","text":"clearColor"}],"role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/clear","type":"topic","url":"/documentation/uikit/uicolor/clear","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clear"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"abstract":[{"type":"text","text":"A color object with grayscale and alpha values that are both "},{"type":"codeVoice","code":"0.0"},{"type":"text","text":"."}]},"doc://com.apple.uikit/documentation/UIKit/UIColor/systemGray2":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/systemGray2","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"systemGray2"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"role":"symbol","title":"systemGray2","navigatorTitle":[{"kind":"identifier","text":"systemGray2Color"}],"type":"topic","abstract":[{"type":"text","text":"A second-level shade of gray that adapts to the environment."}],"url":"/documentation/uikit/uicolor/systemgray2","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIColor/yellow":{"navigatorTitle":[{"kind":"identifier","text":"yellowColor"}],"title":"yellow","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/yellow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"yellow"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"abstract":[{"type":"text","text":"A color object with RGB values of "},{"type":"codeVoice","code":"1.0"},{"type":"text","text":", "},{"type":"codeVoice","code":"1.0"},{"type":"text","text":", and "},{"type":"codeVoice","code":"0.0"},{"type":"text","text":", and an alpha value of "},{"type":"codeVoice","code":"1.0"},{"type":"text","text":"."}],"url":"/documentation/uikit/uicolor/yellow","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/supporting-dark-mode-in-your-interface":{"url":"/documentation/uikit/supporting-dark-mode-in-your-interface","role":"collectionGroup","kind":"article","title":"Supporting Dark Mode in Your Interface","type":"topic","abstract":[{"type":"text","text":"Update colors, images, and behaviors so that your app adapts automatically when Dark Mode is active."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/supporting-dark-mode-in-your-interface"},"doc://com.apple.uikit/documentation/UIKit/UIColor/gray":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gray"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"url":"/documentation/uikit/uicolor/gray","title":"gray","navigatorTitle":[{"kind":"identifier","text":"grayColor"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIColor/gray","abstract":[{"text":"A color object with a grayscale value of ","type":"text"},{"type":"codeVoice","code":"0.5"},{"text":" and an alpha value of ","type":"text"},{"type":"codeVoice","code":"1.0"},{"text":".","type":"text"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","path":"/topicSections","value":[{"title":"Adaptable colors","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIColor/systemBlue","doc://com.apple.uikit/documentation/UIKit/UIColor/systemBrown","doc://com.apple.uikit/documentation/UIKit/UIColor/systemCyan","doc://com.apple.uikit/documentation/UIKit/UIColor/systemGreen","doc://com.apple.uikit/documentation/UIKit/UIColor/systemIndigo","doc://com.apple.uikit/documentation/UIKit/UIColor/systemMint","doc://com.apple.uikit/documentation/UIKit/UIColor/systemOrange","doc://com.apple.uikit/documentation/UIKit/UIColor/systemPink","doc://com.apple.uikit/documentation/UIKit/UIColor/systemPurple","doc://com.apple.uikit/documentation/UIKit/UIColor/systemRed","doc://com.apple.uikit/documentation/UIKit/UIColor/systemTeal","doc://com.apple.uikit/documentation/UIKit/UIColor/systemYellow"],"anchor":"Adaptable-colors"},{"title":"Adaptable gray colors","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIColor/systemGray","doc://com.apple.uikit/documentation/UIKit/UIColor/systemGray2","doc://com.apple.uikit/documentation/UIKit/UIColor/systemGray3","doc://com.apple.uikit/documentation/UIKit/UIColor/systemGray4","doc://com.apple.uikit/documentation/UIKit/UIColor/systemGray5","doc://com.apple.uikit/documentation/UIKit/UIColor/systemGray6"],"anchor":"Adaptable-gray-colors"},{"title":"Transparent color","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIColor/clear"],"anchor":"Transparent-color"},{"title":"Fixed colors","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIColor/black","doc://com.apple.uikit/documentation/UIKit/UIColor/blue","doc://com.apple.uikit/documentation/UIKit/UIColor/brown","doc://com.apple.uikit/documentation/UIKit/UIColor/cyan","doc://com.apple.uikit/documentation/UIKit/UIColor/darkGray","doc://com.apple.uikit/documentation/UIKit/UIColor/gray","doc://com.apple.uikit/documentation/UIKit/UIColor/green","doc://com.apple.uikit/documentation/UIKit/UIColor/lightGray","doc://com.apple.uikit/documentation/UIKit/UIColor/magenta","doc://com.apple.uikit/documentation/UIKit/UIColor/orange","doc://com.apple.uikit/documentation/UIKit/UIColor/purple","doc://com.apple.uikit/documentation/UIKit/UIColor/red","doc://com.apple.uikit/documentation/UIKit/UIColor/white","doc://com.apple.uikit/documentation/UIKit/UIColor/yellow"],"anchor":"Fixed-colors"}]},{"op":"replace","path":"/seeAlsoSections","value":[{"generated":true,"anchor":"Getting-existing-colors","identifiers":["doc://com.apple.uikit/documentation/UIKit/ui-element-colors","doc://com.apple.uikit/documentation/UIKit/color-creation"],"title":"Getting existing colors"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor/title","value":"UIColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor/fragments","value":[{"kind":"identifier","text":"UIColor"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor/navigatorTitle","value":[{"text":"UIColor","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemYellow/title","value":"systemYellowColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemYellow/fragments","value":[{"text":"systemYellowColor","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemGreen/title","value":"systemGreenColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemGreen/fragments","value":[{"kind":"identifier","text":"systemGreenColor"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemMint/title","value":"systemMintColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemMint/fragments","value":[{"kind":"identifier","text":"systemMintColor"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1magenta/title","value":"magentaColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1magenta/fragments","value":[{"kind":"identifier","text":"magentaColor"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemGray4/title","value":"systemGray4Color"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemGray4/fragments","value":[{"kind":"identifier","text":"systemGray4Color"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1red/title","value":"redColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1red/fragments","value":[{"text":"redColor","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemGray6/title","value":"systemGray6Color"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemGray6/fragments","value":[{"kind":"identifier","text":"systemGray6Color"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1darkGray/title","value":"darkGrayColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1darkGray/fragments","value":[{"text":"darkGrayColor","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemTeal/title","value":"systemTealColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemTeal/fragments","value":[{"kind":"identifier","text":"systemTealColor"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemGray5/title","value":"systemGray5Color"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemGray5/fragments","value":[{"text":"systemGray5Color","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1lightGray/title","value":"lightGrayColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1lightGray/fragments","value":[{"kind":"identifier","text":"lightGrayColor"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1blue/title","value":"blueColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1blue/fragments","value":[{"kind":"identifier","text":"blueColor"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1green/title","value":"greenColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1green/fragments","value":[{"kind":"identifier","text":"greenColor"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemPink/title","value":"systemPinkColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemPink/fragments","value":[{"kind":"identifier","text":"systemPinkColor"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1black/title","value":"blackColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1black/fragments","value":[{"text":"blackColor","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1white/title","value":"whiteColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1white/fragments","value":[{"kind":"identifier","text":"whiteColor"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemBlue/title","value":"systemBlueColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemBlue/fragments","value":[{"kind":"identifier","text":"systemBlueColor"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemGray/title","value":"systemGrayColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemGray/fragments","value":[{"text":"systemGrayColor","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1purple/title","value":"purpleColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1purple/fragments","value":[{"text":"purpleColor","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemIndigo/title","value":"systemIndigoColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemIndigo/fragments","value":[{"kind":"identifier","text":"systemIndigoColor"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemRed/title","value":"systemRedColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemRed/fragments","value":[{"text":"systemRedColor","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemCyan/title","value":"systemCyanColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemCyan/fragments","value":[{"kind":"identifier","text":"systemCyanColor"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1cyan/title","value":"cyanColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1cyan/fragments","value":[{"kind":"identifier","text":"cyanColor"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1brown/title","value":"brownColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1brown/fragments","value":[{"kind":"identifier","text":"brownColor"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemBrown/title","value":"systemBrownColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemBrown/fragments","value":[{"kind":"identifier","text":"systemBrownColor"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemPurple/title","value":"systemPurpleColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemPurple/fragments","value":[{"text":"systemPurpleColor","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1orange/title","value":"orangeColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1orange/fragments","value":[{"text":"orangeColor","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.documentation~1documentation~1coregraphics~1cgcolor/title","value":"CGColorRef"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemGray3/title","value":"systemGray3Color"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemGray3/fragments","value":[{"text":"systemGray3Color","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemOrange/title","value":"systemOrangeColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemOrange/fragments","value":[{"kind":"identifier","text":"systemOrangeColor"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1clear/title","value":"clearColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1clear/fragments","value":[{"kind":"identifier","text":"clearColor"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemGray2/title","value":"systemGray2Color"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemGray2/fragments","value":[{"text":"systemGray2Color","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1yellow/title","value":"yellowColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1yellow/fragments","value":[{"text":"yellowColor","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1gray/title","value":"grayColor"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1gray/fragments","value":[{"text":"grayColor","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}