{
  "abstract": [
    {
      "text": "Enhance your iPad app by adding desktop-class features and document support.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/app-and-environment"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/supporting-desktop-class-features-in-your-ipad-app"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "17.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "17.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst"
      },
      {
        "beta": false,
        "introducedAt": "15.0",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Supporting desktop-class features in your iPad app"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This sample project shows how to build an app that takes full advantage",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "of the iPad’s desktop-class features like hardware keyboard and trackpad support,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Stage Manager, and rich document-editing capabilities.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The app is a markup document editor that allows creating, editing, previewing,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and saving documents, including features like a title menu with custom actions,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "document renaming, Find and Replace, and more.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "This sample code project is associated with WWDC22 sessions: ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/wwdc22/10069/",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/wwdc22/10070/",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", and ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/wwdc22/10076/",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "anchor": "Choose-the-appropriate-navigation-style",
          "level": 3,
          "text": "Choose the appropriate navigation style",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Because the app allows focused viewing and editing of individual documents,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "it uses the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationItem/ItemStyle/editor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "navigation style.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "This navigation style moves the navigation item’s title to the leading edge",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and opens up space in the center of the bar for common document actions.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "To choose the navigation style, the editor view controller assigns the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "navigation item’s",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationItem/style",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Add-center-items-for-quick-access-to-common-actions",
          "level": 3,
          "text": "Add center items for quick access to common actions",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Center item groups are groups of controls that appear in the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "navigation bar to provide quick access to the app’s most important capabilities.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "A person can customize the navigation bar’s center items by moving, removing,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "or adding certain groups.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "To enable user customization, the app assigns a string to the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "navigation item’s",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationItem/customizationIdentifier",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Set a `customizationIdentifier` and add center item groups.",
            "navigationItem.customizationIdentifier = \"editorViewCustomization\""
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The editor view controller configures center items and assigns them to",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the navigation item’s",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationItem/centerItemGroups",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "property in ",
              "type": "text"
            },
            {
              "code": "configureCenterItemGroups()",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The editor view controller creates one fixed group that people can’t move",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "or remove from the navigation bar for the Sync Scrolling item using",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/creatingFixedGroup()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "UIBarButtonItem(primaryAction: UIAction(title: \"Sync Scrolling\", image: syncScrollingImage) { [unowned self] action in",
            "    syncScrolling.toggle()",
            "    if let barButtonItem = action.sender as? UIBarButtonItem {",
            "        barButtonItem.image = syncScrollingImage",
            "    }",
            "}).creatingFixedGroup(),"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Other center item groups are optional, which means people can customize their",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "placement in the navigation bar. Optional groups that have",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "code": "isInDefaultCustomization",
              "type": "codeVoice"
            },
            {
              "text": " set to ",
              "type": "text"
            },
            {
              "code": "false",
              "type": "codeVoice"
            },
            {
              "text": " don’t appear in the navigation bar by",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "default. They appear in the customization popover that a person can access",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "by choosing the customization option in the overflow menu.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "UIBarButtonItem(primaryAction: UIAction(title: \"Strikethrough\", image: UIImage(systemName: \"strikethrough\")) { [unowned self] _ in",
            "    insertTag(.strikethrough)",
            "}).creatingOptionalGroup(customizationIdentifier: \"strikethrough\", isInDefaultCustomization: false),"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Add-a-title-menu-with-system-and-custom-actions",
          "level": 3,
          "text": "Add a title menu with system and custom actions",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A title menu appears when a person taps the navigation item’s title.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "This menu can surface actions that are relevant to the current document.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "To configure a title menu,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the editor view controller assigns a closure to the navigation item’s",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationItem/titleMenuProvider",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "navigationItem.titleMenuProvider = { suggested in",
            "    let custom = [",
            "        UIMenu(title: \"Export…\", image: UIImage(systemName: \"arrow.up.forward.square\"), children: [",
            "            UIAction(title: \"HTML\", image: UIImage(systemName: \"safari\")) { [unowned self] _ in",
            "                previewView.exportAsWebArchive(named: document.localizedName, presenter: self)",
            "            },",
            "            UIAction(title: \"PDF\", image: UIImage(systemName: \"doc.richtext\")) { [unowned self] _ in",
            "                previewView.exportAsPDF(named: document.localizedName, presenter: self)",
            "            }",
            "        ])",
            "    ]",
            "    return UIMenu(children: suggested + custom)",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The closure returns a menu that combines the suggested system actions and",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "custom actions.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The first set of actions in the menu are the ",
              "type": "text"
            },
            {
              "code": "suggested",
              "type": "codeVoice"
            },
            {
              "text": " actions that the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "system passes in to the closure, including Move and Duplicate.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The next set of actions are the ",
              "type": "text"
            },
            {
              "code": "custom",
              "type": "codeVoice"
            },
            {
              "text": " actions that the app defines:",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "exporting the document to HTML and PDF.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Configure-a-document-header",
          "level": 3,
          "text": "Configure a document header",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A document header displays helpful information about the current document,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "such as its title, file type, and size.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "It also provides a place from which to share or drag and drop the document.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "To display a document header at the top of the title menu,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the editor view controller assigns a",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentProperties",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "object to the navigation item’s",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationItem/documentProperties",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Enable-the-system-Find-and-Replace-experience",
          "level": 3,
          "text": "Enable the system Find and Replace experience",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The editor view supports editing the content of the document.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Because the editor view is a subclass of",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ",",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "enabling the system",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "Find and Replace experience takes one line of code.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Enable Find and Replace in editor text view and register as its",
            "// delegate.",
            "editorTextView.isFindInteractionEnabled = true"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "Setting the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextView/isFindInteractionEnabled",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "property enables using standard keyboard shortcuts to find text in a document",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and quickly replace it using the system-provided Find panel.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Enhance-multiple-item-selection",
          "level": 3,
          "text": "Enhance multiple-item selection",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The outline view is a collection view that serves as a table of",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "contents for the document, allowing for quick navigation",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "or taking actions on the top-level tags in the document.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "This view supports an enhanced multiple-selection experience when a",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "person interacts with the app using a keyboard and pointer.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The outline view enables lightweight multiple selection of the tags",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "without placing the collection view into editing mode by setting",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionView/allowsMultipleSelection",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ",",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionView/allowsFocus",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ",",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionView/selectionFollowsFocus",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to ",
              "type": "text"
            },
            {
              "code": "true",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Enable multiple selection.",
            "collectionView.allowsMultipleSelection = true",
            "",
            "// Enable keyboard focus.",
            "collectionView.allowsFocus = true",
            "",
            "// Allow keyboard focus to drive selection.",
            "collectionView.selectionFollowsFocus = true"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "A person can use the keyboard and pointer to select tags, and perform a",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "secondary click to open a context menu with relevant actions.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The outline view presents a specialized context menu according to the number",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "of tags in the selection by implementing",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegate/collectionView(_:contextMenuConfigurationForItemsAt:point:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to return different configurations when the selection contains one or many tags.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "if indexPaths.count > 1 {",
            "    // Action titles for a multiple-item menu.",
            "    hideTitle = \"Hide Selected\"",
            "    deleteTitle = \"Delete Selected\"",
            "} else {",
            "    // Action titles for a single-item menu.",
            "    hideTitle = \"Hide\"",
            "    deleteTitle = \"Delete\"",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Perform-a-primary-action-when-tapping-a-single-item",
          "level": 3,
          "text": "Perform a primary action when tapping a single item",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In addition to performing a secondary click on a tag in the outline view,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "a person can tap a single tag to scroll to its",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "corresponding location in the editor view.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "To distinguish the explicit user action of tapping one tag to navigate to that",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "location in the document from selecting multiple tags,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the outline view implements",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegate/collectionView(_:performPrimaryActionForItemAt:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "The system calls this method when a person taps a single tag without extending",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "a multiple selection of tags.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func collectionView(_ collectionView: UICollectionView, performPrimaryActionForItemAt indexPath: IndexPath) {",
            "    // Get the element at the `indexPath`.",
            "    if let element = dataSource.itemIdentifier(for: indexPath) {",
            "        delegate?.outline(self, didChoose: element)",
            "    }",
            "",
            "    // Wait a short amount of time before deselecting the cell for visual clarity.",
            "    DispatchQueue.main.asyncAfter(deadline: .now() + 0.2) {",
            "        collectionView.deselectItem(at: indexPath, animated: true)",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "037b0a0bd9d7/SupportingDesktopClassFeaturesInYourIPadApp.zip": {
      "checksum": "037b0a0bd9d7380d5d2ef3309e369c9b7771859156684da178525669c0a016b7e01b147bc2bdc332e74c02d3730d66100f546f306c38c02b2d4020a3fdde56fc",
      "identifier": "037b0a0bd9d7/SupportingDesktopClassFeaturesInYourIPadApp.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/037b0a0bd9d7/SupportingDesktopClassFeaturesInYourIPadApp.zip"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/creatingFixedGroup()": {
      "abstract": [
        {
          "text": "Places the item in a fixed group that a person can’t move or remove from the navigation bar during layout customization.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "creatingFixedGroup"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIBarButtonItemGroup",
          "text": "UIBarButtonItemGroup"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem/creatingFixedGroup()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "creatingFixedGroup"
        }
      ],
      "role": "symbol",
      "title": "creatingFixedGroup()",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem/creatingfixedgroup()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionView/allowsFocus": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the collection view allows its cells to become focused.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsFocus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionView/allowsFocus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsFocus"
        }
      ],
      "role": "symbol",
      "title": "allowsFocus",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionview/allowsfocus"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionView/allowsMultipleSelection": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether users can select more than one item in the collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsMultipleSelection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionView/allowsMultipleSelection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsMultipleSelection"
        }
      ],
      "role": "symbol",
      "title": "allowsMultipleSelection",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionview/allowsmultipleselection"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionView/selectionFollowsFocus": {
      "abstract": [
        {
          "text": "A Boolean value that triggers an automatic selection when focus moves to a cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectionFollowsFocus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionView/selectionFollowsFocus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectionFollowsFocus"
        }
      ],
      "role": "symbol",
      "title": "selectionFollowsFocus",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionview/selectionfollowsfocus"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegate/collectionView(_:contextMenuConfigurationForItemsAt:point:)": {
      "abstract": [
        {
          "text": "Asks the delegate for a context-menu configuration for the items at the specified index paths.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "collectionView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICollectionView",
          "text": "UICollectionView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "contextMenuConfigurationForItemsAt"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation9IndexPathV",
          "text": "IndexPath"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "point"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIContextMenuConfiguration",
          "text": "UIContextMenuConfiguration"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegate/collectionView(_:contextMenuConfigurationForItemsAt:point:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "collectionView:contextMenuConfigurationForItemsAtIndexPaths:point:"
        }
      ],
      "role": "symbol",
      "title": "collectionView(_:contextMenuConfigurationForItemsAt:point:)",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdelegate/collectionview(_:contextmenuconfigurationforitemsat:point:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegate/collectionView(_:performPrimaryActionForItemAt:)": {
      "abstract": [
        {
          "text": "Tells the delegate to perform the primary action for the cell at the specified index path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "collectionView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICollectionView",
          "text": "UICollectionView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "performPrimaryActionForItemAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation9IndexPathV",
          "text": "IndexPath"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegate/collectionView(_:performPrimaryActionForItemAt:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "collectionView:performPrimaryActionForItemAtIndexPath:"
        }
      ],
      "role": "symbol",
      "title": "collectionView(_:performPrimaryActionForItemAt:)",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdelegate/collectionview(_:performprimaryactionforitemat:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentProperties": {
      "abstract": [
        {
          "text": "Information that UIKit uses to generate a document header for a navigation item’s title menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDocumentProperties"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentProperties",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDocumentProperties"
        }
      ],
      "role": "symbol",
      "title": "UIDocumentProperties",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentproperties"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationItem/ItemStyle/editor": {
      "abstract": [
        {
          "text": "A style for an editor app interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "editor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationItem/ItemStyle/editor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UINavigationItemStyleEditor"
        }
      ],
      "role": "symbol",
      "title": "UINavigationItem.ItemStyle.editor",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationitem/itemstyle/editor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationItem/centerItemGroups": {
      "abstract": [
        {
          "text": "Customizable item groups to display in the center section of the navigation bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "centerItemGroups"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIBarButtonItemGroup",
          "text": "UIBarButtonItemGroup"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationItem/centerItemGroups",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "centerItemGroups"
        }
      ],
      "role": "symbol",
      "title": "centerItemGroups",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationitem/centeritemgroups"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationItem/customizationIdentifier": {
      "abstract": [
        {
          "text": "A globally unique string that enables user customization of the navigation bar layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "customizationIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationItem/customizationIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "customizationIdentifier"
        }
      ],
      "role": "symbol",
      "title": "customizationIdentifier",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationitem/customizationidentifier"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationItem/documentProperties": {
      "abstract": [
        {
          "text": "An object that provides the document header for the title menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentProperties"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDocumentProperties",
          "text": "UIDocumentProperties"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationItem/documentProperties",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentProperties"
        }
      ],
      "role": "symbol",
      "title": "documentProperties",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationitem/documentproperties"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationItem/style": {
      "abstract": [
        {
          "text": "A style that determines how the content of the navigation item lays out in the navigation bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "style"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UINavigationItem",
          "text": "UINavigationItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UINavigationItemStyle",
          "text": "ItemStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationItem/style",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "style"
        }
      ],
      "role": "symbol",
      "title": "style",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationitem/style"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationItem/titleMenuProvider": {
      "abstract": [
        {
          "text": "A closure that generates the navigation item’s title menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "titleMenuProvider"
        },
        {
          "kind": "text",
          "text": ": ((["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIMenuElement",
          "text": "UIMenuElement"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIMenu",
          "text": "UIMenu"
        },
        {
          "kind": "text",
          "text": "?)?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationItem/titleMenuProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "titleMenuProvider"
        }
      ],
      "role": "symbol",
      "title": "titleMenuProvider",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationitem/titlemenuprovider"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextView": {
      "abstract": [
        {
          "text": "A scrollable, multiline text region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextView"
        }
      ],
      "role": "symbol",
      "title": "UITextView",
      "type": "topic",
      "url": "/documentation/uikit/uitextview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextView/isFindInteractionEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that enables a text view’s built-in find interaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isFindInteractionEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextView/isFindInteractionEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "findInteractionEnabled"
        }
      ],
      "role": "symbol",
      "title": "isFindInteractionEnabled",
      "type": "topic",
      "url": "/documentation/uikit/uitextview/isfindinteractionenabled"
    },
    "doc://com.apple.uikit/documentation/UIKit/app-and-environment": {
      "abstract": [
        {
          "text": "Manage life-cycle events and your app’s UI scenes, and get information about traits and the environment in which your app runs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/app-and-environment",
      "kind": "article",
      "role": "collectionGroup",
      "title": "App and environment",
      "type": "topic",
      "url": "/documentation/uikit/app-and-environment"
    },
    "doc://com.apple.uikit/documentation/UIKit/building-a-desktop-class-ipad-app": {
      "abstract": [
        {
          "text": "Optimize your iPad app’s user experience by adopting desktop-class enhancements for multitasking with Stage Manager, document interactions, text editing, search, and more in iPadOS 16.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/building-a-desktop-class-ipad-app",
      "kind": "article",
      "role": "article",
      "title": "Building a desktop-class iPad app",
      "type": "topic",
      "url": "/documentation/uikit/building-a-desktop-class-ipad-app"
    },
    "doc://com.apple.uikit/documentation/UIKit/elevating-your-ipad-app-with-a-tab-bar-and-sidebar": {
      "abstract": [
        {
          "text": "Provide a compact, ergonomic tab bar for quick access to key parts of your app, and a sidebar for in-depth navigation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/elevating-your-ipad-app-with-a-tab-bar-and-sidebar",
      "kind": "article",
      "role": "article",
      "title": "Elevating your iPad app with a tab bar and sidebar",
      "type": "topic",
      "url": "/documentation/uikit/elevating-your-ipad-app-with-a-tab-bar-and-sidebar"
    },
    "doc://com.apple.uikit/documentation/UIKit/multitasking-on-ipad": {
      "abstract": [
        {
          "text": "Implement multitasking APIs to seamlessly integrate your app with iPadOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/multitasking-on-ipad",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Multitasking on iPad",
      "type": "topic",
      "url": "/documentation/uikit/multitasking-on-ipad"
    },
    "https://developer.apple.com/wwdc22/10069/": {
      "identifier": "https://developer.apple.com/wwdc22/10069/",
      "title": "10069: Meet desktop class iPad",
      "titleInlineContent": [
        {
          "text": "10069: Meet desktop class iPad",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/wwdc22/10069/"
    },
    "https://developer.apple.com/wwdc22/10070/": {
      "identifier": "https://developer.apple.com/wwdc22/10070/",
      "title": "10070: Build a desktop class iPad app",
      "titleInlineContent": [
        {
          "text": "10070: Build a desktop class iPad app",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/wwdc22/10070/"
    },
    "https://developer.apple.com/wwdc22/10076/": {
      "identifier": "https://developer.apple.com/wwdc22/10076/",
      "title": "10076: Bring your iOS app to the Mac",
      "titleInlineContent": [
        {
          "text": "10076: Bring your iOS app to the Mac",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/wwdc22/10076/"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "037b0a0bd9d7/SupportingDesktopClassFeaturesInYourIPadApp.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "iPad",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/building-a-desktop-class-ipad-app",
        "doc://com.apple.uikit/documentation/UIKit/elevating-your-ipad-app-with-a-tab-bar-and-sidebar",
        "doc://com.apple.uikit/documentation/UIKit/multitasking-on-ipad"
      ],
      "title": "iPad"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "iPad",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/building-a-desktop-class-ipad-app",
                "doc://com.apple.uikit/documentation/UIKit/elevating-your-ipad-app-with-a-tab-bar-and-sidebar",
                "doc://com.apple.uikit/documentation/UIKit/multitasking-on-ipad"
              ],
              "title": "iPad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentProperties/title",
          "value": "UIDocumentProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentProperties/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocumentProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentProperties/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocumentProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDelegate~1collectionView(_:performPrimaryActionForItemAt:)/title",
          "value": "collectionView:performPrimaryActionForItemAtIndexPath:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDelegate~1collectionView(_:performPrimaryActionForItemAt:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "collectionView:performPrimaryActionForItemAtIndexPath:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDelegate~1collectionView(_:contextMenuConfigurationForItemsAt:point:)/title",
          "value": "collectionView:contextMenuConfigurationForItemsAtIndexPaths:point:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDelegate~1collectionView(_:contextMenuConfigurationForItemsAt:point:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "collectionView:contextMenuConfigurationForItemsAtIndexPaths:point:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationItem~1style/title",
          "value": "style"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationItem~1style/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "style"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextView~1isFindInteractionEnabled/title",
          "value": "findInteractionEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextView~1isFindInteractionEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "findInteractionEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationItem~1centerItemGroups/title",
          "value": "centerItemGroups"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationItem~1centerItemGroups/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "centerItemGroups"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1allowsMultipleSelection/title",
          "value": "allowsMultipleSelection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1allowsMultipleSelection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsMultipleSelection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1selectionFollowsFocus/title",
          "value": "selectionFollowsFocus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1selectionFollowsFocus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "selectionFollowsFocus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationItem~1ItemStyle~1editor/title",
          "value": "UINavigationItemStyleEditor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationItem~1ItemStyle~1editor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UINavigationItemStyleEditor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextView/title",
          "value": "UITextView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1creatingFixedGroup()/title",
          "value": "creatingFixedGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem~1creatingFixedGroup()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "creatingFixedGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationItem~1documentProperties/title",
          "value": "documentProperties"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationItem~1documentProperties/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "documentProperties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1allowsFocus/title",
          "value": "allowsFocus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1allowsFocus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsFocus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationItem~1titleMenuProvider/title",
          "value": "titleMenuProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationItem~1titleMenuProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "titleMenuProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationItem~1customizationIdentifier/title",
          "value": "customizationIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationItem~1customizationIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "customizationIdentifier"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/supporting-desktop-class-features-in-your-ipad-app"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/supporting-desktop-class-features-in-your-ipad-app"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
