{
  "abstract": [
    {
      "text": "Manage documents across multiple devices to create a seamless editing and collaboration experience.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/documents-data-and-pasteboard"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/synchronizing-documents-in-the-icloud-environment"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "14.0",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "12.4",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Synchronizing documents in the iCloud environment"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "As technology advances, more and more people generate their digital assets from different devices, and expect those assets to synchronize seamlessly. To support such use cases, apps need to discover the assets, as well as their changes, from all the devices, and present the user with a consistent view.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This sample demonstrates how to discover and synchronize documents in the iCloud environment, and manage them to achieve high performance and a low memory footprint. These ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "documents",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " can be the digital assets or any user data.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The sample also demonstrates how to publish an iCloud container to iCloud Drive so that the user can access the container’s ",
              "type": "text"
            },
            {
              "code": "Documents",
              "type": "codeVoice"
            },
            {
              "text": " folder from other apps. Additionally, it shows how to support the Open-in-Place feature, which allows the user to launch an app by tapping a document in Files, and then edit it directly.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Configure-the-sample-code-project",
          "level": 3,
          "text": "Configure the sample code project",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Before building the sample, perform the following steps in Xcode:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In the General pane of the ",
                      "type": "text"
                    },
                    {
                      "code": "SimpleiCloudDocument",
                      "type": "codeVoice"
                    },
                    {
                      "text": " target, update the Bundle Identifier field with a new identifier.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "In the Signing & Capabilities pane, select the applicable team from the Team drop-down menu to let Xcode automatically manage the provisioning profile. See ",
                      "type": "text"
                    },
                    {
                      "identifier": "https://help.apple.com/xcode/mac/current/#/dev23aab79b4",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " for details.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Make sure the iCloud capability is present and the iCloud Documents box is in a selected state, then select the iCloud container with your bundle identifier from step 1 from the Containers list. If the container doesn’t exist, click the Add button (+), enter the container name (iCloud.<bundle identifier>), and click OK to let Xcode create the container and associate it with the app.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If you prefer to use a different container, select it from the Containers list, specify the container identifier when creating the ",
                      "type": "text"
                    },
                    {
                      "code": "MetadataProvider",
                      "type": "codeVoice"
                    },
                    {
                      "text": " instance in the ",
                      "type": "text"
                    },
                    {
                      "code": "viewDidLoad",
                      "type": "codeVoice"
                    },
                    {
                      "text": " method of the ",
                      "type": "text"
                    },
                    {
                      "code": "MainViewController",
                      "type": "codeVoice"
                    },
                    {
                      "text": " class. An iCloud container identifier is case-sensitive and must begin with “",
                      "type": "text"
                    },
                    {
                      "code": "iCloud.",
                      "type": "codeVoice"
                    },
                    {
                      "text": "”.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Find the ",
                      "type": "text"
                    },
                    {
                      "code": "NSUbiquitousContainers",
                      "type": "codeVoice"
                    },
                    {
                      "text": " entry in the ",
                      "type": "text"
                    },
                    {
                      "code": "Info.plist",
                      "type": "codeVoice"
                    },
                    {
                      "text": " file, and change the iCloud container identifier there as well.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Before running the sample on a device, configure the device as follows:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Log in with an Apple ID. For documents to synchronize across devices, the Apple ID must be the same on all devices.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Choose Settings > Apple ID > iCloud, and turn on iCloud Drive, if it is off.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Prepare some pictures in the Photo Library to use in the sample.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "anchor": "Publish-an-iCloud-container-to-iCloud-Drive",
          "level": 3,
          "text": "Publish an iCloud container to iCloud Drive",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Publishing an iCloud container to iCloud Drive makes the container’s ",
              "type": "text"
            },
            {
              "code": "Documents",
              "type": "codeVoice"
            },
            {
              "text": " folder appear in iCloud Drive so the user can access the folder from other apps. Follow these steps to publish a container:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Provide the container’s metadata by adding an ",
                      "type": "text"
                    },
                    {
                      "code": "NSUbiquitousContainers",
                      "type": "codeVoice"
                    },
                    {
                      "text": " entry to the ",
                      "type": "text"
                    },
                    {
                      "code": "Info.plist",
                      "type": "codeVoice"
                    },
                    {
                      "text": " file like the example code below demonstrates.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Increase the bundle version by changing the Build field in the General pane of the Xcode target, or the  ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CFBundleVersion",
                      "isActive": true,
                      "overridingTitle": "CFBundleVersion",
                      "overridingTitleInlineContent": [
                        {
                          "code": "CFBundleVersion",
                          "type": "codeVoice"
                        }
                      ],
                      "type": "reference"
                    },
                    {
                      "text": " entry in the ",
                      "type": "text"
                    },
                    {
                      "code": "Info.plist",
                      "type": "codeVoice"
                    },
                    {
                      "text": " file. The new value must be larger than the previous value when using the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring/1408732-compare",
                      "isActive": true,
                      "overridingTitle": "compare(_:options:range:)",
                      "overridingTitleInlineContent": [
                        {
                          "code": "compare(_:options:range:)",
                          "type": "codeVoice"
                        }
                      ],
                      "type": "reference"
                    },
                    {
                      "text": " method with the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring/compareoptions/1415530-numeric",
                      "isActive": true,
                      "overridingTitle": "NSString.CompareOptions.numeric",
                      "overridingTitleInlineContent": [
                        {
                          "code": "NSString.CompareOptions.numeric",
                          "type": "codeVoice"
                        }
                      ],
                      "type": "reference"
                    },
                    {
                      "text": " option to compare, and must only contain numeric (0 – 9) and period (.) characters. The system only updates an app’s iCloud container metadata when detecting a new version, so perform this step every time the metadata changes.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Make sure the ",
                      "type": "text"
                    },
                    {
                      "code": "Documents",
                      "type": "codeVoice"
                    },
                    {
                      "text": " folder exists in the iCloud container and has at least one document.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "NSUbiquitousContainers",
              "type": "codeVoice"
            },
            {
              "text": " entry of the sample is as follows:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "    <key>NSUbiquitousContainers</key>",
            "    <dict>",
            "        <key>iCloud.com.example.apple-samplecode.SimpleiCloudDocument</key>",
            "        <dict>",
            "            <key>NSUbiquitousContainerIsDocumentScopePublic</key>",
            "            <true/>",
            "            <key>NSUbiquitousContainerName</key>",
            "            <string>SimpleiCloudDocument</string>",
            "            <key>NSUbiquitousContainerSupportedFolderLevels</key>",
            "            <string>ANY</string>",
            "        </dict>",
            "    </dict>"
          ],
          "syntax": "xml",
          "type": "codeListing"
        },
        {
          "anchor": "Support-Open-in-Place",
          "level": 3,
          "text": "Support Open-in-Place",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The Open-in-Place feature allows the user to launch an app by tapping a document of the type the app owns. After opening it, the app can change the document directly without copying it to the app’s sandbox container. Follow these steps to implement the feature:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Declare and export a document type for the app by adding the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes",
                      "isActive": true,
                      "overridingTitle": "CFBundleDocumentTypes",
                      "overridingTitleInlineContent": [
                        {
                          "code": "CFBundleDocumentTypes",
                          "type": "codeVoice"
                        }
                      ],
                      "type": "reference"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations",
                      "isActive": true,
                      "overridingTitle": "UTExportedTypeDeclarations",
                      "overridingTitleInlineContent": [
                        {
                          "code": "UTExportedTypeDeclarations",
                          "type": "codeVoice"
                        }
                      ],
                      "type": "reference"
                    },
                    {
                      "text": " ",
                      "type": "text"
                    },
                    {
                      "code": "Info.plist",
                      "type": "codeVoice"
                    },
                    {
                      "text": " entries. Make sure the type conforms to at least ",
                      "type": "text"
                    },
                    {
                      "code": "public.content",
                      "type": "codeVoice"
                    },
                    {
                      "text": " and ",
                      "type": "text"
                    },
                    {
                      "code": "public.data",
                      "type": "codeVoice"
                    },
                    {
                      "text": " in the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeConformsTo",
                      "isActive": true,
                      "overridingTitle": "UTTypeConformsTo",
                      "overridingTitleInlineContent": [
                        {
                          "code": "UTTypeConformsTo",
                          "type": "codeVoice"
                        }
                      ],
                      "type": "reference"
                    },
                    {
                      "text": " entry so that the other system components, like ",
                      "type": "text"
                    },
                    {
                      "code": "UIActivityViewController",
                      "type": "codeVoice"
                    },
                    {
                      "text": ", recognize it.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Add the ",
                      "type": "text"
                    },
                    {
                      "code": "LSSupportsOpeningDocumentsInPlace",
                      "type": "codeVoice"
                    },
                    {
                      "text": " key to the ",
                      "type": "text"
                    },
                    {
                      "code": "Info.plist",
                      "type": "codeVoice"
                    },
                    {
                      "text": " file, and set the value to ",
                      "type": "text"
                    },
                    {
                      "code": "YES",
                      "type": "codeVoice"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Implement the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISceneDelegate/scene(_:openURLContexts:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method of the  ",
                      "type": "text"
                    },
                    {
                      "code": "UISceneDelegate",
                      "type": "codeVoice"
                    },
                    {
                      "text": " protocol to accept the document.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Apps need to wrap the code that accesses the passed-in URL with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsurl/1417051-startaccessingsecurityscopedreso",
              "isActive": true,
              "overridingTitle": "startAccessingSecurityScopedResource",
              "overridingTitleInlineContent": [
                {
                  "code": "startAccessingSecurityScopedResource",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsurl/1413736-stopaccessingsecurityscopedresou",
              "isActive": true,
              "overridingTitle": "stopAccessingSecurityScopedResource",
              "overridingTitleInlineContent": [
                {
                  "code": "stopAccessingSecurityScopedResource",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " methods if the URL is outside of their sandbox. This sample doesn’t explicitly do that because it accesses the URL via ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocument",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", which handles ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/Security/Conceptual/AppSandboxDesignGuide/AppSandboxInDepth/AppSandboxInDepth.html#//apple_ref/doc/uid/TP40011183-CH3-SW16",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " automatically.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Discover-documents-in-an-iCloud-container",
          "level": 3,
          "text": "Discover documents in an iCloud container",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "iOS apps use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsmetadataquery",
              "isActive": true,
              "overridingTitle": "NSMetadataQuery",
              "overridingTitleInlineContent": [
                {
                  "code": "NSMetadataQuery",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " rather than file system APIs to discover documents in an iCloud container. When an app creates an iCloud document on one device, iCloud first synchronizes the document metadata to the other devices to tell them about the existence of the document. Then, depending on the device types, iCloud may or may not continue to synchronize the document data. For iOS devices, iCloud doesn’t synchronize the document data until an app asks (either explicitly or implicitly). When an iOS app receives a notification that a new document exists, the document data may not physically exist on the local file system, so it isn’t discoverable with file system APIs.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To watch the metadata changes in the iCloud container, the sample creates an ",
              "type": "text"
            },
            {
              "code": "NSMetadataQuery",
              "type": "codeVoice"
            },
            {
              "text": " object. It uses the following code to configure and start the query to gather the changes of documents that are in the iCloud container and have an ",
              "type": "text"
            },
            {
              "code": ".sicd",
              "type": "codeVoice"
            },
            {
              "text": " extension name.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "metadataQuery.notificationBatchingInterval = 1",
            "metadataQuery.searchScopes = [NSMetadataQueryUbiquitousDataScope, NSMetadataQueryUbiquitousDocumentsScope]",
            "metadataQuery.predicate = NSPredicate(format: \"%K LIKE %@\", NSMetadataItemFSNameKey, \"*.\" + Document.extensionName)",
            "metadataQuery.sortDescriptors = [NSSortDescriptor(key: NSMetadataItemFSNameKey, ascending: true)]",
            "metadataQuery.start()"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "A query has two phases when gathering the metadata: the initial phase that collects all currently matching results, and a second phase that gathers live updates. It posts an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1414740-nsmetadataquerydidfinishgatherin",
              "isActive": true,
              "overridingTitle": "NSMetadataQueryDidFinishGathering",
              "overridingTitleInlineContent": [
                {
                  "code": "NSMetadataQueryDidFinishGathering",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " notification when it finishes the first phase, and an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1413406-nsmetadataquerydidupdate",
              "isActive": true,
              "overridingTitle": "NSMetadataQueryDidUpdate",
              "overridingTitleInlineContent": [
                {
                  "code": "NSMetadataQueryDidUpdate",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " notification each time an update occurs. To avoid potential conflicts with the system, disable the query update when accessing the results, and enable it after finishing the access, as the following example shows:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func metadataItemList() -> [MetadataItem] {",
            "    var result = [MetadataItem]()",
            "    metadataQuery.disableUpdates()",
            "    if let metadatItems = metadataQuery.results as? [NSMetadataItem] {",
            "        result = metadataItemList(from: metadatItems)",
            "    }",
            "    metadataQuery.enableUpdates()",
            "    return result",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Manage-a-large-data-set",
          "level": 3,
          "text": "Manage a large data set",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Documents in this sample could potentially contain many images, and the images might be large. To load image data only when necessary, and release the data immediately after using it, the ",
              "type": "text"
            },
            {
              "code": "Document",
              "type": "codeVoice"
            },
            {
              "text": " class provides public methods for directly accessing the images in the document package. As an example, the following method retrieves a full image asynchronously:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "func retrieveImageAsynchronously(with imageName: String, completionHandler: @escaping (UIImage?) -> Void) {",
            "    performAsynchronousFileAccess {",
            "        let imageFileURL = self.fileURL.appendingPathComponent(imageName)",
            "        let fileCoordinator = NSFileCoordinator(filePresenter: self)",
            "        fileCoordinator.coordinate(readingItemAt: imageFileURL, options: .withoutChanges, error: nil) { newURL in",
            "            if let imageData = try? Data(contentsOf: newURL), let image = UIImage(data: imageData) {",
            "                completionHandler(image)",
            "            } else {",
            "                completionHandler(nil)",
            "            }",
            "        }",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "When directly manipulating the files in the document package, the sample calls the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocument/performAsynchronousFileAccess(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to serialize the file access in the background queue, and uses ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsfilecoordinator",
              "isActive": true,
              "overridingTitle": "NSFileCoordinator",
              "overridingTitleInlineContent": [
                {
                  "code": "NSFileCoordinator",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " to coordinate the reading or writing.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Likewise, to avoid the default implementation that loads image data to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/filewrapper",
              "isActive": true,
              "overridingTitle": "FileWrapper",
              "overridingTitleInlineContent": [
                {
                  "code": "FileWrapper",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " objects and keeps it in memory, the sample overrides the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocument/save(to:for:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to directly remove or add image files when updating a document.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "override func save(to url: URL, for saveOperation: UIDocument.SaveOperation, completionHandler: ((Bool) -> Void)? = nil) {",
            "    if saveOperation != .forCreating {",
            "        print(\"\\(#function)\")",
            "        return performAsynchronousFileAccess {",
            "            let fileCoordinator = NSFileCoordinator(filePresenter: self)",
            "            fileCoordinator.coordinate(writingItemAt: self.fileURL, options: .forMerging, error: nil) { newURL in",
            "                let success = self.fulfillUnsavedChanges()",
            "                self.fileModificationDate = Date()",
            "                if let completionHandler = completionHandler {",
            "                    DispatchQueue.main.async {",
            "                        completionHandler(success)",
            "                    }",
            "                }",
            "            }",
            "        }",
            "    }",
            "    super.save(to: url, for: saveOperation, completionHandler: completionHandler)",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Resolve-version-conflicts",
          "level": 3,
          "text": "Resolve version conflicts",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In the iCloud environment, the user can edit a document from different devices. Depending on networking conditions and the timing of synchronization, that may trigger version conflicts. Apps that provide support for iCloud documents need to resolve these conflicts, and remove the obsolete versions so they don’t consume the user’s iCloud storage.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To create a document conflict with the sample:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Run the sample on two iOS devices with Internet connections that use the same Apple ID to log in to iCloud.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Create a document with several images on one device, and watch the document synchronize with the other device.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Turn on Airplane mode on both devices to disconnect them from the Internet.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Change the document on both devices by adding some images on one device, removing some images from the other device, and then saving the changes.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Turn off Airplane mode on both devices at the same time to connect them back to the Internet.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "If no conflict occurs, repeat steps 3–5. After detecting a conflict, the sample enables the ",
                      "type": "text"
                    },
                    {
                      "code": "Conflicts",
                      "type": "codeVoice"
                    },
                    {
                      "text": " item on the toolbar, and changes its color to red, so users can resolve the conflict.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Handling version conflicts in document-based apps is straightforward because ",
              "type": "text"
            },
            {
              "code": "UIDocument",
              "type": "codeVoice"
            },
            {
              "text": " does most of the heavy lifting. When a conflict occurs, ",
              "type": "text"
            },
            {
              "code": "UIDocument",
              "type": "codeVoice"
            },
            {
              "text": " detects it and posts a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocument/stateChangedNotification",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " notification, which apps can observe and then implement their conflict resolution strategy.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The sample resolves a conflict by selecting the version that has the most recent ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsfileversion/1411506-modificationdate",
              "isActive": true,
              "overridingTitle": "modificationDate",
              "overridingTitleInlineContent": [
                {
                  "code": "modificationDate",
                  "type": "codeVoice"
                }
              ],
              "type": "reference"
            },
            {
              "text": " and removing all others. It uses file coordination to assess the version information of an iCloud document to avoid potential conflicts with the system.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "private func resolveConflictsAsynchronously(document: Document, completionHandler: ((Bool) -> Void)?) {",
            "    DispatchQueue.global().async {",
            "        NSFileCoordinator().coordinate(writingItemAt: document.fileURL,",
            "                                       options: .contentIndependentMetadataOnly, error: nil) { newURL in",
            "            let shouldRevert = self.pickLatestVersion(for: newURL)",
            "            completionHandler?(shouldRevert)",
            "        }",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "74e04f5e0a75/SynchronizingDocumentsInTheICloudEnvironment.zip": {
      "checksum": "74e04f5e0a75047838c2da074c14a21a7ca18a4a84376123586deaf71b79b68d477eaddb4bc8bee61523cddbccca19d09b11e795ba74495a7b95aa4e9d4b0192",
      "identifier": "74e04f5e0a75/SynchronizingDocumentsInTheICloudEnvironment.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/74e04f5e0a75/SynchronizingDocumentsInTheICloudEnvironment.zip"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes": {
      "abstract": [
        {
          "text": "The document types supported by the bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFBundleDocumentTypes",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/CFBundleDocumentTypes"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CFBundleVersion": {
      "abstract": [
        {
          "text": "The version of the build that identifies an iteration of the bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/CFBundleVersion",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFBundleVersion",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/CFBundleVersion"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations": {
      "abstract": [
        {
          "text": "The uniform type identifiers owned and exported by the app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations",
      "kind": "symbol",
      "role": "symbol",
      "title": "UTExportedTypeDeclarations",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations"
    },
    "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeConformsTo": {
      "abstract": [
        {
          "text": "The Uniform Type Identifier types that this type conforms to.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeConformsTo",
      "kind": "symbol",
      "role": "symbol",
      "title": "UTTypeConformsTo",
      "type": "topic",
      "url": "/documentation/BundleResources/Information-Property-List/UTExportedTypeDeclarations/UTTypeConformsTo"
    },
    "doc://com.apple.documentation/documentation/foundation/filewrapper": {
      "abstract": [
        {
          "text": "A representation of a node (a file, directory, or symbolic link) in the file system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "FileWrapper"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/filewrapper",
      "kind": "symbol",
      "role": "symbol",
      "title": "FileWrapper",
      "type": "topic",
      "url": "/documentation/foundation/filewrapper"
    },
    "doc://com.apple.documentation/documentation/foundation/nsfilecoordinator": {
      "abstract": [
        {
          "text": "An object that coordinates the reading and writing of files and directories among file presenters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSFileCoordinator"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsfilecoordinator",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFileCoordinator",
      "type": "topic",
      "url": "/documentation/foundation/nsfilecoordinator"
    },
    "doc://com.apple.documentation/documentation/foundation/nsfileversion/1411506-modificationdate": {
      "abstract": [
        {
          "text": "The modification date of the version.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "modificationDate"
        },
        {
          "kind": "text",
          "text": ": Date?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsfileversion/1411506-modificationdate",
      "kind": "symbol",
      "role": "symbol",
      "title": "modificationDate",
      "type": "topic",
      "url": "/documentation/foundation/nsfileversion/1411506-modificationdate"
    },
    "doc://com.apple.documentation/documentation/foundation/nsmetadataquery": {
      "abstract": [
        {
          "text": "A query that you perform against Spotlight metadata.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSMetadataQuery"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsmetadataquery",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMetadataQuery",
      "type": "topic",
      "url": "/documentation/foundation/nsmetadataquery"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1413406-nsmetadataquerydidupdate": {
      "abstract": [
        {
          "text": "Posted when the receiver’s results have changed during the live-update phase of the query.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "NSMetadataQueryDidUpdate"
        },
        {
          "kind": "text",
          "text": ": NSNotification.Name"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1413406-nsmetadataquerydidupdate",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMetadataQueryDidUpdate",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name/1413406-nsmetadataquerydidupdate"
    },
    "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1414740-nsmetadataquerydidfinishgatherin": {
      "abstract": [
        {
          "text": "Posted when the receiver has finished with the initial result-gathering phase of the query.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "NSMetadataQueryDidFinishGathering"
        },
        {
          "kind": "text",
          "text": ": NSNotification.Name"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnotification/name/1414740-nsmetadataquerydidfinishgatherin",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMetadataQueryDidFinishGathering",
      "type": "topic",
      "url": "/documentation/foundation/nsnotification/name/1414740-nsmetadataquerydidfinishgatherin"
    },
    "doc://com.apple.documentation/documentation/foundation/nsstring/1408732-compare": {
      "abstract": [
        {
          "text": "Returns the result of invoking  with a `nil` locale.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "compare"
        },
        {
          "kind": "text",
          "text": "(String, "
        },
        {
          "kind": "identifier",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": NSString.CompareOptions, "
        },
        {
          "kind": "identifier",
          "text": "range"
        },
        {
          "kind": "text",
          "text": ": NSRange) -> ComparisonResult"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring/1408732-compare",
      "kind": "symbol",
      "role": "symbol",
      "title": "compare(_:options:range:)",
      "type": "topic",
      "url": "/documentation/foundation/nsstring/1408732-compare"
    },
    "doc://com.apple.documentation/documentation/foundation/nsstring/compareoptions/1415530-numeric": {
      "abstract": [
        {
          "text": "Numbers within strings are compared using numeric value, that is, `Name2.txt` < `Name7.txt` < `Name25.txt`. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static var "
        },
        {
          "kind": "identifier",
          "text": "numeric"
        },
        {
          "kind": "text",
          "text": ": NSString.CompareOptions"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring/compareoptions/1415530-numeric",
      "kind": "symbol",
      "role": "symbol",
      "title": "numeric",
      "type": "topic",
      "url": "/documentation/foundation/nsstring/compareoptions/1415530-numeric"
    },
    "doc://com.apple.documentation/documentation/foundation/nsurl/1413736-stopaccessingsecurityscopedresou": {
      "abstract": [
        {
          "text": "In an app that adopts App Sandbox, revokes access to the resource pointed to by a security-scoped URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "stopAccessingSecurityScopedResource"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsurl/1413736-stopaccessingsecurityscopedresou",
      "kind": "symbol",
      "role": "symbol",
      "title": "stopAccessingSecurityScopedResource()",
      "type": "topic",
      "url": "/documentation/foundation/nsurl/1413736-stopaccessingsecurityscopedresou"
    },
    "doc://com.apple.documentation/documentation/foundation/nsurl/1417051-startaccessingsecurityscopedreso": {
      "abstract": [
        {
          "text": "In an app that has adopted App Sandbox, makes the resource pointed to by a security-scoped URL available to the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "startAccessingSecurityScopedResource"
        },
        {
          "kind": "text",
          "text": "() -> Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsurl/1417051-startaccessingsecurityscopedreso",
      "kind": "symbol",
      "role": "symbol",
      "title": "startAccessingSecurityScopedResource()",
      "type": "topic",
      "url": "/documentation/foundation/nsurl/1417051-startaccessingsecurityscopedreso"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocument": {
      "abstract": [
        {
          "text": "An abstract base class for managing discrete portions of your app’s data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDocument"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDocument"
        }
      ],
      "role": "symbol",
      "title": "UIDocument",
      "type": "topic",
      "url": "/documentation/uikit/uidocument"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocument/performAsynchronousFileAccess(_:)": {
      "abstract": [
        {
          "text": "Schedules a document-reading or document-writing operation on a concurrent background queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "performAsynchronousFileAccess"
        },
        {
          "kind": "text",
          "text": "(() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocument/performAsynchronousFileAccess(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "performAsynchronousFileAccessUsingBlock:"
        }
      ],
      "role": "symbol",
      "title": "performAsynchronousFileAccess(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uidocument/performasynchronousfileaccess(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocument/save(to:for:completionHandler:)": {
      "abstract": [
        {
          "text": "Saves document data to the specified location in the application sandbox.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "save"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDocument",
          "text": "UIDocument"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIDocumentSaveOperation",
          "text": "SaveOperation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocument/save(to:for:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "saveToURL:forSaveOperation:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "save(to:for:completionHandler:)",
      "type": "topic",
      "url": "/documentation/uikit/uidocument/save(to:for:completionhandler:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocument/stateChangedNotification": {
      "abstract": [
        {
          "text": "A notification the document object posts when there’s a change in the state of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stateChangedNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocument/stateChangedNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDocumentStateChangedNotification"
        }
      ],
      "role": "symbol",
      "title": "stateChangedNotification",
      "type": "topic",
      "url": "/documentation/uikit/uidocument/statechangednotification"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument": {
      "abstract": [
        {
          "text": "A managed document object that integrates with Core Data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIManagedDocument"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIManagedDocument"
        }
      ],
      "role": "symbol",
      "title": "UIManagedDocument",
      "type": "topic",
      "url": "/documentation/uikit/uimanageddocument"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISceneDelegate/scene(_:openURLContexts:)": {
      "abstract": [
        {
          "text": "Asks the delegate to open one or more URLs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scene"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIScene",
          "text": "UIScene"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "openURLContexts"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIOpenURLContext",
          "text": "UIOpenURLContext"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISceneDelegate/scene(_:openURLContexts:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scene:openURLContexts:"
        }
      ],
      "role": "symbol",
      "title": "scene(_:openURLContexts:)",
      "type": "topic",
      "url": "/documentation/uikit/uiscenedelegate/scene(_:openurlcontexts:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/documents-data-and-pasteboard": {
      "abstract": [
        {
          "text": "Organize your app’s data and share that data on the pasteboard.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/documents-data-and-pasteboard",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Documents, data, and pasteboard",
      "type": "topic",
      "url": "/documentation/uikit/documents-data-and-pasteboard"
    },
    "https://developer.apple.com/library/archive/documentation/Security/Conceptual/AppSandboxDesignGuide/AppSandboxInDepth/AppSandboxInDepth.html#//apple_ref/doc/uid/TP40011183-CH3-SW16": {
      "identifier": "https://developer.apple.com/library/archive/documentation/Security/Conceptual/AppSandboxDesignGuide/AppSandboxInDepth/AppSandboxInDepth.html#//apple_ref/doc/uid/TP40011183-CH3-SW16",
      "title": "security-scoped bookmarks",
      "titleInlineContent": [
        {
          "text": "security-scoped bookmarks",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/Security/Conceptual/AppSandboxDesignGuide/AppSandboxInDepth/AppSandboxInDepth.html#//apple_ref/doc/uid/TP40011183-CH3-SW16"
    },
    "https://help.apple.com/xcode/mac/current/#/dev23aab79b4": {
      "identifier": "https://help.apple.com/xcode/mac/current/#/dev23aab79b4",
      "title": "Assign a project to a team",
      "titleInlineContent": [
        {
          "text": "Assign a project to a team",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://help.apple.com/xcode/mac/current/#/dev23aab79b4"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "74e04f5e0a75/SynchronizingDocumentsInTheICloudEnvironment.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Documents",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIDocument",
        "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument"
      ],
      "title": "Documents"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Documents",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIDocument",
                "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument"
              ],
              "title": "Documents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsnotification~1name~11413406-nsmetadataquerydidupdate/title",
          "value": "NSMetadataQueryDidUpdateNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1filewrapper/title",
          "value": "NSFileWrapper"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneDelegate~1scene(_:openURLContexts:)/title",
          "value": "scene:openURLContexts:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneDelegate~1scene(_:openURLContexts:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scene:openURLContexts:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsstring~11408732-compare/title",
          "value": "compare:options:range:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsurl~11413736-stopaccessingsecurityscopedresou/title",
          "value": "stopAccessingSecurityScopedResource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsnotification~1name~11414740-nsmetadataquerydidfinishgatherin/title",
          "value": "NSMetadataQueryDidFinishGatheringNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocument~1stateChangedNotification/title",
          "value": "UIDocumentStateChangedNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocument~1stateChangedNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocumentStateChangedNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocument/title",
          "value": "UIDocument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocument/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocument~1performAsynchronousFileAccess(_:)/title",
          "value": "performAsynchronousFileAccessUsingBlock:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocument~1performAsynchronousFileAccess(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "performAsynchronousFileAccessUsingBlock:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocument~1save(to:for:completionHandler:)/title",
          "value": "saveToURL:forSaveOperation:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocument~1save(to:for:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "saveToURL:forSaveOperation:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsstring~1compareoptions~11415530-numeric/title",
          "value": "NSNumericSearch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsurl~11417051-startaccessingsecurityscopedreso/title",
          "value": "startAccessingSecurityScopedResource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIManagedDocument/title",
          "value": "UIManagedDocument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIManagedDocument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIManagedDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIManagedDocument/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIManagedDocument"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/synchronizing-documents-in-the-icloud-environment"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/synchronizing-documents-in-the-icloud-environment"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
