{
  "abstract": [
    {
      "text": "Apply attributes to text in an attributed string to convey extra information about the text.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/accessibility-for-uikit",
        "doc://com.apple.uikit/documentation/UIKit/uiaccessibility-protocol"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/text-attributes-for-attributed-strings"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Text attributes for attributed strings"
  },
  "references": {
    "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/2865778-accessibilitytextcustom": {
      "abstract": [
        {
          "text": "A key for specifying custom attributes to apply to the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "accessibilityTextCustom"
        },
        {
          "kind": "text",
          "text": ": NSAttributedString.Key"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/2865778-accessibilitytextcustom",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityTextCustom",
      "type": "topic",
      "url": "/documentation/foundation/nsattributedstring/key/2865778-accessibilitytextcustom"
    },
    "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/2865779-accessibilitytextheadinglevel": {
      "abstract": [
        {
          "text": "A key for specifying the heading level of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "accessibilityTextHeadingLevel"
        },
        {
          "kind": "text",
          "text": ": NSAttributedString.Key"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/2865779-accessibilitytextheadinglevel",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityTextHeadingLevel",
      "type": "topic",
      "url": "/documentation/foundation/nsattributedstring/key/2865779-accessibilitytextheadinglevel"
    },
    "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/3074363-uiaccessibilitytextattributecont": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "UIAccessibilityTextAttributeContext"
        },
        {
          "kind": "text",
          "text": ": NSAttributedString.Key"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/3074363-uiaccessibilitytextattributecont",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAccessibilityTextAttributeContext",
      "type": "topic",
      "url": "/documentation/foundation/nsattributedstring/key/3074363-uiaccessibilitytextattributecont"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1615192-accessibilitylanguage": {
      "abstract": [
        {
          "text": "The language to use when speaking the accessibility element's label, value, and hint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "accessibilityLanguage"
        },
        {
          "kind": "text",
          "text": ": String?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1615192-accessibilitylanguage",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityLanguage",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1615192-accessibilitylanguage"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1627578-accessibilityheaderelements": {
      "abstract": [
        {
          "text": "An array of elements that serves as the headers for the accessibility element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "accessibilityHeaderElements"
        },
        {
          "kind": "text",
          "text": ": [Any]?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1627578-accessibilityheaderelements",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityHeaderElements",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1627578-accessibilityheaderelements"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/2865913-accessibilityattributedhint": {
      "abstract": [
        {
          "text": "The underlying attributed version of the accessibility hint.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "accessibilityAttributedHint"
        },
        {
          "kind": "text",
          "text": ": NSAttributedString?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/2865913-accessibilityattributedhint",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityAttributedHint",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/2865913-accessibilityattributedhint"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/2865944-accessibilityattributedlabel": {
      "abstract": [
        {
          "text": "The underlying attributed version of the accessibility label.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "accessibilityAttributedLabel"
        },
        {
          "kind": "text",
          "text": ": NSAttributedString?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/2865944-accessibilityattributedlabel",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityAttributedLabel",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/2865944-accessibilityattributedlabel"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/2866105-accessibilityattributedvalue": {
      "abstract": [
        {
          "text": "The underlying attributed version of the accessibility value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "accessibilityAttributedValue"
        },
        {
          "kind": "text",
          "text": ": NSAttributedString?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/2866105-accessibilityattributedvalue",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityAttributedValue",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/2866105-accessibilityattributedvalue"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/3075456-accessibilitytextualcontext": {
      "abstract": [
        {
          "text": "A named context that helps identify and classify the type of text inside an element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "accessibilityTextualContext"
        },
        {
          "kind": "text",
          "text": ": UIAccessibilityTextualContext?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/3075456-accessibilitytextualcontext",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityTextualContext",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/3075456-accessibilitytextualcontext"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/3197988-accessibilityattributeduserinput": {
      "abstract": [
        {
          "text": "The underlying attributed versions of the accessibility user input labels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "accessibilityAttributedUserInputLabels"
        },
        {
          "kind": "text",
          "text": ": [NSAttributedString]!"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/3197988-accessibilityattributeduserinput",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityAttributedUserInputLabels",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/3197988-accessibilityattributeduserinput"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/3197989-accessibilityuserinputlabels": {
      "abstract": [
        {
          "text": "An array of localized labels the user provides to refer to the accessibility element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "accessibilityUserInputLabels"
        },
        {
          "kind": "text",
          "text": ": [String]!"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/3197989-accessibilityuserinputlabels",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityUserInputLabels",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/3197989-accessibilityuserinputlabels"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTextAttributeContext": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityTextAttributeContext"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTextAttributeContext",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAccessibilityTextAttributeContext",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitytextattributecontext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTextAttributeCustom": {
      "abstract": [
        {
          "text": "A key for specifying custom attributes to apply to the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityTextAttributeCustom"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTextAttributeCustom",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAccessibilityTextAttributeCustom",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitytextattributecustom"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTextAttributeHeadingLevel": {
      "abstract": [
        {
          "text": "A key for specifying the heading level of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityTextAttributeHeadingLevel"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTextAttributeHeadingLevel",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAccessibilityTextAttributeHeadingLevel",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitytextattributeheadinglevel"
    },
    "doc://com.apple.uikit/documentation/UIKit/accessibility-for-uikit": {
      "abstract": [
        {
          "text": "Make your UIKit apps accessible to everyone who uses iOS and tvOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/accessibility-for-uikit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Accessibility for UIKit",
      "type": "topic",
      "url": "/documentation/uikit/accessibility-for-uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/speech-attributes-for-attributed-strings": {
      "abstract": [
        {
          "text": "Apply attributes to text in an attributed string to modify the pronunciation of that text.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/speech-attributes-for-attributed-strings",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Speech attributes for attributed strings",
      "type": "topic",
      "url": "/documentation/uikit/speech-attributes-for-attributed-strings"
    },
    "doc://com.apple.uikit/documentation/UIKit/uiaccessibility-protocol": {
      "abstract": [
        {
          "text": "A set of methods that provides accessibility information about views and controls in an app’s user interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/uiaccessibility-protocol",
      "kind": "article",
      "role": "collectionGroup",
      "title": "UIAccessibility",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility-protocol"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Defining-accessibility-text-and-language",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/speech-attributes-for-attributed-strings",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/1627578-accessibilityheaderelements",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/2865913-accessibilityattributedhint",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/2865944-accessibilityattributedlabel",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/1615192-accessibilitylanguage",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/3075456-accessibilitytextualcontext",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/3197989-accessibilityuserinputlabels",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/3197988-accessibilityattributeduserinput",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/2866105-accessibilityattributedvalue"
      ],
      "title": "Defining accessibility text and language"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/2865778-accessibilitytextcustom",
        "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/2865779-accessibilitytextheadinglevel",
        "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/3074363-uiaccessibilitytextattributecont"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTextAttributeCustom",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTextAttributeHeadingLevel",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTextAttributeContext"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Defining-accessibility-text-and-language",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/speech-attributes-for-attributed-strings",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/1627578-accessibilityheaderelements",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/2865913-accessibilityattributedhint",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/2865944-accessibilityattributedlabel",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/1615192-accessibilitylanguage",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/3075456-accessibilitytextualcontext",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/3197989-accessibilityuserinputlabels",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/3197988-accessibilityattributeduserinput",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/2866105-accessibilityattributedvalue"
              ],
              "title": "Defining accessibility text and language"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/text-attributes-for-attributed-strings"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/text-attributes-for-attributed-strings"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
