{
  "abstract": [
    {
      "text": "UIKit-specific keys and values for displaying text and managing documents.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/textkit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/textkit-string-attributes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "TextKit string attributes"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "UIKit defines these attributes and attribute keys you use to specify attribute values in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsattributedstring",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsmutableattributedstring",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/nsattributedstring": {
      "abstract": [
        {
          "text": "A string of text that manages data, layout, and stylistic information for ranges of characters to support rendering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSAttributedString"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsattributedstring",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAttributedString",
      "type": "topic",
      "url": "/documentation/foundation/nsattributedstring"
    },
    "doc://com.apple.documentation/documentation/foundation/nsmutableattributedstring": {
      "abstract": [
        {
          "text": "A mutable string with associated attributes (such as visual style, hyperlinks, or accessibility data) for portions of its text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSMutableAttributedString"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsmutableattributedstring",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMutableAttributedString",
      "type": "topic",
      "url": "/documentation/foundation/nsmutableattributedstring"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSAttributedStringDocumentAttributeKey": {
      "abstract": [
        {
          "text": "The attributes you apply to an entire document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAttributedStringDocumentAttributeKey"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSAttributedStringDocumentAttributeKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAttributedStringDocumentAttributeKey",
      "type": "topic",
      "url": "/documentation/uikit/nsattributedstringdocumentattributekey"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSAttributedStringDocumentType": {
      "abstract": [
        {
          "text": "Constants for the document type document attribute key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAttributedStringDocumentType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSAttributedStringDocumentType",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAttributedStringDocumentType",
      "type": "topic",
      "url": "/documentation/uikit/nsattributedstringdocumenttype"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager": {
      "abstract": [
        {
          "text": "An abstract class that defines the interface and a default implementation for managing the text document contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextContentManager"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentManager"
        }
      ],
      "role": "symbol",
      "title": "NSTextContentManager",
      "type": "topic",
      "url": "/documentation/uikit/nstextcontentmanager"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextContentStorage": {
      "abstract": [
        {
          "text": "A concrete object for managing your view’s text content and generating the text elements necessary for layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextContentStorage"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextContentStorage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentStorage"
        }
      ],
      "role": "symbol",
      "title": "NSTextContentStorage",
      "type": "topic",
      "url": "/documentation/uikit/nstextcontentstorage"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextEffectStyle": {
      "abstract": [
        {
          "text": "Constants for the type of effect to apply to the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextEffectStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextEffectStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextEffectStyle",
      "type": "topic",
      "url": "/documentation/uikit/nstexteffectstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextHighlightColorScheme": {
      "abstract": [
        {
          "text": "Constants that specify the highlight color to use with the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextHighlightColorScheme"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextHighlightColorScheme",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextHighlightColorScheme",
      "type": "topic",
      "url": "/documentation/uikit/nstexthighlightcolorscheme"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextHighlightStyle": {
      "abstract": [
        {
          "text": "Constants that specify the type of highlight to apply to text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextHighlightStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextHighlightStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextHighlightStyle",
      "type": "topic",
      "url": "/documentation/uikit/nstexthighlightstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutSectionKey": {
      "abstract": [
        {
          "text": "Constants for the text layout sections document attribute key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextLayoutSectionKey"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutSectionKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextLayoutSectionKey",
      "type": "topic",
      "url": "/documentation/uikit/nstextlayoutsectionkey"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextScalingType": {
      "abstract": [
        {
          "text": "Constants that specify the text scaling.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextScalingType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextScalingType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextScalingType"
        }
      ],
      "role": "symbol",
      "title": "NSTextScalingType",
      "type": "topic",
      "url": "/documentation/uikit/nstextscalingtype"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextWritingDirection": {
      "abstract": [
        {
          "text": "Options for specifying text-writing direction.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextWritingDirection"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextWritingDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextWritingDirection"
        }
      ],
      "role": "symbol",
      "title": "NSTextWritingDirection",
      "type": "topic",
      "url": "/documentation/uikit/nstextwritingdirection"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle": {
      "abstract": [
        {
          "text": "Constants for the underline style and strikethrough style attribute keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUnderlineStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUnderlineStyle"
        }
      ],
      "role": "symbol",
      "title": "NSUnderlineStyle",
      "type": "topic",
      "url": "/documentation/uikit/nsunderlinestyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSWritingDirectionFormatType": {
      "abstract": [
        {
          "text": "Constants for the writing direction attribute key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWritingDirectionFormatType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSWritingDirectionFormatType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingDirectionFormatType"
        }
      ],
      "role": "symbol",
      "title": "NSWritingDirectionFormatType",
      "type": "topic",
      "url": "/documentation/uikit/nswritingdirectionformattype"
    },
    "doc://com.apple.uikit/documentation/UIKit/document-reading-option-keys": {
      "abstract": [
        {
          "text": "Keys for constructing an attributed string from data on disk.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/document-reading-option-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Document reading option keys",
      "type": "topic",
      "url": "/documentation/uikit/document-reading-option-keys"
    },
    "doc://com.apple.uikit/documentation/UIKit/textkit": {
      "abstract": [
        {
          "text": "Manage text storage and perform custom layout of text-based content in your app’s views.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/textkit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TextKit",
      "type": "topic",
      "url": "/documentation/uikit/textkit"
    },
    "doc://com.apple.uikit/documentation/UIKit/textkit-string-attribute-keys": {
      "abstract": [
        {
          "text": "UIKit-specific keys you use to apply attributes to ranges of characters in an attributed string.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/textkit-string-attribute-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TextKit string attribute keys",
      "type": "topic",
      "url": "/documentation/uikit/textkit-string-attribute-keys"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Text-management",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSTextContentStorage",
        "doc://com.apple.uikit/documentation/UIKit/NSTextContentManager",
        "doc://com.apple.documentation/documentation/foundation/nsattributedstring",
        "doc://com.apple.documentation/documentation/foundation/nsmutableattributedstring"
      ],
      "title": "Text management"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-text-content-attributes",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/textkit-string-attribute-keys",
        "doc://com.apple.uikit/documentation/UIKit/NSTextHighlightStyle",
        "doc://com.apple.uikit/documentation/UIKit/NSTextHighlightColorScheme",
        "doc://com.apple.uikit/documentation/UIKit/NSTextEffectStyle",
        "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle",
        "doc://com.apple.uikit/documentation/UIKit/NSWritingDirectionFormatType"
      ],
      "title": "Getting text content attributes"
    },
    {
      "anchor": "Getting-document-wide-attributes",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSAttributedStringDocumentAttributeKey",
        "doc://com.apple.uikit/documentation/UIKit/document-reading-option-keys",
        "doc://com.apple.uikit/documentation/UIKit/NSAttributedStringDocumentType",
        "doc://com.apple.uikit/documentation/UIKit/NSTextLayoutSectionKey",
        "doc://com.apple.uikit/documentation/UIKit/NSTextScalingType"
      ],
      "title": "Getting document-wide attributes"
    },
    {
      "anchor": "Deprecated-Constants",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSTextWritingDirection"
      ],
      "title": "Deprecated Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSWritingDirectionFormatType/title",
          "value": "NSWritingDirectionFormatType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSWritingDirectionFormatType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingDirectionFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSWritingDirectionFormatType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingDirectionFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextScalingType/title",
          "value": "NSTextScalingType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextScalingType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextScalingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextScalingType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextScalingType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextWritingDirection/title",
          "value": "NSTextWritingDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextWritingDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextWritingDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextWritingDirection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextWritingDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSUnderlineStyle/title",
          "value": "NSUnderlineStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSUnderlineStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnderlineStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSUnderlineStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnderlineStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentStorage/title",
          "value": "NSTextContentStorage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentStorage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentStorage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentStorage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentStorage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentManager/title",
          "value": "NSTextContentManager"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentManager/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentManager"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextContentManager/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentManager"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/textkit-string-attributes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
