{
  "abstract": [
    {
      "text": "UIKit-specific keys you use to apply attributes to ranges of characters in an attributed string.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/textkit",
        "doc://com.apple.uikit/documentation/UIKit/textkit-string-attributes"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/textkit-string-attribute-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "TextKit string attribute keys"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "UIKit defines these attribute keys you use to specify attribute values in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsattributedstring",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsmutableattributedstring",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/nsattributedstring": {
      "abstract": [
        {
          "text": "A string of text that manages data, layout, and stylistic information for ranges of characters to support rendering.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSAttributedString"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsattributedstring",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAttributedString",
      "type": "topic",
      "url": "/documentation/foundation/nsattributedstring"
    },
    "doc://com.apple.documentation/documentation/foundation/nsmutableattributedstring": {
      "abstract": [
        {
          "text": "A mutable string with associated attributes (such as visual style, hyperlinks, or accessibility data) for portions of its text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSMutableAttributedString"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsmutableattributedstring",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMutableAttributedString",
      "type": "topic",
      "url": "/documentation/foundation/nsmutableattributedstring"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSAdaptiveImageGlyphAttributeName": {
      "abstract": [
        {
          "text": "The adaptive image glyph for the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAdaptiveImageGlyphAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSAdaptiveImageGlyphAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAdaptiveImageGlyphAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nsadaptiveimageglyphattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSAttachmentAttributeName": {
      "abstract": [
        {
          "text": "The attachment for the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSAttachmentAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSAttachmentAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAttachmentAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nsattachmentattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSBackgroundColorAttributeName": {
      "abstract": [
        {
          "text": "The color of the background behind the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSBackgroundColorAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSBackgroundColorAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSBackgroundColorAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nsbackgroundcolorattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSBaselineOffsetAttributeName": {
      "abstract": [
        {
          "text": "The vertical offset for the position of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSBaselineOffsetAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSBaselineOffsetAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSBaselineOffsetAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nsbaselineoffsetattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSExpansionAttributeName": {
      "abstract": [
        {
          "text": "The expansion factor of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSExpansionAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSExpansionAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSExpansionAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nsexpansionattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSFontAttributeName": {
      "abstract": [
        {
          "text": "The font of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSFontAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSFontAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFontAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nsfontattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSForegroundColorAttributeName": {
      "abstract": [
        {
          "text": "The color of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSForegroundColorAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSForegroundColorAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSForegroundColorAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nsforegroundcolorattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSKernAttributeName": {
      "abstract": [
        {
          "text": "The kerning of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSKernAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSKernAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSKernAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nskernattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLigatureAttributeName": {
      "abstract": [
        {
          "text": "The ligature of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSLigatureAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLigatureAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLigatureAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nsligatureattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLinkAttributeName": {
      "abstract": [
        {
          "text": "The link for the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSLinkAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLinkAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLinkAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nslinkattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSObliquenessAttributeName": {
      "abstract": [
        {
          "text": "The obliqueness of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSObliquenessAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSObliquenessAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObliquenessAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nsobliquenessattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSParagraphStyleAttributeName": {
      "abstract": [
        {
          "text": "The paragraph style of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSParagraphStyleAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSParagraphStyleAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSParagraphStyleAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nsparagraphstyleattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSShadowAttributeName": {
      "abstract": [
        {
          "text": "The shadow of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSShadowAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSShadowAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSShadowAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nsshadowattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSStrikethroughColorAttributeName": {
      "abstract": [
        {
          "text": "The color of the strikethrough.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSStrikethroughColorAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSStrikethroughColorAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSStrikethroughColorAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nsstrikethroughcolorattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSStrikethroughStyleAttributeName": {
      "abstract": [
        {
          "text": "The strikethrough style of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSStrikethroughStyleAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSStrikethroughStyleAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSStrikethroughStyleAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nsstrikethroughstyleattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSStrokeColorAttributeName": {
      "abstract": [
        {
          "text": "The color of the stroke.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSStrokeColorAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSStrokeColorAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSStrokeColorAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nsstrokecolorattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSStrokeWidthAttributeName": {
      "abstract": [
        {
          "text": "The width of the stroke.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSStrokeWidthAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSStrokeWidthAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSStrokeWidthAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nsstrokewidthattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextEffectAttributeName": {
      "abstract": [
        {
          "text": "An attribute that applies a text effect to the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextEffectAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextEffectAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextEffectAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nstexteffectattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextEffectStyle": {
      "abstract": [
        {
          "text": "Constants for the type of effect to apply to the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextEffectStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextEffectStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextEffectStyle",
      "type": "topic",
      "url": "/documentation/uikit/nstexteffectstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextHighlightColorScheme": {
      "abstract": [
        {
          "text": "Constants that specify the highlight color to use with the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextHighlightColorScheme"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextHighlightColorScheme",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextHighlightColorScheme",
      "type": "topic",
      "url": "/documentation/uikit/nstexthighlightcolorscheme"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextHighlightColorSchemeAttributeName": {
      "abstract": [
        {
          "text": "The custom highlight color to apply to the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextHighlightColorSchemeAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextHighlightColorSchemeAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextHighlightColorSchemeAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nstexthighlightcolorschemeattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextHighlightStyle": {
      "abstract": [
        {
          "text": "Constants that specify the type of highlight to apply to text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextHighlightStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextHighlightStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextHighlightStyle",
      "type": "topic",
      "url": "/documentation/uikit/nstexthighlightstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextHighlightStyleAttributeName": {
      "abstract": [
        {
          "text": "An attribute that adds a highlight color to the text to emphasize it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTextHighlightStyleAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextHighlightStyleAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTextHighlightStyleAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nstexthighlightstyleattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTrackingAttributeName": {
      "abstract": [
        {
          "text": "The amount to modify the default tracking.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSTrackingAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTrackingAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTrackingAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nstrackingattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSUnderlineColorAttributeName": {
      "abstract": [
        {
          "text": "The color of the underline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSUnderlineColorAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSUnderlineColorAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUnderlineColorAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nsunderlinecolorattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle": {
      "abstract": [
        {
          "text": "Constants for the underline style and strikethrough style attribute keys.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUnderlineStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUnderlineStyle"
        }
      ],
      "role": "symbol",
      "title": "NSUnderlineStyle",
      "type": "topic",
      "url": "/documentation/uikit/nsunderlinestyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyleAttributeName": {
      "abstract": [
        {
          "text": "The underline style of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSUnderlineStyleAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyleAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUnderlineStyleAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nsunderlinestyleattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSVerticalGlyphFormAttributeName": {
      "abstract": [
        {
          "text": "The vertical glyph form of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSVerticalGlyphFormAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSVerticalGlyphFormAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSVerticalGlyphFormAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nsverticalglyphformattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSWritingDirectionAttributeName": {
      "abstract": [
        {
          "text": "The writing direction of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSWritingDirectionAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSWritingDirectionAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSWritingDirectionAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/nswritingdirectionattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSWritingDirectionFormatType": {
      "abstract": [
        {
          "text": "Constants for the writing direction attribute key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWritingDirectionFormatType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSWritingDirectionFormatType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingDirectionFormatType"
        }
      ],
      "role": "symbol",
      "title": "NSWritingDirectionFormatType",
      "type": "topic",
      "url": "/documentation/uikit/nswritingdirectionformattype"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeAnnouncementPriority": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIAccessibilitySpeechAttributeAnnouncementPriority"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeAnnouncementPriority",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAccessibilitySpeechAttributeAnnouncementPriority",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityspeechattributeannouncementpriority"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeIPANotation": {
      "abstract": [
        {
          "text": "A key that indicates the pronunciation of a specific word or phrase, such as a proper name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIAccessibilitySpeechAttributeIPANotation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeIPANotation",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAccessibilitySpeechAttributeIPANotation",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityspeechattributeipanotation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeLanguage": {
      "abstract": [
        {
          "text": "A key that indicates the language to use when speaking a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIAccessibilitySpeechAttributeLanguage"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeLanguage",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAccessibilitySpeechAttributeLanguage",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityspeechattributelanguage"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributePitch": {
      "abstract": [
        {
          "text": "A key that indicates the pitch to apply to spoken content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIAccessibilitySpeechAttributePitch"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributePitch",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAccessibilitySpeechAttributePitch",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityspeechattributepitch"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributePunctuation": {
      "abstract": [
        {
          "text": "A key that indicates whether to speak punctuation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIAccessibilitySpeechAttributePunctuation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributePunctuation",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAccessibilitySpeechAttributePunctuation",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityspeechattributepunctuation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeQueueAnnouncement": {
      "abstract": [
        {
          "text": "A key that indicates whether to queue an announcement behind existing speech or to interrupt it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIAccessibilitySpeechAttributeQueueAnnouncement"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeQueueAnnouncement",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAccessibilitySpeechAttributeQueueAnnouncement",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityspeechattributequeueannouncement"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeSpellOut": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIAccessibilitySpeechAttributeSpellOut"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeSpellOut",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAccessibilitySpeechAttributeSpellOut",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityspeechattributespellout"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTextAttributeContext": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityTextAttributeContext"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTextAttributeContext",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAccessibilityTextAttributeContext",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitytextattributecontext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTextAttributeCustom": {
      "abstract": [
        {
          "text": "A key for specifying custom attributes to apply to the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityTextAttributeCustom"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTextAttributeCustom",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAccessibilityTextAttributeCustom",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitytextattributecustom"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTextAttributeHeadingLevel": {
      "abstract": [
        {
          "text": "A key for specifying the heading level of the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityTextAttributeHeadingLevel"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTextAttributeHeadingLevel",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAccessibilityTextAttributeHeadingLevel",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitytextattributeheadinglevel"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextItemTagAttributeName": {
      "abstract": [
        {
          "text": "The name of a custom tag associated with a text item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextItemTagAttributeName"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextItemTagAttributeName",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextItemTagAttributeName",
      "type": "topic",
      "url": "/documentation/uikit/uitextitemtagattributename"
    },
    "doc://com.apple.uikit/documentation/UIKit/textkit": {
      "abstract": [
        {
          "text": "Manage text storage and perform custom layout of text-based content in your app’s views.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/textkit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TextKit",
      "type": "topic",
      "url": "/documentation/uikit/textkit"
    },
    "doc://com.apple.uikit/documentation/UIKit/textkit-string-attributes": {
      "abstract": [
        {
          "text": "UIKit-specific keys and values for displaying text and managing documents.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/textkit-string-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "TextKit string attributes",
      "type": "topic",
      "url": "/documentation/uikit/textkit-string-attributes"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-text-content-attributes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSTextHighlightStyle",
        "doc://com.apple.uikit/documentation/UIKit/NSTextHighlightColorScheme",
        "doc://com.apple.uikit/documentation/UIKit/NSTextEffectStyle",
        "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyle",
        "doc://com.apple.uikit/documentation/UIKit/NSWritingDirectionFormatType"
      ],
      "title": "Getting text content attributes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-rendering-attribute-keys",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSBackgroundColorAttributeName",
        "doc://com.apple.uikit/documentation/UIKit/NSBaselineOffsetAttributeName",
        "doc://com.apple.uikit/documentation/UIKit/NSFontAttributeName",
        "doc://com.apple.uikit/documentation/UIKit/NSForegroundColorAttributeName",
        "doc://com.apple.uikit/documentation/UIKit/NSKernAttributeName",
        "doc://com.apple.uikit/documentation/UIKit/NSLigatureAttributeName",
        "doc://com.apple.uikit/documentation/UIKit/NSParagraphStyleAttributeName",
        "doc://com.apple.uikit/documentation/UIKit/NSStrikethroughColorAttributeName",
        "doc://com.apple.uikit/documentation/UIKit/NSStrikethroughStyleAttributeName",
        "doc://com.apple.uikit/documentation/UIKit/NSStrokeColorAttributeName",
        "doc://com.apple.uikit/documentation/UIKit/NSStrokeWidthAttributeName",
        "doc://com.apple.uikit/documentation/UIKit/NSTrackingAttributeName",
        "doc://com.apple.uikit/documentation/UIKit/NSUnderlineColorAttributeName",
        "doc://com.apple.uikit/documentation/UIKit/NSUnderlineStyleAttributeName",
        "doc://com.apple.uikit/documentation/UIKit/NSWritingDirectionAttributeName"
      ],
      "title": "Getting rendering attribute keys"
    },
    {
      "anchor": "Getting-text-attribute-keys",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSLinkAttributeName",
        "doc://com.apple.uikit/documentation/UIKit/NSShadowAttributeName",
        "doc://com.apple.uikit/documentation/UIKit/NSTextEffectAttributeName",
        "doc://com.apple.uikit/documentation/UIKit/NSTextHighlightColorSchemeAttributeName",
        "doc://com.apple.uikit/documentation/UIKit/NSTextHighlightStyleAttributeName",
        "doc://com.apple.uikit/documentation/UIKit/UITextItemTagAttributeName"
      ],
      "title": "Getting text attribute keys"
    },
    {
      "anchor": "Getting-attachment-attribute-keys",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSAdaptiveImageGlyphAttributeName",
        "doc://com.apple.uikit/documentation/UIKit/NSAttachmentAttributeName"
      ],
      "title": "Getting attachment attribute keys"
    },
    {
      "anchor": "Getting-accessibility-attribute-keys",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeAnnouncementPriority",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeIPANotation",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeLanguage",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributePitch",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributePunctuation",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeQueueAnnouncement",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeSpellOut",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTextAttributeCustom",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTextAttributeHeadingLevel",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTextAttributeContext"
      ],
      "title": "Getting accessibility attribute keys"
    },
    {
      "anchor": "Deprecated-keys",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSExpansionAttributeName",
        "doc://com.apple.uikit/documentation/UIKit/NSObliquenessAttributeName",
        "doc://com.apple.uikit/documentation/UIKit/NSVerticalGlyphFormAttributeName"
      ],
      "title": "Deprecated keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSWritingDirectionFormatType/title",
          "value": "NSWritingDirectionFormatType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSWritingDirectionFormatType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingDirectionFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSWritingDirectionFormatType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingDirectionFormatType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSUnderlineStyle/title",
          "value": "NSUnderlineStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSUnderlineStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnderlineStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSUnderlineStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUnderlineStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/textkit-string-attribute-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
