{
  "abstract": [
    {
      "text": "Provide a space for controls under a window’s title bar and above your custom content.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/mac-catalyst"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/toolbar"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Toolbar"
  },
  "references": {
    "doc://com.apple.documentation/documentation/AppKit/NSCloudSharingValidation": {
      "abstract": [
        {
          "text": "A protocol that a Cloud-sharing toolbar item uses to get validation of an item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCloudSharingValidation"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSCloudSharingValidation",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCloudSharingValidation",
      "type": "topic",
      "url": "/documentation/AppKit/NSCloudSharingValidation"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSMenuToolbarItem": {
      "abstract": [
        {
          "text": "A control that presents a menu in a window’s toolbar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSMenuToolbarItem"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSMenuToolbarItem",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMenuToolbarItem",
      "type": "topic",
      "url": "/documentation/AppKit/NSMenuToolbarItem"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSSearchToolbarItem": {
      "abstract": [
        {
          "text": "A toolbar item that contains a search field optimized for performing text-based searches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSearchToolbarItem"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSSearchToolbarItem",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSearchToolbarItem",
      "type": "topic",
      "url": "/documentation/AppKit/NSSearchToolbarItem"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSToolbar": {
      "abstract": [
        {
          "text": "An object that manages the space above your app’s custom content and either below or integrated with the window’s title bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSToolbar"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSToolbar",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSToolbar",
      "type": "topic",
      "url": "/documentation/AppKit/NSToolbar"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSToolbarItem": {
      "abstract": [
        {
          "text": "A single item that appears in a window’s toolbar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSToolbarItem"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSToolbarItem",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSToolbarItem",
      "type": "topic",
      "url": "/documentation/AppKit/NSToolbarItem"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSToolbarItemGroup": {
      "abstract": [
        {
          "text": "A group of subitems in a toolbar item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSToolbarItemGroup"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSToolbarItemGroup",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSToolbarItemGroup",
      "type": "topic",
      "url": "/documentation/AppKit/NSToolbarItemGroup"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSToolbarItemGroup/ControlRepresentation-swift.enum": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ControlRepresentation"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSToolbarItemGroup/ControlRepresentation-swift.enum",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSToolbarItemGroup.ControlRepresentation",
      "type": "topic",
      "url": "/documentation/AppKit/NSToolbarItemGroup/ControlRepresentation-swift.enum"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSToolbarItemGroup/SelectionMode-swift.enum": {
      "abstract": [
        {
          "text": "A value that indicates how a grouped toolbar item selects its subitems.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SelectionMode"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSToolbarItemGroup/SelectionMode-swift.enum",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSToolbarItemGroup.SelectionMode",
      "type": "topic",
      "url": "/documentation/AppKit/NSToolbarItemGroup/SelectionMode-swift.enum"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSToolbarItemValidation": {
      "abstract": [
        {
          "text": "Validation of a toolbar item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSToolbarItemValidation"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSToolbarItemValidation",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSToolbarItemValidation",
      "type": "topic",
      "url": "/documentation/AppKit/NSToolbarItemValidation"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSTrackingSeparatorToolbarItem": {
      "abstract": [
        {
          "text": "A toolbar separator that aligns with the vertical split view in the same window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTrackingSeparatorToolbarItem"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSTrackingSeparatorToolbarItem",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTrackingSeparatorToolbarItem",
      "type": "topic",
      "url": "/documentation/AppKit/NSTrackingSeparatorToolbarItem"
    },
    "doc://com.apple.documentation/documentation/AppKit/integrating-a-toolbar-and-touch-bar-into-your-app": {
      "abstract": [
        {
          "text": "Provide users quick access to your app’s features from a toolbar and corresponding Touch Bar.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/integrating-a-toolbar-and-touch-bar-into-your-app",
      "kind": "article",
      "role": "sampleCode",
      "title": "Integrating a Toolbar and Touch Bar into Your App",
      "type": "topic",
      "url": "/documentation/AppKit/integrating-a-toolbar-and-touch-bar-into-your-app"
    },
    "doc://com.apple.documentation/documentation/AppKit/touch-bar": {
      "abstract": [
        {
          "text": "Display interactive content and controls in the Touch Bar.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/touch-bar",
      "kind": "article",
      "role": "article",
      "title": "Touch Bar",
      "type": "topic",
      "url": "/documentation/AppKit/touch-bar"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSToolbarItemIdentifier": {
      "abstract": [
        {
          "text": "UIKit-specific constants for the standard toolbar items that the system provides.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSToolbarItemIdentifier",
      "kind": "article",
      "role": "collectionGroup",
      "title": "NSToolbarItemIdentifier",
      "type": "topic",
      "url": "/documentation/uikit/nstoolbaritemidentifier"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSUIViewToolbarItem": {
      "abstract": [
        {
          "text": "An item in a window’s toolbar that hosts a custom UIKit view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSUIViewToolbarItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSUIViewToolbarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSUIViewToolbarItem"
        }
      ],
      "role": "symbol",
      "title": "NSUIViewToolbarItem",
      "type": "topic",
      "url": "/documentation/uikit/nsuiviewtoolbaritem"
    },
    "doc://com.apple.uikit/documentation/UIKit/building-and-improving-your-app-with-mac-catalyst": {
      "abstract": [
        {
          "text": "Improve your iPadOS app with Mac Catalyst by supporting native controls, multiple windows, sharing, printing, menus and keyboard shortcuts.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/building-and-improving-your-app-with-mac-catalyst",
      "kind": "article",
      "role": "sampleCode",
      "title": "Building and improving your app with Mac Catalyst",
      "type": "topic",
      "url": "/documentation/uikit/building-and-improving-your-app-with-mac-catalyst"
    },
    "doc://com.apple.uikit/documentation/UIKit/displaying-a-checkbox-in-your-mac-app-built-with-mac-catalyst": {
      "abstract": [
        {
          "text": "Present a switch control as a Mac-style checkbox when your app runs in the Mac user interface idiom.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/displaying-a-checkbox-in-your-mac-app-built-with-mac-catalyst",
      "kind": "article",
      "role": "article",
      "title": "Displaying a checkbox in your Mac app built with Mac Catalyst",
      "type": "topic",
      "url": "/documentation/uikit/displaying-a-checkbox-in-your-mac-app-built-with-mac-catalyst"
    },
    "doc://com.apple.uikit/documentation/UIKit/mac-catalyst": {
      "abstract": [
        {
          "text": "Create a version of your iPad app that users can run on a Mac device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/mac-catalyst",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Mac Catalyst",
      "type": "topic",
      "url": "/documentation/uikit/mac-catalyst"
    },
    "doc://com.apple.uikit/documentation/UIKit/removing-the-title-bar-in-your-mac-app-built-with-mac-catalyst": {
      "abstract": [
        {
          "text": "Display content that fills the entire height of a window by removing the title bar.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/removing-the-title-bar-in-your-mac-app-built-with-mac-catalyst",
      "kind": "article",
      "role": "article",
      "title": "Removing the title bar in your Mac app built with Mac Catalyst",
      "type": "topic",
      "url": "/documentation/uikit/removing-the-title-bar-in-your-mac-app-built-with-mac-catalyst"
    },
    "doc://com.apple.uikit/documentation/UIKit/uikit-catalog-creating-and-customizing-views-and-controls": {
      "abstract": [
        {
          "text": "Customize your app’s user interface with views and controls.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/uikit-catalog-creating-and-customizing-views-and-controls",
      "kind": "article",
      "role": "sampleCode",
      "title": "UIKit Catalog: Creating and customizing views and controls",
      "type": "topic",
      "url": "/documentation/uikit/uikit-catalog-creating-and-customizing-views-and-controls"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "User-interface",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/uikit-catalog-creating-and-customizing-views-and-controls",
        "doc://com.apple.uikit/documentation/UIKit/building-and-improving-your-app-with-mac-catalyst",
        "doc://com.apple.uikit/documentation/UIKit/displaying-a-checkbox-in-your-mac-app-built-with-mac-catalyst",
        "doc://com.apple.uikit/documentation/UIKit/removing-the-title-bar-in-your-mac-app-built-with-mac-catalyst",
        "doc://com.apple.documentation/documentation/AppKit/touch-bar"
      ],
      "title": "User interface"
    }
  ],
  "topicSections": [
    {
      "anchor": "View",
      "identifiers": [
        "doc://com.apple.documentation/documentation/AppKit/integrating-a-toolbar-and-touch-bar-into-your-app",
        "doc://com.apple.documentation/documentation/AppKit/NSToolbar",
        "doc://com.apple.documentation/documentation/AppKit/NSToolbarItemValidation"
      ],
      "title": "View"
    },
    {
      "anchor": "Items",
      "identifiers": [
        "doc://com.apple.documentation/documentation/AppKit/NSToolbarItem",
        "doc://com.apple.documentation/documentation/AppKit/NSToolbarItemGroup",
        "doc://com.apple.documentation/documentation/AppKit/NSToolbarItemGroup/ControlRepresentation-swift.enum",
        "doc://com.apple.documentation/documentation/AppKit/NSToolbarItemGroup/SelectionMode-swift.enum",
        "doc://com.apple.documentation/documentation/AppKit/NSMenuToolbarItem",
        "doc://com.apple.documentation/documentation/AppKit/NSSearchToolbarItem",
        "doc://com.apple.documentation/documentation/AppKit/NSTrackingSeparatorToolbarItem",
        "doc://com.apple.uikit/documentation/UIKit/NSUIViewToolbarItem"
      ],
      "title": "Items"
    },
    {
      "anchor": "Item-validation",
      "identifiers": [
        "doc://com.apple.documentation/documentation/AppKit/NSCloudSharingValidation"
      ],
      "title": "Item validation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "View",
              "identifiers": [
                "doc://com.apple.documentation/documentation/AppKit/integrating-a-toolbar-and-touch-bar-into-your-app",
                "doc://com.apple.documentation/documentation/AppKit/NSToolbar",
                "doc://com.apple.documentation/documentation/AppKit/NSToolbarItemValidation"
              ],
              "title": "View"
            },
            {
              "anchor": "Items",
              "identifiers": [
                "doc://com.apple.documentation/documentation/AppKit/NSToolbarItem",
                "doc://com.apple.uikit/documentation/UIKit/NSToolbarItemIdentifier",
                "doc://com.apple.documentation/documentation/AppKit/NSToolbarItemGroup",
                "doc://com.apple.documentation/documentation/AppKit/NSToolbarItemGroup/ControlRepresentation-swift.enum",
                "doc://com.apple.documentation/documentation/AppKit/NSToolbarItemGroup/SelectionMode-swift.enum",
                "doc://com.apple.documentation/documentation/AppKit/NSMenuToolbarItem",
                "doc://com.apple.documentation/documentation/AppKit/NSSearchToolbarItem",
                "doc://com.apple.documentation/documentation/AppKit/NSTrackingSeparatorToolbarItem",
                "doc://com.apple.uikit/documentation/UIKit/NSUIViewToolbarItem"
              ],
              "title": "Items"
            },
            {
              "anchor": "Item-validation",
              "identifiers": [
                "doc://com.apple.documentation/documentation/AppKit/NSCloudSharingValidation"
              ],
              "title": "Item validation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "User-interface",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/uikit-catalog-creating-and-customizing-views-and-controls",
                "doc://com.apple.uikit/documentation/UIKit/building-and-improving-your-app-with-mac-catalyst",
                "doc://com.apple.uikit/documentation/UIKit/displaying-a-checkbox-in-your-mac-app-built-with-mac-catalyst",
                "doc://com.apple.uikit/documentation/UIKit/removing-the-title-bar-in-your-mac-app-built-with-mac-catalyst",
                "doc://com.apple.documentation/documentation/AppKit/touch-bar"
              ],
              "title": "User interface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSToolbarItemValidation/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSToolbarItemValidation"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSTrackingSeparatorToolbarItem/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSTrackingSeparatorToolbarItem"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSToolbarItem",
              "text": "NSToolbarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSSearchToolbarItem/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSSearchToolbarItem"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSToolbarItem",
              "text": "NSToolbarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSMenuToolbarItem/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSMenuToolbarItem"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSToolbarItem",
              "text": "NSToolbarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSToolbarItemGroup~1SelectionMode-swift.enum/title",
          "value": "NSToolbarItemGroupSelectionMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSToolbarItemGroup~1SelectionMode-swift.enum/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSToolbarItemGroupSelectionMode"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSInteger",
              "text": "NSInteger"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSCloudSharingValidation/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSCloudSharingValidation"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSToolbarItemGroup~1ControlRepresentation-swift.enum/title",
          "value": "NSToolbarItemGroupControlRepresentation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSToolbarItemGroup~1ControlRepresentation-swift.enum/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSToolbarItemGroupControlRepresentation"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSInteger",
              "text": "NSInteger"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSToolbarItemGroup/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSToolbarItemGroup"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSToolbarItem",
              "text": "NSToolbarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSUIViewToolbarItem/title",
          "value": "NSUIViewToolbarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSUIViewToolbarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUIViewToolbarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSUIViewToolbarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSUIViewToolbarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSToolbarItem/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSToolbarItem"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSToolbar/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSToolbar"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/toolbar"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/toolbar"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
