{
  "abstract": [
    {
      "text": "Choose colors for UI elements such as labels, text, backgrounds, and links.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/drawing",
        "doc://com.apple.uikit/documentation/UIKit/UIColor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/ui-element-colors"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "UI element colors"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "UIKit provides color objects for the foreground and background colors of your app’s UI elements. The names of these color objects reflect their intended use, rather than specific color values.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Except where noted, the color objects adapt automatically to Dark Mode changes when you use the provided ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIColor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. If you retrieve the color values, either directly or using another type such as ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/coregraphics/cgcolor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", you must handle Dark Mode changes yourself. For more information about supporting Dark Mode, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/supporting-dark-mode-in-your-interface",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/coregraphics/cgcolor": {
      "abstract": [
        {
          "text": "A set of components that define a color, with a color space specifying how to interpret them.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CGColor"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/coregraphics/cgcolor",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGColor",
      "type": "topic",
      "url": "/documentation/coregraphics/cgcolor"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIColor": {
      "abstract": [
        {
          "text": "An object that stores color data and sometimes opacity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIColor"
        }
      ],
      "role": "symbol",
      "title": "UIColor",
      "type": "topic",
      "url": "/documentation/uikit/uicolor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIColor/darkText": {
      "abstract": [
        {
          "text": "The nonadaptable system color for text on a light background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "darkText"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIColor/darkText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "darkTextColor"
        }
      ],
      "role": "symbol",
      "title": "darkText",
      "type": "topic",
      "url": "/documentation/uikit/uicolor/darktext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIColor/groupTableViewBackground": {
      "abstract": [
        {
          "text": "The system color to use for the background of a grouped table.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "groupTableViewBackground"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIColor/groupTableViewBackground",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "groupTableViewBackgroundColor"
        }
      ],
      "role": "symbol",
      "title": "groupTableViewBackground",
      "type": "topic",
      "url": "/documentation/uikit/uicolor/grouptableviewbackground"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIColor/label": {
      "abstract": [
        {
          "text": "The color for text labels that contain primary content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "label"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIColor/label",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "labelColor"
        }
      ],
      "role": "symbol",
      "title": "label",
      "type": "topic",
      "url": "/documentation/uikit/uicolor/label"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIColor/lightText": {
      "abstract": [
        {
          "text": "The nonadaptable system color for text on a dark background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lightText"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIColor/lightText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "lightTextColor"
        }
      ],
      "role": "symbol",
      "title": "lightText",
      "type": "topic",
      "url": "/documentation/uikit/uicolor/lighttext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIColor/link": {
      "abstract": [
        {
          "text": "The specified color for links.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "link"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIColor/link",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "linkColor"
        }
      ],
      "role": "symbol",
      "title": "link",
      "type": "topic",
      "url": "/documentation/uikit/uicolor/link"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIColor/opaqueSeparator": {
      "abstract": [
        {
          "text": "The color for borders or divider lines that hides any underlying content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "opaqueSeparator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIColor/opaqueSeparator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "opaqueSeparatorColor"
        }
      ],
      "role": "symbol",
      "title": "opaqueSeparator",
      "type": "topic",
      "url": "/documentation/uikit/uicolor/opaqueseparator"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIColor/placeholderText": {
      "abstract": [
        {
          "text": "The color for placeholder text in controls or text views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "placeholderText"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIColor/placeholderText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "placeholderTextColor"
        }
      ],
      "role": "symbol",
      "title": "placeholderText",
      "type": "topic",
      "url": "/documentation/uikit/uicolor/placeholdertext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIColor/quaternaryLabel": {
      "abstract": [
        {
          "text": "The color for text labels that contain quaternary content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quaternaryLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIColor/quaternaryLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "quaternaryLabelColor"
        }
      ],
      "role": "symbol",
      "title": "quaternaryLabel",
      "type": "topic",
      "url": "/documentation/uikit/uicolor/quaternarylabel"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIColor/quaternarySystemFill": {
      "abstract": [
        {
          "text": "An overlay fill color for large areas that contain complex content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quaternarySystemFill"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIColor/quaternarySystemFill",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "quaternarySystemFillColor"
        }
      ],
      "role": "symbol",
      "title": "quaternarySystemFill",
      "type": "topic",
      "url": "/documentation/uikit/uicolor/quaternarysystemfill"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIColor/scrollViewTexturedBackgroundColor": {
      "abstract": [
        {
          "text": "The system pattern color to use for the area behind scrollable content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "scrollViewTexturedBackgroundColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIColor/scrollViewTexturedBackgroundColor",
      "kind": "symbol",
      "role": "symbol",
      "title": "scrollViewTexturedBackgroundColor",
      "type": "topic",
      "url": "/documentation/uikit/uicolor/scrollviewtexturedbackgroundcolor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIColor/secondaryLabel": {
      "abstract": [
        {
          "text": "The color for text labels that contain secondary content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "secondaryLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIColor/secondaryLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "secondaryLabelColor"
        }
      ],
      "role": "symbol",
      "title": "secondaryLabel",
      "type": "topic",
      "url": "/documentation/uikit/uicolor/secondarylabel"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIColor/secondarySystemBackground": {
      "abstract": [
        {
          "text": "The color for content layered on top of the main background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "secondarySystemBackground"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIColor/secondarySystemBackground",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "secondarySystemBackgroundColor"
        }
      ],
      "role": "symbol",
      "title": "secondarySystemBackground",
      "type": "topic",
      "url": "/documentation/uikit/uicolor/secondarysystembackground"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIColor/secondarySystemFill": {
      "abstract": [
        {
          "text": "An overlay fill color for medium-size shapes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "secondarySystemFill"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIColor/secondarySystemFill",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "secondarySystemFillColor"
        }
      ],
      "role": "symbol",
      "title": "secondarySystemFill",
      "type": "topic",
      "url": "/documentation/uikit/uicolor/secondarysystemfill"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIColor/secondarySystemGroupedBackground": {
      "abstract": [
        {
          "text": "The color for content layered on top of the main background of your grouped interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "secondarySystemGroupedBackground"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIColor/secondarySystemGroupedBackground",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "secondarySystemGroupedBackgroundColor"
        }
      ],
      "role": "symbol",
      "title": "secondarySystemGroupedBackground",
      "type": "topic",
      "url": "/documentation/uikit/uicolor/secondarysystemgroupedbackground"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIColor/separator": {
      "abstract": [
        {
          "text": "The color for thin borders or divider lines that allows some underlying content to be visible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "separator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIColor/separator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "separatorColor"
        }
      ],
      "role": "symbol",
      "title": "separator",
      "type": "topic",
      "url": "/documentation/uikit/uicolor/separator"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIColor/systemBackground": {
      "abstract": [
        {
          "text": "The color for the main background of your interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemBackground"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIColor/systemBackground",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "systemBackgroundColor"
        }
      ],
      "role": "symbol",
      "title": "systemBackground",
      "type": "topic",
      "url": "/documentation/uikit/uicolor/systembackground"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIColor/systemFill": {
      "abstract": [
        {
          "text": "An overlay fill color for thin and small shapes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemFill"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIColor/systemFill",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "systemFillColor"
        }
      ],
      "role": "symbol",
      "title": "systemFill",
      "type": "topic",
      "url": "/documentation/uikit/uicolor/systemfill"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIColor/systemGroupedBackground": {
      "abstract": [
        {
          "text": "The color for the main background of your grouped interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemGroupedBackground"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIColor/systemGroupedBackground",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "systemGroupedBackgroundColor"
        }
      ],
      "role": "symbol",
      "title": "systemGroupedBackground",
      "type": "topic",
      "url": "/documentation/uikit/uicolor/systemgroupedbackground"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIColor/tertiaryLabel": {
      "abstract": [
        {
          "text": "The color for text labels that contain tertiary content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tertiaryLabel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIColor/tertiaryLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tertiaryLabelColor"
        }
      ],
      "role": "symbol",
      "title": "tertiaryLabel",
      "type": "topic",
      "url": "/documentation/uikit/uicolor/tertiarylabel"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIColor/tertiarySystemBackground": {
      "abstract": [
        {
          "text": "The color for content layered on top of secondary backgrounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tertiarySystemBackground"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIColor/tertiarySystemBackground",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tertiarySystemBackgroundColor"
        }
      ],
      "role": "symbol",
      "title": "tertiarySystemBackground",
      "type": "topic",
      "url": "/documentation/uikit/uicolor/tertiarysystembackground"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIColor/tertiarySystemFill": {
      "abstract": [
        {
          "text": "An overlay fill color for large shapes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tertiarySystemFill"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIColor/tertiarySystemFill",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tertiarySystemFillColor"
        }
      ],
      "role": "symbol",
      "title": "tertiarySystemFill",
      "type": "topic",
      "url": "/documentation/uikit/uicolor/tertiarysystemfill"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIColor/tertiarySystemGroupedBackground": {
      "abstract": [
        {
          "text": "The color for content layered on top of secondary backgrounds of your grouped interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tertiarySystemGroupedBackground"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIColor/tertiarySystemGroupedBackground",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tertiarySystemGroupedBackgroundColor"
        }
      ],
      "role": "symbol",
      "title": "tertiarySystemGroupedBackground",
      "type": "topic",
      "url": "/documentation/uikit/uicolor/tertiarysystemgroupedbackground"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIColor/tintColor": {
      "abstract": [
        {
          "text": "A color value that resolves at runtime based on the current tint color of the app or trait hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tintColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIColor/tintColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tintColor"
        }
      ],
      "role": "symbol",
      "title": "tintColor",
      "type": "topic",
      "url": "/documentation/uikit/uicolor/tintcolor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIColor/underPageBackgroundColor": {
      "abstract": [
        {
          "text": "The system pattern color to use for the background of a page.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "underPageBackgroundColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIColor/underPageBackgroundColor",
      "kind": "symbol",
      "role": "symbol",
      "title": "underPageBackgroundColor",
      "type": "topic",
      "url": "/documentation/uikit/uicolor/underpagebackgroundcolor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIColor/viewFlipsideBackgroundColor": {
      "abstract": [
        {
          "text": "The system color to use for the back side of a view when it’s flipped.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "viewFlipsideBackgroundColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIColor/viewFlipsideBackgroundColor",
      "kind": "symbol",
      "role": "symbol",
      "title": "viewFlipsideBackgroundColor",
      "type": "topic",
      "url": "/documentation/uikit/uicolor/viewflipsidebackgroundcolor"
    },
    "doc://com.apple.uikit/documentation/UIKit/color-creation": {
      "abstract": [
        {
          "text": "Load colors from asset catalogs and create colors from raw component values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/color-creation",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Color creation",
      "type": "topic",
      "url": "/documentation/uikit/color-creation"
    },
    "doc://com.apple.uikit/documentation/UIKit/drawing": {
      "abstract": [
        {
          "text": "Configure your app’s drawing environment using colors, renderers, draw paths, strings, and shadows.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/drawing",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Drawing",
      "type": "topic",
      "url": "/documentation/uikit/drawing"
    },
    "doc://com.apple.uikit/documentation/UIKit/standard-colors": {
      "abstract": [
        {
          "text": "Define standard color objects for specific shades, such as red, blue, green, black, white, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/standard-colors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Standard colors",
      "type": "topic",
      "url": "/documentation/uikit/standard-colors"
    },
    "doc://com.apple.uikit/documentation/UIKit/supporting-dark-mode-in-your-interface": {
      "abstract": [
        {
          "text": "Update colors, images, and behaviors so that your app adapts automatically when Dark Mode is active.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/supporting-dark-mode-in-your-interface",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Supporting Dark Mode in Your Interface",
      "type": "topic",
      "url": "/documentation/uikit/supporting-dark-mode-in-your-interface"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-existing-colors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/standard-colors",
        "doc://com.apple.uikit/documentation/UIKit/color-creation"
      ],
      "title": "Getting existing colors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Label-colors",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIColor/label",
        "doc://com.apple.uikit/documentation/UIKit/UIColor/secondaryLabel",
        "doc://com.apple.uikit/documentation/UIKit/UIColor/tertiaryLabel",
        "doc://com.apple.uikit/documentation/UIKit/UIColor/quaternaryLabel"
      ],
      "title": "Label colors"
    },
    {
      "anchor": "Fill-colors",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIColor/systemFill",
        "doc://com.apple.uikit/documentation/UIKit/UIColor/secondarySystemFill",
        "doc://com.apple.uikit/documentation/UIKit/UIColor/tertiarySystemFill",
        "doc://com.apple.uikit/documentation/UIKit/UIColor/quaternarySystemFill"
      ],
      "title": "Fill colors"
    },
    {
      "anchor": "Text-colors",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIColor/placeholderText"
      ],
      "title": "Text colors"
    },
    {
      "anchor": "Tint-color",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIColor/tintColor"
      ],
      "title": "Tint color"
    },
    {
      "anchor": "Standard-content-background-colors",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIColor/systemBackground",
        "doc://com.apple.uikit/documentation/UIKit/UIColor/secondarySystemBackground",
        "doc://com.apple.uikit/documentation/UIKit/UIColor/tertiarySystemBackground"
      ],
      "title": "Standard content background colors"
    },
    {
      "anchor": "Grouped-content-background-colors",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIColor/systemGroupedBackground",
        "doc://com.apple.uikit/documentation/UIKit/UIColor/secondarySystemGroupedBackground",
        "doc://com.apple.uikit/documentation/UIKit/UIColor/tertiarySystemGroupedBackground"
      ],
      "title": "Grouped content background colors"
    },
    {
      "anchor": "Separator-colors",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIColor/separator",
        "doc://com.apple.uikit/documentation/UIKit/UIColor/opaqueSeparator"
      ],
      "title": "Separator colors"
    },
    {
      "anchor": "Link-color",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIColor/link"
      ],
      "title": "Link color"
    },
    {
      "anchor": "Nonadaptable-colors",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIColor/darkText",
        "doc://com.apple.uikit/documentation/UIKit/UIColor/lightText"
      ],
      "title": "Nonadaptable colors"
    },
    {
      "anchor": "Deprecated-colors",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIColor/groupTableViewBackground"
      ],
      "title": "Deprecated colors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Label-colors",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIColor/label",
                "doc://com.apple.uikit/documentation/UIKit/UIColor/secondaryLabel",
                "doc://com.apple.uikit/documentation/UIKit/UIColor/tertiaryLabel",
                "doc://com.apple.uikit/documentation/UIKit/UIColor/quaternaryLabel"
              ],
              "title": "Label colors"
            },
            {
              "anchor": "Fill-colors",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIColor/systemFill",
                "doc://com.apple.uikit/documentation/UIKit/UIColor/secondarySystemFill",
                "doc://com.apple.uikit/documentation/UIKit/UIColor/tertiarySystemFill",
                "doc://com.apple.uikit/documentation/UIKit/UIColor/quaternarySystemFill"
              ],
              "title": "Fill colors"
            },
            {
              "anchor": "Text-colors",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIColor/placeholderText"
              ],
              "title": "Text colors"
            },
            {
              "anchor": "Tint-color",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIColor/tintColor"
              ],
              "title": "Tint color"
            },
            {
              "anchor": "Standard-content-background-colors",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIColor/systemBackground",
                "doc://com.apple.uikit/documentation/UIKit/UIColor/secondarySystemBackground",
                "doc://com.apple.uikit/documentation/UIKit/UIColor/tertiarySystemBackground"
              ],
              "title": "Standard content background colors"
            },
            {
              "anchor": "Grouped-content-background-colors",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIColor/systemGroupedBackground",
                "doc://com.apple.uikit/documentation/UIKit/UIColor/secondarySystemGroupedBackground",
                "doc://com.apple.uikit/documentation/UIKit/UIColor/tertiarySystemGroupedBackground"
              ],
              "title": "Grouped content background colors"
            },
            {
              "anchor": "Separator-colors",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIColor/separator",
                "doc://com.apple.uikit/documentation/UIKit/UIColor/opaqueSeparator"
              ],
              "title": "Separator colors"
            },
            {
              "anchor": "Link-color",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIColor/link"
              ],
              "title": "Link color"
            },
            {
              "anchor": "Nonadaptable-colors",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIColor/darkText",
                "doc://com.apple.uikit/documentation/UIKit/UIColor/lightText"
              ],
              "title": "Nonadaptable colors"
            },
            {
              "anchor": "Deprecated-colors",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIColor/groupTableViewBackground",
                "doc://com.apple.uikit/documentation/UIKit/UIColor/scrollViewTexturedBackgroundColor",
                "doc://com.apple.uikit/documentation/UIKit/UIColor/underPageBackgroundColor",
                "doc://com.apple.uikit/documentation/UIKit/UIColor/viewFlipsideBackgroundColor"
              ],
              "title": "Deprecated colors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-existing-colors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/standard-colors",
                "doc://com.apple.uikit/documentation/UIKit/color-creation"
              ],
              "title": "Getting existing colors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemBackground/title",
          "value": "systemBackgroundColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemBackground/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "systemBackgroundColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1link/title",
          "value": "linkColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1link/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "linkColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1tertiarySystemFill/title",
          "value": "tertiarySystemFillColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1tertiarySystemFill/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tertiarySystemFillColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1tertiarySystemBackground/title",
          "value": "tertiarySystemBackgroundColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1tertiarySystemBackground/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tertiarySystemBackgroundColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1groupTableViewBackground/title",
          "value": "groupTableViewBackgroundColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1groupTableViewBackground/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "groupTableViewBackgroundColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1separator/title",
          "value": "separatorColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1separator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "separatorColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1quaternaryLabel/title",
          "value": "quaternaryLabelColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1quaternaryLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "quaternaryLabelColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1label/title",
          "value": "labelColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1label/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "labelColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor/title",
          "value": "UIColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1opaqueSeparator/title",
          "value": "opaqueSeparatorColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1opaqueSeparator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "opaqueSeparatorColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemFill/title",
          "value": "systemFillColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemFill/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "systemFillColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1darkText/title",
          "value": "darkTextColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1darkText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "darkTextColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1tertiarySystemGroupedBackground/title",
          "value": "tertiarySystemGroupedBackgroundColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1tertiarySystemGroupedBackground/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tertiarySystemGroupedBackgroundColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1secondaryLabel/title",
          "value": "secondaryLabelColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1secondaryLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "secondaryLabelColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1tintColor/title",
          "value": "tintColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1tintColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tintColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1secondarySystemFill/title",
          "value": "secondarySystemFillColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1secondarySystemFill/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "secondarySystemFillColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1secondarySystemBackground/title",
          "value": "secondarySystemBackgroundColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1secondarySystemBackground/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "secondarySystemBackgroundColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1secondarySystemGroupedBackground/title",
          "value": "secondarySystemGroupedBackgroundColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1secondarySystemGroupedBackground/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "secondarySystemGroupedBackgroundColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1tertiaryLabel/title",
          "value": "tertiaryLabelColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1tertiaryLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tertiaryLabelColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1coregraphics~1cgcolor/title",
          "value": "CGColorRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemGroupedBackground/title",
          "value": "systemGroupedBackgroundColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1systemGroupedBackground/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "systemGroupedBackgroundColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1lightText/title",
          "value": "lightTextColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1lightText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "lightTextColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1placeholderText/title",
          "value": "placeholderTextColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1placeholderText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "placeholderTextColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1quaternarySystemFill/title",
          "value": "quaternarySystemFillColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIColor~1quaternarySystemFill/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "quaternarySystemFillColor"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/ui-element-colors"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/ui-element-colors"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
