{
  "abstract": [
    {
      "text": "Constants that specify priorities for accessibility announcements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityPriority"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@UIAccessibilityPriority",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIAccessibilityPriority"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIAccessibilityPriority"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "UIAccessibilityPriority"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIAccessibilityPriority"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use these constants either with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/attributescopes/accessibilityattributes/4183580-accessibilityspeechannouncementp",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/attributedstring",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", or with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/4168159-accessibilityspeechannouncementp",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " (Swift) or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeAnnouncementPriority",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " (Objective-C) attributed key. For example, the following code shows how to create an announcement with a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityPriority/high",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " announcement priority:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let highPriorityAnnouncement = NSAttributedString(string: \"Camera active\", attributes:",
            "[NSAttributedString.Key.accessibilitySpeechAnnouncementPriority: UIAccessibilityPriority.high])"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/attributedstring": {
      "abstract": [
        {
          "text": "A value type for a string with associated attributes for portions of its text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "AttributedString"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/attributedstring",
      "kind": "symbol",
      "role": "symbol",
      "title": "AttributedString",
      "type": "topic",
      "url": "/documentation/foundation/attributedstring"
    },
    "doc://com.apple.documentation/documentation/foundation/attributescopes/accessibilityattributes/4183580-accessibilityspeechannouncementp": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "let "
        },
        {
          "kind": "identifier",
          "text": "accessibilitySpeechAnnouncementPriority"
        },
        {
          "kind": "text",
          "text": ": AttributeScopes.AccessibilityAttributes.AnnouncementPriorityAttribute"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/attributescopes/accessibilityattributes/4183580-accessibilityspeechannouncementp",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilitySpeechAnnouncementPriority",
      "type": "topic",
      "url": "/documentation/foundation/attributescopes/accessibilityattributes/4183580-accessibilityspeechannouncementp"
    },
    "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/1620188-accessibilityspeechlanguage": {
      "abstract": [
        {
          "text": "A key that indicates the language to use when speaking a string. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "accessibilitySpeechLanguage"
        },
        {
          "kind": "text",
          "text": ": NSAttributedString.Key"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/1620188-accessibilityspeechlanguage",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilitySpeechLanguage",
      "type": "topic",
      "url": "/documentation/foundation/nsattributedstring/key/1620188-accessibilityspeechlanguage"
    },
    "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/1620195-accessibilityspeechpitch": {
      "abstract": [
        {
          "text": "A key that indicates the pitch to apply to spoken content. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "accessibilitySpeechPitch"
        },
        {
          "kind": "text",
          "text": ": NSAttributedString.Key"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/1620195-accessibilityspeechpitch",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilitySpeechPitch",
      "type": "topic",
      "url": "/documentation/foundation/nsattributedstring/key/1620195-accessibilityspeechpitch"
    },
    "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/1620201-accessibilityspeechpunctuation": {
      "abstract": [
        {
          "text": "A key that indicates whether to speak punctuation. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "accessibilitySpeechPunctuation"
        },
        {
          "kind": "text",
          "text": ": NSAttributedString.Key"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/1620201-accessibilityspeechpunctuation",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilitySpeechPunctuation",
      "type": "topic",
      "url": "/documentation/foundation/nsattributedstring/key/1620201-accessibilityspeechpunctuation"
    },
    "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/2865770-accessibilityspeechqueueannounce": {
      "abstract": [
        {
          "text": "A key that indicates whether to queue an announcement behind existing speech or to interrupt it.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "accessibilitySpeechQueueAnnouncement"
        },
        {
          "kind": "text",
          "text": ": NSAttributedString.Key"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/2865770-accessibilityspeechqueueannounce",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilitySpeechQueueAnnouncement",
      "type": "topic",
      "url": "/documentation/foundation/nsattributedstring/key/2865770-accessibilityspeechqueueannounce"
    },
    "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/2890748-accessibilityspeechipanotation": {
      "abstract": [
        {
          "text": "A key that indicates the pronunciation of a specific word or phrase, such as a proper name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "accessibilitySpeechIPANotation"
        },
        {
          "kind": "text",
          "text": ": NSAttributedString.Key"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/2890748-accessibilityspeechipanotation",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilitySpeechIPANotation",
      "type": "topic",
      "url": "/documentation/foundation/nsattributedstring/key/2890748-accessibilityspeechipanotation"
    },
    "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/3333285-accessibilityspeechspellout": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "accessibilitySpeechSpellOut"
        },
        {
          "kind": "text",
          "text": ": NSAttributedString.Key"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/3333285-accessibilityspeechspellout",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilitySpeechSpellOut",
      "type": "topic",
      "url": "/documentation/foundation/nsattributedstring/key/3333285-accessibilityspeechspellout"
    },
    "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/4168159-accessibilityspeechannouncementp": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "static let "
        },
        {
          "kind": "identifier",
          "text": "accessibilitySpeechAnnouncementPriority"
        },
        {
          "kind": "text",
          "text": ": NSAttributedString.Key"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/4168159-accessibilityspeechannouncementp",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilitySpeechAnnouncementPriority",
      "type": "topic",
      "url": "/documentation/foundation/nsattributedstring/key/4168159-accessibilityspeechannouncementp"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityPriority": {
      "abstract": [
        {
          "text": "Constants that specify priorities for accessibility announcements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAccessibilityPriority"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityPriority",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityPriority"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityPriority",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitypriority"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityPriority/default": {
      "abstract": [
        {
          "text": "A default-priority announcement that interrupts existing speech, but is interruptible if a new speech utterance starts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityPriority",
          "text": "UIAccessibilityPriority"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityPriority/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityPriorityDefault"
        }
      ],
      "role": "symbol",
      "title": "default",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitypriority/default"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityPriority/high": {
      "abstract": [
        {
          "text": "A high-priority announcement that interrupts other speech and isn’t interruptible after it starts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "high"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityPriority",
          "text": "UIAccessibilityPriority"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityPriority/high",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityPriorityHigh"
        }
      ],
      "role": "symbol",
      "title": "high",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitypriority/high"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityPriority/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a priority structure with the specified raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityPriority/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitypriority/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityPriority/low": {
      "abstract": [
        {
          "text": "A low-priority announcement that the system queues and speaks after other speech utterances are complete.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "low"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityPriority",
          "text": "UIAccessibilityPriority"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityPriority/low",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityPriorityLow"
        }
      ],
      "role": "symbol",
      "title": "low",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitypriority/low"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeAnnouncementPriority": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIAccessibilitySpeechAttributeAnnouncementPriority"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeAnnouncementPriority",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAccessibilitySpeechAttributeAnnouncementPriority",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityspeechattributeannouncementpriority"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeIPANotation": {
      "abstract": [
        {
          "text": "A key that indicates the pronunciation of a specific word or phrase, such as a proper name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIAccessibilitySpeechAttributeIPANotation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeIPANotation",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAccessibilitySpeechAttributeIPANotation",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityspeechattributeipanotation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeLanguage": {
      "abstract": [
        {
          "text": "A key that indicates the language to use when speaking a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIAccessibilitySpeechAttributeLanguage"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeLanguage",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAccessibilitySpeechAttributeLanguage",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityspeechattributelanguage"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributePitch": {
      "abstract": [
        {
          "text": "A key that indicates the pitch to apply to spoken content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIAccessibilitySpeechAttributePitch"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributePitch",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAccessibilitySpeechAttributePitch",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityspeechattributepitch"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributePunctuation": {
      "abstract": [
        {
          "text": "A key that indicates whether to speak punctuation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIAccessibilitySpeechAttributePunctuation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributePunctuation",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAccessibilitySpeechAttributePunctuation",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityspeechattributepunctuation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeQueueAnnouncement": {
      "abstract": [
        {
          "text": "A key that indicates whether to queue an announcement behind existing speech or to interrupt it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIAccessibilitySpeechAttributeQueueAnnouncement"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeQueueAnnouncement",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAccessibilitySpeechAttributeQueueAnnouncement",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityspeechattributequeueannouncement"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeSpellOut": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIAccessibilitySpeechAttributeSpellOut"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeSpellOut",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAccessibilitySpeechAttributeSpellOut",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityspeechattributespellout"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/1620201-accessibilityspeechpunctuation",
        "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/1620188-accessibilityspeechlanguage",
        "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/1620195-accessibilityspeechpitch",
        "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/2865770-accessibilityspeechqueueannounce",
        "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/2890748-accessibilityspeechipanotation",
        "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/4168159-accessibilityspeechannouncementp",
        "doc://com.apple.documentation/documentation/foundation/nsattributedstring/key/3333285-accessibilityspeechspellout"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Choosing-a-priority",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityPriority/high",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityPriority/default",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityPriority/low"
      ],
      "title": "Choosing a priority"
    },
    {
      "anchor": "Creating-a-priority",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityPriority/init(rawValue:)"
      ],
      "title": "Creating a priority"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIAccessibilityPriority"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityPriority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityPriority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Choosing-a-priority",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityPriority/high",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityPriority/default",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityPriority/low"
              ],
              "title": "Choosing a priority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributePunctuation",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeLanguage",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributePitch",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeQueueAnnouncement",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeIPANotation",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeAnnouncementPriority",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeSpellOut"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIAccessibilityPriority"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityPriority~1high/title",
          "value": "UIAccessibilityPriorityHigh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityPriority~1high/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityPriorityHigh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityPriority~1low/title",
          "value": "UIAccessibilityPriorityLow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityPriority~1low/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityPriorityLow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityPriority/title",
          "value": "UIAccessibilityPriority"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityPriority/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityPriority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityPriority/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityPriority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityPriority~1default/title",
          "value": "UIAccessibilityPriorityDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityPriority~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityPriorityDefault"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiaccessibilitypriority"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiaccessibilitypriority"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
