{
  "abstract": [
    {
      "text": "The direction of a scrolling action.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityScrollDirection"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIAccessibilityScrollDirection",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIAccessibilityScrollDirection"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIAccessibilityScrollDirection"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "UIAccessibilityScrollDirection"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIAccessibilityScrollDirection"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/AssistiveTechnologyIdentifier": {
      "abstract": [
        {
          "text": "Identifiers for assistive apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AssistiveTechnologyIdentifier"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/AssistiveTechnologyIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AssistiveTechnologyIdentifier"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibility.AssistiveTechnologyIdentifier",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/assistivetechnologyidentifier"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/DirectTouchOptions": {
      "abstract": [
        {
          "text": "Constants that configure how VoiceOver produces audio for direct touch areas.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DirectTouchOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/DirectTouchOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DirectTouchOptions"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibility.DirectTouchOptions",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/directtouchoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/HearingDeviceEar": {
      "abstract": [
        {
          "text": "Constants that specify how a person is using a hearing device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HearingDeviceEar"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/HearingDeviceEar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HearingDeviceEar"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibility.HearingDeviceEar",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/hearingdeviceear"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/ZoomType": {
      "abstract": [
        {
          "text": "The types of system Zoom that can be in effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ZoomType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/ZoomType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ZoomType"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibility.ZoomType",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/zoomtype"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType": {
      "abstract": [
        {
          "text": "Constants that indicate the type of content in a data-based container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAccessibilityContainerType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityContainerType"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityContainerType",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycontainertype"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityNavigationStyle": {
      "abstract": [
        {
          "text": "Constants that describe how to navigate an object’s elements with an assistive app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAccessibilityNavigationStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityNavigationStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityNavigationStyle"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityNavigationStyle",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitynavigationstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityScrollDirection": {
      "abstract": [
        {
          "text": "The direction of a scrolling action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAccessibilityScrollDirection"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityScrollDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityScrollDirection"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityScrollDirection",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityscrolldirection"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityScrollDirection/down": {
      "abstract": [
        {
          "text": "The user is scrolling down.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "down"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityScrollDirection/down",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityScrollDirectionDown"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityScrollDirection.down",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityscrolldirection/down"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityScrollDirection/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityScrollDirection/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityscrolldirection/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityScrollDirection/left": {
      "abstract": [
        {
          "text": "The user is scrolling to the left.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "left"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityScrollDirection/left",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityScrollDirectionLeft"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityScrollDirection.left",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityscrolldirection/left"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityScrollDirection/next": {
      "abstract": [
        {
          "text": "The user is scrolling to the next view in an ordered set of views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "next"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityScrollDirection/next",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityScrollDirectionNext"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityScrollDirection.next",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityscrolldirection/next"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityScrollDirection/previous": {
      "abstract": [
        {
          "text": "The user is scrolling to the previous view in an ordered set of views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "previous"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityScrollDirection/previous",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityScrollDirectionPrevious"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityScrollDirection.previous",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityscrolldirection/previous"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityScrollDirection/right": {
      "abstract": [
        {
          "text": "The user is scrolling to the right.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "right"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityScrollDirection/right",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityScrollDirectionRight"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityScrollDirection.right",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityscrolldirection/right"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityScrollDirection/up": {
      "abstract": [
        {
          "text": "The user is scrolling up.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "up"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityScrollDirection/up",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityScrollDirectionUp"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityScrollDirection.up",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityscrolldirection/up"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits": {
      "abstract": [
        {
          "text": "Constants that describe how an accessibility element behaves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAccessibilityTraits"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityTraits"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityTraits",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitytraits"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/AssistiveTechnologyIdentifier",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/HearingDeviceEar",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityNavigationStyle",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/ZoomType",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/DirectTouchOptions"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityScrollDirection/right",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityScrollDirection/left",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityScrollDirection/up",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityScrollDirection/down",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityScrollDirection/next",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityScrollDirection/previous"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityScrollDirection/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIAccessibilityScrollDirection"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityScrollDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityScrollDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityScrollDirection/right",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityScrollDirection/left",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityScrollDirection/up",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityScrollDirection/down",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityScrollDirection/next",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityScrollDirection/previous"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/AssistiveTechnologyIdentifier",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/HearingDeviceEar",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityNavigationStyle",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/ZoomType",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/DirectTouchOptions"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIAccessibilityScrollDirection"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerType/title",
          "value": "UIAccessibilityContainerType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityContainerType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityContainerType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1ZoomType/title",
          "value": "UIAccessibilityZoomType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1ZoomType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityZoomType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1ZoomType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityZoomType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityScrollDirection~1next/title",
          "value": "UIAccessibilityScrollDirectionNext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityScrollDirection~1next/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityScrollDirectionNext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityScrollDirection/title",
          "value": "UIAccessibilityScrollDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityScrollDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityScrollDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityScrollDirection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityScrollDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityScrollDirection~1down/title",
          "value": "UIAccessibilityScrollDirectionDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityScrollDirection~1down/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityScrollDirectionDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityScrollDirection~1up/title",
          "value": "UIAccessibilityScrollDirectionUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityScrollDirection~1up/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityScrollDirectionUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1AssistiveTechnologyIdentifier/title",
          "value": "UIAccessibilityAssistiveTechnologyIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1AssistiveTechnologyIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityAssistiveTechnologyIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1AssistiveTechnologyIdentifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityAssistiveTechnologyIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityScrollDirection~1previous/title",
          "value": "UIAccessibilityScrollDirectionPrevious"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityScrollDirection~1previous/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityScrollDirectionPrevious"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityScrollDirection~1right/title",
          "value": "UIAccessibilityScrollDirectionRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityScrollDirection~1right/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityScrollDirectionRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityScrollDirection~1left/title",
          "value": "UIAccessibilityScrollDirectionLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityScrollDirection~1left/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityScrollDirectionLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityNavigationStyle/title",
          "value": "UIAccessibilityNavigationStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityNavigationStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityNavigationStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityNavigationStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityNavigationStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits/title",
          "value": "UIAccessibilityTraits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1HearingDeviceEar/title",
          "value": "UIAccessibilityHearingDeviceEar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1HearingDeviceEar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityHearingDeviceEar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1HearingDeviceEar/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityHearingDeviceEar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1DirectTouchOptions/title",
          "value": "UIAccessibilityDirectTouchOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1DirectTouchOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityDirectTouchOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1DirectTouchOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityDirectTouchOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiaccessibilityscrolldirection"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiaccessibilityscrolldirection"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
