{
  "abstract": [
    {
      "text": "A configuration that allows a responder to export data through a variety of interactions.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIActivityItemsConfiguration",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIActivityItemsConfiguration"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIActivityItemsConfiguration"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "UIActivityItemsConfiguration"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIActivityItemsConfiguration"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.uikit/documentation/UIKit/collaborating-and-sharing-copies-of-your-data"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivityCollaborationMode": {
      "abstract": [
        {
          "text": "A value that defines how the system shares an item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIActivityCollaborationMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivityCollaborationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIActivityCollaborationMode"
        }
      ],
      "role": "symbol",
      "title": "UIActivityCollaborationMode",
      "type": "topic",
      "url": "/documentation/uikit/uiactivitycollaborationmode"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration": {
      "abstract": [
        {
          "text": "A configuration that allows a responder to export data through a variety of interactions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIActivityItemsConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIActivityItemsConfiguration"
        }
      ],
      "role": "symbol",
      "title": "UIActivityItemsConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uiactivityitemsconfiguration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration/activityItemsConfigurationWithItemProviders:": {
      "abstract": [
        {
          "text": "Creates an activity items configuration with the specified item providers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "activityItemsConfigurationWithItemProviders:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration/activityItemsConfigurationWithItemProviders:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activityItemsConfigurationWithItemProviders:"
        }
      ],
      "role": "symbol",
      "title": "activityItemsConfigurationWithItemProviders:",
      "type": "topic",
      "url": "/documentation/uikit/uiactivityitemsconfiguration/activityitemsconfigurationwithitemproviders:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration/activityItemsConfigurationWithObjects:": {
      "abstract": [
        {
          "text": "Creates an activity items configuration with the specified objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "activityItemsConfigurationWithObjects:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration/activityItemsConfigurationWithObjects:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activityItemsConfigurationWithObjects:"
        }
      ],
      "role": "symbol",
      "title": "activityItemsConfigurationWithObjects:",
      "type": "topic",
      "url": "/documentation/uikit/uiactivityitemsconfiguration/activityitemsconfigurationwithobjects:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration/applicationActivitiesProvider": {
      "abstract": [
        {
          "text": "A closure that provides application acitivites for the activity items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationActivitiesProvider"
        },
        {
          "kind": "text",
          "text": ": (() -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIActivity",
          "text": "UIActivity"
        },
        {
          "kind": "text",
          "text": "])?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration/applicationActivitiesProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applicationActivitiesProvider"
        }
      ],
      "role": "symbol",
      "title": "applicationActivitiesProvider",
      "type": "topic",
      "url": "/documentation/uikit/uiactivityitemsconfiguration/applicationactivitiesprovider"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration/init(itemProviders:)": {
      "abstract": [
        {
          "text": "Initializes and returns an activity items configuration with the specified item providers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "itemProviders"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSItemProvider",
          "text": "NSItemProvider"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration/init(itemProviders:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithItemProviders:"
        }
      ],
      "role": "symbol",
      "title": "init(itemProviders:)",
      "type": "topic",
      "url": "/documentation/uikit/uiactivityitemsconfiguration/init(itemproviders:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration/init(objects:)": {
      "abstract": [
        {
          "text": "Initializes and returns an activity items configuration with the specified objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "objects"
        },
        {
          "kind": "text",
          "text": ": [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSItemProviderWriting",
          "text": "NSItemProviderWriting"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration/init(objects:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithObjects:"
        }
      ],
      "role": "symbol",
      "title": "init(objects:)",
      "type": "topic",
      "url": "/documentation/uikit/uiactivityitemsconfiguration/init(objects:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration/localObject": {
      "abstract": [
        {
          "text": "A local object that represents the configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localObject"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration/localObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localObject"
        }
      ],
      "role": "symbol",
      "title": "localObject",
      "type": "topic",
      "url": "/documentation/uikit/uiactivityitemsconfiguration/localobject"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration/metadataProvider": {
      "abstract": [
        {
          "text": "A closure that provides metadata for the activity items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "metadataProvider"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIActivityItemsConfigurationMetadataKey",
          "text": "UIActivityItemsConfigurationMetadataKey"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration/metadataProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "metadataProvider"
        }
      ],
      "role": "symbol",
      "title": "metadataProvider",
      "type": "topic",
      "url": "/documentation/uikit/uiactivityitemsconfiguration/metadataprovider"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration/perItemMetadataProvider": {
      "abstract": [
        {
          "text": "A closure that provides metadata for each activity item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "perItemMetadataProvider"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIActivityItemsConfigurationMetadataKey",
          "text": "UIActivityItemsConfigurationMetadataKey"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration/perItemMetadataProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "perItemMetadataProvider"
        }
      ],
      "role": "symbol",
      "title": "perItemMetadataProvider",
      "type": "topic",
      "url": "/documentation/uikit/uiactivityitemsconfiguration/peritemmetadataprovider"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration/previewProvider": {
      "abstract": [
        {
          "text": "A closure that provides previews for the activity items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "previewProvider"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIActivityItemsConfigurationPreviewIntent",
          "text": "UIActivityItemsConfigurationPreviewIntent"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSItemProvider",
          "text": "NSItemProvider"
        },
        {
          "kind": "text",
          "text": "?)?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration/previewProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "previewProvider"
        }
      ],
      "role": "symbol",
      "title": "previewProvider",
      "type": "topic",
      "url": "/documentation/uikit/uiactivityitemsconfiguration/previewprovider"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration/supportedInteractions": {
      "abstract": [
        {
          "text": "The types of interactions that the configuration supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportedInteractions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIActivityItemsConfigurationInteraction",
          "text": "UIActivityItemsConfigurationInteraction"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration/supportedInteractions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportedInteractions"
        }
      ],
      "role": "symbol",
      "title": "supportedInteractions",
      "type": "topic",
      "url": "/documentation/uikit/uiactivityitemsconfiguration/supportedinteractions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationInteraction": {
      "abstract": [
        {
          "text": "A structure that describes types of interactions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIActivityItemsConfigurationInteraction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIActivityItemsConfigurationInteraction"
        }
      ],
      "role": "symbol",
      "title": "UIActivityItemsConfigurationInteraction",
      "type": "topic",
      "url": "/documentation/uikit/uiactivityitemsconfigurationinteraction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationMetadataKey": {
      "abstract": [
        {
          "text": "A structure that defines keys for the metadata associated with an activity items configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIActivityItemsConfigurationMetadataKey"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationMetadataKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIActivityItemsConfigurationMetadataKey"
        }
      ],
      "role": "symbol",
      "title": "UIActivityItemsConfigurationMetadataKey",
      "type": "topic",
      "url": "/documentation/uikit/uiactivityitemsconfigurationmetadatakey"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationPreviewIntent": {
      "abstract": [
        {
          "text": "A structure that specifies the types of activity item previews.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIActivityItemsConfigurationPreviewIntent"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationPreviewIntent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIActivityItemsConfigurationPreviewIntent"
        }
      ],
      "role": "symbol",
      "title": "UIActivityItemsConfigurationPreviewIntent",
      "type": "topic",
      "url": "/documentation/uikit/uiactivityitemsconfigurationpreviewintent"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationReading": {
      "abstract": [
        {
          "text": "A set of methods adopted by an object so that the object can act as an activity items configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIActivityItemsConfigurationReading"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationReading",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIActivityItemsConfigurationReading"
        }
      ],
      "role": "symbol",
      "title": "UIActivityItemsConfigurationReading",
      "type": "topic",
      "url": "/documentation/uikit/uiactivityitemsconfigurationreading"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivityViewController/CollaborationModeRestriction": {
      "abstract": [
        {
          "text": "An object that disables the sharing mode and optionally displays an alert.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CollaborationModeRestriction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivityViewController/CollaborationModeRestriction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CollaborationModeRestriction"
        }
      ],
      "role": "symbol",
      "title": "UIActivityViewController.CollaborationModeRestriction",
      "type": "topic",
      "url": "/documentation/uikit/uiactivityviewcontroller/collaborationmoderestriction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivityViewController/init(activityItems:applicationActivities:)": {
      "abstract": [
        {
          "text": "Initializes a new activity view controller object that acts on the specified data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "activityItems"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "applicationActivities"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIActivity",
          "text": "UIActivity"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivityViewController/init(activityItems:applicationActivities:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithActivityItems:applicationActivities:"
        }
      ],
      "role": "symbol",
      "title": "init(activityItems:applicationActivities:)",
      "type": "topic",
      "url": "/documentation/uikit/uiactivityviewcontroller/init(activityitems:applicationactivities:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivityViewController/init(activityItemsConfiguration:)": {
      "abstract": [
        {
          "text": "Initializes a new activity view controller object that acts on the specified configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "activityItemsConfiguration"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIActivityItemsConfigurationReading",
          "text": "UIActivityItemsConfigurationReading"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivityViewController/init(activityItemsConfiguration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithActivityItemsConfiguration:"
        }
      ],
      "role": "symbol",
      "title": "init(activityItemsConfiguration:)",
      "type": "topic",
      "url": "/documentation/uikit/uiactivityviewcontroller/init(activityitemsconfiguration:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/collaborating-and-sharing-copies-of-your-data": {
      "abstract": [
        {
          "text": "Share data and collaborate with people from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/collaborating-and-sharing-copies-of-your-data",
      "kind": "article",
      "role": "article",
      "title": "Collaborating and sharing copies of your data",
      "type": "topic",
      "url": "/documentation/uikit/collaborating-and-sharing-copies-of-your-data"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationReading"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Initializing-the-activity-view-controller",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIActivityViewController/init(activityItems:applicationActivities:)",
        "doc://com.apple.uikit/documentation/UIKit/UIActivityViewController/init(activityItemsConfiguration:)",
        "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationReading"
      ],
      "title": "Initializing the activity view controller"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-an-activity-items-configuration",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration/init(objects:)",
        "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration/init(itemProviders:)"
      ],
      "title": "Creating an activity items configuration"
    },
    {
      "anchor": "Managing-the-configuration",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration/localObject",
        "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration/metadataProvider",
        "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration/perItemMetadataProvider",
        "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration/applicationActivitiesProvider",
        "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationMetadataKey"
      ],
      "title": "Managing the configuration"
    },
    {
      "anchor": "Managing-supported-interactions",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration/supportedInteractions",
        "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationInteraction"
      ],
      "title": "Managing supported interactions"
    },
    {
      "anchor": "Managing-previews",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration/previewProvider",
        "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationPreviewIntent"
      ],
      "title": "Managing previews"
    },
    {
      "anchor": "Restricting-the-sharing-mode",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIActivityViewController/CollaborationModeRestriction",
        "doc://com.apple.uikit/documentation/UIKit/UIActivityCollaborationMode"
      ],
      "title": "Restricting the sharing mode"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIActivityItemsConfiguration"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityItemsConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityItemsConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-an-activity-items-configuration",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration/init(objects:)",
                "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration/init(itemProviders:)",
                "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration/activityItemsConfigurationWithObjects:",
                "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration/activityItemsConfigurationWithItemProviders:"
              ],
              "title": "Creating an activity items configuration"
            },
            {
              "anchor": "Managing-the-configuration",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration/localObject",
                "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration/metadataProvider",
                "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration/perItemMetadataProvider",
                "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration/applicationActivitiesProvider",
                "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationMetadataKey"
              ],
              "title": "Managing the configuration"
            },
            {
              "anchor": "Managing-supported-interactions",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration/supportedInteractions",
                "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationInteraction"
              ],
              "title": "Managing supported interactions"
            },
            {
              "anchor": "Managing-previews",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfiguration/previewProvider",
                "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationPreviewIntent"
              ],
              "title": "Managing previews"
            },
            {
              "anchor": "Restricting-the-sharing-mode",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIActivityViewController/CollaborationModeRestriction",
                "doc://com.apple.uikit/documentation/UIKit/UIActivityCollaborationMode"
              ],
              "title": "Restricting the sharing mode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationReading"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Initializing-the-activity-view-controller",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIActivityViewController/init(activityItems:applicationActivities:)",
                "doc://com.apple.uikit/documentation/UIKit/UIActivityViewController/init(activityItemsConfiguration:)",
                "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationReading"
              ],
              "title": "Initializing the activity view controller"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIActivityItemsConfiguration"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityViewController~1init(activityItems:applicationActivities:)/title",
          "value": "initWithActivityItems:applicationActivities:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityViewController~1init(activityItems:applicationActivities:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithActivityItems:applicationActivities:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfiguration~1init(objects:)/title",
          "value": "initWithObjects:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfiguration~1init(objects:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithObjects:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfiguration/title",
          "value": "UIActivityItemsConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityItemsConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityItemsConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfiguration~1supportedInteractions/title",
          "value": "supportedInteractions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfiguration~1supportedInteractions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportedInteractions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfiguration~1perItemMetadataProvider/title",
          "value": "perItemMetadataProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfiguration~1perItemMetadataProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "perItemMetadataProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityViewController~1CollaborationModeRestriction/title",
          "value": "UIActivityCollaborationModeRestriction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityViewController~1CollaborationModeRestriction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityCollaborationModeRestriction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityViewController~1CollaborationModeRestriction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityCollaborationModeRestriction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfiguration~1applicationActivitiesProvider/title",
          "value": "applicationActivitiesProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfiguration~1applicationActivitiesProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "applicationActivitiesProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfigurationPreviewIntent/title",
          "value": "UIActivityItemsConfigurationPreviewIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfigurationPreviewIntent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityItemsConfigurationPreviewIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfigurationPreviewIntent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityItemsConfigurationPreviewIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfiguration~1metadataProvider/title",
          "value": "metadataProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfiguration~1metadataProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "metadataProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfiguration~1localObject/title",
          "value": "localObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfiguration~1localObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfiguration~1init(itemProviders:)/title",
          "value": "initWithItemProviders:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfiguration~1init(itemProviders:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithItemProviders:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfigurationMetadataKey/title",
          "value": "UIActivityItemsConfigurationMetadataKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfigurationMetadataKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityItemsConfigurationMetadataKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfigurationMetadataKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityItemsConfigurationMetadataKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfigurationReading/title",
          "value": "UIActivityItemsConfigurationReading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfigurationReading/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityItemsConfigurationReading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfigurationReading/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityItemsConfigurationReading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfigurationInteraction/title",
          "value": "UIActivityItemsConfigurationInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfigurationInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityItemsConfigurationInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfigurationInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityItemsConfigurationInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityViewController~1init(activityItemsConfiguration:)/title",
          "value": "initWithActivityItemsConfiguration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityViewController~1init(activityItemsConfiguration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithActivityItemsConfiguration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfiguration~1previewProvider/title",
          "value": "previewProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfiguration~1previewProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "previewProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityCollaborationMode/title",
          "value": "UIActivityCollaborationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityCollaborationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityCollaborationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityCollaborationMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityCollaborationMode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiactivityitemsconfiguration"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiactivityitemsconfiguration"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
