{
  "abstract": [
    {
      "text": "A key that indicates whether to queue an announcement behind existing speech or to interrupt it.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeQueueAnnouncement"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@UIAccessibilitySpeechAttributeQueueAnnouncement",
    "fragments": [
      {
        "kind": "identifier",
        "text": "UIAccessibilitySpeechAttributeQueueAnnouncement"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIAccessibilitySpeechAttributeQueueAnnouncement"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "1.0",
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "UIAccessibilitySpeechAttributeQueueAnnouncement"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSAttributedStringKey",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSAttributedStringKey",
              "text": "NSAttributedStringKey"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIAccessibilitySpeechAttributeQueueAnnouncement"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The value of this key is an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object that the system interprets as a Boolean value. When the value is ",
              "type": "text"
            },
            {
              "code": "YES",
              "type": "codeVoice"
            },
            {
              "text": ", the system queues the announcement behind existing speech. When the value is ",
              "type": "text"
            },
            {
              "code": "NO",
              "type": "codeVoice"
            },
            {
              "text": ", the announcement interrupts the existing speech. The default behavior is to interrupt existing speech.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/nsnumber": {
      "abstract": [
        {
          "text": "An object wrapper for primitive scalar numeric values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSNumber"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsnumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSNumber",
      "type": "topic",
      "url": "/documentation/foundation/nsnumber"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityPriority": {
      "abstract": [
        {
          "text": "Constants that specify priorities for accessibility announcements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAccessibilityPriority"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityPriority",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityPriority"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityPriority",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitypriority"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeAnnouncementPriority": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIAccessibilitySpeechAttributeAnnouncementPriority"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeAnnouncementPriority",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAccessibilitySpeechAttributeAnnouncementPriority",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityspeechattributeannouncementpriority"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeIPANotation": {
      "abstract": [
        {
          "text": "A key that indicates the pronunciation of a specific word or phrase, such as a proper name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIAccessibilitySpeechAttributeIPANotation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeIPANotation",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAccessibilitySpeechAttributeIPANotation",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityspeechattributeipanotation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeLanguage": {
      "abstract": [
        {
          "text": "A key that indicates the language to use when speaking a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIAccessibilitySpeechAttributeLanguage"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeLanguage",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAccessibilitySpeechAttributeLanguage",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityspeechattributelanguage"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributePitch": {
      "abstract": [
        {
          "text": "A key that indicates the pitch to apply to spoken content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIAccessibilitySpeechAttributePitch"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributePitch",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAccessibilitySpeechAttributePitch",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityspeechattributepitch"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributePunctuation": {
      "abstract": [
        {
          "text": "A key that indicates whether to speak punctuation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIAccessibilitySpeechAttributePunctuation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributePunctuation",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAccessibilitySpeechAttributePunctuation",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityspeechattributepunctuation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeQueueAnnouncement": {
      "abstract": [
        {
          "text": "A key that indicates whether to queue an announcement behind existing speech or to interrupt it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIAccessibilitySpeechAttributeQueueAnnouncement"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeQueueAnnouncement",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAccessibilitySpeechAttributeQueueAnnouncement",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityspeechattributequeueannouncement"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeSpellOut": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIAccessibilitySpeechAttributeSpellOut"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeSpellOut",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAccessibilitySpeechAttributeSpellOut",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityspeechattributespellout"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSAttributedStringKey": {
      "abstract": [
        {
          "text": "The attributes you apply to ranges of characters in an attributed string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "NSAttributedString.Key"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSAttributedStringKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSAttributedString.Key",
      "type": "topic",
      "url": "/documentation/foundation/nsattributedstring/key"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributePunctuation",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeLanguage",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributePitch",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeIPANotation",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeAnnouncementPriority",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilitySpeechAttributeSpellOut",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityPriority"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityPriority/title",
          "value": "UIAccessibilityPriority"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityPriority/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityPriority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityPriority/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityPriority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@NSAttributedStringKey/title",
          "value": "NSAttributedStringKey"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiaccessibilityspeechattributequeueannouncement"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
