{
  "abstract": [
    {
      "text": "Methods to implement for an object that represents content that users read, such as a book or an article.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UIAccessibilityReadingContent",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIAccessibilityReadingContent"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIAccessibilityReadingContent"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "UIAccessibilityReadingContent"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIAccessibilityReadingContent"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To give VoiceOver users a superior, continuous reading experience, you can implement this protocol on an element that represents readable content, characterize it with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/causesPageTurn",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " trait, and use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityScrollDirection/next",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityScrollDirection/previous",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " constants to enable page turning.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/objectivec/nsobject/uiaccessibilityfocus": {
      "abstract": [
        {
          "text": "An informal protocol that provides a way to determine whether an assistive app, such as VoiceOver, has focus on an accessible element.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/uiaccessibilityfocus",
      "kind": "article",
      "role": "article",
      "title": "UIAccessibilityFocus",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/uiaccessibilityfocus"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContentSizeCategoryImageAdjusting": {
      "abstract": [
        {
          "text": "Methods to determine when to adjust images for different content size categories.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAccessibilityContentSizeCategoryImageAdjusting"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContentSizeCategoryImageAdjusting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityContentSizeCategoryImageAdjusting"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityContentSizeCategoryImageAdjusting",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycontentsizecategoryimageadjusting"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityIdentification": {
      "abstract": [
        {
          "text": "Methods that associate a unique identifier with elements in your user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAccessibilityIdentification"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityIdentification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityIdentification"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityIdentification",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityidentification"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent": {
      "abstract": [
        {
          "text": "Methods to implement for an object that represents content that users read, such as a book or an article.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAccessibilityReadingContent"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityReadingContent"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityReadingContent",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityreadingcontent"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityAttributedContent(forLineNumber:)": {
      "abstract": [
        {
          "text": "Returns the styled text associated with the specified line number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityAttributedContent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forLineNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityAttributedContent(forLineNumber:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityAttributedContentForLineNumber:"
        }
      ],
      "role": "symbol",
      "title": "accessibilityAttributedContent(forLineNumber:)",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityreadingcontent/accessibilityattributedcontent(forlinenumber:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityAttributedPageContent()": {
      "abstract": [
        {
          "text": "Returns the styled text displayed on the current page.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityAttributedPageContent"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityAttributedPageContent()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityAttributedPageContent"
        }
      ],
      "role": "symbol",
      "title": "accessibilityAttributedPageContent()",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityreadingcontent/accessibilityattributedpagecontent()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityContent(forLineNumber:)": {
      "abstract": [
        {
          "text": "Returns the text associated with the specified line number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityContent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forLineNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityContent(forLineNumber:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityContentForLineNumber:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "accessibilityContent(forLineNumber:)",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityreadingcontent/accessibilitycontent(forlinenumber:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityFrame(forLineNumber:)": {
      "abstract": [
        {
          "text": "Returns the onscreen frame associated with the specified line number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityFrame"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forLineNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityFrame(forLineNumber:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityFrameForLineNumber:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "accessibilityFrame(forLineNumber:)",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityreadingcontent/accessibilityframe(forlinenumber:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityLineNumber(for:)": {
      "abstract": [
        {
          "text": "Returns the line number that contains the specified point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityLineNumber"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityLineNumber(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityLineNumberForPoint:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "accessibilityLineNumber(for:)",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityreadingcontent/accessibilitylinenumber(for:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityPageContent()": {
      "abstract": [
        {
          "text": "Returns the text displayed on the current page.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityPageContent"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityPageContent()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityPageContent"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "accessibilityPageContent()",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityreadingcontent/accessibilitypagecontent()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityScrollDirection/next": {
      "abstract": [
        {
          "text": "The user is scrolling to the next view in an ordered set of views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "next"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityScrollDirection/next",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityScrollDirectionNext"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityScrollDirection.next",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityscrolldirection/next"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityScrollDirection/previous": {
      "abstract": [
        {
          "text": "The user is scrolling to the previous view in an ordered set of views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "previous"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityScrollDirection/previous",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityScrollDirectionPrevious"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityScrollDirection.previous",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityscrolldirection/previous"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTextualContext": {
      "abstract": [
        {
          "text": "Constants that describe a named context that helps identify and classify the type of text inside an element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAccessibilityTextualContext"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTextualContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityTextualContext"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityTextualContext",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitytextualcontext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/causesPageTurn": {
      "abstract": [
        {
          "text": "The accessibility element causes an automatic page turn when VoiceOver finishes reading the text within it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "causesPageTurn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityTraits",
          "text": "UIAccessibilityTraits"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/causesPageTurn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityTraitCausesPageTurn"
        }
      ],
      "role": "symbol",
      "title": "causesPageTurn",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitytraits/causespageturn"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Behaviors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/objectivec/nsobject/uiaccessibilityfocus",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityIdentification",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContentSizeCategoryImageAdjusting",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTextualContext"
      ],
      "title": "Behaviors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accessing-the-content-on-a-page",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityLineNumber(for:)",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityAttributedContent(forLineNumber:)",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityContent(forLineNumber:)",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityFrame(forLineNumber:)",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityAttributedPageContent()",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityPageContent()"
      ],
      "title": "Accessing the content on a page"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIAccessibilityReadingContent"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityReadingContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityReadingContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Accessing-the-content-on-a-page",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityLineNumber(for:)",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityAttributedContent(forLineNumber:)",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityContent(forLineNumber:)",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityFrame(forLineNumber:)",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityAttributedPageContent()",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityReadingContent/accessibilityPageContent()"
              ],
              "title": "Accessing the content on a page"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Behaviors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.documentation/documentation/objectivec/nsobject/uiaccessibilityfocus",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityIdentification",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContentSizeCategoryImageAdjusting",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTextualContext"
              ],
              "title": "Behaviors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIAccessibilityReadingContent"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1causesPageTurn/title",
          "value": "UIAccessibilityTraitCausesPageTurn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1causesPageTurn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityTraitCausesPageTurn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityReadingContent~1accessibilityContent(forLineNumber:)/title",
          "value": "accessibilityContentForLineNumber:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityReadingContent~1accessibilityContent(forLineNumber:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessibilityContentForLineNumber:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityReadingContent~1accessibilityAttributedPageContent()/title",
          "value": "accessibilityAttributedPageContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityReadingContent~1accessibilityAttributedPageContent()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessibilityAttributedPageContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityScrollDirection~1previous/title",
          "value": "UIAccessibilityScrollDirectionPrevious"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityScrollDirection~1previous/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityScrollDirectionPrevious"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityReadingContent~1accessibilityLineNumber(for:)/title",
          "value": "accessibilityLineNumberForPoint:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityReadingContent~1accessibilityLineNumber(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessibilityLineNumberForPoint:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityScrollDirection~1next/title",
          "value": "UIAccessibilityScrollDirectionNext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityScrollDirection~1next/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityScrollDirectionNext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityIdentification/title",
          "value": "UIAccessibilityIdentification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityIdentification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityIdentification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityIdentification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityIdentification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityReadingContent~1accessibilityPageContent()/title",
          "value": "accessibilityPageContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityReadingContent~1accessibilityPageContent()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessibilityPageContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTextualContext/title",
          "value": "UIAccessibilityTextualContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTextualContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityTextualContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTextualContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityTextualContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContentSizeCategoryImageAdjusting/title",
          "value": "UIAccessibilityContentSizeCategoryImageAdjusting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContentSizeCategoryImageAdjusting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityContentSizeCategoryImageAdjusting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContentSizeCategoryImageAdjusting/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityContentSizeCategoryImageAdjusting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityReadingContent~1accessibilityFrame(forLineNumber:)/title",
          "value": "accessibilityFrameForLineNumber:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityReadingContent~1accessibilityFrame(forLineNumber:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessibilityFrameForLineNumber:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityReadingContent~1accessibilityAttributedContent(forLineNumber:)/title",
          "value": "accessibilityAttributedContentForLineNumber:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityReadingContent~1accessibilityAttributedContent(forLineNumber:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "accessibilityAttributedContentForLineNumber:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityReadingContent/title",
          "value": "UIAccessibilityReadingContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityReadingContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityReadingContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityReadingContent/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityReadingContent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiaccessibilityreadingcontent"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiaccessibilityreadingcontent"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
