{
  "abstract": [
    {
      "text": "A custom action to perform on an accessible object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIAccessibilityCustomAction",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIAccessibilityCustomAction"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIAccessibilityCustomAction"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "UIAccessibilityCustomAction"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomAction"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Apps that support custom actions can create instances of this class, specifying the user-readable name of the action and the object and selector to use when performing the action. Assistive apps display custom actions in response to specific user cues. For example, VoiceOver lets users access actions quickly using the Actions rotor.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "After creating an instance of this class, add it to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1615150-accessibilitycustomactions",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of an appropriate accessible object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/Accessibility/delivering_an_exceptional_accessibility_experience": {
      "abstract": [
        {
          "text": "Make improvements to your app’s interaction model to support assistive technologies such as VoiceOver.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Accessibility/delivering_an_exceptional_accessibility_experience",
      "kind": "article",
      "role": "sampleCode",
      "title": "Delivering an exceptional accessibility experience",
      "type": "topic",
      "url": "/documentation/Accessibility/delivering_an_exceptional_accessibility_experience"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1615150-accessibilitycustomactions": {
      "abstract": [
        {
          "text": "An array of custom actions to display along with the built-in actions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "accessibilityCustomActions"
        },
        {
          "kind": "text",
          "text": ": [UIAccessibilityCustomAction]?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1615150-accessibilitycustomactions",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityCustomActions",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1615150-accessibilitycustomactions"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/uiaccessibilityaction": {
      "abstract": [
        {
          "text": "A set of methods that accessibility elements can use to support specific actions.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/uiaccessibilityaction",
      "kind": "article",
      "role": "article",
      "title": "UIAccessibilityAction",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/uiaccessibilityaction"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction": {
      "abstract": [
        {
          "text": "A custom action to perform on an accessible object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAccessibilityCustomAction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityCustomAction"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityCustomAction",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomaction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/Handler": {
      "abstract": [
        {
          "text": "A closure type that defines a handler to perform for an action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Handler"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/Handler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Handler"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityCustomAction.Handler",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomaction/handler"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/actionHandler": {
      "abstract": [
        {
          "text": "A handler to perform for the action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "actionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIAccessibilityCustomAction",
          "text": "UIAccessibilityCustomAction"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityCustomActionHandler",
          "text": "Handler"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/actionHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "actionHandler"
        }
      ],
      "role": "symbol",
      "title": "actionHandler",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomaction/actionhandler"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/attributedName": {
      "abstract": [
        {
          "text": "The localized name of the action as an attributed string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attributedName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/attributedName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attributedName"
        }
      ],
      "role": "symbol",
      "title": "attributedName",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomaction/attributedname"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/category": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "category"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/category",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "category"
        }
      ],
      "role": "symbol",
      "title": "category",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomaction/category"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/editCategory": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "editCategory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/editCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityCustomActionCategoryEdit"
        }
      ],
      "role": "symbol",
      "title": "editCategory",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomaction/editcategory"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/image": {
      "abstract": [
        {
          "text": "An image that represents the action in assistive apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "image"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/image",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "image"
        }
      ],
      "role": "symbol",
      "title": "image",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomaction/image"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/init(attributedName:actionHandler:)": {
      "abstract": [
        {
          "text": "Creates a custom action object with the specified attributed name and action handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "attributedName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "actionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIAccessibilityCustomAction",
          "text": "UIAccessibilityCustomAction"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityCustomActionHandler",
          "text": "Handler"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/init(attributedName:actionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithAttributedName:actionHandler:"
        }
      ],
      "role": "symbol",
      "title": "init(attributedName:actionHandler:)",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomaction/init(attributedname:actionhandler:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/init(attributedName:image:actionHandler:)": {
      "abstract": [
        {
          "text": "Creates a custom action object with the specified attributed name, image, and action handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "attributedName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "image"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "actionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIAccessibilityCustomAction",
          "text": "UIAccessibilityCustomAction"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityCustomActionHandler",
          "text": "Handler"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/init(attributedName:image:actionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithAttributedName:image:actionHandler:"
        }
      ],
      "role": "symbol",
      "title": "init(attributedName:image:actionHandler:)",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomaction/init(attributedname:image:actionhandler:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/init(attributedName:image:target:selector:)": {
      "abstract": [
        {
          "text": "Creates a custom action object with the specified attributed name, image, target, and selector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "attributedName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "image"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "target"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "selector"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/init(attributedName:image:target:selector:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithAttributedName:image:target:selector:"
        }
      ],
      "role": "symbol",
      "title": "init(attributedName:image:target:selector:)",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomaction/init(attributedname:image:target:selector:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/init(attributedName:target:selector:)": {
      "abstract": [
        {
          "text": "Creates a custom action object with the specified attributed name, target, and selector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "attributedName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "target"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "selector"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/init(attributedName:target:selector:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithAttributedName:target:selector:"
        }
      ],
      "role": "symbol",
      "title": "init(attributedName:target:selector:)",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomaction/init(attributedname:target:selector:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/init(name:actionHandler:)": {
      "abstract": [
        {
          "text": "Creates a custom action object with the specified name and action handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "actionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIAccessibilityCustomAction",
          "text": "UIAccessibilityCustomAction"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityCustomActionHandler",
          "text": "Handler"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/init(name:actionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithName:actionHandler:"
        }
      ],
      "role": "symbol",
      "title": "init(name:actionHandler:)",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomaction/init(name:actionhandler:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/init(name:image:actionHandler:)": {
      "abstract": [
        {
          "text": "Creates a custom action object with the specified name, image, and action handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "image"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "actionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIAccessibilityCustomAction",
          "text": "UIAccessibilityCustomAction"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityCustomActionHandler",
          "text": "Handler"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/init(name:image:actionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithName:image:actionHandler:"
        }
      ],
      "role": "symbol",
      "title": "init(name:image:actionHandler:)",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomaction/init(name:image:actionhandler:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/init(name:image:target:selector:)": {
      "abstract": [
        {
          "text": "Creates a custom action object with the specified name, image, target, and selector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "image"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "target"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "selector"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/init(name:image:target:selector:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithName:image:target:selector:"
        }
      ],
      "role": "symbol",
      "title": "init(name:image:target:selector:)",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomaction/init(name:image:target:selector:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/init(name:target:selector:)": {
      "abstract": [
        {
          "text": "Creates a custom action object with the specified name, target, and selector.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "target"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "selector"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/init(name:target:selector:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithName:target:selector:"
        }
      ],
      "role": "symbol",
      "title": "init(name:target:selector:)",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomaction/init(name:target:selector:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/name": {
      "abstract": [
        {
          "text": "The localized name of the action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "name"
        }
      ],
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomaction/name"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/selector": {
      "abstract": [
        {
          "text": "The method that performs the action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selector"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/selector",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selector"
        }
      ],
      "role": "symbol",
      "title": "selector",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomaction/selector"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/target": {
      "abstract": [
        {
          "text": "The object that performs the action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "target"
        },
        {
          "kind": "text",
          "text": ": AnyObject?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/target",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "target"
        }
      ],
      "role": "symbol",
      "title": "target",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomaction/target"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Actions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/objectivec/nsobject/uiaccessibilityaction",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/Handler",
        "doc://com.apple.documentation/documentation/Accessibility/delivering_an_exceptional_accessibility_experience"
      ],
      "title": "Actions"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-custom-action",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/init(name:actionHandler:)",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/init(name:target:selector:)",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/init(name:image:actionHandler:)",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/init(name:image:target:selector:)",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/init(attributedName:actionHandler:)",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/init(attributedName:target:selector:)",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/init(attributedName:image:actionHandler:)",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/init(attributedName:image:target:selector:)"
      ],
      "title": "Creating a custom action"
    },
    {
      "anchor": "Accessing-the-action-parameters",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/name",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/attributedName",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/image",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/actionHandler",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/target",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/selector",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/Handler"
      ],
      "title": "Accessing the action parameters"
    },
    {
      "anchor": "Type-Properties",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/editCategory"
      ],
      "title": "Type Properties"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/category"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIAccessibilityCustomAction"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-custom-action",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/init(name:actionHandler:)",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/init(name:target:selector:)",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/init(name:image:actionHandler:)",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/init(name:image:target:selector:)",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/init(attributedName:actionHandler:)",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/init(attributedName:target:selector:)",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/init(attributedName:image:actionHandler:)",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/init(attributedName:image:target:selector:)"
              ],
              "title": "Creating a custom action"
            },
            {
              "anchor": "Accessing-the-action-parameters",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/name",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/attributedName",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/image",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/actionHandler",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/target",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/selector",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/Handler"
              ],
              "title": "Accessing the action parameters"
            },
            {
              "anchor": "Type-Properties",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/editCategory"
              ],
              "title": "Type Properties"
            },
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/category"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Actions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.documentation/documentation/objectivec/nsobject/uiaccessibilityaction",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomAction/Handler",
                "doc://com.apple.documentation/documentation/Accessibility/delivering_an_exceptional_accessibility_experience"
              ],
              "title": "Actions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIAccessibilityCustomAction"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomAction~1init(attributedName:image:actionHandler:)/title",
          "value": "initWithAttributedName:image:actionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomAction~1init(attributedName:image:actionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithAttributedName:image:actionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomAction~1name/title",
          "value": "name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomAction~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomAction~1init(name:image:target:selector:)/title",
          "value": "initWithName:image:target:selector:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomAction~1init(name:image:target:selector:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithName:image:target:selector:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomAction~1category/title",
          "value": "category"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomAction~1category/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "category"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomAction~1Handler/title",
          "value": "UIAccessibilityCustomActionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomAction~1Handler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomActionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomAction~1Handler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomActionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomAction~1actionHandler/title",
          "value": "actionHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomAction~1actionHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "actionHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomAction/title",
          "value": "UIAccessibilityCustomAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomAction~1target/title",
          "value": "target"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomAction~1target/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "target"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomAction~1image/title",
          "value": "image"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomAction~1image/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "image"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomAction~1init(attributedName:image:target:selector:)/title",
          "value": "initWithAttributedName:image:target:selector:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomAction~1init(attributedName:image:target:selector:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithAttributedName:image:target:selector:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomAction~1init(name:image:actionHandler:)/title",
          "value": "initWithName:image:actionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomAction~1init(name:image:actionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithName:image:actionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomAction~1init(attributedName:target:selector:)/title",
          "value": "initWithAttributedName:target:selector:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomAction~1init(attributedName:target:selector:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithAttributedName:target:selector:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomAction~1init(attributedName:actionHandler:)/title",
          "value": "initWithAttributedName:actionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomAction~1init(attributedName:actionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithAttributedName:actionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomAction~1editCategory/title",
          "value": "UIAccessibilityCustomActionCategoryEdit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomAction~1editCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomActionCategoryEdit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomAction~1init(name:target:selector:)/title",
          "value": "initWithName:target:selector:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomAction~1init(name:target:selector:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithName:target:selector:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomAction~1init(name:actionHandler:)/title",
          "value": "initWithName:actionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomAction~1init(name:actionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithName:actionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomAction~1selector/title",
          "value": "selector"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomAction~1selector/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "selector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomAction~1attributedName/title",
          "value": "attributedName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomAction~1attributedName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "attributedName"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiaccessibilitycustomaction"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiaccessibilitycustomaction"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
