{
  "abstract": [
    {
      "text": "Constants that indicate the accessibility contrast setting.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContrast"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIAccessibilityContrast",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIAccessibilityContrast"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIAccessibilityContrast"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "UIAccessibilityContrast"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIAccessibilityContrast"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContrast": {
      "abstract": [
        {
          "text": "Constants that indicate the accessibility contrast setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAccessibilityContrast"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContrast",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityContrast"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityContrast",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycontrast"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContrast/high": {
      "abstract": [
        {
          "text": "A high contrast level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "high"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContrast/high",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityContrastHigh"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityContrast.high",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycontrast/high"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContrast/init(_:)": {
      "abstract": [
        {
          "text": "Creates an accessibility contrast from the specified SwiftUI color scheme contrast.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI19ColorSchemeContrastO",
          "text": "ColorSchemeContrast"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContrast/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycontrast/init(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContrast/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContrast/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycontrast/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContrast/normal": {
      "abstract": [
        {
          "text": "A normal contrast level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "normal"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContrast/normal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityContrastNormal"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityContrast.normal",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycontrast/normal"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContrast/unspecified": {
      "abstract": [
        {
          "text": "An unspecified contrast.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContrast/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityContrastUnspecified"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityContrast.unspecified",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycontrast/unspecified"
    },
    "doc://com.apple.uikit/documentation/UIKit/UILegibilityWeight": {
      "abstract": [
        {
          "text": "Constants that indicate the weight to apply to text in your interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UILegibilityWeight"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UILegibilityWeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILegibilityWeight"
        }
      ],
      "role": "symbol",
      "title": "UILegibilityWeight",
      "type": "topic",
      "url": "/documentation/uikit/uilegibilityweight"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINSToolbarItemPresentationSize": {
      "abstract": [
        {
          "text": "Constants that specify the presentation size of a toolbar item in an AppKit toolbar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UINSToolbarItemPresentationSize"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINSToolbarItemPresentationSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UINSToolbarItemPresentationSize"
        }
      ],
      "role": "symbol",
      "title": "UINSToolbarItemPresentationSize",
      "type": "topic",
      "url": "/documentation/uikit/uinstoolbaritempresentationsize"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitCollection/accessibilityContrast": {
      "abstract": [
        {
          "text": "The accessibility contrast associated with the current environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityContrast"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIAccessibilityContrast",
          "text": "UIAccessibilityContrast"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitCollection/accessibilityContrast",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accessibilityContrast"
        }
      ],
      "role": "symbol",
      "title": "accessibilityContrast",
      "type": "topic",
      "url": "/documentation/uikit/uitraitcollection/accessibilitycontrast"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitCollection/activeAppearance": {
      "abstract": [
        {
          "text": "A property that indicates whether the user interface has an active appearance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activeAppearance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIUserInterfaceActiveAppearance",
          "text": "UIUserInterfaceActiveAppearance"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitCollection/activeAppearance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activeAppearance"
        }
      ],
      "role": "symbol",
      "title": "activeAppearance",
      "type": "topic",
      "url": "/documentation/uikit/uitraitcollection/activeappearance"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitCollection/layoutDirection": {
      "abstract": [
        {
          "text": "The layout direction associated with the current environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layoutDirection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UITraitEnvironmentLayoutDirection",
          "text": "UITraitEnvironmentLayoutDirection"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitCollection/layoutDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layoutDirection"
        }
      ],
      "role": "symbol",
      "title": "layoutDirection",
      "type": "topic",
      "url": "/documentation/uikit/uitraitcollection/layoutdirection"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitCollection/legibilityWeight": {
      "abstract": [
        {
          "text": "The font weight to apply to text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "legibilityWeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UILegibilityWeight",
          "text": "UILegibilityWeight"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitCollection/legibilityWeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "legibilityWeight"
        }
      ],
      "role": "symbol",
      "title": "legibilityWeight",
      "type": "topic",
      "url": "/documentation/uikit/uitraitcollection/legibilityweight"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitCollection/toolbarItemPresentationSize": {
      "abstract": [
        {
          "text": "The presentation size of a toolbar item in an AppKit toolbar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toolbarItemPresentationSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UINSToolbarItemPresentationSize",
          "text": "UINSToolbarItemPresentationSize"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitCollection/toolbarItemPresentationSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "toolbarItemPresentationSize"
        }
      ],
      "role": "symbol",
      "title": "toolbarItemPresentationSize",
      "type": "topic",
      "url": "/documentation/uikit/uitraitcollection/toolbaritempresentationsize"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitCollection/userInterfaceIdiom": {
      "abstract": [
        {
          "text": "The user interface idiom of the trait collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userInterfaceIdiom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIUserInterfaceIdiom",
          "text": "UIUserInterfaceIdiom"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitCollection/userInterfaceIdiom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userInterfaceIdiom"
        }
      ],
      "role": "symbol",
      "title": "userInterfaceIdiom",
      "type": "topic",
      "url": "/documentation/uikit/uitraitcollection/userinterfaceidiom"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitCollection/userInterfaceLevel": {
      "abstract": [
        {
          "text": "The elevation level of the interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userInterfaceLevel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIUserInterfaceLevel",
          "text": "UIUserInterfaceLevel"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitCollection/userInterfaceLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userInterfaceLevel"
        }
      ],
      "role": "symbol",
      "title": "userInterfaceLevel",
      "type": "topic",
      "url": "/documentation/uikit/uitraitcollection/userinterfacelevel"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitCollection/userInterfaceStyle": {
      "abstract": [
        {
          "text": "The style associated with the user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "userInterfaceStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIUserInterfaceStyle",
          "text": "UIUserInterfaceStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitCollection/userInterfaceStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "userInterfaceStyle"
        }
      ],
      "role": "symbol",
      "title": "userInterfaceStyle",
      "type": "topic",
      "url": "/documentation/uikit/uitraitcollection/userinterfacestyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitEnvironmentLayoutDirection": {
      "abstract": [
        {
          "text": "Constants that indicate the layout direction associated with the current environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITraitEnvironmentLayoutDirection"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitEnvironmentLayoutDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITraitEnvironmentLayoutDirection"
        }
      ],
      "role": "symbol",
      "title": "UITraitEnvironmentLayoutDirection",
      "type": "topic",
      "url": "/documentation/uikit/uitraitenvironmentlayoutdirection"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceActiveAppearance": {
      "abstract": [
        {
          "text": "Constants that indicate whether the user interface has an active appearance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIUserInterfaceActiveAppearance"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceActiveAppearance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserInterfaceActiveAppearance"
        }
      ],
      "role": "symbol",
      "title": "UIUserInterfaceActiveAppearance",
      "type": "topic",
      "url": "/documentation/uikit/uiuserinterfaceactiveappearance"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom": {
      "abstract": [
        {
          "text": "Constants that indicate the interface type for the device or an object that has a trait environment, such as a view and view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIUserInterfaceIdiom"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserInterfaceIdiom"
        }
      ],
      "role": "symbol",
      "title": "UIUserInterfaceIdiom",
      "type": "topic",
      "url": "/documentation/uikit/uiuserinterfaceidiom"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceLevel": {
      "abstract": [
        {
          "text": "Constants that indicate the visual level for content in the window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIUserInterfaceLevel"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceLevel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserInterfaceLevel"
        }
      ],
      "role": "symbol",
      "title": "UIUserInterfaceLevel",
      "type": "topic",
      "url": "/documentation/uikit/uiuserinterfacelevel"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceStyle": {
      "abstract": [
        {
          "text": "Constants that indicate the interface style for the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIUserInterfaceStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserInterfaceStyle"
        }
      ],
      "role": "symbol",
      "title": "UIUserInterfaceStyle",
      "type": "topic",
      "url": "/documentation/uikit/uiuserinterfacestyle"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Retrieving-interface-related-traits",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITraitCollection/userInterfaceStyle",
        "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceStyle",
        "doc://com.apple.uikit/documentation/UIKit/UITraitCollection/userInterfaceIdiom",
        "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom",
        "doc://com.apple.uikit/documentation/UIKit/UITraitCollection/userInterfaceLevel",
        "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceLevel",
        "doc://com.apple.uikit/documentation/UIKit/UITraitCollection/layoutDirection",
        "doc://com.apple.uikit/documentation/UIKit/UITraitEnvironmentLayoutDirection",
        "doc://com.apple.uikit/documentation/UIKit/UITraitCollection/accessibilityContrast",
        "doc://com.apple.uikit/documentation/UIKit/UITraitCollection/legibilityWeight",
        "doc://com.apple.uikit/documentation/UIKit/UILegibilityWeight",
        "doc://com.apple.uikit/documentation/UIKit/UITraitCollection/activeAppearance",
        "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceActiveAppearance",
        "doc://com.apple.uikit/documentation/UIKit/UITraitCollection/toolbarItemPresentationSize",
        "doc://com.apple.uikit/documentation/UIKit/UINSToolbarItemPresentationSize"
      ],
      "title": "Retrieving interface-related traits"
    }
  ],
  "topicSections": [
    {
      "anchor": "Contrast-settings",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContrast/unspecified",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContrast/normal",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContrast/high"
      ],
      "title": "Contrast settings"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContrast/init(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContrast/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIAccessibilityContrast"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityContrast"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityContrast"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Contrast-settings",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContrast/unspecified",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContrast/normal",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContrast/high"
              ],
              "title": "Contrast settings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Retrieving-interface-related-traits",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITraitCollection/userInterfaceStyle",
                "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceStyle",
                "doc://com.apple.uikit/documentation/UIKit/UITraitCollection/userInterfaceIdiom",
                "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom",
                "doc://com.apple.uikit/documentation/UIKit/UITraitCollection/userInterfaceLevel",
                "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceLevel",
                "doc://com.apple.uikit/documentation/UIKit/UITraitCollection/layoutDirection",
                "doc://com.apple.uikit/documentation/UIKit/UITraitEnvironmentLayoutDirection",
                "doc://com.apple.uikit/documentation/UIKit/UITraitCollection/accessibilityContrast",
                "doc://com.apple.uikit/documentation/UIKit/UITraitCollection/legibilityWeight",
                "doc://com.apple.uikit/documentation/UIKit/UILegibilityWeight",
                "doc://com.apple.uikit/documentation/UIKit/UITraitCollection/activeAppearance",
                "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceActiveAppearance",
                "doc://com.apple.uikit/documentation/UIKit/UITraitCollection/toolbarItemPresentationSize",
                "doc://com.apple.uikit/documentation/UIKit/UINSToolbarItemPresentationSize"
              ],
              "title": "Retrieving interface-related traits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIAccessibilityContrast"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceActiveAppearance/title",
          "value": "UIUserInterfaceActiveAppearance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceActiveAppearance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceActiveAppearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceActiveAppearance/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceActiveAppearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitCollection~1userInterfaceLevel/title",
          "value": "userInterfaceLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitCollection~1userInterfaceLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "userInterfaceLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitCollection~1legibilityWeight/title",
          "value": "legibilityWeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitCollection~1legibilityWeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "legibilityWeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceIdiom/title",
          "value": "UIUserInterfaceIdiom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceIdiom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceIdiom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceIdiom/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceIdiom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitCollection~1userInterfaceStyle/title",
          "value": "userInterfaceStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitCollection~1userInterfaceStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "userInterfaceStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINSToolbarItemPresentationSize/title",
          "value": "UINSToolbarItemPresentationSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINSToolbarItemPresentationSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UINSToolbarItemPresentationSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINSToolbarItemPresentationSize/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UINSToolbarItemPresentationSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitCollection~1userInterfaceIdiom/title",
          "value": "userInterfaceIdiom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitCollection~1userInterfaceIdiom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "userInterfaceIdiom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContrast~1unspecified/title",
          "value": "UIAccessibilityContrastUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContrast~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityContrastUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitCollection~1toolbarItemPresentationSize/title",
          "value": "toolbarItemPresentationSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitCollection~1toolbarItemPresentationSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "toolbarItemPresentationSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceStyle/title",
          "value": "UIUserInterfaceStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitCollection~1layoutDirection/title",
          "value": "layoutDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitCollection~1layoutDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "layoutDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitCollection~1accessibilityContrast/title",
          "value": "accessibilityContrast"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitCollection~1accessibilityContrast/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "accessibilityContrast"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitEnvironmentLayoutDirection/title",
          "value": "UITraitEnvironmentLayoutDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitEnvironmentLayoutDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITraitEnvironmentLayoutDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitEnvironmentLayoutDirection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITraitEnvironmentLayoutDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILegibilityWeight/title",
          "value": "UILegibilityWeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILegibilityWeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UILegibilityWeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILegibilityWeight/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILegibilityWeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceLevel/title",
          "value": "UIUserInterfaceLevel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceLevel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceLevel/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceLevel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContrast~1normal/title",
          "value": "UIAccessibilityContrastNormal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContrast~1normal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityContrastNormal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitCollection~1activeAppearance/title",
          "value": "activeAppearance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitCollection~1activeAppearance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "activeAppearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContrast/title",
          "value": "UIAccessibilityContrast"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContrast/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityContrast"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContrast/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityContrast"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContrast~1high/title",
          "value": "UIAccessibilityContrastHigh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContrast~1high/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityContrastHigh"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiaccessibilitycontrast"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiaccessibilitycontrast"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
