{"abstract":[{"text":"Specifies the style of an action sheet.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIActionSheetStyle"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","relationshipsSections":[{"kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/s:SY","doc://com.externally.resolved.symbol/s:s8SendableP"],"title":"Conforms To","type":"conformsTo"}],"variants":[{"paths":["/documentation/uikit/uiactionsheetstyle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uiactionsheetstyle"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"metadata":{"title":"UIActionSheetStyle","externalID":"c:@E@UIActionSheetStyle","role":"symbol","platforms":[{"unavailable":false,"deprecated":false,"deprecatedAt":"13.0","message":"UIActionSheet is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleActionSheet instead.","introducedAt":"2.0","name":"iOS","beta":false},{"unavailable":false,"deprecated":false,"deprecatedAt":"13.0","message":"UIActionSheet is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleActionSheet instead.","introducedAt":"2.0","name":"iPadOS","beta":false},{"unavailable":false,"deprecated":false,"deprecatedAt":"13.1","message":"UIActionSheet is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleActionSheet instead.","introducedAt":"13.1","name":"Mac Catalyst","beta":false}],"navigatorTitle":[{"text":"UIActionSheetStyle","kind":"identifier"}],"symbolKind":"enum","modules":[{"name":"UIKit"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIActionSheetStyle","kind":"identifier"}],"roleHeading":"Enumeration"},"topicSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIActionSheetStyle/automatic","doc://com.apple.uikit/documentation/UIKit/UIActionSheetStyle/default","doc://com.apple.uikit/documentation/UIKit/UIActionSheetStyle/blackTranslucent","doc://com.apple.uikit/documentation/UIKit/UIActionSheetStyle/blackOpaque"],"title":"Constants","anchor":"Constants"},{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIActionSheetStyle/init(rawValue:)"],"generated":true,"title":"Initializers","anchor":"Initializers"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIActionSheetStyle"}],"languages":["swift"]}]}],"references":{"doc://com.apple.uikit/documentation/UIKit/UIActionSheetStyle":{"type":"topic","abstract":[{"text":"Specifies the style of an action sheet.","type":"text"}],"url":"/documentation/uikit/uiactionsheetstyle","navigatorTitle":[{"text":"UIActionSheetStyle","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIActionSheetStyle","kind":"identifier"}],"role":"symbol","title":"UIActionSheetStyle","kind":"symbol","deprecated":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIActionSheetStyle"},"doc://com.externally.resolved.symbol/s:s8SendableP":{"abstract":[{"type":"text","text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races."}],"url":"/documentation/Swift/Sendable","identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}],"role":"symbol","title":"Sendable","type":"topic","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIActionSheetStyle/automatic":{"role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"automatic","kind":"identifier"}],"abstract":[{"type":"text","text":"Takes the appearance of the bottom bar if specified; otherwise, same as "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIActionSheetStyle/default"},{"type":"text","text":"."}],"deprecated":true,"type":"topic","title":"UIActionSheetStyle.automatic","navigatorTitle":[{"text":"UIActionSheetStyleAutomatic","kind":"identifier"}],"url":"/documentation/uikit/uiactionsheetstyle/automatic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIActionSheetStyle/automatic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIActionSheetStyle/init(rawValue:)":{"abstract":[],"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"url":"/documentation/uikit/uiactionsheetstyle/init(rawvalue:)","role":"symbol","title":"init(rawValue:)","deprecated":true,"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIActionSheetStyle/init(rawValue:)"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.externally.resolved.symbol/s:SY":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RawRepresentable"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:SY8RawValueQa","kind":"typeIdentifier","text":"RawValue"},{"kind":"text","text":">"}],"url":"/documentation/Swift/RawRepresentable","title":"RawRepresentable","abstract":[{"type":"text","text":"A type that can be converted to and from an associated raw value."}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SY"},"doc://com.apple.uikit/documentation/UIKit/UIActionSheetStyle/blackOpaque":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"blackOpaque","kind":"identifier"}],"abstract":[{"type":"text","text":"A black opaque style."}],"deprecated":true,"type":"topic","title":"UIActionSheetStyle.blackOpaque","navigatorTitle":[{"text":"UIActionSheetStyleBlackOpaque","kind":"identifier"}],"url":"/documentation/uikit/uiactionsheetstyle/blackopaque","identifier":"doc://com.apple.uikit/documentation/UIKit/UIActionSheetStyle/blackOpaque"},"doc://com.externally.resolved.symbol/s:SH":{"abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}],"url":"/documentation/Swift/Hashable","identifier":"doc://com.externally.resolved.symbol/s:SH","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hashable","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SQ","text":"Equatable","kind":"typeIdentifier"}],"role":"symbol","title":"Hashable","type":"topic","kind":"symbol"},"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP":{"title":"BitwiseCopyable","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BitwiseCopyable"},{"kind":"text","text":" : ~Escapable"}],"identifier":"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","role":"symbol","url":"/documentation/Swift/BitwiseCopyable","kind":"symbol","abstract":[{"type":"text","text":""}]},"doc://com.apple.uikit/documentation/UIKit/UIActionSheetStyle/blackTranslucent":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"blackTranslucent","kind":"identifier"}],"abstract":[{"text":"A black translucent style.","type":"text"}],"deprecated":true,"type":"topic","title":"UIActionSheetStyle.blackTranslucent","navigatorTitle":[{"kind":"identifier","text":"UIActionSheetStyleBlackTranslucent"}],"url":"/documentation/uikit/uiactionsheetstyle/blacktranslucent","identifier":"doc://com.apple.uikit/documentation/UIKit/UIActionSheetStyle/blackTranslucent"},"doc://com.externally.resolved.symbol/c:@T@NSInteger":{"abstract":[{"type":"text","text":"Describes an integer."}],"url":"/documentation/objectivec/nsinteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","fragments":[{"text":"typealias ","kind":"text"},{"text":"NSInteger","kind":"identifier"}],"role":"symbol","title":"NSInteger","type":"topic","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIActionSheetStyle/default":{"role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"`default`","kind":"identifier"}],"abstract":[{"type":"text","text":"The default style."}],"deprecated":true,"type":"topic","title":"UIActionSheetStyle.default","navigatorTitle":[{"text":"UIActionSheetStyleDefault","kind":"identifier"}],"url":"/documentation/uikit/uiactionsheetstyle/default","identifier":"doc://com.apple.uikit/documentation/UIKit/UIActionSheetStyle/default"},"doc://com.externally.resolved.symbol/s:SQ":{"abstract":[{"type":"text","text":"A type that can be compared for value equality."}],"url":"/documentation/Swift/Equatable","identifier":"doc://com.externally.resolved.symbol/s:SQ","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"role":"symbol","title":"Equatable","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"unavailable":false,"name":"iOS","deprecated":false,"beta":false,"deprecatedAt":"13.0","introducedAt":"2.0"},{"unavailable":false,"name":"iPadOS","deprecated":false,"beta":false,"deprecatedAt":"13.0","introducedAt":"2.0"},{"unavailable":false,"name":"Mac Catalyst","deprecated":false,"beta":false,"deprecatedAt":"13.1","introducedAt":"13.1"}]},{"op":"replace","path":"/metadata/roleHeading","value":"Enumeration"},{"op":"replace","path":"/metadata/title","value":"UIActionSheetStyle"},{"op":"replace","path":"/metadata/symbolKind","value":"enum"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"UIActionSheetStyle"}]},{"op":"replace","path":"/metadata/navigatorTitle","value":[{"kind":"identifier","text":"UIActionSheetStyle"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]}},{"op":"replace","path":"/topicSections","value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIActionSheetStyle/automatic","doc://com.apple.uikit/documentation/UIKit/UIActionSheetStyle/default","doc://com.apple.uikit/documentation/UIKit/UIActionSheetStyle/blackTranslucent","doc://com.apple.uikit/documentation/UIKit/UIActionSheetStyle/blackOpaque"],"title":"Constants","anchor":"Constants"}]},{"op":"replace","path":"/relationshipsSections","value":null},{"op":"add","path":"/seeAlsoSections","value":null},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UIActionSheetStyle"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"/deprecationSummary","op":"add","value":[]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheetStyle/title","op":"replace","value":"UIActionSheetStyle"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheetStyle/fragments","op":"replace","value":[{"kind":"identifier","text":"UIActionSheetStyle"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheetStyle/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIActionSheetStyle"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheetStyle~1automatic/title","op":"replace","value":"UIActionSheetStyleAutomatic"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheetStyle~1automatic/fragments","op":"replace","value":[{"text":"UIActionSheetStyleAutomatic","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheetStyle~1blackOpaque/title","op":"replace","value":"UIActionSheetStyleBlackOpaque"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheetStyle~1blackOpaque/fragments","op":"replace","value":[{"text":"UIActionSheetStyleBlackOpaque","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheetStyle~1blackTranslucent/title","op":"replace","value":"UIActionSheetStyleBlackTranslucent"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheetStyle~1blackTranslucent/fragments","op":"replace","value":[{"kind":"identifier","text":"UIActionSheetStyleBlackTranslucent"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheetStyle~1default/title","op":"replace","value":"UIActionSheetStyleDefault"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheetStyle~1default/fragments","op":"replace","value":[{"kind":"identifier","text":"UIActionSheetStyleDefault"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}