{
  "abstract": [
    {
      "text": "Provide a set of methods that view subclasses use to make subcomponents accessible as separate elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/accessibility-for-uikit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/uiaccessibilitycontainer"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "UIAccessibilityContainer"
  },
  "references": {
    "doc://com.apple.documentation/documentation/Accessibility/accessibility_design_for_mac_catalyst": {
      "abstract": [
        {
          "text": "Improve navigation in your app by using keyboard shortcuts and accessibility containers.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Accessibility/accessibility_design_for_mac_catalyst",
      "kind": "article",
      "role": "sampleCode",
      "title": "Accessibility design for Mac Catalyst",
      "type": "topic",
      "url": "/documentation/Accessibility/accessibility_design_for_mac_catalyst"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1615078-index": {
      "abstract": [
        {
          "text": "Returns the index of the specified accessibility element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "index"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "ofAccessibilityElement"
        },
        {
          "kind": "text",
          "text": ": Any) -> Int"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1615078-index",
      "kind": "symbol",
      "role": "symbol",
      "title": "index(ofAccessibilityElement:)",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1615078-index"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1615084-accessibilityelement": {
      "abstract": [
        {
          "text": "Returns the accessibility element at the specified index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "accessibilityElement"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": Int) -> Any?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1615084-accessibilityelement",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityElement(at:)",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1615084-accessibilityelement"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1615147-accessibilityelements": {
      "abstract": [
        {
          "text": "An array of the accessibility elements in the container. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "accessibilityElements"
        },
        {
          "kind": "text",
          "text": ": [Any]?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1615147-accessibilityelements",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityElements",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1615147-accessibilityelements"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1615149-accessibilityelementcount": {
      "abstract": [
        {
          "text": "Returns the number of accessibility elements in the container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "accessibilityElementCount"
        },
        {
          "kind": "text",
          "text": "() -> Int"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1615149-accessibilityelementcount",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityElementCount()",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1615149-accessibilityelementcount"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/2865802-accessibilitycontainertype": {
      "abstract": [
        {
          "text": "The type of container used for accessibility elements, such as tables or lists.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "accessibilityContainerType"
        },
        {
          "kind": "text",
          "text": ": UIAccessibilityContainerType"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/2865802-accessibilitycontainertype",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityContainerType",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/2865802-accessibilitycontainertype"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/4165627-automationelements": {
      "abstract": [
        {
          "text": "An array of the automation elements in the container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "automationElements"
        },
        {
          "kind": "text",
          "text": ": [Any]?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/4165627-automationelements",
      "kind": "symbol",
      "role": "symbol",
      "title": "automationElements",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/4165627-automationelements"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType": {
      "abstract": [
        {
          "text": "Constants that indicate the type of content in a data-based container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAccessibilityContainerType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityContainerType"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityContainerType",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycontainertype"
    },
    "doc://com.apple.uikit/documentation/UIKit/accessibility-for-uikit": {
      "abstract": [
        {
          "text": "Make your UIKit apps accessible to everyone who uses iOS and tvOS.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/accessibility-for-uikit",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Accessibility for UIKit",
      "type": "topic",
      "url": "/documentation/uikit/accessibility-for-uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/supporting-voiceover-in-your-app": {
      "abstract": [
        {
          "text": "Add VoiceOver support to make your iOS app more accessible to users who are blind or have low vision.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/supporting-voiceover-in-your-app",
      "kind": "article",
      "role": "article",
      "title": "Supporting VoiceOver in your app",
      "type": "topic",
      "url": "/documentation/uikit/supporting-voiceover-in-your-app"
    },
    "doc://com.apple.uikit/documentation/UIKit/uiaccessibility-protocol": {
      "abstract": [
        {
          "text": "A set of methods that provides accessibility information about views and controls in an app’s user interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/uiaccessibility-protocol",
      "kind": "article",
      "role": "collectionGroup",
      "title": "UIAccessibility",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility-protocol"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Essentials",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/uiaccessibility-protocol",
        "doc://com.apple.uikit/documentation/UIKit/supporting-voiceover-in-your-app"
      ],
      "title": "Essentials"
    }
  ],
  "topicSections": [
    {
      "anchor": "Providing-information-about-accessibility-elements",
      "identifiers": [
        "doc://com.apple.documentation/documentation/objectivec/nsobject/1615149-accessibilityelementcount",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/1615084-accessibilityelement",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/1615078-index",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/1615147-accessibilityelements",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/4165627-automationelements",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/2865802-accessibilitycontainertype",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType"
      ],
      "title": "Providing information about accessibility elements"
    },
    {
      "anchor": "Useful-links",
      "identifiers": [
        "doc://com.apple.documentation/documentation/Accessibility/accessibility_design_for_mac_catalyst"
      ],
      "title": "Useful links"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Providing-information-about-accessibility-elements",
              "identifiers": [
                "doc://com.apple.documentation/documentation/objectivec/nsobject/1615149-accessibilityelementcount",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/1615084-accessibilityelement",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/1615078-index",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/1615147-accessibilityelements",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/4165627-automationelements",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/2865802-accessibilitycontainertype",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityContainerType"
              ],
              "title": "Providing information about accessibility elements"
            },
            {
              "anchor": "Useful-links",
              "identifiers": [
                "doc://com.apple.documentation/documentation/Accessibility/accessibility_design_for_mac_catalyst"
              ],
              "title": "Useful links"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Essentials",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/uiaccessibility-protocol",
                "doc://com.apple.uikit/documentation/UIKit/supporting-voiceover-in-your-app"
              ],
              "title": "Essentials"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1objectivec~1nsobject~11615084-accessibilityelement/title",
          "value": "accessibilityElementAtIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1objectivec~1nsobject~11615149-accessibilityelementcount/title",
          "value": "accessibilityElementCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerType/title",
          "value": "UIAccessibilityContainerType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityContainerType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityContainerType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityContainerType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1objectivec~1nsobject~11615078-index/title",
          "value": "indexOfAccessibilityElement:"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiaccessibilitycontainer"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiaccessibilitycontainer"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
