{
  "abstract": [
    {
      "text": "Constants that describe how an accessibility element behaves.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@UIAccessibilityTraits",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIAccessibilityTraits"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIAccessibilityTraits"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "UIAccessibilityTraits"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIAccessibilityTraits"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Set these traits to tell an assistive app how an accessibility element behaves or how to treat it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1615093-accessibilityhint": {
      "abstract": [
        {
          "text": "A localized string that contains a brief description of the result of performing an action on the accessibility element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "accessibilityHint"
        },
        {
          "kind": "text",
          "text": ": String?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1615093-accessibilityhint",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityHint",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1615093-accessibilityhint"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1615117-accessibilityvalue": {
      "abstract": [
        {
          "text": "A localized string that contains the value of the accessibility element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "accessibilityValue"
        },
        {
          "kind": "text",
          "text": ": String?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1615117-accessibilityvalue",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityValue",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1615117-accessibilityvalue"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1615141-isaccessibilityelement": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the element is an accessibility element that an assistive app can access.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "isAccessibilityElement"
        },
        {
          "kind": "text",
          "text": ": Bool"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1615141-isaccessibilityelement",
      "kind": "symbol",
      "role": "symbol",
      "title": "isAccessibilityElement",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1615141-isaccessibilityelement"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1615181-accessibilitylabel": {
      "abstract": [
        {
          "text": "A succinct label in a localized string that identifies the accessibility element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "accessibilityLabel"
        },
        {
          "kind": "text",
          "text": ": String?"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1615181-accessibilitylabel",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityLabel",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1615181-accessibilitylabel"
    },
    "doc://com.apple.documentation/documentation/objectivec/nsobject/1615202-accessibilitytraits": {
      "abstract": [
        {
          "text": "The combination of accessibility traits that best characterizes the accessibility element. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "accessibilityTraits"
        },
        {
          "kind": "text",
          "text": ": UIAccessibilityTraits"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/objectivec/nsobject/1615202-accessibilitytraits",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityTraits",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject/1615202-accessibilitytraits"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits": {
      "abstract": [
        {
          "text": "Constants that describe how an accessibility element behaves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAccessibilityTraits"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityTraits"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityTraits",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitytraits"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/adjustable": {
      "abstract": [
        {
          "text": "The accessibility element allows continuous adjustment through a range of values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjustable"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityTraits",
          "text": "UIAccessibilityTraits"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/adjustable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityTraitAdjustable"
        }
      ],
      "role": "symbol",
      "title": "adjustable",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitytraits/adjustable"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/allowsDirectInteraction": {
      "abstract": [
        {
          "text": "The accessibility element allows direct touch interaction for VoiceOver users.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsDirectInteraction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityTraits",
          "text": "UIAccessibilityTraits"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/allowsDirectInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityTraitAllowsDirectInteraction"
        }
      ],
      "role": "symbol",
      "title": "allowsDirectInteraction",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitytraits/allowsdirectinteraction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/button": {
      "abstract": [
        {
          "text": "The accessibility element behaves like a button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "button"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityTraits",
          "text": "UIAccessibilityTraits"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/button",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityTraitButton"
        }
      ],
      "role": "symbol",
      "title": "button",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitytraits/button"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/causesPageTurn": {
      "abstract": [
        {
          "text": "The accessibility element causes an automatic page turn when VoiceOver finishes reading the text within it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "causesPageTurn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityTraits",
          "text": "UIAccessibilityTraits"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/causesPageTurn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityTraitCausesPageTurn"
        }
      ],
      "role": "symbol",
      "title": "causesPageTurn",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitytraits/causespageturn"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/header": {
      "abstract": [
        {
          "text": "The accessibility element is a header that divides content into sections, such as the title of a navigation bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "header"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityTraits",
          "text": "UIAccessibilityTraits"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/header",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityTraitHeader"
        }
      ],
      "role": "symbol",
      "title": "header",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitytraits/header"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/image": {
      "abstract": [
        {
          "text": "The accessibility element behaves like an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "image"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityTraits",
          "text": "UIAccessibilityTraits"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/image",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityTraitImage"
        }
      ],
      "role": "symbol",
      "title": "image",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitytraits/image"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/keyboardKey": {
      "abstract": [
        {
          "text": "The accessibility element behaves like a keyboard key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityTraits",
          "text": "UIAccessibilityTraits"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/keyboardKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityTraitKeyboardKey"
        }
      ],
      "role": "symbol",
      "title": "keyboardKey",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitytraits/keyboardkey"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/link": {
      "abstract": [
        {
          "text": "The accessibility element behaves like a link.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "link"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityTraits",
          "text": "UIAccessibilityTraits"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/link",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityTraitLink"
        }
      ],
      "role": "symbol",
      "title": "link",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitytraits/link"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/none": {
      "abstract": [
        {
          "text": "The accessibility element has no traits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityTraits",
          "text": "UIAccessibilityTraits"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityTraitNone"
        }
      ],
      "role": "symbol",
      "title": "none",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitytraits/none"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/notEnabled": {
      "abstract": [
        {
          "text": "The accessibility element isn’t in an enabled state and doesn’t respond to user interaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityTraits",
          "text": "UIAccessibilityTraits"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/notEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityTraitNotEnabled"
        }
      ],
      "role": "symbol",
      "title": "notEnabled",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitytraits/notenabled"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/playsSound": {
      "abstract": [
        {
          "text": "The accessibility element plays its own sound when the user activates it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playsSound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityTraits",
          "text": "UIAccessibilityTraits"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/playsSound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityTraitPlaysSound"
        }
      ],
      "role": "symbol",
      "title": "playsSound",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitytraits/playssound"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/searchField": {
      "abstract": [
        {
          "text": "The accessibility element behaves like a search field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchField"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityTraits",
          "text": "UIAccessibilityTraits"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/searchField",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityTraitSearchField"
        }
      ],
      "role": "symbol",
      "title": "searchField",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitytraits/searchfield"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/selected": {
      "abstract": [
        {
          "text": "The accessibility element is currently in a selected state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selected"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityTraits",
          "text": "UIAccessibilityTraits"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/selected",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityTraitSelected"
        }
      ],
      "role": "symbol",
      "title": "selected",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitytraits/selected"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/startsMediaSession": {
      "abstract": [
        {
          "text": "The accessibility element starts a media session when the user activates it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startsMediaSession"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityTraits",
          "text": "UIAccessibilityTraits"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/startsMediaSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityTraitStartsMediaSession"
        }
      ],
      "role": "symbol",
      "title": "startsMediaSession",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitytraits/startsmediasession"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/staticText": {
      "abstract": [
        {
          "text": "The accessibility element behaves like static text that can’t change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "staticText"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityTraits",
          "text": "UIAccessibilityTraits"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/staticText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityTraitStaticText"
        }
      ],
      "role": "symbol",
      "title": "staticText",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitytraits/statictext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/summaryElement": {
      "abstract": [
        {
          "text": "The accessibility element provides summary information when the app starts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "summaryElement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityTraits",
          "text": "UIAccessibilityTraits"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/summaryElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityTraitSummaryElement"
        }
      ],
      "role": "symbol",
      "title": "summaryElement",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitytraits/summaryelement"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/supportsZoom": {
      "abstract": [
        {
          "text": "The accessibility element supports zooming in and out on its content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsZoom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityTraits",
          "text": "UIAccessibilityTraits"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/supportsZoom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityTraitSupportsZoom"
        }
      ],
      "role": "symbol",
      "title": "supportsZoom",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitytraits/supportszoom"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/tabBar": {
      "abstract": [
        {
          "text": "The accessibility element behaves like a tab bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabBar"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityTraits",
          "text": "UIAccessibilityTraits"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/tabBar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityTraitTabBar"
        }
      ],
      "role": "symbol",
      "title": "tabBar",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitytraits/tabbar"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/toggleButton": {
      "abstract": [
        {
          "text": "The accessibility element behaves like a toggle button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "toggleButton"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityTraits",
          "text": "UIAccessibilityTraits"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/toggleButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityTraitToggleButton"
        }
      ],
      "role": "symbol",
      "title": "toggleButton",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitytraits/togglebutton"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/updatesFrequently": {
      "abstract": [
        {
          "text": "The accessibility element frequently updates its label or value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updatesFrequently"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityTraits",
          "text": "UIAccessibilityTraits"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/updatesFrequently",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityTraitUpdatesFrequently"
        }
      ],
      "role": "symbol",
      "title": "updatesFrequently",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitytraits/updatesfrequently"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Supporting-basic-accessibility",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/objectivec/nsobject/1615141-isaccessibilityelement",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/1615181-accessibilitylabel",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/1615117-accessibilityvalue",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/1615093-accessibilityhint",
        "doc://com.apple.documentation/documentation/objectivec/nsobject/1615202-accessibilitytraits"
      ],
      "title": "Supporting basic accessibility"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/none",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/button",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/link",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/image",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/searchField",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/toggleButton",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/keyboardKey",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/staticText",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/header",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/tabBar",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/summaryElement",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/selected",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/notEnabled",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/adjustable",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/allowsDirectInteraction",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/updatesFrequently",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/causesPageTurn",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/playsSound",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/startsMediaSession",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/supportsZoom"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIAccessibilityTraits"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/none",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/button",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/link",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/image",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/searchField",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/toggleButton",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/keyboardKey",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/staticText",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/header",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/tabBar",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/summaryElement",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/selected",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/notEnabled",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/adjustable",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/allowsDirectInteraction",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/updatesFrequently",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/causesPageTurn",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/playsSound",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/startsMediaSession",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityTraits/supportsZoom"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Supporting-basic-accessibility",
              "generated": true,
              "identifiers": [
                "doc://com.apple.documentation/documentation/objectivec/nsobject/1615141-isaccessibilityelement",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/1615181-accessibilitylabel",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/1615117-accessibilityvalue",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/1615093-accessibilityhint",
                "doc://com.apple.documentation/documentation/objectivec/nsobject/1615202-accessibilitytraits"
              ],
              "title": "Supporting basic accessibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint64_t",
                    "text": "uint64_t"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIAccessibilityTraits"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1staticText/title",
          "value": "UIAccessibilityTraitStaticText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1staticText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityTraitStaticText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1startsMediaSession/title",
          "value": "UIAccessibilityTraitStartsMediaSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1startsMediaSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityTraitStartsMediaSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1toggleButton/title",
          "value": "UIAccessibilityTraitToggleButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1toggleButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityTraitToggleButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1causesPageTurn/title",
          "value": "UIAccessibilityTraitCausesPageTurn"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1causesPageTurn/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityTraitCausesPageTurn"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1playsSound/title",
          "value": "UIAccessibilityTraitPlaysSound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1playsSound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityTraitPlaysSound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1summaryElement/title",
          "value": "UIAccessibilityTraitSummaryElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1summaryElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityTraitSummaryElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1none/title",
          "value": "UIAccessibilityTraitNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityTraitNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1adjustable/title",
          "value": "UIAccessibilityTraitAdjustable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1adjustable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityTraitAdjustable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1image/title",
          "value": "UIAccessibilityTraitImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1image/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityTraitImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1notEnabled/title",
          "value": "UIAccessibilityTraitNotEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1notEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityTraitNotEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1searchField/title",
          "value": "UIAccessibilityTraitSearchField"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1searchField/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityTraitSearchField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits/title",
          "value": "UIAccessibilityTraits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1tabBar/title",
          "value": "UIAccessibilityTraitTabBar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1tabBar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityTraitTabBar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1button/title",
          "value": "UIAccessibilityTraitButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1button/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityTraitButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1keyboardKey/title",
          "value": "UIAccessibilityTraitKeyboardKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1keyboardKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityTraitKeyboardKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1allowsDirectInteraction/title",
          "value": "UIAccessibilityTraitAllowsDirectInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1allowsDirectInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityTraitAllowsDirectInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1selected/title",
          "value": "UIAccessibilityTraitSelected"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1selected/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityTraitSelected"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1updatesFrequently/title",
          "value": "UIAccessibilityTraitUpdatesFrequently"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1updatesFrequently/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityTraitUpdatesFrequently"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1link/title",
          "value": "UIAccessibilityTraitLink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1link/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityTraitLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1supportsZoom/title",
          "value": "UIAccessibilityTraitSupportsZoom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1supportsZoom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityTraitSupportsZoom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1header/title",
          "value": "UIAccessibilityTraitHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityTraits~1header/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityTraitHeader"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiaccessibilitytraits"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiaccessibilitytraits"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
