{
  "abstract": [
    {
      "text": "A context-sensitive function that helps VoiceOver users find the next instance of a related element.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIAccessibilityCustomRotor",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIAccessibilityCustomRotor"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIAccessibilityCustomRotor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "UIAccessibilityCustomRotor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomRotor"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You might use an instance of this class to find the next link in an article, or the next misspelled word in a document.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Session 10116: ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/wwdc20/10116",
                  "isActive": true,
                  "type": "reference"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Related Sessions from WWDC20",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor": {
      "abstract": [
        {
          "text": "A context-sensitive function that helps VoiceOver users find the next instance of a related element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAccessibilityCustomRotor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityCustomRotor"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityCustomRotor",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomrotor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/Direction": {
      "abstract": [
        {
          "text": "Constants that indicate the search direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Direction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/Direction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Direction"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityCustomRotor.Direction",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomrotor/direction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/Search": {
      "abstract": [
        {
          "text": "The block type for retrieving the next or previous rotor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Search"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/Search",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Search"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityCustomRotor.Search",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomrotor/search"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum": {
      "abstract": [
        {
          "text": "Constants that indicate the type of content that the rotor represents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SystemRotorType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SystemRotorType"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityCustomRotor.SystemRotorType",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomrotor/systemrotortype-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/attributedName": {
      "abstract": [
        {
          "text": "The name of the rotor as an attributed string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attributedName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/attributedName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attributedName"
        }
      ],
      "role": "symbol",
      "title": "attributedName",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomrotor/attributedname"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/init(attributedName:itemSearch:)": {
      "abstract": [
        {
          "text": "Creates a rotor with the specified name and search block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "attributedName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "itemSearch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIAccessibilityCustomRotor",
          "text": "UIAccessibilityCustomRotor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityCustomRotorSearch",
          "text": "Search"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/init(attributedName:itemSearch:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithAttributedName:itemSearchBlock:"
        }
      ],
      "role": "symbol",
      "title": "init(attributedName:itemSearch:)",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomrotor/init(attributedname:itemsearch:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/init(name:itemSearch:)": {
      "abstract": [
        {
          "text": "Creates a rotor with the specified name and search block.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "itemSearch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIAccessibilityCustomRotor",
          "text": "UIAccessibilityCustomRotor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityCustomRotorSearch",
          "text": "Search"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/init(name:itemSearch:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithName:itemSearchBlock:"
        }
      ],
      "role": "symbol",
      "title": "init(name:itemSearch:)",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomrotor/init(name:itemsearch:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/init(systemType:itemSearch:)": {
      "abstract": [
        {
          "text": "Creates a rotor for the specified type of item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "systemType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIAccessibilityCustomRotor",
          "text": "UIAccessibilityCustomRotor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIAccessibilityCustomSystemRotorType",
          "text": "SystemRotorType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "itemSearch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIAccessibilityCustomRotor",
          "text": "UIAccessibilityCustomRotor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityCustomRotorSearch",
          "text": "Search"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/init(systemType:itemSearch:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithSystemType:itemSearchBlock:"
        }
      ],
      "role": "symbol",
      "title": "init(systemType:itemSearch:)",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomrotor/init(systemtype:itemsearch:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/itemSearchBlock": {
      "abstract": [
        {
          "text": "The block for retrieving the next or previous rotor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "itemSearchBlock"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIAccessibilityCustomRotor",
          "text": "UIAccessibilityCustomRotor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIAccessibilityCustomRotorSearch",
          "text": "Search"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/itemSearchBlock",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "itemSearchBlock"
        }
      ],
      "role": "symbol",
      "title": "itemSearchBlock",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomrotor/itemsearchblock"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/name": {
      "abstract": [
        {
          "text": "The name of the rotor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "name"
        }
      ],
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomrotor/name"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/systemRotorType-swift.property": {
      "abstract": [
        {
          "text": "The type of content that the rotor searches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemRotorType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIAccessibilityCustomRotor",
          "text": "UIAccessibilityCustomRotor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIAccessibilityCustomSystemRotorType",
          "text": "SystemRotorType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/systemRotorType-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "systemRotorType"
        }
      ],
      "role": "symbol",
      "title": "systemRotorType",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomrotor/systemrotortype-swift.property"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotorItemResult": {
      "abstract": [
        {
          "text": "A target element that a custom rotor references.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAccessibilityCustomRotorItemResult"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotorItemResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityCustomRotorItemResult"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityCustomRotorItemResult",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomrotoritemresult"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotorSearchPredicate": {
      "abstract": [
        {
          "text": "The search parameters that help determine the next matching custom rotor item result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAccessibilityCustomRotorSearchPredicate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotorSearchPredicate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityCustomRotorSearchPredicate"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityCustomRotorSearchPredicate",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilitycustomrotorsearchpredicate"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "https://developer.apple.com/wwdc20/10116": {
      "identifier": "https://developer.apple.com/wwdc20/10116",
      "title": "VoiceOver Efficiency with Custom Rotors",
      "titleInlineContent": [
        {
          "text": "VoiceOver Efficiency with Custom Rotors",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/wwdc20/10116"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Navigation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotorItemResult",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotorSearchPredicate"
      ],
      "title": "Navigation"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-rotor-object",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/init(attributedName:itemSearch:)",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/init(name:itemSearch:)",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/init(systemType:itemSearch:)"
      ],
      "title": "Creating a rotor object"
    },
    {
      "anchor": "Navigating-to-the-next-item",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/itemSearchBlock",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/Search",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/Direction"
      ],
      "title": "Navigating to the next item"
    },
    {
      "anchor": "Getting-the-rotor-type",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/systemRotorType-swift.property",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum"
      ],
      "title": "Getting the rotor type"
    },
    {
      "anchor": "Identifying-the-rotor",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/name",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/attributedName"
      ],
      "title": "Identifying the rotor"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIAccessibilityCustomRotor"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomRotor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomRotor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-rotor-object",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/init(attributedName:itemSearch:)",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/init(name:itemSearch:)",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/init(systemType:itemSearch:)"
              ],
              "title": "Creating a rotor object"
            },
            {
              "anchor": "Navigating-to-the-next-item",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/itemSearchBlock",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/Search",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/Direction"
              ],
              "title": "Navigating to the next item"
            },
            {
              "anchor": "Getting-the-rotor-type",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/systemRotorType-swift.property",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/SystemRotorType-swift.enum"
              ],
              "title": "Getting the rotor type"
            },
            {
              "anchor": "Identifying-the-rotor",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/name",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotor/attributedName"
              ],
              "title": "Identifying the rotor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Navigation",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotorItemResult",
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityCustomRotorSearchPredicate"
              ],
              "title": "Navigation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIAccessibilityCustomRotor"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotorSearchPredicate/title",
          "value": "UIAccessibilityCustomRotorSearchPredicate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotorSearchPredicate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomRotorSearchPredicate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotorSearchPredicate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomRotorSearchPredicate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1systemRotorType-swift.property/title",
          "value": "systemRotorType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1systemRotorType-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "systemRotorType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1name/title",
          "value": "name"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "name"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotorItemResult/title",
          "value": "UIAccessibilityCustomRotorItemResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotorItemResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomRotorItemResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotorItemResult/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomRotorItemResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1Direction/title",
          "value": "UIAccessibilityCustomRotorDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1Direction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomRotorDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1Direction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomRotorDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor/title",
          "value": "UIAccessibilityCustomRotor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomRotor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomRotor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1SystemRotorType-swift.enum/title",
          "value": "UIAccessibilityCustomSystemRotorType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1SystemRotorType-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomSystemRotorType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1SystemRotorType-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomSystemRotorType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1itemSearchBlock/title",
          "value": "itemSearchBlock"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1itemSearchBlock/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "itemSearchBlock"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1init(attributedName:itemSearch:)/title",
          "value": "initWithAttributedName:itemSearchBlock:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1init(attributedName:itemSearch:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithAttributedName:itemSearchBlock:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1init(name:itemSearch:)/title",
          "value": "initWithName:itemSearchBlock:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1init(name:itemSearch:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithName:itemSearchBlock:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1attributedName/title",
          "value": "attributedName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1attributedName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "attributedName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1Search/title",
          "value": "UIAccessibilityCustomRotorSearch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1Search/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomRotorSearch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1Search/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityCustomRotorSearch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1init(systemType:itemSearch:)/title",
          "value": "initWithSystemType:itemSearchBlock:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityCustomRotor~1init(systemType:itemSearch:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithSystemType:itemSearchBlock:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiaccessibilitycustomrotor"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiaccessibilitycustomrotor"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
