{
  "abstract": [
    {
      "text": "Review unsupported symbols and their replacements.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/app-and-environment",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/uiapplication-deprecated-symbols"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Deprecated symbols"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication": {
      "abstract": [
        {
          "text": "The centralized point of control and coordination for apps running in iOS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIApplication"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplication"
        }
      ],
      "role": "symbol",
      "title": "UIApplication",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/applicationIconBadgeNumber": {
      "abstract": [
        {
          "text": "The number currently set as the badge of the app icon on the Home screen.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationIconBadgeNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/applicationIconBadgeNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applicationIconBadgeNumber"
        }
      ],
      "role": "symbol",
      "title": "applicationIconBadgeNumber",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/applicationiconbadgenumber"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/beginIgnoringInteractionEvents()": {
      "abstract": [
        {
          "text": "Tells the receiver to suspend the handling of touch-related events.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginIgnoringInteractionEvents"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/beginIgnoringInteractionEvents()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beginIgnoringInteractionEvents"
        }
      ],
      "role": "symbol",
      "title": "beginIgnoringInteractionEvents()",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/beginignoringinteractionevents()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/cancelAllLocalNotifications()": {
      "abstract": [
        {
          "text": "Cancels the delivery of all scheduled local notifications.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelAllLocalNotifications"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/cancelAllLocalNotifications()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cancelAllLocalNotifications"
        }
      ],
      "role": "symbol",
      "title": "cancelAllLocalNotifications()",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/cancelalllocalnotifications()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/cancelLocalNotification(_:)": {
      "abstract": [
        {
          "text": "Cancels the delivery of the specified scheduled local notification.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelLocalNotification"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UILocalNotification",
          "text": "UILocalNotification"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/cancelLocalNotification(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cancelLocalNotification:"
        }
      ],
      "role": "symbol",
      "title": "cancelLocalNotification(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/cancellocalnotification(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/clearKeepAliveTimeout()": {
      "abstract": [
        {
          "text": "Removes a previously installed periodic handler block.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clearKeepAliveTimeout"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/clearKeepAliveTimeout()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clearKeepAliveTimeout"
        }
      ],
      "role": "symbol",
      "title": "clearKeepAliveTimeout()",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/clearkeepalivetimeout()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/currentUserNotificationSettings": {
      "abstract": [
        {
          "text": "Returns the user notification settings for the app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentUserNotificationSettings"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIUserNotificationSettings",
          "text": "UIUserNotificationSettings"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/currentUserNotificationSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentUserNotificationSettings"
        }
      ],
      "role": "symbol",
      "title": "currentUserNotificationSettings",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/currentusernotificationsettings"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/didChangeStatusBarFrameNotification": {
      "abstract": [
        {
          "text": "Posted when the frame of the status bar changes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didChangeStatusBarFrameNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/didChangeStatusBarFrameNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationDidChangeStatusBarFrameNotification"
        }
      ],
      "role": "symbol",
      "title": "didChangeStatusBarFrameNotification",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/didchangestatusbarframenotification"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/didChangeStatusBarOrientationNotification": {
      "abstract": [
        {
          "text": "Posted when the orientation of the app’s user interface changes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didChangeStatusBarOrientationNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/didChangeStatusBarOrientationNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationDidChangeStatusBarOrientationNotification"
        }
      ],
      "role": "symbol",
      "title": "didChangeStatusBarOrientationNotification",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/didchangestatusbarorientationnotification"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/enabledRemoteNotificationTypes()": {
      "abstract": [
        {
          "text": "Returns the types of notifications the app accepts.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enabledRemoteNotificationTypes"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIRemoteNotificationType",
          "text": "UIRemoteNotificationType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/enabledRemoteNotificationTypes()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enabledRemoteNotificationTypes"
        }
      ],
      "role": "symbol",
      "title": "enabledRemoteNotificationTypes()",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/enabledremotenotificationtypes()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/endIgnoringInteractionEvents()": {
      "abstract": [
        {
          "text": "Tells the receiver to resume the handling of touch-related events.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endIgnoringInteractionEvents"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/endIgnoringInteractionEvents()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "endIgnoringInteractionEvents"
        }
      ],
      "role": "symbol",
      "title": "endIgnoringInteractionEvents()",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/endignoringinteractionevents()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/isIgnoringInteractionEvents": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the receiver is ignoring events initiated by touches on the screen.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isIgnoringInteractionEvents"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/isIgnoringInteractionEvents",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ignoringInteractionEvents"
        }
      ],
      "role": "symbol",
      "title": "isIgnoringInteractionEvents",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/isignoringinteractionevents"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/isNetworkActivityIndicatorVisible": {
      "abstract": [
        {
          "text": "A Boolean value that turns an indicator of network activity on or off.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isNetworkActivityIndicatorVisible"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/isNetworkActivityIndicatorVisible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "networkActivityIndicatorVisible"
        }
      ],
      "role": "symbol",
      "title": "isNetworkActivityIndicatorVisible",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/isnetworkactivityindicatorvisible"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/isStatusBarHidden": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the status bar is hidden.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isStatusBarHidden"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/isStatusBarHidden",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "statusBarHidden"
        }
      ],
      "role": "symbol",
      "title": "isStatusBarHidden",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/isstatusbarhidden"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/keyWindow": {
      "abstract": [
        {
          "text": "The app’s key window.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyWindow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIWindow",
          "text": "UIWindow"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/keyWindow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "keyWindow"
        }
      ],
      "role": "symbol",
      "title": "keyWindow",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/keywindow"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/openURL(_:)": {
      "abstract": [
        {
          "text": "Attempts to open the resource at the specified URL.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openURL"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/openURL(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "openURL:"
        }
      ],
      "role": "symbol",
      "title": "openURL(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/openurl(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/presentLocalNotificationNow(_:)": {
      "abstract": [
        {
          "text": "Presents a local notification immediately.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "presentLocalNotificationNow"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UILocalNotification",
          "text": "UILocalNotification"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/presentLocalNotificationNow(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "presentLocalNotificationNow:"
        }
      ],
      "role": "symbol",
      "title": "presentLocalNotificationNow(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/presentlocalnotificationnow(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/proximitySensingEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether proximity sensing is enabled.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "proximitySensingEnabled"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/proximitySensingEnabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "proximitySensingEnabled",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/proximitysensingenabled"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/registerForRemoteNotifications(matching:)": {
      "abstract": [
        {
          "text": "Register to receive remote notifications of the specified types via Apple Push Notification service.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "registerForRemoteNotifications"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "matching"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIRemoteNotificationType",
          "text": "UIRemoteNotificationType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/registerForRemoteNotifications(matching:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "registerForRemoteNotificationTypes:"
        }
      ],
      "role": "symbol",
      "title": "registerForRemoteNotifications(matching:)",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/registerforremotenotifications(matching:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/registerUserNotificationSettings(_:)": {
      "abstract": [
        {
          "text": "Registers your preferred options for notifying the user.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "registerUserNotificationSettings"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIUserNotificationSettings",
          "text": "UIUserNotificationSettings"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/registerUserNotificationSettings(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "registerUserNotificationSettings:"
        }
      ],
      "role": "symbol",
      "title": "registerUserNotificationSettings(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/registerusernotificationsettings(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/requestSceneSessionActivation(_:userActivity:options:errorHandler:)": {
      "abstract": [
        {
          "text": "Asks the system to activate an existing scene, or create a new scene and associate it with your app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestSceneSessionActivation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISceneSession",
          "text": "UISceneSession"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "userActivity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUserActivity",
          "text": "NSUserActivity"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIScene",
          "text": "UIScene"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISceneActivationRequestOptions",
          "text": "ActivationRequestOptions"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "errorHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/requestSceneSessionActivation(_:userActivity:options:errorHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestSceneSessionActivation:userActivity:options:errorHandler:"
        }
      ],
      "role": "symbol",
      "title": "requestSceneSessionActivation(_:userActivity:options:errorHandler:)",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/requestscenesessionactivation(_:useractivity:options:errorhandler:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/scheduleLocalNotification(_:)": {
      "abstract": [
        {
          "text": "Schedules a local notification for delivery at its encapsulated date and time.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scheduleLocalNotification"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UILocalNotification",
          "text": "UILocalNotification"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/scheduleLocalNotification(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scheduleLocalNotification:"
        }
      ],
      "role": "symbol",
      "title": "scheduleLocalNotification(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/schedulelocalnotification(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/scheduledLocalNotifications": {
      "abstract": [
        {
          "text": "All currently scheduled local notifications.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scheduledLocalNotifications"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UILocalNotification",
          "text": "UILocalNotification"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/scheduledLocalNotifications",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scheduledLocalNotifications"
        }
      ],
      "role": "symbol",
      "title": "scheduledLocalNotifications",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/scheduledlocalnotifications"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/setKeepAliveTimeout(_:handler:)": {
      "abstract": [
        {
          "text": "Configures a periodic handler for VoIP apps in older versions of iOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setKeepAliveTimeout"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": (() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/setKeepAliveTimeout(_:handler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setKeepAliveTimeout:handler:"
        }
      ],
      "role": "symbol",
      "title": "setKeepAliveTimeout(_:handler:)",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/setkeepalivetimeout(_:handler:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/setMinimumBackgroundFetchInterval(_:)": {
      "abstract": [
        {
          "text": "Specifies the minimum amount of time that must elapse between background fetch operations.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setMinimumBackgroundFetchInterval"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/setMinimumBackgroundFetchInterval(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setMinimumBackgroundFetchInterval:"
        }
      ],
      "role": "symbol",
      "title": "setMinimumBackgroundFetchInterval(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/setminimumbackgroundfetchinterval(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/setNewsstandIconImage(_:)": {
      "abstract": [
        {
          "text": "Sets the icon of a Newsstand app to an image depicting the current issue of a publication.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setNewsstandIconImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/setNewsstandIconImage(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setNewsstandIconImage:"
        }
      ],
      "role": "symbol",
      "title": "setNewsstandIconImage(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/setnewsstandiconimage(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/setStatusBarHidden(_:with:)": {
      "abstract": [
        {
          "text": "Hides or shows the status bar, optionally animating the transition.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setStatusBarHidden"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIStatusBarAnimation",
          "text": "UIStatusBarAnimation"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/setStatusBarHidden(_:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setStatusBarHidden:withAnimation:"
        }
      ],
      "role": "symbol",
      "title": "setStatusBarHidden(_:with:)",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/setstatusbarhidden(_:with:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/setStatusBarHidden:animated:": {
      "abstract": [
        {
          "text": "Hides or shows the status bar, optionally animating the transition.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setStatusBarHidden:animated:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/setStatusBarHidden:animated:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setStatusBarHidden:animated:"
        }
      ],
      "role": "symbol",
      "title": "setStatusBarHidden:animated:",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/setstatusbarhidden:animated:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/setStatusBarOrientation(_:animated:)": {
      "abstract": [
        {
          "text": "Sets the app’s status bar to the specified orientation, optionally animating the transition.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setStatusBarOrientation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIInterfaceOrientation",
          "text": "UIInterfaceOrientation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "animated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/setStatusBarOrientation(_:animated:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setStatusBarOrientation:animated:"
        }
      ],
      "role": "symbol",
      "title": "setStatusBarOrientation(_:animated:)",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/setstatusbarorientation(_:animated:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/setStatusBarStyle(_:animated:)": {
      "abstract": [
        {
          "text": "Sets the style of the status bar, optionally animating the transition to the new style.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setStatusBarStyle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIStatusBarStyle",
          "text": "UIStatusBarStyle"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "animated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/setStatusBarStyle(_:animated:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setStatusBarStyle:animated:"
        }
      ],
      "role": "symbol",
      "title": "setStatusBarStyle(_:animated:)",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/setstatusbarstyle(_:animated:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarFrame": {
      "abstract": [
        {
          "text": "The frame rectangle defining the area of the status bar.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusBarFrame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "statusBarFrame"
        }
      ],
      "role": "symbol",
      "title": "statusBarFrame",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/statusbarframe"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarFrameUserInfoKey": {
      "abstract": [
        {
          "text": "A key whose value indicates the new status bar frame.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusBarFrameUserInfoKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarFrameUserInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationStatusBarFrameUserInfoKey"
        }
      ],
      "role": "symbol",
      "title": "statusBarFrameUserInfoKey",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/statusbarframeuserinfokey"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarOrientation": {
      "abstract": [
        {
          "text": "The current orientation of the app’s status bar.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusBarOrientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIInterfaceOrientation",
          "text": "UIInterfaceOrientation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "statusBarOrientation"
        }
      ],
      "role": "symbol",
      "title": "statusBarOrientation",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/statusbarorientation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarOrientationAnimationDuration": {
      "abstract": [
        {
          "text": "The animation duration in seconds for the status bar during a 90 degree orientation change.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusBarOrientationAnimationDuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarOrientationAnimationDuration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "statusBarOrientationAnimationDuration"
        }
      ],
      "role": "symbol",
      "title": "statusBarOrientationAnimationDuration",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/statusbarorientationanimationduration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarOrientationUserInfoKey": {
      "abstract": [
        {
          "text": "A key whose value indicates the current interface orientation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusBarOrientationUserInfoKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarOrientationUserInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationStatusBarOrientationUserInfoKey"
        }
      ],
      "role": "symbol",
      "title": "statusBarOrientationUserInfoKey",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/statusbarorientationuserinfokey"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarStyle": {
      "abstract": [
        {
          "text": "The current style of the status bar.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "statusBarStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIStatusBarStyle",
          "text": "UIStatusBarStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "statusBarStyle"
        }
      ],
      "role": "symbol",
      "title": "statusBarStyle",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/statusbarstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/willChangeStatusBarFrameNotification": {
      "abstract": [
        {
          "text": "Posted when the app is about to change the frame of the status bar.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "willChangeStatusBarFrameNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/willChangeStatusBarFrameNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationWillChangeStatusBarFrameNotification"
        }
      ],
      "role": "symbol",
      "title": "willChangeStatusBarFrameNotification",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/willchangestatusbarframenotification"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/willChangeStatusBarOrientationNotification": {
      "abstract": [
        {
          "text": "Posted when the app is about to change the orientation of its interface.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "willChangeStatusBarOrientationNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/willChangeStatusBarOrientationNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationWillChangeStatusBarOrientationNotification"
        }
      ],
      "role": "symbol",
      "title": "willChangeStatusBarOrientationNotification",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/willchangestatusbarorientationnotification"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/windows": {
      "abstract": [
        {
          "text": "The app’s visible and hidden windows.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "windows"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIWindow",
          "text": "UIWindow"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/windows",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "windows"
        }
      ],
      "role": "symbol",
      "title": "windows",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/windows"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMinimumKeepAliveTimeout": {
      "abstract": [
        {
          "text": "The minimum amount of time (measured in seconds) an app may run a critical background task in the background.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIMinimumKeepAliveTimeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMinimumKeepAliveTimeout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIMinimumKeepAliveTimeout"
        }
      ],
      "role": "symbol",
      "title": "UIMinimumKeepAliveTimeout",
      "type": "topic",
      "url": "/documentation/uikit/uiminimumkeepalivetimeout"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType": {
      "abstract": [
        {
          "text": "Constants indicating the types of notifications the app may display to the user.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIRemoteNotificationType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIRemoteNotificationType"
        }
      ],
      "role": "symbol",
      "title": "UIRemoteNotificationType",
      "type": "topic",
      "url": "/documentation/uikit/uiremotenotificationtype"
    },
    "doc://com.apple.uikit/documentation/UIKit/app-and-environment": {
      "abstract": [
        {
          "text": "Manage life-cycle events and your app’s UI scenes, and get information about traits and the environment in which your app runs.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/app-and-environment",
      "kind": "article",
      "role": "collectionGroup",
      "title": "App and environment",
      "type": "topic",
      "url": "/documentation/uikit/app-and-environment"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Deprecated-methods",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/requestSceneSessionActivation(_:userActivity:options:errorHandler:)",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/beginIgnoringInteractionEvents()",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/endIgnoringInteractionEvents()",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/setMinimumBackgroundFetchInterval(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/scheduleLocalNotification(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/presentLocalNotificationNow(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/cancelLocalNotification(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/cancelAllLocalNotifications()",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/setKeepAliveTimeout(_:handler:)",
        "doc://com.apple.uikit/documentation/UIKit/UIMinimumKeepAliveTimeout",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/clearKeepAliveTimeout()",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/setStatusBarHidden(_:with:)",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/setStatusBarStyle(_:animated:)",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/setStatusBarOrientation(_:animated:)",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/registerUserNotificationSettings(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/registerForRemoteNotifications(matching:)",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/enabledRemoteNotificationTypes()",
        "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/openURL(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/setNewsstandIconImage(_:)"
      ],
      "title": "Deprecated methods"
    },
    {
      "anchor": "Deprecated-notifications",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/willChangeStatusBarFrameNotification",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/didChangeStatusBarFrameNotification",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/willChangeStatusBarOrientationNotification",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/didChangeStatusBarOrientationNotification"
      ],
      "title": "Deprecated notifications"
    },
    {
      "anchor": "Deprecated-properties",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/applicationIconBadgeNumber",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarFrameUserInfoKey",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarOrientationUserInfoKey",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/currentUserNotificationSettings",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/isIgnoringInteractionEvents",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/isNetworkActivityIndicatorVisible",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/isStatusBarHidden",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/keyWindow",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/scheduledLocalNotifications",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarFrame",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarOrientation",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarOrientationAnimationDuration",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarStyle",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/windows"
      ],
      "title": "Deprecated properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Deprecated-methods",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/requestSceneSessionActivation(_:userActivity:options:errorHandler:)",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/beginIgnoringInteractionEvents()",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/endIgnoringInteractionEvents()",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/setMinimumBackgroundFetchInterval(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/scheduleLocalNotification(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/presentLocalNotificationNow(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/cancelLocalNotification(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/cancelAllLocalNotifications()",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/setKeepAliveTimeout(_:handler:)",
                "doc://com.apple.uikit/documentation/UIKit/UIMinimumKeepAliveTimeout",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/clearKeepAliveTimeout()",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/setStatusBarHidden:animated:",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/setStatusBarHidden(_:with:)",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/setStatusBarStyle(_:animated:)",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/setStatusBarOrientation(_:animated:)",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/registerUserNotificationSettings(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/registerForRemoteNotifications(matching:)",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/enabledRemoteNotificationTypes()",
                "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/openURL(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/setNewsstandIconImage(_:)"
              ],
              "title": "Deprecated methods"
            },
            {
              "anchor": "Deprecated-notifications",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/willChangeStatusBarFrameNotification",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/didChangeStatusBarFrameNotification",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/willChangeStatusBarOrientationNotification",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/didChangeStatusBarOrientationNotification"
              ],
              "title": "Deprecated notifications"
            },
            {
              "anchor": "Deprecated-properties",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/applicationIconBadgeNumber",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarFrameUserInfoKey",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarOrientationUserInfoKey",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/currentUserNotificationSettings",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/isIgnoringInteractionEvents",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/isNetworkActivityIndicatorVisible",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/proximitySensingEnabled",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/isStatusBarHidden",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/keyWindow",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/scheduledLocalNotifications",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarFrame",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarOrientation",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarOrientationAnimationDuration",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/statusBarStyle",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/windows"
              ],
              "title": "Deprecated properties"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1statusBarOrientation/title",
          "value": "statusBarOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1statusBarOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "statusBarOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1setStatusBarStyle(_:animated:)/title",
          "value": "setStatusBarStyle:animated:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1setStatusBarStyle(_:animated:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setStatusBarStyle:animated:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1statusBarStyle/title",
          "value": "statusBarStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1statusBarStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "statusBarStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1setKeepAliveTimeout(_:handler:)/title",
          "value": "setKeepAliveTimeout:handler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1setKeepAliveTimeout(_:handler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setKeepAliveTimeout:handler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRemoteNotificationType/title",
          "value": "UIRemoteNotificationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRemoteNotificationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIRemoteNotificationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRemoteNotificationType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIRemoteNotificationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1setMinimumBackgroundFetchInterval(_:)/title",
          "value": "setMinimumBackgroundFetchInterval:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1setMinimumBackgroundFetchInterval(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setMinimumBackgroundFetchInterval:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1statusBarOrientationUserInfoKey/title",
          "value": "UIApplicationStatusBarOrientationUserInfoKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1statusBarOrientationUserInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationStatusBarOrientationUserInfoKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMinimumKeepAliveTimeout/title",
          "value": "UIMinimumKeepAliveTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMinimumKeepAliveTimeout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMinimumKeepAliveTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1requestSceneSessionActivation(_:userActivity:options:errorHandler:)/title",
          "value": "requestSceneSessionActivation:userActivity:options:errorHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1requestSceneSessionActivation(_:userActivity:options:errorHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestSceneSessionActivation:userActivity:options:errorHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1openURL(_:)/title",
          "value": "openURL:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1openURL(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "openURL:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1enabledRemoteNotificationTypes()/title",
          "value": "enabledRemoteNotificationTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1enabledRemoteNotificationTypes()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "enabledRemoteNotificationTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1beginIgnoringInteractionEvents()/title",
          "value": "beginIgnoringInteractionEvents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1beginIgnoringInteractionEvents()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "beginIgnoringInteractionEvents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1didChangeStatusBarOrientationNotification/title",
          "value": "UIApplicationDidChangeStatusBarOrientationNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1didChangeStatusBarOrientationNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationDidChangeStatusBarOrientationNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1registerUserNotificationSettings(_:)/title",
          "value": "registerUserNotificationSettings:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1registerUserNotificationSettings(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "registerUserNotificationSettings:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1willChangeStatusBarOrientationNotification/title",
          "value": "UIApplicationWillChangeStatusBarOrientationNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1willChangeStatusBarOrientationNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationWillChangeStatusBarOrientationNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1registerForRemoteNotifications(matching:)/title",
          "value": "registerForRemoteNotificationTypes:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1registerForRemoteNotifications(matching:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "registerForRemoteNotificationTypes:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1isIgnoringInteractionEvents/title",
          "value": "ignoringInteractionEvents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1isIgnoringInteractionEvents/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ignoringInteractionEvents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1isStatusBarHidden/title",
          "value": "statusBarHidden"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1isStatusBarHidden/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "statusBarHidden"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1cancelAllLocalNotifications()/title",
          "value": "cancelAllLocalNotifications"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1cancelAllLocalNotifications()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cancelAllLocalNotifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1statusBarFrame/title",
          "value": "statusBarFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1statusBarFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "statusBarFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1endIgnoringInteractionEvents()/title",
          "value": "endIgnoringInteractionEvents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1endIgnoringInteractionEvents()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "endIgnoringInteractionEvents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1isNetworkActivityIndicatorVisible/title",
          "value": "networkActivityIndicatorVisible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1isNetworkActivityIndicatorVisible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "networkActivityIndicatorVisible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/title",
          "value": "UIApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplication"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1scheduledLocalNotifications/title",
          "value": "scheduledLocalNotifications"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1scheduledLocalNotifications/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scheduledLocalNotifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1statusBarOrientationAnimationDuration/title",
          "value": "statusBarOrientationAnimationDuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1statusBarOrientationAnimationDuration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "statusBarOrientationAnimationDuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1keyWindow/title",
          "value": "keyWindow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1keyWindow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "keyWindow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1applicationIconBadgeNumber/title",
          "value": "applicationIconBadgeNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1applicationIconBadgeNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "applicationIconBadgeNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1presentLocalNotificationNow(_:)/title",
          "value": "presentLocalNotificationNow:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1presentLocalNotificationNow(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "presentLocalNotificationNow:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1statusBarFrameUserInfoKey/title",
          "value": "UIApplicationStatusBarFrameUserInfoKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1statusBarFrameUserInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationStatusBarFrameUserInfoKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1windows/title",
          "value": "windows"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1windows/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "windows"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1setStatusBarHidden(_:with:)/title",
          "value": "setStatusBarHidden:withAnimation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1setStatusBarHidden(_:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setStatusBarHidden:withAnimation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1didChangeStatusBarFrameNotification/title",
          "value": "UIApplicationDidChangeStatusBarFrameNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1didChangeStatusBarFrameNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationDidChangeStatusBarFrameNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1setNewsstandIconImage(_:)/title",
          "value": "setNewsstandIconImage:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1setNewsstandIconImage(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setNewsstandIconImage:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1willChangeStatusBarFrameNotification/title",
          "value": "UIApplicationWillChangeStatusBarFrameNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1willChangeStatusBarFrameNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationWillChangeStatusBarFrameNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1setStatusBarOrientation(_:animated:)/title",
          "value": "setStatusBarOrientation:animated:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1setStatusBarOrientation(_:animated:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setStatusBarOrientation:animated:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1cancelLocalNotification(_:)/title",
          "value": "cancelLocalNotification:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1cancelLocalNotification(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cancelLocalNotification:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1scheduleLocalNotification(_:)/title",
          "value": "scheduleLocalNotification:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1scheduleLocalNotification(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scheduleLocalNotification:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1currentUserNotificationSettings/title",
          "value": "currentUserNotificationSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1currentUserNotificationSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentUserNotificationSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1clearKeepAliveTimeout()/title",
          "value": "clearKeepAliveTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1clearKeepAliveTimeout()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "clearKeepAliveTimeout"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiapplication-deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiapplication-deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
