{
  "abstract": [
    {
      "text": "A string that identifies errors the system encounters when it determines if your app is the default in a category.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIApplicationCategoryDefaultErrorDomain"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@UIApplicationCategoryDefaultErrorDomain",
    "fragments": [
      {
        "kind": "identifier",
        "text": "UIApplicationCategoryDefaultErrorDomain"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIApplicationCategoryDefaultErrorDomain"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.2",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "UIApplicationCategoryDefaultErrorDomain"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSErrorDomain",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSErrorDomain",
              "text": "NSErrorDomain"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIApplicationCategoryDefaultErrorDomain"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/Category": {
      "abstract": [
        {
          "text": "Constants that describe the types of apps in the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Category"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/Category",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Category"
        }
      ],
      "role": "symbol",
      "title": "UIApplication.Category",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/category"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/defaultStatusForCategory:error:": {
      "abstract": [
        {
          "text": "Reports whether this app is the person’s default app in the given category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "defaultStatusForCategory:error:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/defaultStatusForCategory:error:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultStatusForCategory:error:"
        }
      ],
      "role": "symbol",
      "title": "defaultStatusForCategory:error:",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/defaultstatusforcategory:error:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationCategoryDefaultErrorDomain": {
      "abstract": [
        {
          "text": "A string that identifies errors the system encounters when it determines if your app is the default in a category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIApplicationCategoryDefaultErrorDomain"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationCategoryDefaultErrorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIApplicationCategoryDefaultErrorDomain",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationcategorydefaulterrordomain"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationCategoryDefaultRetryAvailabilityDateErrorKey": {
      "abstract": [
        {
          "text": "A dictionary key, with a value that’s a date when a result is next available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIApplicationCategoryDefaultRetryAvailabilityDateErrorKey"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationCategoryDefaultRetryAvailabilityDateErrorKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIApplicationCategoryDefaultRetryAvailabilityDateErrorKey",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationcategorydefaultretryavailabilitydateerrorkey"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationCategoryDefaultStatus": {
      "abstract": [
        {
          "text": "The default status of an application for some category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIApplicationCategoryDefaultStatus"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationCategoryDefaultStatus",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIApplicationCategoryDefaultStatus",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationcategorydefaultstatus"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationCategoryDefaultStatusLastProvidedDateErrorKey": {
      "abstract": [
        {
          "text": "A dictionary key, with a value that’s the date your app last received a successful result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIApplicationCategoryDefaultStatusLastProvidedDateErrorKey"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationCategoryDefaultStatusLastProvidedDateErrorKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIApplicationCategoryDefaultStatusLastProvidedDateErrorKey",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationcategorydefaultstatuslastprovideddateerrorkey"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSErrorDomain": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSErrorDomain"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSErrorDomain",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSErrorDomain",
      "type": "topic",
      "url": "/documentation/foundation/nserrordomain"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Discovering-if-your-app-is-the-default-app-in-a-category",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/defaultStatusForCategory:error:",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationCategoryDefaultStatus",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/Category",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationCategoryDefaultRetryAvailabilityDateErrorKey",
        "doc://com.apple.uikit/documentation/UIKit/UIApplicationCategoryDefaultStatusLastProvidedDateErrorKey"
      ],
      "title": "Discovering if your app is the default app in a category"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1Category/title",
          "value": "UIApplicationCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1Category/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1Category/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationCategory"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiapplicationcategorydefaulterrordomain"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
