{"metadata":{"roleHeading":"API Collection","modules":[{"name":"UIKit"}],"role":"collectionGroup","title":"Deprecated symbols"},"kind":"article","topicSections":[{"anchor":"Deprecated","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didRegister:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didReceive:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didReceiveRemoteNotification:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleActionWithIdentifier:for:completionHandler:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleActionWithIdentifier:for:withResponseInfo:completionHandler:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleActionWithIdentifier:forRemoteNotification:completionHandler:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleActionWithIdentifier:forRemoteNotification:withResponseInfo:completionHandler:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleOpen:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:open:sourceApplication:annotation:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:willChangeStatusBarOrientation:duration:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didChangeStatusBarOrientation:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:willChangeStatusBarFrame:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didChangeStatusBarFrame:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handle:completionHandler:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:performFetchWithCompletionHandler:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:shouldSaveApplicationState:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:shouldRestoreApplicationState:)"],"title":"Deprecated"}],"abstract":[{"text":"Symbols that are no longer supported.","type":"text"}],"seeAlsoSections":[{"title":"Deprecated","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationDidFinishLaunching(_:)"],"anchor":"Deprecated","generated":true}],"variants":[{"paths":["/documentation/uikit/uiapplicationdelegate-deprecated-symbols"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uiapplicationdelegate-deprecated-symbols"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/uiapplicationdelegate-deprecated-symbols"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/app-and-environment","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate"],["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/app-and-environment","doc://com.apple.uikit/documentation/UIKit/UIApplication","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate"]]},"references":{"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:willChangeStatusBarOrientation:duration:)":{"navigatorTitle":[{"text":"application:willChangeStatusBarOrientation:duration:","kind":"identifier"}],"abstract":[{"text":"Tells the delegate when the interface orientation of the status bar is about to change.","type":"text"}],"kind":"symbol","title":"application(_:willChangeStatusBarOrientation:duration:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"application","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"willChangeStatusBarOrientation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIInterfaceOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIInterfaceOrientation"},{"text":", ","kind":"text"},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":")","kind":"text"}],"deprecated":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:willChangeStatusBarOrientation:duration:)","type":"topic","url":"/documentation/uikit/uiapplicationdelegate/application(_:willchangestatusbarorientation:duration:)","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didChangeStatusBarOrientation:)":{"url":"/documentation/uikit/uiapplicationdelegate/application(_:didchangestatusbarorientation:)","navigatorTitle":[{"kind":"identifier","text":"application:didChangeStatusBarOrientation:"}],"deprecated":true,"type":"topic","title":"application(_:didChangeStatusBarOrientation:)","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didChangeStatusBarOrientation:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeStatusBarOrientation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIInterfaceOrientation","preciseIdentifier":"c:@E@UIInterfaceOrientation"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[{"type":"text","text":"Tells the delegate when the interface orientation of the status bar has changed."}]},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didReceive:)":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didReceive:)","abstract":[{"text":"Sent to the delegate when a running app receives a local notification.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"application","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILocalNotification","preciseIdentifier":"c:objc(cs)UILocalNotification"},{"kind":"text","text":")"}],"type":"topic","title":"application(_:didReceive:)","url":"/documentation/uikit/uiapplicationdelegate/application(_:didreceive:)","role":"symbol","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"application:didReceiveLocalNotification:"}],"kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didReceiveRemoteNotification:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"application","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveRemoteNotification"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"])"}],"url":"/documentation/uikit/uiapplicationdelegate/application(_:didreceiveremotenotification:)","abstract":[{"type":"text","text":"Called when your app has received a remote notification."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"application:didReceiveRemoteNotification:"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didReceiveRemoteNotification:)","deprecated":true,"type":"topic","title":"application(_:didReceiveRemoteNotification:)"},"doc://com.apple.uikit/documentation/UIKit/UIApplication":{"kind":"symbol","role":"symbol","title":"UIApplication","navigatorTitle":[{"text":"UIApplication","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIApplication","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication","url":"/documentation/uikit/uiapplication","abstract":[{"type":"text","text":"The centralized point of control and coordination for apps running in iOS."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:performFetchWithCompletionHandler:)":{"title":"application(_:performFetchWithCompletionHandler:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:performFetchWithCompletionHandler:)","abstract":[{"text":"Tells the app that it can begin a fetch operation if it has data to download.","type":"text"}],"url":"/documentation/uikit/uiapplicationdelegate/application(_:performfetchwithcompletionhandler:)","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"application:performFetchWithCompletionHandler:"}],"role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"application","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"performFetchWithCompletionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"UIBackgroundFetchResult","preciseIdentifier":"c:@E@UIBackgroundFetchResult"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/app-and-environment":{"role":"collectionGroup","title":"App and environment","identifier":"doc://com.apple.uikit/documentation/UIKit/app-and-environment","type":"topic","url":"/documentation/uikit/app-and-environment","kind":"article","abstract":[{"text":"Manage life-cycle events and your app’s UI scenes, and get information about traits and the environment in which your app runs.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handle:completionHandler:)":{"url":"/documentation/uikit/uiapplicationdelegate/application(_:handle:completionhandler:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier","text":"UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"handle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"INIntent","preciseIdentifier":"c:objc(cs)INIntent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"INIntentResponse","preciseIdentifier":"c:objc(cs)INIntentResponse"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"deprecated":true,"title":"application(_:handle:completionHandler:)","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Asks the delegate to handle the specified SiriKit intent directly."}],"navigatorTitle":[{"kind":"identifier","text":"application:handleIntent:completionHandler:"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handle:completionHandler:)","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didRegister:)":{"abstract":[{"type":"text","text":"Called to tell the delegate the types of local and remote notifications that can be used to get the user’s attention."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier","text":"UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRegister"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIUserNotificationSettings","kind":"typeIdentifier","text":"UIUserNotificationSettings"},{"kind":"text","text":")"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didRegister:)","kind":"symbol","type":"topic","title":"application(_:didRegister:)","role":"symbol","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"application:didRegisterUserNotificationSettings:"}],"url":"/documentation/uikit/uiapplicationdelegate/application(_:didregister:)"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:shouldRestoreApplicationState:)":{"role":"symbol","abstract":[{"type":"text","text":"Asks the delegate whether to restore the app’s saved state."}],"url":"/documentation/uikit/uiapplicationdelegate/application(_:shouldrestoreapplicationstate:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"application","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"text":", ","kind":"text"},{"text":"shouldRestoreApplicationState","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"application(_:shouldRestoreApplicationState:)","deprecated":true,"navigatorTitle":[{"text":"application:shouldRestoreApplicationState:","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:shouldRestoreApplicationState:)","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleActionWithIdentifier:forRemoteNotification:completionHandler:)":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleActionWithIdentifier:forRemoteNotification:completionHandler:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"application:handleActionWithIdentifier:forRemoteNotification:completionHandler:"}],"role":"symbol","deprecated":true,"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"application","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIApplication","text":"UIApplication","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"handleActionWithIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forRemoteNotification"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"title":"application(_:handleActionWithIdentifier:forRemoteNotification:completionHandler:)","abstract":[{"type":"text","text":"Tells the app delegate to perform the custom action specified by a remote notification."}],"url":"/documentation/uikit/uiapplicationdelegate/application(_:handleactionwithidentifier:forremotenotification:completionhandler:)"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didChangeStatusBarFrame:)":{"abstract":[{"text":"Tells the delegate when the frame of the status bar has changed.","type":"text"}],"title":"application(_:didChangeStatusBarFrame:)","type":"topic","url":"/documentation/uikit/uiapplicationdelegate/application(_:didchangestatusbarframe:)","navigatorTitle":[{"kind":"identifier","text":"application:didChangeStatusBarFrame:"}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didChangeStatusBarFrame:)","deprecated":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier","text":"UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeStatusBarFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate":{"role":"symbol","abstract":[{"text":"A set of methods to manage shared behaviors for your app.","type":"text"}],"url":"/documentation/uikit/uiapplicationdelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UIApplicationDelegate"}],"title":"UIApplicationDelegate","navigatorTitle":[{"text":"UIApplicationDelegate","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleActionWithIdentifier:for:completionHandler:)":{"deprecated":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleActionWithIdentifier:for:completionHandler:)","title":"application(_:handleActionWithIdentifier:for:completionHandler:)","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Called when your app has been activated because user selected a custom action from the alert panel of a local notification."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"text":"(","kind":"text"},{"text":"UIApplication","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication"},{"text":", ","kind":"text"},{"text":"handleActionWithIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UILocalNotification","preciseIdentifier":"c:objc(cs)UILocalNotification"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"application:handleActionWithIdentifier:forLocalNotification:completionHandler:"}],"url":"/documentation/uikit/uiapplicationdelegate/application(_:handleactionwithidentifier:for:completionhandler:)","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationDidFinishLaunching(_:)":{"kind":"symbol","abstract":[{"type":"text","text":"Tells the delegate when the app has finished launching."}],"url":"/documentation/uikit/uiapplicationdelegate/applicationdidfinishlaunching(_:)","type":"topic","deprecated":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"applicationDidFinishLaunching","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIApplication","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationDidFinishLaunching(_:)","title":"applicationDidFinishLaunching(_:)","navigatorTitle":[{"text":"applicationDidFinishLaunching:","kind":"identifier"}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleOpen:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"application:handleOpenURL:"}],"deprecated":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"application","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIApplication","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication"},{"text":", ","kind":"text"},{"text":"handleOpen","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"/documentation/uikit/uiapplicationdelegate/application(_:handleopen:)","abstract":[{"type":"text","text":"Asks the delegate to open a resource identified by URL."}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleOpen:)","title":"application(_:handleOpen:)"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleActionWithIdentifier:for:withResponseInfo:completionHandler:)":{"deprecated":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleActionWithIdentifier:for:withResponseInfo:completionHandler:)","title":"application(_:handleActionWithIdentifier:for:withResponseInfo:completionHandler:)","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Called when your app has been activated by the user selecting an action from a local notification."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"application","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIApplication","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIApplication"},{"text":", ","kind":"text"},{"text":"handleActionWithIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UILocalNotification","preciseIdentifier":"c:objc(cs)UILocalNotification"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withResponseInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"application:handleActionWithIdentifier:forLocalNotification:withResponseInfo:completionHandler:"}],"url":"/documentation/uikit/uiapplicationdelegate/application(_:handleactionwithidentifier:for:withresponseinfo:completionhandler:)","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:shouldSaveApplicationState:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldSaveApplicationState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"deprecated":true,"type":"topic","abstract":[{"text":"Asks the delegate whether to preserve the app’s state.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:shouldSaveApplicationState:)","navigatorTitle":[{"kind":"identifier","text":"application:shouldSaveApplicationState:"}],"role":"symbol","title":"application(_:shouldSaveApplicationState:)","url":"/documentation/uikit/uiapplicationdelegate/application(_:shouldsaveapplicationstate:)"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:open:sourceApplication:annotation:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier","text":"UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"open"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sourceApplication"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"annotation"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"url":"/documentation/uikit/uiapplicationdelegate/application(_:open:sourceapplication:annotation:)","title":"application(_:open:sourceApplication:annotation:)","navigatorTitle":[{"kind":"identifier","text":"application:openURL:sourceApplication:annotation:"}],"deprecated":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:open:sourceApplication:annotation:)","abstract":[{"text":"Asks the delegate to open a resource identified by a URL.","type":"text"}],"kind":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleActionWithIdentifier:forRemoteNotification:withResponseInfo:completionHandler:)":{"url":"/documentation/uikit/uiapplicationdelegate/application(_:handleactionwithidentifier:forremotenotification:withresponseinfo:completionhandler:)","navigatorTitle":[{"kind":"identifier","text":"application:handleActionWithIdentifier:forRemoteNotification:withResponseInfo:completionHandler:"}],"deprecated":true,"type":"topic","title":"application(_:handleActionWithIdentifier:forRemoteNotification:withResponseInfo:completionHandler:)","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleActionWithIdentifier:forRemoteNotification:withResponseInfo:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier","text":"UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"handleActionWithIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forRemoteNotification"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"withResponseInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[{"text":"Called when your app has been activated by the user selecting an action from a remote notification.","type":"text"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:willChangeStatusBarFrame:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"application:willChangeStatusBarFrame:"}],"deprecated":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"application","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willChangeStatusBarFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"url":"/documentation/uikit/uiapplicationdelegate/application(_:willchangestatusbarframe:)","abstract":[{"type":"text","text":"Tells the delegate when the frame of the status bar is about to change."}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:willChangeStatusBarFrame:)","title":"application(_:willChangeStatusBarFrame:)"}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"path":"/topicSections","value":[{"anchor":"Deprecated","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didRegister:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didReceive:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didReceiveRemoteNotification:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleActionWithIdentifier:for:completionHandler:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleActionWithIdentifier:for:withResponseInfo:completionHandler:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleActionWithIdentifier:forRemoteNotification:completionHandler:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleActionWithIdentifier:forRemoteNotification:withResponseInfo:completionHandler:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleOpen:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:open:sourceApplication:annotation:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:willChangeStatusBarOrientation:duration:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didChangeStatusBarOrientation:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:willChangeStatusBarFrame:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:didChangeStatusBarFrame:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handle:completionHandler:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:performFetchWithCompletionHandler:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:shouldSaveApplicationState:)","doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:shouldRestoreApplicationState:)"],"title":"Deprecated"}],"op":"replace"},{"path":"/seeAlsoSections","value":[{"anchor":"Deprecated","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/applicationDidFinishLaunching(_:)"],"title":"Deprecated"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:willChangeStatusBarOrientation:duration:)/title","value":"application:willChangeStatusBarOrientation:duration:","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:willChangeStatusBarOrientation:duration:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"application:willChangeStatusBarOrientation:duration:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:didChangeStatusBarOrientation:)/title","value":"application:didChangeStatusBarOrientation:","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:didChangeStatusBarOrientation:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"application:didChangeStatusBarOrientation:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"application:didReceiveLocalNotification:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:didReceive:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:didReceiveLocalNotification:"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:didReceive:)/fragments"},{"op":"replace","value":"application:didReceiveRemoteNotification:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:didReceiveRemoteNotification:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"application:didReceiveRemoteNotification:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:didReceiveRemoteNotification:)/fragments"},{"op":"replace","value":"UIApplication","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIApplication"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/fragments"},{"op":"replace","value":[{"text":"UIApplication","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/navigatorTitle"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:performFetchWithCompletionHandler:)/title","op":"replace","value":"application:performFetchWithCompletionHandler:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:performFetchWithCompletionHandler:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:performFetchWithCompletionHandler:"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:handle:completionHandler:)/title","op":"replace","value":"application:handleIntent:completionHandler:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:handle:completionHandler:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"application:handleIntent:completionHandler:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:didRegister:)/title","op":"replace","value":"application:didRegisterUserNotificationSettings:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:didRegister:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"application:didRegisterUserNotificationSettings:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:shouldRestoreApplicationState:)/title","op":"replace","value":"application:shouldRestoreApplicationState:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:shouldRestoreApplicationState:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:shouldRestoreApplicationState:"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:handleActionWithIdentifier:forRemoteNotification:completionHandler:)/title","op":"replace","value":"application:handleActionWithIdentifier:forRemoteNotification:completionHandler:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:handleActionWithIdentifier:forRemoteNotification:completionHandler:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:handleActionWithIdentifier:forRemoteNotification:completionHandler:"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:didChangeStatusBarFrame:)/title","op":"replace","value":"application:didChangeStatusBarFrame:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:didChangeStatusBarFrame:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"application:didChangeStatusBarFrame:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate/title","op":"replace","value":"UIApplicationDelegate"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate/fragments","op":"replace","value":[{"kind":"identifier","text":"UIApplicationDelegate"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate/navigatorTitle","op":"replace","value":[{"text":"UIApplicationDelegate","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:handleActionWithIdentifier:for:completionHandler:)/title","op":"replace","value":"application:handleActionWithIdentifier:forLocalNotification:completionHandler:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:handleActionWithIdentifier:for:completionHandler:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:handleActionWithIdentifier:forLocalNotification:completionHandler:"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1applicationDidFinishLaunching(_:)/title","op":"replace","value":"applicationDidFinishLaunching:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1applicationDidFinishLaunching(_:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"applicationDidFinishLaunching:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:handleOpen:)/title","op":"replace","value":"application:handleOpenURL:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:handleOpen:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"application:handleOpenURL:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:handleActionWithIdentifier:for:withResponseInfo:completionHandler:)/title","op":"replace","value":"application:handleActionWithIdentifier:forLocalNotification:withResponseInfo:completionHandler:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:handleActionWithIdentifier:for:withResponseInfo:completionHandler:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:handleActionWithIdentifier:forLocalNotification:withResponseInfo:completionHandler:"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:shouldSaveApplicationState:)/title","op":"replace","value":"application:shouldSaveApplicationState:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:shouldSaveApplicationState:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"application:shouldSaveApplicationState:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:open:sourceApplication:annotation:)/title","op":"replace","value":"application:openURL:sourceApplication:annotation:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:open:sourceApplication:annotation:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"application:openURL:sourceApplication:annotation:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:handleActionWithIdentifier:forRemoteNotification:withResponseInfo:completionHandler:)/title","op":"replace","value":"application:handleActionWithIdentifier:forRemoteNotification:withResponseInfo:completionHandler:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:handleActionWithIdentifier:forRemoteNotification:withResponseInfo:completionHandler:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:handleActionWithIdentifier:forRemoteNotification:withResponseInfo:completionHandler:"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:willChangeStatusBarFrame:)/title","op":"replace","value":"application:willChangeStatusBarFrame:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:willChangeStatusBarFrame:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"application:willChangeStatusBarFrame:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}