{
  "abstract": [
    {
      "text": "An object that tracks the selection of multiple items using pointer-based input.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIBandSelectionInteraction",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIBandSelectionInteraction"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIBandSelectionInteraction"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "UIBandSelectionInteraction"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIBandSelectionInteraction"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Attach a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object to a custom view that contains one or more selectable items. On devices with pointer-based input, such as an iPad with a Magic Keyboard, this interaction object displays a visible selection rectangle over the view when someone clicks and drags on it. As the pointer moves, the selection rectangle expands or contracts to match. Use your interaction object’s handler to select items based on the current selection rectangle.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You create a band selection interaction object and add it to a view that contains one or more selectable items. When you create the interaction object, specify a handler to process changes to the selection rectangle. In the example, the custom view defines an ",
              "type": "text"
            },
            {
              "code": "itemsInRect",
              "type": "codeVoice"
            },
            {
              "text": " method to get the items that intersect the selection rectangle. It also defines custom methods to modify the selection and commit the changes. If someone presses the Shift key at the start of the interaction, the code extends the current selection instead of replacing it.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "// Create a UIBandSelectionInteraction object.",
            "let bandSelectionInteraction = UIBandSelectionInteraction { [weak self] interaction in",
            "    guard let strongSelf = self else { return }",
            "    ",
            "    switch interaction.state {",
            "    case .began:",
            "        // Prepare the view to handle selection changes.",
            "        strongSelf.selectionSession.begin()",
            "    case .selecting:",
            "        // Get the custom view items that intersect the selection rectangle.",
            "        let newItems = strongSelf.itemsInRect(interaction.selectionRect)",
            "        ",
            "        if interaction.initialModifierFlags == .shift {",
            "            // If Shift is held, extend the view's current selection...",
            "            strongSelf.selectionSession.append(newItems)",
            "        } else {",
            "            // ...otherwise, replace the view's selection with the new items.",
            "            strongSelf.selectionSession.setSelection(newItems)",
            "        }",
            "    case .ended:",
            "        // When the interaction ends, commit the selection changes.",
            "        strongSelf.selectionSession.commit()",
            "    }",
            "}",
            "    ",
            "// Add the interaction object to the view.",
            "view.addInteraction(bandSelectionInteraction)"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "You don’t need to add this interaction object to a collection view to handle the selection of items. ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionView",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " already supports its own multiple selection interface. For a list of methods you use to manage selections in a collection view, see ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegate",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction": {
      "abstract": [
        {
          "text": "An object that tracks the selection of multiple items using pointer-based input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIBandSelectionInteraction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBandSelectionInteraction"
        }
      ],
      "role": "symbol",
      "title": "UIBandSelectionInteraction",
      "type": "topic",
      "url": "/documentation/uikit/uibandselectioninteraction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/State-swift.enum": {
      "abstract": [
        {
          "text": "Constants that indicate whether a band selection interaction object is inactive or currently tracking an interaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "State"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/State-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "State"
        }
      ],
      "role": "symbol",
      "title": "UIBandSelectionInteraction.State",
      "type": "topic",
      "url": "/documentation/uikit/uibandselectioninteraction/state-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/init(_:)": {
      "abstract": [
        {
          "text": "Creates a new band selection interaction object with the provided handler code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "(("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIBandSelectionInteraction",
          "text": "UIBandSelectionInteraction"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/init(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithSelectionHandler:"
        }
      ],
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uibandselectioninteraction/init(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/initialModifierFlags": {
      "abstract": [
        {
          "text": "The pressed modifier keys at the start of the interaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "initialModifierFlags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIKeyModifierFlags",
          "text": "UIKeyModifierFlags"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/initialModifierFlags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initialModifierFlags"
        }
      ],
      "role": "symbol",
      "title": "initialModifierFlags",
      "type": "topic",
      "url": "/documentation/uikit/uibandselectioninteraction/initialmodifierflags"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/isEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that specifies whether the object is ready to detect interactions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/isEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enabled"
        }
      ],
      "role": "symbol",
      "title": "isEnabled",
      "type": "topic",
      "url": "/documentation/uikit/uibandselectioninteraction/isenabled"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/selectionRect-1fj7p": {
      "abstract": [
        {
          "text": "The selection rectangle for an in-progress interaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "selectionRect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/selectionRect-1fj7p",
      "kind": "symbol",
      "role": "symbol",
      "title": "selectionRect",
      "type": "topic",
      "url": "/documentation/uikit/uibandselectioninteraction/selectionrect-1fj7p"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/selectionRect-2us5d": {
      "abstract": [
        {
          "text": "The selection rectangle for an in-progress interaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectionRect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/selectionRect-2us5d",
      "kind": "symbol",
      "role": "symbol",
      "title": "selectionRect",
      "type": "topic",
      "url": "/documentation/uikit/uibandselectioninteraction/selectionrect-2us5d"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/shouldBeginHandler": {
      "abstract": [
        {
          "text": "The handler that determines whether to start a band selection interaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shouldBeginHandler"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIBandSelectionInteraction",
          "text": "UIBandSelectionInteraction"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/shouldBeginHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shouldBeginHandler"
        }
      ],
      "role": "symbol",
      "title": "shouldBeginHandler",
      "type": "topic",
      "url": "/documentation/uikit/uibandselectioninteraction/shouldbeginhandler"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/state-swift.property": {
      "abstract": [
        {
          "text": "The current state of the interaction object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "state"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIBandSelectionInteraction",
          "text": "UIBandSelectionInteraction"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIBandSelectionInteractionState",
          "text": "State"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/state-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "state"
        }
      ],
      "role": "symbol",
      "title": "state",
      "type": "topic",
      "url": "/documentation/uikit/uibandselectioninteraction/state-swift.property"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionView": {
      "abstract": [
        {
          "text": "An object that manages an ordered collection of data items and presents them using customizable layouts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionView"
        }
      ],
      "role": "symbol",
      "title": "UICollectionView",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegate": {
      "abstract": [
        {
          "text": "The methods adopted by the object you use to manage user interactions with items in a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewDelegate"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIInteraction": {
      "abstract": [
        {
          "text": "The protocol that an interaction implements to access the view that owns it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIInteraction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIInteraction"
        }
      ],
      "role": "symbol",
      "title": "UIInteraction",
      "type": "topic",
      "url": "/documentation/uikit/uiinteraction"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.apple.uikit/documentation/UIKit/UIInteraction"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Band-selection",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/State-swift.enum"
      ],
      "title": "Band selection"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-band-selection-interaction",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/init(_:)"
      ],
      "title": "Creating a band selection interaction"
    },
    {
      "anchor": "Getting-the-selection-rectangle",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/selectionRect-2us5d"
      ],
      "title": "Getting the selection rectangle"
    },
    {
      "anchor": "Getting-the-interaction-state",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/isEnabled",
        "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/initialModifierFlags",
        "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/state-swift.property",
        "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/State-swift.enum"
      ],
      "title": "Getting the interaction state"
    },
    {
      "anchor": "Starting-the-interaction",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/shouldBeginHandler"
      ],
      "title": "Starting the interaction"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIBandSelectionInteraction"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBandSelectionInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBandSelectionInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-band-selection-interaction",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/init(_:)"
              ],
              "title": "Creating a band selection interaction"
            },
            {
              "anchor": "Getting-the-selection-rectangle",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/selectionRect-1fj7p"
              ],
              "title": "Getting the selection rectangle"
            },
            {
              "anchor": "Getting-the-interaction-state",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/isEnabled",
                "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/initialModifierFlags",
                "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/state-swift.property",
                "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/State-swift.enum"
              ],
              "title": "Getting the interaction state"
            },
            {
              "anchor": "Starting-the-interaction",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/shouldBeginHandler"
              ],
              "title": "Starting the interaction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIInteraction"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Band-selection",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIBandSelectionInteraction/State-swift.enum"
              ],
              "title": "Band selection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIBandSelectionInteraction"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBandSelectionInteraction~1state-swift.property/title",
          "value": "state"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBandSelectionInteraction~1state-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "state"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView/title",
          "value": "UICollectionView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBandSelectionInteraction~1init(_:)/title",
          "value": "initWithSelectionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBandSelectionInteraction~1init(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithSelectionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBandSelectionInteraction~1isEnabled/title",
          "value": "enabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBandSelectionInteraction~1isEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "enabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInteraction/title",
          "value": "UIInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDelegate/title",
          "value": "UICollectionViewDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBandSelectionInteraction~1initialModifierFlags/title",
          "value": "initialModifierFlags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBandSelectionInteraction~1initialModifierFlags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "initialModifierFlags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBandSelectionInteraction~1State-swift.enum/title",
          "value": "UIBandSelectionInteractionState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBandSelectionInteraction~1State-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBandSelectionInteractionState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBandSelectionInteraction~1State-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBandSelectionInteractionState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBandSelectionInteraction/title",
          "value": "UIBandSelectionInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBandSelectionInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBandSelectionInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBandSelectionInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBandSelectionInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBandSelectionInteraction~1shouldBeginHandler/title",
          "value": "shouldBeginHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBandSelectionInteraction~1shouldBeginHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shouldBeginHandler"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uibandselectioninteraction"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uibandselectioninteraction"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
