{
  "abstract": [
    {
      "text": "Symbols that buttons no longer support.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/views-and-controls",
        "doc://com.apple.uikit/documentation/UIKit/UIButton"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/uibutton-deprecated-symbols"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Deprecated symbols"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton": {
      "abstract": [
        {
          "text": "A control that executes your custom code in response to user interactions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIButton"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIButton"
        }
      ],
      "role": "symbol",
      "title": "UIButton",
      "type": "topic",
      "url": "/documentation/uikit/uibutton"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/adjustsImageWhenDisabled": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the image changes when the button is disabled.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjustsImageWhenDisabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/adjustsImageWhenDisabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "adjustsImageWhenDisabled"
        }
      ],
      "role": "symbol",
      "title": "adjustsImageWhenDisabled",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/adjustsimagewhendisabled"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/adjustsImageWhenHighlighted": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the image changes when the button is highlighted.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjustsImageWhenHighlighted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/adjustsImageWhenHighlighted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "adjustsImageWhenHighlighted"
        }
      ],
      "role": "symbol",
      "title": "adjustsImageWhenHighlighted",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/adjustsimagewhenhighlighted"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/backgroundRect(forBounds:)": {
      "abstract": [
        {
          "text": "Returns the rectangle in which the receiver draws its background.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backgroundRect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forBounds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/backgroundRect(forBounds:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backgroundRectForBounds:"
        }
      ],
      "role": "symbol",
      "title": "backgroundRect(forBounds:)",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/backgroundrect(forbounds:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/contentEdgeInsets": {
      "abstract": [
        {
          "text": "The inset or outset margins for the rectangle surrounding all of the button’s content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentEdgeInsets"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@UIEdgeInsets",
          "text": "UIEdgeInsets"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/contentEdgeInsets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentEdgeInsets"
        }
      ],
      "role": "symbol",
      "title": "contentEdgeInsets",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/contentedgeinsets"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/contentRect(forBounds:)": {
      "abstract": [
        {
          "text": "Returns the rectangle in which the receiver draws its entire content.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentRect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forBounds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/contentRect(forBounds:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentRectForBounds:"
        }
      ],
      "role": "symbol",
      "title": "contentRect(forBounds:)",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/contentrect(forbounds:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/font": {
      "abstract": [
        {
          "text": "The font used to display text on the button.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "font"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/font",
      "kind": "symbol",
      "role": "symbol",
      "title": "font",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/font"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/imageEdgeInsets": {
      "abstract": [
        {
          "text": "The inset or outset margins for the rectangle around the button’s image.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageEdgeInsets"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@UIEdgeInsets",
          "text": "UIEdgeInsets"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/imageEdgeInsets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageEdgeInsets"
        }
      ],
      "role": "symbol",
      "title": "imageEdgeInsets",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/imageedgeinsets"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/imageRect(forContentRect:)": {
      "abstract": [
        {
          "text": "Returns the rectangle in which the receiver draws its image.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageRect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forContentRect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/imageRect(forContentRect:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageRectForContentRect:"
        }
      ],
      "role": "symbol",
      "title": "imageRect(forContentRect:)",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/imagerect(forcontentrect:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/lineBreakMode": {
      "abstract": [
        {
          "text": "The line break mode to use when drawing text.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "lineBreakMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/lineBreakMode",
      "kind": "symbol",
      "role": "symbol",
      "title": "lineBreakMode",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/linebreakmode"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/reversesTitleShadowWhenHighlighted": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the title shadow changes when the button is highlighted.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reversesTitleShadowWhenHighlighted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/reversesTitleShadowWhenHighlighted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "reversesTitleShadowWhenHighlighted"
        }
      ],
      "role": "symbol",
      "title": "reversesTitleShadowWhenHighlighted",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/reversestitleshadowwhenhighlighted"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/showsTouchWhenHighlighted": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether tapping the button causes it to glow.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showsTouchWhenHighlighted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/showsTouchWhenHighlighted",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "showsTouchWhenHighlighted"
        }
      ],
      "role": "symbol",
      "title": "showsTouchWhenHighlighted",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/showstouchwhenhighlighted"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/titleEdgeInsets": {
      "abstract": [
        {
          "text": "The inset or outset margins for the rectangle around the button’s title text.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "titleEdgeInsets"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@UIEdgeInsets",
          "text": "UIEdgeInsets"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/titleEdgeInsets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "titleEdgeInsets"
        }
      ],
      "role": "symbol",
      "title": "titleEdgeInsets",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/titleedgeinsets"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/titleRect(forContentRect:)": {
      "abstract": [
        {
          "text": "Returns the rectangle in which the receiver draws its title.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "titleRect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forContentRect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/titleRect(forContentRect:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "titleRectForContentRect:"
        }
      ],
      "role": "symbol",
      "title": "titleRect(forContentRect:)",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/titlerect(forcontentrect:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/titleShadowOffset": {
      "abstract": [
        {
          "text": "The offset of the shadow used to display the receiver’s title.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "titleShadowOffset"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/titleShadowOffset",
      "kind": "symbol",
      "role": "symbol",
      "title": "titleShadowOffset",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/titleshadowoffset"
    },
    "doc://com.apple.uikit/documentation/UIKit/views-and-controls": {
      "abstract": [
        {
          "text": "Present your content onscreen and define the interactions allowed with that content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/views-and-controls",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Views and controls",
      "type": "topic",
      "url": "/documentation/uikit/views-and-controls"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Title-effects",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIButton/reversesTitleShadowWhenHighlighted"
      ],
      "title": "Title effects"
    },
    {
      "anchor": "Button-presentation",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIButton/adjustsImageWhenHighlighted",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/adjustsImageWhenDisabled",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/showsTouchWhenHighlighted"
      ],
      "title": "Button presentation"
    },
    {
      "anchor": "Edge-insets",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIButton/contentEdgeInsets",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/titleEdgeInsets",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/imageEdgeInsets"
      ],
      "title": "Edge insets"
    },
    {
      "anchor": "Dimensions",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIButton/backgroundRect(forBounds:)",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/contentRect(forBounds:)",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/titleRect(forContentRect:)",
        "doc://com.apple.uikit/documentation/UIKit/UIButton/imageRect(forContentRect:)"
      ],
      "title": "Dimensions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Title-effects",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIButton/font",
                "doc://com.apple.uikit/documentation/UIKit/UIButton/lineBreakMode",
                "doc://com.apple.uikit/documentation/UIKit/UIButton/titleShadowOffset",
                "doc://com.apple.uikit/documentation/UIKit/UIButton/reversesTitleShadowWhenHighlighted"
              ],
              "title": "Title effects"
            },
            {
              "anchor": "Button-presentation",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIButton/adjustsImageWhenHighlighted",
                "doc://com.apple.uikit/documentation/UIKit/UIButton/adjustsImageWhenDisabled",
                "doc://com.apple.uikit/documentation/UIKit/UIButton/showsTouchWhenHighlighted"
              ],
              "title": "Button presentation"
            },
            {
              "anchor": "Edge-insets",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIButton/contentEdgeInsets",
                "doc://com.apple.uikit/documentation/UIKit/UIButton/titleEdgeInsets",
                "doc://com.apple.uikit/documentation/UIKit/UIButton/imageEdgeInsets"
              ],
              "title": "Edge insets"
            },
            {
              "anchor": "Dimensions",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIButton/backgroundRect(forBounds:)",
                "doc://com.apple.uikit/documentation/UIKit/UIButton/contentRect(forBounds:)",
                "doc://com.apple.uikit/documentation/UIKit/UIButton/titleRect(forContentRect:)",
                "doc://com.apple.uikit/documentation/UIKit/UIButton/imageRect(forContentRect:)"
              ],
              "title": "Dimensions"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1showsTouchWhenHighlighted/title",
          "value": "showsTouchWhenHighlighted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1showsTouchWhenHighlighted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "showsTouchWhenHighlighted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1contentRect(forBounds:)/title",
          "value": "contentRectForBounds:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1contentRect(forBounds:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "contentRectForBounds:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1titleRect(forContentRect:)/title",
          "value": "titleRectForContentRect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1titleRect(forContentRect:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "titleRectForContentRect:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1imageRect(forContentRect:)/title",
          "value": "imageRectForContentRect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1imageRect(forContentRect:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "imageRectForContentRect:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1imageEdgeInsets/title",
          "value": "imageEdgeInsets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1imageEdgeInsets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "imageEdgeInsets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1titleEdgeInsets/title",
          "value": "titleEdgeInsets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1titleEdgeInsets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "titleEdgeInsets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1backgroundRect(forBounds:)/title",
          "value": "backgroundRectForBounds:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1backgroundRect(forBounds:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "backgroundRectForBounds:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1reversesTitleShadowWhenHighlighted/title",
          "value": "reversesTitleShadowWhenHighlighted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1reversesTitleShadowWhenHighlighted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "reversesTitleShadowWhenHighlighted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1adjustsImageWhenDisabled/title",
          "value": "adjustsImageWhenDisabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1adjustsImageWhenDisabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "adjustsImageWhenDisabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1adjustsImageWhenHighlighted/title",
          "value": "adjustsImageWhenHighlighted"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1adjustsImageWhenHighlighted/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "adjustsImageWhenHighlighted"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/title",
          "value": "UIButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1contentEdgeInsets/title",
          "value": "contentEdgeInsets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1contentEdgeInsets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentEdgeInsets"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uibutton-deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uibutton-deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
