{
  "abstract": [
    {
      "text": "A configuration that specifies the appearance and behavior of a button and its contents.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIButtonConfiguration",
    "fragments": [
      {
        "kind": "identifier",
        "text": "UIButtonConfiguration"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIButtonConfiguration"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "UIButtonConfiguration"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIButtonConfiguration"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can configure and update a button with a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". A button configuration contains all the customization options available with other methods, such as ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/setTitle(_:for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and can serve as a replacement for those methods. Alternatively, you can use a configuration in combination with these other methods and adopt new button behaviors and appearance without rewriting your customized ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " code.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton": {
      "abstract": [
        {
          "text": "A control that executes your custom code in response to user interactions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIButton"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIButton"
        }
      ],
      "role": "symbol",
      "title": "UIButton",
      "type": "topic",
      "url": "/documentation/uikit/uibutton"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/buttonWithConfiguration:primaryAction:": {
      "abstract": [
        {
          "text": "Creates a new button with the specified configuration and registers the primary action event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "buttonWithConfiguration:primaryAction:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/buttonWithConfiguration:primaryAction:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "buttonWithConfiguration:primaryAction:"
        }
      ],
      "role": "symbol",
      "title": "buttonWithConfiguration:primaryAction:",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/buttonwithconfiguration:primaryaction:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton/setTitle(_:for:)": {
      "abstract": [
        {
          "text": "Sets the title to use for the specified state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setTitle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIControl",
          "text": "UIControl"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIControlState",
          "text": "State"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton/setTitle(_:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTitle:forState:"
        }
      ],
      "role": "symbol",
      "title": "setTitle(_:for:)",
      "type": "topic",
      "url": "/documentation/uikit/uibutton/settitle(_:for:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration": {
      "abstract": [
        {
          "text": "A configuration that specifies the appearance and behavior of a button and its contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIButtonConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIButtonConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/activityIndicatorColorTransformer": {
      "abstract": [
        {
          "text": "The color transformer for resolving the color of the activity indicator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "activityIndicatorColorTransformer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/activityIndicatorColorTransformer",
      "kind": "symbol",
      "role": "symbol",
      "title": "activityIndicatorColorTransformer",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/activityindicatorcolortransformer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/attributedSubtitle": {
      "abstract": [
        {
          "text": "The text and style attributes for the button’s subtitle label.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "attributedSubtitle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/attributedSubtitle",
      "kind": "symbol",
      "role": "symbol",
      "title": "attributedSubtitle",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/attributedsubtitle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/attributedTitle": {
      "abstract": [
        {
          "text": "The text and style attributes for the button’s title label.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "attributedTitle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/attributedTitle",
      "kind": "symbol",
      "role": "symbol",
      "title": "attributedTitle",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/attributedtitle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/automaticallyUpdateForSelection": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the style automatically updates when the button is in a selected state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "automaticallyUpdateForSelection"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/automaticallyUpdateForSelection",
      "kind": "symbol",
      "role": "symbol",
      "title": "automaticallyUpdateForSelection",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/automaticallyupdateforselection"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/background": {
      "abstract": [
        {
          "text": "The configuration to customize the button background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "background"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/background",
      "kind": "symbol",
      "role": "symbol",
      "title": "background",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/background"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/baseBackgroundColor": {
      "abstract": [
        {
          "text": "The untransformed color for background views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "baseBackgroundColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/baseBackgroundColor",
      "kind": "symbol",
      "role": "symbol",
      "title": "baseBackgroundColor",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/basebackgroundcolor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/baseForegroundColor": {
      "abstract": [
        {
          "text": "The untransformed color for foreground views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "baseForegroundColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/baseForegroundColor",
      "kind": "symbol",
      "role": "symbol",
      "title": "baseForegroundColor",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/baseforegroundcolor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/borderedButtonConfiguration": {
      "abstract": [
        {
          "text": "Creates a configuration for a button that has a bordered style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "borderedButtonConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/borderedButtonConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "borderedButtonConfiguration"
        }
      ],
      "role": "symbol",
      "title": "borderedButtonConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/borderedbuttonconfiguration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/borderedProminentButtonConfiguration": {
      "abstract": [
        {
          "text": "Creates a configuration for a button that has a prominent, bordered style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "borderedProminentButtonConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/borderedProminentButtonConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "borderedProminentButtonConfiguration"
        }
      ],
      "role": "symbol",
      "title": "borderedProminentButtonConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/borderedprominentbuttonconfiguration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/borderedTintedButtonConfiguration": {
      "abstract": [
        {
          "text": "Creates a configuration for a button that has a tinted, bordered style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "borderedTintedButtonConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/borderedTintedButtonConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "borderedTintedButtonConfiguration"
        }
      ],
      "role": "symbol",
      "title": "borderedTintedButtonConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/borderedtintedbuttonconfiguration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/borderlessButtonConfiguration": {
      "abstract": [
        {
          "text": "Creates a configuration for a button that has a borderless style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "borderlessButtonConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/borderlessButtonConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "borderlessButtonConfiguration"
        }
      ],
      "role": "symbol",
      "title": "borderlessButtonConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/borderlessbuttonconfiguration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/buttonSize": {
      "abstract": [
        {
          "text": "A size that requests a preferred size for the button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "buttonSize"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/buttonSize",
      "kind": "symbol",
      "role": "symbol",
      "title": "buttonSize",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/buttonsize"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/contentInsets": {
      "abstract": [
        {
          "text": "The distance from the button’s content area to its bounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "contentInsets"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/contentInsets",
      "kind": "symbol",
      "role": "symbol",
      "title": "contentInsets",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/contentinsets"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/cornerStyle": {
      "abstract": [
        {
          "text": "The button style that controls the display behavior of the background corner radius.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "cornerStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/cornerStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "cornerStyle",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/cornerstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/filledButtonConfiguration": {
      "abstract": [
        {
          "text": "Creates a configuration for a button with a background filled with the button’s tint color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "filledButtonConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/filledButtonConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "filledButtonConfiguration"
        }
      ],
      "role": "symbol",
      "title": "filledButtonConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/filledbuttonconfiguration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/grayButtonConfiguration": {
      "abstract": [
        {
          "text": "Creates a configuration for a button with a gray background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "grayButtonConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/grayButtonConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "grayButtonConfiguration"
        }
      ],
      "role": "symbol",
      "title": "grayButtonConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/graybuttonconfiguration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/image": {
      "abstract": [
        {
          "text": "The foreground image the button displays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "image"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/image",
      "kind": "symbol",
      "role": "symbol",
      "title": "image",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/image"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/imageColorTransformer": {
      "abstract": [
        {
          "text": "A block that transforms the image color when the button state changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "imageColorTransformer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/imageColorTransformer",
      "kind": "symbol",
      "role": "symbol",
      "title": "imageColorTransformer",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/imagecolortransformer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/imagePadding": {
      "abstract": [
        {
          "text": "The distance between the button’s image and text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "imagePadding"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/imagePadding",
      "kind": "symbol",
      "role": "symbol",
      "title": "imagePadding",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/imagepadding"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/imagePlacement": {
      "abstract": [
        {
          "text": "The edge against which the button places the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "imagePlacement"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/imagePlacement",
      "kind": "symbol",
      "role": "symbol",
      "title": "imagePlacement",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/imageplacement"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/indicator": {
      "abstract": [
        {
          "text": "The style of the indicator that appears on the button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "indicator"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/indicator",
      "kind": "symbol",
      "role": "symbol",
      "title": "indicator",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/indicator"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/indicatorColorTransformer": {
      "abstract": [
        {
          "text": "The color transformer for resolving the indicator color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "indicatorColorTransformer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/indicatorColorTransformer",
      "kind": "symbol",
      "role": "symbol",
      "title": "indicatorColorTransformer",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/indicatorcolortransformer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/macIdiomStyle": {
      "abstract": [
        {
          "text": "The style to use when this button appears in macOS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "macIdiomStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/macIdiomStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "macIdiomStyle",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/macidiomstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/plainButtonConfiguration": {
      "abstract": [
        {
          "text": "Creates a configuration for a button with a transparent background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "plainButtonConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/plainButtonConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "plainButtonConfiguration"
        }
      ],
      "role": "symbol",
      "title": "plainButtonConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/plainbuttonconfiguration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/preferredSymbolConfigurationForImage": {
      "abstract": [
        {
          "text": "A requested configuration object for the button symbol image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "preferredSymbolConfigurationForImage"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/preferredSymbolConfigurationForImage",
      "kind": "symbol",
      "role": "symbol",
      "title": "preferredSymbolConfigurationForImage",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/preferredsymbolconfigurationforimage"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/setDefaultContentInsets": {
      "abstract": [
        {
          "text": "Restores the default content insets.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setDefaultContentInsets"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/setDefaultContentInsets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setDefaultContentInsets"
        }
      ],
      "role": "symbol",
      "title": "setDefaultContentInsets",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/setdefaultcontentinsets"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/showsActivityIndicator": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the button displays an activity indicator instead of an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "showsActivityIndicator"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/showsActivityIndicator",
      "kind": "symbol",
      "role": "symbol",
      "title": "showsActivityIndicator",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/showsactivityindicator"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/subtitle": {
      "abstract": [
        {
          "text": "The text the subtitle label of the button displays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "subtitle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/subtitle",
      "kind": "symbol",
      "role": "symbol",
      "title": "subtitle",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/subtitle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/subtitleLineBreakMode": {
      "abstract": [
        {
          "text": "The line break mode the button uses to lay out the button’s subtitle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "subtitleLineBreakMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/subtitleLineBreakMode",
      "kind": "symbol",
      "role": "symbol",
      "title": "subtitleLineBreakMode",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/subtitlelinebreakmode"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/subtitleTextAttributesTransformer": {
      "abstract": [
        {
          "text": "A transformer to update the attributed subtitle when the button state changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "subtitleTextAttributesTransformer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/subtitleTextAttributesTransformer",
      "kind": "symbol",
      "role": "symbol",
      "title": "subtitleTextAttributesTransformer",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/subtitletextattributestransformer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/tintedButtonConfiguration": {
      "abstract": [
        {
          "text": "Creates a configuration for a button with a tinted background color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "tintedButtonConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/tintedButtonConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tintedButtonConfiguration"
        }
      ],
      "role": "symbol",
      "title": "tintedButtonConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/tintedbuttonconfiguration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/title": {
      "abstract": [
        {
          "text": "The text of the title label the button displays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "title"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/title",
      "kind": "symbol",
      "role": "symbol",
      "title": "title",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/title"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/titleAlignment": {
      "abstract": [
        {
          "text": "The text alignment the button uses to lay out the title and subtitle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "titleAlignment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/titleAlignment",
      "kind": "symbol",
      "role": "symbol",
      "title": "titleAlignment",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/titlealignment"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/titleLineBreakMode": {
      "abstract": [
        {
          "text": "The line break mode the button uses to lay out the button’s title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "titleLineBreakMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/titleLineBreakMode",
      "kind": "symbol",
      "role": "symbol",
      "title": "titleLineBreakMode",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/titlelinebreakmode"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/titlePadding": {
      "abstract": [
        {
          "text": "The distance between the title and subtitle labels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "titlePadding"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/titlePadding",
      "kind": "symbol",
      "role": "symbol",
      "title": "titlePadding",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/titlepadding"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/titleTextAttributesTransformer": {
      "abstract": [
        {
          "text": "A transformer to update the attributed title when the button state changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "titleTextAttributesTransformer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/titleTextAttributesTransformer",
      "kind": "symbol",
      "role": "symbol",
      "title": "titleTextAttributesTransformer",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/titletextattributestransformer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/updatedConfigurationForButton:": {
      "abstract": [
        {
          "text": "Returns a copy of the configuration, updated for the given button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "updatedConfigurationForButton:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/updatedConfigurationForButton:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updatedConfigurationForButton:"
        }
      ],
      "role": "symbol",
      "title": "updatedConfigurationForButton:",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfiguration/updatedconfigurationforbutton:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfigurationCornerStyle": {
      "abstract": [
        {
          "text": "Settings that determine the appearance of the background corner radius.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIButtonConfigurationCornerStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfigurationCornerStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIButtonConfigurationCornerStyle",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfigurationcornerstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfigurationIndicator": {
      "abstract": [
        {
          "text": "Constants that determine the style of the indicator that appears on a button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIButtonConfigurationIndicator"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfigurationIndicator",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIButtonConfigurationIndicator",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfigurationindicator"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfigurationMacIdiomStyle": {
      "abstract": [
        {
          "text": "The button style your app uses when running in macOS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIButtonConfigurationMacIdiomStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfigurationMacIdiomStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIButtonConfigurationMacIdiomStyle",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfigurationmacidiomstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfigurationSize": {
      "abstract": [
        {
          "text": "A predefined size for button elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIButtonConfigurationSize"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfigurationSize",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIButtonConfigurationSize",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfigurationsize"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButtonConfigurationTitleAlignment": {
      "abstract": [
        {
          "text": "Specifies how to align a button’s title and subtitle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIButtonConfigurationTitleAlignment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButtonConfigurationTitleAlignment",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIButtonConfigurationTitleAlignment",
      "type": "topic",
      "url": "/documentation/uikit/uibuttonconfigurationtitlealignment"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIConfigurationTextAttributesTransformer-c.typealias": {
      "abstract": [
        {
          "text": "Defines a text transformation that can affect the visual appearance of a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIConfigurationTextAttributesTransformer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIConfigurationTextAttributesTransformer-c.typealias",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIConfigurationTextAttributesTransformer",
      "type": "topic",
      "url": "/documentation/uikit/uiconfigurationtextattributestransformer-c.typealias"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-buttons-from-a-configuration-object",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIButton/buttonWithConfiguration:primaryAction:"
      ],
      "title": "Creating buttons from a configuration object"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-configurations",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/plainButtonConfiguration",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/grayButtonConfiguration",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/tintedButtonConfiguration",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/filledButtonConfiguration",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/borderlessButtonConfiguration",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/borderedButtonConfiguration",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/borderedTintedButtonConfiguration",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/borderedProminentButtonConfiguration",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/updatedConfigurationForButton:"
      ],
      "title": "Creating configurations"
    },
    {
      "anchor": "Configuring-titles",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/title",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/subtitle",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/attributedTitle",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/attributedSubtitle",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/titleTextAttributesTransformer",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/subtitleTextAttributesTransformer",
        "doc://com.apple.uikit/documentation/UIKit/UIConfigurationTextAttributesTransformer-c.typealias",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/titlePadding",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/titleAlignment",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfigurationTitleAlignment",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/titleLineBreakMode",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/subtitleLineBreakMode"
      ],
      "title": "Configuring titles"
    },
    {
      "anchor": "Configuring-images",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/image",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/imagePadding",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/imagePlacement",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/imageColorTransformer",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/preferredSymbolConfigurationForImage"
      ],
      "title": "Configuring images"
    },
    {
      "anchor": "Configuring-layout",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/buttonSize",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfigurationSize",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/contentInsets",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/setDefaultContentInsets"
      ],
      "title": "Configuring layout"
    },
    {
      "anchor": "Configuring-button-colors",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/baseBackgroundColor",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/baseForegroundColor"
      ],
      "title": "Configuring button colors"
    },
    {
      "anchor": "Configuring-the-button-background",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/background",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/cornerStyle",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfigurationCornerStyle"
      ],
      "title": "Configuring the button background"
    },
    {
      "anchor": "Configuring-the-indicator",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/indicator",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfigurationIndicator",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/indicatorColorTransformer"
      ],
      "title": "Configuring the indicator"
    },
    {
      "anchor": "Configuring-the-activity-indicator",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/showsActivityIndicator",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/activityIndicatorColorTransformer"
      ],
      "title": "Configuring the activity indicator"
    },
    {
      "anchor": "Configuring-selection-behavior",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/automaticallyUpdateForSelection"
      ],
      "title": "Configuring selection behavior"
    },
    {
      "anchor": "Configuring-the-appearance-on-macOS",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfiguration/macIdiomStyle",
        "doc://com.apple.uikit/documentation/UIKit/UIButtonConfigurationMacIdiomStyle"
      ],
      "title": "Configuring the appearance on macOS"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1setTitle(_:for:)/title",
          "value": "setTitle:forState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton~1setTitle(_:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setTitle:forState:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/title",
          "value": "UIButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIButton"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uibuttonconfiguration"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
