{
  "abstract": [
    {
      "text": "An accessory in a collection view list cell.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:5UIKit15UICellAccessoryV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UICellAccessory"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UICellAccessory"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "UICellAccessory"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UICellAccessory"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A cell accessory is a visual element that you can add to a list cell (",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewListCell",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "). You use a cell accessory as a visual indicator or to let a user perform a cell-specific action like selecting, reordering, or deleting the cell. A cell accessory appears either on the leading or the trailing edge of a cell, outside of the cell’s content view.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "UIKit defines a set of standard system cell accessories. System accessories have default system-defined appearances, but you can make some customizations to them, like setting a custom tint color. You can’t customize the placement of system accessories. If you want additional customization, you can create a custom accessory with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/customView(configuration:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You add accessories to a list cell by setting its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewListCell/accessories-88j0f",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " array.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "cell.accessories = [ ",
            "    .checkmark(), ",
            "    .disclosureIndicator(options: .init(tintColor: .systemGray)), ",
            "    .delete(),",
            "    .reorder() ",
            "]"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The system throws an exception if you include more than one instance of any system accessory. You can include multiple custom accessories.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct": {
      "abstract": [
        {
          "text": "An accessory in a collection view list cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICellAccessory"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICellAccessory"
        }
      ],
      "role": "symbol",
      "title": "UICellAccessory",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/AccessoryType-swift.enum": {
      "abstract": [
        {
          "text": "Constants that describe the type of the cell accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AccessoryType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/AccessoryType-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AccessoryType"
        }
      ],
      "role": "symbol",
      "title": "UICellAccessory.AccessoryType",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/accessorytype-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/ActionHandler": {
      "abstract": [
        {
          "text": "A closure that the system calls when a user taps a cell accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ActionHandler"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/ActionHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ActionHandler"
        }
      ],
      "role": "symbol",
      "title": "UICellAccessory.ActionHandler",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/actionhandler"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/CheckmarkOptions": {
      "abstract": [
        {
          "text": "Configuration options for a checkmark accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CheckmarkOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/CheckmarkOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CheckmarkOptions"
        }
      ],
      "role": "symbol",
      "title": "UICellAccessory.CheckmarkOptions",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/checkmarkoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/CustomViewConfiguration": {
      "abstract": [
        {
          "text": "Configuration options for a custom accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomViewConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/CustomViewConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CustomViewConfiguration"
        }
      ],
      "role": "symbol",
      "title": "UICellAccessory.CustomViewConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/customviewconfiguration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/DeleteOptions": {
      "abstract": [
        {
          "text": "Configuration options for a delete accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DeleteOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/DeleteOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DeleteOptions"
        }
      ],
      "role": "symbol",
      "title": "UICellAccessory.DeleteOptions",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/deleteoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/DetailOptions": {
      "abstract": [
        {
          "text": "Configuration options for a detail accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DetailOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/DetailOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DetailOptions"
        }
      ],
      "role": "symbol",
      "title": "UICellAccessory.DetailOptions",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/detailoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/DisclosureIndicatorOptions": {
      "abstract": [
        {
          "text": "Configuration options for a disclosure indicator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DisclosureIndicatorOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/DisclosureIndicatorOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DisclosureIndicatorOptions"
        }
      ],
      "role": "symbol",
      "title": "UICellAccessory.DisclosureIndicatorOptions",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/disclosureindicatoroptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/DisplayedState": {
      "abstract": [
        {
          "text": "Constants that describe the cell-editing states that the accessory appears in.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DisplayedState"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/DisplayedState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DisplayedState"
        }
      ],
      "role": "symbol",
      "title": "UICellAccessory.DisplayedState",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/displayedstate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/InsertOptions": {
      "abstract": [
        {
          "text": "Configuration options for an insert accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "InsertOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/InsertOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "InsertOptions"
        }
      ],
      "role": "symbol",
      "title": "UICellAccessory.InsertOptions",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/insertoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/LabelOptions": {
      "abstract": [
        {
          "text": "Configuration options for a label accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LabelOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/LabelOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LabelOptions"
        }
      ],
      "role": "symbol",
      "title": "UICellAccessory.LabelOptions",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/labeloptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/LayoutDimension": {
      "abstract": [
        {
          "text": "Constants that describe the layout dimension for the accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LayoutDimension"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/LayoutDimension",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LayoutDimension"
        }
      ],
      "role": "symbol",
      "title": "UICellAccessory.LayoutDimension",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/layoutdimension"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/MenuSelectedElementDidChangeHandler": {
      "abstract": [
        {
          "text": "A closure type that defines a handler to perform when a user selects an element in the menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MenuSelectedElementDidChangeHandler"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/MenuSelectedElementDidChangeHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MenuSelectedElementDidChangeHandler"
        }
      ],
      "role": "symbol",
      "title": "UICellAccessory.MenuSelectedElementDidChangeHandler",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/menuselectedelementdidchangehandler"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/MultiselectOptions": {
      "abstract": [
        {
          "text": "Configuration options for a multiselect accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MultiselectOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/MultiselectOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MultiselectOptions"
        }
      ],
      "role": "symbol",
      "title": "UICellAccessory.MultiselectOptions",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/multiselectoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/OutlineDisclosureOptions": {
      "abstract": [
        {
          "text": "Configuration options for an outline disclosure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OutlineDisclosureOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/OutlineDisclosureOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OutlineDisclosureOptions"
        }
      ],
      "role": "symbol",
      "title": "UICellAccessory.OutlineDisclosureOptions",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/outlinedisclosureoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/Placement": {
      "abstract": [
        {
          "text": "Constants that describe the placement of the accessory within the cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Placement"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/Placement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Placement"
        }
      ],
      "role": "symbol",
      "title": "UICellAccessory.Placement",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/placement"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/PopUpMenuOptions": {
      "abstract": [
        {
          "text": "Configuration options for a popup menu accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "PopUpMenuOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/PopUpMenuOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PopUpMenuOptions"
        }
      ],
      "role": "symbol",
      "title": "UICellAccessory.PopUpMenuOptions",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/popupmenuoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/ReorderOptions": {
      "abstract": [
        {
          "text": "Configuration options for a reorder accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ReorderOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/ReorderOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ReorderOptions"
        }
      ],
      "role": "symbol",
      "title": "UICellAccessory.ReorderOptions",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/reorderoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/accessoryType-swift.property": {
      "abstract": [
        {
          "text": "The type of the cell accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessoryType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV0C4TypeO",
          "text": "AccessoryType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/accessoryType-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessoryType",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/accessorytype-swift.property"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/checkmark(displayed:options:)": {
      "abstract": [
        {
          "text": "Creates a checkmark system accessory with the specified display state and configuration options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "checkmark"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "displayed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV14DisplayedStateO",
          "text": "DisplayedState"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV16CheckmarkOptionsV",
          "text": "CheckmarkOptions"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/checkmark(displayed:options:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "checkmark(displayed:options:)",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/checkmark(displayed:options:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/customView(configuration:)": {
      "abstract": [
        {
          "text": "Creates a custom view accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "customView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "configuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV23CustomViewConfigurationV",
          "text": "CustomViewConfiguration"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/customView(configuration:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "customView(configuration:)",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/customview(configuration:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/delete(displayed:options:actionHandler:)": {
      "abstract": [
        {
          "text": "Creates a delete system accessory with the specified display state, configuration options, and optional action handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delete"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "displayed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV14DisplayedStateO",
          "text": "DisplayedState"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV13DeleteOptionsV",
          "text": "DeleteOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "actionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV13ActionHandlera",
          "text": "ActionHandler"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/delete(displayed:options:actionHandler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "delete(displayed:options:actionHandler:)",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/delete(displayed:options:actionhandler:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/detail(displayed:options:actionHandler:)": {
      "abstract": [
        {
          "text": "Creates a detail system accessory with the specified display state, configuration options, and optional action handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "detail"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "displayed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV14DisplayedStateO",
          "text": "DisplayedState"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV13DetailOptionsV",
          "text": "DetailOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "actionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV13ActionHandlera",
          "text": "ActionHandler"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/detail(displayed:options:actionHandler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "detail(displayed:options:actionHandler:)",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/detail(displayed:options:actionhandler:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/disclosureIndicator(displayed:options:)": {
      "abstract": [
        {
          "text": "Creates a disclosure indicator system accessory with the specified display state and configuration options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "disclosureIndicator"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "displayed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV14DisplayedStateO",
          "text": "DisplayedState"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV26DisclosureIndicatorOptionsV",
          "text": "DisclosureIndicatorOptions"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/disclosureIndicator(displayed:options:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "disclosureIndicator(displayed:options:)",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/disclosureindicator(displayed:options:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/insert(displayed:options:actionHandler:)": {
      "abstract": [
        {
          "text": "Creates an insert system accessory with the specified display state, configuration options, and optional action handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insert"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "displayed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV14DisplayedStateO",
          "text": "DisplayedState"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV13InsertOptionsV",
          "text": "InsertOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "actionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV13ActionHandlera",
          "text": "ActionHandler"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/insert(displayed:options:actionHandler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "insert(displayed:options:actionHandler:)",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/insert(displayed:options:actionhandler:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/label(text:displayed:options:)": {
      "abstract": [
        {
          "text": "Creates a label system accessory with the specified text, display state, and configuration options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "label"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "text"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "displayed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV14DisplayedStateO",
          "text": "DisplayedState"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV12LabelOptionsV",
          "text": "LabelOptions"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/label(text:displayed:options:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "label(text:displayed:options:)",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/label(text:displayed:options:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/multiselect(displayed:options:)": {
      "abstract": [
        {
          "text": "Creates a multiselect system accessory with the specified display state and configuration options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multiselect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "displayed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV14DisplayedStateO",
          "text": "DisplayedState"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV18MultiselectOptionsV",
          "text": "MultiselectOptions"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/multiselect(displayed:options:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "multiselect(displayed:options:)",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/multiselect(displayed:options:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/outlineDisclosure(displayed:options:actionHandler:)": {
      "abstract": [
        {
          "text": "Creates an outline disclosure system accessory with the specified display state, configuration options, and optional action handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outlineDisclosure"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "displayed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV14DisplayedStateO",
          "text": "DisplayedState"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV24OutlineDisclosureOptionsV",
          "text": "OutlineDisclosureOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "actionHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV13ActionHandlera",
          "text": "ActionHandler"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/outlineDisclosure(displayed:options:actionHandler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "outlineDisclosure(displayed:options:actionHandler:)",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/outlinedisclosure(displayed:options:actionhandler:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/popUpMenu(_:displayed:options:selectedElementDidChangeHandler:)": {
      "abstract": [
        {
          "text": "Creates a popup menu system accessory with the specified menu, display state, configuration options, and optional selection handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "popUpMenu"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIMenu",
          "text": "UIMenu"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "displayed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV14DisplayedStateO",
          "text": "DisplayedState"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV16PopUpMenuOptionsV",
          "text": "PopUpMenuOptions"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "selectedElementDidChangeHandler"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV35MenuSelectedElementDidChangeHandlera",
          "text": "MenuSelectedElementDidChangeHandler"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/popUpMenu(_:displayed:options:selectedElementDidChangeHandler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "popUpMenu(_:displayed:options:selectedElementDidChangeHandler:)",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/popupmenu(_:displayed:options:selectedelementdidchangehandler:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/reorder(displayed:options:)": {
      "abstract": [
        {
          "text": "Creates a reorder system accessory with the specified display state and configuration options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "reorder"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "displayed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV14DisplayedStateO",
          "text": "DisplayedState"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV14ReorderOptionsV",
          "text": "ReorderOptions"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/reorder(displayed:options:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "reorder(displayed:options:)",
      "type": "topic",
      "url": "/documentation/uikit/uicellaccessory-swift.struct/reorder(displayed:options:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewListCell": {
      "abstract": [
        {
          "text": "A collection view cell that provides list features and default styling.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewListCell"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewListCell",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewListCell"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewListCell",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewlistcell"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewListCell/accessories-88j0f": {
      "abstract": [
        {
          "text": "An array of the accessories that decorate the cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessories"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewListCell/accessories-88j0f",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessories",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewlistcell/accessories-88j0f"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewListCell/accessories-8nui4": {
      "abstract": [
        {
          "text": "An array of the accessories that decorate the cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessories"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UICellAccessoryV",
          "text": "UICellAccessory"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewListCell/accessories-8nui4",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessories",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewlistcell/accessories-8nui4"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-cell-accessories",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewListCell/accessories-8nui4"
      ],
      "title": "Managing cell accessories"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-disclosure-indicator",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/disclosureIndicator(displayed:options:)",
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/DisclosureIndicatorOptions"
      ],
      "title": "Creating a disclosure indicator"
    },
    {
      "anchor": "Creating-an-outline-disclosure",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/outlineDisclosure(displayed:options:actionHandler:)",
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/OutlineDisclosureOptions"
      ],
      "title": "Creating an outline disclosure"
    },
    {
      "anchor": "Creating-a-popup-menu-accessory",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/popUpMenu(_:displayed:options:selectedElementDidChangeHandler:)",
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/MenuSelectedElementDidChangeHandler",
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/PopUpMenuOptions"
      ],
      "title": "Creating a popup menu accessory"
    },
    {
      "anchor": "Creating-a-checkmark-accessory",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/checkmark(displayed:options:)",
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/CheckmarkOptions"
      ],
      "title": "Creating a checkmark accessory"
    },
    {
      "anchor": "Creating-a-delete-accessory",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/delete(displayed:options:actionHandler:)",
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/DeleteOptions"
      ],
      "title": "Creating a delete accessory"
    },
    {
      "anchor": "Creating-an-insert-accessory",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/insert(displayed:options:actionHandler:)",
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/InsertOptions"
      ],
      "title": "Creating an insert accessory"
    },
    {
      "anchor": "Creating-a-reorder-accessory",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/reorder(displayed:options:)",
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/ReorderOptions"
      ],
      "title": "Creating a reorder accessory"
    },
    {
      "anchor": "Creating-a-multiselect-accessory",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/multiselect(displayed:options:)",
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/MultiselectOptions"
      ],
      "title": "Creating a multiselect accessory"
    },
    {
      "anchor": "Creating-a-label-accessory",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/label(text:displayed:options:)",
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/LabelOptions"
      ],
      "title": "Creating a label accessory"
    },
    {
      "anchor": "Creating-a-detail-accessory",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/detail(displayed:options:actionHandler:)",
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/DetailOptions"
      ],
      "title": "Creating a detail accessory"
    },
    {
      "anchor": "Creating-a-custom-accessory",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/customView(configuration:)",
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/CustomViewConfiguration"
      ],
      "title": "Creating a custom accessory"
    },
    {
      "anchor": "Checking-the-accessorys-type",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/accessoryType-swift.property",
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/AccessoryType-swift.enum"
      ],
      "title": "Checking the accessory’s type"
    },
    {
      "anchor": "Customizing-appearance-and-placement",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/LayoutDimension",
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/Placement",
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/DisplayedState"
      ],
      "title": "Customizing appearance and placement"
    },
    {
      "anchor": "Performing-accessory-actions",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICellAccessory-swift.struct/ActionHandler"
      ],
      "title": "Performing accessory actions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewListCell/title",
          "value": "UICollectionViewListCell"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewListCell/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewListCell"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewListCell/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewListCell"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uicellaccessory-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
