{
  "abstract": [
    {
      "text": "The protocol you implement to provide additional information to, and receive notifications from, the CloudKit sharing controller.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UICloudSharingControllerDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UICloudSharingControllerDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UICloudSharingControllerDelegate"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UICloudSharingControllerDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "UICloudSharingControllerDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UICloudSharingControllerDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Implement an object that conforms to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICloudSharingControllerDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol when you want to:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Configure a ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICloudSharingController",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " instance.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Receive notifications from a ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICloudSharingController",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " instance as it attempts to save or remove the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/CloudKit/CKShare",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " record based on user interactions on the Invitation and People screens.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/CloudKit/CKShare": {
      "abstract": [
        {
          "text": "A specialized record type that manages a collection of shared records.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CKShare"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/CloudKit/CKShare",
      "kind": "symbol",
      "role": "symbol",
      "title": "CKShare",
      "type": "topic",
      "url": "/documentation/CloudKit/CKShare"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICloudSharingController": {
      "abstract": [
        {
          "text": "A view controller that presents standard screens for adding and removing people from a CloudKit share record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICloudSharingController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICloudSharingController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICloudSharingController"
        }
      ],
      "role": "symbol",
      "title": "UICloudSharingController",
      "type": "topic",
      "url": "/documentation/uikit/uicloudsharingcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICloudSharingController/delegate": {
      "abstract": [
        {
          "text": "A reference to an object that conforms to the CloudKit sharing controller delegate protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UICloudSharingControllerDelegate",
          "text": "UICloudSharingControllerDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICloudSharingController/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/uikit/uicloudsharingcontroller/delegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICloudSharingControllerDelegate": {
      "abstract": [
        {
          "text": "The protocol you implement to provide additional information to, and receive notifications from, the CloudKit sharing controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICloudSharingControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICloudSharingControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICloudSharingControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "UICloudSharingControllerDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uicloudsharingcontrollerdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICloudSharingControllerDelegate/cloudSharingController(_:failedToSaveShareWithError:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the CloudKit sharing controller failed to save the share record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cloudSharingController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICloudSharingController",
          "text": "UICloudSharingController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "failedToSaveShareWithError"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICloudSharingControllerDelegate/cloudSharingController(_:failedToSaveShareWithError:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cloudSharingController:failedToSaveShareWithError:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "cloudSharingController(_:failedToSaveShareWithError:)",
      "type": "topic",
      "url": "/documentation/uikit/uicloudsharingcontrollerdelegate/cloudsharingcontroller(_:failedtosavesharewitherror:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICloudSharingControllerDelegate/cloudSharingControllerDidSaveShare(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the CloudKit sharing controller saved the share record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cloudSharingControllerDidSaveShare"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICloudSharingController",
          "text": "UICloudSharingController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICloudSharingControllerDelegate/cloudSharingControllerDidSaveShare(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cloudSharingControllerDidSaveShare:"
        }
      ],
      "role": "symbol",
      "title": "cloudSharingControllerDidSaveShare(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uicloudsharingcontrollerdelegate/cloudsharingcontrollerdidsaveshare(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICloudSharingControllerDelegate/cloudSharingControllerDidStopSharing(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user has stopped sharing the record.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cloudSharingControllerDidStopSharing"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICloudSharingController",
          "text": "UICloudSharingController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICloudSharingControllerDelegate/cloudSharingControllerDidStopSharing(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cloudSharingControllerDidStopSharing:"
        }
      ],
      "role": "symbol",
      "title": "cloudSharingControllerDidStopSharing(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uicloudsharingcontrollerdelegate/cloudsharingcontrollerdidstopsharing(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICloudSharingControllerDelegate/itemThumbnailData(for:)": {
      "abstract": [
        {
          "text": "Asks the delegate for the thumbnail image data to display on the invitation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "itemThumbnailData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICloudSharingController",
          "text": "UICloudSharingController"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICloudSharingControllerDelegate/itemThumbnailData(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "itemThumbnailDataForCloudSharingController:"
        }
      ],
      "role": "symbol",
      "title": "itemThumbnailData(for:)",
      "type": "topic",
      "url": "/documentation/uikit/uicloudsharingcontrollerdelegate/itemthumbnaildata(for:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICloudSharingControllerDelegate/itemTitle(for:)": {
      "abstract": [
        {
          "text": "Asks the delegate for the title to display on the invitation screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "itemTitle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICloudSharingController",
          "text": "UICloudSharingController"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICloudSharingControllerDelegate/itemTitle(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "itemTitleForCloudSharingController:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "itemTitle(for:)",
      "type": "topic",
      "url": "/documentation/uikit/uicloudsharingcontrollerdelegate/itemtitle(for:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICloudSharingControllerDelegate/itemType(for:)": {
      "abstract": [
        {
          "text": "Asks the delegate for the Uniform Type Identifier (UTI) of the item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "itemType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICloudSharingController",
          "text": "UICloudSharingController"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICloudSharingControllerDelegate/itemType(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "itemTypeForCloudSharingController:"
        }
      ],
      "role": "symbol",
      "title": "itemType(for:)",
      "type": "topic",
      "url": "/documentation/uikit/uicloudsharingcontrollerdelegate/itemtype(for:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Customizing-the-cloud-sharing-controller-behavior",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICloudSharingController/delegate"
      ],
      "title": "Customizing the cloud sharing controller behavior"
    }
  ],
  "topicSections": [
    {
      "anchor": "Configuring-the-view-controller",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICloudSharingControllerDelegate/itemTitle(for:)",
        "doc://com.apple.uikit/documentation/UIKit/UICloudSharingControllerDelegate/itemType(for:)",
        "doc://com.apple.uikit/documentation/UIKit/UICloudSharingControllerDelegate/itemThumbnailData(for:)"
      ],
      "title": "Configuring the view controller"
    },
    {
      "anchor": "Processing-shared-items",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICloudSharingControllerDelegate/cloudSharingController(_:failedToSaveShareWithError:)",
        "doc://com.apple.uikit/documentation/UIKit/UICloudSharingControllerDelegate/cloudSharingControllerDidStopSharing(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UICloudSharingControllerDelegate/cloudSharingControllerDidSaveShare(_:)"
      ],
      "title": "Processing shared items"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UICloudSharingControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICloudSharingControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICloudSharingControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Configuring-the-view-controller",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UICloudSharingControllerDelegate/itemTitle(for:)",
                "doc://com.apple.uikit/documentation/UIKit/UICloudSharingControllerDelegate/itemType(for:)",
                "doc://com.apple.uikit/documentation/UIKit/UICloudSharingControllerDelegate/itemThumbnailData(for:)"
              ],
              "title": "Configuring the view controller"
            },
            {
              "anchor": "Processing-shared-items",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UICloudSharingControllerDelegate/cloudSharingController(_:failedToSaveShareWithError:)",
                "doc://com.apple.uikit/documentation/UIKit/UICloudSharingControllerDelegate/cloudSharingControllerDidStopSharing(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UICloudSharingControllerDelegate/cloudSharingControllerDidSaveShare(_:)"
              ],
              "title": "Processing shared items"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Customizing-the-cloud-sharing-controller-behavior",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UICloudSharingController/delegate"
              ],
              "title": "Customizing the cloud sharing controller behavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UICloudSharingControllerDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICloudSharingControllerDelegate~1itemTitle(for:)/title",
          "value": "itemTitleForCloudSharingController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICloudSharingControllerDelegate~1itemTitle(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "itemTitleForCloudSharingController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICloudSharingControllerDelegate~1itemType(for:)/title",
          "value": "itemTypeForCloudSharingController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICloudSharingControllerDelegate~1itemType(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "itemTypeForCloudSharingController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICloudSharingControllerDelegate~1cloudSharingControllerDidSaveShare(_:)/title",
          "value": "cloudSharingControllerDidSaveShare:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICloudSharingControllerDelegate~1cloudSharingControllerDidSaveShare(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cloudSharingControllerDidSaveShare:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICloudSharingControllerDelegate~1cloudSharingControllerDidStopSharing(_:)/title",
          "value": "cloudSharingControllerDidStopSharing:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICloudSharingControllerDelegate~1cloudSharingControllerDidStopSharing(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cloudSharingControllerDidStopSharing:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICloudSharingControllerDelegate~1itemThumbnailData(for:)/title",
          "value": "itemThumbnailDataForCloudSharingController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICloudSharingControllerDelegate~1itemThumbnailData(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "itemThumbnailDataForCloudSharingController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICloudSharingController/title",
          "value": "UICloudSharingController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICloudSharingController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICloudSharingController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICloudSharingController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICloudSharingController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICloudSharingControllerDelegate~1cloudSharingController(_:failedToSaveShareWithError:)/title",
          "value": "cloudSharingController:failedToSaveShareWithError:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICloudSharingControllerDelegate~1cloudSharingController(_:failedToSaveShareWithError:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cloudSharingController:failedToSaveShareWithError:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1CloudKit~1CKShare/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CKShare"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CKRecord",
              "text": "CKRecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICloudSharingController~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICloudSharingController~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICloudSharingControllerDelegate/title",
          "value": "UICloudSharingControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICloudSharingControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICloudSharingControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICloudSharingControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICloudSharingControllerDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uicloudsharingcontrollerdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uicloudsharingcontrollerdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
