{
  "abstract": [
    {
      "text": "An interface for coordinating your custom drop-related actions with the collection view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UICollectionViewDropCoordinator",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UICollectionViewDropCoordinator"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UICollectionViewDropCoordinator"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "UICollectionViewDropCoordinator"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UICollectionViewDropCoordinator"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.uikit/documentation/UIKit/supporting-drag-and-drop-in-collection-views"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You don’t create instances of this class yourself. When a drop occurs in the collection view, UIKit creates an instance of this class and passes it to your ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:performDropWith:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. Use the object to let the collection view know how you want to animate the dropped items into position.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDragDelegate": {
      "abstract": [
        {
          "text": "The interface for initiating drags from a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewDragDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDragDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewDragDelegate"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewDragDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdragdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator": {
      "abstract": [
        {
          "text": "An interface for coordinating your custom drop-related actions with the collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewDropCoordinator"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewDropCoordinator"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewDropCoordinator",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdropcoordinator"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/destinationIndexPath": {
      "abstract": [
        {
          "text": "The index path at which to insert the item in the collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "destinationIndexPath"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation9IndexPathV",
          "text": "IndexPath"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/destinationIndexPath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "destinationIndexPath"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "destinationIndexPath",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdropcoordinator/destinationindexpath"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/drop(_:intoItemAt:rect:)": {
      "abstract": [
        {
          "text": "Animates the item to the specified rectangle in the collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDragItem",
          "text": "UIDragItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "intoItemAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation9IndexPathV",
          "text": "IndexPath"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "rect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ") -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDragAnimating",
          "text": "UIDragAnimating"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/drop(_:intoItemAt:rect:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dropItem:intoItemAtIndexPath:rect:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "drop(_:intoItemAt:rect:)",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdropcoordinator/drop(_:intoitemat:rect:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/drop(_:to:)-7w5rn": {
      "abstract": [
        {
          "text": "Animates the item to an arbitrary location in your view hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDragItem",
          "text": "UIDragItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDragPreviewTarget",
          "text": "UIDragPreviewTarget"
        },
        {
          "kind": "text",
          "text": ") -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDragAnimating",
          "text": "UIDragAnimating"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/drop(_:to:)-7w5rn",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dropItem:toTarget:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "drop(_:to:)",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdropcoordinator/drop(_:to:)-7w5rn"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/drop(_:to:)-l5tg": {
      "abstract": [
        {
          "text": "Animates the item to the specified location and inserts a placeholder cell at that location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDragItem",
          "text": "UIDragItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICollectionViewDropPlaceholder",
          "text": "UICollectionViewDropPlaceholder"
        },
        {
          "kind": "text",
          "text": ") -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UICollectionViewDropPlaceholderContext",
          "text": "UICollectionViewDropPlaceholderContext"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/drop(_:to:)-l5tg",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dropItem:toPlaceholder:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "drop(_:to:)",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdropcoordinator/drop(_:to:)-l5tg"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/drop(_:toItemAt:)": {
      "abstract": [
        {
          "text": "Animates the item to the specified index path in the collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDragItem",
          "text": "UIDragItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "toItemAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation9IndexPathV",
          "text": "IndexPath"
        },
        {
          "kind": "text",
          "text": ") -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDragAnimating",
          "text": "UIDragAnimating"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/drop(_:toItemAt:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dropItem:toItemAtIndexPath:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "drop(_:toItemAt:)",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdropcoordinator/drop(_:toitemat:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/items": {
      "abstract": [
        {
          "text": "The items being dragged.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "items"
        },
        {
          "kind": "text",
          "text": ": [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UICollectionViewDropItem",
          "text": "UICollectionViewDropItem"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/items",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "items"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "items",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdropcoordinator/items"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/proposal": {
      "abstract": [
        {
          "text": "The current proposal for how to incorporate the dropped items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "proposal"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICollectionViewDropProposal",
          "text": "UICollectionViewDropProposal"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/proposal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "proposal"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "proposal",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdropcoordinator/proposal"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/session": {
      "abstract": [
        {
          "text": "The drop session containing information about the transaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "session"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDropSession",
          "text": "UIDropSession"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/session",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "session"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "session",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdropcoordinator/session"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate": {
      "abstract": [
        {
          "text": "The interface for handling drops in a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewDropDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewDropDelegate"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewDropDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdropdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:performDropWith:)": {
      "abstract": [
        {
          "text": "Tells your delegate to incorporate the drop data into the collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "collectionView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICollectionView",
          "text": "UICollectionView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "performDropWith"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UICollectionViewDropCoordinator",
          "text": "UICollectionViewDropCoordinator"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:performDropWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "collectionView:performDropWithCoordinator:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "collectionView(_:performDropWith:)",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdropdelegate/collectionview(_:performdropwith:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropItem": {
      "abstract": [
        {
          "text": "The data associated with an item being dropped into the collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewDropItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewDropItem"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewDropItem",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdropitem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropPlaceholder": {
      "abstract": [
        {
          "text": "A placeholder for an item dropped on a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewDropPlaceholder"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropPlaceholder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewDropPlaceholder"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewDropPlaceholder",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdropplaceholder"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropPlaceholderContext": {
      "abstract": [
        {
          "text": "An object that contains information about a placeholder in the collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewDropPlaceholderContext"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropPlaceholderContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewDropPlaceholderContext"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewDropPlaceholderContext",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdropplaceholdercontext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropProposal": {
      "abstract": [
        {
          "text": "Your proposed solution for handling a drop in a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewDropProposal"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropProposal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewDropProposal"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewDropProposal",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdropproposal"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewPlaceholder": {
      "abstract": [
        {
          "text": "A placeholder for an item dragged or dropped on a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewPlaceholder"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewPlaceholder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewPlaceholder"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewPlaceholder",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewplaceholder"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDataSourceTranslating": {
      "abstract": [
        {
          "text": "An advanced interface for managing a data source object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDataSourceTranslating"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDataSourceTranslating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDataSourceTranslating"
        }
      ],
      "role": "symbol",
      "title": "UIDataSourceTranslating",
      "type": "topic",
      "url": "/documentation/uikit/uidatasourcetranslating"
    },
    "doc://com.apple.uikit/documentation/UIKit/supporting-drag-and-drop-in-collection-views": {
      "abstract": [
        {
          "text": "Initiate drags and handle drops from a collection view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/supporting-drag-and-drop-in-collection-views",
      "kind": "article",
      "role": "article",
      "title": "Supporting Drag and Drop in Collection Views",
      "type": "topic",
      "url": "/documentation/uikit/supporting-drag-and-drop-in-collection-views"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Drag-and-drop",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/supporting-drag-and-drop-in-collection-views",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDragDelegate",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropPlaceholder",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropProposal",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropItem",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropPlaceholderContext",
        "doc://com.apple.uikit/documentation/UIKit/UIDataSourceTranslating",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewPlaceholder"
      ],
      "title": "Drag and drop"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-Dragged-Items",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/items"
      ],
      "title": "Getting the Dragged Items"
    },
    {
      "anchor": "Getting-the-Drop-Location",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/destinationIndexPath"
      ],
      "title": "Getting the Drop Location"
    },
    {
      "anchor": "Animating-Items-to-Their-Destination",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/drop(_:toItemAt:)",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/drop(_:intoItemAt:rect:)",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/drop(_:to:)-7w5rn",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/drop(_:to:)-l5tg"
      ],
      "title": "Animating Items to Their Destination"
    },
    {
      "anchor": "Getting-the-Session-Information",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/session",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/proposal"
      ],
      "title": "Getting the Session Information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UICollectionViewDropCoordinator"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-the-Dragged-Items",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/items"
              ],
              "title": "Getting the Dragged Items"
            },
            {
              "anchor": "Getting-the-Drop-Location",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/destinationIndexPath"
              ],
              "title": "Getting the Drop Location"
            },
            {
              "anchor": "Animating-Items-to-Their-Destination",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/drop(_:toItemAt:)",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/drop(_:intoItemAt:rect:)",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/drop(_:to:)-7w5rn",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/drop(_:to:)-l5tg"
              ],
              "title": "Animating Items to Their Destination"
            },
            {
              "anchor": "Getting-the-Session-Information",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/session",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator/proposal"
              ],
              "title": "Getting the Session Information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Drag-and-drop",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/supporting-drag-and-drop-in-collection-views",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDragDelegate",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropPlaceholder",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropProposal",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropItem",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropPlaceholderContext",
                "doc://com.apple.uikit/documentation/UIKit/UIDataSourceTranslating",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewPlaceholder"
              ],
              "title": "Drag and drop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UICollectionViewDropCoordinator"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropCoordinator~1drop(_:intoItemAt:rect:)/title",
          "value": "dropItem:intoItemAtIndexPath:rect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropCoordinator~1drop(_:intoItemAt:rect:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dropItem:intoItemAtIndexPath:rect:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropCoordinator~1drop(_:to:)-l5tg/title",
          "value": "dropItem:toPlaceholder:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropCoordinator~1drop(_:to:)-l5tg/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dropItem:toPlaceholder:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropCoordinator~1destinationIndexPath/title",
          "value": "destinationIndexPath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropCoordinator~1destinationIndexPath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "destinationIndexPath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewPlaceholder/title",
          "value": "UICollectionViewPlaceholder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewPlaceholder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewPlaceholder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewPlaceholder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewPlaceholder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDragDelegate/title",
          "value": "UICollectionViewDragDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDragDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDragDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDragDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDragDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropCoordinator~1proposal/title",
          "value": "proposal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropCoordinator~1proposal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "proposal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate~1collectionView(_:performDropWith:)/title",
          "value": "collectionView:performDropWithCoordinator:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate~1collectionView(_:performDropWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "collectionView:performDropWithCoordinator:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropItem/title",
          "value": "UICollectionViewDropItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDataSourceTranslating/title",
          "value": "UIDataSourceTranslating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDataSourceTranslating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDataSourceTranslating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDataSourceTranslating/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDataSourceTranslating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropPlaceholderContext/title",
          "value": "UICollectionViewDropPlaceholderContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropPlaceholderContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropPlaceholderContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropPlaceholderContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropPlaceholderContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropCoordinator~1drop(_:to:)-7w5rn/title",
          "value": "dropItem:toTarget:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropCoordinator~1drop(_:to:)-7w5rn/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dropItem:toTarget:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate/title",
          "value": "UICollectionViewDropDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropCoordinator/title",
          "value": "UICollectionViewDropCoordinator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropCoordinator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropCoordinator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropCoordinator~1items/title",
          "value": "items"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropCoordinator~1items/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "items"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropPlaceholder/title",
          "value": "UICollectionViewDropPlaceholder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropPlaceholder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropPlaceholder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropPlaceholder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropPlaceholder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropCoordinator~1drop(_:toItemAt:)/title",
          "value": "dropItem:toItemAtIndexPath:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropCoordinator~1drop(_:toItemAt:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dropItem:toItemAtIndexPath:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropProposal/title",
          "value": "UICollectionViewDropProposal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropProposal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropProposal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropProposal/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropProposal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropCoordinator~1session/title",
          "value": "session"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropCoordinator~1session/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "session"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uicollectionviewdropcoordinator"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uicollectionviewdropcoordinator"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
