{"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegateFlowLayout","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"UIKit"}],"platforms":[{"unavailable":false,"name":"iOS","deprecated":false,"beta":false},{"unavailable":false,"name":"iPadOS","deprecated":false,"beta":false},{"unavailable":false,"name":"Mac Catalyst","deprecated":false,"beta":false},{"unavailable":false,"name":"tvOS","deprecated":false,"beta":false},{"unavailable":false,"name":"visionOS","deprecated":false,"beta":false}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UICollectionViewDelegateFlowLayout","kind":"identifier"}],"roleHeading":"Protocol","externalID":"c:objc(pl)UICollectionViewDelegateFlowLayout","symbolKind":"protocol","title":"UICollectionViewDelegateFlowLayout","navigatorTitle":[{"text":"UICollectionViewDelegateFlowLayout","kind":"identifier"}]},"kind":"symbol","topicSections":[{"anchor":"Getting-the-size-of-items","identifiers":["doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegateFlowLayout/collectionView(_:layout:sizeForItemAt:)"],"title":"Getting the size of items"},{"anchor":"Getting-the-section-spacing","identifiers":["doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegateFlowLayout/collectionView(_:layout:insetForSectionAt:)","doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegateFlowLayout/collectionView(_:layout:minimumLineSpacingForSectionAt:)","doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegateFlowLayout/collectionView(_:layout:minimumInteritemSpacingForSectionAt:)"],"title":"Getting the section spacing"},{"anchor":"Getting-the-header-and-footer-sizes","identifiers":["doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegateFlowLayout/collectionView(_:layout:referenceSizeForHeaderInSection:)","doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegateFlowLayout/collectionView(_:layout:referenceSizeForFooterInSection:)"],"title":"Getting the header and footer sizes"}],"variants":[{"paths":["/documentation/uikit/uicollectionviewdelegateflowlayout"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uicollectionviewdelegateflowlayout"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UICollectionViewDelegateFlowLayout","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"UICollectionViewDelegate","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegate","preciseIdentifier":"c:objc(pl)UICollectionViewDelegate"}]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"inlineContent":[{"type":"text","text":"The methods of this protocol define the size of items and the spacing between items in the grid. All of the methods in this protocol are optional. If you don’t implement a particular method, the flow layout delegate uses values in its own properties for the appropriate spacing information."}],"type":"paragraph"},{"inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewFlowLayout","type":"reference"},{"text":" object expects the collection view’s delegate object to adopt this protocol. Therefore, implement this protocol on the object assigned to your collection view’s ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionView/delegate","type":"reference"},{"text":" property.","type":"text"}],"type":"paragraph"}]}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc://com.externally.resolved.symbol/c:objc(pl)NSObject","doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegate","doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate"],"kind":"relationships","title":"Inherits From"}],"abstract":[{"type":"text","text":"The methods that let you coordinate with a flow layout object to implement a grid-based layout."}],"references":{"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegateFlowLayout/collectionView(_:layout:referenceSizeForHeaderInSection:)":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegateFlowLayout/collectionView(_:layout:referenceSizeForHeaderInSection:)","title":"collectionView(_:layout:referenceSizeForHeaderInSection:)","kind":"symbol","navigatorTitle":[{"text":"collectionView:layout:referenceSizeForHeaderInSection:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView"},{"kind":"text","text":", "},{"text":"layout","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UICollectionViewLayout","preciseIdentifier":"c:objc(cs)UICollectionViewLayout","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"referenceSizeForHeaderInSection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"}],"url":"/documentation/uikit/uicollectionviewdelegateflowlayout/collectionview(_:layout:referencesizeforheaderinsection:)","type":"topic","abstract":[{"type":"text","text":"Asks the delegate for the size of the header view in the specified section."}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegateFlowLayout/collectionView(_:layout:minimumLineSpacingForSectionAt:)":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegateFlowLayout/collectionView(_:layout:minimumLineSpacingForSectionAt:)","title":"collectionView(_:layout:minimumLineSpacingForSectionAt:)","kind":"symbol","navigatorTitle":[{"text":"collectionView:layout:minimumLineSpacingForSectionAtIndex:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView"},{"kind":"text","text":", "},{"text":"layout","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UICollectionViewLayout","preciseIdentifier":"c:objc(cs)UICollectionViewLayout","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"minimumLineSpacingForSectionAt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"}],"url":"/documentation/uikit/uicollectionviewdelegateflowlayout/collectionview(_:layout:minimumlinespacingforsectionat:)","type":"topic","abstract":[{"type":"text","text":"Asks the delegate for the spacing between successive rows or columns of a section."}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegateFlowLayout/collectionView(_:layout:sizeForItemAt:)":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegateFlowLayout/collectionView(_:layout:sizeForItemAt:)","title":"collectionView(_:layout:sizeForItemAt:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"text":"(","kind":"text"},{"text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"layout","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UICollectionViewLayout","preciseIdentifier":"c:objc(cs)UICollectionViewLayout","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sizeForItemAt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"}],"url":"/documentation/uikit/uicollectionviewdelegateflowlayout/collectionview(_:layout:sizeforitemat:)","type":"topic","navigatorTitle":[{"text":"collectionView:layout:sizeForItemAtIndexPath:","kind":"identifier"}],"abstract":[{"text":"Asks the delegate for the size of the specified item’s cell.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UICollectionView/delegate":{"title":"delegate","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"UICollectionViewDelegate","preciseIdentifier":"c:objc(pl)UICollectionViewDelegate","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionView/delegate","kind":"symbol","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"type":"topic","url":"/documentation/uikit/uicollectionview/delegate","abstract":[{"text":"The object that acts as the delegate of the collection view.","type":"text"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegateFlowLayout/collectionView(_:layout:referenceSizeForFooterInSection:)":{"title":"collectionView(_:layout:referenceSizeForFooterInSection:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"layout","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UICollectionViewLayout","preciseIdentifier":"c:objc(cs)UICollectionViewLayout","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"referenceSizeForFooterInSection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegateFlowLayout/collectionView(_:layout:referenceSizeForFooterInSection:)","kind":"symbol","navigatorTitle":[{"text":"collectionView:layout:referenceSizeForFooterInSection:","kind":"identifier"}],"type":"topic","url":"/documentation/uikit/uicollectionviewdelegateflowlayout/collectionview(_:layout:referencesizeforfooterinsection:)","abstract":[{"text":"Asks the delegate for the size of the footer view in the specified section.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewFlowLayout":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewFlowLayout","title":"UICollectionViewFlowLayout","abstract":[{"type":"text","text":"A layout object that organizes items into a grid with optional header and footer views for each section."}],"url":"/documentation/uikit/uicollectionviewflowlayout","navigatorTitle":[{"text":"UICollectionViewFlowLayout","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UICollectionViewFlowLayout","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegateFlowLayout/collectionView(_:layout:insetForSectionAt:)":{"title":"collectionView(_:layout:insetForSectionAt:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"layout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewLayout","text":"UICollectionViewLayout"},{"kind":"text","text":", "},{"kind":"externalParam","text":"insetForSectionAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@UIEdgeInsets","text":"UIEdgeInsets"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegateFlowLayout/collectionView(_:layout:insetForSectionAt:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"collectionView:layout:insetForSectionAtIndex:"}],"type":"topic","url":"/documentation/uikit/uicollectionviewdelegateflowlayout/collectionview(_:layout:insetforsectionat:)","abstract":[{"text":"Asks the delegate for the margins to apply to content in the specified section.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegateFlowLayout/collectionView(_:layout:minimumInteritemSpacingForSectionAt:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UICollectionView","kind":"typeIdentifier","text":"UICollectionView"},{"text":", ","kind":"text"},{"text":"layout","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UICollectionViewLayout","preciseIdentifier":"c:objc(cs)UICollectionViewLayout","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"minimumInteritemSpacingForSectionAt","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegateFlowLayout/collectionView(_:layout:minimumInteritemSpacingForSectionAt:)","role":"symbol","navigatorTitle":[{"text":"collectionView:layout:minimumInteritemSpacingForSectionAtIndex:","kind":"identifier"}],"type":"topic","url":"/documentation/uikit/uicollectionviewdelegateflowlayout/collectionview(_:layout:minimuminteritemspacingforsectionat:)","abstract":[{"type":"text","text":"Asks the delegate for the spacing between successive items in the rows or columns of a section."}],"title":"collectionView(_:layout:minimumInteritemSpacingForSectionAt:)","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegateFlowLayout":{"title":"UICollectionViewDelegateFlowLayout","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UICollectionViewDelegateFlowLayout"}],"abstract":[{"text":"The methods that let you coordinate with a flow layout object to implement a grid-based layout.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegateFlowLayout","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UICollectionViewDelegateFlowLayout"}],"kind":"symbol","url":"/documentation/uikit/uicollectionviewdelegateflowlayout"},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"title":"NSObjectProtocol","type":"topic","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","role":"symbol","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"kind":"symbol","url":"/documentation/objectivec/nsobjectprotocol"},"doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate":{"url":"/documentation/uikit/uiscrollviewdelegate","identifier":"doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate","role":"symbol","navigatorTitle":[{"text":"UIScrollViewDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIScrollViewDelegate","kind":"identifier"}],"type":"topic","title":"UIScrollViewDelegate","kind":"symbol","abstract":[{"text":"The interface for the delegate of a scroll view.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegate":{"type":"topic","kind":"symbol","title":"UICollectionViewDelegate","role":"symbol","navigatorTitle":[{"text":"UICollectionViewDelegate","kind":"identifier"}],"url":"/documentation/uikit/uicollectionviewdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UICollectionViewDelegate","kind":"identifier"}],"abstract":[{"text":"The methods adopted by the object you use to manage user interactions with items in a collection view.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegate"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"deprecated":false,"beta":false,"name":"iOS","unavailable":false},{"deprecated":false,"beta":false,"name":"iPadOS","unavailable":false},{"deprecated":false,"beta":false,"name":"Mac Catalyst","unavailable":false},{"deprecated":false,"beta":false,"name":"tvOS","unavailable":false},{"deprecated":false,"beta":false,"name":"visionOS","unavailable":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Protocol","op":"replace"},{"path":"/metadata/title","value":"UICollectionViewDelegateFlowLayout","op":"replace"},{"path":"/metadata/symbolKind","value":"protocol","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"UICollectionViewDelegateFlowLayout","kind":"identifier"}],"op":"replace"},{"path":"/metadata/navigatorTitle","value":[{"kind":"identifier","text":"UICollectionViewDelegateFlowLayout"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"op":"replace"},{"path":"/topicSections","value":[{"title":"Getting the size of items","anchor":"Getting-the-size-of-items","identifiers":["doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegateFlowLayout/collectionView(_:layout:sizeForItemAt:)"]},{"title":"Getting the section spacing","anchor":"Getting-the-section-spacing","identifiers":["doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegateFlowLayout/collectionView(_:layout:insetForSectionAt:)","doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegateFlowLayout/collectionView(_:layout:minimumLineSpacingForSectionAt:)","doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegateFlowLayout/collectionView(_:layout:minimumInteritemSpacingForSectionAt:)"]},{"title":"Getting the header and footer sizes","anchor":"Getting-the-header-and-footer-sizes","identifiers":["doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegateFlowLayout/collectionView(_:layout:referenceSizeForHeaderInSection:)","doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegateFlowLayout/collectionView(_:layout:referenceSizeForFooterInSection:)"]}],"op":"replace"},{"path":"/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegate"],"title":"Inherits From"}],"op":"replace"},{"path":"/seeAlsoSections","value":null,"op":"add"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UICollectionViewDelegateFlowLayout","kind":"identifier"},{"text":" <","kind":"text"},{"text":"UICollectionViewDelegate","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UICollectionViewDelegate"},{"text":">","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"]}]},"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDelegateFlowLayout~1collectionView(_:layout:referenceSizeForHeaderInSection:)/title","op":"replace","value":"collectionView:layout:referenceSizeForHeaderInSection:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDelegateFlowLayout~1collectionView(_:layout:referenceSizeForHeaderInSection:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:layout:referenceSizeForHeaderInSection:"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDelegateFlowLayout~1collectionView(_:layout:minimumLineSpacingForSectionAt:)/title","op":"replace","value":"collectionView:layout:minimumLineSpacingForSectionAtIndex:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDelegateFlowLayout~1collectionView(_:layout:minimumLineSpacingForSectionAt:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"collectionView:layout:minimumLineSpacingForSectionAtIndex:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDelegateFlowLayout~1collectionView(_:layout:sizeForItemAt:)/title","op":"replace","value":"collectionView:layout:sizeForItemAtIndexPath:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDelegateFlowLayout~1collectionView(_:layout:sizeForItemAt:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:layout:sizeForItemAtIndexPath:"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1delegate/title","op":"replace","value":"delegate"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1delegate/fragments","op":"replace","value":[{"kind":"identifier","text":"delegate"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDelegateFlowLayout~1collectionView(_:layout:referenceSizeForFooterInSection:)/title","op":"replace","value":"collectionView:layout:referenceSizeForFooterInSection:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDelegateFlowLayout~1collectionView(_:layout:referenceSizeForFooterInSection:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:layout:referenceSizeForFooterInSection:"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewFlowLayout/title","op":"replace","value":"UICollectionViewFlowLayout"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewFlowLayout/fragments","op":"replace","value":[{"kind":"identifier","text":"UICollectionViewFlowLayout"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewFlowLayout/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UICollectionViewFlowLayout"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDelegateFlowLayout~1collectionView(_:layout:insetForSectionAt:)/title","op":"replace","value":"collectionView:layout:insetForSectionAtIndex:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDelegateFlowLayout~1collectionView(_:layout:insetForSectionAt:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"collectionView:layout:insetForSectionAtIndex:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDelegateFlowLayout~1collectionView(_:layout:minimumInteritemSpacingForSectionAt:)/title","op":"replace","value":"collectionView:layout:minimumInteritemSpacingForSectionAtIndex:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDelegateFlowLayout~1collectionView(_:layout:minimumInteritemSpacingForSectionAt:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"collectionView:layout:minimumInteritemSpacingForSectionAtIndex:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDelegateFlowLayout/title","op":"replace","value":"UICollectionViewDelegateFlowLayout"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDelegateFlowLayout/fragments","op":"replace","value":[{"kind":"identifier","text":"UICollectionViewDelegateFlowLayout"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDelegateFlowLayout/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UICollectionViewDelegateFlowLayout"}]},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title","op":"replace","value":"NSObject"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewDelegate/title","op":"replace","value":"UIScrollViewDelegate"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewDelegate/fragments","op":"replace","value":[{"kind":"identifier","text":"UIScrollViewDelegate"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewDelegate/navigatorTitle","op":"replace","value":[{"text":"UIScrollViewDelegate","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDelegate/title","op":"replace","value":"UICollectionViewDelegate"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDelegate/fragments","op":"replace","value":[{"text":"UICollectionViewDelegate","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDelegate/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UICollectionViewDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}