{
  "abstract": [
    {
      "text": "To respond to UIKit dynamic item collisions, configure a custom class to adopt the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollisionBehaviorDelegate",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " protocol. Then, in a collision behavior (an instance of the ",
      "type": "text"
    },
    {
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior",
      "isActive": true,
      "type": "reference"
    },
    {
      "text": " class), set the delegate to be an instance of your custom class.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UICollisionBehaviorDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UICollisionBehaviorDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UICollisionBehaviorDelegate"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UICollisionBehaviorDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "UICollisionBehaviorDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UICollisionBehaviorDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The delegate is notified of collisions that occur between the behavior’s dynamic items, or between a dynamic item and a boundary, depending on the behavior’s mode (as set with its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/collisionMode",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property). In the case of a collision between an item and the boundary defined by a reference view, the identifier passed to the delegate method is ",
              "type": "text"
            },
            {
              "code": "nil",
              "type": "codeVoice"
            },
            {
              "text": ". (For more on the reference view and the different ways to initialize a dynamic animator, read the Overview in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDynamicAnimator",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".)",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior": {
      "abstract": [
        {
          "text": "An object that confers to a specified array of dynamic items the ability to engage in collisions with each other and with the behavior’s specified boundaries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollisionBehavior"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollisionBehavior"
        }
      ],
      "role": "symbol",
      "title": "UICollisionBehavior",
      "type": "topic",
      "url": "/documentation/uikit/uicollisionbehavior"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/collisionDelegate": {
      "abstract": [
        {
          "text": "The delegate object that you want to respond to collisions for the collision behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "collisionDelegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UICollisionBehaviorDelegate",
          "text": "UICollisionBehaviorDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/collisionDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "collisionDelegate"
        }
      ],
      "role": "symbol",
      "title": "collisionDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uicollisionbehavior/collisiondelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/collisionMode": {
      "abstract": [
        {
          "text": "The type of edges that participate in collisions for the collision behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "collisionMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICollisionBehavior",
          "text": "UICollisionBehavior"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UICollisionBehaviorMode",
          "text": "Mode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/collisionMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "collisionMode"
        }
      ],
      "role": "symbol",
      "title": "collisionMode",
      "type": "topic",
      "url": "/documentation/uikit/uicollisionbehavior/collisionmode"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollisionBehaviorDelegate": {
      "abstract": [
        {
          "text": "To respond to UIKit dynamic item collisions, configure a custom class to adopt the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollisionBehaviorDelegate",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " protocol. Then, in a collision behavior (an instance of the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " class), set the delegate to be an instance of your custom class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollisionBehaviorDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollisionBehaviorDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollisionBehaviorDelegate"
        }
      ],
      "role": "symbol",
      "title": "UICollisionBehaviorDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uicollisionbehaviordelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollisionBehaviorDelegate/collisionBehavior(_:beganContactFor:with:at:)": {
      "abstract": [
        {
          "text": "Called when a collision between two dynamic items has begun.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "collisionBehavior"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICollisionBehavior",
          "text": "UICollisionBehavior"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "beganContactFor"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDynamicItem",
          "text": "UIDynamicItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDynamicItem",
          "text": "UIDynamicItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollisionBehaviorDelegate/collisionBehavior(_:beganContactFor:with:at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "collisionBehavior:beganContactForItem:withItem:atPoint:"
        }
      ],
      "role": "symbol",
      "title": "collisionBehavior(_:beganContactFor:with:at:)",
      "type": "topic",
      "url": "/documentation/uikit/uicollisionbehaviordelegate/collisionbehavior(_:begancontactfor:with:at:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollisionBehaviorDelegate/collisionBehavior(_:beganContactFor:withBoundaryIdentifier:at:)": {
      "abstract": [
        {
          "text": "Called when a collision, between a dynamic item and a collision boundary, has begun.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "collisionBehavior"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICollisionBehavior",
          "text": "UICollisionBehavior"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "beganContactFor"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDynamicItem",
          "text": "UIDynamicItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withBoundaryIdentifier"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSCopying",
          "text": "NSCopying"
        },
        {
          "kind": "text",
          "text": ")?, "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollisionBehaviorDelegate/collisionBehavior(_:beganContactFor:withBoundaryIdentifier:at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "collisionBehavior:beganContactForItem:withBoundaryIdentifier:atPoint:"
        }
      ],
      "role": "symbol",
      "title": "collisionBehavior(_:beganContactFor:withBoundaryIdentifier:at:)",
      "type": "topic",
      "url": "/documentation/uikit/uicollisionbehaviordelegate/collisionbehavior(_:begancontactfor:withboundaryidentifier:at:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollisionBehaviorDelegate/collisionBehavior(_:endedContactFor:with:)": {
      "abstract": [
        {
          "text": "Called when a collision between two dynamic items has ended.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "collisionBehavior"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICollisionBehavior",
          "text": "UICollisionBehavior"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "endedContactFor"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDynamicItem",
          "text": "UIDynamicItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDynamicItem",
          "text": "UIDynamicItem"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollisionBehaviorDelegate/collisionBehavior(_:endedContactFor:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "collisionBehavior:endedContactForItem:withItem:"
        }
      ],
      "role": "symbol",
      "title": "collisionBehavior(_:endedContactFor:with:)",
      "type": "topic",
      "url": "/documentation/uikit/uicollisionbehaviordelegate/collisionbehavior(_:endedcontactfor:with:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollisionBehaviorDelegate/collisionBehavior(_:endedContactFor:withBoundaryIdentifier:)": {
      "abstract": [
        {
          "text": "Called when a collision between a dynamic item and a boundary has ended.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "collisionBehavior"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICollisionBehavior",
          "text": "UICollisionBehavior"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "endedContactFor"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDynamicItem",
          "text": "UIDynamicItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withBoundaryIdentifier"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSCopying",
          "text": "NSCopying"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollisionBehaviorDelegate/collisionBehavior(_:endedContactFor:withBoundaryIdentifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "collisionBehavior:endedContactForItem:withBoundaryIdentifier:"
        }
      ],
      "role": "symbol",
      "title": "collisionBehavior(_:endedContactFor:withBoundaryIdentifier:)",
      "type": "topic",
      "url": "/documentation/uikit/uicollisionbehaviordelegate/collisionbehavior(_:endedcontactfor:withboundaryidentifier:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDynamicAnimator": {
      "abstract": [
        {
          "text": "An object that provides physics-related capabilities and animations for its dynamic items, and provides the context for those animations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDynamicAnimator"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDynamicAnimator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDynamicAnimator"
        }
      ],
      "role": "symbol",
      "title": "UIDynamicAnimator",
      "type": "topic",
      "url": "/documentation/uikit/uidynamicanimator"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Customizing-the-collision-behavior",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/collisionDelegate"
      ],
      "title": "Customizing the collision behavior"
    }
  ],
  "topicSections": [
    {
      "anchor": "Responding-to-UIKit-Dynamics-collisions",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICollisionBehaviorDelegate/collisionBehavior(_:beganContactFor:withBoundaryIdentifier:at:)",
        "doc://com.apple.uikit/documentation/UIKit/UICollisionBehaviorDelegate/collisionBehavior(_:beganContactFor:with:at:)",
        "doc://com.apple.uikit/documentation/UIKit/UICollisionBehaviorDelegate/collisionBehavior(_:endedContactFor:withBoundaryIdentifier:)",
        "doc://com.apple.uikit/documentation/UIKit/UICollisionBehaviorDelegate/collisionBehavior(_:endedContactFor:with:)"
      ],
      "title": "Responding to UIKit Dynamics collisions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UICollisionBehaviorDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollisionBehaviorDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollisionBehaviorDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Responding-to-UIKit-Dynamics-collisions",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UICollisionBehaviorDelegate/collisionBehavior(_:beganContactFor:withBoundaryIdentifier:at:)",
                "doc://com.apple.uikit/documentation/UIKit/UICollisionBehaviorDelegate/collisionBehavior(_:beganContactFor:with:at:)",
                "doc://com.apple.uikit/documentation/UIKit/UICollisionBehaviorDelegate/collisionBehavior(_:endedContactFor:withBoundaryIdentifier:)",
                "doc://com.apple.uikit/documentation/UIKit/UICollisionBehaviorDelegate/collisionBehavior(_:endedContactFor:with:)"
              ],
              "title": "Responding to UIKit Dynamics collisions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Customizing-the-collision-behavior",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior/collisionDelegate"
              ],
              "title": "Customizing the collision behavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UICollisionBehaviorDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicAnimator/title",
          "value": "UIDynamicAnimator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicAnimator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDynamicAnimator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicAnimator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDynamicAnimator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehavior~1collisionMode/title",
          "value": "collisionMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehavior~1collisionMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "collisionMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehavior~1collisionDelegate/title",
          "value": "collisionDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehavior~1collisionDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "collisionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehaviorDelegate/title",
          "value": "UICollisionBehaviorDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehaviorDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollisionBehaviorDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehaviorDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollisionBehaviorDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehaviorDelegate~1collisionBehavior(_:endedContactFor:with:)/title",
          "value": "collisionBehavior:endedContactForItem:withItem:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehaviorDelegate~1collisionBehavior(_:endedContactFor:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "collisionBehavior:endedContactForItem:withItem:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehaviorDelegate~1collisionBehavior(_:beganContactFor:withBoundaryIdentifier:at:)/title",
          "value": "collisionBehavior:beganContactForItem:withBoundaryIdentifier:atPoint:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehaviorDelegate~1collisionBehavior(_:beganContactFor:withBoundaryIdentifier:at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "collisionBehavior:beganContactForItem:withBoundaryIdentifier:atPoint:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehaviorDelegate~1collisionBehavior(_:endedContactFor:withBoundaryIdentifier:)/title",
          "value": "collisionBehavior:endedContactForItem:withBoundaryIdentifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehaviorDelegate~1collisionBehavior(_:endedContactFor:withBoundaryIdentifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "collisionBehavior:endedContactForItem:withBoundaryIdentifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehavior/title",
          "value": "UICollisionBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollisionBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehavior/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollisionBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehaviorDelegate~1collisionBehavior(_:beganContactFor:with:at:)/title",
          "value": "collisionBehavior:beganContactForItem:withItem:atPoint:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehaviorDelegate~1collisionBehavior(_:beganContactFor:with:at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "collisionBehavior:beganContactForItem:withItem:atPoint:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uicollisionbehaviordelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uicollisionbehaviordelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
