{
  "abstract": [
    {
      "text": "The corner curve to apply to a view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UICornerCurve"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UICornerCurve",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UICornerCurve"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UICornerCurve"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "UICornerCurve"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UICornerCurve"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICornerCurve": {
      "abstract": [
        {
          "text": "The corner curve to apply to a view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICornerCurve"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICornerCurve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICornerCurve"
        }
      ],
      "role": "symbol",
      "title": "UICornerCurve",
      "type": "topic",
      "url": "/documentation/uikit/uicornercurve"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICornerCurve/automatic": {
      "abstract": [
        {
          "text": "Selects the corner style automatically.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICornerCurve/automatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICornerCurveAutomatic"
        }
      ],
      "role": "symbol",
      "title": "UICornerCurve.automatic",
      "type": "topic",
      "url": "/documentation/uikit/uicornercurve/automatic"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICornerCurve/circular": {
      "abstract": [
        {
          "text": "Always uses a circular corner style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "circular"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICornerCurve/circular",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICornerCurveCircular"
        }
      ],
      "role": "symbol",
      "title": "UICornerCurve.circular",
      "type": "topic",
      "url": "/documentation/uikit/uicornercurve/circular"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICornerCurve/continuous": {
      "abstract": [
        {
          "text": "Always uses a continuous corner style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "continuous"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICornerCurve/continuous",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICornerCurveContinuous"
        }
      ],
      "role": "symbol",
      "title": "UICornerCurve.continuous",
      "type": "topic",
      "url": "/documentation/uikit/uicornercurve/continuous"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICornerCurve/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICornerCurve/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/uicornercurve/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/capsuleShape": {
      "abstract": [
        {
          "text": "Creates a capsule shape, a rounded rectangle with a corner radius equal to half the length of the rectangle’s smallest edge.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "capsuleShape"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/capsuleShape",
      "kind": "symbol",
      "role": "symbol",
      "title": "capsuleShape",
      "type": "topic",
      "url": "/documentation/uikit/uishape-c.class/capsuleshape"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/circleShape": {
      "abstract": [
        {
          "text": "Creates a circular shape, with a radius equal to half the length of the frame rectangle’s smallest edge.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "circleShape"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/circleShape",
      "kind": "symbol",
      "role": "symbol",
      "title": "circleShape",
      "type": "topic",
      "url": "/documentation/uikit/uishape-c.class/circleshape"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/fixedRectShapeWithRect:": {
      "abstract": [
        {
          "text": "Creates a fixed rectangular shape that uses the provided rectangle as its shape, regardless of the frame that contains it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "fixedRectShapeWithRect:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/fixedRectShapeWithRect:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fixedRectShapeWithRect:"
        }
      ],
      "role": "symbol",
      "title": "fixedRectShapeWithRect:",
      "type": "topic",
      "url": "/documentation/uikit/uishape-c.class/fixedrectshapewithrect:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/fixedRectShapeWithRect:cornerRadius:": {
      "abstract": [
        {
          "text": "Creates a fixed rectangular shape with the provided corner radius, using the provided rectangle as its shape.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "fixedRectShapeWithRect:cornerRadius:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/fixedRectShapeWithRect:cornerRadius:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fixedRectShapeWithRect:cornerRadius:"
        }
      ],
      "role": "symbol",
      "title": "fixedRectShapeWithRect:cornerRadius:",
      "type": "topic",
      "url": "/documentation/uikit/uishape-c.class/fixedrectshapewithrect:cornerradius:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/fixedRectShapeWithRect:cornerRadius:cornerCurve:maskedCorners:": {
      "abstract": [
        {
          "text": "Creates a fixed rectangular shape with the provided corner radius and corner curve, using the provided rectangle as its shape.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "fixedRectShapeWithRect:cornerRadius:cornerCurve:maskedCorners:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/fixedRectShapeWithRect:cornerRadius:cornerCurve:maskedCorners:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fixedRectShapeWithRect:cornerRadius:cornerCurve:maskedCorners:"
        }
      ],
      "role": "symbol",
      "title": "fixedRectShapeWithRect:cornerRadius:cornerCurve:maskedCorners:",
      "type": "topic",
      "url": "/documentation/uikit/uishape-c.class/fixedrectshapewithrect:cornerradius:cornercurve:maskedcorners:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/rectShape": {
      "abstract": [
        {
          "text": "Creates a rectangular shape.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "rectShape"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/rectShape",
      "kind": "symbol",
      "role": "symbol",
      "title": "rectShape",
      "type": "topic",
      "url": "/documentation/uikit/uishape-c.class/rectshape"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/rectShapeWithCornerRadius:": {
      "abstract": [
        {
          "text": "Creates a rectangular shape with rounded corners, using the provided corner radius.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "rectShapeWithCornerRadius:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/rectShapeWithCornerRadius:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rectShapeWithCornerRadius:"
        }
      ],
      "role": "symbol",
      "title": "rectShapeWithCornerRadius:",
      "type": "topic",
      "url": "/documentation/uikit/uishape-c.class/rectshapewithcornerradius:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/rectShapeWithCornerRadius:cornerCurve:": {
      "abstract": [
        {
          "text": "Creates a rectangular shape with rounded corners, using the provided corner radius and corner curve.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "rectShapeWithCornerRadius:cornerCurve:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/rectShapeWithCornerRadius:cornerCurve:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rectShapeWithCornerRadius:cornerCurve:"
        }
      ],
      "role": "symbol",
      "title": "rectShapeWithCornerRadius:cornerCurve:",
      "type": "topic",
      "url": "/documentation/uikit/uishape-c.class/rectshapewithcornerradius:cornercurve:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/rectShapeWithCornerRadius:cornerCurve:maskedCorners:": {
      "abstract": [
        {
          "text": "Creates a rectangular shape with rounded corners, using the provided corner radius, corner curve, and rectangle corners.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "rectShapeWithCornerRadius:cornerCurve:maskedCorners:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/rectShapeWithCornerRadius:cornerCurve:maskedCorners:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rectShapeWithCornerRadius:cornerCurve:maskedCorners:"
        }
      ],
      "role": "symbol",
      "title": "rectShapeWithCornerRadius:cornerCurve:maskedCorners:",
      "type": "topic",
      "url": "/documentation/uikit/uishape-c.class/rectshapewithcornerradius:cornercurve:maskedcorners:"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Choosing-a-corner-style",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICornerCurve/automatic",
        "doc://com.apple.uikit/documentation/UIKit/UICornerCurve/circular",
        "doc://com.apple.uikit/documentation/UIKit/UICornerCurve/continuous"
      ],
      "title": "Choosing a corner style"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICornerCurve/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UICornerCurve"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICornerCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICornerCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Choosing-a-corner-style",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UICornerCurve/automatic",
                "doc://com.apple.uikit/documentation/UIKit/UICornerCurve/circular",
                "doc://com.apple.uikit/documentation/UIKit/UICornerCurve/continuous"
              ],
              "title": "Choosing a corner style"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-a-hover-shape",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/rectShape",
                "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/capsuleShape",
                "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/circleShape",
                "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/rectShapeWithCornerRadius:",
                "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/rectShapeWithCornerRadius:cornerCurve:",
                "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/rectShapeWithCornerRadius:cornerCurve:maskedCorners:",
                "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/fixedRectShapeWithRect:",
                "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/fixedRectShapeWithRect:cornerRadius:",
                "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/fixedRectShapeWithRect:cornerRadius:cornerCurve:maskedCorners:"
              ],
              "title": "Creating a hover shape"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UICornerCurve"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICornerCurve~1circular/title",
          "value": "UICornerCurveCircular"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICornerCurve~1circular/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICornerCurveCircular"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICornerCurve~1automatic/title",
          "value": "UICornerCurveAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICornerCurve~1automatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICornerCurveAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICornerCurve~1continuous/title",
          "value": "UICornerCurveContinuous"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICornerCurve~1continuous/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICornerCurveContinuous"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICornerCurve/title",
          "value": "UICornerCurve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICornerCurve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICornerCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICornerCurve/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICornerCurve"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uicornercurve"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uicornercurve"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
