{
  "abstract": [
    {
      "text": "A structure that encapsulates state for a content-unavailable view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfigurationState-swift.struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:5UIKit38UIContentUnavailableConfigurationStateV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIContentUnavailableConfigurationState"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIContentUnavailableConfigurationState"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "UIContentUnavailableConfigurationState"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIContentUnavailableConfigurationState"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Typically, you don’t create a configuration state yourself. To obtain a configuration state, override ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/updateContentUnavailableConfiguration(using:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in your view controller subclass and use the state parameter. Outside of this method, you can get a view controller’s configuration state from the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/contentUnavailableConfigurationState-7sczw",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can create your own custom states to add to a content-unavailable configuration state by defining a custom state key with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIConfigurationStateCustomKey",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-8d7pd": {
      "abstract": [
        {
          "text": "The requirements for an object that encapsulates a view’s state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIConfigurationState"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-8d7pd",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIConfigurationState"
        }
      ],
      "role": "symbol",
      "title": "UIConfigurationState",
      "type": "topic",
      "url": "/documentation/uikit/uiconfigurationstate-8d7pd"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIConfigurationStateCustomKey": {
      "abstract": [
        {
          "text": "A key that defines a custom state for a view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIConfigurationStateCustomKey"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIConfigurationStateCustomKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIConfigurationStateCustomKey"
        }
      ],
      "role": "symbol",
      "title": "UIConfigurationStateCustomKey",
      "type": "topic",
      "url": "/documentation/uikit/uiconfigurationstatecustomkey"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct": {
      "abstract": [
        {
          "text": "A content configuration for a content-unavailable view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIContentUnavailableConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentUnavailableConfiguration"
        }
      ],
      "role": "symbol",
      "title": "UIContentUnavailableConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfigurationState-swift.struct": {
      "abstract": [
        {
          "text": "A structure that encapsulates state for a content-unavailable view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIContentUnavailableConfigurationState"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfigurationState-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentUnavailableConfigurationState"
        }
      ],
      "role": "symbol",
      "title": "UIContentUnavailableConfigurationState",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfigurationstate-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfigurationState-swift.struct/searchText": {
      "abstract": [
        {
          "text": "The search text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchText"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfigurationState-swift.struct/searchText",
      "kind": "symbol",
      "role": "symbol",
      "title": "searchText",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfigurationstate-swift.struct/searchtext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/contentUnavailableConfigurationState-7sczw": {
      "abstract": [
        {
          "text": "The current configuration state of the content-unavailable view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentUnavailableConfigurationState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit38UIContentUnavailableConfigurationStateV",
          "text": "UIContentUnavailableConfigurationState"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/contentUnavailableConfigurationState-7sczw",
      "kind": "symbol",
      "role": "symbol",
      "title": "contentUnavailableConfigurationState",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/contentunavailableconfigurationstate-7sczw"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/updateContentUnavailableConfiguration(using:)": {
      "abstract": [
        {
          "text": "Updates the content-unavailable configuration for the provided state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateContentUnavailableConfiguration"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit38UIContentUnavailableConfigurationStateV",
          "text": "UIContentUnavailableConfigurationState"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/updateContentUnavailableConfiguration(using:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "updateContentUnavailableConfiguration(using:)",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/updatecontentunavailableconfiguration(using:)"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s17CustomReflectableP": {
      "abstract": [
        {
          "text": "A type that explicitly supplies its own mirror.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomReflectable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s17CustomReflectableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomReflectable",
      "type": "topic",
      "url": "/documentation/Swift/CustomReflectable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s17CustomReflectableP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-8d7pd"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Unavailable-content-configurations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct"
      ],
      "title": "Unavailable content configurations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfigurationState-swift.struct/searchText"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIConfigurationStateCustomKey/title",
          "value": "UIConfigurationStateCustomKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIConfigurationStateCustomKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIConfigurationStateCustomKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIConfigurationStateCustomKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIConfigurationStateCustomKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uicontentunavailableconfigurationstate-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
