{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uicontentview-3zu2k"]}],"identifier":{"interfaceLanguage":"occ","url":"doc://com.apple.uikit/documentation/UIKit/UIContentView-3zu2k"},"sections":[],"abstract":[{"type":"text","text":"The requirements for a content view that you create using a configuration."}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"UIContentView"}],"title":"UIContentView","modules":[{"name":"UIKit"}],"role":"symbol","roleHeading":"Protocol","symbolKind":"protocol","externalID":"c:objc(pl)UIContentView","fragments":[{"kind":"identifier","text":"UIContentView"}],"platforms":[{"unavailable":false,"deprecated":false,"beta":false,"name":"iOS","introducedAt":"14.0"},{"unavailable":false,"deprecated":false,"beta":false,"name":"iPadOS","introducedAt":"14.0"},{"unavailable":false,"deprecated":false,"beta":false,"name":"Mac Catalyst","introducedAt":"14.0"},{"unavailable":false,"deprecated":false,"beta":false,"name":"tvOS","introducedAt":"14.0"},{"unavailable":false,"deprecated":false,"beta":false,"name":"visionOS","introducedAt":"1.0"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","seeAlsoSections":[{"title":"Content configurations","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-c.class","doc://com.apple.uikit/documentation/UIKit/UIListContentView","doc://com.apple.uikit/documentation/UIKit/UIContentConfiguration-2raci"],"anchor":"Content-configurations"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"topicSections":[{"title":"Managing the content configuration","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIContentView-3zu2k/configuration"],"anchor":"Managing-the-content-configuration"},{"title":"Determining configuration support","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIContentView-3zu2k/supportsConfiguration:"],"anchor":"Determining-configuration-support"}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc://com.externally.resolved.symbol/c:objc(pl)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforming Types","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableView","doc://com.apple.uikit/documentation/UIKit/UIListContentView"],"kind":"relationships","type":"conformingTypes"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIContentView","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"]}]},{"content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This protocol provides a blueprint for a content view object that renders the content and styling that you define with its configuration. The content view’s configuration encapsulates all of the supported properties and behaviors for content view customization. Setting the content view’s "},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIContentView-5fh3z/configuration","isActive":true},{"type":"text","text":" property applies the new configuration to the view, causing the view to render any updates to its appearance."}]}],"kind":"content"}],"references":{"doc://com.apple.uikit/documentation/UIKit/UIContentView-3zu2k/configuration":{"url":"/documentation/uikit/uicontentview-3zu2k/configuration","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIContentView-3zu2k/configuration","title":"configuration","fragments":[{"text":"configuration","kind":"identifier"}],"abstract":[{"type":"text","text":"The current configuration of the view."}],"kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIListContentView":{"navigatorTitle":[{"text":"UIListContentView","kind":"identifier"}],"title":"UIListContentView","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIListContentView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIListContentView","kind":"identifier"}],"abstract":[{"type":"text","text":"A content view for displaying list-based content."}],"url":"/documentation/uikit/uilistcontentview","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIContentConfiguration-2raci":{"role":"symbol","type":"topic","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIContentConfiguration-2raci","fragments":[{"kind":"identifier","text":"UIContentConfiguration"}],"title":"UIContentConfiguration","abstract":[{"text":"The requirements for an object that provides the configuration for a content view.","type":"text"}],"url":"/documentation/uikit/uicontentconfiguration-2raci"},"doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-c.class":{"abstract":[{"text":"A content configuration for a list-based content view.","type":"text"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-c.class","fragments":[{"kind":"identifier","text":"UIListContentConfiguration"}],"title":"UIListContentConfiguration","role":"symbol","type":"topic","url":"/documentation/uikit/uilistcontentconfiguration-c.class"},"doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableView":{"title":"UIContentUnavailableView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIContentUnavailableView","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"UIContentUnavailableView","kind":"identifier"}],"abstract":[{"type":"text","text":"A view that indicates there’s no content to display."}],"url":"/documentation/uikit/uicontentunavailableview","identifier":"doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableView"},"doc://com.apple.uikit/documentation/UIKit/UIContentView-3zu2k":{"fragments":[{"text":"UIContentView","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIContentView-3zu2k","abstract":[{"type":"text","text":"The requirements for a content view that you create using a configuration."}],"role":"symbol","type":"topic","url":"/documentation/uikit/uicontentview-3zu2k","kind":"symbol","title":"UIContentView"},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"title":"NSObjectProtocol","type":"topic","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","role":"symbol","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"kind":"symbol","url":"/documentation/objectivec/nsobjectprotocol"},"doc://com.apple.uikit/documentation/UIKit/UIContentView-3zu2k/supportsConfiguration:":{"url":"/documentation/uikit/uicontentview-3zu2k/supportsconfiguration:","type":"topic","navigatorTitle":[{"text":"supportsConfiguration:","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIContentView-3zu2k/supportsConfiguration:","title":"supportsConfiguration:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"supportsConfiguration:"}],"abstract":[{"type":"text","text":"Determines whether the view is compatible with the provided configuration."}],"kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIContentView-5fh3z/configuration":{"type":"topic","kind":"symbol","role":"symbol","title":"configuration","url":"/documentation/uikit/uicontentview-5fh3z/configuration","abstract":[{"type":"text","text":"The current configuration of the view."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIContentView-5fh3z/configuration","required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"configuration","kind":"identifier"},{"text":": any ","kind":"text"},{"text":"UIContentConfiguration","kind":"typeIdentifier","preciseIdentifier":"s:5UIKit22UIContentConfigurationP"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIListContentView/title","value":"UIListContentView"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIListContentView/fragments","value":[{"text":"UIListContentView","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIListContentView/navigatorTitle","value":[{"text":"UIListContentView","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentUnavailableView/title","value":"UIContentUnavailableView"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentUnavailableView/fragments","value":[{"text":"UIContentUnavailableView","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentUnavailableView/navigatorTitle","value":[{"kind":"identifier","text":"UIContentUnavailableView"}]},{"value":"NSObject","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}