{
  "abstract": [
    {
      "text": "An object that encapsulates state for a content-unavailable view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfigurationState-c.class"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIContentUnavailableConfigurationState",
    "fragments": [
      {
        "kind": "identifier",
        "text": "UIContentUnavailableConfigurationState"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIContentUnavailableConfigurationState"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "UIContentUnavailableConfigurationState"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIContentUnavailableConfigurationState"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Typically, you don’t create a configuration state yourself. To obtain a configuration state, override ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/updateContentUnavailableConfigurationUsingState:",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in your view controller subclass and use the state parameter. Outside of this method, you can get a view controller’s configuration state from the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/contentUnavailableConfigurationState-9bvga",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can create your own custom states to add to a content unavailable configuration state by defining a custom state key with ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIConfigurationStateCustomKey",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-1smq1": {
      "abstract": [
        {
          "text": "The requirements for an object that encapsulates a view’s state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIConfigurationState"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-1smq1",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIConfigurationState",
      "type": "topic",
      "url": "/documentation/uikit/uiconfigurationstate-1smq1"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIConfigurationStateCustomKey": {
      "abstract": [
        {
          "text": "A key that defines a custom state for a view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIConfigurationStateCustomKey"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIConfigurationStateCustomKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIConfigurationStateCustomKey"
        }
      ],
      "role": "symbol",
      "title": "UIConfigurationStateCustomKey",
      "type": "topic",
      "url": "/documentation/uikit/uiconfigurationstatecustomkey"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableAlignment": {
      "abstract": [
        {
          "text": "Defines the alignment of views in a content-unavailable view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIContentUnavailableAlignment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableAlignment",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIContentUnavailableAlignment",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailablealignment"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableButtonProperties": {
      "abstract": [
        {
          "text": "Properties configuring the appearance and behavior of a button in a content-unavailable view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIContentUnavailableButtonProperties"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableButtonProperties",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIContentUnavailableButtonProperties",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailablebuttonproperties"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class": {
      "abstract": [
        {
          "text": "A content configuration for a content-unavailable view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIContentUnavailableConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIContentUnavailableConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfigurationState-c.class": {
      "abstract": [
        {
          "text": "An object that encapsulates state for a content-unavailable view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIContentUnavailableConfigurationState"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfigurationState-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIContentUnavailableConfigurationState",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfigurationstate-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfigurationState-c.class/initWithCoder:": {
      "abstract": [
        {
          "text": "Creates a configuration state from data in an unarchiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithCoder:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfigurationState-c.class/initWithCoder:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCoder:"
        }
      ],
      "role": "symbol",
      "title": "initWithCoder:",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfigurationstate-c.class/initwithcoder:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfigurationState-c.class/initWithTraitCollection:": {
      "abstract": [
        {
          "text": "Creates a configuration state with the specified trait collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithTraitCollection:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfigurationState-c.class/initWithTraitCollection:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTraitCollection:"
        }
      ],
      "role": "symbol",
      "title": "initWithTraitCollection:",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfigurationstate-c.class/initwithtraitcollection:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfigurationState-c.class/searchText": {
      "abstract": [
        {
          "text": "The search text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "searchText"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfigurationState-c.class/searchText",
      "kind": "symbol",
      "role": "symbol",
      "title": "searchText",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfigurationstate-c.class/searchtext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfigurationState-c.class/traitCollection": {
      "abstract": [
        {
          "text": "The traits describing the current user interface environment of the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "traitCollection"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfigurationState-c.class/traitCollection",
      "kind": "symbol",
      "role": "symbol",
      "title": "traitCollection",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfigurationstate-c.class/traitcollection"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableImageProperties": {
      "abstract": [
        {
          "text": "Properties configuring the appearance of images in a content-unavailable view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIContentUnavailableImageProperties"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableImageProperties",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIContentUnavailableImageProperties",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableimageproperties"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableTextProperties": {
      "abstract": [
        {
          "text": "Properties configuring the appearance of text in a content-unavailable view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIContentUnavailableTextProperties"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableTextProperties",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIContentUnavailableTextProperties",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailabletextproperties"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/contentUnavailableConfigurationState-9bvga": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "contentUnavailableConfigurationState"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/contentUnavailableConfigurationState-9bvga",
      "kind": "symbol",
      "role": "symbol",
      "title": "contentUnavailableConfigurationState",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/contentunavailableconfigurationstate-9bvga"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/updateContentUnavailableConfigurationUsingState:": {
      "abstract": [
        {
          "text": "Updates the content-unavailable configuration for the provided state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "updateContentUnavailableConfigurationUsingState:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/updateContentUnavailableConfigurationUsingState:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateContentUnavailableConfigurationUsingState:"
        }
      ],
      "role": "symbol",
      "title": "updateContentUnavailableConfigurationUsingState:",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/updatecontentunavailableconfigurationusingstate:"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-1smq1"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Unavailable-content-configurations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableButtonProperties",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableImageProperties",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableTextProperties",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableAlignment"
      ],
      "title": "Unavailable content configurations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfigurationState-c.class/searchText",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfigurationState-c.class/traitCollection"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfigurationState-c.class/initWithCoder:",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfigurationState-c.class/initWithTraitCollection:"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIConfigurationStateCustomKey/title",
          "value": "UIConfigurationStateCustomKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIConfigurationStateCustomKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIConfigurationStateCustomKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIConfigurationStateCustomKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIConfigurationStateCustomKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uicontentunavailableconfigurationstate-c.class"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
