{
  "abstract": [
    {
      "text": "A content configuration for a content-unavailable view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIContentUnavailableConfiguration",
    "fragments": [
      {
        "kind": "identifier",
        "text": "UIContentUnavailableConfiguration"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIContentUnavailableConfiguration"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "UIContentUnavailableConfiguration"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIContentUnavailableConfiguration"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A content-unavailable configuration is a composable description of a view that indicates that your app can’t display content. Using a content-unavailable configuration, you can obtain system default styling for a variety of different empty states. Fill the configuration with placeholder content, and then assign it to a view controller’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/contentUnavailableConfiguration-6kqfk",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", or to a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following screenshot shows an example of a content-unavailable view configured by setting the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/image",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/text",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/secondaryText",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-4274238",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentConfiguration-2raci": {
      "abstract": [
        {
          "text": "The requirements for an object that provides the configuration for a content view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIContentConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentConfiguration-2raci",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIContentConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uicontentconfiguration-2raci"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableAlignment": {
      "abstract": [
        {
          "text": "Defines the alignment of views in a content-unavailable view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIContentUnavailableAlignment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableAlignment",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIContentUnavailableAlignment",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailablealignment"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableButtonProperties": {
      "abstract": [
        {
          "text": "Properties configuring the appearance and behavior of a button in a content-unavailable view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIContentUnavailableButtonProperties"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableButtonProperties",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIContentUnavailableButtonProperties",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailablebuttonproperties"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class": {
      "abstract": [
        {
          "text": "A content configuration for a content-unavailable view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIContentUnavailableConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIContentUnavailableConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/alignment": {
      "abstract": [
        {
          "text": "The alignment of the image, text, and buttons.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "alignment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/alignment",
      "kind": "symbol",
      "role": "symbol",
      "title": "alignment",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-c.class/alignment"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/attributedText": {
      "abstract": [
        {
          "text": "An attributed variant of the primary text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "attributedText"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/attributedText",
      "kind": "symbol",
      "role": "symbol",
      "title": "attributedText",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-c.class/attributedtext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/axesPreservingSuperviewLayoutMargins": {
      "abstract": [
        {
          "text": "Configures which margins use the layout margins inherited from the superview.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "axesPreservingSuperviewLayoutMargins"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/axesPreservingSuperviewLayoutMargins",
      "kind": "symbol",
      "role": "symbol",
      "title": "axesPreservingSuperviewLayoutMargins",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-c.class/axespreservingsuperviewlayoutmargins"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/background": {
      "abstract": [
        {
          "text": "The configuration for the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "background"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/background",
      "kind": "symbol",
      "role": "symbol",
      "title": "background",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-c.class/background"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/button": {
      "abstract": [
        {
          "text": "The configuration for the primary button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "button"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/button",
      "kind": "symbol",
      "role": "symbol",
      "title": "button",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-c.class/button"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/buttonProperties": {
      "abstract": [
        {
          "text": "Additional configuration for the primary button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "buttonProperties"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/buttonProperties",
      "kind": "symbol",
      "role": "symbol",
      "title": "buttonProperties",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-c.class/buttonproperties"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/buttonToSecondaryButtonPadding": {
      "abstract": [
        {
          "text": "The padding between the primary button and secondary button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "buttonToSecondaryButtonPadding"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/buttonToSecondaryButtonPadding",
      "kind": "symbol",
      "role": "symbol",
      "title": "buttonToSecondaryButtonPadding",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-c.class/buttontosecondarybuttonpadding"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/directionalLayoutMargins": {
      "abstract": [
        {
          "text": "The margins between the content and the edges of the content view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "directionalLayoutMargins"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/directionalLayoutMargins",
      "kind": "symbol",
      "role": "symbol",
      "title": "directionalLayoutMargins",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-c.class/directionallayoutmargins"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/emptyConfiguration": {
      "abstract": [
        {
          "text": "Creates a configuration ready to customize.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "emptyConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/emptyConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "emptyConfiguration"
        }
      ],
      "role": "symbol",
      "title": "emptyConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-c.class/emptyconfiguration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/image": {
      "abstract": [
        {
          "text": "The image to display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "image"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/image",
      "kind": "symbol",
      "role": "symbol",
      "title": "image",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-c.class/image"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/imageProperties": {
      "abstract": [
        {
          "text": "The configuration for the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "imageProperties"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/imageProperties",
      "kind": "symbol",
      "role": "symbol",
      "title": "imageProperties",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-c.class/imageproperties"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/imageToTextPadding": {
      "abstract": [
        {
          "text": "The padding between the image and the primary text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "imageToTextPadding"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/imageToTextPadding",
      "kind": "symbol",
      "role": "symbol",
      "title": "imageToTextPadding",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-c.class/imagetotextpadding"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/loadingConfiguration": {
      "abstract": [
        {
          "text": "Creates a configuration appropriate for indicating a view is waiting on content to load.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "loadingConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/loadingConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadingConfiguration"
        }
      ],
      "role": "symbol",
      "title": "loadingConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-c.class/loadingconfiguration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/searchConfiguration": {
      "abstract": [
        {
          "text": "Creates a configuration appropriate for indicating an empty search result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "searchConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/searchConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "searchConfiguration"
        }
      ],
      "role": "symbol",
      "title": "searchConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-c.class/searchconfiguration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/secondaryAttributedText": {
      "abstract": [
        {
          "text": "An attributed variant of the secondary text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "secondaryAttributedText"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/secondaryAttributedText",
      "kind": "symbol",
      "role": "symbol",
      "title": "secondaryAttributedText",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-c.class/secondaryattributedtext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/secondaryButton": {
      "abstract": [
        {
          "text": "The configuration for the secondary button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "secondaryButton"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/secondaryButton",
      "kind": "symbol",
      "role": "symbol",
      "title": "secondaryButton",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-c.class/secondarybutton"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/secondaryButtonProperties": {
      "abstract": [
        {
          "text": "Additional configuration for the secondary button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "secondaryButtonProperties"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/secondaryButtonProperties",
      "kind": "symbol",
      "role": "symbol",
      "title": "secondaryButtonProperties",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-c.class/secondarybuttonproperties"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/secondaryText": {
      "abstract": [
        {
          "text": "The secondary text to display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "secondaryText"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/secondaryText",
      "kind": "symbol",
      "role": "symbol",
      "title": "secondaryText",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-c.class/secondarytext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/secondaryTextProperties": {
      "abstract": [
        {
          "text": "Properties for configuring the secondary text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "secondaryTextProperties"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/secondaryTextProperties",
      "kind": "symbol",
      "role": "symbol",
      "title": "secondaryTextProperties",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-c.class/secondarytextproperties"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/text": {
      "abstract": [
        {
          "text": "The primary text to display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/text",
      "kind": "symbol",
      "role": "symbol",
      "title": "text",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-c.class/text"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/textProperties": {
      "abstract": [
        {
          "text": "Properties for configuring the primary text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "textProperties"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/textProperties",
      "kind": "symbol",
      "role": "symbol",
      "title": "textProperties",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-c.class/textproperties"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/textToButtonPadding": {
      "abstract": [
        {
          "text": "The padding between the text and buttons.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "textToButtonPadding"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/textToButtonPadding",
      "kind": "symbol",
      "role": "symbol",
      "title": "textToButtonPadding",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-c.class/texttobuttonpadding"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/textToSecondaryTextPadding": {
      "abstract": [
        {
          "text": "The padding between the primary and secondary text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "textToSecondaryTextPadding"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/textToSecondaryTextPadding",
      "kind": "symbol",
      "role": "symbol",
      "title": "textToSecondaryTextPadding",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-c.class/texttosecondarytextpadding"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfigurationState-c.class": {
      "abstract": [
        {
          "text": "An object that encapsulates state for a content-unavailable view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIContentUnavailableConfigurationState"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfigurationState-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIContentUnavailableConfigurationState",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfigurationstate-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableImageProperties": {
      "abstract": [
        {
          "text": "Properties configuring the appearance of images in a content-unavailable view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIContentUnavailableImageProperties"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableImageProperties",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIContentUnavailableImageProperties",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableimageproperties"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableTextProperties": {
      "abstract": [
        {
          "text": "Properties configuring the appearance of text in a content-unavailable view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIContentUnavailableTextProperties"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableTextProperties",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIContentUnavailableTextProperties",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailabletextproperties"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableView": {
      "abstract": [
        {
          "text": "A view that indicates there’s no content to display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIContentUnavailableView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentUnavailableView"
        }
      ],
      "role": "symbol",
      "title": "UIContentUnavailableView",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/contentUnavailableConfiguration-6kqfk": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "contentUnavailableConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/contentUnavailableConfiguration-6kqfk",
      "kind": "symbol",
      "role": "symbol",
      "title": "contentUnavailableConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/contentunavailableconfiguration-6kqfk"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "media-4274238": {
      "alt": "A screenshot of a content-unavailable view indicating that a user has no files in the iCloud Drive Downloads folder.",
      "identifier": "media-4274238",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/7c656513bf8e80dc345aa2d89f317248/media-4274238@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/a288bb691822db7face6d5cca4d9e0d1/media-4274238~dark@2x.png"
        }
      ]
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
        "doc://com.apple.uikit/documentation/UIKit/UIContentConfiguration-2raci"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Unavailable-content-configurations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfigurationState-c.class",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableButtonProperties",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableImageProperties",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableTextProperties",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableAlignment"
      ],
      "title": "Unavailable content configurations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/alignment",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/attributedText",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/axesPreservingSuperviewLayoutMargins",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/background",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/button",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/buttonProperties",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/buttonToSecondaryButtonPadding",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/directionalLayoutMargins",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/image",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/imageProperties",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/imageToTextPadding",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/secondaryAttributedText",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/secondaryButton",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/secondaryButtonProperties",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/secondaryText",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/secondaryTextProperties",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/text",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/textProperties",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/textToButtonPadding",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/textToSecondaryTextPadding"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Type-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/emptyConfiguration",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/loadingConfiguration",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class/searchConfiguration"
      ],
      "title": "Type Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentUnavailableView/title",
          "value": "UIContentUnavailableView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentUnavailableView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentUnavailableView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentUnavailableView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentUnavailableView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uicontentunavailableconfiguration-c.class"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
