{"variants":[{"paths":["/documentation/uikit/uiconfigurationstate-1smq1"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","doc://com.externally.resolved.symbol/c:objc(pl)NSObject","doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"]},{"type":"conformingTypes","kind":"relationships","title":"Conforming Types","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfigurationState-c.class","doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-c.class"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"UIConfigurationState"}],"platforms":[{"beta":false,"name":"iOS","introducedAt":"14.0","unavailable":false,"deprecated":false},{"beta":false,"name":"iPadOS","introducedAt":"14.0","unavailable":false,"deprecated":false},{"beta":false,"name":"Mac Catalyst","introducedAt":"14.0","unavailable":false,"deprecated":false},{"beta":false,"name":"tvOS","introducedAt":"14.0","unavailable":false,"deprecated":false},{"beta":false,"name":"visionOS","introducedAt":"1.0","unavailable":false,"deprecated":false}],"externalID":"c:objc(pl)UIConfigurationState","modules":[{"name":"UIKit"}],"role":"symbol","title":"UIConfigurationState","roleHeading":"Protocol","symbolKind":"protocol","fragments":[{"kind":"identifier","text":"UIConfigurationState"}]},"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"sections":[],"abstract":[{"type":"text","text":"The requirements for an object that encapsulates a view’s state."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"anchor":"Managing-configuration-states","title":"Managing configuration states","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-1smq1/traitCollection","doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-1smq1/customStateForKey:","doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-1smq1/setCustomState:forKey:","doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-1smq1/objectForKeyedSubscript:","doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-1smq1/setObject:forKeyedSubscript:"]},{"anchor":"Creating-a-configuration-state-manually","title":"Creating a configuration state manually","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-1smq1/initWithTraitCollection:"]}],"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIConfigurationState","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"NSCopying","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","preciseIdentifier":"c:objc(pl)NSCopying","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"NSSecureCoding","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding","preciseIdentifier":"c:objc(pl)NSSecureCoding","kind":"typeIdentifier"},{"text":">","kind":"text"}]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"overview","level":2,"text":"Overview","type":"heading"},{"inlineContent":[{"type":"text","text":"This protocol provides a blueprint for a configuration state object, which encompasses a trait collection along with all of the common states that affect a view’s appearance. A configuration state encapsulates the inputs that configure a view for any possible state or combination of states. You use a configuration state with background and content configurations to obtain the default appearance for a specific state."}],"type":"paragraph"},{"inlineContent":[{"text":"Typically, you don’t create a configuration state yourself. To obtain a configuration state, override the ","type":"text"},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/updateConfiguration(using:)","isActive":true},{"text":" method in your view subclass and use the state parameter. Outside of this method, you can get a view’s configuration state by using its ","type":"text"},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/configurationState-4u37h","isActive":true},{"text":" property.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"For more information, see ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-c.class","type":"reference","isActive":true},{"text":" and ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UICellConfigurationState-c.class","type":"reference","isActive":true},{"text":".","type":"text"}],"type":"paragraph"}]}],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-1smq1","interfaceLanguage":"occ"},"seeAlsoSections":[{"generated":true,"anchor":"Configuration-states","title":"Configuration states","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-c.class","doc://com.apple.uikit/documentation/UIKit/UICellConfigurationState-c.class","doc://com.apple.uikit/documentation/UIKit/UIConfigurationStateCustomKey"]}],"references":{"doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-1smq1":{"type":"topic","role":"symbol","title":"UIConfigurationState","fragments":[{"kind":"identifier","text":"UIConfigurationState"}],"abstract":[{"type":"text","text":"The requirements for an object that encapsulates a view’s state."}],"url":"/documentation/uikit/uiconfigurationstate-1smq1","identifier":"doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-1smq1","kind":"symbol"},"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying":{"kind":"symbol","abstract":[{"text":"A protocol that objects adopt to provide functional copies of themselves.","type":"text"}],"url":"/documentation/foundation/nscopying","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSCopying","kind":"identifier"}],"title":"NSCopying","type":"topic","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-1smq1/setObject:forKeyedSubscript:":{"navigatorTitle":[{"kind":"identifier","text":"setObject:forKeyedSubscript:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setObject:forKeyedSubscript:"}],"title":"setObject:forKeyedSubscript:","abstract":[{"type":"text","text":"Sets the object for the specified custom state key."}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-1smq1/setObject:forKeyedSubscript:","url":"/documentation/uikit/uiconfigurationstate-1smq1/setobject:forkeyedsubscript:","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-c.class":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-c.class","abstract":[{"type":"text","text":"A structure that encapsulates a view’s state."}],"title":"UIViewConfigurationState","fragments":[{"text":"UIViewConfigurationState","kind":"identifier"}],"role":"symbol","url":"/documentation/uikit/uiviewconfigurationstate-c.class","kind":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UICellConfigurationState-c.class":{"abstract":[{"text":"An object that encapsulates a cell’s state.","type":"text"}],"fragments":[{"kind":"identifier","text":"UICellConfigurationState"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UICellConfigurationState-c.class","role":"symbol","type":"topic","title":"UICellConfigurationState","kind":"symbol","url":"/documentation/uikit/uicellconfigurationstate-c.class"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIConfigurationStateCustomKey":{"role":"symbol","abstract":[{"type":"text","text":"A key that defines a custom state for a view."}],"url":"/documentation/uikit/uiconfigurationstatecustomkey","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIConfigurationStateCustomKey"}],"title":"UIConfigurationStateCustomKey","navigatorTitle":[{"kind":"identifier","text":"UIConfigurationStateCustomKey"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIConfigurationStateCustomKey","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-1smq1/initWithTraitCollection:":{"navigatorTitle":[{"text":"initWithTraitCollection:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithTraitCollection:","kind":"identifier"}],"kind":"symbol","title":"initWithTraitCollection:","abstract":[{"text":"Creates a configuration state with the specified trait collection.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-1smq1/initWithTraitCollection:","url":"/documentation/uikit/uiconfigurationstate-1smq1/initwithtraitcollection:"},"doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-1smq1/objectForKeyedSubscript:":{"title":"objectForKeyedSubscript:","url":"/documentation/uikit/uiconfigurationstate-1smq1/objectforkeyedsubscript:","abstract":[{"text":"Retrieves the object for the specified custom state key.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"objectForKeyedSubscript:","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-1smq1/objectForKeyedSubscript:","navigatorTitle":[{"text":"objectForKeyedSubscript:","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/configurationState-4u37h":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configurationState","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:5UIKit24UICellConfigurationStateV","text":"UICellConfigurationState","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/configurationState-4u37h","abstract":[{"text":"The current configuration state of the cell.","type":"text"}],"url":"/documentation/uikit/uicollectionviewcell/configurationstate-4u37h","title":"configurationState"},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"title":"NSObjectProtocol","type":"topic","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","role":"symbol","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"kind":"symbol","url":"/documentation/objectivec/nsobjectprotocol"},"doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfigurationState-c.class":{"url":"/documentation/uikit/uicontentunavailableconfigurationstate-c.class","kind":"symbol","fragments":[{"kind":"identifier","text":"UIContentUnavailableConfigurationState"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfigurationState-c.class","title":"UIContentUnavailableConfigurationState","role":"symbol","abstract":[{"type":"text","text":"An object that encapsulates state for a content-unavailable view."}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-1smq1/traitCollection":{"title":"traitCollection","url":"/documentation/uikit/uiconfigurationstate-1smq1/traitcollection","abstract":[{"text":"The traits that describe the current layout environment of the view, such as the user interface style and layout direction.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"traitCollection","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-1smq1/traitCollection"},"doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding":{"fragments":[{"kind":"text","text":"protocol "},{"kind":"identifier","text":"NSSecureCoding"}],"type":"topic","abstract":[{"text":"A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.","type":"text"}],"role":"symbol","kind":"symbol","url":"/documentation/foundation/nssecurecoding","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding","title":"NSSecureCoding"},"doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-1smq1/customStateForKey:":{"title":"customStateForKey:","url":"/documentation/uikit/uiconfigurationstate-1smq1/customstateforkey:","abstract":[{"text":"Retrieves the custom state for the specified custom state key.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"customStateForKey:","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-1smq1/customStateForKey:","navigatorTitle":[{"text":"customStateForKey:","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/updateConfiguration(using:)":{"abstract":[{"text":"Updates the cell’s configuration using the current state.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"updateConfiguration","kind":"identifier"},{"kind":"text","text":"("},{"text":"using","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UICellConfigurationState","kind":"typeIdentifier","preciseIdentifier":"s:5UIKit24UICellConfigurationStateV"},{"text":")","kind":"text"}],"url":"/documentation/uikit/uicollectionviewcell/updateconfiguration(using:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/updateConfiguration(using:)","kind":"symbol","type":"topic","role":"symbol","title":"updateConfiguration(using:)"},"doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-1smq1/setCustomState:forKey:":{"title":"setCustomState:forKey:","url":"/documentation/uikit/uiconfigurationstate-1smq1/setcustomstate:forkey:","abstract":[{"text":"Sets the custom state for the specified custom state key.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"setCustomState:forKey:","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-1smq1/setCustomState:forKey:","navigatorTitle":[{"text":"setCustomState:forKey:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"UIConfigurationStateCustomKey","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIConfigurationStateCustomKey/title"},{"value":[{"kind":"identifier","text":"UIConfigurationStateCustomKey"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIConfigurationStateCustomKey/fragments"},{"value":[{"text":"UIConfigurationStateCustomKey","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIConfigurationStateCustomKey/navigatorTitle"},{"value":"NSObject","op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}