{"topicSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIContentConfiguration-2raci/makeContentView"],"title":"Creating a content configuration","anchor":"Creating-a-content-configuration"},{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIContentConfiguration-2raci/updatedConfigurationForState:"],"title":"Updating a content configuration","anchor":"Updating-a-content-configuration"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uicontentconfiguration-2raci"]}],"identifier":{"interfaceLanguage":"occ","url":"doc://com.apple.uikit/documentation/UIKit/UIContentConfiguration-2raci"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"UIContentConfiguration","kind":"identifier"}],"roleHeading":"Protocol","title":"UIContentConfiguration","modules":[{"name":"UIKit"}],"platforms":[{"introducedAt":"14.0","beta":false,"name":"iOS","deprecated":false,"unavailable":false},{"introducedAt":"14.0","beta":false,"name":"iPadOS","deprecated":false,"unavailable":false},{"introducedAt":"14.0","beta":false,"name":"Mac Catalyst","deprecated":false,"unavailable":false},{"introducedAt":"14.0","beta":false,"name":"tvOS","deprecated":false,"unavailable":false},{"introducedAt":"1.0","beta":false,"name":"visionOS","deprecated":false,"unavailable":false}],"symbolKind":"protocol","role":"symbol","navigatorTitle":[{"text":"UIContentConfiguration","kind":"identifier"}],"externalID":"c:objc(pl)UIContentConfiguration"},"abstract":[{"type":"text","text":"The requirements for an object that provides the configuration for a content view."}],"kind":"symbol","seeAlsoSections":[{"anchor":"Content-configurations","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-c.class","doc://com.apple.uikit/documentation/UIKit/UIListContentView","doc://com.apple.uikit/documentation/UIKit/UIContentView-3zu2k"],"title":"Content configurations","generated":true}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"relationshipsSections":[{"identifiers":["doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","doc://com.externally.resolved.symbol/c:objc(pl)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class","doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-c.class"],"title":"Conforming Types","kind":"relationships","type":"conformingTypes"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIContentConfiguration"},{"kind":"text","text":" <"},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","text":"NSObject"},{"kind":"text","text":", "},{"preciseIdentifier":"c:objc(pl)NSCopying","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","text":"NSCopying"},{"kind":"text","text":">"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"This protocol provides a blueprint for a content-configuration object, which encompasses default styling and content for a content view. The content configuration encapsulates all of the supported properties and behaviors for content view customization. You use the configuration to create the content view.","type":"text"}]}]}],"references":{"doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class":{"url":"/documentation/uikit/uicontentunavailableconfiguration-c.class","role":"symbol","title":"UIContentUnavailableConfiguration","type":"topic","abstract":[{"type":"text","text":"A content configuration for a content-unavailable view."}],"fragments":[{"kind":"identifier","text":"UIContentUnavailableConfiguration"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-c.class","kind":"symbol"},"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying":{"kind":"symbol","abstract":[{"text":"A protocol that objects adopt to provide functional copies of themselves.","type":"text"}],"url":"/documentation/foundation/nscopying","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSCopying","kind":"identifier"}],"title":"NSCopying","type":"topic","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","role":"symbol"},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"title":"NSObjectProtocol","type":"topic","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","role":"symbol","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"kind":"symbol","url":"/documentation/objectivec/nsobjectprotocol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIContentView-3zu2k":{"fragments":[{"text":"UIContentView","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIContentView-3zu2k","abstract":[{"type":"text","text":"The requirements for a content view that you create using a configuration."}],"role":"symbol","type":"topic","url":"/documentation/uikit/uicontentview-3zu2k","kind":"symbol","title":"UIContentView"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIListContentView":{"navigatorTitle":[{"text":"UIListContentView","kind":"identifier"}],"title":"UIListContentView","role":"symbol","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIListContentView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIListContentView","kind":"identifier"}],"abstract":[{"type":"text","text":"A content view for displaying list-based content."}],"url":"/documentation/uikit/uilistcontentview","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-c.class":{"abstract":[{"text":"A content configuration for a list-based content view.","type":"text"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-c.class","fragments":[{"kind":"identifier","text":"UIListContentConfiguration"}],"title":"UIListContentConfiguration","role":"symbol","type":"topic","url":"/documentation/uikit/uilistcontentconfiguration-c.class"},"doc://com.apple.uikit/documentation/UIKit/UIContentConfiguration-2raci/makeContentView":{"role":"symbol","type":"topic","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIContentConfiguration-2raci/makeContentView","navigatorTitle":[{"kind":"identifier","text":"makeContentView"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"makeContentView"}],"title":"makeContentView","abstract":[{"text":"Creates a new instance of the content view using this configuration.","type":"text"}],"url":"/documentation/uikit/uicontentconfiguration-2raci/makecontentview"},"doc://com.apple.uikit/documentation/UIKit/UIContentConfiguration-2raci":{"role":"symbol","type":"topic","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIContentConfiguration-2raci","fragments":[{"kind":"identifier","text":"UIContentConfiguration"}],"title":"UIContentConfiguration","abstract":[{"text":"The requirements for an object that provides the configuration for a content view.","type":"text"}],"url":"/documentation/uikit/uicontentconfiguration-2raci"},"doc://com.apple.uikit/documentation/UIKit/UIContentConfiguration-2raci/updatedConfigurationForState:":{"navigatorTitle":[{"text":"updatedConfigurationForState:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"updatedConfigurationForState:","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIContentConfiguration-2raci/updatedConfigurationForState:","abstract":[{"type":"text","text":"Generates a configuration for the specified state by applying the configuration’s default values for that state to any properties that you haven’t customized."}],"role":"symbol","type":"topic","url":"/documentation/uikit/uicontentconfiguration-2raci/updatedconfigurationforstate:","kind":"symbol","title":"updatedConfigurationForState:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title","value":"NSObject"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIListContentView/title","value":"UIListContentView"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIListContentView/fragments","value":[{"kind":"identifier","text":"UIListContentView"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIListContentView/navigatorTitle","value":[{"text":"UIListContentView","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}