{
  "abstract": [
    {
      "text": "Your proposed solution for handling a drop in a collection view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropProposal"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UICollectionViewDropProposal",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UICollectionViewDropProposal"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UICollectionViewDropProposal"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "UICollectionViewDropProposal"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UICollectionViewDropProposal"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.uikit/documentation/UIKit/supporting-drag-and-drop-in-collection-views"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Create instances of this class in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidUpdate:withDestinationIndexPath:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method of your drop delegate object. You create drop proposals to let the collection view know how you intend to handle a drop at the currently specified location. The collection view uses that information to provide appropriate visual feedback to the user.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDragDelegate": {
      "abstract": [
        {
          "text": "The interface for initiating drags from a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewDragDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDragDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewDragDelegate"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewDragDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdragdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator": {
      "abstract": [
        {
          "text": "An interface for coordinating your custom drop-related actions with the collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewDropCoordinator"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewDropCoordinator"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewDropCoordinator",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdropcoordinator"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate": {
      "abstract": [
        {
          "text": "The interface for handling drops in a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewDropDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewDropDelegate"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewDropDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdropdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidUpdate:withDestinationIndexPath:)": {
      "abstract": [
        {
          "text": "Tells your delegate that the position of the dragged data over the collection view changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "collectionView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICollectionView",
          "text": "UICollectionView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dropSessionDidUpdate"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDropSession",
          "text": "UIDropSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withDestinationIndexPath"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation9IndexPathV",
          "text": "IndexPath"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICollectionViewDropProposal",
          "text": "UICollectionViewDropProposal"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidUpdate:withDestinationIndexPath:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "collectionView:dropSessionDidUpdate:withDestinationIndexPath:"
        }
      ],
      "role": "symbol",
      "title": "collectionView(_:dropSessionDidUpdate:withDestinationIndexPath:)",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdropdelegate/collectionview(_:dropsessiondidupdate:withdestinationindexpath:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropItem": {
      "abstract": [
        {
          "text": "The data associated with an item being dropped into the collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewDropItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewDropItem"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewDropItem",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdropitem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropPlaceholder": {
      "abstract": [
        {
          "text": "A placeholder for an item dropped on a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewDropPlaceholder"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropPlaceholder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewDropPlaceholder"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewDropPlaceholder",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdropplaceholder"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropPlaceholderContext": {
      "abstract": [
        {
          "text": "An object that contains information about a placeholder in the collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewDropPlaceholderContext"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropPlaceholderContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewDropPlaceholderContext"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewDropPlaceholderContext",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdropplaceholdercontext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropProposal": {
      "abstract": [
        {
          "text": "Your proposed solution for handling a drop in a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewDropProposal"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropProposal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewDropProposal"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewDropProposal",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdropproposal"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropProposal/Intent-swift.enum": {
      "abstract": [
        {
          "text": "Constants indicating how you intend to handle a drop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Intent"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropProposal/Intent-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Intent"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewDropProposal.Intent",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdropproposal/intent-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropProposal/init(operation:intent:)": {
      "abstract": [
        {
          "text": "Creates a drop proposal object that specifies how to incorporate the dropped content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "operation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIDropOperation",
          "text": "UIDropOperation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "intent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICollectionViewDropProposal",
          "text": "UICollectionViewDropProposal"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UICollectionViewDropIntent",
          "text": "Intent"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropProposal/init(operation:intent:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithDropOperation:intent:"
        }
      ],
      "role": "symbol",
      "title": "init(operation:intent:)",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdropproposal/init(operation:intent:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropProposal/intent-swift.property": {
      "abstract": [
        {
          "text": "The option to use when incorporating the dropped items into your content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "intent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICollectionViewDropProposal",
          "text": "UICollectionViewDropProposal"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UICollectionViewDropIntent",
          "text": "Intent"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropProposal/intent-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "intent"
        }
      ],
      "role": "symbol",
      "title": "intent",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdropproposal/intent-swift.property"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewPlaceholder": {
      "abstract": [
        {
          "text": "A placeholder for an item dragged or dropped on a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewPlaceholder"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewPlaceholder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewPlaceholder"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewPlaceholder",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewplaceholder"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDataSourceTranslating": {
      "abstract": [
        {
          "text": "An advanced interface for managing a data source object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDataSourceTranslating"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDataSourceTranslating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDataSourceTranslating"
        }
      ],
      "role": "symbol",
      "title": "UIDataSourceTranslating",
      "type": "topic",
      "url": "/documentation/uikit/uidatasourcetranslating"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDropOperation": {
      "abstract": [
        {
          "text": "Operation types that determine how a drag and drop activity resolves when the user drops a drag item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDropOperation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDropOperation"
        }
      ],
      "role": "symbol",
      "title": "UIDropOperation",
      "type": "topic",
      "url": "/documentation/uikit/uidropoperation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDropProposal": {
      "abstract": [
        {
          "text": "A configuration for the behavior of a drop interaction, required if a view accepts drop activities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDropProposal"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropProposal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDropProposal"
        }
      ],
      "role": "symbol",
      "title": "UIDropProposal",
      "type": "topic",
      "url": "/documentation/uikit/uidropproposal"
    },
    "doc://com.apple.uikit/documentation/UIKit/supporting-drag-and-drop-in-collection-views": {
      "abstract": [
        {
          "text": "Initiate drags and handle drops from a collection view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/supporting-drag-and-drop-in-collection-views",
      "kind": "article",
      "role": "article",
      "title": "Supporting Drag and Drop in Collection Views",
      "type": "topic",
      "url": "/documentation/uikit/supporting-drag-and-drop-in-collection-views"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIDropProposal"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Drag-and-drop",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/supporting-drag-and-drop-in-collection-views",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDragDelegate",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropPlaceholder",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropItem",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropPlaceholderContext",
        "doc://com.apple.uikit/documentation/UIKit/UIDataSourceTranslating",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewPlaceholder"
      ],
      "title": "Drag and drop"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Drop-Proposal",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropProposal/init(operation:intent:)"
      ],
      "title": "Creating a Drop Proposal"
    },
    {
      "anchor": "Getting-the-Proposed-Drop-Location",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropProposal/intent-swift.property",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropProposal/Intent-swift.enum",
        "doc://com.apple.uikit/documentation/UIKit/UIDropOperation"
      ],
      "title": "Getting the Proposed Drop Location"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UICollectionViewDropProposal"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropProposal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropProposal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Drop-Proposal",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropProposal/init(operation:intent:)"
              ],
              "title": "Creating a Drop Proposal"
            },
            {
              "anchor": "Getting-the-Proposed-Drop-Location",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropProposal/intent-swift.property",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropProposal/Intent-swift.enum",
                "doc://com.apple.uikit/documentation/UIKit/UIDropOperation"
              ],
              "title": "Getting the Proposed Drop Location"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIDropProposal"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Drag-and-drop",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/supporting-drag-and-drop-in-collection-views",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDragDelegate",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropPlaceholder",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropItem",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropPlaceholderContext",
                "doc://com.apple.uikit/documentation/UIKit/UIDataSourceTranslating",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewPlaceholder"
              ],
              "title": "Drag and drop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UICollectionViewDropProposal"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropProposal",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UIDropProposal",
                    "text": "UIDropProposal"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropOperation/title",
          "value": "UIDropOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDropOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDropOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropPlaceholderContext/title",
          "value": "UICollectionViewDropPlaceholderContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropPlaceholderContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropPlaceholderContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropPlaceholderContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropPlaceholderContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropProposal/title",
          "value": "UICollectionViewDropProposal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropProposal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropProposal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropProposal/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropProposal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropProposal~1intent-swift.property/title",
          "value": "intent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropProposal~1intent-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "intent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropProposal/title",
          "value": "UIDropProposal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropProposal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDropProposal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropProposal/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDropProposal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropPlaceholder/title",
          "value": "UICollectionViewDropPlaceholder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropPlaceholder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropPlaceholder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropPlaceholder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropPlaceholder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropProposal~1init(operation:intent:)/title",
          "value": "initWithDropOperation:intent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropProposal~1init(operation:intent:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithDropOperation:intent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropItem/title",
          "value": "UICollectionViewDropItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate~1collectionView(_:dropSessionDidUpdate:withDestinationIndexPath:)/title",
          "value": "collectionView:dropSessionDidUpdate:withDestinationIndexPath:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate~1collectionView(_:dropSessionDidUpdate:withDestinationIndexPath:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "collectionView:dropSessionDidUpdate:withDestinationIndexPath:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropProposal~1Intent-swift.enum/title",
          "value": "UICollectionViewDropIntent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropProposal~1Intent-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropProposal~1Intent-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropIntent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDataSourceTranslating/title",
          "value": "UIDataSourceTranslating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDataSourceTranslating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDataSourceTranslating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDataSourceTranslating/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDataSourceTranslating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate/title",
          "value": "UICollectionViewDropDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropCoordinator/title",
          "value": "UICollectionViewDropCoordinator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropCoordinator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropCoordinator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDragDelegate/title",
          "value": "UICollectionViewDragDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDragDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDragDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDragDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDragDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewPlaceholder/title",
          "value": "UICollectionViewPlaceholder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewPlaceholder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewPlaceholder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewPlaceholder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewPlaceholder"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uicollectionviewdropproposal"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uicollectionviewdropproposal"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
