{"metadata":{"externalID":"c:@T@UICollectionViewCompositionalLayoutSectionProvider","navigatorTitle":[{"kind":"identifier","text":"UICollectionViewCompositionalLayoutSectionProvider"}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"UICollectionViewCompositionalLayoutSectionProvider"}],"platforms":[{"unavailable":false,"beta":false,"name":"iOS","deprecated":false},{"unavailable":false,"beta":false,"name":"iPadOS","deprecated":false},{"unavailable":false,"beta":false,"name":"Mac Catalyst","deprecated":false},{"unavailable":false,"beta":false,"name":"tvOS","deprecated":false},{"unavailable":false,"beta":false,"name":"visionOS","deprecated":false}],"role":"symbol","modules":[{"name":"UIKit"}],"title":"UICollectionViewCompositionalLayoutSectionProvider","roleHeading":"Type Alias","symbolKind":"typealias"},"abstract":[{"type":"text","text":"A closure that creates and returns each of the layout’s sections."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"UICollectionViewCompositionalLayoutSectionProvider"},{"kind":"text","text":" = ("},{"kind":"typeIdentifier","text":"Int","identifier":"doc://com.externally.resolved.symbol/s:Si","preciseIdentifier":"s:Si"},{"kind":"text","text":", any "},{"kind":"typeIdentifier","text":"NSCollectionLayoutEnvironment","identifier":"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutEnvironment","preciseIdentifier":"c:objc(pl)NSCollectionLayoutEnvironment"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"NSCollectionLayoutSection","identifier":"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSection","preciseIdentifier":"c:objc(cs)NSCollectionLayoutSection"},{"kind":"text","text":"?"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"Discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You use a section provider to create a compositional layout ("},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCompositionalLayout","isActive":true},{"type":"text","text":") that has multiple sections with different layouts. The section provider keeps track of the index of the section that it’s currently creating, so you can configure each section differently."}]},{"type":"paragraph","inlineContent":[{"text":"For example, the following code shows a section provider that creates a two-column layout in the first section, and a four-column layout in each section after the first section.","type":"text"}]},{"tabs":[{"title":"Swift","content":[{"code":["func createPerSectionLayout() -> UICollectionViewLayout {","    let layout = UICollectionViewCompositionalLayout { (sectionIndex: Int,","        layoutEnvironment: NSCollectionLayoutEnvironment) -> NSCollectionLayoutSection? in","        ","        let columns = sectionIndex == 0 ? 2 : 4","        ","        let itemSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0),","                                             heightDimension: .fractionalHeight(1.0))","        let item = NSCollectionLayoutItem(layoutSize: itemSize)","        ","        let groupSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0),","                                              heightDimension: .absolute(44))","        let group = NSCollectionLayoutGroup.horizontal(layoutSize: groupSize,","                                                          subitem: item,","                                                            count: columns)","        ","        let section = NSCollectionLayoutSection(group: group)","        return section","    }","    return layout","}"],"type":"codeListing","syntax":"swift"}]},{"title":"Objective-C","content":[{"type":"codeListing","syntax":"objc","code":["UICollectionViewCompositionalLayout *layout = [[UICollectionViewCompositionalLayout alloc] initWithSectionProvider:^NSCollectionLayoutSection *(NSInteger sectionIndex, id<NSCollectionLayoutEnvironment> layoutEnvironment) {","    ","    NSInteger columns = (sectionIndex == 0) ? 2 : 4;","    ","    NSCollectionLayoutSize *itemSize = [NSCollectionLayoutSize sizeWithWidthDimension:[NSCollectionLayoutDimension fractionalWidthDimension:1.0] heightDimension:[NSCollectionLayoutDimension fractionalHeightDimension:1.0]];","    ","    NSCollectionLayoutItem *item = [NSCollectionLayoutItem itemWithLayoutSize:itemSize];","","    NSCollectionLayoutSize *groupSize = [NSCollectionLayoutSize sizeWithWidthDimension:[NSCollectionLayoutDimension fractionalWidthDimension:1.0] heightDimension:[NSCollectionLayoutDimension absoluteDimension:44.0]];","","    NSCollectionLayoutGroup *group = [NSCollectionLayoutGroup horizontalGroupWithLayoutSize:groupSize subitem:item count:columns];","            ","    NSCollectionLayoutSection *section = [NSCollectionLayoutSection sectionWithGroup:group];","    return section;","}];","","return layout;"]}]}],"type":"tabNavigator"},{"inlineContent":[{"type":"text","text":"A section provider is also invoked in response to system events such as changes in device orientation, system font size, and size classes from iPad multitasking. You can use this opportunity to adapt the layout to different layout environments by inspecting information about the current layout environment ("},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutEnvironment"},{"type":"text","text":") and using that information to configure each section."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"For example, the following code shows a section provider that creates a two-column layout when the width of the section’s container is less than 800 points, and a four-column layout otherwise."}],"type":"paragraph"},{"tabs":[{"title":"Swift","content":[{"type":"codeListing","syntax":"swift","code":["func createAdaptiveLayout() -> UICollectionViewLayout {","    let layout = UICollectionViewCompositionalLayout { (sectionIndex: Int,","        layoutEnvironment: NSCollectionLayoutEnvironment) -> NSCollectionLayoutSection in","","        let columns = layoutEnvironment.container.effectiveContentSize.width < 800 ? 2 : 4","        ","        let itemSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0),","                                             heightDimension: .fractionalHeight(1.0))","        let item = NSCollectionLayoutItem(layoutSize: itemSize)","        ","        let groupSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0),","                                              heightDimension: .absolute(44))","        let group = NSCollectionLayoutGroup.horizontal(layoutSize: groupSize,","                                                          subitem: item,","                                                            count: columns)","        ","        let section = NSCollectionLayoutSection(group: group)","        return section","    }","    return layout","}"]}]},{"title":"Objective-C","content":[{"code":["UICollectionViewCompositionalLayout *layout = [[UICollectionViewCompositionalLayout alloc] initWithSectionProvider:^NSCollectionLayoutSection *(NSInteger sectionIndex, id<NSCollectionLayoutEnvironment> layoutEnvironment) {    ","    NSInteger columns = (layoutEnvironment.container.effectiveContentSize.width < 800) ? 2 : 4;","    ","    NSCollectionLayoutSize *itemSize = [NSCollectionLayoutSize sizeWithWidthDimension:[NSCollectionLayoutDimension fractionalWidthDimension:1.0] heightDimension:[NSCollectionLayoutDimension fractionalHeightDimension:1.0]];","    ","    NSCollectionLayoutItem *item = [NSCollectionLayoutItem itemWithLayoutSize:itemSize];","","    NSCollectionLayoutSize *groupSize = [NSCollectionLayoutSize sizeWithWidthDimension:[NSCollectionLayoutDimension fractionalWidthDimension:1.0] heightDimension:[NSCollectionLayoutDimension absoluteDimension:44.0]];","","    NSCollectionLayoutGroup *group = [NSCollectionLayoutGroup horizontalGroupWithLayoutSize:groupSize subitem:item count:columns];","            ","    NSCollectionLayoutSection *section = [NSCollectionLayoutSection sectionWithGroup:group];","    return section;","}];","","return layout;"],"syntax":"objc","type":"codeListing"}]}],"type":"tabNavigator"},{"inlineContent":[{"text":"In iOS 18 and later, UIKit supports automatic trait tracking inside this closure for traits from the ","type":"text"},{"type":"codeVoice","code":"traitCollection"},{"text":" of the ","type":"text"},{"type":"codeVoice","code":"layoutEnvironment"},{"text":" parameter. For more information, see ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/automatic-trait-tracking"},{"text":".","type":"text"}],"type":"paragraph"}]}],"variants":[{"paths":["/documentation/uikit/uicollectionviewcompositionallayoutsectionprovider"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uicollectionviewcompositionallayoutsectionprovider"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCompositionalLayoutSectionProvider"},"kind":"symbol","references":{"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutEnvironment":{"abstract":[{"type":"text","text":"A protocol used to provide information about the layout’s container and environment traits, such as size classes and display scale factor."}],"url":"/documentation/uikit/nscollectionlayoutenvironment","identifier":"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutEnvironment","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSCollectionLayoutEnvironment","kind":"identifier"}],"role":"symbol","title":"NSCollectionLayoutEnvironment","type":"topic","kind":"symbol","navigatorTitle":[{"text":"NSCollectionLayoutEnvironment","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSection":{"navigatorTitle":[{"kind":"identifier","text":"NSCollectionLayoutSection"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/NSCollectionLayoutSection","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSCollectionLayoutSection"}],"url":"/documentation/uikit/nscollectionlayoutsection","abstract":[{"type":"text","text":"A container that combines a set of groups into distinct visual groupings."}],"title":"NSCollectionLayoutSection","type":"topic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCompositionalLayout":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCompositionalLayout","url":"/documentation/uikit/uicollectionviewcompositionallayout","kind":"symbol","title":"UICollectionViewCompositionalLayout","type":"topic","abstract":[{"type":"text","text":"A layout object that lets you combine items in highly adaptive and flexible visual arrangements."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UICollectionViewCompositionalLayout","kind":"identifier"}],"navigatorTitle":[{"text":"UICollectionViewCompositionalLayout","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/automatic-trait-tracking":{"kind":"article","abstract":[{"text":"Reduce the need to manually register for trait changes when you use traits within a method or closure that supports automatic trait tracking.","type":"text"}],"url":"/documentation/uikit/automatic-trait-tracking","identifier":"doc://com.apple.uikit/documentation/UIKit/automatic-trait-tracking","title":"Automatic trait tracking","role":"collectionGroup","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCompositionalLayoutSectionProvider":{"url":"/documentation/uikit/uicollectionviewcompositionallayoutsectionprovider","navigatorTitle":[{"text":"UICollectionViewCompositionalLayoutSectionProvider","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCompositionalLayoutSectionProvider","role":"symbol","kind":"symbol","type":"topic","title":"UICollectionViewCompositionalLayoutSectionProvider","abstract":[{"text":"A closure that creates and returns each of the layout’s sections.","type":"text"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UICollectionViewCompositionalLayoutSectionProvider","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:Si":{"url":"/documentation/Swift/Int","identifier":"doc://com.externally.resolved.symbol/s:Si","role":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}],"type":"topic","title":"Int","kind":"symbol","abstract":[{"type":"text","text":"A signed integer value type."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"deprecated":false,"name":"iOS","beta":false,"unavailable":false},{"deprecated":false,"name":"iPadOS","beta":false,"unavailable":false},{"deprecated":false,"name":"Mac Catalyst","beta":false,"unavailable":false},{"deprecated":false,"name":"tvOS","beta":false,"unavailable":false},{"deprecated":false,"name":"visionOS","beta":false,"unavailable":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Type Alias","path":"/metadata/roleHeading"},{"op":"replace","value":"UICollectionViewCompositionalLayoutSectionProvider","path":"/metadata/title"},{"op":"replace","value":"typealias","path":"/metadata/symbolKind"},{"value":[{"text":"UICollectionViewCompositionalLayoutSectionProvider","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"UICollectionViewCompositionalLayoutSectionProvider"}],"path":"/metadata/navigatorTitle","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":null,"path":"/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSCollectionLayoutSection *(^)(long, id<NSCollectionLayoutEnvironment>)","preciseIdentifier":"c:BF*$objc(cs)NSCollectionLayoutSection(#L#*Qoobjc(pl)NSCollectionLayoutEnvironment)"},{"kind":"text","text":" "},{"kind":"identifier","text":"UICollectionViewCompositionalLayoutSectionProvider"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutEnvironment/title","value":"NSCollectionLayoutEnvironment","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutEnvironment/fragments","value":[{"kind":"identifier","text":"NSCollectionLayoutEnvironment"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutEnvironment/navigatorTitle","value":[{"kind":"identifier","text":"NSCollectionLayoutEnvironment"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutSection/title","value":"NSCollectionLayoutSection","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutSection/fragments","value":[{"kind":"identifier","text":"NSCollectionLayoutSection"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSCollectionLayoutSection/navigatorTitle","value":[{"text":"NSCollectionLayoutSection","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCompositionalLayout/title","value":"UICollectionViewCompositionalLayout","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCompositionalLayout/fragments","value":[{"text":"UICollectionViewCompositionalLayout","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCompositionalLayout/navigatorTitle","value":[{"kind":"identifier","text":"UICollectionViewCompositionalLayout"}],"op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCompositionalLayoutSectionProvider/title","value":"UICollectionViewCompositionalLayoutSectionProvider"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCompositionalLayoutSectionProvider/fragments","value":[{"kind":"identifier","text":"UICollectionViewCompositionalLayoutSectionProvider"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewCompositionalLayoutSectionProvider/navigatorTitle","value":[{"text":"UICollectionViewCompositionalLayoutSectionProvider","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}