{
  "abstract": [
    {
      "text": "A content configuration for a content-unavailable view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:5UIKit33UIContentUnavailableConfigurationV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIContentUnavailableConfiguration"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIContentUnavailableConfiguration"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "UIContentUnavailableConfiguration"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIContentUnavailableConfiguration"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A content-unavailable configuration is a composable description of a view that indicates your app can’t display content. Using a content-unavailable configuration, you can obtain system default styling for a variety of different empty states. Fill the configuration with placeholder content, and then assign it to a view controller’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/contentUnavailableConfiguration-4b95e",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", or to a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following screenshot shows an example of a content-unavailable view configured by setting the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/image",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/text",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/secondaryText",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-4274239",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentConfiguration-9eib5": {
      "abstract": [
        {
          "text": "The requirements for an object that provides the configuration for a content view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIContentConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentConfiguration-9eib5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentConfiguration"
        }
      ],
      "role": "symbol",
      "title": "UIContentConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uicontentconfiguration-9eib5"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct": {
      "abstract": [
        {
          "text": "A content configuration for a content-unavailable view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIContentUnavailableConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentUnavailableConfiguration"
        }
      ],
      "role": "symbol",
      "title": "UIContentUnavailableConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/Alignment-swift.enum": {
      "abstract": [
        {
          "text": "Constants to define the alignment of views in a content-unavailable view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Alignment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/Alignment-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Alignment"
        }
      ],
      "role": "symbol",
      "title": "UIContentUnavailableConfiguration.Alignment",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-swift.struct/alignment-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/ButtonProperties-swift.struct": {
      "abstract": [
        {
          "text": "Properties to configure buttons for a content-unavailable view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ButtonProperties"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/ButtonProperties-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ButtonProperties"
        }
      ],
      "role": "symbol",
      "title": "UIContentUnavailableConfiguration.ButtonProperties",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-swift.struct/buttonproperties-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/ImageProperties-swift.struct": {
      "abstract": [
        {
          "text": "Properties to configure the image for a content-unavailable view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ImageProperties"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/ImageProperties-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ImageProperties"
        }
      ],
      "role": "symbol",
      "title": "UIContentUnavailableConfiguration.ImageProperties",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-swift.struct/imageproperties-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/TextProperties-swift.struct": {
      "abstract": [
        {
          "text": "Properties to configure text for a content-unavailable view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TextProperties"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/TextProperties-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TextProperties"
        }
      ],
      "role": "symbol",
      "title": "UIContentUnavailableConfiguration.TextProperties",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-swift.struct/textproperties-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/alignment-swift.property": {
      "abstract": [
        {
          "text": "The alignment of the image, text, and buttons.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alignment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit33UIContentUnavailableConfigurationV",
          "text": "UIContentUnavailableConfiguration"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit33UIContentUnavailableConfigurationV9AlignmentO",
          "text": "Alignment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/alignment-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "alignment",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-swift.struct/alignment-swift.property"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/attributedText": {
      "abstract": [
        {
          "text": "An attributed variant of the primary text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attributedText"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/attributedText",
      "kind": "symbol",
      "role": "symbol",
      "title": "attributedText",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-swift.struct/attributedtext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/axesPreservingSuperviewLayoutMargins": {
      "abstract": [
        {
          "text": "Configures which margins use the layout margins inherited from the superview.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "axesPreservingSuperviewLayoutMargins"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIAxis",
          "text": "UIAxis"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/axesPreservingSuperviewLayoutMargins",
      "kind": "symbol",
      "role": "symbol",
      "title": "axesPreservingSuperviewLayoutMargins",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-swift.struct/axespreservingsuperviewlayoutmargins"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/background": {
      "abstract": [
        {
          "text": "The configuration for the background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "background"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit25UIBackgroundConfigurationV",
          "text": "UIBackgroundConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/background",
      "kind": "symbol",
      "role": "symbol",
      "title": "background",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-swift.struct/background"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/button": {
      "abstract": [
        {
          "text": "The configuration for the primary button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "button"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIButton",
          "text": "UIButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So8UIButtonC5UIKitE13ConfigurationV",
          "text": "Configuration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/button",
      "kind": "symbol",
      "role": "symbol",
      "title": "button",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-swift.struct/button"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/buttonProperties-swift.property": {
      "abstract": [
        {
          "text": "Additional configuration for the primary button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "buttonProperties"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit33UIContentUnavailableConfigurationV",
          "text": "UIContentUnavailableConfiguration"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit33UIContentUnavailableConfigurationV16ButtonPropertiesV",
          "text": "ButtonProperties"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/buttonProperties-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "buttonProperties",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-swift.struct/buttonproperties-swift.property"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/buttonToSecondaryButtonPadding": {
      "abstract": [
        {
          "text": "The padding between the primary button and secondary button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "buttonToSecondaryButtonPadding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/buttonToSecondaryButtonPadding",
      "kind": "symbol",
      "role": "symbol",
      "title": "buttonToSecondaryButtonPadding",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-swift.struct/buttontosecondarybuttonpadding"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/directionalLayoutMargins": {
      "abstract": [
        {
          "text": "The margins between the content and the edges of the content view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "directionalLayoutMargins"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSDirectionalEdgeInsets",
          "text": "NSDirectionalEdgeInsets"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/directionalLayoutMargins",
      "kind": "symbol",
      "role": "symbol",
      "title": "directionalLayoutMargins",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-swift.struct/directionallayoutmargins"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/empty()": {
      "abstract": [
        {
          "text": "Creates the default configuration for unavailable content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "empty"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit33UIContentUnavailableConfigurationV",
          "text": "UIContentUnavailableConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/empty()",
      "kind": "symbol",
      "role": "symbol",
      "title": "empty()",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-swift.struct/empty()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/image": {
      "abstract": [
        {
          "text": "The image to display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "image"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/image",
      "kind": "symbol",
      "role": "symbol",
      "title": "image",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-swift.struct/image"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/imageProperties-swift.property": {
      "abstract": [
        {
          "text": "The configuration for the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageProperties"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit33UIContentUnavailableConfigurationV",
          "text": "UIContentUnavailableConfiguration"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit33UIContentUnavailableConfigurationV15ImagePropertiesV",
          "text": "ImageProperties"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/imageProperties-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "imageProperties",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-swift.struct/imageproperties-swift.property"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/imageToTextPadding": {
      "abstract": [
        {
          "text": "The padding between the image and the primary text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageToTextPadding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/imageToTextPadding",
      "kind": "symbol",
      "role": "symbol",
      "title": "imageToTextPadding",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-swift.struct/imagetotextpadding"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/loading()": {
      "abstract": [
        {
          "text": "Creates the default configuration for content that’s loading.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loading"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit33UIContentUnavailableConfigurationV",
          "text": "UIContentUnavailableConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/loading()",
      "kind": "symbol",
      "role": "symbol",
      "title": "loading()",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-swift.struct/loading()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/search()": {
      "abstract": [
        {
          "text": "Creates the default configuration for searches that return no results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "search"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit33UIContentUnavailableConfigurationV",
          "text": "UIContentUnavailableConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/search()",
      "kind": "symbol",
      "role": "symbol",
      "title": "search()",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-swift.struct/search()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/secondaryAttributedText": {
      "abstract": [
        {
          "text": "An attributed variant of the secondary text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "secondaryAttributedText"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/secondaryAttributedText",
      "kind": "symbol",
      "role": "symbol",
      "title": "secondaryAttributedText",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-swift.struct/secondaryattributedtext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/secondaryButton": {
      "abstract": [
        {
          "text": "The configuration for the secondary button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "secondaryButton"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIButton",
          "text": "UIButton"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So8UIButtonC5UIKitE13ConfigurationV",
          "text": "Configuration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/secondaryButton",
      "kind": "symbol",
      "role": "symbol",
      "title": "secondaryButton",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-swift.struct/secondarybutton"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/secondaryButtonProperties": {
      "abstract": [
        {
          "text": "Additional configuration for the secondary button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "secondaryButtonProperties"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit33UIContentUnavailableConfigurationV",
          "text": "UIContentUnavailableConfiguration"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit33UIContentUnavailableConfigurationV16ButtonPropertiesV",
          "text": "ButtonProperties"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/secondaryButtonProperties",
      "kind": "symbol",
      "role": "symbol",
      "title": "secondaryButtonProperties",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-swift.struct/secondarybuttonproperties"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/secondaryText": {
      "abstract": [
        {
          "text": "The secondary text to display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "secondaryText"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/secondaryText",
      "kind": "symbol",
      "role": "symbol",
      "title": "secondaryText",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-swift.struct/secondarytext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/secondaryTextProperties": {
      "abstract": [
        {
          "text": "Properties for configuring the secondary text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "secondaryTextProperties"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit33UIContentUnavailableConfigurationV",
          "text": "UIContentUnavailableConfiguration"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit33UIContentUnavailableConfigurationV14TextPropertiesV",
          "text": "TextProperties"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/secondaryTextProperties",
      "kind": "symbol",
      "role": "symbol",
      "title": "secondaryTextProperties",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-swift.struct/secondarytextproperties"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/text": {
      "abstract": [
        {
          "text": "The primary text to display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "text"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/text",
      "kind": "symbol",
      "role": "symbol",
      "title": "text",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-swift.struct/text"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/textProperties-swift.property": {
      "abstract": [
        {
          "text": "Properties for configuring the primary text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textProperties"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit33UIContentUnavailableConfigurationV",
          "text": "UIContentUnavailableConfiguration"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit33UIContentUnavailableConfigurationV14TextPropertiesV",
          "text": "TextProperties"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/textProperties-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "textProperties",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-swift.struct/textproperties-swift.property"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/textToButtonPadding": {
      "abstract": [
        {
          "text": "The padding between the text and buttons.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textToButtonPadding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/textToButtonPadding",
      "kind": "symbol",
      "role": "symbol",
      "title": "textToButtonPadding",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-swift.struct/texttobuttonpadding"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/textToSecondaryTextPadding": {
      "abstract": [
        {
          "text": "The padding between the primary and secondary text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textToSecondaryTextPadding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/textToSecondaryTextPadding",
      "kind": "symbol",
      "role": "symbol",
      "title": "textToSecondaryTextPadding",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-swift.struct/texttosecondarytextpadding"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfigurationState-swift.struct": {
      "abstract": [
        {
          "text": "A structure that encapsulates state for a content-unavailable view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIContentUnavailableConfigurationState"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfigurationState-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentUnavailableConfigurationState"
        }
      ],
      "role": "symbol",
      "title": "UIContentUnavailableConfigurationState",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfigurationstate-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableView": {
      "abstract": [
        {
          "text": "A view that indicates there’s no content to display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIContentUnavailableView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentUnavailableView"
        }
      ],
      "role": "symbol",
      "title": "UIContentUnavailableView",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/contentUnavailableConfiguration-4b95e": {
      "abstract": [
        {
          "text": "The current content-unavailable configuration of the view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentUnavailableConfiguration"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit22UIContentConfigurationP",
          "text": "UIContentConfiguration"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/contentUnavailableConfiguration-4b95e",
      "kind": "symbol",
      "role": "symbol",
      "title": "contentUnavailableConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/contentunavailableconfiguration-4b95e"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s17CustomReflectableP": {
      "abstract": [
        {
          "text": "A type that explicitly supplies its own mirror.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomReflectable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s17CustomReflectableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomReflectable",
      "type": "topic",
      "url": "/documentation/Swift/CustomReflectable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    },
    "media-4274239": {
      "alt": "A screenshot of a content-unavailable view indicating that a user has no files in the iCloud Drive Downloads folder.",
      "identifier": "media-4274239",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/7c656513bf8e80dc345aa2d89f317248/media-4274239@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/a288bb691822db7face6d5cca4d9e0d1/media-4274239~dark@2x.png"
        }
      ]
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s17CustomReflectableP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.apple.uikit/documentation/UIKit/UIContentConfiguration-9eib5"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Unavailable-content-configurations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfigurationState-swift.struct"
      ],
      "title": "Unavailable content configurations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/ButtonProperties-swift.struct",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/ImageProperties-swift.struct",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/TextProperties-swift.struct"
      ],
      "title": "Structures"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/alignment-swift.property",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/attributedText",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/axesPreservingSuperviewLayoutMargins",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/background",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/button",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/buttonProperties-swift.property",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/buttonToSecondaryButtonPadding",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/directionalLayoutMargins",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/image",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/imageProperties-swift.property",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/imageToTextPadding",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/secondaryAttributedText",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/secondaryButton",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/secondaryButtonProperties",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/secondaryText",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/secondaryTextProperties",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/text",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/textProperties-swift.property",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/textToButtonPadding",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/textToSecondaryTextPadding"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Type-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/empty()",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/loading()",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/search()"
      ],
      "title": "Type Methods"
    },
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct/Alignment-swift.enum"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentUnavailableView/title",
          "value": "UIContentUnavailableView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentUnavailableView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentUnavailableView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentUnavailableView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentUnavailableView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uicontentunavailableconfiguration-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
