{
  "abstract": [
    {
      "text": "The interface for handling drops in a collection view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UICollectionViewDropDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UICollectionViewDropDelegate"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UICollectionViewDropDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "UICollectionViewDropDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UICollectionViewDropDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.uikit/documentation/UIKit/supporting-drag-and-drop-in-collection-views"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Implement this protocol in the object that you use to incorporate dropped data into your collection view. The only required method of this protocol is the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:performDropWith:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method, but you can implement other methods as needed to customize the drop behavior of your collection view.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Assign your custom delegate object to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionView/dropDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of your collection view.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionView/dropDelegate": {
      "abstract": [
        {
          "text": "The delegate object that manages the dropping of items into the collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dropDelegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UICollectionViewDropDelegate",
          "text": "UICollectionViewDropDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionView/dropDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dropDelegate"
        }
      ],
      "role": "symbol",
      "title": "dropDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionview/dropdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDragDelegate": {
      "abstract": [
        {
          "text": "The interface for initiating drags from a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewDragDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDragDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewDragDelegate"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewDragDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdragdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator": {
      "abstract": [
        {
          "text": "An interface for coordinating your custom drop-related actions with the collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewDropCoordinator"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewDropCoordinator"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewDropCoordinator",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdropcoordinator"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate": {
      "abstract": [
        {
          "text": "The interface for handling drops in a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewDropDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewDropDelegate"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewDropDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdropdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:canHandle:)": {
      "abstract": [
        {
          "text": "Asks your delegate whether the collection view can accept a drop with the specified type of data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "collectionView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICollectionView",
          "text": "UICollectionView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "canHandle"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDropSession",
          "text": "UIDropSession"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:canHandle:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "collectionView:canHandleDropSession:"
        }
      ],
      "role": "symbol",
      "title": "collectionView(_:canHandle:)",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdropdelegate/collectionview(_:canhandle:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropPreviewParametersForItemAt:)": {
      "abstract": [
        {
          "text": "Returns custom information about how to display the item at the specified location during the drop.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "collectionView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICollectionView",
          "text": "UICollectionView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dropPreviewParametersForItemAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation9IndexPathV",
          "text": "IndexPath"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDragPreviewParameters",
          "text": "UIDragPreviewParameters"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropPreviewParametersForItemAt:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "collectionView:dropPreviewParametersForItemAtIndexPath:"
        }
      ],
      "role": "symbol",
      "title": "collectionView(_:dropPreviewParametersForItemAt:)",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdropdelegate/collectionview(_:droppreviewparametersforitemat:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidEnd:)": {
      "abstract": [
        {
          "text": "Notifies you when the drag operation ends.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "collectionView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICollectionView",
          "text": "UICollectionView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dropSessionDidEnd"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDropSession",
          "text": "UIDropSession"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidEnd:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "collectionView:dropSessionDidEnd:"
        }
      ],
      "role": "symbol",
      "title": "collectionView(_:dropSessionDidEnd:)",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdropdelegate/collectionview(_:dropsessiondidend:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidEnter:)": {
      "abstract": [
        {
          "text": "Notifies you when dragged content enters the collection view’s bounds rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "collectionView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICollectionView",
          "text": "UICollectionView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dropSessionDidEnter"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDropSession",
          "text": "UIDropSession"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidEnter:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "collectionView:dropSessionDidEnter:"
        }
      ],
      "role": "symbol",
      "title": "collectionView(_:dropSessionDidEnter:)",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdropdelegate/collectionview(_:dropsessiondidenter:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidExit:)": {
      "abstract": [
        {
          "text": "Notifies you when dragged content exits the collection view’s bounds rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "collectionView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICollectionView",
          "text": "UICollectionView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dropSessionDidExit"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDropSession",
          "text": "UIDropSession"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidExit:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "collectionView:dropSessionDidExit:"
        }
      ],
      "role": "symbol",
      "title": "collectionView(_:dropSessionDidExit:)",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdropdelegate/collectionview(_:dropsessiondidexit:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidUpdate:withDestinationIndexPath:)": {
      "abstract": [
        {
          "text": "Tells your delegate that the position of the dragged data over the collection view changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "collectionView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICollectionView",
          "text": "UICollectionView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dropSessionDidUpdate"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDropSession",
          "text": "UIDropSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withDestinationIndexPath"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation9IndexPathV",
          "text": "IndexPath"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICollectionViewDropProposal",
          "text": "UICollectionViewDropProposal"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidUpdate:withDestinationIndexPath:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "collectionView:dropSessionDidUpdate:withDestinationIndexPath:"
        }
      ],
      "role": "symbol",
      "title": "collectionView(_:dropSessionDidUpdate:withDestinationIndexPath:)",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdropdelegate/collectionview(_:dropsessiondidupdate:withdestinationindexpath:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:performDropWith:)": {
      "abstract": [
        {
          "text": "Tells your delegate to incorporate the drop data into the collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "collectionView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICollectionView",
          "text": "UICollectionView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "performDropWith"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UICollectionViewDropCoordinator",
          "text": "UICollectionViewDropCoordinator"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:performDropWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "collectionView:performDropWithCoordinator:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "collectionView(_:performDropWith:)",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdropdelegate/collectionview(_:performdropwith:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropItem": {
      "abstract": [
        {
          "text": "The data associated with an item being dropped into the collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewDropItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewDropItem"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewDropItem",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdropitem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropPlaceholder": {
      "abstract": [
        {
          "text": "A placeholder for an item dropped on a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewDropPlaceholder"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropPlaceholder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewDropPlaceholder"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewDropPlaceholder",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdropplaceholder"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropPlaceholderContext": {
      "abstract": [
        {
          "text": "An object that contains information about a placeholder in the collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewDropPlaceholderContext"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropPlaceholderContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewDropPlaceholderContext"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewDropPlaceholderContext",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdropplaceholdercontext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropProposal": {
      "abstract": [
        {
          "text": "Your proposed solution for handling a drop in a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewDropProposal"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropProposal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewDropProposal"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewDropProposal",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdropproposal"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewPlaceholder": {
      "abstract": [
        {
          "text": "A placeholder for an item dragged or dropped on a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewPlaceholder"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewPlaceholder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewPlaceholder"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewPlaceholder",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewplaceholder"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDataSourceTranslating": {
      "abstract": [
        {
          "text": "An advanced interface for managing a data source object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDataSourceTranslating"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDataSourceTranslating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDataSourceTranslating"
        }
      ],
      "role": "symbol",
      "title": "UIDataSourceTranslating",
      "type": "topic",
      "url": "/documentation/uikit/uidatasourcetranslating"
    },
    "doc://com.apple.uikit/documentation/UIKit/supporting-drag-and-drop-in-collection-views": {
      "abstract": [
        {
          "text": "Initiate drags and handle drops from a collection view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/supporting-drag-and-drop-in-collection-views",
      "kind": "article",
      "role": "article",
      "title": "Supporting Drag and Drop in Collection Views",
      "type": "topic",
      "url": "/documentation/uikit/supporting-drag-and-drop-in-collection-views"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Drag-and-drop",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/supporting-drag-and-drop-in-collection-views",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDragDelegate",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropPlaceholder",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropProposal",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropItem",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropPlaceholderContext",
        "doc://com.apple.uikit/documentation/UIKit/UIDataSourceTranslating",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewPlaceholder"
      ],
      "title": "Drag and drop"
    }
  ],
  "topicSections": [
    {
      "anchor": "Declaring-support-for-handling-drops",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:canHandle:)"
      ],
      "title": "Declaring support for handling drops"
    },
    {
      "anchor": "Incorporating-the-dropped-data",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:performDropWith:)"
      ],
      "title": "Incorporating the dropped data"
    },
    {
      "anchor": "Tracking-the-drag-movements",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidUpdate:withDestinationIndexPath:)",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidEnter:)",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidExit:)",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidEnd:)"
      ],
      "title": "Tracking the drag movements"
    },
    {
      "anchor": "Providing-a-custom-preview",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropPreviewParametersForItemAt:)"
      ],
      "title": "Providing a custom preview"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UICollectionViewDropDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Declaring-support-for-handling-drops",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:canHandle:)"
              ],
              "title": "Declaring support for handling drops"
            },
            {
              "anchor": "Incorporating-the-dropped-data",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:performDropWith:)"
              ],
              "title": "Incorporating the dropped data"
            },
            {
              "anchor": "Tracking-the-drag-movements",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidUpdate:withDestinationIndexPath:)",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidEnter:)",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidExit:)",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropSessionDidEnd:)"
              ],
              "title": "Tracking the drag movements"
            },
            {
              "anchor": "Providing-a-custom-preview",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropDelegate/collectionView(_:dropPreviewParametersForItemAt:)"
              ],
              "title": "Providing a custom preview"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Drag-and-drop",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/supporting-drag-and-drop-in-collection-views",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDragDelegate",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropCoordinator",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropPlaceholder",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropProposal",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropItem",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDropPlaceholderContext",
                "doc://com.apple.uikit/documentation/UIKit/UIDataSourceTranslating",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewPlaceholder"
              ],
              "title": "Drag and drop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UICollectionViewDropDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropCoordinator/title",
          "value": "UICollectionViewDropCoordinator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropCoordinator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropCoordinator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1dropDelegate/title",
          "value": "dropDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView~1dropDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dropDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropItem/title",
          "value": "UICollectionViewDropItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate~1collectionView(_:dropSessionDidUpdate:withDestinationIndexPath:)/title",
          "value": "collectionView:dropSessionDidUpdate:withDestinationIndexPath:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate~1collectionView(_:dropSessionDidUpdate:withDestinationIndexPath:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "collectionView:dropSessionDidUpdate:withDestinationIndexPath:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate~1collectionView(_:performDropWith:)/title",
          "value": "collectionView:performDropWithCoordinator:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate~1collectionView(_:performDropWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "collectionView:performDropWithCoordinator:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate/title",
          "value": "UICollectionViewDropDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropPlaceholder/title",
          "value": "UICollectionViewDropPlaceholder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropPlaceholder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropPlaceholder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropPlaceholder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropPlaceholder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewPlaceholder/title",
          "value": "UICollectionViewPlaceholder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewPlaceholder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewPlaceholder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewPlaceholder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewPlaceholder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDragDelegate/title",
          "value": "UICollectionViewDragDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDragDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDragDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDragDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDragDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropPlaceholderContext/title",
          "value": "UICollectionViewDropPlaceholderContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropPlaceholderContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropPlaceholderContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropPlaceholderContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropPlaceholderContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate~1collectionView(_:dropSessionDidEnd:)/title",
          "value": "collectionView:dropSessionDidEnd:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate~1collectionView(_:dropSessionDidEnd:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "collectionView:dropSessionDidEnd:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDataSourceTranslating/title",
          "value": "UIDataSourceTranslating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDataSourceTranslating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDataSourceTranslating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDataSourceTranslating/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDataSourceTranslating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate~1collectionView(_:dropPreviewParametersForItemAt:)/title",
          "value": "collectionView:dropPreviewParametersForItemAtIndexPath:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate~1collectionView(_:dropPreviewParametersForItemAt:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "collectionView:dropPreviewParametersForItemAtIndexPath:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate~1collectionView(_:dropSessionDidExit:)/title",
          "value": "collectionView:dropSessionDidExit:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate~1collectionView(_:dropSessionDidExit:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "collectionView:dropSessionDidExit:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate~1collectionView(_:dropSessionDidEnter:)/title",
          "value": "collectionView:dropSessionDidEnter:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate~1collectionView(_:dropSessionDidEnter:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "collectionView:dropSessionDidEnter:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate~1collectionView(_:canHandle:)/title",
          "value": "collectionView:canHandleDropSession:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropDelegate~1collectionView(_:canHandle:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "collectionView:canHandleDropSession:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropProposal/title",
          "value": "UICollectionViewDropProposal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropProposal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropProposal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDropProposal/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDropProposal"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uicollectionviewdropdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uicollectionviewdropdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
