{
  "abstract": [
    {
      "text": "Constants that indicate the preferred size of your content.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@UIContentSizeCategory",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIContentSizeCategory"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIContentSizeCategory"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "UIContentSizeCategory"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIContentSizeCategory"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/preferredContentSizeCategory": {
      "abstract": [
        {
          "text": "The font sizing option preferred by the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredContentSizeCategory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIContentSizeCategory",
          "text": "UIContentSizeCategory"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/preferredContentSizeCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredContentSizeCategory"
        }
      ],
      "role": "symbol",
      "title": "preferredContentSizeCategory",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/preferredcontentsizecategory"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory": {
      "abstract": [
        {
          "text": "Constants that indicate the preferred size of your content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIContentSizeCategory"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentSizeCategory"
        }
      ],
      "role": "symbol",
      "title": "UIContentSizeCategory",
      "type": "topic",
      "url": "/documentation/uikit/uicontentsizecategory"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/accessibilityExtraExtraExtraLarge": {
      "abstract": [
        {
          "text": "The largest font size that reflects the current accessibility settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityExtraExtraExtraLarge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIContentSizeCategory",
          "text": "UIContentSizeCategory"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/accessibilityExtraExtraExtraLarge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentSizeCategoryAccessibilityExtraExtraExtraLarge"
        }
      ],
      "role": "symbol",
      "title": "accessibilityExtraExtraExtraLarge",
      "type": "topic",
      "url": "/documentation/uikit/uicontentsizecategory/accessibilityextraextraextralarge"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/accessibilityExtraExtraLarge": {
      "abstract": [
        {
          "text": "A font that is larger than the extra-large font but not the largest available, reflecting the current accessibility settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityExtraExtraLarge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIContentSizeCategory",
          "text": "UIContentSizeCategory"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/accessibilityExtraExtraLarge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentSizeCategoryAccessibilityExtraExtraLarge"
        }
      ],
      "role": "symbol",
      "title": "accessibilityExtraExtraLarge",
      "type": "topic",
      "url": "/documentation/uikit/uicontentsizecategory/accessibilityextraextralarge"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/accessibilityExtraLarge": {
      "abstract": [
        {
          "text": "An extra-large font size that reflects the current accessibility settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityExtraLarge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIContentSizeCategory",
          "text": "UIContentSizeCategory"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/accessibilityExtraLarge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentSizeCategoryAccessibilityExtraLarge"
        }
      ],
      "role": "symbol",
      "title": "accessibilityExtraLarge",
      "type": "topic",
      "url": "/documentation/uikit/uicontentsizecategory/accessibilityextralarge"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/accessibilityLarge": {
      "abstract": [
        {
          "text": "A large font size that reflects the current accessibility settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityLarge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIContentSizeCategory",
          "text": "UIContentSizeCategory"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/accessibilityLarge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentSizeCategoryAccessibilityLarge"
        }
      ],
      "role": "symbol",
      "title": "accessibilityLarge",
      "type": "topic",
      "url": "/documentation/uikit/uicontentsizecategory/accessibilitylarge"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/accessibilityMedium": {
      "abstract": [
        {
          "text": "A medium font size that reflects the current accessibility settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityMedium"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIContentSizeCategory",
          "text": "UIContentSizeCategory"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/accessibilityMedium",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentSizeCategoryAccessibilityMedium"
        }
      ],
      "role": "symbol",
      "title": "accessibilityMedium",
      "type": "topic",
      "url": "/documentation/uikit/uicontentsizecategory/accessibilitymedium"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/didChangeNotification": {
      "abstract": [
        {
          "text": "A notification that posts when the user changes the preferred content size setting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/didChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentSizeCategoryDidChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "didChangeNotification",
      "type": "topic",
      "url": "/documentation/uikit/uicontentsizecategory/didchangenotification"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/extraExtraExtraLarge": {
      "abstract": [
        {
          "text": "The largest font size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extraExtraExtraLarge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIContentSizeCategory",
          "text": "UIContentSizeCategory"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/extraExtraExtraLarge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentSizeCategoryExtraExtraExtraLarge"
        }
      ],
      "role": "symbol",
      "title": "extraExtraExtraLarge",
      "type": "topic",
      "url": "/documentation/uikit/uicontentsizecategory/extraextraextralarge"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/extraExtraLarge": {
      "abstract": [
        {
          "text": "A font that is larger than the extra-large font but smaller than the largest font size available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extraExtraLarge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIContentSizeCategory",
          "text": "UIContentSizeCategory"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/extraExtraLarge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentSizeCategoryExtraExtraLarge"
        }
      ],
      "role": "symbol",
      "title": "extraExtraLarge",
      "type": "topic",
      "url": "/documentation/uikit/uicontentsizecategory/extraextralarge"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/extraLarge": {
      "abstract": [
        {
          "text": "An extra-large font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extraLarge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIContentSizeCategory",
          "text": "UIContentSizeCategory"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/extraLarge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentSizeCategoryExtraLarge"
        }
      ],
      "role": "symbol",
      "title": "extraLarge",
      "type": "topic",
      "url": "/documentation/uikit/uicontentsizecategory/extralarge"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/extraSmall": {
      "abstract": [
        {
          "text": "An extra-small font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extraSmall"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIContentSizeCategory",
          "text": "UIContentSizeCategory"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/extraSmall",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentSizeCategoryExtraSmall"
        }
      ],
      "role": "symbol",
      "title": "extraSmall",
      "type": "topic",
      "url": "/documentation/uikit/uicontentsizecategory/extrasmall"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/init(_:)-9l1kn": {
      "abstract": [
        {
          "text": "Creates a content size category from the specified SwiftUI content size category.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI19ContentSizeCategoryO",
          "text": "ContentSizeCategory"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/init(_:)-9l1kn",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uicontentsizecategory/init(_:)-9l1kn"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/init(_:)-abz4": {
      "abstract": [
        {
          "text": "Creates a content size category from the specified SwiftUI Dynamic Type size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI15DynamicTypeSizeO",
          "text": "DynamicTypeSize"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/init(_:)-abz4",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uicontentsizecategory/init(_:)-abz4"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a new instance with the specified raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/uicontentsizecategory/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/isAccessibilityCategory": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the content size category is associated with accessibility.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAccessibilityCategory"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/isAccessibilityCategory",
      "kind": "symbol",
      "role": "symbol",
      "title": "isAccessibilityCategory",
      "type": "topic",
      "url": "/documentation/uikit/uicontentsizecategory/isaccessibilitycategory"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/large": {
      "abstract": [
        {
          "text": "A large font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "large"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIContentSizeCategory",
          "text": "UIContentSizeCategory"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/large",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentSizeCategoryLarge"
        }
      ],
      "role": "symbol",
      "title": "large",
      "type": "topic",
      "url": "/documentation/uikit/uicontentsizecategory/large"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/medium": {
      "abstract": [
        {
          "text": "A medium-sized font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "medium"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIContentSizeCategory",
          "text": "UIContentSizeCategory"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/medium",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentSizeCategoryMedium"
        }
      ],
      "role": "symbol",
      "title": "medium",
      "type": "topic",
      "url": "/documentation/uikit/uicontentsizecategory/medium"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/newValueUserInfoKey": {
      "abstract": [
        {
          "text": "A key that reflects the new preferred content size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "newValueUserInfoKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/newValueUserInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentSizeCategoryNewValueKey"
        }
      ],
      "role": "symbol",
      "title": "newValueUserInfoKey",
      "type": "topic",
      "url": "/documentation/uikit/uicontentsizecategory/newvalueuserinfokey"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/small": {
      "abstract": [
        {
          "text": "A small font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "small"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIContentSizeCategory",
          "text": "UIContentSizeCategory"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/small",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentSizeCategorySmall"
        }
      ],
      "role": "symbol",
      "title": "small",
      "type": "topic",
      "url": "/documentation/uikit/uicontentsizecategory/small"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/unspecified": {
      "abstract": [
        {
          "text": "An unspecified font size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIContentSizeCategory",
          "text": "UIContentSizeCategory"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentSizeCategoryUnspecified"
        }
      ],
      "role": "symbol",
      "title": "unspecified",
      "type": "topic",
      "url": "/documentation/uikit/uicontentsizecategory/unspecified"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategoryAdjusting": {
      "abstract": [
        {
          "text": "A collection of methods that give controls an easy way to adopt automatic adjustment to content category changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIContentSizeCategoryAdjusting"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategoryAdjusting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentSizeCategoryAdjusting"
        }
      ],
      "role": "symbol",
      "title": "UIContentSizeCategoryAdjusting",
      "type": "topic",
      "url": "/documentation/uikit/uicontentsizecategoryadjusting"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SL": {
      "abstract": [
        {
          "text": "A type that can be compared using the relational operators `<`, `<=`, `>=`, and `>`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Comparable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SL",
      "kind": "symbol",
      "role": "symbol",
      "title": "Comparable",
      "type": "topic",
      "url": "/documentation/Swift/Comparable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SL",
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-the-preferred-content-size",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/preferredContentSizeCategory",
        "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategoryAdjusting",
        "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/didChangeNotification",
        "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/newValueUserInfoKey"
      ],
      "title": "Managing the preferred content size"
    }
  ],
  "topicSections": [
    {
      "anchor": "Font-sizes",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/unspecified",
        "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/extraSmall",
        "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/small",
        "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/medium",
        "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/large",
        "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/extraLarge",
        "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/extraExtraLarge",
        "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/extraExtraExtraLarge"
      ],
      "title": "Font sizes"
    },
    {
      "anchor": "Accessibility-sizes",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/accessibilityMedium",
        "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/accessibilityLarge",
        "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/accessibilityExtraLarge",
        "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/accessibilityExtraExtraLarge",
        "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/accessibilityExtraExtraExtraLarge",
        "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/isAccessibilityCategory"
      ],
      "title": "Accessibility sizes"
    },
    {
      "anchor": "Font-size-change-notifications",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/didChangeNotification",
        "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/newValueUserInfoKey"
      ],
      "title": "Font size change notifications"
    },
    {
      "anchor": "Font-size-category-creation",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/init(rawValue:)",
        "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/init(_:)-9l1kn",
        "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/init(_:)-abz4"
      ],
      "title": "Font size category creation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIContentSizeCategory"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentSizeCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentSizeCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Font-sizes",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/unspecified",
                "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/extraSmall",
                "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/small",
                "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/medium",
                "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/large",
                "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/extraLarge",
                "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/extraExtraLarge",
                "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/extraExtraExtraLarge"
              ],
              "title": "Font sizes"
            },
            {
              "anchor": "Accessibility-sizes",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/accessibilityMedium",
                "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/accessibilityLarge",
                "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/accessibilityExtraLarge",
                "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/accessibilityExtraExtraLarge",
                "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/accessibilityExtraExtraExtraLarge"
              ],
              "title": "Accessibility sizes"
            },
            {
              "anchor": "Font-size-change-notifications",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/didChangeNotification",
                "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/newValueUserInfoKey"
              ],
              "title": "Font size change notifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-the-preferred-content-size",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/preferredContentSizeCategory",
                "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategoryAdjusting",
                "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/didChangeNotification",
                "doc://com.apple.uikit/documentation/UIKit/UIContentSizeCategory/newValueUserInfoKey"
              ],
              "title": "Managing the preferred content size"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIContentSizeCategory"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentSizeCategory~1accessibilityExtraLarge/title",
          "value": "UIContentSizeCategoryAccessibilityExtraLarge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentSizeCategory~1accessibilityExtraLarge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentSizeCategoryAccessibilityExtraLarge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentSizeCategory~1extraExtraLarge/title",
          "value": "UIContentSizeCategoryExtraExtraLarge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentSizeCategory~1extraExtraLarge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentSizeCategoryExtraExtraLarge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentSizeCategory~1accessibilityLarge/title",
          "value": "UIContentSizeCategoryAccessibilityLarge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentSizeCategory~1accessibilityLarge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentSizeCategoryAccessibilityLarge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentSizeCategory~1extraSmall/title",
          "value": "UIContentSizeCategoryExtraSmall"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentSizeCategory~1extraSmall/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentSizeCategoryExtraSmall"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1preferredContentSizeCategory/title",
          "value": "preferredContentSizeCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1preferredContentSizeCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preferredContentSizeCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentSizeCategory~1newValueUserInfoKey/title",
          "value": "UIContentSizeCategoryNewValueKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentSizeCategory~1newValueUserInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentSizeCategoryNewValueKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentSizeCategory~1extraLarge/title",
          "value": "UIContentSizeCategoryExtraLarge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentSizeCategory~1extraLarge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentSizeCategoryExtraLarge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentSizeCategory~1medium/title",
          "value": "UIContentSizeCategoryMedium"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentSizeCategory~1medium/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentSizeCategoryMedium"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentSizeCategory~1small/title",
          "value": "UIContentSizeCategorySmall"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentSizeCategory~1small/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentSizeCategorySmall"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentSizeCategory~1unspecified/title",
          "value": "UIContentSizeCategoryUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentSizeCategory~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentSizeCategoryUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentSizeCategory~1large/title",
          "value": "UIContentSizeCategoryLarge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentSizeCategory~1large/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentSizeCategoryLarge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentSizeCategory~1didChangeNotification/title",
          "value": "UIContentSizeCategoryDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentSizeCategory~1didChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentSizeCategoryDidChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentSizeCategoryAdjusting/title",
          "value": "UIContentSizeCategoryAdjusting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentSizeCategoryAdjusting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentSizeCategoryAdjusting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentSizeCategoryAdjusting/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentSizeCategoryAdjusting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentSizeCategory/title",
          "value": "UIContentSizeCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentSizeCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentSizeCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentSizeCategory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentSizeCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentSizeCategory~1accessibilityExtraExtraExtraLarge/title",
          "value": "UIContentSizeCategoryAccessibilityExtraExtraExtraLarge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentSizeCategory~1accessibilityExtraExtraExtraLarge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentSizeCategoryAccessibilityExtraExtraExtraLarge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentSizeCategory~1accessibilityExtraExtraLarge/title",
          "value": "UIContentSizeCategoryAccessibilityExtraExtraLarge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentSizeCategory~1accessibilityExtraExtraLarge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentSizeCategoryAccessibilityExtraExtraLarge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentSizeCategory~1extraExtraExtraLarge/title",
          "value": "UIContentSizeCategoryExtraExtraExtraLarge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentSizeCategory~1extraExtraExtraLarge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentSizeCategoryExtraExtraExtraLarge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentSizeCategory~1accessibilityMedium/title",
          "value": "UIContentSizeCategoryAccessibilityMedium"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentSizeCategory~1accessibilityMedium/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentSizeCategoryAccessibilityMedium"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uicontentsizecategory"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uicontentsizecategory"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
