{
  "abstract": [
    {
      "text": "A view that indicates there’s no content to display.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableView"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIContentUnavailableView",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIContentUnavailableView"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIContentUnavailableView"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "UIContentUnavailableView"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIContentUnavailableView"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use a content-unavailable view to indicate that your app can’t display content. For example, content may not be available if a search returns no results or your app is loading data over the network.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In many cases, you won’t need to create a view of this type directly. Set a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " as the view controller’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/contentUnavailableConfiguration-4b95e",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and the view controller manages the layout of the content-unavailable view.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityIdentification": {
      "abstract": [
        {
          "text": "Methods that associate a unique identifier with elements in your user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAccessibilityIdentification"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityIdentification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityIdentification"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityIdentification",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityidentification"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivityIndicatorView": {
      "abstract": [
        {
          "text": "A view that shows that a task is in progress.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIActivityIndicatorView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivityIndicatorView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIActivityIndicatorView"
        }
      ],
      "role": "symbol",
      "title": "UIActivityIndicatorView",
      "type": "topic",
      "url": "/documentation/uikit/uiactivityindicatorview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationProviding": {
      "abstract": [
        {
          "text": "An interface that provides a source for shareable content to fulfill user requests to share current content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIActivityItemsConfigurationProviding"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationProviding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIActivityItemsConfigurationProviding"
        }
      ],
      "role": "symbol",
      "title": "UIActivityItemsConfigurationProviding",
      "type": "topic",
      "url": "/documentation/uikit/uiactivityitemsconfigurationproviding"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAppearance": {
      "abstract": [
        {
          "text": "A collection of methods that gives you access to the appearance proxy for a class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAppearance"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAppearance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAppearance"
        }
      ],
      "role": "symbol",
      "title": "UIAppearance",
      "type": "topic",
      "url": "/documentation/uikit/uiappearance"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAppearanceContainer": {
      "abstract": [
        {
          "text": "A protocol that a class must adopt to allow appearance customization using the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAppearance",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " API.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAppearanceContainer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAppearanceContainer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAppearanceContainer"
        }
      ],
      "role": "symbol",
      "title": "UIAppearanceContainer",
      "type": "topic",
      "url": "/documentation/uikit/uiappearancecontainer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICalendarView": {
      "abstract": [
        {
          "text": "A view that displays a calendar with date-specific decorations, and provides for user selection of a single date or multiple dates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICalendarView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICalendarView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICalendarView"
        }
      ],
      "role": "symbol",
      "title": "UICalendarView",
      "type": "topic",
      "url": "/documentation/uikit/uicalendarview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct": {
      "abstract": [
        {
          "text": "A content configuration for a content-unavailable view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIContentUnavailableConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableConfiguration-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentUnavailableConfiguration"
        }
      ],
      "role": "symbol",
      "title": "UIContentUnavailableConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableconfiguration-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableView": {
      "abstract": [
        {
          "text": "A view that indicates there’s no content to display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIContentUnavailableView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentUnavailableView"
        }
      ],
      "role": "symbol",
      "title": "UIContentUnavailableView",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableView/configuration": {
      "abstract": [
        {
          "text": "The content-unavailable configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "configuration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableView/configuration",
      "kind": "symbol",
      "role": "symbol",
      "title": "configuration",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableview/configuration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableView/init(coder:)": {
      "abstract": [
        {
          "text": "Creates a view from data in an unarchiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "coder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCoder",
          "text": "NSCoder"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableView/init(coder:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCoder:"
        }
      ],
      "role": "symbol",
      "title": "init(coder:)",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableview/init(coder:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableView/init(configuration:)": {
      "abstract": [
        {
          "text": "Creates a new content-unavailable view with the specified configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "configuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit33UIContentUnavailableConfigurationV",
          "text": "UIContentUnavailableConfiguration"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableView/init(configuration:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(configuration:)",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableview/init(configuration:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableView/initWithConfiguration:": {
      "abstract": [
        {
          "text": "Creates a new content-unavailable view with the specified configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithConfiguration:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableView/initWithConfiguration:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithConfiguration:"
        }
      ],
      "role": "symbol",
      "title": "initWithConfiguration:",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableview/initwithconfiguration:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableView/isScrollEnabled": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the view content can scroll.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isScrollEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableView/isScrollEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scrollEnabled"
        }
      ],
      "role": "symbol",
      "title": "isScrollEnabled",
      "type": "topic",
      "url": "/documentation/uikit/uicontentunavailableview/isscrollenabled"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentView-3zu2k": {
      "abstract": [
        {
          "text": "The requirements for a content view that you create using a configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIContentView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentView-3zu2k",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIContentView",
      "type": "topic",
      "url": "/documentation/uikit/uicontentview-3zu2k"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentView-5fh3z": {
      "abstract": [
        {
          "text": "The requirements for a content view that you create using a configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIContentView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentView-5fh3z",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentView"
        }
      ],
      "role": "symbol",
      "title": "UIContentView",
      "type": "topic",
      "url": "/documentation/uikit/uicontentview-5fh3z"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICoordinateSpace": {
      "abstract": [
        {
          "text": "A set of methods for converting between different frames of reference on a screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICoordinateSpace"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICoordinateSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICoordinateSpace"
        }
      ],
      "role": "symbol",
      "title": "UICoordinateSpace",
      "type": "topic",
      "url": "/documentation/uikit/uicoordinatespace"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDynamicItem": {
      "abstract": [
        {
          "text": "A set of methods that can make a custom object eligible to participate in UIKit Dynamics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDynamicItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDynamicItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDynamicItem"
        }
      ],
      "role": "symbol",
      "title": "UIDynamicItem",
      "type": "topic",
      "url": "/documentation/uikit/uidynamicitem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment": {
      "abstract": [
        {
          "text": "A set of methods that define the focus behavior for a branch of the view hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFocusEnvironment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFocusEnvironment"
        }
      ],
      "role": "symbol",
      "title": "UIFocusEnvironment",
      "type": "topic",
      "url": "/documentation/uikit/uifocusenvironment"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFocusItem": {
      "abstract": [
        {
          "text": "An object that can become focused.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFocusItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFocusItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFocusItem"
        }
      ],
      "role": "symbol",
      "title": "UIFocusItem",
      "type": "topic",
      "url": "/documentation/uikit/uifocusitem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFocusItemContainer": {
      "abstract": [
        {
          "text": "The container responsible for providing geometric context to focus items within a given focus environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFocusItemContainer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFocusItemContainer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFocusItemContainer"
        }
      ],
      "role": "symbol",
      "title": "UIFocusItemContainer",
      "type": "topic",
      "url": "/documentation/uikit/uifocusitemcontainer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImageView": {
      "abstract": [
        {
          "text": "A view that displays a single image or a sequence of animated images in your interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIImageView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImageView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImageView"
        }
      ],
      "role": "symbol",
      "title": "UIImageView",
      "type": "topic",
      "url": "/documentation/uikit/uiimageview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UILargeContentViewerItem": {
      "abstract": [
        {
          "text": "Methods that provide details about how to display your custom content in the large content viewer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UILargeContentViewerItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UILargeContentViewerItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILargeContentViewerItem"
        }
      ],
      "role": "symbol",
      "title": "UILargeContentViewerItem",
      "type": "topic",
      "url": "/documentation/uikit/uilargecontentvieweritem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteConfigurationSupporting": {
      "abstract": [
        {
          "text": "The interface that determines whether a responder object supports paste configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPasteConfigurationSupporting"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteConfigurationSupporting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPasteConfigurationSupporting"
        }
      ],
      "role": "symbol",
      "title": "UIPasteConfigurationSupporting",
      "type": "topic",
      "url": "/documentation/uikit/uipasteconfigurationsupporting"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPickerView": {
      "abstract": [
        {
          "text": "A view that uses a spinning-wheel or slot-machine metaphor to show one or more sets of values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPickerView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPickerView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPickerView"
        }
      ],
      "role": "symbol",
      "title": "UIPickerView",
      "type": "topic",
      "url": "/documentation/uikit/uipickerview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationControllerSourceItem": {
      "abstract": [
        {
          "text": "A type that can be an anchor for a popover presentation controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPopoverPresentationControllerSourceItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationControllerSourceItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPopoverPresentationControllerSourceItem"
        }
      ],
      "role": "symbol",
      "title": "UIPopoverPresentationControllerSourceItem",
      "type": "topic",
      "url": "/documentation/uikit/uipopoverpresentationcontrollersourceitem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIProgressView": {
      "abstract": [
        {
          "text": "A view that depicts the progress of a task over time.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIProgressView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIProgressView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIProgressView"
        }
      ],
      "role": "symbol",
      "title": "UIProgressView",
      "type": "topic",
      "url": "/documentation/uikit/uiprogressview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions": {
      "abstract": [
        {
          "text": "A set of standard methods that apps can adopt to support editing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIResponderStandardEditActions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIResponderStandardEditActions"
        }
      ],
      "role": "symbol",
      "title": "UIResponderStandardEditActions",
      "type": "topic",
      "url": "/documentation/uikit/uiresponderstandardeditactions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94": {
      "abstract": [
        {
          "text": "A type that calls your code in reaction to changes in the trait environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITraitChangeObservable"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITraitChangeObservable"
        }
      ],
      "role": "symbol",
      "title": "UITraitChangeObservable",
      "type": "topic",
      "url": "/documentation/uikit/uitraitchangeobservable-67e94"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitEnvironment": {
      "abstract": [
        {
          "text": "A set of methods that makes the iOS interface environment available to your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITraitEnvironment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitEnvironment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITraitEnvironment"
        }
      ],
      "role": "symbol",
      "title": "UITraitEnvironment",
      "type": "topic",
      "url": "/documentation/uikit/uitraitenvironment"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserActivityRestoring": {
      "abstract": [
        {
          "text": "The protocol you adopt to restore an object’s state from a user activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIUserActivityRestoring"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserActivityRestoring",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserActivityRestoring"
        }
      ],
      "role": "symbol",
      "title": "UIUserActivityRestoring",
      "type": "topic",
      "url": "/documentation/uikit/uiuseractivityrestoring"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView": {
      "abstract": [
        {
          "text": "An object that manages the content for a rectangular area on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIView"
        }
      ],
      "role": "symbol",
      "title": "UIView",
      "type": "topic",
      "url": "/documentation/uikit/uiview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/contentUnavailableConfiguration-4b95e": {
      "abstract": [
        {
          "text": "The current content-unavailable configuration of the view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentUnavailableConfiguration"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit22UIContentConfigurationP",
          "text": "UIContentConfiguration"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/contentUnavailableConfiguration-4b95e",
      "kind": "symbol",
      "role": "symbol",
      "title": "contentUnavailableConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/contentunavailableconfiguration-4b95e"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWebView": {
      "abstract": [
        {
          "text": "A view that embeds web content in your app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIWebView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWebView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWebView"
        }
      ],
      "role": "symbol",
      "title": "UIWebView",
      "type": "topic",
      "url": "/documentation/uikit/uiwebview"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)CALayerDelegate": {
      "abstract": [
        {
          "text": "Methods your app can implement to respond to layer-related events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CALayerDelegate"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)CALayerDelegate",
      "kind": "symbol",
      "role": "symbol",
      "title": "CALayerDelegate",
      "type": "topic",
      "url": "/documentation/QuartzCore/CALayerDelegate"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSTouchBarProvider": {
      "abstract": [
        {
          "text": "A protocol that an object adopts to create a bar object in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTouchBarProvider"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSTouchBarProvider",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTouchBarProvider",
      "type": "topic",
      "url": "/documentation/AppKit/NSTouchBarProvider"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIView"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)CALayerDelegate",
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSTouchBarProvider",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityIdentification",
        "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationProviding",
        "doc://com.apple.uikit/documentation/UIKit/UIAppearance",
        "doc://com.apple.uikit/documentation/UIKit/UIAppearanceContainer",
        "doc://com.apple.uikit/documentation/UIKit/UIContentView-5fh3z",
        "doc://com.apple.uikit/documentation/UIKit/UICoordinateSpace",
        "doc://com.apple.uikit/documentation/UIKit/UIDynamicItem",
        "doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment",
        "doc://com.apple.uikit/documentation/UIKit/UIFocusItem",
        "doc://com.apple.uikit/documentation/UIKit/UIFocusItemContainer",
        "doc://com.apple.uikit/documentation/UIKit/UILargeContentViewerItem",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteConfigurationSupporting",
        "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationControllerSourceItem",
        "doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions",
        "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94",
        "doc://com.apple.uikit/documentation/UIKit/UITraitEnvironment",
        "doc://com.apple.uikit/documentation/UIKit/UIUserActivityRestoring"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Content-views",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIActivityIndicatorView",
        "doc://com.apple.uikit/documentation/UIKit/UICalendarView",
        "doc://com.apple.uikit/documentation/UIKit/UIImageView",
        "doc://com.apple.uikit/documentation/UIKit/UIPickerView",
        "doc://com.apple.uikit/documentation/UIKit/UIProgressView",
        "doc://com.apple.uikit/documentation/UIKit/UIWebView"
      ],
      "title": "Content views"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableView/init(coder:)",
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableView/init(configuration:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableView/isScrollEnabled"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIContentUnavailableView"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentUnavailableView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentUnavailableView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableView/configuration",
                "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableView/isScrollEnabled"
              ],
              "title": "Instance Properties"
            },
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableView/init(coder:)",
                "doc://com.apple.uikit/documentation/UIKit/UIContentUnavailableView/initWithConfiguration:"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIView"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIContentView-3zu2k"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Content-views",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIActivityIndicatorView",
                "doc://com.apple.uikit/documentation/UIKit/UICalendarView",
                "doc://com.apple.uikit/documentation/UIKit/UIImageView",
                "doc://com.apple.uikit/documentation/UIKit/UIPickerView",
                "doc://com.apple.uikit/documentation/UIKit/UIProgressView",
                "doc://com.apple.uikit/documentation/UIKit/UIWebView"
              ],
              "title": "Content views"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIContentUnavailableView"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UIView",
                    "text": "UIView"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentUnavailableView~1isScrollEnabled/title",
          "value": "scrollEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentUnavailableView~1isScrollEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scrollEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfigurationProviding/title",
          "value": "UIActivityItemsConfigurationProviding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfigurationProviding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityItemsConfigurationProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfigurationProviding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityItemsConfigurationProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/title",
          "value": "UIView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentUnavailableView~1init(coder:)/title",
          "value": "initWithCoder:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentUnavailableView~1init(coder:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCoder:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAppearance/title",
          "value": "UIAppearance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAppearance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAppearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAppearance/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAppearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserActivityRestoring/title",
          "value": "UIUserActivityRestoring"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserActivityRestoring/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserActivityRestoring"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserActivityRestoring/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserActivityRestoring"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponderStandardEditActions/title",
          "value": "UIResponderStandardEditActions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponderStandardEditActions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIResponderStandardEditActions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponderStandardEditActions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIResponderStandardEditActions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusItemContainer/title",
          "value": "UIFocusItemContainer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusItemContainer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFocusItemContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusItemContainer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFocusItemContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIProgressView/title",
          "value": "UIProgressView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIProgressView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIProgressView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIProgressView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIProgressView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILargeContentViewerItem/title",
          "value": "UILargeContentViewerItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILargeContentViewerItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UILargeContentViewerItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILargeContentViewerItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILargeContentViewerItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationControllerSourceItem/title",
          "value": "UIPopoverPresentationControllerSourceItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationControllerSourceItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPopoverPresentationControllerSourceItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationControllerSourceItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPopoverPresentationControllerSourceItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteConfigurationSupporting/title",
          "value": "UIPasteConfigurationSupporting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteConfigurationSupporting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteConfigurationSupporting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteConfigurationSupporting/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteConfigurationSupporting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityIndicatorView/title",
          "value": "UIActivityIndicatorView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityIndicatorView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityIndicatorView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityIndicatorView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityIndicatorView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImageView/title",
          "value": "UIImageView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImageView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImageView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImageView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICalendarView/title",
          "value": "UICalendarView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICalendarView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICalendarView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICalendarView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICalendarView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSTouchBarProvider/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSTouchBarProvider"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusItem/title",
          "value": "UIFocusItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFocusItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFocusItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusEnvironment/title",
          "value": "UIFocusEnvironment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusEnvironment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFocusEnvironment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusEnvironment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFocusEnvironment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView/title",
          "value": "UIWebView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWebView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWebView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPickerView/title",
          "value": "UIPickerView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPickerView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPickerView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPickerView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPickerView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityIdentification/title",
          "value": "UIAccessibilityIdentification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityIdentification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityIdentification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityIdentification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityIdentification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)CALayerDelegate/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CALayerDelegate"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAppearanceContainer/title",
          "value": "UIAppearanceContainer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAppearanceContainer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAppearanceContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAppearanceContainer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAppearanceContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICoordinateSpace/title",
          "value": "UICoordinateSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICoordinateSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICoordinateSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICoordinateSpace/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICoordinateSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitEnvironment/title",
          "value": "UITraitEnvironment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitEnvironment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITraitEnvironment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitEnvironment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITraitEnvironment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicItem/title",
          "value": "UIDynamicItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDynamicItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDynamicItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentUnavailableView/title",
          "value": "UIContentUnavailableView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentUnavailableView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentUnavailableView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentUnavailableView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentUnavailableView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uicontentunavailableview"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uicontentunavailableview"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
