{
  "abstract": [
    {
      "text": "An interaction object that you use to display relevant actions for your content.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIContextMenuInteraction",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIContextMenuInteraction"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIContextMenuInteraction"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "UIContextMenuInteraction"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIContextMenuInteraction"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.uikit/documentation/UIKit/building-a-desktop-class-ipad-app"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object to focus the user’s attention on a specific portion of your content, and to provide actions for the user to perform on that content. A context menu interaction object tracks Force Touch gestures on devices that support 3D Touch, and long-press gestures on devices that don’t support it. When the appropriate gesture occurs, this object animates your content to a new interface and displays the contextual menu that you supplied. UIKit manages all menu-related interactions and reports the selected action, if any, back to your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "A context menu interaction object inherits from ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIInteraction",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". After creating the object, assign an appropriate object to its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction/delegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property and use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/addInteraction(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to attach it to one of your views. The delegate object you provide must adopt the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteractionDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol. Use the methods of that object to provide the contents of the contextual menu. Add your context menu interaction object to a view in your interface using the view’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/addInteraction(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction": {
      "abstract": [
        {
          "text": "An interaction object that you use to display relevant actions for your content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIContextMenuInteraction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContextMenuInteraction"
        }
      ],
      "role": "symbol",
      "title": "UIContextMenuInteraction",
      "type": "topic",
      "url": "/documentation/uikit/uicontextmenuinteraction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction/appearance": {
      "abstract": [
        {
          "text": "Constants that describe the appearance of the menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "appearance"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction/appearance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "appearance"
        }
      ],
      "role": "symbol",
      "title": "UIContextMenuInteraction.appearance",
      "type": "topic",
      "url": "/documentation/uikit/uicontextmenuinteraction/appearance"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction/delegate": {
      "abstract": [
        {
          "text": "The object that provides the preview and contextual menu for your content and responds to interaction-related events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIContextMenuInteractionDelegate",
          "text": "UIContextMenuInteractionDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/uikit/uicontextmenuinteraction/delegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction/dismissMenu()": {
      "abstract": [
        {
          "text": "Dismisses the context menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dismissMenu"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction/dismissMenu()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dismissMenu"
        }
      ],
      "role": "symbol",
      "title": "dismissMenu()",
      "type": "topic",
      "url": "/documentation/uikit/uicontextmenuinteraction/dismissmenu()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction/init(delegate:)": {
      "abstract": [
        {
          "text": "Creates a context menu interaction object with the specified delegate object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIContextMenuInteractionDelegate",
          "text": "UIContextMenuInteractionDelegate"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction/init(delegate:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithDelegate:"
        }
      ],
      "role": "symbol",
      "title": "init(delegate:)",
      "type": "topic",
      "url": "/documentation/uikit/uicontextmenuinteraction/init(delegate:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction/location(in:)": {
      "abstract": [
        {
          "text": "Returns the location of the user interaction in the specified view’s coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "location"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction/location(in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "locationInView:"
        }
      ],
      "role": "symbol",
      "title": "location(in:)",
      "type": "topic",
      "url": "/documentation/uikit/uicontextmenuinteraction/location(in:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction/menuAppearance": {
      "abstract": [
        {
          "text": "The appearance of the context menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "menuAppearance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIContextMenuInteraction",
          "text": "UIContextMenuInteraction"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIContextMenuInteractionAppearance",
          "text": "appearance"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction/menuAppearance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "menuAppearance"
        }
      ],
      "role": "symbol",
      "title": "menuAppearance",
      "type": "topic",
      "url": "/documentation/uikit/uicontextmenuinteraction/menuappearance"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction/updateVisibleMenu(_:)": {
      "abstract": [
        {
          "text": "Updates the currently visible menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateVisibleMenu"
        },
        {
          "kind": "text",
          "text": "(("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIMenu",
          "text": "UIMenu"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIMenu",
          "text": "UIMenu"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction/updateVisibleMenu(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "updateVisibleMenuWithBlock:"
        }
      ],
      "role": "symbol",
      "title": "updateVisibleMenu(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uicontextmenuinteraction/updatevisiblemenu(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteractionDelegate": {
      "abstract": [
        {
          "text": "The methods for providing the set of actions to perform on your content, and for customizing the preview of that content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIContextMenuInteractionDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteractionDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContextMenuInteractionDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIContextMenuInteractionDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uicontextmenuinteractiondelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIInteraction": {
      "abstract": [
        {
          "text": "The protocol that an interaction implements to access the view that owns it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIInteraction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIInteraction"
        }
      ],
      "role": "symbol",
      "title": "UIInteraction",
      "type": "topic",
      "url": "/documentation/uikit/uiinteraction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPreviewParameters": {
      "abstract": [
        {
          "text": "Additional parameters to use when animating a preview interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPreviewParameters"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPreviewParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPreviewParameters"
        }
      ],
      "role": "symbol",
      "title": "UIPreviewParameters",
      "type": "topic",
      "url": "/documentation/uikit/uipreviewparameters"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPreviewTarget": {
      "abstract": [
        {
          "text": "An object that specifies the container view to use for animations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPreviewTarget"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPreviewTarget",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPreviewTarget"
        }
      ],
      "role": "symbol",
      "title": "UIPreviewTarget",
      "type": "topic",
      "url": "/documentation/uikit/uipreviewtarget"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITargetedPreview": {
      "abstract": [
        {
          "text": "An object describing the view to use during preview-related animations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITargetedPreview"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITargetedPreview",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITargetedPreview"
        }
      ],
      "role": "symbol",
      "title": "UITargetedPreview",
      "type": "topic",
      "url": "/documentation/uikit/uitargetedpreview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/addInteraction(_:)": {
      "abstract": [
        {
          "text": "Adds an interaction to the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addInteraction"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIInteraction",
          "text": "UIInteraction"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/addInteraction(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addInteraction:"
        }
      ],
      "role": "symbol",
      "title": "addInteraction(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiview/addinteraction(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/adding-context-menus-in-your-app": {
      "abstract": [
        {
          "text": "Provide quick access to useful actions by adding context menus to your iOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/adding-context-menus-in-your-app",
      "kind": "article",
      "role": "sampleCode",
      "title": "Adding context menus in your app",
      "type": "topic",
      "url": "/documentation/uikit/adding-context-menus-in-your-app"
    },
    "doc://com.apple.uikit/documentation/UIKit/adding-menus-and-shortcuts-to-the-menu-bar-and-user-interface": {
      "abstract": [
        {
          "text": "Provide quick access to useful actions by adding menus and keyboard shortcuts to your Mac app built with Mac Catalyst.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/adding-menus-and-shortcuts-to-the-menu-bar-and-user-interface",
      "kind": "article",
      "role": "sampleCode",
      "title": "Adding menus and shortcuts to the menu bar and user interface",
      "type": "topic",
      "url": "/documentation/uikit/adding-menus-and-shortcuts-to-the-menu-bar-and-user-interface"
    },
    "doc://com.apple.uikit/documentation/UIKit/building-a-desktop-class-ipad-app": {
      "abstract": [
        {
          "text": "Optimize your iPad app’s user experience by adopting desktop-class enhancements for multitasking with Stage Manager, document interactions, text editing, search, and more in iPadOS 16.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/building-a-desktop-class-ipad-app",
      "kind": "article",
      "role": "article",
      "title": "Building a desktop-class iPad app",
      "type": "topic",
      "url": "/documentation/uikit/building-a-desktop-class-ipad-app"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.apple.uikit/documentation/UIKit/UIInteraction"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Contextual-menus",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteractionDelegate",
        "doc://com.apple.uikit/documentation/UIKit/UITargetedPreview",
        "doc://com.apple.uikit/documentation/UIKit/UIPreviewTarget",
        "doc://com.apple.uikit/documentation/UIKit/UIPreviewParameters"
      ],
      "title": "Contextual menus"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-context-menu-interaction-object",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction/init(delegate:)",
        "doc://com.apple.uikit/documentation/UIKit/adding-context-menus-in-your-app",
        "doc://com.apple.uikit/documentation/UIKit/adding-menus-and-shortcuts-to-the-menu-bar-and-user-interface"
      ],
      "title": "Creating a context menu interaction object"
    },
    {
      "anchor": "Previewing-and-managing-the-content",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction/delegate",
        "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteractionDelegate"
      ],
      "title": "Previewing and managing the content"
    },
    {
      "anchor": "Getting-the-interactions-location",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction/location(in:)"
      ],
      "title": "Getting the interaction’s location"
    },
    {
      "anchor": "Getting-the-menu-appearance",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction/menuAppearance",
        "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction/appearance"
      ],
      "title": "Getting the menu appearance"
    },
    {
      "anchor": "Managing-menu-interactions",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction/dismissMenu()",
        "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction/updateVisibleMenu(_:)"
      ],
      "title": "Managing menu interactions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIContextMenuInteraction"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContextMenuInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContextMenuInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-context-menu-interaction-object",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction/init(delegate:)",
                "doc://com.apple.uikit/documentation/UIKit/adding-context-menus-in-your-app",
                "doc://com.apple.uikit/documentation/UIKit/adding-menus-and-shortcuts-to-the-menu-bar-and-user-interface"
              ],
              "title": "Creating a context menu interaction object"
            },
            {
              "anchor": "Previewing-and-managing-the-content",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction/delegate",
                "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteractionDelegate"
              ],
              "title": "Previewing and managing the content"
            },
            {
              "anchor": "Getting-the-interactions-location",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction/location(in:)"
              ],
              "title": "Getting the interaction’s location"
            },
            {
              "anchor": "Getting-the-menu-appearance",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction/menuAppearance",
                "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction/appearance"
              ],
              "title": "Getting the menu appearance"
            },
            {
              "anchor": "Managing-menu-interactions",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction/dismissMenu()",
                "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteraction/updateVisibleMenu(_:)"
              ],
              "title": "Managing menu interactions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIInteraction"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Contextual-menus",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteractionDelegate",
                "doc://com.apple.uikit/documentation/UIKit/UITargetedPreview",
                "doc://com.apple.uikit/documentation/UIKit/UIPreviewTarget",
                "doc://com.apple.uikit/documentation/UIKit/UIPreviewParameters"
              ],
              "title": "Contextual menus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIContextMenuInteraction"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuInteraction/title",
          "value": "UIContextMenuInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContextMenuInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContextMenuInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPreviewTarget/title",
          "value": "UIPreviewTarget"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPreviewTarget/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPreviewTarget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPreviewTarget/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPreviewTarget"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuInteraction~1updateVisibleMenu(_:)/title",
          "value": "updateVisibleMenuWithBlock:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuInteraction~1updateVisibleMenu(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "updateVisibleMenuWithBlock:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPreviewParameters/title",
          "value": "UIPreviewParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPreviewParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPreviewParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPreviewParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPreviewParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuInteraction~1init(delegate:)/title",
          "value": "initWithDelegate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuInteraction~1init(delegate:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithDelegate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1addInteraction(_:)/title",
          "value": "addInteraction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1addInteraction(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addInteraction:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuInteraction~1menuAppearance/title",
          "value": "menuAppearance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuInteraction~1menuAppearance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "menuAppearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuInteraction~1appearance/title",
          "value": "UIContextMenuInteractionAppearance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuInteraction~1appearance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContextMenuInteractionAppearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuInteraction~1appearance/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContextMenuInteractionAppearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITargetedPreview/title",
          "value": "UITargetedPreview"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITargetedPreview/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITargetedPreview"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITargetedPreview/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITargetedPreview"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuInteractionDelegate/title",
          "value": "UIContextMenuInteractionDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuInteractionDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContextMenuInteractionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuInteractionDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContextMenuInteractionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuInteraction~1dismissMenu()/title",
          "value": "dismissMenu"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuInteraction~1dismissMenu()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dismissMenu"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuInteraction~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuInteraction~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuInteraction~1location(in:)/title",
          "value": "locationInView:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuInteraction~1location(in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "locationInView:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInteraction/title",
          "value": "UIInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIInteraction"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uicontextmenuinteraction"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uicontextmenuinteraction"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
