{
  "abstract": [
    {
      "text": "Constants that describe the physical orientation of the device.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIDeviceOrientation",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIDeviceOrientation"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIDeviceOrientation"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "UIDeviceOrientation"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIDeviceOrientation"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDevice/orientation",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property uses these constants to identify the device orientation. These constants identify the physical orientation of the device and aren’t tied to the orientation of your app’s user interface.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDevice/beginGeneratingDeviceOrientationNotifications()": {
      "abstract": [
        {
          "text": "Begins the generation of notifications of device orientation changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginGeneratingDeviceOrientationNotifications"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDevice/beginGeneratingDeviceOrientationNotifications()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beginGeneratingDeviceOrientationNotifications"
        }
      ],
      "role": "symbol",
      "title": "beginGeneratingDeviceOrientationNotifications()",
      "type": "topic",
      "url": "/documentation/uikit/uidevice/begingeneratingdeviceorientationnotifications()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDevice/endGeneratingDeviceOrientationNotifications()": {
      "abstract": [
        {
          "text": "Ends the generation of notifications of device orientation changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endGeneratingDeviceOrientationNotifications"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDevice/endGeneratingDeviceOrientationNotifications()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "endGeneratingDeviceOrientationNotifications"
        }
      ],
      "role": "symbol",
      "title": "endGeneratingDeviceOrientationNotifications()",
      "type": "topic",
      "url": "/documentation/uikit/uidevice/endgeneratingdeviceorientationnotifications()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDevice/isGeneratingDeviceOrientationNotifications": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the device generates orientation notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isGeneratingDeviceOrientationNotifications"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDevice/isGeneratingDeviceOrientationNotifications",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "generatesDeviceOrientationNotifications"
        }
      ],
      "role": "symbol",
      "title": "isGeneratingDeviceOrientationNotifications",
      "type": "topic",
      "url": "/documentation/uikit/uidevice/isgeneratingdeviceorientationnotifications"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDevice/orientation": {
      "abstract": [
        {
          "text": "The physical orientation of the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "orientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIDeviceOrientation",
          "text": "UIDeviceOrientation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDevice/orientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "orientation"
        }
      ],
      "role": "symbol",
      "title": "orientation",
      "type": "topic",
      "url": "/documentation/uikit/uidevice/orientation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation": {
      "abstract": [
        {
          "text": "Constants that describe the physical orientation of the device.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDeviceOrientation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDeviceOrientation"
        }
      ],
      "role": "symbol",
      "title": "UIDeviceOrientation",
      "type": "topic",
      "url": "/documentation/uikit/uideviceorientation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/faceDown": {
      "abstract": [
        {
          "text": "The device is held parallel to the ground with the screen facing downwards.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "faceDown"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/faceDown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDeviceOrientationFaceDown"
        }
      ],
      "role": "symbol",
      "title": "UIDeviceOrientation.faceDown",
      "type": "topic",
      "url": "/documentation/uikit/uideviceorientation/facedown"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/faceUp": {
      "abstract": [
        {
          "text": "The device is held parallel to the ground with the screen facing upwards.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "faceUp"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/faceUp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDeviceOrientationFaceUp"
        }
      ],
      "role": "symbol",
      "title": "UIDeviceOrientation.faceUp",
      "type": "topic",
      "url": "/documentation/uikit/uideviceorientation/faceup"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/uideviceorientation/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/isFlat": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the specified orientation is face up or face down.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isFlat"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/isFlat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDeviceOrientationIsFlat"
        }
      ],
      "role": "symbol",
      "title": "isFlat",
      "type": "topic",
      "url": "/documentation/uikit/uideviceorientation/isflat"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/isLandscape": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the device is in a landscape orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isLandscape"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/isLandscape",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDeviceOrientationIsLandscape"
        }
      ],
      "role": "symbol",
      "title": "isLandscape",
      "type": "topic",
      "url": "/documentation/uikit/uideviceorientation/islandscape"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/isPortrait": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the device is in a portrait orientation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isPortrait"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/isPortrait",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDeviceOrientationIsPortrait"
        }
      ],
      "role": "symbol",
      "title": "isPortrait",
      "type": "topic",
      "url": "/documentation/uikit/uideviceorientation/isportrait"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/isValidInterfaceOrientation": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the specified orientation is one of the portrait or landscape orientations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isValidInterfaceOrientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/isValidInterfaceOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDeviceOrientationIsValidInterfaceOrientation"
        }
      ],
      "role": "symbol",
      "title": "isValidInterfaceOrientation",
      "type": "topic",
      "url": "/documentation/uikit/uideviceorientation/isvalidinterfaceorientation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/landscapeLeft": {
      "abstract": [
        {
          "text": "The device is in landscape mode, with the device held upright and the front-facing camera on the left side.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "landscapeLeft"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/landscapeLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDeviceOrientationLandscapeLeft"
        }
      ],
      "role": "symbol",
      "title": "UIDeviceOrientation.landscapeLeft",
      "type": "topic",
      "url": "/documentation/uikit/uideviceorientation/landscapeleft"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/landscapeRight": {
      "abstract": [
        {
          "text": "The device is in landscape mode, with the device held upright and the front-facing camera on the right side.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "landscapeRight"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/landscapeRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDeviceOrientationLandscapeRight"
        }
      ],
      "role": "symbol",
      "title": "UIDeviceOrientation.landscapeRight",
      "type": "topic",
      "url": "/documentation/uikit/uideviceorientation/landscaperight"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/portrait": {
      "abstract": [
        {
          "text": "The device is in portrait mode, with the device held upright and the front-facing camera at the top.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "portrait"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/portrait",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDeviceOrientationPortrait"
        }
      ],
      "role": "symbol",
      "title": "UIDeviceOrientation.portrait",
      "type": "topic",
      "url": "/documentation/uikit/uideviceorientation/portrait"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/portraitUpsideDown": {
      "abstract": [
        {
          "text": "The device is in portrait mode but upside down, with the device held upright and the front-facing camera at the bottom.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "portraitUpsideDown"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/portraitUpsideDown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDeviceOrientationPortraitUpsideDown"
        }
      ],
      "role": "symbol",
      "title": "UIDeviceOrientation.portraitUpsideDown",
      "type": "topic",
      "url": "/documentation/uikit/uideviceorientation/portraitupsidedown"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/unknown": {
      "abstract": [
        {
          "text": "The orientation of the device can’t be determined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unknown"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/unknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDeviceOrientationUnknown"
        }
      ],
      "role": "symbol",
      "title": "UIDeviceOrientation.unknown",
      "type": "topic",
      "url": "/documentation/uikit/uideviceorientation/unknown"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Tracking-the-device-orientation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIDevice/orientation",
        "doc://com.apple.uikit/documentation/UIKit/UIDevice/isGeneratingDeviceOrientationNotifications",
        "doc://com.apple.uikit/documentation/UIKit/UIDevice/beginGeneratingDeviceOrientationNotifications()",
        "doc://com.apple.uikit/documentation/UIKit/UIDevice/endGeneratingDeviceOrientationNotifications()"
      ],
      "title": "Tracking the device orientation"
    }
  ],
  "topicSections": [
    {
      "anchor": "Device-orientations",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/unknown",
        "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/portrait",
        "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/portraitUpsideDown",
        "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/landscapeLeft",
        "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/landscapeRight",
        "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/faceUp",
        "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/faceDown"
      ],
      "title": "Device orientations"
    },
    {
      "anchor": "Orientation-testing",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/isPortrait",
        "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/isLandscape",
        "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/isFlat",
        "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/isValidInterfaceOrientation"
      ],
      "title": "Orientation testing"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIDeviceOrientation"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDeviceOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDeviceOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Device-orientations",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/unknown",
                "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/portrait",
                "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/portraitUpsideDown",
                "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/landscapeLeft",
                "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/landscapeRight",
                "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/faceUp",
                "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/faceDown"
              ],
              "title": "Device orientations"
            },
            {
              "anchor": "Orientation-testing",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/isPortrait",
                "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/isLandscape",
                "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/isFlat",
                "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientation/isValidInterfaceOrientation"
              ],
              "title": "Orientation testing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Tracking-the-device-orientation",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIDevice/orientation",
                "doc://com.apple.uikit/documentation/UIKit/UIDevice/isGeneratingDeviceOrientationNotifications",
                "doc://com.apple.uikit/documentation/UIKit/UIDevice/beginGeneratingDeviceOrientationNotifications()",
                "doc://com.apple.uikit/documentation/UIKit/UIDevice/endGeneratingDeviceOrientationNotifications()"
              ],
              "title": "Tracking the device orientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIDeviceOrientation"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDeviceOrientation~1isPortrait/title",
          "value": "UIDeviceOrientationIsPortrait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDeviceOrientation~1isPortrait/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDeviceOrientationIsPortrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDevice~1beginGeneratingDeviceOrientationNotifications()/title",
          "value": "beginGeneratingDeviceOrientationNotifications"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDevice~1beginGeneratingDeviceOrientationNotifications()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "beginGeneratingDeviceOrientationNotifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDeviceOrientation~1landscapeLeft/title",
          "value": "UIDeviceOrientationLandscapeLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDeviceOrientation~1landscapeLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDeviceOrientationLandscapeLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDevice~1isGeneratingDeviceOrientationNotifications/title",
          "value": "generatesDeviceOrientationNotifications"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDevice~1isGeneratingDeviceOrientationNotifications/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "generatesDeviceOrientationNotifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDeviceOrientation~1isValidInterfaceOrientation/title",
          "value": "UIDeviceOrientationIsValidInterfaceOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDeviceOrientation~1isValidInterfaceOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDeviceOrientationIsValidInterfaceOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDeviceOrientation~1isLandscape/title",
          "value": "UIDeviceOrientationIsLandscape"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDeviceOrientation~1isLandscape/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDeviceOrientationIsLandscape"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDeviceOrientation~1isFlat/title",
          "value": "UIDeviceOrientationIsFlat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDeviceOrientation~1isFlat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDeviceOrientationIsFlat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDeviceOrientation~1faceUp/title",
          "value": "UIDeviceOrientationFaceUp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDeviceOrientation~1faceUp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDeviceOrientationFaceUp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDevice~1orientation/title",
          "value": "orientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDevice~1orientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "orientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDeviceOrientation~1faceDown/title",
          "value": "UIDeviceOrientationFaceDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDeviceOrientation~1faceDown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDeviceOrientationFaceDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDeviceOrientation~1portrait/title",
          "value": "UIDeviceOrientationPortrait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDeviceOrientation~1portrait/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDeviceOrientationPortrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDeviceOrientation~1portraitUpsideDown/title",
          "value": "UIDeviceOrientationPortraitUpsideDown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDeviceOrientation~1portraitUpsideDown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDeviceOrientationPortraitUpsideDown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDeviceOrientation~1unknown/title",
          "value": "UIDeviceOrientationUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDeviceOrientation~1unknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDeviceOrientationUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDeviceOrientation~1landscapeRight/title",
          "value": "UIDeviceOrientationLandscapeRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDeviceOrientation~1landscapeRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDeviceOrientationLandscapeRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDevice~1endGeneratingDeviceOrientationNotifications()/title",
          "value": "endGeneratingDeviceOrientationNotifications"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDevice~1endGeneratingDeviceOrientationNotifications()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "endGeneratingDeviceOrientationNotifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDeviceOrientation/title",
          "value": "UIDeviceOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDeviceOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDeviceOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDeviceOrientation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDeviceOrientation"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uideviceorientation"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uideviceorientation"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
