{
  "abstract": [
    {
      "text": "A set of methods you can implement to respond to messages from a document interaction controller.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UIDocumentInteractionControllerDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIDocumentInteractionControllerDelegate"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIDocumentInteractionControllerDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "UIDocumentInteractionControllerDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIDocumentInteractionControllerDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this protocol to participate when document previews are displayed and when a document is about to be opened by another application. You can also use this protocol to respond to commands (such as “copy” and “print”) from a document interaction controller’s options menu.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you use a document interaction controller to display a document preview, your delegate must implement the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionControllerViewControllerForPreview(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. All other methods of this protocol are optional.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information about using a document interaction controller, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionController": {
      "abstract": [
        {
          "text": "A view controller that previews, opens, or prints files with a file format that your app can’t handle directly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDocumentInteractionController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDocumentInteractionController"
        }
      ],
      "role": "symbol",
      "title": "UIDocumentInteractionController",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentinteractioncontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionController/delegate": {
      "abstract": [
        {
          "text": "The delegate you want to receive document interaction notifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDocumentInteractionControllerDelegate",
          "text": "UIDocumentInteractionControllerDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionController/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentinteractioncontroller/delegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate": {
      "abstract": [
        {
          "text": "A set of methods you can implement to respond to messages from a document interaction controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDocumentInteractionControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDocumentInteractionControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIDocumentInteractionControllerDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentinteractioncontrollerdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionController(_:canPerformAction:)": {
      "abstract": [
        {
          "text": "Called when a document interaction controller needs to know whether the specified action can be performed on the associated document.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentInteractionController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDocumentInteractionController",
          "text": "UIDocumentInteractionController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "canPerformAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionController(_:canPerformAction:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentInteractionController:canPerformAction:"
        }
      ],
      "role": "symbol",
      "title": "documentInteractionController(_:canPerformAction:)",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentinteractioncontrollerdelegate/documentinteractioncontroller(_:canperformaction:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionController(_:didEndSendingToApplication:)": {
      "abstract": [
        {
          "text": "Called when a document interaction controller’s document has been handed off to the specified application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentInteractionController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDocumentInteractionController",
          "text": "UIDocumentInteractionController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didEndSendingToApplication"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionController(_:didEndSendingToApplication:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentInteractionController:didEndSendingToApplication:"
        }
      ],
      "role": "symbol",
      "title": "documentInteractionController(_:didEndSendingToApplication:)",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentinteractioncontrollerdelegate/documentinteractioncontroller(_:didendsendingtoapplication:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionController(_:performAction:)": {
      "abstract": [
        {
          "text": "Called when a document interaction controller wants its delegate to perform a specified action with the associated document.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentInteractionController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDocumentInteractionController",
          "text": "UIDocumentInteractionController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "performAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionController(_:performAction:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentInteractionController:performAction:"
        }
      ],
      "role": "symbol",
      "title": "documentInteractionController(_:performAction:)",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentinteractioncontrollerdelegate/documentinteractioncontroller(_:performaction:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionController(_:willBeginSendingToApplication:)": {
      "abstract": [
        {
          "text": "Called when a document interaction controller’s document is about to be opened by the specified application.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentInteractionController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDocumentInteractionController",
          "text": "UIDocumentInteractionController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willBeginSendingToApplication"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionController(_:willBeginSendingToApplication:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentInteractionController:willBeginSendingToApplication:"
        }
      ],
      "role": "symbol",
      "title": "documentInteractionController(_:willBeginSendingToApplication:)",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentinteractioncontrollerdelegate/documentinteractioncontroller(_:willbeginsendingtoapplication:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionControllerDidDismissOpenInMenu(_:)": {
      "abstract": [
        {
          "text": "Called when a document interaction controller has dismissed its Open In menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentInteractionControllerDidDismissOpenInMenu"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDocumentInteractionController",
          "text": "UIDocumentInteractionController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionControllerDidDismissOpenInMenu(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentInteractionControllerDidDismissOpenInMenu:"
        }
      ],
      "role": "symbol",
      "title": "documentInteractionControllerDidDismissOpenInMenu(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentinteractioncontrollerdelegate/documentinteractioncontrollerdiddismissopeninmenu(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionControllerDidDismissOptionsMenu(_:)": {
      "abstract": [
        {
          "text": "Called when a document interaction controller has dismissed its options menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentInteractionControllerDidDismissOptionsMenu"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDocumentInteractionController",
          "text": "UIDocumentInteractionController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionControllerDidDismissOptionsMenu(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentInteractionControllerDidDismissOptionsMenu:"
        }
      ],
      "role": "symbol",
      "title": "documentInteractionControllerDidDismissOptionsMenu(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentinteractioncontrollerdelegate/documentinteractioncontrollerdiddismissoptionsmenu(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionControllerDidEndPreview(_:)": {
      "abstract": [
        {
          "text": "Called when a document interaction controller has dismissed its document preview.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentInteractionControllerDidEndPreview"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDocumentInteractionController",
          "text": "UIDocumentInteractionController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionControllerDidEndPreview(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentInteractionControllerDidEndPreview:"
        }
      ],
      "role": "symbol",
      "title": "documentInteractionControllerDidEndPreview(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentinteractioncontrollerdelegate/documentinteractioncontrollerdidendpreview(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionControllerRectForPreview(_:)": {
      "abstract": [
        {
          "text": "Called when a document interaction controller needs the rectangle to use as the starting point for animating the display of a document preview.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentInteractionControllerRectForPreview"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDocumentInteractionController",
          "text": "UIDocumentInteractionController"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionControllerRectForPreview(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentInteractionControllerRectForPreview:"
        }
      ],
      "role": "symbol",
      "title": "documentInteractionControllerRectForPreview(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentinteractioncontrollerdelegate/documentinteractioncontrollerrectforpreview(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionControllerViewControllerForPreview(_:)": {
      "abstract": [
        {
          "text": "Called when a document interaction controller needs a view controller for presenting a document preview.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentInteractionControllerViewControllerForPreview"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDocumentInteractionController",
          "text": "UIDocumentInteractionController"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionControllerViewControllerForPreview(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentInteractionControllerViewControllerForPreview:"
        }
      ],
      "role": "symbol",
      "title": "documentInteractionControllerViewControllerForPreview(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentinteractioncontrollerdelegate/documentinteractioncontrollerviewcontrollerforpreview(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionControllerViewForPreview(_:)": {
      "abstract": [
        {
          "text": "Called when a document interaction controller needs the starting point for animating the display of a document preview.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentInteractionControllerViewForPreview"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDocumentInteractionController",
          "text": "UIDocumentInteractionController"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionControllerViewForPreview(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentInteractionControllerViewForPreview:"
        }
      ],
      "role": "symbol",
      "title": "documentInteractionControllerViewForPreview(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentinteractioncontrollerdelegate/documentinteractioncontrollerviewforpreview(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionControllerWillBeginPreview(_:)": {
      "abstract": [
        {
          "text": "Called when a document interaction controller is about to display a preview for its document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentInteractionControllerWillBeginPreview"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDocumentInteractionController",
          "text": "UIDocumentInteractionController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionControllerWillBeginPreview(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentInteractionControllerWillBeginPreview:"
        }
      ],
      "role": "symbol",
      "title": "documentInteractionControllerWillBeginPreview(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentinteractioncontrollerdelegate/documentinteractioncontrollerwillbeginpreview(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionControllerWillPresentOpenInMenu(_:)": {
      "abstract": [
        {
          "text": "Called when a document interaction controller is about to display an Open In menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentInteractionControllerWillPresentOpenInMenu"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDocumentInteractionController",
          "text": "UIDocumentInteractionController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionControllerWillPresentOpenInMenu(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentInteractionControllerWillPresentOpenInMenu:"
        }
      ],
      "role": "symbol",
      "title": "documentInteractionControllerWillPresentOpenInMenu(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentinteractioncontrollerdelegate/documentinteractioncontrollerwillpresentopeninmenu(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionControllerWillPresentOptionsMenu(_:)": {
      "abstract": [
        {
          "text": "Called when a document interaction controller is about to display an options menu.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentInteractionControllerWillPresentOptionsMenu"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDocumentInteractionController",
          "text": "UIDocumentInteractionController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionControllerWillPresentOptionsMenu(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentInteractionControllerWillPresentOptionsMenu:"
        }
      ],
      "role": "symbol",
      "title": "documentInteractionControllerWillPresentOptionsMenu(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentinteractioncontrollerdelegate/documentinteractioncontrollerwillpresentoptionsmenu(_:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Handling-document-related-interactions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionController/delegate"
      ],
      "title": "Handling document-related interactions"
    }
  ],
  "topicSections": [
    {
      "anchor": "Configuring-the-parent-view-controller",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionControllerViewControllerForPreview(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionControllerViewForPreview(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionControllerRectForPreview(_:)"
      ],
      "title": "Configuring the parent view controller"
    },
    {
      "anchor": "Presenting-the-user-interface",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionControllerWillBeginPreview(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionControllerDidEndPreview(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionControllerWillPresentOptionsMenu(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionControllerDidDismissOptionsMenu(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionControllerWillPresentOpenInMenu(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionControllerDidDismissOpenInMenu(_:)"
      ],
      "title": "Presenting the user interface"
    },
    {
      "anchor": "Opening-files",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionController(_:willBeginSendingToApplication:)",
        "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionController(_:didEndSendingToApplication:)"
      ],
      "title": "Opening files"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionController(_:canPerformAction:)",
        "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionController(_:performAction:)"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIDocumentInteractionControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocumentInteractionControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocumentInteractionControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Configuring-the-parent-view-controller",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionControllerViewControllerForPreview(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionControllerViewForPreview(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionControllerRectForPreview(_:)"
              ],
              "title": "Configuring the parent view controller"
            },
            {
              "anchor": "Presenting-the-user-interface",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionControllerWillBeginPreview(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionControllerDidEndPreview(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionControllerWillPresentOptionsMenu(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionControllerDidDismissOptionsMenu(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionControllerWillPresentOpenInMenu(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionControllerDidDismissOpenInMenu(_:)"
              ],
              "title": "Presenting the user interface"
            },
            {
              "anchor": "Opening-files",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionController(_:willBeginSendingToApplication:)",
                "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionController(_:didEndSendingToApplication:)"
              ],
              "title": "Opening files"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionController(_:canPerformAction:)",
                "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionControllerDelegate/documentInteractionController(_:performAction:)"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Handling-document-related-interactions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIDocumentInteractionController/delegate"
              ],
              "title": "Handling document-related interactions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIDocumentInteractionControllerDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentInteractionControllerDelegate~1documentInteractionControllerDidDismissOpenInMenu(_:)/title",
          "value": "documentInteractionControllerDidDismissOpenInMenu:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentInteractionControllerDelegate~1documentInteractionControllerDidDismissOpenInMenu(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "documentInteractionControllerDidDismissOpenInMenu:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentInteractionControllerDelegate~1documentInteractionController(_:didEndSendingToApplication:)/title",
          "value": "documentInteractionController:didEndSendingToApplication:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentInteractionControllerDelegate~1documentInteractionController(_:didEndSendingToApplication:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "documentInteractionController:didEndSendingToApplication:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentInteractionControllerDelegate~1documentInteractionController(_:performAction:)/title",
          "value": "documentInteractionController:performAction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentInteractionControllerDelegate~1documentInteractionController(_:performAction:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "documentInteractionController:performAction:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentInteractionControllerDelegate~1documentInteractionControllerViewForPreview(_:)/title",
          "value": "documentInteractionControllerViewForPreview:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentInteractionControllerDelegate~1documentInteractionControllerViewForPreview(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "documentInteractionControllerViewForPreview:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentInteractionControllerDelegate~1documentInteractionControllerDidEndPreview(_:)/title",
          "value": "documentInteractionControllerDidEndPreview:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentInteractionControllerDelegate~1documentInteractionControllerDidEndPreview(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "documentInteractionControllerDidEndPreview:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentInteractionController~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentInteractionController~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentInteractionController/title",
          "value": "UIDocumentInteractionController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentInteractionController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocumentInteractionController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentInteractionController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocumentInteractionController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentInteractionControllerDelegate~1documentInteractionController(_:willBeginSendingToApplication:)/title",
          "value": "documentInteractionController:willBeginSendingToApplication:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentInteractionControllerDelegate~1documentInteractionController(_:willBeginSendingToApplication:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "documentInteractionController:willBeginSendingToApplication:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentInteractionControllerDelegate~1documentInteractionControllerWillPresentOptionsMenu(_:)/title",
          "value": "documentInteractionControllerWillPresentOptionsMenu:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentInteractionControllerDelegate~1documentInteractionControllerWillPresentOptionsMenu(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "documentInteractionControllerWillPresentOptionsMenu:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentInteractionControllerDelegate~1documentInteractionController(_:canPerformAction:)/title",
          "value": "documentInteractionController:canPerformAction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentInteractionControllerDelegate~1documentInteractionController(_:canPerformAction:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "documentInteractionController:canPerformAction:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentInteractionControllerDelegate~1documentInteractionControllerDidDismissOptionsMenu(_:)/title",
          "value": "documentInteractionControllerDidDismissOptionsMenu:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentInteractionControllerDelegate~1documentInteractionControllerDidDismissOptionsMenu(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "documentInteractionControllerDidDismissOptionsMenu:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentInteractionControllerDelegate~1documentInteractionControllerWillPresentOpenInMenu(_:)/title",
          "value": "documentInteractionControllerWillPresentOpenInMenu:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentInteractionControllerDelegate~1documentInteractionControllerWillPresentOpenInMenu(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "documentInteractionControllerWillPresentOpenInMenu:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentInteractionControllerDelegate~1documentInteractionControllerRectForPreview(_:)/title",
          "value": "documentInteractionControllerRectForPreview:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentInteractionControllerDelegate~1documentInteractionControllerRectForPreview(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "documentInteractionControllerRectForPreview:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentInteractionControllerDelegate~1documentInteractionControllerWillBeginPreview(_:)/title",
          "value": "documentInteractionControllerWillBeginPreview:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentInteractionControllerDelegate~1documentInteractionControllerWillBeginPreview(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "documentInteractionControllerWillBeginPreview:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentInteractionControllerDelegate/title",
          "value": "UIDocumentInteractionControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentInteractionControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocumentInteractionControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentInteractionControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocumentInteractionControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentInteractionControllerDelegate~1documentInteractionControllerViewControllerForPreview(_:)/title",
          "value": "documentInteractionControllerViewControllerForPreview:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentInteractionControllerDelegate~1documentInteractionControllerViewControllerForPreview(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "documentInteractionControllerViewControllerForPreview:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uidocumentinteractioncontrollerdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uidocumentinteractioncontrollerdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
