{
  "abstract": [
    {
      "text": "The interface for querying a drop session about its state and associated drag items.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIDropSession"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UIDropSession",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIDropSession"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIDropSession"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "UIDropSession"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIDropSession"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSProgressReporting",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSProgressReporting",
              "text": "ProgressReporting"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDragDropSession",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)UIDragDropSession",
              "text": "UIDragDropSession"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.uikit/documentation/UIKit/making-a-view-into-a-drop-destination"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDragDropSession": {
      "abstract": [
        {
          "text": "The common interface for querying the state of both drag sessions and drop sessions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDragDropSession"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDragDropSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDragDropSession"
        }
      ],
      "role": "symbol",
      "title": "UIDragDropSession",
      "type": "topic",
      "url": "/documentation/uikit/uidragdropsession"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDropOperation": {
      "abstract": [
        {
          "text": "Operation types that determine how a drag and drop activity resolves when the user drops a drag item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDropOperation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDropOperation"
        }
      ],
      "role": "symbol",
      "title": "UIDropOperation",
      "type": "topic",
      "url": "/documentation/uikit/uidropoperation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDropProposal": {
      "abstract": [
        {
          "text": "A configuration for the behavior of a drop interaction, required if a view accepts drop activities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDropProposal"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropProposal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDropProposal"
        }
      ],
      "role": "symbol",
      "title": "UIDropProposal",
      "type": "topic",
      "url": "/documentation/uikit/uidropproposal"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDropSession": {
      "abstract": [
        {
          "text": "The interface for querying a drop session about its state and associated drag items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDropSession"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDropSession"
        }
      ],
      "role": "symbol",
      "title": "UIDropSession",
      "type": "topic",
      "url": "/documentation/uikit/uidropsession"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDropSession/loadObjects(ofClass:completion:)": {
      "abstract": [
        {
          "text": "Creates and loads a new instance of the specified class for each drag item in the session.",
          "type": "text"
        }
      ],
      "defaultImplementations": 1,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadObjects"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ofClass"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSItemProviderReading",
          "text": "NSItemProviderReading"
        },
        {
          "kind": "text",
          "text": ".Type, "
        },
        {
          "kind": "externalParam",
          "text": "completion"
        },
        {
          "kind": "text",
          "text": ": ([any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSItemProviderReading",
          "text": "NSItemProviderReading"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSProgress",
          "text": "Progress"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropSession/loadObjects(ofClass:completion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "loadObjectsOfClass:completion:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "loadObjects(ofClass:completion:)",
      "type": "topic",
      "url": "/documentation/uikit/uidropsession/loadobjects(ofclass:completion:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDropSession/localDragSession": {
      "abstract": [
        {
          "text": "The drag session that corresponds to this drop session, for in-app drag activities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localDragSession"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDragSession",
          "text": "UIDragSession"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropSession/localDragSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localDragSession"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "localDragSession",
      "type": "topic",
      "url": "/documentation/uikit/uidropsession/localdragsession"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDropSession/progressIndicatorStyle": {
      "abstract": [
        {
          "text": "The drop-progress indicator style associated with the drop session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "progressIndicatorStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIDropSessionProgressIndicatorStyle",
          "text": "UIDropSessionProgressIndicatorStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropSession/progressIndicatorStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "progressIndicatorStyle"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "progressIndicatorStyle",
      "type": "topic",
      "url": "/documentation/uikit/uidropsession/progressindicatorstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDropSessionProgressIndicatorStyle": {
      "abstract": [
        {
          "text": "The drop-progress indicator styles for the drop session, used while data is moving from the source to the destination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDropSessionProgressIndicatorStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDropSessionProgressIndicatorStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDropSessionProgressIndicatorStyle"
        }
      ],
      "role": "symbol",
      "title": "UIDropSessionProgressIndicatorStyle",
      "type": "topic",
      "url": "/documentation/uikit/uidropsessionprogressindicatorstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/making-a-view-into-a-drop-destination": {
      "abstract": [
        {
          "text": "Adopt drop interaction APIs to selectively consume dragged content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/making-a-view-into-a-drop-destination",
      "kind": "article",
      "role": "article",
      "title": "Making a view into a drop destination",
      "type": "topic",
      "url": "/documentation/uikit/making-a-view-into-a-drop-destination"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSProgressReporting": {
      "abstract": [
        {
          "text": "An interface for objects that report progress using a single progress instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "ProgressReporting"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSProgressReporting",
      "kind": "symbol",
      "role": "symbol",
      "title": "ProgressReporting",
      "type": "topic",
      "url": "/documentation/foundation/progressreporting"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSProgressReporting",
        "doc://com.apple.uikit/documentation/UIKit/UIDragDropSession"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Drop-destinations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIDropProposal",
        "doc://com.apple.uikit/documentation/UIKit/UIDropOperation",
        "doc://com.apple.uikit/documentation/UIKit/UIDropSessionProgressIndicatorStyle"
      ],
      "title": "Drop destinations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-drag-session",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIDropSession/localDragSession"
      ],
      "title": "Getting the drag session"
    },
    {
      "anchor": "Loading-objects",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIDropSession/loadObjects(ofClass:completion:)"
      ],
      "title": "Loading objects"
    },
    {
      "anchor": "Showing-a-progress-indicator",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIDropSession/progressIndicatorStyle"
      ],
      "title": "Showing a progress indicator"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIDropSession"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDropSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDropSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-the-drag-session",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIDropSession/localDragSession"
              ],
              "title": "Getting the drag session"
            },
            {
              "anchor": "Loading-objects",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIDropSession/loadObjects(ofClass:completion:)"
              ],
              "title": "Loading objects"
            },
            {
              "anchor": "Showing-a-progress-indicator",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIDropSession/progressIndicatorStyle"
              ],
              "title": "Showing a progress indicator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSProgressReporting",
                "doc://com.apple.uikit/documentation/UIKit/UIDragDropSession"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Drop-destinations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIDropProposal",
                "doc://com.apple.uikit/documentation/UIKit/UIDropOperation",
                "doc://com.apple.uikit/documentation/UIKit/UIDropSessionProgressIndicatorStyle"
              ],
              "title": "Drop destinations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIDropSession"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDragDropSession",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)UIDragDropSession",
                    "text": "UIDragDropSession"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSProgressReporting",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSProgressReporting",
                    "text": "NSProgressReporting"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSProgressReporting/title",
          "value": "NSProgressReporting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSessionProgressIndicatorStyle/title",
          "value": "UIDropSessionProgressIndicatorStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSessionProgressIndicatorStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDropSessionProgressIndicatorStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSessionProgressIndicatorStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDropSessionProgressIndicatorStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragDropSession/title",
          "value": "UIDragDropSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragDropSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDragDropSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragDropSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDragDropSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropOperation/title",
          "value": "UIDropOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDropOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDropOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession/title",
          "value": "UIDropSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDropSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDropSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession~1progressIndicatorStyle/title",
          "value": "progressIndicatorStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession~1progressIndicatorStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "progressIndicatorStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession~1loadObjects(ofClass:completion:)/title",
          "value": "loadObjectsOfClass:completion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession~1loadObjects(ofClass:completion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "loadObjectsOfClass:completion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropProposal/title",
          "value": "UIDropProposal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropProposal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDropProposal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropProposal/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDropProposal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession~1localDragSession/title",
          "value": "localDragSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDropSession~1localDragSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localDragSession"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uidropsession"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uidropsession"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
