{
  "abstract": [
    {
      "text": "The abstract superclass for all feedback generators.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIFeedbackGenerator"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIFeedbackGenerator",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIFeedbackGenerator"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIFeedbackGenerator"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "UIFeedbackGenerator"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIFeedbackGenerator"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Don’t subclass or create instances of this class yourself. Instead, instantiate one of the concrete feedback generator subclasses:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImpactFeedbackGenerator",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". Use impact feedback to indicate when an impact occurs. For example, you might trigger impact feedback when a user interface object collides with something or snaps into place.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISelectionFeedbackGenerator",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". Use selection feedback to indicate a change in selection.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINotificationFeedbackGenerator",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". Use notification feedback to indicate successes, failures, and warnings.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICanvasFeedbackGenerator",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". Use canvas feedback to indicate when a drawing event occurs, such as an object snapping to a guide or ruler.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "For more information, read ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/ApplePencil/playing-haptic-feedback-in-your-app",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/ApplePencil/playing-haptic-feedback-in-your-app": {
      "abstract": [
        {
          "text": "Provide tactile feedback when people perform certain actions in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/ApplePencil/playing-haptic-feedback-in-your-app",
      "kind": "article",
      "role": "article",
      "title": "Playing haptic feedback in your app",
      "type": "topic",
      "url": "/documentation/ApplePencil/playing-haptic-feedback-in-your-app"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICanvasFeedbackGenerator": {
      "abstract": [
        {
          "text": "A concrete feedback generator subclass that creates haptics to indicate events on a drawing canvas.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICanvasFeedbackGenerator"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICanvasFeedbackGenerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICanvasFeedbackGenerator"
        }
      ],
      "role": "symbol",
      "title": "UICanvasFeedbackGenerator",
      "type": "topic",
      "url": "/documentation/uikit/uicanvasfeedbackgenerator"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFeedbackGenerator": {
      "abstract": [
        {
          "text": "The abstract superclass for all feedback generators.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFeedbackGenerator"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFeedbackGenerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFeedbackGenerator"
        }
      ],
      "role": "symbol",
      "title": "UIFeedbackGenerator",
      "type": "topic",
      "url": "/documentation/uikit/uifeedbackgenerator"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFeedbackGenerator/init()": {
      "abstract": [
        {
          "text": "Creates a feedback generator.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFeedbackGenerator/init()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/uikit/uifeedbackgenerator/init()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFeedbackGenerator/init(view:)": {
      "abstract": [
        {
          "text": "Creates a feedback generator and attaches it to the specified view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "view"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFeedbackGenerator/init(view:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "feedbackGeneratorForView:"
        }
      ],
      "role": "symbol",
      "title": "init(view:)",
      "type": "topic",
      "url": "/documentation/uikit/uifeedbackgenerator/init(view:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFeedbackGenerator/prepare()": {
      "abstract": [
        {
          "text": "Prepares the generator to trigger feedback.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prepare"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFeedbackGenerator/prepare()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "prepare"
        }
      ],
      "role": "symbol",
      "title": "prepare()",
      "type": "topic",
      "url": "/documentation/uikit/uifeedbackgenerator/prepare()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImpactFeedbackGenerator": {
      "abstract": [
        {
          "text": "A concrete feedback generator subclass that creates haptics to simulate physical impacts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIImpactFeedbackGenerator"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImpactFeedbackGenerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImpactFeedbackGenerator"
        }
      ],
      "role": "symbol",
      "title": "UIImpactFeedbackGenerator",
      "type": "topic",
      "url": "/documentation/uikit/uiimpactfeedbackgenerator"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIInteraction": {
      "abstract": [
        {
          "text": "The protocol that an interaction implements to access the view that owns it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIInteraction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIInteraction"
        }
      ],
      "role": "symbol",
      "title": "UIInteraction",
      "type": "topic",
      "url": "/documentation/uikit/uiinteraction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINotificationFeedbackGenerator": {
      "abstract": [
        {
          "text": "A concrete feedback generator subclass that creates haptics to communicate successes, failures, and warnings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UINotificationFeedbackGenerator"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINotificationFeedbackGenerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UINotificationFeedbackGenerator"
        }
      ],
      "role": "symbol",
      "title": "UINotificationFeedbackGenerator",
      "type": "topic",
      "url": "/documentation/uikit/uinotificationfeedbackgenerator"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISelectionFeedbackGenerator": {
      "abstract": [
        {
          "text": "A concrete feedback generator subclass that creates haptics to indicate a change in selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISelectionFeedbackGenerator"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISelectionFeedbackGenerator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISelectionFeedbackGenerator"
        }
      ],
      "role": "symbol",
      "title": "UISelectionFeedbackGenerator",
      "type": "topic",
      "url": "/documentation/uikit/uiselectionfeedbackgenerator"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICanvasFeedbackGenerator",
        "doc://com.apple.uikit/documentation/UIKit/UIImpactFeedbackGenerator",
        "doc://com.apple.uikit/documentation/UIKit/UINotificationFeedbackGenerator",
        "doc://com.apple.uikit/documentation/UIKit/UISelectionFeedbackGenerator"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.apple.uikit/documentation/UIKit/UIInteraction"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Haptic-feedback",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/ApplePencil/playing-haptic-feedback-in-your-app",
        "doc://com.apple.uikit/documentation/UIKit/UIImpactFeedbackGenerator",
        "doc://com.apple.uikit/documentation/UIKit/UINotificationFeedbackGenerator",
        "doc://com.apple.uikit/documentation/UIKit/UISelectionFeedbackGenerator",
        "doc://com.apple.uikit/documentation/UIKit/UICanvasFeedbackGenerator"
      ],
      "title": "Haptic feedback"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializing-a-feedback-generator",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIFeedbackGenerator/init(view:)"
      ],
      "title": "Initializing a feedback generator"
    },
    {
      "anchor": "Preparing-to-generate-feedback",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIFeedbackGenerator/prepare()"
      ],
      "title": "Preparing to generate feedback"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIFeedbackGenerator/init()"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIFeedbackGenerator"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFeedbackGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFeedbackGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Initializing-a-feedback-generator",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIFeedbackGenerator/init(view:)"
              ],
              "title": "Initializing a feedback generator"
            },
            {
              "anchor": "Preparing-to-generate-feedback",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIFeedbackGenerator/prepare()"
              ],
              "title": "Preparing to generate feedback"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIFeedbackGenerator/init()"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UICanvasFeedbackGenerator",
                "doc://com.apple.uikit/documentation/UIKit/UIImpactFeedbackGenerator",
                "doc://com.apple.uikit/documentation/UIKit/UINotificationFeedbackGenerator",
                "doc://com.apple.uikit/documentation/UIKit/UISelectionFeedbackGenerator"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            },
            {
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIInteraction"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Haptic-feedback",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIImpactFeedbackGenerator",
                "doc://com.apple.uikit/documentation/UIKit/UINotificationFeedbackGenerator",
                "doc://com.apple.uikit/documentation/UIKit/UISelectionFeedbackGenerator",
                "doc://com.apple.uikit/documentation/UIKit/UICanvasFeedbackGenerator"
              ],
              "title": "Haptic feedback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIFeedbackGenerator"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFeedbackGenerator~1init()/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFeedbackGenerator~1init()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "init"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFeedbackGenerator/title",
          "value": "UIFeedbackGenerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFeedbackGenerator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFeedbackGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFeedbackGenerator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFeedbackGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImpactFeedbackGenerator/title",
          "value": "UIImpactFeedbackGenerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImpactFeedbackGenerator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImpactFeedbackGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImpactFeedbackGenerator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImpactFeedbackGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISelectionFeedbackGenerator/title",
          "value": "UISelectionFeedbackGenerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISelectionFeedbackGenerator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISelectionFeedbackGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISelectionFeedbackGenerator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISelectionFeedbackGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINotificationFeedbackGenerator/title",
          "value": "UINotificationFeedbackGenerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINotificationFeedbackGenerator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UINotificationFeedbackGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINotificationFeedbackGenerator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UINotificationFeedbackGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInteraction/title",
          "value": "UIInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICanvasFeedbackGenerator/title",
          "value": "UICanvasFeedbackGenerator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICanvasFeedbackGenerator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICanvasFeedbackGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICanvasFeedbackGenerator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICanvasFeedbackGenerator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFeedbackGenerator~1init(view:)/title",
          "value": "feedbackGeneratorForView:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFeedbackGenerator~1init(view:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "feedbackGeneratorForView:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFeedbackGenerator~1prepare()/title",
          "value": "prepare"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFeedbackGenerator~1prepare()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "prepare"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uifeedbackgenerator"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uifeedbackgenerator"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
