{
  "abstract": [
    {
      "text": "An abstract base class that manages the state, presentation, and behavior for a search that the find interaction initiates.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIFindSession"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIFindSession",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIFindSession"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIFindSession"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "UIFindSession"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIFindSession"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You return a session object from the delegate of a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindInteraction",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to manage the state, presentation, and behavior for a given search. The session object responds to navigation and replacement requests through its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindSession/highlightNextResult(in:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindSession/performSingleReplacement(query:replacementString:options:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " methods. It also provides presentation information to the system find panel through ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindSession/resultCount",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindSession/highlightedResultIndex",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "UIKit can manage the state when you implement the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol on a class that encapsulates the searchable content. To do this, create an instance of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchingFindSession",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and provide it a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchingFindSession/searchableObject",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " using an instance of your class.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you want to manage the state yourself or already have a class that implements find and replace for your app, you can subclass ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindSession",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to bridge your custom implementation to the system UI.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFindInteraction": {
      "abstract": [
        {
          "text": "An interaction that provides text finding and replacing operations using a system find panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFindInteraction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFindInteraction"
        }
      ],
      "role": "symbol",
      "title": "UIFindInteraction",
      "type": "topic",
      "url": "/documentation/uikit/uifindinteraction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFindInteractionDelegate": {
      "abstract": [
        {
          "text": "A delegate object that provides a session object to manage the search state for a find interaction and receives notifications of search session lifetimes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFindInteractionDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindInteractionDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFindInteractionDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIFindInteractionDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uifindinteractiondelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFindSession": {
      "abstract": [
        {
          "text": "An abstract base class that manages the state, presentation, and behavior for a search that the find interaction initiates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFindSession"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFindSession"
        }
      ],
      "role": "symbol",
      "title": "UIFindSession",
      "type": "topic",
      "url": "/documentation/uikit/uifindsession"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFindSession/SearchResultDisplayStyle-swift.enum": {
      "abstract": [
        {
          "text": "Constants that describe the results summary the find panel UI includes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SearchResultDisplayStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindSession/SearchResultDisplayStyle-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SearchResultDisplayStyle"
        }
      ],
      "role": "symbol",
      "title": "UIFindSession.SearchResultDisplayStyle",
      "type": "topic",
      "url": "/documentation/uikit/uifindsession/searchresultdisplaystyle-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFindSession/allowsReplacement": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to allow replacing the result the find panel is highlighting.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsReplacement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindSession/allowsReplacement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsReplacement"
        }
      ],
      "role": "symbol",
      "title": "allowsReplacement",
      "type": "topic",
      "url": "/documentation/uikit/uifindsession/allowsreplacement"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFindSession/allowsReplacementForCurrentlyHighlightedResult": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to allow replacing the result the find panel is highlighting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "allowsReplacementForCurrentlyHighlightedResult"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindSession/allowsReplacementForCurrentlyHighlightedResult",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "allowsReplacementForCurrentlyHighlightedResult"
        }
      ],
      "role": "symbol",
      "title": "allowsReplacementForCurrentlyHighlightedResult",
      "type": "topic",
      "url": "/documentation/uikit/uifindsession/allowsreplacementforcurrentlyhighlightedresult"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFindSession/highlightNextResult(in:)": {
      "abstract": [
        {
          "text": "Updates the highlighted result to the next or previous match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "highlightNextResult"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UITextStorageDirection",
          "text": "UITextStorageDirection"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindSession/highlightNextResult(in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "highlightNextResultInDirection:"
        }
      ],
      "role": "symbol",
      "title": "highlightNextResult(in:)",
      "type": "topic",
      "url": "/documentation/uikit/uifindsession/highlightnextresult(in:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFindSession/highlightedResultIndex": {
      "abstract": [
        {
          "text": "The index of the result the find panel highlights.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "highlightedResultIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindSession/highlightedResultIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "highlightedResultIndex"
        }
      ],
      "role": "symbol",
      "title": "highlightedResultIndex",
      "type": "topic",
      "url": "/documentation/uikit/uifindsession/highlightedresultindex"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFindSession/invalidateFoundResults()": {
      "abstract": [
        {
          "text": "Invalidates the found ranges and updates the system find panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidateFoundResults"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindSession/invalidateFoundResults()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "invalidateFoundResults"
        }
      ],
      "role": "symbol",
      "title": "invalidateFoundResults()",
      "type": "topic",
      "url": "/documentation/uikit/uifindsession/invalidatefoundresults()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFindSession/performSearch(query:options:)": {
      "abstract": [
        {
          "text": "Initiates a search for the query string you provide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "performSearch"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "query"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextSearchOptions",
          "text": "UITextSearchOptions"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindSession/performSearch(query:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "performSearchWithQuery:options:"
        }
      ],
      "role": "symbol",
      "title": "performSearch(query:options:)",
      "type": "topic",
      "url": "/documentation/uikit/uifindsession/performsearch(query:options:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFindSession/performSingleReplacement(query:replacementString:options:)": {
      "abstract": [
        {
          "text": "Replaces a single instance of the query string with the replacement string you provide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "performSingleReplacement"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "query"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "replacementString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextSearchOptions",
          "text": "UITextSearchOptions"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindSession/performSingleReplacement(query:replacementString:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "performSingleReplacementWithSearchQuery:replacementString:options:"
        }
      ],
      "role": "symbol",
      "title": "performSingleReplacement(query:replacementString:options:)",
      "type": "topic",
      "url": "/documentation/uikit/uifindsession/performsinglereplacement(query:replacementstring:options:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFindSession/replaceAll(searchQuery:replacementString:options:)": {
      "abstract": [
        {
          "text": "Replaces all matching instances of the query string with the replacement string you provide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "replaceAll"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "searchQuery"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "replacementString"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextSearchOptions",
          "text": "UITextSearchOptions"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindSession/replaceAll(searchQuery:replacementString:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "replaceAllInstancesOfSearchQuery:withReplacementString:options:"
        }
      ],
      "role": "symbol",
      "title": "replaceAll(searchQuery:replacementString:options:)",
      "type": "topic",
      "url": "/documentation/uikit/uifindsession/replaceall(searchquery:replacementstring:options:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFindSession/resultCount": {
      "abstract": [
        {
          "text": "The total number of results the search matches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "resultCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindSession/resultCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resultCount"
        }
      ],
      "role": "symbol",
      "title": "resultCount",
      "type": "topic",
      "url": "/documentation/uikit/uifindsession/resultcount"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFindSession/searchResultDisplayStyle-swift.property": {
      "abstract": [
        {
          "text": "The information the find panel includes in the summary of found results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchResultDisplayStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIFindSession",
          "text": "UIFindSession"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIFindSessionSearchResultDisplayStyle",
          "text": "SearchResultDisplayStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindSession/searchResultDisplayStyle-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "searchResultDisplayStyle"
        }
      ],
      "role": "symbol",
      "title": "searchResultDisplayStyle",
      "type": "topic",
      "url": "/documentation/uikit/uifindsession/searchresultdisplaystyle-swift.property"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFindSession/supportsReplacement": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to allow replacing find panel results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsReplacement"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindSession/supportsReplacement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsReplacement"
        }
      ],
      "role": "symbol",
      "title": "supportsReplacement",
      "type": "topic",
      "url": "/documentation/uikit/uifindsession/supportsreplacement"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchFoundTextStyle": {
      "abstract": [
        {
          "text": "Constants that describe the style a find session uses to decorate the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextSearchFoundTextStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchFoundTextStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextSearchFoundTextStyle"
        }
      ],
      "role": "symbol",
      "title": "UITextSearchFoundTextStyle",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchfoundtextstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions": {
      "abstract": [
        {
          "text": "An object containing the configurable options for a text search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextSearchOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextSearchOptions"
        }
      ],
      "role": "symbol",
      "title": "UITextSearchOptions",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum": {
      "abstract": [
        {
          "text": "Constants that describe the method to use when searching text for words that match a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WordMatchMethod"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WordMatchMethod"
        }
      ],
      "role": "symbol",
      "title": "UITextSearchOptions.WordMatchMethod",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchoptions/wordmatchmethod-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearching-3wkjv": {
      "abstract": [
        {
          "text": "The methods you use on a find session’s searchable objects to perform search operations and decorate the found text results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextSearching"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearching-3wkjv",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextSearching"
        }
      ],
      "role": "symbol",
      "title": "UITextSearching",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearching-3wkjv"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq": {
      "abstract": [
        {
          "text": "The methods you use on a find session’s searchable objects to perform search operations and decorate the found text results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextSearching"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextSearching",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearching-53wjq"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchingFindSession": {
      "abstract": [
        {
          "text": "A find session object that wraps a searchable object implementing the text-searching protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextSearchingFindSession"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchingFindSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextSearchingFindSession"
        }
      ],
      "role": "symbol",
      "title": "UITextSearchingFindSession",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchingfindsession"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchingFindSession/searchableObject": {
      "abstract": [
        {
          "text": "The object to search, responsible for performing the search operation and decorating the results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchableObject"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "text": "__UITextSearching"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchingFindSession/searchableObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "searchableObject"
        }
      ],
      "role": "symbol",
      "title": "searchableObject",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchingfindsession/searchableobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchingFindSession"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Find-and-replace",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIFindInteraction",
        "doc://com.apple.uikit/documentation/UIKit/UIFindInteractionDelegate",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchingFindSession",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearching-3wkjv",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchFoundTextStyle",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum",
        "doc://com.apple.uikit/documentation/UIKit/UIFindSession/SearchResultDisplayStyle-swift.enum"
      ],
      "title": "Find and replace"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-session-information",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIFindSession/resultCount",
        "doc://com.apple.uikit/documentation/UIKit/UIFindSession/highlightedResultIndex",
        "doc://com.apple.uikit/documentation/UIKit/UIFindSession/supportsReplacement",
        "doc://com.apple.uikit/documentation/UIKit/UIFindSession/allowsReplacementForCurrentlyHighlightedResult",
        "doc://com.apple.uikit/documentation/UIKit/UIFindSession/searchResultDisplayStyle-swift.property",
        "doc://com.apple.uikit/documentation/UIKit/UIFindSession/SearchResultDisplayStyle-swift.enum"
      ],
      "title": "Getting session information"
    },
    {
      "anchor": "Managing-session-interactions",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIFindSession/performSearch(query:options:)",
        "doc://com.apple.uikit/documentation/UIKit/UIFindSession/performSingleReplacement(query:replacementString:options:)",
        "doc://com.apple.uikit/documentation/UIKit/UIFindSession/replaceAll(searchQuery:replacementString:options:)",
        "doc://com.apple.uikit/documentation/UIKit/UIFindSession/highlightNextResult(in:)",
        "doc://com.apple.uikit/documentation/UIKit/UIFindSession/invalidateFoundResults()"
      ],
      "title": "Managing session interactions"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIFindSession/allowsReplacement"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIFindSession"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-session-information",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIFindSession/resultCount",
                "doc://com.apple.uikit/documentation/UIKit/UIFindSession/highlightedResultIndex",
                "doc://com.apple.uikit/documentation/UIKit/UIFindSession/supportsReplacement",
                "doc://com.apple.uikit/documentation/UIKit/UIFindSession/allowsReplacementForCurrentlyHighlightedResult",
                "doc://com.apple.uikit/documentation/UIKit/UIFindSession/searchResultDisplayStyle-swift.property",
                "doc://com.apple.uikit/documentation/UIKit/UIFindSession/SearchResultDisplayStyle-swift.enum"
              ],
              "title": "Getting session information"
            },
            {
              "anchor": "Managing-session-interactions",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIFindSession/performSearch(query:options:)",
                "doc://com.apple.uikit/documentation/UIKit/UIFindSession/performSingleReplacement(query:replacementString:options:)",
                "doc://com.apple.uikit/documentation/UIKit/UIFindSession/replaceAll(searchQuery:replacementString:options:)",
                "doc://com.apple.uikit/documentation/UIKit/UIFindSession/highlightNextResult(in:)",
                "doc://com.apple.uikit/documentation/UIKit/UIFindSession/invalidateFoundResults()"
              ],
              "title": "Managing session interactions"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIFindSession/allowsReplacement"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextSearchingFindSession"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Find-and-replace",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIFindInteraction",
                "doc://com.apple.uikit/documentation/UIKit/UIFindInteractionDelegate",
                "doc://com.apple.uikit/documentation/UIKit/UITextSearchingFindSession",
                "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq",
                "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions",
                "doc://com.apple.uikit/documentation/UIKit/UITextSearchFoundTextStyle",
                "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum",
                "doc://com.apple.uikit/documentation/UIKit/UIFindSession/SearchResultDisplayStyle-swift.enum"
              ],
              "title": "Find and replace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIFindSession"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1highlightedResultIndex/title",
          "value": "highlightedResultIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1highlightedResultIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "highlightedResultIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1supportsReplacement/title",
          "value": "supportsReplacement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1supportsReplacement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportsReplacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindInteractionDelegate/title",
          "value": "UIFindInteractionDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindInteractionDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindInteractionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindInteractionDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindInteractionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1SearchResultDisplayStyle-swift.enum/title",
          "value": "UIFindSessionSearchResultDisplayStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1SearchResultDisplayStyle-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindSessionSearchResultDisplayStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1SearchResultDisplayStyle-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindSessionSearchResultDisplayStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchingFindSession~1searchableObject/title",
          "value": "searchableObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchingFindSession~1searchableObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "searchableObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1replaceAll(searchQuery:replacementString:options:)/title",
          "value": "replaceAllInstancesOfSearchQuery:withReplacementString:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1replaceAll(searchQuery:replacementString:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "replaceAllInstancesOfSearchQuery:withReplacementString:options:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1performSingleReplacement(query:replacementString:options:)/title",
          "value": "performSingleReplacementWithSearchQuery:replacementString:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1performSingleReplacement(query:replacementString:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "performSingleReplacementWithSearchQuery:replacementString:options:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession/title",
          "value": "UIFindSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1invalidateFoundResults()/title",
          "value": "invalidateFoundResults"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1invalidateFoundResults()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "invalidateFoundResults"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1allowsReplacement/title",
          "value": "allowsReplacement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1allowsReplacement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsReplacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1allowsReplacementForCurrentlyHighlightedResult/title",
          "value": "allowsReplacementForCurrentlyHighlightedResult"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1allowsReplacementForCurrentlyHighlightedResult/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "allowsReplacementForCurrentlyHighlightedResult"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1highlightNextResult(in:)/title",
          "value": "highlightNextResultInDirection:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1highlightNextResult(in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "highlightNextResultInDirection:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions/title",
          "value": "UITextSearchOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1searchResultDisplayStyle-swift.property/title",
          "value": "searchResultDisplayStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1searchResultDisplayStyle-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "searchResultDisplayStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1performSearch(query:options:)/title",
          "value": "performSearchWithQuery:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1performSearch(query:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "performSearchWithQuery:options:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchFoundTextStyle/title",
          "value": "UITextSearchFoundTextStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchFoundTextStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchFoundTextStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchFoundTextStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchFoundTextStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchingFindSession/title",
          "value": "UITextSearchingFindSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchingFindSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchingFindSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchingFindSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchingFindSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions~1WordMatchMethod-swift.enum/title",
          "value": "UITextSearchMatchMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions~1WordMatchMethod-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchMatchMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions~1WordMatchMethod-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchMatchMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindInteraction/title",
          "value": "UIFindInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1resultCount/title",
          "value": "resultCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1resultCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "resultCount"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uifindsession"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uifindsession"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
