{
  "abstract": [
    {
      "text": "A delegate object that provides a session object to manage the search state for a find interaction and receives notifications of search session lifetimes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIFindInteractionDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UIFindInteractionDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIFindInteractionDelegate"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIFindInteractionDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "UIFindInteractionDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIFindInteractionDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFindInteraction": {
      "abstract": [
        {
          "text": "An interaction that provides text finding and replacing operations using a system find panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFindInteraction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFindInteraction"
        }
      ],
      "role": "symbol",
      "title": "UIFindInteraction",
      "type": "topic",
      "url": "/documentation/uikit/uifindinteraction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFindInteractionDelegate": {
      "abstract": [
        {
          "text": "A delegate object that provides a session object to manage the search state for a find interaction and receives notifications of search session lifetimes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFindInteractionDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindInteractionDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFindInteractionDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIFindInteractionDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uifindinteractiondelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFindInteractionDelegate/findInteraction(_:didBegin:)": {
      "abstract": [
        {
          "text": "Informs the delegate when the interaction is about to present the find panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "findInteraction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIFindInteraction",
          "text": "UIFindInteraction"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didBegin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIFindSession",
          "text": "UIFindSession"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindInteractionDelegate/findInteraction(_:didBegin:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "findInteraction:didBeginFindSession:"
        }
      ],
      "role": "symbol",
      "title": "findInteraction(_:didBegin:)",
      "type": "topic",
      "url": "/documentation/uikit/uifindinteractiondelegate/findinteraction(_:didbegin:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFindInteractionDelegate/findInteraction(_:didEnd:)": {
      "abstract": [
        {
          "text": "Informs the delegate when the interaction is about to dismiss the find panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "findInteraction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIFindInteraction",
          "text": "UIFindInteraction"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didEnd"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIFindSession",
          "text": "UIFindSession"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindInteractionDelegate/findInteraction(_:didEnd:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "findInteraction:didEndFindSession:"
        }
      ],
      "role": "symbol",
      "title": "findInteraction(_:didEnd:)",
      "type": "topic",
      "url": "/documentation/uikit/uifindinteractiondelegate/findinteraction(_:didend:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFindInteractionDelegate/findInteraction(_:sessionFor:)": {
      "abstract": [
        {
          "text": "Provides the object for managing the state, presentation, and behavior of the search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "findInteraction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIFindInteraction",
          "text": "UIFindInteraction"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "sessionFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIFindSession",
          "text": "UIFindSession"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindInteractionDelegate/findInteraction(_:sessionFor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "findInteraction:sessionForView:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "findInteraction(_:sessionFor:)",
      "type": "topic",
      "url": "/documentation/uikit/uifindinteractiondelegate/findinteraction(_:sessionfor:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFindSession": {
      "abstract": [
        {
          "text": "An abstract base class that manages the state, presentation, and behavior for a search that the find interaction initiates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFindSession"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFindSession"
        }
      ],
      "role": "symbol",
      "title": "UIFindSession",
      "type": "topic",
      "url": "/documentation/uikit/uifindsession"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFindSession/SearchResultDisplayStyle-swift.enum": {
      "abstract": [
        {
          "text": "Constants that describe the results summary the find panel UI includes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SearchResultDisplayStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindSession/SearchResultDisplayStyle-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SearchResultDisplayStyle"
        }
      ],
      "role": "symbol",
      "title": "UIFindSession.SearchResultDisplayStyle",
      "type": "topic",
      "url": "/documentation/uikit/uifindsession/searchresultdisplaystyle-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchFoundTextStyle": {
      "abstract": [
        {
          "text": "Constants that describe the style a find session uses to decorate the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextSearchFoundTextStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchFoundTextStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextSearchFoundTextStyle"
        }
      ],
      "role": "symbol",
      "title": "UITextSearchFoundTextStyle",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchfoundtextstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions": {
      "abstract": [
        {
          "text": "An object containing the configurable options for a text search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextSearchOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextSearchOptions"
        }
      ],
      "role": "symbol",
      "title": "UITextSearchOptions",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum": {
      "abstract": [
        {
          "text": "Constants that describe the method to use when searching text for words that match a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WordMatchMethod"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WordMatchMethod"
        }
      ],
      "role": "symbol",
      "title": "UITextSearchOptions.WordMatchMethod",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchoptions/wordmatchmethod-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearching-3wkjv": {
      "abstract": [
        {
          "text": "The methods you use on a find session’s searchable objects to perform search operations and decorate the found text results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextSearching"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearching-3wkjv",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextSearching"
        }
      ],
      "role": "symbol",
      "title": "UITextSearching",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearching-3wkjv"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq": {
      "abstract": [
        {
          "text": "The methods you use on a find session’s searchable objects to perform search operations and decorate the found text results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextSearching"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextSearching",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearching-53wjq"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchingFindSession": {
      "abstract": [
        {
          "text": "A find session object that wraps a searchable object implementing the text-searching protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextSearchingFindSession"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchingFindSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextSearchingFindSession"
        }
      ],
      "role": "symbol",
      "title": "UITextSearchingFindSession",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchingfindsession"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextView": {
      "abstract": [
        {
          "text": "A scrollable, multiline text region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextView"
        }
      ],
      "role": "symbol",
      "title": "UITextView",
      "type": "topic",
      "url": "/documentation/uikit/uitextview"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextView"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Find-and-replace",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIFindInteraction",
        "doc://com.apple.uikit/documentation/UIKit/UIFindSession",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchingFindSession",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearching-3wkjv",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchFoundTextStyle",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum",
        "doc://com.apple.uikit/documentation/UIKit/UIFindSession/SearchResultDisplayStyle-swift.enum"
      ],
      "title": "Find and replace"
    }
  ],
  "topicSections": [
    {
      "anchor": "Beginning-the-search",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIFindInteractionDelegate/findInteraction(_:sessionFor:)"
      ],
      "title": "Beginning the search"
    },
    {
      "anchor": "Decorating-the-searched-content",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIFindInteractionDelegate/findInteraction(_:didBegin:)",
        "doc://com.apple.uikit/documentation/UIKit/UIFindInteractionDelegate/findInteraction(_:didEnd:)"
      ],
      "title": "Decorating the searched content"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIFindInteractionDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindInteractionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindInteractionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Beginning-the-search",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIFindInteractionDelegate/findInteraction(_:sessionFor:)"
              ],
              "title": "Beginning the search"
            },
            {
              "anchor": "Decorating-the-searched-content",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIFindInteractionDelegate/findInteraction(_:didBegin:)",
                "doc://com.apple.uikit/documentation/UIKit/UIFindInteractionDelegate/findInteraction(_:didEnd:)"
              ],
              "title": "Decorating the searched content"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextView"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Find-and-replace",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIFindInteraction",
                "doc://com.apple.uikit/documentation/UIKit/UIFindSession",
                "doc://com.apple.uikit/documentation/UIKit/UITextSearchingFindSession",
                "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq",
                "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions",
                "doc://com.apple.uikit/documentation/UIKit/UITextSearchFoundTextStyle",
                "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum",
                "doc://com.apple.uikit/documentation/UIKit/UIFindSession/SearchResultDisplayStyle-swift.enum"
              ],
              "title": "Find and replace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIFindInteractionDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions/title",
          "value": "UITextSearchOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextView/title",
          "value": "UITextView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindInteractionDelegate~1findInteraction(_:sessionFor:)/title",
          "value": "findInteraction:sessionForView:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindInteractionDelegate~1findInteraction(_:sessionFor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "findInteraction:sessionForView:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindInteractionDelegate/title",
          "value": "UIFindInteractionDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindInteractionDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindInteractionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindInteractionDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindInteractionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1SearchResultDisplayStyle-swift.enum/title",
          "value": "UIFindSessionSearchResultDisplayStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1SearchResultDisplayStyle-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindSessionSearchResultDisplayStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1SearchResultDisplayStyle-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindSessionSearchResultDisplayStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindInteractionDelegate~1findInteraction(_:didEnd:)/title",
          "value": "findInteraction:didEndFindSession:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindInteractionDelegate~1findInteraction(_:didEnd:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "findInteraction:didEndFindSession:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindInteractionDelegate~1findInteraction(_:didBegin:)/title",
          "value": "findInteraction:didBeginFindSession:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindInteractionDelegate~1findInteraction(_:didBegin:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "findInteraction:didBeginFindSession:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions~1WordMatchMethod-swift.enum/title",
          "value": "UITextSearchMatchMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions~1WordMatchMethod-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchMatchMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions~1WordMatchMethod-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchMatchMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchingFindSession/title",
          "value": "UITextSearchingFindSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchingFindSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchingFindSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchingFindSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchingFindSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindInteraction/title",
          "value": "UIFindInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchFoundTextStyle/title",
          "value": "UITextSearchFoundTextStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchFoundTextStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchFoundTextStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchFoundTextStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchFoundTextStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession/title",
          "value": "UIFindSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindSession"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uifindinteractiondelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uifindinteractiondelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
