{
  "abstract": [
    {
      "text": "A view controller that manages the interface for selecting a font that the system provides or the user installs.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewController"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIFontPickerViewController",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIFontPickerViewController"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIFontPickerViewController"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "UIFontPickerViewController"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIFontPickerViewController"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to provide the user access to all the fonts on their device. Directly querying ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFont",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " provides only system fonts, but the user may have additional fonts on their device. When the user selects one of these nonsystem fonts in the font picker, the system grants your app access to the font.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The font picker has several customization options collected into a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewController/Configuration-swift.class",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. For example, you can set ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewController/Configuration-swift.class/includeFaces",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/swift/true",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " so that the user can select not only the font but a bold or italic face within that font family. Customize the configuration object first, then pass it as an argument in the font picker’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewController/init(configuration:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "    func showFontPicker(_ sender: Any) {",
            "        let fontConfig = UIFontPickerViewController.Configuration()",
            "        fontConfig.includeFaces = true",
            "        let fontPicker = UIFontPickerViewController(configuration: fontConfig)",
            "        fontPicker.delegate = self",
            "        self.present(fontPicker, animated: true, completion: nil)",
            "    }"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "When your ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewControllerDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " receives ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewControllerDelegate/fontPickerViewControllerDidPickFont(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", retrieve information about the user’s selected font from the font picker’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewController/selectedFontDescriptor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/swift/true": {
      "abstract": [
        {
          "text": "A true value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swift/true",
      "kind": "symbol",
      "role": "symbol",
      "title": "true",
      "type": "topic",
      "url": "/documentation/swift/true"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationProviding": {
      "abstract": [
        {
          "text": "An interface that provides a source for shareable content to fulfill user requests to share current content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIActivityItemsConfigurationProviding"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationProviding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIActivityItemsConfigurationProviding"
        }
      ],
      "role": "symbol",
      "title": "UIActivityItemsConfigurationProviding",
      "type": "topic",
      "url": "/documentation/uikit/uiactivityitemsconfigurationproviding"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAppearance": {
      "abstract": [
        {
          "text": "A collection of methods that gives you access to the appearance proxy for a class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAppearance"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAppearance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAppearance"
        }
      ],
      "role": "symbol",
      "title": "UIAppearance",
      "type": "topic",
      "url": "/documentation/uikit/uiappearance"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAppearanceContainer": {
      "abstract": [
        {
          "text": "A protocol that a class must adopt to allow appearance customization using the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAppearance",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " API.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAppearanceContainer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAppearanceContainer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAppearanceContainer"
        }
      ],
      "role": "symbol",
      "title": "UIAppearanceContainer",
      "type": "topic",
      "url": "/documentation/uikit/uiappearancecontainer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentContainer": {
      "abstract": [
        {
          "text": "A set of methods for adapting the contents of your view controllers to size and trait changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIContentContainer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentContainer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentContainer"
        }
      ],
      "role": "symbol",
      "title": "UIContentContainer",
      "type": "topic",
      "url": "/documentation/uikit/uicontentcontainer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment": {
      "abstract": [
        {
          "text": "A set of methods that define the focus behavior for a branch of the view hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFocusEnvironment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFocusEnvironment"
        }
      ],
      "role": "symbol",
      "title": "UIFocusEnvironment",
      "type": "topic",
      "url": "/documentation/uikit/uifocusenvironment"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFont": {
      "abstract": [
        {
          "text": "An object that provides access to the font’s characteristics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFont"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFont",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFont"
        }
      ],
      "role": "symbol",
      "title": "UIFont",
      "type": "topic",
      "url": "/documentation/uikit/uifont"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewController": {
      "abstract": [
        {
          "text": "A view controller that manages the interface for selecting a font that the system provides or the user installs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFontPickerViewController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFontPickerViewController"
        }
      ],
      "role": "symbol",
      "title": "UIFontPickerViewController",
      "type": "topic",
      "url": "/documentation/uikit/uifontpickerviewcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewController/Configuration-swift.class": {
      "abstract": [
        {
          "text": "The filters and display settings a font picker view controller uses to set up a font picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Configuration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewController/Configuration-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Configuration"
        }
      ],
      "role": "symbol",
      "title": "UIFontPickerViewController.Configuration",
      "type": "topic",
      "url": "/documentation/uikit/uifontpickerviewcontroller/configuration-swift.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewController/Configuration-swift.class/includeFaces": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the font picker should allow the user to select from font faces, or just font families.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "includeFaces"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewController/Configuration-swift.class/includeFaces",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "includeFaces"
        }
      ],
      "role": "symbol",
      "title": "includeFaces",
      "type": "topic",
      "url": "/documentation/uikit/uifontpickerviewcontroller/configuration-swift.class/includefaces"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewController/configuration-swift.property": {
      "abstract": [
        {
          "text": "Settings for fonts the font picker should offer to the user and how to display those fonts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIFontPickerViewController",
          "text": "UIFontPickerViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIFontPickerViewControllerConfiguration",
          "text": "Configuration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewController/configuration-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "configuration"
        }
      ],
      "role": "symbol",
      "title": "configuration",
      "type": "topic",
      "url": "/documentation/uikit/uifontpickerviewcontroller/configuration-swift.property"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewController/delegate": {
      "abstract": [
        {
          "text": "The object that handles messages about the user’s interaction with a font picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIFontPickerViewControllerDelegate",
          "text": "UIFontPickerViewControllerDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewController/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/uikit/uifontpickerviewcontroller/delegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewController/init(configuration:)": {
      "abstract": [
        {
          "text": "Creates a controller for a font picker view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "configuration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIFontPickerViewController",
          "text": "UIFontPickerViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIFontPickerViewControllerConfiguration",
          "text": "Configuration"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewController/init(configuration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithConfiguration:"
        }
      ],
      "role": "symbol",
      "title": "init(configuration:)",
      "type": "topic",
      "url": "/documentation/uikit/uifontpickerviewcontroller/init(configuration:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewController/selectedFontDescriptor": {
      "abstract": [
        {
          "text": "Information about the font family or face selected by the user in the font picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectedFontDescriptor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIFontDescriptor",
          "text": "UIFontDescriptor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewController/selectedFontDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectedFontDescriptor"
        }
      ],
      "role": "symbol",
      "title": "selectedFontDescriptor",
      "type": "topic",
      "url": "/documentation/uikit/uifontpickerviewcontroller/selectedfontdescriptor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewControllerDelegate": {
      "abstract": [
        {
          "text": "A set of optional methods for receiving messages about the user’s interaction with the font picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFontPickerViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFontPickerViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIFontPickerViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uifontpickerviewcontrollerdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewControllerDelegate/fontPickerViewControllerDidPickFont(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user has selected a font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fontPickerViewControllerDidPickFont"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIFontPickerViewController",
          "text": "UIFontPickerViewController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewControllerDelegate/fontPickerViewControllerDidPickFont(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fontPickerViewControllerDidPickFont:"
        }
      ],
      "role": "symbol",
      "title": "fontPickerViewControllerDidPickFont(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uifontpickerviewcontrollerdelegate/fontpickerviewcontrollerdidpickfont(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteConfigurationSupporting": {
      "abstract": [
        {
          "text": "The interface that determines whether a responder object supports paste configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPasteConfigurationSupporting"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteConfigurationSupporting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPasteConfigurationSupporting"
        }
      ],
      "role": "symbol",
      "title": "UIPasteConfigurationSupporting",
      "type": "topic",
      "url": "/documentation/uikit/uipasteconfigurationsupporting"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions": {
      "abstract": [
        {
          "text": "A set of standard methods that apps can adopt to support editing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIResponderStandardEditActions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIResponderStandardEditActions"
        }
      ],
      "role": "symbol",
      "title": "UIResponderStandardEditActions",
      "type": "topic",
      "url": "/documentation/uikit/uiresponderstandardeditactions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIStateRestoring": {
      "abstract": [
        {
          "text": "Methods for adding objects to your state restoration archives.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIStateRestoring"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIStateRestoring",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIStateRestoring"
        }
      ],
      "role": "symbol",
      "title": "UIStateRestoring",
      "type": "topic",
      "url": "/documentation/uikit/uistaterestoring"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94": {
      "abstract": [
        {
          "text": "A type that calls your code in reaction to changes in the trait environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITraitChangeObservable"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITraitChangeObservable"
        }
      ],
      "role": "symbol",
      "title": "UITraitChangeObservable",
      "type": "topic",
      "url": "/documentation/uikit/uitraitchangeobservable-67e94"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitEnvironment": {
      "abstract": [
        {
          "text": "A set of methods that makes the iOS interface environment available to your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITraitEnvironment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitEnvironment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITraitEnvironment"
        }
      ],
      "role": "symbol",
      "title": "UITraitEnvironment",
      "type": "topic",
      "url": "/documentation/uikit/uitraitenvironment"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserActivityRestoring": {
      "abstract": [
        {
          "text": "The protocol you adopt to restore an object’s state from a user activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIUserActivityRestoring"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserActivityRestoring",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserActivityRestoring"
        }
      ],
      "role": "symbol",
      "title": "UIUserActivityRestoring",
      "type": "topic",
      "url": "/documentation/uikit/uiuseractivityrestoring"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController": {
      "abstract": [
        {
          "text": "An object that manages a view hierarchy for your UIKit app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewController"
        }
      ],
      "role": "symbol",
      "title": "UIViewController",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSExtensionRequestHandling": {
      "abstract": [
        {
          "text": "The interface an app extension uses to respond to a request from a host app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSExtensionRequestHandling"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSExtensionRequestHandling",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSExtensionRequestHandling",
      "type": "topic",
      "url": "/documentation/foundation/nsextensionrequesthandling"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSTouchBarProvider": {
      "abstract": [
        {
          "text": "A protocol that an object adopts to create a bar object in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTouchBarProvider"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSTouchBarProvider",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTouchBarProvider",
      "type": "topic",
      "url": "/documentation/AppKit/NSTouchBarProvider"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIViewController"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSExtensionRequestHandling",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSTouchBarProvider",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.apple.uikit/documentation/UIKit/UIActivityItemsConfigurationProviding",
        "doc://com.apple.uikit/documentation/UIKit/UIAppearanceContainer",
        "doc://com.apple.uikit/documentation/UIKit/UIContentContainer",
        "doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteConfigurationSupporting",
        "doc://com.apple.uikit/documentation/UIKit/UIResponderStandardEditActions",
        "doc://com.apple.uikit/documentation/UIKit/UIStateRestoring",
        "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94",
        "doc://com.apple.uikit/documentation/UIKit/UITraitEnvironment",
        "doc://com.apple.uikit/documentation/UIKit/UIUserActivityRestoring"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Font-picker",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewControllerDelegate",
        "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewController/Configuration-swift.class"
      ],
      "title": "Font picker"
    }
  ],
  "topicSections": [
    {
      "anchor": "Configuring-a-font-picker-to-display-in-iOS",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewController/init(configuration:)",
        "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewController/configuration-swift.property",
        "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewController/Configuration-swift.class"
      ],
      "title": "Configuring a font picker to display in iOS"
    },
    {
      "anchor": "Responding-to-font-picker-interactions",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewController/delegate",
        "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewControllerDelegate",
        "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewController/selectedFontDescriptor"
      ],
      "title": "Responding to font picker interactions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIFontPickerViewController"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFontPickerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFontPickerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Configuring-a-font-picker-to-display-in-iOS",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewController/init(configuration:)",
                "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewController/configuration-swift.property",
                "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewController/Configuration-swift.class"
              ],
              "title": "Configuring a font picker to display in iOS"
            },
            {
              "anchor": "Responding-to-font-picker-interactions",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewController/delegate",
                "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewControllerDelegate",
                "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewController/selectedFontDescriptor"
              ],
              "title": "Responding to font picker interactions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIViewController"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Font-picker",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewControllerDelegate",
                "doc://com.apple.uikit/documentation/UIKit/UIFontPickerViewController/Configuration-swift.class"
              ],
              "title": "Font picker"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIFontPickerViewController"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UIViewController",
                    "text": "UIViewController"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontPickerViewController~1selectedFontDescriptor/title",
          "value": "selectedFontDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontPickerViewController~1selectedFontDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "selectedFontDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserActivityRestoring/title",
          "value": "UIUserActivityRestoring"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserActivityRestoring/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserActivityRestoring"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserActivityRestoring/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserActivityRestoring"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontPickerViewController~1configuration-swift.property/title",
          "value": "configuration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontPickerViewController~1configuration-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontPickerViewController~1init(configuration:)/title",
          "value": "initWithConfiguration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontPickerViewController~1init(configuration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithConfiguration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontPickerViewControllerDelegate~1fontPickerViewControllerDidPickFont(_:)/title",
          "value": "fontPickerViewControllerDidPickFont:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontPickerViewControllerDelegate~1fontPickerViewControllerDidPickFont(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "fontPickerViewControllerDidPickFont:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStateRestoring/title",
          "value": "UIStateRestoring"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStateRestoring/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIStateRestoring"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStateRestoring/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIStateRestoring"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitEnvironment/title",
          "value": "UITraitEnvironment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitEnvironment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITraitEnvironment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitEnvironment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITraitEnvironment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController/title",
          "value": "UIViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSTouchBarProvider/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSTouchBarProvider"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentContainer/title",
          "value": "UIContentContainer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentContainer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentContainer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFont/title",
          "value": "UIFont"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFont/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFont"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFont/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFont"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAppearanceContainer/title",
          "value": "UIAppearanceContainer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAppearanceContainer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAppearanceContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAppearanceContainer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAppearanceContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusEnvironment/title",
          "value": "UIFocusEnvironment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusEnvironment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFocusEnvironment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusEnvironment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFocusEnvironment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontPickerViewController~1Configuration-swift.class/title",
          "value": "UIFontPickerViewControllerConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontPickerViewController~1Configuration-swift.class/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFontPickerViewControllerConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontPickerViewController~1Configuration-swift.class/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFontPickerViewControllerConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfigurationProviding/title",
          "value": "UIActivityItemsConfigurationProviding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfigurationProviding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityItemsConfigurationProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActivityItemsConfigurationProviding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActivityItemsConfigurationProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontPickerViewController~1Configuration-swift.class~1includeFaces/title",
          "value": "includeFaces"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontPickerViewController~1Configuration-swift.class~1includeFaces/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "includeFaces"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAppearance/title",
          "value": "UIAppearance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAppearance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAppearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAppearance/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAppearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponderStandardEditActions/title",
          "value": "UIResponderStandardEditActions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponderStandardEditActions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIResponderStandardEditActions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIResponderStandardEditActions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIResponderStandardEditActions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteConfigurationSupporting/title",
          "value": "UIPasteConfigurationSupporting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteConfigurationSupporting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteConfigurationSupporting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteConfigurationSupporting/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteConfigurationSupporting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontPickerViewControllerDelegate/title",
          "value": "UIFontPickerViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontPickerViewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFontPickerViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontPickerViewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFontPickerViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontPickerViewController~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontPickerViewController~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontPickerViewController/title",
          "value": "UIFontPickerViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontPickerViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFontPickerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontPickerViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFontPickerViewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uifontpickerviewcontroller"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uifontpickerviewcontroller"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
