{
  "abstract": [
    {
      "text": "A utility object for obtaining custom fonts that scale to support Dynamic Type.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIFontMetrics"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIFontMetrics",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIFontMetrics"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIFontMetrics"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "UIFontMetrics"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIFontMetrics"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.uikit/documentation/UIKit/scaling-fonts-automatically"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFontMetrics",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object to support scalable custom fonts in your app. You create a font metrics object that specifies the font style—for example, body or title—that you want to use in your app. You then pass your custom font to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFontMetrics/scaledFont(for:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method (or one of the other methods of this class) to obtain a font object that is based on your custom font, has the appropriate style information, and automatically scales to match the current Dynamic Type settings.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFont": {
      "abstract": [
        {
          "text": "An object that provides access to the font’s characteristics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFont"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFont",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFont"
        }
      ],
      "role": "symbol",
      "title": "UIFont",
      "type": "topic",
      "url": "/documentation/uikit/uifont"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFont/TextStyle": {
      "abstract": [
        {
          "text": "Constants that describe the preferred styles for fonts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TextStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFont/TextStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TextStyle"
        }
      ],
      "role": "symbol",
      "title": "UIFont.TextStyle",
      "type": "topic",
      "url": "/documentation/uikit/uifont/textstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFontDescriptor": {
      "abstract": [
        {
          "text": "A collection of attributes that describes a font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFontDescriptor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFontDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFontDescriptor"
        }
      ],
      "role": "symbol",
      "title": "UIFontDescriptor",
      "type": "topic",
      "url": "/documentation/uikit/uifontdescriptor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFontDescriptor/SymbolicTraits-swift.struct": {
      "abstract": [
        {
          "text": "Constants that describe the stylistic aspects of a font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFontDescriptor/SymbolicTraits-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SymbolicTraits"
        }
      ],
      "role": "symbol",
      "title": "UIFontDescriptor.SymbolicTraits",
      "type": "topic",
      "url": "/documentation/uikit/uifontdescriptor/symbolictraits-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFontMetrics": {
      "abstract": [
        {
          "text": "A utility object for obtaining custom fonts that scale to support Dynamic Type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFontMetrics"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFontMetrics",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFontMetrics"
        }
      ],
      "role": "symbol",
      "title": "UIFontMetrics",
      "type": "topic",
      "url": "/documentation/uikit/uifontmetrics"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFontMetrics/default": {
      "abstract": [
        {
          "text": "The default font metrics object for content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIFontMetrics",
          "text": "UIFontMetrics"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFontMetrics/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultMetrics"
        }
      ],
      "role": "symbol",
      "title": "default",
      "type": "topic",
      "url": "/documentation/uikit/uifontmetrics/default"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFontMetrics/init(forTextStyle:)": {
      "abstract": [
        {
          "text": "Creates a font metrics object for the specified text style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forTextStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIFont",
          "text": "UIFont"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIFontTextStyle",
          "text": "TextStyle"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFontMetrics/init(forTextStyle:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initForTextStyle:"
        }
      ],
      "role": "symbol",
      "title": "init(forTextStyle:)",
      "type": "topic",
      "url": "/documentation/uikit/uifontmetrics/init(fortextstyle:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFontMetrics/metricsForTextStyle:": {
      "abstract": [
        {
          "text": "Creates and returns a font metrics object for the specified text style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "metricsForTextStyle:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFontMetrics/metricsForTextStyle:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "metricsForTextStyle:"
        }
      ],
      "role": "symbol",
      "title": "metricsForTextStyle:",
      "type": "topic",
      "url": "/documentation/uikit/uifontmetrics/metricsfortextstyle:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFontMetrics/scaledFont(for:)": {
      "abstract": [
        {
          "text": "Returns a version of the specified font that adopts the current font metrics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaledFont"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIFont",
          "text": "UIFont"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIFont",
          "text": "UIFont"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFontMetrics/scaledFont(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scaledFontForFont:"
        }
      ],
      "role": "symbol",
      "title": "scaledFont(for:)",
      "type": "topic",
      "url": "/documentation/uikit/uifontmetrics/scaledfont(for:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFontMetrics/scaledFont(for:compatibleWith:)": {
      "abstract": [
        {
          "text": "Returns a version of the specified font that adopts the current font metrics and supports the specified traits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaledFont"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIFont",
          "text": "UIFont"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "compatibleWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITraitCollection",
          "text": "UITraitCollection"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIFont",
          "text": "UIFont"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFontMetrics/scaledFont(for:compatibleWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scaledFontForFont:compatibleWithTraitCollection:"
        }
      ],
      "role": "symbol",
      "title": "scaledFont(for:compatibleWith:)",
      "type": "topic",
      "url": "/documentation/uikit/uifontmetrics/scaledfont(for:compatiblewith:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFontMetrics/scaledFont(for:maximumPointSize:)": {
      "abstract": [
        {
          "text": "Returns a version of the specified font that adopts the current font metrics and is constrained to the specified maximum size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaledFont"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIFont",
          "text": "UIFont"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "maximumPointSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIFont",
          "text": "UIFont"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFontMetrics/scaledFont(for:maximumPointSize:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scaledFontForFont:maximumPointSize:"
        }
      ],
      "role": "symbol",
      "title": "scaledFont(for:maximumPointSize:)",
      "type": "topic",
      "url": "/documentation/uikit/uifontmetrics/scaledfont(for:maximumpointsize:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFontMetrics/scaledFont(for:maximumPointSize:compatibleWith:)": {
      "abstract": [
        {
          "text": "Returns a version of the specified font that adopts the current font metrics and is constrained to the specified traits and size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaledFont"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIFont",
          "text": "UIFont"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "maximumPointSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "compatibleWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITraitCollection",
          "text": "UITraitCollection"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIFont",
          "text": "UIFont"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFontMetrics/scaledFont(for:maximumPointSize:compatibleWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scaledFontForFont:maximumPointSize:compatibleWithTraitCollection:"
        }
      ],
      "role": "symbol",
      "title": "scaledFont(for:maximumPointSize:compatibleWith:)",
      "type": "topic",
      "url": "/documentation/uikit/uifontmetrics/scaledfont(for:maximumpointsize:compatiblewith:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFontMetrics/scaledValue(for:)": {
      "abstract": [
        {
          "text": "Scales an arbitrary layout value based on the current Dynamic Type settings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaledValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFontMetrics/scaledValue(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scaledValueForValue:"
        }
      ],
      "role": "symbol",
      "title": "scaledValue(for:)",
      "type": "topic",
      "url": "/documentation/uikit/uifontmetrics/scaledvalue(for:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFontMetrics/scaledValue(for:compatibleWith:)": {
      "abstract": [
        {
          "text": "Scales an arbitrary layout value based on the current Dynamic Type settings and the specified traits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scaledValue"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "compatibleWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITraitCollection",
          "text": "UITraitCollection"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFontMetrics/scaledValue(for:compatibleWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scaledValueForValue:compatibleWithTraitCollection:"
        }
      ],
      "role": "symbol",
      "title": "scaledValue(for:compatibleWith:)",
      "type": "topic",
      "url": "/documentation/uikit/uifontmetrics/scaledvalue(for:compatiblewith:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/adding-a-custom-font-to-your-app": {
      "abstract": [
        {
          "text": "Add a custom font to your app and use it in your app’s interface.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/adding-a-custom-font-to-your-app",
      "kind": "article",
      "role": "article",
      "title": "Adding a Custom Font to Your App",
      "type": "topic",
      "url": "/documentation/uikit/adding-a-custom-font-to-your-app"
    },
    "doc://com.apple.uikit/documentation/UIKit/scaling-fonts-automatically": {
      "abstract": [
        {
          "text": "Scale text in your interface automatically using Dynamic Type.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/scaling-fonts-automatically",
      "kind": "article",
      "role": "article",
      "title": "Scaling Fonts Automatically",
      "type": "topic",
      "url": "/documentation/uikit/scaling-fonts-automatically"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Fonts",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/scaling-fonts-automatically",
        "doc://com.apple.uikit/documentation/UIKit/adding-a-custom-font-to-your-app",
        "doc://com.apple.uikit/documentation/UIKit/UIFont",
        "doc://com.apple.uikit/documentation/UIKit/UIFontDescriptor",
        "doc://com.apple.uikit/documentation/UIKit/UIFontDescriptor/SymbolicTraits-swift.struct"
      ],
      "title": "Fonts"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-Font-Metrics-Object",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIFontMetrics/init(forTextStyle:)",
        "doc://com.apple.uikit/documentation/UIKit/UIFontMetrics/default",
        "doc://com.apple.uikit/documentation/UIKit/UIFont/TextStyle"
      ],
      "title": "Creating a Font Metrics Object"
    },
    {
      "anchor": "Creating-Scaled-Fonts",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/scaling-fonts-automatically",
        "doc://com.apple.uikit/documentation/UIKit/UIFontMetrics/scaledFont(for:)",
        "doc://com.apple.uikit/documentation/UIKit/UIFontMetrics/scaledFont(for:compatibleWith:)",
        "doc://com.apple.uikit/documentation/UIKit/UIFontMetrics/scaledFont(for:maximumPointSize:)",
        "doc://com.apple.uikit/documentation/UIKit/UIFontMetrics/scaledFont(for:maximumPointSize:compatibleWith:)"
      ],
      "title": "Creating Scaled Fonts"
    },
    {
      "anchor": "Scaling-Layout-Values",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIFontMetrics/scaledValue(for:)",
        "doc://com.apple.uikit/documentation/UIKit/UIFontMetrics/scaledValue(for:compatibleWith:)"
      ],
      "title": "Scaling Layout Values"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIFontMetrics"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFontMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFontMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-Font-Metrics-Object",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIFontMetrics/init(forTextStyle:)",
                "doc://com.apple.uikit/documentation/UIKit/UIFontMetrics/metricsForTextStyle:",
                "doc://com.apple.uikit/documentation/UIKit/UIFontMetrics/default",
                "doc://com.apple.uikit/documentation/UIKit/UIFont/TextStyle"
              ],
              "title": "Creating a Font Metrics Object"
            },
            {
              "anchor": "Creating-Scaled-Fonts",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/scaling-fonts-automatically",
                "doc://com.apple.uikit/documentation/UIKit/UIFontMetrics/scaledFont(for:)",
                "doc://com.apple.uikit/documentation/UIKit/UIFontMetrics/scaledFont(for:compatibleWith:)",
                "doc://com.apple.uikit/documentation/UIKit/UIFontMetrics/scaledFont(for:maximumPointSize:)",
                "doc://com.apple.uikit/documentation/UIKit/UIFontMetrics/scaledFont(for:maximumPointSize:compatibleWith:)"
              ],
              "title": "Creating Scaled Fonts"
            },
            {
              "anchor": "Scaling-Layout-Values",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIFontMetrics/scaledValue(for:)",
                "doc://com.apple.uikit/documentation/UIKit/UIFontMetrics/scaledValue(for:compatibleWith:)"
              ],
              "title": "Scaling Layout Values"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Fonts",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/scaling-fonts-automatically",
                "doc://com.apple.uikit/documentation/UIKit/adding-a-custom-font-to-your-app",
                "doc://com.apple.uikit/documentation/UIKit/UIFont",
                "doc://com.apple.uikit/documentation/UIKit/UIFontDescriptor",
                "doc://com.apple.uikit/documentation/UIKit/UIFontDescriptor/SymbolicTraits-swift.struct"
              ],
              "title": "Fonts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIFontMetrics"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFont/title",
          "value": "UIFont"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFont/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFont"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFont/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFont"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontMetrics~1default/title",
          "value": "defaultMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontMetrics~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "defaultMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontMetrics~1scaledValue(for:)/title",
          "value": "scaledValueForValue:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontMetrics~1scaledValue(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scaledValueForValue:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontMetrics~1scaledFont(for:compatibleWith:)/title",
          "value": "scaledFontForFont:compatibleWithTraitCollection:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontMetrics~1scaledFont(for:compatibleWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scaledFontForFont:compatibleWithTraitCollection:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontMetrics~1scaledFont(for:maximumPointSize:compatibleWith:)/title",
          "value": "scaledFontForFont:maximumPointSize:compatibleWithTraitCollection:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontMetrics~1scaledFont(for:maximumPointSize:compatibleWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scaledFontForFont:maximumPointSize:compatibleWithTraitCollection:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontMetrics~1scaledFont(for:)/title",
          "value": "scaledFontForFont:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontMetrics~1scaledFont(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scaledFontForFont:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontMetrics~1init(forTextStyle:)/title",
          "value": "initForTextStyle:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontMetrics~1init(forTextStyle:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initForTextStyle:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFont~1TextStyle/title",
          "value": "UIFontTextStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFont~1TextStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFontTextStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFont~1TextStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFontTextStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontMetrics/title",
          "value": "UIFontMetrics"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontMetrics/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFontMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontMetrics/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFontMetrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontDescriptor/title",
          "value": "UIFontDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFontDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFontDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontDescriptor~1SymbolicTraits-swift.struct/title",
          "value": "UIFontDescriptorSymbolicTraits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontDescriptor~1SymbolicTraits-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFontDescriptorSymbolicTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontDescriptor~1SymbolicTraits-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFontDescriptorSymbolicTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontMetrics~1scaledValue(for:compatibleWith:)/title",
          "value": "scaledValueForValue:compatibleWithTraitCollection:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontMetrics~1scaledValue(for:compatibleWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scaledValueForValue:compatibleWithTraitCollection:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontMetrics~1scaledFont(for:maximumPointSize:)/title",
          "value": "scaledFontForFont:maximumPointSize:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFontMetrics~1scaledFont(for:maximumPointSize:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scaledFontForFont:maximumPointSize:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uifontmetrics"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uifontmetrics"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
