{
  "abstract": [
    {
      "text": "Marks the beginning of a new page in a PDF context and configures it using the specified custom values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsBeginPDFPageWithInfo(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@UIGraphicsBeginPDFPageWithInfo",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIGraphicsBeginPDFPageWithInfo"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@S@CGRect",
        "text": "CGRect"
      },
      {
        "kind": "text",
        "text": ", ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s11AnyHashableV",
        "text": "AnyHashable"
      },
      {
        "kind": "text",
        "text": " : "
      },
      {
        "kind": "keyword",
        "text": "Any"
      },
      {
        "kind": "text",
        "text": "]?)"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIGraphicsBeginPDFPageWithInfo"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "UIGraphicsBeginPDFPageWithInfo(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIGraphicsBeginPDFPageWithInfo"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "bounds"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@S@CGRect",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@S@CGRect",
              "text": "CGRect"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "pageInfo"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s11AnyHashableV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s11AnyHashableV",
              "text": "AnyHashable"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "keyword",
              "text": "Any"
            },
            {
              "kind": "text",
              "text": "]?)"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A rectangle that specifies the size and location of the new PDF page. This rectangle corresponds to the media box rectangle for the page.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "bounds"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A dictionary that specifies additional page-related information, such as the boxes that define different parts of the page. For a list of keys you can include in this dictionary, see Box Dictionary Keys in ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/coregraphics/cgpdfcontext",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". The dictionary is retained by the new page, so you may release it after this function returns.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            },
            {
              "inlineContent": [
                {
                  "text": "Specify ",
                  "type": "text"
                },
                {
                  "code": "nil",
                  "type": "codeVoice"
                },
                {
                  "text": " if you do not want to associate any additional information with the page.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "pageInfo"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This function ends any previous page before beginning a new one. It sets the media box of the new page to the value in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/coregraphics/kcgpdfcontextmediabox",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " key of the ",
              "type": "text"
            },
            {
              "code": "pageInfo",
              "type": "codeVoice"
            },
            {
              "text": " dictionary, or to the value in the ",
              "type": "text"
            },
            {
              "code": "bounds",
              "type": "codeVoice"
            },
            {
              "text": " parameter if the dictionary does not contain the key.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If the current graphics context is not a PDF context, this function does nothing.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You must call this function or the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsBeginPDFPageWithInfo(_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function before you issue any drawing commands.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/coregraphics/cgpdfcontext": {
      "abstract": [
        {
          "text": "A type of  for drawing PDF content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/coregraphics/cgpdfcontext",
      "kind": "article",
      "role": "article",
      "title": "CGPDFContext",
      "type": "topic",
      "url": "/documentation/coregraphics/cgpdfcontext"
    },
    "doc://com.apple.documentation/documentation/coregraphics/kcgpdfcontextmediabox": {
      "abstract": [
        {
          "text": "The media box for the document or for a given page. This key is optional. If present, the value of this key must be a  object that contains a  (stored by value, not by reference).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "let "
        },
        {
          "kind": "identifier",
          "text": "kCGPDFContextMediaBox"
        },
        {
          "kind": "text",
          "text": ": CFString"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/coregraphics/kcgpdfcontextmediabox",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCGPDFContextMediaBox",
      "type": "topic",
      "url": "/documentation/coregraphics/kcgpdfcontextmediabox"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsAddPDFContextDestinationAtPoint(_:_:)": {
      "abstract": [
        {
          "text": "Creates a jump destination in the current page.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsAddPDFContextDestinationAtPoint"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsAddPDFContextDestinationAtPoint(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsAddPDFContextDestinationAtPoint"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsAddPDFContextDestinationAtPoint(_:_:)",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsaddpdfcontextdestinationatpoint(_:_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsBeginPDFContextToData(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a PDF graphics context that targets the specified mutable data object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsBeginPDFContextToData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSMutableData",
          "text": "NSMutableData"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ", ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsBeginPDFContextToData(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsBeginPDFContextToData"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsBeginPDFContextToData(_:_:_:)",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsbeginpdfcontexttodata(_:_:_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsBeginPDFContextToFile(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a PDF graphics context that targets a file at the specified path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsBeginPDFContextToFile"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ", ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsBeginPDFContextToFile(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsBeginPDFContextToFile"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsBeginPDFContextToFile(_:_:_:)",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsbeginpdfcontexttofile(_:_:_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsBeginPDFPage()": {
      "abstract": [
        {
          "text": "Marks the beginning of a new page in a PDF context and configures it using default values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsBeginPDFPage"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsBeginPDFPage()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsBeginPDFPage"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsBeginPDFPage()",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsbeginpdfpage()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsBeginPDFPageWithInfo(_:_:)": {
      "abstract": [
        {
          "text": "Marks the beginning of a new page in a PDF context and configures it using the specified custom values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsBeginPDFPageWithInfo"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ", ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsBeginPDFPageWithInfo(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsBeginPDFPageWithInfo"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsBeginPDFPageWithInfo(_:_:)",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsbeginpdfpagewithinfo(_:_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsEndPDFContext()": {
      "abstract": [
        {
          "text": "Closes a PDF graphics context and pops it from the current context stack.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsEndPDFContext"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsEndPDFContext()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsEndPDFContext"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsEndPDFContext()",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsendpdfcontext()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsGetPDFContextBounds()": {
      "abstract": [
        {
          "text": "Returns the current page bounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsGetPDFContextBounds"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsGetPDFContextBounds()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsGetPDFContextBounds"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsGetPDFContextBounds()",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsgetpdfcontextbounds()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsSetPDFContextDestinationForRect(_:_:)": {
      "abstract": [
        {
          "text": "Links a rectangular area on the current page to the specified jump destination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsSetPDFContextDestinationForRect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsSetPDFContextDestinationForRect(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsSetPDFContextDestinationForRect"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsSetPDFContextDestinationForRect(_:_:)",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicssetpdfcontextdestinationforrect(_:_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsSetPDFContextURLForRect(_:_:)": {
      "abstract": [
        {
          "text": "Links a rectangular area on the current page to the specified URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsSetPDFContextURLForRect"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsSetPDFContextURLForRect(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsSetPDFContextURLForRect"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsSetPDFContextURLForRect(_:_:)",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicssetpdfcontexturlforrect(_:_:)"
    },
    "doc://com.externally.resolved.symbol/c:@S@CGRect": {
      "abstract": [
        {
          "text": "A structure that contains the location and dimensions of a rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@S@CGRect",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGRect",
      "type": "topic",
      "url": "/documentation/corefoundation/cgrect"
    },
    "doc://com.externally.resolved.symbol/s:s11AnyHashableV": {
      "abstract": [
        {
          "text": "A type-erased hashable value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AnyHashable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s11AnyHashableV",
      "kind": "symbol",
      "role": "symbol",
      "title": "AnyHashable",
      "type": "topic",
      "url": "/documentation/Swift/AnyHashable"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "PDF-creation",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsBeginPDFContextToData(_:_:_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsBeginPDFContextToFile(_:_:_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsEndPDFContext()",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsBeginPDFPage()",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsGetPDFContextBounds()",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsAddPDFContextDestinationAtPoint(_:_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsSetPDFContextDestinationForRect(_:_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsSetPDFContextURLForRect(_:_:)"
      ],
      "title": "PDF creation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIGraphicsBeginPDFPageWithInfo"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsBeginPDFPageWithInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "PDF-creation",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsBeginPDFContextToData(_:_:_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsBeginPDFContextToFile(_:_:_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsEndPDFContext()",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsBeginPDFPage()",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsGetPDFContextBounds()",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsAddPDFContextDestinationAtPoint(_:_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsSetPDFContextDestinationForRect(_:_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsSetPDFContextURLForRect(_:_:)"
              ],
              "title": "PDF creation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIGraphicsBeginPDFPageWithInfo"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@S@CGRect",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@CGRect",
                    "text": "CGRect"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "bounds"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSDictionary",
                    "text": "NSDictionary"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "internalParam",
                    "text": "pageInfo"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A rectangle that specifies the size and location of the new PDF page. This rectangle corresponds to the media box rectangle for the page.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "bounds"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A dictionary that specifies additional page-related information, such as the boxes that define different parts of the page. For a list of keys you can include in this dictionary, see Box Dictionary Keys in ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/coregraphics/cgpdfcontext",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ". The dictionary is retained by the new page, so you may release it after this function returns.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  },
                  {
                    "inlineContent": [
                      {
                        "text": "Specify ",
                        "type": "text"
                      },
                      {
                        "code": "nil",
                        "type": "codeVoice"
                      },
                      {
                        "text": " if you do not want to associate any additional information with the page.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "pageInfo"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsBeginPDFContextToData(_:_:_:)/title",
          "value": "UIGraphicsBeginPDFContextToData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsBeginPDFContextToData(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsBeginPDFContextToData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsSetPDFContextURLForRect(_:_:)/title",
          "value": "UIGraphicsSetPDFContextURLForRect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsSetPDFContextURLForRect(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsSetPDFContextURLForRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsEndPDFContext()/title",
          "value": "UIGraphicsEndPDFContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsEndPDFContext()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsEndPDFContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsBeginPDFContextToFile(_:_:_:)/title",
          "value": "UIGraphicsBeginPDFContextToFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsBeginPDFContextToFile(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsBeginPDFContextToFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsSetPDFContextDestinationForRect(_:_:)/title",
          "value": "UIGraphicsSetPDFContextDestinationForRect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsSetPDFContextDestinationForRect(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsSetPDFContextDestinationForRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsBeginPDFPageWithInfo(_:_:)/title",
          "value": "UIGraphicsBeginPDFPageWithInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsBeginPDFPageWithInfo(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsBeginPDFPageWithInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsAddPDFContextDestinationAtPoint(_:_:)/title",
          "value": "UIGraphicsAddPDFContextDestinationAtPoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsAddPDFContextDestinationAtPoint(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsAddPDFContextDestinationAtPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsBeginPDFPage()/title",
          "value": "UIGraphicsBeginPDFPage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsBeginPDFPage()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsBeginPDFPage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsGetPDFContextBounds()/title",
          "value": "UIGraphicsGetPDFContextBounds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsGetPDFContextBounds()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsGetPDFContextBounds"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uigraphicsbeginpdfpagewithinfo(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uigraphicsbeginpdfpagewithinfo(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
