{
  "abstract": [
    {
      "text": "A closure that executes a set of drawing instructions that the renderer applies to the Core Graphics context.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsDrawingActions"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@UIGraphicsDrawingActions",
    "fragments": [
      {
        "kind": "keyword",
        "text": "typealias"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIGraphicsDrawingActions"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIGraphicsDrawingActions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Alias",
    "symbolKind": "typealias",
    "title": "UIGraphicsDrawingActions"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "typealias"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIGraphicsDrawingActions"
            },
            {
              "kind": "text",
              "text": " = ("
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererContext",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIGraphicsRendererContext",
              "text": "UIGraphicsRendererContext"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsDrawingActions",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " defines a block type that takes a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererContext",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object as an argument and has no return value.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You provide a block of this type as an argument to the graphics drawing methods on ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRenderer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". Your block should use the provided renderer context to perform the drawing operations you want the renderer to execute.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsDrawingActions": {
      "abstract": [
        {
          "text": "A closure that executes a set of drawing instructions that the renderer applies to the Core Graphics context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsDrawingActions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsDrawingActions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsDrawingActions"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsDrawingActions",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsdrawingactions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer/DrawingActions": {
      "abstract": [
        {
          "text": "A closure for drawing an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DrawingActions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer/DrawingActions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DrawingActions"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsImageRenderer.DrawingActions",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsimagerenderer/drawingactions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer/DrawingActions": {
      "abstract": [
        {
          "text": "A closure for drawing PDF content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DrawingActions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer/DrawingActions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DrawingActions"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsPDFRenderer.DrawingActions",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicspdfrenderer/drawingactions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRenderer": {
      "abstract": [
        {
          "text": "An abstract base class for creating graphics renderers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsRenderer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsRenderer"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsRenderer",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsrenderer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRenderer/runDrawingActions(_:completionActions:)": {
      "abstract": [
        {
          "text": "Performs drawing actions on a Core Graphics context that the renderer prepares.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "runDrawingActions"
        },
        {
          "kind": "text",
          "text": "(("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIGraphicsRendererContext",
          "text": "UIGraphicsRendererContext"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionActions"
        },
        {
          "kind": "text",
          "text": ": (("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIGraphicsRendererContext",
          "text": "UIGraphicsRendererContext"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRenderer/runDrawingActions(_:completionActions:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "runDrawingActions:completionActions:error:"
        }
      ],
      "role": "symbol",
      "title": "runDrawingActions(_:completionActions:)",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsrenderer/rundrawingactions(_:completionactions:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererContext": {
      "abstract": [
        {
          "text": "The base class for the drawing environments for graphics renderers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsRendererContext"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsRendererContext"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsRendererContext",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsrenderercontext"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer/DrawingActions",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer/DrawingActions"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Running-the-drawing-actions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRenderer/runDrawingActions(_:completionActions:)"
      ],
      "title": "Running the drawing actions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIGraphicsDrawingActions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsDrawingActions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsDrawingActions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer/DrawingActions",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer/DrawingActions"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Running-the-drawing-actions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRenderer/runDrawingActions(_:completionActions:)"
              ],
              "title": "Running the drawing actions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:BFv(#*Q$objc(cs)UIGraphicsRendererContext)",
                    "text": "void (^)(__kindof UIGraphicsRendererContext *)"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIGraphicsDrawingActions"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRenderer~1runDrawingActions(_:completionActions:)/title",
          "value": "runDrawingActions:completionActions:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRenderer~1runDrawingActions(_:completionActions:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "runDrawingActions:completionActions:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRenderer/title",
          "value": "UIGraphicsRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRendererContext/title",
          "value": "UIGraphicsRendererContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRendererContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsRendererContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRendererContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsRendererContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRenderer~1DrawingActions/title",
          "value": "UIGraphicsImageDrawingActions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRenderer~1DrawingActions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsImageDrawingActions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRenderer~1DrawingActions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsImageDrawingActions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRenderer~1DrawingActions/title",
          "value": "UIGraphicsPDFDrawingActions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRenderer~1DrawingActions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsPDFDrawingActions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRenderer~1DrawingActions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsPDFDrawingActions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsDrawingActions/title",
          "value": "UIGraphicsDrawingActions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsDrawingActions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsDrawingActions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsDrawingActions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsDrawingActions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uigraphicsdrawingactions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uigraphicsdrawingactions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
