{
  "abstract": [
    {
      "text": "A graphics renderer for creating Core Graphics-backed images.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIGraphicsImageRenderer",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIGraphicsImageRenderer"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIGraphicsImageRenderer"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "UIGraphicsImageRenderer"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIGraphicsImageRenderer"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.uikit/documentation/UIKit/adding-writing-tools-support-to-a-custom-uiview"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can use image renderers to accomplish drawing tasks, without having to handle configuration such as color depth and image scale, or manage Core Graphics contexts. You initialize an image renderer with parameters such as image output dimensions and format. You then use one or more of the drawing functions to render images that share these properties.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To render an image:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Optionally, create a ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " object to specify nondefault parameters the renderer should use to create its context.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Instantiate a ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " object, providing the dimensions of the output image and a format object. The renderer uses default values for the current device if you don’t provide format object, as demonstrated in ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer#Creating-a-graphics-image-renderer",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Choose one of the rendering methods depending on the output you desire: ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer/image(actions:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " returns a ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " object; ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer/jpegData(withCompressionQuality:actions:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " returns a JPEG-encoded ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/data",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " object; and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer/pngData(actions:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " returns a PNG-encoded ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/data",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " object.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Execute your chosen method, providing Core Graphics drawing instructions as the closure argument, as shown in ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer#Creating-an-image-with-an-image-renderer",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ". ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer#Using-blend-mode",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " demonstrates some of the more advanced rendering features you can use in your drawing instructions.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Optionally, you can use Core Graphics drawing code within the drawing instructions you provide to the rendering method, as shown in ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer#Using-Core-Graphics-rendering-functions",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "After initializing an image renderer, you can use it to draw multiple images with the same configuration. An image renderer keeps a cache of Core Graphics contexts, so reusing the same renderer can be more efficient than creating new renderers.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Creating-a-graphics-image-renderer",
          "level": 3,
          "text": "Creating a graphics image renderer",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Create an image renderer, providing the size of the output image:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "let renderer = UIGraphicsImageRenderer(size: CGSize(width: 200, height: 200))"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "UIGraphicsImageRenderer *renderer = [[UIGraphicsImageRenderer alloc] initWithSize:CGSizeMake(200, 200)];"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "You can instead use one of the other ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " initializers to specify a renderer format (",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ") in addition to the size. This allows you to configure the underlying Core Graphics context for wide color and retina images.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you don’t provide a format, the renderer uses the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererFormat/default()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " format, which creates a context best suited for the current device.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Creating-an-image-with-an-image-renderer",
          "level": 3,
          "text": "Creating an image with an image renderer",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer/image(actions:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to create an image (",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object) with an image renderer. This method takes a closure that represents the drawing actions. Within this closure, the renderer creates a Core Graphics context using the parameters provided during renderer initialization, and sets this Core Graphics context to be the current context.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "let image = renderer.image { (context) in",
                    "  UIColor.darkGray.setStroke()",
                    "  context.stroke(renderer.format.bounds)",
                    "  UIColor(colorLiteralRed: 158/255, green: 215/255, blue: 245/255, alpha: 1).setFill()",
                    "  context.fill(CGRect(x: 1, y: 1, width: 140, height: 140))",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "  UIImage *image = [renderer imageWithActions:^(UIGraphicsImageRendererContext * _Nonnull context) {",
                    "    [[UIColor darkGrayColor] setStroke];",
                    "    [context strokeRect:renderer.format.bounds];",
                    "    [[UIColor colorWithRed:158/255.0 green:215/255.0 blue:245/255.0 alpha:1] setFill];",
                    "    [context fillRect:CGRectMake(1, 1, 140, 140)];",
                    "  }];"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "The drawing actions closure takes a single argument of type ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererContext",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". This provides access to some high-level drawing functions, such as ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererContext/fill(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", through the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererContext",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " superclass.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The above code creates the following image:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2874999",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In addition to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer/image(actions:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method that creates an ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object, ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " also has ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer/jpegData(withCompressionQuality:actions:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer/pngData(actions:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " methods that create ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/data",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects containing the image encoded as a JPEG or a PNG respectively. All three methods take the same approach as detailed here, accepting a block that represents the drawing actions.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Using-blend-mode",
          "level": 3,
          "text": "Using blend mode",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The utility methods on ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererContext",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " also offer a variant that accepts a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/coregraphics/cgblendmode",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " value. This value determines how to combine the pixel values when painting.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "let image = renderer.image { (context) in",
                    "  UIColor.darkGray.setStroke()",
                    "  context.stroke(renderer.format.bounds)",
                    "  UIColor(colorLiteralRed: 158/255, green: 215/255, blue: 245/255, alpha: 1).setFill()",
                    "  context.fill(CGRect(x: 1, y: 1, width: 140, height: 140))",
                    "  UIColor(colorLiteralRed: 145/255, green: 211/255, blue: 205/255, alpha: 1).setFill()",
                    "  context.fill(CGRect(x: 60, y: 60, width: 140, height: 140), blendMode: .multiply)",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "  UIImage *image = [renderer imageWithActions:^(UIGraphicsImageRendererContext * _Nonnull context) {",
                    "    [[UIColor darkGrayColor] setStroke];",
                    "    [context strokeRect:renderer.format.bounds];",
                    "    [[UIColor colorWithRed:158/255.0 green:215/255.0 blue:245/255.0 alpha:1] setFill];",
                    "    [context fillRect:CGRectMake(1, 1, 140, 140)];",
                    "    [[UIColor colorWithRed:145/255.0 green:211/255.0 blue:205/255.0 alpha:1] setFill];",
                    "    [context fillRect:CGRectMake(60, 60, 140, 140) blendMode:kCGBlendModeMultiply];",
                    "  }];"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "This code draws a second square, using a blend mode of multiply. The following image shows the result.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2875000",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Using-Core-Graphics-rendering-functions",
          "level": 3,
          "text": "Using Core Graphics rendering functions",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererContext",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " available in the image closure has a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererContext/cgContext",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property, which allows you to use Core Graphics rendering functions directly. For example, the following code demonstrates how to add a circle to the image:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "let image = renderer.image { (context) in",
                    "  UIColor.darkGray.setStroke()",
                    "  context.stroke(renderer.format.bounds)",
                    "  UIColor(colorLiteralRed: 158/255, green: 215/255, blue: 245/255, alpha: 1).setFill()",
                    "  context.fill(CGRect(x: 1, y: 1, width: 140, height: 140))",
                    "  UIColor(colorLiteralRed: 145/255, green: 211/255, blue: 205/255, alpha: 1).setFill()",
                    "  context.fill(CGRect(x: 60, y: 60, width: 140, height: 140), blendMode: .multiply)",
                    "  ",
                    "  UIColor(colorLiteralRed: 203/255, green: 222/255, blue: 116/255, alpha: 0.6).setFill()",
                    "  context.cgContext.fillEllipse(in: CGRect(x: 60, y: 60, width: 140, height: 140))",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "  UIImage *image = [renderer imageWithActions:^(UIGraphicsImageRendererContext * _Nonnull context) {",
                    "    [[UIColor darkGrayColor] setStroke];",
                    "    [context strokeRect:renderer.format.bounds];",
                    "    [[UIColor colorWithRed:158/255.0 green:215/255.0 blue:245/255.0 alpha:1] setFill];",
                    "    [context fillRect:CGRectMake(1, 1, 140, 140)];",
                    "    [[UIColor colorWithRed:145/255.0 green:211/255.0 blue:205/255.0 alpha:1] setFill];",
                    "    [context fillRect:CGRectMake(60, 60, 140, 140) blendMode:kCGBlendModeMultiply];",
                    "    ",
                    "    [[UIColor colorWithRed:203/255.0 green:222/255.0 blue:116/255.0 alpha:0.6] setFill];",
                    "    CGContextFillEllipseInRect(context.CGContext, CGRectMake(60, 60, 140, 140));",
                    "  }];"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "This code uses the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/coregraphics/cgcontext/1454371-fillellipse",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method on ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/coregraphics/cgcontext",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to draw a green circle on the blue and turquoise squares image; the following image shows the result.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2875001",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/coregraphics/cgblendmode": {
      "abstract": [
        {
          "text": "Compositing operations for images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "enum "
        },
        {
          "kind": "identifier",
          "text": "CGBlendMode"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/coregraphics/cgblendmode",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGBlendMode",
      "type": "topic",
      "url": "/documentation/coregraphics/cgblendmode"
    },
    "doc://com.apple.documentation/documentation/coregraphics/cgcontext": {
      "abstract": [
        {
          "text": "A Quartz 2D drawing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CGContext"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/coregraphics/cgcontext",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGContext",
      "type": "topic",
      "url": "/documentation/coregraphics/cgcontext"
    },
    "doc://com.apple.documentation/documentation/coregraphics/cgcontext/1454371-fillellipse": {
      "abstract": [
        {
          "text": "Paints the area of the ellipse that fits inside the provided rectangle, using the fill color in the current graphics state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "fillEllipse"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "identifier",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": CGRect)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/coregraphics/cgcontext/1454371-fillellipse",
      "kind": "symbol",
      "role": "symbol",
      "title": "fillEllipse(in:)",
      "type": "topic",
      "url": "/documentation/coregraphics/cgcontext/1454371-fillellipse"
    },
    "doc://com.apple.documentation/documentation/foundation/data": {
      "abstract": [
        {
          "text": "A byte buffer in memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/data",
      "kind": "symbol",
      "role": "symbol",
      "title": "Data",
      "type": "topic",
      "url": "/documentation/foundation/data"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer": {
      "abstract": [
        {
          "text": "A graphics renderer for creating Core Graphics-backed images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsImageRenderer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsImageRenderer"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsImageRenderer",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsimagerenderer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer#Creating-a-graphics-image-renderer": {
      "abstract": [],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer#Creating-a-graphics-image-renderer",
      "kind": "section",
      "title": "Creating a graphics image renderer",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsimagerenderer#Creating-a-graphics-image-renderer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer#Creating-an-image-with-an-image-renderer": {
      "abstract": [],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer#Creating-an-image-with-an-image-renderer",
      "kind": "section",
      "title": "Creating an image with an image renderer",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsimagerenderer#Creating-an-image-with-an-image-renderer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer#Using-Core-Graphics-rendering-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer#Using-Core-Graphics-rendering-functions",
      "kind": "section",
      "title": "Using Core Graphics rendering functions",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsimagerenderer#Using-Core-Graphics-rendering-functions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer#Using-blend-mode": {
      "abstract": [],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer#Using-blend-mode",
      "kind": "section",
      "title": "Using blend mode",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsimagerenderer#Using-blend-mode"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer/DrawingActions": {
      "abstract": [
        {
          "text": "A closure for drawing an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DrawingActions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer/DrawingActions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DrawingActions"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsImageRenderer.DrawingActions",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsimagerenderer/drawingactions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer/image(actions:)": {
      "abstract": [
        {
          "text": "Creates an image from a set of drawing instructions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "image"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "actions"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIGraphicsImageRendererContext",
          "text": "UIGraphicsImageRendererContext"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer/image(actions:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageWithActions:"
        }
      ],
      "role": "symbol",
      "title": "image(actions:)",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsimagerenderer/image(actions:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer/init(bounds:format:)": {
      "abstract": [
        {
          "text": "Creates an image renderer with the specified bounds and format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "bounds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "format"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIGraphicsImageRendererFormat",
          "text": "UIGraphicsImageRendererFormat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer/init(bounds:format:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithBounds:format:"
        }
      ],
      "role": "symbol",
      "title": "init(bounds:format:)",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsimagerenderer/init(bounds:format:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer/init(size:)": {
      "abstract": [
        {
          "text": "Creates an image renderer for drawing images of the specified size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "convenience"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer/init(size:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithSize:"
        }
      ],
      "role": "symbol",
      "title": "init(size:)",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsimagerenderer/init(size:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer/init(size:format:)": {
      "abstract": [
        {
          "text": "Creates an image renderer with the specified size and format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "format"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIGraphicsImageRendererFormat",
          "text": "UIGraphicsImageRendererFormat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer/init(size:format:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithSize:format:"
        }
      ],
      "role": "symbol",
      "title": "init(size:format:)",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsimagerenderer/init(size:format:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer/jpegData(withCompressionQuality:actions:)": {
      "abstract": [
        {
          "text": "Creates a JPEG-encoded image from a set of drawing instructions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "jpegData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withCompressionQuality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "actions"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIGraphicsImageRendererContext",
          "text": "UIGraphicsImageRendererContext"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer/jpegData(withCompressionQuality:actions:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JPEGDataWithCompressionQuality:actions:"
        }
      ],
      "role": "symbol",
      "title": "jpegData(withCompressionQuality:actions:)",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsimagerenderer/jpegdata(withcompressionquality:actions:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer/pngData(actions:)": {
      "abstract": [
        {
          "text": "Creates a PNG-encoded image from a set of drawing instructions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pngData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "actions"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIGraphicsImageRendererContext",
          "text": "UIGraphicsImageRendererContext"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer/pngData(actions:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PNGDataWithActions:"
        }
      ],
      "role": "symbol",
      "title": "pngData(actions:)",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsimagerenderer/pngdata(actions:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererContext": {
      "abstract": [
        {
          "text": "The drawing environment for an image renderer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsImageRendererContext"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsImageRendererContext"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsImageRendererContext",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsimagerenderercontext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat": {
      "abstract": [
        {
          "text": "A set of drawing attributes that represents the configuration of an image renderer context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsImageRendererFormat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsImageRendererFormat"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsImageRendererFormat",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsimagerendererformat"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer": {
      "abstract": [
        {
          "text": "A graphics renderer for creating PDFs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsPDFRenderer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsPDFRenderer"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsPDFRenderer",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicspdfrenderer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererContext": {
      "abstract": [
        {
          "text": "The drawing environment for a PDF renderer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsPDFRendererContext"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsPDFRendererContext"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsPDFRendererContext",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicspdfrenderercontext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererFormat": {
      "abstract": [
        {
          "text": "A set of drawing attributes that represents the configuration of a PDF renderer context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsPDFRendererFormat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsPDFRendererFormat"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsPDFRendererFormat",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicspdfrendererformat"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRenderer": {
      "abstract": [
        {
          "text": "An abstract base class for creating graphics renderers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsRenderer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsRenderer"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsRenderer",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsrenderer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererContext": {
      "abstract": [
        {
          "text": "The base class for the drawing environments for graphics renderers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsRendererContext"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsRendererContext"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsRendererContext",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsrenderercontext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererContext/cgContext": {
      "abstract": [
        {
          "text": "The underlying Core Graphics context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cgContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGContextRef",
          "text": "CGContext"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererContext/cgContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CGContext"
        }
      ],
      "role": "symbol",
      "title": "cgContext",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsrenderercontext/cgcontext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererContext/fill(_:)": {
      "abstract": [
        {
          "text": "Paints a rectangular area with the currently selected fill color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fill"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererContext/fill(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fillRect:"
        }
      ],
      "role": "symbol",
      "title": "fill(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsrenderercontext/fill(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererFormat": {
      "abstract": [
        {
          "text": "A set of drawing attributes that represents the configuration of a graphics renderer context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsRendererFormat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsRendererFormat"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsRendererFormat",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsrendererformat"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererFormat/default()": {
      "abstract": [
        {
          "text": "Returns a format that represents the highest fidelity that the current device supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererFormat/default()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultFormat"
        }
      ],
      "role": "symbol",
      "title": "default()",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsrendererformat/default()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage": {
      "abstract": [
        {
          "text": "An object that manages image data in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIImage"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImage"
        }
      ],
      "role": "symbol",
      "title": "UIImage",
      "type": "topic",
      "url": "/documentation/uikit/uiimage"
    },
    "doc://com.apple.uikit/documentation/UIKit/adding-writing-tools-support-to-a-custom-uiview": {
      "abstract": [
        {
          "text": "Add Writing Tools support, including support for inline replacement animations,",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "to your custom iOS views that contain text.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/adding-writing-tools-support-to-a-custom-uiview",
      "kind": "article",
      "role": "article",
      "title": "Adding Writing Tools support to a custom UIKit view",
      "type": "topic",
      "url": "/documentation/uikit/adding-writing-tools-support-to-a-custom-uiview"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "media-2874999": {
      "alt": "Image showing a blue square in the top left of a larger white squares",
      "identifier": "media-2874999",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/120452bcd4ba5d1e1217df3088cb4c20/media-2874999@2x.png"
        }
      ]
    },
    "media-2875000": {
      "alt": "Image showing two overlapping squares, one blue, the other turquoise, in the top-left and bottom-right of a white background square respectively.",
      "identifier": "media-2875000",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/80b9801ced2dfb67ba11c15a666db490/media-2875000@2x.png"
        }
      ]
    },
    "media-2875001": {
      "alt": "An image showing two overlapping squares and an overlaid green circle.",
      "identifier": "media-2875001",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/4493395a1867556cb03a84fee2c59ed7/media-2875001@2x.png"
        }
      ]
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRenderer"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Graphics-contexts",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRenderer",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererContext",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererFormat",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererContext",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererContext",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererFormat"
      ],
      "title": "Graphics contexts"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializing-an-image-renderer",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer/init(bounds:format:)",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer/init(size:)",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer/init(size:format:)"
      ],
      "title": "Initializing an image renderer"
    },
    {
      "anchor": "Creating-images",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer/image(actions:)",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer/jpegData(withCompressionQuality:actions:)",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer/pngData(actions:)",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer/DrawingActions"
      ],
      "title": "Creating images"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIGraphicsImageRenderer"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsImageRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsImageRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Initializing-an-image-renderer",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer/init(bounds:format:)",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer/init(size:)",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer/init(size:format:)"
              ],
              "title": "Initializing an image renderer"
            },
            {
              "anchor": "Creating-images",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer/image(actions:)",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer/jpegData(withCompressionQuality:actions:)",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer/pngData(actions:)",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer/DrawingActions"
              ],
              "title": "Creating images"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRenderer"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Graphics-contexts",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRenderer",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererContext",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererFormat",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererContext",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererContext",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererFormat"
              ],
              "title": "Graphics contexts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIGraphicsImageRenderer"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRenderer",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UIGraphicsRenderer",
                    "text": "UIGraphicsRenderer"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRendererFormat/title",
          "value": "UIGraphicsImageRendererFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRendererFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsImageRendererFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRendererFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsImageRendererFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRendererFormat/title",
          "value": "UIGraphicsRendererFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRendererFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsRendererFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRendererFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsRendererFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRenderer/title",
          "value": "UIGraphicsImageRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsImageRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsImageRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRenderer~1pngData(actions:)/title",
          "value": "PNGDataWithActions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRenderer~1pngData(actions:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "PNGDataWithActions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRenderer~1jpegData(withCompressionQuality:actions:)/title",
          "value": "JPEGDataWithCompressionQuality:actions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRenderer~1jpegData(withCompressionQuality:actions:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "JPEGDataWithCompressionQuality:actions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRendererFormat/title",
          "value": "UIGraphicsPDFRendererFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRendererFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsPDFRendererFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRendererFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsPDFRendererFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRenderer~1image(actions:)/title",
          "value": "imageWithActions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRenderer~1image(actions:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "imageWithActions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1coregraphics~1cgcontext/title",
          "value": "CGContextRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/title",
          "value": "UIImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRendererContext/title",
          "value": "UIGraphicsPDFRendererContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRendererContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsPDFRendererContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRendererContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsPDFRendererContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRendererFormat~1default()/title",
          "value": "defaultFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRendererFormat~1default()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "defaultFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRenderer~1DrawingActions/title",
          "value": "UIGraphicsImageDrawingActions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRenderer~1DrawingActions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsImageDrawingActions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRenderer~1DrawingActions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsImageDrawingActions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRenderer/title",
          "value": "UIGraphicsRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRendererContext~1cgContext/title",
          "value": "CGContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRendererContext~1cgContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CGContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRendererContext/title",
          "value": "UIGraphicsImageRendererContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRendererContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsImageRendererContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRendererContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsImageRendererContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1coregraphics~1cgcontext~11454371-fillellipse/title",
          "value": "CGContextFillEllipseInRect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRenderer~1init(bounds:format:)/title",
          "value": "initWithBounds:format:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRenderer~1init(bounds:format:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithBounds:format:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRenderer~1init(size:format:)/title",
          "value": "initWithSize:format:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRenderer~1init(size:format:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithSize:format:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRendererContext~1fill(_:)/title",
          "value": "fillRect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRendererContext~1fill(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "fillRect:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRendererContext/title",
          "value": "UIGraphicsRendererContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRendererContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsRendererContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRendererContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsRendererContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRenderer/title",
          "value": "UIGraphicsPDFRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsPDFRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsPDFRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRenderer~1init(size:)/title",
          "value": "initWithSize:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRenderer~1init(size:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithSize:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uigraphicsimagerenderer"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uigraphicsimagerenderer"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
