{
  "abstract": [
    {
      "text": "A graphics renderer for creating PDFs.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIGraphicsPDFRenderer",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIGraphicsPDFRenderer"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIGraphicsPDFRenderer"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "UIGraphicsPDFRenderer"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIGraphicsPDFRenderer"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can use PDF renderers to create PDF files, without having to manage Core Graphics contexts.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To render a PDF:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Optionally create a ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererFormat",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " object to specify nondefault parameters the renderer should use to create its context.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Instantiate a ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " object, providing the dimensions of the output image and a format object. The renderer uses sensible defaults for the current device if you don’t provide format object, as demonstrated in ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer#Creating-a-graphics-PDF-renderer",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Choose one of the rendering methods depending on your desired output: ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer/pdfData(actions:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " outputs the PDF in the form of a ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.documentation/documentation/foundation/data",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " object, and ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer/writePDF(to:withActions:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " saves the PDF as a file directly to disk.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Provide Core Graphics drawing instructions within the closure associated with your chosen method, as shown in ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer#Creating-a-PDF-with-a-PDF-renderer",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Optionally, you can create a multi-page PDF, using the approach shown in ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer#Adding-pages",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Optionally, add links to your PDF to make navigation easy, as shown in ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer#Creating-internal-links",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "After initializing a PDF renderer, you can use it to draw multiple PDFs with the same configuration.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Creating-a-graphics-PDF-renderer",
          "level": 3,
          "text": "Creating a graphics PDF renderer",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Create a PDF renderer, providing the bounds of the PDF page.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "let renderer = UIGraphicsPDFRenderer(bounds: CGRect(x: 0, y: 0, width: 500, height: 300))"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "UIGraphicsPDFRenderer *renderer = [[UIGraphicsPDFRenderer alloc] initWithBounds:CGRectMake(0, 0, 500, 300)];"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "You can instead use one of the other ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " initializers to specify a renderer format (",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererFormat",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ") in addition to the bounds. This allows you to configure the underlying Core Graphics context with custom PDF document info. If you don’t provide a format, the renderer uses the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererFormat/default()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " format, which creates a context best suited for the current device.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Creating-a-PDF-with-a-PDF-renderer",
          "level": 3,
          "text": "Creating a PDF with a PDF renderer",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer/pdfData(actions:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to create a PDF with the PDF renderer you created above. This takes a block that represents the drawing actions. Within this block, the renderer creates a Core Graphics context using the parameters provided during renderer initialization, and sets this to be the current context.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Before issuing PDF drawing instructions, you must create a page with a call to either the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererContext/beginPage()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererContext/beginPage(withBounds:pageInfo:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method on the supplied ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererContext",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "let pdf = renderer.pdfData { (context) in",
                    "  context.beginPage()",
                    "  let attributes = [",
                    "    NSFontAttributeName : UIFont.boldSystemFont(ofSize: 150)",
                    "  ]",
                    "  let text = \"Hello!\" as NSString",
                    "  text.draw(in: CGRect(x: 0, y: 0, width: 500, height: 200), withAttributes: attributes)",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "NSData *pdf = [renderer PDFDataWithActions:^(UIGraphicsPDFRendererContext * _Nonnull context) {",
                    "  [context beginPage];",
                    "  NSDictionary *attributes = @{NSFontAttributeName : [UIFont boldSystemFontOfSize:150]};",
                    "  NSString *text = @\"Hello!\";",
                    "  [text drawInRect:CGRectMake(0, 0, 500, 200) withAttributes:attributes];}];  "
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "The drawing actions closure takes a single argument of type ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererContext",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". This provides access to some high-level drawing functions, such as ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererContext/fill(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " through the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererContext",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " superclass.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "This code uses a drawing method on ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". If you want to create a PDF with more text, consider using ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/library/archive/documentation/Miscellaneous/Conceptual/iPhoneOSTechOverview/iPhoneOSTechnologies/iPhoneOSTechnologies.html#//apple_ref/doc/uid/TP40007898-CH3-SW11",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " or ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/library/archive/documentation/StringsTextFonts/Conceptual/TextAndWebiPhoneOS/LowerLevelText-HandlingTechnologies/LowerLevelText-HandlingTechnologies.html#//apple_ref/doc/uid/TP40009542-CH15-SW3",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", both of which provide extensive text layout functionality.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "The above code creates the following result:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2864001",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Adding-pages",
          "level": 3,
          "text": "Adding pages",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Add multiple pages to your PDF through repeated calls to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererContext/beginPage()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method on the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererContext",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " provided to the drawing block.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "let pdf = renderer.pdfData { (context) in",
                    "  let attributes = [",
                    "    NSFontAttributeName : UIFont.boldSystemFont(ofSize: 150)",
                    "  ]",
                    "  for page in 1...3 {",
                    "    context.beginPage()",
                    "    let text = \"Page \\(page)\" as NSString",
                    "    text.draw(in: CGRect(x: 0, y: 0, width: 500, height: 200), withAttributes: attributes)",
                    "  }",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "NSData *pdf = [renderer PDFDataWithActions:^(UIGraphicsPDFRendererContext * _Nonnull context) {",
                    "  NSDictionary *attributes = @{NSFontAttributeName : [UIFont boldSystemFontOfSize:150]}; ",
                    "  for (int page = 1; page < 4; page++) {",
                    "    [context beginPage];",
                    "    NSString *text = [NSString stringWithFormat:@\"Page %d\", page];",
                    "    [text drawInRect:CGRectMake(0, 0, 500, 200) withAttributes:attributes];",
                    "  }}];"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererContext/beginPage(withBounds:pageInfo:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method instead of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererContext/beginPage()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method if you want to override the default properties for the new page.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This code creates a PDF with three pages, each of which contains the current page number as large text, as shown in the following image.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2864003",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Creating-internal-links",
          "level": 3,
          "text": "Creating internal links",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You can create internal links, known as destinations, in PDFs. A complete link has two components:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A named destination. This is a point on a PDF page. You create these with the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererContext/addDestination(withName:at:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method on ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererContext",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ".",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A link region. This is a rectangle on a PDF page, which when tapped, instructs the PDF viewing app to jump to a specific named destination. You create these with the ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererContext/setDestinationWithName(_:for:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " method on ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererContext",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": ", providing the name of the destination to jump to, and the bounds of the active link region.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The following code demonstrates how to use destinations with a PDF renderer by showing how to create links that jump to the next page.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "let pdf = renderer.pdfData { (context) in",
                    "  let pageNumberAttributes = [",
                    "    NSFontAttributeName : UIFont.boldSystemFont(ofSize: 150)",
                    "  ]",
                    "  ",
                    "  let nextPage = \"Next Page ↠\" as NSString",
                    "  let nextPageRect = CGRect(x: 350, y: 250, width: 150, height: 40)",
                    "  let nextPageAttributes = [",
                    "    NSFontAttributeName : UIFont.systemFont(ofSize: 25),",
                    "    NSBackgroundColorAttributeName : UIColor.red,",
                    "    NSForegroundColorAttributeName : UIColor.white",
                    "  ]",
                    "  ",
                    "  for page in 1...3 {",
                    "    context.beginPage()",
                    "    let pageNumber = \"Page \\(page)\" as NSString",
                    "    pageNumber.draw(in: CGRect(x: 0, y: 0, width: 500, height: 200), withAttributes: pageNumberAttributes)",
                    "    ",
                    "    nextPage.draw(in: nextPageRect, withAttributes: nextPageAttributes)",
                    "    ",
                    "    context.addDestination(withName: \"page-\\(page)\", at: CGPoint.zero.applying(context.cgContext.userSpaceToDeviceSpaceTransform))",
                    "    context.setDestinationWithName(\"page-\\(page + 1)\", for: nextPageRect.applying(context.cgContext.userSpaceToDeviceSpaceTransform))",
                    "  }",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "NSData *pdf = [renderer PDFDataWithActions:^(UIGraphicsPDFRendererContext * _Nonnull context) {",
                    "  NSDictionary *attributes = @{NSFontAttributeName : [UIFont boldSystemFontOfSize:150]};",
                    "    ",
                    "  NSString *nextPage = @\"Next Page ↠\";",
                    "  CGRect nextPageRect = CGRectMake(350, 250, 150, 40);",
                    "  NSDictionary *nextPageAttributes = @{",
                    "    NSFontAttributeName : [UIFont systemFontOfSize:25],",
                    "    NSBackgroundColorAttributeName : [UIColor redColor],",
                    "    NSForegroundColorAttributeName : [UIColor whiteColor]",
                    "  };",
                    "  for (int page = 1; page < 4; page++) {",
                    "    [context beginPage];",
                    "    NSString *pageNumber = [NSString stringWithFormat:@\"Page %d\", page];",
                    "    [pageNumber drawInRect:CGRectMake(0, 0, 500, 200) withAttributes:attributes];",
                    "    [nextPage drawInRect:nextPageRect withAttributes:nextPageAttributes];",
                    "      ",
                    "    [context addDestinationWithName:[NSString stringWithFormat:@\"page-%d\", page]",
                    "                            atPoint:CGContextConvertPointToDeviceSpace(context.CGContext, CGPointZero)];",
                    "    [context setDestinationWithName:[NSString stringWithFormat:@\"page-%d\", page+1]",
                    "                            forRect:CGContextConvertRectToDeviceSpace(context.CGContext, nextPageRect)];",
                    "  }",
                    "}];"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "This code adds large red labels that jump from the current page to the next page when clicked. Each page has a destination with names of the form ",
              "type": "text"
            },
            {
              "code": "page-1",
              "type": "codeVoice"
            },
            {
              "text": ", positioned at the origin. The bounding box for the next-page label is the link to the destination on the following page.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererContext/addDestination(withName:at:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererContext/setDestinationWithName(_:for:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " methods on ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererContext",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " use the underlying PDF coordinate space, which has its y-axis flipped with respect to the coordinate system used by Core Graphics. You can translate between the two using the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/coregraphics/cgcontext/1455677-userspacetodevicespacetransform",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " property on ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/coregraphics/cgcontext",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", as shown in the code.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        },
        {
          "inlineContent": [
            {
              "text": "The above code results in the following PDF:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2864256",
              "type": "image"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/coregraphics/cgcontext": {
      "abstract": [
        {
          "text": "A Quartz 2D drawing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CGContext"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/coregraphics/cgcontext",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGContext",
      "type": "topic",
      "url": "/documentation/coregraphics/cgcontext"
    },
    "doc://com.apple.documentation/documentation/coregraphics/cgcontext/1455677-userspacetodevicespacetransform": {
      "abstract": [
        {
          "text": "Returns an affine transform that maps user space coordinates to device space coordinates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "var "
        },
        {
          "kind": "identifier",
          "text": "userSpaceToDeviceSpaceTransform"
        },
        {
          "kind": "text",
          "text": ": CGAffineTransform"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/coregraphics/cgcontext/1455677-userspacetodevicespacetransform",
      "kind": "symbol",
      "role": "symbol",
      "title": "userSpaceToDeviceSpaceTransform",
      "type": "topic",
      "url": "/documentation/coregraphics/cgcontext/1455677-userspacetodevicespacetransform"
    },
    "doc://com.apple.documentation/documentation/foundation/data": {
      "abstract": [
        {
          "text": "A byte buffer in memory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/data",
      "kind": "symbol",
      "role": "symbol",
      "title": "Data",
      "type": "topic",
      "url": "/documentation/foundation/data"
    },
    "doc://com.apple.documentation/documentation/foundation/nsstring": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer": {
      "abstract": [
        {
          "text": "A graphics renderer for creating Core Graphics-backed images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsImageRenderer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsImageRenderer"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsImageRenderer",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsimagerenderer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererContext": {
      "abstract": [
        {
          "text": "The drawing environment for an image renderer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsImageRendererContext"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsImageRendererContext"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsImageRendererContext",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsimagerenderercontext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat": {
      "abstract": [
        {
          "text": "A set of drawing attributes that represents the configuration of an image renderer context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsImageRendererFormat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsImageRendererFormat"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsImageRendererFormat",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsimagerendererformat"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer": {
      "abstract": [
        {
          "text": "A graphics renderer for creating PDFs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsPDFRenderer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsPDFRenderer"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsPDFRenderer",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicspdfrenderer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer#Adding-pages": {
      "abstract": [],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer#Adding-pages",
      "kind": "section",
      "title": "Adding pages",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicspdfrenderer#Adding-pages"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer#Creating-a-PDF-with-a-PDF-renderer": {
      "abstract": [],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer#Creating-a-PDF-with-a-PDF-renderer",
      "kind": "section",
      "title": "Creating a PDF with a PDF renderer",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicspdfrenderer#Creating-a-PDF-with-a-PDF-renderer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer#Creating-a-graphics-PDF-renderer": {
      "abstract": [],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer#Creating-a-graphics-PDF-renderer",
      "kind": "section",
      "title": "Creating a graphics PDF renderer",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicspdfrenderer#Creating-a-graphics-PDF-renderer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer#Creating-internal-links": {
      "abstract": [],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer#Creating-internal-links",
      "kind": "section",
      "title": "Creating internal links",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicspdfrenderer#Creating-internal-links"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer/DrawingActions": {
      "abstract": [
        {
          "text": "A closure for drawing PDF content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DrawingActions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer/DrawingActions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DrawingActions"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsPDFRenderer.DrawingActions",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicspdfrenderer/drawingactions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer/init(bounds:format:)": {
      "abstract": [
        {
          "text": "Creates a new graphics renderer with the specified bounds and format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "bounds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "format"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIGraphicsPDFRendererFormat",
          "text": "UIGraphicsPDFRendererFormat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer/init(bounds:format:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithBounds:format:"
        }
      ],
      "role": "symbol",
      "title": "init(bounds:format:)",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicspdfrenderer/init(bounds:format:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer/pdfData(actions:)": {
      "abstract": [
        {
          "text": "Creates a PDF from a set of drawing instructions and returns it as a data object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pdfData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "actions"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIGraphicsPDFRendererContext",
          "text": "UIGraphicsPDFRendererContext"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer/pdfData(actions:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "PDFDataWithActions:"
        }
      ],
      "role": "symbol",
      "title": "pdfData(actions:)",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicspdfrenderer/pdfdata(actions:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer/writePDF(to:withActions:)": {
      "abstract": [
        {
          "text": "Creates a PDF from a set of drawing instructions and saves it to a specified URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "writePDF"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withActions"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIGraphicsPDFRendererContext",
          "text": "UIGraphicsPDFRendererContext"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer/writePDF(to:withActions:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "writePDFToURL:withActions:error:"
        }
      ],
      "role": "symbol",
      "title": "writePDF(to:withActions:)",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicspdfrenderer/writepdf(to:withactions:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererContext": {
      "abstract": [
        {
          "text": "The drawing environment for a PDF renderer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsPDFRendererContext"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsPDFRendererContext"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsPDFRendererContext",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicspdfrenderercontext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererContext/addDestination(withName:at:)": {
      "abstract": [
        {
          "text": "Creates a named destination point in the current PDF page.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addDestination"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererContext/addDestination(withName:at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addDestinationWithName:atPoint:"
        }
      ],
      "role": "symbol",
      "title": "addDestination(withName:at:)",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicspdfrenderercontext/adddestination(withname:at:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererContext/beginPage()": {
      "abstract": [
        {
          "text": "Marks the beginning of a new page in the PDF context and configures it using default values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginPage"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererContext/beginPage()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beginPage"
        }
      ],
      "role": "symbol",
      "title": "beginPage()",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicspdfrenderercontext/beginpage()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererContext/beginPage(withBounds:pageInfo:)": {
      "abstract": [
        {
          "text": "Marks the beginning of a new page in the PDF context and configures it using the specified values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginPage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withBounds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "pageInfo"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererContext/beginPage(withBounds:pageInfo:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beginPageWithBounds:pageInfo:"
        }
      ],
      "role": "symbol",
      "title": "beginPage(withBounds:pageInfo:)",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicspdfrenderercontext/beginpage(withbounds:pageinfo:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererContext/setDestinationWithName(_:for:)": {
      "abstract": [
        {
          "text": "Creates a link rectangle in the current page that jumps the PDF viewer to the named destination when clicked.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setDestinationWithName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererContext/setDestinationWithName(_:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setDestinationWithName:forRect:"
        }
      ],
      "role": "symbol",
      "title": "setDestinationWithName(_:for:)",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicspdfrenderercontext/setdestinationwithname(_:for:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererFormat": {
      "abstract": [
        {
          "text": "A set of drawing attributes that represents the configuration of a PDF renderer context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsPDFRendererFormat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsPDFRendererFormat"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsPDFRendererFormat",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicspdfrendererformat"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRenderer": {
      "abstract": [
        {
          "text": "An abstract base class for creating graphics renderers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsRenderer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsRenderer"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsRenderer",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsrenderer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererContext": {
      "abstract": [
        {
          "text": "The base class for the drawing environments for graphics renderers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsRendererContext"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsRendererContext"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsRendererContext",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsrenderercontext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererContext/fill(_:)": {
      "abstract": [
        {
          "text": "Paints a rectangular area with the currently selected fill color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fill"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererContext/fill(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fillRect:"
        }
      ],
      "role": "symbol",
      "title": "fill(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsrenderercontext/fill(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererFormat": {
      "abstract": [
        {
          "text": "A set of drawing attributes that represents the configuration of a graphics renderer context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGraphicsRendererFormat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGraphicsRendererFormat"
        }
      ],
      "role": "symbol",
      "title": "UIGraphicsRendererFormat",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsrendererformat"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererFormat/default()": {
      "abstract": [
        {
          "text": "Returns a format that represents the highest fidelity that the current device supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererFormat/default()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "defaultFormat"
        }
      ],
      "role": "symbol",
      "title": "default()",
      "type": "topic",
      "url": "/documentation/uikit/uigraphicsrendererformat/default()"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "https://developer.apple.com/library/archive/documentation/Miscellaneous/Conceptual/iPhoneOSTechOverview/iPhoneOSTechnologies/iPhoneOSTechnologies.html#//apple_ref/doc/uid/TP40007898-CH3-SW11": {
      "identifier": "https://developer.apple.com/library/archive/documentation/Miscellaneous/Conceptual/iPhoneOSTechOverview/iPhoneOSTechnologies/iPhoneOSTechnologies.html#//apple_ref/doc/uid/TP40007898-CH3-SW11",
      "title": "TextKit",
      "titleInlineContent": [
        {
          "text": "TextKit",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/Miscellaneous/Conceptual/iPhoneOSTechOverview/iPhoneOSTechnologies/iPhoneOSTechnologies.html#//apple_ref/doc/uid/TP40007898-CH3-SW11"
    },
    "https://developer.apple.com/library/archive/documentation/StringsTextFonts/Conceptual/TextAndWebiPhoneOS/LowerLevelText-HandlingTechnologies/LowerLevelText-HandlingTechnologies.html#//apple_ref/doc/uid/TP40009542-CH15-SW3": {
      "identifier": "https://developer.apple.com/library/archive/documentation/StringsTextFonts/Conceptual/TextAndWebiPhoneOS/LowerLevelText-HandlingTechnologies/LowerLevelText-HandlingTechnologies.html#//apple_ref/doc/uid/TP40009542-CH15-SW3",
      "title": "Core Text",
      "titleInlineContent": [
        {
          "text": "Core Text",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/StringsTextFonts/Conceptual/TextAndWebiPhoneOS/LowerLevelText-HandlingTechnologies/LowerLevelText-HandlingTechnologies.html#//apple_ref/doc/uid/TP40009542-CH15-SW3"
    },
    "media-2864001": {
      "alt": "Image of a PDF open in Preview, with the word “Hello!” rendered in large, black lettering in the top-left.",
      "identifier": "media-2864001",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/a1502445dbaa2ddde3045eaa89064476/media-2864001@2x.png"
        }
      ]
    },
    "media-2864003": {
      "alt": "Screenshot from Preview showing a 3-page PDF. Each page contains large black lettering which details the current page number.",
      "identifier": "media-2864003",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/69c0b1a8802e3a5f9e3d1cd2cfa64c77/media-2864003@2x.png"
        }
      ]
    },
    "media-2864256": {
      "alt": "Screenshot from Preview showing a 3-page PDFs with red links entitled “Next Page” at the bottom-right of each page.",
      "identifier": "media-2864256",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/9cae1cc7f0812418f8639b4d40da5e94/media-2864256@2x.png"
        }
      ]
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRenderer"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Graphics-contexts",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRenderer",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererContext",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererFormat",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererContext",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererContext",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererFormat"
      ],
      "title": "Graphics contexts"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-PDF-renderer",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer/init(bounds:format:)"
      ],
      "title": "Creating a PDF renderer"
    },
    {
      "anchor": "Managing-the-PDF-data",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer/pdfData(actions:)",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer/writePDF(to:withActions:)",
        "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer/DrawingActions"
      ],
      "title": "Managing the PDF data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIGraphicsPDFRenderer"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsPDFRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsPDFRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-PDF-renderer",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer/init(bounds:format:)"
              ],
              "title": "Creating a PDF renderer"
            },
            {
              "anchor": "Managing-the-PDF-data",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer/pdfData(actions:)",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer/writePDF(to:withActions:)",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRenderer/DrawingActions"
              ],
              "title": "Managing the PDF data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRenderer"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Graphics-contexts",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRenderer",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererContext",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRendererFormat",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRenderer",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererContext",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsImageRendererFormat",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererContext",
                "doc://com.apple.uikit/documentation/UIKit/UIGraphicsPDFRendererFormat"
              ],
              "title": "Graphics contexts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIGraphicsPDFRenderer"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGraphicsRenderer",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UIGraphicsRenderer",
                    "text": "UIGraphicsRenderer"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRendererContext~1addDestination(withName:at:)/title",
          "value": "addDestinationWithName:atPoint:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRendererContext~1addDestination(withName:at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addDestinationWithName:atPoint:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRenderer/title",
          "value": "UIGraphicsPDFRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsPDFRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsPDFRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRenderer~1DrawingActions/title",
          "value": "UIGraphicsPDFDrawingActions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRenderer~1DrawingActions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsPDFDrawingActions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRenderer~1DrawingActions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsPDFDrawingActions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRendererContext~1beginPage()/title",
          "value": "beginPage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRendererContext~1beginPage()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "beginPage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRenderer~1writePDF(to:withActions:)/title",
          "value": "writePDFToURL:withActions:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRenderer~1writePDF(to:withActions:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "writePDFToURL:withActions:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsstring/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRenderer~1init(bounds:format:)/title",
          "value": "initWithBounds:format:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRenderer~1init(bounds:format:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithBounds:format:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRenderer/title",
          "value": "UIGraphicsRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRenderer/title",
          "value": "UIGraphicsImageRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsImageRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsImageRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRendererFormat/title",
          "value": "UIGraphicsPDFRendererFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRendererFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsPDFRendererFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRendererFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsPDFRendererFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRendererContext~1setDestinationWithName(_:for:)/title",
          "value": "setDestinationWithName:forRect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRendererContext~1setDestinationWithName(_:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setDestinationWithName:forRect:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRendererContext~1fill(_:)/title",
          "value": "fillRect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRendererContext~1fill(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "fillRect:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRendererContext~1beginPage(withBounds:pageInfo:)/title",
          "value": "beginPageWithBounds:pageInfo:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRendererContext~1beginPage(withBounds:pageInfo:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "beginPageWithBounds:pageInfo:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRenderer~1pdfData(actions:)/title",
          "value": "PDFDataWithActions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRenderer~1pdfData(actions:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "PDFDataWithActions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRendererFormat~1default()/title",
          "value": "defaultFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRendererFormat~1default()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "defaultFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1coregraphics~1cgcontext~11455677-userspacetodevicespacetransform/title",
          "value": "CGContextGetUserSpaceToDeviceSpaceTransform"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRendererContext/title",
          "value": "UIGraphicsRendererContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRendererContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsRendererContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRendererContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsRendererContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRendererContext/title",
          "value": "UIGraphicsPDFRendererContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRendererContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsPDFRendererContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsPDFRendererContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsPDFRendererContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRendererContext/title",
          "value": "UIGraphicsImageRendererContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRendererContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsImageRendererContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRendererContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsImageRendererContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1coregraphics~1cgcontext/title",
          "value": "CGContextRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRendererFormat/title",
          "value": "UIGraphicsRendererFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRendererFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsRendererFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsRendererFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsRendererFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRendererFormat/title",
          "value": "UIGraphicsImageRendererFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRendererFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsImageRendererFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGraphicsImageRendererFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGraphicsImageRendererFormat"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uigraphicspdfrenderer"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uigraphicspdfrenderer"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
