{
  "abstract": [
    {
      "text": "The properties that a reader uses to decode images.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIImageReaderConfiguration"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIImageReaderConfiguration",
    "fragments": [
      {
        "kind": "identifier",
        "text": "UIImageReaderConfiguration"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIImageReaderConfiguration"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "UIImageReaderConfiguration"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIImageReaderConfiguration"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/imageWithCGImage:": {
      "abstract": [
        {
          "text": "Creates and returns an image object representing the specified Quartz image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "imageWithCGImage:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/imageWithCGImage:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageWithCGImage:"
        }
      ],
      "role": "symbol",
      "title": "imageWithCGImage:",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/imagewithcgimage:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/imageWithCGImage:scale:orientation:": {
      "abstract": [
        {
          "text": "Creates and returns an image object with the specified scale and orientation factors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "imageWithCGImage:scale:orientation:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/imageWithCGImage:scale:orientation:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageWithCGImage:scale:orientation:"
        }
      ],
      "role": "symbol",
      "title": "imageWithCGImage:scale:orientation:",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/imagewithcgimage:scale:orientation:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/imageWithCIImage:": {
      "abstract": [
        {
          "text": "Creates and returns an image object that contains a Core Image object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "imageWithCIImage:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/imageWithCIImage:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageWithCIImage:"
        }
      ],
      "role": "symbol",
      "title": "imageWithCIImage:",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/imagewithciimage:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/imageWithCIImage:scale:orientation:": {
      "abstract": [
        {
          "text": "Creates and returns an image object based on a Core Image object and the specified attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "imageWithCIImage:scale:orientation:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/imageWithCIImage:scale:orientation:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageWithCIImage:scale:orientation:"
        }
      ],
      "role": "symbol",
      "title": "imageWithCIImage:scale:orientation:",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/imagewithciimage:scale:orientation:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/imageWithContentsOfFile:": {
      "abstract": [
        {
          "text": "Creates and returns an image object by loading the image data from the file at the specified path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "imageWithContentsOfFile:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/imageWithContentsOfFile:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageWithContentsOfFile:"
        }
      ],
      "role": "symbol",
      "title": "imageWithContentsOfFile:",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/imagewithcontentsoffile:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/imageWithData:": {
      "abstract": [
        {
          "text": "Creates and returns an image object that uses the specified image data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "imageWithData:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/imageWithData:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageWithData:"
        }
      ],
      "role": "symbol",
      "title": "imageWithData:",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/imagewithdata:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/imageWithData:scale:": {
      "abstract": [
        {
          "text": "Creates and returns an image object that uses the specified image data and scale factor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "imageWithData:scale:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/imageWithData:scale:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "imageWithData:scale:"
        }
      ],
      "role": "symbol",
      "title": "imageWithData:scale:",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/imagewithdata:scale:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/init(cgImage:)": {
      "abstract": [
        {
          "text": "Initializes and returns the image object with the specified Quartz image reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "cgImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageRef",
          "text": "CGImage"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/init(cgImage:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCGImage:"
        }
      ],
      "role": "symbol",
      "title": "init(cgImage:)",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/init(cgimage:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/init(cgImage:scale:orientation:)": {
      "abstract": [
        {
          "text": "Initializes and returns an image object with the specified scale and orientation factors.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "cgImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageRef",
          "text": "CGImage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "scale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "orientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIImageOrientation",
          "text": "Orientation"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/init(cgImage:scale:orientation:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCGImage:scale:orientation:"
        }
      ],
      "role": "symbol",
      "title": "init(cgImage:scale:orientation:)",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/init(cgimage:scale:orientation:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/init(ciImage:)": {
      "abstract": [
        {
          "text": "Initializes and returns an image object with the specified Core Image object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ciImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CIImage",
          "text": "CIImage"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/init(ciImage:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCIImage:"
        }
      ],
      "role": "symbol",
      "title": "init(ciImage:)",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/init(ciimage:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/init(ciImage:scale:orientation:)": {
      "abstract": [
        {
          "text": "Initializes and returns an image object with the specified Core Image object and properties.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ciImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CIImage",
          "text": "CIImage"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "scale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "orientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIImageOrientation",
          "text": "Orientation"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/init(ciImage:scale:orientation:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCIImage:scale:orientation:"
        }
      ],
      "role": "symbol",
      "title": "init(ciImage:scale:orientation:)",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/init(ciimage:scale:orientation:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/init(contentsOfFile:)": {
      "abstract": [
        {
          "text": "Initializes and returns the image object with the contents of the specified file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "contentsOfFile"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/init(contentsOfFile:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithContentsOfFile:"
        }
      ],
      "role": "symbol",
      "title": "init(contentsOfFile:)",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/init(contentsoffile:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/init(data:)": {
      "abstract": [
        {
          "text": "Initializes and returns the image object with the specified data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/init(data:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithData:"
        }
      ],
      "role": "symbol",
      "title": "init(data:)",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/init(data:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage/init(data:scale:)": {
      "abstract": [
        {
          "text": "Initializes and returns the image object with the specified data and scale factor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "data"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "scale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage/init(data:scale:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithData:scale:"
        }
      ],
      "role": "symbol",
      "title": "init(data:scale:)",
      "type": "topic",
      "url": "/documentation/uikit/uiimage/init(data:scale:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImageReader-c.class": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIImageReader"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImageReader-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIImageReader",
      "type": "topic",
      "url": "/documentation/uikit/uiimagereader-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImageReaderConfiguration": {
      "abstract": [
        {
          "text": "The properties that a reader uses to decode images.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIImageReaderConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImageReaderConfiguration",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIImageReaderConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uiimagereaderconfiguration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImageReaderConfiguration/pixelsPerInch": {
      "abstract": [
        {
          "text": "The integral scale that the image reader applies to the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "pixelsPerInch"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImageReaderConfiguration/pixelsPerInch",
      "kind": "symbol",
      "role": "symbol",
      "title": "pixelsPerInch",
      "type": "topic",
      "url": "/documentation/uikit/uiimagereaderconfiguration/pixelsperinch"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImageReaderConfiguration/preferredThumbnailSize": {
      "abstract": [
        {
          "text": "The thumbnail size in pixels that the image reader makes the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "preferredThumbnailSize"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImageReaderConfiguration/preferredThumbnailSize",
      "kind": "symbol",
      "role": "symbol",
      "title": "preferredThumbnailSize",
      "type": "topic",
      "url": "/documentation/uikit/uiimagereaderconfiguration/preferredthumbnailsize"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImageReaderConfiguration/prefersHighDynamicRange": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the image reader should decode the image as HDR when the type is capable of decoding in either SDR or HDR.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "prefersHighDynamicRange"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImageReaderConfiguration/prefersHighDynamicRange",
      "kind": "symbol",
      "role": "symbol",
      "title": "prefersHighDynamicRange",
      "type": "topic",
      "url": "/documentation/uikit/uiimagereaderconfiguration/prefershighdynamicrange"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImageReaderConfiguration/preparesImagesForDisplay": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the image reader prepares the image for display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "preparesImagesForDisplay"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImageReaderConfiguration/preparesImagesForDisplay",
      "kind": "symbol",
      "role": "symbol",
      "title": "preparesImagesForDisplay",
      "type": "topic",
      "url": "/documentation/uikit/uiimagereaderconfiguration/preparesimagesfordisplay"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-and-initializing-image-objects",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIImage/imageWithContentsOfFile:",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/imageWithData:",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/imageWithData:scale:",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/imageWithCGImage:",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/imageWithCGImage:scale:orientation:",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/imageWithCIImage:",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/imageWithCIImage:scale:orientation:",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/init(contentsOfFile:)",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/init(data:)",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/init(data:scale:)",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/init(cgImage:)",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/init(cgImage:scale:orientation:)",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/init(ciImage:)",
        "doc://com.apple.uikit/documentation/UIKit/UIImage/init(ciImage:scale:orientation:)",
        "doc://com.apple.uikit/documentation/UIKit/UIImageReader-c.class"
      ],
      "title": "Creating and initializing image objects"
    }
  ],
  "topicSections": [
    {
      "anchor": "Configuration-properties",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIImageReaderConfiguration/prefersHighDynamicRange",
        "doc://com.apple.uikit/documentation/UIKit/UIImageReaderConfiguration/preferredThumbnailSize",
        "doc://com.apple.uikit/documentation/UIKit/UIImageReaderConfiguration/preparesImagesForDisplay",
        "doc://com.apple.uikit/documentation/UIKit/UIImageReaderConfiguration/pixelsPerInch"
      ],
      "title": "Configuration properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1init(ciImage:scale:orientation:)/title",
          "value": "initWithCIImage:scale:orientation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1init(ciImage:scale:orientation:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCIImage:scale:orientation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1init(data:)/title",
          "value": "initWithData:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1init(data:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithData:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1init(contentsOfFile:)/title",
          "value": "initWithContentsOfFile:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1init(contentsOfFile:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithContentsOfFile:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1init(data:scale:)/title",
          "value": "initWithData:scale:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1init(data:scale:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithData:scale:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1init(ciImage:)/title",
          "value": "initWithCIImage:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1init(ciImage:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCIImage:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1init(cgImage:)/title",
          "value": "initWithCGImage:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1init(cgImage:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCGImage:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1init(cgImage:scale:orientation:)/title",
          "value": "initWithCGImage:scale:orientation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage~1init(cgImage:scale:orientation:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCGImage:scale:orientation:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiimagereaderconfiguration"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
