{
  "abstract": [
    {
      "text": "An interaction for using Scribble to enter text by writing on a view that isn’t formally a text input.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteraction-2dap8"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIIndirectScribbleInteraction",
    "fragments": [
      {
        "kind": "identifier",
        "text": "UIIndirectScribbleInteraction"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIIndirectScribbleInteraction"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "UIIndirectScribbleInteraction"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIIndirectScribbleInteraction"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteraction-1nfjm",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " if your app has a view that looks to the user like a text input but doesn’t implement ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextInput",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". It makes the view act as a container of one or more virtual “text input elements”, each of which defines an area the user can write into without having to tap first.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Some example uses of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteraction-1nfjm",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " include:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A view that looks like a search or text field that in reality is a button, but when tapped installs a real text field.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A view that contains multiple virtual text fields which the user can normally tap and type into, but aren’t full blown text fields all the time.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteraction-1nfjm": {
      "abstract": [
        {
          "text": "An interaction for using Scribble to enter text by writing on a view that isn’t formally a text input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIIndirectScribbleInteraction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteraction-1nfjm",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIIndirectScribbleInteraction"
        }
      ],
      "role": "symbol",
      "title": "UIIndirectScribbleInteraction",
      "type": "topic",
      "url": "/documentation/uikit/uiindirectscribbleinteraction-1nfjm"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteraction-2dap8": {
      "abstract": [
        {
          "text": "An interaction for using Scribble to enter text by writing on a view that isn’t formally a text input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIIndirectScribbleInteraction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteraction-2dap8",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIIndirectScribbleInteraction",
      "type": "topic",
      "url": "/documentation/uikit/uiindirectscribbleinteraction-2dap8"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteraction-2dap8/delegate": {
      "abstract": [
        {
          "text": "The delegate for the interaction, to supply and customize writable elements in the interaction’s view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteraction-2dap8/delegate",
      "kind": "symbol",
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/uikit/uiindirectscribbleinteraction-2dap8/delegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteraction-2dap8/handlingWriting": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the user is actively writing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "handlingWriting"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteraction-2dap8/handlingWriting",
      "kind": "symbol",
      "role": "symbol",
      "title": "handlingWriting",
      "type": "topic",
      "url": "/documentation/uikit/uiindirectscribbleinteraction-2dap8/handlingwriting"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteraction-2dap8/initWithDelegate:": {
      "abstract": [
        {
          "text": "Creates an indirect Scribble interaction item with the specified delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithDelegate:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteraction-2dap8/initWithDelegate:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithDelegate:"
        }
      ],
      "role": "symbol",
      "title": "initWithDelegate:",
      "type": "topic",
      "url": "/documentation/uikit/uiindirectscribbleinteraction-2dap8/initwithdelegate:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteractionDelegate-3jmnk": {
      "abstract": [
        {
          "text": "Methods that customize behavior on views that aren’t formally text input views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIIndirectScribbleInteractionDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteractionDelegate-3jmnk",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIIndirectScribbleInteractionDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uiindirectscribbleinteractiondelegate-3jmnk"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIInteraction": {
      "abstract": [
        {
          "text": "The protocol that an interaction implements to access the view that owns it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIInteraction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIInteraction"
        }
      ],
      "role": "symbol",
      "title": "UIInteraction",
      "type": "topic",
      "url": "/documentation/uikit/uiinteraction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScribbleElementIdentifier": {
      "abstract": [
        {
          "text": "The element’s unique identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIScribbleElementIdentifier"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScribbleElementIdentifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIScribbleElementIdentifier",
      "type": "topic",
      "url": "/documentation/uikit/uiscribbleelementidentifier"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextInput": {
      "abstract": [
        {
          "text": "A set of methods for interacting with the text input system and enabling features in documents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextInput"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextInput"
        }
      ],
      "role": "symbol",
      "title": "UITextInput",
      "type": "topic",
      "url": "/documentation/uikit/uitextinput"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIInteraction"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Custom-views",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteractionDelegate-3jmnk",
        "doc://com.apple.uikit/documentation/UIKit/UIScribbleElementIdentifier"
      ],
      "title": "Custom views"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-an-indirect-Scribble-interaction",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteraction-2dap8/initWithDelegate:"
      ],
      "title": "Creating an indirect Scribble interaction"
    },
    {
      "anchor": "Managing-indirect-Scribble-interactions",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteraction-2dap8/delegate"
      ],
      "title": "Managing indirect Scribble interactions"
    },
    {
      "anchor": "Detecting-writing",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIIndirectScribbleInteraction-2dap8/handlingWriting"
      ],
      "title": "Detecting writing"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInteraction/title",
          "value": "UIInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInput/title",
          "value": "UITextInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextInput"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiindirectscribbleinteraction-2dap8"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
