{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIItemProviderPresentationSizeProviding"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UIItemProviderPresentationSizeProviding",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIItemProviderPresentationSizeProviding"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIItemProviderPresentationSizeProviding"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "UIItemProviderPresentationSizeProviding"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIItemProviderPresentationSizeProviding"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/nsitemprovider": {
      "abstract": [
        {
          "text": "An item provider for conveying data or a file between processes during drag-and-drop or copy-and-paste activities, or from a host app to an app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSItemProvider"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsitemprovider",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSItemProvider",
      "type": "topic",
      "url": "/documentation/foundation/nsitemprovider"
    },
    "doc://com.apple.documentation/documentation/foundation/nsitemproviderreading": {
      "abstract": [
        {
          "text": "The protocol for implementing a class to allow an item provider to create an instance of the class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSItemProviderReading"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsitemproviderreading",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSItemProviderReading",
      "type": "topic",
      "url": "/documentation/foundation/nsitemproviderreading"
    },
    "doc://com.apple.documentation/documentation/foundation/nsitemproviderwriting": {
      "abstract": [
        {
          "text": "The protocol for implementing a class to allow an item provider to retrieve data from an instance of the class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSItemProviderWriting"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsitemproviderwriting",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSItemProviderWriting",
      "type": "topic",
      "url": "/documentation/foundation/nsitemproviderwriting"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIImage": {
      "abstract": [
        {
          "text": "An object that manages image data in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIImage"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIImage"
        }
      ],
      "role": "symbol",
      "title": "UIImage",
      "type": "topic",
      "url": "/documentation/uikit/uiimage"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIItemProviderPresentationSizeProviding": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIItemProviderPresentationSizeProviding"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIItemProviderPresentationSizeProviding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIItemProviderPresentationSizeProviding"
        }
      ],
      "role": "symbol",
      "title": "UIItemProviderPresentationSizeProviding",
      "type": "topic",
      "url": "/documentation/uikit/uiitemproviderpresentationsizeproviding"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIItemProviderPresentationSizeProviding/preferredPresentationSizeForItemProvider": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredPresentationSizeForItemProvider"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIItemProviderPresentationSizeProviding/preferredPresentationSizeForItemProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredPresentationSizeForItemProvider"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "preferredPresentationSizeForItemProvider",
      "type": "topic",
      "url": "/documentation/uikit/uiitemproviderpresentationsizeproviding/preferredpresentationsizeforitemprovider"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIItemProviderReadingAugmentationDesignating": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIItemProviderReadingAugmentationDesignating"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIItemProviderReadingAugmentationDesignating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIItemProviderReadingAugmentationDesignating"
        }
      ],
      "role": "symbol",
      "title": "UIItemProviderReadingAugmentationDesignating",
      "type": "topic",
      "url": "/documentation/uikit/uiitemproviderreadingaugmentationdesignating"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIItemProviderReadingAugmentationProviding": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIItemProviderReadingAugmentationProviding"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIItemProviderReadingAugmentationProviding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIItemProviderReadingAugmentationProviding"
        }
      ],
      "role": "symbol",
      "title": "UIItemProviderReadingAugmentationProviding",
      "type": "topic",
      "url": "/documentation/uikit/uiitemproviderreadingaugmentationproviding"
    },
    "doc://com.apple.uikit/documentation/UIKit/data-delivery-with-drag-and-drop": {
      "abstract": [
        {
          "text": "Share data between iPad apps during a drag and drop operation using an item provider.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/data-delivery-with-drag-and-drop",
      "kind": "article",
      "role": "sampleCode",
      "title": "Data delivery with drag and drop",
      "type": "topic",
      "url": "/documentation/uikit/data-delivery-with-drag-and-drop"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIImage"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Item-providers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/data-delivery-with-drag-and-drop",
        "doc://com.apple.documentation/documentation/foundation/nsitemprovider",
        "doc://com.apple.documentation/documentation/foundation/nsitemproviderreading",
        "doc://com.apple.documentation/documentation/foundation/nsitemproviderwriting",
        "doc://com.apple.uikit/documentation/UIKit/UIItemProviderReadingAugmentationDesignating",
        "doc://com.apple.uikit/documentation/UIKit/UIItemProviderReadingAugmentationProviding"
      ],
      "title": "Item providers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Determining-the-presentation-size",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIItemProviderPresentationSizeProviding/preferredPresentationSizeForItemProvider"
      ],
      "title": "Determining the presentation size"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIItemProviderPresentationSizeProviding"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIItemProviderPresentationSizeProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIItemProviderPresentationSizeProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Determining-the-presentation-size",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIItemProviderPresentationSizeProviding/preferredPresentationSizeForItemProvider"
              ],
              "title": "Determining the presentation size"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIImage"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Item-providers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/data-delivery-with-drag-and-drop",
                "doc://com.apple.documentation/documentation/foundation/nsitemprovider",
                "doc://com.apple.documentation/documentation/foundation/nsitemproviderreading",
                "doc://com.apple.documentation/documentation/foundation/nsitemproviderwriting",
                "doc://com.apple.uikit/documentation/UIKit/UIItemProviderReadingAugmentationDesignating",
                "doc://com.apple.uikit/documentation/UIKit/UIItemProviderReadingAugmentationProviding"
              ],
              "title": "Item providers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIItemProviderPresentationSizeProviding"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIItemProviderPresentationSizeProviding~1preferredPresentationSizeForItemProvider/title",
          "value": "preferredPresentationSizeForItemProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIItemProviderPresentationSizeProviding~1preferredPresentationSizeForItemProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preferredPresentationSizeForItemProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIItemProviderPresentationSizeProviding/title",
          "value": "UIItemProviderPresentationSizeProviding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIItemProviderPresentationSizeProviding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIItemProviderPresentationSizeProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIItemProviderPresentationSizeProviding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIItemProviderPresentationSizeProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIItemProviderReadingAugmentationProviding/title",
          "value": "UIItemProviderReadingAugmentationProviding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIItemProviderReadingAugmentationProviding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIItemProviderReadingAugmentationProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIItemProviderReadingAugmentationProviding/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIItemProviderReadingAugmentationProviding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/title",
          "value": "UIImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIImage/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIItemProviderReadingAugmentationDesignating/title",
          "value": "UIItemProviderReadingAugmentationDesignating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIItemProviderReadingAugmentationDesignating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIItemProviderReadingAugmentationDesignating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIItemProviderReadingAugmentationDesignating/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIItemProviderReadingAugmentationDesignating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiitemproviderpresentationsizeproviding"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiitemproviderpresentationsizeproviding"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
