{
  "abstract": [
    {
      "text": "Macros that UIKit defines.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/views-and-controls"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/uikit-macros"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "UIKit macros"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/IBSegueAction": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IBSegueAction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/IBSegueAction",
      "kind": "symbol",
      "role": "symbol",
      "title": "IBSegueAction",
      "type": "topic",
      "url": "/documentation/uikit/ibsegueaction"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSDirectionalEdgeInsets": {
      "abstract": [
        {
          "text": "The inset distances for views, taking the user interface layout direction into account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDirectionalEdgeInsets"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSDirectionalEdgeInsets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDirectionalEdgeInsets"
        }
      ],
      "role": "symbol",
      "title": "NSDirectionalEdgeInsets",
      "type": "topic",
      "url": "/documentation/uikit/nsdirectionaledgeinsets"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge": {
      "abstract": [
        {
          "text": "Constants that specify an edge or a set of edges, taking the user interface layout direction into account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSDirectionalRectEdge"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSDirectionalRectEdge"
        }
      ],
      "role": "symbol",
      "title": "NSDirectionalRectEdge",
      "type": "topic",
      "url": "/documentation/uikit/nsdirectionalrectedge"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLAYOUTANCHOR_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSLAYOUTANCHOR_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLAYOUTANCHOR_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLAYOUTANCHOR_EXTERN",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutanchor_extern"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLAYOUTCONSTRAINT_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSLAYOUTCONSTRAINT_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLAYOUTCONSTRAINT_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLAYOUTCONSTRAINT_EXTERN",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint_extern"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment": {
      "abstract": [
        {
          "text": "Constants that specify alignment to an edge or a set of edges depending on the user interface layout direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSRectAlignment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSRectAlignment"
        }
      ],
      "role": "symbol",
      "title": "NSRectAlignment",
      "type": "topic",
      "url": "/documentation/uikit/nsrectalignment"
    },
    "doc://com.apple.uikit/documentation/UIKit/Preview(_:traits:body:)-c7kr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "macro"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Preview"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "traits"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:21DeveloperToolsSupport12PreviewTraitV",
          "text": "PreviewTrait"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:21DeveloperToolsSupport7PreviewV",
          "text": "Preview"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:21DeveloperToolsSupport7PreviewV10ViewTraitsO",
          "text": "ViewTraits"
        },
        {
          "kind": "text",
          "text": ">..., "
        },
        {
          "kind": "externalParam",
          "text": "body"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/Preview(_:traits:body:)-c7kr",
      "kind": "symbol",
      "role": "symbol",
      "title": "Preview(_:traits:body:)",
      "type": "topic",
      "url": "/documentation/uikit/preview(_:traits:body:)-c7kr"
    },
    "doc://com.apple.uikit/documentation/UIKit/Preview(_:traits:body:)-en9c": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "macro"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Preview"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "traits"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:21DeveloperToolsSupport12PreviewTraitV",
          "text": "PreviewTrait"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:21DeveloperToolsSupport7PreviewV",
          "text": "Preview"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:21DeveloperToolsSupport7PreviewV10ViewTraitsO",
          "text": "ViewTraits"
        },
        {
          "kind": "text",
          "text": ">..., "
        },
        {
          "kind": "externalParam",
          "text": "body"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/Preview(_:traits:body:)-en9c",
      "kind": "symbol",
      "role": "symbol",
      "title": "Preview(_:traits:body:)",
      "type": "topic",
      "url": "/documentation/uikit/preview(_:traits:body:)-en9c"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAxis": {
      "abstract": [
        {
          "text": "A structure that specifies the layout axes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAxis"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAxis",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAxis"
        }
      ],
      "role": "symbol",
      "title": "UIAxis",
      "type": "topic",
      "url": "/documentation/uikit/uiaxis"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge": {
      "abstract": [
        {
          "text": "Constants that specify an edge or a set of edges, taking the user interface layout direction into account.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDirectionalRectEdge"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDirectionalRectEdge"
        }
      ],
      "role": "symbol",
      "title": "UIDirectionalRectEdge",
      "type": "topic",
      "url": "/documentation/uikit/uidirectionalrectedge"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIEdgeInsets": {
      "abstract": [
        {
          "text": "The inset distances for views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIEdgeInsets"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIEdgeInsets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIEdgeInsets"
        }
      ],
      "role": "symbol",
      "title": "UIEdgeInsets",
      "type": "topic",
      "url": "/documentation/uikit/uiedgeinsets"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKIT_AVAILABLE_IOS_ONLY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIKIT_AVAILABLE_IOS_ONLY"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKIT_AVAILABLE_IOS_ONLY",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIKIT_AVAILABLE_IOS_ONLY",
      "type": "topic",
      "url": "/documentation/uikit/uikit_available_ios_only"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKIT_AVAILABLE_IOS_TVOS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIKIT_AVAILABLE_IOS_TVOS"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKIT_AVAILABLE_IOS_TVOS",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIKIT_AVAILABLE_IOS_TVOS",
      "type": "topic",
      "url": "/documentation/uikit/uikit_available_ios_tvos"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKIT_AVAILABLE_IOS_WATCHOS_TVOS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIKIT_AVAILABLE_IOS_WATCHOS_TVOS"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKIT_AVAILABLE_IOS_WATCHOS_TVOS",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIKIT_AVAILABLE_IOS_WATCHOS_TVOS",
      "type": "topic",
      "url": "/documentation/uikit/uikit_available_ios_watchos_tvos"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKIT_AVAILABLE_TVOS_ONLY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIKIT_AVAILABLE_TVOS_ONLY"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKIT_AVAILABLE_TVOS_ONLY",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIKIT_AVAILABLE_TVOS_ONLY",
      "type": "topic",
      "url": "/documentation/uikit/uikit_available_tvos_only"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKIT_AVAILABLE_WATCHOS_ONLY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIKIT_AVAILABLE_WATCHOS_ONLY"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKIT_AVAILABLE_WATCHOS_ONLY",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIKIT_AVAILABLE_WATCHOS_ONLY",
      "type": "topic",
      "url": "/documentation/uikit/uikit_available_watchos_only"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKIT_CLASS_AVAILABLE_IOS_ONLY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIKIT_CLASS_AVAILABLE_IOS_ONLY"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKIT_CLASS_AVAILABLE_IOS_ONLY",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIKIT_CLASS_AVAILABLE_IOS_ONLY",
      "type": "topic",
      "url": "/documentation/uikit/uikit_class_available_ios_only"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKIT_CLASS_AVAILABLE_IOS_TVOS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIKIT_CLASS_AVAILABLE_IOS_TVOS"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKIT_CLASS_AVAILABLE_IOS_TVOS",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIKIT_CLASS_AVAILABLE_IOS_TVOS",
      "type": "topic",
      "url": "/documentation/uikit/uikit_class_available_ios_tvos"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKIT_CLASS_AVAILABLE_IOS_WATCHOS_TVOS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIKIT_CLASS_AVAILABLE_IOS_WATCHOS_TVOS"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKIT_CLASS_AVAILABLE_IOS_WATCHOS_TVOS",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIKIT_CLASS_AVAILABLE_IOS_WATCHOS_TVOS",
      "type": "topic",
      "url": "/documentation/uikit/uikit_class_available_ios_watchos_tvos"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKIT_CLASS_AVAILABLE_TVOS_ONLY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIKIT_CLASS_AVAILABLE_TVOS_ONLY"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKIT_CLASS_AVAILABLE_TVOS_ONLY",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIKIT_CLASS_AVAILABLE_TVOS_ONLY",
      "type": "topic",
      "url": "/documentation/uikit/uikit_class_available_tvos_only"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKIT_CLASS_AVAILABLE_WATCHOS_ONLY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIKIT_CLASS_AVAILABLE_WATCHOS_ONLY"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKIT_CLASS_AVAILABLE_WATCHOS_ONLY",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIKIT_CLASS_AVAILABLE_WATCHOS_ONLY",
      "type": "topic",
      "url": "/documentation/uikit/uikit_class_available_watchos_only"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKIT_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIKIT_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKIT_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIKIT_EXTERN",
      "type": "topic",
      "url": "/documentation/uikit/uikit_extern"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKIT_EXTERN_C_BEGIN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIKIT_EXTERN_C_BEGIN"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKIT_EXTERN_C_BEGIN",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIKIT_EXTERN_C_BEGIN",
      "type": "topic",
      "url": "/documentation/uikit/uikit_extern_c_begin"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKIT_EXTERN_C_END": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIKIT_EXTERN_C_END"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKIT_EXTERN_C_END",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIKIT_EXTERN_C_END",
      "type": "topic",
      "url": "/documentation/uikit/uikit_extern_c_end"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKIT_HAS_UIFOUNDATION_SYMBOLS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIKIT_HAS_UIFOUNDATION_SYMBOLS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKIT_HAS_UIFOUNDATION_SYMBOLS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKIT_HAS_UIFOUNDATION_SYMBOLS"
        }
      ],
      "role": "symbol",
      "title": "UIKIT_HAS_UIFOUNDATION_SYMBOLS",
      "type": "topic",
      "url": "/documentation/uikit/uikit_has_uifoundation_symbols"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKIT_STATIC_INLINE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIKIT_STATIC_INLINE"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKIT_STATIC_INLINE",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIKIT_STATIC_INLINE",
      "type": "topic",
      "url": "/documentation/uikit/uikit_static_inline"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKIT_SWIFT_FORWARD_DECLARE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIKIT_SWIFT_FORWARD_DECLARE"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKIT_SWIFT_FORWARD_DECLARE",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIKIT_SWIFT_FORWARD_DECLARE",
      "type": "topic",
      "url": "/documentation/uikit/uikit_swift_forward_declare"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIOffset": {
      "abstract": [
        {
          "text": "A structure that specifies an amount to offset a position.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIOffset"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIOffset",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIOffset"
        }
      ],
      "role": "symbol",
      "title": "UIOffset",
      "type": "topic",
      "url": "/documentation/uikit/uioffset"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewCellStateEditingMask": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITableViewCellStateEditingMask"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewCellStateEditingMask",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITableViewCellStateEditingMask",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcellstateeditingmask"
    },
    "doc://com.apple.uikit/documentation/UIKit/views-and-controls": {
      "abstract": [
        {
          "text": "Present your content onscreen and define the interactions allowed with that content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/views-and-controls",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Views and controls",
      "type": "topic",
      "url": "/documentation/uikit/views-and-controls"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIOffset",
        "doc://com.apple.uikit/documentation/UIKit/UIAxis",
        "doc://com.apple.uikit/documentation/UIKit/UIEdgeInsets",
        "doc://com.apple.uikit/documentation/UIKit/NSDirectionalEdgeInsets",
        "doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge",
        "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment",
        "doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge"
      ],
      "title": "Related types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Macros",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/Preview(_:traits:body:)-c7kr",
        "doc://com.apple.uikit/documentation/UIKit/Preview(_:traits:body:)-en9c",
        "doc://com.apple.uikit/documentation/UIKit/UIKIT_HAS_UIFOUNDATION_SYMBOLS"
      ],
      "title": "Macros"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Macros",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/IBSegueAction",
                "doc://com.apple.uikit/documentation/UIKit/NSLAYOUTANCHOR_EXTERN",
                "doc://com.apple.uikit/documentation/UIKit/NSLAYOUTCONSTRAINT_EXTERN",
                "doc://com.apple.uikit/documentation/UIKit/UIKIT_AVAILABLE_IOS_ONLY",
                "doc://com.apple.uikit/documentation/UIKit/UIKIT_AVAILABLE_IOS_TVOS",
                "doc://com.apple.uikit/documentation/UIKit/UIKIT_AVAILABLE_IOS_WATCHOS_TVOS",
                "doc://com.apple.uikit/documentation/UIKit/UIKIT_AVAILABLE_TVOS_ONLY",
                "doc://com.apple.uikit/documentation/UIKit/UIKIT_AVAILABLE_WATCHOS_ONLY",
                "doc://com.apple.uikit/documentation/UIKit/UIKIT_CLASS_AVAILABLE_IOS_ONLY",
                "doc://com.apple.uikit/documentation/UIKit/UIKIT_CLASS_AVAILABLE_IOS_TVOS",
                "doc://com.apple.uikit/documentation/UIKit/UIKIT_CLASS_AVAILABLE_IOS_WATCHOS_TVOS",
                "doc://com.apple.uikit/documentation/UIKit/UIKIT_CLASS_AVAILABLE_TVOS_ONLY",
                "doc://com.apple.uikit/documentation/UIKit/UIKIT_CLASS_AVAILABLE_WATCHOS_ONLY",
                "doc://com.apple.uikit/documentation/UIKit/UIKIT_EXTERN",
                "doc://com.apple.uikit/documentation/UIKit/UIKIT_EXTERN_C_BEGIN",
                "doc://com.apple.uikit/documentation/UIKit/UIKIT_EXTERN_C_END",
                "doc://com.apple.uikit/documentation/UIKit/UIKIT_HAS_UIFOUNDATION_SYMBOLS",
                "doc://com.apple.uikit/documentation/UIKit/UIKIT_STATIC_INLINE",
                "doc://com.apple.uikit/documentation/UIKit/UIKIT_SWIFT_FORWARD_DECLARE",
                "doc://com.apple.uikit/documentation/UIKit/UITableViewCellStateEditingMask"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIOffset",
                "doc://com.apple.uikit/documentation/UIKit/UIAxis",
                "doc://com.apple.uikit/documentation/UIKit/UIEdgeInsets",
                "doc://com.apple.uikit/documentation/UIKit/NSDirectionalEdgeInsets",
                "doc://com.apple.uikit/documentation/UIKit/NSDirectionalRectEdge",
                "doc://com.apple.uikit/documentation/UIKit/NSRectAlignment",
                "doc://com.apple.uikit/documentation/UIKit/UIDirectionalRectEdge"
              ],
              "title": "Related types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment/title",
          "value": "NSRectAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRectAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSRectAlignment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSRectAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEdgeInsets/title",
          "value": "UIEdgeInsets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEdgeInsets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEdgeInsets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIEdgeInsets/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIEdgeInsets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDirectionalRectEdge/title",
          "value": "UIDirectionalRectEdge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDirectionalRectEdge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDirectionalRectEdge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDirectionalRectEdge/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDirectionalRectEdge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSDirectionalRectEdge/title",
          "value": "NSDirectionalRectEdge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSDirectionalRectEdge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDirectionalRectEdge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSDirectionalRectEdge/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDirectionalRectEdge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKIT_HAS_UIFOUNDATION_SYMBOLS/title",
          "value": "UIKIT_HAS_UIFOUNDATION_SYMBOLS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKIT_HAS_UIFOUNDATION_SYMBOLS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKIT_HAS_UIFOUNDATION_SYMBOLS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAxis/title",
          "value": "UIAxis"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAxis/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAxis"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAxis/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAxis"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSDirectionalEdgeInsets/title",
          "value": "NSDirectionalEdgeInsets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSDirectionalEdgeInsets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDirectionalEdgeInsets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSDirectionalEdgeInsets/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSDirectionalEdgeInsets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIOffset/title",
          "value": "UIOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIOffset/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIOffset/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIOffset"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uikit-macros"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uikit-macros"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
