{
  "abstract": [
    {
      "text": "Apply physics-based animations to your views.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/animation-and-haptics"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/uikit-dynamics"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "UIKit Dynamics"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior": {
      "abstract": [
        {
          "text": "A relationship between two dynamic items, or between a dynamic item and an anchor point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAttachmentBehavior"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAttachmentBehavior"
        }
      ],
      "role": "symbol",
      "title": "UIAttachmentBehavior",
      "type": "topic",
      "url": "/documentation/uikit/uiattachmentbehavior"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior": {
      "abstract": [
        {
          "text": "An object that confers to a specified array of dynamic items the ability to engage in collisions with each other and with the behavior’s specified boundaries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollisionBehavior"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollisionBehavior"
        }
      ],
      "role": "symbol",
      "title": "UICollisionBehavior",
      "type": "topic",
      "url": "/documentation/uikit/uicollisionbehavior"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDynamicAnimator": {
      "abstract": [
        {
          "text": "An object that provides physics-related capabilities and animations for its dynamic items, and provides the context for those animations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDynamicAnimator"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDynamicAnimator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDynamicAnimator"
        }
      ],
      "role": "symbol",
      "title": "UIDynamicAnimator",
      "type": "topic",
      "url": "/documentation/uikit/uidynamicanimator"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDynamicBehavior": {
      "abstract": [
        {
          "text": "An object that confers a behavioral configuration on one or more dynamic items, for their participation in 2D animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDynamicBehavior"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDynamicBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDynamicBehavior"
        }
      ],
      "role": "symbol",
      "title": "UIDynamicBehavior",
      "type": "topic",
      "url": "/documentation/uikit/uidynamicbehavior"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDynamicItem": {
      "abstract": [
        {
          "text": "A set of methods that can make a custom object eligible to participate in UIKit Dynamics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDynamicItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDynamicItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDynamicItem"
        }
      ],
      "role": "symbol",
      "title": "UIDynamicItem",
      "type": "topic",
      "url": "/documentation/uikit/uidynamicitem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDynamicItemBehavior": {
      "abstract": [
        {
          "text": "A base dynamic animation configuration for one or more dynamic items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDynamicItemBehavior"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDynamicItemBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDynamicItemBehavior"
        }
      ],
      "role": "symbol",
      "title": "UIDynamicItemBehavior",
      "type": "topic",
      "url": "/documentation/uikit/uidynamicitembehavior"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDynamicItemGroup": {
      "abstract": [
        {
          "text": "A dynamic item that comprises multiple other dynamic items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDynamicItemGroup"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDynamicItemGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDynamicItemGroup"
        }
      ],
      "role": "symbol",
      "title": "UIDynamicItemGroup",
      "type": "topic",
      "url": "/documentation/uikit/uidynamicitemgroup"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFieldBehavior": {
      "abstract": [
        {
          "text": "An object that applies field-based physics to dynamic items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFieldBehavior"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFieldBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFieldBehavior"
        }
      ],
      "role": "symbol",
      "title": "UIFieldBehavior",
      "type": "topic",
      "url": "/documentation/uikit/uifieldbehavior"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGravityBehavior": {
      "abstract": [
        {
          "text": "An object that applies a gravity-like force to all of its associated dynamic items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGravityBehavior"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGravityBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGravityBehavior"
        }
      ],
      "role": "symbol",
      "title": "UIGravityBehavior",
      "type": "topic",
      "url": "/documentation/uikit/uigravitybehavior"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPushBehavior": {
      "abstract": [
        {
          "text": "A behavior that applies a continuous or instantaneous force to one or more dynamic items, causing those items to change position accordingly.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPushBehavior"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPushBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPushBehavior"
        }
      ],
      "role": "symbol",
      "title": "UIPushBehavior",
      "type": "topic",
      "url": "/documentation/uikit/uipushbehavior"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIRegion": {
      "abstract": [
        {
          "text": "A shape for use in UIKit Dynamics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIRegion"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIRegion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIRegion"
        }
      ],
      "role": "symbol",
      "title": "UIRegion",
      "type": "topic",
      "url": "/documentation/uikit/uiregion"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISnapBehavior": {
      "abstract": [
        {
          "text": "A spring-like behavior whose initial motion is damped over time so that the object settles at a specific point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISnapBehavior"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISnapBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISnapBehavior"
        }
      ],
      "role": "symbol",
      "title": "UISnapBehavior",
      "type": "topic",
      "url": "/documentation/uikit/uisnapbehavior"
    },
    "doc://com.apple.uikit/documentation/UIKit/animation-and-haptics": {
      "abstract": [
        {
          "text": "Provide feedback to users using view-based animations and haptics.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/animation-and-haptics",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Animation and haptics",
      "type": "topic",
      "url": "/documentation/uikit/animation-and-haptics"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Dynamic-animators",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIDynamicAnimator"
      ],
      "title": "Dynamic animators"
    },
    {
      "anchor": "Dynamic-Items",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIDynamicItem",
        "doc://com.apple.uikit/documentation/UIKit/UIDynamicItemBehavior",
        "doc://com.apple.uikit/documentation/UIKit/UIDynamicItemGroup"
      ],
      "title": "Dynamic Items"
    },
    {
      "anchor": "Behaviors",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIDynamicBehavior",
        "doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior",
        "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior",
        "doc://com.apple.uikit/documentation/UIKit/UIFieldBehavior",
        "doc://com.apple.uikit/documentation/UIKit/UIGravityBehavior",
        "doc://com.apple.uikit/documentation/UIKit/UIPushBehavior",
        "doc://com.apple.uikit/documentation/UIKit/UISnapBehavior"
      ],
      "title": "Behaviors"
    },
    {
      "anchor": "Animation-regions",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIRegion"
      ],
      "title": "Animation regions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Dynamic-animators",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIDynamicAnimator"
              ],
              "title": "Dynamic animators"
            },
            {
              "anchor": "Dynamic-Items",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIDynamicItem",
                "doc://com.apple.uikit/documentation/UIKit/UIDynamicItemBehavior",
                "doc://com.apple.uikit/documentation/UIKit/UIDynamicItemGroup"
              ],
              "title": "Dynamic Items"
            },
            {
              "anchor": "Behaviors",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIDynamicBehavior",
                "doc://com.apple.uikit/documentation/UIKit/UIAttachmentBehavior",
                "doc://com.apple.uikit/documentation/UIKit/UICollisionBehavior",
                "doc://com.apple.uikit/documentation/UIKit/UIFieldBehavior",
                "doc://com.apple.uikit/documentation/UIKit/UIGravityBehavior",
                "doc://com.apple.uikit/documentation/UIKit/UIPushBehavior",
                "doc://com.apple.uikit/documentation/UIKit/UISnapBehavior"
              ],
              "title": "Behaviors"
            },
            {
              "anchor": "Animation-regions",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIRegion"
              ],
              "title": "Animation regions"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRegion/title",
          "value": "UIRegion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRegion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRegion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIRegion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehavior/title",
          "value": "UICollisionBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollisionBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollisionBehavior/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollisionBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicAnimator/title",
          "value": "UIDynamicAnimator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicAnimator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDynamicAnimator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicAnimator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDynamicAnimator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGravityBehavior/title",
          "value": "UIGravityBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGravityBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGravityBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGravityBehavior/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGravityBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPushBehavior/title",
          "value": "UIPushBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPushBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPushBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPushBehavior/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPushBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicItemGroup/title",
          "value": "UIDynamicItemGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicItemGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDynamicItemGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicItemGroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDynamicItemGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior/title",
          "value": "UIAttachmentBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAttachmentBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAttachmentBehavior/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAttachmentBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFieldBehavior/title",
          "value": "UIFieldBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFieldBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFieldBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFieldBehavior/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFieldBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicBehavior/title",
          "value": "UIDynamicBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDynamicBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicBehavior/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDynamicBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicItem/title",
          "value": "UIDynamicItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDynamicItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDynamicItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISnapBehavior/title",
          "value": "UISnapBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISnapBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISnapBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISnapBehavior/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISnapBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicItemBehavior/title",
          "value": "UIDynamicItemBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicItemBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDynamicItemBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDynamicItemBehavior/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDynamicItemBehavior"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uikit-dynamics"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uikit-dynamics"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
