{
  "abstract": [
    {
      "text": "The UIKit framework defines a number of functions, many of them used in graphics and drawing operations.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/uikit-functions"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "UIKit Functions"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientationIsLandscape(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDeviceOrientationIsLandscape"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIDeviceOrientation",
          "text": "UIDeviceOrientation"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientationIsLandscape(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIDeviceOrientationIsLandscape(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uideviceorientationislandscape(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientationIsPortrait(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDeviceOrientationIsPortrait"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIDeviceOrientation",
          "text": "UIDeviceOrientation"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientationIsPortrait(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIDeviceOrientationIsPortrait(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uideviceorientationisportrait(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientationIsValidInterfaceOrientation(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDeviceOrientationIsValidInterfaceOrientation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIDeviceOrientation",
          "text": "UIDeviceOrientation"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientationIsValidInterfaceOrientation(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIDeviceOrientationIsValidInterfaceOrientation(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uideviceorientationisvalidinterfaceorientation(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIInterfaceOrientationIsLandscape(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIInterfaceOrientationIsLandscape"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIInterfaceOrientation",
          "text": "UIInterfaceOrientation"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIInterfaceOrientationIsLandscape(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIInterfaceOrientationIsLandscape(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiinterfaceorientationislandscape(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIInterfaceOrientationIsPortrait(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIInterfaceOrientationIsPortrait"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIInterfaceOrientation",
          "text": "UIInterfaceOrientation"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIInterfaceOrientationIsPortrait(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIInterfaceOrientationIsPortrait(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiinterfaceorientationisportrait(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWritingToolsCoordinatorTextAnimationDebugDescription(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIWritingToolsCoordinatorTextAnimationDebugDescription"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIWritingToolsCoordinator",
          "text": "UIWritingToolsCoordinator"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIWritingToolsCoordinatorTextAnimation",
          "text": "TextAnimation"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWritingToolsCoordinatorTextAnimationDebugDescription(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWritingToolsCoordinatorTextAnimationDebugDescription"
        }
      ],
      "role": "symbol",
      "title": "UIWritingToolsCoordinatorTextAnimationDebugDescription(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiwritingtoolscoordinatortextanimationdebugdescription(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/uikit-constants": {
      "abstract": [
        {
          "text": "This document describes constants that are used throughout the UIKit framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/uikit-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "UIKit Constants",
      "type": "topic",
      "url": "/documentation/uikit/uikit-constants"
    },
    "doc://com.apple.uikit/documentation/UIKit/uikit-data-types": {
      "abstract": [
        {
          "text": "The UIKit framework defines data types that are used in multiple places throughout the framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/uikit-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "UIKit Data Types",
      "type": "topic",
      "url": "/documentation/uikit/uikit-data-types"
    },
    "doc://com.apple.uikit/documentation/UIKit/uikit-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/uikit-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "UIKit Enumerations",
      "type": "topic",
      "url": "/documentation/uikit/uikit-enumerations"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/uikit-enumerations",
        "doc://com.apple.uikit/documentation/UIKit/uikit-constants",
        "doc://com.apple.uikit/documentation/UIKit/uikit-data-types"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Functions",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientationIsLandscape(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientationIsPortrait(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIDeviceOrientationIsValidInterfaceOrientation(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIInterfaceOrientationIsLandscape(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIInterfaceOrientationIsPortrait(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIWritingToolsCoordinatorTextAnimationDebugDescription(_:)"
      ],
      "title": "Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Functions",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIWritingToolsCoordinatorTextAnimationDebugDescription(_:)"
              ],
              "title": "Functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/uikit-enumerations",
                "doc://com.apple.uikit/documentation/UIKit/uikit-constants",
                "doc://com.apple.uikit/documentation/UIKit/uikit-data-types"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWritingToolsCoordinatorTextAnimationDebugDescription(_:)/title",
          "value": "UIWritingToolsCoordinatorTextAnimationDebugDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWritingToolsCoordinatorTextAnimationDebugDescription(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWritingToolsCoordinatorTextAnimationDebugDescription"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uikit-functions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uikit-functions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
