{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIKIT_HAS_UIFOUNDATION_SYMBOLS"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@macro@UIKIT_HAS_UIFOUNDATION_SYMBOLS",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIKIT_HAS_UIFOUNDATION_SYMBOLS"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int32V",
        "text": "Int32"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIKIT_HAS_UIFOUNDATION_SYMBOLS"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "UIKIT_HAS_UIFOUNDATION_SYMBOLS"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIKIT_HAS_UIFOUNDATION_SYMBOLS"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int32V",
              "text": "Int32"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/IBSegueAction": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "IBSegueAction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/IBSegueAction",
      "kind": "symbol",
      "role": "symbol",
      "title": "IBSegueAction",
      "type": "topic",
      "url": "/documentation/uikit/ibsegueaction"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLAYOUTANCHOR_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSLAYOUTANCHOR_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLAYOUTANCHOR_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLAYOUTANCHOR_EXTERN",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutanchor_extern"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLAYOUTCONSTRAINT_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSLAYOUTCONSTRAINT_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLAYOUTCONSTRAINT_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSLAYOUTCONSTRAINT_EXTERN",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint_extern"
    },
    "doc://com.apple.uikit/documentation/UIKit/Preview(_:traits:body:)-c7kr": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "macro"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Preview"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "traits"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:21DeveloperToolsSupport12PreviewTraitV",
          "text": "PreviewTrait"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:21DeveloperToolsSupport7PreviewV",
          "text": "Preview"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:21DeveloperToolsSupport7PreviewV10ViewTraitsO",
          "text": "ViewTraits"
        },
        {
          "kind": "text",
          "text": ">..., "
        },
        {
          "kind": "externalParam",
          "text": "body"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/Preview(_:traits:body:)-c7kr",
      "kind": "symbol",
      "role": "symbol",
      "title": "Preview(_:traits:body:)",
      "type": "topic",
      "url": "/documentation/uikit/preview(_:traits:body:)-c7kr"
    },
    "doc://com.apple.uikit/documentation/UIKit/Preview(_:traits:body:)-en9c": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "macro"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Preview"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "traits"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:21DeveloperToolsSupport12PreviewTraitV",
          "text": "PreviewTrait"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:21DeveloperToolsSupport7PreviewV",
          "text": "Preview"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:21DeveloperToolsSupport7PreviewV10ViewTraitsO",
          "text": "ViewTraits"
        },
        {
          "kind": "text",
          "text": ">..., "
        },
        {
          "kind": "externalParam",
          "text": "body"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/Preview(_:traits:body:)-en9c",
      "kind": "symbol",
      "role": "symbol",
      "title": "Preview(_:traits:body:)",
      "type": "topic",
      "url": "/documentation/uikit/preview(_:traits:body:)-en9c"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKIT_AVAILABLE_IOS_ONLY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIKIT_AVAILABLE_IOS_ONLY"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKIT_AVAILABLE_IOS_ONLY",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIKIT_AVAILABLE_IOS_ONLY",
      "type": "topic",
      "url": "/documentation/uikit/uikit_available_ios_only"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKIT_AVAILABLE_IOS_TVOS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIKIT_AVAILABLE_IOS_TVOS"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKIT_AVAILABLE_IOS_TVOS",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIKIT_AVAILABLE_IOS_TVOS",
      "type": "topic",
      "url": "/documentation/uikit/uikit_available_ios_tvos"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKIT_AVAILABLE_IOS_WATCHOS_TVOS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIKIT_AVAILABLE_IOS_WATCHOS_TVOS"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKIT_AVAILABLE_IOS_WATCHOS_TVOS",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIKIT_AVAILABLE_IOS_WATCHOS_TVOS",
      "type": "topic",
      "url": "/documentation/uikit/uikit_available_ios_watchos_tvos"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKIT_AVAILABLE_TVOS_ONLY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIKIT_AVAILABLE_TVOS_ONLY"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKIT_AVAILABLE_TVOS_ONLY",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIKIT_AVAILABLE_TVOS_ONLY",
      "type": "topic",
      "url": "/documentation/uikit/uikit_available_tvos_only"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKIT_AVAILABLE_WATCHOS_ONLY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIKIT_AVAILABLE_WATCHOS_ONLY"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKIT_AVAILABLE_WATCHOS_ONLY",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIKIT_AVAILABLE_WATCHOS_ONLY",
      "type": "topic",
      "url": "/documentation/uikit/uikit_available_watchos_only"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKIT_CLASS_AVAILABLE_IOS_ONLY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIKIT_CLASS_AVAILABLE_IOS_ONLY"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKIT_CLASS_AVAILABLE_IOS_ONLY",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIKIT_CLASS_AVAILABLE_IOS_ONLY",
      "type": "topic",
      "url": "/documentation/uikit/uikit_class_available_ios_only"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKIT_CLASS_AVAILABLE_IOS_TVOS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIKIT_CLASS_AVAILABLE_IOS_TVOS"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKIT_CLASS_AVAILABLE_IOS_TVOS",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIKIT_CLASS_AVAILABLE_IOS_TVOS",
      "type": "topic",
      "url": "/documentation/uikit/uikit_class_available_ios_tvos"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKIT_CLASS_AVAILABLE_IOS_WATCHOS_TVOS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIKIT_CLASS_AVAILABLE_IOS_WATCHOS_TVOS"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKIT_CLASS_AVAILABLE_IOS_WATCHOS_TVOS",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIKIT_CLASS_AVAILABLE_IOS_WATCHOS_TVOS",
      "type": "topic",
      "url": "/documentation/uikit/uikit_class_available_ios_watchos_tvos"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKIT_CLASS_AVAILABLE_TVOS_ONLY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIKIT_CLASS_AVAILABLE_TVOS_ONLY"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKIT_CLASS_AVAILABLE_TVOS_ONLY",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIKIT_CLASS_AVAILABLE_TVOS_ONLY",
      "type": "topic",
      "url": "/documentation/uikit/uikit_class_available_tvos_only"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKIT_CLASS_AVAILABLE_WATCHOS_ONLY": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIKIT_CLASS_AVAILABLE_WATCHOS_ONLY"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKIT_CLASS_AVAILABLE_WATCHOS_ONLY",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIKIT_CLASS_AVAILABLE_WATCHOS_ONLY",
      "type": "topic",
      "url": "/documentation/uikit/uikit_class_available_watchos_only"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKIT_EXTERN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIKIT_EXTERN"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKIT_EXTERN",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIKIT_EXTERN",
      "type": "topic",
      "url": "/documentation/uikit/uikit_extern"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKIT_EXTERN_C_BEGIN": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIKIT_EXTERN_C_BEGIN"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKIT_EXTERN_C_BEGIN",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIKIT_EXTERN_C_BEGIN",
      "type": "topic",
      "url": "/documentation/uikit/uikit_extern_c_begin"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKIT_HAS_UIFOUNDATION_SYMBOLS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIKIT_HAS_UIFOUNDATION_SYMBOLS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKIT_HAS_UIFOUNDATION_SYMBOLS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKIT_HAS_UIFOUNDATION_SYMBOLS"
        }
      ],
      "role": "symbol",
      "title": "UIKIT_HAS_UIFOUNDATION_SYMBOLS",
      "type": "topic",
      "url": "/documentation/uikit/uikit_has_uifoundation_symbols"
    },
    "doc://com.externally.resolved.symbol/s:s5Int32V": {
      "abstract": [
        {
          "text": "A 32-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int32",
      "type": "topic",
      "url": "/documentation/Swift/Int32"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Macros",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/Preview(_:traits:body:)-c7kr",
        "doc://com.apple.uikit/documentation/UIKit/Preview(_:traits:body:)-en9c"
      ],
      "title": "Macros"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Macro"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIKIT_HAS_UIFOUNDATION_SYMBOLS"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "macro"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKIT_HAS_UIFOUNDATION_SYMBOLS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Macros",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/IBSegueAction",
                "doc://com.apple.uikit/documentation/UIKit/NSLAYOUTANCHOR_EXTERN",
                "doc://com.apple.uikit/documentation/UIKit/NSLAYOUTCONSTRAINT_EXTERN",
                "doc://com.apple.uikit/documentation/UIKit/UIKIT_AVAILABLE_IOS_ONLY",
                "doc://com.apple.uikit/documentation/UIKit/UIKIT_AVAILABLE_IOS_TVOS",
                "doc://com.apple.uikit/documentation/UIKit/UIKIT_AVAILABLE_IOS_WATCHOS_TVOS",
                "doc://com.apple.uikit/documentation/UIKit/UIKIT_AVAILABLE_TVOS_ONLY",
                "doc://com.apple.uikit/documentation/UIKit/UIKIT_AVAILABLE_WATCHOS_ONLY",
                "doc://com.apple.uikit/documentation/UIKit/UIKIT_CLASS_AVAILABLE_IOS_ONLY",
                "doc://com.apple.uikit/documentation/UIKit/UIKIT_CLASS_AVAILABLE_IOS_TVOS",
                "doc://com.apple.uikit/documentation/UIKit/UIKIT_CLASS_AVAILABLE_IOS_WATCHOS_TVOS",
                "doc://com.apple.uikit/documentation/UIKit/UIKIT_CLASS_AVAILABLE_TVOS_ONLY",
                "doc://com.apple.uikit/documentation/UIKit/UIKIT_CLASS_AVAILABLE_WATCHOS_ONLY",
                "doc://com.apple.uikit/documentation/UIKit/UIKIT_EXTERN",
                "doc://com.apple.uikit/documentation/UIKit/UIKIT_EXTERN_C_BEGIN"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "#define"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIKIT_HAS_UIFOUNDATION_SYMBOLS"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKIT_HAS_UIFOUNDATION_SYMBOLS/title",
          "value": "UIKIT_HAS_UIFOUNDATION_SYMBOLS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKIT_HAS_UIFOUNDATION_SYMBOLS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKIT_HAS_UIFOUNDATION_SYMBOLS"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uikit_has_uifoundation_symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uikit_has_uifoundation_symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
