{
  "abstract": [
    {
      "text": "The UIKit framework defines data types that are used in multiple places throughout the framework.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/uikit-data-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "UIKit Data Types"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ComponentKey"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ComponentKey"
        }
      ],
      "role": "symbol",
      "title": "UITextFormattingViewController.ComponentKey",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/componentkey"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/Highlight": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Highlight"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/Highlight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Highlight"
        }
      ],
      "role": "symbol",
      "title": "UITextFormattingViewController.Highlight",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/highlight"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/TextAlignment": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TextAlignment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/TextAlignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TextAlignment"
        }
      ],
      "role": "symbol",
      "title": "UITextFormattingViewController.TextAlignment",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/textalignment"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/TextList": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TextList"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/TextList",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TextList"
        }
      ],
      "role": "symbol",
      "title": "UITextFormattingViewController.TextList",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/textlist"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerChangeType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextFormattingViewControllerChangeType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerChangeType",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextFormattingViewControllerChangeType",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontrollerchangetype"
    },
    "doc://com.apple.uikit/documentation/UIKit/uikit-constants": {
      "abstract": [
        {
          "text": "This document describes constants that are used throughout the UIKit framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/uikit-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "UIKit Constants",
      "type": "topic",
      "url": "/documentation/uikit/uikit-constants"
    },
    "doc://com.apple.uikit/documentation/UIKit/uikit-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/uikit-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "UIKit Enumerations",
      "type": "topic",
      "url": "/documentation/uikit/uikit-enumerations"
    },
    "doc://com.apple.uikit/documentation/UIKit/uikit-functions": {
      "abstract": [
        {
          "text": "The UIKit framework defines a number of functions, many of them used in graphics and drawing operations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/uikit-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "UIKit Functions",
      "type": "topic",
      "url": "/documentation/uikit/uikit-functions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/uikit-enumerations",
        "doc://com.apple.uikit/documentation/UIKit/uikit-constants",
        "doc://com.apple.uikit/documentation/UIKit/uikit-functions"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/Highlight",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/TextAlignment",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/TextList"
      ],
      "title": "Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentKey",
                "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/Highlight",
                "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/TextAlignment",
                "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/TextList",
                "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerChangeType"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/uikit-enumerations",
                "doc://com.apple.uikit/documentation/UIKit/uikit-constants",
                "doc://com.apple.uikit/documentation/UIKit/uikit-functions"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1Highlight/title",
          "value": "UITextFormattingViewControllerHighlight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1Highlight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerHighlight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1Highlight/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerHighlight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1TextAlignment/title",
          "value": "UITextFormattingViewControllerTextAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1TextAlignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerTextAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1TextAlignment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerTextAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1TextList/title",
          "value": "UITextFormattingViewControllerTextList"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1TextList/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerTextList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1TextList/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerTextList"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentKey/title",
          "value": "UITextFormattingViewControllerComponentKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerComponentKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerComponentKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uikit-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uikit-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
