{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/uikit-enumerations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "UIKit Enumerations"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/ExpandedStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpandedStatus"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/ExpandedStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ExpandedStatus"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibility.ExpandedStatus",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/expandedstatus"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFocusItemDeferralMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFocusItemDeferralMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFocusItemDeferralMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFocusItemDeferralMode"
        }
      ],
      "role": "symbol",
      "title": "UIFocusItemDeferralMode",
      "type": "topic",
      "url": "/documentation/uikit/uifocusitemdeferralmode"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPreferredPresentationStyle": {
      "abstract": [
        {
          "text": "The presentation styles that determine how a view shows an item provider’s data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIPreferredPresentationStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPreferredPresentationStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIPreferredPresentationStyle",
      "type": "topic",
      "url": "/documentation/uikit/uipreferredpresentationstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ComponentSize"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ComponentSize"
        }
      ],
      "role": "symbol",
      "title": "UITextFormattingViewController.ComponentSize",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/componentsize"
    },
    "doc://com.apple.uikit/documentation/UIKit/uikit-constants": {
      "abstract": [
        {
          "text": "This document describes constants that are used throughout the UIKit framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/uikit-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "UIKit Constants",
      "type": "topic",
      "url": "/documentation/uikit/uikit-constants"
    },
    "doc://com.apple.uikit/documentation/UIKit/uikit-data-types": {
      "abstract": [
        {
          "text": "The UIKit framework defines data types that are used in multiple places throughout the framework.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/uikit-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "UIKit Data Types",
      "type": "topic",
      "url": "/documentation/uikit/uikit-data-types"
    },
    "doc://com.apple.uikit/documentation/UIKit/uikit-functions": {
      "abstract": [
        {
          "text": "The UIKit framework defines a number of functions, many of them used in graphics and drawing operations.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/uikit-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "UIKit Functions",
      "type": "topic",
      "url": "/documentation/uikit/uikit-functions"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/uikit-constants",
        "doc://com.apple.uikit/documentation/UIKit/uikit-data-types",
        "doc://com.apple.uikit/documentation/UIKit/uikit-functions"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumerations",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/ExpandedStatus",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentSize",
        "doc://com.apple.uikit/documentation/UIKit/UIFocusItemDeferralMode"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumerations",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/ExpandedStatus",
                "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentSize",
                "doc://com.apple.uikit/documentation/UIKit/UIPreferredPresentationStyle",
                "doc://com.apple.uikit/documentation/UIKit/UIFocusItemDeferralMode"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/uikit-constants",
                "doc://com.apple.uikit/documentation/UIKit/uikit-data-types",
                "doc://com.apple.uikit/documentation/UIKit/uikit-functions"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusItemDeferralMode/title",
          "value": "UIFocusItemDeferralMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusItemDeferralMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFocusItemDeferralMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusItemDeferralMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFocusItemDeferralMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentSize/title",
          "value": "UITextFormattingViewControllerComponentSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerComponentSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentSize/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerComponentSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1ExpandedStatus/title",
          "value": "UIAccessibilityExpandedStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1ExpandedStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityExpandedStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1ExpandedStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityExpandedStatus"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uikit-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uikit-enumerations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
