{
  "abstract": [
    {
      "text": "A content configuration for a list-based content view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:5UIKit26UIListContentConfigurationV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIListContentConfiguration"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIListContentConfiguration"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "UIListContentConfiguration"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIListContentConfiguration"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A list content configuration describes the styling and content for an individual element that might appear in a list, like a cell, header, or footer. Using a list content configuration, you can obtain system default styling for a variety of different view states. You fill the configuration with your content, and then assign it directly to cells, headers, and footers in ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", or to your own custom list content view (",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ").",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For views like cells, headers, and footers, use their ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewListCell/defaultContentConfiguration()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to get a list content configuration that has preconfigured default styling. Alternatively, you can create a list content configuration from one of the system default styles. After you get the configuration, you assign your content to it, customize any other properties, and assign it to your view as the current content configuration.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "var content = cell.defaultContentConfiguration()",
            "",
            "// Configure content.",
            "content.image = UIImage(systemName: \"star\")",
            "content.text = \"Favorites\"",
            "",
            "// Customize appearance.",
            "content.imageProperties.tintColor = .purple",
            "",
            "cell.contentConfiguration = content"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionView": {
      "abstract": [
        {
          "text": "An object that manages an ordered collection of data items and presents them using customizable layouts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionView"
        }
      ],
      "role": "symbol",
      "title": "UICollectionView",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewListCell/defaultContentConfiguration()": {
      "abstract": [
        {
          "text": "Retrieves a default list content configuration for the cell’s style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultContentConfiguration"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit26UIListContentConfigurationV",
          "text": "UIListContentConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewListCell/defaultContentConfiguration()",
      "kind": "symbol",
      "role": "symbol",
      "title": "defaultContentConfiguration()",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewlistcell/defaultcontentconfiguration()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentConfiguration-9eib5": {
      "abstract": [
        {
          "text": "The requirements for an object that provides the configuration for a content view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIContentConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentConfiguration-9eib5",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentConfiguration"
        }
      ],
      "role": "symbol",
      "title": "UIContentConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uicontentconfiguration-9eib5"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentView-5fh3z": {
      "abstract": [
        {
          "text": "The requirements for a content view that you create using a configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIContentView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentView-5fh3z",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentView"
        }
      ],
      "role": "symbol",
      "title": "UIContentView",
      "type": "topic",
      "url": "/documentation/uikit/uicontentview-5fh3z"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct": {
      "abstract": [
        {
          "text": "A content configuration for a list-based content view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIListContentConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIListContentConfiguration"
        }
      ],
      "role": "symbol",
      "title": "UIListContentConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/ImageProperties-swift.struct": {
      "abstract": [
        {
          "text": "Properties that affect the list content configuration’s image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ImageProperties"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/ImageProperties-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ImageProperties"
        }
      ],
      "role": "symbol",
      "title": "UIListContentConfiguration.ImageProperties",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct/imageproperties-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/TextProperties-swift.struct": {
      "abstract": [
        {
          "text": "Properties that affect the list content configuration’s text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TextProperties"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/TextProperties-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TextProperties"
        }
      ],
      "role": "symbol",
      "title": "UIListContentConfiguration.TextProperties",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct/textproperties-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/accompaniedSidebarCell()": {
      "abstract": [
        {
          "text": "Creates the default configuration you use to style a cell in an accompanied sidebar list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accompaniedSidebarCell"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit26UIListContentConfigurationV",
          "text": "UIListContentConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/accompaniedSidebarCell()",
      "kind": "symbol",
      "role": "symbol",
      "title": "accompaniedSidebarCell()",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct/accompaniedsidebarcell()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/accompaniedSidebarSubtitleCell()": {
      "abstract": [
        {
          "text": "Creates the default configuration you use to style a cell that’s in an accompanied sidebar list and contains subtitle text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accompaniedSidebarSubtitleCell"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit26UIListContentConfigurationV",
          "text": "UIListContentConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/accompaniedSidebarSubtitleCell()",
      "kind": "symbol",
      "role": "symbol",
      "title": "accompaniedSidebarSubtitleCell()",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct/accompaniedsidebarsubtitlecell()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/alpha": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alpha"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/alpha",
      "kind": "symbol",
      "role": "symbol",
      "title": "alpha",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct/alpha"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/attributedText": {
      "abstract": [
        {
          "text": "An attributed variant of the primary text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attributedText"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/attributedText",
      "kind": "symbol",
      "role": "symbol",
      "title": "attributedText",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct/attributedtext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/axesPreservingSuperviewLayoutMargins": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the content view preserves the layout margins that it inherits from its superview on the horizontal or vertical axes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "axesPreservingSuperviewLayoutMargins"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIAxis",
          "text": "UIAxis"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/axesPreservingSuperviewLayoutMargins",
      "kind": "symbol",
      "role": "symbol",
      "title": "axesPreservingSuperviewLayoutMargins",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct/axespreservingsuperviewlayoutmargins"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/cell()": {
      "abstract": [
        {
          "text": "Creates the default configuration you use to style a cell in a list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cell"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit26UIListContentConfigurationV",
          "text": "UIListContentConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/cell()",
      "kind": "symbol",
      "role": "symbol",
      "title": "cell()",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct/cell()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/directionalLayoutMargins": {
      "abstract": [
        {
          "text": "The margins between the content and the edges of the content view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "directionalLayoutMargins"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@NSDirectionalEdgeInsets",
          "text": "NSDirectionalEdgeInsets"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/directionalLayoutMargins",
      "kind": "symbol",
      "role": "symbol",
      "title": "directionalLayoutMargins",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct/directionallayoutmargins"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/extraProminentInsetGroupedHeader()": {
      "abstract": [
        {
          "text": "Creates the default configuration you use to style an extra prominent header in an inset grouped list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "extraProminentInsetGroupedHeader"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit26UIListContentConfigurationV",
          "text": "UIListContentConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/extraProminentInsetGroupedHeader()",
      "kind": "symbol",
      "role": "symbol",
      "title": "extraProminentInsetGroupedHeader()",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct/extraprominentinsetgroupedheader()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/footer()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "footer"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit26UIListContentConfigurationV",
          "text": "UIListContentConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/footer()",
      "kind": "symbol",
      "role": "symbol",
      "title": "footer()",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct/footer()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/groupedFooter()": {
      "abstract": [
        {
          "text": "Creates the default configuration you use to style a footer in a grouped list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "groupedFooter"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit26UIListContentConfigurationV",
          "text": "UIListContentConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/groupedFooter()",
      "kind": "symbol",
      "role": "symbol",
      "title": "groupedFooter()",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct/groupedfooter()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/groupedHeader()": {
      "abstract": [
        {
          "text": "Creates the default configuration you use to style a header in a grouped list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "groupedHeader"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit26UIListContentConfigurationV",
          "text": "UIListContentConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/groupedHeader()",
      "kind": "symbol",
      "role": "symbol",
      "title": "groupedHeader()",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct/groupedheader()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/header()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "header"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit26UIListContentConfigurationV",
          "text": "UIListContentConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/header()",
      "kind": "symbol",
      "role": "symbol",
      "title": "header()",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct/header()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/image": {
      "abstract": [
        {
          "text": "The image to display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "image"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/image",
      "kind": "symbol",
      "role": "symbol",
      "title": "image",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct/image"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/imageProperties-swift.property": {
      "abstract": [
        {
          "text": "Properties for configuring the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageProperties"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit26UIListContentConfigurationV",
          "text": "UIListContentConfiguration"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit26UIListContentConfigurationV15ImagePropertiesV",
          "text": "ImageProperties"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/imageProperties-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "imageProperties",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct/imageproperties-swift.property"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/imageToTextPadding": {
      "abstract": [
        {
          "text": "The padding between the image and text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "imageToTextPadding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/imageToTextPadding",
      "kind": "symbol",
      "role": "symbol",
      "title": "imageToTextPadding",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct/imagetotextpadding"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/plainFooter()": {
      "abstract": [
        {
          "text": "Creates the default configuration you use to style a footer in a plain list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "plainFooter"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit26UIListContentConfigurationV",
          "text": "UIListContentConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/plainFooter()",
      "kind": "symbol",
      "role": "symbol",
      "title": "plainFooter()",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct/plainfooter()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/plainHeader()": {
      "abstract": [
        {
          "text": "Creates the default configuration you use to style a header in a plain list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "plainHeader"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit26UIListContentConfigurationV",
          "text": "UIListContentConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/plainHeader()",
      "kind": "symbol",
      "role": "symbol",
      "title": "plainHeader()",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct/plainheader()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/prefersSideBySideTextAndSecondaryText": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the configuration positions the text and secondary text side by side.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prefersSideBySideTextAndSecondaryText"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/prefersSideBySideTextAndSecondaryText",
      "kind": "symbol",
      "role": "symbol",
      "title": "prefersSideBySideTextAndSecondaryText",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct/preferssidebysidetextandsecondarytext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/prominentInsetGroupedHeader()": {
      "abstract": [
        {
          "text": "Creates the default configuration you use to style a prominent header in an inset grouped list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prominentInsetGroupedHeader"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit26UIListContentConfigurationV",
          "text": "UIListContentConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/prominentInsetGroupedHeader()",
      "kind": "symbol",
      "role": "symbol",
      "title": "prominentInsetGroupedHeader()",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct/prominentinsetgroupedheader()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/secondaryAttributedText": {
      "abstract": [
        {
          "text": "An attributed variant of the secondary text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "secondaryAttributedText"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/secondaryAttributedText",
      "kind": "symbol",
      "role": "symbol",
      "title": "secondaryAttributedText",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct/secondaryattributedtext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/secondaryText": {
      "abstract": [
        {
          "text": "The secondary text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "secondaryText"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/secondaryText",
      "kind": "symbol",
      "role": "symbol",
      "title": "secondaryText",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct/secondarytext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/secondaryTextProperties": {
      "abstract": [
        {
          "text": "Properties for configuring the secondary text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "secondaryTextProperties"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit26UIListContentConfigurationV",
          "text": "UIListContentConfiguration"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit26UIListContentConfigurationV14TextPropertiesV",
          "text": "TextProperties"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/secondaryTextProperties",
      "kind": "symbol",
      "role": "symbol",
      "title": "secondaryTextProperties",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct/secondarytextproperties"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/sidebarCell()": {
      "abstract": [
        {
          "text": "Creates the default configuration you use to style a cell in a sidebar list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sidebarCell"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit26UIListContentConfigurationV",
          "text": "UIListContentConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/sidebarCell()",
      "kind": "symbol",
      "role": "symbol",
      "title": "sidebarCell()",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct/sidebarcell()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/sidebarHeader()": {
      "abstract": [
        {
          "text": "Creates the default configuration you use to style a header in a sidebar list.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sidebarHeader"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit26UIListContentConfigurationV",
          "text": "UIListContentConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/sidebarHeader()",
      "kind": "symbol",
      "role": "symbol",
      "title": "sidebarHeader()",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct/sidebarheader()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/sidebarSubtitleCell()": {
      "abstract": [
        {
          "text": "Creates the default configuration you use to style a cell that’s in a sidebar list and contains subtitle text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sidebarSubtitleCell"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit26UIListContentConfigurationV",
          "text": "UIListContentConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/sidebarSubtitleCell()",
      "kind": "symbol",
      "role": "symbol",
      "title": "sidebarSubtitleCell()",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct/sidebarsubtitlecell()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/subtitleCell()": {
      "abstract": [
        {
          "text": "Creates the default configuration you use to style a cell that’s in a list and contains subtitle text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subtitleCell"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit26UIListContentConfigurationV",
          "text": "UIListContentConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/subtitleCell()",
      "kind": "symbol",
      "role": "symbol",
      "title": "subtitleCell()",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct/subtitlecell()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/text": {
      "abstract": [
        {
          "text": "The primary text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "text"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/text",
      "kind": "symbol",
      "role": "symbol",
      "title": "text",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct/text"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/textProperties-swift.property": {
      "abstract": [
        {
          "text": "Properties for configuring the primary text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textProperties"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit26UIListContentConfigurationV",
          "text": "UIListContentConfiguration"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit26UIListContentConfigurationV14TextPropertiesV",
          "text": "TextProperties"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/textProperties-swift.property",
      "kind": "symbol",
      "role": "symbol",
      "title": "textProperties",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct/textproperties-swift.property"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/textToSecondaryTextHorizontalPadding": {
      "abstract": [
        {
          "text": "The minimum horizontal padding between the text and secondary text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textToSecondaryTextHorizontalPadding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/textToSecondaryTextHorizontalPadding",
      "kind": "symbol",
      "role": "symbol",
      "title": "textToSecondaryTextHorizontalPadding",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct/texttosecondarytexthorizontalpadding"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/textToSecondaryTextVerticalPadding": {
      "abstract": [
        {
          "text": "The vertical padding between the text and secondary text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textToSecondaryTextVerticalPadding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/textToSecondaryTextVerticalPadding",
      "kind": "symbol",
      "role": "symbol",
      "title": "textToSecondaryTextVerticalPadding",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct/texttosecondarytextverticalpadding"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/valueCell()": {
      "abstract": [
        {
          "text": "Creates the default configuration you use to style a cell that’s in a list and contains side-by-side value text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "valueCell"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit26UIListContentConfigurationV",
          "text": "UIListContentConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/valueCell()",
      "kind": "symbol",
      "role": "symbol",
      "title": "valueCell()",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentconfiguration-swift.struct/valuecell()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIListContentView": {
      "abstract": [
        {
          "text": "A content view for displaying list-based content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIListContentView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIListContentView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIListContentView"
        }
      ],
      "role": "symbol",
      "title": "UIListContentView",
      "type": "topic",
      "url": "/documentation/uikit/uilistcontentview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableView": {
      "abstract": [
        {
          "text": "A view that presents data using rows in a single column.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITableView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableView"
        }
      ],
      "role": "symbol",
      "title": "UITableView",
      "type": "topic",
      "url": "/documentation/uikit/uitableview"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s17CustomReflectableP": {
      "abstract": [
        {
          "text": "A type that explicitly supplies its own mirror.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomReflectable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s17CustomReflectableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomReflectable",
      "type": "topic",
      "url": "/documentation/Swift/CustomReflectable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s17CustomReflectableP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.apple.uikit/documentation/UIKit/UIContentConfiguration-9eib5"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Content-configurations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIListContentView",
        "doc://com.apple.uikit/documentation/UIKit/UIContentConfiguration-9eib5",
        "doc://com.apple.uikit/documentation/UIKit/UIContentView-5fh3z"
      ],
      "title": "Content configurations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-default-cell-configurations",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/cell()",
        "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/subtitleCell()",
        "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/valueCell()",
        "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/sidebarCell()",
        "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/sidebarSubtitleCell()",
        "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/accompaniedSidebarCell()",
        "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/accompaniedSidebarSubtitleCell()"
      ],
      "title": "Creating default cell configurations"
    },
    {
      "anchor": "Creating-header-and-footer-configurations",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/plainHeader()",
        "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/plainFooter()",
        "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/groupedHeader()",
        "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/groupedFooter()",
        "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/prominentInsetGroupedHeader()",
        "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/extraProminentInsetGroupedHeader()",
        "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/sidebarHeader()"
      ],
      "title": "Creating header and footer configurations"
    },
    {
      "anchor": "Customizing-content",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/image",
        "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/text",
        "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/attributedText",
        "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/secondaryText",
        "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/secondaryAttributedText"
      ],
      "title": "Customizing content"
    },
    {
      "anchor": "Customizing-appearance",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/imageProperties-swift.property",
        "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/textProperties-swift.property",
        "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/secondaryTextProperties",
        "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/ImageProperties-swift.struct",
        "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/TextProperties-swift.struct"
      ],
      "title": "Customizing appearance"
    },
    {
      "anchor": "Customizing-layout",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/axesPreservingSuperviewLayoutMargins",
        "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/directionalLayoutMargins",
        "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/prefersSideBySideTextAndSecondaryText",
        "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/imageToTextPadding",
        "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/textToSecondaryTextHorizontalPadding",
        "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/textToSecondaryTextVerticalPadding"
      ],
      "title": "Customizing layout"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/alpha"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Type-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/footer()",
        "doc://com.apple.uikit/documentation/UIKit/UIListContentConfiguration-swift.struct/header()"
      ],
      "title": "Type Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView/title",
          "value": "UITableView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIListContentView/title",
          "value": "UIListContentView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIListContentView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIListContentView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIListContentView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIListContentView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView/title",
          "value": "UICollectionView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionView"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uilistcontentconfiguration-swift.struct"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
