{
  "abstract": [
    {
      "text": "Options for wrapping and truncating text.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLineBreakMode",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UILineBreakMode"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UILineBreakMode",
    "fragments": [
      {
        "kind": "identifier",
        "text": "UILineBreakMode"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UILineBreakMode"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "6.0",
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "6.0",
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "UILineBreakMode"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UILineBreakMode"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSInteger",
              "text": "NSInteger"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "For methods that draw at a specified point (as opposed to those that draw in a rectangular region), these options specify the clipping behavior that UIKit applies to the string.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLineBreakMode": {
      "abstract": [
        {
          "text": "Constants that specify what happens when a line is too long for a container.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSLineBreakMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLineBreakMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSLineBreakMode"
        }
      ],
      "role": "symbol",
      "title": "NSLineBreakMode",
      "type": "topic",
      "url": "/documentation/uikit/nslinebreakmode"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSStringDrawingContext": {
      "abstract": [
        {
          "text": "An object that manages metrics for drawing attributed strings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStringDrawingContext"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSStringDrawingContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSStringDrawingContext"
        }
      ],
      "role": "symbol",
      "title": "NSStringDrawingContext",
      "type": "topic",
      "url": "/documentation/uikit/nsstringdrawingcontext"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSStringDrawingOptions": {
      "abstract": [
        {
          "text": "Constants that specify the rendering options for drawing a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStringDrawingOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSStringDrawingOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSStringDrawingOptions"
        }
      ],
      "role": "symbol",
      "title": "NSStringDrawingOptions",
      "type": "topic",
      "url": "/documentation/uikit/nsstringdrawingoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBaselineAdjustment": {
      "abstract": [
        {
          "text": "Vertical adjustment options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIBaselineAdjustment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBaselineAdjustment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBaselineAdjustment"
        }
      ],
      "role": "symbol",
      "title": "UIBaselineAdjustment",
      "type": "topic",
      "url": "/documentation/uikit/uibaselineadjustment"
    },
    "doc://com.apple.uikit/documentation/UIKit/UILineBreakMode": {
      "abstract": [
        {
          "text": "Options for wrapping and truncating text.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "UILineBreakMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UILineBreakMode",
      "kind": "symbol",
      "role": "symbol",
      "title": "UILineBreakMode",
      "type": "topic",
      "url": "/documentation/uikit/uilinebreakmode"
    },
    "doc://com.apple.uikit/documentation/UIKit/UILineBreakMode/UILineBreakModeCharacterWrap": {
      "abstract": [
        {
          "text": "Wrap or clip the string at the closest character boundary.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "UILineBreakModeCharacterWrap"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UILineBreakMode/UILineBreakModeCharacterWrap",
      "kind": "symbol",
      "role": "symbol",
      "title": "UILineBreakModeCharacterWrap",
      "type": "topic",
      "url": "/documentation/uikit/uilinebreakmode/uilinebreakmodecharacterwrap"
    },
    "doc://com.apple.uikit/documentation/UIKit/UILineBreakMode/UILineBreakModeClip": {
      "abstract": [
        {
          "text": "Clip the text when reaching the end of the drawing rectangle.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "UILineBreakModeClip"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UILineBreakMode/UILineBreakModeClip",
      "kind": "symbol",
      "role": "symbol",
      "title": "UILineBreakModeClip",
      "type": "topic",
      "url": "/documentation/uikit/uilinebreakmode/uilinebreakmodeclip"
    },
    "doc://com.apple.uikit/documentation/UIKit/UILineBreakMode/UILineBreakModeHeadTruncation": {
      "abstract": [
        {
          "text": "Truncate text (as necessary) from the beginning of the line.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "UILineBreakModeHeadTruncation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UILineBreakMode/UILineBreakModeHeadTruncation",
      "kind": "symbol",
      "role": "symbol",
      "title": "UILineBreakModeHeadTruncation",
      "type": "topic",
      "url": "/documentation/uikit/uilinebreakmode/uilinebreakmodeheadtruncation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UILineBreakMode/UILineBreakModeMiddleTruncation": {
      "abstract": [
        {
          "text": "Truncate text (as necessary) from the middle of the line.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "UILineBreakModeMiddleTruncation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UILineBreakMode/UILineBreakModeMiddleTruncation",
      "kind": "symbol",
      "role": "symbol",
      "title": "UILineBreakModeMiddleTruncation",
      "type": "topic",
      "url": "/documentation/uikit/uilinebreakmode/uilinebreakmodemiddletruncation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UILineBreakMode/UILineBreakModeTailTruncation": {
      "abstract": [
        {
          "text": "Truncate text (as necessary) from the end of the line.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "UILineBreakModeTailTruncation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UILineBreakMode/UILineBreakModeTailTruncation",
      "kind": "symbol",
      "role": "symbol",
      "title": "UILineBreakModeTailTruncation",
      "type": "topic",
      "url": "/documentation/uikit/uilinebreakmode/uilinebreakmodetailtruncation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UILineBreakMode/UILineBreakModeWordWrap": {
      "abstract": [
        {
          "text": "Wrap or clip the string only at word boundaries.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "UILineBreakModeWordWrap"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UILineBreakMode/UILineBreakModeWordWrap",
      "kind": "symbol",
      "role": "symbol",
      "title": "UILineBreakModeWordWrap",
      "type": "topic",
      "url": "/documentation/uikit/uilinebreakmode/uilinebreakmodewordwrap"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextAlignment": {
      "abstract": [
        {
          "text": "Options for aligning text horizontally.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextAlignment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextAlignment",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextAlignment",
      "type": "topic",
      "url": "/documentation/uikit/uitextalignment"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextAttributeFont": {
      "abstract": [
        {
          "text": "The key to the font in a text attributes dictionary.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextAttributeFont"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextAttributeFont",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextAttributeFont",
      "type": "topic",
      "url": "/documentation/uikit/uitextattributefont"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextAttributeTextColor": {
      "abstract": [
        {
          "text": "The key to the text color in a text attributes dictionary.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextAttributeTextColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextAttributeTextColor",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextAttributeTextColor",
      "type": "topic",
      "url": "/documentation/uikit/uitextattributetextcolor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextAttributeTextShadowColor": {
      "abstract": [
        {
          "text": "The key to the text shadow color in a text attributes dictionary.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextAttributeTextShadowColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextAttributeTextShadowColor",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextAttributeTextShadowColor",
      "type": "topic",
      "url": "/documentation/uikit/uitextattributetextshadowcolor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextAttributeTextShadowOffset": {
      "abstract": [
        {
          "text": "The key to the offset for the text shadow in a text attributes dictionary.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextAttributeTextShadowOffset"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextAttributeTextShadowOffset",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextAttributeTextShadowOffset",
      "type": "topic",
      "url": "/documentation/uikit/uitextattributetextshadowoffset"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Strings",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSStringDrawingContext",
        "doc://com.apple.uikit/documentation/UIKit/NSStringDrawingOptions",
        "doc://com.apple.uikit/documentation/UIKit/UIBaselineAdjustment",
        "doc://com.apple.uikit/documentation/UIKit/UITextAlignment",
        "doc://com.apple.uikit/documentation/UIKit/UITextAttributeFont",
        "doc://com.apple.uikit/documentation/UIKit/UITextAttributeTextColor",
        "doc://com.apple.uikit/documentation/UIKit/UITextAttributeTextShadowColor",
        "doc://com.apple.uikit/documentation/UIKit/UITextAttributeTextShadowOffset"
      ],
      "title": "Strings"
    }
  ],
  "topicSections": [
    {
      "anchor": "Deprecated-constants",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UILineBreakMode/UILineBreakModeWordWrap",
        "doc://com.apple.uikit/documentation/UIKit/UILineBreakMode/UILineBreakModeCharacterWrap",
        "doc://com.apple.uikit/documentation/UIKit/UILineBreakMode/UILineBreakModeClip",
        "doc://com.apple.uikit/documentation/UIKit/UILineBreakMode/UILineBreakModeHeadTruncation",
        "doc://com.apple.uikit/documentation/UIKit/UILineBreakMode/UILineBreakModeTailTruncation",
        "doc://com.apple.uikit/documentation/UIKit/UILineBreakMode/UILineBreakModeMiddleTruncation"
      ],
      "title": "Deprecated constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSStringDrawingContext/title",
          "value": "NSStringDrawingContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSStringDrawingContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStringDrawingContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSStringDrawingContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStringDrawingContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBaselineAdjustment/title",
          "value": "UIBaselineAdjustment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBaselineAdjustment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBaselineAdjustment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBaselineAdjustment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBaselineAdjustment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLineBreakMode/title",
          "value": "NSLineBreakMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLineBreakMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineBreakMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLineBreakMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSLineBreakMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSStringDrawingOptions/title",
          "value": "NSStringDrawingOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSStringDrawingOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStringDrawingOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSStringDrawingOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStringDrawingOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uilinebreakmode"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
