{
  "abstract": [
    {
      "text": "A managed document object that integrates with Core Data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIManagedDocument",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIManagedDocument"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIManagedDocument"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "UIManagedDocument"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIManagedDocument"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is a concrete subclass of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocument",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". When you initialize a managed document, you specify the URL for the document location. The document object then creates a Core Data stack to use to access the document’s persistent store using a managed object model from the app’s main bundle. ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " performs all the basic setup you need for Core Data, and in some cases you may use instances of the class directly (without a need to subclass). You can supply configuration options for the creation of the coordinator using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/persistentStoreOptions",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and for the model using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/modelConfiguration",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". You can also perform additional customization by creating a subclass of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ":",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Override ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/persistentStoreName",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to customize the name of the persistent store file inside the document’s file package.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Override ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/managedObjectModel",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to customize creation of the managed object model.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "You do this if, for example, your app supports multiple document types, each of which uses a different model. You want to ensure that the models aren’t merged for each document class.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Override ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/persistentStoreType(forFileType:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to customize the type of persistent store used by a document.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Override ",
                      "type": "text"
                    },
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/configurePersistentStoreCoordinator(for:ofType:modelConfiguration:storeOptions:)",
                      "isActive": true,
                      "type": "reference"
                    },
                    {
                      "text": " to customize the loading or creation of a persistent store.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Handling-errors",
          "level": 3,
          "text": "Handling errors",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To enable your app to observe and handle errors in saving and validating a managed document, you must subclass the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class and override one or both of the following two inherited methods from the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocument",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocument/handleError(_:userInteractionPermitted:)",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocument/finishedHandlingError(_:recovered:)",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "Overriding is required because otherwise, the only information your app receives on error is the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocument/stateChangedNotification",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " notification, which doesn’t contain a ",
              "type": "text"
            },
            {
              "code": "userInfo",
              "type": "codeVoice"
            },
            {
              "text": " dictionary and so doesn’t convey specific error information.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocument": {
      "abstract": [
        {
          "text": "An abstract base class for managing discrete portions of your app’s data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDocument"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDocument"
        }
      ],
      "role": "symbol",
      "title": "UIDocument",
      "type": "topic",
      "url": "/documentation/uikit/uidocument"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocument/finishedHandlingError(_:recovered:)": {
      "abstract": [
        {
          "text": "Tells UIKit that you finished handling the error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "finishedHandlingError"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "recovered"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocument/finishedHandlingError(_:recovered:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "finishedHandlingError:recovered:"
        }
      ],
      "role": "symbol",
      "title": "finishedHandlingError(_:recovered:)",
      "type": "topic",
      "url": "/documentation/uikit/uidocument/finishedhandlingerror(_:recovered:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocument/handleError(_:userInteractionPermitted:)": {
      "abstract": [
        {
          "text": "Handles an error that occurs during an attempt to read, save, or revert a document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handleError"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "userInteractionPermitted"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocument/handleError(_:userInteractionPermitted:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handleError:userInteractionPermitted:"
        }
      ],
      "role": "symbol",
      "title": "handleError(_:userInteractionPermitted:)",
      "type": "topic",
      "url": "/documentation/uikit/uidocument/handleerror(_:userinteractionpermitted:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocument/stateChangedNotification": {
      "abstract": [
        {
          "text": "A notification the document object posts when there’s a change in the state of the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "stateChangedNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocument/stateChangedNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDocumentStateChangedNotification"
        }
      ],
      "role": "symbol",
      "title": "stateChangedNotification",
      "type": "topic",
      "url": "/documentation/uikit/uidocument/statechangednotification"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument": {
      "abstract": [
        {
          "text": "A managed document object that integrates with Core Data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIManagedDocument"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIManagedDocument"
        }
      ],
      "role": "symbol",
      "title": "UIManagedDocument",
      "type": "topic",
      "url": "/documentation/uikit/uimanageddocument"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/additionalContent(for:)": {
      "abstract": [
        {
          "text": "Handles writing non-Core Data content to the additional content directory in the document’s file package.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "additionalContent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        },
        {
          "kind": "text",
          "text": " -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/additionalContent(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "additionalContentForURL:error:"
        }
      ],
      "role": "symbol",
      "title": "additionalContent(for:)",
      "type": "topic",
      "url": "/documentation/uikit/uimanageddocument/additionalcontent(for:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/configurePersistentStoreCoordinator(for:ofType:modelConfiguration:storeOptions:)": {
      "abstract": [
        {
          "text": "Creates or loads the document’s persistent store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurePersistentStoreCoordinator"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "ofType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "modelConfiguration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "storeOptions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/configurePersistentStoreCoordinator(for:ofType:modelConfiguration:storeOptions:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "configurePersistentStoreCoordinatorForURL:ofType:modelConfiguration:storeOptions:error:"
        }
      ],
      "role": "symbol",
      "title": "configurePersistentStoreCoordinator(for:ofType:modelConfiguration:storeOptions:)",
      "type": "topic",
      "url": "/documentation/uikit/uimanageddocument/configurepersistentstorecoordinator(for:oftype:modelconfiguration:storeoptions:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/managedObjectContext": {
      "abstract": [
        {
          "text": "The document’s managed object context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "managedObjectContext"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSManagedObjectContext",
          "text": "NSManagedObjectContext"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/managedObjectContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "managedObjectContext"
        }
      ],
      "role": "symbol",
      "title": "managedObjectContext",
      "type": "topic",
      "url": "/documentation/uikit/uimanageddocument/managedobjectcontext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/managedObjectModel": {
      "abstract": [
        {
          "text": "The document’s managed object model.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "managedObjectModel"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSManagedObjectModel",
          "text": "NSManagedObjectModel"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/managedObjectModel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "managedObjectModel"
        }
      ],
      "role": "symbol",
      "title": "managedObjectModel",
      "type": "topic",
      "url": "/documentation/uikit/uimanageddocument/managedobjectmodel"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/modelConfiguration": {
      "abstract": [
        {
          "text": "A model configuration name to be passed when configuring the persistent store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "modelConfiguration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/modelConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "modelConfiguration"
        }
      ],
      "role": "symbol",
      "title": "modelConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uimanageddocument/modelconfiguration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/persistentStoreName": {
      "abstract": [
        {
          "text": "Returns the name for the persistent store file inside the document’s file package.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "persistentStoreName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/persistentStoreName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "persistentStoreName"
        }
      ],
      "role": "symbol",
      "title": "persistentStoreName",
      "type": "topic",
      "url": "/documentation/uikit/uimanageddocument/persistentstorename"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/persistentStoreOptions": {
      "abstract": [
        {
          "text": "Options used when creating the document’s persistent store.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "persistentStoreOptions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/persistentStoreOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "persistentStoreOptions"
        }
      ],
      "role": "symbol",
      "title": "persistentStoreOptions",
      "type": "topic",
      "url": "/documentation/uikit/uimanageddocument/persistentstoreoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/persistentStoreType(forFileType:)": {
      "abstract": [
        {
          "text": "Returns the Core Data store type for a given document file type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "persistentStoreType"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forFileType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/persistentStoreType(forFileType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "persistentStoreTypeForFileType:"
        }
      ],
      "role": "symbol",
      "title": "persistentStoreType(forFileType:)",
      "type": "topic",
      "url": "/documentation/uikit/uimanageddocument/persistentstoretype(forfiletype:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/readAdditionalContent(from:)": {
      "abstract": [
        {
          "text": "Handles reading non-Core Data content in the additional content directory in the document’s file package.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readAdditionalContent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/readAdditionalContent(from:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readAdditionalContentFromURL:error:"
        }
      ],
      "role": "symbol",
      "title": "readAdditionalContent(from:)",
      "type": "topic",
      "url": "/documentation/uikit/uimanageddocument/readadditionalcontent(from:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/writeAdditionalContent(_:to:originalContentsURL:)": {
      "abstract": [
        {
          "text": "Handles writing non-Core Data content to the document’s file package.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "writeAdditionalContent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "originalContentsURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?) "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/writeAdditionalContent(_:to:originalContentsURL:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "writeAdditionalContent:toURL:originalContentsURL:error:"
        }
      ],
      "role": "symbol",
      "title": "writeAdditionalContent(_:to:originalContentsURL:)",
      "type": "topic",
      "url": "/documentation/uikit/uimanageddocument/writeadditionalcontent(_:to:originalcontentsurl:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationItemRenameDelegate-96g5t": {
      "abstract": [
        {
          "text": "Methods an object implements to rename a navigation item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UINavigationItemRenameDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationItemRenameDelegate-96g5t",
      "kind": "symbol",
      "role": "symbol",
      "title": "UINavigationItemRenameDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationitemrenamedelegate-96g5t"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserActivityRestoring": {
      "abstract": [
        {
          "text": "The protocol you adopt to restore an object’s state from a user activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIUserActivityRestoring"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserActivityRestoring",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserActivityRestoring"
        }
      ],
      "role": "symbol",
      "title": "UIUserActivityRestoring",
      "type": "topic",
      "url": "/documentation/uikit/uiuseractivityrestoring"
    },
    "doc://com.apple.uikit/documentation/UIKit/synchronizing-documents-in-the-icloud-environment": {
      "abstract": [
        {
          "text": "Manage documents across multiple devices to create a seamless editing and collaboration experience.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/synchronizing-documents-in-the-icloud-environment",
      "kind": "article",
      "role": "sampleCode",
      "title": "Synchronizing documents in the iCloud environment",
      "type": "topic",
      "url": "/documentation/uikit/synchronizing-documents-in-the-icloud-environment"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSFilePresenter": {
      "abstract": [
        {
          "text": "The interface a file coordinator uses to inform an object presenting a file about changes to that file made elsewhere in the system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSFilePresenter"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSFilePresenter",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSFilePresenter",
      "type": "topic",
      "url": "/documentation/foundation/nsfilepresenter"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSProgressReporting": {
      "abstract": [
        {
          "text": "An interface for objects that report progress using a single progress instance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "ProgressReporting"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSProgressReporting",
      "kind": "symbol",
      "role": "symbol",
      "title": "ProgressReporting",
      "type": "topic",
      "url": "/documentation/foundation/progressreporting"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIDocument"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSFilePresenter",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSProgressReporting",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.apple.uikit/documentation/UIKit/UIUserActivityRestoring"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Documents",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIDocument",
        "doc://com.apple.uikit/documentation/UIKit/synchronizing-documents-in-the-icloud-environment"
      ],
      "title": "Documents"
    }
  ],
  "topicSections": [
    {
      "anchor": "Managing-the-Core-Data-stack",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/configurePersistentStoreCoordinator(for:ofType:modelConfiguration:storeOptions:)",
        "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/managedObjectContext",
        "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/managedObjectModel",
        "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/persistentStoreOptions",
        "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/modelConfiguration",
        "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/persistentStoreType(forFileType:)"
      ],
      "title": "Managing the Core Data stack"
    },
    {
      "anchor": "Customizing-read-and-write-operations",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/readAdditionalContent(from:)",
        "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/additionalContent(for:)",
        "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/writeAdditionalContent(_:to:originalContentsURL:)"
      ],
      "title": "Customizing read and write operations"
    },
    {
      "anchor": "Naming-the-persistent-store-file",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/persistentStoreName"
      ],
      "title": "Naming the persistent store file"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIManagedDocument"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIManagedDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIManagedDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Managing-the-Core-Data-stack",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/configurePersistentStoreCoordinator(for:ofType:modelConfiguration:storeOptions:)",
                "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/managedObjectContext",
                "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/managedObjectModel",
                "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/persistentStoreOptions",
                "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/modelConfiguration",
                "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/persistentStoreType(forFileType:)"
              ],
              "title": "Managing the Core Data stack"
            },
            {
              "anchor": "Customizing-read-and-write-operations",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/readAdditionalContent(from:)",
                "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/additionalContent(for:)",
                "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/writeAdditionalContent(_:to:originalContentsURL:)"
              ],
              "title": "Customizing read and write operations"
            },
            {
              "anchor": "Naming-the-persistent-store-file",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIManagedDocument/persistentStoreName"
              ],
              "title": "Naming the persistent store file"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIDocument"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Documents",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIDocument",
                "doc://com.apple.uikit/documentation/UIKit/synchronizing-documents-in-the-icloud-environment"
              ],
              "title": "Documents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIManagedDocument"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocument",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UIDocument",
                    "text": "UIDocument"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIManagedDocument~1managedObjectContext/title",
          "value": "managedObjectContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIManagedDocument~1managedObjectContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "managedObjectContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIManagedDocument~1writeAdditionalContent(_:to:originalContentsURL:)/title",
          "value": "writeAdditionalContent:toURL:originalContentsURL:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIManagedDocument~1writeAdditionalContent(_:to:originalContentsURL:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "writeAdditionalContent:toURL:originalContentsURL:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIManagedDocument~1persistentStoreType(forFileType:)/title",
          "value": "persistentStoreTypeForFileType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIManagedDocument~1persistentStoreType(forFileType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "persistentStoreTypeForFileType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIManagedDocument~1additionalContent(for:)/title",
          "value": "additionalContentForURL:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIManagedDocument~1additionalContent(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "additionalContentForURL:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIManagedDocument~1persistentStoreOptions/title",
          "value": "persistentStoreOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIManagedDocument~1persistentStoreOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "persistentStoreOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocument~1handleError(_:userInteractionPermitted:)/title",
          "value": "handleError:userInteractionPermitted:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocument~1handleError(_:userInteractionPermitted:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "handleError:userInteractionPermitted:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIManagedDocument~1configurePersistentStoreCoordinator(for:ofType:modelConfiguration:storeOptions:)/title",
          "value": "configurePersistentStoreCoordinatorForURL:ofType:modelConfiguration:storeOptions:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIManagedDocument~1configurePersistentStoreCoordinator(for:ofType:modelConfiguration:storeOptions:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "configurePersistentStoreCoordinatorForURL:ofType:modelConfiguration:storeOptions:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocument~1finishedHandlingError(_:recovered:)/title",
          "value": "finishedHandlingError:recovered:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocument~1finishedHandlingError(_:recovered:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "finishedHandlingError:recovered:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIManagedDocument~1managedObjectModel/title",
          "value": "managedObjectModel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIManagedDocument~1managedObjectModel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "managedObjectModel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIManagedDocument~1modelConfiguration/title",
          "value": "modelConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIManagedDocument~1modelConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "modelConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIManagedDocument~1persistentStoreName/title",
          "value": "persistentStoreName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIManagedDocument~1persistentStoreName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "persistentStoreName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSProgressReporting/title",
          "value": "NSProgressReporting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocument/title",
          "value": "UIDocument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocument/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserActivityRestoring/title",
          "value": "UIUserActivityRestoring"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserActivityRestoring/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserActivityRestoring"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserActivityRestoring/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserActivityRestoring"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocument~1stateChangedNotification/title",
          "value": "UIDocumentStateChangedNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocument~1stateChangedNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocumentStateChangedNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIManagedDocument~1readAdditionalContent(from:)/title",
          "value": "readAdditionalContentFromURL:error:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIManagedDocument~1readAdditionalContent(from:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readAdditionalContentFromURL:error:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIManagedDocument/title",
          "value": "UIManagedDocument"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIManagedDocument/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIManagedDocument"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIManagedDocument/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIManagedDocument"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uimanageddocument"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uimanageddocument"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
