{
  "abstract": [
    {
      "text": "A class that represents an email conversation.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIMailConversationContext",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIMailConversationContext"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIMailConversationContext"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "18.4",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "UIMailConversationContext"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIMailConversationContext"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.uikit/documentation/UIKit/adopting-smart-reply-in-your-messaging-or-email-app"
      ]
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIConversationContext": {
      "abstract": [
        {
          "text": "A base class that represents a conversation between participants, such as in an email or messaging app.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIConversationContext"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIConversationContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIConversationContext"
        }
      ],
      "role": "symbol",
      "title": "UIConversationContext",
      "type": "topic",
      "url": "/documentation/uikit/uiconversationcontext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIConversationContext/Entry": {
      "abstract": [
        {
          "text": "A base class that represents a message in a conversation.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Entry"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIConversationContext/Entry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Entry"
        }
      ],
      "role": "symbol",
      "title": "UIConversationContext.Entry",
      "type": "topic",
      "url": "/documentation/uikit/uiconversationcontext/entry"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIInputSuggestion": {
      "abstract": [
        {
          "text": "A base class you use to handle suggestions from the keyboard or system.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIInputSuggestion"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIInputSuggestion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIInputSuggestion"
        }
      ],
      "role": "symbol",
      "title": "UIInputSuggestion",
      "type": "topic",
      "url": "/documentation/uikit/uiinputsuggestion"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext": {
      "abstract": [
        {
          "text": "A class that represents an email conversation.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIMailConversationContext"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIMailConversationContext"
        }
      ],
      "role": "symbol",
      "title": "UIMailConversationContext",
      "type": "topic",
      "url": "/documentation/uikit/uimailconversationcontext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/MailEntry": {
      "abstract": [
        {
          "text": "A class that represents a specific email in an email thread.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MailEntry"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/MailEntry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MailEntry"
        }
      ],
      "role": "symbol",
      "title": "UIMailConversationContext.MailEntry",
      "type": "topic",
      "url": "/documentation/uikit/uimailconversationcontext/mailentry"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/responseHasCustomSignature": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the intended response contains a custom signature.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "responseHasCustomSignature"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/responseHasCustomSignature",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "responseHasCustomSignature"
        }
      ],
      "role": "symbol",
      "title": "responseHasCustomSignature",
      "type": "topic",
      "url": "/documentation/uikit/uimailconversationcontext/responsehascustomsignature"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/responseSecondaryRecipientIdentifiers": {
      "abstract": [
        {
          "text": "A set of strings that identifies the secondary recipients of the message, such as those in CC or BCC messages.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "responseSecondaryRecipientIdentifiers"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/responseSecondaryRecipientIdentifiers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "responseSecondaryRecipientIdentifiers"
        }
      ],
      "role": "symbol",
      "title": "responseSecondaryRecipientIdentifiers",
      "type": "topic",
      "url": "/documentation/uikit/uimailconversationcontext/responsesecondaryrecipientidentifiers"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/responseSubject": {
      "abstract": [
        {
          "text": "A string that contains the subject line of an intended response.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "responseSubject"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/responseSubject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "responseSubject"
        }
      ],
      "role": "symbol",
      "title": "responseSubject",
      "type": "topic",
      "url": "/documentation/uikit/uimailconversationcontext/responsesubject"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext": {
      "abstract": [
        {
          "text": "A class that represents a message conversation.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIMessageConversationContext"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIMessageConversationContext"
        }
      ],
      "role": "symbol",
      "title": "UIMessageConversationContext",
      "type": "topic",
      "url": "/documentation/uikit/uimessageconversationcontext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry": {
      "abstract": [
        {
          "text": "A class that represents a message in a message conversation.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MessageEntry"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MessageEntry"
        }
      ],
      "role": "symbol",
      "title": "UIMessageConversationContext.MessageEntry",
      "type": "topic",
      "url": "/documentation/uikit/uimessageconversationcontext/messageentry"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISmartReplySuggestion": {
      "abstract": [
        {
          "text": "A class you use to handle a Smart Reply suggestion.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISmartReplySuggestion"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISmartReplySuggestion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISmartReplySuggestion"
        }
      ],
      "role": "symbol",
      "title": "UISmartReplySuggestion",
      "type": "topic",
      "url": "/documentation/uikit/uismartreplysuggestion"
    },
    "doc://com.apple.uikit/documentation/UIKit/adopting-smart-reply-in-your-messaging-or-email-app": {
      "abstract": [
        {
          "text": "Generate reply suggestions by using Apple Intelligence and put selected text into your text UI.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/adopting-smart-reply-in-your-messaging-or-email-app",
      "kind": "article",
      "role": "article",
      "title": "Adopting Smart Reply in your messaging or email app",
      "type": "topic",
      "url": "/documentation/uikit/adopting-smart-reply-in-your-messaging-or-email-app"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIConversationContext"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Smart-Reply-for-messaging",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/adopting-smart-reply-in-your-messaging-or-email-app",
        "doc://com.apple.uikit/documentation/UIKit/UIConversationContext",
        "doc://com.apple.uikit/documentation/UIKit/UIConversationContext/Entry",
        "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/MailEntry",
        "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext",
        "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry",
        "doc://com.apple.uikit/documentation/UIKit/UIInputSuggestion",
        "doc://com.apple.uikit/documentation/UIKit/UISmartReplySuggestion"
      ],
      "title": "Smart Reply for messaging"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-message-details",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/responseSubject",
        "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/responseHasCustomSignature",
        "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/responseSecondaryRecipientIdentifiers"
      ],
      "title": "Getting message details"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": true,
              "deprecated": false,
              "introducedAt": "18.4",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIMailConversationContext"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMailConversationContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMailConversationContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-message-details",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/responseSubject",
                "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/responseHasCustomSignature",
                "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/responseSecondaryRecipientIdentifiers"
              ],
              "title": "Getting message details"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIConversationContext"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Smart-Reply-for-messaging",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/adopting-smart-reply-in-your-messaging-or-email-app",
                "doc://com.apple.uikit/documentation/UIKit/UIConversationContext",
                "doc://com.apple.uikit/documentation/UIKit/UIConversationContext/Entry",
                "doc://com.apple.uikit/documentation/UIKit/UIMailConversationContext/MailEntry",
                "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext",
                "doc://com.apple.uikit/documentation/UIKit/UIMessageConversationContext/MessageEntry",
                "doc://com.apple.uikit/documentation/UIKit/UIInputSuggestion",
                "doc://com.apple.uikit/documentation/UIKit/UISmartReplySuggestion"
              ],
              "title": "Smart Reply for messaging"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIMailConversationContext"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIConversationContext",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UIConversationContext",
                    "text": "UIConversationContext"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMailConversationContext~1responseHasCustomSignature/title",
          "value": "responseHasCustomSignature"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMailConversationContext~1responseHasCustomSignature/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "responseHasCustomSignature"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMailConversationContext~1responseSecondaryRecipientIdentifiers/title",
          "value": "responseSecondaryRecipientIdentifiers"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMailConversationContext~1responseSecondaryRecipientIdentifiers/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "responseSecondaryRecipientIdentifiers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIConversationContext/title",
          "value": "UIConversationContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIConversationContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIConversationContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIConversationContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIConversationContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMailConversationContext~1MailEntry/title",
          "value": "UIMailConversationEntry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMailConversationContext~1MailEntry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMailConversationEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMailConversationContext~1MailEntry/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMailConversationEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIConversationContext~1Entry/title",
          "value": "UIConversationEntry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIConversationContext~1Entry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIConversationEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIConversationContext~1Entry/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIConversationEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMessageConversationContext/title",
          "value": "UIMessageConversationContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMessageConversationContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMessageConversationContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMessageConversationContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMessageConversationContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInputSuggestion/title",
          "value": "UIInputSuggestion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInputSuggestion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIInputSuggestion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInputSuggestion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIInputSuggestion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMailConversationContext/title",
          "value": "UIMailConversationContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMailConversationContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMailConversationContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMailConversationContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMailConversationContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMessageConversationContext~1MessageEntry/title",
          "value": "UIMessageConversationEntry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMessageConversationContext~1MessageEntry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMessageConversationEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMessageConversationContext~1MessageEntry/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMessageConversationEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISmartReplySuggestion/title",
          "value": "UISmartReplySuggestion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISmartReplySuggestion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISmartReplySuggestion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISmartReplySuggestion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISmartReplySuggestion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMailConversationContext~1responseSubject/title",
          "value": "responseSubject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMailConversationContext~1responseSubject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "responseSubject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uimailconversationcontext"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uimailconversationcontext"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
