{"sections":[],"topicSections":[{"title":"Initializing a motion effect","anchor":"Initializing-a-motion-effect","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIMotionEffect/init()","doc://com.apple.uikit/documentation/UIKit/UIMotionEffect/init(coder:)"]},{"title":"Getting the key paths","anchor":"Getting-the-key-paths","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIMotionEffect/keyPathsAndRelativeValues(forViewerOffset:)"]}],"abstract":[{"text":"An abstract superclass for defining motion-based modifiers for views.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIMotionEffect","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Subclasses of "},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIMotionEffect","isActive":true},{"type":"text","text":" are responsible for defining the behavior to apply to a view when motion is detected. They do this by overriding the "},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIMotionEffect/keyPathsAndRelativeValues(forViewerOffset:)"},{"text":" method and returning one or more key paths representing the view properties to modify.","type":"text"}]},{"level":3,"type":"heading","text":"Subclassing notes","anchor":"Subclassing-notes"},{"type":"paragraph","inlineContent":[{"text":"This class is abstract and can’t be instantiated directly. You can use the ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIInterpolatingMotionEffect","type":"reference"},{"text":" class to implement effects or you can subclass and implement your own effects. If you subclass, your subclass must conform to the ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/foundation/nscopying","type":"reference"},{"text":" and ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/foundation/nscoding","type":"reference"},{"text":" protocols and must implement the ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIMotionEffect/keyPathsAndRelativeValues(forViewerOffset:)","type":"reference"},{"text":" method.","type":"text"}]}],"kind":"content"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIMotionEffect"},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc://com.externally.resolved.symbol/c:objc(cs)NSObject"],"kind":"relationships"},{"type":"inheritedBy","title":"Inherited By","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIInterpolatingMotionEffect","doc://com.apple.uikit/documentation/UIKit/UIMotionEffectGroup"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc://com.externally.resolved.symbol/s:s7CVarArgP","doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/c:objc(pl)NSCoding","doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","doc://com.externally.resolved.symbol/c:objc(pl)NSObject","doc://com.externally.resolved.symbol/s:s8SendableP"],"kind":"relationships"}],"metadata":{"role":"symbol","title":"UIMotionEffect","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"UIMotionEffect"}],"modules":[{"name":"UIKit"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIMotionEffect","kind":"identifier"}],"symbolKind":"class","platforms":[{"deprecated":false,"introducedAt":"7.0","name":"iOS","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"7.0","name":"iPadOS","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"13.1","name":"Mac Catalyst","unavailable":false,"beta":false},{"deprecated":false,"name":"tvOS","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"1.0","name":"visionOS","unavailable":false,"beta":false}],"externalID":"c:objc(cs)UIMotionEffect"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uimotioneffect"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uimotioneffect"]}],"references":{"doc://com.apple.documentation/documentation/foundation/nscoding":{"type":"topic","identifier":"doc://com.apple.documentation/documentation/foundation/nscoding","role":"symbol","title":"NSCoding","abstract":[{"type":"text","text":"A protocol that enables an object to be encoded and decoded for archiving and distribution."}],"fragments":[{"text":"protocol ","kind":"text"},{"text":"NSCoding","kind":"identifier"}],"url":"/documentation/foundation/nscoding","kind":"symbol"},"doc://com.externally.resolved.symbol/c:objc(cs)NSObject":{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSObject","role":"symbol","kind":"symbol","url":"/documentation/objectivec/nsobject","title":"NSObject","type":"topic","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSObject"}],"abstract":[{"text":"The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.","type":"text"}]},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"title":"NSObjectProtocol","type":"topic","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","role":"symbol","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"kind":"symbol","url":"/documentation/objectivec/nsobjectprotocol"},"doc://com.apple.uikit/documentation/UIKit/UIMotionEffect/keyPathsAndRelativeValues(forViewerOffset:)":{"role":"symbol","abstract":[{"text":"For a given set of offset values, returns the view properties (and corresponding values) to update.","type":"text"}],"title":"keyPathsAndRelativeValues(forViewerOffset:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyPathsAndRelativeValues","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forViewerOffset","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIOffset","preciseIdentifier":"c:@S@UIOffset","kind":"typeIdentifier"},{"text":") -> [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"url":"/documentation/uikit/uimotioneffect/keypathsandrelativevalues(forvieweroffset:)","navigatorTitle":[{"kind":"identifier","text":"keyPathsAndRelativeValuesForViewerOffset:"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIMotionEffect/keyPathsAndRelativeValues(forViewerOffset:)","kind":"symbol"},"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying":{"kind":"symbol","abstract":[{"text":"A protocol that objects adopt to provide functional copies of themselves.","type":"text"}],"url":"/documentation/foundation/nscopying","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSCopying","kind":"identifier"}],"title":"NSCopying","type":"topic","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIMotionEffect/init()":{"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","url":"/documentation/uikit/uimotioneffect/init()","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIMotionEffect/init()","title":"init()","type":"topic","navigatorTitle":[{"text":"init","kind":"identifier"}],"abstract":[{"type":"text","text":"Initializes the motion effect to its default state."}]},"doc://com.externally.resolved.symbol/c:objc(pl)NSCoding":{"url":"/documentation/foundation/nscoding","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCoding","role":"symbol","fragments":[{"kind":"text","text":"protocol "},{"kind":"identifier","text":"NSCoding"}],"type":"topic","title":"NSCoding","kind":"symbol","abstract":[{"text":"A protocol that enables an object to be encoded and decoded for archiving and distribution.","type":"text"}]},"doc://com.externally.resolved.symbol/s:SQ":{"abstract":[{"type":"text","text":"A type that can be compared for value equality."}],"url":"/documentation/Swift/Equatable","identifier":"doc://com.externally.resolved.symbol/s:SQ","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"role":"symbol","title":"Equatable","type":"topic","kind":"symbol"},"doc://com.apple.documentation/documentation/foundation/nscopying":{"fragments":[{"text":"protocol ","kind":"text"},{"text":"NSCopying","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"NSCopying","abstract":[{"type":"text","text":"A protocol that objects adopt to provide functional copies of themselves."}],"type":"topic","url":"/documentation/foundation/nscopying","identifier":"doc://com.apple.documentation/documentation/foundation/nscopying"},"doc://com.externally.resolved.symbol/s:s7CVarArgP":{"abstract":[{"type":"text","text":"A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVarArg"}],"identifier":"doc://com.externally.resolved.symbol/s:s7CVarArgP","type":"topic","title":"CVarArg","kind":"symbol","role":"symbol","url":"/documentation/Swift/CVarArg"},"doc://com.apple.uikit/documentation/UIKit/UIMotionEffect/init(coder:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"coder","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"text":")","kind":"text"}],"kind":"symbol","url":"/documentation/uikit/uimotioneffect/init(coder:)","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIMotionEffect/init(coder:)","title":"init(coder:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"abstract":[{"type":"text","text":"Creates a motion effect from data in an unarchiver."}]},"doc://com.apple.uikit/documentation/UIKit/UIInterpolatingMotionEffect":{"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIInterpolatingMotionEffect"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIInterpolatingMotionEffect","title":"UIInterpolatingMotionEffect","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIInterpolatingMotionEffect"}],"abstract":[{"text":"An object that maps the horizontal or vertical tilt of a device to values that you specify so that UIKit can apply those values to your views.","type":"text"}],"url":"/documentation/uikit/uiinterpolatingmotioneffect"},"doc://com.externally.resolved.symbol/s:s8SendableP":{"abstract":[{"type":"text","text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races."}],"url":"/documentation/Swift/Sendable","identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}],"role":"symbol","title":"Sendable","type":"topic","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIMotionEffect":{"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIMotionEffect"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIMotionEffect","title":"UIMotionEffect","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UIMotionEffect"}],"abstract":[{"type":"text","text":"An abstract superclass for defining motion-based modifiers for views."}],"url":"/documentation/uikit/uimotioneffect"},"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP":{"identifier":"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","kind":"symbol","type":"topic","title":"CustomDebugStringConvertible","url":"/documentation/Swift/CustomDebugStringConvertible","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomDebugStringConvertible"}],"role":"symbol","abstract":[{"type":"text","text":"A type with a customized textual representation suitable for debugging purposes."}]},"doc://com.apple.uikit/documentation/UIKit/UIMotionEffectGroup":{"kind":"symbol","role":"symbol","title":"UIMotionEffectGroup","navigatorTitle":[{"text":"UIMotionEffectGroup","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIMotionEffectGroup","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIMotionEffectGroup","url":"/documentation/uikit/uimotioneffectgroup","abstract":[{"type":"text","text":"A collection of motion effects that you want to apply to a view at the same time."}],"type":"topic"},"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP":{"identifier":"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","kind":"symbol","type":"topic","title":"CustomStringConvertible","url":"/documentation/Swift/CustomStringConvertible","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomStringConvertible"}],"role":"symbol","abstract":[{"text":"A type with a customized textual representation.","type":"text"}]},"doc://com.externally.resolved.symbol/s:SH":{"abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}],"url":"/documentation/Swift/Hashable","identifier":"doc://com.externally.resolved.symbol/s:SH","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hashable","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SQ","text":"Equatable","kind":"typeIdentifier"}],"role":"symbol","title":"Hashable","type":"topic","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"name":"iOS","introducedAt":"7.0","beta":false,"deprecated":false,"unavailable":false},{"name":"iPadOS","introducedAt":"7.0","beta":false,"deprecated":false,"unavailable":false},{"name":"Mac Catalyst","introducedAt":"13.1","beta":false,"deprecated":false,"unavailable":false},{"name":"tvOS","beta":false,"deprecated":false,"unavailable":false},{"name":"visionOS","introducedAt":"1.0","beta":false,"deprecated":false,"unavailable":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Class","path":"/metadata/roleHeading"},{"op":"replace","value":"UIMotionEffect","path":"/metadata/title"},{"op":"replace","value":"class","path":"/metadata/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"UIMotionEffect"}],"path":"/metadata/fragments"},{"op":"replace","value":[{"text":"UIMotionEffect","kind":"identifier"}],"path":"/metadata/navigatorTitle"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"path":"/hierarchy"},{"op":"replace","value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIMotionEffect/init()","doc://com.apple.uikit/documentation/UIKit/UIMotionEffect/init(coder:)"],"title":"Initializing a motion effect","anchor":"Initializing-a-motion-effect"},{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIMotionEffect/keyPathsAndRelativeValues(forViewerOffset:)"],"title":"Getting the key paths","anchor":"Getting-the-key-paths"}],"path":"/topicSections"},{"op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/c:objc(cs)NSObject"]},{"type":"inheritedBy","title":"Inherited By","kind":"relationships","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIInterpolatingMotionEffect","doc://com.apple.uikit/documentation/UIKit/UIMotionEffectGroup"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/c:objc(pl)NSCoding","doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"]}],"path":"/relationshipsSections"},{"op":"add","value":null,"path":"/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIMotionEffect","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}]},"path":"/primaryContentSections/0"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title","op":"replace","value":"NSObject"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMotionEffect~1keyPathsAndRelativeValues(forViewerOffset:)/title","op":"replace","value":"keyPathsAndRelativeValuesForViewerOffset:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMotionEffect~1keyPathsAndRelativeValues(forViewerOffset:)/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"keyPathsAndRelativeValuesForViewerOffset:","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMotionEffect~1init()/title","op":"replace","value":"init"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMotionEffect~1init()/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMotionEffect~1init(coder:)/title","op":"replace","value":"initWithCoder:"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMotionEffect~1init(coder:)/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInterpolatingMotionEffect/title","op":"replace","value":"UIInterpolatingMotionEffect"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInterpolatingMotionEffect/fragments","op":"replace","value":[{"text":"UIInterpolatingMotionEffect","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInterpolatingMotionEffect/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIInterpolatingMotionEffect"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMotionEffect/title","op":"replace","value":"UIMotionEffect"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMotionEffect/fragments","op":"replace","value":[{"kind":"identifier","text":"UIMotionEffect"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMotionEffect/navigatorTitle","op":"replace","value":[{"text":"UIMotionEffect","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMotionEffectGroup/title","op":"replace","value":"UIMotionEffectGroup"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMotionEffectGroup/fragments","op":"replace","value":[{"text":"UIMotionEffectGroup","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMotionEffectGroup/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIMotionEffectGroup"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}