{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UIMutableTraits",
    "fragments": [
      {
        "kind": "identifier",
        "text": "UIMutableTraits"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIMutableTraits"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "UIMutableTraits"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIMutableTraits"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAdaptivePresentationControllerDelegate": {
      "abstract": [
        {
          "text": "A set of methods that, in conjunction with a presentation controller, determine how to respond to trait changes in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAdaptivePresentationControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAdaptivePresentationControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAdaptivePresentationControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIAdaptivePresentationControllerDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uiadaptivepresentationcontrollerdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICGFloatTrait": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UICGFloatTrait"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICGFloatTrait",
      "kind": "symbol",
      "role": "symbol",
      "title": "UICGFloatTrait",
      "type": "topic",
      "url": "/documentation/uikit/uicgfloattrait"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentContainer": {
      "abstract": [
        {
          "text": "A set of methods for adapting the contents of your view controllers to size and trait changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIContentContainer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentContainer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentContainer"
        }
      ],
      "role": "symbol",
      "title": "UIContentContainer",
      "type": "topic",
      "url": "/documentation/uikit/uicontentcontainer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIMutableTraits"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIMutableTraits",
      "type": "topic",
      "url": "/documentation/uikit/uimutabletraits-8l00o"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/accessibilityContrast": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "accessibilityContrast"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/accessibilityContrast",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityContrast",
      "type": "topic",
      "url": "/documentation/uikit/uimutabletraits-8l00o/accessibilitycontrast"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/activeAppearance": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "activeAppearance"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/activeAppearance",
      "kind": "symbol",
      "role": "symbol",
      "title": "activeAppearance",
      "type": "topic",
      "url": "/documentation/uikit/uimutabletraits-8l00o/activeappearance"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/displayGamut": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "displayGamut"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/displayGamut",
      "kind": "symbol",
      "role": "symbol",
      "title": "displayGamut",
      "type": "topic",
      "url": "/documentation/uikit/uimutabletraits-8l00o/displaygamut"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/displayScale": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "displayScale"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/displayScale",
      "kind": "symbol",
      "role": "symbol",
      "title": "displayScale",
      "type": "topic",
      "url": "/documentation/uikit/uimutabletraits-8l00o/displayscale"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/forceTouchCapability": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "forceTouchCapability"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/forceTouchCapability",
      "kind": "symbol",
      "role": "symbol",
      "title": "forceTouchCapability",
      "type": "topic",
      "url": "/documentation/uikit/uimutabletraits-8l00o/forcetouchcapability"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/horizontalSizeClass": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "horizontalSizeClass"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/horizontalSizeClass",
      "kind": "symbol",
      "role": "symbol",
      "title": "horizontalSizeClass",
      "type": "topic",
      "url": "/documentation/uikit/uimutabletraits-8l00o/horizontalsizeclass"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/imageDynamicRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "imageDynamicRange"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/imageDynamicRange",
      "kind": "symbol",
      "role": "symbol",
      "title": "imageDynamicRange",
      "type": "topic",
      "url": "/documentation/uikit/uimutabletraits-8l00o/imagedynamicrange"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/layoutDirection": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "layoutDirection"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/layoutDirection",
      "kind": "symbol",
      "role": "symbol",
      "title": "layoutDirection",
      "type": "topic",
      "url": "/documentation/uikit/uimutabletraits-8l00o/layoutdirection"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/legibilityWeight": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "legibilityWeight"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/legibilityWeight",
      "kind": "symbol",
      "role": "symbol",
      "title": "legibilityWeight",
      "type": "topic",
      "url": "/documentation/uikit/uimutabletraits-8l00o/legibilityweight"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/listEnvironment": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "listEnvironment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/listEnvironment",
      "kind": "symbol",
      "role": "symbol",
      "title": "listEnvironment",
      "type": "topic",
      "url": "/documentation/uikit/uimutabletraits-8l00o/listenvironment"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/objectForTrait:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "objectForTrait:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/objectForTrait:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "objectForTrait:"
        }
      ],
      "role": "symbol",
      "title": "objectForTrait:",
      "type": "topic",
      "url": "/documentation/uikit/uimutabletraits-8l00o/objectfortrait:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/preferredContentSizeCategory": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "preferredContentSizeCategory"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/preferredContentSizeCategory",
      "kind": "symbol",
      "role": "symbol",
      "title": "preferredContentSizeCategory",
      "type": "topic",
      "url": "/documentation/uikit/uimutabletraits-8l00o/preferredcontentsizecategory"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/sceneCaptureState": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "sceneCaptureState"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/sceneCaptureState",
      "kind": "symbol",
      "role": "symbol",
      "title": "sceneCaptureState",
      "type": "topic",
      "url": "/documentation/uikit/uimutabletraits-8l00o/scenecapturestate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/setCGFloatValue:forTrait:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setCGFloatValue:forTrait:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/setCGFloatValue:forTrait:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setCGFloatValue:forTrait:"
        }
      ],
      "role": "symbol",
      "title": "setCGFloatValue:forTrait:",
      "type": "topic",
      "url": "/documentation/uikit/uimutabletraits-8l00o/setcgfloatvalue:fortrait:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/setNSIntegerValue:forTrait:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setNSIntegerValue:forTrait:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/setNSIntegerValue:forTrait:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setNSIntegerValue:forTrait:"
        }
      ],
      "role": "symbol",
      "title": "setNSIntegerValue:forTrait:",
      "type": "topic",
      "url": "/documentation/uikit/uimutabletraits-8l00o/setnsintegervalue:fortrait:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/setObject:forTrait:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setObject:forTrait:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/setObject:forTrait:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setObject:forTrait:"
        }
      ],
      "role": "symbol",
      "title": "setObject:forTrait:",
      "type": "topic",
      "url": "/documentation/uikit/uimutabletraits-8l00o/setobject:fortrait:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/toolbarItemPresentationSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "toolbarItemPresentationSize"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/toolbarItemPresentationSize",
      "kind": "symbol",
      "role": "symbol",
      "title": "toolbarItemPresentationSize",
      "type": "topic",
      "url": "/documentation/uikit/uimutabletraits-8l00o/toolbaritempresentationsize"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/typesettingLanguage": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "typesettingLanguage"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/typesettingLanguage",
      "kind": "symbol",
      "role": "symbol",
      "title": "typesettingLanguage",
      "type": "topic",
      "url": "/documentation/uikit/uimutabletraits-8l00o/typesettinglanguage"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/userInterfaceIdiom": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "userInterfaceIdiom"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/userInterfaceIdiom",
      "kind": "symbol",
      "role": "symbol",
      "title": "userInterfaceIdiom",
      "type": "topic",
      "url": "/documentation/uikit/uimutabletraits-8l00o/userinterfaceidiom"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/userInterfaceLevel": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "userInterfaceLevel"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/userInterfaceLevel",
      "kind": "symbol",
      "role": "symbol",
      "title": "userInterfaceLevel",
      "type": "topic",
      "url": "/documentation/uikit/uimutabletraits-8l00o/userinterfacelevel"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/userInterfaceStyle": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "userInterfaceStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/userInterfaceStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "userInterfaceStyle",
      "type": "topic",
      "url": "/documentation/uikit/uimutabletraits-8l00o/userinterfacestyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/valueForCGFloatTrait:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "valueForCGFloatTrait:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/valueForCGFloatTrait:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "valueForCGFloatTrait:"
        }
      ],
      "role": "symbol",
      "title": "valueForCGFloatTrait:",
      "type": "topic",
      "url": "/documentation/uikit/uimutabletraits-8l00o/valueforcgfloattrait:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/valueForNSIntegerTrait:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "valueForNSIntegerTrait:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/valueForNSIntegerTrait:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "valueForNSIntegerTrait:"
        }
      ],
      "role": "symbol",
      "title": "valueForNSIntegerTrait:",
      "type": "topic",
      "url": "/documentation/uikit/uimutabletraits-8l00o/valuefornsintegertrait:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/verticalSizeClass": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "verticalSizeClass"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/verticalSizeClass",
      "kind": "symbol",
      "role": "symbol",
      "title": "verticalSizeClass",
      "type": "topic",
      "url": "/documentation/uikit/uimutabletraits-8l00o/verticalsizeclass"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINSIntegerTrait": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UINSIntegerTrait"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINSIntegerTrait",
      "kind": "symbol",
      "role": "symbol",
      "title": "UINSIntegerTrait",
      "type": "topic",
      "url": "/documentation/uikit/uinsintegertrait"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIObjectTrait": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIObjectTrait"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIObjectTrait",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIObjectTrait",
      "type": "topic",
      "url": "/documentation/uikit/uiobjecttrait"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitAccessibilityContrast-c.class": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITraitAccessibilityContrast"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitAccessibilityContrast-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitAccessibilityContrast",
      "type": "topic",
      "url": "/documentation/uikit/uitraitaccessibilitycontrast-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitActiveAppearance-c.class": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITraitActiveAppearance"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitActiveAppearance-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitActiveAppearance",
      "type": "topic",
      "url": "/documentation/uikit/uitraitactiveappearance-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-7qoet": {
      "abstract": [
        {
          "text": "A type that calls your code in reaction to changes in the trait environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITraitChangeObservable"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-7qoet",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitChangeObservable",
      "type": "topic",
      "url": "/documentation/uikit/uitraitchangeobservable-7qoet"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitCollection": {
      "abstract": [
        {
          "text": "A collection of data that represents the environment for an individual element in your app’s user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITraitCollection"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITraitCollection"
        }
      ],
      "role": "symbol",
      "title": "UITraitCollection",
      "type": "topic",
      "url": "/documentation/uikit/uitraitcollection"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitDisplayGamut-c.class": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITraitDisplayGamut"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitDisplayGamut-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitDisplayGamut",
      "type": "topic",
      "url": "/documentation/uikit/uitraitdisplaygamut-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitDisplayScale-c.class": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITraitDisplayScale"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitDisplayScale-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitDisplayScale",
      "type": "topic",
      "url": "/documentation/uikit/uitraitdisplayscale-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitEnvironment": {
      "abstract": [
        {
          "text": "A set of methods that makes the iOS interface environment available to your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITraitEnvironment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitEnvironment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITraitEnvironment"
        }
      ],
      "role": "symbol",
      "title": "UITraitEnvironment",
      "type": "topic",
      "url": "/documentation/uikit/uitraitenvironment"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitForceTouchCapability-c.class": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITraitForceTouchCapability"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitForceTouchCapability-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitForceTouchCapability",
      "type": "topic",
      "url": "/documentation/uikit/uitraitforcetouchcapability-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitHorizontalSizeClass-c.class": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITraitHorizontalSizeClass"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitHorizontalSizeClass-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitHorizontalSizeClass",
      "type": "topic",
      "url": "/documentation/uikit/uitraithorizontalsizeclass-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitImageDynamicRange-c.class": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITraitImageDynamicRange"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitImageDynamicRange-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitImageDynamicRange",
      "type": "topic",
      "url": "/documentation/uikit/uitraitimagedynamicrange-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitLayoutDirection-c.class": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITraitLayoutDirection"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitLayoutDirection-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitLayoutDirection",
      "type": "topic",
      "url": "/documentation/uikit/uitraitlayoutdirection-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitLegibilityWeight-c.class": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITraitLegibilityWeight"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitLegibilityWeight-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitLegibilityWeight",
      "type": "topic",
      "url": "/documentation/uikit/uitraitlegibilityweight-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitListEnvironment-c.class": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITraitListEnvironment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitListEnvironment-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitListEnvironment",
      "type": "topic",
      "url": "/documentation/uikit/uitraitlistenvironment-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitOverrides-c.protocol": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITraitOverrides"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitOverrides-c.protocol",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitOverrides",
      "type": "topic",
      "url": "/documentation/uikit/uitraitoverrides-c.protocol"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitPreferredContentSizeCategory-c.class": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITraitPreferredContentSizeCategory"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitPreferredContentSizeCategory-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitPreferredContentSizeCategory",
      "type": "topic",
      "url": "/documentation/uikit/uitraitpreferredcontentsizecategory-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitSceneCaptureState-c.class": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITraitSceneCaptureState"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitSceneCaptureState-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitSceneCaptureState",
      "type": "topic",
      "url": "/documentation/uikit/uitraitscenecapturestate-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitToolbarItemPresentationSize-c.class": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITraitToolbarItemPresentationSize"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitToolbarItemPresentationSize-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitToolbarItemPresentationSize",
      "type": "topic",
      "url": "/documentation/uikit/uitraittoolbaritempresentationsize-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitTypesettingLanguage-c.class": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITraitTypesettingLanguage"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitTypesettingLanguage-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitTypesettingLanguage",
      "type": "topic",
      "url": "/documentation/uikit/uitraittypesettinglanguage-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitUserInterfaceIdiom-c.class": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITraitUserInterfaceIdiom"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitUserInterfaceIdiom-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitUserInterfaceIdiom",
      "type": "topic",
      "url": "/documentation/uikit/uitraituserinterfaceidiom-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitUserInterfaceLevel-c.class": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITraitUserInterfaceLevel"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitUserInterfaceLevel-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitUserInterfaceLevel",
      "type": "topic",
      "url": "/documentation/uikit/uitraituserinterfacelevel-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitUserInterfaceStyle-c.class": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITraitUserInterfaceStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitUserInterfaceStyle-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitUserInterfaceStyle",
      "type": "topic",
      "url": "/documentation/uikit/uitraituserinterfacestyle-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitVerticalSizeClass-c.class": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITraitVerticalSizeClass"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitVerticalSizeClass-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitVerticalSizeClass",
      "type": "topic",
      "url": "/documentation/uikit/uitraitverticalsizeclass-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/automatic-trait-tracking": {
      "abstract": [
        {
          "text": "Reduce the need to manually register for trait changes when you use traits within a method or closure that supports automatic trait tracking.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/automatic-trait-tracking",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Automatic trait tracking",
      "type": "topic",
      "url": "/documentation/uikit/automatic-trait-tracking"
    },
    "doc://com.apple.uikit/documentation/UIKit/responding-to-changing-display-modes-on-apple-tv": {
      "abstract": [
        {
          "text": "Change images and resources dynamically when the screen gamut on your device changes.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/responding-to-changing-display-modes-on-apple-tv",
      "kind": "article",
      "role": "article",
      "title": "Responding to changing display modes on Apple TV",
      "type": "topic",
      "url": "/documentation/uikit/responding-to-changing-display-modes-on-apple-tv"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITraitOverrides-c.protocol"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Adaptivity",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/automatic-trait-tracking",
        "doc://com.apple.uikit/documentation/UIKit/responding-to-changing-display-modes-on-apple-tv",
        "doc://com.apple.uikit/documentation/UIKit/UITraitCollection",
        "doc://com.apple.uikit/documentation/UIKit/UITraitEnvironment",
        "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-7qoet",
        "doc://com.apple.uikit/documentation/UIKit/UIAdaptivePresentationControllerDelegate",
        "doc://com.apple.uikit/documentation/UIKit/UIContentContainer"
      ],
      "title": "Adaptivity"
    }
  ],
  "topicSections": [
    {
      "anchor": "Defining-custom-traits",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/accessibilityContrast",
        "doc://com.apple.uikit/documentation/UIKit/UITraitAccessibilityContrast-c.class",
        "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/activeAppearance",
        "doc://com.apple.uikit/documentation/UIKit/UITraitActiveAppearance-c.class",
        "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/displayGamut",
        "doc://com.apple.uikit/documentation/UIKit/UITraitDisplayGamut-c.class",
        "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/displayScale",
        "doc://com.apple.uikit/documentation/UIKit/UITraitDisplayScale-c.class",
        "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/forceTouchCapability",
        "doc://com.apple.uikit/documentation/UIKit/UITraitForceTouchCapability-c.class",
        "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/horizontalSizeClass",
        "doc://com.apple.uikit/documentation/UIKit/UITraitHorizontalSizeClass-c.class",
        "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/imageDynamicRange",
        "doc://com.apple.uikit/documentation/UIKit/UITraitImageDynamicRange-c.class",
        "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/layoutDirection",
        "doc://com.apple.uikit/documentation/UIKit/UITraitLayoutDirection-c.class",
        "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/legibilityWeight",
        "doc://com.apple.uikit/documentation/UIKit/UITraitLegibilityWeight-c.class",
        "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/listEnvironment",
        "doc://com.apple.uikit/documentation/UIKit/UITraitListEnvironment-c.class",
        "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/preferredContentSizeCategory",
        "doc://com.apple.uikit/documentation/UIKit/UITraitPreferredContentSizeCategory-c.class",
        "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/sceneCaptureState",
        "doc://com.apple.uikit/documentation/UIKit/UITraitSceneCaptureState-c.class",
        "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/toolbarItemPresentationSize",
        "doc://com.apple.uikit/documentation/UIKit/UITraitToolbarItemPresentationSize-c.class",
        "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/typesettingLanguage",
        "doc://com.apple.uikit/documentation/UIKit/UITraitTypesettingLanguage-c.class",
        "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/userInterfaceIdiom",
        "doc://com.apple.uikit/documentation/UIKit/UITraitUserInterfaceIdiom-c.class",
        "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/userInterfaceLevel",
        "doc://com.apple.uikit/documentation/UIKit/UITraitUserInterfaceLevel-c.class",
        "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/userInterfaceStyle",
        "doc://com.apple.uikit/documentation/UIKit/UITraitUserInterfaceStyle-c.class",
        "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/verticalSizeClass",
        "doc://com.apple.uikit/documentation/UIKit/UITraitVerticalSizeClass-c.class"
      ],
      "title": "Defining custom traits"
    },
    {
      "anchor": "Getting-and-setting-trait-data",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/objectForTrait:",
        "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/setObject:forTrait:",
        "doc://com.apple.uikit/documentation/UIKit/UIObjectTrait",
        "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/valueForCGFloatTrait:",
        "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/setCGFloatValue:forTrait:",
        "doc://com.apple.uikit/documentation/UIKit/UICGFloatTrait",
        "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/valueForNSIntegerTrait:",
        "doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-8l00o/setNSIntegerValue:forTrait:",
        "doc://com.apple.uikit/documentation/UIKit/UINSIntegerTrait"
      ],
      "title": "Getting and setting trait data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentContainer/title",
          "value": "UIContentContainer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentContainer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentContainer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitCollection/title",
          "value": "UITraitCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITraitCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitCollection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITraitCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitEnvironment/title",
          "value": "UITraitEnvironment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitEnvironment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITraitEnvironment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitEnvironment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITraitEnvironment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAdaptivePresentationControllerDelegate/title",
          "value": "UIAdaptivePresentationControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAdaptivePresentationControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAdaptivePresentationControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAdaptivePresentationControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAdaptivePresentationControllerDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uimutabletraits-8l00o"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
