{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UINavigationItemRenameDelegate-5j4ws"},"metadata":{"platforms":[{"name":"iOS","beta":false,"deprecated":false,"unavailable":false,"introducedAt":"16.0"},{"name":"iPadOS","beta":false,"deprecated":false,"unavailable":false,"introducedAt":"16.0"},{"name":"Mac Catalyst","beta":false,"deprecated":false,"unavailable":false},{"name":"visionOS","beta":false,"deprecated":false,"unavailable":false}],"roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UINavigationItemRenameDelegate","kind":"identifier"}],"symbolKind":"protocol","modules":[{"name":"UIKit"}],"title":"UINavigationItemRenameDelegate","externalID":"s:5UIKit30UINavigationItemRenameDelegateP","role":"symbol","navigatorTitle":[{"text":"UINavigationItemRenameDelegate","kind":"identifier"}]},"seeAlsoSections":[{"title":"Renaming documents","identifiers":["doc://com.apple.uikit/documentation/UIKit/UINavigationItem/renameDelegate-8jiuf"],"anchor":"Renaming-documents","generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"kind":"text","text":" "},{"kind":"attribute","text":"@preconcurrency"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UINavigationItemRenameDelegate"},{"kind":"text","text":" : AnyObject"}]}]},{"kind":"content","content":[{"text":"Overview","anchor":"overview","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"A navigation item ("},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationItem"},{"type":"text","text":") uses this delegate to determine whether a person can change the navigation item’s title and to handle the rename process."}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"text":" ","type":"text"},{"text":"Session 10069: ","type":"text"},{"isActive":true,"identifier":"https://developer.apple.com/wwdc22/10069","type":"reference"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Session 10070: "},{"isActive":true,"type":"reference","identifier":"https://developer.apple.com/wwdc22/10070"}]}],"type":"aside","name":"Related Sessions from WWDC22"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","topicSections":[{"title":"Determining rename support","identifiers":["doc://com.apple.uikit/documentation/UIKit/UINavigationItemRenameDelegate-5j4ws/navigationItemShouldBeginRenaming(_:)","doc://com.apple.uikit/documentation/UIKit/UINavigationItemRenameDelegate-5j4ws/navigationItem(_:shouldEndRenamingWith:)"],"anchor":"Determining-rename-support"},{"title":"Handling the rename process","identifiers":["doc://com.apple.uikit/documentation/UIKit/UINavigationItemRenameDelegate-5j4ws/navigationItem(_:willBeginRenamingWith:selectedRange:)","doc://com.apple.uikit/documentation/UIKit/UINavigationItemRenameDelegate-5j4ws/navigationItem(_:didEndRenamingWith:)"],"anchor":"Handling-the-rename-process"}],"abstract":[{"type":"text","text":"Methods an object implements to rename a navigation item."}],"variants":[{"paths":["/documentation/uikit/uinavigationitemrenamedelegate-5j4ws"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"references":{"doc://com.apple.uikit/documentation/UIKit/UINavigationItem":{"title":"UINavigationItem","kind":"symbol","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationItem","abstract":[{"text":"The items that a navigation bar displays when the associated view controller is visible.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"UINavigationItem","kind":"identifier"}],"url":"/documentation/uikit/uinavigationitem","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UINavigationItem","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UINavigationItemRenameDelegate-5j4ws/navigationItem(_:shouldEndRenamingWith:)":{"type":"topic","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationItemRenameDelegate-5j4ws/navigationItem(_:shouldEndRenamingWith:)","abstract":[{"text":"Asks the delegate whether to continue or abandon the rename process.","type":"text"}],"defaultImplementations":1,"title":"navigationItem(_:shouldEndRenamingWith:)","url":"/documentation/uikit/uinavigationitemrenamedelegate-5j4ws/navigationitem(_:shouldendrenamingwith:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationItem"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationItem","text":"UINavigationItem"},{"text":", ","kind":"text"},{"text":"shouldEndRenamingWith","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"required":true},"doc://com.apple.uikit/documentation/UIKit/UINavigationItemRenameDelegate-5j4ws/navigationItem(_:willBeginRenamingWith:selectedRange:)":{"role":"symbol","kind":"symbol","defaultImplementations":1,"type":"topic","title":"navigationItem(_:willBeginRenamingWith:selectedRange:)","url":"/documentation/uikit/uinavigationitemrenamedelegate-5j4ws/navigationitem(_:willbeginrenamingwith:selectedrange:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationItemRenameDelegate-5j4ws/navigationItem(_:willBeginRenamingWith:selectedRange:)","abstract":[{"type":"text","text":"Tells the delegate when the rename process starts."}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationItem"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UINavigationItem","preciseIdentifier":"c:objc(cs)UINavigationItem"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willBeginRenamingWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"selectedRange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sn","text":"Range"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:SS5IndexV","text":"Index"},{"kind":"text","text":">) -> ("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sn","text":"Range"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:SS5IndexV","text":"Index"},{"kind":"text","text":">)"}]},"doc://com.apple.uikit/documentation/UIKit/UINavigationItemRenameDelegate-5j4ws/navigationItemShouldBeginRenaming(_:)":{"type":"topic","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationItemRenameDelegate-5j4ws/navigationItemShouldBeginRenaming(_:)","abstract":[{"text":"Asks the delegate whether the navigation item supports renaming.","type":"text"}],"defaultImplementations":1,"title":"navigationItemShouldBeginRenaming(_:)","url":"/documentation/uikit/uinavigationitemrenamedelegate-5j4ws/navigationitemshouldbeginrenaming(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationItemShouldBeginRenaming"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationItem","text":"UINavigationItem"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"required":true},"https://developer.apple.com/wwdc22/10070":{"identifier":"https://developer.apple.com/wwdc22/10070","url":"https://developer.apple.com/wwdc22/10070","type":"link","titleInlineContent":[{"type":"text","text":"Build a desktop-class iPad app"}],"title":"Build a desktop-class iPad app"},"https://developer.apple.com/wwdc22/10069":{"identifier":"https://developer.apple.com/wwdc22/10069","url":"https://developer.apple.com/wwdc22/10069","type":"link","titleInlineContent":[{"type":"text","text":"Meet desktop-class iPad"}],"title":"Meet desktop-class iPad"},"doc://com.apple.uikit/documentation/UIKit/UINavigationItemRenameDelegate-5j4ws":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"UINavigationItemRenameDelegate"}],"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationItemRenameDelegate-5j4ws","abstract":[{"text":"Methods an object implements to rename a navigation item.","type":"text"}],"title":"UINavigationItemRenameDelegate","url":"/documentation/uikit/uinavigationitemrenamedelegate-5j4ws","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UINavigationItemRenameDelegate"}]},"doc://com.apple.uikit/documentation/UIKit/UINavigationItem/renameDelegate-8jiuf":{"title":"renameDelegate","type":"topic","kind":"symbol","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationItem/renameDelegate-8jiuf","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"renameDelegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"UINavigationItemRenameDelegate","preciseIdentifier":"s:5UIKit30UINavigationItemRenameDelegateP","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"url":"/documentation/uikit/uinavigationitem/renamedelegate-8jiuf","abstract":[{"text":"The delegate for renaming the navigation item.","type":"text"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UINavigationItemRenameDelegate-5j4ws/navigationItem(_:didEndRenamingWith:)":{"role":"symbol","type":"topic","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UINavigationItemRenameDelegate-5j4ws/navigationItem(_:didEndRenamingWith:)","url":"/documentation/uikit/uinavigationitemrenamedelegate-5j4ws/navigationitem(_:didendrenamingwith:)","abstract":[{"type":"text","text":"Tells the delegate when the rename process ends."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"navigationItem","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UINavigationItem","preciseIdentifier":"c:objc(cs)UINavigationItem","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didEndRenamingWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"navigationItem(_:didEndRenamingWith:)","required":true},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"UINavigationItem","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationItem/title"},{"value":[{"text":"UINavigationItem","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationItem/fragments"},{"value":[{"kind":"identifier","text":"UINavigationItem"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationItem/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}