{
  "abstract": [
    {
      "text": "Customize appearance information directly on the navigation bar object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/view-controllers",
        "doc://com.apple.uikit/documentation/UIKit/UINavigationBar"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/views-and-controls",
        "doc://com.apple.uikit/documentation/UIKit/UINavigationBar"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/uinavigationbar-legacy-customizations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Legacy customizations"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In iOS 13 and later, customize your navigation bar using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/standardAppearance",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/compactAppearance",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/scrollEdgeAppearance",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties. You may continue to use these legacy accessors to customize your navigation bar’s appearance directly, but you must update the appearance for different bar configurations yourself.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarStyle": {
      "abstract": [
        {
          "text": "Defines the stylistic appearance of different types of views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIBarStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarStyle"
        }
      ],
      "role": "symbol",
      "title": "UIBarStyle",
      "type": "topic",
      "url": "/documentation/uikit/uibarstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationBar": {
      "abstract": [
        {
          "text": "Navigational controls that display in a bar along the top of the screen, usually in conjunction with a navigation controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UINavigationBar"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationBar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UINavigationBar"
        }
      ],
      "role": "symbol",
      "title": "UINavigationBar",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationbar"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backIndicatorImage": {
      "abstract": [
        {
          "text": "The image shown beside the Back button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backIndicatorImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backIndicatorImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backIndicatorImage"
        }
      ],
      "role": "symbol",
      "title": "backIndicatorImage",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationbar/backindicatorimage"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backIndicatorTransitionMaskImage": {
      "abstract": [
        {
          "text": "The image used as a mask for content during push and pop transitions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backIndicatorTransitionMaskImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backIndicatorTransitionMaskImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backIndicatorTransitionMaskImage"
        }
      ],
      "role": "symbol",
      "title": "backIndicatorTransitionMaskImage",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationbar/backindicatortransitionmaskimage"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backgroundImage(for:)": {
      "abstract": [
        {
          "text": "Returns the background image for given bar metrics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backgroundImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIBarMetrics",
          "text": "UIBarMetrics"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backgroundImage(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backgroundImageForBarMetrics:"
        }
      ],
      "role": "symbol",
      "title": "backgroundImage(for:)",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationbar/backgroundimage(for:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backgroundImage(for:barMetrics:)": {
      "abstract": [
        {
          "text": "Returns the background image to use for a given bar position and set of metrics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backgroundImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIBarPosition",
          "text": "UIBarPosition"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "barMetrics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIBarMetrics",
          "text": "UIBarMetrics"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backgroundImage(for:barMetrics:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backgroundImageForBarPosition:barMetrics:"
        }
      ],
      "role": "symbol",
      "title": "backgroundImage(for:barMetrics:)",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationbar/backgroundimage(for:barmetrics:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/barStyle": {
      "abstract": [
        {
          "text": "The navigation bar style that specifies its appearance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "barStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIBarStyle",
          "text": "UIBarStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/barStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "barStyle"
        }
      ],
      "role": "symbol",
      "title": "barStyle",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationbar/barstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/barTintColor": {
      "abstract": [
        {
          "text": "The tint color to apply to the navigation bar background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "barTintColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/barTintColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "barTintColor"
        }
      ],
      "role": "symbol",
      "title": "barTintColor",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationbar/bartintcolor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/compactAppearance": {
      "abstract": [
        {
          "text": "The appearance settings for a compact-height navigation bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compactAppearance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UINavigationBarAppearance",
          "text": "UINavigationBarAppearance"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/compactAppearance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "compactAppearance"
        }
      ],
      "role": "symbol",
      "title": "compactAppearance",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationbar/compactappearance"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/compactScrollEdgeAppearance": {
      "abstract": [
        {
          "text": "The appearance settings for a compact-height navigation bar when the edge of scrollable content aligns with the edge of the navigation bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compactScrollEdgeAppearance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UINavigationBarAppearance",
          "text": "UINavigationBarAppearance"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/compactScrollEdgeAppearance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "compactScrollEdgeAppearance"
        }
      ],
      "role": "symbol",
      "title": "compactScrollEdgeAppearance",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationbar/compactscrolledgeappearance"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/isTranslucent": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the navigation bar is translucent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isTranslucent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/isTranslucent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "translucent"
        }
      ],
      "role": "symbol",
      "title": "isTranslucent",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationbar/istranslucent"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/largeTitleTextAttributes": {
      "abstract": [
        {
          "text": "Display attributes for the bar’s large title text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "largeTitleTextAttributes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAttributedStringKey",
          "text": "Key"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/largeTitleTextAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "largeTitleTextAttributes"
        }
      ],
      "role": "symbol",
      "title": "largeTitleTextAttributes",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationbar/largetitletextattributes"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/prefersLargeTitles": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the title displays in a large format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prefersLargeTitles"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/prefersLargeTitles",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "prefersLargeTitles"
        }
      ],
      "role": "symbol",
      "title": "prefersLargeTitles",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationbar/preferslargetitles"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/scrollEdgeAppearance": {
      "abstract": [
        {
          "text": "The appearance settings for the navigation bar when the edge of scrollable content aligns with the edge of the navigation bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scrollEdgeAppearance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UINavigationBarAppearance",
          "text": "UINavigationBarAppearance"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/scrollEdgeAppearance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scrollEdgeAppearance"
        }
      ],
      "role": "symbol",
      "title": "scrollEdgeAppearance",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationbar/scrolledgeappearance"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setBackgroundImage(_:for:)": {
      "abstract": [
        {
          "text": "Sets the background image for given bar metrics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setBackgroundImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIBarMetrics",
          "text": "UIBarMetrics"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setBackgroundImage(_:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setBackgroundImage:forBarMetrics:"
        }
      ],
      "role": "symbol",
      "title": "setBackgroundImage(_:for:)",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationbar/setbackgroundimage(_:for:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setBackgroundImage(_:for:barMetrics:)": {
      "abstract": [
        {
          "text": "Sets the background image to use for a given bar position and set of metrics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setBackgroundImage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIBarPosition",
          "text": "UIBarPosition"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "barMetrics"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIBarMetrics",
          "text": "UIBarMetrics"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setBackgroundImage(_:for:barMetrics:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setBackgroundImage:forBarPosition:barMetrics:"
        }
      ],
      "role": "symbol",
      "title": "setBackgroundImage(_:for:barMetrics:)",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationbar/setbackgroundimage(_:for:barmetrics:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setTitleVerticalPositionAdjustment(_:for:)": {
      "abstract": [
        {
          "text": "Sets the title’s vertical position adjustment for given bar metrics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setTitleVerticalPositionAdjustment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIBarMetrics",
          "text": "UIBarMetrics"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setTitleVerticalPositionAdjustment(_:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setTitleVerticalPositionAdjustment:forBarMetrics:"
        }
      ],
      "role": "symbol",
      "title": "setTitleVerticalPositionAdjustment(_:for:)",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationbar/settitleverticalpositionadjustment(_:for:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/shadowImage": {
      "abstract": [
        {
          "text": "The shadow image to be used for the navigation bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shadowImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/shadowImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shadowImage"
        }
      ],
      "role": "symbol",
      "title": "shadowImage",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationbar/shadowimage"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/standardAppearance": {
      "abstract": [
        {
          "text": "The appearance settings for a standard-height navigation bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "standardAppearance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UINavigationBarAppearance",
          "text": "UINavigationBarAppearance"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/standardAppearance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "standardAppearance"
        }
      ],
      "role": "symbol",
      "title": "standardAppearance",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationbar/standardappearance"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/tintColor": {
      "abstract": [
        {
          "text": "The tint color to apply to the navigation items and bar button items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tintColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/tintColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tintColor"
        }
      ],
      "role": "symbol",
      "title": "tintColor",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationbar/tintcolor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/titleTextAttributes": {
      "abstract": [
        {
          "text": "Display attributes for the bar’s title text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "titleTextAttributes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSAttributedStringKey",
          "text": "Key"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/titleTextAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "titleTextAttributes"
        }
      ],
      "role": "symbol",
      "title": "titleTextAttributes",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationbar/titletextattributes"
    },
    "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/titleVerticalPositionAdjustment(for:)": {
      "abstract": [
        {
          "text": "Returns the title’s vertical position adjustment for given bar metrics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "titleVerticalPositionAdjustment"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIBarMetrics",
          "text": "UIBarMetrics"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/titleVerticalPositionAdjustment(for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "titleVerticalPositionAdjustmentForBarMetrics:"
        }
      ],
      "role": "symbol",
      "title": "titleVerticalPositionAdjustment(for:)",
      "type": "topic",
      "url": "/documentation/uikit/uinavigationbar/titleverticalpositionadjustment(for:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/customizing-your-app-s-navigation-bar": {
      "abstract": [
        {
          "text": "Create custom titles, prompts, and buttons in your app’s navigation bar.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/customizing-your-app-s-navigation-bar",
      "kind": "article",
      "role": "sampleCode",
      "title": "Customizing your app’s navigation bar",
      "type": "topic",
      "url": "/documentation/uikit/customizing-your-app-s-navigation-bar"
    },
    "doc://com.apple.uikit/documentation/UIKit/view-controllers": {
      "abstract": [
        {
          "text": "Manage your interface using view controllers and facilitate navigation around your app’s content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/view-controllers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "View controllers",
      "type": "topic",
      "url": "/documentation/uikit/view-controllers"
    },
    "doc://com.apple.uikit/documentation/UIKit/views-and-controls": {
      "abstract": [
        {
          "text": "Present your content onscreen and define the interactions allowed with that content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/views-and-controls",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Views and controls",
      "type": "topic",
      "url": "/documentation/uikit/views-and-controls"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Customizing-the-bars-appearance",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/prefersLargeTitles",
        "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/standardAppearance",
        "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/compactAppearance",
        "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/scrollEdgeAppearance",
        "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/compactScrollEdgeAppearance",
        "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/isTranslucent"
      ],
      "title": "Customizing the bar’s appearance"
    }
  ],
  "topicSections": [
    {
      "anchor": "Configuring-the-navigation-bar",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/customizing-your-app-s-navigation-bar"
      ],
      "title": "Configuring the navigation bar"
    },
    {
      "anchor": "Setting-the-bars-style",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/barStyle",
        "doc://com.apple.uikit/documentation/UIKit/UIBarStyle"
      ],
      "title": "Setting the bar’s style"
    },
    {
      "anchor": "Configuring-the-title",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/titleTextAttributes",
        "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/largeTitleTextAttributes",
        "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/titleVerticalPositionAdjustment(for:)",
        "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setTitleVerticalPositionAdjustment(_:for:)"
      ],
      "title": "Configuring the title"
    },
    {
      "anchor": "Configuring-bar-button-items",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/tintColor"
      ],
      "title": "Configuring bar button items"
    },
    {
      "anchor": "Configuring-the-Back-button",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backIndicatorImage",
        "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backIndicatorTransitionMaskImage"
      ],
      "title": "Configuring the Back button"
    },
    {
      "anchor": "Changing-the-background",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/barTintColor",
        "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backgroundImage(for:)",
        "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setBackgroundImage(_:for:)",
        "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backgroundImage(for:barMetrics:)",
        "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setBackgroundImage(_:for:barMetrics:)"
      ],
      "title": "Changing the background"
    },
    {
      "anchor": "Adding-a-shadow",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/shadowImage"
      ],
      "title": "Adding a shadow"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Configuring-the-navigation-bar",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/customizing-your-app-s-navigation-bar"
              ],
              "title": "Configuring the navigation bar"
            },
            {
              "anchor": "Setting-the-bars-style",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/barStyle",
                "doc://com.apple.uikit/documentation/UIKit/UIBarStyle"
              ],
              "title": "Setting the bar’s style"
            },
            {
              "anchor": "Configuring-the-title",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/titleTextAttributes",
                "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/largeTitleTextAttributes",
                "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/titleVerticalPositionAdjustment(for:)",
                "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setTitleVerticalPositionAdjustment(_:for:)"
              ],
              "title": "Configuring the title"
            },
            {
              "anchor": "Configuring-bar-button-items",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/tintColor"
              ],
              "title": "Configuring bar button items"
            },
            {
              "anchor": "Configuring-the-Back-button",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backIndicatorImage",
                "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backIndicatorTransitionMaskImage"
              ],
              "title": "Configuring the Back button"
            },
            {
              "anchor": "Changing-the-background",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/barTintColor",
                "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backgroundImage(for:)",
                "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setBackgroundImage(_:for:)",
                "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/backgroundImage(for:barMetrics:)",
                "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/setBackgroundImage(_:for:barMetrics:)"
              ],
              "title": "Changing the background"
            },
            {
              "anchor": "Adding-a-shadow",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/shadowImage"
              ],
              "title": "Adding a shadow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Customizing-the-bars-appearance",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/prefersLargeTitles",
                "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/standardAppearance",
                "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/compactAppearance",
                "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/scrollEdgeAppearance",
                "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/compactScrollEdgeAppearance",
                "doc://com.apple.uikit/documentation/UIKit/UINavigationBar/isTranslucent"
              ],
              "title": "Customizing the bar’s appearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1compactScrollEdgeAppearance/title",
          "value": "compactScrollEdgeAppearance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1compactScrollEdgeAppearance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "compactScrollEdgeAppearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1setTitleVerticalPositionAdjustment(_:for:)/title",
          "value": "setTitleVerticalPositionAdjustment:forBarMetrics:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1setTitleVerticalPositionAdjustment(_:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setTitleVerticalPositionAdjustment:forBarMetrics:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1titleTextAttributes/title",
          "value": "titleTextAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1titleTextAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "titleTextAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1tintColor/title",
          "value": "tintColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1tintColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tintColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1largeTitleTextAttributes/title",
          "value": "largeTitleTextAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1largeTitleTextAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "largeTitleTextAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar/title",
          "value": "UINavigationBar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UINavigationBar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UINavigationBar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1standardAppearance/title",
          "value": "standardAppearance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1standardAppearance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "standardAppearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1barTintColor/title",
          "value": "barTintColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1barTintColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "barTintColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarStyle/title",
          "value": "UIBarStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1backIndicatorTransitionMaskImage/title",
          "value": "backIndicatorTransitionMaskImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1backIndicatorTransitionMaskImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "backIndicatorTransitionMaskImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1isTranslucent/title",
          "value": "translucent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1isTranslucent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "translucent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1backgroundImage(for:)/title",
          "value": "backgroundImageForBarMetrics:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1backgroundImage(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "backgroundImageForBarMetrics:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1backIndicatorImage/title",
          "value": "backIndicatorImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1backIndicatorImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "backIndicatorImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1compactAppearance/title",
          "value": "compactAppearance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1compactAppearance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "compactAppearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1setBackgroundImage(_:for:barMetrics:)/title",
          "value": "setBackgroundImage:forBarPosition:barMetrics:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1setBackgroundImage(_:for:barMetrics:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setBackgroundImage:forBarPosition:barMetrics:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1barStyle/title",
          "value": "barStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1barStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "barStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1scrollEdgeAppearance/title",
          "value": "scrollEdgeAppearance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1scrollEdgeAppearance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scrollEdgeAppearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1backgroundImage(for:barMetrics:)/title",
          "value": "backgroundImageForBarPosition:barMetrics:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1backgroundImage(for:barMetrics:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "backgroundImageForBarPosition:barMetrics:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1setBackgroundImage(_:for:)/title",
          "value": "setBackgroundImage:forBarMetrics:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1setBackgroundImage(_:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setBackgroundImage:forBarMetrics:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1titleVerticalPositionAdjustment(for:)/title",
          "value": "titleVerticalPositionAdjustmentForBarMetrics:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1titleVerticalPositionAdjustment(for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "titleVerticalPositionAdjustmentForBarMetrics:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1shadowImage/title",
          "value": "shadowImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1shadowImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shadowImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1prefersLargeTitles/title",
          "value": "prefersLargeTitles"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UINavigationBar~1prefersLargeTitles/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "prefersLargeTitles"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uinavigationbar-legacy-customizations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uinavigationbar-legacy-customizations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
