{"kind":"symbol","variants":[{"paths":["/documentation/uikit/uioffsetfromstring"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"seeAlsoSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/NSStringFromUIOffset","doc://com.apple.documentation/documentation/foundation/nscoder/1624491-string","doc://com.apple.documentation/documentation/foundation/nscoder/1624509-uioffset"],"generated":true,"title":"Converting to and from strings","anchor":"Converting-to-and-from-strings"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"type":"text","text":"Returns a UIKit offset structure corresponding to the data in a given string."}],"metadata":{"externalID":"c:@F@UIOffsetFromString","symbolKind":"func","title":"UIOffsetFromString","fragments":[{"text":"UIOffsetFromString","kind":"identifier"}],"platforms":[{"beta":false,"deprecated":false,"unavailable":false,"name":"iOS"},{"beta":false,"deprecated":false,"unavailable":false,"name":"iPadOS"},{"beta":false,"deprecated":false,"unavailable":false,"name":"Mac Catalyst"},{"beta":false,"deprecated":false,"unavailable":false,"name":"tvOS"},{"beta":false,"deprecated":false,"unavailable":false,"name":"visionOS"},{"introducedAt":"2.0","beta":false,"deprecated":false,"unavailable":false,"name":"watchOS"}],"roleHeading":"Function","role":"symbol","navigatorTitle":[{"text":"UIOffsetFromString","kind":"identifier"}],"modules":[{"name":"UIKit"}]},"identifier":{"interfaceLanguage":"occ","url":"doc://com.apple.uikit/documentation/UIKit/UIOffsetFromString"},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS","watchOS"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIOffset","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIOffset","preciseIdentifier":"c:@S@UIOffset"},{"text":" ","kind":"text"},{"text":"UIOffsetFromString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"string","kind":"internalParam"},{"text":");","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"name":"string","content":[{"inlineContent":[{"type":"text","text":"A string containing a representation of an offset."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"inlineContent":[{"type":"text","text":"An edge insets data structure. If the string is not well-formed, the function returns "},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIOffset/zero","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"paragraph"}]},{"kind":"content","content":[{"level":2,"text":"Discussion","type":"heading","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In general, you should use this function only to convert strings that were previously created using the "},{"identifier":"doc://com.apple.uikit/documentation/UIKit/NSStringFromUIOffset","type":"reference","isActive":true},{"type":"text","text":" function."}]}]}],"references":{"doc://com.apple.uikit/documentation/UIKit/UIOffset":{"type":"topic","navigatorTitle":[{"text":"UIOffset","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIOffset","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIOffset","abstract":[{"text":"A structure that specifies an amount to offset a position.","type":"text"}],"url":"/documentation/uikit/uioffset","title":"UIOffset"},"doc://com.apple.uikit/documentation/UIKit/UIOffset/zero":{"kind":"symbol","type":"topic","abstract":[{"text":"An offset structure with no offset in the horizontal and vertical directions.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIOffset/zero","url":"/documentation/uikit/uioffset/zero","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIOffsetZero"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"zero"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIOffset","preciseIdentifier":"c:@S@UIOffset"}],"title":"zero"},"doc://com.apple.uikit/documentation/UIKit/NSStringFromUIOffset":{"fragments":[{"text":"NSStringFromUIOffset","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"Returns a string formatted to contain the data from an offset structure.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/NSStringFromUIOffset","title":"NSStringFromUIOffset","url":"/documentation/uikit/nsstringfromuioffset"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIOffsetFromString":{"fragments":[{"text":"UIOffsetFromString","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"Returns a UIKit offset structure corresponding to the data in a given string.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIOffsetFromString","title":"UIOffsetFromString","url":"/documentation/uikit/uioffsetfromstring"},"doc://com.apple.documentation/documentation/foundation/nscoder/1624509-uioffset":{"fragments":[{"text":"class func ","kind":"text"},{"text":"uiOffset","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"identifier"},{"text":": String) -> UIOffset","kind":"text"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"Returns a UIKit offset structure corresponding to the data in a given string.","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/foundation/nscoder/1624509-uioffset","title":"uiOffset(for:)","url":"/documentation/foundation/nscoder/1624509-uioffset"},"doc://com.apple.documentation/documentation/foundation/nscoder/1624491-string":{"fragments":[{"text":"class func ","kind":"text"},{"text":"string","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"identifier"},{"text":": UIOffset) -> String","kind":"text"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"Returns a string formatted to contain the data from an offset structure.","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/foundation/nscoder/1624491-string","title":"string(for:)","url":"/documentation/foundation/nscoder/1624491-string"},"doc://com.externally.resolved.symbol/c:objc(cs)NSString":{"abstract":[{"type":"text","text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. "}],"title":"NSString","url":"/documentation/foundation/nsstring","kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","fragments":[{"kind":"text","text":"class "},{"text":"NSString","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIOffset/title","value":"UIOffset"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIOffset/fragments","value":[{"kind":"identifier","text":"UIOffset"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIOffset/navigatorTitle","value":[{"text":"UIOffset","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIOffset~1zero/title","value":"UIOffsetZero"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIOffset~1zero/fragments","value":[{"text":"UIOffsetZero","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract","value":[{"text":"A static, plain-text Unicode string object.","type":"text"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}