{
  "abstract": [
    {
      "text": "A pattern that indicates the pasteboard detects a string that contains a flight number.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIPasteboardDetectionPatternFlightNumber"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@UIPasteboardDetectionPatternFlightNumber",
    "fragments": [
      {
        "kind": "identifier",
        "text": "UIPasteboardDetectionPatternFlightNumber"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIPasteboardDetectionPatternFlightNumber"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "UIPasteboardDetectionPatternFlightNumber"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectionPattern",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@UIPasteboardDetectionPattern",
              "text": "UIPasteboardDetectionPattern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIPasteboardDetectionPatternFlightNumber"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When you include this pattern in calls to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectValuesForPatterns:inItemSet:completionHandler:",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectValuesForPatterns:completionHandler:",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and the pasteboard detects a string that contains a flight number, the system reports the value as an array of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". You can return the detected results in a paste operation with ",
              "type": "text"
            },
            {
              "code": "UIPasteboardDetectionResultFlightNumber",
              "type": "codeVoice"
            },
            {
              "text": ", which contains a semantic representation of the flight number and airline carrier values.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/nsstring": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/nsstring",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectionPattern": {
      "abstract": [
        {
          "text": "An object that represents a pattern to detect for the pasteboard, such as a URL, text, or a number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DetectionPattern"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectionPattern",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DetectionPattern"
        }
      ],
      "role": "symbol",
      "title": "UIPasteboard.DetectionPattern",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectionpattern"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectionPattern/number": {
      "abstract": [
        {
          "text": "A pattern that indicates the pasteboard contains a string that consists of a numeric value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "number"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPasteboard",
          "text": "UIPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIPasteboardDetectionPattern",
          "text": "DetectionPattern"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectionPattern/number",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPasteboardDetectionPatternNumber"
        }
      ],
      "role": "symbol",
      "title": "number",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectionpattern/number"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectionPattern/probableWebSearch": {
      "abstract": [
        {
          "text": "A pattern that indicates the pasteboard contains a string suitable for use as a web search term.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "probableWebSearch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPasteboard",
          "text": "UIPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIPasteboardDetectionPattern",
          "text": "DetectionPattern"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectionPattern/probableWebSearch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPasteboardDetectionPatternProbableWebSearch"
        }
      ],
      "role": "symbol",
      "title": "probableWebSearch",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectionpattern/probablewebsearch"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectionPattern/probableWebURL": {
      "abstract": [
        {
          "text": "A pattern that indicates the pasteboard contains a string that consists of a URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "probableWebURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPasteboard",
          "text": "UIPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIPasteboardDetectionPattern",
          "text": "DetectionPattern"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectionPattern/probableWebURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPasteboardDetectionPatternProbableWebURL"
        }
      ],
      "role": "symbol",
      "title": "probableWebURL",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectionpattern/probableweburl"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectValuesForPatterns:completionHandler:": {
      "abstract": [
        {
          "text": "Determines whether the first pasteboard item matches the specified patterns, reading the contents if it finds a match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "detectValuesForPatterns:completionHandler:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectValuesForPatterns:completionHandler:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "detectValuesForPatterns:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "detectValuesForPatterns:completionHandler:",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectvaluesforpatterns:completionhandler:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectValuesForPatterns:inItemSet:completionHandler:": {
      "abstract": [
        {
          "text": "Determines whether pasteboard items match the specified patterns, reading the contents if it finds a match.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "detectValuesForPatterns:inItemSet:completionHandler:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectValuesForPatterns:inItemSet:completionHandler:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "detectValuesForPatterns:inItemSet:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "detectValuesForPatterns:inItemSet:completionHandler:",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectvaluesforpatterns:initemset:completionhandler:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboardDetectionPatternCalendarEvent": {
      "abstract": [
        {
          "text": "A pattern that indicates the pasteboard detects a string that contains a calendar event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIPasteboardDetectionPatternCalendarEvent"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboardDetectionPatternCalendarEvent",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIPasteboardDetectionPatternCalendarEvent",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboarddetectionpatterncalendarevent"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboardDetectionPatternEmailAddress": {
      "abstract": [
        {
          "text": "A pattern that indicates the pasteboard detects a string that contains an email address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIPasteboardDetectionPatternEmailAddress"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboardDetectionPatternEmailAddress",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIPasteboardDetectionPatternEmailAddress",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboarddetectionpatternemailaddress"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboardDetectionPatternFlightNumber": {
      "abstract": [
        {
          "text": "A pattern that indicates the pasteboard detects a string that contains a flight number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIPasteboardDetectionPatternFlightNumber"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboardDetectionPatternFlightNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIPasteboardDetectionPatternFlightNumber",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboarddetectionpatternflightnumber"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboardDetectionPatternLink": {
      "abstract": [
        {
          "text": "A pattern that indicates the pasteboard detects of a string that contains a URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIPasteboardDetectionPatternLink"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboardDetectionPatternLink",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIPasteboardDetectionPatternLink",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboarddetectionpatternlink"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboardDetectionPatternMoneyAmount": {
      "abstract": [
        {
          "text": "A pattern that indicates the pasteboard detects a string that contains an amount of money.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIPasteboardDetectionPatternMoneyAmount"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboardDetectionPatternMoneyAmount",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIPasteboardDetectionPatternMoneyAmount",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboarddetectionpatternmoneyamount"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboardDetectionPatternPhoneNumber": {
      "abstract": [
        {
          "text": "A pattern that indicates the pasteboard detects a string that contains a phone number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIPasteboardDetectionPatternPhoneNumber"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboardDetectionPatternPhoneNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIPasteboardDetectionPatternPhoneNumber",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboarddetectionpatternphonenumber"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboardDetectionPatternPostalAddress": {
      "abstract": [
        {
          "text": "A pattern that indicates the pasteboard detects a string that contains a postal address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIPasteboardDetectionPatternPostalAddress"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboardDetectionPatternPostalAddress",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIPasteboardDetectionPatternPostalAddress",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboarddetectionpatternpostaladdress"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboardDetectionPatternShipmentTrackingNumber": {
      "abstract": [
        {
          "text": "A pattern that indicates the pasteboard detects a string that contains a parcel tracking number and carrier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIPasteboardDetectionPatternShipmentTrackingNumber"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboardDetectionPatternShipmentTrackingNumber",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIPasteboardDetectionPatternShipmentTrackingNumber",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboarddetectionpatternshipmenttrackingnumber"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Detecting-common-patterns",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboardDetectionPatternCalendarEvent",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboardDetectionPatternEmailAddress",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboardDetectionPatternLink",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboardDetectionPatternMoneyAmount",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectionPattern/number",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboardDetectionPatternPhoneNumber",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboardDetectionPatternPostalAddress",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectionPattern/probableWebSearch",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/DetectionPattern/probableWebURL",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboardDetectionPatternShipmentTrackingNumber"
      ],
      "title": "Detecting common patterns"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard~1DetectionPattern~1number/title",
          "value": "UIPasteboardDetectionPatternNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard~1DetectionPattern~1number/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteboardDetectionPatternNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1nsstring/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard~1DetectionPattern~1probableWebURL/title",
          "value": "UIPasteboardDetectionPatternProbableWebURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard~1DetectionPattern~1probableWebURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteboardDetectionPatternProbableWebURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard~1DetectionPattern~1probableWebSearch/title",
          "value": "UIPasteboardDetectionPatternProbableWebSearch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard~1DetectionPattern~1probableWebSearch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteboardDetectionPatternProbableWebSearch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard~1DetectionPattern/title",
          "value": "UIPasteboardDetectionPattern"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard~1DetectionPattern/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteboardDetectionPattern"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard~1DetectionPattern/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteboardDetectionPattern"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uipasteboarddetectionpatternflightnumber"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
