{
  "abstract": [
    {
      "text": "Review unsupported symbols and their replacements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/documents-data-and-pasteboard",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/uipasteboard-deprecated-symbols"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Deprecated symbols"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard": {
      "abstract": [
        {
          "text": "An object that helps a user share data from one place to another within your app, and from your app to other apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPasteboard"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPasteboard"
        }
      ],
      "role": "symbol",
      "title": "UIPasteboard",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectPatterns(for:completionHandler:)-5zlnd": {
      "abstract": [
        {
          "text": "Determines whether the first pasteboard item matches the specified patterns, without notifying the user.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "detectPatterns"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPasteboard",
          "text": "UIPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIPasteboardDetectionPattern",
          "text": "DetectionPattern"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6ResultO",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPasteboard",
          "text": "UIPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIPasteboardDetectionPattern",
          "text": "DetectionPattern"
        },
        {
          "kind": "text",
          "text": ">, any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ">) -> ())"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectPatterns(for:completionHandler:)-5zlnd",
      "kind": "symbol",
      "role": "symbol",
      "title": "detectPatterns(for:completionHandler:)",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectpatterns(for:completionhandler:)-5zlnd"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectPatterns(for:inItemSet:completionHandler:)-29iwn": {
      "abstract": [
        {
          "text": "Determines whether pasteboard items match the specified patterns, without notifying the user.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "detectPatterns"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPasteboard",
          "text": "UIPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIPasteboardDetectionPattern",
          "text": "DetectionPattern"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "inItemSet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation8IndexSetV",
          "text": "IndexSet"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6ResultO",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": "<["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPasteboard",
          "text": "UIPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIPasteboardDetectionPattern",
          "text": "DetectionPattern"
        },
        {
          "kind": "text",
          "text": ">], any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ">) -> ())"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectPatterns(for:inItemSet:completionHandler:)-29iwn",
      "kind": "symbol",
      "role": "symbol",
      "title": "detectPatterns(for:inItemSet:completionHandler:)",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectpatterns(for:initemset:completionhandler:)-29iwn"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectValues(for:completionHandler:)-9p2ff": {
      "abstract": [
        {
          "text": "Determines whether the first pasteboard item matches the specified patterns, reading the contents if it finds a match.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "detectValues"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPasteboard",
          "text": "UIPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIPasteboardDetectionPattern",
          "text": "DetectionPattern"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6ResultO",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": "<["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPasteboard",
          "text": "UIPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIPasteboardDetectionPattern",
          "text": "DetectionPattern"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ">) -> ())"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectValues(for:completionHandler:)-9p2ff",
      "kind": "symbol",
      "role": "symbol",
      "title": "detectValues(for:completionHandler:)",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectvalues(for:completionhandler:)-9p2ff"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectValues(for:inItemSet:completionHandler:)-8y0iw": {
      "abstract": [
        {
          "text": "Determines whether pasteboard items match the specified patterns, reading the contents if it finds a match.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "detectValues"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPasteboard",
          "text": "UIPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIPasteboardDetectionPattern",
          "text": "DetectionPattern"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "externalParam",
          "text": "inItemSet"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation8IndexSetV",
          "text": "IndexSet"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6ResultO",
          "text": "Result"
        },
        {
          "kind": "text",
          "text": "<[["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPasteboard",
          "text": "UIPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UIPasteboardDetectionPattern",
          "text": "DetectionPattern"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]], any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ">) -> ())"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectValues(for:inItemSet:completionHandler:)-8y0iw",
      "kind": "symbol",
      "role": "symbol",
      "title": "detectValues(for:inItemSet:completionHandler:)",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/detectvalues(for:initemset:completionhandler:)-8y0iw"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/isPersistent": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the pasteboard is persistent.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isPersistent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/isPersistent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "persistent"
        }
      ],
      "role": "symbol",
      "title": "isPersistent",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/ispersistent"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/setPersistent(_:)": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the pasteboard is persistent.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setPersistent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/setPersistent(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setPersistent:"
        }
      ],
      "role": "symbol",
      "title": "setPersistent(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/setpersistent(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/documents-data-and-pasteboard": {
      "abstract": [
        {
          "text": "Organize your app’s data and share that data on the pasteboard.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/documents-data-and-pasteboard",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Documents, data, and pasteboard",
      "type": "topic",
      "url": "/documentation/uikit/documents-data-and-pasteboard"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/isPersistent",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/setPersistent(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectPatterns(for:completionHandler:)-5zlnd",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectPatterns(for:inItemSet:completionHandler:)-29iwn",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectValues(for:completionHandler:)-9p2ff",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/detectValues(for:inItemSet:completionHandler:)-8y0iw"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/isPersistent",
                "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/setPersistent(_:)"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard~1isPersistent/title",
          "value": "persistent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard~1isPersistent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "persistent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard~1setPersistent(_:)/title",
          "value": "setPersistent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard~1setPersistent(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setPersistent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard/title",
          "value": "UIPasteboard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteboard"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uipasteboard-deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uipasteboard-deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
