{
  "abstract": [
    {
      "text": "The actions Apple Pencil can perform after a person performs a double tap or squeeze.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIPencilPreferredAction",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIPencilPreferredAction"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIPencilPreferredAction"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.1",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.1",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "UIPencilPreferredAction"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIPencilPreferredAction"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPencilInteraction/preferredSqueezeAction": {
      "abstract": [
        {
          "text": "A person’s preferred squeeze action for Apple Pencil, as specified in the Settings app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredSqueezeAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIPencilPreferredAction",
          "text": "UIPencilPreferredAction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPencilInteraction/preferredSqueezeAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredSqueezeAction"
        }
      ],
      "role": "symbol",
      "title": "preferredSqueezeAction",
      "type": "topic",
      "url": "/documentation/uikit/uipencilinteraction/preferredsqueezeaction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPencilInteraction/preferredTapAction": {
      "abstract": [
        {
          "text": "A person’s preferred double-tap action for Apple Pencil, as specified in the Settings app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredTapAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIPencilPreferredAction",
          "text": "UIPencilPreferredAction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPencilInteraction/preferredTapAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredTapAction"
        }
      ],
      "role": "symbol",
      "title": "preferredTapAction",
      "type": "topic",
      "url": "/documentation/uikit/uipencilinteraction/preferredtapaction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction": {
      "abstract": [
        {
          "text": "The actions Apple Pencil can perform after a person performs a double tap or squeeze.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPencilPreferredAction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPencilPreferredAction"
        }
      ],
      "role": "symbol",
      "title": "UIPencilPreferredAction",
      "type": "topic",
      "url": "/documentation/uikit/uipencilpreferredaction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/ignore": {
      "abstract": [
        {
          "text": "An action that does nothing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ignore"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/ignore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPencilPreferredActionIgnore"
        }
      ],
      "role": "symbol",
      "title": "UIPencilPreferredAction.ignore",
      "type": "topic",
      "url": "/documentation/uikit/uipencilpreferredaction/ignore"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/uipencilpreferredaction/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/runSystemShortcut": {
      "abstract": [
        {
          "text": "An action that runs a system shortcut.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "runSystemShortcut"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/runSystemShortcut",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPencilPreferredActionRunSystemShortcut"
        }
      ],
      "role": "symbol",
      "title": "UIPencilPreferredAction.runSystemShortcut",
      "type": "topic",
      "url": "/documentation/uikit/uipencilpreferredaction/runsystemshortcut"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/showColorPalette": {
      "abstract": [
        {
          "text": "An action that toggles the display of the color palette.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showColorPalette"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/showColorPalette",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPencilPreferredActionShowColorPalette"
        }
      ],
      "role": "symbol",
      "title": "UIPencilPreferredAction.showColorPalette",
      "type": "topic",
      "url": "/documentation/uikit/uipencilpreferredaction/showcolorpalette"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/showContextualPalette": {
      "abstract": [
        {
          "text": "An action that toggles shows a contextual palette of markup tools, or undo and redo options if tools aren’t available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showContextualPalette"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/showContextualPalette",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPencilPreferredActionShowContextualPalette"
        }
      ],
      "role": "symbol",
      "title": "UIPencilPreferredAction.showContextualPalette",
      "type": "topic",
      "url": "/documentation/uikit/uipencilpreferredaction/showcontextualpalette"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/showInkAttributes": {
      "abstract": [
        {
          "text": "An action that toggles the display of the selected tool’s ink attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "showInkAttributes"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/showInkAttributes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPencilPreferredActionShowInkAttributes"
        }
      ],
      "role": "symbol",
      "title": "UIPencilPreferredAction.showInkAttributes",
      "type": "topic",
      "url": "/documentation/uikit/uipencilpreferredaction/showinkattributes"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/switchEraser": {
      "abstract": [
        {
          "text": "An action that switches between the current tool and the eraser.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "switchEraser"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/switchEraser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPencilPreferredActionSwitchEraser"
        }
      ],
      "role": "symbol",
      "title": "UIPencilPreferredAction.switchEraser",
      "type": "topic",
      "url": "/documentation/uikit/uipencilpreferredaction/switcheraser"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/switchPrevious": {
      "abstract": [
        {
          "text": "An action that switches between the current tool and the last used tool.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "switchPrevious"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/switchPrevious",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPencilPreferredActionSwitchPrevious"
        }
      ],
      "role": "symbol",
      "title": "UIPencilPreferredAction.switchPrevious",
      "type": "topic",
      "url": "/documentation/uikit/uipencilpreferredaction/switchprevious"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Determining-preferences-for-actions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPencilInteraction/preferredTapAction",
        "doc://com.apple.uikit/documentation/UIKit/UIPencilInteraction/preferredSqueezeAction"
      ],
      "title": "Determining preferences for actions"
    }
  ],
  "topicSections": [
    {
      "anchor": "Preferred-actions",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/ignore",
        "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/switchEraser",
        "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/switchPrevious",
        "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/showColorPalette",
        "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/showInkAttributes",
        "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/showContextualPalette",
        "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/runSystemShortcut"
      ],
      "title": "Preferred actions"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIPencilPreferredAction"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilPreferredAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilPreferredAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Preferred-actions",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/ignore",
                "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/switchEraser",
                "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/switchPrevious",
                "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/showColorPalette",
                "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/showInkAttributes",
                "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/showContextualPalette",
                "doc://com.apple.uikit/documentation/UIKit/UIPencilPreferredAction/runSystemShortcut"
              ],
              "title": "Preferred actions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Determining-preferences-for-actions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPencilInteraction/preferredTapAction",
                "doc://com.apple.uikit/documentation/UIKit/UIPencilInteraction/preferredSqueezeAction"
              ],
              "title": "Determining preferences for actions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIPencilPreferredAction"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilPreferredAction~1runSystemShortcut/title",
          "value": "UIPencilPreferredActionRunSystemShortcut"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilPreferredAction~1runSystemShortcut/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilPreferredActionRunSystemShortcut"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilPreferredAction/title",
          "value": "UIPencilPreferredAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilPreferredAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilPreferredAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilPreferredAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilPreferredAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilPreferredAction~1switchEraser/title",
          "value": "UIPencilPreferredActionSwitchEraser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilPreferredAction~1switchEraser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilPreferredActionSwitchEraser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilInteraction~1preferredSqueezeAction/title",
          "value": "preferredSqueezeAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilInteraction~1preferredSqueezeAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preferredSqueezeAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilPreferredAction~1showContextualPalette/title",
          "value": "UIPencilPreferredActionShowContextualPalette"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilPreferredAction~1showContextualPalette/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilPreferredActionShowContextualPalette"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilPreferredAction~1showInkAttributes/title",
          "value": "UIPencilPreferredActionShowInkAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilPreferredAction~1showInkAttributes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilPreferredActionShowInkAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilInteraction~1preferredTapAction/title",
          "value": "preferredTapAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilInteraction~1preferredTapAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preferredTapAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilPreferredAction~1switchPrevious/title",
          "value": "UIPencilPreferredActionSwitchPrevious"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilPreferredAction~1switchPrevious/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilPreferredActionSwitchPrevious"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilPreferredAction~1showColorPalette/title",
          "value": "UIPencilPreferredActionShowColorPalette"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilPreferredAction~1showColorPalette/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilPreferredActionShowColorPalette"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilPreferredAction~1ignore/title",
          "value": "UIPencilPreferredActionIgnore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilPreferredAction~1ignore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilPreferredActionIgnore"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uipencilpreferredaction"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uipencilpreferredaction"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
