{
  "abstract": [
    {
      "text": "The interface an object implements to handle double taps or squeezes a person makes on Apple Pencil.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIPencilInteractionDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UIPencilInteractionDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIPencilInteractionDelegate"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIPencilInteractionDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.1",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.1",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "UIPencilInteractionDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIPencilInteractionDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPencilHoverPose": {
      "abstract": [
        {
          "text": "An object that describes the hover pose of Apple Pencil during an interaction like double tap or squeeze.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPencilHoverPose"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPencilHoverPose",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPencilHoverPose"
        }
      ],
      "role": "symbol",
      "title": "UIPencilHoverPose",
      "type": "topic",
      "url": "/documentation/uikit/uipencilhoverpose"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPencilInteraction": {
      "abstract": [
        {
          "text": "An interaction that tells your app when a person double-taps or squeezes Apple Pencil.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPencilInteraction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPencilInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPencilInteraction"
        }
      ],
      "role": "symbol",
      "title": "UIPencilInteraction",
      "type": "topic",
      "url": "/documentation/uikit/uipencilinteraction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPencilInteraction/Phase": {
      "abstract": [
        {
          "text": "Constants that describe the phases of an interaction on Apple Pencil.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Phase"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPencilInteraction/Phase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Phase"
        }
      ],
      "role": "symbol",
      "title": "UIPencilInteraction.Phase",
      "type": "topic",
      "url": "/documentation/uikit/uipencilinteraction/phase"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPencilInteraction/Squeeze": {
      "abstract": [
        {
          "text": "An interaction that represents a squeeze on Apple Pencil.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Squeeze"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPencilInteraction/Squeeze",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Squeeze"
        }
      ],
      "role": "symbol",
      "title": "UIPencilInteraction.Squeeze",
      "type": "topic",
      "url": "/documentation/uikit/uipencilinteraction/squeeze"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPencilInteraction/Tap": {
      "abstract": [
        {
          "text": "An interaction that represents a double tap on Apple Pencil.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Tap"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPencilInteraction/Tap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Tap"
        }
      ],
      "role": "symbol",
      "title": "UIPencilInteraction.Tap",
      "type": "topic",
      "url": "/documentation/uikit/uipencilinteraction/tap"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPencilInteractionDelegate": {
      "abstract": [
        {
          "text": "The interface an object implements to handle double taps or squeezes a person makes on Apple Pencil.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPencilInteractionDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPencilInteractionDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPencilInteractionDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIPencilInteractionDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uipencilinteractiondelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPencilInteractionDelegate/pencilInteraction(_:didReceiveSqueeze:)": {
      "abstract": [
        {
          "text": "Tells the delegate when a person squeezes Apple Pencil.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pencilInteraction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPencilInteraction",
          "text": "UIPencilInteraction"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didReceiveSqueeze"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPencilInteraction",
          "text": "UIPencilInteraction"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPencilInteractionSqueeze",
          "text": "Squeeze"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPencilInteractionDelegate/pencilInteraction(_:didReceiveSqueeze:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pencilInteraction:didReceiveSqueeze:"
        }
      ],
      "role": "symbol",
      "title": "pencilInteraction(_:didReceiveSqueeze:)",
      "type": "topic",
      "url": "/documentation/uikit/uipencilinteractiondelegate/pencilinteraction(_:didreceivesqueeze:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPencilInteractionDelegate/pencilInteraction(_:didReceiveTap:)": {
      "abstract": [
        {
          "text": "Tells the delegate when a person double-taps Apple Pencil.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pencilInteraction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPencilInteraction",
          "text": "UIPencilInteraction"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didReceiveTap"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPencilInteraction",
          "text": "UIPencilInteraction"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPencilInteractionTap",
          "text": "Tap"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPencilInteractionDelegate/pencilInteraction(_:didReceiveTap:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pencilInteraction:didReceiveTap:"
        }
      ],
      "role": "symbol",
      "title": "pencilInteraction(_:didReceiveTap:)",
      "type": "topic",
      "url": "/documentation/uikit/uipencilinteractiondelegate/pencilinteraction(_:didreceivetap:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPencilInteractionDelegate/pencilInteractionDidTap(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user double-tapped Apple Pencil.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pencilInteractionDidTap"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPencilInteraction",
          "text": "UIPencilInteraction"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPencilInteractionDelegate/pencilInteractionDidTap(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pencilInteractionDidTap:"
        }
      ],
      "role": "symbol",
      "title": "pencilInteractionDidTap(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uipencilinteractiondelegate/pencilinteractiondidtap(_:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Apple-Pencil-interactions-in-UIKit",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPencilInteraction",
        "doc://com.apple.uikit/documentation/UIKit/UIPencilInteraction/Tap",
        "doc://com.apple.uikit/documentation/UIKit/UIPencilInteraction/Squeeze",
        "doc://com.apple.uikit/documentation/UIKit/UIPencilInteraction/Phase",
        "doc://com.apple.uikit/documentation/UIKit/UIPencilHoverPose"
      ],
      "title": "Apple Pencil interactions in UIKit"
    }
  ],
  "topicSections": [
    {
      "anchor": "Handling-double-tap-interactions",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPencilInteractionDelegate/pencilInteraction(_:didReceiveTap:)"
      ],
      "title": "Handling double-tap interactions"
    },
    {
      "anchor": "Handling-squeeze-interactions",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPencilInteractionDelegate/pencilInteraction(_:didReceiveSqueeze:)"
      ],
      "title": "Handling squeeze interactions"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPencilInteractionDelegate/pencilInteractionDidTap(_:)"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.1",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.1",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIPencilInteractionDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilInteractionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilInteractionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Handling-double-tap-interactions",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPencilInteractionDelegate/pencilInteraction(_:didReceiveTap:)"
              ],
              "title": "Handling double-tap interactions"
            },
            {
              "anchor": "Handling-squeeze-interactions",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPencilInteractionDelegate/pencilInteraction(_:didReceiveSqueeze:)"
              ],
              "title": "Handling squeeze interactions"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPencilInteractionDelegate/pencilInteractionDidTap(_:)"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Apple-Pencil-interactions-in-UIKit",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPencilInteraction",
                "doc://com.apple.uikit/documentation/UIKit/UIPencilInteraction/Tap",
                "doc://com.apple.uikit/documentation/UIKit/UIPencilInteraction/Squeeze",
                "doc://com.apple.uikit/documentation/UIKit/UIPencilInteraction/Phase",
                "doc://com.apple.uikit/documentation/UIKit/UIPencilHoverPose"
              ],
              "title": "Apple Pencil interactions in UIKit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIPencilInteractionDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilInteractionDelegate/title",
          "value": "UIPencilInteractionDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilInteractionDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilInteractionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilInteractionDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilInteractionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilInteraction~1Tap/title",
          "value": "UIPencilInteractionTap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilInteraction~1Tap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilInteractionTap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilInteraction~1Tap/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilInteractionTap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilInteraction~1Squeeze/title",
          "value": "UIPencilInteractionSqueeze"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilInteraction~1Squeeze/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilInteractionSqueeze"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilInteraction~1Squeeze/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilInteractionSqueeze"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilHoverPose/title",
          "value": "UIPencilHoverPose"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilHoverPose/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilHoverPose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilHoverPose/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilHoverPose"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilInteractionDelegate~1pencilInteraction(_:didReceiveSqueeze:)/title",
          "value": "pencilInteraction:didReceiveSqueeze:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilInteractionDelegate~1pencilInteraction(_:didReceiveSqueeze:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pencilInteraction:didReceiveSqueeze:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilInteraction/title",
          "value": "UIPencilInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilInteractionDelegate~1pencilInteraction(_:didReceiveTap:)/title",
          "value": "pencilInteraction:didReceiveTap:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilInteractionDelegate~1pencilInteraction(_:didReceiveTap:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pencilInteraction:didReceiveTap:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilInteraction~1Phase/title",
          "value": "UIPencilInteractionPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilInteraction~1Phase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilInteractionPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilInteraction~1Phase/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPencilInteractionPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilInteractionDelegate~1pencilInteractionDidTap(_:)/title",
          "value": "pencilInteractionDidTap:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPencilInteractionDelegate~1pencilInteractionDidTap(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pencilInteractionDidTap:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uipencilinteractiondelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uipencilinteractiondelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
