{
  "abstract": [
    {
      "text": "A set of methods you can implement to provide accessibility information for individual components of a picker view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIPickerViewAccessibilityDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UIPickerViewAccessibilityDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIPickerViewAccessibilityDelegate"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIPickerViewAccessibilityDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "UIPickerViewAccessibilityDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIPickerViewAccessibilityDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPickerViewDelegate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)UIPickerViewDelegate",
              "text": "UIPickerViewDelegate"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityElement": {
      "abstract": [
        {
          "text": "An element that should be accessible to users with disabilities, but that isn’t accessible by default.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAccessibilityElement"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityElement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccessibilityElement"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibilityElement",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibilityelement"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPickerViewAccessibilityDelegate": {
      "abstract": [
        {
          "text": "A set of methods you can implement to provide accessibility information for individual components of a picker view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPickerViewAccessibilityDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPickerViewAccessibilityDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPickerViewAccessibilityDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIPickerViewAccessibilityDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uipickerviewaccessibilitydelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPickerViewAccessibilityDelegate/pickerView(_:accessibilityAttributedHintForComponent:)": {
      "abstract": [
        {
          "text": "Returns an attributed string that describes the result of performing an action on the specified component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pickerView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPickerView",
          "text": "UIPickerView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "accessibilityAttributedHintForComponent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPickerViewAccessibilityDelegate/pickerView(_:accessibilityAttributedHintForComponent:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pickerView:accessibilityAttributedHintForComponent:"
        }
      ],
      "role": "symbol",
      "title": "pickerView(_:accessibilityAttributedHintForComponent:)",
      "type": "topic",
      "url": "/documentation/uikit/uipickerviewaccessibilitydelegate/pickerview(_:accessibilityattributedhintforcomponent:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPickerViewAccessibilityDelegate/pickerView(_:accessibilityAttributedLabelForComponent:)": {
      "abstract": [
        {
          "text": "Returns an attributed string that identifies the picker view component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pickerView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPickerView",
          "text": "UIPickerView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "accessibilityAttributedLabelForComponent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPickerViewAccessibilityDelegate/pickerView(_:accessibilityAttributedLabelForComponent:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pickerView:accessibilityAttributedLabelForComponent:"
        }
      ],
      "role": "symbol",
      "title": "pickerView(_:accessibilityAttributedLabelForComponent:)",
      "type": "topic",
      "url": "/documentation/uikit/uipickerviewaccessibilitydelegate/pickerview(_:accessibilityattributedlabelforcomponent:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPickerViewAccessibilityDelegate/pickerView(_:accessibilityAttributedUserInputLabelsForComponent:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pickerView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPickerView",
          "text": "UIPickerView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "accessibilityAttributedUserInputLabelsForComponent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPickerViewAccessibilityDelegate/pickerView(_:accessibilityAttributedUserInputLabelsForComponent:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pickerView:accessibilityAttributedUserInputLabelsForComponent:"
        }
      ],
      "role": "symbol",
      "title": "pickerView(_:accessibilityAttributedUserInputLabelsForComponent:)",
      "type": "topic",
      "url": "/documentation/uikit/uipickerviewaccessibilitydelegate/pickerview(_:accessibilityattributeduserinputlabelsforcomponent:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPickerViewAccessibilityDelegate/pickerView(_:accessibilityHintForComponent:)": {
      "abstract": [
        {
          "text": "Returns a string that describes the result of performing an action on the component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pickerView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPickerView",
          "text": "UIPickerView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "accessibilityHintForComponent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPickerViewAccessibilityDelegate/pickerView(_:accessibilityHintForComponent:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pickerView:accessibilityHintForComponent:"
        }
      ],
      "role": "symbol",
      "title": "pickerView(_:accessibilityHintForComponent:)",
      "type": "topic",
      "url": "/documentation/uikit/uipickerviewaccessibilitydelegate/pickerview(_:accessibilityhintforcomponent:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPickerViewAccessibilityDelegate/pickerView(_:accessibilityLabelForComponent:)": {
      "abstract": [
        {
          "text": "Returns a string that identifies the picker view component.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pickerView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPickerView",
          "text": "UIPickerView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "accessibilityLabelForComponent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPickerViewAccessibilityDelegate/pickerView(_:accessibilityLabelForComponent:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pickerView:accessibilityLabelForComponent:"
        }
      ],
      "role": "symbol",
      "title": "pickerView(_:accessibilityLabelForComponent:)",
      "type": "topic",
      "url": "/documentation/uikit/uipickerviewaccessibilitydelegate/pickerview(_:accessibilitylabelforcomponent:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPickerViewAccessibilityDelegate/pickerView(_:accessibilityUserInputLabelsForComponent:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pickerView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPickerView",
          "text": "UIPickerView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "accessibilityUserInputLabelsForComponent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPickerViewAccessibilityDelegate/pickerView(_:accessibilityUserInputLabelsForComponent:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pickerView:accessibilityUserInputLabelsForComponent:"
        }
      ],
      "role": "symbol",
      "title": "pickerView(_:accessibilityUserInputLabelsForComponent:)",
      "type": "topic",
      "url": "/documentation/uikit/uipickerviewaccessibilitydelegate/pickerview(_:accessibilityuserinputlabelsforcomponent:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPickerViewDelegate": {
      "abstract": [
        {
          "text": "The interface for a picker view’s delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPickerViewDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPickerViewDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPickerViewDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIPickerViewDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uipickerviewdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScrollViewAccessibilityDelegate": {
      "abstract": [
        {
          "text": "A set of methods you can implement to provide accessibility information for a scroll view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIScrollViewAccessibilityDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScrollViewAccessibilityDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIScrollViewAccessibilityDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIScrollViewAccessibilityDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uiscrollviewaccessibilitydelegate"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.apple.uikit/documentation/UIKit/UIPickerViewDelegate"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Elements",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityElement",
        "doc://com.apple.uikit/documentation/UIKit/UIScrollViewAccessibilityDelegate"
      ],
      "title": "Elements"
    }
  ],
  "topicSections": [
    {
      "anchor": "Providing-descriptive-information",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPickerViewAccessibilityDelegate/pickerView(_:accessibilityLabelForComponent:)",
        "doc://com.apple.uikit/documentation/UIKit/UIPickerViewAccessibilityDelegate/pickerView(_:accessibilityAttributedLabelForComponent:)",
        "doc://com.apple.uikit/documentation/UIKit/UIPickerViewAccessibilityDelegate/pickerView(_:accessibilityHintForComponent:)",
        "doc://com.apple.uikit/documentation/UIKit/UIPickerViewAccessibilityDelegate/pickerView(_:accessibilityAttributedHintForComponent:)",
        "doc://com.apple.uikit/documentation/UIKit/UIPickerViewAccessibilityDelegate/pickerView(_:accessibilityUserInputLabelsForComponent:)",
        "doc://com.apple.uikit/documentation/UIKit/UIPickerViewAccessibilityDelegate/pickerView(_:accessibilityAttributedUserInputLabelsForComponent:)"
      ],
      "title": "Providing descriptive information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIPickerViewAccessibilityDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPickerViewAccessibilityDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPickerViewAccessibilityDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Providing-descriptive-information",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPickerViewAccessibilityDelegate/pickerView(_:accessibilityLabelForComponent:)",
                "doc://com.apple.uikit/documentation/UIKit/UIPickerViewAccessibilityDelegate/pickerView(_:accessibilityAttributedLabelForComponent:)",
                "doc://com.apple.uikit/documentation/UIKit/UIPickerViewAccessibilityDelegate/pickerView(_:accessibilityHintForComponent:)",
                "doc://com.apple.uikit/documentation/UIKit/UIPickerViewAccessibilityDelegate/pickerView(_:accessibilityAttributedHintForComponent:)",
                "doc://com.apple.uikit/documentation/UIKit/UIPickerViewAccessibilityDelegate/pickerView(_:accessibilityUserInputLabelsForComponent:)",
                "doc://com.apple.uikit/documentation/UIKit/UIPickerViewAccessibilityDelegate/pickerView(_:accessibilityAttributedUserInputLabelsForComponent:)"
              ],
              "title": "Providing descriptive information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPickerViewDelegate"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Elements",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIAccessibilityElement",
                "doc://com.apple.uikit/documentation/UIKit/UIScrollViewAccessibilityDelegate"
              ],
              "title": "Elements"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIPickerViewAccessibilityDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPickerViewDelegate",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)UIPickerViewDelegate",
                    "text": "UIPickerViewDelegate"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPickerViewAccessibilityDelegate~1pickerView(_:accessibilityUserInputLabelsForComponent:)/title",
          "value": "pickerView:accessibilityUserInputLabelsForComponent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPickerViewAccessibilityDelegate~1pickerView(_:accessibilityUserInputLabelsForComponent:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pickerView:accessibilityUserInputLabelsForComponent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPickerViewAccessibilityDelegate~1pickerView(_:accessibilityAttributedHintForComponent:)/title",
          "value": "pickerView:accessibilityAttributedHintForComponent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPickerViewAccessibilityDelegate~1pickerView(_:accessibilityAttributedHintForComponent:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pickerView:accessibilityAttributedHintForComponent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPickerViewAccessibilityDelegate~1pickerView(_:accessibilityLabelForComponent:)/title",
          "value": "pickerView:accessibilityLabelForComponent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPickerViewAccessibilityDelegate~1pickerView(_:accessibilityLabelForComponent:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pickerView:accessibilityLabelForComponent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPickerViewDelegate/title",
          "value": "UIPickerViewDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPickerViewDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPickerViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPickerViewDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPickerViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPickerViewAccessibilityDelegate~1pickerView(_:accessibilityHintForComponent:)/title",
          "value": "pickerView:accessibilityHintForComponent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPickerViewAccessibilityDelegate~1pickerView(_:accessibilityHintForComponent:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pickerView:accessibilityHintForComponent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPickerViewAccessibilityDelegate~1pickerView(_:accessibilityAttributedLabelForComponent:)/title",
          "value": "pickerView:accessibilityAttributedLabelForComponent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPickerViewAccessibilityDelegate~1pickerView(_:accessibilityAttributedLabelForComponent:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pickerView:accessibilityAttributedLabelForComponent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityElement/title",
          "value": "UIAccessibilityElement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityElement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibilityElement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityElement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPickerViewAccessibilityDelegate/title",
          "value": "UIPickerViewAccessibilityDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPickerViewAccessibilityDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPickerViewAccessibilityDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPickerViewAccessibilityDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPickerViewAccessibilityDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPickerViewAccessibilityDelegate~1pickerView(_:accessibilityAttributedUserInputLabelsForComponent:)/title",
          "value": "pickerView:accessibilityAttributedUserInputLabelsForComponent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPickerViewAccessibilityDelegate~1pickerView(_:accessibilityAttributedUserInputLabelsForComponent:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "pickerView:accessibilityAttributedUserInputLabelsForComponent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewAccessibilityDelegate/title",
          "value": "UIScrollViewAccessibilityDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewAccessibilityDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScrollViewAccessibilityDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewAccessibilityDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScrollViewAccessibilityDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uipickerviewaccessibilitydelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uipickerviewaccessibilitydelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
