{
  "abstract": [
    {
      "text": "An effect that alters a view’s appearance when a pointer enters the current region.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIPointerEffect-swift.enum"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:5UIKit15UIPointerEffectO",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIPointerEffect"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIPointerEffect"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "UIPointerEffect"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIPointerEffect"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "code": "UIPointerEffect",
              "type": "codeVoice"
            },
            {
              "text": " automatically attempts to determine the appropriate effect for the given preview. Use one of its enumeration cases to request a specific system-provided effect.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIHoverEffect-40091": {
      "abstract": [
        {
          "text": "A hover effect that can apply to a view through a hover style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIHoverEffect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIHoverEffect-40091",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIHoverEffect"
        }
      ],
      "role": "symbol",
      "title": "UIHoverEffect",
      "type": "topic",
      "url": "/documentation/uikit/uihovereffect-40091"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory": {
      "abstract": [
        {
          "text": "Constants that describe accessories to display alongside the primary pointer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPointerAccessory"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPointerAccessory"
        }
      ],
      "role": "symbol",
      "title": "UIPointerAccessory",
      "type": "topic",
      "url": "/documentation/uikit/uipointeraccessory"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPointerEffect-swift.enum": {
      "abstract": [
        {
          "text": "An effect that alters a view’s appearance when a pointer enters the current region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPointerEffect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerEffect-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPointerEffect"
        }
      ],
      "role": "symbol",
      "title": "UIPointerEffect",
      "type": "topic",
      "url": "/documentation/uikit/uipointereffect-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPointerEffect-swift.enum/TintMode": {
      "abstract": [
        {
          "text": "An effect that defines how to apply a tint to a view during a pointer interaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TintMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerEffect-swift.enum/TintMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TintMode"
        }
      ],
      "role": "symbol",
      "title": "UIPointerEffect.TintMode",
      "type": "topic",
      "url": "/documentation/uikit/uipointereffect-swift.enum/tintmode"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPointerEffect-swift.enum/automatic(_:)": {
      "abstract": [
        {
          "text": "A pointer content effect with the given preview’s view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITargetedPreview",
          "text": "UITargetedPreview"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerEffect-swift.enum/automatic(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIPointerEffect.automatic(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uipointereffect-swift.enum/automatic(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPointerEffect-swift.enum/highlight(_:)": {
      "abstract": [
        {
          "text": "An effect where the pointer slides under the given view and morphs into the view’s shape.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "highlight"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITargetedPreview",
          "text": "UITargetedPreview"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerEffect-swift.enum/highlight(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIPointerEffect.highlight(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uipointereffect-swift.enum/highlight(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPointerEffect-swift.enum/hover(_:preferredTintMode:prefersShadow:prefersScaledContent:)": {
      "abstract": [
        {
          "text": "An effect where visual changes apply to the view and the pointer retains its default shape.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hover"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITargetedPreview",
          "text": "UITargetedPreview"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "preferredTintMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UIPointerEffectO",
          "text": "UIPointerEffect"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit15UIPointerEffectO8TintModeO",
          "text": "TintMode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "prefersShadow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "prefersScaledContent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerEffect-swift.enum/hover(_:preferredTintMode:prefersShadow:prefersScaledContent:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIPointerEffect.hover(_:preferredTintMode:prefersShadow:prefersScaledContent:)",
      "type": "topic",
      "url": "/documentation/uikit/uipointereffect-swift.enum/hover(_:preferredtintmode:prefersshadow:prefersscaledcontent:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPointerEffect-swift.enum/lift(_:)": {
      "abstract": [
        {
          "text": "An effect where the pointer slides under the given view and disappears as the view scales up and gains a shadow.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lift"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITargetedPreview",
          "text": "UITargetedPreview"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerEffect-swift.enum/lift(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIPointerEffect.lift(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uipointereffect-swift.enum/lift(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPointerEffect-swift.enum/preview": {
      "abstract": [
        {
          "text": "A preview of the view used during an interaction’s animations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preview"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITargetedPreview",
          "text": "UITargetedPreview"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerEffect-swift.enum/preview",
      "kind": "symbol",
      "role": "symbol",
      "title": "preview",
      "type": "topic",
      "url": "/documentation/uikit/uipointereffect-swift.enum/preview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPointerShape-swift.enum": {
      "abstract": [
        {
          "text": "An object that defines the shape of custom pointers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPointerShape"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerShape-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPointerShape"
        }
      ],
      "role": "symbol",
      "title": "UIPointerShape",
      "type": "topic",
      "url": "/documentation/uikit/uipointershape-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPointerStyle": {
      "abstract": [
        {
          "text": "An object that defines the pointer shape and effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPointerStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPointerStyle"
        }
      ],
      "role": "symbol",
      "title": "UIPointerStyle",
      "type": "topic",
      "url": "/documentation/uikit/uipointerstyle"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.apple.uikit/documentation/UIKit/UIHoverEffect-40091"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Pointer-styles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPointerStyle",
        "doc://com.apple.uikit/documentation/UIKit/UIPointerShape-swift.enum",
        "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory"
      ],
      "title": "Pointer styles"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accessing-the-preview",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPointerEffect-swift.enum/preview"
      ],
      "title": "Accessing the preview"
    },
    {
      "anchor": "Creating-a-default-effect",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPointerEffect-swift.enum/automatic(_:)"
      ],
      "title": "Creating a default effect"
    },
    {
      "anchor": "Creating-a-specific-effect",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPointerEffect-swift.enum/highlight(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIPointerEffect-swift.enum/hover(_:preferredTintMode:prefersShadow:prefersScaledContent:)",
        "doc://com.apple.uikit/documentation/UIKit/UIPointerEffect-swift.enum/lift(_:)"
      ],
      "title": "Creating a specific effect"
    },
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPointerEffect-swift.enum/TintMode"
      ],
      "title": "Enumerations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPointerAccessory/title",
          "value": "UIPointerAccessory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPointerAccessory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPointerAccessory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPointerAccessory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPointerAccessory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPointerStyle/title",
          "value": "UIPointerStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPointerStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPointerStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPointerStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPointerStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uipointereffect-swift.enum"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
