{
  "abstract": [
    {
      "text": "An object that defines the shape of custom pointers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIPointerShape-c.class"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIPointerShape",
    "fragments": [
      {
        "kind": "identifier",
        "text": "UIPointerShape"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIPointerShape"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.4",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "UIPointerShape"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIPointerShape"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If the desired pointer shape can be expressed as a rounded rectangle, use either ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerShape-c.class/shapeWithRoundedRect:",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerShape-c.class/shapeWithRoundedRect:cornerRadius:",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for best results.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "If used alongside a content effect, this rectangle must be in the view coordinate space of the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerEffect-swift.enum/preview",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ". Otherwise, it’s centered about the pointer’s current location, and the rectangle’s origin is interpreted as an offset.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory": {
      "abstract": [
        {
          "text": "Constants that describe accessories to display alongside the primary pointer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPointerAccessory"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPointerAccessory"
        }
      ],
      "role": "symbol",
      "title": "UIPointerAccessory",
      "type": "topic",
      "url": "/documentation/uikit/uipointeraccessory"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPointerEffect-c.class": {
      "abstract": [
        {
          "text": "An effect that alters a view’s appearance when a pointer enters the current region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIPointerEffect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerEffect-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIPointerEffect",
      "type": "topic",
      "url": "/documentation/uikit/uipointereffect-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPointerEffect-swift.enum/preview": {
      "abstract": [
        {
          "text": "A preview of the view used during an interaction’s animations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preview"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITargetedPreview",
          "text": "UITargetedPreview"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerEffect-swift.enum/preview",
      "kind": "symbol",
      "role": "symbol",
      "title": "preview",
      "type": "topic",
      "url": "/documentation/uikit/uipointereffect-swift.enum/preview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPointerShape-c.class": {
      "abstract": [
        {
          "text": "An object that defines the shape of custom pointers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIPointerShape"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerShape-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIPointerShape",
      "type": "topic",
      "url": "/documentation/uikit/uipointershape-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPointerShape-c.class/beamWithPreferredLength:axis:": {
      "abstract": [
        {
          "text": "Morphs the pointer into a vertical or horizontal beam.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "beamWithPreferredLength:axis:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerShape-c.class/beamWithPreferredLength:axis:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beamWithPreferredLength:axis:"
        }
      ],
      "role": "symbol",
      "title": "beamWithPreferredLength:axis:",
      "type": "topic",
      "url": "/documentation/uikit/uipointershape-c.class/beamwithpreferredlength:axis:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPointerShape-c.class/shapeWithPath:": {
      "abstract": [
        {
          "text": "Morphs the pointer into the given Bézier path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "shapeWithPath:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerShape-c.class/shapeWithPath:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shapeWithPath:"
        }
      ],
      "role": "symbol",
      "title": "shapeWithPath:",
      "type": "topic",
      "url": "/documentation/uikit/uipointershape-c.class/shapewithpath:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPointerShape-c.class/shapeWithRoundedRect:": {
      "abstract": [
        {
          "text": "Morphs the pointer into a rounded rectangle using the default corner radius.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "shapeWithRoundedRect:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerShape-c.class/shapeWithRoundedRect:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shapeWithRoundedRect:"
        }
      ],
      "role": "symbol",
      "title": "shapeWithRoundedRect:",
      "type": "topic",
      "url": "/documentation/uikit/uipointershape-c.class/shapewithroundedrect:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPointerShape-c.class/shapeWithRoundedRect:cornerRadius:": {
      "abstract": [
        {
          "text": "Morphs the pointer into a rounded rectangle using the provided corner radius.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "shapeWithRoundedRect:cornerRadius:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerShape-c.class/shapeWithRoundedRect:cornerRadius:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shapeWithRoundedRect:cornerRadius:"
        }
      ],
      "role": "symbol",
      "title": "shapeWithRoundedRect:cornerRadius:",
      "type": "topic",
      "url": "/documentation/uikit/uipointershape-c.class/shapewithroundedrect:cornerradius:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPointerStyle": {
      "abstract": [
        {
          "text": "An object that defines the pointer shape and effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPointerStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPointerStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPointerStyle"
        }
      ],
      "role": "symbol",
      "title": "UIPointerStyle",
      "type": "topic",
      "url": "/documentation/uikit/uipointerstyle"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Pointer-styles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPointerStyle",
        "doc://com.apple.uikit/documentation/UIKit/UIPointerEffect-c.class",
        "doc://com.apple.uikit/documentation/UIKit/UIPointerAccessory"
      ],
      "title": "Pointer styles"
    }
  ],
  "topicSections": [
    {
      "anchor": "Specifying-pointer-shapes",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPointerShape-c.class/beamWithPreferredLength:axis:",
        "doc://com.apple.uikit/documentation/UIKit/UIPointerShape-c.class/shapeWithPath:",
        "doc://com.apple.uikit/documentation/UIKit/UIPointerShape-c.class/shapeWithRoundedRect:",
        "doc://com.apple.uikit/documentation/UIKit/UIPointerShape-c.class/shapeWithRoundedRect:cornerRadius:"
      ],
      "title": "Specifying pointer shapes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPointerAccessory/title",
          "value": "UIPointerAccessory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPointerAccessory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPointerAccessory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPointerAccessory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPointerAccessory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPointerStyle/title",
          "value": "UIPointerStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPointerStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPointerStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPointerStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPointerStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uipointershape-c.class"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
