{
  "abstract": [
    {
      "text": "An object that manages the display of content in a popover.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIPopoverPresentationController",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIPopoverPresentationController"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIPopoverPresentationController"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "UIPopoverPresentationController"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIPopoverPresentationController"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.uikit/documentation/UIKit/displaying-transient-content-in-a-popover"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "From the time a popover is presented until the time it’s dismissed, UIKit uses an instance of this class to manage the presentation behavior. You use instances of this class as-is to configure aspects of the popover appearance and behavior for view controllers whose presentation style is set to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/popover",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "In nearly all cases, you use this class as-is and don’t create instances of it directly. UIKit creates an instance of this class automatically when you present a view controller using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/popover",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " style. You can retrieve that instance from the presented view controller’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/popoverPresentationController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property and use it to configure the popover behavior.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you don’t want to configure a popover immediately after presenting a view controller, you can use a delegate object to configure the popover instead. During the presentation process, the popover presentation controller calls various methods of its delegate—an object that conforms to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationControllerDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol—to ask for information and to inform it about the state of the presentation. Your delegate object can use those methods to configure the popover and adjust its behavior as needed. For information about how to implement a delegate for a popover presentation controller, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationControllerDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For information about how to display a view controller using a popover presentation controller, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/displaying-transient-content-in-a-popover",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAppearance": {
      "abstract": [
        {
          "text": "A collection of methods that gives you access to the appearance proxy for a class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAppearance"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAppearance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAppearance"
        }
      ],
      "role": "symbol",
      "title": "UIAppearance",
      "type": "topic",
      "url": "/documentation/uikit/uiappearance"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAppearanceContainer": {
      "abstract": [
        {
          "text": "A protocol that a class must adopt to allow appearance customization using the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAppearance",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " API.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAppearanceContainer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAppearanceContainer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAppearanceContainer"
        }
      ],
      "role": "symbol",
      "title": "UIAppearanceContainer",
      "type": "topic",
      "url": "/documentation/uikit/uiappearancecontainer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContentContainer": {
      "abstract": [
        {
          "text": "A set of methods for adapting the contents of your view controllers to size and trait changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIContentContainer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContentContainer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContentContainer"
        }
      ],
      "role": "symbol",
      "title": "UIContentContainer",
      "type": "topic",
      "url": "/documentation/uikit/uicontentcontainer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment": {
      "abstract": [
        {
          "text": "A set of methods that define the focus behavior for a branch of the view hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFocusEnvironment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFocusEnvironment"
        }
      ],
      "role": "symbol",
      "title": "UIFocusEnvironment",
      "type": "topic",
      "url": "/documentation/uikit/uifocusenvironment"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/popover": {
      "abstract": [
        {
          "text": "A presentation style where the content is displayed in a popover view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "popover"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIModalPresentationStyle/popover",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIModalPresentationPopover"
        }
      ],
      "role": "symbol",
      "title": "UIModalPresentationStyle.popover",
      "type": "topic",
      "url": "/documentation/uikit/uimodalpresentationstyle/popover"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPopoverBackgroundView": {
      "abstract": [
        {
          "text": "The background appearance for a popover.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPopoverBackgroundView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPopoverBackgroundView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPopoverBackgroundView"
        }
      ],
      "role": "symbol",
      "title": "UIPopoverBackgroundView",
      "type": "topic",
      "url": "/documentation/uikit/uipopoverbackgroundview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPopoverBackgroundViewMethods": {
      "abstract": [
        {
          "text": "A set of methods that popover background view subclasses must implement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPopoverBackgroundViewMethods"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPopoverBackgroundViewMethods",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPopoverBackgroundViewMethods"
        }
      ],
      "role": "symbol",
      "title": "UIPopoverBackgroundViewMethods",
      "type": "topic",
      "url": "/documentation/uikit/uipopoverbackgroundviewmethods"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController": {
      "abstract": [
        {
          "text": "An object that manages the display of content in a popover.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPopoverPresentationController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPopoverPresentationController"
        }
      ],
      "role": "symbol",
      "title": "UIPopoverPresentationController",
      "type": "topic",
      "url": "/documentation/uikit/uipopoverpresentationcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/adaptiveSheetPresentationController": {
      "abstract": [
        {
          "text": "The sheet presentation controller the popover adapts to in compact size classes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adaptiveSheetPresentationController"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISheetPresentationController",
          "text": "UISheetPresentationController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/adaptiveSheetPresentationController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "adaptiveSheetPresentationController"
        }
      ],
      "role": "symbol",
      "title": "adaptiveSheetPresentationController",
      "type": "topic",
      "url": "/documentation/uikit/uipopoverpresentationcontroller/adaptivesheetpresentationcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/arrowDirection": {
      "abstract": [
        {
          "text": "The arrow direction in use by the popover.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "arrowDirection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIPopoverArrowDirection",
          "text": "UIPopoverArrowDirection"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/arrowDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "arrowDirection"
        }
      ],
      "role": "symbol",
      "title": "arrowDirection",
      "type": "topic",
      "url": "/documentation/uikit/uipopoverpresentationcontroller/arrowdirection"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/backgroundColor": {
      "abstract": [
        {
          "text": "The color of the popover’s backdrop view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backgroundColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/backgroundColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backgroundColor"
        }
      ],
      "role": "symbol",
      "title": "backgroundColor",
      "type": "topic",
      "url": "/documentation/uikit/uipopoverpresentationcontroller/backgroundcolor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/barButtonItem": {
      "abstract": [
        {
          "text": "The bar button item on which to anchor the popover.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "barButtonItem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIBarButtonItem",
          "text": "UIBarButtonItem"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/barButtonItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "barButtonItem"
        }
      ],
      "role": "symbol",
      "title": "barButtonItem",
      "type": "topic",
      "url": "/documentation/uikit/uipopoverpresentationcontroller/barbuttonitem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/canOverlapSourceViewRect": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the popover can overlap its view rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canOverlapSourceViewRect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/canOverlapSourceViewRect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canOverlapSourceViewRect"
        }
      ],
      "role": "symbol",
      "title": "canOverlapSourceViewRect",
      "type": "topic",
      "url": "/documentation/uikit/uipopoverpresentationcontroller/canoverlapsourceviewrect"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/delegate": {
      "abstract": [
        {
          "text": "The delegate that handles popover-related messages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIPopoverPresentationControllerDelegate",
          "text": "UIPopoverPresentationControllerDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/uikit/uipopoverpresentationcontroller/delegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/passthroughViews": {
      "abstract": [
        {
          "text": "An array of views that the user can interact with while the popover is visible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "passthroughViews"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/passthroughViews",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "passthroughViews"
        }
      ],
      "role": "symbol",
      "title": "passthroughViews",
      "type": "topic",
      "url": "/documentation/uikit/uipopoverpresentationcontroller/passthroughviews"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/permittedArrowDirections": {
      "abstract": [
        {
          "text": "The arrow directions that you allow for the popover.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "permittedArrowDirections"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIPopoverArrowDirection",
          "text": "UIPopoverArrowDirection"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/permittedArrowDirections",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "permittedArrowDirections"
        }
      ],
      "role": "symbol",
      "title": "permittedArrowDirections",
      "type": "topic",
      "url": "/documentation/uikit/uipopoverpresentationcontroller/permittedarrowdirections"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/popoverBackgroundViewClass": {
      "abstract": [
        {
          "text": "The class to use for displaying the popover background content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "popoverBackgroundViewClass"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIPopoverBackgroundViewMethods",
          "text": "UIPopoverBackgroundViewMethods"
        },
        {
          "kind": "text",
          "text": ".Type)?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/popoverBackgroundViewClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "popoverBackgroundViewClass"
        }
      ],
      "role": "symbol",
      "title": "popoverBackgroundViewClass",
      "type": "topic",
      "url": "/documentation/uikit/uipopoverpresentationcontroller/popoverbackgroundviewclass"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/popoverLayoutMargins": {
      "abstract": [
        {
          "text": "The margins that define the portion of the screen in which it is permissible to display the popover.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "popoverLayoutMargins"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@UIEdgeInsets",
          "text": "UIEdgeInsets"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/popoverLayoutMargins",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "popoverLayoutMargins"
        }
      ],
      "role": "symbol",
      "title": "popoverLayoutMargins",
      "type": "topic",
      "url": "/documentation/uikit/uipopoverpresentationcontroller/popoverlayoutmargins"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/sourceItem": {
      "abstract": [
        {
          "text": "The item on which to anchor the popover.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceItem"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIPopoverPresentationControllerSourceItem",
          "text": "UIPopoverPresentationControllerSourceItem"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/sourceItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sourceItem"
        }
      ],
      "role": "symbol",
      "title": "sourceItem",
      "type": "topic",
      "url": "/documentation/uikit/uipopoverpresentationcontroller/sourceitem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/sourceRect": {
      "abstract": [
        {
          "text": "The area in the source view in which you anchor the popover.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceRect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/sourceRect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sourceRect"
        }
      ],
      "role": "symbol",
      "title": "sourceRect",
      "type": "topic",
      "url": "/documentation/uikit/uipopoverpresentationcontroller/sourcerect"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/sourceView": {
      "abstract": [
        {
          "text": "The view containing the anchor rectangle for the popover.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sourceView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/sourceView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "sourceView"
        }
      ],
      "role": "symbol",
      "title": "sourceView",
      "type": "topic",
      "url": "/documentation/uikit/uipopoverpresentationcontroller/sourceview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationControllerDelegate": {
      "abstract": [
        {
          "text": "The interface for a popover presentation delegate, which lets you customize the behavior of a popover-based presentation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPopoverPresentationControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPopoverPresentationControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIPopoverPresentationControllerDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uipopoverpresentationcontrollerdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationControllerSourceItem": {
      "abstract": [
        {
          "text": "A type that can be an anchor for a popover presentation controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPopoverPresentationControllerSourceItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationControllerSourceItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPopoverPresentationControllerSourceItem"
        }
      ],
      "role": "symbol",
      "title": "UIPopoverPresentationControllerSourceItem",
      "type": "topic",
      "url": "/documentation/uikit/uipopoverpresentationcontrollersourceitem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPresentationController": {
      "abstract": [
        {
          "text": "An object that manages the transition animations and the presentation of view controllers onscreen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPresentationController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPresentationController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPresentationController"
        }
      ],
      "role": "symbol",
      "title": "UIPresentationController",
      "type": "topic",
      "url": "/documentation/uikit/uipresentationcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94": {
      "abstract": [
        {
          "text": "A type that calls your code in reaction to changes in the trait environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITraitChangeObservable"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITraitChangeObservable"
        }
      ],
      "role": "symbol",
      "title": "UITraitChangeObservable",
      "type": "topic",
      "url": "/documentation/uikit/uitraitchangeobservable-67e94"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitEnvironment": {
      "abstract": [
        {
          "text": "A set of methods that makes the iOS interface environment available to your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITraitEnvironment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitEnvironment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITraitEnvironment"
        }
      ],
      "role": "symbol",
      "title": "UITraitEnvironment",
      "type": "topic",
      "url": "/documentation/uikit/uitraitenvironment"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/popoverPresentationController": {
      "abstract": [
        {
          "text": "The nearest popover presentation controller that is managing the current view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "popoverPresentationController"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPopoverPresentationController",
          "text": "UIPopoverPresentationController"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/popoverPresentationController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "popoverPresentationController"
        }
      ],
      "role": "symbol",
      "title": "popoverPresentationController",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/popoverpresentationcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/displaying-transient-content-in-a-popover": {
      "abstract": [
        {
          "text": "Show a temporary interface on top of your app’s content on iPad.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/displaying-transient-content-in-a-popover",
      "kind": "article",
      "role": "article",
      "title": "Displaying transient content in a popover",
      "type": "topic",
      "url": "/documentation/uikit/displaying-transient-content-in-a-popover"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPresentationController"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.apple.uikit/documentation/UIKit/UIAppearanceContainer",
        "doc://com.apple.uikit/documentation/UIKit/UIContentContainer",
        "doc://com.apple.uikit/documentation/UIKit/UIFocusEnvironment",
        "doc://com.apple.uikit/documentation/UIKit/UITraitChangeObservable-67e94",
        "doc://com.apple.uikit/documentation/UIKit/UITraitEnvironment"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Popovers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/displaying-transient-content-in-a-popover",
        "doc://com.apple.uikit/documentation/UIKit/UIPopoverBackgroundView",
        "doc://com.apple.uikit/documentation/UIKit/UIPopoverBackgroundViewMethods"
      ],
      "title": "Popovers"
    }
  ],
  "topicSections": [
    {
      "anchor": "Customizing-the-popover-behavior",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/delegate",
        "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationControllerDelegate"
      ],
      "title": "Customizing the popover behavior"
    },
    {
      "anchor": "Configuring-the-popover-appearance",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/popoverLayoutMargins",
        "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/backgroundColor",
        "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/passthroughViews",
        "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/popoverBackgroundViewClass",
        "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/canOverlapSourceViewRect"
      ],
      "title": "Configuring the popover appearance"
    },
    {
      "anchor": "Specifying-the-popovers-anchor-point",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/sourceItem",
        "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationControllerSourceItem",
        "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/sourceView",
        "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/sourceRect",
        "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/barButtonItem"
      ],
      "title": "Specifying the popover’s anchor point"
    },
    {
      "anchor": "Configuring-the-popover-arrows",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/permittedArrowDirections",
        "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/arrowDirection"
      ],
      "title": "Configuring the popover arrows"
    },
    {
      "anchor": "Displaying-the-popover-as-a-sheet",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/adaptiveSheetPresentationController"
      ],
      "title": "Displaying the popover as a sheet"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIPopoverPresentationController"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPopoverPresentationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPopoverPresentationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Customizing-the-popover-behavior",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/delegate",
                "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationControllerDelegate"
              ],
              "title": "Customizing the popover behavior"
            },
            {
              "anchor": "Configuring-the-popover-appearance",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/popoverLayoutMargins",
                "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/backgroundColor",
                "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/passthroughViews",
                "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/popoverBackgroundViewClass",
                "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/canOverlapSourceViewRect"
              ],
              "title": "Configuring the popover appearance"
            },
            {
              "anchor": "Specifying-the-popovers-anchor-point",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/sourceItem",
                "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationControllerSourceItem",
                "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/sourceView",
                "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/sourceRect",
                "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/barButtonItem"
              ],
              "title": "Specifying the popover’s anchor point"
            },
            {
              "anchor": "Configuring-the-popover-arrows",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/permittedArrowDirections",
                "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/arrowDirection"
              ],
              "title": "Configuring the popover arrows"
            },
            {
              "anchor": "Displaying-the-popover-as-a-sheet",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPopoverPresentationController/adaptiveSheetPresentationController"
              ],
              "title": "Displaying the popover as a sheet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPresentationController"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Popovers",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/displaying-transient-content-in-a-popover",
                "doc://com.apple.uikit/documentation/UIKit/UIPopoverBackgroundView",
                "doc://com.apple.uikit/documentation/UIKit/UIPopoverBackgroundViewMethods"
              ],
              "title": "Popovers"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIPopoverPresentationController"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPresentationController",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UIPresentationController",
                    "text": "UIPresentationController"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController~1popoverLayoutMargins/title",
          "value": "popoverLayoutMargins"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController~1popoverLayoutMargins/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "popoverLayoutMargins"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController~1popoverBackgroundViewClass/title",
          "value": "popoverBackgroundViewClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController~1popoverBackgroundViewClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "popoverBackgroundViewClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusEnvironment/title",
          "value": "UIFocusEnvironment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusEnvironment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFocusEnvironment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusEnvironment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFocusEnvironment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController~1backgroundColor/title",
          "value": "backgroundColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController~1backgroundColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "backgroundColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationControllerSourceItem/title",
          "value": "UIPopoverPresentationControllerSourceItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationControllerSourceItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPopoverPresentationControllerSourceItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationControllerSourceItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPopoverPresentationControllerSourceItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentContainer/title",
          "value": "UIContentContainer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentContainer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContentContainer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContentContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationControllerDelegate/title",
          "value": "UIPopoverPresentationControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPopoverPresentationControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPopoverPresentationControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverBackgroundViewMethods/title",
          "value": "UIPopoverBackgroundViewMethods"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverBackgroundViewMethods/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPopoverBackgroundViewMethods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverBackgroundViewMethods/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPopoverBackgroundViewMethods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverBackgroundView/title",
          "value": "UIPopoverBackgroundView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverBackgroundView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPopoverBackgroundView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverBackgroundView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPopoverBackgroundView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController~1passthroughViews/title",
          "value": "passthroughViews"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController~1passthroughViews/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "passthroughViews"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController~1canOverlapSourceViewRect/title",
          "value": "canOverlapSourceViewRect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController~1canOverlapSourceViewRect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "canOverlapSourceViewRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController/title",
          "value": "UIPopoverPresentationController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPopoverPresentationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPopoverPresentationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1popover/title",
          "value": "UIModalPresentationPopover"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIModalPresentationStyle~1popover/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIModalPresentationPopover"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1popoverPresentationController/title",
          "value": "popoverPresentationController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1popoverPresentationController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "popoverPresentationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPresentationController/title",
          "value": "UIPresentationController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPresentationController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPresentationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPresentationController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPresentationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController~1permittedArrowDirections/title",
          "value": "permittedArrowDirections"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController~1permittedArrowDirections/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "permittedArrowDirections"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAppearance/title",
          "value": "UIAppearance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAppearance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAppearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAppearance/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAppearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController~1sourceItem/title",
          "value": "sourceItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController~1sourceItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sourceItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController~1sourceView/title",
          "value": "sourceView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController~1sourceView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sourceView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController~1adaptiveSheetPresentationController/title",
          "value": "adaptiveSheetPresentationController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController~1adaptiveSheetPresentationController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "adaptiveSheetPresentationController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitEnvironment/title",
          "value": "UITraitEnvironment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitEnvironment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITraitEnvironment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitEnvironment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITraitEnvironment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController~1arrowDirection/title",
          "value": "arrowDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController~1arrowDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "arrowDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController~1barButtonItem/title",
          "value": "barButtonItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController~1barButtonItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "barButtonItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController~1sourceRect/title",
          "value": "sourceRect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverPresentationController~1sourceRect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "sourceRect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAppearanceContainer/title",
          "value": "UIAppearanceContainer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAppearanceContainer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAppearanceContainer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAppearanceContainer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAppearanceContainer"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uipopoverpresentationcontroller"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uipopoverpresentationcontroller"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
