{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIProposedSceneSizeNoPreference"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@UIProposedSceneSizeNoPreference",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIProposedSceneSizeNoPreference"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
        "text": "CGFloat"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIProposedSceneSizeNoPreference"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "UIProposedSceneSizeNoPreference"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIProposedSceneSizeNoPreference"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
              "text": "CGFloat"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIProposedSceneSizeNoPreference": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIProposedSceneSizeNoPreference"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIProposedSceneSizeNoPreference",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIProposedSceneSizeNoPreference"
        }
      ],
      "role": "symbol",
      "title": "UIProposedSceneSizeNoPreference",
      "type": "topic",
      "url": "/documentation/uikit/uiproposedscenesizenopreference"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/Geometry": {
      "abstract": [
        {
          "text": "An object that provides geometry information about the window scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Geometry"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/Geometry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Geometry"
        }
      ],
      "role": "symbol",
      "title": "UIWindowScene.Geometry",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/geometry"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences": {
      "abstract": [
        {
          "text": "An abstract superclass for representing window scene geometry preferences.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GeometryPreferences"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GeometryPreferences"
        }
      ],
      "role": "symbol",
      "title": "UIWindowScene.GeometryPreferences",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/geometrypreferences"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences/Mac": {
      "abstract": [
        {
          "text": "An object that represents the geometry preferences for a window scene in an app built with Mac Catalyst.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Mac"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences/Mac",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Mac"
        }
      ],
      "role": "symbol",
      "title": "UIWindowScene.GeometryPreferences.Mac",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/geometrypreferences/mac"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences/Vision": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Vision"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences/Vision",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Vision"
        }
      ],
      "role": "symbol",
      "title": "UIWindowScene.GeometryPreferences.Vision",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/geometrypreferences/vision"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences/iOS": {
      "abstract": [
        {
          "text": "An object that represents the geometry preferences for a window scene in an iOS app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iOS"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences/iOS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "iOS"
        }
      ],
      "role": "symbol",
      "title": "UIWindowScene.GeometryPreferences.iOS",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/geometrypreferences/ios"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/effectiveGeometry": {
      "abstract": [
        {
          "text": "The current values for the window scene’s geometry in system space.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "effectiveGeometry"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIWindowScene",
          "text": "UIWindowScene"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIWindowSceneGeometry",
          "text": "Geometry"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/effectiveGeometry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "effectiveGeometry"
        }
      ],
      "role": "symbol",
      "title": "effectiveGeometry",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/effectivegeometry"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/requestGeometryUpdate(_:errorHandler:)": {
      "abstract": [
        {
          "text": "Requests an update to the window scene’s geometry using the specified geometry preferences object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestGeometryUpdate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIWindowScene",
          "text": "UIWindowScene"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIWindowSceneGeometryPreferences",
          "text": "GeometryPreferences"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "errorHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/requestGeometryUpdate(_:errorHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestGeometryUpdateWithPreferences:errorHandler:"
        }
      ],
      "role": "symbol",
      "title": "requestGeometryUpdate(_:errorHandler:)",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene/requestgeometryupdate(_:errorhandler:)"
    },
    "doc://com.externally.resolved.symbol/c:@T@CGFloat": {
      "abstract": [
        {
          "text": "The basic type for all floating-point values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CGFloat",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGFloat",
      "type": "topic",
      "url": "/documentation/corefoundation/cgfloat"
    },
    "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV": {
      "abstract": [
        {
          "text": "The basic type for floating-point scalar values in Core Graphics and related frameworks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGFloat",
      "type": "topic",
      "url": "/documentation/corefoundation/cgfloat"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Working-with-window-geometry",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/effectiveGeometry",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/requestGeometryUpdate(_:errorHandler:)",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/Geometry",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences/iOS",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences/Mac",
        "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences/Vision"
      ],
      "title": "Working with window geometry"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIProposedSceneSizeNoPreference"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIProposedSceneSizeNoPreference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Working-with-window-geometry",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/effectiveGeometry",
                "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/requestGeometryUpdate(_:errorHandler:)",
                "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/Geometry",
                "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences",
                "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences/iOS",
                "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences/Mac",
                "doc://com.apple.uikit/documentation/UIKit/UIWindowScene/GeometryPreferences/Vision"
              ],
              "title": "Working with window geometry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CGFloat",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CGFloat",
                    "text": "CGFloat"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIProposedSceneSizeNoPreference"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1GeometryPreferences~1iOS/title",
          "value": "UIWindowSceneGeometryPreferencesIOS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1GeometryPreferences~1iOS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneGeometryPreferencesIOS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1GeometryPreferences~1iOS/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneGeometryPreferencesIOS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1GeometryPreferences~1Mac/title",
          "value": "UIWindowSceneGeometryPreferencesMac"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1GeometryPreferences~1Mac/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneGeometryPreferencesMac"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1GeometryPreferences~1Mac/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneGeometryPreferencesMac"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1requestGeometryUpdate(_:errorHandler:)/title",
          "value": "requestGeometryUpdateWithPreferences:errorHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1requestGeometryUpdate(_:errorHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestGeometryUpdateWithPreferences:errorHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1GeometryPreferences~1Vision/title",
          "value": "UIWindowSceneGeometryPreferencesVision"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1GeometryPreferences~1Vision/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneGeometryPreferencesVision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1GeometryPreferences~1Vision/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneGeometryPreferencesVision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1Geometry/title",
          "value": "UIWindowSceneGeometry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1Geometry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneGeometry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1Geometry/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneGeometry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1GeometryPreferences/title",
          "value": "UIWindowSceneGeometryPreferences"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1GeometryPreferences/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneGeometryPreferences"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1GeometryPreferences/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowSceneGeometryPreferences"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1effectiveGeometry/title",
          "value": "effectiveGeometry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1effectiveGeometry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "effectiveGeometry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIProposedSceneSizeNoPreference/title",
          "value": "UIProposedSceneSizeNoPreference"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIProposedSceneSizeNoPreference/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIProposedSceneSizeNoPreference"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiproposedscenesizenopreference"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiproposedscenesizenopreference"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
