{
  "abstract": [
    {
      "text": "A set of methods for managing the presentation and dismissal of a printer picker interface.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerControllerDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UIPrinterPickerControllerDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIPrinterPickerControllerDelegate"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIPrinterPickerControllerDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "UIPrinterPickerControllerDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIPrinterPickerControllerDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You also use the methods of this protocol to influence the content displayed in the picker and to respond when the user selects a printer. Implement the methods of this protocol in your own custom object and assign that object to the delegate property of your ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object before presenting it. When you present the picker, it calls the methods of your delegate at appropriate times to ask for information or provide you with information about the state of the picker interface. For more information about presenting a printer picker interface, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerController": {
      "abstract": [
        {
          "text": "A view controller that displays the standard interface for selecting a printer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPrinterPickerController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrinterPickerController"
        }
      ],
      "role": "symbol",
      "title": "UIPrinterPickerController",
      "type": "topic",
      "url": "/documentation/uikit/uiprinterpickercontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerController/delegate": {
      "abstract": [
        {
          "text": "The delegate for the printer picker controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIPrinterPickerControllerDelegate",
          "text": "UIPrinterPickerControllerDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerController/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/uikit/uiprinterpickercontroller/delegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerControllerDelegate": {
      "abstract": [
        {
          "text": "A set of methods for managing the presentation and dismissal of a printer picker interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPrinterPickerControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrinterPickerControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIPrinterPickerControllerDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uiprinterpickercontrollerdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerControllerDelegate/printerPickerController(_:shouldShow:)": {
      "abstract": [
        {
          "text": "Asks the delegate if the specified printer should be included in the picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "printerPickerController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPrinterPickerController",
          "text": "UIPrinterPickerController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shouldShow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPrinter",
          "text": "UIPrinter"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerControllerDelegate/printerPickerController(_:shouldShow:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printerPickerController:shouldShowPrinter:"
        }
      ],
      "role": "symbol",
      "title": "printerPickerController(_:shouldShow:)",
      "type": "topic",
      "url": "/documentation/uikit/uiprinterpickercontrollerdelegate/printerpickercontroller(_:shouldshow:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerControllerDelegate/printerPickerControllerDidDismiss(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the printer picker was dismissed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "printerPickerControllerDidDismiss"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPrinterPickerController",
          "text": "UIPrinterPickerController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerControllerDelegate/printerPickerControllerDidDismiss(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printerPickerControllerDidDismiss:"
        }
      ],
      "role": "symbol",
      "title": "printerPickerControllerDidDismiss(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiprinterpickercontrollerdelegate/printerpickercontrollerdiddismiss(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerControllerDelegate/printerPickerControllerDidPresent(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the printer picker was displayed and is now visible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "printerPickerControllerDidPresent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPrinterPickerController",
          "text": "UIPrinterPickerController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerControllerDelegate/printerPickerControllerDidPresent(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printerPickerControllerDidPresent:"
        }
      ],
      "role": "symbol",
      "title": "printerPickerControllerDidPresent(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiprinterpickercontrollerdelegate/printerpickercontrollerdidpresent(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerControllerDelegate/printerPickerControllerDidSelectPrinter(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that a printer was selected.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "printerPickerControllerDidSelectPrinter"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPrinterPickerController",
          "text": "UIPrinterPickerController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerControllerDelegate/printerPickerControllerDidSelectPrinter(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printerPickerControllerDidSelectPrinter:"
        }
      ],
      "role": "symbol",
      "title": "printerPickerControllerDidSelectPrinter(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiprinterpickercontrollerdelegate/printerpickercontrollerdidselectprinter(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerControllerDelegate/printerPickerControllerParentViewController(_:)": {
      "abstract": [
        {
          "text": "Asks the delegate to provide the view controller to act as the parent of the printer picker.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "printerPickerControllerParentViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPrinterPickerController",
          "text": "UIPrinterPickerController"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerControllerDelegate/printerPickerControllerParentViewController(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printerPickerControllerParentViewController:"
        }
      ],
      "role": "symbol",
      "title": "printerPickerControllerParentViewController(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiprinterpickercontrollerdelegate/printerpickercontrollerparentviewcontroller(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerControllerDelegate/printerPickerControllerWillDismiss(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the printer picker is about to be dismissed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "printerPickerControllerWillDismiss"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPrinterPickerController",
          "text": "UIPrinterPickerController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerControllerDelegate/printerPickerControllerWillDismiss(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printerPickerControllerWillDismiss:"
        }
      ],
      "role": "symbol",
      "title": "printerPickerControllerWillDismiss(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiprinterpickercontrollerdelegate/printerpickercontrollerwilldismiss(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerControllerDelegate/printerPickerControllerWillPresent(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the printer picker is about to be displayed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "printerPickerControllerWillPresent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPrinterPickerController",
          "text": "UIPrinterPickerController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerControllerDelegate/printerPickerControllerWillPresent(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printerPickerControllerWillPresent:"
        }
      ],
      "role": "symbol",
      "title": "printerPickerControllerWillPresent(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiprinterpickercontrollerdelegate/printerpickercontrollerwillpresent(_:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-the-printer-picker-interface",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerController/delegate"
      ],
      "title": "Managing the printer picker interface"
    }
  ],
  "topicSections": [
    {
      "anchor": "Filtering-the-List-of-Printers",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerControllerDelegate/printerPickerController(_:shouldShow:)"
      ],
      "title": "Filtering the List of Printers"
    },
    {
      "anchor": "Handling-the-Printer-Selection",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerControllerDelegate/printerPickerControllerDidSelectPrinter(_:)"
      ],
      "title": "Handling the Printer Selection"
    },
    {
      "anchor": "Responding-to-Printer-Picker-Events",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerControllerDelegate/printerPickerControllerParentViewController(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerControllerDelegate/printerPickerControllerWillPresent(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerControllerDelegate/printerPickerControllerDidPresent(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerControllerDelegate/printerPickerControllerWillDismiss(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerControllerDelegate/printerPickerControllerDidDismiss(_:)"
      ],
      "title": "Responding to Printer Picker Events"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIPrinterPickerControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrinterPickerControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrinterPickerControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Filtering-the-List-of-Printers",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerControllerDelegate/printerPickerController(_:shouldShow:)"
              ],
              "title": "Filtering the List of Printers"
            },
            {
              "anchor": "Handling-the-Printer-Selection",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerControllerDelegate/printerPickerControllerDidSelectPrinter(_:)"
              ],
              "title": "Handling the Printer Selection"
            },
            {
              "anchor": "Responding-to-Printer-Picker-Events",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerControllerDelegate/printerPickerControllerParentViewController(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerControllerDelegate/printerPickerControllerWillPresent(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerControllerDelegate/printerPickerControllerDidPresent(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerControllerDelegate/printerPickerControllerWillDismiss(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerControllerDelegate/printerPickerControllerDidDismiss(_:)"
              ],
              "title": "Responding to Printer Picker Events"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-the-printer-picker-interface",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPrinterPickerController/delegate"
              ],
              "title": "Managing the printer picker interface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIPrinterPickerControllerDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinterPickerController/title",
          "value": "UIPrinterPickerController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinterPickerController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrinterPickerController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinterPickerController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrinterPickerController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinterPickerControllerDelegate~1printerPickerController(_:shouldShow:)/title",
          "value": "printerPickerController:shouldShowPrinter:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinterPickerControllerDelegate~1printerPickerController(_:shouldShow:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "printerPickerController:shouldShowPrinter:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinterPickerControllerDelegate~1printerPickerControllerWillPresent(_:)/title",
          "value": "printerPickerControllerWillPresent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinterPickerControllerDelegate~1printerPickerControllerWillPresent(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "printerPickerControllerWillPresent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinterPickerControllerDelegate~1printerPickerControllerDidSelectPrinter(_:)/title",
          "value": "printerPickerControllerDidSelectPrinter:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinterPickerControllerDelegate~1printerPickerControllerDidSelectPrinter(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "printerPickerControllerDidSelectPrinter:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinterPickerControllerDelegate/title",
          "value": "UIPrinterPickerControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinterPickerControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrinterPickerControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinterPickerControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrinterPickerControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinterPickerControllerDelegate~1printerPickerControllerDidPresent(_:)/title",
          "value": "printerPickerControllerDidPresent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinterPickerControllerDelegate~1printerPickerControllerDidPresent(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "printerPickerControllerDidPresent:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinterPickerControllerDelegate~1printerPickerControllerParentViewController(_:)/title",
          "value": "printerPickerControllerParentViewController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinterPickerControllerDelegate~1printerPickerControllerParentViewController(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "printerPickerControllerParentViewController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinterPickerControllerDelegate~1printerPickerControllerWillDismiss(_:)/title",
          "value": "printerPickerControllerWillDismiss:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinterPickerControllerDelegate~1printerPickerControllerWillDismiss(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "printerPickerControllerWillDismiss:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinterPickerControllerDelegate~1printerPickerControllerDidDismiss(_:)/title",
          "value": "printerPickerControllerDidDismiss:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinterPickerControllerDelegate~1printerPickerControllerDidDismiss(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "printerPickerControllerDidDismiss:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinterPickerController~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinterPickerController~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiprinterpickercontrollerdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiprinterpickercontrollerdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
