{
  "abstract": [
    {
      "text": "An optional set of methods that the delegate of the shared print-interaction controller implements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UIPrintInteractionControllerDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIPrintInteractionControllerDelegate"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIPrintInteractionControllerDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "UIPrintInteractionControllerDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIPrintInteractionControllerDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If the application has special requirements for content sizes, it can implement ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionController(_:choosePaper:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to return a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintPaper",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object encapsulating the page size and the printing area to use for a print job. If you want more control of the presentation of the printing options, the delegate can return a view controller that owns the printing-options view in an implementation of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionControllerParentViewController(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". The delegate can also implement methods that are invoked when the printing user interface is presented and when it is dismissed, and when the print job begins and ends.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionController/delegate": {
      "abstract": [
        {
          "text": "The delegate of the print-interaction controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIPrintInteractionControllerDelegate",
          "text": "UIPrintInteractionControllerDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionController/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinteractioncontroller/delegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate": {
      "abstract": [
        {
          "text": "An optional set of methods that the delegate of the shared print-interaction controller implements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPrintInteractionControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrintInteractionControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIPrintInteractionControllerDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinteractioncontrollerdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionController(_:chooseCutterBehavior:)": {
      "abstract": [
        {
          "text": "Asks the delegate for the cutter behavior for the print job.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "printInteractionController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPrintInteractionController",
          "text": "UIPrintInteractionController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "chooseCutterBehavior"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPrinter",
          "text": "UIPrinter"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIPrinterCutterBehavior",
          "text": "CutterBehavior"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionController(_:chooseCutterBehavior:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printInteractionController:chooseCutterBehavior:"
        }
      ],
      "role": "symbol",
      "title": "printInteractionController(_:chooseCutterBehavior:)",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinteractioncontrollerdelegate/printinteractioncontroller(_:choosecutterbehavior:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionController(_:choosePaper:)": {
      "abstract": [
        {
          "text": "Asks the delegate for an object that encapsulates the paper size and printing area for the print job.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "printInteractionController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPrintInteractionController",
          "text": "UIPrintInteractionController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "choosePaper"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPrintPaper",
          "text": "UIPrintPaper"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPrintPaper",
          "text": "UIPrintPaper"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionController(_:choosePaper:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printInteractionController:choosePaper:"
        }
      ],
      "role": "symbol",
      "title": "printInteractionController(_:choosePaper:)",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinteractioncontrollerdelegate/printinteractioncontroller(_:choosepaper:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionController(_:cutLengthFor:)": {
      "abstract": [
        {
          "text": "Asks the delegate for a length to use when cutting the page.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "printInteractionController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPrintInteractionController",
          "text": "UIPrintInteractionController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "cutLengthFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPrintPaper",
          "text": "UIPrintPaper"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionController(_:cutLengthFor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printInteractionController:cutLengthForPaper:"
        }
      ],
      "role": "symbol",
      "title": "printInteractionController(_:cutLengthFor:)",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinteractioncontrollerdelegate/printinteractioncontroller(_:cutlengthfor:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionControllerDidDismissPrinterOptions(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the device is dismissing the printing-options user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "printInteractionControllerDidDismissPrinterOptions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPrintInteractionController",
          "text": "UIPrintInteractionController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionControllerDidDismissPrinterOptions(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printInteractionControllerDidDismissPrinterOptions:"
        }
      ],
      "role": "symbol",
      "title": "printInteractionControllerDidDismissPrinterOptions(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinteractioncontrollerdelegate/printinteractioncontrollerdiddismissprinteroptions(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionControllerDidFinishJob(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the print job has ended.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "printInteractionControllerDidFinishJob"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPrintInteractionController",
          "text": "UIPrintInteractionController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionControllerDidFinishJob(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printInteractionControllerDidFinishJob:"
        }
      ],
      "role": "symbol",
      "title": "printInteractionControllerDidFinishJob(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinteractioncontrollerdelegate/printinteractioncontrollerdidfinishjob(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionControllerDidPresentPrinterOptions(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the device has presented the printing-options user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "printInteractionControllerDidPresentPrinterOptions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPrintInteractionController",
          "text": "UIPrintInteractionController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionControllerDidPresentPrinterOptions(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printInteractionControllerDidPresentPrinterOptions:"
        }
      ],
      "role": "symbol",
      "title": "printInteractionControllerDidPresentPrinterOptions(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinteractioncontrollerdelegate/printinteractioncontrollerdidpresentprinteroptions(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionControllerParentViewController(_:)": {
      "abstract": [
        {
          "text": "Returns a parent view controller for managing the printing-options view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "printInteractionControllerParentViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPrintInteractionController",
          "text": "UIPrintInteractionController"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionControllerParentViewController(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printInteractionControllerParentViewController:"
        }
      ],
      "role": "symbol",
      "title": "printInteractionControllerParentViewController(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinteractioncontrollerdelegate/printinteractioncontrollerparentviewcontroller(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionControllerWillDismissPrinterOptions(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the device is about to dismiss the printing-options user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "printInteractionControllerWillDismissPrinterOptions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPrintInteractionController",
          "text": "UIPrintInteractionController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionControllerWillDismissPrinterOptions(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printInteractionControllerWillDismissPrinterOptions:"
        }
      ],
      "role": "symbol",
      "title": "printInteractionControllerWillDismissPrinterOptions(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinteractioncontrollerdelegate/printinteractioncontrollerwilldismissprinteroptions(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionControllerWillPresentPrinterOptions(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the device is about to display the printing-options user interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "printInteractionControllerWillPresentPrinterOptions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPrintInteractionController",
          "text": "UIPrintInteractionController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionControllerWillPresentPrinterOptions(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printInteractionControllerWillPresentPrinterOptions:"
        }
      ],
      "role": "symbol",
      "title": "printInteractionControllerWillPresentPrinterOptions(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinteractioncontrollerdelegate/printinteractioncontrollerwillpresentprinteroptions(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionControllerWillStartJob(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the print job is about to start.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "printInteractionControllerWillStartJob"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPrintInteractionController",
          "text": "UIPrintInteractionController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionControllerWillStartJob(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printInteractionControllerWillStartJob:"
        }
      ],
      "role": "symbol",
      "title": "printInteractionControllerWillStartJob(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinteractioncontrollerdelegate/printinteractioncontrollerwillstartjob(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintPaper": {
      "abstract": [
        {
          "text": "The size of paper for a print job and the rectangular area that the content prints within.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPrintPaper"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintPaper",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrintPaper"
        }
      ],
      "role": "symbol",
      "title": "UIPrintPaper",
      "type": "topic",
      "url": "/documentation/uikit/uiprintpaper"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrinter/CutterBehavior": {
      "abstract": [
        {
          "text": "Constants that specify the cutter behavior of a roll-fed printer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CutterBehavior"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrinter/CutterBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CutterBehavior"
        }
      ],
      "role": "symbol",
      "title": "UIPrinter.CutterBehavior",
      "type": "topic",
      "url": "/documentation/uikit/uiprinter/cutterbehavior"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Assigning-the-delegate",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionController/delegate"
      ],
      "title": "Assigning the delegate"
    }
  ],
  "topicSections": [
    {
      "anchor": "Returning-a-Parent-View-Controller",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionControllerParentViewController(_:)"
      ],
      "title": "Returning a Parent View Controller"
    },
    {
      "anchor": "Choosing-a-Paper-Size-for-the-Print-Job",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionController(_:choosePaper:)",
        "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionController(_:cutLengthFor:)",
        "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionController(_:chooseCutterBehavior:)"
      ],
      "title": "Choosing a Paper Size for the Print Job"
    },
    {
      "anchor": "Responding-to-the-Presentation-and-Dismissal-of-the-Printing-Interface",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionControllerWillPresentPrinterOptions(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionControllerDidPresentPrinterOptions(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionControllerWillDismissPrinterOptions(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionControllerDidDismissPrinterOptions(_:)"
      ],
      "title": "Responding to the Presentation and Dismissal of the Printing Interface"
    },
    {
      "anchor": "Responding-to-the-Start-and-End-of-a-Print-Job",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionControllerWillStartJob(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionControllerDidFinishJob(_:)"
      ],
      "title": "Responding to the Start and End of a Print Job"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPrinter/CutterBehavior"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIPrintInteractionControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintInteractionControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintInteractionControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Returning-a-Parent-View-Controller",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionControllerParentViewController(_:)"
              ],
              "title": "Returning a Parent View Controller"
            },
            {
              "anchor": "Choosing-a-Paper-Size-for-the-Print-Job",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionController(_:choosePaper:)",
                "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionController(_:cutLengthFor:)",
                "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionController(_:chooseCutterBehavior:)"
              ],
              "title": "Choosing a Paper Size for the Print Job"
            },
            {
              "anchor": "Responding-to-the-Presentation-and-Dismissal-of-the-Printing-Interface",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionControllerWillPresentPrinterOptions(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionControllerDidPresentPrinterOptions(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionControllerWillDismissPrinterOptions(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionControllerDidDismissPrinterOptions(_:)"
              ],
              "title": "Responding to the Presentation and Dismissal of the Printing Interface"
            },
            {
              "anchor": "Responding-to-the-Start-and-End-of-a-Print-Job",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionControllerWillStartJob(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionControllerDelegate/printInteractionControllerDidFinishJob(_:)"
              ],
              "title": "Responding to the Start and End of a Print Job"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPrinter/CutterBehavior"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Assigning-the-delegate",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionController/delegate"
              ],
              "title": "Assigning the delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIPrintInteractionControllerDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionControllerDelegate~1printInteractionController(_:chooseCutterBehavior:)/title",
          "value": "printInteractionController:chooseCutterBehavior:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionControllerDelegate~1printInteractionController(_:chooseCutterBehavior:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "printInteractionController:chooseCutterBehavior:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionControllerDelegate~1printInteractionController(_:choosePaper:)/title",
          "value": "printInteractionController:choosePaper:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionControllerDelegate~1printInteractionController(_:choosePaper:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "printInteractionController:choosePaper:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionControllerDelegate~1printInteractionController(_:cutLengthFor:)/title",
          "value": "printInteractionController:cutLengthForPaper:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionControllerDelegate~1printInteractionController(_:cutLengthFor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "printInteractionController:cutLengthForPaper:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinter~1CutterBehavior/title",
          "value": "UIPrinterCutterBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinter~1CutterBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrinterCutterBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrinter~1CutterBehavior/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrinterCutterBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionControllerDelegate~1printInteractionControllerDidPresentPrinterOptions(_:)/title",
          "value": "printInteractionControllerDidPresentPrinterOptions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionControllerDelegate~1printInteractionControllerDidPresentPrinterOptions(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "printInteractionControllerDidPresentPrinterOptions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionController~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionController~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionControllerDelegate~1printInteractionControllerDidDismissPrinterOptions(_:)/title",
          "value": "printInteractionControllerDidDismissPrinterOptions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionControllerDelegate~1printInteractionControllerDidDismissPrinterOptions(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "printInteractionControllerDidDismissPrinterOptions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionControllerDelegate~1printInteractionControllerDidFinishJob(_:)/title",
          "value": "printInteractionControllerDidFinishJob:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionControllerDelegate~1printInteractionControllerDidFinishJob(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "printInteractionControllerDidFinishJob:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionControllerDelegate~1printInteractionControllerWillStartJob(_:)/title",
          "value": "printInteractionControllerWillStartJob:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionControllerDelegate~1printInteractionControllerWillStartJob(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "printInteractionControllerWillStartJob:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionControllerDelegate/title",
          "value": "UIPrintInteractionControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintInteractionControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintInteractionControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintPaper/title",
          "value": "UIPrintPaper"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintPaper/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintPaper"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintPaper/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintPaper"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionControllerDelegate~1printInteractionControllerWillPresentPrinterOptions(_:)/title",
          "value": "printInteractionControllerWillPresentPrinterOptions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionControllerDelegate~1printInteractionControllerWillPresentPrinterOptions(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "printInteractionControllerWillPresentPrinterOptions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionControllerDelegate~1printInteractionControllerParentViewController(_:)/title",
          "value": "printInteractionControllerParentViewController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionControllerDelegate~1printInteractionControllerParentViewController(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "printInteractionControllerParentViewController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionControllerDelegate~1printInteractionControllerWillDismissPrinterOptions(_:)/title",
          "value": "printInteractionControllerWillDismissPrinterOptions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionControllerDelegate~1printInteractionControllerWillDismissPrinterOptions(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "printInteractionControllerWillDismissPrinterOptions:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiprintinteractioncontrollerdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiprintinteractioncontrollerdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
