{
  "abstract": [
    {
      "text": "The presentation styles that determine how a view shows an item provider’s data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIPreferredPresentationStyle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIPreferredPresentationStyle",
    "fragments": [
      {
        "kind": "identifier",
        "text": "UIPreferredPresentationStyle"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIPreferredPresentationStyle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "UIPreferredPresentationStyle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIPreferredPresentationStyle"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSInteger",
              "text": "NSInteger"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/ExpandedStatus": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpandedStatus"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/ExpandedStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ExpandedStatus"
        }
      ],
      "role": "symbol",
      "title": "UIAccessibility.ExpandedStatus",
      "type": "topic",
      "url": "/documentation/uikit/uiaccessibility/expandedstatus"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFocusItemDeferralMode": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFocusItemDeferralMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFocusItemDeferralMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFocusItemDeferralMode"
        }
      ],
      "role": "symbol",
      "title": "UIFocusItemDeferralMode",
      "type": "topic",
      "url": "/documentation/uikit/uifocusitemdeferralmode"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPreferredPresentationStyle": {
      "abstract": [
        {
          "text": "The presentation styles that determine how a view shows an item provider’s data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIPreferredPresentationStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPreferredPresentationStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIPreferredPresentationStyle",
      "type": "topic",
      "url": "/documentation/uikit/uipreferredpresentationstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPreferredPresentationStyle/UIPreferredPresentationStyleAttachment": {
      "abstract": [
        {
          "text": "A presentation style indicating that the item provider data should be presented as an attachment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIPreferredPresentationStyleAttachment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPreferredPresentationStyle/UIPreferredPresentationStyleAttachment",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIPreferredPresentationStyleAttachment",
      "type": "topic",
      "url": "/documentation/uikit/uipreferredpresentationstyle/uipreferredpresentationstyleattachment"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPreferredPresentationStyle/UIPreferredPresentationStyleInline": {
      "abstract": [
        {
          "text": "A presentation style indicating that the item provider data should be presented inline.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIPreferredPresentationStyleInline"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPreferredPresentationStyle/UIPreferredPresentationStyleInline",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIPreferredPresentationStyleInline",
      "type": "topic",
      "url": "/documentation/uikit/uipreferredpresentationstyle/uipreferredpresentationstyleinline"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPreferredPresentationStyle/UIPreferredPresentationStyleUnspecified": {
      "abstract": [
        {
          "text": "A presentation style indicating that no preferred style is specified.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIPreferredPresentationStyleUnspecified"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPreferredPresentationStyle/UIPreferredPresentationStyleUnspecified",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIPreferredPresentationStyleUnspecified",
      "type": "topic",
      "url": "/documentation/uikit/uipreferredpresentationstyle/uipreferredpresentationstyleunspecified"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentSize": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ComponentSize"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ComponentSize"
        }
      ],
      "role": "symbol",
      "title": "UITextFormattingViewController.ComponentSize",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/componentsize"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIAccessibility/ExpandedStatus",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentSize",
        "doc://com.apple.uikit/documentation/UIKit/UIFocusItemDeferralMode"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Presentation-styles",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPreferredPresentationStyle/UIPreferredPresentationStyleUnspecified",
        "doc://com.apple.uikit/documentation/UIKit/UIPreferredPresentationStyle/UIPreferredPresentationStyleInline",
        "doc://com.apple.uikit/documentation/UIKit/UIPreferredPresentationStyle/UIPreferredPresentationStyleAttachment"
      ],
      "title": "Presentation styles"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1ExpandedStatus/title",
          "value": "UIAccessibilityExpandedStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1ExpandedStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityExpandedStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccessibility~1ExpandedStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccessibilityExpandedStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentSize/title",
          "value": "UITextFormattingViewControllerComponentSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerComponentSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentSize/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerComponentSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusItemDeferralMode/title",
          "value": "UIFocusItemDeferralMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusItemDeferralMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFocusItemDeferralMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFocusItemDeferralMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFocusItemDeferralMode"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uipreferredpresentationstyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
