{
  "abstract": [
    {
      "text": "An abstract base class for print formatters, which are objects that lay out custom printable content that can cross page boundaries.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIPrintFormatter",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIPrintFormatter"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIPrintFormatter"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "4.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "UIPrintFormatter"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIPrintFormatter"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Given a print formatter, the printing system can automate the printing of the type of content associated with the print formatter. Examples of such content could be a web view, a mix of images and text, or a long text document. The UIKit framework provides several concrete subclasses of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ": ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UISimpleTextPrintFormatter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMarkupTextPrintFormatter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewPrintFormatter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can assign a single print formatter for a print job using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionController/printFormatter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " shared instance; or you can specify one or more print formatters that are associated with specific pages of a page renderer through the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintPageRenderer/addPrintFormatter(_:startingAtPageAt:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": "method of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintPageRenderer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". A page renderer is an instance of a custom subclass of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintPageRenderer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " that draws content for printing.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " publishes an interface that allows you to specify the starting page for a print job and the margins around the printed content; given that information plus the content, a print formatter computes the number of pages for the print job. The following image depicts the print-formatter properties, along with certain ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintPaper",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintPageRenderer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " properties, that define the layout of a multipage print job.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-1965769",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Third-party subclasses of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " aren’t recommended. If you have custom content to print, use a custom ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintPageRenderer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMarkupTextPrintFormatter": {
      "abstract": [
        {
          "text": "An object that lays out HTML text for a multipage print job.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIMarkupTextPrintFormatter"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMarkupTextPrintFormatter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIMarkupTextPrintFormatter"
        }
      ],
      "role": "symbol",
      "title": "UIMarkupTextPrintFormatter",
      "type": "topic",
      "url": "/documentation/uikit/uimarkuptextprintformatter"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter": {
      "abstract": [
        {
          "text": "An abstract base class for print formatters, which are objects that lay out custom printable content that can cross page boundaries.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPrintFormatter"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrintFormatter"
        }
      ],
      "role": "symbol",
      "title": "UIPrintFormatter",
      "type": "topic",
      "url": "/documentation/uikit/uiprintformatter"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/contentInsets": {
      "abstract": [
        {
          "text": "The distances the edges of content are inset from the printing rectangle.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "contentInsets"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@UIEdgeInsets",
          "text": "UIEdgeInsets"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/contentInsets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "contentInsets"
        }
      ],
      "role": "symbol",
      "title": "contentInsets",
      "type": "topic",
      "url": "/documentation/uikit/uiprintformatter/contentinsets"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/draw(in:forPageAt:)": {
      "abstract": [
        {
          "text": "Draws the portion of a print formatter’s content for the specified area of the specified page.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "draw"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "forPageAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/draw(in:forPageAt:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "drawInRect:forPageAtIndex:"
        }
      ],
      "role": "symbol",
      "title": "draw(in:forPageAt:)",
      "type": "topic",
      "url": "/documentation/uikit/uiprintformatter/draw(in:forpageat:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/maximumContentHeight": {
      "abstract": [
        {
          "text": "The maximum height of the content area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumContentHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/maximumContentHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumContentHeight"
        }
      ],
      "role": "symbol",
      "title": "maximumContentHeight",
      "type": "topic",
      "url": "/documentation/uikit/uiprintformatter/maximumcontentheight"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/maximumContentWidth": {
      "abstract": [
        {
          "text": "The maximum width of the content area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumContentWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/maximumContentWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumContentWidth"
        }
      ],
      "role": "symbol",
      "title": "maximumContentWidth",
      "type": "topic",
      "url": "/documentation/uikit/uiprintformatter/maximumcontentwidth"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/pageCount": {
      "abstract": [
        {
          "text": "The number of pages to print.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pageCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/pageCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pageCount"
        }
      ],
      "role": "symbol",
      "title": "pageCount",
      "type": "topic",
      "url": "/documentation/uikit/uiprintformatter/pagecount"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/perPageContentInsets": {
      "abstract": [
        {
          "text": "The margins for each printed page.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "perPageContentInsets"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@UIEdgeInsets",
          "text": "UIEdgeInsets"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/perPageContentInsets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "perPageContentInsets"
        }
      ],
      "role": "symbol",
      "title": "perPageContentInsets",
      "type": "topic",
      "url": "/documentation/uikit/uiprintformatter/perpagecontentinsets"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/printPageRenderer": {
      "abstract": [
        {
          "text": "Returns the page renderer for the print formatter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "printPageRenderer"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPrintPageRenderer",
          "text": "UIPrintPageRenderer"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/printPageRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printPageRenderer"
        }
      ],
      "role": "symbol",
      "title": "printPageRenderer",
      "type": "topic",
      "url": "/documentation/uikit/uiprintformatter/printpagerenderer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/rectForPage(at:)": {
      "abstract": [
        {
          "text": "Returns the area that encloses a specified page of content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rectForPage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/rectForPage(at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rectForPageAtIndex:"
        }
      ],
      "role": "symbol",
      "title": "rectForPage(at:)",
      "type": "topic",
      "url": "/documentation/uikit/uiprintformatter/rectforpage(at:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/removeFromPrintPageRenderer()": {
      "abstract": [
        {
          "text": "Removes the print formatter from the page renderer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "removeFromPrintPageRenderer"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/removeFromPrintPageRenderer()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "removeFromPrintPageRenderer"
        }
      ],
      "role": "symbol",
      "title": "removeFromPrintPageRenderer()",
      "type": "topic",
      "url": "/documentation/uikit/uiprintformatter/removefromprintpagerenderer()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/requiresMainThread": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the system executes the print formatter’s rendering operations on the main thread.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requiresMainThread"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/requiresMainThread",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requiresMainThread"
        }
      ],
      "role": "symbol",
      "title": "requiresMainThread",
      "type": "topic",
      "url": "/documentation/uikit/uiprintformatter/requiresmainthread"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/startPage": {
      "abstract": [
        {
          "text": "The index of the first page that the print formatter lays out.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startPage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/startPage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startPage"
        }
      ],
      "role": "symbol",
      "title": "startPage",
      "type": "topic",
      "url": "/documentation/uikit/uiprintformatter/startpage"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionController": {
      "abstract": [
        {
          "text": "A user interface that manages the printing of documents, images, and other printable content in iOS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPrintInteractionController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrintInteractionController"
        }
      ],
      "role": "symbol",
      "title": "UIPrintInteractionController",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinteractioncontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionController/printFormatter": {
      "abstract": [
        {
          "text": "An object that lays out the content of pages according to the kind of content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "printFormatter"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPrintFormatter",
          "text": "UIPrintFormatter"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintInteractionController/printFormatter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "printFormatter"
        }
      ],
      "role": "symbol",
      "title": "printFormatter",
      "type": "topic",
      "url": "/documentation/uikit/uiprintinteractioncontroller/printformatter"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintPageRenderer": {
      "abstract": [
        {
          "text": "An object that draws pages of content to print, with or without the assistance of print formatters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPrintPageRenderer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintPageRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrintPageRenderer"
        }
      ],
      "role": "symbol",
      "title": "UIPrintPageRenderer",
      "type": "topic",
      "url": "/documentation/uikit/uiprintpagerenderer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintPageRenderer/addPrintFormatter(_:startingAtPageAt:)": {
      "abstract": [
        {
          "text": "Adds a print formatter to the page renderer starting at the specified page.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addPrintFormatter"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPrintFormatter",
          "text": "UIPrintFormatter"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "startingAtPageAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintPageRenderer/addPrintFormatter(_:startingAtPageAt:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "addPrintFormatter:startingAtPageAtIndex:"
        }
      ],
      "role": "symbol",
      "title": "addPrintFormatter(_:startingAtPageAt:)",
      "type": "topic",
      "url": "/documentation/uikit/uiprintpagerenderer/addprintformatter(_:startingatpageat:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPrintPaper": {
      "abstract": [
        {
          "text": "The size of paper for a print job and the rectangular area that the content prints within.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPrintPaper"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPrintPaper",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPrintPaper"
        }
      ],
      "role": "symbol",
      "title": "UIPrintPaper",
      "type": "topic",
      "url": "/documentation/uikit/uiprintpaper"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISimpleTextPrintFormatter": {
      "abstract": [
        {
          "text": "An object that lays out plain text for printing, possibly over multiple pages.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISimpleTextPrintFormatter"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISimpleTextPrintFormatter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISimpleTextPrintFormatter"
        }
      ],
      "role": "symbol",
      "title": "UISimpleTextPrintFormatter",
      "type": "topic",
      "url": "/documentation/uikit/uisimpletextprintformatter"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewPrintFormatter": {
      "abstract": [
        {
          "text": "An object that lays out the drawn content of a view for printing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewPrintFormatter"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewPrintFormatter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewPrintFormatter"
        }
      ],
      "role": "symbol",
      "title": "UIViewPrintFormatter",
      "type": "topic",
      "url": "/documentation/uikit/uiviewprintformatter"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "media-1965769": {
      "alt": "Diagram that shows the layout of printed content.",
      "identifier": "media-1965769",
      "type": "image",
      "variants": [
        {
          "traits": [
            "1x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/5af87d7015f12142813615b85252c418/media-1965769.jpg"
        }
      ]
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIMarkupTextPrintFormatter",
        "doc://com.apple.uikit/documentation/UIKit/UISimpleTextPrintFormatter",
        "doc://com.apple.uikit/documentation/UIKit/UIViewPrintFormatter"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Formatters",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIViewPrintFormatter",
        "doc://com.apple.uikit/documentation/UIKit/UISimpleTextPrintFormatter",
        "doc://com.apple.uikit/documentation/UIKit/UIMarkupTextPrintFormatter"
      ],
      "title": "Formatters"
    }
  ],
  "topicSections": [
    {
      "anchor": "Laying-out-the-content",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/perPageContentInsets",
        "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/maximumContentHeight",
        "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/maximumContentWidth",
        "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/contentInsets"
      ],
      "title": "Laying out the content"
    },
    {
      "anchor": "Managing-pagination",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/startPage",
        "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/pageCount"
      ],
      "title": "Managing pagination"
    },
    {
      "anchor": "Drawing-the-content",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/draw(in:forPageAt:)",
        "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/rectForPage(at:)"
      ],
      "title": "Drawing the content"
    },
    {
      "anchor": "Communicating-with-the-page-renderer",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/removeFromPrintPageRenderer()",
        "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/printPageRenderer"
      ],
      "title": "Communicating with the page renderer"
    },
    {
      "anchor": "Requiring-operations-to-take-place-on-the-main-thread",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/requiresMainThread"
      ],
      "title": "Requiring operations to take place on the main thread"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "4.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIPrintFormatter"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Laying-out-the-content",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/perPageContentInsets",
                "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/maximumContentHeight",
                "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/maximumContentWidth",
                "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/contentInsets"
              ],
              "title": "Laying out the content"
            },
            {
              "anchor": "Managing-pagination",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/startPage",
                "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/pageCount"
              ],
              "title": "Managing pagination"
            },
            {
              "anchor": "Drawing-the-content",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/draw(in:forPageAt:)",
                "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/rectForPage(at:)"
              ],
              "title": "Drawing the content"
            },
            {
              "anchor": "Communicating-with-the-page-renderer",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/removeFromPrintPageRenderer()",
                "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/printPageRenderer"
              ],
              "title": "Communicating with the page renderer"
            },
            {
              "anchor": "Requiring-operations-to-take-place-on-the-main-thread",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPrintFormatter/requiresMainThread"
              ],
              "title": "Requiring operations to take place on the main thread"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIMarkupTextPrintFormatter",
                "doc://com.apple.uikit/documentation/UIKit/UISimpleTextPrintFormatter",
                "doc://com.apple.uikit/documentation/UIKit/UIViewPrintFormatter"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Formatters",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIViewPrintFormatter",
                "doc://com.apple.uikit/documentation/UIKit/UISimpleTextPrintFormatter",
                "doc://com.apple.uikit/documentation/UIKit/UIMarkupTextPrintFormatter"
              ],
              "title": "Formatters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIPrintFormatter"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintFormatter~1perPageContentInsets/title",
          "value": "perPageContentInsets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintFormatter~1perPageContentInsets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "perPageContentInsets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISimpleTextPrintFormatter/title",
          "value": "UISimpleTextPrintFormatter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISimpleTextPrintFormatter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISimpleTextPrintFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISimpleTextPrintFormatter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISimpleTextPrintFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionController/title",
          "value": "UIPrintInteractionController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintInteractionController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintInteractionController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintFormatter~1startPage/title",
          "value": "startPage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintFormatter~1startPage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "startPage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintFormatter~1draw(in:forPageAt:)/title",
          "value": "drawInRect:forPageAtIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintFormatter~1draw(in:forPageAt:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "drawInRect:forPageAtIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintFormatter~1requiresMainThread/title",
          "value": "requiresMainThread"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintFormatter~1requiresMainThread/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "requiresMainThread"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewPrintFormatter/title",
          "value": "UIViewPrintFormatter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewPrintFormatter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewPrintFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewPrintFormatter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewPrintFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintFormatter~1rectForPage(at:)/title",
          "value": "rectForPageAtIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintFormatter~1rectForPage(at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rectForPageAtIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintPaper/title",
          "value": "UIPrintPaper"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintPaper/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintPaper"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintPaper/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintPaper"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintFormatter~1maximumContentHeight/title",
          "value": "maximumContentHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintFormatter~1maximumContentHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumContentHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintFormatter~1pageCount/title",
          "value": "pageCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintFormatter~1pageCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pageCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintPageRenderer/title",
          "value": "UIPrintPageRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintPageRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintPageRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintPageRenderer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintPageRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintFormatter~1removeFromPrintPageRenderer()/title",
          "value": "removeFromPrintPageRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintFormatter~1removeFromPrintPageRenderer()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "removeFromPrintPageRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintFormatter~1printPageRenderer/title",
          "value": "printPageRenderer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintFormatter~1printPageRenderer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "printPageRenderer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintFormatter/title",
          "value": "UIPrintFormatter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintFormatter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintFormatter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPrintFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintFormatter~1contentInsets/title",
          "value": "contentInsets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintFormatter~1contentInsets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "contentInsets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionController~1printFormatter/title",
          "value": "printFormatter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintInteractionController~1printFormatter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "printFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintPageRenderer~1addPrintFormatter(_:startingAtPageAt:)/title",
          "value": "addPrintFormatter:startingAtPageAtIndex:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintPageRenderer~1addPrintFormatter(_:startingAtPageAt:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "addPrintFormatter:startingAtPageAtIndex:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintFormatter~1maximumContentWidth/title",
          "value": "maximumContentWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPrintFormatter~1maximumContentWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumContentWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMarkupTextPrintFormatter/title",
          "value": "UIMarkupTextPrintFormatter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMarkupTextPrintFormatter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMarkupTextPrintFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMarkupTextPrintFormatter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMarkupTextPrintFormatter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiprintformatter"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiprintformatter"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
