{"metadata":{"roleHeading":"Class","title":"UIRegion","modules":[{"name":"UIKit"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIRegion","kind":"identifier"}],"navigatorTitle":[{"text":"UIRegion","kind":"identifier"}],"symbolKind":"class","externalID":"c:objc(cs)UIRegion","role":"symbol","platforms":[{"beta":false,"unavailable":false,"introducedAt":"9.0","deprecated":false,"name":"iOS"},{"beta":false,"unavailable":false,"introducedAt":"9.0","deprecated":false,"name":"iPadOS"},{"beta":false,"unavailable":false,"introducedAt":"13.1","deprecated":false,"name":"Mac Catalyst"},{"beta":false,"unavailable":false,"introducedAt":"9.0","deprecated":false,"name":"tvOS"},{"beta":false,"unavailable":false,"introducedAt":"1.0","deprecated":false,"name":"visionOS"}]},"topicSections":[{"anchor":"Creating-and-initializing-regions","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIRegion/infinite","doc://com.apple.uikit/documentation/UIKit/UIRegion/init(size:)","doc://com.apple.uikit/documentation/UIKit/UIRegion/init(radius:)"],"title":"Creating and initializing regions"},{"anchor":"Creating-complex-regions","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIRegion/inverse()","doc://com.apple.uikit/documentation/UIKit/UIRegion/byDifference(from:)","doc://com.apple.uikit/documentation/UIKit/UIRegion/byIntersection(with:)","doc://com.apple.uikit/documentation/UIKit/UIRegion/byUnion(with:)"],"title":"Creating complex regions"},{"anchor":"Interacting-with-a-region","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIRegion/contains(_:)"],"title":"Interacting with a region"}],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIRegion","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"abstract":[{"type":"text","text":"A shape for use in UIKit Dynamics."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIRegion","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"When creating animations, you use regions to define the effective area of a field behavior such as a magnetic or gravitational force. Most regions are rectangular or elliptical in shape, but you can use the methods of this class to create more complex shapes by adding, subtracting, and intersecting other regions.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"When creating a new region, you specify only the size of the corresponding rectangle or circle. The origin of a newly created region is at the center of the specified area, and any mathematical manipulations you make to the region occur relative to that origin point."}]}],"kind":"content"}],"sections":[],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/c:objc(cs)NSObject"],"title":"Inherits From"},{"type":"conformsTo","kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/s:s7CVarArgP","doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/c:objc(pl)NSCoding","doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","doc://com.externally.resolved.symbol/c:objc(pl)NSObject","doc://com.externally.resolved.symbol/s:s8SendableP"],"title":"Conforms To"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uiregion"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uiregion"]}],"references":{"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIRegion/byIntersection(with:)":{"abstract":[{"text":"Returns a new region containing only the area occupied by both the specified region and current region.","type":"text"}],"kind":"symbol","title":"byIntersection(with:)","navigatorTitle":[{"text":"regionByIntersectionWithRegion:","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIRegion/byIntersection(with:)","url":"/documentation/uikit/uiregion/byintersection(with:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"byIntersection"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIRegion","text":"UIRegion"},{"text":") -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIRegion/byDifference(from:)":{"abstract":[{"text":"Returns a new region created by subtracting the specified region from the current region.","type":"text"}],"role":"symbol","url":"/documentation/uikit/uiregion/bydifference(from:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"regionByDifferenceFromRegion:"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIRegion/byDifference(from:)","title":"byDifference(from:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"byDifference","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIRegion","kind":"typeIdentifier","text":"UIRegion"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}]},"doc://com.apple.uikit/documentation/UIKit/UIRegion/infinite":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIRegion/infinite","url":"/documentation/uikit/uiregion/infinite","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"infinite","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIRegion","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIRegion"}],"navigatorTitle":[{"text":"infiniteRegion","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Returns the region that encloses all points."}],"title":"infinite","role":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIRegion/init(size:)":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIRegion/init(size:)","url":"/documentation/uikit/uiregion/init(size:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithSize:","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Initializes and returns a rectangular region of the specified size."}],"title":"init(size:)","role":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIRegion/contains(_:)":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIRegion/contains(_:)","url":"/documentation/uikit/uiregion/contains(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contains","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGPoint","preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"containsPoint:","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Returns a Boolean indicating whether the specified point is inside of the current region."}],"title":"contains(_:)","role":"symbol","type":"topic"},"doc://com.externally.resolved.symbol/c:objc(pl)NSCoding":{"url":"/documentation/foundation/nscoding","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCoding","role":"symbol","fragments":[{"kind":"text","text":"protocol "},{"kind":"identifier","text":"NSCoding"}],"type":"topic","title":"NSCoding","kind":"symbol","abstract":[{"text":"A protocol that enables an object to be encoded and decoded for archiving and distribution.","type":"text"}]},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"title":"NSObjectProtocol","type":"topic","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","role":"symbol","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"kind":"symbol","url":"/documentation/objectivec/nsobjectprotocol"},"doc://com.externally.resolved.symbol/s:s7CVarArgP":{"abstract":[{"type":"text","text":"A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVarArg"}],"identifier":"doc://com.externally.resolved.symbol/s:s7CVarArgP","type":"topic","title":"CVarArg","kind":"symbol","role":"symbol","url":"/documentation/Swift/CVarArg"},"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP":{"identifier":"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","kind":"symbol","type":"topic","title":"CustomDebugStringConvertible","url":"/documentation/Swift/CustomDebugStringConvertible","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomDebugStringConvertible"}],"role":"symbol","abstract":[{"type":"text","text":"A type with a customized textual representation suitable for debugging purposes."}]},"doc://com.apple.uikit/documentation/UIKit/UIRegion/inverse()":{"abstract":[{"type":"text","text":"Returns a new region that’s the mathematical inverse of the current region."}],"role":"symbol","url":"/documentation/uikit/uiregion/inverse()","type":"topic","navigatorTitle":[{"kind":"identifier","text":"inverseRegion"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIRegion/inverse()","title":"inverse()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"inverse"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Self"}]},"doc://com.apple.uikit/documentation/UIKit/UIRegion/byUnion(with:)":{"abstract":[{"text":"Returns a new region containing the combined areas of the specified region and the current region.","type":"text"}],"role":"symbol","url":"/documentation/uikit/uiregion/byunion(with:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"regionByUnionWithRegion:"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIRegion/byUnion(with:)","title":"byUnion(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"byUnion","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIRegion","kind":"typeIdentifier","text":"UIRegion"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}]},"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying":{"kind":"symbol","abstract":[{"text":"A protocol that objects adopt to provide functional copies of themselves.","type":"text"}],"url":"/documentation/foundation/nscopying","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSCopying","kind":"identifier"}],"title":"NSCopying","type":"topic","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","role":"symbol"},"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP":{"identifier":"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","kind":"symbol","type":"topic","title":"CustomStringConvertible","url":"/documentation/Swift/CustomStringConvertible","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomStringConvertible"}],"role":"symbol","abstract":[{"text":"A type with a customized textual representation.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.externally.resolved.symbol/s:s8SendableP":{"abstract":[{"type":"text","text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races."}],"url":"/documentation/Swift/Sendable","identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}],"role":"symbol","title":"Sendable","type":"topic","kind":"symbol"},"doc://com.externally.resolved.symbol/c:objc(cs)NSObject":{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSObject","role":"symbol","kind":"symbol","url":"/documentation/objectivec/nsobject","title":"NSObject","type":"topic","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSObject"}],"abstract":[{"text":"The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.","type":"text"}]},"doc://com.externally.resolved.symbol/s:SH":{"abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}],"url":"/documentation/Swift/Hashable","identifier":"doc://com.externally.resolved.symbol/s:SH","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hashable","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SQ","text":"Equatable","kind":"typeIdentifier"}],"role":"symbol","title":"Hashable","type":"topic","kind":"symbol"},"doc://com.externally.resolved.symbol/s:SQ":{"abstract":[{"type":"text","text":"A type that can be compared for value equality."}],"url":"/documentation/Swift/Equatable","identifier":"doc://com.externally.resolved.symbol/s:SQ","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"role":"symbol","title":"Equatable","type":"topic","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIRegion":{"abstract":[{"text":"A shape for use in UIKit Dynamics.","type":"text"}],"role":"symbol","url":"/documentation/uikit/uiregion","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UIRegion"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIRegion","title":"UIRegion","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UIRegion"}]},"doc://com.apple.uikit/documentation/UIKit/UIRegion/init(radius:)":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIRegion/init(radius:)","url":"/documentation/uikit/uiregion/init(radius:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"radius","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithRadius:","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Initializes and returns a region with a circular shape of the specified radius."}],"title":"init(radius:)","role":"symbol","type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"beta":false,"name":"iOS","introducedAt":"9.0","deprecated":false,"unavailable":false},{"beta":false,"name":"iPadOS","introducedAt":"9.0","deprecated":false,"unavailable":false},{"beta":false,"name":"Mac Catalyst","introducedAt":"13.1","deprecated":false,"unavailable":false},{"beta":false,"name":"tvOS","introducedAt":"9.0","deprecated":false,"unavailable":false},{"beta":false,"name":"visionOS","introducedAt":"1.0","deprecated":false,"unavailable":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Class","path":"/metadata/roleHeading","op":"replace"},{"value":"UIRegion","path":"/metadata/title","op":"replace"},{"value":"class","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"UIRegion"}],"path":"/metadata/fragments","op":"replace"},{"value":[{"text":"UIRegion","kind":"identifier"}],"path":"/metadata/navigatorTitle","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"path":"/hierarchy","op":"replace"},{"value":[{"anchor":"Creating-and-initializing-regions","title":"Creating and initializing regions","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIRegion/infinite","doc://com.apple.uikit/documentation/UIKit/UIRegion/init(size:)","doc://com.apple.uikit/documentation/UIKit/UIRegion/init(radius:)"]},{"anchor":"Creating-complex-regions","title":"Creating complex regions","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIRegion/inverse()","doc://com.apple.uikit/documentation/UIKit/UIRegion/byDifference(from:)","doc://com.apple.uikit/documentation/UIKit/UIRegion/byIntersection(with:)","doc://com.apple.uikit/documentation/UIKit/UIRegion/byUnion(with:)"]},{"anchor":"Interacting-with-a-region","title":"Interacting with a region","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIRegion/contains(_:)"]}],"path":"/topicSections","op":"replace"},{"value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc://com.externally.resolved.symbol/c:objc(cs)NSObject"],"kind":"relationships"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc://com.externally.resolved.symbol/c:objc(pl)NSCoding","doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"],"kind":"relationships"}],"path":"/relationshipsSections","op":"replace"},{"value":null,"path":"/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIRegion","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","value":"regionByIntersectionWithRegion:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRegion~1byIntersection(with:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"regionByIntersectionWithRegion:"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRegion~1byIntersection(with:)/fragments"},{"op":"replace","value":"regionByDifferenceFromRegion:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRegion~1byDifference(from:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"regionByDifferenceFromRegion:"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRegion~1byDifference(from:)/fragments"},{"op":"replace","value":"infiniteRegion","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRegion~1infinite/title"},{"op":"replace","value":[{"kind":"identifier","text":"infiniteRegion"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRegion~1infinite/fragments"},{"op":"replace","value":"initWithSize:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRegion~1init(size:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSize:"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRegion~1init(size:)/fragments"},{"op":"replace","value":"containsPoint:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRegion~1contains(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"containsPoint:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRegion~1contains(_:)/fragments"},{"op":"replace","value":"NSObject","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title"},{"op":"replace","value":"inverseRegion","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRegion~1inverse()/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"inverseRegion","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRegion~1inverse()/fragments"},{"value":"regionByUnionWithRegion:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRegion~1byUnion(with:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"regionByUnionWithRegion:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRegion~1byUnion(with:)/fragments"},{"value":"UIRegion","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRegion/title"},{"value":[{"text":"UIRegion","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRegion/fragments"},{"value":[{"kind":"identifier","text":"UIRegion"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRegion/navigatorTitle"},{"value":"initWithRadius:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRegion~1init(radius:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithRadius:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRegion~1init(radius:)/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}