{
  "abstract": [
    {
      "text": "Constants that specify the text string that displays in the Return key of a keyboard.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIReturnKeyType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIReturnKeyType"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIReturnKeyType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "UIReturnKeyType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIReturnKeyType"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use these constants with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/returnKeyType",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardAppearance": {
      "abstract": [
        {
          "text": "Constants that specify the appearance of the keyboard for a text-based view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIKeyboardAppearance"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardAppearance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardAppearance"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardAppearance",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardappearance"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType": {
      "abstract": [
        {
          "text": "Constants that specify the type of keyboard to display for a text-based view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIKeyboardType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyboardType"
        }
      ],
      "role": "symbol",
      "title": "UIKeyboardType",
      "type": "topic",
      "url": "/documentation/uikit/uikeyboardtype"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType": {
      "abstract": [
        {
          "text": "Constants that specify the text string that displays in the Return key of a keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIReturnKeyType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIReturnKeyType"
        }
      ],
      "role": "symbol",
      "title": "UIReturnKeyType",
      "type": "topic",
      "url": "/documentation/uikit/uireturnkeytype"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/continue": {
      "abstract": [
        {
          "text": "Specifies that the visible title of the Return key is ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Continue",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`continue`"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/continue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIReturnKeyContinue"
        }
      ],
      "role": "symbol",
      "title": "UIReturnKeyType.continue",
      "type": "topic",
      "url": "/documentation/uikit/uireturnkeytype/continue"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/default": {
      "abstract": [
        {
          "text": "Specifies that the visible title of the Return key is ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "return",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIReturnKeyDefault"
        }
      ],
      "role": "symbol",
      "title": "UIReturnKeyType.default",
      "type": "topic",
      "url": "/documentation/uikit/uireturnkeytype/default"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/done": {
      "abstract": [
        {
          "text": "Specifies that the visible title of the Return key is ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Done",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "done"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/done",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIReturnKeyDone"
        }
      ],
      "role": "symbol",
      "title": "UIReturnKeyType.done",
      "type": "topic",
      "url": "/documentation/uikit/uireturnkeytype/done"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/emergencyCall": {
      "abstract": [
        {
          "text": "Specifies that the visible title of the Return key is ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Emergency Call",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "emergencyCall"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/emergencyCall",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIReturnKeyEmergencyCall"
        }
      ],
      "role": "symbol",
      "title": "UIReturnKeyType.emergencyCall",
      "type": "topic",
      "url": "/documentation/uikit/uireturnkeytype/emergencycall"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/go": {
      "abstract": [
        {
          "text": "Specifies that the visible title of the Return key is ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Go",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "go"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/go",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIReturnKeyGo"
        }
      ],
      "role": "symbol",
      "title": "UIReturnKeyType.go",
      "type": "topic",
      "url": "/documentation/uikit/uireturnkeytype/go"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/google": {
      "abstract": [
        {
          "text": "Specifies that the visible title of the Return key is ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Google",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "google"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/google",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIReturnKeyGoogle"
        }
      ],
      "role": "symbol",
      "title": "UIReturnKeyType.google",
      "type": "topic",
      "url": "/documentation/uikit/uireturnkeytype/google"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/uireturnkeytype/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/join": {
      "abstract": [
        {
          "text": "Specifies that the visible title of the Return key is ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Join",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "join"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/join",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIReturnKeyJoin"
        }
      ],
      "role": "symbol",
      "title": "UIReturnKeyType.join",
      "type": "topic",
      "url": "/documentation/uikit/uireturnkeytype/join"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/next": {
      "abstract": [
        {
          "text": "Specifies that the visible title of the Return key is ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Next",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "next"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/next",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIReturnKeyNext"
        }
      ],
      "role": "symbol",
      "title": "UIReturnKeyType.next",
      "type": "topic",
      "url": "/documentation/uikit/uireturnkeytype/next"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/route": {
      "abstract": [
        {
          "text": "Specifies that the visible title of the Return key is ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Route",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "route"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/route",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIReturnKeyRoute"
        }
      ],
      "role": "symbol",
      "title": "UIReturnKeyType.route",
      "type": "topic",
      "url": "/documentation/uikit/uireturnkeytype/route"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/search": {
      "abstract": [
        {
          "text": "Specifies that the visible title of the Return key is ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Search",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "search"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/search",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIReturnKeySearch"
        }
      ],
      "role": "symbol",
      "title": "UIReturnKeyType.search",
      "type": "topic",
      "url": "/documentation/uikit/uireturnkeytype/search"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/send": {
      "abstract": [
        {
          "text": "Specifies that the visible title of the Return key is ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Send",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "send"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/send",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIReturnKeySend"
        }
      ],
      "role": "symbol",
      "title": "UIReturnKeyType.send",
      "type": "topic",
      "url": "/documentation/uikit/uireturnkeytype/send"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/yahoo": {
      "abstract": [
        {
          "text": "Specifies that the visible title of the Return key is ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Yahoo",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "yahoo"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/yahoo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIReturnKeyYahoo"
        }
      ],
      "role": "symbol",
      "title": "UIReturnKeyType.yahoo",
      "type": "topic",
      "url": "/documentation/uikit/uireturnkeytype/yahoo"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextContentType": {
      "abstract": [
        {
          "text": "Constants that identify the semantic meaning for a text-entry area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextContentType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextContentType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextContentType"
        }
      ],
      "role": "symbol",
      "title": "UITextContentType",
      "type": "topic",
      "url": "/documentation/uikit/uitextcontenttype"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/keyboardAppearance": {
      "abstract": [
        {
          "text": "The appearance style of the keyboard for the text object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardAppearance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIKeyboardAppearance",
          "text": "UIKeyboardAppearance"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/keyboardAppearance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "keyboardAppearance"
        }
      ],
      "role": "symbol",
      "title": "keyboardAppearance",
      "type": "topic",
      "url": "/documentation/uikit/uitextinputtraits/keyboardappearance"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/keyboardType": {
      "abstract": [
        {
          "text": "The keyboard type for the text object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyboardType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIKeyboardType",
          "text": "UIKeyboardType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/keyboardType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "keyboardType"
        }
      ],
      "role": "symbol",
      "title": "keyboardType",
      "type": "topic",
      "url": "/documentation/uikit/uitextinputtraits/keyboardtype"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/returnKeyType": {
      "abstract": [
        {
          "text": "The visible title of the Return key.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "returnKeyType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIReturnKeyType",
          "text": "UIReturnKeyType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/returnKeyType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "returnKeyType"
        }
      ],
      "role": "symbol",
      "title": "returnKeyType",
      "type": "topic",
      "url": "/documentation/uikit/uitextinputtraits/returnkeytype"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/textContentType": {
      "abstract": [
        {
          "text": "The semantic meaning for a text input area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textContentType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UITextContentType",
          "text": "UITextContentType"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/textContentType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textContentType"
        }
      ],
      "role": "symbol",
      "title": "textContentType",
      "type": "topic",
      "url": "/documentation/uikit/uitextinputtraits/textcontenttype"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-keyboard-appearance",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/keyboardType",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType",
        "doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/keyboardAppearance",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyboardAppearance",
        "doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/returnKeyType",
        "doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/textContentType",
        "doc://com.apple.uikit/documentation/UIKit/UITextContentType"
      ],
      "title": "Configuring the keyboard appearance"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/default",
        "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/go",
        "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/google",
        "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/join",
        "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/next",
        "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/route",
        "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/search",
        "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/send",
        "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/yahoo",
        "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/done",
        "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/emergencyCall",
        "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/continue"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIReturnKeyType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIReturnKeyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIReturnKeyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/default",
                "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/go",
                "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/google",
                "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/join",
                "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/next",
                "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/route",
                "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/search",
                "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/send",
                "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/yahoo",
                "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/done",
                "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/emergencyCall",
                "doc://com.apple.uikit/documentation/UIKit/UIReturnKeyType/continue"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-keyboard-appearance",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/keyboardType",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardType",
                "doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/keyboardAppearance",
                "doc://com.apple.uikit/documentation/UIKit/UIKeyboardAppearance",
                "doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/returnKeyType",
                "doc://com.apple.uikit/documentation/UIKit/UITextInputTraits/textContentType",
                "doc://com.apple.uikit/documentation/UIKit/UITextContentType"
              ],
              "title": "Configuring the keyboard appearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIReturnKeyType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1next/title",
          "value": "UIReturnKeyNext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1next/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIReturnKeyNext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardAppearance/title",
          "value": "UIKeyboardAppearance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardAppearance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardAppearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardAppearance/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardAppearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType/title",
          "value": "UIKeyboardType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyboardType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyboardType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1go/title",
          "value": "UIReturnKeyGo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1go/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIReturnKeyGo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1yahoo/title",
          "value": "UIReturnKeyYahoo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1yahoo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIReturnKeyYahoo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextContentType/title",
          "value": "UITextContentType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextContentType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextContentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextContentType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextContentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1send/title",
          "value": "UIReturnKeySend"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1send/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIReturnKeySend"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType/title",
          "value": "UIReturnKeyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIReturnKeyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIReturnKeyType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1google/title",
          "value": "UIReturnKeyGoogle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1google/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIReturnKeyGoogle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1route/title",
          "value": "UIReturnKeyRoute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1route/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIReturnKeyRoute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1continue/title",
          "value": "UIReturnKeyContinue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1continue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIReturnKeyContinue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1emergencyCall/title",
          "value": "UIReturnKeyEmergencyCall"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1emergencyCall/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIReturnKeyEmergencyCall"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputTraits~1keyboardAppearance/title",
          "value": "keyboardAppearance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputTraits~1keyboardAppearance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "keyboardAppearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputTraits~1textContentType/title",
          "value": "textContentType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputTraits~1textContentType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "textContentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1done/title",
          "value": "UIReturnKeyDone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1done/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIReturnKeyDone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1search/title",
          "value": "UIReturnKeySearch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1search/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIReturnKeySearch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1join/title",
          "value": "UIReturnKeyJoin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1join/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIReturnKeyJoin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputTraits~1keyboardType/title",
          "value": "keyboardType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputTraits~1keyboardType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "keyboardType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1default/title",
          "value": "UIReturnKeyDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIReturnKeyType~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIReturnKeyDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputTraits~1returnKeyType/title",
          "value": "returnKeyType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputTraits~1returnKeyType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "returnKeyType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uireturnkeytype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uireturnkeytype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
