{
  "abstract": [
    {
      "text": "Constants indicating the types of notifications the app may display to the user.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIRemoteNotificationType",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIRemoteNotificationType"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIRemoteNotificationType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "8.0",
        "introducedAt": "3.0",
        "message": "Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead.",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "8.0",
        "introducedAt": "3.0",
        "message": "Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead.",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead.",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "UIRemoteNotificationType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIRemoteNotificationType"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "One or more of the values in the ",
              "type": "text"
            },
            {
              "code": "UIRemoteNotificationType",
              "type": "codeVoice"
            },
            {
              "text": " bit mask are passed to iOS as the argument of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/registerForRemoteNotifications(matching:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method. Thereafter, iOS filters notifications for the app based on these values. You can always get the current notification types by calling the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/enabledRemoteNotificationTypes()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/beginIgnoringInteractionEvents()": {
      "abstract": [
        {
          "text": "Tells the receiver to suspend the handling of touch-related events.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginIgnoringInteractionEvents"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/beginIgnoringInteractionEvents()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beginIgnoringInteractionEvents"
        }
      ],
      "role": "symbol",
      "title": "beginIgnoringInteractionEvents()",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/beginignoringinteractionevents()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/cancelAllLocalNotifications()": {
      "abstract": [
        {
          "text": "Cancels the delivery of all scheduled local notifications.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelAllLocalNotifications"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/cancelAllLocalNotifications()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cancelAllLocalNotifications"
        }
      ],
      "role": "symbol",
      "title": "cancelAllLocalNotifications()",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/cancelalllocalnotifications()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/cancelLocalNotification(_:)": {
      "abstract": [
        {
          "text": "Cancels the delivery of the specified scheduled local notification.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelLocalNotification"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UILocalNotification",
          "text": "UILocalNotification"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/cancelLocalNotification(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cancelLocalNotification:"
        }
      ],
      "role": "symbol",
      "title": "cancelLocalNotification(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/cancellocalnotification(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/clearKeepAliveTimeout()": {
      "abstract": [
        {
          "text": "Removes a previously installed periodic handler block.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clearKeepAliveTimeout"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/clearKeepAliveTimeout()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clearKeepAliveTimeout"
        }
      ],
      "role": "symbol",
      "title": "clearKeepAliveTimeout()",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/clearkeepalivetimeout()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/enabledRemoteNotificationTypes()": {
      "abstract": [
        {
          "text": "Returns the types of notifications the app accepts.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "enabledRemoteNotificationTypes"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIRemoteNotificationType",
          "text": "UIRemoteNotificationType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/enabledRemoteNotificationTypes()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "enabledRemoteNotificationTypes"
        }
      ],
      "role": "symbol",
      "title": "enabledRemoteNotificationTypes()",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/enabledremotenotificationtypes()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/endIgnoringInteractionEvents()": {
      "abstract": [
        {
          "text": "Tells the receiver to resume the handling of touch-related events.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "endIgnoringInteractionEvents"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/endIgnoringInteractionEvents()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "endIgnoringInteractionEvents"
        }
      ],
      "role": "symbol",
      "title": "endIgnoringInteractionEvents()",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/endignoringinteractionevents()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/presentLocalNotificationNow(_:)": {
      "abstract": [
        {
          "text": "Presents a local notification immediately.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "presentLocalNotificationNow"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UILocalNotification",
          "text": "UILocalNotification"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/presentLocalNotificationNow(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "presentLocalNotificationNow:"
        }
      ],
      "role": "symbol",
      "title": "presentLocalNotificationNow(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/presentlocalnotificationnow(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/registerForRemoteNotifications(matching:)": {
      "abstract": [
        {
          "text": "Register to receive remote notifications of the specified types via Apple Push Notification service.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "registerForRemoteNotifications"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "matching"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIRemoteNotificationType",
          "text": "UIRemoteNotificationType"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/registerForRemoteNotifications(matching:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "registerForRemoteNotificationTypes:"
        }
      ],
      "role": "symbol",
      "title": "registerForRemoteNotifications(matching:)",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/registerforremotenotifications(matching:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/registerUserNotificationSettings(_:)": {
      "abstract": [
        {
          "text": "Registers your preferred options for notifying the user.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "registerUserNotificationSettings"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIUserNotificationSettings",
          "text": "UIUserNotificationSettings"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/registerUserNotificationSettings(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "registerUserNotificationSettings:"
        }
      ],
      "role": "symbol",
      "title": "registerUserNotificationSettings(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/registerusernotificationsettings(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/requestSceneSessionActivation(_:userActivity:options:errorHandler:)": {
      "abstract": [
        {
          "text": "Asks the system to activate an existing scene, or create a new scene and associate it with your app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "requestSceneSessionActivation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISceneSession",
          "text": "UISceneSession"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "userActivity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUserActivity",
          "text": "NSUserActivity"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIScene",
          "text": "UIScene"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISceneActivationRequestOptions",
          "text": "ActivationRequestOptions"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "errorHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/requestSceneSessionActivation(_:userActivity:options:errorHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "requestSceneSessionActivation:userActivity:options:errorHandler:"
        }
      ],
      "role": "symbol",
      "title": "requestSceneSessionActivation(_:userActivity:options:errorHandler:)",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/requestscenesessionactivation(_:useractivity:options:errorhandler:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/scheduleLocalNotification(_:)": {
      "abstract": [
        {
          "text": "Schedules a local notification for delivery at its encapsulated date and time.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scheduleLocalNotification"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UILocalNotification",
          "text": "UILocalNotification"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/scheduleLocalNotification(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scheduleLocalNotification:"
        }
      ],
      "role": "symbol",
      "title": "scheduleLocalNotification(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/schedulelocalnotification(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/setKeepAliveTimeout(_:handler:)": {
      "abstract": [
        {
          "text": "Configures a periodic handler for VoIP apps in older versions of iOS.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setKeepAliveTimeout"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "handler"
        },
        {
          "kind": "text",
          "text": ": (() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/setKeepAliveTimeout(_:handler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setKeepAliveTimeout:handler:"
        }
      ],
      "role": "symbol",
      "title": "setKeepAliveTimeout(_:handler:)",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/setkeepalivetimeout(_:handler:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/setMinimumBackgroundFetchInterval(_:)": {
      "abstract": [
        {
          "text": "Specifies the minimum amount of time that must elapse between background fetch operations.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setMinimumBackgroundFetchInterval"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/setMinimumBackgroundFetchInterval(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setMinimumBackgroundFetchInterval:"
        }
      ],
      "role": "symbol",
      "title": "setMinimumBackgroundFetchInterval(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/setminimumbackgroundfetchinterval(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/setStatusBarHidden(_:with:)": {
      "abstract": [
        {
          "text": "Hides or shows the status bar, optionally animating the transition.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setStatusBarHidden"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIStatusBarAnimation",
          "text": "UIStatusBarAnimation"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/setStatusBarHidden(_:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setStatusBarHidden:withAnimation:"
        }
      ],
      "role": "symbol",
      "title": "setStatusBarHidden(_:with:)",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/setstatusbarhidden(_:with:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/setStatusBarHidden:animated:": {
      "abstract": [
        {
          "text": "Hides or shows the status bar, optionally animating the transition.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "setStatusBarHidden:animated:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/setStatusBarHidden:animated:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setStatusBarHidden:animated:"
        }
      ],
      "role": "symbol",
      "title": "setStatusBarHidden:animated:",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/setstatusbarhidden:animated:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/setStatusBarOrientation(_:animated:)": {
      "abstract": [
        {
          "text": "Sets the app’s status bar to the specified orientation, optionally animating the transition.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setStatusBarOrientation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIInterfaceOrientation",
          "text": "UIInterfaceOrientation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "animated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/setStatusBarOrientation(_:animated:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setStatusBarOrientation:animated:"
        }
      ],
      "role": "symbol",
      "title": "setStatusBarOrientation(_:animated:)",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/setstatusbarorientation(_:animated:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplication/setStatusBarStyle(_:animated:)": {
      "abstract": [
        {
          "text": "Sets the style of the status bar, optionally animating the transition to the new style.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setStatusBarStyle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIStatusBarStyle",
          "text": "UIStatusBarStyle"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "animated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplication/setStatusBarStyle(_:animated:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setStatusBarStyle:animated:"
        }
      ],
      "role": "symbol",
      "title": "setStatusBarStyle(_:animated:)",
      "type": "topic",
      "url": "/documentation/uikit/uiapplication/setstatusbarstyle(_:animated:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMinimumKeepAliveTimeout": {
      "abstract": [
        {
          "text": "The minimum amount of time (measured in seconds) an app may run a critical background task in the background.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIMinimumKeepAliveTimeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMinimumKeepAliveTimeout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIMinimumKeepAliveTimeout"
        }
      ],
      "role": "symbol",
      "title": "UIMinimumKeepAliveTimeout",
      "type": "topic",
      "url": "/documentation/uikit/uiminimumkeepalivetimeout"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType": {
      "abstract": [
        {
          "text": "Constants indicating the types of notifications the app may display to the user.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIRemoteNotificationType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIRemoteNotificationType"
        }
      ],
      "role": "symbol",
      "title": "UIRemoteNotificationType",
      "type": "topic",
      "url": "/documentation/uikit/uiremotenotificationtype"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType/UIRemoteNotificationTypeNone": {
      "abstract": [
        {
          "text": "The app accepts no notifications.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIRemoteNotificationTypeNone"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType/UIRemoteNotificationTypeNone",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIRemoteNotificationTypeNone",
      "type": "topic",
      "url": "/documentation/uikit/uiremotenotificationtype/uiremotenotificationtypenone"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType/alert": {
      "abstract": [
        {
          "text": "The app accepts alert messages as notifications.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alert"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIRemoteNotificationType",
          "text": "UIRemoteNotificationType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType/alert",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIRemoteNotificationTypeAlert"
        }
      ],
      "role": "symbol",
      "title": "alert",
      "type": "topic",
      "url": "/documentation/uikit/uiremotenotificationtype/alert"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType/badge": {
      "abstract": [
        {
          "text": "The app accepts notifications that badge the app icon.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "badge"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIRemoteNotificationType",
          "text": "UIRemoteNotificationType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType/badge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIRemoteNotificationTypeBadge"
        }
      ],
      "role": "symbol",
      "title": "badge",
      "type": "topic",
      "url": "/documentation/uikit/uiremotenotificationtype/badge"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType/init(rawValue:)": {
      "abstract": [],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/uiremotenotificationtype/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType/newsstandContentAvailability": {
      "abstract": [
        {
          "text": "The app accepts notifications that start the downloading of issue assets for Newsstand apps.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "newsstandContentAvailability"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIRemoteNotificationType",
          "text": "UIRemoteNotificationType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType/newsstandContentAvailability",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIRemoteNotificationTypeNewsstandContentAvailability"
        }
      ],
      "role": "symbol",
      "title": "newsstandContentAvailability",
      "type": "topic",
      "url": "/documentation/uikit/uiremotenotificationtype/newsstandcontentavailability"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType/sound": {
      "abstract": [
        {
          "text": "The app accepts alert sounds as notifications.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sound"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIRemoteNotificationType",
          "text": "UIRemoteNotificationType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType/sound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIRemoteNotificationTypeSound"
        }
      ],
      "role": "symbol",
      "title": "sound",
      "type": "topic",
      "url": "/documentation/uikit/uiremotenotificationtype/sound"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/requestSceneSessionActivation(_:userActivity:options:errorHandler:)",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/beginIgnoringInteractionEvents()",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/endIgnoringInteractionEvents()",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/setMinimumBackgroundFetchInterval(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/scheduleLocalNotification(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/presentLocalNotificationNow(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/cancelLocalNotification(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/cancelAllLocalNotifications()",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/setKeepAliveTimeout(_:handler:)",
        "doc://com.apple.uikit/documentation/UIKit/UIMinimumKeepAliveTimeout",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/clearKeepAliveTimeout()",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/setStatusBarHidden(_:with:)",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/setStatusBarStyle(_:animated:)",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/setStatusBarOrientation(_:animated:)",
        "doc://com.apple.uikit/documentation/UIKit/UIApplication/registerUserNotificationSettings(_:)"
      ],
      "title": "Deprecated methods"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType/badge",
        "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType/sound",
        "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType/alert",
        "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType/newsstandContentAvailability"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "8.0",
              "introducedAt": "3.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "8.0",
              "introducedAt": "3.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIRemoteNotificationType"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIRemoteNotificationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIRemoteNotificationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType/UIRemoteNotificationTypeNone",
                "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType/badge",
                "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType/sound",
                "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType/alert",
                "doc://com.apple.uikit/documentation/UIKit/UIRemoteNotificationType/newsstandContentAvailability"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Deprecated-methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/requestSceneSessionActivation(_:userActivity:options:errorHandler:)",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/beginIgnoringInteractionEvents()",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/endIgnoringInteractionEvents()",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/setMinimumBackgroundFetchInterval(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/scheduleLocalNotification(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/presentLocalNotificationNow(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/cancelLocalNotification(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/cancelAllLocalNotifications()",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/setKeepAliveTimeout(_:handler:)",
                "doc://com.apple.uikit/documentation/UIKit/UIMinimumKeepAliveTimeout",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/clearKeepAliveTimeout()",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/setStatusBarHidden:animated:",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/setStatusBarHidden(_:with:)",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/setStatusBarStyle(_:animated:)",
                "doc://com.apple.uikit/documentation/UIKit/UIApplication/setStatusBarOrientation(_:animated:)"
              ],
              "title": "Deprecated methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIRemoteNotificationType"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "add",
          "path": "/deprecationSummary",
          "value": []
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1registerUserNotificationSettings(_:)/title",
          "value": "registerUserNotificationSettings:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1registerUserNotificationSettings(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "registerUserNotificationSettings:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1setMinimumBackgroundFetchInterval(_:)/title",
          "value": "setMinimumBackgroundFetchInterval:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1setMinimumBackgroundFetchInterval(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setMinimumBackgroundFetchInterval:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1requestSceneSessionActivation(_:userActivity:options:errorHandler:)/title",
          "value": "requestSceneSessionActivation:userActivity:options:errorHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1requestSceneSessionActivation(_:userActivity:options:errorHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "requestSceneSessionActivation:userActivity:options:errorHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1endIgnoringInteractionEvents()/title",
          "value": "endIgnoringInteractionEvents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1endIgnoringInteractionEvents()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "endIgnoringInteractionEvents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1cancelAllLocalNotifications()/title",
          "value": "cancelAllLocalNotifications"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1cancelAllLocalNotifications()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cancelAllLocalNotifications"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRemoteNotificationType/title",
          "value": "UIRemoteNotificationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRemoteNotificationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIRemoteNotificationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRemoteNotificationType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIRemoteNotificationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRemoteNotificationType~1newsstandContentAvailability/title",
          "value": "UIRemoteNotificationTypeNewsstandContentAvailability"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRemoteNotificationType~1newsstandContentAvailability/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIRemoteNotificationTypeNewsstandContentAvailability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1cancelLocalNotification(_:)/title",
          "value": "cancelLocalNotification:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1cancelLocalNotification(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "cancelLocalNotification:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1presentLocalNotificationNow(_:)/title",
          "value": "presentLocalNotificationNow:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1presentLocalNotificationNow(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "presentLocalNotificationNow:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRemoteNotificationType~1sound/title",
          "value": "UIRemoteNotificationTypeSound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRemoteNotificationType~1sound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIRemoteNotificationTypeSound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1registerForRemoteNotifications(matching:)/title",
          "value": "registerForRemoteNotificationTypes:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1registerForRemoteNotifications(matching:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "registerForRemoteNotificationTypes:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1beginIgnoringInteractionEvents()/title",
          "value": "beginIgnoringInteractionEvents"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1beginIgnoringInteractionEvents()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "beginIgnoringInteractionEvents"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1setStatusBarStyle(_:animated:)/title",
          "value": "setStatusBarStyle:animated:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1setStatusBarStyle(_:animated:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setStatusBarStyle:animated:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRemoteNotificationType~1badge/title",
          "value": "UIRemoteNotificationTypeBadge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRemoteNotificationType~1badge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIRemoteNotificationTypeBadge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1setStatusBarHidden(_:with:)/title",
          "value": "setStatusBarHidden:withAnimation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1setStatusBarHidden(_:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setStatusBarHidden:withAnimation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1enabledRemoteNotificationTypes()/title",
          "value": "enabledRemoteNotificationTypes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1enabledRemoteNotificationTypes()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "enabledRemoteNotificationTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1setStatusBarOrientation(_:animated:)/title",
          "value": "setStatusBarOrientation:animated:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1setStatusBarOrientation(_:animated:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setStatusBarOrientation:animated:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1clearKeepAliveTimeout()/title",
          "value": "clearKeepAliveTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1clearKeepAliveTimeout()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "clearKeepAliveTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMinimumKeepAliveTimeout/title",
          "value": "UIMinimumKeepAliveTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMinimumKeepAliveTimeout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMinimumKeepAliveTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1scheduleLocalNotification(_:)/title",
          "value": "scheduleLocalNotification:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1scheduleLocalNotification(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scheduleLocalNotification:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRemoteNotificationType~1alert/title",
          "value": "UIRemoteNotificationTypeAlert"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRemoteNotificationType~1alert/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIRemoteNotificationTypeAlert"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1setKeepAliveTimeout(_:handler:)/title",
          "value": "setKeepAliveTimeout:handler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1setKeepAliveTimeout(_:handler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setKeepAliveTimeout:handler:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiremotenotificationtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiremotenotificationtype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
