{
  "abstract": [
    {
      "text": "The interface for the delegate of a scroll view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UIScrollViewDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIScrollViewDelegate"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIScrollViewDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "UIScrollViewDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIScrollViewDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The methods that the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol declares allow the adopting delegate to respond to messages from the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScrollView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class. The delegate responds to and affects operations like scrolling, zooming, deceleration of scrolled content, and scrolling animations.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewController": {
      "abstract": [
        {
          "text": "A view controller that specializes in managing a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewController"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewController",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegate": {
      "abstract": [
        {
          "text": "The methods adopted by the object you use to manage user interactions with items in a collection view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewDelegate"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegateFlowLayout": {
      "abstract": [
        {
          "text": "The methods that let you coordinate with a flow layout object to implement a grid-based layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionViewDelegateFlowLayout"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegateFlowLayout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionViewDelegateFlowLayout"
        }
      ],
      "role": "symbol",
      "title": "UICollectionViewDelegateFlowLayout",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewdelegateflowlayout"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScrollView": {
      "abstract": [
        {
          "text": "A view that allows the scrolling and zooming of its contained views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIScrollView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScrollView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIScrollView"
        }
      ],
      "role": "symbol",
      "title": "UIScrollView",
      "type": "topic",
      "url": "/documentation/uikit/uiscrollview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScrollView/delegate": {
      "abstract": [
        {
          "text": "The delegate of the scroll view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIScrollViewDelegate",
          "text": "UIScrollViewDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScrollView/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/uikit/uiscrollview/delegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScrollViewAccessibilityDelegate": {
      "abstract": [
        {
          "text": "A set of methods you can implement to provide accessibility information for a scroll view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIScrollViewAccessibilityDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScrollViewAccessibilityDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIScrollViewAccessibilityDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIScrollViewAccessibilityDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uiscrollviewaccessibilitydelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate": {
      "abstract": [
        {
          "text": "The interface for the delegate of a scroll view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIScrollViewDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIScrollViewDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIScrollViewDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uiscrollviewdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewDidChangeAdjustedContentInset(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate when the scroll view’s inset values change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scrollViewDidChangeAdjustedContentInset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIScrollView",
          "text": "UIScrollView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewDidChangeAdjustedContentInset(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scrollViewDidChangeAdjustedContentInset:"
        }
      ],
      "role": "symbol",
      "title": "scrollViewDidChangeAdjustedContentInset(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiscrollviewdelegate/scrollviewdidchangeadjustedcontentinset(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewDidEndDecelerating(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the scroll view ended decelerating the scrolling movement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scrollViewDidEndDecelerating"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIScrollView",
          "text": "UIScrollView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewDidEndDecelerating(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scrollViewDidEndDecelerating:"
        }
      ],
      "role": "symbol",
      "title": "scrollViewDidEndDecelerating(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiscrollviewdelegate/scrollviewdidenddecelerating(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewDidEndDragging(_:willDecelerate:)": {
      "abstract": [
        {
          "text": "Tells the delegate when dragging ended in the scroll view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scrollViewDidEndDragging"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIScrollView",
          "text": "UIScrollView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willDecelerate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewDidEndDragging(_:willDecelerate:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scrollViewDidEndDragging:willDecelerate:"
        }
      ],
      "role": "symbol",
      "title": "scrollViewDidEndDragging(_:willDecelerate:)",
      "type": "topic",
      "url": "/documentation/uikit/uiscrollviewdelegate/scrollviewdidenddragging(_:willdecelerate:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewDidEndScrollingAnimation(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate when a scrolling animation in the scroll view concludes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scrollViewDidEndScrollingAnimation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIScrollView",
          "text": "UIScrollView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewDidEndScrollingAnimation(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scrollViewDidEndScrollingAnimation:"
        }
      ],
      "role": "symbol",
      "title": "scrollViewDidEndScrollingAnimation(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiscrollviewdelegate/scrollviewdidendscrollinganimation(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewDidEndZooming(_:with:atScale:)": {
      "abstract": [
        {
          "text": "Tells the delegate when zooming of the content in the scroll view completed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scrollViewDidEndZooming"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIScrollView",
          "text": "UIScrollView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "atScale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewDidEndZooming(_:with:atScale:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scrollViewDidEndZooming:withView:atScale:"
        }
      ],
      "role": "symbol",
      "title": "scrollViewDidEndZooming(_:with:atScale:)",
      "type": "topic",
      "url": "/documentation/uikit/uiscrollviewdelegate/scrollviewdidendzooming(_:with:atscale:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewDidScroll(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate when the user scrolls the content view within the scroll view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scrollViewDidScroll"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIScrollView",
          "text": "UIScrollView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewDidScroll(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scrollViewDidScroll:"
        }
      ],
      "role": "symbol",
      "title": "scrollViewDidScroll(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiscrollviewdelegate/scrollviewdidscroll(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewDidScrollToTop(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the scroll view scrolled to the top of the content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scrollViewDidScrollToTop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIScrollView",
          "text": "UIScrollView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewDidScrollToTop(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scrollViewDidScrollToTop:"
        }
      ],
      "role": "symbol",
      "title": "scrollViewDidScrollToTop(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiscrollviewdelegate/scrollviewdidscrolltotop(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewDidZoom(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the scroll view’s zoom factor changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scrollViewDidZoom"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIScrollView",
          "text": "UIScrollView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewDidZoom(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scrollViewDidZoom:"
        }
      ],
      "role": "symbol",
      "title": "scrollViewDidZoom(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiscrollviewdelegate/scrollviewdidzoom(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewShouldScrollToTop(_:)": {
      "abstract": [
        {
          "text": "Asks the delegate if the scroll view should scroll to the top of the content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scrollViewShouldScrollToTop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIScrollView",
          "text": "UIScrollView"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewShouldScrollToTop(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scrollViewShouldScrollToTop:"
        }
      ],
      "role": "symbol",
      "title": "scrollViewShouldScrollToTop(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiscrollviewdelegate/scrollviewshouldscrolltotop(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewWillBeginDecelerating(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the scroll view is starting to decelerate the scrolling movement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scrollViewWillBeginDecelerating"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIScrollView",
          "text": "UIScrollView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewWillBeginDecelerating(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scrollViewWillBeginDecelerating:"
        }
      ],
      "role": "symbol",
      "title": "scrollViewWillBeginDecelerating(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiscrollviewdelegate/scrollviewwillbegindecelerating(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewWillBeginDragging(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate when the scroll view is about to start scrolling the content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scrollViewWillBeginDragging"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIScrollView",
          "text": "UIScrollView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewWillBeginDragging(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scrollViewWillBeginDragging:"
        }
      ],
      "role": "symbol",
      "title": "scrollViewWillBeginDragging(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiscrollviewdelegate/scrollviewwillbegindragging(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewWillBeginZooming(_:with:)": {
      "abstract": [
        {
          "text": "Tells the delegate that zooming of the content in the scroll view is about to commence.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scrollViewWillBeginZooming"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIScrollView",
          "text": "UIScrollView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewWillBeginZooming(_:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scrollViewWillBeginZooming:withView:"
        }
      ],
      "role": "symbol",
      "title": "scrollViewWillBeginZooming(_:with:)",
      "type": "topic",
      "url": "/documentation/uikit/uiscrollviewdelegate/scrollviewwillbeginzooming(_:with:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewWillEndDragging(_:withVelocity:targetContentOffset:)": {
      "abstract": [
        {
          "text": "Tells the delegate when the user finishes scrolling the content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scrollViewWillEndDragging"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIScrollView",
          "text": "UIScrollView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withVelocity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "targetContentOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewWillEndDragging(_:withVelocity:targetContentOffset:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scrollViewWillEndDragging:withVelocity:targetContentOffset:"
        }
      ],
      "role": "symbol",
      "title": "scrollViewWillEndDragging(_:withVelocity:targetContentOffset:)",
      "type": "topic",
      "url": "/documentation/uikit/uiscrollviewdelegate/scrollviewwillenddragging(_:withvelocity:targetcontentoffset:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/viewForZooming(in:)": {
      "abstract": [
        {
          "text": "Asks the delegate for the view to scale when zooming is about to occur in the scroll view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "viewForZooming"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIScrollView",
          "text": "UIScrollView"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/viewForZooming(in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "viewForZoomingInScrollView:"
        }
      ],
      "role": "symbol",
      "title": "viewForZooming(in:)",
      "type": "topic",
      "url": "/documentation/uikit/uiscrollviewdelegate/viewforzooming(in:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewController": {
      "abstract": [
        {
          "text": "A view controller that specializes in managing a table view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITableViewController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableViewController"
        }
      ],
      "role": "symbol",
      "title": "UITableViewController",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewDelegate": {
      "abstract": [
        {
          "text": "Methods for managing selections, configuring section headers and footers, deleting and reordering cells, and performing other actions in a table view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITableViewDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableViewDelegate"
        }
      ],
      "role": "symbol",
      "title": "UITableViewDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate": {
      "abstract": [
        {
          "text": "The methods for receiving editing-related messages for text view objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextViewDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextViewDelegate"
        }
      ],
      "role": "symbol",
      "title": "UITextViewDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uitextviewdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWebView": {
      "abstract": [
        {
          "text": "A view that embeds web content in your app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIWebView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWebView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWebView"
        }
      ],
      "role": "symbol",
      "title": "UIWebView",
      "type": "topic",
      "url": "/documentation/uikit/uiwebview"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegate",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegateFlowLayout",
        "doc://com.apple.uikit/documentation/UIKit/UIScrollViewAccessibilityDelegate",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewDelegate",
        "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICollectionViewController",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewController",
        "doc://com.apple.uikit/documentation/UIKit/UIWebView"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Responding-to-scroll-view-interactions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIScrollView/delegate"
      ],
      "title": "Responding to scroll view interactions"
    }
  ],
  "topicSections": [
    {
      "anchor": "Responding-to-scrolling-and-dragging",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewDidScroll(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewWillBeginDragging(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewWillEndDragging(_:withVelocity:targetContentOffset:)",
        "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewDidEndDragging(_:willDecelerate:)",
        "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewShouldScrollToTop(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewDidScrollToTop(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewWillBeginDecelerating(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewDidEndDecelerating(_:)"
      ],
      "title": "Responding to scrolling and dragging"
    },
    {
      "anchor": "Managing-zooming",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/viewForZooming(in:)",
        "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewWillBeginZooming(_:with:)",
        "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewDidEndZooming(_:with:atScale:)",
        "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewDidZoom(_:)"
      ],
      "title": "Managing zooming"
    },
    {
      "anchor": "Responding-to-scrolling-animations",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewDidEndScrollingAnimation(_:)"
      ],
      "title": "Responding to scrolling animations"
    },
    {
      "anchor": "Responding-to-inset-changes",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewDidChangeAdjustedContentInset(_:)"
      ],
      "title": "Responding to inset changes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIScrollViewDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScrollViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScrollViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Responding-to-scrolling-and-dragging",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewDidScroll(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewWillBeginDragging(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewWillEndDragging(_:withVelocity:targetContentOffset:)",
                "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewDidEndDragging(_:willDecelerate:)",
                "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewShouldScrollToTop(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewDidScrollToTop(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewWillBeginDecelerating(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewDidEndDecelerating(_:)"
              ],
              "title": "Responding to scrolling and dragging"
            },
            {
              "anchor": "Managing-zooming",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/viewForZooming(in:)",
                "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewWillBeginZooming(_:with:)",
                "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewDidEndZooming(_:with:atScale:)",
                "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewDidZoom(_:)"
              ],
              "title": "Managing zooming"
            },
            {
              "anchor": "Responding-to-scrolling-animations",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewDidEndScrollingAnimation(_:)"
              ],
              "title": "Responding to scrolling animations"
            },
            {
              "anchor": "Responding-to-inset-changes",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate/scrollViewDidChangeAdjustedContentInset(_:)"
              ],
              "title": "Responding to inset changes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UICollectionViewDelegate",
                "doc://com.apple.uikit/documentation/UIKit/UIScrollViewAccessibilityDelegate",
                "doc://com.apple.uikit/documentation/UIKit/UITableViewDelegate",
                "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            },
            {
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIWebView"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Responding-to-scroll-view-interactions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIScrollView/delegate"
              ],
              "title": "Responding to scroll view interactions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIScrollViewDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewDelegate~1scrollViewWillBeginZooming(_:with:)/title",
          "value": "scrollViewWillBeginZooming:withView:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewDelegate~1scrollViewWillBeginZooming(_:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scrollViewWillBeginZooming:withView:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewDelegate~1scrollViewDidScrollToTop(_:)/title",
          "value": "scrollViewDidScrollToTop:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewDelegate~1scrollViewDidScrollToTop(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scrollViewDidScrollToTop:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewDelegate/title",
          "value": "UIScrollViewDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScrollViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScrollViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewDelegate~1scrollViewDidEndScrollingAnimation(_:)/title",
          "value": "scrollViewDidEndScrollingAnimation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewDelegate~1scrollViewDidEndScrollingAnimation(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scrollViewDidEndScrollingAnimation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewDelegate~1scrollViewDidZoom(_:)/title",
          "value": "scrollViewDidZoom:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewDelegate~1scrollViewDidZoom(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scrollViewDidZoom:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewDelegate~1scrollViewWillEndDragging(_:withVelocity:targetContentOffset:)/title",
          "value": "scrollViewWillEndDragging:withVelocity:targetContentOffset:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewDelegate~1scrollViewWillEndDragging(_:withVelocity:targetContentOffset:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scrollViewWillEndDragging:withVelocity:targetContentOffset:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDelegate/title",
          "value": "UITableViewDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewDelegate~1scrollViewDidEndDragging(_:willDecelerate:)/title",
          "value": "scrollViewDidEndDragging:willDecelerate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewDelegate~1scrollViewDidEndDragging(_:willDecelerate:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scrollViewDidEndDragging:willDecelerate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewDelegate~1scrollViewWillBeginDecelerating(_:)/title",
          "value": "scrollViewWillBeginDecelerating:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewDelegate~1scrollViewWillBeginDecelerating(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scrollViewWillBeginDecelerating:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewDelegate~1scrollViewDidEndZooming(_:with:atScale:)/title",
          "value": "scrollViewDidEndZooming:withView:atScale:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewDelegate~1scrollViewDidEndZooming(_:with:atScale:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scrollViewDidEndZooming:withView:atScale:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView/title",
          "value": "UIWebView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWebView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWebView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWebView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewDelegate~1scrollViewDidScroll(_:)/title",
          "value": "scrollViewDidScroll:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewDelegate~1scrollViewDidScroll(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scrollViewDidScroll:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewController/title",
          "value": "UICollectionViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewController/title",
          "value": "UITableViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewDelegate~1scrollViewWillBeginDragging(_:)/title",
          "value": "scrollViewWillBeginDragging:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewDelegate~1scrollViewWillBeginDragging(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scrollViewWillBeginDragging:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollView/title",
          "value": "UIScrollView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScrollView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScrollView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDelegateFlowLayout/title",
          "value": "UICollectionViewDelegateFlowLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDelegateFlowLayout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDelegateFlowLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDelegateFlowLayout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDelegateFlowLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDelegate/title",
          "value": "UICollectionViewDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionViewDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewDelegate~1scrollViewDidChangeAdjustedContentInset(_:)/title",
          "value": "scrollViewDidChangeAdjustedContentInset:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewDelegate~1scrollViewDidChangeAdjustedContentInset(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scrollViewDidChangeAdjustedContentInset:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewDelegate~1scrollViewShouldScrollToTop(_:)/title",
          "value": "scrollViewShouldScrollToTop:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewDelegate~1scrollViewShouldScrollToTop(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scrollViewShouldScrollToTop:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewAccessibilityDelegate/title",
          "value": "UIScrollViewAccessibilityDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewAccessibilityDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScrollViewAccessibilityDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewAccessibilityDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScrollViewAccessibilityDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewDelegate~1viewForZooming(in:)/title",
          "value": "viewForZoomingInScrollView:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewDelegate~1viewForZooming(in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "viewForZoomingInScrollView:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollView~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollView~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate/title",
          "value": "UITextViewDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewDelegate~1scrollViewDidEndDecelerating(_:)/title",
          "value": "scrollViewDidEndDecelerating:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewDelegate~1scrollViewDidEndDecelerating(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "scrollViewDidEndDecelerating:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiscrollviewdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiscrollviewdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
