{
  "abstract": [
    {
      "text": "An object that defines the properties associated with a hardware-based display.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIScreen"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIScreen",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIScreen"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIScreen"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "UIScreen"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIScreen"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.uikit/documentation/UIKit/presenting-content-on-a-connected-display",
        "doc://com.apple.uikit/documentation/UIKit/building-a-desktop-class-ipad-app"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object provides information about the screens attached to an iOS, iPadOS, or tvOS device. Every iOS and iPadOS device has a screen object with information about the integrated display, and zero or more screen objects for attached displays. A tvOS device has a screen object that represents the television connected to the device. In a compatible iPad or iPhone app running in visionOS, don’t rely on screen-related properties to configure your app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You don’t create any of these screen objects directly. Instead, fetch the screen object for one of your app’s windows from the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object that manages the window.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Avoid using screen objects to make decisions about your app’s interface. Use a screen object only as needed to retrieve screen-related information, such as the screen’s bounds rectangle, brightness, and overscan settings. Apps that rely on the screen dimensions can use the object in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/fixedCoordinateSpace",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property as a fixed point of reference for any calculations they must make.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen": {
      "abstract": [
        {
          "text": "An object that defines the properties associated with a hardware-based display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIScreen"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIScreen"
        }
      ],
      "role": "symbol",
      "title": "UIScreen",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/OverscanCompensation-swift.enum": {
      "abstract": [
        {
          "text": "Describes different techniques for compensating for pixel loss at the edge of the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OverscanCompensation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/OverscanCompensation-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OverscanCompensation"
        }
      ],
      "role": "symbol",
      "title": "UIScreen.OverscanCompensation",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/overscancompensation-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum": {
      "abstract": [
        {
          "text": "Describes a screen’s reference display mode status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ReferenceDisplayModeStatus"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ReferenceDisplayModeStatus"
        }
      ],
      "role": "symbol",
      "title": "UIScreen.ReferenceDisplayModeStatus",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/referencedisplaymodestatus-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/availableModes": {
      "abstract": [
        {
          "text": "The display modes that can be associated with the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "availableModes"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIScreenMode",
          "text": "UIScreenMode"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/availableModes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "availableModes"
        }
      ],
      "role": "symbol",
      "title": "availableModes",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/availablemodes"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/bounds": {
      "abstract": [
        {
          "text": "The bounding rectangle of the screen, measured in points.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bounds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/bounds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bounds"
        }
      ],
      "role": "symbol",
      "title": "bounds",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/bounds"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/brightness": {
      "abstract": [
        {
          "text": "The brightness level of the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "brightness"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/brightness",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "brightness"
        }
      ],
      "role": "symbol",
      "title": "brightness",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/brightness"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/brightnessDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification that posts when a screen’s brightness changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "brightnessDidChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/brightnessDidChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIScreenBrightnessDidChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "brightnessDidChangeNotification",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/brightnessdidchangenotification"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/calibratedLatency": {
      "abstract": [
        {
          "text": "The user-calibrated latency for the current screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calibratedLatency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTimeInterval",
          "text": "CFTimeInterval"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/calibratedLatency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "calibratedLatency"
        }
      ],
      "role": "symbol",
      "title": "calibratedLatency",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/calibratedlatency"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/capturedDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification that posts when the capture status of a screen changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "capturedDidChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/capturedDidChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIScreenCapturedDidChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "capturedDidChangeNotification",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/captureddidchangenotification"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/coordinateSpace": {
      "abstract": [
        {
          "text": "The current coordinate space of the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "coordinateSpace"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UICoordinateSpace",
          "text": "UICoordinateSpace"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/coordinateSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "coordinateSpace"
        }
      ],
      "role": "symbol",
      "title": "coordinateSpace",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/coordinatespace"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/currentEDRHeadroom": {
      "abstract": [
        {
          "text": "The screen’s current headroom when displaying extended dynamic range content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentEDRHeadroom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/currentEDRHeadroom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentEDRHeadroom"
        }
      ],
      "role": "symbol",
      "title": "currentEDRHeadroom",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/currentedrheadroom"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/currentMode": {
      "abstract": [
        {
          "text": "The current screen mode associated with the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "currentMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIScreenMode",
          "text": "UIScreenMode"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/currentMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "currentMode"
        }
      ],
      "role": "symbol",
      "title": "currentMode",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/currentmode"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/displayLink(withTarget:selector:)": {
      "abstract": [
        {
          "text": "Returns a display link object for the current screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displayLink"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withTarget"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "selector"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CADisplayLink",
          "text": "CADisplayLink"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/displayLink(withTarget:selector:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "displayLinkWithTarget:selector:"
        }
      ],
      "role": "symbol",
      "title": "displayLink(withTarget:selector:)",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/displaylink(withtarget:selector:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/fixedCoordinateSpace": {
      "abstract": [
        {
          "text": "The fixed coordinate space of the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fixedCoordinateSpace"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UICoordinateSpace",
          "text": "UICoordinateSpace"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/fixedCoordinateSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fixedCoordinateSpace"
        }
      ],
      "role": "symbol",
      "title": "fixedCoordinateSpace",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/fixedcoordinatespace"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/isCaptured": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the system is actively cloning the screen to another destination.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isCaptured"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/isCaptured",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "captured"
        }
      ],
      "role": "symbol",
      "title": "isCaptured",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/iscaptured"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/maximumFramesPerSecond": {
      "abstract": [
        {
          "text": "The maximum number of frames per second a screen can render.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumFramesPerSecond"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/maximumFramesPerSecond",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "maximumFramesPerSecond"
        }
      ],
      "role": "symbol",
      "title": "maximumFramesPerSecond",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/maximumframespersecond"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/mirrored": {
      "abstract": [
        {
          "text": "The screen an external display mirrors from.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mirrored"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIScreen",
          "text": "UIScreen"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/mirrored",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mirroredScreen"
        }
      ],
      "role": "symbol",
      "title": "mirrored",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/mirrored"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/modeDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification that posts when a screen’s mode changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "modeDidChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/modeDidChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIScreenModeDidChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "modeDidChangeNotification",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/modedidchangenotification"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/nativeBounds": {
      "abstract": [
        {
          "text": "The bounding rectangle of the physical screen, measured in pixels.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nativeBounds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/nativeBounds",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nativeBounds"
        }
      ],
      "role": "symbol",
      "title": "nativeBounds",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/nativebounds"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/nativeScale": {
      "abstract": [
        {
          "text": "The native scale factor for the physical screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nativeScale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/nativeScale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "nativeScale"
        }
      ],
      "role": "symbol",
      "title": "nativeScale",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/nativescale"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/overscanCompensation-swift.property": {
      "abstract": [
        {
          "text": "For an external screen, this property sets the desired technique to compensate for overscan.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overscanCompensation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIScreen",
          "text": "UIScreen"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIScreenOverscanCompensation",
          "text": "OverscanCompensation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/overscanCompensation-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "overscanCompensation"
        }
      ],
      "role": "symbol",
      "title": "overscanCompensation",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/overscancompensation-swift.property"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/overscanCompensationInsets": {
      "abstract": [
        {
          "text": "The edge inset values needed to avoid clipping the rectangle.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overscanCompensationInsets"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@UIEdgeInsets",
          "text": "UIEdgeInsets"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/overscanCompensationInsets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "overscanCompensationInsets"
        }
      ],
      "role": "symbol",
      "title": "overscanCompensationInsets",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/overscancompensationinsets"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/potentialEDRHeadroom": {
      "abstract": [
        {
          "text": "The screen’s maximum headroom when displaying extended dynamic range content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "potentialEDRHeadroom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/potentialEDRHeadroom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "potentialEDRHeadroom"
        }
      ],
      "role": "symbol",
      "title": "potentialEDRHeadroom",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/potentialedrheadroom"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/preferredMode": {
      "abstract": [
        {
          "text": "The preferred display mode for the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIScreenMode",
          "text": "UIScreenMode"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/preferredMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredMode"
        }
      ],
      "role": "symbol",
      "title": "preferredMode",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/preferredmode"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/referenceDisplayModeStatus-swift.property": {
      "abstract": [
        {
          "text": "The status of the screen’s reference display mode.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "referenceDisplayModeStatus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIScreen",
          "text": "UIScreen"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIScreenReferenceDisplayModeStatus",
          "text": "ReferenceDisplayModeStatus"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/referenceDisplayModeStatus-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "referenceDisplayModeStatus"
        }
      ],
      "role": "symbol",
      "title": "referenceDisplayModeStatus",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/referencedisplaymodestatus-swift.property"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/referenceDisplayModeStatusDidChangeNotification": {
      "abstract": [
        {
          "text": "A notification that posts when there’s a change to a screen’s reference display mode status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "referenceDisplayModeStatusDidChangeNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/referenceDisplayModeStatusDidChangeNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIScreenReferenceDisplayModeStatusDidChangeNotification"
        }
      ],
      "role": "symbol",
      "title": "referenceDisplayModeStatusDidChangeNotification",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/referencedisplaymodestatusdidchangenotification"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/scale": {
      "abstract": [
        {
          "text": "The natural scale factor associated with the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/scale",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scale"
        }
      ],
      "role": "symbol",
      "title": "scale",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/scale"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/snapshotView(afterScreenUpdates:)": {
      "abstract": [
        {
          "text": "Returns a snapshot view based on the current screen contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "snapshotView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "afterScreenUpdates"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/snapshotView(afterScreenUpdates:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "snapshotViewAfterScreenUpdates:"
        }
      ],
      "role": "symbol",
      "title": "snapshotView(afterScreenUpdates:)",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/snapshotview(afterscreenupdates:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/wantsSoftwareDimming": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the screen may be dimmed lower than the hardware is normally capable of by emulating it in software.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wantsSoftwareDimming"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/wantsSoftwareDimming",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "wantsSoftwareDimming"
        }
      ],
      "role": "symbol",
      "title": "wantsSoftwareDimming",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/wantssoftwaredimming"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreenMode": {
      "abstract": [
        {
          "text": "A possible set of attributes that can apply to a screen object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIScreenMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreenMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIScreenMode"
        }
      ],
      "role": "symbol",
      "title": "UIScreenMode",
      "type": "topic",
      "url": "/documentation/uikit/uiscreenmode"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITraitEnvironment": {
      "abstract": [
        {
          "text": "A set of methods that makes the iOS interface environment available to your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITraitEnvironment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITraitEnvironment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITraitEnvironment"
        }
      ],
      "role": "symbol",
      "title": "UITraitEnvironment",
      "type": "topic",
      "url": "/documentation/uikit/uitraitenvironment"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIWindowScene": {
      "abstract": [
        {
          "text": "A scene that manages one or more windows for your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIWindowScene"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIWindowScene",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIWindowScene"
        }
      ],
      "role": "symbol",
      "title": "UIWindowScene",
      "type": "topic",
      "url": "/documentation/uikit/uiwindowscene"
    },
    "doc://com.apple.uikit/documentation/UIKit/building-a-desktop-class-ipad-app": {
      "abstract": [
        {
          "text": "Optimize your iPad app’s user experience by adopting desktop-class enhancements for multitasking with Stage Manager, document interactions, text editing, search, and more in iPadOS 16.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/building-a-desktop-class-ipad-app",
      "kind": "article",
      "role": "article",
      "title": "Building a desktop-class iPad app",
      "type": "topic",
      "url": "/documentation/uikit/building-a-desktop-class-ipad-app"
    },
    "doc://com.apple.uikit/documentation/UIKit/presenting-content-on-a-connected-display": {
      "abstract": [
        {
          "text": "Fill connected displays with additional content from your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/presenting-content-on-a-connected-display",
      "kind": "article",
      "role": "article",
      "title": "Presenting content on a connected display",
      "type": "topic",
      "url": "/documentation/uikit/presenting-content-on-a-connected-display"
    },
    "doc://com.apple.uikit/documentation/UIKit/uiscreen-deprecated-symbols": {
      "abstract": [
        {
          "text": "Review unsupported symbols and their replacements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/uiscreen-deprecated-symbols",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Deprecated symbols",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen-deprecated-symbols"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.apple.uikit/documentation/UIKit/UITraitEnvironment"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Screens",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/presenting-content-on-a-connected-display",
        "doc://com.apple.uikit/documentation/UIKit/UIScreenMode"
      ],
      "title": "Screens"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-coordinate-space",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/coordinateSpace",
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/fixedCoordinateSpace"
      ],
      "title": "Getting the coordinate space"
    },
    {
      "anchor": "Getting-the-size-and-scale",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/bounds",
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/nativeBounds",
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/nativeScale",
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/scale"
      ],
      "title": "Getting the size and scale"
    },
    {
      "anchor": "Managing-brightness",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/brightness",
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/wantsSoftwareDimming"
      ],
      "title": "Managing brightness"
    },
    {
      "anchor": "Managing-screen-modes",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/currentMode",
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/preferredMode",
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/availableModes"
      ],
      "title": "Managing screen modes"
    },
    {
      "anchor": "Managing-overscan-compensation",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/overscanCompensationInsets",
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/overscanCompensation-swift.property",
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/OverscanCompensation-swift.enum"
      ],
      "title": "Managing overscan compensation"
    },
    {
      "anchor": "Getting-the-calibrated-latency",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/calibratedLatency"
      ],
      "title": "Getting the calibrated latency"
    },
    {
      "anchor": "Getting-the-reference-display-mode-status",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/referenceDisplayModeStatus-swift.property",
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum",
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/currentEDRHeadroom",
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/potentialEDRHeadroom"
      ],
      "title": "Getting the reference display mode status"
    },
    {
      "anchor": "Getting-a-display-link",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/displayLink(withTarget:selector:)",
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/maximumFramesPerSecond"
      ],
      "title": "Getting a display link"
    },
    {
      "anchor": "Capturing-a-snapshot",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/snapshotView(afterScreenUpdates:)"
      ],
      "title": "Capturing a snapshot"
    },
    {
      "anchor": "Detecting-screen-capture",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/isCaptured",
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/mirrored"
      ],
      "title": "Detecting screen capture"
    },
    {
      "anchor": "Notifications",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/brightnessDidChangeNotification",
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/modeDidChangeNotification",
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/capturedDidChangeNotification",
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/referenceDisplayModeStatusDidChangeNotification"
      ],
      "title": "Notifications"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/uiscreen-deprecated-symbols"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIScreen"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-the-coordinate-space",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/coordinateSpace",
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/fixedCoordinateSpace"
              ],
              "title": "Getting the coordinate space"
            },
            {
              "anchor": "Getting-the-size-and-scale",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/bounds",
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/nativeBounds",
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/nativeScale",
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/scale"
              ],
              "title": "Getting the size and scale"
            },
            {
              "anchor": "Managing-brightness",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/brightness",
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/wantsSoftwareDimming"
              ],
              "title": "Managing brightness"
            },
            {
              "anchor": "Managing-screen-modes",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/currentMode",
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/preferredMode",
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/availableModes"
              ],
              "title": "Managing screen modes"
            },
            {
              "anchor": "Managing-overscan-compensation",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/overscanCompensationInsets",
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/overscanCompensation-swift.property",
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/OverscanCompensation-swift.enum"
              ],
              "title": "Managing overscan compensation"
            },
            {
              "anchor": "Getting-the-calibrated-latency",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/calibratedLatency"
              ],
              "title": "Getting the calibrated latency"
            },
            {
              "anchor": "Getting-the-reference-display-mode-status",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/referenceDisplayModeStatus-swift.property",
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/ReferenceDisplayModeStatus-swift.enum",
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/currentEDRHeadroom",
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/potentialEDRHeadroom"
              ],
              "title": "Getting the reference display mode status"
            },
            {
              "anchor": "Getting-a-display-link",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/displayLink(withTarget:selector:)",
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/maximumFramesPerSecond"
              ],
              "title": "Getting a display link"
            },
            {
              "anchor": "Capturing-a-snapshot",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/snapshotView(afterScreenUpdates:)"
              ],
              "title": "Capturing a snapshot"
            },
            {
              "anchor": "Detecting-screen-capture",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/isCaptured",
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/mirrored"
              ],
              "title": "Detecting screen capture"
            },
            {
              "anchor": "Notifications",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/brightnessDidChangeNotification",
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/modeDidChangeNotification",
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/capturedDidChangeNotification",
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/referenceDisplayModeStatusDidChangeNotification"
              ],
              "title": "Notifications"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/uiscreen-deprecated-symbols"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITraitEnvironment"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Screens",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/presenting-content-on-a-connected-display",
                "doc://com.apple.uikit/documentation/UIKit/UIScreenMode"
              ],
              "title": "Screens"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIScreen"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1referenceDisplayModeStatus-swift.property/title",
          "value": "referenceDisplayModeStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1referenceDisplayModeStatus-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "referenceDisplayModeStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1wantsSoftwareDimming/title",
          "value": "wantsSoftwareDimming"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1wantsSoftwareDimming/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "wantsSoftwareDimming"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1bounds/title",
          "value": "bounds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1bounds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bounds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreenMode/title",
          "value": "UIScreenMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreenMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreenMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreenMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreenMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1nativeScale/title",
          "value": "nativeScale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1nativeScale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nativeScale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitEnvironment/title",
          "value": "UITraitEnvironment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitEnvironment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITraitEnvironment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITraitEnvironment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITraitEnvironment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1referenceDisplayModeStatusDidChangeNotification/title",
          "value": "UIScreenReferenceDisplayModeStatusDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1referenceDisplayModeStatusDidChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreenReferenceDisplayModeStatusDidChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1ReferenceDisplayModeStatus-swift.enum/title",
          "value": "UIScreenReferenceDisplayModeStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1ReferenceDisplayModeStatus-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreenReferenceDisplayModeStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1ReferenceDisplayModeStatus-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreenReferenceDisplayModeStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1displayLink(withTarget:selector:)/title",
          "value": "displayLinkWithTarget:selector:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1displayLink(withTarget:selector:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "displayLinkWithTarget:selector:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1overscanCompensationInsets/title",
          "value": "overscanCompensationInsets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1overscanCompensationInsets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "overscanCompensationInsets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1potentialEDRHeadroom/title",
          "value": "potentialEDRHeadroom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1potentialEDRHeadroom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "potentialEDRHeadroom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1modeDidChangeNotification/title",
          "value": "UIScreenModeDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1modeDidChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreenModeDidChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1OverscanCompensation-swift.enum/title",
          "value": "UIScreenOverscanCompensation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1OverscanCompensation-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreenOverscanCompensation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1OverscanCompensation-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreenOverscanCompensation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1preferredMode/title",
          "value": "preferredMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1preferredMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preferredMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1mirrored/title",
          "value": "mirroredScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1mirrored/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mirroredScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1isCaptured/title",
          "value": "captured"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1isCaptured/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "captured"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1fixedCoordinateSpace/title",
          "value": "fixedCoordinateSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1fixedCoordinateSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "fixedCoordinateSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1currentEDRHeadroom/title",
          "value": "currentEDRHeadroom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1currentEDRHeadroom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentEDRHeadroom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1coordinateSpace/title",
          "value": "coordinateSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1coordinateSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "coordinateSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1brightness/title",
          "value": "brightness"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1brightness/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "brightness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene/title",
          "value": "UIWindowScene"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIWindowScene"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1brightnessDidChangeNotification/title",
          "value": "UIScreenBrightnessDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1brightnessDidChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreenBrightnessDidChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1capturedDidChangeNotification/title",
          "value": "UIScreenCapturedDidChangeNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1capturedDidChangeNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreenCapturedDidChangeNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1currentMode/title",
          "value": "currentMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1currentMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "currentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen/title",
          "value": "UIScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1overscanCompensation-swift.property/title",
          "value": "overscanCompensation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1overscanCompensation-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "overscanCompensation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1nativeBounds/title",
          "value": "nativeBounds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1nativeBounds/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "nativeBounds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1snapshotView(afterScreenUpdates:)/title",
          "value": "snapshotViewAfterScreenUpdates:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1snapshotView(afterScreenUpdates:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "snapshotViewAfterScreenUpdates:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1maximumFramesPerSecond/title",
          "value": "maximumFramesPerSecond"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1maximumFramesPerSecond/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "maximumFramesPerSecond"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1scale/title",
          "value": "scale"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1scale/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scale"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1calibratedLatency/title",
          "value": "calibratedLatency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1calibratedLatency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "calibratedLatency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1availableModes/title",
          "value": "availableModes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1availableModes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "availableModes"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiscreen"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiscreen"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
