{
  "abstract": [
    {
      "text": "Review unsupported symbols and their replacements.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/windows-and-screens",
        "doc://com.apple.uikit/documentation/UIKit/UIScreen"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/uiscreen-deprecated-symbols"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Deprecated symbols"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen": {
      "abstract": [
        {
          "text": "An object that defines the properties associated with a hardware-based display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIScreen"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIScreen"
        }
      ],
      "role": "symbol",
      "title": "UIScreen",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/applicationFrame": {
      "abstract": [
        {
          "text": "The frame rectangle for the app window, measured in points.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applicationFrame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/applicationFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applicationFrame"
        }
      ],
      "role": "symbol",
      "title": "applicationFrame",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/applicationframe"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/didConnectNotification": {
      "abstract": [
        {
          "text": "A notification the system posts when a new screen connects to the device.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didConnectNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/didConnectNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIScreenDidConnectNotification"
        }
      ],
      "role": "symbol",
      "title": "didConnectNotification",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/didconnectnotification"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/didDisconnectNotification": {
      "abstract": [
        {
          "text": "A notification the system posts when a screen disconnects from the device.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didDisconnectNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/didDisconnectNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIScreenDidDisconnectNotification"
        }
      ],
      "role": "symbol",
      "title": "didDisconnectNotification",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/diddisconnectnotification"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/focusedItem": {
      "abstract": [
        {
          "text": "The item that is currently focused.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "focusedItem"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIFocusItem",
          "text": "UIFocusItem"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/focusedItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "focusedItem"
        }
      ],
      "role": "symbol",
      "title": "focusedItem",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/focuseditem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/focusedView": {
      "abstract": [
        {
          "text": "The view that is currently focused.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "focusedView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/focusedView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "focusedView"
        }
      ],
      "role": "symbol",
      "title": "focusedView",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/focusedview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/main": {
      "abstract": [
        {
          "text": "Returns the screen object representing the device’s screen.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "main"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIScreen",
          "text": "UIScreen"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/main",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "mainScreen"
        }
      ],
      "role": "symbol",
      "title": "main",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/main"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/screens": {
      "abstract": [
        {
          "text": "Returns an array containing all of the screens attached to the device.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "screens"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIScreen",
          "text": "UIScreen"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/screens",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "screens"
        }
      ],
      "role": "symbol",
      "title": "screens",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/screens"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreen/supportsFocus": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the screen supports focus-based inputs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "supportsFocus"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreen/supportsFocus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "supportsFocus"
        }
      ],
      "role": "symbol",
      "title": "supportsFocus",
      "type": "topic",
      "url": "/documentation/uikit/uiscreen/supportsfocus"
    },
    "doc://com.apple.uikit/documentation/UIKit/windows-and-screens": {
      "abstract": [
        {
          "text": "Provide a container for your view hierarchies and other content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/windows-and-screens",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Windows and screens",
      "type": "topic",
      "url": "/documentation/uikit/windows-and-screens"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Deprecated-properties",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/main",
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/screens",
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/applicationFrame",
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/focusedItem",
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/focusedView",
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/supportsFocus"
      ],
      "title": "Deprecated properties"
    },
    {
      "anchor": "Deprecated-notifications",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/didConnectNotification",
        "doc://com.apple.uikit/documentation/UIKit/UIScreen/didDisconnectNotification"
      ],
      "title": "Deprecated notifications"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Deprecated-properties",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/main",
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/screens",
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/applicationFrame",
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/focusedItem",
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/focusedView",
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/supportsFocus"
              ],
              "title": "Deprecated properties"
            },
            {
              "anchor": "Deprecated-notifications",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/didConnectNotification",
                "doc://com.apple.uikit/documentation/UIKit/UIScreen/didDisconnectNotification"
              ],
              "title": "Deprecated notifications"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1focusedItem/title",
          "value": "focusedItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1focusedItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "focusedItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1focusedView/title",
          "value": "focusedView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1focusedView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "focusedView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1applicationFrame/title",
          "value": "applicationFrame"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1applicationFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "applicationFrame"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1didConnectNotification/title",
          "value": "UIScreenDidConnectNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1didConnectNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreenDidConnectNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1screens/title",
          "value": "screens"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1screens/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "screens"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen/title",
          "value": "UIScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreen"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1supportsFocus/title",
          "value": "supportsFocus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1supportsFocus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "supportsFocus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1didDisconnectNotification/title",
          "value": "UIScreenDidDisconnectNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1didDisconnectNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreenDidDisconnectNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1main/title",
          "value": "mainScreen"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreen~1main/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "mainScreen"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiscreen-deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiscreen-deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
