{"sections":[],"abstract":[{"text":"An object that contains information about one of your app’s scenes.","type":"text"}],"relationshipsSections":[{"identifiers":["doc://com.externally.resolved.symbol/c:objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc://com.externally.resolved.symbol/s:s7CVarArgP","doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/c:objc(pl)NSCoding","doc://com.externally.resolved.symbol/c:objc(pl)NSObject","doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding","doc://com.externally.resolved.symbol/s:s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"topicSections":[{"title":"Getting the scene information","anchor":"Getting-the-scene-information","identifiers":["doc://com.apple.uikit/documentation/UIKit/UISceneSession/scene","doc://com.apple.uikit/documentation/UIKit/UISceneSession/role-swift.property","doc://com.apple.uikit/documentation/UIKit/UISceneSession/Role-swift.struct"]},{"title":"Getting the scene configuration details","anchor":"Getting-the-scene-configuration-details","identifiers":["doc://com.apple.uikit/documentation/UIKit/UISceneSession/configuration","doc://com.apple.uikit/documentation/UIKit/UISceneConfiguration"]},{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UISceneSession/persistentIdentifier"],"anchor":"Identifying-the-scene","title":"Identifying the scene"},{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UISceneSession/stateRestorationActivity","doc://com.apple.uikit/documentation/UIKit/UISceneSession/userInfo"],"anchor":"Getting-additional-session-information","title":"Getting additional session information"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UISceneSession"},"seeAlsoSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/specifying-the-scenes-your-app-supports","doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest","doc://com.apple.uikit/documentation/UIKit/UISceneConfiguration"],"generated":true,"anchor":"Configuration","title":"Configuration"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"UISceneSession"}],"roleHeading":"Class","title":"UISceneSession","externalID":"c:objc(cs)UISceneSession","modules":[{"name":"UIKit"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UISceneSession"}],"role":"symbol","platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false},{"beta":false,"unavailable":false,"name":"iPadOS","introducedAt":"13.0","deprecated":false},{"name":"Mac Catalyst","introducedAt":"13.1","unavailable":false,"beta":false,"deprecated":false},{"name":"tvOS","introducedAt":"13.0","unavailable":false,"beta":false,"deprecated":false},{"name":"visionOS","introducedAt":"1.0","unavailable":false,"beta":false,"deprecated":false}],"symbolKind":"class"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UISceneSession","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Overview","anchor":"overview","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"A ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UISceneSession","isActive":true,"type":"reference"},{"text":" object manages a unique runtime instance of your scene. When the user adds a new scene to your app, or when you request one programmatically, the system creates a session object to track that scene. The session contains a unique identifier and the configuration details of the scene. UIKit maintains the session information for the lifetime of the scene itself, destroying the session in response to the user closing the scene in the app switcher.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"You don’t create session objects directly. UIKit creates sessions in response to user interactions with your app. You can also ask UIKit to create a new scene and session programmatically by calling the ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication/requestSceneSessionActivation(_:userActivity:options:errorHandler:)","type":"reference","isActive":true},{"text":" method of ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication","type":"reference","isActive":true},{"text":". UIKit initializes the session with default configuration data based on the contents of your app’s ","type":"text"},{"type":"codeVoice","code":"Info.plist"},{"text":" file.","type":"text"}]}],"kind":"content"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uiscenesession"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uiscenesession"]}],"references":{"doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest":{"kind":"symbol","role":"symbol","title":"UIApplicationSceneManifest","identifier":"doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest","type":"topic","url":"/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest","abstract":[{"text":"The information about the app’s scene-based life-cycle support.","type":"text"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.externally.resolved.symbol/s:s8SendableP":{"abstract":[{"type":"text","text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races."}],"url":"/documentation/Swift/Sendable","identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}],"role":"symbol","title":"Sendable","type":"topic","kind":"symbol"},"doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding":{"fragments":[{"kind":"text","text":"protocol "},{"kind":"identifier","text":"NSSecureCoding"}],"type":"topic","abstract":[{"text":"A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.","type":"text"}],"role":"symbol","kind":"symbol","url":"/documentation/foundation/nssecurecoding","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding","title":"NSSecureCoding"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.externally.resolved.symbol/s:s7CVarArgP":{"abstract":[{"type":"text","text":"A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVarArg"}],"identifier":"doc://com.externally.resolved.symbol/s:s7CVarArgP","type":"topic","title":"CVarArg","kind":"symbol","role":"symbol","url":"/documentation/Swift/CVarArg"},"doc://com.externally.resolved.symbol/c:objc(pl)NSCoding":{"url":"/documentation/foundation/nscoding","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCoding","role":"symbol","fragments":[{"kind":"text","text":"protocol "},{"kind":"identifier","text":"NSCoding"}],"type":"topic","title":"NSCoding","kind":"symbol","abstract":[{"text":"A protocol that enables an object to be encoded and decoded for archiving and distribution.","type":"text"}]},"doc://com.externally.resolved.symbol/s:SQ":{"abstract":[{"type":"text","text":"A type that can be compared for value equality."}],"url":"/documentation/Swift/Equatable","identifier":"doc://com.externally.resolved.symbol/s:SQ","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"role":"symbol","title":"Equatable","type":"topic","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UISceneSession/Role-swift.struct":{"title":"UISceneSession.Role","url":"/documentation/uikit/uiscenesession/role-swift.struct","role":"symbol","abstract":[{"text":"Constants that indicate the possible roles for a scene.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"Role","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UISceneSession/Role-swift.struct","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Role","kind":"identifier"}]},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"title":"NSObjectProtocol","type":"topic","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","role":"symbol","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"kind":"symbol","url":"/documentation/objectivec/nsobjectprotocol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UISceneSession/configuration":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configuration","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UISceneConfiguration","kind":"typeIdentifier","text":"UISceneConfiguration"}],"url":"/documentation/uikit/uiscenesession/configuration","abstract":[{"text":"The configuration data for creating the scene.","type":"text"}],"title":"configuration","navigatorTitle":[{"kind":"identifier","text":"configuration"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISceneSession/configuration","type":"topic","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UISceneSession/persistentIdentifier":{"abstract":[{"text":"A unique identifier that persists for the lifetime of the session.","type":"text"}],"navigatorTitle":[{"text":"persistentIdentifier","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISceneSession/persistentIdentifier","url":"/documentation/uikit/uiscenesession/persistentidentifier","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"persistentIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol","title":"persistentIdentifier","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIApplication/requestSceneSessionActivation(_:userActivity:options:errorHandler:)":{"type":"topic","title":"requestSceneSessionActivation(_:userActivity:options:errorHandler:)","deprecated":true,"abstract":[{"text":"Asks the system to activate an existing scene, or create a new scene and associate it with your app.","type":"text"}],"navigatorTitle":[{"text":"requestSceneSessionActivation:userActivity:options:errorHandler:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestSceneSessionActivation"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISceneSession","text":"UISceneSession"},{"text":"?, ","kind":"text"},{"text":"userActivity","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSUserActivity","preciseIdentifier":"c:objc(cs)NSUserActivity"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"options"},{"text":": ","kind":"text"},{"text":"UIScene","preciseIdentifier":"c:objc(cs)UIScene","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"ActivationRequestOptions","preciseIdentifier":"c:objc(cs)UISceneActivationRequestOptions","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"errorHandler","kind":"externalParam"},{"text":": ((any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"role":"symbol","url":"/documentation/uikit/uiapplication/requestscenesessionactivation(_:useractivity:options:errorhandler:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication/requestSceneSessionActivation(_:userActivity:options:errorHandler:)","kind":"symbol"},"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP":{"identifier":"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","kind":"symbol","type":"topic","title":"CustomDebugStringConvertible","url":"/documentation/Swift/CustomDebugStringConvertible","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomDebugStringConvertible"}],"role":"symbol","abstract":[{"type":"text","text":"A type with a customized textual representation suitable for debugging purposes."}]},"doc://com.externally.resolved.symbol/c:objc(cs)NSObject":{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSObject","role":"symbol","kind":"symbol","url":"/documentation/objectivec/nsobject","title":"NSObject","type":"topic","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSObject"}],"abstract":[{"text":"The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UISceneSession/stateRestorationActivity":{"abstract":[{"type":"text","text":"An activity object you can use to restore the previous contents of your scene’s interface."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stateRestorationActivity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSUserActivity","text":"NSUserActivity"},{"kind":"text","text":"?"}],"role":"symbol","url":"/documentation/uikit/uiscenesession/staterestorationactivity","navigatorTitle":[{"kind":"identifier","text":"stateRestorationActivity"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISceneSession/stateRestorationActivity","type":"topic","title":"stateRestorationActivity","kind":"symbol"},"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP":{"identifier":"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","kind":"symbol","type":"topic","title":"CustomStringConvertible","url":"/documentation/Swift/CustomStringConvertible","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomStringConvertible"}],"role":"symbol","abstract":[{"text":"A type with a customized textual representation.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UISceneSession":{"title":"UISceneSession","type":"topic","navigatorTitle":[{"text":"UISceneSession","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UISceneSession","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISceneSession","role":"symbol","url":"/documentation/uikit/uiscenesession","kind":"symbol","abstract":[{"text":"An object that contains information about one of your app’s scenes.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UIApplication":{"kind":"symbol","role":"symbol","title":"UIApplication","navigatorTitle":[{"text":"UIApplication","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIApplication","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication","url":"/documentation/uikit/uiapplication","abstract":[{"type":"text","text":"The centralized point of control and coordination for apps running in iOS."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UISceneSession/scene":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scene"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIScene","kind":"typeIdentifier","text":"UIScene"},{"text":"?","kind":"text"}],"url":"/documentation/uikit/uiscenesession/scene","abstract":[{"text":"The scene associated with the current session.","type":"text"}],"title":"scene","navigatorTitle":[{"text":"scene","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISceneSession/scene","type":"topic","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UISceneConfiguration":{"navigatorTitle":[{"text":"UISceneConfiguration","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UISceneConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"text":"Information about the objects and storyboard for UKit to use when creating a particular scene.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISceneConfiguration","title":"UISceneConfiguration","url":"/documentation/uikit/uisceneconfiguration","kind":"symbol"},"doc://com.externally.resolved.symbol/s:SH":{"abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}],"url":"/documentation/Swift/Hashable","identifier":"doc://com.externally.resolved.symbol/s:SH","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hashable","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SQ","text":"Equatable","kind":"typeIdentifier"}],"role":"symbol","title":"Hashable","type":"topic","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/specifying-the-scenes-your-app-supports":{"abstract":[{"text":"Tell the system about your app’s scenes, including the objects you use to manage each scene and its initial user interface.","type":"text"}],"kind":"article","role":"article","title":"Specifying the scenes your app supports","identifier":"doc://com.apple.uikit/documentation/UIKit/specifying-the-scenes-your-app-supports","type":"topic","url":"/documentation/uikit/specifying-the-scenes-your-app-supports"},"doc://com.apple.uikit/documentation/UIKit/UISceneSession/role-swift.property":{"title":"role","navigatorTitle":[{"kind":"identifier","text":"role"}],"role":"symbol","type":"topic","url":"/documentation/uikit/uiscenesession/role-swift.property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"role"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISceneSession","text":"UISceneSession"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@UISceneSessionRole","text":"Role"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISceneSession/role-swift.property","abstract":[{"type":"text","text":"The role played by the scene’s content."}],"kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UISceneSession/userInfo":{"title":"userInfo","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userInfo","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISceneSession/userInfo","abstract":[{"text":"Custom attributes that you can associate with the scene.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"userInfo"}],"type":"topic","url":"/documentation/uikit/uiscenesession/userinfo","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"op":"replace","path":"/metadata/platforms","value":[{"beta":false,"name":"iOS","unavailable":false,"introducedAt":"13.0","deprecated":false},{"beta":false,"name":"iPadOS","unavailable":false,"introducedAt":"13.0","deprecated":false},{"beta":false,"name":"Mac Catalyst","unavailable":false,"introducedAt":"13.1","deprecated":false},{"beta":false,"name":"tvOS","unavailable":false,"introducedAt":"13.0","deprecated":false},{"beta":false,"unavailable":false,"introducedAt":"1.0","name":"visionOS","deprecated":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Class"},{"op":"replace","path":"/metadata/title","value":"UISceneSession"},{"op":"replace","path":"/metadata/symbolKind","value":"class"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"UISceneSession","kind":"identifier"}]},{"path":"/metadata/navigatorTitle","value":[{"text":"UISceneSession","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"op":"replace"},{"path":"/topicSections","value":[{"title":"Getting the scene information","anchor":"Getting-the-scene-information","identifiers":["doc://com.apple.uikit/documentation/UIKit/UISceneSession/scene","doc://com.apple.uikit/documentation/UIKit/UISceneSession/role-swift.property","doc://com.apple.uikit/documentation/UIKit/UISceneSession/Role-swift.struct"]},{"anchor":"Getting-the-scene-configuration-details","identifiers":["doc://com.apple.uikit/documentation/UIKit/UISceneSession/configuration","doc://com.apple.uikit/documentation/UIKit/UISceneConfiguration"],"title":"Getting the scene configuration details"},{"anchor":"Identifying-the-scene","identifiers":["doc://com.apple.uikit/documentation/UIKit/UISceneSession/persistentIdentifier"],"title":"Identifying the scene"},{"anchor":"Getting-additional-session-information","identifiers":["doc://com.apple.uikit/documentation/UIKit/UISceneSession/stateRestorationActivity","doc://com.apple.uikit/documentation/UIKit/UISceneSession/userInfo"],"title":"Getting additional session information"}],"op":"replace"},{"path":"/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc://com.externally.resolved.symbol/c:objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"]}],"op":"replace"},{"path":"/seeAlsoSections","value":[{"anchor":"Configuration","title":"Configuration","identifiers":["doc://com.apple.uikit/documentation/UIKit/specifying-the-scenes-your-app-supports","doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest","doc://com.apple.uikit/documentation/UIKit/UISceneConfiguration"],"generated":true}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"UISceneSession"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneSession~1Role-swift.struct/title","value":"UISceneSessionRole","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneSession~1Role-swift.struct/fragments","value":[{"kind":"identifier","text":"UISceneSessionRole"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneSession~1Role-swift.struct/navigatorTitle","value":[{"text":"UISceneSessionRole","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title","value":"NSObject","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneSession~1configuration/title","value":"configuration","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneSession~1configuration/fragments","value":[{"text":"configuration","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneSession~1persistentIdentifier/title","value":"persistentIdentifier","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneSession~1persistentIdentifier/fragments","value":[{"text":"persistentIdentifier","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1requestSceneSessionActivation(_:userActivity:options:errorHandler:)/title","value":"requestSceneSessionActivation:userActivity:options:errorHandler:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1requestSceneSessionActivation(_:userActivity:options:errorHandler:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"requestSceneSessionActivation:userActivity:options:errorHandler:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneSession~1stateRestorationActivity/title","value":"stateRestorationActivity"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneSession~1stateRestorationActivity/fragments","value":[{"kind":"identifier","text":"stateRestorationActivity"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneSession/title","value":"UISceneSession"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneSession/fragments","value":[{"text":"UISceneSession","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneSession/navigatorTitle","value":[{"text":"UISceneSession","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/title","value":"UIApplication"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/fragments","value":[{"kind":"identifier","text":"UIApplication"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/navigatorTitle","value":[{"kind":"identifier","text":"UIApplication"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneSession~1scene/title","value":"scene"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneSession~1scene/fragments","value":[{"kind":"identifier","text":"scene"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneConfiguration/title","value":"UISceneConfiguration"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneConfiguration/fragments","value":[{"text":"UISceneConfiguration","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneConfiguration/navigatorTitle","value":[{"kind":"identifier","text":"UISceneConfiguration"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneSession~1role-swift.property/title","value":"role"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneSession~1role-swift.property/fragments","value":[{"text":"role","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneSession~1userInfo/title","value":"userInfo"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneSession~1userInfo/fragments","value":[{"text":"userInfo","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}