{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uisceneconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uisceneconfiguration"]}],"abstract":[{"type":"text","text":"Information about the objects and storyboard for UKit to use when creating a particular scene."}],"sections":[],"topicSections":[{"anchor":"Creating-a-configuration-object","title":"Creating a configuration object","identifiers":["doc://com.apple.uikit/documentation/UIKit/UISceneConfiguration/init(name:sessionRole:)"]},{"anchor":"Specifying-the-scene-creation-details","title":"Specifying the scene creation details","identifiers":["doc://com.apple.uikit/documentation/UIKit/UISceneConfiguration/sceneClass","doc://com.apple.uikit/documentation/UIKit/UISceneConfiguration/delegateClass","doc://com.apple.uikit/documentation/UIKit/UISceneConfiguration/storyboard"]},{"anchor":"Getting-the-configuration-attributes","title":"Getting the configuration attributes","identifiers":["doc://com.apple.uikit/documentation/UIKit/UISceneConfiguration/name","doc://com.apple.uikit/documentation/UIKit/UISceneConfiguration/role","doc://com.apple.uikit/documentation/UIKit/UISceneSession/Role-swift.struct"]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UISceneConfiguration"},"metadata":{"role":"symbol","title":"UISceneConfiguration","platforms":[{"name":"iOS","deprecated":false,"unavailable":false,"introducedAt":"13.0","beta":false},{"name":"iPadOS","deprecated":false,"unavailable":false,"introducedAt":"13.0","beta":false},{"name":"Mac Catalyst","deprecated":false,"unavailable":false,"introducedAt":"13.1","beta":false},{"name":"tvOS","deprecated":false,"unavailable":false,"introducedAt":"13.0","beta":false},{"name":"visionOS","deprecated":false,"unavailable":false,"introducedAt":"1.0","beta":false}],"modules":[{"name":"UIKit"}],"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UISceneConfiguration","kind":"identifier"}],"externalID":"c:objc(cs)UISceneConfiguration","navigatorTitle":[{"text":"UISceneConfiguration","kind":"identifier"}],"roleHeading":"Class"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"identifier":"doc://com.externally.resolved.symbol/s:ScM","text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UISceneConfiguration","kind":"identifier"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"text":"Use a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UISceneConfiguration"},{"text":" object to specify information that UIKit can use to create a new scene for your app. Specifically, you must provide the class of the specific scene you want, the class of the scene delegate object your app uses to manage scenes of that type, and a storyboard containing the scene’s initial view controller.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"When the user requests a new instance of your app’s user interface, UIKit looks in your app’s "},{"type":"codeVoice","code":"Info.plist"},{"type":"text","text":" file for the configuration data it needs to create the corresponding scene object. It then packages that information into a "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UISceneConfiguration"},{"type":"text","text":" object and delivers it as part of the session it passes to the "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:configurationForConnecting:options:)"},{"type":"text","text":" method of your app delegate. You can accept that configuration data as is or create a return a new "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UISceneConfiguration"},{"type":"text","text":" object with a different set of configuration details."}]}],"kind":"content"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc://com.externally.resolved.symbol/c:objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc://com.externally.resolved.symbol/s:s7CVarArgP","doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/c:objc(pl)NSCoding","doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","doc://com.externally.resolved.symbol/c:objc(pl)NSObject","doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding","doc://com.externally.resolved.symbol/s:s8SendableP"],"kind":"relationships","type":"conformsTo"}],"seeAlsoSections":[{"anchor":"Configuration","title":"Configuration","identifiers":["doc://com.apple.uikit/documentation/UIKit/specifying-the-scenes-your-app-supports","doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest","doc://com.apple.uikit/documentation/UIKit/UISceneSession"],"generated":true}],"references":{"doc://com.externally.resolved.symbol/s:s7CVarArgP":{"abstract":[{"type":"text","text":"A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVarArg"}],"identifier":"doc://com.externally.resolved.symbol/s:s7CVarArgP","type":"topic","title":"CVarArg","kind":"symbol","role":"symbol","url":"/documentation/Swift/CVarArg"},"doc://com.apple.uikit/documentation/UIKit/UISceneSession/Role-swift.struct":{"title":"UISceneSession.Role","url":"/documentation/uikit/uiscenesession/role-swift.struct","role":"symbol","abstract":[{"text":"Constants that indicate the possible roles for a scene.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"Role","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UISceneSession/Role-swift.struct","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Role","kind":"identifier"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP":{"identifier":"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","kind":"symbol","type":"topic","title":"CustomDebugStringConvertible","url":"/documentation/Swift/CustomDebugStringConvertible","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomDebugStringConvertible"}],"role":"symbol","abstract":[{"type":"text","text":"A type with a customized textual representation suitable for debugging purposes."}]},"doc://com.externally.resolved.symbol/s:s8SendableP":{"abstract":[{"type":"text","text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races."}],"url":"/documentation/Swift/Sendable","identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}],"role":"symbol","title":"Sendable","type":"topic","kind":"symbol"},"doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest":{"kind":"symbol","role":"symbol","title":"UIApplicationSceneManifest","identifier":"doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest","type":"topic","url":"/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest","abstract":[{"text":"The information about the app’s scene-based life-cycle support.","type":"text"}]},"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP":{"identifier":"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","kind":"symbol","type":"topic","title":"CustomStringConvertible","url":"/documentation/Swift/CustomStringConvertible","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomStringConvertible"}],"role":"symbol","abstract":[{"text":"A type with a customized textual representation.","type":"text"}]},"doc://com.externally.resolved.symbol/s:SQ":{"abstract":[{"type":"text","text":"A type that can be compared for value equality."}],"url":"/documentation/Swift/Equatable","identifier":"doc://com.externally.resolved.symbol/s:SQ","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"role":"symbol","title":"Equatable","type":"topic","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UISceneConfiguration/delegateClass":{"kind":"symbol","url":"/documentation/uikit/uisceneconfiguration/delegateclass","abstract":[{"text":"The class of the custom delegate object that you want UIKit to create.","type":"text"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UISceneConfiguration/delegateClass","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegateClass","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s8AnyClassa","text":"AnyClass","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","title":"delegateClass","navigatorTitle":[{"text":"delegateClass","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UISceneConfiguration":{"navigatorTitle":[{"text":"UISceneConfiguration","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UISceneConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"text":"Information about the objects and storyboard for UKit to use when creating a particular scene.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISceneConfiguration","title":"UISceneConfiguration","url":"/documentation/uikit/uisceneconfiguration","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:configurationForConnecting:options:)":{"navigatorTitle":[{"text":"application:configurationForConnectingSceneSession:options:","kind":"identifier"}],"role":"symbol","type":"topic","title":"application(_:configurationForConnecting:options:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:configurationForConnecting:options:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"application","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"configurationForConnecting","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UISceneSession","preciseIdentifier":"c:objc(cs)UISceneSession","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIScene","preciseIdentifier":"c:objc(cs)UIScene","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"ConnectionOptions","preciseIdentifier":"c:objc(cs)UISceneConnectionOptions","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UISceneConfiguration","preciseIdentifier":"c:objc(cs)UISceneConfiguration","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Retrieves the configuration data for UIKit to use when creating a new scene."}],"kind":"symbol","url":"/documentation/uikit/uiapplicationdelegate/application(_:configurationforconnecting:options:)"},"doc://com.apple.uikit/documentation/UIKit/UISceneConfiguration/role":{"abstract":[{"type":"text","text":"The role assigned to the scene configuration."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISceneConfiguration/role","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"role","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UISceneSession","text":"UISceneSession","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@UISceneSessionRole","text":"Role","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"role","kind":"identifier"}],"type":"topic","title":"role","role":"symbol","url":"/documentation/uikit/uisceneconfiguration/role"},"doc://com.externally.resolved.symbol/c:objc(pl)NSCoding":{"url":"/documentation/foundation/nscoding","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCoding","role":"symbol","fragments":[{"kind":"text","text":"protocol "},{"kind":"identifier","text":"NSCoding"}],"type":"topic","title":"NSCoding","kind":"symbol","abstract":[{"text":"A protocol that enables an object to be encoded and decoded for archiving and distribution.","type":"text"}]},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"title":"NSObjectProtocol","type":"topic","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","role":"symbol","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"kind":"symbol","url":"/documentation/objectivec/nsobjectprotocol"},"doc://com.externally.resolved.symbol/s:SH":{"abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}],"url":"/documentation/Swift/Hashable","identifier":"doc://com.externally.resolved.symbol/s:SH","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hashable","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SQ","text":"Equatable","kind":"typeIdentifier"}],"role":"symbol","title":"Hashable","type":"topic","kind":"symbol"},"doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding":{"fragments":[{"kind":"text","text":"protocol "},{"kind":"identifier","text":"NSSecureCoding"}],"type":"topic","abstract":[{"text":"A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.","type":"text"}],"role":"symbol","kind":"symbol","url":"/documentation/foundation/nssecurecoding","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding","title":"NSSecureCoding"},"doc://com.apple.uikit/documentation/UIKit/UISceneSession":{"title":"UISceneSession","type":"topic","navigatorTitle":[{"text":"UISceneSession","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UISceneSession","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISceneSession","role":"symbol","url":"/documentation/uikit/uiscenesession","kind":"symbol","abstract":[{"text":"An object that contains information about one of your app’s scenes.","type":"text"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.externally.resolved.symbol/c:objc(cs)NSObject":{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSObject","role":"symbol","kind":"symbol","url":"/documentation/objectivec/nsobject","title":"NSObject","type":"topic","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSObject"}],"abstract":[{"text":"The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/specifying-the-scenes-your-app-supports":{"abstract":[{"text":"Tell the system about your app’s scenes, including the objects you use to manage each scene and its initial user interface.","type":"text"}],"kind":"article","role":"article","title":"Specifying the scenes your app supports","identifier":"doc://com.apple.uikit/documentation/UIKit/specifying-the-scenes-your-app-supports","type":"topic","url":"/documentation/uikit/specifying-the-scenes-your-app-supports"},"doc://com.apple.uikit/documentation/UIKit/UISceneConfiguration/sceneClass":{"kind":"symbol","url":"/documentation/uikit/uisceneconfiguration/sceneclass","abstract":[{"text":"The class of the scene object that you want UIKit to create.","type":"text"}],"type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UISceneConfiguration/sceneClass","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sceneClass","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s8AnyClassa","text":"AnyClass","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","title":"sceneClass","navigatorTitle":[{"text":"sceneClass","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UISceneConfiguration/name":{"abstract":[{"type":"text","text":"The app-specific name assigned to the scene configuration."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISceneConfiguration/name","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"name","kind":"identifier"}],"type":"topic","title":"name","role":"symbol","url":"/documentation/uikit/uisceneconfiguration/name"},"doc://com.apple.uikit/documentation/UIKit/UISceneConfiguration/configurationWithName:sessionRole:":{"role":"symbol","abstract":[{"text":"Returns a scene-configuration object with the specified role and app-specific name.","type":"text"}],"title":"configurationWithName:sessionRole:","type":"topic","fragments":[{"text":"+ ","kind":"text"},{"text":"configurationWithName:sessionRole:","kind":"identifier"}],"navigatorTitle":[{"text":"configurationWithName:sessionRole:","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISceneConfiguration/configurationWithName:sessionRole:","kind":"symbol","url":"/documentation/uikit/uisceneconfiguration/configurationwithname:sessionrole:"},"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying":{"kind":"symbol","abstract":[{"text":"A protocol that objects adopt to provide functional copies of themselves.","type":"text"}],"url":"/documentation/foundation/nscopying","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSCopying","kind":"identifier"}],"title":"NSCopying","type":"topic","identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UISceneConfiguration/init(name:sessionRole:)":{"role":"symbol","abstract":[{"text":"Creates a scene-configuration object with the specified role and app-specific name.","type":"text"}],"title":"init(name:sessionRole:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"sessionRole","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UISceneSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISceneSession"},{"text":".","kind":"text"},{"text":"Role","kind":"typeIdentifier","preciseIdentifier":"c:@T@UISceneSessionRole"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithName:sessionRole:","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISceneConfiguration/init(name:sessionRole:)","kind":"symbol","url":"/documentation/uikit/uisceneconfiguration/init(name:sessionrole:)"},"doc://com.apple.uikit/documentation/UIKit/UISceneConfiguration/storyboard":{"kind":"symbol","title":"storyboard","role":"symbol","navigatorTitle":[{"text":"storyboard","kind":"identifier"}],"url":"/documentation/uikit/uisceneconfiguration/storyboard","identifier":"doc://com.apple.uikit/documentation/UIKit/UISceneConfiguration/storyboard","type":"topic","abstract":[{"type":"text","text":"The storyboard object that contains your scene’s initial view controller."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"storyboard"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIStoryboard","text":"UIStoryboard","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"deprecated":false,"introducedAt":"13.0","name":"iOS","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"13.0","name":"iPadOS","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"13.1","name":"Mac Catalyst","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"13.0","name":"tvOS","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"1.0","name":"visionOS","unavailable":false,"beta":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Class","op":"replace"},{"path":"/metadata/title","value":"UISceneConfiguration","op":"replace"},{"path":"/metadata/symbolKind","value":"class","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"identifier","text":"UISceneConfiguration"}],"op":"replace"},{"path":"/metadata/navigatorTitle","value":[{"text":"UISceneConfiguration","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"op":"replace"},{"path":"/topicSections","value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UISceneConfiguration/configurationWithName:sessionRole:","doc://com.apple.uikit/documentation/UIKit/UISceneConfiguration/init(name:sessionRole:)"],"title":"Creating a configuration object","anchor":"Creating-a-configuration-object"},{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UISceneConfiguration/sceneClass","doc://com.apple.uikit/documentation/UIKit/UISceneConfiguration/delegateClass","doc://com.apple.uikit/documentation/UIKit/UISceneConfiguration/storyboard"],"title":"Specifying the scene creation details","anchor":"Specifying-the-scene-creation-details"},{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UISceneConfiguration/name","doc://com.apple.uikit/documentation/UIKit/UISceneConfiguration/role","doc://com.apple.uikit/documentation/UIKit/UISceneSession/Role-swift.struct"],"title":"Getting the configuration attributes","anchor":"Getting-the-configuration-attributes"}],"op":"replace"},{"path":"/relationshipsSections","value":[{"identifiers":["doc://com.externally.resolved.symbol/c:objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc://com.externally.resolved.symbol/c:objc(pl)NSCopying","doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"op":"replace"},{"path":"/seeAlsoSections","value":[{"generated":true,"anchor":"Configuration","title":"Configuration","identifiers":["doc://com.apple.uikit/documentation/UIKit/specifying-the-scenes-your-app-supports","doc://com.apple.documentation/documentation/BundleResources/Information-Property-List/UIApplicationSceneManifest","doc://com.apple.uikit/documentation/UIKit/UISceneSession"]}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UISceneConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"},"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneSession~1Role-swift.struct/title","value":"UISceneSessionRole","op":"replace"},{"op":"replace","value":[{"text":"UISceneSessionRole","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneSession~1Role-swift.struct/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UISceneSessionRole"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneSession~1Role-swift.struct/navigatorTitle"},{"op":"replace","value":"delegateClass","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneConfiguration~1delegateClass/title"},{"op":"replace","value":[{"text":"delegateClass","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneConfiguration~1delegateClass/fragments"},{"op":"replace","value":"UISceneConfiguration","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneConfiguration/title"},{"op":"replace","value":[{"kind":"identifier","text":"UISceneConfiguration"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneConfiguration/fragments"},{"op":"replace","value":[{"text":"UISceneConfiguration","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneConfiguration/navigatorTitle"},{"op":"replace","value":"application:configurationForConnectingSceneSession:options:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:configurationForConnecting:options:)/title"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:configurationForConnecting:options:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:configurationForConnectingSceneSession:options:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneConfiguration~1role/title","value":"role","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneConfiguration~1role/fragments","value":[{"text":"role","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title","value":"NSObject","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneSession/title","value":"UISceneSession","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneSession/fragments","value":[{"text":"UISceneSession","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneSession/navigatorTitle","value":[{"text":"UISceneSession","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneConfiguration~1sceneClass/title","value":"sceneClass","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneConfiguration~1sceneClass/fragments","value":[{"text":"sceneClass","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneConfiguration~1name/title","value":"name","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneConfiguration~1name/fragments","value":[{"kind":"identifier","text":"name"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneConfiguration~1init(name:sessionRole:)/title","value":"initWithName:sessionRole:","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneConfiguration~1init(name:sessionRole:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithName:sessionRole:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneConfiguration~1storyboard/title","value":"storyboard","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneConfiguration~1storyboard/fragments","value":[{"kind":"identifier","text":"storyboard"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}