{
  "abstract": [
    {
      "text": "A semantic description of the view’s contents, used to determine whether the view should be flipped when switching between left-to-right and right-to-left layouts.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UISemanticContentAttribute",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UISemanticContentAttribute"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UISemanticContentAttribute"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "UISemanticContentAttribute"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UISemanticContentAttribute"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Axis": {
      "abstract": [
        {
          "text": "Keys that specify a horizontal or vertical layout constraint between objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Axis"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Axis",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Axis"
        }
      ],
      "role": "symbol",
      "title": "NSLayoutConstraint.Axis",
      "type": "topic",
      "url": "/documentation/uikit/nslayoutconstraint/axis"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute": {
      "abstract": [
        {
          "text": "A semantic description of the view’s contents, used to determine whether the view should be flipped when switching between left-to-right and right-to-left layouts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISemanticContentAttribute"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISemanticContentAttribute"
        }
      ],
      "role": "symbol",
      "title": "UISemanticContentAttribute",
      "type": "topic",
      "url": "/documentation/uikit/uisemanticcontentattribute"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/forceLeftToRight": {
      "abstract": [
        {
          "text": "A view that’s always displayed using a left-to-right layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forceLeftToRight"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/forceLeftToRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISemanticContentAttributeForceLeftToRight"
        }
      ],
      "role": "symbol",
      "title": "UISemanticContentAttribute.forceLeftToRight",
      "type": "topic",
      "url": "/documentation/uikit/uisemanticcontentattribute/forcelefttoright"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/forceRightToLeft": {
      "abstract": [
        {
          "text": "A view that’s always displayed using a right-to-left layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forceRightToLeft"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/forceRightToLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISemanticContentAttributeForceRightToLeft"
        }
      ],
      "role": "symbol",
      "title": "UISemanticContentAttribute.forceRightToLeft",
      "type": "topic",
      "url": "/documentation/uikit/uisemanticcontentattribute/forcerighttoleft"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/uisemanticcontentattribute/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/playback": {
      "abstract": [
        {
          "text": "A view representing the playback controls, such as Play, Rewind, or Fast Forward buttons or playhead scrubbers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "playback"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/playback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISemanticContentAttributePlayback"
        }
      ],
      "role": "symbol",
      "title": "UISemanticContentAttribute.playback",
      "type": "topic",
      "url": "/documentation/uikit/uisemanticcontentattribute/playback"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/spatial": {
      "abstract": [
        {
          "text": "A view representing a directional control, such as a segment control for text alignment, or a D-pad control for a game.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "spatial"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/spatial",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISemanticContentAttributeSpatial"
        }
      ],
      "role": "symbol",
      "title": "UISemanticContentAttribute.spatial",
      "type": "topic",
      "url": "/documentation/uikit/uisemanticcontentattribute/spatial"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/unspecified": {
      "abstract": [
        {
          "text": "The default value for views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISemanticContentAttributeUnspecified"
        }
      ],
      "role": "symbol",
      "title": "UISemanticContentAttribute.unspecified",
      "type": "topic",
      "url": "/documentation/uikit/uisemanticcontentattribute/unspecified"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationCurve": {
      "abstract": [
        {
          "text": "Specifies the supported animation curves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AnimationCurve"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationCurve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AnimationCurve"
        }
      ],
      "role": "symbol",
      "title": "UIView.AnimationCurve",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationcurve"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions": {
      "abstract": [
        {
          "text": "Options for animating views using block objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AnimationOptions"
        }
      ],
      "role": "symbol",
      "title": "UIView.AnimationOptions",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationTransition": {
      "abstract": [
        {
          "text": "Animation transition options for use in an animation block object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AnimationTransition"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationTransition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AnimationTransition"
        }
      ],
      "role": "symbol",
      "title": "UIView.AnimationTransition",
      "type": "topic",
      "url": "/documentation/uikit/uiview/animationtransition"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/AutoresizingMask-swift.struct": {
      "abstract": [
        {
          "text": "Options for automatic view resizing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AutoresizingMask"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/AutoresizingMask-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AutoresizingMask"
        }
      ],
      "role": "symbol",
      "title": "UIView.AutoresizingMask",
      "type": "topic",
      "url": "/documentation/uikit/uiview/autoresizingmask-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions": {
      "abstract": [
        {
          "text": "Options for configuring keyframe-based animations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "KeyframeAnimationOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "KeyframeAnimationOptions"
        }
      ],
      "role": "symbol",
      "title": "UIView.KeyframeAnimationOptions",
      "type": "topic",
      "url": "/documentation/uikit/uiview/keyframeanimationoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/SystemAnimation": {
      "abstract": [
        {
          "text": "Option to remove the views from the hierarchy when animation is complete.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SystemAnimation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/SystemAnimation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SystemAnimation"
        }
      ],
      "role": "symbol",
      "title": "UIView.SystemAnimation",
      "type": "topic",
      "url": "/documentation/uikit/uiview/systemanimation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/TintAdjustmentMode-swift.enum": {
      "abstract": [
        {
          "text": "The tint adjustment mode for the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TintAdjustmentMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/TintAdjustmentMode-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TintAdjustmentMode"
        }
      ],
      "role": "symbol",
      "title": "UIView.TintAdjustmentMode",
      "type": "topic",
      "url": "/documentation/uikit/uiview/tintadjustmentmode-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/layoutFittingCompressedSize": {
      "abstract": [
        {
          "text": "The option to use the smallest possible size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layoutFittingCompressedSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/layoutFittingCompressedSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILayoutFittingCompressedSize"
        }
      ],
      "role": "symbol",
      "title": "layoutFittingCompressedSize",
      "type": "topic",
      "url": "/documentation/uikit/uiview/layoutfittingcompressedsize"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/layoutFittingExpandedSize": {
      "abstract": [
        {
          "text": "The option to use the largest possible size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layoutFittingExpandedSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/layoutFittingExpandedSize",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILayoutFittingExpandedSize"
        }
      ],
      "role": "symbol",
      "title": "layoutFittingExpandedSize",
      "type": "topic",
      "url": "/documentation/uikit/uiview/layoutfittingexpandedsize"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/noIntrinsicMetric": {
      "abstract": [
        {
          "text": "The absence of an intrinsic metric for a given numeric view property.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "noIntrinsicMetric"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/noIntrinsicMetric",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewNoIntrinsicMetric"
        }
      ],
      "role": "symbol",
      "title": "noIntrinsicMetric",
      "type": "topic",
      "url": "/documentation/uikit/uiview/nointrinsicmetric"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationCurve",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationTransition",
        "doc://com.apple.uikit/documentation/UIKit/UIView/SystemAnimation",
        "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions",
        "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Axis",
        "doc://com.apple.uikit/documentation/UIKit/UIView/TintAdjustmentMode-swift.enum",
        "doc://com.apple.uikit/documentation/UIKit/UIView/layoutFittingCompressedSize",
        "doc://com.apple.uikit/documentation/UIKit/UIView/layoutFittingExpandedSize",
        "doc://com.apple.uikit/documentation/UIKit/UIView/noIntrinsicMetric",
        "doc://com.apple.uikit/documentation/UIKit/UIView/AutoresizingMask-swift.struct"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/unspecified",
        "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/playback",
        "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/spatial",
        "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/forceLeftToRight",
        "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/forceRightToLeft"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UISemanticContentAttribute"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISemanticContentAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISemanticContentAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/unspecified",
                "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/playback",
                "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/spatial",
                "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/forceLeftToRight",
                "doc://com.apple.uikit/documentation/UIKit/UISemanticContentAttribute/forceRightToLeft"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationCurve",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationOptions",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AnimationTransition",
                "doc://com.apple.uikit/documentation/UIKit/UIView/SystemAnimation",
                "doc://com.apple.uikit/documentation/UIKit/UIView/KeyframeAnimationOptions",
                "doc://com.apple.uikit/documentation/UIKit/NSLayoutConstraint/Axis",
                "doc://com.apple.uikit/documentation/UIKit/UIView/TintAdjustmentMode-swift.enum",
                "doc://com.apple.uikit/documentation/UIKit/UIView/layoutFittingCompressedSize",
                "doc://com.apple.uikit/documentation/UIKit/UIView/layoutFittingExpandedSize",
                "doc://com.apple.uikit/documentation/UIKit/UIView/noIntrinsicMetric",
                "doc://com.apple.uikit/documentation/UIKit/UIView/AutoresizingMask-swift.struct"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UISemanticContentAttribute"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISemanticContentAttribute/title",
          "value": "UISemanticContentAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISemanticContentAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISemanticContentAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISemanticContentAttribute/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISemanticContentAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISemanticContentAttribute~1unspecified/title",
          "value": "UISemanticContentAttributeUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISemanticContentAttribute~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISemanticContentAttributeUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationCurve/title",
          "value": "UIViewAnimationCurve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationCurve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationCurve/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISemanticContentAttribute~1spatial/title",
          "value": "UISemanticContentAttributeSpatial"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISemanticContentAttribute~1spatial/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISemanticContentAttributeSpatial"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1layoutFittingExpandedSize/title",
          "value": "UILayoutFittingExpandedSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1layoutFittingExpandedSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UILayoutFittingExpandedSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1SystemAnimation/title",
          "value": "UISystemAnimation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1SystemAnimation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISystemAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1SystemAnimation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISystemAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Axis/title",
          "value": "UILayoutConstraintAxis"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Axis/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UILayoutConstraintAxis"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSLayoutConstraint~1Axis/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILayoutConstraintAxis"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISemanticContentAttribute~1forceLeftToRight/title",
          "value": "UISemanticContentAttributeForceLeftToRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISemanticContentAttribute~1forceLeftToRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISemanticContentAttributeForceLeftToRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AutoresizingMask-swift.struct/title",
          "value": "UIViewAutoresizing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AutoresizingMask-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAutoresizing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AutoresizingMask-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAutoresizing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1TintAdjustmentMode-swift.enum/title",
          "value": "UIViewTintAdjustmentMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1TintAdjustmentMode-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewTintAdjustmentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1TintAdjustmentMode-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewTintAdjustmentMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationTransition/title",
          "value": "UIViewAnimationTransition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationTransition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationTransition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationTransition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationTransition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions/title",
          "value": "UIViewAnimationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1AnimationOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewAnimationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISemanticContentAttribute~1playback/title",
          "value": "UISemanticContentAttributePlayback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISemanticContentAttribute~1playback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISemanticContentAttributePlayback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions/title",
          "value": "UIViewKeyframeAnimationOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewKeyframeAnimationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1KeyframeAnimationOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewKeyframeAnimationOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISemanticContentAttribute~1forceRightToLeft/title",
          "value": "UISemanticContentAttributeForceRightToLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISemanticContentAttribute~1forceRightToLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISemanticContentAttributeForceRightToLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1layoutFittingCompressedSize/title",
          "value": "UILayoutFittingCompressedSize"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1layoutFittingCompressedSize/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UILayoutFittingCompressedSize"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1noIntrinsicMetric/title",
          "value": "UIViewNoIntrinsicMetric"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1noIntrinsicMetric/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewNoIntrinsicMetric"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uisemanticcontentattribute"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uisemanticcontentattribute"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
