{
  "abstract": [
    {
      "text": "A collection of optional methods that you implement to make a search bar control functional.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UISearchBarDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UISearchBarDelegate"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UISearchBarDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "UISearchBarDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UISearchBarDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarPositioningDelegate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)UIBarPositioningDelegate",
              "text": "UIBarPositioningDelegate"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBar",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object provides the user interface for a search field on a bar, but it’s the application’s responsibility to implement the actions when buttons are tapped. At a minimum, the delegate needs to perform the actual search when text is entered in the text field.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarPositioning": {
      "abstract": [
        {
          "text": "A set of methods for defining the positioning of bars in iOS apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIBarPositioning"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarPositioning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarPositioning"
        }
      ],
      "role": "symbol",
      "title": "UIBarPositioning",
      "type": "topic",
      "url": "/documentation/uikit/uibarpositioning"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarPositioningDelegate": {
      "abstract": [
        {
          "text": "A set of methods that support the positioning of a bar that conforms to the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarPositioning",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIBarPositioningDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarPositioningDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarPositioningDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIBarPositioningDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uibarpositioningdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBar": {
      "abstract": [
        {
          "text": "A specialized view for receiving search-related information from the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISearchBar"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISearchBar"
        }
      ],
      "role": "symbol",
      "title": "UISearchBar",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbar"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBar/delegate": {
      "abstract": [
        {
          "text": "The search bar’s delegate object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UISearchBarDelegate",
          "text": "UISearchBarDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBar/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbar/delegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate": {
      "abstract": [
        {
          "text": "A collection of optional methods that you implement to make a search bar control functional.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISearchBarDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISearchBarDelegate"
        }
      ],
      "role": "symbol",
      "title": "UISearchBarDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbardelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBar(_:selectedScopeButtonIndexDidChange:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the scope button selection changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchBar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISearchBar",
          "text": "UISearchBar"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "selectedScopeButtonIndexDidChange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBar(_:selectedScopeButtonIndexDidChange:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "searchBar:selectedScopeButtonIndexDidChange:"
        }
      ],
      "role": "symbol",
      "title": "searchBar(_:selectedScopeButtonIndexDidChange:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbardelegate/searchbar(_:selectedscopebuttonindexdidchange:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBar(_:shouldChangeTextIn:replacementText:)": {
      "abstract": [
        {
          "text": "Ask the delegate if text in a specified range should be replaced with given text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchBar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISearchBar",
          "text": "UISearchBar"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shouldChangeTextIn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "replacementText"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBar(_:shouldChangeTextIn:replacementText:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "searchBar:shouldChangeTextInRange:replacementText:"
        }
      ],
      "role": "symbol",
      "title": "searchBar(_:shouldChangeTextIn:replacementText:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbardelegate/searchbar(_:shouldchangetextin:replacementtext:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBar(_:textDidChange:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user changed the search text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchBar"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISearchBar",
          "text": "UISearchBar"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "textDidChange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBar(_:textDidChange:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "searchBar:textDidChange:"
        }
      ],
      "role": "symbol",
      "title": "searchBar(_:textDidChange:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbardelegate/searchbar(_:textdidchange:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarBookmarkButtonClicked(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the bookmark button was tapped.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchBarBookmarkButtonClicked"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISearchBar",
          "text": "UISearchBar"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarBookmarkButtonClicked(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "searchBarBookmarkButtonClicked:"
        }
      ],
      "role": "symbol",
      "title": "searchBarBookmarkButtonClicked(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbardelegate/searchbarbookmarkbuttonclicked(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarCancelButtonClicked(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the cancel button was tapped.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchBarCancelButtonClicked"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISearchBar",
          "text": "UISearchBar"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarCancelButtonClicked(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "searchBarCancelButtonClicked:"
        }
      ],
      "role": "symbol",
      "title": "searchBarCancelButtonClicked(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbardelegate/searchbarcancelbuttonclicked(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarResultsListButtonClicked(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the search results list button was tapped.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchBarResultsListButtonClicked"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISearchBar",
          "text": "UISearchBar"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarResultsListButtonClicked(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "searchBarResultsListButtonClicked:"
        }
      ],
      "role": "symbol",
      "title": "searchBarResultsListButtonClicked(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbardelegate/searchbarresultslistbuttonclicked(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarSearchButtonClicked(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the search button was tapped.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchBarSearchButtonClicked"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISearchBar",
          "text": "UISearchBar"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarSearchButtonClicked(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "searchBarSearchButtonClicked:"
        }
      ],
      "role": "symbol",
      "title": "searchBarSearchButtonClicked(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbardelegate/searchbarsearchbuttonclicked(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarShouldBeginEditing(_:)": {
      "abstract": [
        {
          "text": "Asks the delegate if editing should begin in the specified search bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchBarShouldBeginEditing"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISearchBar",
          "text": "UISearchBar"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarShouldBeginEditing(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "searchBarShouldBeginEditing:"
        }
      ],
      "role": "symbol",
      "title": "searchBarShouldBeginEditing(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbardelegate/searchbarshouldbeginediting(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarShouldEndEditing(_:)": {
      "abstract": [
        {
          "text": "Asks the delegate if editing should stop in the specified search bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchBarShouldEndEditing"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISearchBar",
          "text": "UISearchBar"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarShouldEndEditing(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "searchBarShouldEndEditing:"
        }
      ],
      "role": "symbol",
      "title": "searchBarShouldEndEditing(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbardelegate/searchbarshouldendediting(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarTextDidBeginEditing(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate when the user begins editing the search text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchBarTextDidBeginEditing"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISearchBar",
          "text": "UISearchBar"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarTextDidBeginEditing(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "searchBarTextDidBeginEditing:"
        }
      ],
      "role": "symbol",
      "title": "searchBarTextDidBeginEditing(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbardelegate/searchbartextdidbeginediting(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarTextDidEndEditing(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user finished editing the search text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchBarTextDidEndEditing"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISearchBar",
          "text": "UISearchBar"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarTextDidEndEditing(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "searchBarTextDidEndEditing:"
        }
      ],
      "role": "symbol",
      "title": "searchBarTextDidEndEditing(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbardelegate/searchbartextdidendediting(_:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.apple.uikit/documentation/UIKit/UIBarPositioningDelegate"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Handling-search-bar-interactions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISearchBar/delegate"
      ],
      "title": "Handling search bar interactions"
    }
  ],
  "topicSections": [
    {
      "anchor": "Managing-the-search-text",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBar(_:textDidChange:)",
        "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBar(_:shouldChangeTextIn:replacementText:)",
        "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarShouldBeginEditing(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarTextDidBeginEditing(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarShouldEndEditing(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarTextDidEndEditing(_:)"
      ],
      "title": "Managing the search text"
    },
    {
      "anchor": "Responding-to-clicks-in-search-controls",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarBookmarkButtonClicked(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarCancelButtonClicked(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarSearchButtonClicked(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarResultsListButtonClicked(_:)"
      ],
      "title": "Responding to clicks in search controls"
    },
    {
      "anchor": "Responding-to-scope-button-changes",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBar(_:selectedScopeButtonIndexDidChange:)"
      ],
      "title": "Responding to scope button changes"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UISearchBarDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchBarDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchBarDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Managing-the-search-text",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBar(_:textDidChange:)",
                "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBar(_:shouldChangeTextIn:replacementText:)",
                "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarShouldBeginEditing(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarTextDidBeginEditing(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarShouldEndEditing(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarTextDidEndEditing(_:)"
              ],
              "title": "Managing the search text"
            },
            {
              "anchor": "Responding-to-clicks-in-search-controls",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarBookmarkButtonClicked(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarCancelButtonClicked(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarSearchButtonClicked(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBarResultsListButtonClicked(_:)"
              ],
              "title": "Responding to clicks in search controls"
            },
            {
              "anchor": "Responding-to-scope-button-changes",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UISearchBarDelegate/searchBar(_:selectedScopeButtonIndexDidChange:)"
              ],
              "title": "Responding to scope button changes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIBarPositioningDelegate"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Handling-search-bar-interactions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UISearchBar/delegate"
              ],
              "title": "Handling search bar interactions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UISearchBarDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarPositioningDelegate",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)UIBarPositioningDelegate",
                    "text": "UIBarPositioningDelegate"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarTextDidEndEditing(_:)/title",
          "value": "searchBarTextDidEndEditing:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarTextDidEndEditing(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "searchBarTextDidEndEditing:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarShouldBeginEditing(_:)/title",
          "value": "searchBarShouldBeginEditing:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarShouldBeginEditing(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "searchBarShouldBeginEditing:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarShouldEndEditing(_:)/title",
          "value": "searchBarShouldEndEditing:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarShouldEndEditing(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "searchBarShouldEndEditing:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarPositioningDelegate/title",
          "value": "UIBarPositioningDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarPositioningDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarPositioningDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarPositioningDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarPositioningDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBar(_:selectedScopeButtonIndexDidChange:)/title",
          "value": "searchBar:selectedScopeButtonIndexDidChange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBar(_:selectedScopeButtonIndexDidChange:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "searchBar:selectedScopeButtonIndexDidChange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarSearchButtonClicked(_:)/title",
          "value": "searchBarSearchButtonClicked:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarSearchButtonClicked(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "searchBarSearchButtonClicked:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBar(_:shouldChangeTextIn:replacementText:)/title",
          "value": "searchBar:shouldChangeTextInRange:replacementText:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBar(_:shouldChangeTextIn:replacementText:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "searchBar:shouldChangeTextInRange:replacementText:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarPositioning/title",
          "value": "UIBarPositioning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarPositioning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarPositioning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarPositioning/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarPositioning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarTextDidBeginEditing(_:)/title",
          "value": "searchBarTextDidBeginEditing:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarTextDidBeginEditing(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "searchBarTextDidBeginEditing:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarCancelButtonClicked(_:)/title",
          "value": "searchBarCancelButtonClicked:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarCancelButtonClicked(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "searchBarCancelButtonClicked:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarResultsListButtonClicked(_:)/title",
          "value": "searchBarResultsListButtonClicked:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarResultsListButtonClicked(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "searchBarResultsListButtonClicked:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarBookmarkButtonClicked(_:)/title",
          "value": "searchBarBookmarkButtonClicked:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBarBookmarkButtonClicked(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "searchBarBookmarkButtonClicked:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBar(_:textDidChange:)/title",
          "value": "searchBar:textDidChange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate~1searchBar(_:textDidChange:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "searchBar:textDidChange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/title",
          "value": "UISearchBar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchBar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchBar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate/title",
          "value": "UISearchBarDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchBarDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBarDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchBarDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uisearchbardelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uisearchbardelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
