{
  "abstract": [
    {
      "text": "A selectable search parameter.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UISearchSuggestionItem",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UISearchSuggestionItem"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UISearchSuggestionItem"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "UISearchSuggestionItem"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UISearchSuggestionItem"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This class provides a basic implementation of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestion",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchController/ignoresSearchSuggestionsForSearchBarPlacementStacked": {
      "abstract": [
        {
          "text": "A Boolean value you use to specify whether the search controller prevents search suggestions from displaying for a stacked search bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ignoresSearchSuggestionsForSearchBarPlacementStacked"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchController/ignoresSearchSuggestionsForSearchBarPlacementStacked",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ignoresSearchSuggestionsForSearchBarPlacementStacked"
        }
      ],
      "role": "symbol",
      "title": "ignoresSearchSuggestionsForSearchBarPlacementStacked",
      "type": "topic",
      "url": "/documentation/uikit/uisearchcontroller/ignoressearchsuggestionsforsearchbarplacementstacked"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchController/searchSuggestions": {
      "abstract": [
        {
          "text": "A list of suggestions to offer as shortcuts below the search field.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchSuggestions"
        },
        {
          "kind": "text",
          "text": ": [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UISearchSuggestion",
          "text": "UISearchSuggestion"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchController/searchSuggestions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "searchSuggestions"
        }
      ],
      "role": "symbol",
      "title": "searchSuggestions",
      "type": "topic",
      "url": "/documentation/uikit/uisearchcontroller/searchsuggestions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestion": {
      "abstract": [
        {
          "text": "A set of attributes that a selectable search suggestion must provide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISearchSuggestion"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISearchSuggestion"
        }
      ],
      "role": "symbol",
      "title": "UISearchSuggestion",
      "type": "topic",
      "url": "/documentation/uikit/uisearchsuggestion"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem": {
      "abstract": [
        {
          "text": "A selectable search parameter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISearchSuggestionItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISearchSuggestionItem"
        }
      ],
      "role": "symbol",
      "title": "UISearchSuggestionItem",
      "type": "topic",
      "url": "/documentation/uikit/uisearchsuggestionitem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/iconImage": {
      "abstract": [
        {
          "text": "An image for display on the suggestion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "iconImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/iconImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "iconImage"
        }
      ],
      "role": "symbol",
      "title": "iconImage",
      "type": "topic",
      "url": "/documentation/uikit/uisearchsuggestionitem/iconimage"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedAttributedSuggestion:)": {
      "abstract": [
        {
          "text": "Creates a search suggestion with the specified attributed label.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "localizedAttributedSuggestion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedAttributedSuggestion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithLocalizedAttributedSuggestion:"
        }
      ],
      "role": "symbol",
      "title": "init(localizedAttributedSuggestion:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchsuggestionitem/init(localizedattributedsuggestion:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedAttributedSuggestion:localizedDescription:)": {
      "abstract": [
        {
          "text": "Creates a search suggestion with the specified attributed label and accessibility description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "localizedAttributedSuggestion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "localizedDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedAttributedSuggestion:localizedDescription:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithLocalizedAttributedSuggestion:localizedDescription:"
        }
      ],
      "role": "symbol",
      "title": "init(localizedAttributedSuggestion:localizedDescription:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchsuggestionitem/init(localizedattributedsuggestion:localizeddescription:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedAttributedSuggestion:localizedDescription:iconImage:)": {
      "abstract": [
        {
          "text": "Creates a search suggestion with the specified attributed label, accessibility description, and image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "localizedAttributedSuggestion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "localizedDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "iconImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedAttributedSuggestion:localizedDescription:iconImage:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithLocalizedAttributedSuggestion:localizedDescription:iconImage:"
        }
      ],
      "role": "symbol",
      "title": "init(localizedAttributedSuggestion:localizedDescription:iconImage:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchsuggestionitem/init(localizedattributedsuggestion:localizeddescription:iconimage:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedSuggestion:)": {
      "abstract": [
        {
          "text": "Creates a search suggestion with the specified label.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "localizedSuggestion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedSuggestion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithLocalizedSuggestion:"
        }
      ],
      "role": "symbol",
      "title": "init(localizedSuggestion:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchsuggestionitem/init(localizedsuggestion:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedSuggestion:localizedDescription:)": {
      "abstract": [
        {
          "text": "Creates a search suggestion with the specified label and accessibility description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "localizedSuggestion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "localizedDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedSuggestion:localizedDescription:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithLocalizedSuggestion:localizedDescription:"
        }
      ],
      "role": "symbol",
      "title": "init(localizedSuggestion:localizedDescription:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchsuggestionitem/init(localizedsuggestion:localizeddescription:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedSuggestion:localizedDescription:iconImage:)": {
      "abstract": [
        {
          "text": "Creates a search suggestion with the specified text and image attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "localizedSuggestion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "localizedDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "iconImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedSuggestion:localizedDescription:iconImage:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithLocalizedSuggestion:localizedDescription:iconImage:"
        }
      ],
      "role": "symbol",
      "title": "init(localizedSuggestion:localizedDescription:iconImage:)",
      "type": "topic",
      "url": "/documentation/uikit/uisearchsuggestionitem/init(localizedsuggestion:localizeddescription:iconimage:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/localizedAttributedSuggestion": {
      "abstract": [
        {
          "text": "An attributed label for the suggestion, usually the search term the suggestion represents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localizedAttributedSuggestion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/localizedAttributedSuggestion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localizedAttributedSuggestion"
        }
      ],
      "role": "symbol",
      "title": "localizedAttributedSuggestion",
      "type": "topic",
      "url": "/documentation/uikit/uisearchsuggestionitem/localizedattributedsuggestion"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/localizedDescription": {
      "abstract": [
        {
          "text": "A description of the suggestion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localizedDescription"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/localizedDescription",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localizedDescription"
        }
      ],
      "role": "symbol",
      "title": "localizedDescription",
      "type": "topic",
      "url": "/documentation/uikit/uisearchsuggestionitem/localizeddescription"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/localizedSuggestion": {
      "abstract": [
        {
          "text": "A label for the suggestion, usually the search term the suggestion represents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "localizedSuggestion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/localizedSuggestion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "localizedSuggestion"
        }
      ],
      "role": "symbol",
      "title": "localizedSuggestion",
      "type": "topic",
      "url": "/documentation/uikit/uisearchsuggestionitem/localizedsuggestion"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/representedObject": {
      "abstract": [
        {
          "text": "An object for tracking supplementary information about the search suggestion.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "representedObject"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/representedObject",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "representedObject"
        }
      ],
      "role": "symbol",
      "title": "representedObject",
      "type": "topic",
      "url": "/documentation/uikit/uisearchsuggestionitem/representedobject"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/suggestionWithLocalizedAttributedSuggestion:": {
      "abstract": [
        {
          "text": "Creates a search suggestion with the specified attributed label.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "suggestionWithLocalizedAttributedSuggestion:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/suggestionWithLocalizedAttributedSuggestion:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "suggestionWithLocalizedAttributedSuggestion:"
        }
      ],
      "role": "symbol",
      "title": "suggestionWithLocalizedAttributedSuggestion:",
      "type": "topic",
      "url": "/documentation/uikit/uisearchsuggestionitem/suggestionwithlocalizedattributedsuggestion:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/suggestionWithLocalizedAttributedSuggestion:descriptionString:": {
      "abstract": [
        {
          "text": "Creates a search suggestion with the specified attributed label and accessibility description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "suggestionWithLocalizedAttributedSuggestion:descriptionString:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/suggestionWithLocalizedAttributedSuggestion:descriptionString:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "suggestionWithLocalizedAttributedSuggestion:descriptionString:"
        }
      ],
      "role": "symbol",
      "title": "suggestionWithLocalizedAttributedSuggestion:descriptionString:",
      "type": "topic",
      "url": "/documentation/uikit/uisearchsuggestionitem/suggestionwithlocalizedattributedsuggestion:descriptionstring:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/suggestionWithLocalizedAttributedSuggestion:descriptionString:iconImage:": {
      "abstract": [
        {
          "text": "Creates a search suggestion with the specified attributed label, accessibility description, and image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "suggestionWithLocalizedAttributedSuggestion:descriptionString:iconImage:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/suggestionWithLocalizedAttributedSuggestion:descriptionString:iconImage:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "suggestionWithLocalizedAttributedSuggestion:descriptionString:iconImage:"
        }
      ],
      "role": "symbol",
      "title": "suggestionWithLocalizedAttributedSuggestion:descriptionString:iconImage:",
      "type": "topic",
      "url": "/documentation/uikit/uisearchsuggestionitem/suggestionwithlocalizedattributedsuggestion:descriptionstring:iconimage:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/suggestionWithLocalizedSuggestion:": {
      "abstract": [
        {
          "text": "Creates a search suggestion with the specified label.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "suggestionWithLocalizedSuggestion:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/suggestionWithLocalizedSuggestion:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "suggestionWithLocalizedSuggestion:"
        }
      ],
      "role": "symbol",
      "title": "suggestionWithLocalizedSuggestion:",
      "type": "topic",
      "url": "/documentation/uikit/uisearchsuggestionitem/suggestionwithlocalizedsuggestion:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/suggestionWithLocalizedSuggestion:descriptionString:": {
      "abstract": [
        {
          "text": "Creates a search suggestion with the specified label and accessibility description.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "suggestionWithLocalizedSuggestion:descriptionString:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/suggestionWithLocalizedSuggestion:descriptionString:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "suggestionWithLocalizedSuggestion:descriptionString:"
        }
      ],
      "role": "symbol",
      "title": "suggestionWithLocalizedSuggestion:descriptionString:",
      "type": "topic",
      "url": "/documentation/uikit/uisearchsuggestionitem/suggestionwithlocalizedsuggestion:descriptionstring:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/suggestionWithLocalizedSuggestion:descriptionString:iconImage:": {
      "abstract": [
        {
          "text": "Creates a search suggestion with the specified text and image attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "suggestionWithLocalizedSuggestion:descriptionString:iconImage:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/suggestionWithLocalizedSuggestion:descriptionString:iconImage:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "suggestionWithLocalizedSuggestion:descriptionString:iconImage:"
        }
      ],
      "role": "symbol",
      "title": "suggestionWithLocalizedSuggestion:descriptionString:iconImage:",
      "type": "topic",
      "url": "/documentation/uikit/uisearchsuggestionitem/suggestionwithlocalizedsuggestion:descriptionstring:iconimage:"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestion"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Providing-search-suggestions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISearchController/searchSuggestions",
        "doc://com.apple.uikit/documentation/UIKit/UISearchController/ignoresSearchSuggestionsForSearchBarPlacementStacked",
        "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestion"
      ],
      "title": "Providing search suggestions"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-search-suggestion",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedSuggestion:localizedDescription:iconImage:)",
        "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedAttributedSuggestion:localizedDescription:iconImage:)",
        "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedSuggestion:localizedDescription:)",
        "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedAttributedSuggestion:localizedDescription:)",
        "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedSuggestion:)",
        "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedAttributedSuggestion:)"
      ],
      "title": "Creating a search suggestion"
    },
    {
      "anchor": "Describing-a-search-suggestion",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/localizedSuggestion",
        "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/localizedAttributedSuggestion",
        "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/localizedDescription",
        "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/iconImage",
        "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/representedObject"
      ],
      "title": "Describing a search suggestion"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "16.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UISearchSuggestionItem"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchSuggestionItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchSuggestionItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-search-suggestion",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedSuggestion:localizedDescription:iconImage:)",
                "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedAttributedSuggestion:localizedDescription:iconImage:)",
                "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/suggestionWithLocalizedSuggestion:descriptionString:iconImage:",
                "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/suggestionWithLocalizedAttributedSuggestion:descriptionString:iconImage:",
                "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedSuggestion:localizedDescription:)",
                "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedAttributedSuggestion:localizedDescription:)",
                "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/suggestionWithLocalizedSuggestion:descriptionString:",
                "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/suggestionWithLocalizedAttributedSuggestion:descriptionString:",
                "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedSuggestion:)",
                "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/init(localizedAttributedSuggestion:)",
                "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/suggestionWithLocalizedSuggestion:",
                "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/suggestionWithLocalizedAttributedSuggestion:"
              ],
              "title": "Creating a search suggestion"
            },
            {
              "anchor": "Describing-a-search-suggestion",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/localizedSuggestion",
                "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/localizedAttributedSuggestion",
                "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/localizedDescription",
                "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/iconImage",
                "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestionItem/representedObject"
              ],
              "title": "Describing a search suggestion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestion"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Providing-search-suggestions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UISearchController/searchSuggestions",
                "doc://com.apple.uikit/documentation/UIKit/UISearchController/ignoresSearchSuggestionsForSearchBarPlacementStacked",
                "doc://com.apple.uikit/documentation/UIKit/UISearchSuggestion"
              ],
              "title": "Providing search suggestions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UISearchSuggestionItem"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestionItem~1init(localizedAttributedSuggestion:)/title",
          "value": "initWithLocalizedAttributedSuggestion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestionItem~1init(localizedAttributedSuggestion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithLocalizedAttributedSuggestion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestionItem~1localizedSuggestion/title",
          "value": "localizedSuggestion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestionItem~1localizedSuggestion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localizedSuggestion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestionItem~1init(localizedSuggestion:)/title",
          "value": "initWithLocalizedSuggestion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestionItem~1init(localizedSuggestion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithLocalizedSuggestion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1searchSuggestions/title",
          "value": "searchSuggestions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1searchSuggestions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "searchSuggestions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestionItem~1iconImage/title",
          "value": "iconImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestionItem~1iconImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "iconImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestionItem~1init(localizedAttributedSuggestion:localizedDescription:)/title",
          "value": "initWithLocalizedAttributedSuggestion:localizedDescription:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestionItem~1init(localizedAttributedSuggestion:localizedDescription:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithLocalizedAttributedSuggestion:localizedDescription:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestionItem/title",
          "value": "UISearchSuggestionItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestionItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchSuggestionItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestionItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchSuggestionItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestion/title",
          "value": "UISearchSuggestion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchSuggestion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchSuggestion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1ignoresSearchSuggestionsForSearchBarPlacementStacked/title",
          "value": "ignoresSearchSuggestionsForSearchBarPlacementStacked"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController~1ignoresSearchSuggestionsForSearchBarPlacementStacked/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ignoresSearchSuggestionsForSearchBarPlacementStacked"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestionItem~1init(localizedAttributedSuggestion:localizedDescription:iconImage:)/title",
          "value": "initWithLocalizedAttributedSuggestion:localizedDescription:iconImage:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestionItem~1init(localizedAttributedSuggestion:localizedDescription:iconImage:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithLocalizedAttributedSuggestion:localizedDescription:iconImage:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestionItem~1representedObject/title",
          "value": "representedObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestionItem~1representedObject/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "representedObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestionItem~1localizedDescription/title",
          "value": "localizedDescription"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestionItem~1localizedDescription/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localizedDescription"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestionItem~1init(localizedSuggestion:localizedDescription:)/title",
          "value": "initWithLocalizedSuggestion:localizedDescription:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestionItem~1init(localizedSuggestion:localizedDescription:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithLocalizedSuggestion:localizedDescription:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestionItem~1localizedAttributedSuggestion/title",
          "value": "localizedAttributedSuggestion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestionItem~1localizedAttributedSuggestion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "localizedAttributedSuggestion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestionItem~1init(localizedSuggestion:localizedDescription:iconImage:)/title",
          "value": "initWithLocalizedSuggestion:localizedDescription:iconImage:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchSuggestionItem~1init(localizedSuggestion:localizedDescription:iconImage:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithLocalizedSuggestion:localizedDescription:iconImage:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uisearchsuggestionitem"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uisearchsuggestionitem"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
