{
  "abstract": [
    {
      "text": "The default value to apply to a dimension.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationControllerAutomaticDimension"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@UISheetPresentationControllerAutomaticDimension",
    "fragments": [
      {
        "kind": "identifier",
        "text": "UISheetPresentationControllerAutomaticDimension"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UISheetPresentationControllerAutomaticDimension"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "UISheetPresentationControllerAutomaticDimension"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "extern"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "const"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CGFloat",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CGFloat",
              "text": "CGFloat"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UISheetPresentationControllerAutomaticDimension"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/preferredCornerRadius-358tc": {
      "abstract": [
        {
          "text": "The corner radius that the sheet attempts to present with.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "preferredCornerRadius"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/preferredCornerRadius-358tc",
      "kind": "symbol",
      "role": "symbol",
      "title": "preferredCornerRadius",
      "type": "topic",
      "url": "/documentation/uikit/uisheetpresentationcontroller/preferredcornerradius-358tc"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/prefersEdgeAttachedInCompactHeight": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the sheet attaches to the bottom edge of the screen in a compact-height size class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prefersEdgeAttachedInCompactHeight"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/prefersEdgeAttachedInCompactHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "prefersEdgeAttachedInCompactHeight"
        }
      ],
      "role": "symbol",
      "title": "prefersEdgeAttachedInCompactHeight",
      "type": "topic",
      "url": "/documentation/uikit/uisheetpresentationcontroller/prefersedgeattachedincompactheight"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/prefersGrabberVisible": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the sheet shows a grabber at the top.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prefersGrabberVisible"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/prefersGrabberVisible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "prefersGrabberVisible"
        }
      ],
      "role": "symbol",
      "title": "prefersGrabberVisible",
      "type": "topic",
      "url": "/documentation/uikit/uisheetpresentationcontroller/prefersgrabbervisible"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/prefersPageSizing": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the sheet sizes itself for readable content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prefersPageSizing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/prefersPageSizing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "prefersPageSizing"
        }
      ],
      "role": "symbol",
      "title": "prefersPageSizing",
      "type": "topic",
      "url": "/documentation/uikit/uisheetpresentationcontroller/preferspagesizing"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/widthFollowsPreferredContentSizeWhenEdgeAttached": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the sheet’s width matches its view controller’s preferred content size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "widthFollowsPreferredContentSizeWhenEdgeAttached"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/widthFollowsPreferredContentSizeWhenEdgeAttached",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "widthFollowsPreferredContentSizeWhenEdgeAttached"
        }
      ],
      "role": "symbol",
      "title": "widthFollowsPreferredContentSizeWhenEdgeAttached",
      "type": "topic",
      "url": "/documentation/uikit/uisheetpresentationcontroller/widthfollowspreferredcontentsizewhenedgeattached"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationControllerAutomaticDimension": {
      "abstract": [
        {
          "text": "The default value to apply to a dimension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UISheetPresentationControllerAutomaticDimension"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationControllerAutomaticDimension",
      "kind": "symbol",
      "role": "symbol",
      "title": "UISheetPresentationControllerAutomaticDimension",
      "type": "topic",
      "url": "/documentation/uikit/uisheetpresentationcontrollerautomaticdimension"
    },
    "doc://com.externally.resolved.symbol/c:@T@CGFloat": {
      "abstract": [
        {
          "text": "The basic type for all floating-point values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CGFloat",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGFloat",
      "type": "topic",
      "url": "/documentation/corefoundation/cgfloat"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-the-appearance",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/prefersGrabberVisible",
        "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/prefersPageSizing",
        "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/prefersEdgeAttachedInCompactHeight",
        "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/widthFollowsPreferredContentSizeWhenEdgeAttached",
        "doc://com.apple.uikit/documentation/UIKit/UISheetPresentationController/preferredCornerRadius-358tc"
      ],
      "title": "Managing the appearance"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISheetPresentationController~1widthFollowsPreferredContentSizeWhenEdgeAttached/title",
          "value": "widthFollowsPreferredContentSizeWhenEdgeAttached"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISheetPresentationController~1widthFollowsPreferredContentSizeWhenEdgeAttached/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "widthFollowsPreferredContentSizeWhenEdgeAttached"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISheetPresentationController~1prefersEdgeAttachedInCompactHeight/title",
          "value": "prefersEdgeAttachedInCompactHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISheetPresentationController~1prefersEdgeAttachedInCompactHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "prefersEdgeAttachedInCompactHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISheetPresentationController~1prefersPageSizing/title",
          "value": "prefersPageSizing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISheetPresentationController~1prefersPageSizing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "prefersPageSizing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISheetPresentationController~1prefersGrabberVisible/title",
          "value": "prefersGrabberVisible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISheetPresentationController~1prefersGrabberVisible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "prefersGrabberVisible"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uisheetpresentationcontrollerautomaticdimension"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
