{
  "abstract": [
    {
      "text": "An abstract representation of a shape.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIShape",
    "fragments": [
      {
        "kind": "identifier",
        "text": "UIShape"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIShape"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "UIShape"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIShape"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-swift.struct",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " can represent different types of shapes, including:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A simple shape like a rectangle or circle that resolves into a concrete shape according to context (like size and position)",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A Bézier path",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "A dynamic shape that resolves using a custom closure",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "You typically use a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-swift.struct",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " with APIs like ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIHoverStyle",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to represent the shape of an effect.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICornerCurve": {
      "abstract": [
        {
          "text": "The corner curve to apply to a view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICornerCurve"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICornerCurve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICornerCurve"
        }
      ],
      "role": "symbol",
      "title": "UICornerCurve",
      "type": "topic",
      "url": "/documentation/uikit/uicornercurve"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIHoverStyle": {
      "abstract": [
        {
          "text": "The hover style to apply to a view, including an effect and a shape to use for displaying that effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIHoverStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIHoverStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIHoverStyle"
        }
      ],
      "role": "symbol",
      "title": "UIHoverStyle",
      "type": "topic",
      "url": "/documentation/uikit/uihoverstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIHoverStyle/shape-55cmq": {
      "abstract": [
        {
          "text": "The shape to use for the hover effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "shape"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIHoverStyle/shape-55cmq",
      "kind": "symbol",
      "role": "symbol",
      "title": "shape",
      "type": "topic",
      "url": "/documentation/uikit/uihoverstyle/shape-55cmq"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIResolvedShape": {
      "abstract": [
        {
          "text": "A shape that has completely resolved based on a context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIResolvedShape"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIResolvedShape",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIResolvedShape",
      "type": "topic",
      "url": "/documentation/uikit/uiresolvedshape"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class": {
      "abstract": [
        {
          "text": "An abstract representation of a shape.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIShape"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIShape",
      "type": "topic",
      "url": "/documentation/uikit/uishape-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/capsuleShape": {
      "abstract": [
        {
          "text": "Creates a capsule shape, a rounded rectangle with a corner radius equal to half the length of the rectangle’s smallest edge.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "capsuleShape"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/capsuleShape",
      "kind": "symbol",
      "role": "symbol",
      "title": "capsuleShape",
      "type": "topic",
      "url": "/documentation/uikit/uishape-c.class/capsuleshape"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/circleShape": {
      "abstract": [
        {
          "text": "Creates a circular shape, with a radius equal to half the length of the frame rectangle’s smallest edge.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "circleShape"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/circleShape",
      "kind": "symbol",
      "role": "symbol",
      "title": "circleShape",
      "type": "topic",
      "url": "/documentation/uikit/uishape-c.class/circleshape"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/fixedRectShapeWithRect:": {
      "abstract": [
        {
          "text": "Creates a fixed rectangular shape that uses the provided rectangle as its shape, regardless of the frame that contains it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "fixedRectShapeWithRect:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/fixedRectShapeWithRect:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fixedRectShapeWithRect:"
        }
      ],
      "role": "symbol",
      "title": "fixedRectShapeWithRect:",
      "type": "topic",
      "url": "/documentation/uikit/uishape-c.class/fixedrectshapewithrect:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/fixedRectShapeWithRect:cornerRadius:": {
      "abstract": [
        {
          "text": "Creates a fixed rectangular shape with the provided corner radius, using the provided rectangle as its shape.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "fixedRectShapeWithRect:cornerRadius:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/fixedRectShapeWithRect:cornerRadius:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fixedRectShapeWithRect:cornerRadius:"
        }
      ],
      "role": "symbol",
      "title": "fixedRectShapeWithRect:cornerRadius:",
      "type": "topic",
      "url": "/documentation/uikit/uishape-c.class/fixedrectshapewithrect:cornerradius:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/fixedRectShapeWithRect:cornerRadius:cornerCurve:maskedCorners:": {
      "abstract": [
        {
          "text": "Creates a fixed rectangular shape with the provided corner radius and corner curve, using the provided rectangle as its shape.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "fixedRectShapeWithRect:cornerRadius:cornerCurve:maskedCorners:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/fixedRectShapeWithRect:cornerRadius:cornerCurve:maskedCorners:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "fixedRectShapeWithRect:cornerRadius:cornerCurve:maskedCorners:"
        }
      ],
      "role": "symbol",
      "title": "fixedRectShapeWithRect:cornerRadius:cornerCurve:maskedCorners:",
      "type": "topic",
      "url": "/documentation/uikit/uishape-c.class/fixedrectshapewithrect:cornerradius:cornercurve:maskedcorners:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/rectShape": {
      "abstract": [
        {
          "text": "Creates a rectangular shape.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "rectShape"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/rectShape",
      "kind": "symbol",
      "role": "symbol",
      "title": "rectShape",
      "type": "topic",
      "url": "/documentation/uikit/uishape-c.class/rectshape"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/rectShapeWithCornerRadius:": {
      "abstract": [
        {
          "text": "Creates a rectangular shape with rounded corners, using the provided corner radius.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "rectShapeWithCornerRadius:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/rectShapeWithCornerRadius:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rectShapeWithCornerRadius:"
        }
      ],
      "role": "symbol",
      "title": "rectShapeWithCornerRadius:",
      "type": "topic",
      "url": "/documentation/uikit/uishape-c.class/rectshapewithcornerradius:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/rectShapeWithCornerRadius:cornerCurve:": {
      "abstract": [
        {
          "text": "Creates a rectangular shape with rounded corners, using the provided corner radius and corner curve.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "rectShapeWithCornerRadius:cornerCurve:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/rectShapeWithCornerRadius:cornerCurve:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rectShapeWithCornerRadius:cornerCurve:"
        }
      ],
      "role": "symbol",
      "title": "rectShapeWithCornerRadius:cornerCurve:",
      "type": "topic",
      "url": "/documentation/uikit/uishape-c.class/rectshapewithcornerradius:cornercurve:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/rectShapeWithCornerRadius:cornerCurve:maskedCorners:": {
      "abstract": [
        {
          "text": "Creates a rectangular shape with rounded corners, using the provided corner radius, corner curve, and rectangle corners.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "rectShapeWithCornerRadius:cornerCurve:maskedCorners:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/rectShapeWithCornerRadius:cornerCurve:maskedCorners:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rectShapeWithCornerRadius:cornerCurve:maskedCorners:"
        }
      ],
      "role": "symbol",
      "title": "rectShapeWithCornerRadius:cornerCurve:maskedCorners:",
      "type": "topic",
      "url": "/documentation/uikit/uishape-c.class/rectshapewithcornerradius:cornercurve:maskedcorners:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/resolvedShapeInContext:": {
      "abstract": [
        {
          "text": "Resolves the shape in the provided context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "resolvedShapeInContext:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/resolvedShapeInContext:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "resolvedShapeInContext:"
        }
      ],
      "role": "symbol",
      "title": "resolvedShapeInContext:",
      "type": "topic",
      "url": "/documentation/uikit/uishape-c.class/resolvedshapeincontext:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/shapeByApplyingInset:": {
      "abstract": [
        {
          "text": "Creates a new modified shape by applying the provided inset to this shape.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "shapeByApplyingInset:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/shapeByApplyingInset:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shapeByApplyingInset:"
        }
      ],
      "role": "symbol",
      "title": "shapeByApplyingInset:",
      "type": "topic",
      "url": "/documentation/uikit/uishape-c.class/shapebyapplyinginset:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/shapeByApplyingInsets:": {
      "abstract": [
        {
          "text": "Creates a new modified shape by applying the provided insets to this shape.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "shapeByApplyingInsets:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/shapeByApplyingInsets:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shapeByApplyingInsets:"
        }
      ],
      "role": "symbol",
      "title": "shapeByApplyingInsets:",
      "type": "topic",
      "url": "/documentation/uikit/uishape-c.class/shapebyapplyinginsets:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/shapeWithBezierPath:": {
      "abstract": [
        {
          "text": "Creates a shape with a custom Bézier path.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "shapeWithBezierPath:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/shapeWithBezierPath:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shapeWithBezierPath:"
        }
      ],
      "role": "symbol",
      "title": "shapeWithBezierPath:",
      "type": "topic",
      "url": "/documentation/uikit/uishape-c.class/shapewithbezierpath:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/shapeWithProvider:": {
      "abstract": [
        {
          "text": "Creates a dynamic shape that resolves using the provided resolver closure and resolution context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "+ "
        },
        {
          "kind": "identifier",
          "text": "shapeWithProvider:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/shapeWithProvider:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shapeWithProvider:"
        }
      ],
      "role": "symbol",
      "title": "shapeWithProvider:",
      "type": "topic",
      "url": "/documentation/uikit/uishape-c.class/shapewithprovider:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShape-swift.struct": {
      "abstract": [
        {
          "text": "An abstract representation of a shape.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIShape"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShape-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIShape"
        }
      ],
      "role": "symbol",
      "title": "UIShape",
      "type": "topic",
      "url": "/documentation/uikit/uishape-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShapeProvider-31jrf": {
      "abstract": [
        {
          "text": "An interface for a type that provides a custom shape by resolving it dynamically based on a context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIShapeProvider"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShapeProvider-31jrf",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIShapeProvider",
      "type": "topic",
      "url": "/documentation/uikit/uishapeprovider-31jrf"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIShapeResolutionContext": {
      "abstract": [
        {
          "text": "The context for resolving a dynamic shape.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIShapeResolutionContext"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIShapeResolutionContext",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIShapeResolutionContext",
      "type": "topic",
      "url": "/documentation/uikit/uishaperesolutioncontext"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.apple.uikit/documentation/UIKit/UIShapeProvider-31jrf"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Specifying-a-hover-shape",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIHoverStyle/shape-55cmq"
      ],
      "title": "Specifying a hover shape"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-hover-shape",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/rectShape",
        "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/capsuleShape",
        "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/circleShape",
        "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/rectShapeWithCornerRadius:",
        "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/rectShapeWithCornerRadius:cornerCurve:",
        "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/rectShapeWithCornerRadius:cornerCurve:maskedCorners:",
        "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/fixedRectShapeWithRect:",
        "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/fixedRectShapeWithRect:cornerRadius:",
        "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/fixedRectShapeWithRect:cornerRadius:cornerCurve:maskedCorners:",
        "doc://com.apple.uikit/documentation/UIKit/UICornerCurve"
      ],
      "title": "Creating a hover shape"
    },
    {
      "anchor": "Creating-a-hover-shape-from-a-custom-path",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/shapeWithBezierPath:"
      ],
      "title": "Creating a hover shape from a custom path"
    },
    {
      "anchor": "Creating-a-dynamic-hover-shape",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/shapeWithProvider:",
        "doc://com.apple.uikit/documentation/UIKit/UIShapeProvider-31jrf",
        "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/resolvedShapeInContext:",
        "doc://com.apple.uikit/documentation/UIKit/UIShapeResolutionContext",
        "doc://com.apple.uikit/documentation/UIKit/UIResolvedShape"
      ],
      "title": "Creating a dynamic hover shape"
    },
    {
      "anchor": "Creating-a-shape-by-applying-insets",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/shapeByApplyingInsets:",
        "doc://com.apple.uikit/documentation/UIKit/UIShape-c.class/shapeByApplyingInset:"
      ],
      "title": "Creating a shape by applying insets"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIHoverStyle/title",
          "value": "UIHoverStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIHoverStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIHoverStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIHoverStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIHoverStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICornerCurve/title",
          "value": "UICornerCurve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICornerCurve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICornerCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICornerCurve/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICornerCurve"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uishape-c.class"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
