{
  "abstract": [
    {
      "text": "The methods adopted by the object you use to manage changes to a split view interface.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UISplitViewControllerDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UISplitViewControllerDelegate"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UISplitViewControllerDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "UISplitViewControllerDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UISplitViewControllerDelegate"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the methods of this protocol to respond to changes in the current display mode and to the current interface orientation. When the split view interface collapses and expands, or when a new view controller is added to the interface, you can also use these methods to configure the child view controllers.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The methods of this protocol are all optional. If you don’t implement any of the methods, the split view controller provides default behavior to handle the collapsing and expanding transitions.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Column-style-split-views",
          "level": 3,
          "text": "Column-style split views",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In a column-style split view interface, you use these delegate methods to customize interface transition behavior:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:topColumnForCollapsingToProposedTopColumn:)",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:willHide:)",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewControllerDidCollapse(_:)",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:displayModeForExpandingToProposedDisplayMode:)",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:willShow:)",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewControllerDidExpand(_:)",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "anchor": "Classic-split-views",
          "level": 3,
          "text": "Classic split views",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In a classic split view interface, you use these delegate methods to customize interface transition behavior:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/primaryViewController(forCollapsing:)",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:collapseSecondary:onto:)",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/primaryViewController(forExpanding:)",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:separateSecondaryFrom:)",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:show:sender:)",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:showDetail:sender:)",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "inlineContent": [
            {
              "text": "At the end of a collapse transition, the split view controller typically shows only the content from its primary view controller. You can change this behavior by implementing the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/primaryViewController(forCollapsing:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method in your split view controller delegate. You might use that method to specify the secondary view controller or an entirely different view controller—perhaps one better suited for display in a horizontally compact environment.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you want to perform any additional adjustments of the view controllers and view hierarchy, you can also implement the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:collapseSecondary:onto:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method in your delegate.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The expansion process reverses the collapsing process by asking the delegate to designate which view controller becomes the primary view controller and to give the delegate a chance to perform the transition itself. If you implement the delegate methods for collapsing your split view interface, you should also implement the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/primaryViewController(forExpanding:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:separateSecondaryFrom:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " methods for expanding that interface.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewController": {
      "abstract": [
        {
          "text": "A container view controller that implements a hierarchical interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISplitViewController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISplitViewController"
        }
      ],
      "role": "symbol",
      "title": "UISplitViewController",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/delegate": {
      "abstract": [
        {
          "text": "The delegate you use to manage changes to a split view interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UISplitViewControllerDelegate",
          "text": "UISplitViewControllerDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontroller/delegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate": {
      "abstract": [
        {
          "text": "The methods adopted by the object you use to manage changes to a split view interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISplitViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISplitViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "UISplitViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontrollerdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/primaryViewController(forCollapsing:)": {
      "abstract": [
        {
          "text": "Asks the delegate to provide the single view controller to display after the split view interface collapses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "primaryViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forCollapsing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/primaryViewController(forCollapsing:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "primaryViewControllerForCollapsingSplitViewController:"
        }
      ],
      "role": "symbol",
      "title": "primaryViewController(forCollapsing:)",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontrollerdelegate/primaryviewcontroller(forcollapsing:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/primaryViewController(forExpanding:)": {
      "abstract": [
        {
          "text": "Asks the delegate to provide the view controller to display in the primary position when the split view interface expands.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "primaryViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forExpanding"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/primaryViewController(forExpanding:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "primaryViewControllerForExpandingSplitViewController:"
        }
      ],
      "role": "symbol",
      "title": "primaryViewController(forExpanding:)",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontrollerdelegate/primaryviewcontroller(forexpanding:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:collapseSecondary:onto:)": {
      "abstract": [
        {
          "text": "Asks the delegate to adjust the primary view controller and to incorporate the secondary view controller into the collapsed interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "splitViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "collapseSecondary"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "onto"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:collapseSecondary:onto:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "splitViewController:collapseSecondaryViewController:ontoPrimaryViewController:"
        }
      ],
      "role": "symbol",
      "title": "splitViewController(_:collapseSecondary:onto:)",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontrollerdelegate/splitviewcontroller(_:collapsesecondary:onto:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:displayModeForExpandingToProposedDisplayMode:)": {
      "abstract": [
        {
          "text": "Asks the delegate to provide the display mode to use after the split view interface expands.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "splitViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "displayModeForExpandingToProposedDisplayMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UISplitViewControllerDisplayMode",
          "text": "DisplayMode"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UISplitViewControllerDisplayMode",
          "text": "DisplayMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:displayModeForExpandingToProposedDisplayMode:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "splitViewController:displayModeForExpandingToProposedDisplayMode:"
        }
      ],
      "role": "symbol",
      "title": "splitViewController(_:displayModeForExpandingToProposedDisplayMode:)",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontrollerdelegate/splitviewcontroller(_:displaymodeforexpandingtoproposeddisplaymode:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:popoverController:willPresent:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the hidden view controller is about to be displayed in a popover.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "splitViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "popoverController"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPopoverController",
          "text": "UIPopoverController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willPresent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:popoverController:willPresent:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "splitViewController:popoverController:willPresentViewController:"
        }
      ],
      "role": "symbol",
      "title": "splitViewController(_:popoverController:willPresent:)",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontrollerdelegate/splitviewcontroller(_:popovercontroller:willpresent:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:separateSecondaryFrom:)": {
      "abstract": [
        {
          "text": "Asks the delegate to provide the new secondary view controller for the split view interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "splitViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "separateSecondaryFrom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:separateSecondaryFrom:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "splitViewController:separateSecondaryViewControllerFromPrimaryViewController:"
        }
      ],
      "role": "symbol",
      "title": "splitViewController(_:separateSecondaryFrom:)",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontrollerdelegate/splitviewcontroller(_:separatesecondaryfrom:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:shouldHide:in:)": {
      "abstract": [
        {
          "text": "Asks the delegate whether the first view controller should be hidden for the specified orientation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "splitViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shouldHide"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIInterfaceOrientation",
          "text": "UIInterfaceOrientation"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:shouldHide:in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "splitViewController:shouldHideViewController:inOrientation:"
        }
      ],
      "role": "symbol",
      "title": "splitViewController(_:shouldHide:in:)",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontrollerdelegate/splitviewcontroller(_:shouldhide:in:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:show:sender:)": {
      "abstract": [
        {
          "text": "Asks the delegate if it will do the work of displaying a view controller in the primary position of the split view interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "splitViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "show"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "sender"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:show:sender:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "splitViewController:showViewController:sender:"
        }
      ],
      "role": "symbol",
      "title": "splitViewController(_:show:sender:)",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontrollerdelegate/splitviewcontroller(_:show:sender:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:showDetail:sender:)": {
      "abstract": [
        {
          "text": "Asks the delegate if it will do the work of displaying a view controller in the secondary position of the split view interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "splitViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "showDetail"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "sender"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:showDetail:sender:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "splitViewController:showDetailViewController:sender:"
        }
      ],
      "role": "symbol",
      "title": "splitViewController(_:showDetail:sender:)",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontrollerdelegate/splitviewcontroller(_:showdetail:sender:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:topColumnForCollapsingToProposedTopColumn:)": {
      "abstract": [
        {
          "text": "Asks the delegate to provide the column to display after the split view interface collapses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "splitViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "topColumnForCollapsingToProposedTopColumn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UISplitViewControllerColumn",
          "text": "Column"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UISplitViewControllerColumn",
          "text": "Column"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:topColumnForCollapsingToProposedTopColumn:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "splitViewController:topColumnForCollapsingToProposedTopColumn:"
        }
      ],
      "role": "symbol",
      "title": "splitViewController(_:topColumnForCollapsingToProposedTopColumn:)",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontrollerdelegate/splitviewcontroller(_:topcolumnforcollapsingtoproposedtopcolumn:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:willChangeTo:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the display mode for the split view controller is about to change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "splitViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willChangeTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UISplitViewControllerDisplayMode",
          "text": "DisplayMode"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:willChangeTo:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "splitViewController:willChangeToDisplayMode:"
        }
      ],
      "role": "symbol",
      "title": "splitViewController(_:willChangeTo:)",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontrollerdelegate/splitviewcontroller(_:willchangeto:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:willHide:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the specified column is about to be hidden.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "splitViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willHide"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UISplitViewControllerColumn",
          "text": "Column"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:willHide:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "splitViewController:willHideColumn:"
        }
      ],
      "role": "symbol",
      "title": "splitViewController(_:willHide:)",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontrollerdelegate/splitviewcontroller(_:willhide:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:willHide:with:for:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the specified view controller is about to be hidden.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "splitViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willHide"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIBarButtonItem",
          "text": "UIBarButtonItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPopoverController",
          "text": "UIPopoverController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:willHide:with:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "splitViewController:willHideViewController:withBarButtonItem:forPopoverController:"
        }
      ],
      "role": "symbol",
      "title": "splitViewController(_:willHide:with:for:)",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontrollerdelegate/splitviewcontroller(_:willhide:with:for:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:willShow:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the specified column is about to be shown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "splitViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willShow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UISplitViewControllerColumn",
          "text": "Column"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:willShow:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "splitViewController:willShowColumn:"
        }
      ],
      "role": "symbol",
      "title": "splitViewController(_:willShow:)",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontrollerdelegate/splitviewcontroller(_:willshow:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:willShow:invalidating:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the specified view controller is about to be shown again.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "splitViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willShow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "invalidating"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIBarButtonItem",
          "text": "UIBarButtonItem"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:willShow:invalidating:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "splitViewController:willShowViewController:invalidatingBarButtonItem:"
        }
      ],
      "role": "symbol",
      "title": "splitViewController(_:willShow:invalidating:)",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontrollerdelegate/splitviewcontroller(_:willshow:invalidating:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewControllerDidCollapse(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the split view controller interface has collapsed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "splitViewControllerDidCollapse"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewControllerDidCollapse(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "splitViewControllerDidCollapse:"
        }
      ],
      "role": "symbol",
      "title": "splitViewControllerDidCollapse(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontrollerdelegate/splitviewcontrollerdidcollapse(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewControllerDidExpand(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the split view controller interface has expanded.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "splitViewControllerDidExpand"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewControllerDidExpand(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "splitViewControllerDidExpand:"
        }
      ],
      "role": "symbol",
      "title": "splitViewControllerDidExpand(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontrollerdelegate/splitviewcontrollerdidexpand(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewControllerInteractivePresentationGestureDidEnd(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate when the interactive presentation gesture ends.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "splitViewControllerInteractivePresentationGestureDidEnd"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewControllerInteractivePresentationGestureDidEnd(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "splitViewControllerInteractivePresentationGestureDidEnd:"
        }
      ],
      "role": "symbol",
      "title": "splitViewControllerInteractivePresentationGestureDidEnd(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontrollerdelegate/splitviewcontrollerinteractivepresentationgesturedidend(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewControllerInteractivePresentationGestureWillBegin(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the interactive presentation gesture is about to begin.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "splitViewControllerInteractivePresentationGestureWillBegin"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewControllerInteractivePresentationGestureWillBegin(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "splitViewControllerInteractivePresentationGestureWillBegin:"
        }
      ],
      "role": "symbol",
      "title": "splitViewControllerInteractivePresentationGestureWillBegin(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontrollerdelegate/splitviewcontrollerinteractivepresentationgesturewillbegin(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewControllerPreferredInterfaceOrientationForPresentation(_:)": {
      "abstract": [
        {
          "text": "Asks the delegate for the orientation to use when presenting the split view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "splitViewControllerPreferredInterfaceOrientationForPresentation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIInterfaceOrientation",
          "text": "UIInterfaceOrientation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewControllerPreferredInterfaceOrientationForPresentation(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "splitViewControllerPreferredInterfaceOrientationForPresentation:"
        }
      ],
      "role": "symbol",
      "title": "splitViewControllerPreferredInterfaceOrientationForPresentation(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontrollerdelegate/splitviewcontrollerpreferredinterfaceorientationforpresentation(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewControllerSupportedInterfaceOrientations(_:)": {
      "abstract": [
        {
          "text": "Asks the delegate to specify the interface orientations that the split view controller supports.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "splitViewControllerSupportedInterfaceOrientations"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIInterfaceOrientationMask",
          "text": "UIInterfaceOrientationMask"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewControllerSupportedInterfaceOrientations(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "splitViewControllerSupportedInterfaceOrientations:"
        }
      ],
      "role": "symbol",
      "title": "splitViewControllerSupportedInterfaceOrientations(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontrollerdelegate/splitviewcontrollersupportedinterfaceorientations(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/targetDisplayModeForAction(in:)": {
      "abstract": [
        {
          "text": "Asks the delegate to provide the display mode to apply when a split view controller action occurs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "targetDisplayModeForAction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UISplitViewControllerDisplayMode",
          "text": "DisplayMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/targetDisplayModeForAction(in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "targetDisplayModeForActionInSplitViewController:"
        }
      ],
      "role": "symbol",
      "title": "targetDisplayModeForAction(in:)",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontrollerdelegate/targetdisplaymodeforaction(in:)"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Customizing-the-split-view-transitions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/delegate"
      ],
      "title": "Customizing the split view transitions"
    }
  ],
  "topicSections": [
    {
      "anchor": "Specifying-the-interface-orientations",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewControllerPreferredInterfaceOrientationForPresentation(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewControllerSupportedInterfaceOrientations(_:)"
      ],
      "title": "Specifying the interface orientations"
    },
    {
      "anchor": "Responding-to-display-mode-changes",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:willChangeTo:)",
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/targetDisplayModeForAction(in:)"
      ],
      "title": "Responding to display mode changes"
    },
    {
      "anchor": "Collapsing-the-interface",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:topColumnForCollapsingToProposedTopColumn:)",
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:willHide:)",
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewControllerDidCollapse(_:)"
      ],
      "title": "Collapsing the interface"
    },
    {
      "anchor": "Expanding-the-interface",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:displayModeForExpandingToProposedDisplayMode:)",
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:willShow:)",
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewControllerDidExpand(_:)"
      ],
      "title": "Expanding the interface"
    },
    {
      "anchor": "Handling-the-presentation-gesture",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewControllerInteractivePresentationGestureWillBegin(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewControllerInteractivePresentationGestureDidEnd(_:)"
      ],
      "title": "Handling the presentation gesture"
    },
    {
      "anchor": "Collapsing-and-expanding-classic-split-views",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/primaryViewController(forCollapsing:)",
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:collapseSecondary:onto:)",
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/primaryViewController(forExpanding:)",
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:separateSecondaryFrom:)"
      ],
      "title": "Collapsing and expanding classic split views"
    },
    {
      "anchor": "Overriding-the-presentation-behavior",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:show:sender:)",
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:showDetail:sender:)"
      ],
      "title": "Overriding the presentation behavior"
    },
    {
      "anchor": "Deprecated-methods",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:shouldHide:in:)",
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:willHide:with:for:)",
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:willShow:invalidating:)",
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:popoverController:willPresent:)"
      ],
      "title": "Deprecated methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UISplitViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISplitViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISplitViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Specifying-the-interface-orientations",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewControllerPreferredInterfaceOrientationForPresentation(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewControllerSupportedInterfaceOrientations(_:)"
              ],
              "title": "Specifying the interface orientations"
            },
            {
              "anchor": "Responding-to-display-mode-changes",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:willChangeTo:)",
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/targetDisplayModeForAction(in:)"
              ],
              "title": "Responding to display mode changes"
            },
            {
              "anchor": "Collapsing-the-interface",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:topColumnForCollapsingToProposedTopColumn:)",
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:willHide:)",
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewControllerDidCollapse(_:)"
              ],
              "title": "Collapsing the interface"
            },
            {
              "anchor": "Expanding-the-interface",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:displayModeForExpandingToProposedDisplayMode:)",
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:willShow:)",
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewControllerDidExpand(_:)"
              ],
              "title": "Expanding the interface"
            },
            {
              "anchor": "Handling-the-presentation-gesture",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewControllerInteractivePresentationGestureWillBegin(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewControllerInteractivePresentationGestureDidEnd(_:)"
              ],
              "title": "Handling the presentation gesture"
            },
            {
              "anchor": "Collapsing-and-expanding-classic-split-views",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/primaryViewController(forCollapsing:)",
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:collapseSecondary:onto:)",
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/primaryViewController(forExpanding:)",
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:separateSecondaryFrom:)"
              ],
              "title": "Collapsing and expanding classic split views"
            },
            {
              "anchor": "Overriding-the-presentation-behavior",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:show:sender:)",
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:showDetail:sender:)"
              ],
              "title": "Overriding the presentation behavior"
            },
            {
              "anchor": "Deprecated-methods",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:shouldHide:in:)",
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:willHide:with:for:)",
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:willShow:invalidating:)",
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:popoverController:willPresent:)"
              ],
              "title": "Deprecated methods"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Customizing-the-split-view-transitions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewController/delegate"
              ],
              "title": "Customizing the split view transitions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UISplitViewControllerDelegate"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewController(_:show:sender:)/title",
          "value": "splitViewController:showViewController:sender:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewController(_:show:sender:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "splitViewController:showViewController:sender:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewController(_:showDetail:sender:)/title",
          "value": "splitViewController:showDetailViewController:sender:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewController(_:showDetail:sender:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "splitViewController:showDetailViewController:sender:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewController(_:topColumnForCollapsingToProposedTopColumn:)/title",
          "value": "splitViewController:topColumnForCollapsingToProposedTopColumn:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewController(_:topColumnForCollapsingToProposedTopColumn:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "splitViewController:topColumnForCollapsingToProposedTopColumn:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewController(_:popoverController:willPresent:)/title",
          "value": "splitViewController:popoverController:willPresentViewController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewController(_:popoverController:willPresent:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "splitViewController:popoverController:willPresentViewController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewController(_:collapseSecondary:onto:)/title",
          "value": "splitViewController:collapseSecondaryViewController:ontoPrimaryViewController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewController(_:collapseSecondary:onto:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "splitViewController:collapseSecondaryViewController:ontoPrimaryViewController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewControllerDidExpand(_:)/title",
          "value": "splitViewControllerDidExpand:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewControllerDidExpand(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "splitViewControllerDidExpand:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewController(_:willShow:invalidating:)/title",
          "value": "splitViewController:willShowViewController:invalidatingBarButtonItem:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewController(_:willShow:invalidating:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "splitViewController:willShowViewController:invalidatingBarButtonItem:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewController(_:willChangeTo:)/title",
          "value": "splitViewController:willChangeToDisplayMode:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewController(_:willChangeTo:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "splitViewController:willChangeToDisplayMode:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewController(_:willHide:with:for:)/title",
          "value": "splitViewController:willHideViewController:withBarButtonItem:forPopoverController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewController(_:willHide:with:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "splitViewController:willHideViewController:withBarButtonItem:forPopoverController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewController(_:willHide:)/title",
          "value": "splitViewController:willHideColumn:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewController(_:willHide:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "splitViewController:willHideColumn:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1primaryViewController(forExpanding:)/title",
          "value": "primaryViewControllerForExpandingSplitViewController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1primaryViewController(forExpanding:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "primaryViewControllerForExpandingSplitViewController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewControllerPreferredInterfaceOrientationForPresentation(_:)/title",
          "value": "splitViewControllerPreferredInterfaceOrientationForPresentation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewControllerPreferredInterfaceOrientationForPresentation(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "splitViewControllerPreferredInterfaceOrientationForPresentation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewControllerInteractivePresentationGestureWillBegin(_:)/title",
          "value": "splitViewControllerInteractivePresentationGestureWillBegin:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewControllerInteractivePresentationGestureWillBegin(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "splitViewControllerInteractivePresentationGestureWillBegin:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewController(_:shouldHide:in:)/title",
          "value": "splitViewController:shouldHideViewController:inOrientation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewController(_:shouldHide:in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "splitViewController:shouldHideViewController:inOrientation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewController(_:willShow:)/title",
          "value": "splitViewController:willShowColumn:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewController(_:willShow:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "splitViewController:willShowColumn:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController/title",
          "value": "UISplitViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISplitViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISplitViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1targetDisplayModeForAction(in:)/title",
          "value": "targetDisplayModeForActionInSplitViewController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1targetDisplayModeForAction(in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "targetDisplayModeForActionInSplitViewController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewControllerDidCollapse(_:)/title",
          "value": "splitViewControllerDidCollapse:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewControllerDidCollapse(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "splitViewControllerDidCollapse:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewController(_:displayModeForExpandingToProposedDisplayMode:)/title",
          "value": "splitViewController:displayModeForExpandingToProposedDisplayMode:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewController(_:displayModeForExpandingToProposedDisplayMode:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "splitViewController:displayModeForExpandingToProposedDisplayMode:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate/title",
          "value": "UISplitViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISplitViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISplitViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewControllerSupportedInterfaceOrientations(_:)/title",
          "value": "splitViewControllerSupportedInterfaceOrientations:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewControllerSupportedInterfaceOrientations(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "splitViewControllerSupportedInterfaceOrientations:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewControllerInteractivePresentationGestureDidEnd(_:)/title",
          "value": "splitViewControllerInteractivePresentationGestureDidEnd:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewControllerInteractivePresentationGestureDidEnd(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "splitViewControllerInteractivePresentationGestureDidEnd:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewController(_:separateSecondaryFrom:)/title",
          "value": "splitViewController:separateSecondaryViewControllerFromPrimaryViewController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewController(_:separateSecondaryFrom:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "splitViewController:separateSecondaryViewControllerFromPrimaryViewController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1primaryViewController(forCollapsing:)/title",
          "value": "primaryViewControllerForCollapsingSplitViewController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1primaryViewController(forCollapsing:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "primaryViewControllerForCollapsingSplitViewController:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uisplitviewcontrollerdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uisplitviewcontrollerdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
