{
  "abstract": [
    {
      "text": "The interface that determines if an object supports a spring-loaded interaction for drag and drop activities.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UISpringLoadedInteractionSupporting"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UISpringLoadedInteractionSupporting",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UISpringLoadedInteractionSupporting"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UISpringLoadedInteractionSupporting"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "UISpringLoadedInteractionSupporting"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UISpringLoadedInteractionSupporting"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAlertController": {
      "abstract": [
        {
          "text": "An object that displays an alert message.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAlertController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAlertController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAlertController"
        }
      ],
      "role": "symbol",
      "title": "UIAlertController",
      "type": "topic",
      "url": "/documentation/uikit/uialertcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem": {
      "abstract": [
        {
          "text": "A specialized button for placement on a toolbar, navigation bar, or shortcuts bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIBarButtonItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonItem"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIButton": {
      "abstract": [
        {
          "text": "A control that executes your custom code in response to user interactions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIButton"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIButton",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIButton"
        }
      ],
      "role": "symbol",
      "title": "UIButton",
      "type": "topic",
      "url": "/documentation/uikit/uibutton"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionView": {
      "abstract": [
        {
          "text": "An object that manages an ordered collection of data items and presents them using customizable layouts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICollectionView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICollectionView"
        }
      ],
      "role": "symbol",
      "title": "UICollectionView",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchTab": {
      "abstract": [
        {
          "text": "A tab subclass that represents the system’s search tab.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISearchTab"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchTab",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISearchTab"
        }
      ],
      "role": "symbol",
      "title": "UISearchTab",
      "type": "topic",
      "url": "/documentation/uikit/uisearchtab"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISegmentedControl": {
      "abstract": [
        {
          "text": "A horizontal control that consists of multiple segments, each segment functioning as a discrete button.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISegmentedControl"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISegmentedControl",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISegmentedControl"
        }
      ],
      "role": "symbol",
      "title": "UISegmentedControl",
      "type": "topic",
      "url": "/documentation/uikit/uisegmentedcontrol"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISpringLoadedInteraction": {
      "abstract": [
        {
          "text": "An interaction object for configuring and controlling spring-loaded, user-driven navigation during a drag activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISpringLoadedInteraction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISpringLoadedInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISpringLoadedInteraction"
        }
      ],
      "role": "symbol",
      "title": "UISpringLoadedInteraction",
      "type": "topic",
      "url": "/documentation/uikit/uispringloadedinteraction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISpringLoadedInteractionBehavior": {
      "abstract": [
        {
          "text": "The interface for specifying the behavior of a spring-loaded interaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISpringLoadedInteractionBehavior"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISpringLoadedInteractionBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISpringLoadedInteractionBehavior"
        }
      ],
      "role": "symbol",
      "title": "UISpringLoadedInteractionBehavior",
      "type": "topic",
      "url": "/documentation/uikit/uispringloadedinteractionbehavior"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISpringLoadedInteractionContext": {
      "abstract": [
        {
          "text": "The interface an object implements to provide information about a spring-loaded interaction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISpringLoadedInteractionContext"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISpringLoadedInteractionContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISpringLoadedInteractionContext"
        }
      ],
      "role": "symbol",
      "title": "UISpringLoadedInteractionContext",
      "type": "topic",
      "url": "/documentation/uikit/uispringloadedinteractioncontext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISpringLoadedInteractionEffect": {
      "abstract": [
        {
          "text": "The interface for providing visual styling to a spring-loaded interaction based on the interaction state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISpringLoadedInteractionEffect"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISpringLoadedInteractionEffect",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISpringLoadedInteractionEffect"
        }
      ],
      "role": "symbol",
      "title": "UISpringLoadedInteractionEffect",
      "type": "topic",
      "url": "/documentation/uikit/uispringloadedinteractioneffect"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISpringLoadedInteractionSupporting": {
      "abstract": [
        {
          "text": "The interface that determines if an object supports a spring-loaded interaction for drag and drop activities.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISpringLoadedInteractionSupporting"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISpringLoadedInteractionSupporting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISpringLoadedInteractionSupporting"
        }
      ],
      "role": "symbol",
      "title": "UISpringLoadedInteractionSupporting",
      "type": "topic",
      "url": "/documentation/uikit/uispringloadedinteractionsupporting"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISpringLoadedInteractionSupporting/isSpringLoaded": {
      "abstract": [
        {
          "text": "A Boolean value that specifies whether the object is participating in spring-loaded interaction for a drag and drop activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isSpringLoaded"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISpringLoadedInteractionSupporting/isSpringLoaded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "springLoaded"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "isSpringLoaded",
      "type": "topic",
      "url": "/documentation/uikit/uispringloadedinteractionsupporting/isspringloaded"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITab": {
      "abstract": [
        {
          "text": "An object that manages a tab in a tab bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITab"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITab",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITab"
        }
      ],
      "role": "symbol",
      "title": "UITab",
      "type": "topic",
      "url": "/documentation/uikit/uitab"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBar": {
      "abstract": [
        {
          "text": "A control that displays one or more buttons in a tab bar for selecting between different subtasks, views, or modes in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITabBar"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabBar"
        }
      ],
      "role": "symbol",
      "title": "UITabBar",
      "type": "topic",
      "url": "/documentation/uikit/uitabbar"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarItem": {
      "abstract": [
        {
          "text": "An object that describes an item in a tab bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITabBarItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabBarItem"
        }
      ],
      "role": "symbol",
      "title": "UITabBarItem",
      "type": "topic",
      "url": "/documentation/uikit/uitabbaritem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabGroup": {
      "abstract": [
        {
          "text": "An object that manages a collection of tab objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITabGroup"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabGroup"
        }
      ],
      "role": "symbol",
      "title": "UITabGroup",
      "type": "topic",
      "url": "/documentation/uikit/uitabgroup"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableView": {
      "abstract": [
        {
          "text": "A view that presents data using rows in a single column.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITableView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableView"
        }
      ],
      "role": "symbol",
      "title": "UITableView",
      "type": "topic",
      "url": "/documentation/uikit/uitableview"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIAlertController",
        "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem",
        "doc://com.apple.uikit/documentation/UIKit/UIButton",
        "doc://com.apple.uikit/documentation/UIKit/UICollectionView",
        "doc://com.apple.uikit/documentation/UIKit/UISearchTab",
        "doc://com.apple.uikit/documentation/UIKit/UISegmentedControl",
        "doc://com.apple.uikit/documentation/UIKit/UITab",
        "doc://com.apple.uikit/documentation/UIKit/UITabBar",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarItem",
        "doc://com.apple.uikit/documentation/UIKit/UITabGroup",
        "doc://com.apple.uikit/documentation/UIKit/UITableView"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Spring-loaded-interactions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISpringLoadedInteractionBehavior",
        "doc://com.apple.uikit/documentation/UIKit/UISpringLoadedInteraction",
        "doc://com.apple.uikit/documentation/UIKit/UISpringLoadedInteractionContext",
        "doc://com.apple.uikit/documentation/UIKit/UISpringLoadedInteractionEffect"
      ],
      "title": "Spring-loaded interactions"
    }
  ],
  "topicSections": [
    {
      "anchor": "Checking-the-spring-loaded-interaction-status",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISpringLoadedInteractionSupporting/isSpringLoaded"
      ],
      "title": "Checking the spring-loaded interaction status"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UISpringLoadedInteractionSupporting"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISpringLoadedInteractionSupporting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISpringLoadedInteractionSupporting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Checking-the-spring-loaded-interaction-status",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UISpringLoadedInteractionSupporting/isSpringLoaded"
              ],
              "title": "Checking the spring-loaded interaction status"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIAlertController",
                "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem",
                "doc://com.apple.uikit/documentation/UIKit/UIButton",
                "doc://com.apple.uikit/documentation/UIKit/UICollectionView",
                "doc://com.apple.uikit/documentation/UIKit/UISegmentedControl",
                "doc://com.apple.uikit/documentation/UIKit/UITab",
                "doc://com.apple.uikit/documentation/UIKit/UITabBar",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarItem",
                "doc://com.apple.uikit/documentation/UIKit/UITableView"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Spring-loaded-interactions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UISpringLoadedInteractionBehavior",
                "doc://com.apple.uikit/documentation/UIKit/UISpringLoadedInteraction",
                "doc://com.apple.uikit/documentation/UIKit/UISpringLoadedInteractionContext",
                "doc://com.apple.uikit/documentation/UIKit/UISpringLoadedInteractionEffect"
              ],
              "title": "Spring-loaded interactions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UISpringLoadedInteractionSupporting"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAlertController/title",
          "value": "UIAlertController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAlertController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAlertController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAlertController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAlertController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/title",
          "value": "UIButton"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIButton/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIButton"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISpringLoadedInteraction/title",
          "value": "UISpringLoadedInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISpringLoadedInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISpringLoadedInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISpringLoadedInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISpringLoadedInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchTab/title",
          "value": "UISearchTab"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchTab/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchTab"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchTab/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchTab"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISpringLoadedInteractionContext/title",
          "value": "UISpringLoadedInteractionContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISpringLoadedInteractionContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISpringLoadedInteractionContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISpringLoadedInteractionContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISpringLoadedInteractionContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISpringLoadedInteractionEffect/title",
          "value": "UISpringLoadedInteractionEffect"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISpringLoadedInteractionEffect/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISpringLoadedInteractionEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISpringLoadedInteractionEffect/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISpringLoadedInteractionEffect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabGroup/title",
          "value": "UITabGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabGroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab/title",
          "value": "UITab"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITab"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITab/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITab"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView/title",
          "value": "UITableView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISpringLoadedInteractionBehavior/title",
          "value": "UISpringLoadedInteractionBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISpringLoadedInteractionBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISpringLoadedInteractionBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISpringLoadedInteractionBehavior/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISpringLoadedInteractionBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem/title",
          "value": "UITabBarItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISpringLoadedInteractionSupporting/title",
          "value": "UISpringLoadedInteractionSupporting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISpringLoadedInteractionSupporting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISpringLoadedInteractionSupporting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISpringLoadedInteractionSupporting/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISpringLoadedInteractionSupporting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISpringLoadedInteractionSupporting~1isSpringLoaded/title",
          "value": "springLoaded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISpringLoadedInteractionSupporting~1isSpringLoaded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "springLoaded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem/title",
          "value": "UIBarButtonItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView/title",
          "value": "UICollectionView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICollectionView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICollectionView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISegmentedControl/title",
          "value": "UISegmentedControl"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISegmentedControl/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISegmentedControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISegmentedControl/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISegmentedControl"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar/title",
          "value": "UITabBar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBar"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uispringloadedinteractionsupporting"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uispringloadedinteractionsupporting"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
