{
  "abstract": [
    {
      "text": "Constants that describe the style of the device’s status bar.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIStatusBarStyle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIStatusBarStyle",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIStatusBarStyle"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIStatusBarStyle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "UIStatusBarStyle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIStatusBarStyle"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIStatusBarStyle": {
      "abstract": [
        {
          "text": "Constants that describe the style of the device’s status bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIStatusBarStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIStatusBarStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIStatusBarStyle"
        }
      ],
      "role": "symbol",
      "title": "UIStatusBarStyle",
      "type": "topic",
      "url": "/documentation/uikit/uistatusbarstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIStatusBarStyle/UIStatusBarStyleBlackOpaque": {
      "abstract": [
        {
          "text": "An opaque black style.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIStatusBarStyleBlackOpaque"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIStatusBarStyle/UIStatusBarStyleBlackOpaque",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIStatusBarStyleBlackOpaque",
      "type": "topic",
      "url": "/documentation/uikit/uistatusbarstyle/uistatusbarstyleblackopaque"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIStatusBarStyle/UIStatusBarStyleBlackTranslucent": {
      "abstract": [
        {
          "text": "A transparent black style.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIStatusBarStyleBlackTranslucent"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIStatusBarStyle/UIStatusBarStyleBlackTranslucent",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIStatusBarStyleBlackTranslucent",
      "type": "topic",
      "url": "/documentation/uikit/uistatusbarstyle/uistatusbarstyleblacktranslucent"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIStatusBarStyle/darkContent": {
      "abstract": [
        {
          "text": "A dark status bar, intended for use on light backgrounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "darkContent"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIStatusBarStyle/darkContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIStatusBarStyleDarkContent"
        }
      ],
      "role": "symbol",
      "title": "UIStatusBarStyle.darkContent",
      "type": "topic",
      "url": "/documentation/uikit/uistatusbarstyle/darkcontent"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIStatusBarStyle/default": {
      "abstract": [
        {
          "text": "A style that automatically selects an appearance for the status bar and updates it dynamically to maintain contrast with the content below it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "`default`"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIStatusBarStyle/default",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIStatusBarStyleDefault"
        }
      ],
      "role": "symbol",
      "title": "UIStatusBarStyle.default",
      "type": "topic",
      "url": "/documentation/uikit/uistatusbarstyle/default"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIStatusBarStyle/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIStatusBarStyle/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/uistatusbarstyle/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIStatusBarStyle/lightContent": {
      "abstract": [
        {
          "text": "A light status bar, intended for use on dark backgrounds.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lightContent"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIStatusBarStyle/lightContent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIStatusBarStyleLightContent"
        }
      ],
      "role": "symbol",
      "title": "UIStatusBarStyle.lightContent",
      "type": "topic",
      "url": "/documentation/uikit/uistatusbarstyle/lightcontent"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/childForStatusBarHidden": {
      "abstract": [
        {
          "text": "The view controller to use for determining the hidden state of the status bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "childForStatusBarHidden"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/childForStatusBarHidden",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "childViewControllerForStatusBarHidden"
        }
      ],
      "role": "symbol",
      "title": "childForStatusBarHidden",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/childforstatusbarhidden"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/childForStatusBarStyle": {
      "abstract": [
        {
          "text": "Called when the system needs the view controller to use for determining status bar style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "childForStatusBarStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/childForStatusBarStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "childViewControllerForStatusBarStyle"
        }
      ],
      "role": "symbol",
      "title": "childForStatusBarStyle",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/childforstatusbarstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/modalPresentationCapturesStatusBarAppearance": {
      "abstract": [
        {
          "text": "Specifies whether a view controller, presented non-fullscreen, takes over control of status bar appearance from the presenting view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "modalPresentationCapturesStatusBarAppearance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/modalPresentationCapturesStatusBarAppearance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "modalPresentationCapturesStatusBarAppearance"
        }
      ],
      "role": "symbol",
      "title": "modalPresentationCapturesStatusBarAppearance",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/modalpresentationcapturesstatusbarappearance"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/preferredStatusBarStyle": {
      "abstract": [
        {
          "text": "The preferred status bar style for the view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredStatusBarStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIStatusBarStyle",
          "text": "UIStatusBarStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/preferredStatusBarStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredStatusBarStyle"
        }
      ],
      "role": "symbol",
      "title": "preferredStatusBarStyle",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/preferredstatusbarstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/preferredStatusBarUpdateAnimation": {
      "abstract": [
        {
          "text": "Specifies the animation style to use for hiding and showing the status bar for the view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredStatusBarUpdateAnimation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIStatusBarAnimation",
          "text": "UIStatusBarAnimation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/preferredStatusBarUpdateAnimation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "preferredStatusBarUpdateAnimation"
        }
      ],
      "role": "symbol",
      "title": "preferredStatusBarUpdateAnimation",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/preferredstatusbarupdateanimation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/prefersStatusBarHidden": {
      "abstract": [
        {
          "text": "Specifies whether the view controller prefers the status bar to be hidden or shown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prefersStatusBarHidden"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/prefersStatusBarHidden",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "prefersStatusBarHidden"
        }
      ],
      "role": "symbol",
      "title": "prefersStatusBarHidden",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/prefersstatusbarhidden"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/setNeedsStatusBarAppearanceUpdate()": {
      "abstract": [
        {
          "text": "Indicates to the system that the view controller status bar attributes have changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setNeedsStatusBarAppearanceUpdate"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/setNeedsStatusBarAppearanceUpdate()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setNeedsStatusBarAppearanceUpdate"
        }
      ],
      "role": "symbol",
      "title": "setNeedsStatusBarAppearanceUpdate()",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/setneedsstatusbarappearanceupdate()"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Managing-the-status-bar",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/prefersStatusBarHidden",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/childForStatusBarHidden",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/childForStatusBarStyle",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/preferredStatusBarStyle",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/modalPresentationCapturesStatusBarAppearance",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/preferredStatusBarUpdateAnimation",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/setNeedsStatusBarAppearanceUpdate()"
      ],
      "title": "Managing the status bar"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIStatusBarStyle/default",
        "doc://com.apple.uikit/documentation/UIKit/UIStatusBarStyle/lightContent",
        "doc://com.apple.uikit/documentation/UIKit/UIStatusBarStyle/darkContent"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIStatusBarStyle/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIStatusBarStyle"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIStatusBarStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIStatusBarStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIStatusBarStyle/default",
                "doc://com.apple.uikit/documentation/UIKit/UIStatusBarStyle/lightContent",
                "doc://com.apple.uikit/documentation/UIKit/UIStatusBarStyle/darkContent"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIStatusBarStyle/UIStatusBarStyleBlackTranslucent",
                "doc://com.apple.uikit/documentation/UIKit/UIStatusBarStyle/UIStatusBarStyleBlackOpaque"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Managing-the-status-bar",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/prefersStatusBarHidden",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/childForStatusBarHidden",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/childForStatusBarStyle",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/preferredStatusBarStyle",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/modalPresentationCapturesStatusBarAppearance",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/preferredStatusBarUpdateAnimation",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/setNeedsStatusBarAppearanceUpdate()"
              ],
              "title": "Managing the status bar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIStatusBarStyle"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1prefersStatusBarHidden/title",
          "value": "prefersStatusBarHidden"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1prefersStatusBarHidden/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "prefersStatusBarHidden"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1modalPresentationCapturesStatusBarAppearance/title",
          "value": "modalPresentationCapturesStatusBarAppearance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1modalPresentationCapturesStatusBarAppearance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "modalPresentationCapturesStatusBarAppearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStatusBarStyle~1default/title",
          "value": "UIStatusBarStyleDefault"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStatusBarStyle~1default/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIStatusBarStyleDefault"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1preferredStatusBarUpdateAnimation/title",
          "value": "preferredStatusBarUpdateAnimation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1preferredStatusBarUpdateAnimation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preferredStatusBarUpdateAnimation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1preferredStatusBarStyle/title",
          "value": "preferredStatusBarStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1preferredStatusBarStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "preferredStatusBarStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStatusBarStyle~1lightContent/title",
          "value": "UIStatusBarStyleLightContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStatusBarStyle~1lightContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIStatusBarStyleLightContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1setNeedsStatusBarAppearanceUpdate()/title",
          "value": "setNeedsStatusBarAppearanceUpdate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1setNeedsStatusBarAppearanceUpdate()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setNeedsStatusBarAppearanceUpdate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1childForStatusBarHidden/title",
          "value": "childViewControllerForStatusBarHidden"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1childForStatusBarHidden/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "childViewControllerForStatusBarHidden"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStatusBarStyle~1darkContent/title",
          "value": "UIStatusBarStyleDarkContent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStatusBarStyle~1darkContent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIStatusBarStyleDarkContent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1childForStatusBarStyle/title",
          "value": "childViewControllerForStatusBarStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1childForStatusBarStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "childViewControllerForStatusBarStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStatusBarStyle/title",
          "value": "UIStatusBarStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStatusBarStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIStatusBarStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStatusBarStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIStatusBarStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uistatusbarstyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uistatusbarstyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
