{
  "abstract": [
    {
      "text": "Customize appearance information directly on the tab bar object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/view-controllers",
        "doc://com.apple.uikit/documentation/UIKit/UITabBar"
      ],
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/views-and-controls",
        "doc://com.apple.uikit/documentation/UIKit/UITabBar"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/uitabbar-legacy-customizations"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Legacy customizations"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "In iOS 13 and later, customize your tab bar using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBar/standardAppearance",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property. You may also continue to use these legacy accessors to customize your tab bar’s appearance directly.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarStyle": {
      "abstract": [
        {
          "text": "Defines the stylistic appearance of different types of views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIBarStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarStyle"
        }
      ],
      "role": "symbol",
      "title": "UIBarStyle",
      "type": "topic",
      "url": "/documentation/uikit/uibarstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBar": {
      "abstract": [
        {
          "text": "A control that displays one or more buttons in a tab bar for selecting between different subtasks, views, or modes in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITabBar"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabBar"
        }
      ],
      "role": "symbol",
      "title": "UITabBar",
      "type": "topic",
      "url": "/documentation/uikit/uitabbar"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBar/ItemPositioning-swift.enum": {
      "abstract": [
        {
          "text": "Constants that specify tab bar item positioning.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ItemPositioning"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBar/ItemPositioning-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ItemPositioning"
        }
      ],
      "role": "symbol",
      "title": "UITabBar.ItemPositioning",
      "type": "topic",
      "url": "/documentation/uikit/uitabbar/itempositioning-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBar/backgroundImage": {
      "abstract": [
        {
          "text": "The custom background image for the tab bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "backgroundImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBar/backgroundImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "backgroundImage"
        }
      ],
      "role": "symbol",
      "title": "backgroundImage",
      "type": "topic",
      "url": "/documentation/uikit/uitabbar/backgroundimage"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBar/barStyle": {
      "abstract": [
        {
          "text": "The tab bar style that specifies its appearance.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "barStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIBarStyle",
          "text": "UIBarStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBar/barStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "barStyle"
        }
      ],
      "role": "symbol",
      "title": "barStyle",
      "type": "topic",
      "url": "/documentation/uikit/uitabbar/barstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBar/barTintColor": {
      "abstract": [
        {
          "text": "The tint color to apply to the tab bar background.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "barTintColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBar/barTintColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "barTintColor"
        }
      ],
      "role": "symbol",
      "title": "barTintColor",
      "type": "topic",
      "url": "/documentation/uikit/uitabbar/bartintcolor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBar/isTranslucent": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the tab bar is translucent.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isTranslucent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBar/isTranslucent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "translucent"
        }
      ],
      "role": "symbol",
      "title": "isTranslucent",
      "type": "topic",
      "url": "/documentation/uikit/uitabbar/istranslucent"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBar/itemPositioning-swift.property": {
      "abstract": [
        {
          "text": "The positioning scheme for the tab bar items in the tab bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "itemPositioning"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITabBar",
          "text": "UITabBar"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UITabBarItemPositioning",
          "text": "ItemPositioning"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBar/itemPositioning-swift.property",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "itemPositioning"
        }
      ],
      "role": "symbol",
      "title": "itemPositioning",
      "type": "topic",
      "url": "/documentation/uikit/uitabbar/itempositioning-swift.property"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBar/itemSpacing": {
      "abstract": [
        {
          "text": "The amount of space (in points) to use between tab bar items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "itemSpacing"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBar/itemSpacing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "itemSpacing"
        }
      ],
      "role": "symbol",
      "title": "itemSpacing",
      "type": "topic",
      "url": "/documentation/uikit/uitabbar/itemspacing"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBar/itemWidth": {
      "abstract": [
        {
          "text": "The width (in points) of tab bar items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "itemWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBar/itemWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "itemWidth"
        }
      ],
      "role": "symbol",
      "title": "itemWidth",
      "type": "topic",
      "url": "/documentation/uikit/uitabbar/itemwidth"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBar/leadingAccessoryView": {
      "abstract": [
        {
          "text": "The view at the leading edge of a tab bar on tvOS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leadingAccessoryView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBar/leadingAccessoryView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "leadingAccessoryView"
        }
      ],
      "role": "symbol",
      "title": "leadingAccessoryView",
      "type": "topic",
      "url": "/documentation/uikit/uitabbar/leadingaccessoryview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBar/scrollEdgeAppearance": {
      "abstract": [
        {
          "text": "The appearance settings for the tab bar when the edge of scrollable content aligns with the edge of the tab bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scrollEdgeAppearance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITabBarAppearance",
          "text": "UITabBarAppearance"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBar/scrollEdgeAppearance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scrollEdgeAppearance"
        }
      ],
      "role": "symbol",
      "title": "scrollEdgeAppearance",
      "type": "topic",
      "url": "/documentation/uikit/uitabbar/scrolledgeappearance"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBar/selectedImageTintColor": {
      "abstract": [
        {
          "text": "The tint color applied to the selected tab bar item.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectedImageTintColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBar/selectedImageTintColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectedImageTintColor"
        }
      ],
      "role": "symbol",
      "title": "selectedImageTintColor",
      "type": "topic",
      "url": "/documentation/uikit/uitabbar/selectedimagetintcolor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBar/selectionIndicatorImage": {
      "abstract": [
        {
          "text": "The image to use for the selection indicator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectionIndicatorImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBar/selectionIndicatorImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectionIndicatorImage"
        }
      ],
      "role": "symbol",
      "title": "selectionIndicatorImage",
      "type": "topic",
      "url": "/documentation/uikit/uitabbar/selectionindicatorimage"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBar/shadowImage": {
      "abstract": [
        {
          "text": "The shadow image to use for the tab bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shadowImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBar/shadowImage",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shadowImage"
        }
      ],
      "role": "symbol",
      "title": "shadowImage",
      "type": "topic",
      "url": "/documentation/uikit/uitabbar/shadowimage"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBar/standardAppearance": {
      "abstract": [
        {
          "text": "The appearance settings for a standard-height tab bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "standardAppearance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITabBarAppearance",
          "text": "UITabBarAppearance"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBar/standardAppearance",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "standardAppearance"
        }
      ],
      "role": "symbol",
      "title": "standardAppearance",
      "type": "topic",
      "url": "/documentation/uikit/uitabbar/standardappearance"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBar/tintColor": {
      "abstract": [
        {
          "text": "The tint color to apply to the tab bar items.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tintColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        },
        {
          "kind": "text",
          "text": "!"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBar/tintColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tintColor"
        }
      ],
      "role": "symbol",
      "title": "tintColor",
      "type": "topic",
      "url": "/documentation/uikit/uitabbar/tintcolor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBar/trailingAccessoryView": {
      "abstract": [
        {
          "text": "The view at the trailing edge of a tab bar on tvOS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trailingAccessoryView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBar/trailingAccessoryView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "trailingAccessoryView"
        }
      ],
      "role": "symbol",
      "title": "trailingAccessoryView",
      "type": "topic",
      "url": "/documentation/uikit/uitabbar/trailingaccessoryview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBar/unselectedItemTintColor": {
      "abstract": [
        {
          "text": "The tint color to apply to unselected tabs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unselectedItemTintColor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIColor",
          "text": "UIColor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBar/unselectedItemTintColor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unselectedItemTintColor"
        }
      ],
      "role": "symbol",
      "title": "unselectedItemTintColor",
      "type": "topic",
      "url": "/documentation/uikit/uitabbar/unselecteditemtintcolor"
    },
    "doc://com.apple.uikit/documentation/UIKit/view-controllers": {
      "abstract": [
        {
          "text": "Manage your interface using view controllers and facilitate navigation around your app’s content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/view-controllers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "View controllers",
      "type": "topic",
      "url": "/documentation/uikit/view-controllers"
    },
    "doc://com.apple.uikit/documentation/UIKit/views-and-controls": {
      "abstract": [
        {
          "text": "Present your content onscreen and define the interactions allowed with that content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/views-and-controls",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Views and controls",
      "type": "topic",
      "url": "/documentation/uikit/views-and-controls"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Customizing-tab-bar-appearance",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITabBar/standardAppearance",
        "doc://com.apple.uikit/documentation/UIKit/UITabBar/scrollEdgeAppearance",
        "doc://com.apple.uikit/documentation/UIKit/UITabBar/leadingAccessoryView",
        "doc://com.apple.uikit/documentation/UIKit/UITabBar/trailingAccessoryView",
        "doc://com.apple.uikit/documentation/UIKit/UITabBar/isTranslucent"
      ],
      "title": "Customizing tab bar appearance"
    }
  ],
  "topicSections": [
    {
      "anchor": "Setting-the-bars-style",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITabBar/barStyle",
        "doc://com.apple.uikit/documentation/UIKit/UIBarStyle"
      ],
      "title": "Setting the bar’s style"
    },
    {
      "anchor": "Configuring-tab-bar-items",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITabBar/tintColor"
      ],
      "title": "Configuring tab bar items"
    },
    {
      "anchor": "Customizing-item-spacing",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITabBar/itemPositioning-swift.property",
        "doc://com.apple.uikit/documentation/UIKit/UITabBar/ItemPositioning-swift.enum",
        "doc://com.apple.uikit/documentation/UIKit/UITabBar/itemSpacing",
        "doc://com.apple.uikit/documentation/UIKit/UITabBar/itemWidth"
      ],
      "title": "Customizing item spacing"
    },
    {
      "anchor": "Configuring-selection-appearance",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITabBar/unselectedItemTintColor",
        "doc://com.apple.uikit/documentation/UIKit/UITabBar/selectionIndicatorImage",
        "doc://com.apple.uikit/documentation/UIKit/UITabBar/selectedImageTintColor"
      ],
      "title": "Configuring selection appearance"
    },
    {
      "anchor": "Changing-the-background",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITabBar/barTintColor",
        "doc://com.apple.uikit/documentation/UIKit/UITabBar/backgroundImage"
      ],
      "title": "Changing the background"
    },
    {
      "anchor": "Adding-a-shadow",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITabBar/shadowImage"
      ],
      "title": "Adding a shadow"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Setting-the-bars-style",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITabBar/barStyle",
                "doc://com.apple.uikit/documentation/UIKit/UIBarStyle"
              ],
              "title": "Setting the bar’s style"
            },
            {
              "anchor": "Configuring-tab-bar-items",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITabBar/tintColor"
              ],
              "title": "Configuring tab bar items"
            },
            {
              "anchor": "Customizing-item-spacing",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITabBar/itemPositioning-swift.property",
                "doc://com.apple.uikit/documentation/UIKit/UITabBar/ItemPositioning-swift.enum",
                "doc://com.apple.uikit/documentation/UIKit/UITabBar/itemSpacing",
                "doc://com.apple.uikit/documentation/UIKit/UITabBar/itemWidth"
              ],
              "title": "Customizing item spacing"
            },
            {
              "anchor": "Configuring-selection-appearance",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITabBar/unselectedItemTintColor",
                "doc://com.apple.uikit/documentation/UIKit/UITabBar/selectionIndicatorImage",
                "doc://com.apple.uikit/documentation/UIKit/UITabBar/selectedImageTintColor"
              ],
              "title": "Configuring selection appearance"
            },
            {
              "anchor": "Changing-the-background",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITabBar/barTintColor",
                "doc://com.apple.uikit/documentation/UIKit/UITabBar/backgroundImage"
              ],
              "title": "Changing the background"
            },
            {
              "anchor": "Adding-a-shadow",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITabBar/shadowImage"
              ],
              "title": "Adding a shadow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Customizing-tab-bar-appearance",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITabBar/standardAppearance",
                "doc://com.apple.uikit/documentation/UIKit/UITabBar/scrollEdgeAppearance",
                "doc://com.apple.uikit/documentation/UIKit/UITabBar/leadingAccessoryView",
                "doc://com.apple.uikit/documentation/UIKit/UITabBar/trailingAccessoryView",
                "doc://com.apple.uikit/documentation/UIKit/UITabBar/isTranslucent"
              ],
              "title": "Customizing tab bar appearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1selectionIndicatorImage/title",
          "value": "selectionIndicatorImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1selectionIndicatorImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "selectionIndicatorImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1isTranslucent/title",
          "value": "translucent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1isTranslucent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "translucent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1ItemPositioning-swift.enum/title",
          "value": "UITabBarItemPositioning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1ItemPositioning-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarItemPositioning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1ItemPositioning-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarItemPositioning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarStyle/title",
          "value": "UIBarStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1standardAppearance/title",
          "value": "standardAppearance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1standardAppearance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "standardAppearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1unselectedItemTintColor/title",
          "value": "unselectedItemTintColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1unselectedItemTintColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "unselectedItemTintColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1leadingAccessoryView/title",
          "value": "leadingAccessoryView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1leadingAccessoryView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "leadingAccessoryView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1shadowImage/title",
          "value": "shadowImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1shadowImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shadowImage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar/title",
          "value": "UITabBar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1itemSpacing/title",
          "value": "itemSpacing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1itemSpacing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "itemSpacing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1trailingAccessoryView/title",
          "value": "trailingAccessoryView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1trailingAccessoryView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "trailingAccessoryView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1itemPositioning-swift.property/title",
          "value": "itemPositioning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1itemPositioning-swift.property/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "itemPositioning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1selectedImageTintColor/title",
          "value": "selectedImageTintColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1selectedImageTintColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "selectedImageTintColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1barTintColor/title",
          "value": "barTintColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1barTintColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "barTintColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1itemWidth/title",
          "value": "itemWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1itemWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "itemWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1scrollEdgeAppearance/title",
          "value": "scrollEdgeAppearance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1scrollEdgeAppearance/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "scrollEdgeAppearance"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1barStyle/title",
          "value": "barStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1barStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "barStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1tintColor/title",
          "value": "tintColor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1tintColor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "tintColor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1backgroundImage/title",
          "value": "backgroundImage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBar~1backgroundImage/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "backgroundImage"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitabbar-legacy-customizations"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uitabbar-legacy-customizations"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
