{
  "abstract": [
    {
      "text": "An object for tracking a placeholder cell that you added to your table during a drop operation.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITableViewDropPlaceholderContext"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UITableViewDropPlaceholderContext",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UITableViewDropPlaceholderContext"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UITableViewDropPlaceholderContext"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "UITableViewDropPlaceholderContext"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UITableViewDropPlaceholderContext"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDragAnimating",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)UIDragAnimating",
              "text": "UIDragAnimating"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Don’t create instances of this class yourself. Instead, call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewDropCoordinator/drop(_:to:)-3znax",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " from your drop coordinator object. That method inserts a placeholder cell into the table and returns a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewDropPlaceholderContext",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object for managing that placeholder.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When you’re ready to swap a placeholder cell for a cell with the actual data, call the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewDropPlaceholderContext/commitInsertion(dataSourceUpdates:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method of the context object. To remove the placeholder cell without providing a replacement, call ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewDropPlaceholderContext/deletePlaceholder()",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instead.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDragAnimating": {
      "abstract": [
        {
          "text": "The interface for providing custom animation alongside the system’s lift, drop, and cancellation animations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDragAnimating"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDragAnimating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDragAnimating"
        }
      ],
      "role": "symbol",
      "title": "UIDragAnimating",
      "type": "topic",
      "url": "/documentation/uikit/uidraganimating"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewDropCoordinator/drop(_:to:)-3znax": {
      "abstract": [
        {
          "text": "Animates the item to the specified location and inserts a placeholder cell at that location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDragItem",
          "text": "UIDragItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITableViewDropPlaceholder",
          "text": "UITableViewDropPlaceholder"
        },
        {
          "kind": "text",
          "text": ") -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITableViewDropPlaceholderContext",
          "text": "UITableViewDropPlaceholderContext"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewDropCoordinator/drop(_:to:)-3znax",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dropItem:toPlaceholder:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "drop(_:to:)",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewdropcoordinator/drop(_:to:)-3znax"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewDropPlaceholder": {
      "abstract": [
        {
          "text": "A placeholder cell that supports customizing the drop preview parameters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITableViewDropPlaceholder"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewDropPlaceholder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableViewDropPlaceholder"
        }
      ],
      "role": "symbol",
      "title": "UITableViewDropPlaceholder",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewdropplaceholder"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewDropPlaceholderContext": {
      "abstract": [
        {
          "text": "An object for tracking a placeholder cell that you added to your table during a drop operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITableViewDropPlaceholderContext"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewDropPlaceholderContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableViewDropPlaceholderContext"
        }
      ],
      "role": "symbol",
      "title": "UITableViewDropPlaceholderContext",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewdropplaceholdercontext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewDropPlaceholderContext/commitInsertion(dataSourceUpdates:)": {
      "abstract": [
        {
          "text": "Exchanges the placeholder cell for a cell with the final content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commitInsertion"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "dataSourceUpdates"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation9IndexPathV",
          "text": "IndexPath"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewDropPlaceholderContext/commitInsertion(dataSourceUpdates:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "commitInsertionWithDataSourceUpdates:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "commitInsertion(dataSourceUpdates:)",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewdropplaceholdercontext/commitinsertion(datasourceupdates:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewDropPlaceholderContext/deletePlaceholder()": {
      "abstract": [
        {
          "text": "Removes an unneeded placeholder cell from the table view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "deletePlaceholder"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewDropPlaceholderContext/deletePlaceholder()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "deletePlaceholder"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "deletePlaceholder()",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewdropplaceholdercontext/deleteplaceholder()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewDropPlaceholderContext/dragItem": {
      "abstract": [
        {
          "text": "The drag item represented by the placeholder cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dragItem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDragItem",
          "text": "UIDragItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewDropPlaceholderContext/dragItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dragItem"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "dragItem",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewdropplaceholdercontext/dragitem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewPlaceholder": {
      "abstract": [
        {
          "text": "An object that contains information about a placeholder cell being inserted into a table.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITableViewPlaceholder"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewPlaceholder",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableViewPlaceholder"
        }
      ],
      "role": "symbol",
      "title": "UITableViewPlaceholder",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewplaceholder"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.apple.uikit/documentation/UIKit/UIDragAnimating"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Placeholder-cells",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITableViewDropPlaceholder",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewPlaceholder"
      ],
      "title": "Placeholder cells"
    }
  ],
  "topicSections": [
    {
      "anchor": "Updating-the-placeholder-cell",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITableViewDropPlaceholderContext/commitInsertion(dataSourceUpdates:)"
      ],
      "title": "Updating the placeholder cell"
    },
    {
      "anchor": "Removing-the-placeholder-cell",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITableViewDropPlaceholderContext/deletePlaceholder()"
      ],
      "title": "Removing the placeholder cell"
    },
    {
      "anchor": "Getting-the-drag-item",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITableViewDropPlaceholderContext/dragItem"
      ],
      "title": "Getting the drag item"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UITableViewDropPlaceholderContext"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewDropPlaceholderContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewDropPlaceholderContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Updating-the-placeholder-cell",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITableViewDropPlaceholderContext/commitInsertion(dataSourceUpdates:)"
              ],
              "title": "Updating the placeholder cell"
            },
            {
              "anchor": "Removing-the-placeholder-cell",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITableViewDropPlaceholderContext/deletePlaceholder()"
              ],
              "title": "Removing the placeholder cell"
            },
            {
              "anchor": "Getting-the-drag-item",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITableViewDropPlaceholderContext/dragItem"
              ],
              "title": "Getting the drag item"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIDragAnimating"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Placeholder-cells",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITableViewDropPlaceholder",
                "doc://com.apple.uikit/documentation/UIKit/UITableViewPlaceholder"
              ],
              "title": "Placeholder cells"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UITableViewDropPlaceholderContext"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDragAnimating",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)UIDragAnimating",
                    "text": "UIDragAnimating"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDropPlaceholderContext~1commitInsertion(dataSourceUpdates:)/title",
          "value": "commitInsertionWithDataSourceUpdates:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDropPlaceholderContext~1commitInsertion(dataSourceUpdates:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "commitInsertionWithDataSourceUpdates:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewPlaceholder/title",
          "value": "UITableViewPlaceholder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewPlaceholder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewPlaceholder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewPlaceholder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewPlaceholder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDropPlaceholderContext~1dragItem/title",
          "value": "dragItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDropPlaceholderContext~1dragItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dragItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDropPlaceholder/title",
          "value": "UITableViewDropPlaceholder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDropPlaceholder/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewDropPlaceholder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDropPlaceholder/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewDropPlaceholder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragAnimating/title",
          "value": "UIDragAnimating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragAnimating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDragAnimating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDragAnimating/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDragAnimating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDropPlaceholderContext/title",
          "value": "UITableViewDropPlaceholderContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDropPlaceholderContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewDropPlaceholderContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDropPlaceholderContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewDropPlaceholderContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDropCoordinator~1drop(_:to:)-3znax/title",
          "value": "dropItem:toPlaceholder:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDropCoordinator~1drop(_:to:)-3znax/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dropItem:toPlaceholder:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDropPlaceholderContext~1deletePlaceholder()/title",
          "value": "deletePlaceholder"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDropPlaceholderContext~1deletePlaceholder()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "deletePlaceholder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitableviewdropplaceholdercontext"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uitableviewdropplaceholdercontext"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
