{
  "abstract": [
    {
      "text": "A set of methods you implement to customize the behavior of a tab bar.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UITabBarControllerDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UITabBarControllerDelegate"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UITabBarControllerDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "UITabBarControllerDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UITabBarControllerDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.uikit/documentation/UIKit/elevating-your-ipad-app-with-a-tab-bar-and-sidebar"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol when you want to augment the behavior of a tab bar. In particular, you can use it to determine whether specific tabs should be selected, to perform actions after a tab is selected, or to perform actions before or after the user customizes the order of the tabs. After implementing these methods in your custom object, you should then assign that object to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarController/delegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of the corresponding ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "All of the methods in this protocol are optional. For more information on how to use and configure tab bar controllers and their delegates, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/featuredarticles/ViewControllerPGforiPhoneOS/index.html#//apple_ref/doc/uid/TP40007457",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarController": {
      "abstract": [
        {
          "text": "A container view controller that manages a multiselection interface, where the selection determines which child view controller to display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITabBarController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabBarController"
        }
      ],
      "role": "symbol",
      "title": "UITabBarController",
      "type": "topic",
      "url": "/documentation/uikit/uitabbarcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarController/delegate": {
      "abstract": [
        {
          "text": "The tab bar controller’s delegate object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITabBarControllerDelegate",
          "text": "UITabBarControllerDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarController/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/uikit/uitabbarcontroller/delegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate": {
      "abstract": [
        {
          "text": "A set of methods you implement to customize the behavior of a tab bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITabBarControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITabBarControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "UITabBarControllerDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uitabbarcontrollerdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:animationControllerForTransitionFrom:to:)": {
      "abstract": [
        {
          "text": "Called to allow the delegate to return a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerAnimatedTransitioning",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " delegate object for use during a noninteractive tab bar view controller transition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabBarController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITabBarController",
          "text": "UITabBarController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "animationControllerForTransitionFrom"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIViewControllerAnimatedTransitioning",
          "text": "UIViewControllerAnimatedTransitioning"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:animationControllerForTransitionFrom:to:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tabBarController:animationControllerForTransitionFromViewController:toViewController:"
        }
      ],
      "role": "symbol",
      "title": "tabBarController(_:animationControllerForTransitionFrom:to:)",
      "type": "topic",
      "url": "/documentation/uikit/uitabbarcontrollerdelegate/tabbarcontroller(_:animationcontrollerfortransitionfrom:to:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:didEndCustomizing:changed:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the tab bar customization sheet was dismissed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabBarController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITabBarController",
          "text": "UITabBarController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didEndCustomizing"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "changed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:didEndCustomizing:changed:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tabBarController:didEndCustomizingViewControllers:changed:"
        }
      ],
      "role": "symbol",
      "title": "tabBarController(_:didEndCustomizing:changed:)",
      "type": "topic",
      "url": "/documentation/uikit/uitabbarcontrollerdelegate/tabbarcontroller(_:didendcustomizing:changed:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:didSelect:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user selected an item in the tab bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabBarController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITabBarController",
          "text": "UITabBarController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:didSelect:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tabBarController:didSelectViewController:"
        }
      ],
      "role": "symbol",
      "title": "tabBarController(_:didSelect:)",
      "type": "topic",
      "url": "/documentation/uikit/uitabbarcontrollerdelegate/tabbarcontroller(_:didselect:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:didSelectTab:previousTab:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabBarController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITabBarController",
          "text": "UITabBarController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didSelectTab"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITab",
          "text": "UITab"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "previousTab"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITab",
          "text": "UITab"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:didSelectTab:previousTab:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tabBarController:didSelectTab:previousTab:"
        }
      ],
      "role": "symbol",
      "title": "tabBarController(_:didSelectTab:previousTab:)",
      "type": "topic",
      "url": "/documentation/uikit/uitabbarcontrollerdelegate/tabbarcontroller(_:didselecttab:previoustab:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:displayOrderDidChangeFor:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabBarController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITabBarController",
          "text": "UITabBarController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "displayOrderDidChangeFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITabGroup",
          "text": "UITabGroup"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:displayOrderDidChangeFor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tabBarController:displayOrderDidChangeForGroup:"
        }
      ],
      "role": "symbol",
      "title": "tabBarController(_:displayOrderDidChangeFor:)",
      "type": "topic",
      "url": "/documentation/uikit/uitabbarcontrollerdelegate/tabbarcontroller(_:displayorderdidchangefor:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:displayedViewControllersFor:proposedViewControllers:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabBarController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITabBarController",
          "text": "UITabBarController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "displayedViewControllersFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITab",
          "text": "UITab"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "proposedViewControllers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": "]) -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:displayedViewControllersFor:proposedViewControllers:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tabBarController:displayedViewControllersForTab:proposedViewControllers:"
        }
      ],
      "role": "symbol",
      "title": "tabBarController(_:displayedViewControllersFor:proposedViewControllers:)",
      "type": "topic",
      "url": "/documentation/uikit/uitabbarcontrollerdelegate/tabbarcontroller(_:displayedviewcontrollersfor:proposedviewcontrollers:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:interactionControllerFor:)": {
      "abstract": [
        {
          "text": "Called to allow the delegate to return a ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerInteractiveTransitioning",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " delegate object for use during an animated tab bar transition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabBarController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITabBarController",
          "text": "UITabBarController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "interactionControllerFor"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIViewControllerAnimatedTransitioning",
          "text": "UIViewControllerAnimatedTransitioning"
        },
        {
          "kind": "text",
          "text": ") -> (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIViewControllerInteractiveTransitioning",
          "text": "UIViewControllerInteractiveTransitioning"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:interactionControllerFor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tabBarController:interactionControllerForAnimationController:"
        }
      ],
      "role": "symbol",
      "title": "tabBarController(_:interactionControllerFor:)",
      "type": "topic",
      "url": "/documentation/uikit/uitabbarcontrollerdelegate/tabbarcontroller(_:interactioncontrollerfor:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:shouldSelect:)": {
      "abstract": [
        {
          "text": "Asks the delegate whether the specified view controller should be made active.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabBarController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITabBarController",
          "text": "UITabBarController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shouldSelect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:shouldSelect:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tabBarController:shouldSelectViewController:"
        }
      ],
      "role": "symbol",
      "title": "tabBarController(_:shouldSelect:)",
      "type": "topic",
      "url": "/documentation/uikit/uitabbarcontrollerdelegate/tabbarcontroller(_:shouldselect:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:shouldSelectTab:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabBarController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITabBarController",
          "text": "UITabBarController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shouldSelectTab"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITab",
          "text": "UITab"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:shouldSelectTab:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tabBarController:shouldSelectTab:"
        }
      ],
      "role": "symbol",
      "title": "tabBarController(_:shouldSelectTab:)",
      "type": "topic",
      "url": "/documentation/uikit/uitabbarcontrollerdelegate/tabbarcontroller(_:shouldselecttab:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:tab:acceptItemsFrom:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabBarController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITabBarController",
          "text": "UITabBarController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "tab"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITab",
          "text": "UITab"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "acceptItemsFrom"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDropSession",
          "text": "UIDropSession"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:tab:acceptItemsFrom:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tabBarController:tab:acceptItemsFromDropSession:"
        }
      ],
      "role": "symbol",
      "title": "tabBarController(_:tab:acceptItemsFrom:)",
      "type": "topic",
      "url": "/documentation/uikit/uitabbarcontrollerdelegate/tabbarcontroller(_:tab:acceptitemsfrom:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:tab:operationForAcceptingItemsFrom:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabBarController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITabBarController",
          "text": "UITabBarController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "tab"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITab",
          "text": "UITab"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "operationForAcceptingItemsFrom"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDropSession",
          "text": "UIDropSession"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIDropOperation",
          "text": "UIDropOperation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:tab:operationForAcceptingItemsFrom:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tabBarController:tab:operationForAcceptingItemsFromDropSession:"
        }
      ],
      "role": "symbol",
      "title": "tabBarController(_:tab:operationForAcceptingItemsFrom:)",
      "type": "topic",
      "url": "/documentation/uikit/uitabbarcontrollerdelegate/tabbarcontroller(_:tab:operationforacceptingitemsfrom:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:visibilityDidChangeFor:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabBarController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITabBarController",
          "text": "UITabBarController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "visibilityDidChangeFor"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITab",
          "text": "UITab"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:visibilityDidChangeFor:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tabBarController:visibilityDidChangeForTabs:"
        }
      ],
      "role": "symbol",
      "title": "tabBarController(_:visibilityDidChangeFor:)",
      "type": "topic",
      "url": "/documentation/uikit/uitabbarcontrollerdelegate/tabbarcontroller(_:visibilitydidchangefor:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:willBeginCustomizing:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the tab bar customization sheet is about to be displayed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabBarController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITabBarController",
          "text": "UITabBarController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willBeginCustomizing"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:willBeginCustomizing:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tabBarController:willBeginCustomizingViewControllers:"
        }
      ],
      "role": "symbol",
      "title": "tabBarController(_:willBeginCustomizing:)",
      "type": "topic",
      "url": "/documentation/uikit/uitabbarcontrollerdelegate/tabbarcontroller(_:willbegincustomizing:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:willEndCustomizing:changed:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the tab bar customization sheet is about to be dismissed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabBarController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITabBarController",
          "text": "UITabBarController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willEndCustomizing"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "changed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:willEndCustomizing:changed:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tabBarController:willEndCustomizingViewControllers:changed:"
        }
      ],
      "role": "symbol",
      "title": "tabBarController(_:willEndCustomizing:changed:)",
      "type": "topic",
      "url": "/documentation/uikit/uitabbarcontrollerdelegate/tabbarcontroller(_:willendcustomizing:changed:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarControllerDidEndEditing(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabBarControllerDidEndEditing"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITabBarController",
          "text": "UITabBarController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarControllerDidEndEditing(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tabBarControllerDidEndEditing:"
        }
      ],
      "role": "symbol",
      "title": "tabBarControllerDidEndEditing(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uitabbarcontrollerdelegate/tabbarcontrollerdidendediting(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarControllerPreferredInterfaceOrientationForPresentation(_:)": {
      "abstract": [
        {
          "text": "Called to allow the delegate to provide the preferred orientation for presentation of the tab bar controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabBarControllerPreferredInterfaceOrientationForPresentation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITabBarController",
          "text": "UITabBarController"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIInterfaceOrientation",
          "text": "UIInterfaceOrientation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarControllerPreferredInterfaceOrientationForPresentation(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tabBarControllerPreferredInterfaceOrientationForPresentation:"
        }
      ],
      "role": "symbol",
      "title": "tabBarControllerPreferredInterfaceOrientationForPresentation(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uitabbarcontrollerdelegate/tabbarcontrollerpreferredinterfaceorientationforpresentation(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarControllerSupportedInterfaceOrientations(_:)": {
      "abstract": [
        {
          "text": "Called to allow the delegate to provide the complete set of supported interface orientations for the tab bar controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabBarControllerSupportedInterfaceOrientations"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITabBarController",
          "text": "UITabBarController"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIInterfaceOrientationMask",
          "text": "UIInterfaceOrientationMask"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarControllerSupportedInterfaceOrientations(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tabBarControllerSupportedInterfaceOrientations:"
        }
      ],
      "role": "symbol",
      "title": "tabBarControllerSupportedInterfaceOrientations(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uitabbarcontrollerdelegate/tabbarcontrollersupportedinterfaceorientations(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarControllerWillBeginEditing(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabBarControllerWillBeginEditing"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITabBarController",
          "text": "UITabBarController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarControllerWillBeginEditing(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tabBarControllerWillBeginEditing:"
        }
      ],
      "role": "symbol",
      "title": "tabBarControllerWillBeginEditing(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uitabbarcontrollerdelegate/tabbarcontrollerwillbeginediting(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewControllerAnimatedTransitioning": {
      "abstract": [
        {
          "text": "A set of methods for implementing the animations for a custom view controller transition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewControllerAnimatedTransitioning"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerAnimatedTransitioning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewControllerAnimatedTransitioning"
        }
      ],
      "role": "symbol",
      "title": "UIViewControllerAnimatedTransitioning",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontrolleranimatedtransitioning"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewControllerInteractiveTransitioning": {
      "abstract": [
        {
          "text": "A set of methods that enable an object (such as a navigation controller) to drive a view controller transition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewControllerInteractiveTransitioning"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerInteractiveTransitioning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewControllerInteractiveTransitioning"
        }
      ],
      "role": "symbol",
      "title": "UIViewControllerInteractiveTransitioning",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontrollerinteractivetransitioning"
    },
    "doc://com.apple.uikit/documentation/UIKit/elevating-your-ipad-app-with-a-tab-bar-and-sidebar": {
      "abstract": [
        {
          "text": "Provide a compact, ergonomic tab bar for quick access to key parts of your app, and a sidebar for in-depth navigation.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/elevating-your-ipad-app-with-a-tab-bar-and-sidebar",
      "kind": "article",
      "role": "article",
      "title": "Elevating your iPad app with a tab bar and sidebar",
      "type": "topic",
      "url": "/documentation/uikit/elevating-your-ipad-app-with-a-tab-bar-and-sidebar"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "https://developer.apple.com/library/archive/featuredarticles/ViewControllerPGforiPhoneOS/index.html#//apple_ref/doc/uid/TP40007457": {
      "identifier": "https://developer.apple.com/library/archive/featuredarticles/ViewControllerPGforiPhoneOS/index.html#//apple_ref/doc/uid/TP40007457",
      "title": "View Controller Programming Guide for iOS",
      "titleInlineContent": [
        {
          "text": "View Controller Programming Guide for iOS",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/featuredarticles/ViewControllerPGforiPhoneOS/index.html#//apple_ref/doc/uid/TP40007457"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Customizing-the-tab-bar-behavior",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITabBarController/delegate"
      ],
      "title": "Customizing the tab bar behavior"
    }
  ],
  "topicSections": [
    {
      "anchor": "Managing-tab-bar-selections",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:shouldSelect:)",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:didSelect:)"
      ],
      "title": "Managing tab bar selections"
    },
    {
      "anchor": "Managing-tab-bar-customizations",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:willBeginCustomizing:)",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:willEndCustomizing:changed:)",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:didEndCustomizing:changed:)"
      ],
      "title": "Managing tab bar customizations"
    },
    {
      "anchor": "Overriding-view-rotation-settings",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarControllerSupportedInterfaceOrientations(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarControllerPreferredInterfaceOrientationForPresentation(_:)"
      ],
      "title": "Overriding view rotation settings"
    },
    {
      "anchor": "Supporting-custom-tab-bar-transition-animations",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:animationControllerForTransitionFrom:to:)",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:interactionControllerFor:)"
      ],
      "title": "Supporting custom tab bar transition animations"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:didSelectTab:previousTab:)",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:displayOrderDidChangeFor:)",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:displayedViewControllersFor:proposedViewControllers:)",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:shouldSelectTab:)",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:tab:acceptItemsFrom:)",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:tab:operationForAcceptingItemsFrom:)",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:visibilityDidChangeFor:)",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarControllerDidEndEditing(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarControllerWillBeginEditing(_:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UITabBarControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Managing-tab-bar-selections",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:shouldSelect:)",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:didSelect:)"
              ],
              "title": "Managing tab bar selections"
            },
            {
              "anchor": "Managing-tab-bar-customizations",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:willBeginCustomizing:)",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:willEndCustomizing:changed:)",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:didEndCustomizing:changed:)"
              ],
              "title": "Managing tab bar customizations"
            },
            {
              "anchor": "Overriding-view-rotation-settings",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarControllerSupportedInterfaceOrientations(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarControllerPreferredInterfaceOrientationForPresentation(_:)"
              ],
              "title": "Overriding view rotation settings"
            },
            {
              "anchor": "Supporting-custom-tab-bar-transition-animations",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:animationControllerForTransitionFrom:to:)",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:interactionControllerFor:)"
              ],
              "title": "Supporting custom tab bar transition animations"
            },
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:didSelectTab:previousTab:)",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:displayOrderDidChangeFor:)",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:displayedViewControllersFor:proposedViewControllers:)",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:shouldSelectTab:)",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:tab:acceptItemsFrom:)",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:tab:operationForAcceptingItemsFrom:)",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarController(_:visibilityDidChangeFor:)",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarControllerDidEndEditing(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UITabBarControllerDelegate/tabBarControllerWillBeginEditing(_:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Customizing-the-tab-bar-behavior",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITabBarController/delegate"
              ],
              "title": "Customizing the tab bar behavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UITabBarControllerDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarControllerDelegate~1tabBarController(_:willEndCustomizing:changed:)/title",
          "value": "tabBarController:willEndCustomizingViewControllers:changed:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarControllerDelegate~1tabBarController(_:willEndCustomizing:changed:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tabBarController:willEndCustomizingViewControllers:changed:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarControllerDelegate~1tabBarControllerDidEndEditing(_:)/title",
          "value": "tabBarControllerDidEndEditing:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarControllerDelegate~1tabBarControllerDidEndEditing(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tabBarControllerDidEndEditing:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarControllerDelegate~1tabBarController(_:visibilityDidChangeFor:)/title",
          "value": "tabBarController:visibilityDidChangeForTabs:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarControllerDelegate~1tabBarController(_:visibilityDidChangeFor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tabBarController:visibilityDidChangeForTabs:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarControllerDelegate~1tabBarController(_:shouldSelectTab:)/title",
          "value": "tabBarController:shouldSelectTab:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarControllerDelegate~1tabBarController(_:shouldSelectTab:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tabBarController:shouldSelectTab:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarControllerDelegate~1tabBarController(_:displayOrderDidChangeFor:)/title",
          "value": "tabBarController:displayOrderDidChangeForGroup:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarControllerDelegate~1tabBarController(_:displayOrderDidChangeFor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tabBarController:displayOrderDidChangeForGroup:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarControllerDelegate~1tabBarControllerSupportedInterfaceOrientations(_:)/title",
          "value": "tabBarControllerSupportedInterfaceOrientations:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarControllerDelegate~1tabBarControllerSupportedInterfaceOrientations(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tabBarControllerSupportedInterfaceOrientations:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarControllerDelegate~1tabBarController(_:didSelect:)/title",
          "value": "tabBarController:didSelectViewController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarControllerDelegate~1tabBarController(_:didSelect:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tabBarController:didSelectViewController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarControllerDelegate/title",
          "value": "UITabBarControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarControllerDelegate~1tabBarController(_:didSelectTab:previousTab:)/title",
          "value": "tabBarController:didSelectTab:previousTab:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarControllerDelegate~1tabBarController(_:didSelectTab:previousTab:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tabBarController:didSelectTab:previousTab:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarControllerDelegate~1tabBarController(_:tab:operationForAcceptingItemsFrom:)/title",
          "value": "tabBarController:tab:operationForAcceptingItemsFromDropSession:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarControllerDelegate~1tabBarController(_:tab:operationForAcceptingItemsFrom:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tabBarController:tab:operationForAcceptingItemsFromDropSession:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController/title",
          "value": "UITabBarController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITabBarController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerAnimatedTransitioning/title",
          "value": "UIViewControllerAnimatedTransitioning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerAnimatedTransitioning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerAnimatedTransitioning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerAnimatedTransitioning/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerAnimatedTransitioning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarControllerDelegate~1tabBarControllerWillBeginEditing(_:)/title",
          "value": "tabBarControllerWillBeginEditing:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarControllerDelegate~1tabBarControllerWillBeginEditing(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tabBarControllerWillBeginEditing:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarControllerDelegate~1tabBarController(_:shouldSelect:)/title",
          "value": "tabBarController:shouldSelectViewController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarControllerDelegate~1tabBarController(_:shouldSelect:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tabBarController:shouldSelectViewController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarControllerDelegate~1tabBarControllerPreferredInterfaceOrientationForPresentation(_:)/title",
          "value": "tabBarControllerPreferredInterfaceOrientationForPresentation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarControllerDelegate~1tabBarControllerPreferredInterfaceOrientationForPresentation(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tabBarControllerPreferredInterfaceOrientationForPresentation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarControllerDelegate~1tabBarController(_:didEndCustomizing:changed:)/title",
          "value": "tabBarController:didEndCustomizingViewControllers:changed:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarControllerDelegate~1tabBarController(_:didEndCustomizing:changed:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tabBarController:didEndCustomizingViewControllers:changed:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarControllerDelegate~1tabBarController(_:interactionControllerFor:)/title",
          "value": "tabBarController:interactionControllerForAnimationController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarControllerDelegate~1tabBarController(_:interactionControllerFor:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tabBarController:interactionControllerForAnimationController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarControllerDelegate~1tabBarController(_:animationControllerForTransitionFrom:to:)/title",
          "value": "tabBarController:animationControllerForTransitionFromViewController:toViewController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarControllerDelegate~1tabBarController(_:animationControllerForTransitionFrom:to:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tabBarController:animationControllerForTransitionFromViewController:toViewController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerInteractiveTransitioning/title",
          "value": "UIViewControllerInteractiveTransitioning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerInteractiveTransitioning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerInteractiveTransitioning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerInteractiveTransitioning/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerInteractiveTransitioning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarControllerDelegate~1tabBarController(_:tab:acceptItemsFrom:)/title",
          "value": "tabBarController:tab:acceptItemsFromDropSession:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarControllerDelegate~1tabBarController(_:tab:acceptItemsFrom:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tabBarController:tab:acceptItemsFromDropSession:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarControllerDelegate~1tabBarController(_:willBeginCustomizing:)/title",
          "value": "tabBarController:willBeginCustomizingViewControllers:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarControllerDelegate~1tabBarController(_:willBeginCustomizing:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tabBarController:willBeginCustomizingViewControllers:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarControllerDelegate~1tabBarController(_:displayedViewControllersFor:proposedViewControllers:)/title",
          "value": "tabBarController:displayedViewControllersForTab:proposedViewControllers:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITabBarControllerDelegate~1tabBarController(_:displayedViewControllersFor:proposedViewControllers:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tabBarController:displayedViewControllersForTab:proposedViewControllers:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitabbarcontrollerdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uitabbarcontrollerdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
