{
  "abstract": [
    {
      "text": "The interface for initiating drags from a table view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITableViewDragDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UITableViewDragDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UITableViewDragDelegate"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UITableViewDragDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "UITableViewDragDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UITableViewDragDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.uikit/documentation/UIKit/supporting-drag-and-drop-in-table-views"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Implement this protocol in the object that you use to initiate drags from your table view. The only required method of this protocol is the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewDragDelegate/tableView(_:itemsForBeginning:at:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method, but you can implement other methods as needed to customize the drag behavior of your table view.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Assign your custom delegate object to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableView/dragDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of your table view.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableView/dragDelegate": {
      "abstract": [
        {
          "text": "The delegate object that manages the dragging of items from the table view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dragDelegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITableViewDragDelegate",
          "text": "UITableViewDragDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableView/dragDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dragDelegate"
        }
      ],
      "role": "symbol",
      "title": "dragDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uitableview/dragdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewDragDelegate": {
      "abstract": [
        {
          "text": "The interface for initiating drags from a table view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITableViewDragDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewDragDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableViewDragDelegate"
        }
      ],
      "role": "symbol",
      "title": "UITableViewDragDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewdragdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewDragDelegate/tableView(_:dragPreviewParametersForRowAt:)": {
      "abstract": [
        {
          "text": "Returns custom information about how to display the row at the specified location during the drag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tableView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITableView",
          "text": "UITableView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dragPreviewParametersForRowAt"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation9IndexPathV",
          "text": "IndexPath"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDragPreviewParameters",
          "text": "UIDragPreviewParameters"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewDragDelegate/tableView(_:dragPreviewParametersForRowAt:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tableView:dragPreviewParametersForRowAtIndexPath:"
        }
      ],
      "role": "symbol",
      "title": "tableView(_:dragPreviewParametersForRowAt:)",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewdragdelegate/tableview(_:dragpreviewparametersforrowat:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewDragDelegate/tableView(_:dragSessionAllowsMoveOperation:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether your app supports a move operation for the dragged content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tableView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITableView",
          "text": "UITableView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dragSessionAllowsMoveOperation"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDragSession",
          "text": "UIDragSession"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewDragDelegate/tableView(_:dragSessionAllowsMoveOperation:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tableView:dragSessionAllowsMoveOperation:"
        }
      ],
      "role": "symbol",
      "title": "tableView(_:dragSessionAllowsMoveOperation:)",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewdragdelegate/tableview(_:dragsessionallowsmoveoperation:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewDragDelegate/tableView(_:dragSessionDidEnd:)": {
      "abstract": [
        {
          "text": "Signals the end of a drag operation involving content from the specified table view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tableView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITableView",
          "text": "UITableView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dragSessionDidEnd"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDragSession",
          "text": "UIDragSession"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewDragDelegate/tableView(_:dragSessionDidEnd:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tableView:dragSessionDidEnd:"
        }
      ],
      "role": "symbol",
      "title": "tableView(_:dragSessionDidEnd:)",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewdragdelegate/tableview(_:dragsessiondidend:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewDragDelegate/tableView(_:dragSessionIsRestrictedToDraggingApplication:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether the dragged content must be dropped in the same app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tableView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITableView",
          "text": "UITableView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dragSessionIsRestrictedToDraggingApplication"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDragSession",
          "text": "UIDragSession"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewDragDelegate/tableView(_:dragSessionIsRestrictedToDraggingApplication:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tableView:dragSessionIsRestrictedToDraggingApplication:"
        }
      ],
      "role": "symbol",
      "title": "tableView(_:dragSessionIsRestrictedToDraggingApplication:)",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewdragdelegate/tableview(_:dragsessionisrestrictedtodraggingapplication:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewDragDelegate/tableView(_:dragSessionWillBegin:)": {
      "abstract": [
        {
          "text": "Signals the start of a drag operation involving content from the specified table view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tableView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITableView",
          "text": "UITableView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dragSessionWillBegin"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDragSession",
          "text": "UIDragSession"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewDragDelegate/tableView(_:dragSessionWillBegin:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tableView:dragSessionWillBegin:"
        }
      ],
      "role": "symbol",
      "title": "tableView(_:dragSessionWillBegin:)",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewdragdelegate/tableview(_:dragsessionwillbegin:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewDragDelegate/tableView(_:itemsForAddingTo:at:point:)": {
      "abstract": [
        {
          "text": "Adds the specified items to an existing drag session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tableView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITableView",
          "text": "UITableView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "itemsForAddingTo"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDragSession",
          "text": "UIDragSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation9IndexPathV",
          "text": "IndexPath"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "point"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDragItem",
          "text": "UIDragItem"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewDragDelegate/tableView(_:itemsForAddingTo:at:point:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tableView:itemsForAddingToDragSession:atIndexPath:point:"
        }
      ],
      "role": "symbol",
      "title": "tableView(_:itemsForAddingTo:at:point:)",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewdragdelegate/tableview(_:itemsforaddingto:at:point:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewDragDelegate/tableView(_:itemsForBeginning:at:)": {
      "abstract": [
        {
          "text": "Provides the initial set of items (if any) to drag.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tableView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITableView",
          "text": "UITableView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "itemsForBeginning"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDragSession",
          "text": "UIDragSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "at"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation9IndexPathV",
          "text": "IndexPath"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDragItem",
          "text": "UIDragItem"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewDragDelegate/tableView(_:itemsForBeginning:at:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "tableView:itemsForBeginningDragSession:atIndexPath:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "tableView(_:itemsForBeginning:at:)",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewdragdelegate/tableview(_:itemsforbeginning:at:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewDropCoordinator": {
      "abstract": [
        {
          "text": "An interface for coordinating your custom drop-related actions with the table view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITableViewDropCoordinator"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewDropCoordinator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableViewDropCoordinator"
        }
      ],
      "role": "symbol",
      "title": "UITableViewDropCoordinator",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewdropcoordinator"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewDropDelegate": {
      "abstract": [
        {
          "text": "The interface for handling drops in a table view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITableViewDropDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewDropDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableViewDropDelegate"
        }
      ],
      "role": "symbol",
      "title": "UITableViewDropDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewdropdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewDropItem": {
      "abstract": [
        {
          "text": "The data associated with an item being dropped into the table view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITableViewDropItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewDropItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableViewDropItem"
        }
      ],
      "role": "symbol",
      "title": "UITableViewDropItem",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewdropitem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewDropProposal": {
      "abstract": [
        {
          "text": "Your proposed solution for handling a drop in a table view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITableViewDropProposal"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewDropProposal",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableViewDropProposal"
        }
      ],
      "role": "symbol",
      "title": "UITableViewDropProposal",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewdropproposal"
    },
    "doc://com.apple.uikit/documentation/UIKit/adopting-drag-and-drop-in-a-table-view": {
      "abstract": [
        {
          "text": "Demonstrates how to enable and implement drag and drop for a table view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/adopting-drag-and-drop-in-a-table-view",
      "kind": "article",
      "role": "sampleCode",
      "title": "Adopting drag and drop in a table view",
      "type": "topic",
      "url": "/documentation/uikit/adopting-drag-and-drop-in-a-table-view"
    },
    "doc://com.apple.uikit/documentation/UIKit/supporting-drag-and-drop-in-table-views": {
      "abstract": [
        {
          "text": "Initiate drags and handle drops from a table view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/supporting-drag-and-drop-in-table-views",
      "kind": "article",
      "role": "article",
      "title": "Supporting drag and drop in table views",
      "type": "topic",
      "url": "/documentation/uikit/supporting-drag-and-drop-in-table-views"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Drag-and-drop",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/supporting-drag-and-drop-in-table-views",
        "doc://com.apple.uikit/documentation/UIKit/adopting-drag-and-drop-in-a-table-view",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewDropDelegate",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewDropCoordinator",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewDropItem",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewDropProposal"
      ],
      "title": "Drag and drop"
    }
  ],
  "topicSections": [
    {
      "anchor": "Providing-the-items-to-drag",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITableViewDragDelegate/tableView(_:itemsForBeginning:at:)",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewDragDelegate/tableView(_:itemsForAddingTo:at:point:)"
      ],
      "title": "Providing the items to drag"
    },
    {
      "anchor": "Tracking-the-drag-session",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITableViewDragDelegate/tableView(_:dragSessionWillBegin:)",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewDragDelegate/tableView(_:dragSessionDidEnd:)",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewDragDelegate/tableView(_:dragSessionIsRestrictedToDraggingApplication:)",
        "doc://com.apple.uikit/documentation/UIKit/UITableViewDragDelegate/tableView(_:dragSessionAllowsMoveOperation:)"
      ],
      "title": "Tracking the drag session"
    },
    {
      "anchor": "Providing-a-custom-preview",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITableViewDragDelegate/tableView(_:dragPreviewParametersForRowAt:)"
      ],
      "title": "Providing a custom preview"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UITableViewDragDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewDragDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewDragDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Providing-the-items-to-drag",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITableViewDragDelegate/tableView(_:itemsForBeginning:at:)",
                "doc://com.apple.uikit/documentation/UIKit/UITableViewDragDelegate/tableView(_:itemsForAddingTo:at:point:)"
              ],
              "title": "Providing the items to drag"
            },
            {
              "anchor": "Tracking-the-drag-session",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITableViewDragDelegate/tableView(_:dragSessionWillBegin:)",
                "doc://com.apple.uikit/documentation/UIKit/UITableViewDragDelegate/tableView(_:dragSessionDidEnd:)",
                "doc://com.apple.uikit/documentation/UIKit/UITableViewDragDelegate/tableView(_:dragSessionIsRestrictedToDraggingApplication:)",
                "doc://com.apple.uikit/documentation/UIKit/UITableViewDragDelegate/tableView(_:dragSessionAllowsMoveOperation:)"
              ],
              "title": "Tracking the drag session"
            },
            {
              "anchor": "Providing-a-custom-preview",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITableViewDragDelegate/tableView(_:dragPreviewParametersForRowAt:)"
              ],
              "title": "Providing a custom preview"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Drag-and-drop",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/supporting-drag-and-drop-in-table-views",
                "doc://com.apple.uikit/documentation/UIKit/adopting-drag-and-drop-in-a-table-view",
                "doc://com.apple.uikit/documentation/UIKit/UITableViewDropDelegate",
                "doc://com.apple.uikit/documentation/UIKit/UITableViewDropCoordinator",
                "doc://com.apple.uikit/documentation/UIKit/UITableViewDropItem",
                "doc://com.apple.uikit/documentation/UIKit/UITableViewDropProposal"
              ],
              "title": "Drag and drop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UITableViewDragDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDragDelegate~1tableView(_:dragSessionIsRestrictedToDraggingApplication:)/title",
          "value": "tableView:dragSessionIsRestrictedToDraggingApplication:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDragDelegate~1tableView(_:dragSessionIsRestrictedToDraggingApplication:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tableView:dragSessionIsRestrictedToDraggingApplication:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDropProposal/title",
          "value": "UITableViewDropProposal"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDropProposal/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewDropProposal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDropProposal/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewDropProposal"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDragDelegate~1tableView(_:dragPreviewParametersForRowAt:)/title",
          "value": "tableView:dragPreviewParametersForRowAtIndexPath:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDragDelegate~1tableView(_:dragPreviewParametersForRowAt:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tableView:dragPreviewParametersForRowAtIndexPath:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDropCoordinator/title",
          "value": "UITableViewDropCoordinator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDropCoordinator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewDropCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDropCoordinator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewDropCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDragDelegate~1tableView(_:dragSessionAllowsMoveOperation:)/title",
          "value": "tableView:dragSessionAllowsMoveOperation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDragDelegate~1tableView(_:dragSessionAllowsMoveOperation:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tableView:dragSessionAllowsMoveOperation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDragDelegate~1tableView(_:dragSessionWillBegin:)/title",
          "value": "tableView:dragSessionWillBegin:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDragDelegate~1tableView(_:dragSessionWillBegin:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tableView:dragSessionWillBegin:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDragDelegate~1tableView(_:itemsForAddingTo:at:point:)/title",
          "value": "tableView:itemsForAddingToDragSession:atIndexPath:point:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDragDelegate~1tableView(_:itemsForAddingTo:at:point:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tableView:itemsForAddingToDragSession:atIndexPath:point:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDragDelegate/title",
          "value": "UITableViewDragDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDragDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewDragDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDragDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewDragDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDragDelegate~1tableView(_:itemsForBeginning:at:)/title",
          "value": "tableView:itemsForBeginningDragSession:atIndexPath:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDragDelegate~1tableView(_:itemsForBeginning:at:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tableView:itemsForBeginningDragSession:atIndexPath:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDropDelegate/title",
          "value": "UITableViewDropDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDropDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewDropDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDropDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewDropDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView~1dragDelegate/title",
          "value": "dragDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableView~1dragDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dragDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDragDelegate~1tableView(_:dragSessionDidEnd:)/title",
          "value": "tableView:dragSessionDidEnd:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDragDelegate~1tableView(_:dragSessionDidEnd:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "tableView:dragSessionDidEnd:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDropItem/title",
          "value": "UITableViewDropItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDropItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewDropItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewDropItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewDropItem"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitableviewdragdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uitableviewdragdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
