{
  "abstract": [
    {
      "text": "A discrete gesture recognizer that interprets single or multiple taps.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UITapGestureRecognizer",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UITapGestureRecognizer"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UITapGestureRecognizer"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "UITapGestureRecognizer"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UITapGestureRecognizer"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.uikit/documentation/UIKit/preferring-one-gesture-over-another",
        "doc://com.apple.uikit/documentation/UIKit/handling-tap-gestures"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " is a concrete subclass of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For gesture recognition, the specified number of fingers must tap the view a specified number of times. Although taps are discrete gestures, they’re discrete for each state of the gesture recognizer. The system sends the associated action message when the gesture begins and then again for each intermediate state until (and including) the ending state of the gesture. Code that handles tap gestures should test for the state of the gesture, for example:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "tabs": [
            {
              "content": [
                {
                  "code": [
                    "func handleTap(sender: UITapGestureRecognizer) {",
                    "    if sender.state == .ended {",
                    "        // handling code",
                    "    }",
                    "}"
                  ],
                  "syntax": "swift",
                  "type": "codeListing"
                }
              ],
              "title": "Swift"
            },
            {
              "content": [
                {
                  "code": [
                    "- (void)handleTap:(UITapGestureRecognizer *)sender",
                    "{",
                    "    if (sender.state == UIGestureRecognizerStateEnded)",
                    "    {",
                    "        // handling code",
                    "    }",
                    "}"
                  ],
                  "syntax": "objc",
                  "type": "codeListing"
                }
              ],
              "title": "Objective-C"
            }
          ],
          "type": "tabNavigator"
        },
        {
          "inlineContent": [
            {
              "text": "Action methods handling this gesture can get the location of the gesture as a whole by calling the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/location(in:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". If there are multiple taps, this location is the first tap. If there are multiple touches, this location is the centroid of all fingers tapping the view. Clients can get the location of particular touches in the tap by calling ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/location(ofTouch:in:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". If multiple taps are allowed, this location is the first tap.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer": {
      "abstract": [
        {
          "text": "The base class for concrete gesture recognizers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIGestureRecognizer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIGestureRecognizer"
        }
      ],
      "role": "symbol",
      "title": "UIGestureRecognizer",
      "type": "topic",
      "url": "/documentation/uikit/uigesturerecognizer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/location(in:)": {
      "abstract": [
        {
          "text": "Returns the point computed as the location in a given view of the gesture represented by the gesture recognizer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "location"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/location(in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "locationInView:"
        }
      ],
      "role": "symbol",
      "title": "location(in:)",
      "type": "topic",
      "url": "/documentation/uikit/uigesturerecognizer/location(in:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/location(ofTouch:in:)": {
      "abstract": [
        {
          "text": "Returns the location of one of the gesture’s touches in the local coordinate system of a given view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "location"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "ofTouch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer/location(ofTouch:in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "locationOfTouch:inView:"
        }
      ],
      "role": "symbol",
      "title": "location(ofTouch:in:)",
      "type": "topic",
      "url": "/documentation/uikit/uigesturerecognizer/location(oftouch:in:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIHoverGestureRecognizer": {
      "abstract": [
        {
          "text": "A continuous gesture recognizer that interprets pointer movement over a view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIHoverGestureRecognizer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIHoverGestureRecognizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIHoverGestureRecognizer"
        }
      ],
      "role": "symbol",
      "title": "UIHoverGestureRecognizer",
      "type": "topic",
      "url": "/documentation/uikit/uihovergesturerecognizer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UILongPressGestureRecognizer": {
      "abstract": [
        {
          "text": "A continuous gesture recognizer that interprets long-press gestures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UILongPressGestureRecognizer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UILongPressGestureRecognizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILongPressGestureRecognizer"
        }
      ],
      "role": "symbol",
      "title": "UILongPressGestureRecognizer",
      "type": "topic",
      "url": "/documentation/uikit/uilongpressgesturerecognizer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPanGestureRecognizer": {
      "abstract": [
        {
          "text": "A continuous gesture recognizer that interprets panning gestures.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPanGestureRecognizer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPanGestureRecognizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPanGestureRecognizer"
        }
      ],
      "role": "symbol",
      "title": "UIPanGestureRecognizer",
      "type": "topic",
      "url": "/documentation/uikit/uipangesturerecognizer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPinchGestureRecognizer": {
      "abstract": [
        {
          "text": "A continuous gesture recognizer that interprets pinching gestures involving two touches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPinchGestureRecognizer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPinchGestureRecognizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPinchGestureRecognizer"
        }
      ],
      "role": "symbol",
      "title": "UIPinchGestureRecognizer",
      "type": "topic",
      "url": "/documentation/uikit/uipinchgesturerecognizer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIRotationGestureRecognizer": {
      "abstract": [
        {
          "text": "A continuous gesture recognizer that interprets rotation gestures involving two touches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIRotationGestureRecognizer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIRotationGestureRecognizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIRotationGestureRecognizer"
        }
      ],
      "role": "symbol",
      "title": "UIRotationGestureRecognizer",
      "type": "topic",
      "url": "/documentation/uikit/uirotationgesturerecognizer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScreenEdgePanGestureRecognizer": {
      "abstract": [
        {
          "text": "A continuous gesture recognizer that interprets panning gestures that start near an edge of the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIScreenEdgePanGestureRecognizer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScreenEdgePanGestureRecognizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIScreenEdgePanGestureRecognizer"
        }
      ],
      "role": "symbol",
      "title": "UIScreenEdgePanGestureRecognizer",
      "type": "topic",
      "url": "/documentation/uikit/uiscreenedgepangesturerecognizer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISwipeGestureRecognizer": {
      "abstract": [
        {
          "text": "A discrete gesture recognizer that interprets swiping gestures in one or more directions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISwipeGestureRecognizer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISwipeGestureRecognizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISwipeGestureRecognizer"
        }
      ],
      "role": "symbol",
      "title": "UISwipeGestureRecognizer",
      "type": "topic",
      "url": "/documentation/uikit/uiswipegesturerecognizer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer": {
      "abstract": [
        {
          "text": "A discrete gesture recognizer that interprets single or multiple taps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITapGestureRecognizer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITapGestureRecognizer"
        }
      ],
      "role": "symbol",
      "title": "UITapGestureRecognizer",
      "type": "topic",
      "url": "/documentation/uikit/uitapgesturerecognizer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer/buttonMaskRequired": {
      "abstract": [
        {
          "text": "The bit mask of the buttons the user must press for gesture recognition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "buttonMaskRequired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIEvent",
          "text": "UIEvent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIEventButtonMask",
          "text": "ButtonMask"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer/buttonMaskRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "buttonMaskRequired"
        }
      ],
      "role": "symbol",
      "title": "buttonMaskRequired",
      "type": "topic",
      "url": "/documentation/uikit/uitapgesturerecognizer/buttonmaskrequired"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer/numberOfTapsRequired": {
      "abstract": [
        {
          "text": "The number of taps necessary for gesture recognition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfTapsRequired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer/numberOfTapsRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberOfTapsRequired"
        }
      ],
      "role": "symbol",
      "title": "numberOfTapsRequired",
      "type": "topic",
      "url": "/documentation/uikit/uitapgesturerecognizer/numberoftapsrequired"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer/numberOfTouchesRequired": {
      "abstract": [
        {
          "text": "The number of fingers that the user must tap for gesture recognition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "numberOfTouchesRequired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer/numberOfTouchesRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "numberOfTouchesRequired"
        }
      ],
      "role": "symbol",
      "title": "numberOfTouchesRequired",
      "type": "topic",
      "url": "/documentation/uikit/uitapgesturerecognizer/numberoftouchesrequired"
    },
    "doc://com.apple.uikit/documentation/UIKit/adopting-hover-support-for-apple-pencil": {
      "abstract": [
        {
          "text": "Enhance user feedback for your iPadOS app with a hover preview for",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "Apple Pencil input.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/adopting-hover-support-for-apple-pencil",
      "kind": "article",
      "role": "sampleCode",
      "title": "Adopting hover support for Apple Pencil",
      "type": "topic",
      "url": "/documentation/uikit/adopting-hover-support-for-apple-pencil"
    },
    "doc://com.apple.uikit/documentation/UIKit/coordinating-multiple-gesture-recognizers": {
      "abstract": [
        {
          "text": "Discover how to use multiple gesture recognizers on the same view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/coordinating-multiple-gesture-recognizers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Coordinating multiple gesture recognizers",
      "type": "topic",
      "url": "/documentation/uikit/coordinating-multiple-gesture-recognizers"
    },
    "doc://com.apple.uikit/documentation/UIKit/handling-tap-gestures": {
      "abstract": [
        {
          "text": "Use brief taps on the screen to implement button-like interactions with your content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/handling-tap-gestures",
      "kind": "article",
      "role": "article",
      "title": "Handling tap gestures",
      "type": "topic",
      "url": "/documentation/uikit/handling-tap-gestures"
    },
    "doc://com.apple.uikit/documentation/UIKit/handling-uikit-gestures": {
      "abstract": [
        {
          "text": "Use gesture recognizers to simplify touch handling and create a consistent user experience.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/handling-uikit-gestures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Handling UIKit gestures",
      "type": "topic",
      "url": "/documentation/uikit/handling-uikit-gestures"
    },
    "doc://com.apple.uikit/documentation/UIKit/preferring-one-gesture-over-another": {
      "abstract": [
        {
          "text": "Use a gesture recognizer delegate object to determine the order in which gestures are recognized in your views.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/preferring-one-gesture-over-another",
      "kind": "article",
      "role": "article",
      "title": "Preferring one gesture over another",
      "type": "topic",
      "url": "/documentation/uikit/preferring-one-gesture-over-another"
    },
    "doc://com.apple.uikit/documentation/UIKit/supporting-gesture-interaction-in-your-apps": {
      "abstract": [
        {
          "text": "Enrich your app’s user experience by supporting standard and custom gesture interaction.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/supporting-gesture-interaction-in-your-apps",
      "kind": "article",
      "role": "sampleCode",
      "title": "Supporting gesture interaction in your apps",
      "type": "topic",
      "url": "/documentation/uikit/supporting-gesture-interaction-in-your-apps"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Standard-gestures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/handling-uikit-gestures",
        "doc://com.apple.uikit/documentation/UIKit/coordinating-multiple-gesture-recognizers",
        "doc://com.apple.uikit/documentation/UIKit/adopting-hover-support-for-apple-pencil",
        "doc://com.apple.uikit/documentation/UIKit/supporting-gesture-interaction-in-your-apps",
        "doc://com.apple.uikit/documentation/UIKit/UIHoverGestureRecognizer",
        "doc://com.apple.uikit/documentation/UIKit/UILongPressGestureRecognizer",
        "doc://com.apple.uikit/documentation/UIKit/UIPanGestureRecognizer",
        "doc://com.apple.uikit/documentation/UIKit/UIPinchGestureRecognizer",
        "doc://com.apple.uikit/documentation/UIKit/UIRotationGestureRecognizer",
        "doc://com.apple.uikit/documentation/UIKit/UIScreenEdgePanGestureRecognizer",
        "doc://com.apple.uikit/documentation/UIKit/UISwipeGestureRecognizer"
      ],
      "title": "Standard gestures"
    }
  ],
  "topicSections": [
    {
      "anchor": "Configuring-the-gesture",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer/buttonMaskRequired",
        "doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer/numberOfTapsRequired",
        "doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer/numberOfTouchesRequired"
      ],
      "title": "Configuring the gesture"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UITapGestureRecognizer"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITapGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITapGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Configuring-the-gesture",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer/buttonMaskRequired",
                "doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer/numberOfTapsRequired",
                "doc://com.apple.uikit/documentation/UIKit/UITapGestureRecognizer/numberOfTouchesRequired"
              ],
              "title": "Configuring the gesture"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Standard-gestures",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/handling-uikit-gestures",
                "doc://com.apple.uikit/documentation/UIKit/coordinating-multiple-gesture-recognizers",
                "doc://com.apple.uikit/documentation/UIKit/adopting-hover-support-for-apple-pencil",
                "doc://com.apple.uikit/documentation/UIKit/supporting-gesture-interaction-in-your-apps",
                "doc://com.apple.uikit/documentation/UIKit/UIHoverGestureRecognizer",
                "doc://com.apple.uikit/documentation/UIKit/UILongPressGestureRecognizer",
                "doc://com.apple.uikit/documentation/UIKit/UIPanGestureRecognizer",
                "doc://com.apple.uikit/documentation/UIKit/UIPinchGestureRecognizer",
                "doc://com.apple.uikit/documentation/UIKit/UIRotationGestureRecognizer",
                "doc://com.apple.uikit/documentation/UIKit/UIScreenEdgePanGestureRecognizer",
                "doc://com.apple.uikit/documentation/UIKit/UISwipeGestureRecognizer"
              ],
              "title": "Standard gestures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UITapGestureRecognizer"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIGestureRecognizer",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UIGestureRecognizer",
                    "text": "UIGestureRecognizer"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILongPressGestureRecognizer/title",
          "value": "UILongPressGestureRecognizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILongPressGestureRecognizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UILongPressGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILongPressGestureRecognizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILongPressGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRotationGestureRecognizer/title",
          "value": "UIRotationGestureRecognizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRotationGestureRecognizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIRotationGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIRotationGestureRecognizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIRotationGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizer~1location(ofTouch:in:)/title",
          "value": "locationOfTouch:inView:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizer~1location(ofTouch:in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "locationOfTouch:inView:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPinchGestureRecognizer/title",
          "value": "UIPinchGestureRecognizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPinchGestureRecognizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPinchGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPinchGestureRecognizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPinchGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITapGestureRecognizer~1buttonMaskRequired/title",
          "value": "buttonMaskRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITapGestureRecognizer~1buttonMaskRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "buttonMaskRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITapGestureRecognizer~1numberOfTapsRequired/title",
          "value": "numberOfTapsRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITapGestureRecognizer~1numberOfTapsRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfTapsRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizer/title",
          "value": "UIGestureRecognizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreenEdgePanGestureRecognizer/title",
          "value": "UIScreenEdgePanGestureRecognizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreenEdgePanGestureRecognizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreenEdgePanGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScreenEdgePanGestureRecognizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScreenEdgePanGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPanGestureRecognizer/title",
          "value": "UIPanGestureRecognizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPanGestureRecognizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPanGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPanGestureRecognizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPanGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITapGestureRecognizer/title",
          "value": "UITapGestureRecognizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITapGestureRecognizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITapGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITapGestureRecognizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITapGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIHoverGestureRecognizer/title",
          "value": "UIHoverGestureRecognizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIHoverGestureRecognizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIHoverGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIHoverGestureRecognizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIHoverGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISwipeGestureRecognizer/title",
          "value": "UISwipeGestureRecognizer"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISwipeGestureRecognizer/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISwipeGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISwipeGestureRecognizer/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISwipeGestureRecognizer"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITapGestureRecognizer~1numberOfTouchesRequired/title",
          "value": "numberOfTouchesRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITapGestureRecognizer~1numberOfTouchesRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "numberOfTouchesRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizer~1location(in:)/title",
          "value": "locationInView:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIGestureRecognizer~1location(in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "locationInView:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitapgesturerecognizer"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uitapgesturerecognizer"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
