{"seeAlsoSections":[{"anchor":"Text-view-additions","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate","doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate","doc://com.apple.uikit/documentation/UIKit/UITextDragOptions","doc://com.apple.uikit/documentation/UIKit/UITextDroppable","doc://com.apple.uikit/documentation/UIKit/UITextDropEditability"],"generated":true,"title":"Text view additions"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"sections":[],"variants":[{"paths":["/documentation/uikit/uitextdraggable"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/uikit/uitextdraggable"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The interface that determines if a text view is a drag source."}],"topicSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextDraggable/isTextDragActive"],"title":"Checking the text drag activity status","anchor":"Checking-the-text-drag-activity-status"},{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextDraggable/textDragInteraction"],"title":"Managing the text drag interaction","anchor":"Managing-the-text-drag-interaction"},{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextDraggable/textDragDelegate"],"title":"Setting the text drag delegate","anchor":"Setting-the-text-drag-delegate"},{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextDraggable/textDragOptions"],"title":"Setting the text drag options","anchor":"Setting-the-text-drag-options"}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc://com.externally.resolved.symbol/c:objc(pl)NSObject","doc://com.apple.uikit/documentation/UIKit/UIKeyInput","doc://com.apple.uikit/documentation/UIKit/UITextInput","doc://com.apple.uikit/documentation/UIKit/UITextInputTraits"],"title":"Inherits From"},{"kind":"relationships","type":"conformingTypes","identifiers":["doc://com.apple.uikit/documentation/UIKit/UISearchTextField","doc://com.apple.uikit/documentation/UIKit/UITextField","doc://com.apple.uikit/documentation/UIKit/UITextView"],"title":"Conforming Types"}],"metadata":{"modules":[{"name":"UIKit"}],"externalID":"c:objc(pl)UITextDraggable","role":"symbol","roleHeading":"Protocol","symbolKind":"protocol","navigatorTitle":[{"kind":"identifier","text":"UITextDraggable"}],"platforms":[{"unavailable":false,"name":"iOS","deprecated":false,"introducedAt":"11.0","beta":false},{"unavailable":false,"name":"iPadOS","deprecated":false,"introducedAt":"11.0","beta":false},{"unavailable":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"13.1","beta":false},{"unavailable":false,"name":"visionOS","deprecated":false,"introducedAt":"1.0","beta":false}],"title":"UITextDraggable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextDraggable"}]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UITextDraggable"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITextDraggable","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UITextInput","text":"UITextInput","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextInput","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.apple.uikit/documentation/UIKit/UITextDraggable":{"role":"symbol","type":"topic","title":"UITextDraggable","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UITextDraggable"}],"url":"/documentation/uikit/uitextdraggable","abstract":[{"type":"text","text":"The interface that determines if a text view is a drag source."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextDraggable"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDraggable"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITextDraggable/isTextDragActive":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isTextDragActive","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","abstract":[{"text":"A Boolean value indicating whether at least one drag session for the text view is active.","type":"text"}],"role":"symbol","required":true,"title":"isTextDragActive","navigatorTitle":[{"text":"textDragActive","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDraggable/isTextDragActive","url":"/documentation/uikit/uitextdraggable/istextdragactive","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITextInputTraits":{"abstract":[{"type":"text","text":"A set of methods that defines features for keyboard input to a text object."}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextInputTraits","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextInputTraits"}],"title":"UITextInputTraits","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UITextInputTraits"}],"type":"topic","url":"/documentation/uikit/uitextinputtraits"},"doc://com.apple.uikit/documentation/UIKit/UIKeyInput":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyInput","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIKeyInput"}],"type":"topic","title":"UIKeyInput","url":"/documentation/uikit/uikeyinput","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIKeyInput"}],"role":"symbol","abstract":[{"type":"text","text":"A set of methods a responder uses to implement simple text entry."}]},"doc://com.apple.uikit/documentation/UIKit/UITextField":{"abstract":[{"text":"An object that displays an editable text area in your interface.","type":"text"}],"url":"/documentation/uikit/uitextfield","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextField","title":"UITextField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextField"}],"navigatorTitle":[{"kind":"identifier","text":"UITextField"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate":{"url":"/documentation/uikit/uitextdragdelegate","abstract":[{"type":"text","text":"The interface for customizing the behavior of a drag activity for a text view."}],"role":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate","kind":"symbol","title":"UITextDragDelegate","navigatorTitle":[{"kind":"identifier","text":"UITextDragDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextDragDelegate"}]},"doc://com.apple.uikit/documentation/UIKit/UITextDroppable":{"role":"symbol","type":"topic","title":"UITextDroppable","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UITextDroppable"}],"url":"/documentation/uikit/uitextdroppable","abstract":[{"type":"text","text":"The interface that determines if a text view is a drop destination."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextDroppable"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDroppable"},"doc://com.apple.uikit/documentation/UIKit/UITextView":{"navigatorTitle":[{"text":"UITextView","kind":"identifier"}],"title":"UITextView","url":"/documentation/uikit/uitextview","abstract":[{"text":"A scrollable, multiline text region.","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITextView","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextView"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITextDragOptions":{"url":"/documentation/uikit/uitextdragoptions","abstract":[{"type":"text","text":"A set of options that determine the behavior of a draggable text view."}],"role":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDragOptions","kind":"symbol","title":"UITextDragOptions","navigatorTitle":[{"kind":"identifier","text":"UITextDragOptions"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextDragOptions"}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"title":"NSObjectProtocol","type":"topic","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","role":"symbol","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"kind":"symbol","url":"/documentation/objectivec/nsobjectprotocol"},"doc://com.apple.uikit/documentation/UIKit/UISearchTextField":{"type":"topic","url":"/documentation/uikit/uisearchtextfield","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchTextField","kind":"symbol","navigatorTitle":[{"text":"UISearchTextField","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UISearchTextField","kind":"identifier"}],"title":"UISearchTextField","abstract":[{"type":"text","text":"A view for displaying and editing text and search tokens."}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITextDropEditability":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"UITextDropEditability","kind":"identifier"}],"title":"UITextDropEditability","kind":"symbol","role":"symbol","type":"topic","url":"/documentation/uikit/uitextdropeditability","navigatorTitle":[{"text":"UITextDropEditability","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDropEditability","abstract":[{"text":"The text-drop editability styles for noneditable text views.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UITextInput":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextInput","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextInput"}],"title":"UITextInput","abstract":[{"type":"text","text":"A set of methods for interacting with the text input system and enabling features in documents."}],"url":"/documentation/uikit/uitextinput","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UITextInput"}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"UITextDropDelegate"}],"url":"/documentation/uikit/uitextdropdelegate","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate","title":"UITextDropDelegate","role":"symbol","kind":"symbol","abstract":[{"text":"The interface for configuring a text view’s drop behavior.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextDropDelegate"}]},"doc://com.apple.uikit/documentation/UIKit/UITextDraggable/textDragInteraction":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDraggable/textDragInteraction","title":"textDragInteraction","role":"symbol","required":true,"type":"topic","abstract":[{"text":"The drag interaction object added by UIKit to the text view.","type":"text"}],"navigatorTitle":[{"text":"textDragInteraction","kind":"identifier"}],"url":"/documentation/uikit/uitextdraggable/textdraginteraction","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textDragInteraction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIDragInteraction","preciseIdentifier":"c:objc(cs)UIDragInteraction"},{"text":"?","kind":"text"}],"kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITextDraggable/textDragOptions":{"title":"textDragOptions","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textDragOptions"}],"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textDragOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextDragOptions","preciseIdentifier":"c:@E@UITextDragOptions"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDraggable/textDragOptions","abstract":[{"text":"The options for the text drag operation.","type":"text"}],"url":"/documentation/uikit/uitextdraggable/textdragoptions"},"doc://com.apple.uikit/documentation/UIKit/UITextDraggable/textDragDelegate":{"type":"topic","url":"/documentation/uikit/uitextdraggable/textdragdelegate","navigatorTitle":[{"text":"textDragDelegate","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDraggable/textDragDelegate","abstract":[{"text":"A text drag delegate object for customizing the drag source behavior of a text view.","type":"text"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textDragDelegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"UITextDragDelegate","preciseIdentifier":"c:objc(pl)UITextDragDelegate","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"required":true,"title":"textDragDelegate","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"unavailable":false,"name":"iOS","introducedAt":"11.0","deprecated":false,"beta":false},{"unavailable":false,"name":"iPadOS","introducedAt":"11.0","deprecated":false,"beta":false},{"unavailable":false,"name":"Mac Catalyst","introducedAt":"13.1","deprecated":false,"beta":false},{"unavailable":false,"name":"visionOS","introducedAt":"1.0","deprecated":false,"beta":false}],"path":"/metadata/platforms","op":"replace"},{"value":"Protocol","path":"/metadata/roleHeading","op":"replace"},{"value":"UITextDraggable","path":"/metadata/title","op":"replace"},{"value":"protocol","path":"/metadata/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"UITextDraggable"}],"path":"/metadata/fragments","op":"replace"},{"value":[{"text":"UITextDraggable","kind":"identifier"}],"path":"/metadata/navigatorTitle","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"path":"/hierarchy","op":"replace"},{"value":[{"anchor":"Checking-the-text-drag-activity-status","title":"Checking the text drag activity status","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextDraggable/isTextDragActive"]},{"anchor":"Managing-the-text-drag-interaction","title":"Managing the text drag interaction","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextDraggable/textDragInteraction"]},{"anchor":"Setting-the-text-drag-delegate","title":"Setting the text drag delegate","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextDraggable/textDragDelegate"]},{"anchor":"Setting-the-text-drag-options","title":"Setting the text drag options","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextDraggable/textDragOptions"]}],"path":"/topicSections","op":"replace"},{"value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextInput"]},{"kind":"relationships","title":"Conforming Types","type":"conformingTypes","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextField","doc://com.apple.uikit/documentation/UIKit/UITextView"]}],"path":"/relationshipsSections","op":"replace"},{"value":[{"title":"Text view additions","generated":true,"anchor":"Text-view-additions","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate","doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate","doc://com.apple.uikit/documentation/UIKit/UITextDragOptions","doc://com.apple.uikit/documentation/UIKit/UITextDroppable","doc://com.apple.uikit/documentation/UIKit/UITextDropEditability"]}],"path":"/seeAlsoSections","op":"replace"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextDraggable"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextInput","preciseIdentifier":"c:objc(pl)UITextInput","text":"UITextInput"},{"kind":"text","text":">"}]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDraggable/title","op":"replace","value":"UITextDraggable"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDraggable/fragments","op":"replace","value":[{"kind":"identifier","text":"UITextDraggable"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDraggable/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UITextDraggable"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDraggable~1isTextDragActive/title","op":"replace","value":"textDragActive"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDraggable~1isTextDragActive/fragments","op":"replace","value":[{"kind":"identifier","text":"textDragActive"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputTraits/title","op":"replace","value":"UITextInputTraits"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputTraits/fragments","op":"replace","value":[{"text":"UITextInputTraits","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputTraits/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UITextInputTraits"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyInput/title","op":"replace","value":"UIKeyInput"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyInput/fragments","op":"replace","value":[{"kind":"identifier","text":"UIKeyInput"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyInput/navigatorTitle","op":"replace","value":[{"text":"UIKeyInput","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextField/title","op":"replace","value":"UITextField"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextField/fragments","op":"replace","value":[{"text":"UITextField","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextField/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UITextField"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragDelegate/title","op":"replace","value":"UITextDragDelegate"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragDelegate/fragments","op":"replace","value":[{"text":"UITextDragDelegate","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragDelegate/navigatorTitle","op":"replace","value":[{"text":"UITextDragDelegate","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDroppable/title","op":"replace","value":"UITextDroppable"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDroppable/fragments","op":"replace","value":[{"text":"UITextDroppable","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDroppable/navigatorTitle","op":"replace","value":[{"text":"UITextDroppable","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextView/title","op":"replace","value":"UITextView"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextView/fragments","op":"replace","value":[{"text":"UITextView","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextView/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UITextView"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragOptions/title","op":"replace","value":"UITextDragOptions"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragOptions/fragments","op":"replace","value":[{"kind":"identifier","text":"UITextDragOptions"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragOptions/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UITextDragOptions"}]},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title","op":"replace","value":"NSObject"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchTextField/title","op":"replace","value":"UISearchTextField"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchTextField/fragments","op":"replace","value":[{"kind":"identifier","text":"UISearchTextField"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchTextField/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UISearchTextField"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropEditability/title","op":"replace","value":"UITextDropEditability"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropEditability/fragments","op":"replace","value":[{"kind":"identifier","text":"UITextDropEditability"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropEditability/navigatorTitle","op":"replace","value":[{"text":"UITextDropEditability","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInput/title","op":"replace","value":"UITextInput"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInput/fragments","op":"replace","value":[{"text":"UITextInput","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInput/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UITextInput"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropDelegate/title","op":"replace","value":"UITextDropDelegate"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropDelegate/fragments","op":"replace","value":[{"kind":"identifier","text":"UITextDropDelegate"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropDelegate/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UITextDropDelegate"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDraggable~1textDragInteraction/title","op":"replace","value":"textDragInteraction"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDraggable~1textDragInteraction/fragments","op":"replace","value":[{"kind":"identifier","text":"textDragInteraction"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDraggable~1textDragOptions/title","op":"replace","value":"textDragOptions"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDraggable~1textDragOptions/fragments","op":"replace","value":[{"kind":"identifier","text":"textDragOptions"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDraggable~1textDragDelegate/title","op":"replace","value":"textDragDelegate"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDraggable~1textDragDelegate/fragments","op":"replace","value":[{"text":"textDragDelegate","kind":"identifier"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}