{
  "abstract": [
    {
      "text": "Options for aligning text horizontally.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextAlignment",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITextAlignment"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UITextAlignment",
    "fragments": [
      {
        "kind": "identifier",
        "text": "UITextAlignment"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UITextAlignment"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "6.0",
        "introducedAt": "2.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "6.0",
        "introducedAt": "2.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "UITextAlignment"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UITextAlignment"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSInteger",
              "text": "NSInteger"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSStringDrawingContext": {
      "abstract": [
        {
          "text": "An object that manages metrics for drawing attributed strings.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStringDrawingContext"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSStringDrawingContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSStringDrawingContext"
        }
      ],
      "role": "symbol",
      "title": "NSStringDrawingContext",
      "type": "topic",
      "url": "/documentation/uikit/nsstringdrawingcontext"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSStringDrawingOptions": {
      "abstract": [
        {
          "text": "Constants that specify the rendering options for drawing a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSStringDrawingOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSStringDrawingOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSStringDrawingOptions"
        }
      ],
      "role": "symbol",
      "title": "NSStringDrawingOptions",
      "type": "topic",
      "url": "/documentation/uikit/nsstringdrawingoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/NSTextAlignment": {
      "abstract": [
        {
          "text": "Constants that specify text alignment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextAlignment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/NSTextAlignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextAlignment"
        }
      ],
      "role": "symbol",
      "title": "NSTextAlignment",
      "type": "topic",
      "url": "/documentation/uikit/nstextalignment"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBaselineAdjustment": {
      "abstract": [
        {
          "text": "Vertical adjustment options.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIBaselineAdjustment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBaselineAdjustment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBaselineAdjustment"
        }
      ],
      "role": "symbol",
      "title": "UIBaselineAdjustment",
      "type": "topic",
      "url": "/documentation/uikit/uibaselineadjustment"
    },
    "doc://com.apple.uikit/documentation/UIKit/UILineBreakMode": {
      "abstract": [
        {
          "text": "Options for wrapping and truncating text.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "UILineBreakMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UILineBreakMode",
      "kind": "symbol",
      "role": "symbol",
      "title": "UILineBreakMode",
      "type": "topic",
      "url": "/documentation/uikit/uilinebreakmode"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextAlignment": {
      "abstract": [
        {
          "text": "Options for aligning text horizontally.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextAlignment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextAlignment",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextAlignment",
      "type": "topic",
      "url": "/documentation/uikit/uitextalignment"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextAlignment/UITextAlignmentCenter": {
      "abstract": [
        {
          "text": "Align text equally along both sides of the center line.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextAlignmentCenter"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextAlignment/UITextAlignmentCenter",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextAlignmentCenter",
      "type": "topic",
      "url": "/documentation/uikit/uitextalignment/uitextalignmentcenter"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextAlignment/UITextAlignmentLeft": {
      "abstract": [
        {
          "text": "Align text along the left edge.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextAlignmentLeft"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextAlignment/UITextAlignmentLeft",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextAlignmentLeft",
      "type": "topic",
      "url": "/documentation/uikit/uitextalignment/uitextalignmentleft"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextAlignment/UITextAlignmentRight": {
      "abstract": [
        {
          "text": "Align text along the right edge.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextAlignmentRight"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextAlignment/UITextAlignmentRight",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextAlignmentRight",
      "type": "topic",
      "url": "/documentation/uikit/uitextalignment/uitextalignmentright"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextAttributeFont": {
      "abstract": [
        {
          "text": "The key to the font in a text attributes dictionary.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextAttributeFont"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextAttributeFont",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextAttributeFont",
      "type": "topic",
      "url": "/documentation/uikit/uitextattributefont"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextAttributeTextColor": {
      "abstract": [
        {
          "text": "The key to the text color in a text attributes dictionary.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextAttributeTextColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextAttributeTextColor",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextAttributeTextColor",
      "type": "topic",
      "url": "/documentation/uikit/uitextattributetextcolor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextAttributeTextShadowColor": {
      "abstract": [
        {
          "text": "The key to the text shadow color in a text attributes dictionary.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextAttributeTextShadowColor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextAttributeTextShadowColor",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextAttributeTextShadowColor",
      "type": "topic",
      "url": "/documentation/uikit/uitextattributetextshadowcolor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextAttributeTextShadowOffset": {
      "abstract": [
        {
          "text": "The key to the offset for the text shadow in a text attributes dictionary.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextAttributeTextShadowOffset"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextAttributeTextShadowOffset",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextAttributeTextShadowOffset",
      "type": "topic",
      "url": "/documentation/uikit/uitextattributetextshadowoffset"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Strings",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/NSStringDrawingContext",
        "doc://com.apple.uikit/documentation/UIKit/NSStringDrawingOptions",
        "doc://com.apple.uikit/documentation/UIKit/UIBaselineAdjustment",
        "doc://com.apple.uikit/documentation/UIKit/UILineBreakMode",
        "doc://com.apple.uikit/documentation/UIKit/UITextAttributeFont",
        "doc://com.apple.uikit/documentation/UIKit/UITextAttributeTextColor",
        "doc://com.apple.uikit/documentation/UIKit/UITextAttributeTextShadowColor",
        "doc://com.apple.uikit/documentation/UIKit/UITextAttributeTextShadowOffset"
      ],
      "title": "Strings"
    }
  ],
  "topicSections": [
    {
      "anchor": "Deprecated-constants",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextAlignment/UITextAlignmentLeft",
        "doc://com.apple.uikit/documentation/UIKit/UITextAlignment/UITextAlignmentCenter",
        "doc://com.apple.uikit/documentation/UIKit/UITextAlignment/UITextAlignmentRight"
      ],
      "title": "Deprecated constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextAlignment/title",
          "value": "NSTextAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextAlignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSTextAlignment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBaselineAdjustment/title",
          "value": "UIBaselineAdjustment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBaselineAdjustment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBaselineAdjustment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBaselineAdjustment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBaselineAdjustment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSStringDrawingOptions/title",
          "value": "NSStringDrawingOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSStringDrawingOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStringDrawingOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSStringDrawingOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStringDrawingOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSStringDrawingContext/title",
          "value": "NSStringDrawingContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSStringDrawingContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStringDrawingContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1NSStringDrawingContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSStringDrawingContext"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitextalignment"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
