{
  "abstract": [
    {
      "text": "An object that provides the system UI for displaying text selection.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteraction"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UITextSelectionDisplayInteraction",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UITextSelectionDisplayInteraction"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UITextSelectionDisplayInteraction"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "UITextSelectionDisplayInteraction"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UITextSelectionDisplayInteraction"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.uikit/documentation/UIKit/adopting-system-selection-ui-in-custom-text-views"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "Session 10058: ",
                  "type": "text"
                },
                {
                  "identifier": "https://developer.apple.com/videos/play/wwdc2023/10058/",
                  "isActive": true,
                  "type": "reference"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Related sessions from WWDC23",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIInteraction": {
      "abstract": [
        {
          "text": "The protocol that an interaction implements to access the view that owns it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIInteraction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIInteraction"
        }
      ],
      "role": "symbol",
      "title": "UIInteraction",
      "type": "topic",
      "url": "/documentation/uikit/uiinteraction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIStandardTextCursorView": {
      "abstract": [
        {
          "text": "A view that draws the standard system insertion point in a piece of text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIStandardTextCursorView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIStandardTextCursorView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIStandardTextCursorView"
        }
      ],
      "role": "symbol",
      "title": "UIStandardTextCursorView",
      "type": "topic",
      "url": "/documentation/uikit/uistandardtextcursorview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextCursorDropPositionAnimator": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextCursorDropPositionAnimator"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextCursorDropPositionAnimator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextCursorDropPositionAnimator"
        }
      ],
      "role": "symbol",
      "title": "UITextCursorDropPositionAnimator",
      "type": "topic",
      "url": "/documentation/uikit/uitextcursordroppositionanimator"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextCursorView": {
      "abstract": [
        {
          "text": "An interface you use to draw the insertion point in a piece of text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextCursorView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextCursorView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextCursorView"
        }
      ],
      "role": "symbol",
      "title": "UITextCursorView",
      "type": "topic",
      "url": "/documentation/uikit/uitextcursorview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextLoupeSession": {
      "abstract": [
        {
          "text": "An object that manages the presentation of the system magnifier at the location you specify.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextLoupeSession"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextLoupeSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextLoupeSession"
        }
      ],
      "role": "symbol",
      "title": "UITextLoupeSession",
      "type": "topic",
      "url": "/documentation/uikit/uitextloupesession"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteraction": {
      "abstract": [
        {
          "text": "An object that provides the system UI for displaying text selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextSelectionDisplayInteraction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextSelectionDisplayInteraction"
        }
      ],
      "role": "symbol",
      "title": "UITextSelectionDisplayInteraction",
      "type": "topic",
      "url": "/documentation/uikit/uitextselectiondisplayinteraction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteraction/cursorView": {
      "abstract": [
        {
          "text": "The view that draws the caret at the text insertion point.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cursorView"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITextCursorView",
          "text": "UITextCursorView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteraction/cursorView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cursorView"
        }
      ],
      "role": "symbol",
      "title": "cursorView",
      "type": "topic",
      "url": "/documentation/uikit/uitextselectiondisplayinteraction/cursorview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteraction/delegate": {
      "abstract": [
        {
          "text": "A delegate that provides a container view to manage the system-supplied selection views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITextSelectionDisplayInteractionDelegate",
          "text": "UITextSelectionDisplayInteractionDelegate"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteraction/delegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "delegate"
        }
      ],
      "role": "symbol",
      "title": "delegate",
      "type": "topic",
      "url": "/documentation/uikit/uitextselectiondisplayinteraction/delegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteraction/handleViews": {
      "abstract": [
        {
          "text": "The view that draws the selection handles for the selected text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "handleViews"
        },
        {
          "kind": "text",
          "text": ": [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITextSelectionHandleView",
          "text": "UITextSelectionHandleView"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteraction/handleViews",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "handleViews"
        }
      ],
      "role": "symbol",
      "title": "handleViews",
      "type": "topic",
      "url": "/documentation/uikit/uitextselectiondisplayinteraction/handleviews"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteraction/highlightView": {
      "abstract": [
        {
          "text": "The view that draws the selection highlight behind the rendered text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "highlightView"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITextSelectionHighlightView",
          "text": "UITextSelectionHighlightView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteraction/highlightView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "highlightView"
        }
      ],
      "role": "symbol",
      "title": "highlightView",
      "type": "topic",
      "url": "/documentation/uikit/uitextselectiondisplayinteraction/highlightview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteraction/init(textInput:delegate:)": {
      "abstract": [
        {
          "text": "Creates a new text selection display interaction object for the specified text view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "textInput"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITextInput",
          "text": "UITextInput"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "delegate"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITextSelectionDisplayInteractionDelegate",
          "text": "UITextSelectionDisplayInteractionDelegate"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteraction/init(textInput:delegate:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTextInput:delegate:"
        }
      ],
      "role": "symbol",
      "title": "init(textInput:delegate:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextselectiondisplayinteraction/init(textinput:delegate:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteraction/isActivated": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether to display the system selection UI.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isActivated"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteraction/isActivated",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activated"
        }
      ],
      "role": "symbol",
      "title": "isActivated",
      "type": "topic",
      "url": "/documentation/uikit/uitextselectiondisplayinteraction/isactivated"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteraction/layoutManagedSubviews()": {
      "abstract": [
        {
          "text": "Loads the selection from the text input view and lays out the selection-related views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "layoutManagedSubviews"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteraction/layoutManagedSubviews()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "layoutManagedSubviews"
        }
      ],
      "role": "symbol",
      "title": "layoutManagedSubviews()",
      "type": "topic",
      "url": "/documentation/uikit/uitextselectiondisplayinteraction/layoutmanagedsubviews()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteraction/setNeedsSelectionUpdate()": {
      "abstract": [
        {
          "text": "Tells the system to update the selection UI to match the current selection state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setNeedsSelectionUpdate"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteraction/setNeedsSelectionUpdate()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setNeedsSelectionUpdate"
        }
      ],
      "role": "symbol",
      "title": "setNeedsSelectionUpdate()",
      "type": "topic",
      "url": "/documentation/uikit/uitextselectiondisplayinteraction/setneedsselectionupdate()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteraction/textInput": {
      "abstract": [
        {
          "text": "The text input object that manages the selection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textInput"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITextInput",
          "text": "UITextInput"
        },
        {
          "kind": "text",
          "text": ")?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteraction/textInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textInput"
        }
      ],
      "role": "symbol",
      "title": "textInput",
      "type": "topic",
      "url": "/documentation/uikit/uitextselectiondisplayinteraction/textinput"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteractionDelegate": {
      "abstract": [
        {
          "text": "An object you use to customize the presentation of text selections in your interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextSelectionDisplayInteractionDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteractionDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextSelectionDisplayInteractionDelegate"
        }
      ],
      "role": "symbol",
      "title": "UITextSelectionDisplayInteractionDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uitextselectiondisplayinteractiondelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSelectionHandleView": {
      "abstract": [
        {
          "text": "An interface you use to draw custom the selection handles for ranges of text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextSelectionHandleView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSelectionHandleView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextSelectionHandleView"
        }
      ],
      "role": "symbol",
      "title": "UITextSelectionHandleView",
      "type": "topic",
      "url": "/documentation/uikit/uitextselectionhandleview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSelectionHighlightView": {
      "abstract": [
        {
          "text": "An interface you use to provide a custom highlight UI behind the selected text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextSelectionHighlightView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSelectionHighlightView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextSelectionHighlightView"
        }
      ],
      "role": "symbol",
      "title": "UITextSelectionHighlightView",
      "type": "topic",
      "url": "/documentation/uikit/uitextselectionhighlightview"
    },
    "doc://com.apple.uikit/documentation/UIKit/adopting-system-selection-ui-in-custom-text-views": {
      "abstract": [
        {
          "text": "Incorporate the system text-selection experience into your custom text UI in UIKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/adopting-system-selection-ui-in-custom-text-views",
      "kind": "article",
      "role": "article",
      "title": "Adopting system selection UI in custom text views",
      "type": "topic",
      "url": "/documentation/uikit/adopting-system-selection-ui-in-custom-text-views"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "https://developer.apple.com/videos/play/wwdc2023/10058/": {
      "identifier": "https://developer.apple.com/videos/play/wwdc2023/10058/",
      "title": "What’s new with text and text interactions",
      "titleInlineContent": [
        {
          "text": "What’s new with text and text interactions",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/videos/play/wwdc2023/10058/"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.apple.uikit/documentation/UIKit/UIInteraction"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Custom-text-selection",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/adopting-system-selection-ui-in-custom-text-views",
        "doc://com.apple.uikit/documentation/UIKit/UITextSelectionHighlightView",
        "doc://com.apple.uikit/documentation/UIKit/UITextSelectionHandleView",
        "doc://com.apple.uikit/documentation/UIKit/UITextCursorView",
        "doc://com.apple.uikit/documentation/UIKit/UIStandardTextCursorView",
        "doc://com.apple.uikit/documentation/UIKit/UITextCursorDropPositionAnimator",
        "doc://com.apple.uikit/documentation/UIKit/UITextLoupeSession"
      ],
      "title": "Custom text selection"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-text-selection-display-interaction",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteraction/init(textInput:delegate:)"
      ],
      "title": "Creating a text selection display interaction"
    },
    {
      "anchor": "Managing-the-drawing-view",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteraction/delegate",
        "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteractionDelegate"
      ],
      "title": "Managing the drawing view"
    },
    {
      "anchor": "Activating-the-selection-UI",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteraction/isActivated"
      ],
      "title": "Activating the selection UI"
    },
    {
      "anchor": "Reporting-changes-to-the-selection",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteraction/setNeedsSelectionUpdate()",
        "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteraction/layoutManagedSubviews()"
      ],
      "title": "Reporting changes to the selection"
    },
    {
      "anchor": "Getting-the-text-input-view",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteraction/textInput"
      ],
      "title": "Getting the text input view"
    },
    {
      "anchor": "Getting-the-system-selection-views",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteraction/highlightView",
        "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteraction/handleViews",
        "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteraction/cursorView"
      ],
      "title": "Getting the system selection views"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "17.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UITextSelectionDisplayInteraction"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSelectionDisplayInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSelectionDisplayInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-a-text-selection-display-interaction",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteraction/init(textInput:delegate:)"
              ],
              "title": "Creating a text selection display interaction"
            },
            {
              "anchor": "Managing-the-drawing-view",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteraction/delegate",
                "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteractionDelegate"
              ],
              "title": "Managing the drawing view"
            },
            {
              "anchor": "Activating-the-selection-UI",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteraction/isActivated"
              ],
              "title": "Activating the selection UI"
            },
            {
              "anchor": "Reporting-changes-to-the-selection",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteraction/setNeedsSelectionUpdate()",
                "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteraction/layoutManagedSubviews()"
              ],
              "title": "Reporting changes to the selection"
            },
            {
              "anchor": "Getting-the-text-input-view",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteraction/textInput"
              ],
              "title": "Getting the text input view"
            },
            {
              "anchor": "Getting-the-system-selection-views",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteraction/highlightView",
                "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteraction/handleViews",
                "doc://com.apple.uikit/documentation/UIKit/UITextSelectionDisplayInteraction/cursorView"
              ],
              "title": "Getting the system selection views"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIInteraction"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Custom-text-selection",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/adopting-system-selection-ui-in-custom-text-views",
                "doc://com.apple.uikit/documentation/UIKit/UITextSelectionHighlightView",
                "doc://com.apple.uikit/documentation/UIKit/UITextSelectionHandleView",
                "doc://com.apple.uikit/documentation/UIKit/UITextCursorView",
                "doc://com.apple.uikit/documentation/UIKit/UIStandardTextCursorView",
                "doc://com.apple.uikit/documentation/UIKit/UITextCursorDropPositionAnimator",
                "doc://com.apple.uikit/documentation/UIKit/UITextLoupeSession"
              ],
              "title": "Custom text selection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UITextSelectionDisplayInteraction"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextCursorView/title",
          "value": "UITextCursorView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextCursorView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextCursorView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextCursorView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextCursorView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSelectionDisplayInteraction~1highlightView/title",
          "value": "highlightView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSelectionDisplayInteraction~1highlightView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "highlightView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextLoupeSession/title",
          "value": "UITextLoupeSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextLoupeSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextLoupeSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextLoupeSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextLoupeSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSelectionDisplayInteraction~1delegate/title",
          "value": "delegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSelectionDisplayInteraction~1delegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "delegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextCursorDropPositionAnimator/title",
          "value": "UITextCursorDropPositionAnimator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextCursorDropPositionAnimator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextCursorDropPositionAnimator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextCursorDropPositionAnimator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextCursorDropPositionAnimator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStandardTextCursorView/title",
          "value": "UIStandardTextCursorView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStandardTextCursorView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIStandardTextCursorView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStandardTextCursorView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIStandardTextCursorView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSelectionDisplayInteraction~1handleViews/title",
          "value": "handleViews"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSelectionDisplayInteraction~1handleViews/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "handleViews"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSelectionDisplayInteraction~1layoutManagedSubviews()/title",
          "value": "layoutManagedSubviews"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSelectionDisplayInteraction~1layoutManagedSubviews()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "layoutManagedSubviews"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSelectionDisplayInteraction~1textInput/title",
          "value": "textInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSelectionDisplayInteraction~1textInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "textInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSelectionDisplayInteraction~1init(textInput:delegate:)/title",
          "value": "initWithTextInput:delegate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSelectionDisplayInteraction~1init(textInput:delegate:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithTextInput:delegate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInteraction/title",
          "value": "UIInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSelectionHighlightView/title",
          "value": "UITextSelectionHighlightView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSelectionHighlightView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSelectionHighlightView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSelectionHighlightView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSelectionHighlightView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSelectionHandleView/title",
          "value": "UITextSelectionHandleView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSelectionHandleView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSelectionHandleView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSelectionHandleView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSelectionHandleView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSelectionDisplayInteraction~1cursorView/title",
          "value": "cursorView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSelectionDisplayInteraction~1cursorView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cursorView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSelectionDisplayInteraction~1isActivated/title",
          "value": "activated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSelectionDisplayInteraction~1isActivated/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "activated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSelectionDisplayInteractionDelegate/title",
          "value": "UITextSelectionDisplayInteractionDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSelectionDisplayInteractionDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSelectionDisplayInteractionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSelectionDisplayInteractionDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSelectionDisplayInteractionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSelectionDisplayInteraction~1setNeedsSelectionUpdate()/title",
          "value": "setNeedsSelectionUpdate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSelectionDisplayInteraction~1setNeedsSelectionUpdate()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setNeedsSelectionUpdate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSelectionDisplayInteraction/title",
          "value": "UITextSelectionDisplayInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSelectionDisplayInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSelectionDisplayInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSelectionDisplayInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSelectionDisplayInteraction"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitextselectiondisplayinteraction"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uitextselectiondisplayinteraction"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
