{"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP","doc://com.externally.resolved.symbol/s:s9OptionSetP","doc://com.externally.resolved.symbol/s:SY","doc://com.externally.resolved.symbol/s:s8SendableP","doc://com.externally.resolved.symbol/s:s10SetAlgebraP"],"kind":"relationships"}],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UITextDragOptions","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uitextdragoptions"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uitextdragoptions"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"A set of options that determine the behavior of a draggable text view."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITextDragOptions","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"languages":["swift"]}]}],"metadata":{"symbolKind":"struct","title":"UITextDragOptions","navigatorTitle":[{"text":"UITextDragOptions","kind":"identifier"}],"modules":[{"name":"UIKit"}],"platforms":[{"beta":false,"introducedAt":"11.0","unavailable":false,"name":"iOS","deprecated":false},{"beta":false,"introducedAt":"11.0","unavailable":false,"name":"iPadOS","deprecated":false},{"beta":false,"introducedAt":"13.1","unavailable":false,"name":"Mac Catalyst","deprecated":false},{"beta":false,"introducedAt":"1.0","name":"visionOS","unavailable":false,"deprecated":false}],"externalID":"c:@E@UITextDragOptions","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITextDragOptions","kind":"identifier"}],"roleHeading":"Structure"},"sections":[],"kind":"symbol","seeAlsoSections":[{"title":"Text view additions","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate","doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate","doc://com.apple.uikit/documentation/UIKit/UITextDraggable","doc://com.apple.uikit/documentation/UIKit/UITextDroppable","doc://com.apple.uikit/documentation/UIKit/UITextDropEditability"],"anchor":"Text-view-additions","generated":true}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"topicSections":[{"title":"Text drag options","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextDragOptions/stripTextColorFromPreviews"],"anchor":"Text-drag-options"},{"title":"Initializers","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextDragOptions/init(rawValue:)"],"anchor":"Initializers"}],"references":{"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP":{"title":"BitwiseCopyable","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BitwiseCopyable"},{"kind":"text","text":" : ~Escapable"}],"identifier":"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","role":"symbol","url":"/documentation/Swift/BitwiseCopyable","kind":"symbol","abstract":[{"type":"text","text":""}]},"doc://com.externally.resolved.symbol/s:s8SendableP":{"abstract":[{"type":"text","text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races."}],"url":"/documentation/Swift/Sendable","identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}],"role":"symbol","title":"Sendable","type":"topic","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITextDropEditability":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"UITextDropEditability","kind":"identifier"}],"title":"UITextDropEditability","kind":"symbol","role":"symbol","type":"topic","url":"/documentation/uikit/uitextdropeditability","navigatorTitle":[{"text":"UITextDropEditability","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDropEditability","abstract":[{"text":"The text-drop editability styles for noneditable text views.","type":"text"}]},"doc://com.externally.resolved.symbol/c:@T@NSInteger":{"abstract":[{"type":"text","text":"Describes an integer."}],"url":"/documentation/objectivec/nsinteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","fragments":[{"text":"typealias ","kind":"text"},{"text":"NSInteger","kind":"identifier"}],"role":"symbol","title":"NSInteger","type":"topic","kind":"symbol"},"doc://com.externally.resolved.symbol/s:SY":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RawRepresentable"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:SY8RawValueQa","kind":"typeIdentifier","text":"RawValue"},{"kind":"text","text":">"}],"url":"/documentation/Swift/RawRepresentable","title":"RawRepresentable","abstract":[{"type":"text","text":"A type that can be converted to and from an associated raw value."}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SY"},"doc://com.apple.uikit/documentation/UIKit/UITextDragOptions/UITextDragOptionsNone":{"url":"/documentation/uikit/uitextdragoptions/uitextdragoptionsnone","role":"symbol","title":"UITextDragOptionsNone","type":"topic","fragments":[{"kind":"identifier","text":"UITextDragOptionsNone"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDragOptions/UITextDragOptionsNone","abstract":[{"type":"text","text":"Indicates no text drag options."}]},"doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate":{"url":"/documentation/uikit/uitextdragdelegate","abstract":[{"type":"text","text":"The interface for customizing the behavior of a drag activity for a text view."}],"role":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate","kind":"symbol","title":"UITextDragDelegate","navigatorTitle":[{"kind":"identifier","text":"UITextDragDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextDragDelegate"}]},"doc://com.apple.uikit/documentation/UIKit/UITextDroppable":{"role":"symbol","type":"topic","title":"UITextDroppable","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UITextDroppable"}],"url":"/documentation/uikit/uitextdroppable","abstract":[{"type":"text","text":"The interface that determines if a text view is a drop destination."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextDroppable"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDroppable"},"doc://com.externally.resolved.symbol/s:s9OptionSetP":{"role":"symbol","url":"/documentation/Swift/OptionSet","abstract":[{"text":"A type that presents a mathematical set interface to a bit set.","type":"text"}],"type":"topic","title":"OptionSet","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OptionSet","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SY","text":"RawRepresentable","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:s10SetAlgebraP","text":"SetAlgebra","kind":"typeIdentifier"}],"identifier":"doc://com.externally.resolved.symbol/s:s9OptionSetP","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITextDragOptions":{"url":"/documentation/uikit/uitextdragoptions","abstract":[{"type":"text","text":"A set of options that determine the behavior of a draggable text view."}],"role":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDragOptions","kind":"symbol","title":"UITextDragOptions","navigatorTitle":[{"kind":"identifier","text":"UITextDragOptions"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextDragOptions"}]},"doc://com.externally.resolved.symbol/s:s10SetAlgebraP":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SetAlgebra"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Element","preciseIdentifier":"s:s10SetAlgebraP7ElementQa"},{"kind":"text","text":"> : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SQ","text":"Equatable"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s25ExpressibleByArrayLiteralP","text":"ExpressibleByArrayLiteral"}],"identifier":"doc://com.externally.resolved.symbol/s:s10SetAlgebraP","role":"symbol","title":"SetAlgebra","url":"/documentation/Swift/SetAlgebra","abstract":[{"type":"text","text":"A type that provides mathematical set operations."}],"kind":"symbol","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITextDragOptions/init(rawValue:)":{"url":"/documentation/uikit/uitextdragoptions/init(rawvalue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","title":"init(rawValue:)","abstract":[{"text":"Creates a text-drag options structure with the specified raw value.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDragOptions/init(rawValue:)","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"UITextDropDelegate"}],"url":"/documentation/uikit/uitextdropdelegate","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate","title":"UITextDropDelegate","role":"symbol","kind":"symbol","abstract":[{"text":"The interface for configuring a text view’s drop behavior.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextDropDelegate"}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP":{"kind":"symbol","abstract":[{"text":"A type that can be initialized using an array literal.","type":"text"}],"url":"/documentation/Swift/ExpressibleByArrayLiteral","identifier":"doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP","title":"ExpressibleByArrayLiteral","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExpressibleByArrayLiteral"}]},"doc://com.apple.uikit/documentation/UIKit/UITextDragOptions/stripTextColorFromPreviews":{"abstract":[{"type":"text","text":"Strips the foreground and background colors for a system-provided text drag preview."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDragOptions/stripTextColorFromPreviews","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"UITextDragOptionStripTextColorFromPreviews","kind":"identifier"}],"url":"/documentation/uikit/uitextdragoptions/striptextcolorfrompreviews","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"stripTextColorFromPreviews","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@UITextDragOptions","text":"UITextDragOptions","kind":"typeIdentifier"}],"title":"stripTextColorFromPreviews","type":"topic"},"doc://com.externally.resolved.symbol/s:SQ":{"abstract":[{"type":"text","text":"A type that can be compared for value equality."}],"url":"/documentation/Swift/Equatable","identifier":"doc://com.externally.resolved.symbol/s:SQ","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"role":"symbol","title":"Equatable","type":"topic","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITextDraggable":{"role":"symbol","type":"topic","title":"UITextDraggable","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UITextDraggable"}],"url":"/documentation/uikit/uitextdraggable","abstract":[{"type":"text","text":"The interface that determines if a text view is a drag source."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextDraggable"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDraggable"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"introducedAt":"11.0","unavailable":false,"beta":false,"name":"iOS","deprecated":false},{"introducedAt":"11.0","unavailable":false,"beta":false,"name":"iPadOS","deprecated":false},{"introducedAt":"13.1","unavailable":false,"beta":false,"name":"Mac Catalyst","deprecated":false},{"beta":false,"introducedAt":"1.0","name":"visionOS","unavailable":false,"deprecated":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Enumeration","op":"replace"},{"path":"/metadata/title","value":"UITextDragOptions","op":"replace"},{"path":"/metadata/symbolKind","value":"enum","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"identifier","text":"UITextDragOptions"}],"op":"replace"},{"path":"/metadata/navigatorTitle","value":[{"text":"UITextDragOptions","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"op":"replace"},{"path":"/topicSections","value":[{"anchor":"Text-drag-options","title":"Text drag options","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextDragOptions/UITextDragOptionsNone","doc://com.apple.uikit/documentation/UIKit/UITextDragOptions/stripTextColorFromPreviews"]}],"op":"replace"},{"path":"/relationshipsSections","value":null,"op":"replace"},{"path":"/seeAlsoSections","value":[{"title":"Text view additions","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate","doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate","doc://com.apple.uikit/documentation/UIKit/UITextDraggable","doc://com.apple.uikit/documentation/UIKit/UITextDroppable","doc://com.apple.uikit/documentation/UIKit/UITextDropEditability"],"generated":true,"anchor":"Text-view-additions"}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITextDragOptions","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"},"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropEditability/title","value":"UITextDropEditability","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropEditability/fragments","value":[{"kind":"identifier","text":"UITextDropEditability"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropEditability/navigatorTitle","value":[{"kind":"identifier","text":"UITextDropEditability"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragDelegate/title","value":"UITextDragDelegate","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragDelegate/fragments","value":[{"kind":"identifier","text":"UITextDragDelegate"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragDelegate/navigatorTitle","value":[{"text":"UITextDragDelegate","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDroppable/title","value":"UITextDroppable","op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDroppable/fragments","value":[{"text":"UITextDroppable","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDroppable/navigatorTitle","value":[{"text":"UITextDroppable","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragOptions/title","value":"UITextDragOptions","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragOptions/fragments","value":[{"text":"UITextDragOptions","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragOptions/navigatorTitle","value":[{"kind":"identifier","text":"UITextDragOptions"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropDelegate/title","value":"UITextDropDelegate"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropDelegate/fragments","value":[{"kind":"identifier","text":"UITextDropDelegate"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropDelegate/navigatorTitle","value":[{"kind":"identifier","text":"UITextDropDelegate"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragOptions~1stripTextColorFromPreviews/title","value":"UITextDragOptionStripTextColorFromPreviews"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragOptions~1stripTextColorFromPreviews/fragments","value":[{"text":"UITextDragOptionStripTextColorFromPreviews","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDraggable/title","value":"UITextDraggable"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDraggable/fragments","value":[{"text":"UITextDraggable","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDraggable/navigatorTitle","value":[{"text":"UITextDraggable","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}