{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerChangeValue"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UITextFormattingViewControllerChangeValue",
    "fragments": [
      {
        "kind": "identifier",
        "text": "UITextFormattingViewControllerChangeValue"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UITextFormattingViewControllerChangeValue"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "UITextFormattingViewControllerChangeValue"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerChangeValue"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/Component": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Component"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/Component",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Component"
        }
      ],
      "role": "symbol",
      "title": "UITextFormattingViewController.Component",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/component"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentGroup": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ComponentGroup"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ComponentGroup"
        }
      ],
      "role": "symbol",
      "title": "UITextFormattingViewController.ComponentGroup",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/componentgroup"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/Configuration-swift.class": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Configuration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/Configuration-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Configuration"
        }
      ],
      "role": "symbol",
      "title": "UITextFormattingViewController.Configuration",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/configuration-swift.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerChangeValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextFormattingViewControllerChangeValue"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerChangeValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextFormattingViewControllerChangeValue",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontrollerchangevalue"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerChangeValue/changeType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "changeType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerChangeValue/changeType",
      "kind": "symbol",
      "role": "symbol",
      "title": "changeType",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontrollerchangevalue/changetype"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerChangeValue/color": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "color"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerChangeValue/color",
      "kind": "symbol",
      "role": "symbol",
      "title": "color",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontrollerchangevalue/color"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerChangeValue/font": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "font"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerChangeValue/font",
      "kind": "symbol",
      "role": "symbol",
      "title": "font",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontrollerchangevalue/font"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerChangeValue/formattingStyleKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "formattingStyleKey"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerChangeValue/formattingStyleKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "formattingStyleKey",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontrollerchangevalue/formattingstylekey"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerChangeValue/highlight": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "highlight"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerChangeValue/highlight",
      "kind": "symbol",
      "role": "symbol",
      "title": "highlight",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontrollerchangevalue/highlight"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerChangeValue/numberValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "numberValue"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerChangeValue/numberValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "numberValue",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontrollerchangevalue/numbervalue"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerChangeValue/textAlignment": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "textAlignment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerChangeValue/textAlignment",
      "kind": "symbol",
      "role": "symbol",
      "title": "textAlignment",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontrollerchangevalue/textalignment"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerChangeValue/textList": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "textList"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerChangeValue/textList",
      "kind": "symbol",
      "role": "symbol",
      "title": "textList",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontrollerchangevalue/textlist"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextFormattingViewControllerFormattingDescriptor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextFormattingViewControllerFormattingDescriptor",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontrollerformattingdescriptor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingStyle": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextFormattingViewControllerFormattingStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextFormattingViewControllerFormattingStyle",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontrollerformattingstyle"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Classes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/Component",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentGroup",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/Configuration-swift.class",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingStyle"
      ],
      "title": "Classes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerChangeValue/changeType",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerChangeValue/color",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerChangeValue/font",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerChangeValue/formattingStyleKey",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerChangeValue/highlight",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerChangeValue/numberValue",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerChangeValue/textAlignment",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerChangeValue/textList"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1Component/title",
          "value": "UITextFormattingViewControllerComponent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1Component/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerComponent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1Component/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerComponent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1Configuration-swift.class/title",
          "value": "UITextFormattingViewControllerConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1Configuration-swift.class/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1Configuration-swift.class/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentGroup/title",
          "value": "UITextFormattingViewControllerComponentGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerComponentGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentGroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerComponentGroup"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitextformattingviewcontrollerchangevalue"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
