{
  "abstract": [
    {
      "text": "The interface for configuring a text view’s drop behavior.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UITextDropDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UITextDropDelegate"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UITextDropDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "UITextDropDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UITextDropDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate": {
      "abstract": [
        {
          "text": "The interface for customizing the behavior of a drag activity for a text view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextDragDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextDragDelegate"
        }
      ],
      "role": "symbol",
      "title": "UITextDragDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uitextdragdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextDragOptions": {
      "abstract": [
        {
          "text": "A set of options that determine the behavior of a draggable text view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextDragOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextDragOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextDragOptions"
        }
      ],
      "role": "symbol",
      "title": "UITextDragOptions",
      "type": "topic",
      "url": "/documentation/uikit/uitextdragoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextDraggable": {
      "abstract": [
        {
          "text": "The interface that determines if a text view is a drag source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextDraggable"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextDraggable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextDraggable"
        }
      ],
      "role": "symbol",
      "title": "UITextDraggable",
      "type": "topic",
      "url": "/documentation/uikit/uitextdraggable"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate": {
      "abstract": [
        {
          "text": "The interface for configuring a text view’s drop behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextDropDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextDropDelegate"
        }
      ],
      "role": "symbol",
      "title": "UITextDropDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uitextdropdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:dropSessionDidEnd:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the drop session has ended.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textDroppableView"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITextDroppable",
          "text": "UITextDroppable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dropSessionDidEnd"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDropSession",
          "text": "UIDropSession"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:dropSessionDidEnd:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textDroppableView:dropSessionDidEnd:"
        }
      ],
      "role": "symbol",
      "title": "textDroppableView(_:dropSessionDidEnd:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextdropdelegate/textdroppableview(_:dropsessiondidend:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:dropSessionDidEnter:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user has moved the drag items into the coordinate system of the text view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textDroppableView"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITextDroppable",
          "text": "UITextDroppable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dropSessionDidEnter"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDropSession",
          "text": "UIDropSession"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:dropSessionDidEnter:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textDroppableView:dropSessionDidEnter:"
        }
      ],
      "role": "symbol",
      "title": "textDroppableView(_:dropSessionDidEnter:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextdropdelegate/textdroppableview(_:dropsessiondidenter:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:dropSessionDidExit:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the user has moved the drag items out of the text view’s coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textDroppableView"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITextDroppable",
          "text": "UITextDroppable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dropSessionDidExit"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDropSession",
          "text": "UIDropSession"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:dropSessionDidExit:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textDroppableView:dropSessionDidExit:"
        }
      ],
      "role": "symbol",
      "title": "textDroppableView(_:dropSessionDidExit:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextdropdelegate/textdroppableview(_:dropsessiondidexit:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:dropSessionDidUpdate:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the drop session has been updated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textDroppableView"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITextDroppable",
          "text": "UITextDroppable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dropSessionDidUpdate"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDropSession",
          "text": "UIDropSession"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:dropSessionDidUpdate:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textDroppableView:dropSessionDidUpdate:"
        }
      ],
      "role": "symbol",
      "title": "textDroppableView(_:dropSessionDidUpdate:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextdropdelegate/textdroppableview(_:dropsessiondidupdate:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:previewForDroppingAllItemsWithDefault:)": {
      "abstract": [
        {
          "text": "Asks the delegate for the preview to show during the drop animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textDroppableView"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITextDroppable",
          "text": "UITextDroppable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "previewForDroppingAllItemsWithDefault"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITargetedDragPreview",
          "text": "UITargetedDragPreview"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITargetedDragPreview",
          "text": "UITargetedDragPreview"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:previewForDroppingAllItemsWithDefault:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textDroppableView:previewForDroppingAllItemsWithDefault:"
        }
      ],
      "role": "symbol",
      "title": "textDroppableView(_:previewForDroppingAllItemsWithDefault:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextdropdelegate/textdroppableview(_:previewfordroppingallitemswithdefault:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:proposalForDrop:)": {
      "abstract": [
        {
          "text": "Asks the delegate if the text view can accept a drop operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textDroppableView"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITextDroppable",
          "text": "UITextDroppable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "proposalForDrop"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITextDropRequest",
          "text": "UITextDropRequest"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextDropProposal",
          "text": "UITextDropProposal"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:proposalForDrop:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textDroppableView:proposalForDrop:"
        }
      ],
      "role": "symbol",
      "title": "textDroppableView(_:proposalForDrop:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextdropdelegate/textdroppableview(_:proposalfordrop:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:willBecomeEditableForDrop:)": {
      "abstract": [
        {
          "text": "Asks the delegate if a noneditable text view can accept a drop operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textDroppableView"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITextDroppable",
          "text": "UITextDroppable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willBecomeEditableForDrop"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITextDropRequest",
          "text": "UITextDropRequest"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UITextDropEditability",
          "text": "UITextDropEditability"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:willBecomeEditableForDrop:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textDroppableView:willBecomeEditableForDrop:"
        }
      ],
      "role": "symbol",
      "title": "textDroppableView(_:willBecomeEditableForDrop:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextdropdelegate/textdroppableview(_:willbecomeeditablefordrop:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:willPerformDrop:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the drop operation is about to happen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textDroppableView"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITextDroppable",
          "text": "UITextDroppable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willPerformDrop"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITextDropRequest",
          "text": "UITextDropRequest"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:willPerformDrop:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textDroppableView:willPerformDrop:"
        }
      ],
      "role": "symbol",
      "title": "textDroppableView(_:willPerformDrop:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextdropdelegate/textdroppableview(_:willperformdrop:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextDropEditability": {
      "abstract": [
        {
          "text": "The text-drop editability styles for noneditable text views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextDropEditability"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextDropEditability",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextDropEditability"
        }
      ],
      "role": "symbol",
      "title": "UITextDropEditability",
      "type": "topic",
      "url": "/documentation/uikit/uitextdropeditability"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextDroppable": {
      "abstract": [
        {
          "text": "The interface that determines if a text view is a drop destination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextDroppable"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextDroppable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextDroppable"
        }
      ],
      "role": "symbol",
      "title": "UITextDroppable",
      "type": "topic",
      "url": "/documentation/uikit/uitextdroppable"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Text-view-additions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate",
        "doc://com.apple.uikit/documentation/UIKit/UITextDraggable",
        "doc://com.apple.uikit/documentation/UIKit/UITextDragOptions",
        "doc://com.apple.uikit/documentation/UIKit/UITextDroppable",
        "doc://com.apple.uikit/documentation/UIKit/UITextDropEditability"
      ],
      "title": "Text view additions"
    }
  ],
  "topicSections": [
    {
      "anchor": "Accepting-a-drop-activity",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:proposalForDrop:)",
        "doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:willBecomeEditableForDrop:)"
      ],
      "title": "Accepting a drop activity"
    },
    {
      "anchor": "Handling-drop-session-notifications",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:dropSessionDidEnter:)",
        "doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:dropSessionDidExit:)",
        "doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:dropSessionDidUpdate:)",
        "doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:dropSessionDidEnd:)"
      ],
      "title": "Handling drop session notifications"
    },
    {
      "anchor": "Handling-drop-activity-notifications",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:willPerformDrop:)"
      ],
      "title": "Handling drop activity notifications"
    },
    {
      "anchor": "Providing-a-custom-preview-for-a-drop-activity",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:previewForDroppingAllItemsWithDefault:)"
      ],
      "title": "Providing a custom preview for a drop activity"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UITextDropDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextDropDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextDropDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Accepting-a-drop-activity",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:proposalForDrop:)",
                "doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:willBecomeEditableForDrop:)"
              ],
              "title": "Accepting a drop activity"
            },
            {
              "anchor": "Handling-drop-session-notifications",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:dropSessionDidEnter:)",
                "doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:dropSessionDidExit:)",
                "doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:dropSessionDidUpdate:)",
                "doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:dropSessionDidEnd:)"
              ],
              "title": "Handling drop session notifications"
            },
            {
              "anchor": "Handling-drop-activity-notifications",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:willPerformDrop:)"
              ],
              "title": "Handling drop activity notifications"
            },
            {
              "anchor": "Providing-a-custom-preview-for-a-drop-activity",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate/textDroppableView(_:previewForDroppingAllItemsWithDefault:)"
              ],
              "title": "Providing a custom preview for a drop activity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Text-view-additions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate",
                "doc://com.apple.uikit/documentation/UIKit/UITextDraggable",
                "doc://com.apple.uikit/documentation/UIKit/UITextDragOptions",
                "doc://com.apple.uikit/documentation/UIKit/UITextDroppable",
                "doc://com.apple.uikit/documentation/UIKit/UITextDropEditability"
              ],
              "title": "Text view additions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UITextDropDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropDelegate/title",
          "value": "UITextDropDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextDropDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextDropDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDraggable/title",
          "value": "UITextDraggable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDraggable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextDraggable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDraggable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextDraggable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDroppable/title",
          "value": "UITextDroppable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDroppable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextDroppable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDroppable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextDroppable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropDelegate~1textDroppableView(_:dropSessionDidExit:)/title",
          "value": "textDroppableView:dropSessionDidExit:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropDelegate~1textDroppableView(_:dropSessionDidExit:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textDroppableView:dropSessionDidExit:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropDelegate~1textDroppableView(_:dropSessionDidEnter:)/title",
          "value": "textDroppableView:dropSessionDidEnter:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropDelegate~1textDroppableView(_:dropSessionDidEnter:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textDroppableView:dropSessionDidEnter:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropDelegate~1textDroppableView(_:dropSessionDidUpdate:)/title",
          "value": "textDroppableView:dropSessionDidUpdate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropDelegate~1textDroppableView(_:dropSessionDidUpdate:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textDroppableView:dropSessionDidUpdate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropDelegate~1textDroppableView(_:previewForDroppingAllItemsWithDefault:)/title",
          "value": "textDroppableView:previewForDroppingAllItemsWithDefault:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropDelegate~1textDroppableView(_:previewForDroppingAllItemsWithDefault:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textDroppableView:previewForDroppingAllItemsWithDefault:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragOptions/title",
          "value": "UITextDragOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextDragOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextDragOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragDelegate/title",
          "value": "UITextDragDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextDragDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextDragDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropDelegate~1textDroppableView(_:willBecomeEditableForDrop:)/title",
          "value": "textDroppableView:willBecomeEditableForDrop:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropDelegate~1textDroppableView(_:willBecomeEditableForDrop:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textDroppableView:willBecomeEditableForDrop:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropDelegate~1textDroppableView(_:dropSessionDidEnd:)/title",
          "value": "textDroppableView:dropSessionDidEnd:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropDelegate~1textDroppableView(_:dropSessionDidEnd:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textDroppableView:dropSessionDidEnd:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropEditability/title",
          "value": "UITextDropEditability"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropEditability/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextDropEditability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropEditability/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextDropEditability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropDelegate~1textDroppableView(_:willPerformDrop:)/title",
          "value": "textDroppableView:willPerformDrop:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropDelegate~1textDroppableView(_:willPerformDrop:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textDroppableView:willPerformDrop:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropDelegate~1textDroppableView(_:proposalForDrop:)/title",
          "value": "textDroppableView:proposalForDrop:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropDelegate~1textDroppableView(_:proposalForDrop:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textDroppableView:proposalForDrop:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitextdropdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uitextdropdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
