{
  "abstract": [
    {
      "text": "The methods you use on a find session’s searchable objects to perform search operations and decorate the found text results.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UITextSearching",
    "fragments": [
      {
        "kind": "identifier",
        "text": "UITextSearching"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UITextSearching"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "UITextSearching"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UITextSearching"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Implement this protocol on the class that encapsulates the searchable content for your view. This allows you to use an instance of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchingFindSession",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to manage the session for a find interaction.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFindInteraction": {
      "abstract": [
        {
          "text": "An interaction that provides text finding and replacing operations using a system find panel.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFindInteraction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFindInteraction"
        }
      ],
      "role": "symbol",
      "title": "UIFindInteraction",
      "type": "topic",
      "url": "/documentation/uikit/uifindinteraction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFindInteractionDelegate": {
      "abstract": [
        {
          "text": "A delegate object that provides a session object to manage the search state for a find interaction and receives notifications of search session lifetimes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFindInteractionDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindInteractionDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFindInteractionDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIFindInteractionDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uifindinteractiondelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFindSession": {
      "abstract": [
        {
          "text": "An abstract base class that manages the state, presentation, and behavior for a search that the find interaction initiates.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFindSession"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIFindSession"
        }
      ],
      "role": "symbol",
      "title": "UIFindSession",
      "type": "topic",
      "url": "/documentation/uikit/uifindsession"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIFindSession/SearchResultDisplayStyle-swift.enum": {
      "abstract": [
        {
          "text": "Constants that describe the results summary the find panel UI includes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SearchResultDisplayStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIFindSession/SearchResultDisplayStyle-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SearchResultDisplayStyle"
        }
      ],
      "role": "symbol",
      "title": "UIFindSession.SearchResultDisplayStyle",
      "type": "topic",
      "url": "/documentation/uikit/uifindsession/searchresultdisplaystyle-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-c.protocol": {
      "abstract": [
        {
          "text": "The methods you use on a find session’s aggregator to collect matching text ranges for a search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextSearchAggregator"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-c.protocol",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextSearchAggregator",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchaggregator-c.protocol"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchDocumentIdentifier": {
      "abstract": [
        {
          "text": "A string that uniquely identifies a specific document when searching for matching text across multiple documents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextSearchDocumentIdentifier"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchDocumentIdentifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextSearchDocumentIdentifier",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchdocumentidentifier"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchFoundTextStyle": {
      "abstract": [
        {
          "text": "Constants that describe the style a find session uses to decorate the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextSearchFoundTextStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchFoundTextStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextSearchFoundTextStyle"
        }
      ],
      "role": "symbol",
      "title": "UITextSearchFoundTextStyle",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchfoundtextstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions": {
      "abstract": [
        {
          "text": "An object containing the configurable options for a text search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextSearchOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextSearchOptions"
        }
      ],
      "role": "symbol",
      "title": "UITextSearchOptions",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum": {
      "abstract": [
        {
          "text": "Constants that describe the method to use when searching text for words that match a string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "WordMatchMethod"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "WordMatchMethod"
        }
      ],
      "role": "symbol",
      "title": "UITextSearchOptions.WordMatchMethod",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchoptions/wordmatchmethod-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq": {
      "abstract": [
        {
          "text": "The methods you use on a find session’s searchable objects to perform search operations and decorate the found text results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextSearching"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextSearching",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearching-53wjq"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/clearAllDecoratedFoundText": {
      "abstract": [
        {
          "text": "Clears the style from all found and highlighted results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "clearAllDecoratedFoundText"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/clearAllDecoratedFoundText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clearAllDecoratedFoundText"
        }
      ],
      "role": "symbol",
      "title": "clearAllDecoratedFoundText",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearching-53wjq/clearalldecoratedfoundtext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/compareFoundRange:toRange:inDocument:": {
      "abstract": [
        {
          "text": "Compares ranges from the set of matches the aggregator provides to determine navigation order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "compareFoundRange:toRange:inDocument:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/compareFoundRange:toRange:inDocument:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "compareFoundRange:toRange:inDocument:"
        }
      ],
      "role": "symbol",
      "title": "compareFoundRange:toRange:inDocument:",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearching-53wjq/comparefoundrange:torange:indocument:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/compareOrderFromDocument:toDocument:": {
      "abstract": [
        {
          "text": "Compares documents containing matching ranges from the set the aggregator provides to determine navigation order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "compareOrderFromDocument:toDocument:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/compareOrderFromDocument:toDocument:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "compareOrderFromDocument:toDocument:"
        }
      ],
      "role": "symbol",
      "title": "compareOrderFromDocument:toDocument:",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearching-53wjq/compareorderfromdocument:todocument:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/decorateFoundTextRange:inDocument:usingStyle:": {
      "abstract": [
        {
          "text": "Applies the style to a specific text range to indicate found and highlighted results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "decorateFoundTextRange:inDocument:usingStyle:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/decorateFoundTextRange:inDocument:usingStyle:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "decorateFoundTextRange:inDocument:usingStyle:"
        }
      ],
      "role": "symbol",
      "title": "decorateFoundTextRange:inDocument:usingStyle:",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearching-53wjq/decoratefoundtextrange:indocument:usingstyle:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/performTextSearchWithQueryString:usingOptions:resultAggregator:": {
      "abstract": [
        {
          "text": "Searches for ranges of text matching the string across all searchable documents and collects results in the aggregator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "performTextSearchWithQueryString:usingOptions:resultAggregator:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/performTextSearchWithQueryString:usingOptions:resultAggregator:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "performTextSearchWithQueryString:usingOptions:resultAggregator:"
        }
      ],
      "role": "symbol",
      "title": "performTextSearchWithQueryString:usingOptions:resultAggregator:",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearching-53wjq/performtextsearchwithquerystring:usingoptions:resultaggregator:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/replaceAllOccurrencesOfQueryString:usingOptions:withText:": {
      "abstract": [
        {
          "text": "Informs the searchable object to replace all matching text across all searchable documents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "replaceAllOccurrencesOfQueryString:usingOptions:withText:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/replaceAllOccurrencesOfQueryString:usingOptions:withText:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "replaceAllOccurrencesOfQueryString:usingOptions:withText:"
        }
      ],
      "role": "symbol",
      "title": "replaceAllOccurrencesOfQueryString:usingOptions:withText:",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearching-53wjq/replacealloccurrencesofquerystring:usingoptions:withtext:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/replaceFoundTextInRange:inDocument:withText:": {
      "abstract": [
        {
          "text": "Informs the searchable object to replace the text range for the highlighted search result.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "replaceFoundTextInRange:inDocument:withText:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/replaceFoundTextInRange:inDocument:withText:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "replaceFoundTextInRange:inDocument:withText:"
        }
      ],
      "role": "symbol",
      "title": "replaceFoundTextInRange:inDocument:withText:",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearching-53wjq/replacefoundtextinrange:indocument:withtext:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/scrollRangeToVisible:inDocument:": {
      "abstract": [
        {
          "text": "Scrolls to the containing view to make the text range visible.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "scrollRangeToVisible:inDocument:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/scrollRangeToVisible:inDocument:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "scrollRangeToVisible:inDocument:"
        }
      ],
      "role": "symbol",
      "title": "scrollRangeToVisible:inDocument:",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearching-53wjq/scrollrangetovisible:indocument:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/selectedTextRange": {
      "abstract": [
        {
          "text": "The range of selected text in a document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "selectedTextRange"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/selectedTextRange",
      "kind": "symbol",
      "role": "symbol",
      "title": "selectedTextRange",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearching-53wjq/selectedtextrange"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/selectedTextSearchDocument": {
      "abstract": [
        {
          "text": "The object that uniquely identifies the specific document with selected text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "selectedTextSearchDocument"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/selectedTextSearchDocument",
      "kind": "symbol",
      "role": "symbol",
      "title": "selectedTextSearchDocument",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearching-53wjq/selectedtextsearchdocument"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/shouldReplaceFoundTextInRange:inDocument:withText:": {
      "abstract": [
        {
          "text": "Determines whether the searchable object allows replacement of the text range you provide.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "shouldReplaceFoundTextInRange:inDocument:withText:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/shouldReplaceFoundTextInRange:inDocument:withText:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shouldReplaceFoundTextInRange:inDocument:withText:"
        }
      ],
      "role": "symbol",
      "title": "shouldReplaceFoundTextInRange:inDocument:withText:",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearching-53wjq/shouldreplacefoundtextinrange:indocument:withtext:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/supportsTextReplacement": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the searchable object supports replacing text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "supportsTextReplacement"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/supportsTextReplacement",
      "kind": "symbol",
      "role": "symbol",
      "title": "supportsTextReplacement",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearching-53wjq/supportstextreplacement"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/willHighlightFoundTextRange:inDocument:": {
      "abstract": [
        {
          "text": "Informs the searchable object when the highlighted search result is about to change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "willHighlightFoundTextRange:inDocument:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/willHighlightFoundTextRange:inDocument:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "willHighlightFoundTextRange:inDocument:"
        }
      ],
      "role": "symbol",
      "title": "willHighlightFoundTextRange:inDocument:",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearching-53wjq/willhighlightfoundtextrange:indocument:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchingFindSession": {
      "abstract": [
        {
          "text": "A find session object that wraps a searchable object implementing the text-searching protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextSearchingFindSession"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchingFindSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextSearchingFindSession"
        }
      ],
      "role": "symbol",
      "title": "UITextSearchingFindSession",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchingfindsession"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextView": {
      "abstract": [
        {
          "text": "A scrollable, multiline text region.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextView"
        }
      ],
      "role": "symbol",
      "title": "UITextView",
      "type": "topic",
      "url": "/documentation/uikit/uitextview"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextView"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Find-and-replace",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIFindInteraction",
        "doc://com.apple.uikit/documentation/UIKit/UIFindInteractionDelegate",
        "doc://com.apple.uikit/documentation/UIKit/UIFindSession",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchingFindSession",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchFoundTextStyle",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchOptions/WordMatchMethod-swift.enum",
        "doc://com.apple.uikit/documentation/UIKit/UIFindSession/SearchResultDisplayStyle-swift.enum"
      ],
      "title": "Find and replace"
    }
  ],
  "topicSections": [
    {
      "anchor": "Handling-searches",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/performTextSearchWithQueryString:usingOptions:resultAggregator:",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-c.protocol",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/compareFoundRange:toRange:inDocument:",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/compareOrderFromDocument:toDocument:",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchDocumentIdentifier"
      ],
      "title": "Handling searches"
    },
    {
      "anchor": "Displaying-results",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/decorateFoundTextRange:inDocument:usingStyle:",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/clearAllDecoratedFoundText",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/willHighlightFoundTextRange:inDocument:",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/scrollRangeToVisible:inDocument:"
      ],
      "title": "Displaying results"
    },
    {
      "anchor": "Identifying-selected-text",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/selectedTextRange",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/selectedTextSearchDocument"
      ],
      "title": "Identifying selected text"
    },
    {
      "anchor": "Handling-replacements",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/supportsTextReplacement",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/replaceFoundTextInRange:inDocument:withText:",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/replaceAllOccurrencesOfQueryString:usingOptions:withText:",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/shouldReplaceFoundTextInRange:inDocument:withText:"
      ],
      "title": "Handling replacements"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindInteraction/title",
          "value": "UIFindInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1SearchResultDisplayStyle-swift.enum/title",
          "value": "UIFindSessionSearchResultDisplayStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1SearchResultDisplayStyle-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindSessionSearchResultDisplayStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession~1SearchResultDisplayStyle-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindSessionSearchResultDisplayStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions/title",
          "value": "UITextSearchOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextView/title",
          "value": "UITextView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchFoundTextStyle/title",
          "value": "UITextSearchFoundTextStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchFoundTextStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchFoundTextStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchFoundTextStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchFoundTextStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchingFindSession/title",
          "value": "UITextSearchingFindSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchingFindSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchingFindSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchingFindSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchingFindSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions~1WordMatchMethod-swift.enum/title",
          "value": "UITextSearchMatchMethod"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions~1WordMatchMethod-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchMatchMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchOptions~1WordMatchMethod-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchMatchMethod"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession/title",
          "value": "UIFindSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindInteractionDelegate/title",
          "value": "UIFindInteractionDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindInteractionDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindInteractionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIFindInteractionDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIFindInteractionDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitextsearching-53wjq"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
