{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UITextFormattingViewControllerFormattingDescriptor",
    "fragments": [
      {
        "kind": "identifier",
        "text": "UITextFormattingViewControllerFormattingDescriptor"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UITextFormattingViewControllerFormattingDescriptor"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "UITextFormattingViewControllerFormattingDescriptor"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerFormattingDescriptor"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/Component": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Component"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/Component",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Component"
        }
      ],
      "role": "symbol",
      "title": "UITextFormattingViewController.Component",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/component"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentGroup": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ComponentGroup"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ComponentGroup"
        }
      ],
      "role": "symbol",
      "title": "UITextFormattingViewController.ComponentGroup",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/componentgroup"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/Configuration-swift.class": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Configuration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/Configuration-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Configuration"
        }
      ],
      "role": "symbol",
      "title": "UITextFormattingViewController.Configuration",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontroller/configuration-swift.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerChangeValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextFormattingViewControllerChangeValue"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerChangeValue",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextFormattingViewControllerChangeValue",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontrollerchangevalue"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextFormattingViewControllerFormattingDescriptor"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextFormattingViewControllerFormattingDescriptor",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontrollerformattingdescriptor"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor/fonts": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "fonts"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor/fonts",
      "kind": "symbol",
      "role": "symbol",
      "title": "fonts",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontrollerformattingdescriptor/fonts"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor/formattingStyleKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "formattingStyleKey"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor/formattingStyleKey",
      "kind": "symbol",
      "role": "symbol",
      "title": "formattingStyleKey",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontrollerformattingdescriptor/formattingstylekey"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor/highlights": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "highlights"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor/highlights",
      "kind": "symbol",
      "role": "symbol",
      "title": "highlights",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontrollerformattingdescriptor/highlights"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor/init": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor/init",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontrollerformattingdescriptor/init"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor/initWithAttributes:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithAttributes:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor/initWithAttributes:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithAttributes:"
        }
      ],
      "role": "symbol",
      "title": "initWithAttributes:",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontrollerformattingdescriptor/initwithattributes:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor/initWithString:range:": {
      "abstract": [],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithString:range:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor/initWithString:range:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithString:range:"
        }
      ],
      "role": "symbol",
      "title": "initWithString:range:",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontrollerformattingdescriptor/initwithstring:range:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor/lineHeight": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "lineHeight"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor/lineHeight",
      "kind": "symbol",
      "role": "symbol",
      "title": "lineHeight",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontrollerformattingdescriptor/lineheight"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor/strikethroughPresent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "strikethroughPresent"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor/strikethroughPresent",
      "kind": "symbol",
      "role": "symbol",
      "title": "strikethroughPresent",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontrollerformattingdescriptor/strikethroughpresent"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor/textAlignments": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "textAlignments"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor/textAlignments",
      "kind": "symbol",
      "role": "symbol",
      "title": "textAlignments",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontrollerformattingdescriptor/textalignments"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor/textColors": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "textColors"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor/textColors",
      "kind": "symbol",
      "role": "symbol",
      "title": "textColors",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontrollerformattingdescriptor/textcolors"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor/textLists": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "textLists"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor/textLists",
      "kind": "symbol",
      "role": "symbol",
      "title": "textLists",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontrollerformattingdescriptor/textlists"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor/underlinePresent": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "underlinePresent"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor/underlinePresent",
      "kind": "symbol",
      "role": "symbol",
      "title": "underlinePresent",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontrollerformattingdescriptor/underlinepresent"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingStyle": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextFormattingViewControllerFormattingStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextFormattingViewControllerFormattingStyle",
      "type": "topic",
      "url": "/documentation/uikit/uitextformattingviewcontrollerformattingstyle"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Classes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/Component",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/ComponentGroup",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewController/Configuration-swift.class",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerChangeValue",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingStyle"
      ],
      "title": "Classes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor/fonts",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor/formattingStyleKey",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor/highlights",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor/lineHeight",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor/strikethroughPresent",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor/textAlignments",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor/textColors",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor/textLists",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor/underlinePresent"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor/init",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor/initWithAttributes:",
        "doc://com.apple.uikit/documentation/UIKit/UITextFormattingViewControllerFormattingDescriptor/initWithString:range:"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentGroup/title",
          "value": "UITextFormattingViewControllerComponentGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerComponentGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1ComponentGroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerComponentGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1Component/title",
          "value": "UITextFormattingViewControllerComponent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1Component/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerComponent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1Component/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerComponent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1Configuration-swift.class/title",
          "value": "UITextFormattingViewControllerConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1Configuration-swift.class/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextFormattingViewController~1Configuration-swift.class/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextFormattingViewControllerConfiguration"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitextformattingviewcontrollerformattingdescriptor"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
