{
  "abstract": [
    {
      "text": "An object that provides textual context to a custom keyboard.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITextDocumentProxy"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UITextDocumentProxy",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UITextDocumentProxy"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UITextDocumentProxy"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "UITextDocumentProxy"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UITextDocumentProxy"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyInput",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)UIKeyInput",
              "text": "UIKeyInput"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "mentions",
      "mentions": [
        "doc://com.apple.uikit/documentation/UIKit/handling-text-interactions-in-custom-keyboards"
      ]
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Through conformance to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyInput",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol, a text document proxy enables a custom keyboard (which is based on the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIInputViewController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class) to insert and delete text, to adjust the position of the insertion point, and to determine whether a text input object is empty. The text document proxy uses the keyboard’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIInputViewController/textDocumentProxy",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to do this.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more about using a text document proxy, see ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIInputViewController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/creating-a-custom-keyboard",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIInputViewAudioFeedback": {
      "abstract": [
        {
          "text": "A property that enables a custom input or keyboard accessory view to play standard keyboard input clicks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIInputViewAudioFeedback"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIInputViewAudioFeedback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIInputViewAudioFeedback"
        }
      ],
      "role": "symbol",
      "title": "UIInputViewAudioFeedback",
      "type": "topic",
      "url": "/documentation/uikit/uiinputviewaudiofeedback"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIInputViewController": {
      "abstract": [
        {
          "text": "The primary view controller for a custom keyboard app extension.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIInputViewController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIInputViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIInputViewController"
        }
      ],
      "role": "symbol",
      "title": "UIInputViewController",
      "type": "topic",
      "url": "/documentation/uikit/uiinputviewcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIInputViewController/textDocumentProxy": {
      "abstract": [
        {
          "text": "A proxy to the text input object that the custom keyboard is interacting with.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textDocumentProxy"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITextDocumentProxy",
          "text": "UITextDocumentProxy"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIInputViewController/textDocumentProxy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textDocumentProxy"
        }
      ],
      "role": "symbol",
      "title": "textDocumentProxy",
      "type": "topic",
      "url": "/documentation/uikit/uiinputviewcontroller/textdocumentproxy"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIKeyInput": {
      "abstract": [
        {
          "text": "A set of methods a responder uses to implement simple text entry.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIKeyInput"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIKeyInput"
        }
      ],
      "role": "symbol",
      "title": "UIKeyInput",
      "type": "topic",
      "url": "/documentation/uikit/uikeyinput"
    },
    "doc://com.apple.uikit/documentation/UIKit/UILexicon": {
      "abstract": [
        {
          "text": "A read-only array of term pairs, each in a lexicon entry object, for a custom keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UILexicon"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UILexicon",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILexicon"
        }
      ],
      "role": "symbol",
      "title": "UILexicon",
      "type": "topic",
      "url": "/documentation/uikit/uilexicon"
    },
    "doc://com.apple.uikit/documentation/UIKit/UILexiconEntry": {
      "abstract": [
        {
          "text": "A read-only term pair, available within a lexicon object, for a custom keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UILexiconEntry"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UILexiconEntry",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILexiconEntry"
        }
      ],
      "role": "symbol",
      "title": "UILexiconEntry",
      "type": "topic",
      "url": "/documentation/uikit/uilexiconentry"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextDocumentProxy": {
      "abstract": [
        {
          "text": "An object that provides textual context to a custom keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextDocumentProxy"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextDocumentProxy",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextDocumentProxy"
        }
      ],
      "role": "symbol",
      "title": "UITextDocumentProxy",
      "type": "topic",
      "url": "/documentation/uikit/uitextdocumentproxy"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextDocumentProxy/adjustTextPosition(byCharacterOffset:)": {
      "abstract": [
        {
          "text": "Moves the insertion point forward or backward in the current text input object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adjustTextPosition"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "byCharacterOffset"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextDocumentProxy/adjustTextPosition(byCharacterOffset:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "adjustTextPositionByCharacterOffset:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "adjustTextPosition(byCharacterOffset:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextdocumentproxy/adjusttextposition(bycharacteroffset:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextDocumentProxy/documentContextAfterInput": {
      "abstract": [
        {
          "text": "Textual context after the insertion point in the current text input object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentContextAfterInput"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextDocumentProxy/documentContextAfterInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentContextAfterInput"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "documentContextAfterInput",
      "type": "topic",
      "url": "/documentation/uikit/uitextdocumentproxy/documentcontextafterinput"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextDocumentProxy/documentContextBeforeInput": {
      "abstract": [
        {
          "text": "Textual context before the insertion point in the current text input object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentContextBeforeInput"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextDocumentProxy/documentContextBeforeInput",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentContextBeforeInput"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "documentContextBeforeInput",
      "type": "topic",
      "url": "/documentation/uikit/uitextdocumentproxy/documentcontextbeforeinput"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextDocumentProxy/documentIdentifier": {
      "abstract": [
        {
          "text": "The unique identifier for the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4UUIDV",
          "text": "UUID"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextDocumentProxy/documentIdentifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentIdentifier"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "documentIdentifier",
      "type": "topic",
      "url": "/documentation/uikit/uitextdocumentproxy/documentidentifier"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextDocumentProxy/documentInputMode": {
      "abstract": [
        {
          "text": "The text-input mode for the keyboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "documentInputMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextInputMode",
          "text": "UITextInputMode"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextDocumentProxy/documentInputMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "documentInputMode"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "documentInputMode",
      "type": "topic",
      "url": "/documentation/uikit/uitextdocumentproxy/documentinputmode"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextDocumentProxy/selectedText": {
      "abstract": [
        {
          "text": "The currently selected text in the document.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "selectedText"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextDocumentProxy/selectedText",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "selectedText"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "selectedText",
      "type": "topic",
      "url": "/documentation/uikit/uitextdocumentproxy/selectedtext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextDocumentProxy/setMarkedText(_:selectedRange:)": {
      "abstract": [
        {
          "text": "Inserts the provided text and marks it to indicate that it’s part of an active input session.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setMarkedText"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "selectedRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextDocumentProxy/setMarkedText(_:selectedRange:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setMarkedText:selectedRange:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "setMarkedText(_:selectedRange:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextdocumentproxy/setmarkedtext(_:selectedrange:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextDocumentProxy/unmarkText()": {
      "abstract": [
        {
          "text": "Unmarks the currently marked text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unmarkText"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextDocumentProxy/unmarkText()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unmarkText"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "unmarkText()",
      "type": "topic",
      "url": "/documentation/uikit/uitextdocumentproxy/unmarktext()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextInputTraits": {
      "abstract": [
        {
          "text": "A set of methods that defines features for keyboard input to a text object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextInputTraits"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextInputTraits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextInputTraits"
        }
      ],
      "role": "symbol",
      "title": "UITextInputTraits",
      "type": "topic",
      "url": "/documentation/uikit/uitextinputtraits"
    },
    "doc://com.apple.uikit/documentation/UIKit/creating-a-custom-keyboard": {
      "abstract": [
        {
          "text": "Add an extension to your Xcode project to provide systemwide customized text input.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/creating-a-custom-keyboard",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Creating a custom keyboard",
      "type": "topic",
      "url": "/documentation/uikit/creating-a-custom-keyboard"
    },
    "doc://com.apple.uikit/documentation/UIKit/handling-text-interactions-in-custom-keyboards": {
      "abstract": [
        {
          "text": "Insert, delete, and manipulate text by using a proxy to a text input view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/handling-text-interactions-in-custom-keyboards",
      "kind": "article",
      "role": "article",
      "title": "Handling text interactions in custom keyboards",
      "type": "topic",
      "url": "/documentation/uikit/handling-text-interactions-in-custom-keyboards"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.apple.uikit/documentation/UIKit/UIKeyInput",
        "doc://com.apple.uikit/documentation/UIKit/UITextInputTraits"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Custom-keyboard",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIInputViewAudioFeedback",
        "doc://com.apple.uikit/documentation/UIKit/UIInputViewController",
        "doc://com.apple.uikit/documentation/UIKit/UILexicon",
        "doc://com.apple.uikit/documentation/UIKit/UILexiconEntry"
      ],
      "title": "Custom keyboard"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-text-input-mode",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextDocumentProxy/documentInputMode"
      ],
      "title": "Getting the text-input mode"
    },
    {
      "anchor": "Obtaining-textual-context-around-the-insertion-point",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextDocumentProxy/documentContextAfterInput",
        "doc://com.apple.uikit/documentation/UIKit/UITextDocumentProxy/documentContextBeforeInput"
      ],
      "title": "Obtaining textual context around the insertion point"
    },
    {
      "anchor": "Adjusting-the-insertion-point-position",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextDocumentProxy/adjustTextPosition(byCharacterOffset:)"
      ],
      "title": "Adjusting the insertion point position"
    },
    {
      "anchor": "Getting-the-selected-text",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextDocumentProxy/selectedText"
      ],
      "title": "Getting the selected text"
    },
    {
      "anchor": "Managing-marked-text",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextDocumentProxy/setMarkedText(_:selectedRange:)",
        "doc://com.apple.uikit/documentation/UIKit/UITextDocumentProxy/unmarkText()"
      ],
      "title": "Managing marked text"
    },
    {
      "anchor": "Distinguishing-changes-in-the-document",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextDocumentProxy/documentIdentifier"
      ],
      "title": "Distinguishing changes in the document"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UITextDocumentProxy"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextDocumentProxy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextDocumentProxy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-the-text-input-mode",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextDocumentProxy/documentInputMode"
              ],
              "title": "Getting the text-input mode"
            },
            {
              "anchor": "Obtaining-textual-context-around-the-insertion-point",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextDocumentProxy/documentContextAfterInput",
                "doc://com.apple.uikit/documentation/UIKit/UITextDocumentProxy/documentContextBeforeInput"
              ],
              "title": "Obtaining textual context around the insertion point"
            },
            {
              "anchor": "Adjusting-the-insertion-point-position",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextDocumentProxy/adjustTextPosition(byCharacterOffset:)"
              ],
              "title": "Adjusting the insertion point position"
            },
            {
              "anchor": "Getting-the-selected-text",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextDocumentProxy/selectedText"
              ],
              "title": "Getting the selected text"
            },
            {
              "anchor": "Managing-marked-text",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextDocumentProxy/setMarkedText(_:selectedRange:)",
                "doc://com.apple.uikit/documentation/UIKit/UITextDocumentProxy/unmarkText()"
              ],
              "title": "Managing marked text"
            },
            {
              "anchor": "Distinguishing-changes-in-the-document",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextDocumentProxy/documentIdentifier"
              ],
              "title": "Distinguishing changes in the document"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIKeyInput"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Custom-keyboard",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIInputViewAudioFeedback",
                "doc://com.apple.uikit/documentation/UIKit/UIInputViewController",
                "doc://com.apple.uikit/documentation/UIKit/UILexicon",
                "doc://com.apple.uikit/documentation/UIKit/UILexiconEntry"
              ],
              "title": "Custom keyboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UITextDocumentProxy"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIKeyInput",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)UIKeyInput",
                    "text": "UIKeyInput"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILexicon/title",
          "value": "UILexicon"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILexicon/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UILexicon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILexicon/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILexicon"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDocumentProxy~1adjustTextPosition(byCharacterOffset:)/title",
          "value": "adjustTextPositionByCharacterOffset:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDocumentProxy~1adjustTextPosition(byCharacterOffset:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "adjustTextPositionByCharacterOffset:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInputViewController~1textDocumentProxy/title",
          "value": "textDocumentProxy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInputViewController~1textDocumentProxy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "textDocumentProxy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyInput/title",
          "value": "UIKeyInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyInput/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIKeyInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDocumentProxy~1documentInputMode/title",
          "value": "documentInputMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDocumentProxy~1documentInputMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "documentInputMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputTraits/title",
          "value": "UITextInputTraits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputTraits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextInputTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputTraits/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextInputTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDocumentProxy~1unmarkText()/title",
          "value": "unmarkText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDocumentProxy~1unmarkText()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "unmarkText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDocumentProxy~1selectedText/title",
          "value": "selectedText"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDocumentProxy~1selectedText/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "selectedText"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILexiconEntry/title",
          "value": "UILexiconEntry"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILexiconEntry/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UILexiconEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILexiconEntry/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILexiconEntry"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDocumentProxy~1documentContextAfterInput/title",
          "value": "documentContextAfterInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDocumentProxy~1documentContextAfterInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "documentContextAfterInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInputViewAudioFeedback/title",
          "value": "UIInputViewAudioFeedback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInputViewAudioFeedback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIInputViewAudioFeedback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInputViewAudioFeedback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIInputViewAudioFeedback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDocumentProxy~1documentIdentifier/title",
          "value": "documentIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDocumentProxy~1documentIdentifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "documentIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDocumentProxy~1setMarkedText(_:selectedRange:)/title",
          "value": "setMarkedText:selectedRange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDocumentProxy~1setMarkedText(_:selectedRange:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setMarkedText:selectedRange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDocumentProxy~1documentContextBeforeInput/title",
          "value": "documentContextBeforeInput"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDocumentProxy~1documentContextBeforeInput/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "documentContextBeforeInput"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDocumentProxy/title",
          "value": "UITextDocumentProxy"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDocumentProxy/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextDocumentProxy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDocumentProxy/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextDocumentProxy"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInputViewController/title",
          "value": "UIInputViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInputViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIInputViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIInputViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIInputViewController"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitextdocumentproxy"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uitextdocumentproxy"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
