{
  "abstract": [
    {
      "text": "The methods for receiving editing-related messages for text view objects.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UITextViewDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UITextViewDelegate"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UITextViewDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "UITextViewDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UITextViewDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)UIScrollViewDelegate",
              "text": "UIScrollViewDelegate"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "All of the methods in this protocol are optional. You can use them in situations where you might want to adjust the text a user is editing (such as in the case of a spell-checker program) or to modify the intended insertion point.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate": {
      "abstract": [
        {
          "text": "The interface for the delegate of a scroll view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIScrollViewDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIScrollViewDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIScrollViewDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uiscrollviewdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextItem": {
      "abstract": [
        {
          "text": "An object for attaching custom actions and menus to links, text attachments, or other specific text in a text view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextItem"
        }
      ],
      "role": "symbol",
      "title": "UITextItem",
      "type": "topic",
      "url": "/documentation/uikit/uitextitem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextItem/MenuConfiguration": {
      "abstract": [
        {
          "text": "An object that describes what type of menu and preview to show for a text item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MenuConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextItem/MenuConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MenuConfiguration"
        }
      ],
      "role": "symbol",
      "title": "UITextItem.MenuConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uitextitem/menuconfiguration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextItemContentType": {
      "abstract": [
        {
          "text": "Constants that describe and capture the type of content a text item represents along with a specific related value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextItemContentType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextItemContentType",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextItemContentType",
      "type": "topic",
      "url": "/documentation/uikit/uitextitemcontenttype"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextItemInteraction": {
      "abstract": [
        {
          "text": "Constants that indicate the type of interaction the user expects to have with a URL or text attachment.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextItemInteraction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextItemInteraction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextItemInteraction"
        }
      ],
      "role": "symbol",
      "title": "UITextItemInteraction",
      "type": "topic",
      "url": "/documentation/uikit/uitextiteminteraction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate": {
      "abstract": [
        {
          "text": "The methods for receiving editing-related messages for text view objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextViewDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextViewDelegate"
        }
      ],
      "role": "symbol",
      "title": "UITextViewDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uitextviewdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:didBeginFormattingWith:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextView",
          "text": "UITextView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didBeginFormattingWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextFormattingViewController",
          "text": "UITextFormattingViewController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:didBeginFormattingWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textView:didBeginFormattingWithViewController:"
        }
      ],
      "role": "symbol",
      "title": "textView(_:didBeginFormattingWith:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextviewdelegate/textview(_:didbeginformattingwith:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:didEndFormattingWith:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextView",
          "text": "UITextView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "didEndFormattingWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextFormattingViewController",
          "text": "UITextFormattingViewController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:didEndFormattingWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textView:didEndFormattingWithViewController:"
        }
      ],
      "role": "symbol",
      "title": "textView(_:didEndFormattingWith:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextviewdelegate/textview(_:didendformattingwith:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:editMenuForTextIn:suggestedActions:)": {
      "abstract": [
        {
          "text": "Asks the delegate for the menu to display in the text view, based on the text range and actions the system provides.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextView",
          "text": "UITextView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "editMenuForTextIn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "suggestedActions"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIMenuElement",
          "text": "UIMenuElement"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIMenu",
          "text": "UIMenu"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:editMenuForTextIn:suggestedActions:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textView:editMenuForTextInRange:suggestedActions:"
        }
      ],
      "role": "symbol",
      "title": "textView(_:editMenuForTextIn:suggestedActions:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextviewdelegate/textview(_:editmenufortextin:suggestedactions:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:insertInputSuggestion:)": {
      "abstract": [
        {
          "text": "Tells the delegate when the keyboard delivers an input suggestion.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextView",
          "text": "UITextView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "insertInputSuggestion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIInputSuggestion",
          "text": "UIInputSuggestion"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:insertInputSuggestion:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textView:insertInputSuggestion:"
        }
      ],
      "role": "symbol",
      "title": "textView(_:insertInputSuggestion:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextviewdelegate/textview(_:insertinputsuggestion:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:menuConfigurationFor:defaultMenu:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextView",
          "text": "UITextView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "menuConfigurationFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextItem",
          "text": "UITextItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "defaultMenu"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIMenu",
          "text": "UIMenu"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextItem",
          "text": "UITextItem"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextItemMenuConfiguration",
          "text": "MenuConfiguration"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:menuConfigurationFor:defaultMenu:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textView:menuConfigurationForTextItem:defaultMenu:"
        }
      ],
      "role": "symbol",
      "title": "textView(_:menuConfigurationFor:defaultMenu:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextviewdelegate/textview(_:menuconfigurationfor:defaultmenu:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:primaryActionFor:defaultAction:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextView",
          "text": "UITextView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "primaryActionFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextItem",
          "text": "UITextItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "defaultAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIAction",
          "text": "UIAction"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIAction",
          "text": "UIAction"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:primaryActionFor:defaultAction:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textView:primaryActionForTextItem:defaultAction:"
        }
      ],
      "role": "symbol",
      "title": "textView(_:primaryActionFor:defaultAction:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextviewdelegate/textview(_:primaryactionfor:defaultaction:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:shouldChangeTextIn:replacementText:)": {
      "abstract": [
        {
          "text": "Asks the delegate whether to replace the specified text in the text view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextView",
          "text": "UITextView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shouldChangeTextIn"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "replacementText"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:shouldChangeTextIn:replacementText:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textView:shouldChangeTextInRange:replacementText:"
        }
      ],
      "role": "symbol",
      "title": "textView(_:shouldChangeTextIn:replacementText:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextviewdelegate/textview(_:shouldchangetextin:replacementtext:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:shouldInteractWith:in:)-97zx6": {
      "abstract": [
        {
          "text": "Asks the delegate whether the specified text view allows user interaction with the provided text attachment in the specified range of text.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextView",
          "text": "UITextView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shouldInteractWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextAttachment",
          "text": "NSTextAttachment"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:shouldInteractWith:in:)-97zx6",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textView:shouldInteractWithTextAttachment:inRange:"
        }
      ],
      "role": "symbol",
      "title": "textView(_:shouldInteractWith:in:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextviewdelegate/textview(_:shouldinteractwith:in:)-97zx6"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:shouldInteractWith:in:)-98tho": {
      "abstract": [
        {
          "text": "Asks the delegate whether the specified text view allows user interaction with the specified URL in the specified range of text.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextView",
          "text": "UITextView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shouldInteractWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:shouldInteractWith:in:)-98tho",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textView:shouldInteractWithURL:inRange:"
        }
      ],
      "role": "symbol",
      "title": "textView(_:shouldInteractWith:in:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextviewdelegate/textview(_:shouldinteractwith:in:)-98tho"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:shouldInteractWith:in:interaction:)-5qha9": {
      "abstract": [
        {
          "text": "Asks the delegate whether the specified text view allows the specified type of user interaction with the provided text attachment in the specified range of text.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextView",
          "text": "UITextView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shouldInteractWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSTextAttachment",
          "text": "NSTextAttachment"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "interaction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UITextItemInteraction",
          "text": "UITextItemInteraction"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:shouldInteractWith:in:interaction:)-5qha9",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textView:shouldInteractWithTextAttachment:inRange:interaction:"
        }
      ],
      "role": "symbol",
      "title": "textView(_:shouldInteractWith:in:interaction:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextviewdelegate/textview(_:shouldinteractwith:in:interaction:)-5qha9"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:shouldInteractWith:in:interaction:)-622ub": {
      "abstract": [
        {
          "text": "Asks the delegate whether the specified text view allows the specified type of user interaction with the specified URL in the specified range of text.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextView",
          "text": "UITextView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shouldInteractWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "interaction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UITextItemInteraction",
          "text": "UITextItemInteraction"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:shouldInteractWith:in:interaction:)-622ub",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textView:shouldInteractWithURL:inRange:interaction:"
        }
      ],
      "role": "symbol",
      "title": "textView(_:shouldInteractWith:in:interaction:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextviewdelegate/textview(_:shouldinteractwith:in:interaction:)-622ub"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:textItemMenuWillDisplayFor:animator:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextView",
          "text": "UITextView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "textItemMenuWillDisplayFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextItem",
          "text": "UITextItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "animator"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIContextMenuInteractionAnimating",
          "text": "UIContextMenuInteractionAnimating"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:textItemMenuWillDisplayFor:animator:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textView:textItemMenuWillDisplayForTextItem:animator:"
        }
      ],
      "role": "symbol",
      "title": "textView(_:textItemMenuWillDisplayFor:animator:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextviewdelegate/textview(_:textitemmenuwilldisplayfor:animator:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:textItemMenuWillEndFor:animator:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextView",
          "text": "UITextView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "textItemMenuWillEndFor"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextItem",
          "text": "UITextItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "animator"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIContextMenuInteractionAnimating",
          "text": "UIContextMenuInteractionAnimating"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:textItemMenuWillEndFor:animator:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textView:textItemMenuWillEndForTextItem:animator:"
        }
      ],
      "role": "symbol",
      "title": "textView(_:textItemMenuWillEndFor:animator:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextviewdelegate/textview(_:textitemmenuwillendfor:animator:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:willBeginFormattingWith:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextView",
          "text": "UITextView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willBeginFormattingWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextFormattingViewController",
          "text": "UITextFormattingViewController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:willBeginFormattingWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textView:willBeginFormattingWithViewController:"
        }
      ],
      "role": "symbol",
      "title": "textView(_:willBeginFormattingWith:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextviewdelegate/textview(_:willbeginformattingwith:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:willDismissEditMenuWith:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextView",
          "text": "UITextView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willDismissEditMenuWith"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIEditMenuInteractionAnimating",
          "text": "UIEditMenuInteractionAnimating"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:willDismissEditMenuWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textView:willDismissEditMenuWithAnimator:"
        }
      ],
      "role": "symbol",
      "title": "textView(_:willDismissEditMenuWith:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextviewdelegate/textview(_:willdismisseditmenuwith:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:willEndFormattingWith:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextView",
          "text": "UITextView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willEndFormattingWith"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextFormattingViewController",
          "text": "UITextFormattingViewController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:willEndFormattingWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textView:willEndFormattingWithViewController:"
        }
      ],
      "role": "symbol",
      "title": "textView(_:willEndFormattingWith:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextviewdelegate/textview(_:willendformattingwith:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:willPresentEditMenuWith:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextView",
          "text": "UITextView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willPresentEditMenuWith"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIEditMenuInteractionAnimating",
          "text": "UIEditMenuInteractionAnimating"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:willPresentEditMenuWith:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textView:willPresentEditMenuWithAnimator:"
        }
      ],
      "role": "symbol",
      "title": "textView(_:willPresentEditMenuWith:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextviewdelegate/textview(_:willpresenteditmenuwith:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:writingToolsIgnoredRangesInEnclosingRange:)": {
      "abstract": [
        {
          "text": "Asks the delegate to specify any ranges of text you want the writing tools to ignore.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextView",
          "text": "UITextView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "writingToolsIgnoredRangesInEnclosingRange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "NSRange"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSValue",
          "text": "NSValue"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:writingToolsIgnoredRangesInEnclosingRange:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textView:writingToolsIgnoredRangesInEnclosingRange:"
        }
      ],
      "role": "symbol",
      "title": "textView(_:writingToolsIgnoredRangesInEnclosingRange:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextviewdelegate/textview(_:writingtoolsignoredrangesinenclosingrange:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewDidBeginEditing(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate when editing of the specified text view begins.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textViewDidBeginEditing"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextView",
          "text": "UITextView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewDidBeginEditing(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textViewDidBeginEditing:"
        }
      ],
      "role": "symbol",
      "title": "textViewDidBeginEditing(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextviewdelegate/textviewdidbeginediting(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewDidChange(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate when the user changes the text or attributes in the specified text view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textViewDidChange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextView",
          "text": "UITextView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewDidChange(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textViewDidChange:"
        }
      ],
      "role": "symbol",
      "title": "textViewDidChange(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextviewdelegate/textviewdidchange(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewDidChangeSelection(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate when the text selection changes in the specified text view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textViewDidChangeSelection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextView",
          "text": "UITextView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewDidChangeSelection(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textViewDidChangeSelection:"
        }
      ],
      "role": "symbol",
      "title": "textViewDidChangeSelection(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextviewdelegate/textviewdidchangeselection(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewDidEndEditing(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate when editing of the specified text view ends.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textViewDidEndEditing"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextView",
          "text": "UITextView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewDidEndEditing(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textViewDidEndEditing:"
        }
      ],
      "role": "symbol",
      "title": "textViewDidEndEditing(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextviewdelegate/textviewdidendediting(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewShouldBeginEditing(_:)": {
      "abstract": [
        {
          "text": "Asks the delegate whether to begin editing in the specified text view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textViewShouldBeginEditing"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextView",
          "text": "UITextView"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewShouldBeginEditing(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textViewShouldBeginEditing:"
        }
      ],
      "role": "symbol",
      "title": "textViewShouldBeginEditing(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextviewdelegate/textviewshouldbeginediting(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewShouldEndEditing(_:)": {
      "abstract": [
        {
          "text": "Asks the delegate whether to stop editing in the specified text view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textViewShouldEndEditing"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextView",
          "text": "UITextView"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewShouldEndEditing(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textViewShouldEndEditing:"
        }
      ],
      "role": "symbol",
      "title": "textViewShouldEndEditing(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextviewdelegate/textviewshouldendediting(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewWritingToolsDidEnd(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the current writing tools session ended.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textViewWritingToolsDidEnd"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextView",
          "text": "UITextView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewWritingToolsDidEnd(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textViewWritingToolsDidEnd:"
        }
      ],
      "role": "symbol",
      "title": "textViewWritingToolsDidEnd(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextviewdelegate/textviewwritingtoolsdidend(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewWritingToolsWillBegin(_:)": {
      "abstract": [
        {
          "text": "Tells the delegate that an interaction with the writing tools interface is about to begin.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textViewWritingToolsWillBegin"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextView",
          "text": "UITextView"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewWritingToolsWillBegin(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textViewWritingToolsWillBegin:"
        }
      ],
      "role": "symbol",
      "title": "textViewWritingToolsWillBegin(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextviewdelegate/textviewwritingtoolswillbegin(_:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Text-actions-and-menus",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextItem",
        "doc://com.apple.uikit/documentation/UIKit/UITextItem/MenuConfiguration"
      ],
      "title": "Text actions and menus"
    }
  ],
  "topicSections": [
    {
      "anchor": "Responding-to-editing-notifications",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewShouldBeginEditing(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewDidBeginEditing(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewShouldEndEditing(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewDidEndEditing(_:)"
      ],
      "title": "Responding to editing notifications"
    },
    {
      "anchor": "Responding-to-text-changes",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:shouldChangeTextIn:replacementText:)",
        "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewDidChange(_:)"
      ],
      "title": "Responding to text changes"
    },
    {
      "anchor": "Responding-to-selection-changes",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewDidChangeSelection(_:)"
      ],
      "title": "Responding to selection changes"
    },
    {
      "anchor": "Interacting-with-text-data",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:menuConfigurationFor:defaultMenu:)",
        "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:primaryActionFor:defaultAction:)",
        "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:textItemMenuWillDisplayFor:animator:)",
        "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:textItemMenuWillEndFor:animator:)"
      ],
      "title": "Interacting with text data"
    },
    {
      "anchor": "Providing-a-context-menu",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:editMenuForTextIn:suggestedActions:)"
      ],
      "title": "Providing a context menu"
    },
    {
      "anchor": "Customizing-an-edit-menu",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:willDismissEditMenuWith:)",
        "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:willPresentEditMenuWith:)"
      ],
      "title": "Customizing an edit menu"
    },
    {
      "anchor": "Responding-to-writing-tools-interactions",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewWritingToolsWillBegin(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewWritingToolsDidEnd(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:writingToolsIgnoredRangesInEnclosingRange:)"
      ],
      "title": "Responding to writing tools interactions"
    },
    {
      "anchor": "Inserting-a-Smart-Reply-suggestion",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:insertInputSuggestion:)"
      ],
      "title": "Inserting a Smart Reply suggestion"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:shouldInteractWith:in:interaction:)-5qha9",
        "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:shouldInteractWith:in:interaction:)-622ub",
        "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:shouldInteractWith:in:)-97zx6",
        "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:shouldInteractWith:in:)-98tho",
        "doc://com.apple.uikit/documentation/UIKit/UITextItemInteraction"
      ],
      "title": "Deprecated"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:didBeginFormattingWith:)",
        "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:didEndFormattingWith:)",
        "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:willBeginFormattingWith:)",
        "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:willEndFormattingWith:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UITextViewDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Responding-to-editing-notifications",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewShouldBeginEditing(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewDidBeginEditing(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewShouldEndEditing(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewDidEndEditing(_:)"
              ],
              "title": "Responding to editing notifications"
            },
            {
              "anchor": "Responding-to-text-changes",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:shouldChangeTextIn:replacementText:)",
                "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewDidChange(_:)"
              ],
              "title": "Responding to text changes"
            },
            {
              "anchor": "Responding-to-selection-changes",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewDidChangeSelection(_:)"
              ],
              "title": "Responding to selection changes"
            },
            {
              "anchor": "Interacting-with-text-data",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:menuConfigurationFor:defaultMenu:)",
                "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:primaryActionFor:defaultAction:)",
                "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:textItemMenuWillDisplayFor:animator:)",
                "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:textItemMenuWillEndFor:animator:)"
              ],
              "title": "Interacting with text data"
            },
            {
              "anchor": "Providing-a-context-menu",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:editMenuForTextIn:suggestedActions:)"
              ],
              "title": "Providing a context menu"
            },
            {
              "anchor": "Customizing-an-edit-menu",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:willDismissEditMenuWith:)",
                "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:willPresentEditMenuWith:)"
              ],
              "title": "Customizing an edit menu"
            },
            {
              "anchor": "Responding-to-writing-tools-interactions",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewWritingToolsWillBegin(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textViewWritingToolsDidEnd(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:writingToolsIgnoredRangesInEnclosingRange:)"
              ],
              "title": "Responding to writing tools interactions"
            },
            {
              "anchor": "Inserting-a-Smart-Reply-suggestion",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:insertInputSuggestion:)"
              ],
              "title": "Inserting a Smart Reply suggestion"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:shouldInteractWith:in:interaction:)-5qha9",
                "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:shouldInteractWith:in:interaction:)-622ub",
                "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:shouldInteractWith:in:)-97zx6",
                "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:shouldInteractWith:in:)-98tho",
                "doc://com.apple.uikit/documentation/UIKit/UITextItemInteraction"
              ],
              "title": "Deprecated"
            },
            {
              "anchor": "Instance-Methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:didBeginFormattingWith:)",
                "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:didEndFormattingWith:)",
                "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:willBeginFormattingWith:)",
                "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:willEndFormattingWith:)"
              ],
              "title": "Instance Methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Text-actions-and-menus",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextItem",
                "doc://com.apple.uikit/documentation/UIKit/UITextItemContentType",
                "doc://com.apple.uikit/documentation/UIKit/UITextItem/MenuConfiguration"
              ],
              "title": "Text actions and menus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UITextViewDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIScrollViewDelegate",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)UIScrollViewDelegate",
                    "text": "UIScrollViewDelegate"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:menuConfigurationFor:defaultMenu:)/title",
          "value": "textView:menuConfigurationForTextItem:defaultMenu:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:menuConfigurationFor:defaultMenu:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textView:menuConfigurationForTextItem:defaultMenu:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:willEndFormattingWith:)/title",
          "value": "textView:willEndFormattingWithViewController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:willEndFormattingWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textView:willEndFormattingWithViewController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewDelegate/title",
          "value": "UIScrollViewDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScrollViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScrollViewDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIScrollViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textViewDidEndEditing(_:)/title",
          "value": "textViewDidEndEditing:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textViewDidEndEditing(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textViewDidEndEditing:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:willDismissEditMenuWith:)/title",
          "value": "textView:willDismissEditMenuWithAnimator:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:willDismissEditMenuWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textView:willDismissEditMenuWithAnimator:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:shouldInteractWith:in:interaction:)-622ub/title",
          "value": "textView:shouldInteractWithURL:inRange:interaction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:shouldInteractWith:in:interaction:)-622ub/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textView:shouldInteractWithURL:inRange:interaction:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textViewDidBeginEditing(_:)/title",
          "value": "textViewDidBeginEditing:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textViewDidBeginEditing(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textViewDidBeginEditing:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textViewShouldBeginEditing(_:)/title",
          "value": "textViewShouldBeginEditing:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textViewShouldBeginEditing(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textViewShouldBeginEditing:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textViewWritingToolsDidEnd(_:)/title",
          "value": "textViewWritingToolsDidEnd:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textViewWritingToolsDidEnd(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textViewWritingToolsDidEnd:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:didBeginFormattingWith:)/title",
          "value": "textView:didBeginFormattingWithViewController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:didBeginFormattingWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textView:didBeginFormattingWithViewController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:textItemMenuWillDisplayFor:animator:)/title",
          "value": "textView:textItemMenuWillDisplayForTextItem:animator:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:textItemMenuWillDisplayFor:animator:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textView:textItemMenuWillDisplayForTextItem:animator:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textViewShouldEndEditing(_:)/title",
          "value": "textViewShouldEndEditing:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textViewShouldEndEditing(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textViewShouldEndEditing:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:shouldInteractWith:in:)-98tho/title",
          "value": "textView:shouldInteractWithURL:inRange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:shouldInteractWith:in:)-98tho/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textView:shouldInteractWithURL:inRange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:insertInputSuggestion:)/title",
          "value": "textView:insertInputSuggestion:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:insertInputSuggestion:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textView:insertInputSuggestion:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:shouldChangeTextIn:replacementText:)/title",
          "value": "textView:shouldChangeTextInRange:replacementText:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:shouldChangeTextIn:replacementText:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textView:shouldChangeTextInRange:replacementText:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextItem~1MenuConfiguration/title",
          "value": "UITextItemMenuConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextItem~1MenuConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextItemMenuConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextItem~1MenuConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextItemMenuConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:didEndFormattingWith:)/title",
          "value": "textView:didEndFormattingWithViewController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:didEndFormattingWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textView:didEndFormattingWithViewController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textViewDidChangeSelection(_:)/title",
          "value": "textViewDidChangeSelection:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textViewDidChangeSelection(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textViewDidChangeSelection:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:textItemMenuWillEndFor:animator:)/title",
          "value": "textView:textItemMenuWillEndForTextItem:animator:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:textItemMenuWillEndFor:animator:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textView:textItemMenuWillEndForTextItem:animator:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:editMenuForTextIn:suggestedActions:)/title",
          "value": "textView:editMenuForTextInRange:suggestedActions:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:editMenuForTextIn:suggestedActions:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textView:editMenuForTextInRange:suggestedActions:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextItem/title",
          "value": "UITextItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:shouldInteractWith:in:)-97zx6/title",
          "value": "textView:shouldInteractWithTextAttachment:inRange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:shouldInteractWith:in:)-97zx6/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textView:shouldInteractWithTextAttachment:inRange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textViewDidChange(_:)/title",
          "value": "textViewDidChange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textViewDidChange(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textViewDidChange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate/title",
          "value": "UITextViewDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextItemInteraction/title",
          "value": "UITextItemInteraction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextItemInteraction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextItemInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextItemInteraction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextItemInteraction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:willPresentEditMenuWith:)/title",
          "value": "textView:willPresentEditMenuWithAnimator:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:willPresentEditMenuWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textView:willPresentEditMenuWithAnimator:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:shouldInteractWith:in:interaction:)-5qha9/title",
          "value": "textView:shouldInteractWithTextAttachment:inRange:interaction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:shouldInteractWith:in:interaction:)-5qha9/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textView:shouldInteractWithTextAttachment:inRange:interaction:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:willBeginFormattingWith:)/title",
          "value": "textView:willBeginFormattingWithViewController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:willBeginFormattingWith:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textView:willBeginFormattingWithViewController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:writingToolsIgnoredRangesInEnclosingRange:)/title",
          "value": "textView:writingToolsIgnoredRangesInEnclosingRange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:writingToolsIgnoredRangesInEnclosingRange:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textView:writingToolsIgnoredRangesInEnclosingRange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:primaryActionFor:defaultAction:)/title",
          "value": "textView:primaryActionForTextItem:defaultAction:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:primaryActionFor:defaultAction:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textView:primaryActionForTextItem:defaultAction:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textViewWritingToolsWillBegin(_:)/title",
          "value": "textViewWritingToolsWillBegin:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textViewWritingToolsWillBegin(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textViewWritingToolsWillBegin:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitextviewdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uitextviewdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
