{
  "abstract": [
    {
      "text": "Constants that describe and capture the type of content a text item represents along with a specific related value.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "major": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "14.0 beta 5",
        "15.0"
      ]
    },
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "14.3",
        "15.0"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITextItemContentType"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UITextItemContentType",
    "fragments": [
      {
        "kind": "identifier",
        "text": "UITextItemContentType"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UITextItemContentType"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "17.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "UITextItemContentType"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UITextItemContentType"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSInteger",
              "text": "NSInteger"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextItem": {
      "abstract": [
        {
          "text": "An object for attaching custom actions and menus to links, text attachments, or other specific text in a text view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextItem"
        }
      ],
      "role": "symbol",
      "title": "UITextItem",
      "type": "topic",
      "url": "/documentation/uikit/uitextitem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextItem/MenuConfiguration": {
      "abstract": [
        {
          "text": "An object that describes what type of menu and preview to show for a text item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MenuConfiguration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextItem/MenuConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MenuConfiguration"
        }
      ],
      "role": "symbol",
      "title": "UITextItem.MenuConfiguration",
      "type": "topic",
      "url": "/documentation/uikit/uitextitem/menuconfiguration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextItemContentType": {
      "abstract": [
        {
          "text": "Constants that describe and capture the type of content a text item represents along with a specific related value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextItemContentType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextItemContentType",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextItemContentType",
      "type": "topic",
      "url": "/documentation/uikit/uitextitemcontenttype"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextItemContentType/UITextItemContentTypeLink": {
      "abstract": [
        {
          "text": "A link to a resource, such as an item on a remote server or the path to a local file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextItemContentTypeLink"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextItemContentType/UITextItemContentTypeLink",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextItemContentTypeLink",
      "type": "topic",
      "url": "/documentation/uikit/uitextitemcontenttype/uitextitemcontenttypelink"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextItemContentType/UITextItemContentTypeTag": {
      "abstract": [
        {
          "text": "A string that represents a custom tag for a topic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextItemContentTypeTag"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextItemContentType/UITextItemContentTypeTag",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextItemContentTypeTag",
      "type": "topic",
      "url": "/documentation/uikit/uitextitemcontenttype/uitextitemcontenttypetag"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextItemContentType/UITextItemContentTypeTextAttachment": {
      "abstract": [
        {
          "text": "A text attachment, such as an image or view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextItemContentTypeTextAttachment"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextItemContentType/UITextItemContentTypeTextAttachment",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextItemContentTypeTextAttachment",
      "type": "topic",
      "url": "/documentation/uikit/uitextitemcontenttype/uitextitemcontenttypetextattachment"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate": {
      "abstract": [
        {
          "text": "The methods for receiving editing-related messages for text view objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextViewDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextViewDelegate"
        }
      ],
      "role": "symbol",
      "title": "UITextViewDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uitextviewdelegate"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Text-actions-and-menus",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextItem",
        "doc://com.apple.uikit/documentation/UIKit/UITextItem/MenuConfiguration",
        "doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate"
      ],
      "title": "Text actions and menus"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-content-type",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextItemContentType/UITextItemContentTypeLink",
        "doc://com.apple.uikit/documentation/UIKit/UITextItemContentType/UITextItemContentTypeTag",
        "doc://com.apple.uikit/documentation/UIKit/UITextItemContentType/UITextItemContentTypeTextAttachment"
      ],
      "title": "Getting the content type"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextItem/title",
          "value": "UITextItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextItem~1MenuConfiguration/title",
          "value": "UITextItemMenuConfiguration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextItem~1MenuConfiguration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextItemMenuConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextItem~1MenuConfiguration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextItemMenuConfiguration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate/title",
          "value": "UITextViewDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextViewDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitextitemcontenttype"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
