{"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","identifiers":["doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/s:SY","doc://com.externally.resolved.symbol/s:s8SendableP"],"kind":"relationships"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextItemInteraction"}]}],"kind":"declarations"}],"topicSections":[{"title":"Constants","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextItemInteraction/invokeDefaultAction","doc://com.apple.uikit/documentation/UIKit/UITextItemInteraction/presentActions","doc://com.apple.uikit/documentation/UIKit/UITextItemInteraction/preview"],"anchor":"Constants"},{"title":"Initializers","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextItemInteraction/init(rawValue:)"],"anchor":"Initializers"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uitextiteminteraction"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uitextiteminteraction"]}],"kind":"symbol","metadata":{"modules":[{"name":"UIKit"}],"externalID":"c:@E@UITextItemInteraction","title":"UITextItemInteraction","symbolKind":"enum","platforms":[{"name":"iOS","introducedAt":"10.0","message":"UITextItemInteraction has been replaced by text item methods on UITextViewDelegate","unavailable":false,"beta":false,"deprecated":false,"deprecatedAt":"17.0"},{"name":"iPadOS","introducedAt":"10.0","message":"UITextItemInteraction has been replaced by text item methods on UITextViewDelegate","unavailable":false,"beta":false,"deprecated":false,"deprecatedAt":"17.0"},{"name":"Mac Catalyst","introducedAt":"13.1","message":"UITextItemInteraction has been replaced by text item methods on UITextViewDelegate","unavailable":false,"beta":false,"deprecated":false,"deprecatedAt":"17.0"},{"name":"tvOS","introducedAt":"10.0","message":"UITextItemInteraction has been replaced by text item methods on UITextViewDelegate","unavailable":false,"beta":false,"deprecated":false,"deprecatedAt":"17.0"},{"name":"visionOS","introducedAt":"1.0","message":"UITextItemInteraction has been replaced by text item methods on UITextViewDelegate","unavailable":false,"beta":false,"deprecated":false,"deprecatedAt":"1.0"}],"role":"symbol","roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextItemInteraction"}],"navigatorTitle":[{"kind":"identifier","text":"UITextItemInteraction"}]},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UITextItemInteraction"},"seeAlsoSections":[{"title":"Deprecated","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:shouldInteractWith:in:interaction:)-5qha9","doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:shouldInteractWith:in:interaction:)-622ub","doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:shouldInteractWith:in:)-97zx6","doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:shouldInteractWith:in:)-98tho"],"anchor":"Deprecated"}],"abstract":[{"text":"Constants that indicate the type of interaction the user expects to have with a URL or text attachment.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.externally.resolved.symbol/s:SY":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RawRepresentable"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:SY8RawValueQa","kind":"typeIdentifier","text":"RawValue"},{"kind":"text","text":">"}],"url":"/documentation/Swift/RawRepresentable","title":"RawRepresentable","abstract":[{"type":"text","text":"A type that can be converted to and from an associated raw value."}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SY"},"doc://com.externally.resolved.symbol/s:SQ":{"abstract":[{"type":"text","text":"A type that can be compared for value equality."}],"url":"/documentation/Swift/Equatable","identifier":"doc://com.externally.resolved.symbol/s:SQ","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"role":"symbol","title":"Equatable","type":"topic","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:shouldInteractWith:in:interaction:)-5qha9":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:shouldInteractWith:in:interaction:)-5qha9","kind":"symbol","navigatorTitle":[{"text":"textView:shouldInteractWithTextAttachment:inRange:interaction:","kind":"identifier"}],"title":"textView(_:shouldInteractWith:in:interaction:)","url":"/documentation/uikit/uitextviewdelegate/textview(_:shouldinteractwith:in:interaction:)-5qha9","abstract":[{"text":"Asks the delegate whether the specified text view allows the specified type of user interaction with the provided text attachment in the specified range of text.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textView","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UITextView","preciseIdentifier":"c:objc(cs)UITextView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldInteractWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSTextAttachment","preciseIdentifier":"c:objc(cs)NSTextAttachment"},{"kind":"text","text":", "},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRange","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"interaction","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@UITextItemInteraction","text":"UITextItemInteraction","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"deprecated":true,"type":"topic","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITextItemInteraction/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextItemInteraction/init(rawValue:)","abstract":[],"type":"topic","url":"/documentation/uikit/uitextiteminteraction/init(rawvalue:)","role":"symbol","title":"init(rawValue:)","deprecated":true,"kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:shouldInteractWith:in:)-97zx6":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:shouldInteractWith:in:)-97zx6","type":"topic","kind":"symbol","role":"symbol","title":"textView(_:shouldInteractWith:in:)","navigatorTitle":[{"text":"textView:shouldInteractWithTextAttachment:inRange:","kind":"identifier"}],"url":"/documentation/uikit/uitextviewdelegate/textview(_:shouldinteractwith:in:)-97zx6","abstract":[{"type":"text","text":"Asks the delegate whether the specified text view allows user interaction with the provided text attachment in the specified range of text."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textView"},{"text":"(","kind":"text"},{"text":"UITextView","preciseIdentifier":"c:objc(cs)UITextView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"shouldInteractWith","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSTextAttachment","preciseIdentifier":"c:objc(cs)NSTextAttachment","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRange","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"deprecated":true},"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP":{"title":"BitwiseCopyable","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BitwiseCopyable"},{"kind":"text","text":" : ~Escapable"}],"identifier":"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","role":"symbol","url":"/documentation/Swift/BitwiseCopyable","kind":"symbol","abstract":[{"type":"text","text":""}]},"doc://com.apple.uikit/documentation/UIKit/UITextItemInteraction":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextItemInteraction","navigatorTitle":[{"text":"UITextItemInteraction","kind":"identifier"}],"abstract":[{"type":"text","text":"Constants that indicate the type of interaction the user expects to have with a URL or text attachment."}],"kind":"symbol","title":"UITextItemInteraction","role":"symbol","url":"/documentation/uikit/uitextiteminteraction","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITextItemInteraction","kind":"identifier"}],"deprecated":true},"doc://com.apple.uikit/documentation/UIKit/UITextItemInteraction/invokeDefaultAction":{"role":"symbol","title":"UITextItemInteraction.invokeDefaultAction","navigatorTitle":[{"text":"UITextItemInteractionInvokeDefaultAction","kind":"identifier"}],"type":"topic","deprecated":true,"url":"/documentation/uikit/uitextiteminteraction/invokedefaultaction","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invokeDefaultAction","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextItemInteraction/invokeDefaultAction","abstract":[{"type":"text","text":"The user wants to perform the default action on the text item; for example, opening a URL."}]},"doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:shouldInteractWith:in:)-98tho":{"title":"textView(_:shouldInteractWith:in:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textView"},{"kind":"text","text":"("},{"text":"UITextView","preciseIdentifier":"c:objc(cs)UITextView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"shouldInteractWith","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRange","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"/documentation/uikit/uitextviewdelegate/textview(_:shouldinteractwith:in:)-98tho","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"textView:shouldInteractWithURL:inRange:","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:shouldInteractWith:in:)-98tho","deprecated":true,"abstract":[{"type":"text","text":"Asks the delegate whether the specified text view allows user interaction with the specified URL in the specified range of text."}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITextItemInteraction/presentActions":{"url":"/documentation/uikit/uitextiteminteraction/presentactions","role":"symbol","navigatorTitle":[{"text":"UITextItemInteractionPresentActions","kind":"identifier"}],"title":"UITextItemInteraction.presentActions","deprecated":true,"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentActions","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"The user wants to be presented with a list of actions that can be taken on the text item, such as opening the link in a different way or downloading content from the link.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextItemInteraction/presentActions"},"doc://com.externally.resolved.symbol/s:s8SendableP":{"abstract":[{"type":"text","text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races."}],"url":"/documentation/Swift/Sendable","identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}],"role":"symbol","title":"Sendable","type":"topic","kind":"symbol"},"doc://com.externally.resolved.symbol/s:SH":{"abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}],"url":"/documentation/Swift/Hashable","identifier":"doc://com.externally.resolved.symbol/s:SH","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hashable","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SQ","text":"Equatable","kind":"typeIdentifier"}],"role":"symbol","title":"Hashable","type":"topic","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:shouldInteractWith:in:interaction:)-622ub":{"abstract":[{"text":"Asks the delegate whether the specified text view allows the specified type of user interaction with the specified URL in the specified range of text.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"textView:shouldInteractWithURL:inRange:interaction:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UITextView","preciseIdentifier":"c:objc(cs)UITextView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"shouldInteractWith","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRange","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"interaction","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@UITextItemInteraction","text":"UITextItemInteraction","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"textView(_:shouldInteractWith:in:interaction:)","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:shouldInteractWith:in:interaction:)-622ub","deprecated":true,"kind":"symbol","url":"/documentation/uikit/uitextviewdelegate/textview(_:shouldinteractwith:in:interaction:)-622ub"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITextItemInteraction/preview":{"role":"symbol","title":"UITextItemInteraction.preview","navigatorTitle":[{"text":"UITextItemInteractionPreview","kind":"identifier"}],"type":"topic","deprecated":true,"url":"/documentation/uikit/uitextiteminteraction/preview","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preview","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextItemInteraction/preview","abstract":[{"type":"text","text":"The user wants to get a preview of the content represented by the text item, such as by initiating a peek and pop on a link."}]},"doc://com.externally.resolved.symbol/c:@T@NSInteger":{"abstract":[{"type":"text","text":"Describes an integer."}],"url":"/documentation/objectivec/nsinteger","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","fragments":[{"text":"typealias ","kind":"text"},{"text":"NSInteger","kind":"identifier"}],"role":"symbol","title":"NSInteger","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"unavailable":false,"introducedAt":"10.0","deprecatedAt":"17.0","beta":false,"deprecated":false,"name":"iOS"},{"unavailable":false,"introducedAt":"10.0","deprecatedAt":"17.0","beta":false,"deprecated":false,"name":"iPadOS"},{"unavailable":false,"introducedAt":"13.1","deprecatedAt":"17.0","beta":false,"deprecated":false,"name":"Mac Catalyst"},{"unavailable":false,"introducedAt":"10.0","deprecatedAt":"17.0","beta":false,"deprecated":false,"name":"tvOS"},{"unavailable":false,"introducedAt":"1.0","deprecatedAt":"1.0","beta":false,"deprecated":false,"name":"visionOS"}],"op":"replace","path":"/metadata/platforms"},{"value":"Enumeration","op":"replace","path":"/metadata/roleHeading"},{"value":"UITextItemInteraction","op":"replace","path":"/metadata/title"},{"value":"enum","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"UITextItemInteraction"}],"op":"replace","path":"/metadata/fragments"},{"value":[{"text":"UITextItemInteraction","kind":"identifier"}],"op":"replace","path":"/metadata/navigatorTitle"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"op":"replace","path":"/hierarchy"},{"value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextItemInteraction/invokeDefaultAction","doc://com.apple.uikit/documentation/UIKit/UITextItemInteraction/presentActions","doc://com.apple.uikit/documentation/UIKit/UITextItemInteraction/preview"],"title":"Constants","anchor":"Constants"}],"op":"replace","path":"/topicSections"},{"value":null,"op":"replace","path":"/relationshipsSections"},{"value":[{"anchor":"Deprecated","title":"Deprecated","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:shouldInteractWith:in:interaction:)-5qha9","doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:shouldInteractWith:in:interaction:)-622ub","doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:shouldInteractWith:in:)-97zx6","doc://com.apple.uikit/documentation/UIKit/UITextViewDelegate/textView(_:shouldInteractWith:in:)-98tho"],"generated":true}],"op":"replace","path":"/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextItemInteraction"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:@T@NSInteger","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"/primaryContentSections/0"},{"op":"add","path":"/deprecationSummary","value":[]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:shouldInteractWith:in:interaction:)-5qha9/title","value":"textView:shouldInteractWithTextAttachment:inRange:interaction:"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:shouldInteractWith:in:interaction:)-5qha9/fragments","value":[{"text":"- ","kind":"text"},{"text":"textView:shouldInteractWithTextAttachment:inRange:interaction:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:shouldInteractWith:in:)-97zx6/title","value":"textView:shouldInteractWithTextAttachment:inRange:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textView:shouldInteractWithTextAttachment:inRange:"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:shouldInteractWith:in:)-97zx6/fragments"},{"op":"replace","value":"UITextItemInteraction","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextItemInteraction/title"},{"op":"replace","value":[{"text":"UITextItemInteraction","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextItemInteraction/fragments"},{"op":"replace","value":[{"text":"UITextItemInteraction","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextItemInteraction/navigatorTitle"},{"value":"UITextItemInteractionInvokeDefaultAction","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextItemInteraction~1invokeDefaultAction/title"},{"value":[{"kind":"identifier","text":"UITextItemInteractionInvokeDefaultAction"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextItemInteraction~1invokeDefaultAction/fragments"},{"value":"textView:shouldInteractWithURL:inRange:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:shouldInteractWith:in:)-98tho/title"},{"value":[{"text":"- ","kind":"text"},{"text":"textView:shouldInteractWithURL:inRange:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:shouldInteractWith:in:)-98tho/fragments"},{"value":"UITextItemInteractionPresentActions","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextItemInteraction~1presentActions/title"},{"value":[{"text":"UITextItemInteractionPresentActions","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextItemInteraction~1presentActions/fragments"},{"value":"textView:shouldInteractWithURL:inRange:interaction:","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:shouldInteractWith:in:interaction:)-622ub/title"},{"value":[{"text":"- ","kind":"text"},{"text":"textView:shouldInteractWithURL:inRange:interaction:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextViewDelegate~1textView(_:shouldInteractWith:in:interaction:)-622ub/fragments"},{"value":"UITextItemInteractionPreview","op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextItemInteraction~1preview/title"},{"value":[{"kind":"identifier","text":"UITextItemInteractionPreview"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextItemInteraction~1preview/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}