{
  "abstract": [
    {
      "text": "The interface for customizing the behavior of a drag activity for a text view.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UITextDragDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UITextDragDelegate"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UITextDragDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "UITextDragDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UITextDragDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate": {
      "abstract": [
        {
          "text": "The interface for customizing the behavior of a drag activity for a text view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextDragDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextDragDelegate"
        }
      ],
      "role": "symbol",
      "title": "UITextDragDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uitextdragdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate/textDraggableView(_:dragPreviewForLiftingItem:session:)": {
      "abstract": [
        {
          "text": "Asks the delegate for the preview to show during the lift animation that happens when a user begins to drag an item from a text view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textDraggableView"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITextDraggable",
          "text": "UITextDraggable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dragPreviewForLiftingItem"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDragItem",
          "text": "UIDragItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "session"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDragSession",
          "text": "UIDragSession"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITargetedDragPreview",
          "text": "UITargetedDragPreview"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate/textDraggableView(_:dragPreviewForLiftingItem:session:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textDraggableView:dragPreviewForLiftingItem:session:"
        }
      ],
      "role": "symbol",
      "title": "textDraggableView(_:dragPreviewForLiftingItem:session:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextdragdelegate/textdraggableview(_:dragpreviewforliftingitem:session:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate/textDraggableView(_:dragSessionDidEnd:with:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the drag session has ended.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textDraggableView"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITextDraggable",
          "text": "UITextDraggable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dragSessionDidEnd"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDragSession",
          "text": "UIDragSession"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIDropOperation",
          "text": "UIDropOperation"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate/textDraggableView(_:dragSessionDidEnd:with:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textDraggableView:dragSessionDidEnd:withOperation:"
        }
      ],
      "role": "symbol",
      "title": "textDraggableView(_:dragSessionDidEnd:with:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextdragdelegate/textdraggableview(_:dragsessiondidend:with:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate/textDraggableView(_:dragSessionWillBegin:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the text has been lifted out of the text view and the user is beginning to drag the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textDraggableView"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITextDraggable",
          "text": "UITextDraggable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dragSessionWillBegin"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDragSession",
          "text": "UIDragSession"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate/textDraggableView(_:dragSessionWillBegin:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textDraggableView:dragSessionWillBegin:"
        }
      ],
      "role": "symbol",
      "title": "textDraggableView(_:dragSessionWillBegin:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextdragdelegate/textdraggableview(_:dragsessionwillbegin:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate/textDraggableView(_:itemsForDrag:)": {
      "abstract": [
        {
          "text": "Asks the delegate for custom drag items from a text view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textDraggableView"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITextDraggable",
          "text": "UITextDraggable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "itemsForDrag"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITextDragRequest",
          "text": "UITextDragRequest"
        },
        {
          "kind": "text",
          "text": ") -> ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIDragItem",
          "text": "UIDragItem"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate/textDraggableView(_:itemsForDrag:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textDraggableView:itemsForDrag:"
        }
      ],
      "role": "symbol",
      "title": "textDraggableView(_:itemsForDrag:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextdragdelegate/textdraggableview(_:itemsfordrag:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate/textDraggableView(_:willAnimateLiftWith:session:)": {
      "abstract": [
        {
          "text": "Tells the delegate when the lift animation is about to begin, and gives you a chance to animate additional changes alongside the system animation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textDraggableView"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": " & "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITextDraggable",
          "text": "UITextDraggable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willAnimateLiftWith"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDragAnimating",
          "text": "UIDragAnimating"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "session"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIDragSession",
          "text": "UIDragSession"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate/textDraggableView(_:willAnimateLiftWith:session:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textDraggableView:willAnimateLiftWithAnimator:session:"
        }
      ],
      "role": "symbol",
      "title": "textDraggableView(_:willAnimateLiftWith:session:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextdragdelegate/textdraggableview(_:willanimateliftwith:session:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextDragOptions": {
      "abstract": [
        {
          "text": "A set of options that determine the behavior of a draggable text view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextDragOptions"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextDragOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextDragOptions"
        }
      ],
      "role": "symbol",
      "title": "UITextDragOptions",
      "type": "topic",
      "url": "/documentation/uikit/uitextdragoptions"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextDraggable": {
      "abstract": [
        {
          "text": "The interface that determines if a text view is a drag source.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextDraggable"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextDraggable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextDraggable"
        }
      ],
      "role": "symbol",
      "title": "UITextDraggable",
      "type": "topic",
      "url": "/documentation/uikit/uitextdraggable"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate": {
      "abstract": [
        {
          "text": "The interface for configuring a text view’s drop behavior.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextDropDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextDropDelegate"
        }
      ],
      "role": "symbol",
      "title": "UITextDropDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uitextdropdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextDropEditability": {
      "abstract": [
        {
          "text": "The text-drop editability styles for noneditable text views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextDropEditability"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextDropEditability",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextDropEditability"
        }
      ],
      "role": "symbol",
      "title": "UITextDropEditability",
      "type": "topic",
      "url": "/documentation/uikit/uitextdropeditability"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextDroppable": {
      "abstract": [
        {
          "text": "The interface that determines if a text view is a drop destination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextDroppable"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextDroppable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextDroppable"
        }
      ],
      "role": "symbol",
      "title": "UITextDroppable",
      "type": "topic",
      "url": "/documentation/uikit/uitextdroppable"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Text-view-additions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate",
        "doc://com.apple.uikit/documentation/UIKit/UITextDraggable",
        "doc://com.apple.uikit/documentation/UIKit/UITextDragOptions",
        "doc://com.apple.uikit/documentation/UIKit/UITextDroppable",
        "doc://com.apple.uikit/documentation/UIKit/UITextDropEditability"
      ],
      "title": "Text view additions"
    }
  ],
  "topicSections": [
    {
      "anchor": "Handling-drag-session-notifications",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate/textDraggableView(_:dragSessionWillBegin:)",
        "doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate/textDraggableView(_:dragSessionDidEnd:with:)"
      ],
      "title": "Handling drag session notifications"
    },
    {
      "anchor": "Providing-additional-animations",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate/textDraggableView(_:willAnimateLiftWith:session:)"
      ],
      "title": "Providing additional animations"
    },
    {
      "anchor": "Providing-custom-drag-items",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate/textDraggableView(_:itemsForDrag:)"
      ],
      "title": "Providing custom drag items"
    },
    {
      "anchor": "Providing-a-custom-preview-for-a-drag-activity",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate/textDraggableView(_:dragPreviewForLiftingItem:session:)"
      ],
      "title": "Providing a custom preview for a drag activity"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UITextDragDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextDragDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextDragDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Handling-drag-session-notifications",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate/textDraggableView(_:dragSessionWillBegin:)",
                "doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate/textDraggableView(_:dragSessionDidEnd:with:)"
              ],
              "title": "Handling drag session notifications"
            },
            {
              "anchor": "Providing-additional-animations",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate/textDraggableView(_:willAnimateLiftWith:session:)"
              ],
              "title": "Providing additional animations"
            },
            {
              "anchor": "Providing-custom-drag-items",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate/textDraggableView(_:itemsForDrag:)"
              ],
              "title": "Providing custom drag items"
            },
            {
              "anchor": "Providing-a-custom-preview-for-a-drag-activity",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate/textDraggableView(_:dragPreviewForLiftingItem:session:)"
              ],
              "title": "Providing a custom preview for a drag activity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Text-view-additions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate",
                "doc://com.apple.uikit/documentation/UIKit/UITextDraggable",
                "doc://com.apple.uikit/documentation/UIKit/UITextDragOptions",
                "doc://com.apple.uikit/documentation/UIKit/UITextDroppable",
                "doc://com.apple.uikit/documentation/UIKit/UITextDropEditability"
              ],
              "title": "Text view additions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UITextDragDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragDelegate~1textDraggableView(_:dragSessionDidEnd:with:)/title",
          "value": "textDraggableView:dragSessionDidEnd:withOperation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragDelegate~1textDraggableView(_:dragSessionDidEnd:with:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textDraggableView:dragSessionDidEnd:withOperation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropEditability/title",
          "value": "UITextDropEditability"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropEditability/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextDropEditability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropEditability/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextDropEditability"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropDelegate/title",
          "value": "UITextDropDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextDropDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextDropDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragDelegate~1textDraggableView(_:itemsForDrag:)/title",
          "value": "textDraggableView:itemsForDrag:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragDelegate~1textDraggableView(_:itemsForDrag:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textDraggableView:itemsForDrag:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDraggable/title",
          "value": "UITextDraggable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDraggable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextDraggable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDraggable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextDraggable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragDelegate~1textDraggableView(_:willAnimateLiftWith:session:)/title",
          "value": "textDraggableView:willAnimateLiftWithAnimator:session:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragDelegate~1textDraggableView(_:willAnimateLiftWith:session:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textDraggableView:willAnimateLiftWithAnimator:session:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragDelegate~1textDraggableView(_:dragSessionWillBegin:)/title",
          "value": "textDraggableView:dragSessionWillBegin:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragDelegate~1textDraggableView(_:dragSessionWillBegin:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textDraggableView:dragSessionWillBegin:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDroppable/title",
          "value": "UITextDroppable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDroppable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextDroppable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDroppable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextDroppable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragDelegate/title",
          "value": "UITextDragDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextDragDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextDragDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragOptions/title",
          "value": "UITextDragOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextDragOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextDragOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragDelegate~1textDraggableView(_:dragPreviewForLiftingItem:session:)/title",
          "value": "textDraggableView:dragPreviewForLiftingItem:session:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragDelegate~1textDraggableView(_:dragPreviewForLiftingItem:session:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textDraggableView:dragPreviewForLiftingItem:session:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitextdragdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uitextdragdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
