{
  "abstract": [
    {
      "text": "The methods you use on a find session’s aggregator to collect matching text ranges for a search.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-c.protocol"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UITextSearchAggregator",
    "fragments": [
      {
        "kind": "identifier",
        "text": "UITextSearchAggregator"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UITextSearchAggregator"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "UITextSearchAggregator"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UITextSearchAggregator"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To track text ranges that match the search, call these methods on the aggregator for the searchable object implementing the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol for a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchingFindSession",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-c.protocol": {
      "abstract": [
        {
          "text": "The methods you use on a find session’s aggregator to collect matching text ranges for a search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextSearchAggregator"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-c.protocol",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextSearchAggregator",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchaggregator-c.protocol"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-c.protocol/allFoundRanges": {
      "abstract": [
        {
          "text": "An ordered set of all the text ranges that match the search.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "allFoundRanges"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-c.protocol/allFoundRanges",
      "kind": "symbol",
      "role": "symbol",
      "title": "allFoundRanges",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchaggregator-c.protocol/allfoundranges"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-c.protocol/finishedSearching": {
      "abstract": [
        {
          "text": "Finishes the search for text ranges.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "finishedSearching"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-c.protocol/finishedSearching",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "finishedSearching"
        }
      ],
      "role": "symbol",
      "title": "finishedSearching",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchaggregator-c.protocol/finishedsearching"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-c.protocol/foundRange:forSearchString:inDocument:": {
      "abstract": [
        {
          "text": "Adds a text range to the set of matches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "foundRange:forSearchString:inDocument:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-c.protocol/foundRange:forSearchString:inDocument:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "foundRange:forSearchString:inDocument:"
        }
      ],
      "role": "symbol",
      "title": "foundRange:forSearchString:inDocument:",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchaggregator-c.protocol/foundrange:forsearchstring:indocument:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-c.protocol/invalidate": {
      "abstract": [
        {
          "text": "Invalidates all currently shown ranges.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "invalidate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-c.protocol/invalidate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "invalidate"
        }
      ],
      "role": "symbol",
      "title": "invalidate",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchaggregator-c.protocol/invalidate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-c.protocol/invalidateFoundRange:inDocument:": {
      "abstract": [
        {
          "text": "Removes a text range from the set of matches.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "invalidateFoundRange:inDocument:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-c.protocol/invalidateFoundRange:inDocument:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "invalidateFoundRange:inDocument:"
        }
      ],
      "role": "symbol",
      "title": "invalidateFoundRange:inDocument:",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchaggregator-c.protocol/invalidatefoundrange:indocument:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchDocumentIdentifier": {
      "abstract": [
        {
          "text": "A string that uniquely identifies a specific document when searching for matching text across multiple documents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextSearchDocumentIdentifier"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchDocumentIdentifier",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextSearchDocumentIdentifier",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchdocumentidentifier"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq": {
      "abstract": [
        {
          "text": "The methods you use on a find session’s searchable objects to perform search operations and decorate the found text results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UITextSearching"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITextSearching",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearching-53wjq"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/compareFoundRange:toRange:inDocument:": {
      "abstract": [
        {
          "text": "Compares ranges from the set of matches the aggregator provides to determine navigation order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "compareFoundRange:toRange:inDocument:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/compareFoundRange:toRange:inDocument:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "compareFoundRange:toRange:inDocument:"
        }
      ],
      "role": "symbol",
      "title": "compareFoundRange:toRange:inDocument:",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearching-53wjq/comparefoundrange:torange:indocument:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/compareOrderFromDocument:toDocument:": {
      "abstract": [
        {
          "text": "Compares documents containing matching ranges from the set the aggregator provides to determine navigation order.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "compareOrderFromDocument:toDocument:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/compareOrderFromDocument:toDocument:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "compareOrderFromDocument:toDocument:"
        }
      ],
      "role": "symbol",
      "title": "compareOrderFromDocument:toDocument:",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearching-53wjq/compareorderfromdocument:todocument:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/performTextSearchWithQueryString:usingOptions:resultAggregator:": {
      "abstract": [
        {
          "text": "Searches for ranges of text matching the string across all searchable documents and collects results in the aggregator.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "performTextSearchWithQueryString:usingOptions:resultAggregator:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/performTextSearchWithQueryString:usingOptions:resultAggregator:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "performTextSearchWithQueryString:usingOptions:resultAggregator:"
        }
      ],
      "role": "symbol",
      "title": "performTextSearchWithQueryString:usingOptions:resultAggregator:",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearching-53wjq/performtextsearchwithquerystring:usingoptions:resultaggregator:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextSearchingFindSession": {
      "abstract": [
        {
          "text": "A find session object that wraps a searchable object implementing the text-searching protocol.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextSearchingFindSession"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextSearchingFindSession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextSearchingFindSession"
        }
      ],
      "role": "symbol",
      "title": "UITextSearchingFindSession",
      "type": "topic",
      "url": "/documentation/uikit/uitextsearchingfindsession"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Handling-searches",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/performTextSearchWithQueryString:usingOptions:resultAggregator:",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/compareFoundRange:toRange:inDocument:",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearching-53wjq/compareOrderFromDocument:toDocument:",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchDocumentIdentifier"
      ],
      "title": "Handling searches"
    }
  ],
  "topicSections": [
    {
      "anchor": "Tracking-search-results",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-c.protocol/foundRange:forSearchString:inDocument:",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-c.protocol/invalidateFoundRange:inDocument:",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-c.protocol/invalidate",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-c.protocol/finishedSearching",
        "doc://com.apple.uikit/documentation/UIKit/UITextSearchAggregator-c.protocol/allFoundRanges"
      ],
      "title": "Tracking search results"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchingFindSession/title",
          "value": "UITextSearchingFindSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchingFindSession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchingFindSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextSearchingFindSession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextSearchingFindSession"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitextsearchaggregator-c.protocol"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
