{"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UITextDroppable","interfaceLanguage":"swift"},"seeAlsoSections":[{"title":"Text view additions","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate","doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate","doc://com.apple.uikit/documentation/UIKit/UITextDraggable","doc://com.apple.uikit/documentation/UIKit/UITextDragOptions","doc://com.apple.uikit/documentation/UIKit/UITextDropEditability"],"anchor":"Text-view-additions"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uitextdroppable"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uitextdroppable"]}],"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"topicSections":[{"title":"Checking the text drop activity status","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextDroppable/isTextDropActive"],"anchor":"Checking-the-text-drop-activity-status"},{"title":"Managing the text drop interaction","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextDroppable/textDropInteraction"],"anchor":"Managing-the-text-drop-interaction"},{"title":"Setting the text drop delegate","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextDroppable/textDropDelegate"],"anchor":"Setting-the-text-drop-delegate"}],"metadata":{"modules":[{"name":"UIKit"}],"navigatorTitle":[{"kind":"identifier","text":"UITextDroppable"}],"symbolKind":"protocol","title":"UITextDroppable","roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITextDroppable","kind":"identifier"}],"platforms":[{"beta":false,"name":"iOS","unavailable":false,"deprecated":false,"introducedAt":"11.0"},{"beta":false,"name":"iPadOS","unavailable":false,"deprecated":false,"introducedAt":"11.0"},{"beta":false,"name":"Mac Catalyst","unavailable":false,"deprecated":false,"introducedAt":"13.1"},{"beta":false,"name":"visionOS","unavailable":false,"deprecated":false,"introducedAt":"1.0"}],"role":"symbol","externalID":"c:objc(pl)UITextDroppable"},"abstract":[{"type":"text","text":"The interface that determines if a text view is a drop destination."}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/c:objc(pl)NSObject","doc://com.apple.uikit/documentation/UIKit/UIKeyInput","doc://com.apple.uikit/documentation/UIKit/UIPasteConfigurationSupporting","doc://com.apple.uikit/documentation/UIKit/UITextInput","doc://com.apple.uikit/documentation/UIKit/UITextInputTraits","doc://com.apple.uikit/documentation/UIKit/UITextPasteConfigurationSupporting"]},{"title":"Conforming Types","type":"conformingTypes","kind":"relationships","identifiers":["doc://com.apple.uikit/documentation/UIKit/UISearchTextField","doc://com.apple.uikit/documentation/UIKit/UITextField","doc://com.apple.uikit/documentation/UIKit/UITextView"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITextDroppable","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"UITextInput","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UITextInput","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextInput"},{"text":", ","kind":"text"},{"text":"UITextPasteConfigurationSupporting","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UITextPasteConfigurationSupporting","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextPasteConfigurationSupporting"}]}]}],"references":{"doc://com.apple.uikit/documentation/UIKit/UITextDraggable":{"role":"symbol","type":"topic","title":"UITextDraggable","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UITextDraggable"}],"url":"/documentation/uikit/uitextdraggable","abstract":[{"type":"text","text":"The interface that determines if a text view is a drag source."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextDraggable"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDraggable"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITextInput":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextInput","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextInput"}],"title":"UITextInput","abstract":[{"type":"text","text":"A set of methods for interacting with the text input system and enabling features in documents."}],"url":"/documentation/uikit/uitextinput","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UITextInput"}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITextPasteConfigurationSupporting":{"kind":"symbol","role":"symbol","title":"UITextPasteConfigurationSupporting","navigatorTitle":[{"text":"UITextPasteConfigurationSupporting","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITextPasteConfigurationSupporting","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextPasteConfigurationSupporting","url":"/documentation/uikit/uitextpasteconfigurationsupporting","abstract":[{"text":"The interface for text-oriented responder objects to participate in the unified paste and drop system in iOS.","type":"text"}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITextView":{"navigatorTitle":[{"text":"UITextView","kind":"identifier"}],"title":"UITextView","url":"/documentation/uikit/uitextview","abstract":[{"text":"A scrollable, multiline text region.","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITextView","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextView"},"doc://com.apple.uikit/documentation/UIKit/UITextInputTraits":{"abstract":[{"type":"text","text":"A set of methods that defines features for keyboard input to a text object."}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextInputTraits","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextInputTraits"}],"title":"UITextInputTraits","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UITextInputTraits"}],"type":"topic","url":"/documentation/uikit/uitextinputtraits"},"doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate":{"url":"/documentation/uikit/uitextdragdelegate","abstract":[{"type":"text","text":"The interface for customizing the behavior of a drag activity for a text view."}],"role":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate","kind":"symbol","title":"UITextDragDelegate","navigatorTitle":[{"kind":"identifier","text":"UITextDragDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextDragDelegate"}]},"doc://com.apple.uikit/documentation/UIKit/UIPasteConfigurationSupporting":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIPasteConfigurationSupporting","kind":"identifier"}],"navigatorTitle":[{"text":"UIPasteConfigurationSupporting","kind":"identifier"}],"title":"UIPasteConfigurationSupporting","identifier":"doc://com.apple.uikit/documentation/UIKit/UIPasteConfigurationSupporting","type":"topic","url":"/documentation/uikit/uipasteconfigurationsupporting","kind":"symbol","abstract":[{"text":"The interface that determines whether a responder object supports paste configuration.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UITextField":{"abstract":[{"text":"An object that displays an editable text area in your interface.","type":"text"}],"url":"/documentation/uikit/uitextfield","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextField","title":"UITextField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextField"}],"navigatorTitle":[{"kind":"identifier","text":"UITextField"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITextDroppable/isTextDropActive":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDroppable/isTextDropActive","navigatorTitle":[{"text":"textDropActive","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"/documentation/uikit/uitextdroppable/istextdropactive","required":true,"type":"topic","title":"isTextDropActive","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isTextDropActive","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"A Boolean value that indicates whether the text view has at least one active drop session."}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITextDroppable/textDropInteraction":{"title":"textDropInteraction","role":"symbol","abstract":[{"text":"The drop interaction object added by UIKit to the text view.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDroppable/textDropInteraction","url":"/documentation/uikit/uitextdroppable/textdropinteraction","required":true,"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textDropInteraction","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIDropInteraction","preciseIdentifier":"c:objc(cs)UIDropInteraction","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"textDropInteraction","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UITextDroppable/textDropDelegate":{"url":"/documentation/uikit/uitextdroppable/textdropdelegate","abstract":[{"type":"text","text":"The text drop delegate for interacting with a drop activity in the text view."}],"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textDropDelegate","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UITextDropDelegate","text":"UITextDropDelegate","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"title":"textDropDelegate","type":"topic","navigatorTitle":[{"text":"textDropDelegate","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDroppable/textDropDelegate","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITextDroppable":{"role":"symbol","type":"topic","title":"UITextDroppable","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UITextDroppable"}],"url":"/documentation/uikit/uitextdroppable","abstract":[{"type":"text","text":"The interface that determines if a text view is a drop destination."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextDroppable"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDroppable"},"doc://com.apple.uikit/documentation/UIKit/UITextDragOptions":{"url":"/documentation/uikit/uitextdragoptions","abstract":[{"type":"text","text":"A set of options that determine the behavior of a draggable text view."}],"role":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDragOptions","kind":"symbol","title":"UITextDragOptions","navigatorTitle":[{"kind":"identifier","text":"UITextDragOptions"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextDragOptions"}]},"doc://com.apple.uikit/documentation/UIKit/UIKeyInput":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIKeyInput","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIKeyInput"}],"type":"topic","title":"UIKeyInput","url":"/documentation/uikit/uikeyinput","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIKeyInput"}],"role":"symbol","abstract":[{"type":"text","text":"A set of methods a responder uses to implement simple text entry."}]},"doc://com.apple.uikit/documentation/UIKit/UISearchTextField":{"type":"topic","url":"/documentation/uikit/uisearchtextfield","identifier":"doc://com.apple.uikit/documentation/UIKit/UISearchTextField","kind":"symbol","navigatorTitle":[{"text":"UISearchTextField","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UISearchTextField","kind":"identifier"}],"title":"UISearchTextField","abstract":[{"type":"text","text":"A view for displaying and editing text and search tokens."}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITextDropEditability":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"UITextDropEditability","kind":"identifier"}],"title":"UITextDropEditability","kind":"symbol","role":"symbol","type":"topic","url":"/documentation/uikit/uitextdropeditability","navigatorTitle":[{"text":"UITextDropEditability","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDropEditability","abstract":[{"text":"The text-drop editability styles for noneditable text views.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"UITextDropDelegate"}],"url":"/documentation/uikit/uitextdropdelegate","identifier":"doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate","title":"UITextDropDelegate","role":"symbol","kind":"symbol","abstract":[{"text":"The interface for configuring a text view’s drop behavior.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITextDropDelegate"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"title":"NSObjectProtocol","type":"topic","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","role":"symbol","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"kind":"symbol","url":"/documentation/objectivec/nsobjectprotocol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"introducedAt":"11.0","unavailable":false,"name":"iOS","beta":false,"deprecated":false},{"introducedAt":"11.0","unavailable":false,"name":"iPadOS","beta":false,"deprecated":false},{"introducedAt":"13.1","unavailable":false,"name":"Mac Catalyst","beta":false,"deprecated":false},{"introducedAt":"1.0","unavailable":false,"name":"visionOS","beta":false,"deprecated":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Protocol","op":"replace","path":"/metadata/roleHeading"},{"value":"UITextDroppable","op":"replace","path":"/metadata/title"},{"value":"protocol","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"identifier","text":"UITextDroppable"}],"op":"replace","path":"/metadata/fragments"},{"op":"replace","path":"/metadata/navigatorTitle","value":[{"text":"UITextDroppable","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]}},{"op":"replace","path":"/topicSections","value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextDroppable/isTextDropActive"],"anchor":"Checking-the-text-drop-activity-status","title":"Checking the text drop activity status"},{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextDroppable/textDropInteraction"],"anchor":"Managing-the-text-drop-interaction","title":"Managing the text drop interaction"},{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextDroppable/textDropDelegate"],"anchor":"Setting-the-text-drop-delegate","title":"Setting the text drop delegate"}]},{"op":"replace","path":"/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextInput","doc://com.apple.uikit/documentation/UIKit/UITextPasteConfigurationSupporting"],"type":"inheritsFrom"},{"title":"Conforming Types","kind":"relationships","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextField","doc://com.apple.uikit/documentation/UIKit/UITextView"],"type":"conformingTypes"}]},{"op":"replace","path":"/seeAlsoSections","value":[{"generated":true,"anchor":"Text-view-additions","title":"Text view additions","identifiers":["doc://com.apple.uikit/documentation/UIKit/UITextDragDelegate","doc://com.apple.uikit/documentation/UIKit/UITextDropDelegate","doc://com.apple.uikit/documentation/UIKit/UITextDraggable","doc://com.apple.uikit/documentation/UIKit/UITextDragOptions","doc://com.apple.uikit/documentation/UIKit/UITextDropEditability"]}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITextDroppable","kind":"identifier"},{"text":" <","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextInput","text":"UITextInput","preciseIdentifier":"c:objc(pl)UITextInput","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UITextPasteConfigurationSupporting","text":"UITextPasteConfigurationSupporting","preciseIdentifier":"c:objc(pl)UITextPasteConfigurationSupporting","kind":"typeIdentifier"},{"text":">","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDraggable/title","op":"replace","value":"UITextDraggable"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDraggable/fragments","op":"replace","value":[{"text":"UITextDraggable","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDraggable/navigatorTitle","op":"replace","value":[{"text":"UITextDraggable","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInput/title","op":"replace","value":"UITextInput"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInput/fragments","op":"replace","value":[{"kind":"identifier","text":"UITextInput"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInput/navigatorTitle","op":"replace","value":[{"text":"UITextInput","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextPasteConfigurationSupporting/title","op":"replace","value":"UITextPasteConfigurationSupporting"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextPasteConfigurationSupporting/fragments","op":"replace","value":[{"text":"UITextPasteConfigurationSupporting","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextPasteConfigurationSupporting/navigatorTitle","op":"replace","value":[{"text":"UITextPasteConfigurationSupporting","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextView/title","op":"replace","value":"UITextView"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextView/fragments","op":"replace","value":[{"kind":"identifier","text":"UITextView"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextView/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UITextView"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputTraits/title","op":"replace","value":"UITextInputTraits"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputTraits/fragments","op":"replace","value":[{"text":"UITextInputTraits","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextInputTraits/navigatorTitle","op":"replace","value":[{"text":"UITextInputTraits","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragDelegate/title","op":"replace","value":"UITextDragDelegate"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragDelegate/fragments","op":"replace","value":[{"kind":"identifier","text":"UITextDragDelegate"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragDelegate/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UITextDragDelegate"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteConfigurationSupporting/title","op":"replace","value":"UIPasteConfigurationSupporting"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteConfigurationSupporting/fragments","op":"replace","value":[{"kind":"identifier","text":"UIPasteConfigurationSupporting"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteConfigurationSupporting/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UIPasteConfigurationSupporting"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextField/title","op":"replace","value":"UITextField"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextField/fragments","op":"replace","value":[{"text":"UITextField","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextField/navigatorTitle","op":"replace","value":[{"text":"UITextField","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDroppable~1isTextDropActive/title","op":"replace","value":"textDropActive"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDroppable~1isTextDropActive/fragments","op":"replace","value":[{"text":"textDropActive","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDroppable~1textDropInteraction/title","op":"replace","value":"textDropInteraction"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDroppable~1textDropInteraction/fragments","op":"replace","value":[{"text":"textDropInteraction","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDroppable~1textDropDelegate/title","op":"replace","value":"textDropDelegate"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDroppable~1textDropDelegate/fragments","op":"replace","value":[{"text":"textDropDelegate","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDroppable/title","op":"replace","value":"UITextDroppable"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDroppable/fragments","op":"replace","value":[{"text":"UITextDroppable","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDroppable/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UITextDroppable"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragOptions/title","op":"replace","value":"UITextDragOptions"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragOptions/fragments","op":"replace","value":[{"text":"UITextDragOptions","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDragOptions/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UITextDragOptions"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyInput/title","op":"replace","value":"UIKeyInput"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyInput/fragments","op":"replace","value":[{"text":"UIKeyInput","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIKeyInput/navigatorTitle","op":"replace","value":[{"text":"UIKeyInput","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchTextField/title","op":"replace","value":"UISearchTextField"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchTextField/fragments","op":"replace","value":[{"text":"UISearchTextField","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchTextField/navigatorTitle","op":"replace","value":[{"text":"UISearchTextField","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropEditability/title","op":"replace","value":"UITextDropEditability"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropEditability/fragments","op":"replace","value":[{"text":"UITextDropEditability","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropEditability/navigatorTitle","op":"replace","value":[{"text":"UITextDropEditability","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropDelegate/title","op":"replace","value":"UITextDropDelegate"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropDelegate/fragments","op":"replace","value":[{"kind":"identifier","text":"UITextDropDelegate"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextDropDelegate/navigatorTitle","op":"replace","value":[{"text":"UITextDropDelegate","kind":"identifier"}]},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title","op":"replace","value":"NSObject"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}