{
  "abstract": [
    {
      "text": "The interface for handling pasting and dropping of text, using item providers.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITextPasteDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UITextPasteDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UITextPasteDelegate"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UITextPasteDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "11.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "UITextPasteDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UITextPasteDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchTextFieldPasteItem": {
      "abstract": [
        {
          "text": "A protocol that supports pasting tokens.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISearchTextFieldPasteItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchTextFieldPasteItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISearchTextFieldPasteItem"
        }
      ],
      "role": "symbol",
      "title": "UISearchTextFieldPasteItem",
      "type": "topic",
      "url": "/documentation/uikit/uisearchtextfieldpasteitem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextPasteConfigurationSupporting": {
      "abstract": [
        {
          "text": "The interface for text-oriented responder objects to participate in the unified paste and drop system in iOS.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextPasteConfigurationSupporting"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextPasteConfigurationSupporting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextPasteConfigurationSupporting"
        }
      ],
      "role": "symbol",
      "title": "UITextPasteConfigurationSupporting",
      "type": "topic",
      "url": "/documentation/uikit/uitextpasteconfigurationsupporting"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextPasteDelegate": {
      "abstract": [
        {
          "text": "The interface for handling pasting and dropping of text, using item providers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextPasteDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextPasteDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextPasteDelegate"
        }
      ],
      "role": "symbol",
      "title": "UITextPasteDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uitextpastedelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextPasteDelegate/textPasteConfigurationSupporting(_:combineItemAttributedStrings:for:)": {
      "abstract": [
        {
          "text": "Asks the delegate to combine multiple strings into a single attributed string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textPasteConfigurationSupporting"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITextPasteConfigurationSupporting",
          "text": "UITextPasteConfigurationSupporting"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "combineItemAttributedStrings"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextRange",
          "text": "UITextRange"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextPasteDelegate/textPasteConfigurationSupporting(_:combineItemAttributedStrings:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textPasteConfigurationSupporting:combineItemAttributedStrings:forRange:"
        }
      ],
      "role": "symbol",
      "title": "textPasteConfigurationSupporting(_:combineItemAttributedStrings:for:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextpastedelegate/textpasteconfigurationsupporting(_:combineitemattributedstrings:for:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextPasteDelegate/textPasteConfigurationSupporting(_:performPasteOf:to:)": {
      "abstract": [
        {
          "text": "Asks the delegate to explicitly handle the final incorporation of a pasted or dropped string of text into the text view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textPasteConfigurationSupporting"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITextPasteConfigurationSupporting",
          "text": "UITextPasteConfigurationSupporting"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "performPasteOf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextRange",
          "text": "UITextRange"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextRange",
          "text": "UITextRange"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextPasteDelegate/textPasteConfigurationSupporting(_:performPasteOf:to:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textPasteConfigurationSupporting:performPasteOfAttributedString:toRange:"
        }
      ],
      "role": "symbol",
      "title": "textPasteConfigurationSupporting(_:performPasteOf:to:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextpastedelegate/textpasteconfigurationsupporting(_:performpasteof:to:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextPasteDelegate/textPasteConfigurationSupporting(_:shouldAnimatePasteOf:to:)": {
      "abstract": [
        {
          "text": "Asks the delegate if the paste or drop operation should be animated.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textPasteConfigurationSupporting"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITextPasteConfigurationSupporting",
          "text": "UITextPasteConfigurationSupporting"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shouldAnimatePasteOf"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSAttributedString",
          "text": "NSAttributedString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITextRange",
          "text": "UITextRange"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextPasteDelegate/textPasteConfigurationSupporting(_:shouldAnimatePasteOf:to:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textPasteConfigurationSupporting:shouldAnimatePasteOfAttributedString:toRange:"
        }
      ],
      "role": "symbol",
      "title": "textPasteConfigurationSupporting(_:shouldAnimatePasteOf:to:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextpastedelegate/textpasteconfigurationsupporting(_:shouldanimatepasteof:to:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextPasteDelegate/textPasteConfigurationSupporting(_:transform:)": {
      "abstract": [
        {
          "text": "Tells the delegate to transform the pasted or dropped text item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "textPasteConfigurationSupporting"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITextPasteConfigurationSupporting",
          "text": "UITextPasteConfigurationSupporting"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "transform"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UITextPasteItem",
          "text": "UITextPasteItem"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextPasteDelegate/textPasteConfigurationSupporting(_:transform:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "textPasteConfigurationSupporting:transformPasteItem:"
        }
      ],
      "role": "symbol",
      "title": "textPasteConfigurationSupporting(_:transform:)",
      "type": "topic",
      "url": "/documentation/uikit/uitextpastedelegate/textpasteconfigurationsupporting(_:transform:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITextPasteItem": {
      "abstract": [
        {
          "text": "The interface for obtaining information about, and interacting with, a text item for pasting or dropping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITextPasteItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITextPasteItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITextPasteItem"
        }
      ],
      "role": "symbol",
      "title": "UITextPasteItem",
      "type": "topic",
      "url": "/documentation/uikit/uitextpasteitem"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Pasteboard-support",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextPasteItem",
        "doc://com.apple.uikit/documentation/UIKit/UISearchTextFieldPasteItem",
        "doc://com.apple.uikit/documentation/UIKit/UITextPasteConfigurationSupporting"
      ],
      "title": "Pasteboard support"
    }
  ],
  "topicSections": [
    {
      "anchor": "Preparing-to-paste-a-text-paste-item",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextPasteDelegate/textPasteConfigurationSupporting(_:transform:)"
      ],
      "title": "Preparing to paste a text paste item"
    },
    {
      "anchor": "Pasting-the-text-paste-item",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextPasteDelegate/textPasteConfigurationSupporting(_:combineItemAttributedStrings:for:)",
        "doc://com.apple.uikit/documentation/UIKit/UITextPasteDelegate/textPasteConfigurationSupporting(_:performPasteOf:to:)"
      ],
      "title": "Pasting the text paste item"
    },
    {
      "anchor": "Animating-the-paste-operation",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITextPasteDelegate/textPasteConfigurationSupporting(_:shouldAnimatePasteOf:to:)"
      ],
      "title": "Animating the paste operation"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UITextPasteDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextPasteDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextPasteDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Preparing-to-paste-a-text-paste-item",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextPasteDelegate/textPasteConfigurationSupporting(_:transform:)"
              ],
              "title": "Preparing to paste a text paste item"
            },
            {
              "anchor": "Pasting-the-text-paste-item",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextPasteDelegate/textPasteConfigurationSupporting(_:combineItemAttributedStrings:for:)",
                "doc://com.apple.uikit/documentation/UIKit/UITextPasteDelegate/textPasteConfigurationSupporting(_:performPasteOf:to:)"
              ],
              "title": "Pasting the text paste item"
            },
            {
              "anchor": "Animating-the-paste-operation",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextPasteDelegate/textPasteConfigurationSupporting(_:shouldAnimatePasteOf:to:)"
              ],
              "title": "Animating the paste operation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Pasteboard-support",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITextPasteItem",
                "doc://com.apple.uikit/documentation/UIKit/UISearchTextFieldPasteItem",
                "doc://com.apple.uikit/documentation/UIKit/UITextPasteConfigurationSupporting"
              ],
              "title": "Pasteboard support"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UITextPasteDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextPasteDelegate~1textPasteConfigurationSupporting(_:performPasteOf:to:)/title",
          "value": "textPasteConfigurationSupporting:performPasteOfAttributedString:toRange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextPasteDelegate~1textPasteConfigurationSupporting(_:performPasteOf:to:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textPasteConfigurationSupporting:performPasteOfAttributedString:toRange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextPasteDelegate/title",
          "value": "UITextPasteDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextPasteDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextPasteDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextPasteDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextPasteDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextPasteDelegate~1textPasteConfigurationSupporting(_:transform:)/title",
          "value": "textPasteConfigurationSupporting:transformPasteItem:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextPasteDelegate~1textPasteConfigurationSupporting(_:transform:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textPasteConfigurationSupporting:transformPasteItem:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextPasteDelegate~1textPasteConfigurationSupporting(_:combineItemAttributedStrings:for:)/title",
          "value": "textPasteConfigurationSupporting:combineItemAttributedStrings:forRange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextPasteDelegate~1textPasteConfigurationSupporting(_:combineItemAttributedStrings:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textPasteConfigurationSupporting:combineItemAttributedStrings:forRange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextPasteDelegate~1textPasteConfigurationSupporting(_:shouldAnimatePasteOf:to:)/title",
          "value": "textPasteConfigurationSupporting:shouldAnimatePasteOfAttributedString:toRange:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextPasteDelegate~1textPasteConfigurationSupporting(_:shouldAnimatePasteOf:to:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "textPasteConfigurationSupporting:shouldAnimatePasteOfAttributedString:toRange:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextPasteItem/title",
          "value": "UITextPasteItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextPasteItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextPasteItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextPasteItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextPasteItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextPasteConfigurationSupporting/title",
          "value": "UITextPasteConfigurationSupporting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextPasteConfigurationSupporting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextPasteConfigurationSupporting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITextPasteConfigurationSupporting/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITextPasteConfigurationSupporting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchTextFieldPasteItem/title",
          "value": "UISearchTextFieldPasteItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchTextFieldPasteItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchTextFieldPasteItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchTextFieldPasteItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchTextFieldPasteItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitextpastedelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uitextpastedelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
