{
  "abstract": [
    {
      "text": "States that determine visibility of the title in the title bar.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITitlebarTitleVisibility"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UITitlebarTitleVisibility",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UITitlebarTitleVisibility"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UITitlebarTitleVisibility"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "UITitlebarTitleVisibility"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UITitlebarTitleVisibility"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITitlebar/representedURL": {
      "abstract": [
        {
          "text": "A URL of the file or resource represented in the window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "representedURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITitlebar/representedURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "representedURL"
        }
      ],
      "role": "symbol",
      "title": "representedURL",
      "type": "topic",
      "url": "/documentation/uikit/uititlebar/representedurl"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITitlebar/separatorStyle": {
      "abstract": [
        {
          "text": "The type of separator that the app displays between the title bar and content of a window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "separatorStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UITitlebarSeparatorStyle",
          "text": "UITitlebarSeparatorStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITitlebar/separatorStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "separatorStyle"
        }
      ],
      "role": "symbol",
      "title": "separatorStyle",
      "type": "topic",
      "url": "/documentation/uikit/uititlebar/separatorstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITitlebar/titleVisibility": {
      "abstract": [
        {
          "text": "A value that indicates the visibility of the title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "titleVisibility"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UITitlebarTitleVisibility",
          "text": "UITitlebarTitleVisibility"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITitlebar/titleVisibility",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "titleVisibility"
        }
      ],
      "role": "symbol",
      "title": "titleVisibility",
      "type": "topic",
      "url": "/documentation/uikit/uititlebar/titlevisibility"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITitlebarSeparatorStyle": {
      "abstract": [
        {
          "text": "Styles that determine the type of separator displayed between the title bar and content of a window.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITitlebarSeparatorStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITitlebarSeparatorStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITitlebarSeparatorStyle"
        }
      ],
      "role": "symbol",
      "title": "UITitlebarSeparatorStyle",
      "type": "topic",
      "url": "/documentation/uikit/uititlebarseparatorstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITitlebarTitleVisibility": {
      "abstract": [
        {
          "text": "States that determine visibility of the title in the title bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITitlebarTitleVisibility"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITitlebarTitleVisibility",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITitlebarTitleVisibility"
        }
      ],
      "role": "symbol",
      "title": "UITitlebarTitleVisibility",
      "type": "topic",
      "url": "/documentation/uikit/uititlebartitlevisibility"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITitlebarTitleVisibility/hidden": {
      "abstract": [
        {
          "text": "A state indicating that the title isn’t visible in the title bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hidden"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITitlebarTitleVisibility/hidden",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITitlebarTitleVisibilityHidden"
        }
      ],
      "role": "symbol",
      "title": "UITitlebarTitleVisibility.hidden",
      "type": "topic",
      "url": "/documentation/uikit/uititlebartitlevisibility/hidden"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITitlebarTitleVisibility/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITitlebarTitleVisibility/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/uititlebartitlevisibility/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITitlebarTitleVisibility/visible": {
      "abstract": [
        {
          "text": "A state indicating that the title is visible in the title bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "visible"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITitlebarTitleVisibility/visible",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITitlebarTitleVisibilityVisible"
        }
      ],
      "role": "symbol",
      "title": "UITitlebarTitleVisibility.visible",
      "type": "topic",
      "url": "/documentation/uikit/uititlebartitlevisibility/visible"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuring-the-title-bar",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITitlebar/separatorStyle",
        "doc://com.apple.uikit/documentation/UIKit/UITitlebarSeparatorStyle",
        "doc://com.apple.uikit/documentation/UIKit/UITitlebar/titleVisibility",
        "doc://com.apple.uikit/documentation/UIKit/UITitlebar/representedURL"
      ],
      "title": "Configuring the title bar"
    }
  ],
  "topicSections": [
    {
      "anchor": "Visibility-states",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITitlebarTitleVisibility/visible",
        "doc://com.apple.uikit/documentation/UIKit/UITitlebarTitleVisibility/hidden"
      ],
      "title": "Visibility states"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITitlebarTitleVisibility/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UITitlebarTitleVisibility"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITitlebarTitleVisibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITitlebarTitleVisibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Visibility-states",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITitlebarTitleVisibility/visible",
                "doc://com.apple.uikit/documentation/UIKit/UITitlebarTitleVisibility/hidden"
              ],
              "title": "Visibility states"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Configuring-the-title-bar",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITitlebar/separatorStyle",
                "doc://com.apple.uikit/documentation/UIKit/UITitlebarSeparatorStyle",
                "doc://com.apple.uikit/documentation/UIKit/UITitlebar/titleVisibility",
                "doc://com.apple.uikit/documentation/UIKit/UITitlebar/representedURL"
              ],
              "title": "Configuring the title bar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UITitlebarTitleVisibility"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarTitleVisibility/title",
          "value": "UITitlebarTitleVisibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarTitleVisibility/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITitlebarTitleVisibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarTitleVisibility/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITitlebarTitleVisibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebar~1separatorStyle/title",
          "value": "separatorStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebar~1separatorStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "separatorStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebar~1representedURL/title",
          "value": "representedURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebar~1representedURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "representedURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarTitleVisibility~1hidden/title",
          "value": "UITitlebarTitleVisibilityHidden"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarTitleVisibility~1hidden/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITitlebarTitleVisibilityHidden"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebar~1titleVisibility/title",
          "value": "titleVisibility"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebar~1titleVisibility/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "titleVisibility"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarTitleVisibility~1visible/title",
          "value": "UITitlebarTitleVisibilityVisible"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarTitleVisibility~1visible/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITitlebarTitleVisibilityVisible"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarSeparatorStyle/title",
          "value": "UITitlebarSeparatorStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarSeparatorStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITitlebarSeparatorStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITitlebarSeparatorStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITitlebarSeparatorStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uititlebartitlevisibility"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uititlebartitlevisibility"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
