{
  "abstract": [
    {
      "text": "An interface for providing the timing information needed to perform animations.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UITimingCurveProvider",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UITimingCurveProvider"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UITimingCurveProvider"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "UITimingCurveProvider"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UITimingCurveProvider"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSCoding",
              "text": "NSCoding"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSCopying",
              "text": "NSCopying"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An object that adopts the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol provides the timing information needed to perform animations with a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewPropertyAnimator",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object. A timing curve defines the velocity at which animated properties change to their new values over the duration of the animation. A custom timing curve provider can specify timing using the built-in UIKit curves, a cubic Bézier curve, a spring-based timing function, or a combination of timing information.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "When implementing this protocol in a custom object, you must provide implementations for all of the properties. Use the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider/timingCurveType",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property to specify which timing information your object provides. Configure the other properties with the actual timing curve values.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICubicTimingParameters": {
      "abstract": [
        {
          "text": "The timing information for animations in the form of a cubic Bézier curve.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UICubicTimingParameters"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICubicTimingParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UICubicTimingParameters"
        }
      ],
      "role": "symbol",
      "title": "UICubicTimingParameters",
      "type": "topic",
      "url": "/documentation/uikit/uicubictimingparameters"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISpringTimingParameters": {
      "abstract": [
        {
          "text": "The timing information for animations that mimics the behavior of a spring.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISpringTimingParameters"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISpringTimingParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISpringTimingParameters"
        }
      ],
      "role": "symbol",
      "title": "UISpringTimingParameters",
      "type": "topic",
      "url": "/documentation/uikit/uispringtimingparameters"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider": {
      "abstract": [
        {
          "text": "An interface for providing the timing information needed to perform animations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITimingCurveProvider"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITimingCurveProvider"
        }
      ],
      "role": "symbol",
      "title": "UITimingCurveProvider",
      "type": "topic",
      "url": "/documentation/uikit/uitimingcurveprovider"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider/cubicTimingParameters": {
      "abstract": [
        {
          "text": "The cubic timing parameters to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cubicTimingParameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UICubicTimingParameters",
          "text": "UICubicTimingParameters"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider/cubicTimingParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cubicTimingParameters"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "cubicTimingParameters",
      "type": "topic",
      "url": "/documentation/uikit/uitimingcurveprovider/cubictimingparameters"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider/springTimingParameters": {
      "abstract": [
        {
          "text": "The spring-based timing parameters to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "springTimingParameters"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISpringTimingParameters",
          "text": "UISpringTimingParameters"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider/springTimingParameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "springTimingParameters"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "springTimingParameters",
      "type": "topic",
      "url": "/documentation/uikit/uitimingcurveprovider/springtimingparameters"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider/timingCurveType": {
      "abstract": [
        {
          "text": "The type of timing information to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "timingCurveType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UITimingCurveType",
          "text": "UITimingCurveType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider/timingCurveType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "timingCurveType"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "timingCurveType",
      "type": "topic",
      "url": "/documentation/uikit/uitimingcurveprovider/timingcurvetype"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITimingCurveType": {
      "abstract": [
        {
          "text": "Constants indicating the type of timing information to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITimingCurveType"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITimingCurveType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITimingCurveType"
        }
      ],
      "role": "symbol",
      "title": "UITimingCurveType",
      "type": "topic",
      "url": "/documentation/uikit/uitimingcurvetype"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewPropertyAnimator": {
      "abstract": [
        {
          "text": "A class that animates changes to views and allows the dynamic modification of those animations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewPropertyAnimator"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewPropertyAnimator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewPropertyAnimator"
        }
      ],
      "role": "symbol",
      "title": "UIViewPropertyAnimator",
      "type": "topic",
      "url": "/documentation/uikit/uiviewpropertyanimator"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICubicTimingParameters",
        "doc://com.apple.uikit/documentation/UIKit/UISpringTimingParameters"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Timing-curves",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISpringTimingParameters",
        "doc://com.apple.uikit/documentation/UIKit/UICubicTimingParameters"
      ],
      "title": "Timing curves"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-timing-information",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider/timingCurveType",
        "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider/cubicTimingParameters",
        "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider/springTimingParameters"
      ],
      "title": "Getting the timing information"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UITimingCurveType"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UITimingCurveProvider"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITimingCurveProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITimingCurveProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-the-timing-information",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider/timingCurveType",
                "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider/cubicTimingParameters",
                "doc://com.apple.uikit/documentation/UIKit/UITimingCurveProvider/springTimingParameters"
              ],
              "title": "Getting the timing information"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UITimingCurveType"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UICubicTimingParameters",
                "doc://com.apple.uikit/documentation/UIKit/UISpringTimingParameters"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Timing-curves",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UISpringTimingParameters",
                "doc://com.apple.uikit/documentation/UIKit/UICubicTimingParameters"
              ],
              "title": "Timing curves"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UITimingCurveProvider"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSCoding",
                    "text": "NSCoding"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSCopying",
                    "text": "NSCopying"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITimingCurveProvider~1cubicTimingParameters/title",
          "value": "cubicTimingParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITimingCurveProvider~1cubicTimingParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cubicTimingParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITimingCurveProvider/title",
          "value": "UITimingCurveProvider"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITimingCurveProvider/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITimingCurveProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITimingCurveProvider/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITimingCurveProvider"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewPropertyAnimator/title",
          "value": "UIViewPropertyAnimator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewPropertyAnimator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewPropertyAnimator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewPropertyAnimator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewPropertyAnimator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITimingCurveType/title",
          "value": "UITimingCurveType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITimingCurveType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITimingCurveType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITimingCurveType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITimingCurveType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITimingCurveProvider~1timingCurveType/title",
          "value": "timingCurveType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITimingCurveProvider~1timingCurveType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "timingCurveType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITimingCurveProvider~1springTimingParameters/title",
          "value": "springTimingParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITimingCurveProvider~1springTimingParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "springTimingParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISpringTimingParameters/title",
          "value": "UISpringTimingParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISpringTimingParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISpringTimingParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISpringTimingParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISpringTimingParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICubicTimingParameters/title",
          "value": "UICubicTimingParameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICubicTimingParameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UICubicTimingParameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UICubicTimingParameters/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UICubicTimingParameters"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uitimingcurveprovider"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uitimingcurveprovider"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
