{
  "abstract": [
    {
      "text": "An object that defines specific phases of the UI update process.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIUpdateActionPhase",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIUpdateActionPhase"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIUpdateActionPhase"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "UIUpdateActionPhase"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIUpdateActionPhase"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Each UI update consists of several phases that run in a consistent order, and the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object defines constants that represent these phases. When using a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateLink",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", you can use these constants to decide which phase of the UI update process you want its actions to run in.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "There are two ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "phase groups",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": ": standard and low-latency. The standard phase group runs for each UI update. This phase group includes these phases, which run in the following order:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeEventDispatch",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterEventDispatch",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeCADisplayLinkDispatch",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterCADisplayLinkDispatch",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeCATransactionCommit",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterCATransactionCommit",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "The low-latency phase group is optional, and it’s off by default. It runs only if you explicitly request low-latency event dispatch using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateLink/wantsLowLatencyEventDispatch",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". The low-latency phase group includes these phases, which run in the following order (after the standard phases):",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeLowLatencyEventDispatch",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterLowLatencyEventDispatch",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeLowLatencyCATransactionCommit",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterLowLatencyCATransactionCommit",
                      "isActive": true,
                      "type": "reference"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "orderedList"
        },
        {
          "inlineContent": [
            {
              "text": "When a phase group runs, all phases inside the group run. Phases run one after another in the specified order without exiting back into the run loop.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase": {
      "abstract": [
        {
          "text": "An object that defines specific phases of the UI update process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIUpdateActionPhase"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUpdateActionPhase"
        }
      ],
      "role": "symbol",
      "title": "UIUpdateActionPhase",
      "type": "topic",
      "url": "/documentation/uikit/uiupdateactionphase"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterCADisplayLinkDispatch": {
      "abstract": [
        {
          "text": "A phase that runs after Core Animation display link callbacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "afterCADisplayLinkDispatch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIUpdateActionPhase",
          "text": "UIUpdateActionPhase"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterCADisplayLinkDispatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "afterCADisplayLinkDispatch"
        }
      ],
      "role": "symbol",
      "title": "afterCADisplayLinkDispatch",
      "type": "topic",
      "url": "/documentation/uikit/uiupdateactionphase/aftercadisplaylinkdispatch"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterCATransactionCommit": {
      "abstract": [
        {
          "text": "A phase that runs after a Core Animation transaction commit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "afterCATransactionCommit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIUpdateActionPhase",
          "text": "UIUpdateActionPhase"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterCATransactionCommit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "afterCATransactionCommit"
        }
      ],
      "role": "symbol",
      "title": "afterCATransactionCommit",
      "type": "topic",
      "url": "/documentation/uikit/uiupdateactionphase/aftercatransactioncommit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterEventDispatch": {
      "abstract": [
        {
          "text": "A phase that runs after standard event handlers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "afterEventDispatch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIUpdateActionPhase",
          "text": "UIUpdateActionPhase"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterEventDispatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "afterEventDispatch"
        }
      ],
      "role": "symbol",
      "title": "afterEventDispatch",
      "type": "topic",
      "url": "/documentation/uikit/uiupdateactionphase/aftereventdispatch"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterLowLatencyCATransactionCommit": {
      "abstract": [
        {
          "text": "A phase that runs after a Core Animation transaction commit for a low-latency event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "afterLowLatencyCATransactionCommit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIUpdateActionPhase",
          "text": "UIUpdateActionPhase"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterLowLatencyCATransactionCommit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "afterLowLatencyCATransactionCommit"
        }
      ],
      "role": "symbol",
      "title": "afterLowLatencyCATransactionCommit",
      "type": "topic",
      "url": "/documentation/uikit/uiupdateactionphase/afterlowlatencycatransactioncommit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterLowLatencyEventDispatch": {
      "abstract": [
        {
          "text": "A phase that runs after low-latency event handlers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "afterLowLatencyEventDispatch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIUpdateActionPhase",
          "text": "UIUpdateActionPhase"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterLowLatencyEventDispatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "afterLowLatencyEventDispatch"
        }
      ],
      "role": "symbol",
      "title": "afterLowLatencyEventDispatch",
      "type": "topic",
      "url": "/documentation/uikit/uiupdateactionphase/afterlowlatencyeventdispatch"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterUpdateComplete": {
      "abstract": [
        {
          "text": "A phase that runs at the end of a UI update.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "afterUpdateComplete"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIUpdateActionPhase",
          "text": "UIUpdateActionPhase"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterUpdateComplete",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "afterUpdateComplete"
        }
      ],
      "role": "symbol",
      "title": "afterUpdateComplete",
      "type": "topic",
      "url": "/documentation/uikit/uiupdateactionphase/afterupdatecomplete"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterUpdateScheduled": {
      "abstract": [
        {
          "text": "A phase that runs after the scheduling of a UI update.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "afterUpdateScheduled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIUpdateActionPhase",
          "text": "UIUpdateActionPhase"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterUpdateScheduled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "afterUpdateScheduled"
        }
      ],
      "role": "symbol",
      "title": "afterUpdateScheduled",
      "type": "topic",
      "url": "/documentation/uikit/uiupdateactionphase/afterupdatescheduled"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeCADisplayLinkDispatch": {
      "abstract": [
        {
          "text": "A phase that runs before Core Animation display link callbacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beforeCADisplayLinkDispatch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIUpdateActionPhase",
          "text": "UIUpdateActionPhase"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeCADisplayLinkDispatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beforeCADisplayLinkDispatch"
        }
      ],
      "role": "symbol",
      "title": "beforeCADisplayLinkDispatch",
      "type": "topic",
      "url": "/documentation/uikit/uiupdateactionphase/beforecadisplaylinkdispatch"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeCATransactionCommit": {
      "abstract": [
        {
          "text": "A phase that runs before a Core Animation transaction commit.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beforeCATransactionCommit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIUpdateActionPhase",
          "text": "UIUpdateActionPhase"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeCATransactionCommit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beforeCATransactionCommit"
        }
      ],
      "role": "symbol",
      "title": "beforeCATransactionCommit",
      "type": "topic",
      "url": "/documentation/uikit/uiupdateactionphase/beforecatransactioncommit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeEventDispatch": {
      "abstract": [
        {
          "text": "A phase that runs before standard event handlers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beforeEventDispatch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIUpdateActionPhase",
          "text": "UIUpdateActionPhase"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeEventDispatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beforeEventDispatch"
        }
      ],
      "role": "symbol",
      "title": "beforeEventDispatch",
      "type": "topic",
      "url": "/documentation/uikit/uiupdateactionphase/beforeeventdispatch"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeLowLatencyCATransactionCommit": {
      "abstract": [
        {
          "text": "A phase that runs before a Core Animation transaction commit for a low-latency event.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beforeLowLatencyCATransactionCommit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIUpdateActionPhase",
          "text": "UIUpdateActionPhase"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeLowLatencyCATransactionCommit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beforeLowLatencyCATransactionCommit"
        }
      ],
      "role": "symbol",
      "title": "beforeLowLatencyCATransactionCommit",
      "type": "topic",
      "url": "/documentation/uikit/uiupdateactionphase/beforelowlatencycatransactioncommit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeLowLatencyEventDispatch": {
      "abstract": [
        {
          "text": "A phase that runs before low-latency event handlers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beforeLowLatencyEventDispatch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIUpdateActionPhase",
          "text": "UIUpdateActionPhase"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeLowLatencyEventDispatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beforeLowLatencyEventDispatch"
        }
      ],
      "role": "symbol",
      "title": "beforeLowLatencyEventDispatch",
      "type": "topic",
      "url": "/documentation/uikit/uiupdateactionphase/beforelowlatencyeventdispatch"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUpdateInfo": {
      "abstract": [
        {
          "text": "An object that contains detailed information about the current UI update state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIUpdateInfo"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUpdateInfo"
        }
      ],
      "role": "symbol",
      "title": "UIUpdateInfo",
      "type": "topic",
      "url": "/documentation/uikit/uiupdateinfo"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUpdateLink": {
      "abstract": [
        {
          "text": "An object you use to observe, participate in, and affect the UI update process.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIUpdateLink"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateLink",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUpdateLink"
        }
      ],
      "role": "symbol",
      "title": "UIUpdateLink",
      "type": "topic",
      "url": "/documentation/uikit/uiupdatelink"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUpdateLink/wantsLowLatencyEventDispatch": {
      "abstract": [
        {
          "text": "A Boolean value that determines whether the UI update link requests dispatch of low-latency eligible events.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wantsLowLatencyEventDispatch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUpdateLink/wantsLowLatencyEventDispatch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "wantsLowLatencyEventDispatch"
        }
      ],
      "role": "symbol",
      "title": "wantsLowLatencyEventDispatch",
      "type": "topic",
      "url": "/documentation/uikit/uiupdatelink/wantslowlatencyeventdispatch"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "UI-updates",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIUpdateLink",
        "doc://com.apple.uikit/documentation/UIKit/UIUpdateInfo"
      ],
      "title": "UI updates"
    }
  ],
  "topicSections": [
    {
      "anchor": "Phases",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterUpdateScheduled",
        "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeEventDispatch",
        "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterEventDispatch",
        "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeCADisplayLinkDispatch",
        "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterCADisplayLinkDispatch",
        "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeCATransactionCommit",
        "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterCATransactionCommit",
        "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeLowLatencyEventDispatch",
        "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterLowLatencyEventDispatch",
        "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeLowLatencyCATransactionCommit",
        "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterLowLatencyCATransactionCommit",
        "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterUpdateComplete"
      ],
      "title": "Phases"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIUpdateActionPhase"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUpdateActionPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUpdateActionPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Phases",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterUpdateScheduled",
                "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeEventDispatch",
                "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterEventDispatch",
                "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeCADisplayLinkDispatch",
                "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterCADisplayLinkDispatch",
                "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeCATransactionCommit",
                "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterCATransactionCommit",
                "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeLowLatencyEventDispatch",
                "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterLowLatencyEventDispatch",
                "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/beforeLowLatencyCATransactionCommit",
                "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterLowLatencyCATransactionCommit",
                "doc://com.apple.uikit/documentation/UIKit/UIUpdateActionPhase/afterUpdateComplete"
              ],
              "title": "Phases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "UI-updates",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIUpdateLink",
                "doc://com.apple.uikit/documentation/UIKit/UIUpdateInfo"
              ],
              "title": "UI updates"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIUpdateActionPhase"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateLink/title",
          "value": "UIUpdateLink"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateLink/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUpdateLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateLink/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUpdateLink"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1afterUpdateScheduled/title",
          "value": "afterUpdateScheduled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1afterUpdateScheduled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "afterUpdateScheduled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1afterLowLatencyCATransactionCommit/title",
          "value": "afterLowLatencyCATransactionCommit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1afterLowLatencyCATransactionCommit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "afterLowLatencyCATransactionCommit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1afterLowLatencyEventDispatch/title",
          "value": "afterLowLatencyEventDispatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1afterLowLatencyEventDispatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "afterLowLatencyEventDispatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1beforeCATransactionCommit/title",
          "value": "beforeCATransactionCommit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1beforeCATransactionCommit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "beforeCATransactionCommit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1beforeLowLatencyCATransactionCommit/title",
          "value": "beforeLowLatencyCATransactionCommit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1beforeLowLatencyCATransactionCommit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "beforeLowLatencyCATransactionCommit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase/title",
          "value": "UIUpdateActionPhase"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUpdateActionPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUpdateActionPhase"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1afterEventDispatch/title",
          "value": "afterEventDispatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1afterEventDispatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "afterEventDispatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1afterCATransactionCommit/title",
          "value": "afterCATransactionCommit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1afterCATransactionCommit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "afterCATransactionCommit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1afterCADisplayLinkDispatch/title",
          "value": "afterCADisplayLinkDispatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1afterCADisplayLinkDispatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "afterCADisplayLinkDispatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1beforeEventDispatch/title",
          "value": "beforeEventDispatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1beforeEventDispatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "beforeEventDispatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1beforeCADisplayLinkDispatch/title",
          "value": "beforeCADisplayLinkDispatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1beforeCADisplayLinkDispatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "beforeCADisplayLinkDispatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateLink~1wantsLowLatencyEventDispatch/title",
          "value": "wantsLowLatencyEventDispatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateLink~1wantsLowLatencyEventDispatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "wantsLowLatencyEventDispatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1afterUpdateComplete/title",
          "value": "afterUpdateComplete"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1afterUpdateComplete/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "afterUpdateComplete"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1beforeLowLatencyEventDispatch/title",
          "value": "beforeLowLatencyEventDispatch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateActionPhase~1beforeLowLatencyEventDispatch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "beforeLowLatencyEventDispatch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateInfo/title",
          "value": "UIUpdateInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUpdateInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUpdateInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUpdateInfo"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiupdateactionphase"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiupdateactionphase"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
