{
  "abstract": [
    {
      "text": "A custom action that your app can perform in response to a remote or local notification.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.documentation/documentation/UserNotifications/UNNotificationAction",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIUserNotificationAction",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIUserNotificationAction"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIUserNotificationAction"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.0",
        "introducedAt": "8.0",
        "message": "Use UserNotifications Framework's UNNotificationAction",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "10.0",
        "introducedAt": "8.0",
        "message": "Use UserNotifications Framework's UNNotificationAction",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "Use UserNotifications Framework's UNNotificationAction",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "UIUserNotificationAction"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIUserNotificationAction"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When a notification is delivered, the system displays a button for each custom action associated with the notification. Tapping a button launches your app (either in the foreground or background) and gives you a chance to perform the indicated action. You use this class to specify the text that is displayed in the button and the information your app needs to perform the corresponding action.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Typically, you create an instance of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableUserNotificationAction",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class instead of this class. You use the mutable object to configure the action and then call the setActions:forContext: method of UIMutableUserNotificationActionSettings to add the resulting actions to a group.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For each action you define, you must specify whether execution of that action requires the app to be running in the foreground or background. You can also specify whether the device must be unlocked or can remain locked while the action is performed. Unlocking the device may be necessary if the action involves reading or writing files that are encrypted on disk using the system’s data protection mechanism. When the user selects an action, the system puts your app into the appropriate mode and calls your app delegate’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleActionWithIdentifier:forRemoteNotification:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " or ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleActionWithIdentifier:for:completionHandler:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method to perform the action.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/UserNotifications/UNNotificationAction": {
      "abstract": [
        {
          "text": "A task your app performs in response to a notification that the system delivers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UNNotificationAction"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UserNotifications/UNNotificationAction",
      "kind": "symbol",
      "role": "symbol",
      "title": "UNNotificationAction",
      "type": "topic",
      "url": "/documentation/UserNotifications/UNNotificationAction"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAcceleration": {
      "abstract": [
        {
          "text": "An acceleration event that represents immediate, three-dimensional acceleration data.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIAcceleration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAcceleration",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAcceleration",
      "type": "topic",
      "url": "/documentation/uikit/uiacceleration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccelerometer": {
      "abstract": [
        {
          "text": "An object that lets you register to receive acceleration-related data from the onboard hardware.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIAccelerometer"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccelerometer",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAccelerometer",
      "type": "topic",
      "url": "/documentation/uikit/uiaccelerometer"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActionSheet": {
      "abstract": [
        {
          "text": "A view that presents a set of alternatives for how to proceed with a task.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIActionSheet"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActionSheet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIActionSheet"
        }
      ],
      "role": "symbol",
      "title": "UIActionSheet",
      "type": "topic",
      "url": "/documentation/uikit/uiactionsheet"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAlertView": {
      "abstract": [
        {
          "text": "A view that displays an alert message.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAlertView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAlertView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAlertView"
        }
      ],
      "role": "symbol",
      "title": "UIAlertView",
      "type": "topic",
      "url": "/documentation/uikit/uialertview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleActionWithIdentifier:for:completionHandler:)": {
      "abstract": [
        {
          "text": "Called when your app has been activated because user selected a custom action from the alert panel of a local notification.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "application"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIApplication",
          "text": "UIApplication"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "handleActionWithIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UILocalNotification",
          "text": "UILocalNotification"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleActionWithIdentifier:for:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "application:handleActionWithIdentifier:forLocalNotification:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "application(_:handleActionWithIdentifier:for:completionHandler:)",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationdelegate/application(_:handleactionwithidentifier:for:completionhandler:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleActionWithIdentifier:forRemoteNotification:completionHandler:)": {
      "abstract": [
        {
          "text": "Tells the app delegate to perform the custom action specified by a remote notification.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "application"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIApplication",
          "text": "UIApplication"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "handleActionWithIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "forRemoteNotification"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": () -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIApplicationDelegate/application(_:handleActionWithIdentifier:forRemoteNotification:completionHandler:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "application:handleActionWithIdentifier:forRemoteNotification:completionHandler:"
        }
      ],
      "role": "symbol",
      "title": "application(_:handleActionWithIdentifier:forRemoteNotification:completionHandler:)",
      "type": "topic",
      "url": "/documentation/uikit/uiapplicationdelegate/application(_:handleactionwithidentifier:forremotenotification:completionhandler:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIDocumentMenuViewController": {
      "abstract": [
        {
          "text": "A list of all the available document providers for a given file type and mode, in addition to custom menu items that you add.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIDocumentMenuViewController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIDocumentMenuViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIDocumentMenuViewController"
        }
      ],
      "role": "symbol",
      "title": "UIDocumentMenuViewController",
      "type": "topic",
      "url": "/documentation/uikit/uidocumentmenuviewcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UILocalNotification": {
      "abstract": [
        {
          "text": "A notification that an app can schedule for presentation at a specific date and time.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UILocalNotification"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UILocalNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UILocalNotification"
        }
      ],
      "role": "symbol",
      "title": "UILocalNotification",
      "type": "topic",
      "url": "/documentation/uikit/uilocalnotification"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMenuController": {
      "abstract": [
        {
          "text": "The menu interface for the Cut, Copy, Paste, Select, Select All, and Delete commands.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIMenuController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMenuController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIMenuController"
        }
      ],
      "role": "symbol",
      "title": "UIMenuController",
      "type": "topic",
      "url": "/documentation/uikit/uimenucontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMenuItem": {
      "abstract": [
        {
          "text": "A custom item in the editing menu managed by the menu controller.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIMenuItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMenuItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIMenuItem"
        }
      ],
      "role": "symbol",
      "title": "UIMenuItem",
      "type": "topic",
      "url": "/documentation/uikit/uimenuitem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableUserNotificationAction": {
      "abstract": [
        {
          "text": "A modifiable version of the user notification action class.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIMutableUserNotificationAction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableUserNotificationAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIMutableUserNotificationAction"
        }
      ],
      "role": "symbol",
      "title": "UIMutableUserNotificationAction",
      "type": "topic",
      "url": "/documentation/uikit/uimutableusernotificationaction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIMutableUserNotificationCategory": {
      "abstract": [
        {
          "text": "Information about custom actions that your app can perform in response to a local or push notification.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIMutableUserNotificationCategory"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIMutableUserNotificationCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIMutableUserNotificationCategory"
        }
      ],
      "role": "symbol",
      "title": "UIMutableUserNotificationCategory",
      "type": "topic",
      "url": "/documentation/uikit/uimutableusernotificationcategory"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPopoverController": {
      "abstract": [
        {
          "text": "An object that manages the presentation of content in a popover.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPopoverController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPopoverController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPopoverController"
        }
      ],
      "role": "symbol",
      "title": "UIPopoverController",
      "type": "topic",
      "url": "/documentation/uikit/uipopovercontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPreviewAction": {
      "abstract": [
        {
          "text": "A preview action, or ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "peek quick action",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ", that displays below a peek when a user swipes the peek upward.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPreviewAction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPreviewAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPreviewAction"
        }
      ],
      "role": "symbol",
      "title": "UIPreviewAction",
      "type": "topic",
      "url": "/documentation/uikit/uipreviewaction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPreviewActionGroup": {
      "abstract": [
        {
          "text": "A group of one or more child quick actions, each an instance of the preview action class.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPreviewActionGroup"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPreviewActionGroup",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPreviewActionGroup"
        }
      ],
      "role": "symbol",
      "title": "UIPreviewActionGroup",
      "type": "topic",
      "url": "/documentation/uikit/uipreviewactiongroup"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchDisplayController": {
      "abstract": [
        {
          "text": "An object that manages the display of a search bar, along with a table view that displays search results.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISearchDisplayController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchDisplayController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISearchDisplayController"
        }
      ],
      "role": "symbol",
      "title": "UISearchDisplayController",
      "type": "topic",
      "url": "/documentation/uikit/uisearchdisplaycontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIStoryboardPopoverSegue": {
      "abstract": [
        {
          "text": "A specific type of segue for presenting content in a popover.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIStoryboardPopoverSegue"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIStoryboardPopoverSegue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIStoryboardPopoverSegue"
        }
      ],
      "role": "symbol",
      "title": "UIStoryboardPopoverSegue",
      "type": "topic",
      "url": "/documentation/uikit/uistoryboardpopoversegue"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction": {
      "abstract": [
        {
          "text": "A custom action that your app can perform in response to a remote or local notification.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIUserNotificationAction"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserNotificationAction"
        }
      ],
      "role": "symbol",
      "title": "UIUserNotificationAction",
      "type": "topic",
      "url": "/documentation/uikit/uiusernotificationaction"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/activationMode": {
      "abstract": [
        {
          "text": "The mode in which to run the app when the action is performed.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "activationMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIUserNotificationActivationMode",
          "text": "UIUserNotificationActivationMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/activationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "activationMode"
        }
      ],
      "role": "symbol",
      "title": "activationMode",
      "type": "topic",
      "url": "/documentation/uikit/uiusernotificationaction/activationmode"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/behavior": {
      "abstract": [
        {
          "text": "The custom behavior (if any) that the action supports.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "behavior"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIUserNotificationActionBehavior",
          "text": "UIUserNotificationActionBehavior"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/behavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "behavior"
        }
      ],
      "role": "symbol",
      "title": "behavior",
      "type": "topic",
      "url": "/documentation/uikit/uiusernotificationaction/behavior"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/identifier": {
      "abstract": [
        {
          "text": "The string that you use internally to identify the action.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/identifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "identifier"
        }
      ],
      "role": "symbol",
      "title": "identifier",
      "type": "topic",
      "url": "/documentation/uikit/uiusernotificationaction/identifier"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/init()": {
      "abstract": [
        {
          "text": "Creates a user notification action.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/init()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "init"
        }
      ],
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/uikit/uiusernotificationaction/init()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/init(coder:)": {
      "abstract": [
        {
          "text": "Creates a user notification action from data in an unarchiver.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "coder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCoder",
          "text": "NSCoder"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/init(coder:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCoder:"
        }
      ],
      "role": "symbol",
      "title": "init(coder:)",
      "type": "topic",
      "url": "/documentation/uikit/uiusernotificationaction/init(coder:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/isAuthenticationRequired": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the user must unlock the device before the action is performed.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isAuthenticationRequired"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/isAuthenticationRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "authenticationRequired"
        }
      ],
      "role": "symbol",
      "title": "isAuthenticationRequired",
      "type": "topic",
      "url": "/documentation/uikit/uiusernotificationaction/isauthenticationrequired"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/isDestructive": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the action is destructive.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isDestructive"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/isDestructive",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "destructive"
        }
      ],
      "role": "symbol",
      "title": "isDestructive",
      "type": "topic",
      "url": "/documentation/uikit/uiusernotificationaction/isdestructive"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/parameters": {
      "abstract": [
        {
          "text": "A dictionary of additional parameters to include with the action.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "parameters"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/parameters",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "parameters"
        }
      ],
      "role": "symbol",
      "title": "parameters",
      "type": "topic",
      "url": "/documentation/uikit/uiusernotificationaction/parameters"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/title": {
      "abstract": [
        {
          "text": "The localized string to use as the button title for the action.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "title"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/title",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "title"
        }
      ],
      "role": "symbol",
      "title": "title",
      "type": "topic",
      "url": "/documentation/uikit/uiusernotificationaction/title"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationActionBehavior": {
      "abstract": [
        {
          "text": "Constants indicating additional behavior that the action supports.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIUserNotificationActionBehavior"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationActionBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserNotificationActionBehavior"
        }
      ],
      "role": "symbol",
      "title": "UIUserNotificationActionBehavior",
      "type": "topic",
      "url": "/documentation/uikit/uiusernotificationactionbehavior"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationActivationMode": {
      "abstract": [
        {
          "text": "Constants indicating whether the app should activate to the foreground or background.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIUserNotificationActivationMode"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationActivationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserNotificationActivationMode"
        }
      ],
      "role": "symbol",
      "title": "UIUserNotificationActivationMode",
      "type": "topic",
      "url": "/documentation/uikit/uiusernotificationactivationmode"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationCategory": {
      "abstract": [
        {
          "text": "Information about custom actions that your app can perform in response to a local or push notification.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIUserNotificationCategory"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationCategory",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserNotificationCategory"
        }
      ],
      "role": "symbol",
      "title": "UIUserNotificationCategory",
      "type": "topic",
      "url": "/documentation/uikit/uiusernotificationcategory"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationSettings": {
      "abstract": [
        {
          "text": "The types of notifications that can be displayed to the user by your app.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIUserNotificationSettings"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationSettings",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserNotificationSettings"
        }
      ],
      "role": "symbol",
      "title": "UIUserNotificationSettings",
      "type": "topic",
      "url": "/documentation/uikit/uiusernotificationsettings"
    },
    "doc://com.apple.uikit/documentation/UIKit/action-parameter-key": {
      "abstract": [
        {
          "text": "Key to include among the parameters of the action.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/action-parameter-key",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Action Parameter Key",
      "type": "topic",
      "url": "/documentation/uikit/action-parameter-key"
    },
    "doc://com.apple.uikit/documentation/UIKit/behavior-key": {
      "abstract": [
        {
          "text": "Key related to action-related behaviors.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/behavior-key",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Behavior Key",
      "type": "topic",
      "url": "/documentation/uikit/behavior-key"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying": {
      "abstract": [
        {
          "text": "A protocol that objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCopying",
      "type": "topic",
      "url": "/documentation/foundation/nscopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSMutableCopying": {
      "abstract": [
        {
          "text": "A protocol that mutable objects adopt to provide functional copies of themselves.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSMutableCopying"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSMutableCopying",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSMutableCopying",
      "type": "topic",
      "url": "/documentation/foundation/nsmutablecopying"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding": {
      "abstract": [
        {
          "text": "A protocol that enables encoding and decoding in a manner that is robust against object substitution attacks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSSecureCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSSecureCoding",
      "type": "topic",
      "url": "/documentation/foundation/nssecurecoding"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIMutableUserNotificationAction"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSMutableCopying",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-classes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIActionSheet",
        "doc://com.apple.uikit/documentation/UIKit/UIAlertView",
        "doc://com.apple.uikit/documentation/UIKit/UIDocumentMenuViewController",
        "doc://com.apple.uikit/documentation/UIKit/UILocalNotification",
        "doc://com.apple.uikit/documentation/UIKit/UIMenuController",
        "doc://com.apple.uikit/documentation/UIKit/UIMenuItem",
        "doc://com.apple.uikit/documentation/UIKit/UIMutableUserNotificationAction",
        "doc://com.apple.uikit/documentation/UIKit/UIMutableUserNotificationCategory",
        "doc://com.apple.uikit/documentation/UIKit/UIPopoverController",
        "doc://com.apple.uikit/documentation/UIKit/UIPreviewAction",
        "doc://com.apple.uikit/documentation/UIKit/UIPreviewActionGroup",
        "doc://com.apple.uikit/documentation/UIKit/UISearchDisplayController",
        "doc://com.apple.uikit/documentation/UIKit/UIStoryboardPopoverSegue",
        "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationCategory",
        "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationSettings"
      ],
      "title": "Deprecated classes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-the-action",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/init()",
        "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/init(coder:)"
      ],
      "title": "Creating the action"
    },
    {
      "anchor": "Getting-the-action-information",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/identifier",
        "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/title"
      ],
      "title": "Getting the action information"
    },
    {
      "anchor": "Getting-the-actions-configuration",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/activationMode",
        "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/isAuthenticationRequired",
        "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/isDestructive",
        "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/behavior",
        "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/parameters"
      ],
      "title": "Getting the action’s configuration"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationActivationMode",
        "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationActionBehavior",
        "doc://com.apple.uikit/documentation/UIKit/action-parameter-key",
        "doc://com.apple.uikit/documentation/UIKit/behavior-key"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.0",
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "10.0",
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Class"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIUserNotificationAction"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "class"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserNotificationAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserNotificationAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-the-action",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/init()",
                "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/init(coder:)"
              ],
              "title": "Creating the action"
            },
            {
              "anchor": "Getting-the-action-information",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/identifier",
                "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/title"
              ],
              "title": "Getting the action information"
            },
            {
              "anchor": "Getting-the-actions-configuration",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/activationMode",
                "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/isAuthenticationRequired",
                "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/isDestructive",
                "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/behavior",
                "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationAction/parameters"
              ],
              "title": "Getting the action’s configuration"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationActivationMode",
                "doc://com.apple.uikit/documentation/UIKit/UIUserNotificationActionBehavior",
                "doc://com.apple.uikit/documentation/UIKit/action-parameter-key",
                "doc://com.apple.uikit/documentation/UIKit/behavior-key"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIMutableUserNotificationAction"
              ],
              "kind": "relationships",
              "title": "Inherited By",
              "type": "inheritedBy"
            },
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSCopying",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSMutableCopying",
                "doc://com.externally.resolved.symbol/c:objc(pl)NSSecureCoding"
              ],
              "kind": "relationships",
              "title": "Conforms To",
              "type": "conformsTo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Deprecated-classes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIAcceleration",
                "doc://com.apple.uikit/documentation/UIKit/UIAccelerometer",
                "doc://com.apple.uikit/documentation/UIKit/UIActionSheet",
                "doc://com.apple.uikit/documentation/UIKit/UIAlertView",
                "doc://com.apple.uikit/documentation/UIKit/UIDocumentMenuViewController",
                "doc://com.apple.uikit/documentation/UIKit/UILocalNotification",
                "doc://com.apple.uikit/documentation/UIKit/UIMenuController",
                "doc://com.apple.uikit/documentation/UIKit/UIMenuItem",
                "doc://com.apple.uikit/documentation/UIKit/UIMutableUserNotificationAction",
                "doc://com.apple.uikit/documentation/UIKit/UIMutableUserNotificationCategory",
                "doc://com.apple.uikit/documentation/UIKit/UIPopoverController",
                "doc://com.apple.uikit/documentation/UIKit/UIPreviewAction",
                "doc://com.apple.uikit/documentation/UIKit/UIPreviewActionGroup",
                "doc://com.apple.uikit/documentation/UIKit/UISearchDisplayController",
                "doc://com.apple.uikit/documentation/UIKit/UIStoryboardPopoverSegue"
              ],
              "title": "Deprecated classes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@interface"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIUserNotificationAction"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSObject",
                    "text": "NSObject"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/UserNotifications/UNNotificationAction",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationSettings/title",
          "value": "UIUserNotificationSettings"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationSettings/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserNotificationSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationSettings/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserNotificationSettings"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationAction~1init(coder:)/title",
          "value": "initWithCoder:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationAction~1init(coder:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithCoder:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILocalNotification/title",
          "value": "UILocalNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILocalNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UILocalNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UILocalNotification/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UILocalNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationAction~1isAuthenticationRequired/title",
          "value": "authenticationRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationAction~1isAuthenticationRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "authenticationRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationAction~1isDestructive/title",
          "value": "destructive"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationAction~1isDestructive/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "destructive"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationActionBehavior/title",
          "value": "UIUserNotificationActionBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationActionBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserNotificationActionBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationActionBehavior/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserNotificationActionBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMutableUserNotificationCategory/title",
          "value": "UIMutableUserNotificationCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMutableUserNotificationCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMutableUserNotificationCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMutableUserNotificationCategory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMutableUserNotificationCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMutableUserNotificationAction/title",
          "value": "UIMutableUserNotificationAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMutableUserNotificationAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMutableUserNotificationAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMutableUserNotificationAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMutableUserNotificationAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationAction~1parameters/title",
          "value": "parameters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationAction~1parameters/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "parameters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:handleActionWithIdentifier:for:completionHandler:)/title",
          "value": "application:handleActionWithIdentifier:forLocalNotification:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:handleActionWithIdentifier:for:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "application:handleActionWithIdentifier:forLocalNotification:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationAction~1identifier/title",
          "value": "identifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationAction~1identifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "identifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheet/title",
          "value": "UIActionSheet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActionSheet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheet/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActionSheet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStoryboardPopoverSegue/title",
          "value": "UIStoryboardPopoverSegue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStoryboardPopoverSegue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIStoryboardPopoverSegue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStoryboardPopoverSegue/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIStoryboardPopoverSegue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchDisplayController/title",
          "value": "UISearchDisplayController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchDisplayController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchDisplayController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchDisplayController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchDisplayController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPreviewActionGroup/title",
          "value": "UIPreviewActionGroup"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPreviewActionGroup/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPreviewActionGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPreviewActionGroup/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPreviewActionGroup"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationCategory/title",
          "value": "UIUserNotificationCategory"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationCategory/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserNotificationCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationCategory/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserNotificationCategory"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationAction/title",
          "value": "UIUserNotificationAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserNotificationAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserNotificationAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationAction~1behavior/title",
          "value": "behavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationAction~1behavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "behavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenuController/title",
          "value": "UIMenuController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenuController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMenuController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenuController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMenuController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:handleActionWithIdentifier:forRemoteNotification:completionHandler:)/title",
          "value": "application:handleActionWithIdentifier:forRemoteNotification:completionHandler:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplicationDelegate~1application(_:handleActionWithIdentifier:forRemoteNotification:completionHandler:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "application:handleActionWithIdentifier:forRemoteNotification:completionHandler:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UserNotifications~1UNNotificationAction/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UNNotificationAction"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationActivationMode/title",
          "value": "UIUserNotificationActivationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationActivationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserNotificationActivationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationActivationMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserNotificationActivationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPreviewAction/title",
          "value": "UIPreviewAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPreviewAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPreviewAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPreviewAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPreviewAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentMenuViewController/title",
          "value": "UIDocumentMenuViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentMenuViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocumentMenuViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIDocumentMenuViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIDocumentMenuViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationAction~1activationMode/title",
          "value": "activationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationAction~1activationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "activationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAlertView/title",
          "value": "UIAlertView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAlertView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAlertView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAlertView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAlertView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationAction~1title/title",
          "value": "title"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationAction~1title/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "title"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverController/title",
          "value": "UIPopoverController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPopoverController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPopoverController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationAction~1init()/title",
          "value": "init"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserNotificationAction~1init()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "init"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenuItem/title",
          "value": "UIMenuItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenuItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMenuItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIMenuItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIMenuItem"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiusernotificationaction"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiusernotificationaction"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
