{
  "abstract": [
    {
      "text": "Constants that indicate the interface type for the device or an object that has a trait environment, such as a view and view controller.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIUserInterfaceIdiom",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIUserInterfaceIdiom"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIUserInterfaceIdiom"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "UIUserInterfaceIdiom"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIUserInterfaceIdiom"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom": {
      "abstract": [
        {
          "text": "Constants that indicate the interface type for the device or an object that has a trait environment, such as a view and view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIUserInterfaceIdiom"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserInterfaceIdiom"
        }
      ],
      "role": "symbol",
      "title": "UIUserInterfaceIdiom",
      "type": "topic",
      "url": "/documentation/uikit/uiuserinterfaceidiom"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/carPlay": {
      "abstract": [
        {
          "text": "An interface designed for an in-car experience.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "carPlay"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/carPlay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserInterfaceIdiomCarPlay"
        }
      ],
      "role": "symbol",
      "title": "UIUserInterfaceIdiom.carPlay",
      "type": "topic",
      "url": "/documentation/uikit/uiuserinterfaceidiom/carplay"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/uiuserinterfaceidiom/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/mac": {
      "abstract": [
        {
          "text": "An interface designed for the Mac.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "mac"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/mac",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserInterfaceIdiomMac"
        }
      ],
      "role": "symbol",
      "title": "UIUserInterfaceIdiom.mac",
      "type": "topic",
      "url": "/documentation/uikit/uiuserinterfaceidiom/mac"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/pad": {
      "abstract": [
        {
          "text": "An interface designed for iPad.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pad"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/pad",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserInterfaceIdiomPad"
        }
      ],
      "role": "symbol",
      "title": "UIUserInterfaceIdiom.pad",
      "type": "topic",
      "url": "/documentation/uikit/uiuserinterfaceidiom/pad"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/phone": {
      "abstract": [
        {
          "text": "An interface designed for iPhone and iPod touch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "phone"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/phone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserInterfaceIdiomPhone"
        }
      ],
      "role": "symbol",
      "title": "UIUserInterfaceIdiom.phone",
      "type": "topic",
      "url": "/documentation/uikit/uiuserinterfaceidiom/phone"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/tv": {
      "abstract": [
        {
          "text": "An interface designed for tvOS and Apple TV.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tv"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/tv",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserInterfaceIdiomTV"
        }
      ],
      "role": "symbol",
      "title": "UIUserInterfaceIdiom.tv",
      "type": "topic",
      "url": "/documentation/uikit/uiuserinterfaceidiom/tv"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/unspecified": {
      "abstract": [
        {
          "text": "An unspecified idiom.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unspecified"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/unspecified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserInterfaceIdiomUnspecified"
        }
      ],
      "role": "symbol",
      "title": "UIUserInterfaceIdiom.unspecified",
      "type": "topic",
      "url": "/documentation/uikit/uiuserinterfaceidiom/unspecified"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/vision": {
      "abstract": [
        {
          "text": "An interface designed for visionOS and Apple Vision Pro.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "vision"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/vision",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserInterfaceIdiomVision"
        }
      ],
      "role": "symbol",
      "title": "UIUserInterfaceIdiom.vision",
      "type": "topic",
      "url": "/documentation/uikit/uiuserinterfaceidiom/vision"
    },
    "doc://com.apple.uikit/documentation/UIKit/UI_USER_INTERFACE_IDIOM()": {
      "abstract": [
        {
          "text": "Returns the interface idiom supported by the current device (recommended for apps that run in versions of iOS earlier than 3.2).",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UI_USER_INTERFACE_IDIOM"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIUserInterfaceIdiom",
          "text": "UIUserInterfaceIdiom"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UI_USER_INTERFACE_IDIOM()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UI_USER_INTERFACE_IDIOM"
        }
      ],
      "role": "symbol",
      "title": "UI_USER_INTERFACE_IDIOM()",
      "type": "topic",
      "url": "/documentation/uikit/ui_user_interface_idiom()"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-current-idiom",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UI_USER_INTERFACE_IDIOM()"
      ],
      "title": "Getting the current idiom"
    }
  ],
  "topicSections": [
    {
      "anchor": "Idioms",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/unspecified",
        "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/phone",
        "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/pad",
        "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/tv",
        "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/carPlay",
        "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/mac",
        "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/vision"
      ],
      "title": "Idioms"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIUserInterfaceIdiom"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceIdiom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceIdiom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Idioms",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/unspecified",
                "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/phone",
                "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/pad",
                "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/tv",
                "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/carPlay",
                "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/mac",
                "doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceIdiom/vision"
              ],
              "title": "Idioms"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-current-idiom",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UI_USER_INTERFACE_IDIOM()"
              ],
              "title": "Getting the current idiom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIUserInterfaceIdiom"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceIdiom~1vision/title",
          "value": "UIUserInterfaceIdiomVision"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceIdiom~1vision/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceIdiomVision"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceIdiom~1phone/title",
          "value": "UIUserInterfaceIdiomPhone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceIdiom~1phone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceIdiomPhone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceIdiom~1pad/title",
          "value": "UIUserInterfaceIdiomPad"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceIdiom~1pad/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceIdiomPad"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UI_USER_INTERFACE_IDIOM()/title",
          "value": "UI_USER_INTERFACE_IDIOM"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UI_USER_INTERFACE_IDIOM()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UI_USER_INTERFACE_IDIOM"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceIdiom~1tv/title",
          "value": "UIUserInterfaceIdiomTV"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceIdiom~1tv/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceIdiomTV"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceIdiom~1unspecified/title",
          "value": "UIUserInterfaceIdiomUnspecified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceIdiom~1unspecified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceIdiomUnspecified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceIdiom~1mac/title",
          "value": "UIUserInterfaceIdiomMac"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceIdiom~1mac/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceIdiomMac"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceIdiom/title",
          "value": "UIUserInterfaceIdiom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceIdiom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceIdiom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceIdiom/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceIdiom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceIdiom~1carPlay/title",
          "value": "UIUserInterfaceIdiomCarPlay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceIdiom~1carPlay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserInterfaceIdiomCarPlay"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiuserinterfaceidiom"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiuserinterfaceidiom"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
