{"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIViewConfigurationState","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"},{"content":[{"type":"heading","text":"Overview","anchor":"overview","level":2},{"type":"paragraph","inlineContent":[{"text":"A view configuration state encompasses a trait collection along with all of the common states that affect a view’s appearance — states like selected, focused, or disabled. A view configuration state encapsulates the inputs that configure a view for any possible state or combination of states. You use a view configuration state with background and content configurations to obtain the default appearance for a specific state.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Typically, you don’t create a configuration state yourself. To obtain a configuration state, override the "},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/updateConfiguration(using:)","isActive":true},{"type":"text","text":" method in your view subclass and use the state parameter. Outside of this method, you can get a view’s configuration state by using its "},{"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/configurationState-4u37h","isActive":true},{"type":"text","text":" property."}]},{"type":"paragraph","inlineContent":[{"text":"You can create your own custom states to add to a view configuration state by defining a custom state key using ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIConfigurationStateCustomKey"},{"text":".","type":"text"}]}],"kind":"content"}],"topicSections":[{"anchor":"Managing-view-configuration-states","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-swift.struct/isSelected","doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-swift.struct/isHighlighted","doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-swift.struct/isFocused","doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-swift.struct/isDisabled","doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-swift.struct/isPinned"],"title":"Managing view configuration states"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"text":"UIViewConfigurationState","kind":"identifier"}],"externalID":"s:5UIKit24UIViewConfigurationStateV","title":"UIViewConfigurationState","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIViewConfigurationState","kind":"identifier"}],"symbolKind":"struct","role":"symbol","modules":[{"name":"UIKit"}],"platforms":[{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"14.0","name":"iOS"},{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"14.0","name":"iPadOS"},{"deprecated":false,"beta":false,"unavailable":false,"name":"Mac Catalyst"},{"unavailable":false,"introducedAt":"14.0","deprecated":false,"name":"tvOS","beta":false},{"unavailable":false,"deprecated":false,"name":"visionOS","beta":false}],"roleHeading":"Structure"},"relationshipsSections":[{"type":"conformsTo","identifiers":["doc://com.externally.resolved.symbol/s:s8CopyableP","doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","doc://com.externally.resolved.symbol/s:s17CustomReflectableP","doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-8d7pd"],"title":"Conforms To","kind":"relationships"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-swift.struct"},"seeAlsoSections":[{"anchor":"Configuration-states","identifiers":["doc://com.apple.uikit/documentation/UIKit/UICellConfigurationState-swift.struct","doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-8d7pd","doc://com.apple.uikit/documentation/UIKit/UIConfigurationStateCustomKey"],"title":"Configuration states","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uiviewconfigurationstate-swift.struct"]}],"abstract":[{"type":"text","text":"A structure that encapsulates a view’s state."}],"sections":[],"references":{"doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-swift.struct/isFocused":{"role":"symbol","type":"topic","url":"/documentation/uikit/uiviewconfigurationstate-swift.struct/isfocused","title":"isFocused","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-swift.struct/isFocused","abstract":[{"text":"A Boolean value that indicates whether the view is in a focused state.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFocused","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://com.externally.resolved.symbol/s:SQ":{"abstract":[{"type":"text","text":"A type that can be compared for value equality."}],"url":"/documentation/Swift/Equatable","identifier":"doc://com.externally.resolved.symbol/s:SQ","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"role":"symbol","title":"Equatable","type":"topic","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UICellConfigurationState-swift.struct":{"role":"symbol","url":"/documentation/uikit/uicellconfigurationstate-swift.struct","abstract":[{"text":"A structure that encapsulates a cell’s state.","type":"text"}],"type":"topic","title":"UICellConfigurationState","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UICellConfigurationState","kind":"identifier"}],"navigatorTitle":[{"text":"UICellConfigurationState","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UICellConfigurationState-swift.struct","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/configurationState-4u37h":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configurationState","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:5UIKit24UICellConfigurationStateV","text":"UICellConfigurationState","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/configurationState-4u37h","abstract":[{"text":"The current configuration state of the cell.","type":"text"}],"url":"/documentation/uikit/uicollectionviewcell/configurationstate-4u37h","title":"configurationState"},"doc://com.externally.resolved.symbol/s:SH":{"abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}],"url":"/documentation/Swift/Hashable","identifier":"doc://com.externally.resolved.symbol/s:SH","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hashable","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SQ","text":"Equatable","kind":"typeIdentifier"}],"role":"symbol","title":"Hashable","type":"topic","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-8d7pd":{"role":"symbol","abstract":[{"type":"text","text":"The requirements for an object that encapsulates a view’s state."}],"url":"/documentation/uikit/uiconfigurationstate-8d7pd","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIConfigurationState"}],"title":"UIConfigurationState","navigatorTitle":[{"kind":"identifier","text":"UIConfigurationState"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-8d7pd","kind":"symbol"},"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP":{"identifier":"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","kind":"symbol","type":"topic","title":"CustomStringConvertible","url":"/documentation/Swift/CustomStringConvertible","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomStringConvertible"}],"role":"symbol","abstract":[{"text":"A type with a customized textual representation.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-swift.struct/isSelected":{"role":"symbol","type":"topic","url":"/documentation/uikit/uiviewconfigurationstate-swift.struct/isselected","title":"isSelected","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-swift.struct/isSelected","abstract":[{"text":"A Boolean value that indicates whether the view is in a selected state.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isSelected","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-swift.struct/isHighlighted":{"role":"symbol","type":"topic","url":"/documentation/uikit/uiviewconfigurationstate-swift.struct/ishighlighted","title":"isHighlighted","kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-swift.struct/isHighlighted","abstract":[{"text":"A Boolean value that indicates whether the view is in a highlighted state.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isHighlighted","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/updateConfiguration(using:)":{"abstract":[{"text":"Updates the cell’s configuration using the current state.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"updateConfiguration","kind":"identifier"},{"kind":"text","text":"("},{"text":"using","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UICellConfigurationState","kind":"typeIdentifier","preciseIdentifier":"s:5UIKit24UICellConfigurationStateV"},{"text":")","kind":"text"}],"url":"/documentation/uikit/uicollectionviewcell/updateconfiguration(using:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/updateConfiguration(using:)","kind":"symbol","type":"topic","role":"symbol","title":"updateConfiguration(using:)"},"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP":{"identifier":"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","kind":"symbol","type":"topic","title":"CustomDebugStringConvertible","url":"/documentation/Swift/CustomDebugStringConvertible","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomDebugStringConvertible"}],"role":"symbol","abstract":[{"type":"text","text":"A type with a customized textual representation suitable for debugging purposes."}]},"doc://com.apple.uikit/documentation/UIKit/UIConfigurationStateCustomKey":{"role":"symbol","abstract":[{"type":"text","text":"A key that defines a custom state for a view."}],"url":"/documentation/uikit/uiconfigurationstatecustomkey","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIConfigurationStateCustomKey"}],"title":"UIConfigurationStateCustomKey","navigatorTitle":[{"kind":"identifier","text":"UIConfigurationStateCustomKey"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIConfigurationStateCustomKey","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-swift.struct/isPinned":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isPinned","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"isPinned","role":"symbol","url":"/documentation/uikit/uiviewconfigurationstate-swift.struct/ispinned","abstract":[{"type":"text","text":"A Boolean value that indicates whether the view is in a pinned state."}],"kind":"symbol","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-swift.struct/isPinned"},"doc://com.externally.resolved.symbol/s:s8CopyableP":{"identifier":"doc://com.externally.resolved.symbol/s:s8CopyableP","role":"symbol","kind":"symbol","url":"/documentation/Swift/Copyable","title":"Copyable","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Copyable"}],"abstract":[{"type":"text","text":"A type whose values can be implicitly or explicitly copied."}]},"doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-swift.struct/isDisabled":{"role":"symbol","type":"topic","abstract":[{"text":"A Boolean value that indicates whether the view is in a disabled state.","type":"text"}],"title":"isDisabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isDisabled","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-swift.struct/isDisabled","url":"/documentation/uikit/uiviewconfigurationstate-swift.struct/isdisabled"},"doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-swift.struct":{"type":"topic","url":"/documentation/uikit/uiviewconfigurationstate-swift.struct","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-swift.struct","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIViewConfigurationState"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIViewConfigurationState"}],"title":"UIViewConfigurationState","abstract":[{"type":"text","text":"A structure that encapsulates a view’s state."}],"role":"symbol"},"doc://com.externally.resolved.symbol/s:s17CustomReflectableP":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomReflectable","kind":"identifier"}],"kind":"symbol","title":"CustomReflectable","type":"topic","role":"symbol","abstract":[{"type":"text","text":"A type that explicitly supplies its own mirror."}],"url":"/documentation/Swift/CustomReflectable","identifier":"doc://com.externally.resolved.symbol/s:s17CustomReflectableP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIConfigurationStateCustomKey/title","op":"replace","value":"UIConfigurationStateCustomKey"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIConfigurationStateCustomKey/fragments","op":"replace","value":[{"kind":"identifier","text":"UIConfigurationStateCustomKey"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIConfigurationStateCustomKey/navigatorTitle","value":[{"text":"UIConfigurationStateCustomKey","kind":"identifier"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}