{"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"seeAlsoSections":[{"title":"Transition coordinators","anchor":"Transition-coordinators","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext"],"generated":true}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc://com.externally.resolved.symbol/c:objc(pl)NSObject","doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext"]}],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","identifier":"doc://com.externally.resolved.symbol/s:ScM","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIViewControllerTransitionCoordinator","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"UIViewControllerTransitionCoordinatorContext","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext","preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinatorContext"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Overview","anchor":"overview","level":2,"type":"heading"},{"inlineContent":[{"text":"Typically, you don’t adopt this protocol in your own classes. When you present or dismiss a view controller, UIKit creates a transition coordinator object automatically and assigns it to the view controller’s ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewController/transitionCoordinator","type":"reference","isActive":true},{"text":" property. That transition coordinator object is ephemeral and lasts for the duration of the transition animation.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"You can use a transition coordinator object to perform tasks that are related to a transition but that are separate from what the animator objects are doing. During a transition, the animator objects are responsible for putting the new view controller content onscreen, but there may be other visual elements that need to be displayed too. For example, a presentation controller might want to animate the appearance or disappearance of decoration views that are separate from the view controller content. In that case, it uses the transition coordinator to perform those animations.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"The transition coordinator works with the animator objects to ensure that any extra animations are performed in the same animation group as the transition animations. Having the animations in the same group means that they execute at the same time and can all respond to timing changes provided by an interactive animator object. These timing adjustments happen automatically and don’t require any extra code on your part.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Using the transition coordinator to handle view hierarchy animations is preferred over making those same changes in the "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewController/viewWillAppear(_:)"},{"type":"text","text":" or similar methods of your view controllers. The blocks you register with the methods of this protocol are guaranteed to execute at the same time as the transition animations. More importantly, the transition coordinator provides important information about the state of the transition, such as whether it was canceled, to your animation blocks through the "},{"type":"reference","isActive":true,"identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext"},{"type":"text","text":" object."}],"type":"paragraph"},{"inlineContent":[{"text":"In addition to registering animations to perform during the transition, you can call the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator/notifyWhenInteractionEnds(_:)"},{"text":" method to register a block to clean up animations associated with an interactive transition. Cleaning up is particularly important when the user cancels a transition interactively. When a cancellation occurs, you need to return to the original view hierarchy state as it existed before the transition.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Because the transition coordinator is in effect only during a transition, UIKit releases the object when the transition finishes and the final callback is made."}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"text":"A set of methods that provides support for animations associated with a view controller transition.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"topicSections":[{"title":"Responding to view controller transition progress","anchor":"Responding-to-view-controller-transition-progress","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator/animate(alongsideTransition:completion:)","doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator/animateAlongsideTransition(in:animation:completion:)","doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator/notifyWhenInteractionChanges(_:)","doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator/notifyWhenInteractionEnds(_:)"]}],"metadata":{"modules":[{"name":"UIKit"}],"platforms":[{"unavailable":false,"beta":false,"name":"iOS","deprecated":false},{"unavailable":false,"beta":false,"name":"iPadOS","deprecated":false},{"unavailable":false,"beta":false,"name":"Mac Catalyst","deprecated":false},{"deprecated":false,"unavailable":false,"beta":false,"name":"tvOS"},{"deprecated":false,"unavailable":false,"beta":false,"name":"visionOS"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIViewControllerTransitionCoordinator"}],"externalID":"c:objc(pl)UIViewControllerTransitionCoordinator","title":"UIViewControllerTransitionCoordinator","symbolKind":"protocol","role":"symbol","roleHeading":"Protocol","navigatorTitle":[{"kind":"identifier","text":"UIViewControllerTransitionCoordinator"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uiviewcontrollertransitioncoordinator"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uiviewcontrollertransitioncoordinator"]}],"references":{"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"title":"NSObjectProtocol","type":"topic","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","role":"symbol","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"kind":"symbol","url":"/documentation/objectivec/nsobjectprotocol"},"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator/notifyWhenInteractionEnds(_:)":{"type":"topic","title":"notifyWhenInteractionEnds(_:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator/notifyWhenInteractionEnds(_:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notifyWhenInteractionEnds","kind":"identifier"},{"text":"((any ","kind":"text"},{"text":"UIViewControllerTransitionCoordinatorContext","preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinatorContext","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"abstract":[{"text":"Registers a block to be executed when a transition changes from interactive to non-interactive.","type":"text"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"notifyWhenInteractionEndsUsingBlock:"}],"deprecated":true,"url":"/documentation/uikit/uiviewcontrollertransitioncoordinator/notifywheninteractionends(_:)"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator/animateAlongsideTransition(in:animation:completion:)":{"type":"topic","title":"animateAlongsideTransition(in:animation:completion:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator/animateAlongsideTransition(in:animation:completion:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"animateAlongsideTransition","kind":"identifier"},{"text":"(","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"animation"},{"kind":"text","text":": ((any "},{"preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinatorContext","kind":"typeIdentifier","text":"UIViewControllerTransitionCoordinatorContext"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"completion"},{"text":": ((any ","kind":"text"},{"text":"UIViewControllerTransitionCoordinatorContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinatorContext"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"text":"Runs the specified animations in a view that’s outside of the designated container view.","type":"text"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"animateAlongsideTransitionInView:animation:completion:"}],"url":"/documentation/uikit/uiviewcontrollertransitioncoordinator/animatealongsidetransition(in:animation:completion:)"},"doc://com.apple.uikit/documentation/UIKit/UIViewController/transitionCoordinator":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewController/transitionCoordinator","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitionCoordinator"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinator","kind":"typeIdentifier","text":"UIViewControllerTransitionCoordinator"},{"kind":"text","text":")?"}],"type":"topic","url":"/documentation/uikit/uiviewcontroller/transitioncoordinator","title":"transitionCoordinator","abstract":[{"text":"Returns the active transition coordinator object.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"transitionCoordinator"}]},"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator/animate(alongsideTransition:completion:)":{"type":"topic","title":"animate(alongsideTransition:completion:)","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator/animate(alongsideTransition:completion:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"animate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"alongsideTransition","kind":"externalParam"},{"text":": ((any ","kind":"text"},{"text":"UIViewControllerTransitionCoordinatorContext","preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinatorContext","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((any ","kind":"text"},{"text":"UIViewControllerTransitionCoordinatorContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinatorContext"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?) -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"abstract":[{"text":"Runs the specified animations at the same time as the view controller transition animations.","type":"text"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"animateAlongsideTransition:completion:"}],"url":"/documentation/uikit/uiviewcontrollertransitioncoordinator/animate(alongsidetransition:completion:)"},"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UIViewControllerTransitionCoordinatorContext"}],"url":"/documentation/uikit/uiviewcontrollertransitioncoordinatorcontext","role":"symbol","title":"UIViewControllerTransitionCoordinatorContext","abstract":[{"type":"text","text":"A set of methods that provides information about an in-progress view controller transition."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIViewControllerTransitionCoordinatorContext"}],"kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIViewControllerTransitionCoordinator"}],"type":"topic","url":"/documentation/uikit/uiviewcontrollertransitioncoordinator","title":"UIViewControllerTransitionCoordinator","abstract":[{"text":"A set of methods that provides support for animations associated with a view controller transition.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIViewControllerTransitionCoordinator"}]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator/notifyWhenInteractionChanges(_:)":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator/notifyWhenInteractionChanges(_:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"notifyWhenInteractionChangesUsingBlock:"}],"required":true,"url":"/documentation/uikit/uiviewcontrollertransitioncoordinator/notifywheninteractionchanges(_:)","role":"symbol","title":"notifyWhenInteractionChanges(_:)","abstract":[{"type":"text","text":"Registers a block to be executed when a transition changes from interactive to non-interactive."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"notifyWhenInteractionChanges"},{"kind":"text","text":"((any "},{"preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinatorContext","kind":"typeIdentifier","text":"UIViewControllerTransitionCoordinatorContext"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIViewController/viewWillAppear(_:)":{"type":"topic","url":"/documentation/uikit/uiviewcontroller/viewwillappear(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewWillAppear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"role":"symbol","title":"viewWillAppear(_:)","navigatorTitle":[{"text":"viewWillAppear:","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewController/viewWillAppear(_:)","abstract":[{"text":"Notifies the view controller that its view is about to be added to a view hierarchy.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"unavailable":false,"name":"iOS","beta":false,"deprecated":false},{"unavailable":false,"name":"iPadOS","beta":false,"deprecated":false},{"name":"Mac Catalyst","deprecated":false,"beta":false,"unavailable":false},{"name":"tvOS","deprecated":false,"beta":false,"unavailable":false},{"name":"visionOS","deprecated":false,"beta":false,"unavailable":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Protocol"},{"op":"replace","path":"/metadata/title","value":"UIViewControllerTransitionCoordinator"},{"op":"replace","path":"/metadata/symbolKind","value":"protocol"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"UIViewControllerTransitionCoordinator"}]},{"op":"replace","path":"/metadata/navigatorTitle","value":[{"text":"UIViewControllerTransitionCoordinator","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]}},{"op":"replace","path":"/topicSections","value":[{"anchor":"Responding-to-view-controller-transition-progress","title":"Responding to view controller transition progress","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator/animate(alongsideTransition:completion:)","doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator/animateAlongsideTransition(in:animation:completion:)","doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator/notifyWhenInteractionChanges(_:)","doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator/notifyWhenInteractionEnds(_:)"]}]},{"op":"replace","path":"/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext"]}]},{"op":"replace","path":"/seeAlsoSections","value":[{"title":"Transition coordinators","identifiers":["doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext"],"anchor":"Transition-coordinators","generated":true}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIViewControllerTransitionCoordinator","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinatorContext","identifier":"doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext","text":"UIViewControllerTransitionCoordinatorContext","kind":"typeIdentifier"},{"text":">","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","value":"NSObject","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title"},{"op":"replace","value":"notifyWhenInteractionEndsUsingBlock:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinator~1notifyWhenInteractionEnds(_:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"notifyWhenInteractionEndsUsingBlock:"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinator~1notifyWhenInteractionEnds(_:)/fragments"},{"op":"replace","value":"animateAlongsideTransitionInView:animation:completion:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinator~1animateAlongsideTransition(in:animation:completion:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"animateAlongsideTransitionInView:animation:completion:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinator~1animateAlongsideTransition(in:animation:completion:)/fragments"},{"op":"replace","value":"transitionCoordinator","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1transitionCoordinator/title"},{"op":"replace","value":[{"text":"transitionCoordinator","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1transitionCoordinator/fragments"},{"op":"replace","value":"animateAlongsideTransition:completion:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinator~1animate(alongsideTransition:completion:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"animateAlongsideTransition:completion:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinator~1animate(alongsideTransition:completion:)/fragments"},{"op":"replace","value":"UIViewControllerTransitionCoordinatorContext","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinatorContext/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIViewControllerTransitionCoordinatorContext"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinatorContext/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UIViewControllerTransitionCoordinatorContext"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinatorContext/navigatorTitle"},{"op":"replace","value":"UIViewControllerTransitionCoordinator","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinator/title"},{"op":"replace","value":[{"kind":"identifier","text":"UIViewControllerTransitionCoordinator"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinator/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"UIViewControllerTransitionCoordinator"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinator/navigatorTitle"},{"op":"replace","value":"notifyWhenInteractionChangesUsingBlock:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinator~1notifyWhenInteractionChanges(_:)/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"notifyWhenInteractionChangesUsingBlock:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinator~1notifyWhenInteractionChanges(_:)/fragments"},{"op":"replace","value":"viewWillAppear:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1viewWillAppear(_:)/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillAppear:"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1viewWillAppear(_:)/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}