{
  "abstract": [
    {
      "text": "Symbols that views no longer support.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/views-and-controls",
        "doc://com.apple.uikit/documentation/UIKit/UIView"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/uiview-deprecated-symbols"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Deprecated symbols"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView": {
      "abstract": [
        {
          "text": "An object that manages the content for a rectangular area on the screen.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIView"
        }
      ],
      "role": "symbol",
      "title": "UIView",
      "type": "topic",
      "url": "/documentation/uikit/uiview"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/areAnimationsEnabled": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether animations are enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "areAnimationsEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/areAnimationsEnabled",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "areAnimationsEnabled"
        }
      ],
      "role": "symbol",
      "title": "areAnimationsEnabled",
      "type": "topic",
      "url": "/documentation/uikit/uiview/areanimationsenabled"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/beginAnimations(_:context:)": {
      "abstract": [
        {
          "text": "Marks the beginning of a begin/commit animation block.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "beginAnimations"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "context"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/beginAnimations(_:context:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "beginAnimations:context:"
        }
      ],
      "role": "symbol",
      "title": "beginAnimations(_:context:)",
      "type": "topic",
      "url": "/documentation/uikit/uiview/beginanimations(_:context:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/commitAnimations()": {
      "abstract": [
        {
          "text": "Marks the end of a begin/commit animation block and schedules the animations for execution.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "commitAnimations"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/commitAnimations()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "commitAnimations"
        }
      ],
      "role": "symbol",
      "title": "commitAnimations()",
      "type": "topic",
      "url": "/documentation/uikit/uiview/commitanimations()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/contentStretch": {
      "abstract": [
        {
          "text": "The rectangle that defines the stretchable and nonstretchable regions of a view.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "contentStretch"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/contentStretch",
      "kind": "symbol",
      "role": "symbol",
      "title": "contentStretch",
      "type": "topic",
      "url": "/documentation/uikit/uiview/contentstretch"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/forBaselineLayout()": {
      "abstract": [
        {
          "text": "Returns a view used to satisfy baseline constraints.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forBaselineLayout"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/forBaselineLayout()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "viewForBaselineLayout"
        }
      ],
      "role": "symbol",
      "title": "forBaselineLayout()",
      "type": "topic",
      "url": "/documentation/uikit/uiview/forbaselinelayout()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationBeginsFromCurrentState(_:)": {
      "abstract": [
        {
          "text": "Sets whether the animation should begin playing from the current state.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAnimationBeginsFromCurrentState"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationBeginsFromCurrentState(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setAnimationBeginsFromCurrentState:"
        }
      ],
      "role": "symbol",
      "title": "setAnimationBeginsFromCurrentState(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiview/setanimationbeginsfromcurrentstate(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationCurve(_:)": {
      "abstract": [
        {
          "text": "Sets the curve to use when animating property changes within an animation block.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAnimationCurve"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationCurve",
          "text": "AnimationCurve"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationCurve(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setAnimationCurve:"
        }
      ],
      "role": "symbol",
      "title": "setAnimationCurve(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiview/setanimationcurve(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationDelay(_:)": {
      "abstract": [
        {
          "text": "Sets the amount of time (in seconds) to wait before animating property changes within an animation block.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAnimationDelay"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationDelay(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setAnimationDelay:"
        }
      ],
      "role": "symbol",
      "title": "setAnimationDelay(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiview/setanimationdelay(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationDelegate(_:)": {
      "abstract": [
        {
          "text": "Sets the delegate for any animation messages.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAnimationDelegate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationDelegate(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setAnimationDelegate:"
        }
      ],
      "role": "symbol",
      "title": "setAnimationDelegate(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiview/setanimationdelegate(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationDidStop(_:)": {
      "abstract": [
        {
          "text": "Sets the message to send to the animation delegate when animation stops.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAnimationDidStop"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationDidStop(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setAnimationDidStopSelector:"
        }
      ],
      "role": "symbol",
      "title": "setAnimationDidStop(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiview/setanimationdidstop(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationDuration(_:)": {
      "abstract": [
        {
          "text": "Sets the duration (measured in seconds) of the animations in an animation block.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAnimationDuration"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationDuration(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setAnimationDuration:"
        }
      ],
      "role": "symbol",
      "title": "setAnimationDuration(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiview/setanimationduration(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationRepeatAutoreverses(_:)": {
      "abstract": [
        {
          "text": "Sets whether the animations within an animation block automatically reverse themselves.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAnimationRepeatAutoreverses"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationRepeatAutoreverses(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setAnimationRepeatAutoreverses:"
        }
      ],
      "role": "symbol",
      "title": "setAnimationRepeatAutoreverses(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiview/setanimationrepeatautoreverses(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationRepeatCount(_:)": {
      "abstract": [
        {
          "text": "Sets the number of times animations within an animation block repeat.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAnimationRepeatCount"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sf",
          "text": "Float"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationRepeatCount(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setAnimationRepeatCount:"
        }
      ],
      "role": "symbol",
      "title": "setAnimationRepeatCount(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiview/setanimationrepeatcount(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationStart(_:)": {
      "abstract": [
        {
          "text": "Sets the start time for the current animation block.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAnimationStart"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DateV",
          "text": "Date"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationStart(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setAnimationStartDate:"
        }
      ],
      "role": "symbol",
      "title": "setAnimationStart(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiview/setanimationstart(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationTransition(_:for:cache:)": {
      "abstract": [
        {
          "text": "Sets a transition to apply to a view during an animation block.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAnimationTransition"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationTransition",
          "text": "AnimationTransition"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "cache"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationTransition(_:for:cache:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setAnimationTransition:forView:cache:"
        }
      ],
      "role": "symbol",
      "title": "setAnimationTransition(_:for:cache:)",
      "type": "topic",
      "url": "/documentation/uikit/uiview/setanimationtransition(_:for:cache:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationWillStart(_:)": {
      "abstract": [
        {
          "text": "Sets the message to send to the animation delegate when the animation starts.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAnimationWillStart"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationWillStart(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setAnimationWillStartSelector:"
        }
      ],
      "role": "symbol",
      "title": "setAnimationWillStart(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiview/setanimationwillstart(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationsEnabled(_:)": {
      "abstract": [
        {
          "text": "Sets whether animations are enabled.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setAnimationsEnabled"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationsEnabled(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setAnimationsEnabled:"
        }
      ],
      "role": "symbol",
      "title": "setAnimationsEnabled(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiview/setanimationsenabled(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/views-and-controls": {
      "abstract": [
        {
          "text": "Present your content onscreen and define the interactions allowed with that content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/views-and-controls",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Views and controls",
      "type": "topic",
      "url": "/documentation/uikit/views-and-controls"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Deprecated-methods",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIView/beginAnimations(_:context:)",
        "doc://com.apple.uikit/documentation/UIKit/UIView/commitAnimations()",
        "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationStart(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationsEnabled(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationDelegate(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationWillStart(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationDidStop(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationDuration(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationDelay(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationCurve(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationRepeatCount(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationRepeatAutoreverses(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationBeginsFromCurrentState(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationTransition(_:for:cache:)",
        "doc://com.apple.uikit/documentation/UIKit/UIView/areAnimationsEnabled",
        "doc://com.apple.uikit/documentation/UIKit/UIView/forBaselineLayout()"
      ],
      "title": "Deprecated methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Deprecated-methods",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIView/beginAnimations(_:context:)",
                "doc://com.apple.uikit/documentation/UIKit/UIView/commitAnimations()",
                "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationStart(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationsEnabled(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationDelegate(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationWillStart(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationDidStop(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationDuration(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationDelay(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationCurve(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationRepeatCount(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationRepeatAutoreverses(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationBeginsFromCurrentState(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIView/setAnimationTransition(_:for:cache:)",
                "doc://com.apple.uikit/documentation/UIKit/UIView/areAnimationsEnabled",
                "doc://com.apple.uikit/documentation/UIKit/UIView/forBaselineLayout()"
              ],
              "title": "Deprecated methods"
            },
            {
              "anchor": "Deprecated-properties",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIView/contentStretch"
              ],
              "title": "Deprecated properties"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1forBaselineLayout()/title",
          "value": "viewForBaselineLayout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1forBaselineLayout()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "viewForBaselineLayout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1beginAnimations(_:context:)/title",
          "value": "beginAnimations:context:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1beginAnimations(_:context:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "beginAnimations:context:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1commitAnimations()/title",
          "value": "commitAnimations"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1commitAnimations()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "commitAnimations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1setAnimationCurve(_:)/title",
          "value": "setAnimationCurve:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1setAnimationCurve(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "setAnimationCurve:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1setAnimationStart(_:)/title",
          "value": "setAnimationStartDate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1setAnimationStart(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "setAnimationStartDate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/title",
          "value": "UIView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1setAnimationBeginsFromCurrentState(_:)/title",
          "value": "setAnimationBeginsFromCurrentState:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1setAnimationBeginsFromCurrentState(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "setAnimationBeginsFromCurrentState:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1setAnimationDuration(_:)/title",
          "value": "setAnimationDuration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1setAnimationDuration(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "setAnimationDuration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1setAnimationTransition(_:for:cache:)/title",
          "value": "setAnimationTransition:forView:cache:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1setAnimationTransition(_:for:cache:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "setAnimationTransition:forView:cache:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1setAnimationDidStop(_:)/title",
          "value": "setAnimationDidStopSelector:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1setAnimationDidStop(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "setAnimationDidStopSelector:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1setAnimationDelegate(_:)/title",
          "value": "setAnimationDelegate:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1setAnimationDelegate(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "setAnimationDelegate:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1setAnimationRepeatCount(_:)/title",
          "value": "setAnimationRepeatCount:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1setAnimationRepeatCount(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "setAnimationRepeatCount:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1setAnimationWillStart(_:)/title",
          "value": "setAnimationWillStartSelector:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1setAnimationWillStart(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "setAnimationWillStartSelector:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1setAnimationsEnabled(_:)/title",
          "value": "setAnimationsEnabled:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1setAnimationsEnabled(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "setAnimationsEnabled:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1areAnimationsEnabled/title",
          "value": "areAnimationsEnabled"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1areAnimationsEnabled/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "areAnimationsEnabled"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1setAnimationRepeatAutoreverses(_:)/title",
          "value": "setAnimationRepeatAutoreverses:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1setAnimationRepeatAutoreverses(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "setAnimationRepeatAutoreverses:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1setAnimationDelay(_:)/title",
          "value": "setAnimationDelay:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIView~1setAnimationDelay(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "setAnimationDelay:"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiview-deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiview-deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
