{
  "abstract": [
    {
      "text": "A set of methods that enable an object (such as a navigation controller) to drive a view controller transition.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerInteractiveTransitioning"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UIViewControllerInteractiveTransitioning",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIViewControllerInteractiveTransitioning"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIViewControllerInteractiveTransitioning"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "UIViewControllerInteractiveTransitioning"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIViewControllerInteractiveTransitioning"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An ",
              "type": "text"
            },
            {
              "inlineContent": [
                {
                  "text": "interactive transition delegate",
                  "type": "text"
                }
              ],
              "type": "emphasis"
            },
            {
              "text": " (which is the term for an object that supports this protocol) can respond to touch events, or to time-varying programmatic input, by speeding up, slowing down, or even reversing the progress of a view controller transition. For example, an interactive transition on a navigation controller could respond to a swipe gesture by moving a view controller onto or off of the navigation stack.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To support an interactive view controller transition, you must also provide a transition animator delegate, which is a custom object that adopts the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerAnimatedTransitioning",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol. The transition delegate and the transition animator can, if you wish, be defined within a single custom class, but the class must adopt both protocols.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If you instead want to provide a fixed-duration animated view controller transition — one that doesn’t support user interaction — use a transition animator delegate on its own. Refer to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerAnimatedTransitioning",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For the methods you can call to retrieve view transition context information from within your ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerInteractiveTransitioning/startInteractiveTransition(_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method, refer to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPercentDrivenInteractiveTransition": {
      "abstract": [
        {
          "text": "An object that drives an interactive animation between one view controller and another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPercentDrivenInteractiveTransition"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPercentDrivenInteractiveTransition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPercentDrivenInteractiveTransition"
        }
      ],
      "role": "symbol",
      "title": "UIPercentDrivenInteractiveTransition",
      "type": "topic",
      "url": "/documentation/uikit/uipercentdriveninteractivetransition"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewControllerAnimatedTransitioning": {
      "abstract": [
        {
          "text": "A set of methods for implementing the animations for a custom view controller transition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewControllerAnimatedTransitioning"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerAnimatedTransitioning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewControllerAnimatedTransitioning"
        }
      ],
      "role": "symbol",
      "title": "UIViewControllerAnimatedTransitioning",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontrolleranimatedtransitioning"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning": {
      "abstract": [
        {
          "text": "A set of methods that provide contextual information for transition animations between view controllers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewControllerContextTransitioning"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewControllerContextTransitioning"
        }
      ],
      "role": "symbol",
      "title": "UIViewControllerContextTransitioning",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontrollercontexttransitioning"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewControllerInteractiveTransitioning": {
      "abstract": [
        {
          "text": "A set of methods that enable an object (such as a navigation controller) to drive a view controller transition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewControllerInteractiveTransitioning"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerInteractiveTransitioning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewControllerInteractiveTransitioning"
        }
      ],
      "role": "symbol",
      "title": "UIViewControllerInteractiveTransitioning",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontrollerinteractivetransitioning"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewControllerInteractiveTransitioning/completionCurve": {
      "abstract": [
        {
          "text": "Called when the system needs the animation completion curve for an interactive view controller transition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "completionCurve"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIViewAnimationCurve",
          "text": "AnimationCurve"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerInteractiveTransitioning/completionCurve",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "completionCurve"
        }
      ],
      "role": "symbol",
      "title": "completionCurve",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontrollerinteractivetransitioning/completioncurve"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewControllerInteractiveTransitioning/completionSpeed": {
      "abstract": [
        {
          "text": "Called when the system needs the speed at which to complete an interactive transition, after the interactive portion is finished.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "completionSpeed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerInteractiveTransitioning/completionSpeed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "completionSpeed"
        }
      ],
      "role": "symbol",
      "title": "completionSpeed",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontrollerinteractivetransitioning/completionspeed"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewControllerInteractiveTransitioning/startInteractiveTransition(_:)": {
      "abstract": [
        {
          "text": "Called when the system needs to set up the interactive portions of a view controller transition and start the animations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "startInteractiveTransition"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIViewControllerContextTransitioning",
          "text": "UIViewControllerContextTransitioning"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerInteractiveTransitioning/startInteractiveTransition(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "startInteractiveTransition:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "startInteractiveTransition(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontrollerinteractivetransitioning/startinteractivetransition(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewControllerInteractiveTransitioning/wantsInteractiveStart": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the transition is interactive when it starts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "wantsInteractiveStart"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerInteractiveTransitioning/wantsInteractiveStart",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "wantsInteractiveStart"
        }
      ],
      "role": "symbol",
      "title": "wantsInteractiveStart",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontrollerinteractivetransitioning/wantsinteractivestart"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewImplicitlyAnimating": {
      "abstract": [
        {
          "text": "An interface for modifying an animation while it’s running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewImplicitlyAnimating"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewImplicitlyAnimating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewImplicitlyAnimating"
        }
      ],
      "role": "symbol",
      "title": "UIViewImplicitlyAnimating",
      "type": "topic",
      "url": "/documentation/uikit/uiviewimplicitlyanimating"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPercentDrivenInteractiveTransition"
      ],
      "kind": "relationships",
      "title": "Conforming Types",
      "type": "conformingTypes"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Interactive-transitions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPercentDrivenInteractiveTransition",
        "doc://com.apple.uikit/documentation/UIKit/UIViewImplicitlyAnimating"
      ],
      "title": "Interactive transitions"
    }
  ],
  "topicSections": [
    {
      "anchor": "Starting-an-interactive-transition",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIViewControllerInteractiveTransitioning/startInteractiveTransition(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIViewControllerInteractiveTransitioning/wantsInteractiveStart"
      ],
      "title": "Starting an interactive transition"
    },
    {
      "anchor": "Providing-a-transitions-completion-characteristics",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIViewControllerInteractiveTransitioning/completionCurve",
        "doc://com.apple.uikit/documentation/UIKit/UIViewControllerInteractiveTransitioning/completionSpeed"
      ],
      "title": "Providing a transition’s completion characteristics"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIViewControllerInteractiveTransitioning"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerInteractiveTransitioning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerInteractiveTransitioning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Starting-an-interactive-transition",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIViewControllerInteractiveTransitioning/startInteractiveTransition(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIViewControllerInteractiveTransitioning/wantsInteractiveStart"
              ],
              "title": "Starting an interactive transition"
            },
            {
              "anchor": "Providing-a-transitions-completion-characteristics",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIViewControllerInteractiveTransitioning/completionCurve",
                "doc://com.apple.uikit/documentation/UIKit/UIViewControllerInteractiveTransitioning/completionSpeed"
              ],
              "title": "Providing a transition’s completion characteristics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            },
            {
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPercentDrivenInteractiveTransition"
              ],
              "kind": "relationships",
              "title": "Conforming Types",
              "type": "conformingTypes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Interactive-transitions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPercentDrivenInteractiveTransition",
                "doc://com.apple.uikit/documentation/UIKit/UIViewImplicitlyAnimating"
              ],
              "title": "Interactive transitions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIViewControllerInteractiveTransitioning"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerInteractiveTransitioning~1wantsInteractiveStart/title",
          "value": "wantsInteractiveStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerInteractiveTransitioning~1wantsInteractiveStart/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "wantsInteractiveStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewImplicitlyAnimating/title",
          "value": "UIViewImplicitlyAnimating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewImplicitlyAnimating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewImplicitlyAnimating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewImplicitlyAnimating/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewImplicitlyAnimating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPercentDrivenInteractiveTransition/title",
          "value": "UIPercentDrivenInteractiveTransition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPercentDrivenInteractiveTransition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPercentDrivenInteractiveTransition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPercentDrivenInteractiveTransition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPercentDrivenInteractiveTransition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerInteractiveTransitioning~1completionSpeed/title",
          "value": "completionSpeed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerInteractiveTransitioning~1completionSpeed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "completionSpeed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerInteractiveTransitioning~1startInteractiveTransition(_:)/title",
          "value": "startInteractiveTransition:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerInteractiveTransitioning~1startInteractiveTransition(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "startInteractiveTransition:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerAnimatedTransitioning/title",
          "value": "UIViewControllerAnimatedTransitioning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerAnimatedTransitioning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerAnimatedTransitioning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerAnimatedTransitioning/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerAnimatedTransitioning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerInteractiveTransitioning~1completionCurve/title",
          "value": "completionCurve"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerInteractiveTransitioning~1completionCurve/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "completionCurve"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerContextTransitioning/title",
          "value": "UIViewControllerContextTransitioning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerContextTransitioning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerContextTransitioning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerContextTransitioning/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerContextTransitioning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerInteractiveTransitioning/title",
          "value": "UIViewControllerInteractiveTransitioning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerInteractiveTransitioning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerInteractiveTransitioning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerInteractiveTransitioning/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerInteractiveTransitioning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiviewcontrollerinteractivetransitioning"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiviewcontrollerinteractivetransitioning"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
