{
  "abstract": [
    {
      "text": "A set of methods used by the delegate to respond, with a preview view controller and a commit view controller, to the user pressing a view object on the screen of a device that supports 3D Touch.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Use ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteractionDelegate",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerPreviewingDelegate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UIViewControllerPreviewingDelegate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIViewControllerPreviewingDelegate"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIViewControllerPreviewingDelegate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "UIViewControllerPreviewingDelegate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIViewControllerPreviewingDelegate"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObjectProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To learn about 3D Touch, read ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/Adopting3DTouchOniPhone/index.html#//apple_ref/doc/uid/TP40016543",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "The end-user terminology for the views presented during the phases of force-based touches includes ",
                  "type": "text"
                },
                {
                  "inlineContent": [
                    {
                      "text": "peek",
                      "type": "text"
                    }
                  ],
                  "type": "emphasis"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "inlineContent": [
                    {
                      "text": "pop",
                      "type": "text"
                    }
                  ],
                  "type": "emphasis"
                },
                {
                  "text": ". For clarity here, and to align with the API names, this document uses the corresponding terms ",
                  "type": "text"
                },
                {
                  "inlineContent": [
                    {
                      "text": "preview",
                      "type": "text"
                    }
                  ],
                  "type": "emphasis"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "inlineContent": [
                    {
                      "text": "commit view",
                      "type": "text"
                    }
                  ],
                  "type": "emphasis"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Terminology Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAccelerometerDelegate": {
      "abstract": [
        {
          "text": "The interface for receiving acceleration-related data from the system.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAccelerometerDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAccelerometerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAccelerometerDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIAccelerometerDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uiaccelerometerdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIActionSheetDelegate": {
      "abstract": [
        {
          "text": "The interface for the delegate of an action sheet object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIActionSheetDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIActionSheetDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIActionSheetDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIActionSheetDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uiactionsheetdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIAlertViewDelegate": {
      "abstract": [
        {
          "text": "The interface for the delegate of an alert view object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAlertViewDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIAlertViewDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIAlertViewDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIAlertViewDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uialertviewdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteractionDelegate": {
      "abstract": [
        {
          "text": "The methods for providing the set of actions to perform on your content, and for customizing the preview of that content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIContextMenuInteractionDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteractionDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIContextMenuInteractionDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIContextMenuInteractionDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uicontextmenuinteractiondelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPopoverControllerDelegate": {
      "abstract": [
        {
          "text": "The interface for the delegate of a popover controller object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPopoverControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPopoverControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPopoverControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIPopoverControllerDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uipopovercontrollerdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchDisplayDelegate": {
      "abstract": [
        {
          "text": "The interface for the delegate of a search display controller.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISearchDisplayDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchDisplayDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISearchDisplayDelegate"
        }
      ],
      "role": "symbol",
      "title": "UISearchDisplayDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uisearchdisplaydelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewControllerPreviewing": {
      "abstract": [
        {
          "text": "A set of methods that define the interface for configuring a previewing view controller on devices that support 3D Touch.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewControllerPreviewing"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerPreviewing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewControllerPreviewing"
        }
      ],
      "role": "symbol",
      "title": "UIViewControllerPreviewing",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontrollerpreviewing"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewControllerPreviewingDelegate": {
      "abstract": [
        {
          "text": "A set of methods used by the delegate to respond, with a preview view controller and a commit view controller, to the user pressing a view object on the screen of a device that supports 3D Touch.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewControllerPreviewingDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerPreviewingDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewControllerPreviewingDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIViewControllerPreviewingDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontrollerpreviewingdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewControllerPreviewingDelegate/previewingContext(_:commit:)": {
      "abstract": [
        {
          "text": "Called to let you prepare the presentation of a commit (pop) view from your commit view controller.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "previewingContext"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIViewControllerPreviewing",
          "text": "UIViewControllerPreviewing"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "commit"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerPreviewingDelegate/previewingContext(_:commit:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "previewingContext:commitViewController:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "previewingContext(_:commit:)",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontrollerpreviewingdelegate/previewingcontext(_:commit:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewControllerPreviewingDelegate/previewingContext(_:viewControllerForLocation:)": {
      "abstract": [
        {
          "text": "Called when the user has pressed a source view in a previewing view controller, thereby obtaining a surrounding blur to indicate that a preview (peek) is available.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "previewingContext"
        },
        {
          "kind": "text",
          "text": "(any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIViewControllerPreviewing",
          "text": "UIViewControllerPreviewing"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "viewControllerForLocation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerPreviewingDelegate/previewingContext(_:viewControllerForLocation:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "previewingContext:viewControllerForLocation:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "previewingContext(_:viewControllerForLocation:)",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontrollerpreviewingdelegate/previewingcontext(_:viewcontrollerforlocation:)"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/Adopting3DTouchOniPhone/index.html#//apple_ref/doc/uid/TP40016543": {
      "identifier": "https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/Adopting3DTouchOniPhone/index.html#//apple_ref/doc/uid/TP40016543",
      "title": "Adopting 3D Touch on iPhone",
      "titleInlineContent": [
        {
          "text": "Adopting 3D Touch on iPhone",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/Adopting3DTouchOniPhone/index.html#//apple_ref/doc/uid/TP40016543"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-protocols",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIAccelerometerDelegate",
        "doc://com.apple.uikit/documentation/UIKit/UIActionSheetDelegate",
        "doc://com.apple.uikit/documentation/UIKit/UIAlertViewDelegate",
        "doc://com.apple.uikit/documentation/UIKit/UIPopoverControllerDelegate",
        "doc://com.apple.uikit/documentation/UIKit/UISearchDisplayDelegate",
        "doc://com.apple.uikit/documentation/UIKit/UIViewControllerPreviewing"
      ],
      "title": "Deprecated protocols"
    }
  ],
  "topicSections": [
    {
      "anchor": "Providing-preview-and-commit-views-for-3D-Touch",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIViewControllerPreviewingDelegate/previewingContext(_:viewControllerForLocation:)",
        "doc://com.apple.uikit/documentation/UIKit/UIViewControllerPreviewingDelegate/previewingContext(_:commit:)"
      ],
      "title": "Providing preview and commit views for 3D Touch"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIViewControllerPreviewingDelegate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerPreviewingDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerPreviewingDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Providing-preview-and-commit-views-for-3D-Touch",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIViewControllerPreviewingDelegate/previewingContext(_:viewControllerForLocation:)",
                "doc://com.apple.uikit/documentation/UIKit/UIViewControllerPreviewingDelegate/previewingContext(_:commit:)"
              ],
              "title": "Providing preview and commit views for 3D Touch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": [
            {
              "identifiers": [
                "doc://com.externally.resolved.symbol/c:objc(pl)NSObject"
              ],
              "kind": "relationships",
              "title": "Inherits From",
              "type": "inheritsFrom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Deprecated-protocols",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIAccelerometerDelegate",
                "doc://com.apple.uikit/documentation/UIKit/UIActionSheetDelegate",
                "doc://com.apple.uikit/documentation/UIKit/UIAlertViewDelegate",
                "doc://com.apple.uikit/documentation/UIKit/UIPopoverControllerDelegate",
                "doc://com.apple.uikit/documentation/UIKit/UISearchDisplayDelegate",
                "doc://com.apple.uikit/documentation/UIKit/UIViewControllerPreviewing"
              ],
              "title": "Deprecated protocols"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIViewControllerPreviewingDelegate"
                  },
                  {
                    "kind": "text",
                    "text": " <"
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(pl)NSObject",
                    "text": "NSObject"
                  },
                  {
                    "kind": "text",
                    "text": ">"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Use ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UIContextMenuInteractionDelegate",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerPreviewingDelegate~1previewingContext(_:viewControllerForLocation:)/title",
          "value": "previewingContext:viewControllerForLocation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerPreviewingDelegate~1previewingContext(_:viewControllerForLocation:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "previewingContext:viewControllerForLocation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccelerometerDelegate/title",
          "value": "UIAccelerometerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccelerometerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccelerometerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAccelerometerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAccelerometerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchDisplayDelegate/title",
          "value": "UISearchDisplayDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchDisplayDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchDisplayDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchDisplayDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchDisplayDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerPreviewing/title",
          "value": "UIViewControllerPreviewing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerPreviewing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerPreviewing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerPreviewing/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerPreviewing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuInteractionDelegate/title",
          "value": "UIContextMenuInteractionDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuInteractionDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContextMenuInteractionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIContextMenuInteractionDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIContextMenuInteractionDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerPreviewingDelegate~1previewingContext(_:commit:)/title",
          "value": "previewingContext:commitViewController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerPreviewingDelegate~1previewingContext(_:commit:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "previewingContext:commitViewController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverControllerDelegate/title",
          "value": "UIPopoverControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPopoverControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPopoverControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheetDelegate/title",
          "value": "UIActionSheetDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheetDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActionSheetDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIActionSheetDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIActionSheetDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerPreviewingDelegate/title",
          "value": "UIViewControllerPreviewingDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerPreviewingDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerPreviewingDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerPreviewingDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerPreviewingDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAlertViewDelegate/title",
          "value": "UIAlertViewDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAlertViewDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAlertViewDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIAlertViewDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIAlertViewDelegate"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiviewcontrollerpreviewingdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiviewcontrollerpreviewingdelegate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
