{
  "abstract": [
    {
      "text": "Symbols that view controllers no longer support.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/view-controllers",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/uiviewcontroller-deprecated-symbols"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Deprecated symbols"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController": {
      "abstract": [
        {
          "text": "An object that manages a view hierarchy for your UIKit app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewController"
        }
      ],
      "role": "symbol",
      "title": "UIViewController",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/attemptRotationToDeviceOrientation()": {
      "abstract": [
        {
          "text": "Attempts to rotate all windows to the orientation of the device.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "attemptRotationToDeviceOrientation"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/attemptRotationToDeviceOrientation()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "attemptRotationToDeviceOrientation"
        }
      ],
      "role": "symbol",
      "title": "attemptRotationToDeviceOrientation()",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/attemptrotationtodeviceorientation()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/automaticallyAdjustsScrollViewInsets": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the view controller should automatically adjust its scroll view insets.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automaticallyAdjustsScrollViewInsets"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/automaticallyAdjustsScrollViewInsets",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "automaticallyAdjustsScrollViewInsets"
        }
      ],
      "role": "symbol",
      "title": "automaticallyAdjustsScrollViewInsets",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/automaticallyadjustsscrollviewinsets"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/automaticallyForwardAppearanceAndRotationMethodsToChildViewControllers": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether appearance and rotation methods are forwarded.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "automaticallyForwardAppearanceAndRotationMethodsToChildViewControllers"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/automaticallyForwardAppearanceAndRotationMethodsToChildViewControllers",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "automaticallyForwardAppearanceAndRotationMethodsToChildViewControllers"
        }
      ],
      "role": "symbol",
      "title": "automaticallyForwardAppearanceAndRotationMethodsToChildViewControllers",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/automaticallyforwardappearanceandrotationmethodstochildviewcontrollers"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/bottomLayoutGuide": {
      "abstract": [
        {
          "text": "Indicates the lowest vertical extent for your onscreen content, for use with Auto Layout constraints.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottomLayoutGuide"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UILayoutSupport",
          "text": "UILayoutSupport"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/bottomLayoutGuide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "bottomLayoutGuide"
        }
      ],
      "role": "symbol",
      "title": "bottomLayoutGuide",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/bottomlayoutguide"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/canPerformUnwindSegueAction(_:from:withSender:)": {
      "abstract": [
        {
          "text": "Called on a view controller to determine whether it wants to respond to an unwind action.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canPerformUnwindSegueAction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withSender"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/canPerformUnwindSegueAction(_:from:withSender:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canPerformUnwindSegueAction:fromViewController:withSender:"
        }
      ],
      "role": "symbol",
      "title": "canPerformUnwindSegueAction(_:from:withSender:)",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/canperformunwindsegueaction(_:from:withsender:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/contentSizeForViewInPopover": {
      "abstract": [
        {
          "text": "The size of the view controller’s view while displayed in a popover.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "contentSizeForViewInPopover"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/contentSizeForViewInPopover",
      "kind": "symbol",
      "role": "symbol",
      "title": "contentSizeForViewInPopover",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/contentsizeforviewinpopover"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/didAnimateFirstHalfOfRotationToInterfaceOrientation:": {
      "abstract": [
        {
          "text": "Sent to the view controller after the completion of the first half of the user interface rotation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "didAnimateFirstHalfOfRotationToInterfaceOrientation:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/didAnimateFirstHalfOfRotationToInterfaceOrientation:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "didAnimateFirstHalfOfRotationToInterfaceOrientation:"
        }
      ],
      "role": "symbol",
      "title": "didAnimateFirstHalfOfRotationToInterfaceOrientation:",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/didanimatefirsthalfofrotationtointerfaceorientation:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/didRotate(from:)": {
      "abstract": [
        {
          "text": "Sent to the view controller after the user interface rotates.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didRotate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIInterfaceOrientation",
          "text": "UIInterfaceOrientation"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/didRotate(from:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "didRotateFromInterfaceOrientation:"
        }
      ],
      "role": "symbol",
      "title": "didRotate(from:)",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/didrotate(from:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/dismissModalViewControllerAnimated:": {
      "abstract": [
        {
          "text": "Dismisses the view controller that was presented by the receiver.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "dismissModalViewControllerAnimated:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/dismissModalViewControllerAnimated:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dismissModalViewControllerAnimated:"
        }
      ],
      "role": "symbol",
      "title": "dismissModalViewControllerAnimated:",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/dismissmodalviewcontrolleranimated:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/dismissMoviePlayerViewControllerAnimated()": {
      "abstract": [
        {
          "text": "Dismisses a movie player view controller using the standard movie player transition.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dismissMoviePlayerViewControllerAnimated"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/dismissMoviePlayerViewControllerAnimated()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dismissMoviePlayerViewControllerAnimated"
        }
      ],
      "role": "symbol",
      "title": "dismissMoviePlayerViewControllerAnimated()",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/dismissmovieplayerviewcontrolleranimated()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/forUnwindSegueAction(_:from:withSender:)": {
      "abstract": [
        {
          "text": "Called when an unwind segue action wants to search a container’s children for a view controller to handle the unwind action.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "forUnwindSegueAction"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withSender"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/forUnwindSegueAction(_:from:withSender:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "viewControllerForUnwindSegueAction:fromViewController:withSender:"
        }
      ],
      "role": "symbol",
      "title": "forUnwindSegueAction(_:from:withSender:)",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/forunwindsegueaction(_:from:withsender:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/interfaceOrientation": {
      "abstract": [
        {
          "text": "Convenience property that provides the current orientation of the interface, meaningful only if the view controller is taking up the full screen.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "interfaceOrientation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIInterfaceOrientation",
          "text": "UIInterfaceOrientation"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/interfaceOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "interfaceOrientation"
        }
      ],
      "role": "symbol",
      "title": "interfaceOrientation",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/interfaceorientation"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/isModalInPopover": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the view controller should be presented modally by a popover.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isModalInPopover"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/isModalInPopover",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "modalInPopover"
        }
      ],
      "role": "symbol",
      "title": "isModalInPopover",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/ismodalinpopover"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/modalViewController": {
      "abstract": [
        {
          "text": "The controller for the active presented view’that is, the view that is temporarily displayed on top of the view managed by the receiver.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "modalViewController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/modalViewController",
      "kind": "symbol",
      "role": "symbol",
      "title": "modalViewController",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/modalviewcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/overrideTraitCollection(forChild:)": {
      "abstract": [
        {
          "text": "Retrieves the trait collection for a child view controller.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "overrideTraitCollection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forChild"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITraitCollection",
          "text": "UITraitCollection"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/overrideTraitCollection(forChild:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "overrideTraitCollectionForChildViewController:"
        }
      ],
      "role": "symbol",
      "title": "overrideTraitCollection(forChild:)",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/overridetraitcollection(forchild:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/presentModalViewController:animated:": {
      "abstract": [
        {
          "text": "Presents a modal view managed by the given view controller to the user.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "presentModalViewController:animated:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/presentModalViewController:animated:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "presentModalViewController:animated:"
        }
      ],
      "role": "symbol",
      "title": "presentModalViewController:animated:",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/presentmodalviewcontroller:animated:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/presentMoviePlayerViewControllerAnimated(_:)": {
      "abstract": [
        {
          "text": "Presents the movie player view controller using the standard movie player transition.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "presentMoviePlayerViewControllerAnimated"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MPMoviePlayerViewController",
          "text": "MPMoviePlayerViewController"
        },
        {
          "kind": "text",
          "text": "!)"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/presentMoviePlayerViewControllerAnimated(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "presentMoviePlayerViewControllerAnimated:"
        }
      ],
      "role": "symbol",
      "title": "presentMoviePlayerViewControllerAnimated(_:)",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/presentmovieplayerviewcontrolleranimated(_:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/previewActionItems": {
      "abstract": [
        {
          "text": "The quick actions displayed when a user swipes upward on a 3D Touch preview.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "previewActionItems"
        },
        {
          "kind": "text",
          "text": ": [any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIPreviewActionItem",
          "text": "UIPreviewActionItem"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/previewActionItems",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "previewActionItems"
        }
      ],
      "role": "symbol",
      "title": "previewActionItems",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/previewactionitems"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/registerForPreviewing(with:sourceView:)": {
      "abstract": [
        {
          "text": "Registers a view controller to participate with 3D Touch preview (peek) and commit (pop).",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "registerForPreviewing"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIViewControllerPreviewingDelegate",
          "text": "UIViewControllerPreviewingDelegate"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "sourceView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": ") -> any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIViewControllerPreviewing",
          "text": "UIViewControllerPreviewing"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/registerForPreviewing(with:sourceView:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "registerForPreviewingWithDelegate:sourceView:"
        }
      ],
      "role": "symbol",
      "title": "registerForPreviewing(with:sourceView:)",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/registerforpreviewing(with:sourceview:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/rotatingFooterView()": {
      "abstract": [
        {
          "text": "Returns the footer view to transition during an interface orientation change.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rotatingFooterView"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/rotatingFooterView()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rotatingFooterView"
        }
      ],
      "role": "symbol",
      "title": "rotatingFooterView()",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/rotatingfooterview()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/rotatingHeaderView()": {
      "abstract": [
        {
          "text": "Returns the header view to transition during an interface orientation change.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rotatingHeaderView"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIView",
          "text": "UIView"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/rotatingHeaderView()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rotatingHeaderView"
        }
      ],
      "role": "symbol",
      "title": "rotatingHeaderView()",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/rotatingheaderview()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/searchDisplayController": {
      "abstract": [
        {
          "text": "The search display controller associated with the view controller.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "searchDisplayController"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISearchDisplayController",
          "text": "UISearchDisplayController"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/searchDisplayController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "searchDisplayController"
        }
      ],
      "role": "symbol",
      "title": "searchDisplayController",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/searchdisplaycontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/segueForUnwinding(to:from:identifier:)": {
      "abstract": [
        {
          "text": "Called when an unwind segue action needs to transition between two view controllers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "segueForUnwinding"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "from"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIStoryboardSegue",
          "text": "UIStoryboardSegue"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/segueForUnwinding(to:from:identifier:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "segueForUnwindingToViewController:fromViewController:identifier:"
        }
      ],
      "role": "symbol",
      "title": "segueForUnwinding(to:from:identifier:)",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/segueforunwinding(to:from:identifier:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/setOverrideTraitCollection(_:forChild:)": {
      "abstract": [
        {
          "text": "Changes the traits assigned to the specified child view controller.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "setOverrideTraitCollection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UITraitCollection",
          "text": "UITraitCollection"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "forChild"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/setOverrideTraitCollection(_:forChild:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "setOverrideTraitCollection:forChildViewController:"
        }
      ],
      "role": "symbol",
      "title": "setOverrideTraitCollection(_:forChild:)",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/setoverridetraitcollection(_:forchild:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/shouldAutomaticallyForwardRotationMethods()": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether rotation methods are forwarded to child view controllers.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shouldAutomaticallyForwardRotationMethods"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/shouldAutomaticallyForwardRotationMethods()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shouldAutomaticallyForwardRotationMethods"
        }
      ],
      "role": "symbol",
      "title": "shouldAutomaticallyForwardRotationMethods()",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/shouldautomaticallyforwardrotationmethods()"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/shouldAutorotate": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the view controller’s contents should autorotate.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shouldAutorotate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/shouldAutorotate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shouldAutorotate"
        }
      ],
      "role": "symbol",
      "title": "shouldAutorotate",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/shouldautorotate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/shouldAutorotateToInterfaceOrientation:": {
      "abstract": [
        {
          "text": "Returns a Boolean value indicating whether the view controller supports the specified orientation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "shouldAutorotateToInterfaceOrientation:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/shouldAutorotateToInterfaceOrientation:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "shouldAutorotateToInterfaceOrientation:"
        }
      ],
      "role": "symbol",
      "title": "shouldAutorotateToInterfaceOrientation:",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/shouldautorotatetointerfaceorientation:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/topLayoutGuide": {
      "abstract": [
        {
          "text": "Indicates the highest vertical extent for your onscreen content, for use with Auto Layout constraints.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topLayoutGuide"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UILayoutSupport",
          "text": "UILayoutSupport"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/topLayoutGuide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "topLayoutGuide"
        }
      ],
      "role": "symbol",
      "title": "topLayoutGuide",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/toplayoutguide"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/unregisterForPreviewing(withContext:)": {
      "abstract": [
        {
          "text": "Unregisters a previously registered view controller identified by its context object.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unregisterForPreviewing"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withContext"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIViewControllerPreviewing",
          "text": "UIViewControllerPreviewing"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/unregisterForPreviewing(withContext:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "unregisterForPreviewingWithContext:"
        }
      ],
      "role": "symbol",
      "title": "unregisterForPreviewing(withContext:)",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/unregisterforpreviewing(withcontext:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/viewDidUnload": {
      "abstract": [
        {
          "text": "Called when the controller’s view is released from memory.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "viewDidUnload"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/viewDidUnload",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "viewDidUnload"
        }
      ],
      "role": "symbol",
      "title": "viewDidUnload",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/viewdidunload"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/viewWillUnload": {
      "abstract": [
        {
          "text": "Called just before releasing the controller’s view from memory.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "viewWillUnload"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/viewWillUnload",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "viewWillUnload"
        }
      ],
      "role": "symbol",
      "title": "viewWillUnload",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/viewwillunload"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/wantsFullScreenLayout": {
      "abstract": [
        {
          "text": "A Boolean value indicating whether the view should underlap the status bar.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "wantsFullScreenLayout"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/wantsFullScreenLayout",
      "kind": "symbol",
      "role": "symbol",
      "title": "wantsFullScreenLayout",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/wantsfullscreenlayout"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/willAnimateFirstHalfOfRotationToInterfaceOrientation:duration:": {
      "abstract": [
        {
          "text": "Sent to the view controller before performing the first half of a user interface rotation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "willAnimateFirstHalfOfRotationToInterfaceOrientation:duration:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/willAnimateFirstHalfOfRotationToInterfaceOrientation:duration:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "willAnimateFirstHalfOfRotationToInterfaceOrientation:duration:"
        }
      ],
      "role": "symbol",
      "title": "willAnimateFirstHalfOfRotationToInterfaceOrientation:duration:",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/willanimatefirsthalfofrotationtointerfaceorientation:duration:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/willAnimateRotation(to:duration:)": {
      "abstract": [
        {
          "text": "Sent to the view controller before performing a one-step user interface rotation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "willAnimateRotation"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIInterfaceOrientation",
          "text": "UIInterfaceOrientation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "duration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/willAnimateRotation(to:duration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "willAnimateRotationToInterfaceOrientation:duration:"
        }
      ],
      "role": "symbol",
      "title": "willAnimateRotation(to:duration:)",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/willanimaterotation(to:duration:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/willAnimateSecondHalfOfRotationFromInterfaceOrientation:duration:": {
      "abstract": [
        {
          "text": "Sent to the view controller before the second half of the user interface rotates.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "willAnimateSecondHalfOfRotationFromInterfaceOrientation:duration:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/willAnimateSecondHalfOfRotationFromInterfaceOrientation:duration:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "willAnimateSecondHalfOfRotationFromInterfaceOrientation:duration:"
        }
      ],
      "role": "symbol",
      "title": "willAnimateSecondHalfOfRotationFromInterfaceOrientation:duration:",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/willanimatesecondhalfofrotationfrominterfaceorientation:duration:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/willRotate(to:duration:)": {
      "abstract": [
        {
          "text": "Sent to the view controller just before the user interface begins rotating.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "willRotate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIInterfaceOrientation",
          "text": "UIInterfaceOrientation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "duration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTimeInterval",
          "text": "TimeInterval"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/willRotate(to:duration:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "willRotateToInterfaceOrientation:duration:"
        }
      ],
      "role": "symbol",
      "title": "willRotate(to:duration:)",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/willrotate(to:duration:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/view-controllers": {
      "abstract": [
        {
          "text": "Manage your interface using view controllers and facilitate navigation around your app’s content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/view-controllers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "View controllers",
      "type": "topic",
      "url": "/documentation/uikit/view-controllers"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Deprecated-methods",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/setOverrideTraitCollection(_:forChild:)",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/overrideTraitCollection(forChild:)",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/attemptRotationToDeviceOrientation()",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/registerForPreviewing(with:sourceView:)",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/unregisterForPreviewing(withContext:)",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/canPerformUnwindSegueAction(_:from:withSender:)",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/didRotate(from:)",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/dismissMoviePlayerViewControllerAnimated()",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/forUnwindSegueAction(_:from:withSender:)",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/presentMoviePlayerViewControllerAnimated(_:)",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/rotatingFooterView()",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/rotatingHeaderView()",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/segueForUnwinding(to:from:identifier:)",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/shouldAutomaticallyForwardRotationMethods()",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/willAnimateRotation(to:duration:)",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/willRotate(to:duration:)"
      ],
      "title": "Deprecated methods"
    },
    {
      "anchor": "Deprecated-properties",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/shouldAutorotate",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/previewActionItems",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/automaticallyAdjustsScrollViewInsets",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/bottomLayoutGuide",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/interfaceOrientation",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/isModalInPopover",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/searchDisplayController",
        "doc://com.apple.uikit/documentation/UIKit/UIViewController/topLayoutGuide"
      ],
      "title": "Deprecated properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Deprecated-methods",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/setOverrideTraitCollection(_:forChild:)",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/overrideTraitCollection(forChild:)",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/attemptRotationToDeviceOrientation()",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/registerForPreviewing(with:sourceView:)",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/unregisterForPreviewing(withContext:)",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/automaticallyForwardAppearanceAndRotationMethodsToChildViewControllers",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/canPerformUnwindSegueAction(_:from:withSender:)",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/didAnimateFirstHalfOfRotationToInterfaceOrientation:",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/didRotate(from:)",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/dismissModalViewControllerAnimated:",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/dismissMoviePlayerViewControllerAnimated()",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/forUnwindSegueAction(_:from:withSender:)",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/presentModalViewController:animated:",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/presentMoviePlayerViewControllerAnimated(_:)",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/rotatingFooterView()",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/rotatingHeaderView()",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/segueForUnwinding(to:from:identifier:)",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/shouldAutomaticallyForwardRotationMethods()",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/shouldAutorotateToInterfaceOrientation:",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/viewDidUnload",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/viewWillUnload",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/willAnimateFirstHalfOfRotationToInterfaceOrientation:duration:",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/willAnimateRotation(to:duration:)",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/willAnimateSecondHalfOfRotationFromInterfaceOrientation:duration:",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/willRotate(to:duration:)"
              ],
              "title": "Deprecated methods"
            },
            {
              "anchor": "Deprecated-properties",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/shouldAutorotate",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/previewActionItems",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/automaticallyAdjustsScrollViewInsets",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/bottomLayoutGuide",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/contentSizeForViewInPopover",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/interfaceOrientation",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/isModalInPopover",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/modalViewController",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/searchDisplayController",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/topLayoutGuide",
                "doc://com.apple.uikit/documentation/UIKit/UIViewController/wantsFullScreenLayout"
              ],
              "title": "Deprecated properties"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1interfaceOrientation/title",
          "value": "interfaceOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1interfaceOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "interfaceOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1registerForPreviewing(with:sourceView:)/title",
          "value": "registerForPreviewingWithDelegate:sourceView:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1registerForPreviewing(with:sourceView:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "registerForPreviewingWithDelegate:sourceView:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1forUnwindSegueAction(_:from:withSender:)/title",
          "value": "viewControllerForUnwindSegueAction:fromViewController:withSender:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1forUnwindSegueAction(_:from:withSender:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "viewControllerForUnwindSegueAction:fromViewController:withSender:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1searchDisplayController/title",
          "value": "searchDisplayController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1searchDisplayController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "searchDisplayController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController/title",
          "value": "UIViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1previewActionItems/title",
          "value": "previewActionItems"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1previewActionItems/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "previewActionItems"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1attemptRotationToDeviceOrientation()/title",
          "value": "attemptRotationToDeviceOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1attemptRotationToDeviceOrientation()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "attemptRotationToDeviceOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1topLayoutGuide/title",
          "value": "topLayoutGuide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1topLayoutGuide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "topLayoutGuide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1bottomLayoutGuide/title",
          "value": "bottomLayoutGuide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1bottomLayoutGuide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "bottomLayoutGuide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1dismissMoviePlayerViewControllerAnimated()/title",
          "value": "dismissMoviePlayerViewControllerAnimated"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1dismissMoviePlayerViewControllerAnimated()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dismissMoviePlayerViewControllerAnimated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1segueForUnwinding(to:from:identifier:)/title",
          "value": "segueForUnwindingToViewController:fromViewController:identifier:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1segueForUnwinding(to:from:identifier:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "segueForUnwindingToViewController:fromViewController:identifier:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1rotatingHeaderView()/title",
          "value": "rotatingHeaderView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1rotatingHeaderView()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rotatingHeaderView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1canPerformUnwindSegueAction(_:from:withSender:)/title",
          "value": "canPerformUnwindSegueAction:fromViewController:withSender:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1canPerformUnwindSegueAction(_:from:withSender:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "canPerformUnwindSegueAction:fromViewController:withSender:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1setOverrideTraitCollection(_:forChild:)/title",
          "value": "setOverrideTraitCollection:forChildViewController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1setOverrideTraitCollection(_:forChild:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "setOverrideTraitCollection:forChildViewController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1shouldAutomaticallyForwardRotationMethods()/title",
          "value": "shouldAutomaticallyForwardRotationMethods"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1shouldAutomaticallyForwardRotationMethods()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "shouldAutomaticallyForwardRotationMethods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1willRotate(to:duration:)/title",
          "value": "willRotateToInterfaceOrientation:duration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1willRotate(to:duration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "willRotateToInterfaceOrientation:duration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1overrideTraitCollection(forChild:)/title",
          "value": "overrideTraitCollectionForChildViewController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1overrideTraitCollection(forChild:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "overrideTraitCollectionForChildViewController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1didRotate(from:)/title",
          "value": "didRotateFromInterfaceOrientation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1didRotate(from:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "didRotateFromInterfaceOrientation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1rotatingFooterView()/title",
          "value": "rotatingFooterView"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1rotatingFooterView()/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "rotatingFooterView"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1unregisterForPreviewing(withContext:)/title",
          "value": "unregisterForPreviewingWithContext:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1unregisterForPreviewing(withContext:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "unregisterForPreviewingWithContext:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1willAnimateRotation(to:duration:)/title",
          "value": "willAnimateRotationToInterfaceOrientation:duration:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1willAnimateRotation(to:duration:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "willAnimateRotationToInterfaceOrientation:duration:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1presentMoviePlayerViewControllerAnimated(_:)/title",
          "value": "presentMoviePlayerViewControllerAnimated:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1presentMoviePlayerViewControllerAnimated(_:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "presentMoviePlayerViewControllerAnimated:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1automaticallyAdjustsScrollViewInsets/title",
          "value": "automaticallyAdjustsScrollViewInsets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1automaticallyAdjustsScrollViewInsets/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "automaticallyAdjustsScrollViewInsets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1shouldAutorotate/title",
          "value": "shouldAutorotate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1shouldAutorotate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "shouldAutorotate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1isModalInPopover/title",
          "value": "modalInPopover"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1isModalInPopover/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "modalInPopover"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiviewcontroller-deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiviewcontroller-deprecated-symbols"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
