{
  "abstract": [
    {
      "text": "The methods that objects adopt so that they can act as a restoration class for view controllers during state restoration.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerRestoration"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UIViewControllerRestoration",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIViewControllerRestoration"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIViewControllerRestoration"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "UIViewControllerRestoration"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIViewControllerRestoration"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "To use a class that adopts this protocol, you must assign that class to the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/restorationClass",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property of one of your app’s view controllers. The method in this protocol should be used to create the view controller, if it doesn’t yet exist, or return an existing view controller object, if one does exist.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/swiftui/restoring_your_app_s_state_with_swiftui": {
      "abstract": [
        {
          "text": "Provide app continuity for users by preserving their current activities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/swiftui/restoring_your_app_s_state_with_swiftui",
      "kind": "article",
      "role": "sampleCode",
      "title": "Restoring Your App’s State with SwiftUI",
      "type": "topic",
      "url": "/documentation/swiftui/restoring_your_app_s_state_with_swiftui"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIObjectRestoration": {
      "abstract": [
        {
          "text": "The interface that restoration classes use to restore preserved objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIObjectRestoration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIObjectRestoration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIObjectRestoration"
        }
      ],
      "role": "symbol",
      "title": "UIObjectRestoration",
      "type": "topic",
      "url": "/documentation/uikit/uiobjectrestoration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIStateRestoring": {
      "abstract": [
        {
          "text": "Methods for adding objects to your state restoration archives.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIStateRestoring"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIStateRestoring",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIStateRestoring"
        }
      ],
      "role": "symbol",
      "title": "UIStateRestoring",
      "type": "topic",
      "url": "/documentation/uikit/uistaterestoring"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController/restorationClass": {
      "abstract": [
        {
          "text": "The class responsible for recreating this view controller when restoring the app’s state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "restorationClass"
        },
        {
          "kind": "text",
          "text": ": (any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIViewControllerRestoration",
          "text": "UIViewControllerRestoration"
        },
        {
          "kind": "text",
          "text": ".Type)?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController/restorationClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "restorationClass"
        }
      ],
      "role": "symbol",
      "title": "restorationClass",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller/restorationclass"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewControllerRestoration": {
      "abstract": [
        {
          "text": "The methods that objects adopt so that they can act as a restoration class for view controllers during state restoration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewControllerRestoration"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerRestoration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewControllerRestoration"
        }
      ],
      "role": "symbol",
      "title": "UIViewControllerRestoration",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontrollerrestoration"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewControllerRestoration/viewController(withRestorationIdentifierPath:coder:)": {
      "abstract": [
        {
          "text": "Requests the view controller that corresponds to the specified identifier information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "viewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "withRestorationIdentifierPath"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "coder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCoder",
          "text": "NSCoder"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerRestoration/viewController(withRestorationIdentifierPath:coder:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "viewControllerWithRestorationIdentifierPath:coder:"
        }
      ],
      "required": true,
      "role": "symbol",
      "title": "viewController(withRestorationIdentifierPath:coder:)",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontrollerrestoration/viewcontroller(withrestorationidentifierpath:coder:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/preserving-your-app-s-ui-across-launches": {
      "abstract": [
        {
          "text": "Return your app to its previous state after the system terminates it.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/preserving-your-app-s-ui-across-launches",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Preserving your app’s UI across launches",
      "type": "topic",
      "url": "/documentation/uikit/preserving-your-app-s-ui-across-launches"
    },
    "doc://com.apple.uikit/documentation/UIKit/restoring-your-app-s-state": {
      "abstract": [
        {
          "text": "Provide continuity for the user by preserving current activities.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/restoring-your-app-s-state",
      "kind": "article",
      "role": "sampleCode",
      "title": "Restoring your app’s state",
      "type": "topic",
      "url": "/documentation/uikit/restoring-your-app-s-state"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Interface-restoration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/restoring-your-app-s-state",
        "doc://com.apple.documentation/documentation/swiftui/restoring_your_app_s_state_with_swiftui",
        "doc://com.apple.uikit/documentation/UIKit/preserving-your-app-s-ui-across-launches",
        "doc://com.apple.uikit/documentation/UIKit/UIObjectRestoration",
        "doc://com.apple.uikit/documentation/UIKit/UIStateRestoring"
      ],
      "title": "Interface restoration"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-the-view-controller",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIViewControllerRestoration/viewController(withRestorationIdentifierPath:coder:)"
      ],
      "title": "Creating the view controller"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIViewControllerRestoration"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "protocol"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerRestoration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerRestoration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-the-view-controller",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIViewControllerRestoration/viewController(withRestorationIdentifierPath:coder:)"
              ],
              "title": "Creating the view controller"
            }
          ]
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Interface-restoration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/restoring-your-app-s-state",
                "doc://com.apple.documentation/documentation/swiftui/restoring_your_app_s_state_with_swiftui",
                "doc://com.apple.uikit/documentation/UIKit/preserving-your-app-s-ui-across-launches",
                "doc://com.apple.uikit/documentation/UIKit/UIObjectRestoration",
                "doc://com.apple.uikit/documentation/UIKit/UIStateRestoring"
              ],
              "title": "Interface restoration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@protocol"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIViewControllerRestoration"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerRestoration/title",
          "value": "UIViewControllerRestoration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerRestoration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerRestoration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerRestoration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerRestoration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1restorationClass/title",
          "value": "restorationClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController~1restorationClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "restorationClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerRestoration~1viewController(withRestorationIdentifierPath:coder:)/title",
          "value": "viewControllerWithRestorationIdentifierPath:coder:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerRestoration~1viewController(withRestorationIdentifierPath:coder:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "viewControllerWithRestorationIdentifierPath:coder:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIObjectRestoration/title",
          "value": "UIObjectRestoration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIObjectRestoration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIObjectRestoration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIObjectRestoration/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIObjectRestoration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStateRestoring/title",
          "value": "UIStateRestoring"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStateRestoring/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIStateRestoring"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIStateRestoring/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIStateRestoring"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiviewcontrollerrestoration"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiviewcontrollerrestoration"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
