{
  "abstract": [
    {
      "text": "Constants for the vibrancy styles.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffectStyle"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UIVibrancyEffectStyle",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIVibrancyEffectStyle"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIVibrancyEffectStyle"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "UIVibrancyEffectStyle"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIVibrancyEffectStyle"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffect/init(blurEffect:)": {
      "abstract": [
        {
          "text": "Creates a vibrancy effect for a specific blur effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "blurEffect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIBlurEffect",
          "text": "UIBlurEffect"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffect/init(blurEffect:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "effectForBlurEffect:"
        }
      ],
      "role": "symbol",
      "title": "init(blurEffect:)",
      "type": "topic",
      "url": "/documentation/uikit/uivibrancyeffect/init(blureffect:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffect/init(forBlurEffect:style:)": {
      "abstract": [
        {
          "text": "Creates a vibrancy effect with the specified blur and style values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forBlurEffect"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIBlurEffect",
          "text": "UIBlurEffect"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "style"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIVibrancyEffectStyle",
          "text": "UIVibrancyEffectStyle"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffect/init(forBlurEffect:style:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "effectForBlurEffect:style:"
        }
      ],
      "role": "symbol",
      "title": "init(forBlurEffect:style:)",
      "type": "topic",
      "url": "/documentation/uikit/uivibrancyeffect/init(forblureffect:style:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffectStyle": {
      "abstract": [
        {
          "text": "Constants for the vibrancy styles.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIVibrancyEffectStyle"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffectStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIVibrancyEffectStyle"
        }
      ],
      "role": "symbol",
      "title": "UIVibrancyEffectStyle",
      "type": "topic",
      "url": "/documentation/uikit/uivibrancyeffectstyle"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffectStyle/fill": {
      "abstract": [
        {
          "text": "A style for views with large filled areas containing primary content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fill"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffectStyle/fill",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIVibrancyEffectStyleFill"
        }
      ],
      "role": "symbol",
      "title": "UIVibrancyEffectStyle.fill",
      "type": "topic",
      "url": "/documentation/uikit/uivibrancyeffectstyle/fill"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffectStyle/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffectStyle/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/uikit/uivibrancyeffectstyle/init(rawvalue:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffectStyle/label": {
      "abstract": [
        {
          "text": "A style for labels containing primary content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "label"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffectStyle/label",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIVibrancyEffectStyleLabel"
        }
      ],
      "role": "symbol",
      "title": "UIVibrancyEffectStyle.label",
      "type": "topic",
      "url": "/documentation/uikit/uivibrancyeffectstyle/label"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffectStyle/quaternaryLabel": {
      "abstract": [
        {
          "text": "A style for labels containing quaternary content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "quaternaryLabel"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffectStyle/quaternaryLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIVibrancyEffectStyleQuaternaryLabel"
        }
      ],
      "role": "symbol",
      "title": "UIVibrancyEffectStyle.quaternaryLabel",
      "type": "topic",
      "url": "/documentation/uikit/uivibrancyeffectstyle/quaternarylabel"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffectStyle/secondaryFill": {
      "abstract": [
        {
          "text": "A style for views with large filled areas containing secondary content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "secondaryFill"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffectStyle/secondaryFill",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIVibrancyEffectStyleSecondaryFill"
        }
      ],
      "role": "symbol",
      "title": "UIVibrancyEffectStyle.secondaryFill",
      "type": "topic",
      "url": "/documentation/uikit/uivibrancyeffectstyle/secondaryfill"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffectStyle/secondaryLabel": {
      "abstract": [
        {
          "text": "A style for labels containing secondary content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "secondaryLabel"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffectStyle/secondaryLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIVibrancyEffectStyleSecondaryLabel"
        }
      ],
      "role": "symbol",
      "title": "UIVibrancyEffectStyle.secondaryLabel",
      "type": "topic",
      "url": "/documentation/uikit/uivibrancyeffectstyle/secondarylabel"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffectStyle/separator": {
      "abstract": [
        {
          "text": "A style for separator lines.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "separator"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffectStyle/separator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIVibrancyEffectStyleSeparator"
        }
      ],
      "role": "symbol",
      "title": "UIVibrancyEffectStyle.separator",
      "type": "topic",
      "url": "/documentation/uikit/uivibrancyeffectstyle/separator"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffectStyle/tertiaryFill": {
      "abstract": [
        {
          "text": "A style for views with large filled areas containing tertiary content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tertiaryFill"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffectStyle/tertiaryFill",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIVibrancyEffectStyleTertiaryFill"
        }
      ],
      "role": "symbol",
      "title": "UIVibrancyEffectStyle.tertiaryFill",
      "type": "topic",
      "url": "/documentation/uikit/uivibrancyeffectstyle/tertiaryfill"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffectStyle/tertiaryLabel": {
      "abstract": [
        {
          "text": "A style for labels containing tertiary content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tertiaryLabel"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffectStyle/tertiaryLabel",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIVibrancyEffectStyleTertiaryLabel"
        }
      ],
      "role": "symbol",
      "title": "UIVibrancyEffectStyle.tertiaryLabel",
      "type": "topic",
      "url": "/documentation/uikit/uivibrancyeffectstyle/tertiarylabel"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSInteger": {
      "abstract": [
        {
          "text": "Describes an integer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "NSInteger"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-vibrancy-effect",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffect/init(forBlurEffect:style:)",
        "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffect/init(blurEffect:)"
      ],
      "title": "Creating a vibrancy effect"
    }
  ],
  "topicSections": [
    {
      "anchor": "Label-styles",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffectStyle/label",
        "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffectStyle/secondaryLabel",
        "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffectStyle/tertiaryLabel",
        "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffectStyle/quaternaryLabel"
      ],
      "title": "Label styles"
    },
    {
      "anchor": "Fill-styles",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffectStyle/fill",
        "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffectStyle/secondaryFill",
        "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffectStyle/tertiaryFill"
      ],
      "title": "Fill styles"
    },
    {
      "anchor": "Separator-style",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffectStyle/separator"
      ],
      "title": "Separator style"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffectStyle/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIVibrancyEffectStyle"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIVibrancyEffectStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIVibrancyEffectStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Label-styles",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffectStyle/label",
                "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffectStyle/secondaryLabel",
                "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffectStyle/tertiaryLabel",
                "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffectStyle/quaternaryLabel"
              ],
              "title": "Label styles"
            },
            {
              "anchor": "Fill-styles",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffectStyle/fill",
                "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffectStyle/secondaryFill",
                "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffectStyle/tertiaryFill"
              ],
              "title": "Fill styles"
            },
            {
              "anchor": "Separator-style",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffectStyle/separator"
              ],
              "title": "Separator style"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-a-vibrancy-effect",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffect/init(forBlurEffect:style:)",
                "doc://com.apple.uikit/documentation/UIKit/UIVibrancyEffect/init(blurEffect:)"
              ],
              "title": "Creating a vibrancy effect"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "UIVibrancyEffectStyle"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSInteger",
                    "text": "NSInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIVibrancyEffect~1init(forBlurEffect:style:)/title",
          "value": "effectForBlurEffect:style:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIVibrancyEffect~1init(forBlurEffect:style:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "effectForBlurEffect:style:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIVibrancyEffectStyle~1fill/title",
          "value": "UIVibrancyEffectStyleFill"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIVibrancyEffectStyle~1fill/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIVibrancyEffectStyleFill"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIVibrancyEffectStyle~1secondaryLabel/title",
          "value": "UIVibrancyEffectStyleSecondaryLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIVibrancyEffectStyle~1secondaryLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIVibrancyEffectStyleSecondaryLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIVibrancyEffectStyle~1secondaryFill/title",
          "value": "UIVibrancyEffectStyleSecondaryFill"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIVibrancyEffectStyle~1secondaryFill/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIVibrancyEffectStyleSecondaryFill"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIVibrancyEffectStyle~1label/title",
          "value": "UIVibrancyEffectStyleLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIVibrancyEffectStyle~1label/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIVibrancyEffectStyleLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIVibrancyEffectStyle~1separator/title",
          "value": "UIVibrancyEffectStyleSeparator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIVibrancyEffectStyle~1separator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIVibrancyEffectStyleSeparator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIVibrancyEffect~1init(blurEffect:)/title",
          "value": "effectForBlurEffect:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIVibrancyEffect~1init(blurEffect:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "+ "
            },
            {
              "kind": "identifier",
              "text": "effectForBlurEffect:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIVibrancyEffectStyle~1tertiaryFill/title",
          "value": "UIVibrancyEffectStyleTertiaryFill"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIVibrancyEffectStyle~1tertiaryFill/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIVibrancyEffectStyleTertiaryFill"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIVibrancyEffectStyle~1tertiaryLabel/title",
          "value": "UIVibrancyEffectStyleTertiaryLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIVibrancyEffectStyle~1tertiaryLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIVibrancyEffectStyleTertiaryLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIVibrancyEffectStyle~1quaternaryLabel/title",
          "value": "UIVibrancyEffectStyleQuaternaryLabel"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIVibrancyEffectStyle~1quaternaryLabel/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIVibrancyEffectStyleQuaternaryLabel"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIVibrancyEffectStyle/title",
          "value": "UIVibrancyEffectStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIVibrancyEffectStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIVibrancyEffectStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIVibrancyEffectStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIVibrancyEffectStyle"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uivibrancyeffectstyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uivibrancyeffectstyle"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
