{
  "abstract": [
    {
      "text": "A structure that encapsulates a view’s state.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "occ",
    "url": "doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-c.class"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)UIViewConfigurationState",
    "fragments": [
      {
        "kind": "identifier",
        "text": "UIViewConfigurationState"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIViewConfigurationState"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "UIViewConfigurationState"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "occ"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIViewConfigurationState"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A view configuration state encompasses a trait collection along with all of the common states that affect a view’s appearance — states like selected, focused, or disabled. A view configuration state encapsulates the inputs that configure a view for any possible state or combination of states. You use a view configuration state with background and content configurations to obtain the default appearance for a specific state.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Typically, you don’t create a configuration state yourself. To obtain a configuration state, override the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/updateConfiguration(using:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method in your view subclass and use the state parameter. Outside of this method, you can get a view’s configuration state by using its ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/configurationState-4u37h",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " property.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "You can create your own custom states to add to a view configuration state by defining a custom state key using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIConfigurationStateCustomKey",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICellConfigurationState-c.class": {
      "abstract": [
        {
          "text": "An object that encapsulates a cell’s state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UICellConfigurationState"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICellConfigurationState-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UICellConfigurationState",
      "type": "topic",
      "url": "/documentation/uikit/uicellconfigurationstate-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/configurationState-4u37h": {
      "abstract": [
        {
          "text": "The current configuration state of the cell.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit24UICellConfigurationStateV",
          "text": "UICellConfigurationState"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/configurationState-4u37h",
      "kind": "symbol",
      "role": "symbol",
      "title": "configurationState",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewcell/configurationstate-4u37h"
    },
    "doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/updateConfiguration(using:)": {
      "abstract": [
        {
          "text": "Updates the cell’s configuration using the current state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateConfiguration"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "using"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:5UIKit24UICellConfigurationStateV",
          "text": "UICellConfigurationState"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UICollectionViewCell/updateConfiguration(using:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "updateConfiguration(using:)",
      "type": "topic",
      "url": "/documentation/uikit/uicollectionviewcell/updateconfiguration(using:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-1smq1": {
      "abstract": [
        {
          "text": "The requirements for an object that encapsulates a view’s state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIConfigurationState"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-1smq1",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIConfigurationState",
      "type": "topic",
      "url": "/documentation/uikit/uiconfigurationstate-1smq1"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIConfigurationStateCustomKey": {
      "abstract": [
        {
          "text": "A key that defines a custom state for a view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIConfigurationStateCustomKey"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIConfigurationStateCustomKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIConfigurationStateCustomKey"
        }
      ],
      "role": "symbol",
      "title": "UIConfigurationStateCustomKey",
      "type": "topic",
      "url": "/documentation/uikit/uiconfigurationstatecustomkey"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-c.class": {
      "abstract": [
        {
          "text": "A structure that encapsulates a view’s state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "UIViewConfigurationState"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-c.class",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIViewConfigurationState",
      "type": "topic",
      "url": "/documentation/uikit/uiviewconfigurationstate-c.class"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-c.class/disabled": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the view is in a disabled state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "disabled"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-c.class/disabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "disabled",
      "type": "topic",
      "url": "/documentation/uikit/uiviewconfigurationstate-c.class/disabled"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-c.class/focused": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the view is in a focused state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "focused"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-c.class/focused",
      "kind": "symbol",
      "role": "symbol",
      "title": "focused",
      "type": "topic",
      "url": "/documentation/uikit/uiviewconfigurationstate-c.class/focused"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-c.class/highlighted": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the view is in a highlighted state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "highlighted"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-c.class/highlighted",
      "kind": "symbol",
      "role": "symbol",
      "title": "highlighted",
      "type": "topic",
      "url": "/documentation/uikit/uiviewconfigurationstate-c.class/highlighted"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-c.class/initWithCoder:": {
      "abstract": [
        {
          "text": "Creates a view configuration state from data in an unarchiver.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithCoder:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-c.class/initWithCoder:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithCoder:"
        }
      ],
      "role": "symbol",
      "title": "initWithCoder:",
      "type": "topic",
      "url": "/documentation/uikit/uiviewconfigurationstate-c.class/initwithcoder:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-c.class/initWithTraitCollection:": {
      "abstract": [
        {
          "text": "Creates a view configuration state with the specified trait collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "- "
        },
        {
          "kind": "identifier",
          "text": "initWithTraitCollection:"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-c.class/initWithTraitCollection:",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithTraitCollection:"
        }
      ],
      "role": "symbol",
      "title": "initWithTraitCollection:",
      "type": "topic",
      "url": "/documentation/uikit/uiviewconfigurationstate-c.class/initwithtraitcollection:"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-c.class/pinned": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the view is in a pinned state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "pinned"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-c.class/pinned",
      "kind": "symbol",
      "role": "symbol",
      "title": "pinned",
      "type": "topic",
      "url": "/documentation/uikit/uiviewconfigurationstate-c.class/pinned"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-c.class/selected": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the view is in a selected state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "selected"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-c.class/selected",
      "kind": "symbol",
      "role": "symbol",
      "title": "selected",
      "type": "topic",
      "url": "/documentation/uikit/uiviewconfigurationstate-c.class/selected"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-c.class/traitCollection": {
      "abstract": [
        {
          "text": "The traits that describe the current layout environment of the view, such as the user interface style and layout direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "traitCollection"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-c.class/traitCollection",
      "kind": "symbol",
      "role": "symbol",
      "title": "traitCollection",
      "type": "topic",
      "url": "/documentation/uikit/uiviewconfigurationstate-c.class/traitcollection"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSObject": {
      "abstract": [
        {
          "text": "The root class of most Objective-C class hierarchies, from which subclasses inherit a basic interface to the runtime system and the ability to behave as Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObject",
      "type": "topic",
      "url": "/documentation/objectivec/nsobject"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)NSObject"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICellConfigurationState-c.class"
      ],
      "kind": "relationships",
      "title": "Inherited By",
      "type": "inheritedBy"
    },
    {
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-1smq1"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Configuration-states",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UICellConfigurationState-c.class",
        "doc://com.apple.uikit/documentation/UIKit/UIConfigurationState-1smq1",
        "doc://com.apple.uikit/documentation/UIKit/UIConfigurationStateCustomKey"
      ],
      "title": "Configuration states"
    }
  ],
  "topicSections": [
    {
      "anchor": "Managing-view-configuration-states",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-c.class/traitCollection",
        "doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-c.class/selected",
        "doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-c.class/highlighted",
        "doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-c.class/focused",
        "doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-c.class/disabled",
        "doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-c.class/pinned"
      ],
      "title": "Managing view configuration states"
    },
    {
      "anchor": "Creating-a-configuration-state-manually",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-c.class/initWithTraitCollection:",
        "doc://com.apple.uikit/documentation/UIKit/UIViewConfigurationState-c.class/initWithCoder:"
      ],
      "title": "Creating a configuration state manually"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIConfigurationStateCustomKey/title",
          "value": "UIConfigurationStateCustomKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIConfigurationStateCustomKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIConfigurationStateCustomKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIConfigurationStateCustomKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIConfigurationStateCustomKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiviewconfigurationstate-c.class"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
