{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uiwindowscenedestructionrequestoptions"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/uikit/uiwindowscenedestructionrequestoptions"]}],"metadata":{"title":"UIWindowSceneDestructionRequestOptions","platforms":[{"deprecated":false,"unavailable":false,"name":"iOS","beta":false,"introducedAt":"13.0"},{"deprecated":false,"unavailable":false,"name":"iPadOS","beta":false,"introducedAt":"13.0"},{"deprecated":false,"beta":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"13.1"},{"deprecated":false,"beta":false,"unavailable":false,"name":"tvOS","introducedAt":"13.0"},{"deprecated":false,"beta":false,"unavailable":false,"name":"visionOS","introducedAt":"1.0"}],"symbolKind":"class","modules":[{"name":"UIKit"}],"navigatorTitle":[{"kind":"identifier","text":"UIWindowSceneDestructionRequestOptions"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIWindowSceneDestructionRequestOptions"}],"externalID":"c:objc(cs)UIWindowSceneDestructionRequestOptions","roleHeading":"Class"},"sections":[],"abstract":[{"type":"text","text":"An object that contains information to use when removing a window scene from your app."}],"seeAlsoSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UISceneActivationConditions","doc://com.apple.uikit/documentation/UIKit/UIScene/ActivationRequestOptions","doc://com.apple.uikit/documentation/UIKit/UISceneDestructionRequestOptions"],"generated":true,"title":"Activation and destruction","anchor":"Activation-and-destruction"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","identifier":"doc://com.externally.resolved.symbol/s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIWindowSceneDestructionRequestOptions","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"},{"content":[{"level":2,"text":"Overview","anchor":"overview","type":"heading"},{"inlineContent":[{"text":"Create a ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIWindowSceneDestructionRequestOptions","isActive":true,"type":"reference"},{"text":" object before you close one of your app’s scenes using the ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication/requestSceneSessionDestruction(_:options:errorHandler:)","isActive":true,"type":"reference"},{"text":" method of ","type":"text"},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication","isActive":true,"type":"reference"},{"text":". Use this object to specify the dismissal animations to apply to the scene’s UI, if that UI is onscreen.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIWindowSceneDestructionRequestOptions","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIWindowSceneDestructionRequestOptions/windowDismissalAnimation","doc://com.apple.uikit/documentation/UIKit/UIWindowScene/DismissalAnimation"],"title":"Configuring the dismissal animation","anchor":"Configuring-the-dismissal-animation"}],"relationshipsSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UISceneDestructionRequestOptions"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"identifiers":["doc://com.externally.resolved.symbol/s:s7CVarArgP","doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","doc://com.externally.resolved.symbol/s:SQ","doc://com.externally.resolved.symbol/s:SH","doc://com.externally.resolved.symbol/c:objc(pl)NSObject","doc://com.externally.resolved.symbol/s:s8SendableP"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"references":{"doc://com.externally.resolved.symbol/s:s8SendableP":{"abstract":[{"type":"text","text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races."}],"url":"/documentation/Swift/Sendable","identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"}],"role":"symbol","title":"Sendable","type":"topic","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIApplication/requestSceneSessionDestruction(_:options:errorHandler:)":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication/requestSceneSessionDestruction(_:options:errorHandler:)","url":"/documentation/uikit/uiapplication/requestscenesessiondestruction(_:options:errorhandler:)","title":"requestSceneSessionDestruction(_:options:errorHandler:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"requestSceneSessionDestruction:options:errorHandler:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestSceneSessionDestruction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UISceneSession","preciseIdentifier":"c:objc(cs)UISceneSession"},{"kind":"text","text":", "},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UISceneDestructionRequestOptions","text":"UISceneDestructionRequestOptions","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"errorHandler"},{"kind":"text","text":": ((any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}],"type":"topic","kind":"symbol","abstract":[{"text":"Asks the system to dismiss an existing scene and remove it from the app switcher.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UISceneDestructionRequestOptions":{"navigatorTitle":[{"text":"UISceneDestructionRequestOptions","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UISceneDestructionRequestOptions","kind":"identifier"}],"type":"topic","abstract":[{"text":"An object you pass to UIKit to permanently remove a scene and its associated session from your app.","type":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISceneDestructionRequestOptions","title":"UISceneDestructionRequestOptions","url":"/documentation/uikit/uiscenedestructionrequestoptions","kind":"symbol"},"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP":{"identifier":"doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP","kind":"symbol","type":"topic","title":"CustomDebugStringConvertible","url":"/documentation/Swift/CustomDebugStringConvertible","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomDebugStringConvertible"}],"role":"symbol","abstract":[{"type":"text","text":"A type with a customized textual representation suitable for debugging purposes."}]},"doc://com.externally.resolved.symbol/s:s7CVarArgP":{"abstract":[{"type":"text","text":"A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CVarArg"}],"identifier":"doc://com.externally.resolved.symbol/s:s7CVarArgP","type":"topic","title":"CVarArg","kind":"symbol","role":"symbol","url":"/documentation/Swift/CVarArg"},"doc://com.apple.uikit/documentation/UIKit/UIWindowSceneDestructionRequestOptions/windowDismissalAnimation":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIWindowSceneDestructionRequestOptions/windowDismissalAnimation","navigatorTitle":[{"text":"windowDismissalAnimation","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"windowDismissalAnimation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIWindowScene","preciseIdentifier":"c:objc(cs)UIWindowScene","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"DismissalAnimation","preciseIdentifier":"c:@E@UIWindowSceneDismissalAnimation","kind":"typeIdentifier"}],"url":"/documentation/uikit/uiwindowscenedestructionrequestoptions/windowdismissalanimation","kind":"symbol","role":"symbol","type":"topic","title":"windowDismissalAnimation","abstract":[{"text":"The animations to use when dismissing the scene’s windows.","type":"text"}]},"doc://com.apple.uikit/documentation/UIKit/UISceneActivationConditions":{"identifier":"doc://com.apple.uikit/documentation/UIKit/UISceneActivationConditions","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UISceneActivationConditions"}],"title":"UISceneActivationConditions","abstract":[{"type":"text","text":"The set of conditions that define when UIKit activates the current scene."}],"url":"/documentation/uikit/uisceneactivationconditions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UISceneActivationConditions"}],"role":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.externally.resolved.symbol/s:SQ":{"abstract":[{"type":"text","text":"A type that can be compared for value equality."}],"url":"/documentation/Swift/Equatable","identifier":"doc://com.externally.resolved.symbol/s:SQ","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Equatable","kind":"identifier"}],"role":"symbol","title":"Equatable","type":"topic","kind":"symbol"},"doc://com.externally.resolved.symbol/s:SH":{"abstract":[{"type":"text","text":"A type that can be hashed into a `Hasher` to produce an integer hash value."}],"url":"/documentation/Swift/Hashable","identifier":"doc://com.externally.resolved.symbol/s:SH","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hashable","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SQ","text":"Equatable","kind":"typeIdentifier"}],"role":"symbol","title":"Hashable","type":"topic","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIWindowScene/DismissalAnimation":{"abstract":[{"text":"Constants that indicate the types of animations available for dismissing a scene’s windows.","type":"text"}],"url":"/documentation/uikit/uiwindowscene/dismissalanimation","identifier":"doc://com.apple.uikit/documentation/UIKit/UIWindowScene/DismissalAnimation","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DismissalAnimation","kind":"identifier"}],"role":"symbol","title":"UIWindowScene.DismissalAnimation","type":"topic","kind":"symbol","navigatorTitle":[{"text":"DismissalAnimation","kind":"identifier"}]},"doc://com.apple.uikit/documentation/UIKit/UIScene/ActivationRequestOptions":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActivationRequestOptions","kind":"identifier"}],"abstract":[{"type":"text","text":"An object that contains information you want the system to use when activating the session associated with a scene."}],"title":"UIScene.ActivationRequestOptions","navigatorTitle":[{"text":"ActivationRequestOptions","kind":"identifier"}],"url":"/documentation/uikit/uiscene/activationrequestoptions","kind":"symbol","type":"topic","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIScene/ActivationRequestOptions"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP":{"identifier":"doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP","kind":"symbol","type":"topic","title":"CustomStringConvertible","url":"/documentation/Swift/CustomStringConvertible","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomStringConvertible"}],"role":"symbol","abstract":[{"text":"A type with a customized textual representation.","type":"text"}]},"doc://com.externally.resolved.symbol/s:ScM":{"abstract":[{"text":"A singleton actor whose executor is equivalent to the main dispatch queue.","type":"text"}],"url":"/documentation/Swift/MainActor","identifier":"doc://com.externally.resolved.symbol/s:ScM","title":"MainActor","fragments":[{"text":"@globalActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actor","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MainActor","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.externally.resolved.symbol/c:objc(pl)NSObject":{"title":"NSObjectProtocol","type":"topic","abstract":[{"text":"The group of methods that are fundamental to all Objective-C objects.","type":"text"}],"identifier":"doc://com.externally.resolved.symbol/c:objc(pl)NSObject","role":"symbol","fragments":[{"text":"protocol ","kind":"text"},{"text":"NSObjectProtocol","kind":"identifier"}],"kind":"symbol","url":"/documentation/objectivec/nsobjectprotocol"},"doc://com.apple.uikit/documentation/UIKit/UIApplication":{"kind":"symbol","role":"symbol","title":"UIApplication","navigatorTitle":[{"text":"UIApplication","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIApplication","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIApplication","url":"/documentation/uikit/uiapplication","abstract":[{"type":"text","text":"The centralized point of control and coordination for apps running in iOS."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIWindowSceneDestructionRequestOptions":{"navigatorTitle":[{"kind":"identifier","text":"UIWindowSceneDestructionRequestOptions"}],"abstract":[{"text":"An object that contains information to use when removing a window scene from your app.","type":"text"}],"type":"topic","role":"symbol","title":"UIWindowSceneDestructionRequestOptions","identifier":"doc://com.apple.uikit/documentation/UIKit/UIWindowSceneDestructionRequestOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIWindowSceneDestructionRequestOptions"}],"kind":"symbol","url":"/documentation/uikit/uiwindowscenedestructionrequestoptions"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"13.0","name":"iOS"},{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"13.0","name":"iPadOS"},{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"13.1","name":"Mac Catalyst"},{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"13.0","name":"tvOS"},{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"1.0","name":"visionOS"}],"path":"/metadata/platforms"},{"op":"replace","value":"Class","path":"/metadata/roleHeading"},{"op":"replace","value":"UIWindowSceneDestructionRequestOptions","path":"/metadata/title"},{"op":"replace","value":"class","path":"/metadata/symbolKind"},{"op":"replace","value":[{"text":"UIWindowSceneDestructionRequestOptions","kind":"identifier"}],"path":"/metadata/fragments"},{"op":"replace","value":[{"text":"UIWindowSceneDestructionRequestOptions","kind":"identifier"}],"path":"/metadata/navigatorTitle"},{"op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit"]]},"path":"/hierarchy"},{"op":"replace","value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIWindowSceneDestructionRequestOptions/windowDismissalAnimation","doc://com.apple.uikit/documentation/UIKit/UIWindowScene/DismissalAnimation"],"title":"Configuring the dismissal animation","anchor":"Configuring-the-dismissal-animation"}],"path":"/topicSections"},{"op":"replace","value":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UISceneDestructionRequestOptions"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"path":"/relationshipsSections"},{"op":"replace","value":[{"generated":true,"title":"Activation and destruction","identifiers":["doc://com.apple.uikit/documentation/UIKit/UISceneActivationConditions","doc://com.apple.uikit/documentation/UIKit/UIScene/ActivationRequestOptions","doc://com.apple.uikit/documentation/UIKit/UISceneDestructionRequestOptions"],"anchor":"Activation-and-destruction"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIWindowSceneDestructionRequestOptions","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UISceneDestructionRequestOptions","text":"UISceneDestructionRequestOptions","kind":"typeIdentifier","identifier":"doc://com.apple.uikit/documentation/UIKit/UISceneDestructionRequestOptions"}],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"value":"requestSceneSessionDestruction:options:errorHandler:","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1requestSceneSessionDestruction(_:options:errorHandler:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"requestSceneSessionDestruction:options:errorHandler:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication~1requestSceneSessionDestruction(_:options:errorHandler:)/fragments","op":"replace"},{"value":"UISceneDestructionRequestOptions","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneDestructionRequestOptions/title","op":"replace"},{"value":[{"text":"UISceneDestructionRequestOptions","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneDestructionRequestOptions/fragments","op":"replace"},{"value":[{"text":"UISceneDestructionRequestOptions","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneDestructionRequestOptions/navigatorTitle","op":"replace"},{"value":"windowDismissalAnimation","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowSceneDestructionRequestOptions~1windowDismissalAnimation/title","op":"replace"},{"value":[{"kind":"identifier","text":"windowDismissalAnimation"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowSceneDestructionRequestOptions~1windowDismissalAnimation/fragments","op":"replace"},{"value":"UISceneActivationConditions","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneActivationConditions/title","op":"replace"},{"value":[{"text":"UISceneActivationConditions","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneActivationConditions/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"UISceneActivationConditions"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneActivationConditions/navigatorTitle","op":"replace"},{"value":"UIWindowSceneDismissalAnimation","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1DismissalAnimation/title","op":"replace"},{"value":[{"text":"UIWindowSceneDismissalAnimation","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1DismissalAnimation/fragments","op":"replace"},{"value":[{"text":"UIWindowSceneDismissalAnimation","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowScene~1DismissalAnimation/navigatorTitle","op":"replace"},{"value":"UISceneActivationRequestOptions","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScene~1ActivationRequestOptions/title","op":"replace"},{"value":[{"text":"UISceneActivationRequestOptions","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScene~1ActivationRequestOptions/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"UISceneActivationRequestOptions"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIScene~1ActivationRequestOptions/navigatorTitle","op":"replace"},{"value":"NSObject","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title","op":"replace"},{"value":"UIApplication","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/title","op":"replace"},{"value":[{"text":"UIApplication","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/fragments","op":"replace"},{"value":[{"text":"UIApplication","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIApplication/navigatorTitle","op":"replace"},{"value":"UIWindowSceneDestructionRequestOptions","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowSceneDestructionRequestOptions/title","op":"replace"},{"value":[{"kind":"identifier","text":"UIWindowSceneDestructionRequestOptions"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowSceneDestructionRequestOptions/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"UIWindowSceneDestructionRequestOptions"}],"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIWindowSceneDestructionRequestOptions/navigatorTitle","op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}