{
  "abstract": [
    {
      "text": "Use these keys to access the representation types of pasteboard items that you add to, or remove from, a pasteboard.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/documents-data-and-pasteboard",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/userinfo-dictionary-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "UserInfo Dictionary Keys"
  },
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard": {
      "abstract": [
        {
          "text": "An object that helps a user share data from one place to another within your app, and from your app to other apps.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPasteboard"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPasteboard"
        }
      ],
      "role": "symbol",
      "title": "UIPasteboard",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/Name-swift.struct": {
      "abstract": [
        {
          "text": "Constants that identify the name of a pasteboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/Name-swift.struct",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Name"
        }
      ],
      "role": "symbol",
      "title": "UIPasteboard.Name",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/name-swift.struct"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/OptionsKey": {
      "abstract": [
        {
          "text": "Options for describing pasteboard privacy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionsKey"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/OptionsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "OptionsKey"
        }
      ],
      "role": "symbol",
      "title": "UIPasteboard.OptionsKey",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/optionskey"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/changedNotification": {
      "abstract": [
        {
          "text": "A notification that a pasteboard object posts when its contents change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changedNotification"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSNotification",
          "text": "NSNotification"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSNotificationName",
          "text": "Name"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/changedNotification",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPasteboardChangedNotification"
        }
      ],
      "role": "symbol",
      "title": "changedNotification",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/changednotification"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/changedTypesAddedUserInfoKey": {
      "abstract": [
        {
          "text": "With the notification named ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/changedNotification",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", use this key to access the added representation types. These types are stored as an array in the notification’s ",
          "type": "text"
        },
        {
          "code": "userInfo",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changedTypesAddedUserInfoKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/changedTypesAddedUserInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPasteboardChangedTypesAddedKey"
        }
      ],
      "role": "symbol",
      "title": "changedTypesAddedUserInfoKey",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/changedtypesaddeduserinfokey"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/changedTypesRemovedUserInfoKey": {
      "abstract": [
        {
          "text": "With the notification named ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/changedNotification",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ", use this key to access the removed representation types. These types are stored as an array in the notification’s ",
          "type": "text"
        },
        {
          "code": "userInfo",
          "type": "codeVoice"
        },
        {
          "text": " dictionary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "changedTypesRemovedUserInfoKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/changedTypesRemovedUserInfoKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPasteboardChangedTypesRemovedKey"
        }
      ],
      "role": "symbol",
      "title": "changedTypesRemovedUserInfoKey",
      "type": "topic",
      "url": "/documentation/uikit/uipasteboard/changedtypesremoveduserinfokey"
    },
    "doc://com.apple.uikit/documentation/UIKit/documents-data-and-pasteboard": {
      "abstract": [
        {
          "text": "Organize your app’s data and share that data on the pasteboard.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/documents-data-and-pasteboard",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Documents, data, and pasteboard",
      "type": "topic",
      "url": "/documentation/uikit/documents-data-and-pasteboard"
    },
    "doc://com.apple.uikit/documentation/UIKit/pasteboard-data-type-representations": {
      "abstract": [
        {
          "text": "Pasteboard-item representation types, as for a given object value.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/pasteboard-data-type-representations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Pasteboard Data Type Representations",
      "type": "topic",
      "url": "/documentation/uikit/pasteboard-data-type-representations"
    },
    "doc://com.apple.uikit/documentation/UIKit/pasteboard-names": {
      "abstract": [
        {
          "text": "Names identifying the system pasteboards.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/pasteboard-names",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Pasteboard Names",
      "type": "topic",
      "url": "/documentation/uikit/pasteboard-names"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/Name-swift.struct",
        "doc://com.apple.uikit/documentation/UIKit/pasteboard-names",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/OptionsKey",
        "doc://com.apple.uikit/documentation/UIKit/pasteboard-data-type-representations"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/changedTypesAddedUserInfoKey",
        "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/changedTypesRemovedUserInfoKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/changedTypesAddedUserInfoKey",
                "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/changedTypesRemovedUserInfoKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/Name-swift.struct",
                "doc://com.apple.uikit/documentation/UIKit/pasteboard-names",
                "doc://com.apple.uikit/documentation/UIKit/UIPasteboard/OptionsKey",
                "doc://com.apple.uikit/documentation/UIKit/pasteboard-data-type-representations"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard~1Name-swift.struct/title",
          "value": "UIPasteboardName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard~1Name-swift.struct/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteboardName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard~1Name-swift.struct/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteboardName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard~1changedTypesRemovedUserInfoKey/title",
          "value": "UIPasteboardChangedTypesRemovedKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard~1changedTypesRemovedUserInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteboardChangedTypesRemovedKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard~1changedNotification/title",
          "value": "UIPasteboardChangedNotification"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard~1changedNotification/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteboardChangedNotification"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard/title",
          "value": "UIPasteboard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard~1changedTypesAddedUserInfoKey/title",
          "value": "UIPasteboardChangedTypesAddedKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard~1changedTypesAddedUserInfoKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteboardChangedTypesAddedKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard~1OptionsKey/title",
          "value": "UIPasteboardOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard~1OptionsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteboardOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPasteboard~1OptionsKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPasteboardOption"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/userinfo-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/userinfo-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
