{
  "abstract": [
    {
      "text": "Create a search interface with a table view of suggested searches.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/view-controllers"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/using-suggested-searches-with-a-search-controller"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "introducedAt": "13.2",
        "name": "iOS"
      },
      {
        "beta": false,
        "introducedAt": "13.2",
        "name": "iPadOS"
      },
      {
        "beta": false,
        "introducedAt": "13.0",
        "name": "Xcode"
      }
    ],
    "role": "sampleCode",
    "roleHeading": "Sample Code",
    "title": "Using suggested searches with a search controller"
  },
  "primaryContentSections": [
    {
      "content": [
        {
          "anchor": "Overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This sample project demonstrates how to implement a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " in your application. ",
              "type": "text"
            },
            {
              "code": "UISearchController",
              "type": "codeVoice"
            },
            {
              "text": " is a view controller that manages the display of search results based on interactions with a search bar.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The sample lists flower products. Users can search for them by title, price, year, and color. As soon as the user taps the search bar, the search controller displays the list of suggested searches. A suggested search represents a particular color: red, blue, or green. The search controller filters the list of flower products by color when a suggested color is selected. This behavior matches that of the Mail app.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "This sample also demonstrates a scene-based architecture using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UISceneDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". It includes the recommended ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserActivityRestoring",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " protocol to save and restore the search results. Adopt this protocol to save the search bar’s active state, first responder status, search bar text and token, and restore them when the app is relaunched.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Create-a-search-controller",
          "level": 3,
          "text": "Create a search controller",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "MainTableViewController",
              "type": "codeVoice"
            },
            {
              "text": ", a subclass of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewController",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", creates the search controller. The search controller’s search bar helps filter a set of ",
              "type": "text"
            },
            {
              "code": "Product",
              "type": "codeVoice"
            },
            {
              "text": " objects and displays the results in the table view. The sample places the search controller in the ",
              "type": "text"
            },
            {
              "code": "MainTableViewController's",
              "type": "codeVoice"
            },
            {
              "text": " navigation bar:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "searchController = UISearchController(searchResultsController: resultsTableController)",
            "searchController.searchResultsUpdater = self",
            "searchController.searchBar.autocapitalizationType = .none",
            "searchController.searchBar.searchTextField.placeholder = NSLocalizedString(\"Enter a search term\", comment: \"\")",
            "searchController.searchBar.returnKeyType = .done",
            "",
            "// Place the search bar in the navigation bar.",
            "navigationItem.searchController = searchController",
            "    ",
            "// Make the search bar always visible.",
            "navigationItem.hidesSearchBarWhenScrolling = false",
            "",
            "// Monitor when the search controller is presented and dismissed.",
            "searchController.delegate = self",
            "",
            "// Monitor when the search button is tapped, and start/end editing.",
            "searchController.searchBar.delegate = self"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "ResultsTableController",
              "type": "codeVoice"
            },
            {
              "text": " displays both the list of filtered flower products and the list of suggested search colors. As the user types text in the search field, the list of flower products matches what is typed. If the user doesn’t enter any text, the search controller displays a list of suggested search colors. A suggested search represents a single query to search for a specific color of a product.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "anchor": "Create-suggested-searches",
          "level": 3,
          "text": "Create suggested searches",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The list of suggested searches is displayed by the results controller once the search bar is tapped:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "   func presentSearchController(_ searchController: UISearchController) {",
            "       searchController.showsSearchResultsController = true",
            "       setToSuggestedSearches()",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "When the user first taps the search bar, the search results controller displays the suggested searches. The user chooses a suggested search, and then types additional search criteria in the search bar. Each suggested search represents a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchToken",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", a visual representation of a search query. Tapping a suggested search creates a search token for a particular color and the search controller places it in the search bar’s text field. This text field is represented by ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchTextField",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " which supports cut, copy, paste, and drag and drop of search tokens. Tokens always precede the text and can be selected and deleted by the user.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The sample creates a ",
              "type": "text"
            },
            {
              "code": "UISearchToken",
              "type": "codeVoice"
            },
            {
              "text": " as follows:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "class func searchToken(tokenValue: Int) -> UISearchToken {",
            "    let tokenColor = ResultsTableController.suggestedColor(fromIndex: tokenValue)",
            "    let image =",
            "        UIImage(systemName: \"circle.fill\")?.withTintColor(tokenColor, renderingMode: .alwaysOriginal)",
            "    let searchToken = UISearchToken(icon: image, text: suggestedTitle(fromIndex: tokenValue))",
            "    ",
            "    // Set the color kind number as the token value.",
            "    let color = ResultsTableController.colorKind(fromIndex: tokenValue).rawValue",
            "    searchToken.representedObject = NSNumber(value: color)",
            "    ",
            "    return searchToken",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "This sample inserts the search token into the search bar’s search text field as follows:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "if let searchField = navigationItem.searchController?.searchBar.searchTextField {",
            "    searchField.insertToken(token, at: 0)",
            "    ",
            "    // Hide the suggested searches now that we have a token.",
            "    resultsTableController.showSuggestedSearches = false",
            "    ",
            "    // Update the search query with the newly inserted token.",
            "    updateSearchResults(for: searchController)",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISceneDelegate": {
      "abstract": [
        {
          "text": "The core methods you use to respond to life-cycle events occurring within a scene.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISceneDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISceneDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISceneDelegate"
        }
      ],
      "role": "symbol",
      "title": "UISceneDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uiscenedelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchBar": {
      "abstract": [
        {
          "text": "A specialized view for receiving search-related information from the user.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISearchBar"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchBar",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISearchBar"
        }
      ],
      "role": "symbol",
      "title": "UISearchBar",
      "type": "topic",
      "url": "/documentation/uikit/uisearchbar"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchContainerViewController": {
      "abstract": [
        {
          "text": "A view controller that manages the presentation of search results in your interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISearchContainerViewController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchContainerViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISearchContainerViewController"
        }
      ],
      "role": "symbol",
      "title": "UISearchContainerViewController",
      "type": "topic",
      "url": "/documentation/uikit/uisearchcontainerviewcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchController": {
      "abstract": [
        {
          "text": "A view controller that manages the display of search results based on interactions with a search bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISearchController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISearchController"
        }
      ],
      "role": "symbol",
      "title": "UISearchController",
      "type": "topic",
      "url": "/documentation/uikit/uisearchcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchResultsUpdating": {
      "abstract": [
        {
          "text": "A set of methods that let you update search results based on information the user enters into the search bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISearchResultsUpdating"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchResultsUpdating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISearchResultsUpdating"
        }
      ],
      "role": "symbol",
      "title": "UISearchResultsUpdating",
      "type": "topic",
      "url": "/documentation/uikit/uisearchresultsupdating"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchTextField": {
      "abstract": [
        {
          "text": "A view for displaying and editing text and search tokens.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISearchTextField"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchTextField",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISearchTextField"
        }
      ],
      "role": "symbol",
      "title": "UISearchTextField",
      "type": "topic",
      "url": "/documentation/uikit/uisearchtextfield"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISearchToken": {
      "abstract": [
        {
          "text": "Search criteria in a search text field, represented by text and an optional icon.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISearchToken"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISearchToken",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISearchToken"
        }
      ],
      "role": "symbol",
      "title": "UISearchToken",
      "type": "topic",
      "url": "/documentation/uikit/uisearchtoken"
    },
    "doc://com.apple.uikit/documentation/UIKit/UITableViewController": {
      "abstract": [
        {
          "text": "A view controller that specializes in managing a table view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITableViewController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UITableViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UITableViewController"
        }
      ],
      "role": "symbol",
      "title": "UITableViewController",
      "type": "topic",
      "url": "/documentation/uikit/uitableviewcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIUserActivityRestoring": {
      "abstract": [
        {
          "text": "The protocol you adopt to restore an object’s state from a user activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIUserActivityRestoring"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIUserActivityRestoring",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIUserActivityRestoring"
        }
      ],
      "role": "symbol",
      "title": "UIUserActivityRestoring",
      "type": "topic",
      "url": "/documentation/uikit/uiuseractivityrestoring"
    },
    "doc://com.apple.uikit/documentation/UIKit/displaying-searchable-content-by-using-a-search-controller": {
      "abstract": [
        {
          "text": "Create a user interface with searchable content in a table view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/displaying-searchable-content-by-using-a-search-controller",
      "kind": "article",
      "role": "sampleCode",
      "title": "Displaying searchable content by using a search controller",
      "type": "topic",
      "url": "/documentation/uikit/displaying-searchable-content-by-using-a-search-controller"
    },
    "doc://com.apple.uikit/documentation/UIKit/view-controllers": {
      "abstract": [
        {
          "text": "Manage your interface using view controllers and facilitate navigation around your app’s content.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/view-controllers",
      "kind": "article",
      "role": "collectionGroup",
      "title": "View controllers",
      "type": "topic",
      "url": "/documentation/uikit/view-controllers"
    },
    "eef0fcbecc3e/UsingSuggestedSearchesWithASearchController.zip": {
      "checksum": "eef0fcbecc3ec01b549fcf8fbbb4f262401764f37667b74503cd5abee0ae1ec623dbb8ac50f3a24abcad624ccdea0bba47420a5dc7e25f3785654679e51e91e4",
      "identifier": "eef0fcbecc3e/UsingSuggestedSearchesWithASearchController.zip",
      "type": "download",
      "url": "https://docs-assets.developer.apple.com/published/eef0fcbecc3e/UsingSuggestedSearchesWithASearchController.zip"
    }
  },
  "sampleCodeDownload": {
    "action": {
      "identifier": "eef0fcbecc3e/UsingSuggestedSearchesWithASearchController.zip",
      "isActive": true,
      "overridingTitle": "Download",
      "type": "reference"
    },
    "kind": "sampleDownload"
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Search-interface",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISearchContainerViewController",
        "doc://com.apple.uikit/documentation/UIKit/UISearchController",
        "doc://com.apple.uikit/documentation/UIKit/UISearchBar",
        "doc://com.apple.uikit/documentation/UIKit/UISearchResultsUpdating",
        "doc://com.apple.uikit/documentation/UIKit/displaying-searchable-content-by-using-a-search-controller"
      ],
      "title": "Search interface"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Search-interface",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UISearchContainerViewController",
                "doc://com.apple.uikit/documentation/UIKit/UISearchController",
                "doc://com.apple.uikit/documentation/UIKit/UISearchBar",
                "doc://com.apple.uikit/documentation/UIKit/UISearchResultsUpdating",
                "doc://com.apple.uikit/documentation/UIKit/displaying-searchable-content-by-using-a-search-controller"
              ],
              "title": "Search interface"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewController/title",
          "value": "UITableViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UITableViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UITableViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchTextField/title",
          "value": "UISearchTextField"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchTextField/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchTextField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchTextField/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchTextField"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController/title",
          "value": "UISearchController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserActivityRestoring/title",
          "value": "UIUserActivityRestoring"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserActivityRestoring/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserActivityRestoring"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserActivityRestoring/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIUserActivityRestoring"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneDelegate/title",
          "value": "UISceneDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISceneDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISceneDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISceneDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchContainerViewController/title",
          "value": "UISearchContainerViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchContainerViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchContainerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchContainerViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchContainerViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/title",
          "value": "UISearchBar"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchBar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchBar/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchBar"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchResultsUpdating/title",
          "value": "UISearchResultsUpdating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchResultsUpdating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchResultsUpdating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchResultsUpdating/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchResultsUpdating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchToken/title",
          "value": "UISearchToken"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchToken/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchToken"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISearchToken/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISearchToken"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/using-suggested-searches-with-a-search-controller"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/using-suggested-searches-with-a-search-controller"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
