{
  "abstract": [
    {
      "text": "Define custom transitions from one view controller to another.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/animation-and-haptics"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/view-controller-transitions"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "View controller transitions"
  },
  "references": {
    "Unifying-your-app-s-animations-PageImage-card.png": {
      "alt": null,
      "identifier": "Unifying-your-app-s-animations-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/3559438f813d2163ecacac3918dbff5f/Unifying-your-app-s-animations-PageImage-card~dark@2x.png"
        },
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/db26bd6bfe171a450c126a68c3bd92d4/Unifying-your-app-s-animations-PageImage-card@2x.png"
        }
      ]
    },
    "doc://com.apple.documentation/documentation/QuartzCore/optimizing-promotion-refresh-rates-for-iphone-13-pro-and-ipad-pro": {
      "abstract": [
        {
          "text": "Provide custom animated content for ProMotion displays.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/QuartzCore/optimizing-promotion-refresh-rates-for-iphone-13-pro-and-ipad-pro",
      "kind": "article",
      "role": "article",
      "title": "Optimizing ProMotion refresh rates for iPhone 13 Pro and iPad Pro",
      "type": "topic",
      "url": "/documentation/QuartzCore/optimizing-promotion-refresh-rates-for-iphone-13-pro-and-ipad-pro"
    },
    "doc://com.apple.documentation/documentation/SwiftUI/Unifying-your-app-s-animations": {
      "abstract": [
        {
          "text": "Create a consistent UI animation experience across SwiftUI, UIKit, and AppKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/SwiftUI/Unifying-your-app-s-animations",
      "images": [
        {
          "identifier": "Unifying-your-app-s-animations-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "article",
      "title": "Unifying your app’s animations",
      "type": "topic",
      "url": "/documentation/SwiftUI/Unifying-your-app-s-animations"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPercentDrivenInteractiveTransition": {
      "abstract": [
        {
          "text": "An object that drives an interactive animation between one view controller and another.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPercentDrivenInteractiveTransition"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPercentDrivenInteractiveTransition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPercentDrivenInteractiveTransition"
        }
      ],
      "role": "symbol",
      "title": "UIPercentDrivenInteractiveTransition",
      "type": "topic",
      "url": "/documentation/uikit/uipercentdriveninteractivetransition"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewControllerAnimatedTransitioning": {
      "abstract": [
        {
          "text": "A set of methods for implementing the animations for a custom view controller transition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewControllerAnimatedTransitioning"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerAnimatedTransitioning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewControllerAnimatedTransitioning"
        }
      ],
      "role": "symbol",
      "title": "UIViewControllerAnimatedTransitioning",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontrolleranimatedtransitioning"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning": {
      "abstract": [
        {
          "text": "A set of methods that provide contextual information for transition animations between view controllers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewControllerContextTransitioning"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewControllerContextTransitioning"
        }
      ],
      "role": "symbol",
      "title": "UIViewControllerContextTransitioning",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontrollercontexttransitioning"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewControllerInteractiveTransitioning": {
      "abstract": [
        {
          "text": "A set of methods that enable an object (such as a navigation controller) to drive a view controller transition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewControllerInteractiveTransitioning"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerInteractiveTransitioning",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewControllerInteractiveTransitioning"
        }
      ],
      "role": "symbol",
      "title": "UIViewControllerInteractiveTransitioning",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontrollerinteractivetransitioning"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator": {
      "abstract": [
        {
          "text": "A set of methods that provides support for animations associated with a view controller transition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewControllerTransitionCoordinator"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewControllerTransitionCoordinator"
        }
      ],
      "role": "symbol",
      "title": "UIViewControllerTransitionCoordinator",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontrollertransitioncoordinator"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext": {
      "abstract": [
        {
          "text": "A set of methods that provides information about an in-progress view controller transition.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewControllerTransitionCoordinatorContext"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewControllerTransitionCoordinatorContext"
        }
      ],
      "role": "symbol",
      "title": "UIViewControllerTransitionCoordinatorContext",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontrollertransitioncoordinatorcontext"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitioningDelegate": {
      "abstract": [
        {
          "text": "A set of methods that vend objects used to manage a fixed-length or interactive transition between view controllers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewControllerTransitioningDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitioningDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewControllerTransitioningDelegate"
        }
      ],
      "role": "symbol",
      "title": "UIViewControllerTransitioningDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontrollertransitioningdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewImplicitlyAnimating": {
      "abstract": [
        {
          "text": "An interface for modifying an animation while it’s running.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewImplicitlyAnimating"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewImplicitlyAnimating",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewImplicitlyAnimating"
        }
      ],
      "role": "symbol",
      "title": "UIViewImplicitlyAnimating",
      "type": "topic",
      "url": "/documentation/uikit/uiviewimplicitlyanimating"
    },
    "doc://com.apple.uikit/documentation/UIKit/animation-and-haptics": {
      "abstract": [
        {
          "text": "Provide feedback to users using view-based animations and haptics.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/animation-and-haptics",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Animation and haptics",
      "type": "topic",
      "url": "/documentation/uikit/animation-and-haptics"
    },
    "doc://com.apple.uikit/documentation/UIKit/enhancing-your-app-with-fluid-transitions": {
      "abstract": [
        {
          "text": "Use the fluid zoom transition to provide a continuously interactive and responsive experience in your app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/enhancing-your-app-with-fluid-transitions",
      "kind": "article",
      "role": "article",
      "title": "Enhancing your app with fluid transitions",
      "type": "topic",
      "url": "/documentation/uikit/enhancing-your-app-with-fluid-transitions"
    },
    "doc://com.apple.uikit/documentation/UIKit/property-based-animations": {
      "abstract": [
        {
          "text": "Create animations by changing the properties of a view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/property-based-animations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Property-based animations",
      "type": "topic",
      "url": "/documentation/uikit/property-based-animations"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Content-animations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/property-based-animations",
        "doc://com.apple.documentation/documentation/SwiftUI/Unifying-your-app-s-animations",
        "doc://com.apple.documentation/documentation/QuartzCore/optimizing-promotion-refresh-rates-for-iphone-13-pro-and-ipad-pro"
      ],
      "title": "Content animations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Essentials",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/enhancing-your-app-with-fluid-transitions"
      ],
      "title": "Essentials"
    },
    {
      "anchor": "Animation-delegate",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitioningDelegate"
      ],
      "title": "Animation delegate"
    },
    {
      "anchor": "Non-interactive-transitions",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIViewControllerAnimatedTransitioning",
        "doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning"
      ],
      "title": "Non-interactive transitions"
    },
    {
      "anchor": "Interactive-transitions",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIPercentDrivenInteractiveTransition",
        "doc://com.apple.uikit/documentation/UIKit/UIViewControllerInteractiveTransitioning",
        "doc://com.apple.uikit/documentation/UIKit/UIViewImplicitlyAnimating"
      ],
      "title": "Interactive transitions"
    },
    {
      "anchor": "Transition-coordinators",
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator",
        "doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext"
      ],
      "title": "Transition coordinators"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Essentials",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/enhancing-your-app-with-fluid-transitions"
              ],
              "title": "Essentials"
            },
            {
              "anchor": "Animation-delegate",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitioningDelegate"
              ],
              "title": "Animation delegate"
            },
            {
              "anchor": "Non-interactive-transitions",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIViewControllerAnimatedTransitioning",
                "doc://com.apple.uikit/documentation/UIKit/UIViewControllerContextTransitioning"
              ],
              "title": "Non-interactive transitions"
            },
            {
              "anchor": "Interactive-transitions",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIPercentDrivenInteractiveTransition",
                "doc://com.apple.uikit/documentation/UIKit/UIViewControllerInteractiveTransitioning",
                "doc://com.apple.uikit/documentation/UIKit/UIViewImplicitlyAnimating"
              ],
              "title": "Interactive transitions"
            },
            {
              "anchor": "Transition-coordinators",
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinator",
                "doc://com.apple.uikit/documentation/UIKit/UIViewControllerTransitionCoordinatorContext"
              ],
              "title": "Transition coordinators"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Content-animations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/property-based-animations",
                "doc://com.apple.documentation/documentation/QuartzCore/optimizing-promotion-refresh-rates-for-iphone-13-pro-and-ipad-pro"
              ],
              "title": "Content animations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewImplicitlyAnimating/title",
          "value": "UIViewImplicitlyAnimating"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewImplicitlyAnimating/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewImplicitlyAnimating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewImplicitlyAnimating/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewImplicitlyAnimating"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPercentDrivenInteractiveTransition/title",
          "value": "UIPercentDrivenInteractiveTransition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPercentDrivenInteractiveTransition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPercentDrivenInteractiveTransition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPercentDrivenInteractiveTransition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPercentDrivenInteractiveTransition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinatorContext/title",
          "value": "UIViewControllerTransitionCoordinatorContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinatorContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerTransitionCoordinatorContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinatorContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerTransitionCoordinatorContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitioningDelegate/title",
          "value": "UIViewControllerTransitioningDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitioningDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerTransitioningDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitioningDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerTransitioningDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinator/title",
          "value": "UIViewControllerTransitionCoordinator"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinator/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerTransitionCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerTransitionCoordinator/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerTransitionCoordinator"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerContextTransitioning/title",
          "value": "UIViewControllerContextTransitioning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerContextTransitioning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerContextTransitioning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerContextTransitioning/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerContextTransitioning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerAnimatedTransitioning/title",
          "value": "UIViewControllerAnimatedTransitioning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerAnimatedTransitioning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerAnimatedTransitioning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerAnimatedTransitioning/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerAnimatedTransitioning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerInteractiveTransitioning/title",
          "value": "UIViewControllerInteractiveTransitioning"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerInteractiveTransitioning/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerInteractiveTransitioning"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewControllerInteractiveTransitioning/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewControllerInteractiveTransitioning"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/view-controller-transitions"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/view-controller-transitions"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
