{
  "abstract": [
    {
      "text": "The media item kind is unknown.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindUnknown"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@ITLibMediaItemMediaKind@ITLibMediaItemMediaKindUnknown",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kindUnknown"
      }
    ],
    "modules": [
      {
        "name": "iTunes Library"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ITLibMediaItemMediaKindUnknown"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "ITLibMediaItemMediaKind.kindUnknown"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kindUnknown"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary": {
      "abstract": [
        {
          "text": "Retrieve the properties of the media in the user’s iTunes library.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary",
      "kind": "symbol",
      "role": "collection",
      "title": "iTunes Library",
      "type": "topic",
      "url": "/documentation/ituneslibrary"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind": {
      "abstract": [
        {
          "text": "These constants specify the possible media kinds of a media item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ITLibMediaItemMediaKind"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemMediaKind"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemMediaKind",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemmediakind"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindAudiobook": {
      "abstract": [
        {
          "text": "The media item is an audiobook.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindAudiobook"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindAudiobook",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemMediaKindAudiobook"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemMediaKind.kindAudiobook",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemmediakind/kindaudiobook"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindBook": {
      "abstract": [
        {
          "text": "The media item is an EPUB file or an iBooks Author book.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindBook"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindBook",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemMediaKindBook"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemMediaKind.kindBook",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemmediakind/kindbook"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindDigitalBooklet": {
      "abstract": [
        {
          "text": "The media item is an iTunes Extra or an iTunes LP item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindDigitalBooklet"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindDigitalBooklet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemMediaKindDigitalBooklet"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemMediaKind.kindDigitalBooklet",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemmediakind/kinddigitalbooklet"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindHomeVideo": {
      "abstract": [
        {
          "text": "The media item is a non-iTunes Store movie.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindHomeVideo"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindHomeVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemMediaKindHomeVideo"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemMediaKind.kindHomeVideo",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemmediakind/kindhomevideo"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindIOSApplication": {
      "abstract": [
        {
          "text": "The media item is an iOS app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindIOSApplication"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindIOSApplication",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemMediaKindIOSApplication"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemMediaKind.kindIOSApplication",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemmediakind/kindiosapplication"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindInteractiveBooklet": {
      "abstract": [
        {
          "text": "The media item is a QuickTime movie with embedded Flash.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindInteractiveBooklet"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindInteractiveBooklet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemMediaKindInteractiveBooklet"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemMediaKind.kindInteractiveBooklet",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemmediakind/kindinteractivebooklet"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindMovie": {
      "abstract": [
        {
          "text": "The media item is a movie.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindMovie"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindMovie",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemMediaKindMovie"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemMediaKind.kindMovie",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemmediakind/kindmovie"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindMusicVideo": {
      "abstract": [
        {
          "text": "The media item is a music video.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindMusicVideo"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindMusicVideo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemMediaKindMusicVideo"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemMediaKind.kindMusicVideo",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemmediakind/kindmusicvideo"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindPDFBooklet": {
      "abstract": [
        {
          "text": "The media item is an unwrapped PDF file that’s part of a music album.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindPDFBooklet"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindPDFBooklet",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemMediaKindPDFBooklet"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemMediaKind.kindPDFBooklet",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemmediakind/kindpdfbooklet"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindPodcast": {
      "abstract": [
        {
          "text": "The media item is an audio or a video podcast.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindPodcast"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindPodcast",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemMediaKindPodcast"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemMediaKind.kindPodcast",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemmediakind/kindpodcast"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindRingtone": {
      "abstract": [
        {
          "text": "The media item is an iOS ringtone.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindRingtone"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindRingtone",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemMediaKindRingtone"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemMediaKind.kindRingtone",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemmediakind/kindringtone"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindSong": {
      "abstract": [
        {
          "text": "The media item is a song.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindSong"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindSong",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemMediaKindSong"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemMediaKind.kindSong",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemmediakind/kindsong"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindTVShow": {
      "abstract": [
        {
          "text": "The media item is a TV show.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindTVShow"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindTVShow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemMediaKindTVShow"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemMediaKind.kindTVShow",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemmediakind/kindtvshow"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindUnknown": {
      "abstract": [
        {
          "text": "The media item kind is unknown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindUnknown"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindUnknown",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemMediaKindUnknown"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemMediaKind.kindUnknown",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemmediakind/kindunknown"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindVoiceMemo": {
      "abstract": [
        {
          "text": "The media item is a recorded voice memo.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindVoiceMemo"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindVoiceMemo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemMediaKindVoiceMemo"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemMediaKind.kindVoiceMemo",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemmediakind/kindvoicememo"
    },
    "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindiTunesU": {
      "abstract": [
        {
          "text": "The media item is an iTunes U audio or video file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kindiTunesU"
        }
      ],
      "identifier": "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindiTunesU",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ITLibMediaItemMediaKindiTunesU"
        }
      ],
      "role": "symbol",
      "title": "ITLibMediaItemMediaKind.kindiTunesU",
      "type": "topic",
      "url": "/documentation/ituneslibrary/itlibmediaitemmediakind/kinditunesu"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Media-Kinds",
      "generated": true,
      "identifiers": [
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindSong",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindMovie",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindPodcast",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindAudiobook",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindPDFBooklet",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindMusicVideo",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindTVShow",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindInteractiveBooklet",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindHomeVideo",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindRingtone",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindDigitalBooklet",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindIOSApplication",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindVoiceMemo",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindiTunesU",
        "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindBook"
      ],
      "title": "Media Kinds"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "ITLibMediaItemMediaKindUnknown"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKindUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Media-Kinds",
              "generated": true,
              "identifiers": [
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindSong",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindMovie",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindPodcast",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindAudiobook",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindPDFBooklet",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindMusicVideo",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindTVShow",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindInteractiveBooklet",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindHomeVideo",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindRingtone",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindDigitalBooklet",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindIOSApplication",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindVoiceMemo",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindiTunesU",
                "doc://com.apple.ituneslibrary/documentation/iTunesLibrary/ITLibMediaItemMediaKind/kindBook"
              ],
              "title": "Media Kinds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "ITLibMediaItemMediaKindUnknown"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindiTunesU/title",
          "value": "ITLibMediaItemMediaKindiTunesU"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindiTunesU/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKindiTunesU"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindPDFBooklet/title",
          "value": "ITLibMediaItemMediaKindPDFBooklet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindPDFBooklet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKindPDFBooklet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindAudiobook/title",
          "value": "ITLibMediaItemMediaKindAudiobook"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindAudiobook/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKindAudiobook"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindHomeVideo/title",
          "value": "ITLibMediaItemMediaKindHomeVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindHomeVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKindHomeVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind/title",
          "value": "ITLibMediaItemMediaKind"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKind"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindBook/title",
          "value": "ITLibMediaItemMediaKindBook"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindBook/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKindBook"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindSong/title",
          "value": "ITLibMediaItemMediaKindSong"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindSong/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKindSong"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindTVShow/title",
          "value": "ITLibMediaItemMediaKindTVShow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindTVShow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKindTVShow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindVoiceMemo/title",
          "value": "ITLibMediaItemMediaKindVoiceMemo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindVoiceMemo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKindVoiceMemo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindPodcast/title",
          "value": "ITLibMediaItemMediaKindPodcast"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindPodcast/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKindPodcast"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindRingtone/title",
          "value": "ITLibMediaItemMediaKindRingtone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindRingtone/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKindRingtone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindMusicVideo/title",
          "value": "ITLibMediaItemMediaKindMusicVideo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindMusicVideo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKindMusicVideo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindInteractiveBooklet/title",
          "value": "ITLibMediaItemMediaKindInteractiveBooklet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindInteractiveBooklet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKindInteractiveBooklet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindUnknown/title",
          "value": "ITLibMediaItemMediaKindUnknown"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindUnknown/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKindUnknown"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindDigitalBooklet/title",
          "value": "ITLibMediaItemMediaKindDigitalBooklet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindDigitalBooklet/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKindDigitalBooklet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindMovie/title",
          "value": "ITLibMediaItemMediaKindMovie"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindMovie/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKindMovie"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindIOSApplication/title",
          "value": "ITLibMediaItemMediaKindIOSApplication"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.ituneslibrary~1documentation~1iTunesLibrary~1ITLibMediaItemMediaKind~1kindIOSApplication/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ITLibMediaItemMediaKindIOSApplication"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/ituneslibrary/itlibmediaitemmediakind/kindunknown"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/ituneslibrary/itlibmediaitemmediakind/kindunknown"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
