{
  "abstract": [
    {
      "text": "A property that defines the content in a text input area as a date of birth.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSTextContentType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/birthdate"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@NSTextContentTypeBirthdate",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "birthdate"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSTextContentType",
        "text": "NSTextContentType"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTextContentTypeBirthdate"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "birthdate"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "birthdate"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSTextContentType",
              "text": "NSTextContentType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContentType": {
      "abstract": [
        {
          "text": "Constants that identify the semantic meaning for a text-entry area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextContentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentType"
        }
      ],
      "role": "symbol",
      "title": "NSTextContentType",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontenttype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/birthdate": {
      "abstract": [
        {
          "text": "A property that defines the content in a text input area as a date of birth.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "birthdate"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextContentType",
          "text": "NSTextContentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/birthdate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentTypeBirthdate"
        }
      ],
      "role": "symbol",
      "title": "birthdate",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontenttype/birthdate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/birthdateDay": {
      "abstract": [
        {
          "text": "A property that defines the content in a text input area as the day component of a birthdate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "birthdateDay"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextContentType",
          "text": "NSTextContentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/birthdateDay",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentTypeBirthdateDay"
        }
      ],
      "role": "symbol",
      "title": "birthdateDay",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontenttype/birthdateday"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/birthdateMonth": {
      "abstract": [
        {
          "text": "A property that defines the content in a text input area as the month component of a birthdate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "birthdateMonth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextContentType",
          "text": "NSTextContentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/birthdateMonth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentTypeBirthdateMonth"
        }
      ],
      "role": "symbol",
      "title": "birthdateMonth",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontenttype/birthdatemonth"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/birthdateYear": {
      "abstract": [
        {
          "text": "A property that defines the content in a text input area as the year component of a birthdate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "birthdateYear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextContentType",
          "text": "NSTextContentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/birthdateYear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentTypeBirthdateYear"
        }
      ],
      "role": "symbol",
      "title": "birthdateYear",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontenttype/birthdateyear"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-birthday-information",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/birthdateDay",
        "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/birthdateMonth",
        "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/birthdateYear"
      ],
      "title": "Getting birthday information"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTextContentTypeBirthdate"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentTypeBirthdate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-birthday-information",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/birthdateDay",
                "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/birthdateMonth",
                "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/birthdateYear"
              ],
              "title": "Getting birthday information"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSTextContentType",
                    "text": "NSTextContentType"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSTextContentTypeBirthdate"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType/title",
          "value": "NSTextContentType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1birthdateDay/title",
          "value": "NSTextContentTypeBirthdateDay"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1birthdateDay/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentTypeBirthdateDay"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1birthdateMonth/title",
          "value": "NSTextContentTypeBirthdateMonth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1birthdateMonth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentTypeBirthdateMonth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1birthdate/title",
          "value": "NSTextContentTypeBirthdate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1birthdate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentTypeBirthdate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1birthdateYear/title",
          "value": "NSTextContentTypeBirthdateYear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1birthdateYear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentTypeBirthdateYear"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstextcontenttype/birthdate"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstextcontenttype/birthdate"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
