{
  "abstract": [
    {
      "text": "A property that defines the content in a text input area as a first name on a credit card.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSTextContentType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/creditCardGivenName"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@NSTextContentTypeCreditCardGivenName",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "creditCardGivenName"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSTextContentType",
        "text": "NSTextContentType"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTextContentTypeCreditCardGivenName"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "creditCardGivenName"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "creditCardGivenName"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSTextContentType",
              "text": "NSTextContentType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContentType": {
      "abstract": [
        {
          "text": "Constants that identify the semantic meaning for a text-entry area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextContentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentType"
        }
      ],
      "role": "symbol",
      "title": "NSTextContentType",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontenttype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/creditCardExpiration": {
      "abstract": [
        {
          "text": "A property that defines the content in a text input area as an expiration date on a credit card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "creditCardExpiration"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextContentType",
          "text": "NSTextContentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/creditCardExpiration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentTypeCreditCardExpiration"
        }
      ],
      "role": "symbol",
      "title": "creditCardExpiration",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontenttype/creditcardexpiration"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/creditCardExpirationMonth": {
      "abstract": [
        {
          "text": "A property that defines the content in a text input area as the month component of an expiration date on a credit card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "creditCardExpirationMonth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextContentType",
          "text": "NSTextContentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/creditCardExpirationMonth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentTypeCreditCardExpirationMonth"
        }
      ],
      "role": "symbol",
      "title": "creditCardExpirationMonth",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontenttype/creditcardexpirationmonth"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/creditCardExpirationYear": {
      "abstract": [
        {
          "text": "A property that defines the content in a text input area as the year component of an expiration date on a credit card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "creditCardExpirationYear"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextContentType",
          "text": "NSTextContentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/creditCardExpirationYear",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentTypeCreditCardExpirationYear"
        }
      ],
      "role": "symbol",
      "title": "creditCardExpirationYear",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontenttype/creditcardexpirationyear"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/creditCardFamilyName": {
      "abstract": [
        {
          "text": "A property that defines the content in a text input area as a family name, or last name, on a credit card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "creditCardFamilyName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextContentType",
          "text": "NSTextContentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/creditCardFamilyName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentTypeCreditCardFamilyName"
        }
      ],
      "role": "symbol",
      "title": "creditCardFamilyName",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontenttype/creditcardfamilyname"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/creditCardGivenName": {
      "abstract": [
        {
          "text": "A property that defines the content in a text input area as a first name on a credit card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "creditCardGivenName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextContentType",
          "text": "NSTextContentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/creditCardGivenName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentTypeCreditCardGivenName"
        }
      ],
      "role": "symbol",
      "title": "creditCardGivenName",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontenttype/creditcardgivenname"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/creditCardMiddleName": {
      "abstract": [
        {
          "text": "A property that defines the content in a text input area as a middle name on a credit card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "creditCardMiddleName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextContentType",
          "text": "NSTextContentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/creditCardMiddleName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentTypeCreditCardMiddleName"
        }
      ],
      "role": "symbol",
      "title": "creditCardMiddleName",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontenttype/creditcardmiddlename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/creditCardName": {
      "abstract": [
        {
          "text": "A property that defines the content in a text input area as a name on a credit card.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "creditCardName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextContentType",
          "text": "NSTextContentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/creditCardName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentTypeCreditCardName"
        }
      ],
      "role": "symbol",
      "title": "creditCardName",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontenttype/creditcardname"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/creditCardNumber": {
      "abstract": [
        {
          "text": "A property that defines the content in a text input area as a credit card number.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "creditCardNumber"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextContentType",
          "text": "NSTextContentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/creditCardNumber",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentTypeCreditCardNumber"
        }
      ],
      "role": "symbol",
      "title": "creditCardNumber",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontenttype/creditcardnumber"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/creditCardSecurityCode": {
      "abstract": [
        {
          "text": "A property that defines the content in a text input area as a credit card security code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "creditCardSecurityCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextContentType",
          "text": "NSTextContentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/creditCardSecurityCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentTypeCreditCardSecurityCode"
        }
      ],
      "role": "symbol",
      "title": "creditCardSecurityCode",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontenttype/creditcardsecuritycode"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/creditCardType": {
      "abstract": [
        {
          "text": "A property that defines the content in a text input area as a credit card type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "creditCardType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextContentType",
          "text": "NSTextContentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/creditCardType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentTypeCreditCardType"
        }
      ],
      "role": "symbol",
      "title": "creditCardType",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontenttype/creditcardtype"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accepting-payment",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/creditCardNumber",
        "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/creditCardExpiration",
        "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/creditCardExpirationMonth",
        "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/creditCardExpirationYear",
        "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/creditCardSecurityCode",
        "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/creditCardType",
        "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/creditCardName",
        "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/creditCardMiddleName",
        "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/creditCardFamilyName"
      ],
      "title": "Accepting payment"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTextContentTypeCreditCardGivenName"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentTypeCreditCardGivenName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accepting-payment",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/creditCardNumber",
                "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/creditCardExpiration",
                "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/creditCardExpirationMonth",
                "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/creditCardExpirationYear",
                "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/creditCardSecurityCode",
                "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/creditCardType",
                "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/creditCardName",
                "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/creditCardMiddleName",
                "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/creditCardFamilyName"
              ],
              "title": "Accepting payment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSTextContentType",
                    "text": "NSTextContentType"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSTextContentTypeCreditCardGivenName"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1creditCardSecurityCode/title",
          "value": "NSTextContentTypeCreditCardSecurityCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1creditCardSecurityCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentTypeCreditCardSecurityCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1creditCardNumber/title",
          "value": "NSTextContentTypeCreditCardNumber"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1creditCardNumber/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentTypeCreditCardNumber"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1creditCardFamilyName/title",
          "value": "NSTextContentTypeCreditCardFamilyName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1creditCardFamilyName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentTypeCreditCardFamilyName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1creditCardExpirationMonth/title",
          "value": "NSTextContentTypeCreditCardExpirationMonth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1creditCardExpirationMonth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentTypeCreditCardExpirationMonth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1creditCardType/title",
          "value": "NSTextContentTypeCreditCardType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1creditCardType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentTypeCreditCardType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1creditCardGivenName/title",
          "value": "NSTextContentTypeCreditCardGivenName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1creditCardGivenName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentTypeCreditCardGivenName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1creditCardName/title",
          "value": "NSTextContentTypeCreditCardName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1creditCardName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentTypeCreditCardName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1creditCardMiddleName/title",
          "value": "NSTextContentTypeCreditCardMiddleName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1creditCardMiddleName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentTypeCreditCardMiddleName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1creditCardExpiration/title",
          "value": "NSTextContentTypeCreditCardExpiration"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1creditCardExpiration/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentTypeCreditCardExpiration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType/title",
          "value": "NSTextContentType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1creditCardExpirationYear/title",
          "value": "NSTextContentTypeCreditCardExpirationYear"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1creditCardExpirationYear/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentTypeCreditCardExpirationYear"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstextcontenttype/creditcardgivenname"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstextcontenttype/creditcardgivenname"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
