{
  "abstract": [
    {
      "text": "A property that defines the content in a text input area as a family name, or last name.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSTextContentType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/familyName"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@NSTextContentTypeFamilyName",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "familyName"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSTextContentType",
        "text": "NSTextContentType"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTextContentTypeFamilyName"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "familyName"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "familyName"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSTextContentType",
              "text": "NSTextContentType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContentType": {
      "abstract": [
        {
          "text": "Constants that identify the semantic meaning for a text-entry area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextContentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentType"
        }
      ],
      "role": "symbol",
      "title": "NSTextContentType",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontenttype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/familyName": {
      "abstract": [
        {
          "text": "A property that defines the content in a text input area as a family name, or last name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "familyName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextContentType",
          "text": "NSTextContentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/familyName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentTypeFamilyName"
        }
      ],
      "role": "symbol",
      "title": "familyName",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontenttype/familyname"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/givenName": {
      "abstract": [
        {
          "text": "A property that defines the content in a text input area as a first name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "givenName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextContentType",
          "text": "NSTextContentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/givenName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentTypeGivenName"
        }
      ],
      "role": "symbol",
      "title": "givenName",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontenttype/givenname"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/jobTitle": {
      "abstract": [
        {
          "text": "A property that defines the content in a text input area as a job title.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "jobTitle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextContentType",
          "text": "NSTextContentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/jobTitle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentTypeJobTitle"
        }
      ],
      "role": "symbol",
      "title": "jobTitle",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontenttype/jobtitle"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/middleName": {
      "abstract": [
        {
          "text": "A property that defines the content in a text input area as a middle name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "middleName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextContentType",
          "text": "NSTextContentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/middleName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentTypeMiddleName"
        }
      ],
      "role": "symbol",
      "title": "middleName",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontenttype/middlename"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/name": {
      "abstract": [
        {
          "text": "A property that defines the content in a text input area as a name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "name"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextContentType",
          "text": "NSTextContentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/name",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentTypeName"
        }
      ],
      "role": "symbol",
      "title": "name",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontenttype/name"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/namePrefix": {
      "abstract": [
        {
          "text": "A property that defines the content in a text input area as a prefix or title, such as ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Dr",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "namePrefix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextContentType",
          "text": "NSTextContentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/namePrefix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentTypeNamePrefix"
        }
      ],
      "role": "symbol",
      "title": "namePrefix",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontenttype/nameprefix"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/nameSuffix": {
      "abstract": [
        {
          "text": "A property that defines the content in a text input area as a suffix, such as ",
          "type": "text"
        },
        {
          "inlineContent": [
            {
              "text": "Jr",
              "type": "text"
            }
          ],
          "type": "emphasis"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nameSuffix"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextContentType",
          "text": "NSTextContentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/nameSuffix",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentTypeNameSuffix"
        }
      ],
      "role": "symbol",
      "title": "nameSuffix",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontenttype/namesuffix"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/nickname": {
      "abstract": [
        {
          "text": "A property that defines the content in a text input area as a nickname.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nickname"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextContentType",
          "text": "NSTextContentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/nickname",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentTypeNickname"
        }
      ],
      "role": "symbol",
      "title": "nickname",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontenttype/nickname"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/organizationName": {
      "abstract": [
        {
          "text": "A property that defines the content in a text input area as an organization name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "organizationName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextContentType",
          "text": "NSTextContentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/organizationName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentTypeOrganizationName"
        }
      ],
      "role": "symbol",
      "title": "organizationName",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontenttype/organizationname"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Identifying-contacts",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/namePrefix",
        "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/name",
        "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/nameSuffix",
        "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/givenName",
        "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/middleName",
        "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/nickname",
        "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/organizationName",
        "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/jobTitle"
      ],
      "title": "Identifying contacts"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTextContentTypeFamilyName"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentTypeFamilyName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Identifying-contacts",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/namePrefix",
                "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/name",
                "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/nameSuffix",
                "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/givenName",
                "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/middleName",
                "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/nickname",
                "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/organizationName",
                "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/jobTitle"
              ],
              "title": "Identifying contacts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSTextContentType",
                    "text": "NSTextContentType"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSTextContentTypeFamilyName"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1jobTitle/title",
          "value": "NSTextContentTypeJobTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1jobTitle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentTypeJobTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1name/title",
          "value": "NSTextContentTypeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1name/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentTypeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1namePrefix/title",
          "value": "NSTextContentTypeNamePrefix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1namePrefix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentTypeNamePrefix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1givenName/title",
          "value": "NSTextContentTypeGivenName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1givenName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentTypeGivenName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1familyName/title",
          "value": "NSTextContentTypeFamilyName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1familyName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentTypeFamilyName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1nameSuffix/title",
          "value": "NSTextContentTypeNameSuffix"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1nameSuffix/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentTypeNameSuffix"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1organizationName/title",
          "value": "NSTextContentTypeOrganizationName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1organizationName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentTypeOrganizationName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType/title",
          "value": "NSTextContentType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1nickname/title",
          "value": "NSTextContentTypeNickname"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1nickname/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentTypeNickname"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1middleName/title",
          "value": "NSTextContentTypeMiddleName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1middleName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentTypeMiddleName"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstextcontenttype/familyname"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstextcontenttype/familyname"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
