{
  "abstract": [
    {
      "text": "A property that defines the content in a text input area as the second line of a street address.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSTextContentType"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/streetAddressLine2"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@NSTextContentTypeStreetAddressLine2",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "streetAddressLine2"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@NSTextContentType",
        "text": "NSTextContentType"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSTextContentTypeStreetAddressLine2"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Type Property",
    "symbolKind": "property",
    "title": "streetAddressLine2"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "streetAddressLine2"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSTextContentType",
              "text": "NSTextContentType"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContentType": {
      "abstract": [
        {
          "text": "Constants that identify the semantic meaning for a text-entry area.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextContentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentType"
        }
      ],
      "role": "symbol",
      "title": "NSTextContentType",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontenttype"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/addressCity": {
      "abstract": [
        {
          "text": "A property that defines the content in a text input area as a city name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addressCity"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextContentType",
          "text": "NSTextContentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/addressCity",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentTypeAddressCity"
        }
      ],
      "role": "symbol",
      "title": "addressCity",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontenttype/addresscity"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/addressCityAndState": {
      "abstract": [
        {
          "text": "A property that defines the content in a text input area as a city name with a state name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addressCityAndState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextContentType",
          "text": "NSTextContentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/addressCityAndState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentTypeAddressCityAndState"
        }
      ],
      "role": "symbol",
      "title": "addressCityAndState",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontenttype/addresscityandstate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/addressState": {
      "abstract": [
        {
          "text": "A property that defines the content in a text input area as a state name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addressState"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextContentType",
          "text": "NSTextContentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/addressState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentTypeAddressState"
        }
      ],
      "role": "symbol",
      "title": "addressState",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontenttype/addressstate"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/countryName": {
      "abstract": [
        {
          "text": "A property that defines the content in a text input area as a country or region name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "countryName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextContentType",
          "text": "NSTextContentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/countryName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentTypeCountryName"
        }
      ],
      "role": "symbol",
      "title": "countryName",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontenttype/countryname"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/fullStreetAddress": {
      "abstract": [
        {
          "text": "A property that defines the content in a text input area as a street address that fully identifies a location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fullStreetAddress"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextContentType",
          "text": "NSTextContentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/fullStreetAddress",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentTypeFullStreetAddress"
        }
      ],
      "role": "symbol",
      "title": "fullStreetAddress",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontenttype/fullstreetaddress"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/location": {
      "abstract": [
        {
          "text": "A property that defines the content in a text input area as a location, such as a point of interest, an address, or another identifier for a location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "location"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextContentType",
          "text": "NSTextContentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/location",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentTypeLocation"
        }
      ],
      "role": "symbol",
      "title": "location",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontenttype/location"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/postalCode": {
      "abstract": [
        {
          "text": "A property that defines the content in a text input area as a postal code.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postalCode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextContentType",
          "text": "NSTextContentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/postalCode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentTypePostalCode"
        }
      ],
      "role": "symbol",
      "title": "postalCode",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontenttype/postalcode"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/streetAddressLine1": {
      "abstract": [
        {
          "text": "A property that defines the content in a text input area as the first line of a street address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "streetAddressLine1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextContentType",
          "text": "NSTextContentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/streetAddressLine1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentTypeStreetAddressLine1"
        }
      ],
      "role": "symbol",
      "title": "streetAddressLine1",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontenttype/streetaddressline1"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/streetAddressLine2": {
      "abstract": [
        {
          "text": "A property that defines the content in a text input area as the second line of a street address.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "streetAddressLine2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextContentType",
          "text": "NSTextContentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/streetAddressLine2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentTypeStreetAddressLine2"
        }
      ],
      "role": "symbol",
      "title": "streetAddressLine2",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontenttype/streetaddressline2"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/sublocality": {
      "abstract": [
        {
          "text": "A property that defines the content in a text input area as a sublocality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sublocality"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSTextContentType",
          "text": "NSTextContentType"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/sublocality",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextContentTypeSublocality"
        }
      ],
      "role": "symbol",
      "title": "sublocality",
      "type": "topic",
      "url": "/documentation/appkit/nstextcontenttype/sublocality"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Setting-location-data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/location",
        "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/fullStreetAddress",
        "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/streetAddressLine1",
        "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/addressCity",
        "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/addressCityAndState",
        "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/addressState",
        "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/postalCode",
        "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/sublocality",
        "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/countryName"
      ],
      "title": "Setting location data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSTextContentTypeStreetAddressLine2"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentTypeStreetAddressLine2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Setting-location-data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/location",
                "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/fullStreetAddress",
                "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/streetAddressLine1",
                "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/addressCity",
                "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/addressCityAndState",
                "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/addressState",
                "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/postalCode",
                "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/sublocality",
                "doc://com.apple.appkit/documentation/AppKit/NSTextContentType/countryName"
              ],
              "title": "Setting location data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextContentType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSTextContentType",
                    "text": "NSTextContentType"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSTextContentTypeStreetAddressLine2"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1fullStreetAddress/title",
          "value": "NSTextContentTypeFullStreetAddress"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1fullStreetAddress/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentTypeFullStreetAddress"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1addressState/title",
          "value": "NSTextContentTypeAddressState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1addressState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentTypeAddressState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1location/title",
          "value": "NSTextContentTypeLocation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1location/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentTypeLocation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1countryName/title",
          "value": "NSTextContentTypeCountryName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1countryName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentTypeCountryName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1postalCode/title",
          "value": "NSTextContentTypePostalCode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1postalCode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentTypePostalCode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1streetAddressLine2/title",
          "value": "NSTextContentTypeStreetAddressLine2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1streetAddressLine2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentTypeStreetAddressLine2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1streetAddressLine1/title",
          "value": "NSTextContentTypeStreetAddressLine1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1streetAddressLine1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentTypeStreetAddressLine1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1addressCity/title",
          "value": "NSTextContentTypeAddressCity"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1addressCity/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentTypeAddressCity"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType/title",
          "value": "NSTextContentType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1sublocality/title",
          "value": "NSTextContentTypeSublocality"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1sublocality/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentTypeSublocality"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1addressCityAndState/title",
          "value": "NSTextContentTypeAddressCityAndState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextContentType~1addressCityAndState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextContentTypeAddressCityAndState"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nstextcontenttype/streetaddressline2"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nstextcontenttype/streetaddressline2"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
