{
  "abstract": [
    {
      "text": "An object that contains common types of data that the data detection system matches for a pasteboard.",
      "type": "text"
    }
  ],
  "diffAvailability": {
    "minor": {
      "change": "added",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/DetectedValues"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "s:So12NSPasteboardC6AppKitE14DetectedValuesV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "DetectedValues"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "DetectedValues"
      }
    ],
    "platforms": [
      {
        "beta": true,
        "deprecated": false,
        "introducedAt": "15.4",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "NSPasteboard.DetectedValues"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "DetectedValues"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard": {
      "abstract": [
        {
          "text": "An object that transfers data to and from the pasteboard server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPasteboard"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPasteboard"
        }
      ],
      "role": "symbol",
      "title": "NSPasteboard",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/DetectedValues": {
      "abstract": [
        {
          "text": "An object that contains common types of data that the data detection system matches for a pasteboard.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DetectedValues"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/DetectedValues",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DetectedValues"
        }
      ],
      "role": "symbol",
      "title": "NSPasteboard.DetectedValues",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/detectedvalues"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/DetectedValues/calendarEvents": {
      "abstract": [
        {
          "text": "An array of calendar events that the data detection system identifies.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "calendarEvents"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)DDMatchCalendarEvent",
          "text": "DDMatchCalendarEvent"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/DetectedValues/calendarEvents",
      "kind": "symbol",
      "role": "symbol",
      "title": "calendarEvents",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/detectedvalues/calendarevents"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/DetectedValues/emailAddresses": {
      "abstract": [
        {
          "text": "An array of email addresses that the data detection system identifies.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "emailAddresses"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)DDMatchEmailAddress",
          "text": "DDMatchEmailAddress"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/DetectedValues/emailAddresses",
      "kind": "symbol",
      "role": "symbol",
      "title": "emailAddresses",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/detectedvalues/emailaddresses"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/DetectedValues/flightNumbers": {
      "abstract": [
        {
          "text": "An array of flight numbers that the data detection system identifies.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flightNumbers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)DDMatchFlightNumber",
          "text": "DDMatchFlightNumber"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/DetectedValues/flightNumbers",
      "kind": "symbol",
      "role": "symbol",
      "title": "flightNumbers",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/detectedvalues/flightnumbers"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/DetectedValues/links": {
      "abstract": [
        {
          "text": "An array of web links that the data detection system identifies.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "links"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)DDMatchLink",
          "text": "DDMatchLink"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/DetectedValues/links",
      "kind": "symbol",
      "role": "symbol",
      "title": "links",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/detectedvalues/links"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/DetectedValues/moneyAmounts": {
      "abstract": [
        {
          "text": "An array of money amounts and currencies that the data detection system identifies.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "moneyAmounts"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)DDMatchMoneyAmount",
          "text": "DDMatchMoneyAmount"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/DetectedValues/moneyAmounts",
      "kind": "symbol",
      "role": "symbol",
      "title": "moneyAmounts",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/detectedvalues/moneyamounts"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/DetectedValues/number": {
      "abstract": [
        {
          "text": "A number that the data detection system identifies.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "number"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/DetectedValues/number",
      "kind": "symbol",
      "role": "symbol",
      "title": "number",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/detectedvalues/number"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/DetectedValues/patterns": {
      "abstract": [
        {
          "text": "A set of key paths that represent patterns that the data detection system identifies.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "patterns"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sh",
          "text": "Set"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s14PartialKeyPathC",
          "text": "PartialKeyPath"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:So12NSPasteboardC6AppKitE14DetectedValuesV",
          "text": "DetectedValues"
        },
        {
          "kind": "text",
          "text": ">>"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/DetectedValues/patterns",
      "kind": "symbol",
      "role": "symbol",
      "title": "patterns",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/detectedvalues/patterns"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/DetectedValues/phoneNumbers": {
      "abstract": [
        {
          "text": "An array of phone numbers that the data detection system identifies.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "phoneNumbers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)DDMatchPhoneNumber",
          "text": "DDMatchPhoneNumber"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/DetectedValues/phoneNumbers",
      "kind": "symbol",
      "role": "symbol",
      "title": "phoneNumbers",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/detectedvalues/phonenumbers"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/DetectedValues/postalAddresses": {
      "abstract": [
        {
          "text": "An array of postal addresses that the data detection system identifies.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postalAddresses"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)DDMatchPostalAddress",
          "text": "DDMatchPostalAddress"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/DetectedValues/postalAddresses",
      "kind": "symbol",
      "role": "symbol",
      "title": "postalAddresses",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/detectedvalues/postaladdresses"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/DetectedValues/probableWebSearch": {
      "abstract": [
        {
          "text": "A string that the data detection system identifies as a probable web search item, suitable for implementing “Paste and Search”.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "probableWebSearch"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/DetectedValues/probableWebSearch",
      "kind": "symbol",
      "role": "symbol",
      "title": "probableWebSearch",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/detectedvalues/probablewebsearch"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/DetectedValues/probableWebURL": {
      "abstract": [
        {
          "text": "A string that the data detection system identifies as a probable web URL, suitable for implementing “Paste and Go”.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "probableWebURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/DetectedValues/probableWebURL",
      "kind": "symbol",
      "role": "symbol",
      "title": "probableWebURL",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/detectedvalues/probableweburl"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/DetectedValues/shipmentTrackingNumbers": {
      "abstract": [
        {
          "text": "An array of parcel tracking numbers and carriers that the data detection system identifies.",
          "type": "text"
        }
      ],
      "beta": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shipmentTrackingNumbers"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)DDMatchShipmentTrackingNumber",
          "text": "DDMatchShipmentTrackingNumber"
        },
        {
          "kind": "text",
          "text": "]"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/DetectedValues/shipmentTrackingNumbers",
      "kind": "symbol",
      "role": "symbol",
      "title": "shipmentTrackingNumbers",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/detectedvalues/shipmenttrackingnumbers"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/DetectedValues/calendarEvents",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/DetectedValues/emailAddresses",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/DetectedValues/flightNumbers",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/DetectedValues/links",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/DetectedValues/moneyAmounts",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/DetectedValues/number",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/DetectedValues/patterns",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/DetectedValues/phoneNumbers",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/DetectedValues/postalAddresses",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/DetectedValues/probableWebSearch",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/DetectedValues/probableWebURL",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/DetectedValues/shipmentTrackingNumbers"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard/title",
          "value": "NSPasteboard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboard"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nspasteboard/detectedvalues"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
