{
  "abstract": [
    {
      "text": "Options for reading pasteboard data.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/ReadingOptionKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@T@NSPasteboardReadingOptionKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ReadingOptionKey"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ReadingOptionKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "NSPasteboard.ReadingOptionKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ReadingOptionKey"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "These options can be used for both the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/readObjects(forClasses:options:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/canReadObject(forClasses:options:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " methods, unless otherwise specified.  The currently available options allow for customization of how URLS are read from the pasteboard.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard": {
      "abstract": [
        {
          "text": "An object that transfers data to and from the pasteboard server.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSPasteboard"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPasteboard"
        }
      ],
      "role": "symbol",
      "title": "NSPasteboard",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/ReadingOptionKey": {
      "abstract": [
        {
          "text": "Options for reading pasteboard data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ReadingOptionKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/ReadingOptionKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ReadingOptionKey"
        }
      ],
      "role": "symbol",
      "title": "NSPasteboard.ReadingOptionKey",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/readingoptionkey"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/ReadingOptionKey/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/ReadingOptionKey/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/readingoptionkey/init(rawvalue:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/ReadingOptionKey/urlReadingContentsConformToTypes": {
      "abstract": [
        {
          "text": "Option for reading URLs to restrict the results to URLs with contents that conform to any of the provided UTI types.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "urlReadingContentsConformToTypes"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardReadingOptionKey",
          "text": "ReadingOptionKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/ReadingOptionKey/urlReadingContentsConformToTypes",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPasteboardURLReadingContentsConformToTypesKey"
        }
      ],
      "role": "symbol",
      "title": "urlReadingContentsConformToTypes",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/readingoptionkey/urlreadingcontentsconformtotypes"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/ReadingOptionKey/urlReadingFileURLsOnly": {
      "abstract": [
        {
          "text": "Option for reading URLs to restrict the results to file URLs only.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "urlReadingFileURLsOnly"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardReadingOptionKey",
          "text": "ReadingOptionKey"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/ReadingOptionKey/urlReadingFileURLsOnly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSPasteboardURLReadingFileURLsOnlyKey"
        }
      ],
      "role": "symbol",
      "title": "urlReadingFileURLsOnly",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/readingoptionkey/urlreadingfileurlsonly"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/ReadingOptions": {
      "abstract": [
        {
          "text": "Options that specify how to interpret data on the pasteboard when initializing pasteboard data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ReadingOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/ReadingOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ReadingOptions"
        }
      ],
      "role": "symbol",
      "title": "NSPasteboard.ReadingOptions",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/readingoptions"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/canReadObject(forClasses:options:)": {
      "abstract": [
        {
          "text": "Returns a Boolean value that indicates whether the receiver contains any items that can be represented as an instance of any class in a given array.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "canReadObject"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forClasses"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8AnyClassa",
          "text": "AnyClass"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardReadingOptionKey",
          "text": "ReadingOptionKey"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/canReadObject(forClasses:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "canReadObjectForClasses:options:"
        }
      ],
      "role": "symbol",
      "title": "canReadObject(forClasses:options:)",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/canreadobject(forclasses:options:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/data(forType:)": {
      "abstract": [
        {
          "text": "Returns the data for the specified type from the first item in the receiver that contains the type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "data"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardType",
          "text": "PasteboardType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation4DataV",
          "text": "Data"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/data(forType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dataForType:"
        }
      ],
      "role": "symbol",
      "title": "data(forType:)",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/data(fortype:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/index(of:)": {
      "abstract": [
        {
          "text": "Returns the index of the specified pasteboard item.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "index"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "of"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboardItem",
          "text": "NSPasteboardItem"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/index(of:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "indexOfPasteboardItem:"
        }
      ],
      "role": "symbol",
      "title": "index(of:)",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/index(of:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/pasteboardItems": {
      "abstract": [
        {
          "text": "An array that contains all the items held by the pasteboard.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pasteboardItems"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboardItem",
          "text": "NSPasteboardItem"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/pasteboardItems",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "pasteboardItems"
        }
      ],
      "role": "symbol",
      "title": "pasteboardItems",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/pasteboarditems"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/propertyList(forType:)": {
      "abstract": [
        {
          "text": "Returns the property list for the specified type from the first item in the receiver that contains the type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "propertyList"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardType",
          "text": "PasteboardType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/propertyList(forType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "propertyListForType:"
        }
      ],
      "role": "symbol",
      "title": "propertyList(forType:)",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/propertylist(fortype:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/readObjects(forClasses:options:)": {
      "abstract": [
        {
          "text": "Reads from the receiver objects that best match the specified array of classes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "readObjects"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forClasses"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s8AnyClassa",
          "text": "AnyClass"
        },
        {
          "kind": "text",
          "text": "], "
        },
        {
          "kind": "externalParam",
          "text": "options"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardReadingOptionKey",
          "text": "ReadingOptionKey"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?) -> ["
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/readObjects(forClasses:options:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "readObjectsForClasses:options:"
        }
      ],
      "role": "symbol",
      "title": "readObjects(forClasses:options:)",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/readobjects(forclasses:options:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/string(forType:)": {
      "abstract": [
        {
          "text": "Returns a concatenation of the strings for the specified type from all the items in the receiver that contain the type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "string"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSPasteboard",
          "text": "NSPasteboard"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSPasteboardType",
          "text": "PasteboardType"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/string(forType:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "stringForType:"
        }
      ],
      "role": "symbol",
      "title": "string(forType:)",
      "type": "topic",
      "url": "/documentation/appkit/nspasteboard/string(fortype:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSString": {
      "abstract": [
        {
          "text": "A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "NSString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSString",
      "type": "topic",
      "url": "/documentation/foundation/nsstring"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reading-Data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/readObjects(forClasses:options:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/ReadingOptions",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/pasteboardItems",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/index(of:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/data(forType:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/propertyList(forType:)",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/string(forType:)"
      ],
      "title": "Reading Data"
    }
  ],
  "topicSections": [
    {
      "anchor": "Type-Properties",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/ReadingOptionKey/urlReadingContentsConformToTypes",
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/ReadingOptionKey/urlReadingFileURLsOnly"
      ],
      "title": "Type Properties"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/ReadingOptionKey/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSPasteboardReadingOptionKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboardReadingOptionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboardReadingOptionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Type-Properties",
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/ReadingOptionKey/urlReadingContentsConformToTypes",
                "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/ReadingOptionKey/urlReadingFileURLsOnly"
              ],
              "title": "Type Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reading-Data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/readObjects(forClasses:options:)",
                "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/ReadingOptions",
                "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/pasteboardItems",
                "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/index(of:)",
                "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/data(forType:)",
                "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/propertyList(forType:)",
                "doc://com.apple.appkit/documentation/AppKit/NSPasteboard/string(forType:)"
              ],
              "title": "Reading Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSString",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSPasteboardReadingOptionKey"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard/title",
          "value": "NSPasteboard"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboard"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1readObjects(forClasses:options:)/title",
          "value": "readObjectsForClasses:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1readObjects(forClasses:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "readObjectsForClasses:options:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1ReadingOptions/title",
          "value": "NSPasteboardReadingOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1ReadingOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboardReadingOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1ReadingOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboardReadingOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1propertyList(forType:)/title",
          "value": "propertyListForType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1propertyList(forType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "propertyListForType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1canReadObject(forClasses:options:)/title",
          "value": "canReadObjectForClasses:options:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1canReadObject(forClasses:options:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "canReadObjectForClasses:options:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1pasteboardItems/title",
          "value": "pasteboardItems"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1pasteboardItems/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "pasteboardItems"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1ReadingOptionKey~1urlReadingContentsConformToTypes/title",
          "value": "NSPasteboardURLReadingContentsConformToTypesKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1ReadingOptionKey~1urlReadingContentsConformToTypes/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboardURLReadingContentsConformToTypesKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1string(forType:)/title",
          "value": "stringForType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1string(forType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "stringForType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1index(of:)/title",
          "value": "indexOfPasteboardItem:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1index(of:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "indexOfPasteboardItem:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1ReadingOptionKey~1urlReadingFileURLsOnly/title",
          "value": "NSPasteboardURLReadingFileURLsOnlyKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1ReadingOptionKey~1urlReadingFileURLsOnly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboardURLReadingFileURLsOnlyKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract",
          "value": [
            {
              "text": "A static, plain-text Unicode string object.",
              "type": "text"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1data(forType:)/title",
          "value": "dataForType:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1data(forType:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "dataForType:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1ReadingOptionKey/title",
          "value": "NSPasteboardReadingOptionKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1ReadingOptionKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboardReadingOptionKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1ReadingOptionKey/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSPasteboardReadingOptionKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nspasteboard/readingoptionkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nspasteboard/readingoptionkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
