{"variants":[{"paths":["/documentation/appkit/nspasteboard/setstring(_:fortype:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nspasteboard/setstring(_:fortype:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"string","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:SS"},{"text":", ","kind":"text"},{"text":"forType","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"dataType","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSPasteboard","preciseIdentifier":"c:objc(cs)NSPasteboard","kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard"},{"text":".","kind":"text"},{"text":"PasteboardType","preciseIdentifier":"c:@T@NSPasteboardType","kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/s:Sb"}],"languages":["swift"],"platforms":["macOS"]}]},{"kind":"parameters","parameters":[{"name":"string","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The string to write to the pasteboard."}]}]},{"name":"dataType","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The type of string data. The type must have been declared by a previous "},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/declareTypes(_:owner:)","isActive":true},{"type":"text","text":" message."}]}]}]},{"content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"inlineContent":[{"text":"","type":"text"},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/true","type":"reference"},{"text":" if the data was written successfully, otherwise ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/false","type":"reference"},{"text":" if ownership of the pasteboard has changed. Any other error raises an ","type":"text"},{"code":"NSPasteboardCommunicationException","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"},{"kind":"mentions","mentions":["doc://com.apple.appkit/documentation/AppKit/supporting-writing-tools-via-the-pasteboard"]},{"content":[{"anchor":"Discussion","type":"heading","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method invokes "},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/setData(_:forType:)","isActive":true},{"type":"text","text":" to perform the write."}]}],"kind":"content"}],"metadata":{"navigatorTitle":[{"text":"setString:forType:","kind":"identifier"}],"modules":[{"name":"AppKit"}],"title":"setString(_:forType:)","platforms":[{"name":"macOS","beta":false,"unavailable":false,"deprecated":false}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setString","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPasteboard","text":"NSPasteboard"},{"text":".","kind":"text"},{"text":"PasteboardType","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPasteboardType"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"externalID":"c:objc(cs)NSPasteboard(im)setString:forType:","roleHeading":"Instance Method","symbolKind":"method"},"abstract":[{"text":"Sets the given string as the representation for the specified type for the first item on the receiver.","type":"text"}],"seeAlsoSections":[{"title":"Related Documentation","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSPasteboard/string(forType:)"],"anchor":"Related-Documentation"},{"title":"Writing Data","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSPasteboard/clearContents()","doc://com.apple.appkit/documentation/AppKit/NSPasteboard/writeObjects(_:)","doc://com.apple.appkit/documentation/AppKit/NSPasteboard/setData(_:forType:)","doc://com.apple.appkit/documentation/AppKit/NSPasteboard/setPropertyList(_:forType:)","doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType"],"generated":true,"anchor":"Writing-Data"}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/setString(_:forType:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSPasteboard"]]},"references":{"doc://com.externally.resolved.symbol/s:SS":{"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:SS","url":"/documentation/Swift/String","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"String","kind":"identifier"}],"type":"topic","title":"String","role":"symbol","abstract":[{"text":"A Unicode string value that is a collection of characters.","type":"text"}]},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/writeObjects(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"writeObjects","kind":"identifier"},{"text":"([any ","kind":"text"},{"text":"NSPasteboardWriting","preciseIdentifier":"c:objc(pl)NSPasteboardWriting","kind":"typeIdentifier"},{"text":"]) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol","url":"/documentation/appkit/nspasteboard/writeobjects(_:)","abstract":[{"text":"Writes an array of objects to the receiver.","type":"text"}],"title":"writeObjects(_:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/writeObjects(_:)","navigatorTitle":[{"kind":"identifier","text":"writeObjects:"}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType":{"abstract":[{"text":"The supported pasteboard types.","type":"text"}],"navigatorTitle":[{"text":"PasteboardType","kind":"identifier"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType","url":"/documentation/appkit/nspasteboard/pasteboardtype","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PasteboardType","kind":"identifier"}],"role":"symbol","title":"NSPasteboard.PasteboardType"},"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/setString(_:forType:)":{"abstract":[{"type":"text","text":"Sets the given string as the representation for the specified type for the first item on the receiver."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSPasteboard","kind":"typeIdentifier","text":"NSPasteboard"},{"kind":"text","text":"."},{"text":"PasteboardType","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPasteboardType"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"/documentation/appkit/nspasteboard/setstring(_:fortype:)","title":"setString(_:forType:)","kind":"symbol","navigatorTitle":[{"text":"setString:forType:","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/setString(_:forType:)","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/declareTypes(_:owner:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"declareTypes","kind":"identifier"},{"text":"([","kind":"text"},{"text":"NSPasteboard","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPasteboard"},{"text":".","kind":"text"},{"text":"PasteboardType","preciseIdentifier":"c:@T@NSPasteboardType","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"owner","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"role":"symbol","url":"/documentation/appkit/nspasteboard/declaretypes(_:owner:)","abstract":[{"text":"Prepares the receiver for a change in its contents by declaring the new types of data it will contain and a new owner.","type":"text"}],"title":"declareTypes(_:owner:)","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/declareTypes(_:owner:)","navigatorTitle":[{"kind":"identifier","text":"declareTypes:owner:"}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/setData(_:forType:)":{"title":"setData(_:forType:)","kind":"symbol","abstract":[{"type":"text","text":"Sets the data as the representation for the specified type for the first item on the receiver."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"forType","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSPasteboard","kind":"typeIdentifier","text":"NSPasteboard"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@NSPasteboardType","kind":"typeIdentifier","text":"PasteboardType"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"setData:forType:","kind":"identifier"}],"type":"topic","url":"/documentation/appkit/nspasteboard/setdata(_:fortype:)","role":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/setData(_:forType:)"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"title":"BOOL","kind":"symbol","abstract":[{"type":"text","text":"Type to represent a Boolean value."}],"type":"topic","role":"symbol","url":"/documentation/objectivec/bool","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},"doc://com.externally.resolved.symbol/s:Sb":{"title":"Bool","type":"topic","identifier":"doc://com.externally.resolved.symbol/s:Sb","role":"symbol","fragments":[{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Bool","kind":"identifier"}],"abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}],"kind":"symbol","url":"/documentation/Swift/Bool"},"doc://com.apple.appkit/documentation/AppKit/supporting-writing-tools-via-the-pasteboard":{"type":"topic","url":"/documentation/appkit/supporting-writing-tools-via-the-pasteboard","title":"Supporting Writing Tools via the pasteboard","abstract":[{"type":"text","text":"Adopt a simplified version of the Writing Tools experience in a custom"},{"type":"text","text":" "},{"type":"text","text":"view using the pasteboard and macOS services."}],"identifier":"doc://com.apple.appkit/documentation/AppKit/supporting-writing-tools-via-the-pasteboard","kind":"article","role":"article"},"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/setPropertyList(_:forType:)":{"abstract":[{"text":"Sets the given property list as the representation for the specified type for the first item on the receiver.","type":"text"}],"url":"/documentation/appkit/nspasteboard/setpropertylist(_:fortype:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setPropertyList","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":", ","kind":"text"},{"text":"forType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSPasteboard","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPasteboard"},{"text":".","kind":"text"},{"text":"PasteboardType","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPasteboardType"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/setPropertyList(_:forType:)","kind":"symbol","title":"setPropertyList(_:forType:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setPropertyList:forType:"}]},"doc://com.apple.documentation/documentation/swift/true":{"title":"true","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/true","role":"symbol","abstract":[{"type":"text","text":"A true value."}],"kind":"symbol","url":"/documentation/swift/true"},"doc://com.apple.documentation/documentation/swift/false":{"title":"false","type":"topic","identifier":"doc://com.apple.documentation/documentation/swift/false","role":"symbol","abstract":[{"text":"A false value.","type":"text"}],"kind":"symbol","url":"/documentation/swift/false"},"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/string(forType:)":{"kind":"symbol","navigatorTitle":[{"text":"stringForType:","kind":"identifier"}],"role":"symbol","title":"string(forType:)","abstract":[{"text":"Returns a concatenation of the strings for the specified type from all the items in the receiver that contain the type.","type":"text"}],"url":"/documentation/appkit/nspasteboard/string(fortype:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"string","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSPasteboard","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSPasteboard"},{"text":".","kind":"text"},{"text":"PasteboardType","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSPasteboardType"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/string(forType:)"},"doc://com.apple.appkit/documentation/AppKit/NSPasteboard":{"url":"/documentation/appkit/nspasteboard","title":"NSPasteboard","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NSPasteboard"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"NSPasteboard","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard","abstract":[{"text":"An object that transfers data to and from the pasteboard server.","type":"text"}],"role":"symbol"},"doc://com.externally.resolved.symbol/c:objc(cs)NSString":{"identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","abstract":[{"text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ","type":"text"}],"role":"symbol","fragments":[{"text":"class ","kind":"text"},{"text":"NSString","kind":"identifier"}],"title":"NSString","kind":"symbol","url":"/documentation/foundation/nsstring","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/clearContents()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clearContents","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"role":"symbol","url":"/documentation/appkit/nspasteboard/clearcontents()","abstract":[{"text":"Clears the existing contents of the pasteboard.","type":"text"}],"title":"clearContents()","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/clearContents()","navigatorTitle":[{"text":"clearContents","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"/identifier/interfaceLanguage"},{"value":[{"beta":false,"name":"macOS","unavailable":false,"deprecated":false}],"op":"replace","path":"/metadata/platforms"},{"value":"Instance Method","op":"replace","path":"/metadata/roleHeading"},{"value":"setString:forType:","op":"replace","path":"/metadata/title"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setString:forType:"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSPasteboard"]]},"op":"replace","path":"/hierarchy"},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"title":"Related Documentation","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSPasteboard/string(forType:)"],"anchor":"Related-Documentation"},{"generated":true,"title":"Writing Data","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSPasteboard/clearContents()","doc://com.apple.appkit/documentation/AppKit/NSPasteboard/writeObjects(_:)","doc://com.apple.appkit/documentation/AppKit/NSPasteboard/setData(_:forType:)","doc://com.apple.appkit/documentation/AppKit/NSPasteboard/setPropertyList(_:forType:)","doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType"],"anchor":"Writing-Data"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"setString:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"string"},{"kind":"text","text":" "},{"kind":"identifier","text":"forType:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSPasteboardType","preciseIdentifier":"c:@T@NSPasteboardType","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/PasteboardType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"dataType"},{"kind":"text","text":";"}]}]}},{"path":"/primaryContentSections/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The string to write to the pasteboard.","type":"text"}]}],"name":"string"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The type of string data. The type must have been declared by a previous "},{"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSPasteboard/declareTypes(_:owner:)","isActive":true},{"type":"text","text":" message."}]}],"name":"dataType"}],"kind":"parameters"},"op":"replace"},{"op":"replace","path":"/primaryContentSections/2","value":{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/true","type":"reference"},{"text":" if the data was written successfully, otherwise ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/swift/false","type":"reference"},{"text":" if ownership of the pasteboard has changed. Any other error raises an ","type":"text"},{"code":"NSPasteboardCommunicationException","type":"codeVoice"},{"text":".","type":"text"}]}]}},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1writeObjects(_:)/title","value":"writeObjects:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1writeObjects(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"writeObjects:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType/title","value":"NSPasteboardType","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType/fragments","value":[{"text":"NSPasteboardType","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1PasteboardType/navigatorTitle","value":[{"text":"NSPasteboardType","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1setString(_:forType:)/title","value":"setString:forType:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1setString(_:forType:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setString:forType:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1declareTypes(_:owner:)/title","value":"declareTypes:owner:","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1declareTypes(_:owner:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"declareTypes:owner:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1setData(_:forType:)/title","value":"setData:forType:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1setData(_:forType:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setData:forType:"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1setPropertyList(_:forType:)/title","value":"setPropertyList:forType:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1setPropertyList(_:forType:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"setPropertyList:forType:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1string(forType:)/title","value":"stringForType:"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1string(forType:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"stringForType:","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard/title","value":"NSPasteboard"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard/fragments","value":[{"kind":"identifier","text":"NSPasteboard"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard/navigatorTitle","value":[{"kind":"identifier","text":"NSPasteboard"}]},{"op":"replace","path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract","value":[{"type":"text","text":"A static, plain-text Unicode string object."}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1clearContents()/title","value":"clearContents"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSPasteboard~1clearContents()/fragments","value":[{"text":"- ","kind":"text"},{"text":"clearContents","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}