{
  "abstract": [
    {
      "text": "The system launches your app at most once per week in response to changes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.healthkit/documentation/HealthKit",
        "doc://com.apple.healthkit/documentation/HealthKit/HKUpdateFrequency"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.healthkit/documentation/HealthKit/HKUpdateFrequency/weekly"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@HKUpdateFrequency@HKUpdateFrequencyWeekly",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "weekly"
      }
    ],
    "modules": [
      {
        "name": "HealthKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "HKUpdateFrequencyWeekly"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "HKUpdateFrequency.weekly"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "weekly"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.healthkit/documentation/HealthKit": {
      "abstract": [
        {
          "text": "Access and share health and fitness data while maintaining the user’s privacy and control.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit",
      "kind": "symbol",
      "role": "collection",
      "title": "HealthKit",
      "type": "topic",
      "url": "/documentation/healthkit"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKUpdateFrequency": {
      "abstract": [
        {
          "text": "Constants that determine how often the system launches your app in response to changes to HealthKit data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "HKUpdateFrequency"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKUpdateFrequency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKUpdateFrequency"
        }
      ],
      "role": "symbol",
      "title": "HKUpdateFrequency",
      "type": "topic",
      "url": "/documentation/healthkit/hkupdatefrequency"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKUpdateFrequency/daily": {
      "abstract": [
        {
          "text": "The system launches your app at most once a day in response to changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "daily"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKUpdateFrequency/daily",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKUpdateFrequencyDaily"
        }
      ],
      "role": "symbol",
      "title": "HKUpdateFrequency.daily",
      "type": "topic",
      "url": "/documentation/healthkit/hkupdatefrequency/daily"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKUpdateFrequency/hourly": {
      "abstract": [
        {
          "text": "The system launches your app at most once an hour in response to changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "hourly"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKUpdateFrequency/hourly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKUpdateFrequencyHourly"
        }
      ],
      "role": "symbol",
      "title": "HKUpdateFrequency.hourly",
      "type": "topic",
      "url": "/documentation/healthkit/hkupdatefrequency/hourly"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKUpdateFrequency/immediate": {
      "abstract": [
        {
          "text": "The system launches your app every time it detects a change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "immediate"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKUpdateFrequency/immediate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKUpdateFrequencyImmediate"
        }
      ],
      "role": "symbol",
      "title": "HKUpdateFrequency.immediate",
      "type": "topic",
      "url": "/documentation/healthkit/hkupdatefrequency/immediate"
    },
    "doc://com.apple.healthkit/documentation/HealthKit/HKUpdateFrequency/weekly": {
      "abstract": [
        {
          "text": "The system launches your app at most once per week in response to changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "weekly"
        }
      ],
      "identifier": "doc://com.apple.healthkit/documentation/HealthKit/HKUpdateFrequency/weekly",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "HKUpdateFrequencyWeekly"
        }
      ],
      "role": "symbol",
      "title": "HKUpdateFrequency.weekly",
      "type": "topic",
      "url": "/documentation/healthkit/hkupdatefrequency/weekly"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.healthkit/documentation/HealthKit/HKUpdateFrequency/immediate",
        "doc://com.apple.healthkit/documentation/HealthKit/HKUpdateFrequency/hourly",
        "doc://com.apple.healthkit/documentation/HealthKit/HKUpdateFrequency/daily"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "HKUpdateFrequencyWeekly"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKUpdateFrequencyWeekly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.healthkit/documentation/HealthKit",
                "doc://com.apple.healthkit/documentation/HealthKit/HKUpdateFrequency"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.healthkit/documentation/HealthKit/HKUpdateFrequency/immediate",
                "doc://com.apple.healthkit/documentation/HealthKit/HKUpdateFrequency/hourly",
                "doc://com.apple.healthkit/documentation/HealthKit/HKUpdateFrequency/daily"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "HKUpdateFrequencyWeekly"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKUpdateFrequency/title",
          "value": "HKUpdateFrequency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKUpdateFrequency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKUpdateFrequency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKUpdateFrequency/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "HKUpdateFrequency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKUpdateFrequency~1hourly/title",
          "value": "HKUpdateFrequencyHourly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKUpdateFrequency~1hourly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKUpdateFrequencyHourly"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKUpdateFrequency~1daily/title",
          "value": "HKUpdateFrequencyDaily"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKUpdateFrequency~1daily/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKUpdateFrequencyDaily"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKUpdateFrequency~1immediate/title",
          "value": "HKUpdateFrequencyImmediate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKUpdateFrequency~1immediate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKUpdateFrequencyImmediate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKUpdateFrequency~1weekly/title",
          "value": "HKUpdateFrequencyWeekly"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.healthkit~1documentation~1HealthKit~1HKUpdateFrequency~1weekly/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "HKUpdateFrequencyWeekly"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/healthkit/hkupdatefrequency/weekly"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/healthkit/hkupdatefrequency/weekly"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
