{
  "abstract": [
    {
      "text": "Copies texture data to another texture.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.RealityKit/documentation/RealityKit",
        "doc://com.apple.RealityKit/documentation/RealityKit/TextureResource"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.RealityKit/documentation/RealityKit/TextureResource/copy(to:)-jfbi"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:17RealityFoundation15TextureResourceC4copy2toySo10MTLTexture_p_tKF",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "copy"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "to"
      },
      {
        "kind": "text",
        "text": ": any "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(pl)MTLTexture",
        "text": "MTLTexture"
      },
      {
        "kind": "text",
        "text": ") "
      },
      {
        "kind": "keyword",
        "text": "throws"
      }
    ],
    "modules": [
      {
        "name": "RealityKit"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "copy(to:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "attribute",
              "text": "@preconcurrency"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "copy"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "to"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "texture"
            },
            {
              "kind": "text",
              "text": ": any "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)MTLTexture",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)MTLTexture",
              "text": "MTLTexture"
            },
            {
              "kind": "text",
              "text": ") "
            },
            {
              "kind": "keyword",
              "text": "throws"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The target texture for copying the data. It needs to have the same width and height as ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/TextureResource",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", and",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/Metal/MTLTextureUsage/shaderWrite",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " usage.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "texture"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This method blocks until it finishes copying the data. If you have an attached ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/TextureResource/DrawableQueue-swift.class",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " on",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "this resource, this function detaches it.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "This method copies all available mipmap sizes to ",
              "type": "text"
            },
            {
              "code": "texture",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "It’s recommended that you provide a value for ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/TextureResource/CreateOptions/semantic",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " when creating this resource. Specifying a",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "semantic enables RealityKit to select an appropriate pixel format for the target texture.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Here’s an example using ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/TextureResource/copy(to:)-jfbi",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to get a texture resource’s raw pixel data:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "let device: MTLDevice = ...",
            "let resource: TextureResource = ...",
            "let descriptor = MTLTextureDescriptor.texture2DDescriptor(",
            "    pixelFormat: .rgba8Unorm,",
            "    width: resource.width, // Needs to match the texture resource.",
            "    height: resource.height, // Needs to match the texture resource.",
            "    mipmapped: false)",
            "descriptor.usage = .shaderWrite // This is required for copying.",
            "",
            "guard let texture = device.makeTexture(descriptor: descriptor)",
            "else { throw ... }",
            "try resource.copy(to: texture)",
            "",
            "#if os(OSX) // The managed mode exists only in OSX.",
            "if texture.storageMode == .managed {",
            "    // You need to synchronize the managed textures before accessing their data.",
            "    guard let commandBuffer = device.makeCommandQueue()?.makeCommandBuffer(),",
            "          let blitEncoder = commandBuffer.makeBlitCommandEncoder()",
            "    else { throw ... }",
            "",
            "    blitEncoder.synchronize(resource: texture)",
            "    blitEncoder.endEncoding()",
            "    commandBuffer.commit()",
            "    commandBuffer.waitUntilCompleted()",
            "}",
            "#endif",
            "",
            "// Getting the raw pixel bytes.",
            "let bytesPerRow = 4 * texture.width",
            "var bytes = [UInt8](repeating: 0, count: texture.height * bytesPerRow)",
            "bytes.withUnsafeMutableBytes { bytesPtr in",
            "    texture.getBytes(",
            "        bytesPtr.baseAddress!,",
            "        bytesPerRow: bytesPerRow,",
            "        from: .init(origin: .init(), size: .init(width: texture.width, height: texture.height, depth: 1)),",
            "        mipmapLevel: 0",
            "    )",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.RealityKit/documentation/RealityKit": {
      "abstract": [
        {
          "text": "Simulate and render 3D content for use in your augmented reality apps.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit",
      "kind": "symbol",
      "role": "collection",
      "title": "RealityKit",
      "type": "topic",
      "url": "/documentation/realitykit"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/TextureResource": {
      "abstract": [
        {
          "text": "A representation of a texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "TextureResource"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/TextureResource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "TextureResource"
        }
      ],
      "role": "symbol",
      "title": "TextureResource",
      "type": "topic",
      "url": "/documentation/realitykit/textureresource"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/TextureResource/CreateOptions/semantic": {
      "abstract": [
        {
          "text": "The intended use of the texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "semantic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:17RealityFoundation15TextureResourceC",
          "text": "TextureResource"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:17RealityFoundation15TextureResourceC8SemanticO",
          "text": "Semantic"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/TextureResource/CreateOptions/semantic",
      "kind": "symbol",
      "role": "symbol",
      "title": "semantic",
      "type": "topic",
      "url": "/documentation/realitykit/textureresource/createoptions/semantic"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/TextureResource/DrawableQueue-swift.class": {
      "abstract": [
        {
          "text": "A drawable queue that may be used to update a texture resource dynamically",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DrawableQueue"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/TextureResource/DrawableQueue-swift.class",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DrawableQueue"
        }
      ],
      "role": "symbol",
      "title": "TextureResource.DrawableQueue",
      "type": "topic",
      "url": "/documentation/realitykit/textureresource/drawablequeue-swift.class"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/TextureResource/copy(to:)-3lfen": {
      "abstract": [
        {
          "text": "Asynchronously copies texture data to another texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "copy"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLTexture",
          "text": "MTLTexture"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "async"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/TextureResource/copy(to:)-3lfen",
      "kind": "symbol",
      "role": "symbol",
      "title": "copy(to:)",
      "type": "topic",
      "url": "/documentation/realitykit/textureresource/copy(to:)-3lfen"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/TextureResource/copy(to:)-jfbi": {
      "abstract": [
        {
          "text": "Copies texture data to another texture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "copy"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLTexture",
          "text": "MTLTexture"
        },
        {
          "kind": "text",
          "text": ") "
        },
        {
          "kind": "keyword",
          "text": "throws"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/TextureResource/copy(to:)-jfbi",
      "kind": "symbol",
      "role": "symbol",
      "title": "copy(to:)",
      "type": "topic",
      "url": "/documentation/realitykit/textureresource/copy(to:)-jfbi"
    },
    "doc://com.apple.RealityKit/documentation/RealityKit/TextureResource/copyAsync(to:completionHandler:)": {
      "abstract": [
        {
          "text": "Asynchronously copies texture data to another texture.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "copyAsync"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLTexture",
          "text": "MTLTexture"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "completionHandler"
        },
        {
          "kind": "text",
          "text": ": ((any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5ErrorP",
          "text": "Error"
        },
        {
          "kind": "text",
          "text": ")?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.RealityKit/documentation/RealityKit/TextureResource/copyAsync(to:completionHandler:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "copyAsync(to:completionHandler:)",
      "type": "topic",
      "url": "/documentation/realitykit/textureresource/copyasync(to:completionhandler:)"
    },
    "doc://com.apple.documentation/documentation/Metal/MTLTextureUsage/shaderWrite": {
      "abstract": [
        {
          "text": "An option for writing to the texture in a shader.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "shaderWrite"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@MTLTextureUsage",
          "text": "MTLTextureUsage"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Metal/MTLTextureUsage/shaderWrite",
      "kind": "symbol",
      "role": "symbol",
      "title": "shaderWrite",
      "type": "topic",
      "url": "/documentation/Metal/MTLTextureUsage/shaderWrite"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)MTLTexture": {
      "abstract": [
        {
          "text": "A resource that holds formatted image data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MTLTexture"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)MTLResource",
          "text": "MTLResource"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)MTLTexture",
      "kind": "symbol",
      "role": "symbol",
      "title": "MTLTexture",
      "type": "topic",
      "url": "/documentation/Metal/MTLTexture"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Copying-the-texture",
      "generated": true,
      "identifiers": [
        "doc://com.apple.RealityKit/documentation/RealityKit/TextureResource/copy(to:)-3lfen",
        "doc://com.apple.RealityKit/documentation/RealityKit/TextureResource/copyAsync(to:completionHandler:)"
      ],
      "title": "Copying the texture"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Metal~1MTLTextureUsage~1shaderWrite/title",
          "value": "MTLTextureUsageShaderWrite"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1Metal~1MTLTextureUsage~1shaderWrite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MTLTextureUsageShaderWrite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)MTLTexture/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MTLTexture"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)MTLResource",
              "text": "MTLResource"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/realitykit/textureresource/copy(to:)-jfbi"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
