{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.bundleresources/documentation/BundleResources",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutItems"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutItems/UIApplicationShortcutItemUserInfo"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "plist:Information_Property_List.UIApplicationShortcutItems.UIApplicationShortcutItemUserInfo",
    "modules": [
      {
        "name": "Bundle Resources"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIApplicationShortcutItemUserInfo"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "iPadOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Property List Key",
    "symbolKind": "dictionary",
    "title": "UIApplicationShortcutItemUserInfo"
  },
  "primaryContentSections": [
    {
      "details": {
        "name": "UIApplicationShortcutItemUserInfo",
        "platforms": [],
        "titleStyle": "symbol",
        "value": [
          {
            "arrayMode": false,
            "baseType": "object"
          }
        ]
      },
      "kind": "details",
      "title": "Details"
    }
  ],
  "references": {
    "doc://com.apple.bundleresources/documentation/BundleResources": {
      "abstract": [
        {
          "text": "Resources located in an app, framework, or plugin bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources",
      "kind": "symbol",
      "role": "collection",
      "title": "Bundle Resources",
      "type": "topic",
      "url": "/documentation/bundleresources"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List": {
      "abstract": [
        {
          "text": "A resource containing key-value pairs that identify and configure a bundle.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
      "kind": "symbol",
      "name": "Information Property List",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Information Property List"
        }
      ],
      "role": "symbol",
      "title": "Information Property List",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutItems": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutItems",
      "kind": "symbol",
      "name": "UIApplicationShortcutItems",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutItems"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutItems",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationshortcutitems"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutItems/UIApplicationShortcutItemIconFile": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutItems/UIApplicationShortcutItemIconFile",
      "kind": "symbol",
      "name": "UIApplicationShortcutItemIconFile",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutItemIconFile"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutItemIconFile",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationshortcutitems/uiapplicationshortcutitemiconfile"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutItems/UIApplicationShortcutItemIconSymbolName": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutItems/UIApplicationShortcutItemIconSymbolName",
      "kind": "symbol",
      "name": "UIApplicationShortcutItemIconSymbolName",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutItemIconSymbolName"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutItemIconSymbolName",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationshortcutitems/uiapplicationshortcutitemiconsymbolname"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutItems/UIApplicationShortcutItemIconType": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutItems/UIApplicationShortcutItemIconType",
      "kind": "symbol",
      "name": "UIApplicationShortcutItemIconType",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutItemIconType"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutItemIconType",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationshortcutitems/uiapplicationshortcutitemicontype"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutItems/UIApplicationShortcutItemSubtitle": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutItems/UIApplicationShortcutItemSubtitle",
      "kind": "symbol",
      "name": "UIApplicationShortcutItemSubtitle",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutItemSubtitle"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutItemSubtitle",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationshortcutitems/uiapplicationshortcutitemsubtitle"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutItems/UIApplicationShortcutItemTitle": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutItems/UIApplicationShortcutItemTitle",
      "kind": "symbol",
      "name": "UIApplicationShortcutItemTitle",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutItemTitle"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutItemTitle",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationshortcutitems/uiapplicationshortcutitemtitle"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutItems/UIApplicationShortcutItemType": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutItems/UIApplicationShortcutItemType",
      "kind": "symbol",
      "name": "UIApplicationShortcutItemType",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutItemType"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutItemType",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationshortcutitems/uiapplicationshortcutitemtype"
    },
    "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutItems/UIApplicationShortcutItemUserInfo": {
      "abstract": [],
      "identifier": "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutItems/UIApplicationShortcutItemUserInfo",
      "kind": "symbol",
      "name": "UIApplicationShortcutItemUserInfo",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIApplicationShortcutItemUserInfo"
        }
      ],
      "role": "symbol",
      "title": "UIApplicationShortcutItemUserInfo",
      "titleStyle": "symbol",
      "type": "topic",
      "url": "/documentation/bundleresources/information-property-list/uiapplicationshortcutitems/uiapplicationshortcutitemuserinfo"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Item-Configuration",
      "generated": true,
      "identifiers": [
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutItems/UIApplicationShortcutItemIconFile",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutItems/UIApplicationShortcutItemIconSymbolName",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutItems/UIApplicationShortcutItemIconType",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutItems/UIApplicationShortcutItemSubtitle",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutItems/UIApplicationShortcutItemTitle",
        "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutItems/UIApplicationShortcutItemType"
      ],
      "title": "Item Configuration"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "iPadOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Property List Key"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UIApplicationShortcutItemUserInfo"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "dictionary"
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutItemUserInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.bundleresources/documentation/BundleResources",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutItems"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Item-Configuration",
              "generated": true,
              "identifiers": [
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutItems/UIApplicationShortcutItemIconFile",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutItems/UIApplicationShortcutItemIconSymbolName",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutItems/UIApplicationShortcutItemIconType",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutItems/UIApplicationShortcutItemSubtitle",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutItems/UIApplicationShortcutItemTitle",
                "doc://com.apple.bundleresources/documentation/BundleResources/Information-Property-List/UIApplicationShortcutItems/UIApplicationShortcutItemType"
              ],
              "title": "Item Configuration"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationShortcutItems~1UIApplicationShortcutItemSubtitle/title",
          "value": "UIApplicationShortcutItemSubtitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationShortcutItems~1UIApplicationShortcutItemSubtitle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutItemSubtitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationShortcutItems~1UIApplicationShortcutItemTitle/title",
          "value": "UIApplicationShortcutItemTitle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationShortcutItems~1UIApplicationShortcutItemTitle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutItemTitle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationShortcutItems/title",
          "value": "UIApplicationShortcutItems"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationShortcutItems/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutItems"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationShortcutItems~1UIApplicationShortcutItemUserInfo/title",
          "value": "UIApplicationShortcutItemUserInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationShortcutItems~1UIApplicationShortcutItemUserInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutItemUserInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/title",
          "value": "Information Property List"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "Information Property List"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationShortcutItems~1UIApplicationShortcutItemIconFile/title",
          "value": "UIApplicationShortcutItemIconFile"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationShortcutItems~1UIApplicationShortcutItemIconFile/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutItemIconFile"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationShortcutItems~1UIApplicationShortcutItemIconSymbolName/title",
          "value": "UIApplicationShortcutItemIconSymbolName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationShortcutItems~1UIApplicationShortcutItemIconSymbolName/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutItemIconSymbolName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationShortcutItems~1UIApplicationShortcutItemIconType/title",
          "value": "UIApplicationShortcutItemIconType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationShortcutItems~1UIApplicationShortcutItemIconType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutItemIconType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationShortcutItems~1UIApplicationShortcutItemType/title",
          "value": "UIApplicationShortcutItemType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.bundleresources~1documentation~1BundleResources~1Information-Property-List~1UIApplicationShortcutItems~1UIApplicationShortcutItemType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIApplicationShortcutItemType"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/uiapplicationshortcutitems/uiapplicationshortcutitemuserinfo"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/bundleresources/information-property-list/uiapplicationshortcutitems/uiapplicationshortcutitemuserinfo"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
