{
  "abstract": [
    {
      "text": "Creates a trip with an origin, destination, and route choices.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.carplay/documentation/CarPlay",
        "doc://com.apple.carplay/documentation/CarPlay/CPTrip"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.carplay/documentation/CarPlay/CPTrip/init(origin:destination:routeChoices:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)CPTrip(im)initWithOrigin:destination:routeChoices:",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "origin"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MKMapItem",
        "text": "MKMapItem"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "destination"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)MKMapItem",
        "text": "MKMapItem"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "routeChoices"
      },
      {
        "kind": "text",
        "text": ": ["
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)CPRouteChoice",
        "text": "CPRouteChoice"
      },
      {
        "kind": "text",
        "text": "])"
      }
    ],
    "modules": [
      {
        "name": "CarPlay"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "initWithOrigin:destination:routeChoices:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(origin:destination:routeChoices:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "origin"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)MKMapItem",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MKMapItem",
              "text": "MKMapItem"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "destination"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)MKMapItem",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)MKMapItem",
              "text": "MKMapItem"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "routeChoices"
            },
            {
              "kind": "text",
              "text": ": ["
            },
            {
              "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPRouteChoice",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)CPRouteChoice",
              "text": "CPRouteChoice"
            },
            {
              "kind": "text",
              "text": "])"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The trip’s origin.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "origin"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The trip’s destination.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "destination"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Up to three route choices available for the trip.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "routeChoices"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A newly initialized trip.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.carplay/documentation/CarPlay": {
      "abstract": [
        {
          "text": "Integrate CarPlay in apps related to audio, communication, navigation, parking, EV charging, food ordering, and more.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay",
      "kind": "symbol",
      "role": "collection",
      "title": "CarPlay",
      "type": "topic",
      "url": "/documentation/carplay"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPRouteChoice": {
      "abstract": [
        {
          "text": "A possible route for a trip.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPRouteChoice"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPRouteChoice",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPRouteChoice"
        }
      ],
      "role": "symbol",
      "title": "CPRouteChoice",
      "type": "topic",
      "url": "/documentation/carplay/cproutechoice"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTrip": {
      "abstract": [
        {
          "text": "An object that represents a journey between an origin and a destination.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CPTrip"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTrip",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CPTrip"
        }
      ],
      "role": "symbol",
      "title": "CPTrip",
      "type": "topic",
      "url": "/documentation/carplay/cptrip"
    },
    "doc://com.apple.carplay/documentation/CarPlay/CPTrip/init(origin:destination:routeChoices:)": {
      "abstract": [
        {
          "text": "Creates a trip with an origin, destination, and route choices.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "origin"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapItem",
          "text": "MKMapItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "destination"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)MKMapItem",
          "text": "MKMapItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "routeChoices"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)CPRouteChoice",
          "text": "CPRouteChoice"
        },
        {
          "kind": "text",
          "text": "])"
        }
      ],
      "identifier": "doc://com.apple.carplay/documentation/CarPlay/CPTrip/init(origin:destination:routeChoices:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithOrigin:destination:routeChoices:"
        }
      ],
      "role": "symbol",
      "title": "init(origin:destination:routeChoices:)",
      "type": "topic",
      "url": "/documentation/carplay/cptrip/init(origin:destination:routechoices:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)MKMapItem": {
      "abstract": [
        {
          "text": "A point of interest on the map.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MKMapItem"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)MKMapItem",
      "kind": "symbol",
      "role": "symbol",
      "title": "MKMapItem",
      "type": "topic",
      "url": "/documentation/MapKit/MKMapItem"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-a-Trip",
      "generated": true,
      "identifiers": [
        "doc://com.apple.carplay/documentation/CarPlay/CPRouteChoice"
      ],
      "title": "Creating a Trip"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "initWithOrigin:destination:routeChoices:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithOrigin:destination:routeChoices:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.carplay/documentation/CarPlay",
                "doc://com.apple.carplay/documentation/CarPlay/CPTrip"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-a-Trip",
              "generated": true,
              "identifiers": [
                "doc://com.apple.carplay/documentation/CarPlay/CPRouteChoice"
              ],
              "title": "Creating a Trip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "Mac Catalyst"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "keyword",
                    "text": "instancetype"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "initWithOrigin:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)MKMapItem",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MKMapItem",
                    "text": "MKMapItem"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "origin"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "destination:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)MKMapItem",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)MKMapItem",
                    "text": "MKMapItem"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "destination"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "routeChoices:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:Q$objc(cs)NSArray",
                    "text": "NSArray<CPRouteChoice *>"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "routeChoices"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The trip’s origin.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "origin"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The trip’s destination.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "destination"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "Up to three route choices available for the trip.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "routeChoices"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A newly initialized trip.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTrip/title",
          "value": "CPTrip"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTrip/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTrip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTrip/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPTrip"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPRouteChoice/title",
          "value": "CPRouteChoice"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPRouteChoice/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CPRouteChoice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPRouteChoice/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CPRouteChoice"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTrip~1init(origin:destination:routeChoices:)/title",
          "value": "initWithOrigin:destination:routeChoices:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.carplay~1documentation~1CarPlay~1CPTrip~1init(origin:destination:routeChoices:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithOrigin:destination:routeChoices:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)MKMapItem/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "MKMapItem"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/carplay/cptrip/init(origin:destination:routechoices:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/carplay/cptrip/init(origin:destination:routechoices:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
