{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/simd",
        "doc://com.apple.accelerate/documentation/simd/simd_double4x2"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/simd/simd_double4x2/*(_:_:)-8tpc2"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "simd",
    "externalID": "s:So14simd_double4x2a0A0E1moiyA2B_So0A10_double4x4atFZ",
    "fragments": [
      {
        "kind": "keyword",
        "text": "static"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "*"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@simd_double4x2",
        "text": "simd_double4x2"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:4simd9double4x4a",
        "text": "double4x4"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:4simd9double4x2a",
        "text": "double4x2"
      }
    ],
    "modules": [
      {
        "name": "simd"
      }
    ],
    "role": "symbol",
    "roleHeading": "Operator",
    "symbolKind": "op",
    "title": "*(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "static"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "*"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "internalParam",
              "text": "lhs"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@simd_double4x2",
              "text": "simd_double4x2"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "internalParam",
              "text": "rhs"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/double4x4",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:4simd9double4x4a",
              "text": "double4x4"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.accelerate/documentation/simd/double4x2",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:4simd9double4x2a",
              "text": "double4x2"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.accelerate/documentation/simd": {
      "abstract": [],
      "identifier": "doc://com.apple.accelerate/documentation/simd",
      "kind": "symbol",
      "role": "collection",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/simd"
    },
    "doc://com.apple.accelerate/documentation/simd/double4x2": {
      "abstract": [
        {
          "text": "A type alias for a double-precision 4 x 2 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "double4x2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/double4x2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "double4x2"
        }
      ],
      "role": "symbol",
      "title": "double4x2",
      "type": "topic",
      "url": "/documentation/simd/double4x2"
    },
    "doc://com.apple.accelerate/documentation/simd/double4x4": {
      "abstract": [
        {
          "text": "A type alias for a double-precision 4 x 4 matrix.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "double4x4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/double4x4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "double4x4"
        }
      ],
      "role": "symbol",
      "title": "double4x4",
      "type": "topic",
      "url": "/documentation/simd/double4x4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x2": {
      "abstract": [
        {
          "text": "A matrix of four columns and two rows that contains double-precision values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_double4x2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_double4x2"
        }
      ],
      "role": "symbol",
      "title": "simd_double4x2",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_double4x2/*(_:_:)-8tpc2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "*"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@simd_double4x2",
          "text": "simd_double4x2"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd9double4x4a",
          "text": "double4x4"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:4simd9double4x2a",
          "text": "double4x2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_double4x2/*(_:_:)-8tpc2",
      "kind": "symbol",
      "role": "symbol",
      "title": "*(_:_:)",
      "type": "topic",
      "url": "/documentation/simd/simd_double4x2/*(_:_:)-8tpc2"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x2/title",
          "value": "simd_double4x2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double4x2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_double4x2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_double4x2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/simd/simd_double4x2/*(_:_:)-8tpc2"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
