{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isBusy"},{"kind":"text","text":"() -> "},{"identifier":"doc://com.externally.resolved.symbol/s:Sb","kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]}],"kind":"declarations"},{"content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Success or failure code."}]}],"kind":"content"},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"Discussion"},{"inlineContent":[{"type":"text","text":"OBEXFileTransferServices will be considered “busy” when an operation in taking place or has not completed. Calling abort: on this module will not automatically reset its busy state. The user will have to wait for the operation to complete or for the current operation to timeout."}],"type":"paragraph"}],"kind":"content"}],"sections":[],"abstract":[{"text":"Get the action state of the module","type":"text"}],"metadata":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isBusy"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"modules":[{"name":"IOBluetooth"}],"navigatorTitle":[{"kind":"identifier","text":"isBusy"}],"platforms":[{"deprecated":false,"unavailable":false,"name":"macOS","beta":false}],"roleHeading":"Instance Method","title":"isBusy()","externalID":"c:objc(cs)OBEXFileTransferServices(im)isBusy","symbolKind":"method"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.iobluetooth/documentation/IOBluetooth","doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXFileTransferServices"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/iobluetooth/obexfiletransferservices/isbusy()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/iobluetooth/obexfiletransferservices/isbusy()"]}],"identifier":{"url":"doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXFileTransferServices/isBusy()","interfaceLanguage":"swift"},"references":{"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXFileTransferServices":{"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"OBEXFileTransferServices","kind":"identifier"}],"title":"OBEXFileTransferServices","url":"/documentation/iobluetooth/obexfiletransferservices","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OBEXFileTransferServices","kind":"identifier"}],"abstract":[{"text":"Implements advanced OBEX operations in addition to simple PUT and GET.","type":"text"}],"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXFileTransferServices"},"doc://com.externally.resolved.symbol/s:Sb":{"url":"/documentation/Swift/Bool","role":"symbol","title":"Bool","type":"topic","fragments":[{"kind":"attribute","text":"@frozen"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Bool"}],"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/s:Sb","abstract":[{"type":"text","text":"A value type whose instances are either `true` or `false`."}]},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","role":"symbol","type":"topic","url":"/documentation/objectivec/bool","title":"BOOL","abstract":[{"type":"text","text":"Type to represent a Boolean value."}]},"doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXFileTransferServices/isBusy()":{"kind":"symbol","url":"/documentation/iobluetooth/obexfiletransferservices/isbusy()","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXFileTransferServices/isBusy()","navigatorTitle":[{"text":"isBusy","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isBusy","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isBusy()","role":"symbol","abstract":[{"text":"Get the action state of the module","type":"text"}]},"doc://com.apple.iobluetooth/documentation/IOBluetooth":{"kind":"symbol","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth","abstract":[{"type":"text","text":"Gain user-space access to Bluetooth devices."}],"url":"/documentation/iobluetooth","role":"collection","type":"topic","title":"IOBluetooth"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"replace","value":[{"unavailable":false,"deprecated":false,"name":"macOS","beta":false}],"path":"/metadata/platforms"},{"op":"replace","value":"Instance Method","path":"/metadata/roleHeading"},{"op":"replace","value":"isBusy","path":"/metadata/title"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"- ","kind":"text"},{"text":"isBusy","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.iobluetooth/documentation/IOBluetooth","doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXFileTransferServices"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":null,"op":"add"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isBusy","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"/primaryContentSections/1","value":{"kind":"content","content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"inlineContent":[{"text":"Success or failure code.","type":"text"}],"type":"paragraph"}]},"op":"replace"},{"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXFileTransferServices/title","value":"OBEXFileTransferServices","op":"replace"},{"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXFileTransferServices/fragments","value":[{"text":"OBEXFileTransferServices","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXFileTransferServices/navigatorTitle","value":[{"text":"OBEXFileTransferServices","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXFileTransferServices~1isBusy()/title","value":"isBusy","op":"replace"},{"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXFileTransferServices~1isBusy()/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isBusy"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}