{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/iobluetooth/obexfiletransferservices/msavedcommand"]}],"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"int","preciseIdentifier":"c:I","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mSavedCommand"},{"kind":"text","text":";"}],"platforms":["macOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"identifier","text":"mSavedCommand"}],"modules":[{"name":"IOBluetooth"}],"symbolKind":"ivar","navigatorTitle":[{"kind":"identifier","text":"mSavedCommand"}],"platforms":[{"name":"macOS","deprecated":false,"unavailable":false,"beta":false}],"role":"symbol","title":"mSavedCommand","externalID":"c:objc(cs)OBEXFileTransferServices@mSavedCommand","roleHeading":"Instance Variable"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.iobluetooth/documentation/IOBluetooth","doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXFileTransferServices"]]},"identifier":{"interfaceLanguage":"occ","url":"doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXFileTransferServices/mSavedCommand"},"references":{"doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXFileTransferServices":{"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"OBEXFileTransferServices","kind":"identifier"}],"title":"OBEXFileTransferServices","url":"/documentation/iobluetooth/obexfiletransferservices","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OBEXFileTransferServices","kind":"identifier"}],"abstract":[{"text":"Implements advanced OBEX operations in addition to simple PUT and GET.","type":"text"}],"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXFileTransferServices"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXFileTransferServices/mSavedCommand":{"fragments":[{"kind":"identifier","text":"mSavedCommand"}],"kind":"symbol","role":"symbol","url":"/documentation/iobluetooth/obexfiletransferservices/msavedcommand","type":"topic","title":"mSavedCommand","abstract":[],"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXFileTransferServices/mSavedCommand"},"doc://com.apple.iobluetooth/documentation/IOBluetooth":{"kind":"symbol","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth","abstract":[{"type":"text","text":"Gain user-space access to Bluetooth devices."}],"url":"/documentation/iobluetooth","role":"collection","type":"topic","title":"IOBluetooth"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXFileTransferServices/title","value":"OBEXFileTransferServices","op":"replace"},{"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXFileTransferServices/fragments","value":[{"text":"OBEXFileTransferServices","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXFileTransferServices/navigatorTitle","value":[{"kind":"identifier","text":"OBEXFileTransferServices"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}