{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/iobluetooth/obexfiletransferservices/mweareaborting"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.iobluetooth/documentation/IOBluetooth","doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXFileTransferServices"]]},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"platforms":[{"deprecated":false,"unavailable":false,"beta":false,"name":"macOS"}],"symbolKind":"ivar","navigatorTitle":[{"text":"mWeAreAborting","kind":"identifier"}],"modules":[{"name":"IOBluetooth"}],"title":"mWeAreAborting","role":"symbol","roleHeading":"Instance Variable","externalID":"c:objc(cs)OBEXFileTransferServices@mWeAreAborting","fragments":[{"text":"mWeAreAborting","kind":"identifier"}]},"identifier":{"url":"doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXFileTransferServices/mWeAreAborting","interfaceLanguage":"occ"},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["occ"],"tokens":[{"text":"BOOL","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"mWeAreAborting","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXFileTransferServices":{"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"OBEXFileTransferServices","kind":"identifier"}],"title":"OBEXFileTransferServices","url":"/documentation/iobluetooth/obexfiletransferservices","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OBEXFileTransferServices","kind":"identifier"}],"abstract":[{"text":"Implements advanced OBEX operations in addition to simple PUT and GET.","type":"text"}],"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXFileTransferServices"},"doc://com.apple.iobluetooth/documentation/IOBluetooth":{"kind":"symbol","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth","abstract":[{"type":"text","text":"Gain user-space access to Bluetooth devices."}],"url":"/documentation/iobluetooth","role":"collection","type":"topic","title":"IOBluetooth"},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies"},"doc://com.externally.resolved.symbol/c:@T@BOOL":{"kind":"symbol","identifier":"doc://com.externally.resolved.symbol/c:@T@BOOL","role":"symbol","type":"topic","url":"/documentation/objectivec/bool","title":"BOOL","abstract":[{"type":"text","text":"Type to represent a Boolean value."}]},"doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXFileTransferServices/mWeAreAborting":{"title":"mWeAreAborting","type":"topic","kind":"symbol","url":"/documentation/iobluetooth/obexfiletransferservices/mweareaborting","role":"symbol","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXFileTransferServices/mWeAreAborting","abstract":[],"fragments":[{"text":"mWeAreAborting","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXFileTransferServices/title","op":"replace","value":"OBEXFileTransferServices"},{"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXFileTransferServices/fragments","op":"replace","value":[{"text":"OBEXFileTransferServices","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXFileTransferServices/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"OBEXFileTransferServices"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}