{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Instance Method","title":"sendFile(_:)","modules":[{"name":"IOBluetooth"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendFile"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"!) -> "},{"preciseIdentifier":"c:@T@OBEXError","kind":"typeIdentifier","text":"OBEXError"}],"platforms":[{"deprecated":false,"name":"macOS","unavailable":false,"beta":false}],"navigatorTitle":[{"kind":"identifier","text":"sendFile:"}],"externalID":"c:objc(cs)OBEXFileTransferServices(im)sendFile:","symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/iobluetooth/obexfiletransferservices/sendfile(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/iobluetooth/obexfiletransferservices/sendfile(_:)"]}],"abstract":[{"type":"text","text":"Put a local file to the remote target"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.iobluetooth/documentation/IOBluetooth","doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXFileTransferServices"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendFile"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"inLocalPathAndName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS","identifier":"doc://com.externally.resolved.symbol/s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"OBEXError","preciseIdentifier":"c:@T@OBEXError","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXError"}],"languages":["swift"],"platforms":["macOS"]}]},{"kind":"parameters","parameters":[{"name":"inLocalPathAndName","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The name and path of the file to be sent an instance of OBEXFilePut."}]}]}]},{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"kOBEXSuccess, kOBEXSessionBusyError, or kOBEXBadArgumentError initially. Further results returned through the fileTransferServicesSendComplete: and fileTransferServicesSendProgress: delegate methods if initially successful."}],"type":"paragraph"}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Equivalent to ‘mv inLocalFilePath remoteCurrentPath’.","type":"text"}]}]}],"sections":[],"identifier":{"url":"doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXFileTransferServices/sendFile(_:)","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.externally.resolved.symbol/s:SS":{"type":"topic","identifier":"doc://com.externally.resolved.symbol/s:SS","title":"String","role":"symbol","kind":"symbol","url":"/documentation/Swift/String","fragments":[{"kind":"attribute","text":"@frozen"},{"text":" ","kind":"text"},{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"String"}],"abstract":[{"type":"text","text":"A Unicode string value that is a collection of characters."}]},"doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXFileTransferServices/sendFile(_:)":{"url":"/documentation/iobluetooth/obexfiletransferservices/sendfile(_:)","abstract":[{"type":"text","text":"Put a local file to the remote target"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendFile"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"OBEXError","preciseIdentifier":"c:@T@OBEXError"}],"navigatorTitle":[{"kind":"identifier","text":"sendFile:"}],"title":"sendFile(_:)","type":"topic","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXFileTransferServices/sendFile(_:)","kind":"symbol"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXFileTransferServices":{"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"OBEXFileTransferServices","kind":"identifier"}],"title":"OBEXFileTransferServices","url":"/documentation/iobluetooth/obexfiletransferservices","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OBEXFileTransferServices","kind":"identifier"}],"abstract":[{"text":"Implements advanced OBEX operations in addition to simple PUT and GET.","type":"text"}],"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXFileTransferServices"},"doc://com.apple.iobluetooth/documentation/IOBluetooth":{"kind":"symbol","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth","abstract":[{"type":"text","text":"Gain user-space access to Bluetooth devices."}],"url":"/documentation/iobluetooth","role":"collection","type":"topic","title":"IOBluetooth"},"doc://com.externally.resolved.symbol/c:objc(cs)NSString":{"kind":"symbol","url":"/documentation/foundation/nsstring","title":"NSString","abstract":[{"text":"A static, plain-text Unicode string object which you use when you need reference semantics or other Foundation-specific behavior. ","type":"text"}],"type":"topic","role":"symbol","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","fragments":[{"kind":"text","text":"class "},{"kind":"identifier","text":"NSString"}]},"doc://com.apple.documentation/documentation/technologies":{"type":"topic","kind":"technologies","abstract":[{"type":"text","text":""}],"url":"/documentation/technologies","role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","title":"Technologies"},"doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXError":{"identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXError","title":"OBEXError","abstract":[{"text":"Codes for OBEX errors. If the return value was not in the following range, then it is most likely resulting from kernel code/IOKit, and you should consult IOReturn.h for those codes.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"OBEXError","kind":"identifier"}],"url":"/documentation/iobluetooth/obexerror","role":"symbol","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OBEXError","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"name":"macOS","beta":false,"unavailable":false,"deprecated":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Instance Method"},{"path":"/metadata/title","op":"replace","value":"sendFile:"},{"path":"/metadata/symbolKind","op":"replace","value":"method"},{"path":"/metadata/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"sendFile:","kind":"identifier"}]},{"path":"/hierarchy","op":"replace","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.iobluetooth/documentation/IOBluetooth","doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXFileTransferServices"]]}},{"path":"/topicSections","op":"add","value":null},{"path":"/relationshipsSections","op":"add","value":null},{"path":"/seeAlsoSections","op":"add","value":null},{"path":"/primaryContentSections/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["macOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"OBEXError","kind":"typeIdentifier","identifier":"doc://com.apple.iobluetooth/documentation/IOBluetooth/OBEXError","preciseIdentifier":"c:@T@OBEXError"},{"text":") ","kind":"text"},{"text":"sendFile:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","identifier":"doc://com.externally.resolved.symbol/c:objc(cs)NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"inLocalPathAndName"},{"kind":"text","text":";"}]}]}},{"path":"/primaryContentSections/1","value":{"kind":"parameters","parameters":[{"name":"inLocalPathAndName","content":[{"inlineContent":[{"text":"The name and path of the file to be sent an instance of OBEXFilePut.","type":"text"}],"type":"paragraph"}]}]},"op":"replace"},{"path":"/primaryContentSections/2","op":"replace","value":{"content":[{"level":2,"type":"heading","anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"kOBEXSuccess, kOBEXSessionBusyError, or kOBEXBadArgumentError initially. Further results returned through the fileTransferServicesSendComplete: and fileTransferServicesSendProgress: delegate methods if initially successful."}]}],"kind":"content"}},{"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXFileTransferServices~1sendFile(_:)/title","value":"sendFile:","op":"replace"},{"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXFileTransferServices~1sendFile(_:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"sendFile:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXFileTransferServices/title","value":"OBEXFileTransferServices","op":"replace"},{"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXFileTransferServices/fragments","value":[{"kind":"identifier","text":"OBEXFileTransferServices"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXFileTransferServices/navigatorTitle","value":[{"text":"OBEXFileTransferServices","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSString/abstract","value":[{"type":"text","text":"A static, plain-text Unicode string object."}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXError/title","value":"OBEXError","op":"replace"},{"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXError/fragments","value":[{"text":"OBEXError","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"OBEXError"}],"path":"/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1OBEXError/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}