{
  "abstract": [
    {
      "text": "An object that creates images from SwiftUI views.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.SwiftUI/documentation/SwiftUI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:7SwiftUI13ImageRendererC",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "ImageRenderer"
      }
    ],
    "modules": [
      {
        "name": "SwiftUI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "ImageRenderer"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "16.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "ImageRenderer"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "final"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "ImageRenderer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "kind": "genericParameter",
              "text": "Content"
            },
            {
              "kind": "text",
              "text": "> "
            },
            {
              "kind": "keyword",
              "text": "where"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "text": "Content"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:7SwiftUI4ViewP",
              "text": "View"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use ",
              "type": "text"
            },
            {
              "code": "ImageRenderer",
              "type": "codeVoice"
            },
            {
              "text": " to export bitmap image data from a SwiftUI view. You",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "initialize the renderer with a view, then render images on demand,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "either by calling the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer/render(rasterizationScale:renderer:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method, or",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "by using the renderer’s properties to create a",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/coregraphics/cgimage",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ",",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppKit/NSImage",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", or",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/UIKit/UIImage",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "By drawing to a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/Canvas",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and exporting with an ",
              "type": "text"
            },
            {
              "code": "ImageRenderer",
              "type": "codeVoice"
            },
            {
              "text": ",",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "you can generate images from any progammatically-rendered content, like",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "paths, shapes, gradients, and more. You can also render standard SwiftUI",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "views like ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/Text",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " views, or containers of multiple view types.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following example uses a private ",
              "type": "text"
            },
            {
              "code": "createAwardView(forUser:date:)",
              "type": "codeVoice"
            },
            {
              "text": " method",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to create a game app’s view of a trophy symbol with a user name and date.",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "This view combines a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/Canvas",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " that applies a shadow filter with",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "two ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/Text",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " views into a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/VStack",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". A ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/Button",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " allows the person to",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "save this view. The button’s action uses an ",
              "type": "text"
            },
            {
              "code": "ImageRenderer",
              "type": "codeVoice"
            },
            {
              "text": " to rasterize a",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "code": "CGImage",
              "type": "codeVoice"
            },
            {
              "text": " and then calls a private ",
              "type": "text"
            },
            {
              "code": "uploadAchievementImage(_:)",
              "type": "codeVoice"
            },
            {
              "text": " method to",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "encode and upload the image.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "var body: some View {",
            "    let trophyAndDate = createAwardView(forUser: playerName,",
            "                                         date: achievementDate)",
            "    VStack {",
            "        trophyAndDate",
            "        Button(\"Save Achievement\") {",
            "            let renderer = ImageRenderer(content: trophyAndDate)",
            "            if let image = renderer.cgImage {",
            "                uploadAchievementImage(image)",
            "            }",
            "        }",
            "    }",
            "}",
            "",
            "private func createAwardView(forUser: String, date: Date) -> some View {",
            "    VStack {",
            "        Image(systemName: \"trophy\")",
            "            .resizable()",
            "            .frame(width: 200, height: 200)",
            "            .frame(maxWidth: .infinity, maxHeight: .infinity)",
            "            .shadow(color: .mint, radius: 5)",
            "        Text(playerName)",
            "            .font(.largeTitle)",
            "        Text(achievementDate.formatted())",
            "    }",
            "    .multilineTextAlignment(.center)",
            "    .frame(width: 200, height: 290)",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "identifier": "ImageRenderer-1",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Because ",
              "type": "text"
            },
            {
              "code": "ImageRenderer",
              "type": "codeVoice"
            },
            {
              "text": " conforms to",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/Combine/ObservableObject",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", you",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "can use it to produce a stream of images as its properties change. Subscribe",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to the renderer’s ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer/objectWillChange",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " publisher, then use the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "renderer to rasterize a new image each time the subscriber receives an",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "update.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "code": "ImageRenderer",
                  "type": "codeVoice"
                },
                {
                  "text": " output only includes views that SwiftUI renders,",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "such as text, images, shapes, and composite views of these types. It",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "does not render views provided by native platform frameworks (AppKit and",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "UIKit) such as web views, media players, and some controls. For these views,",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "code": "ImageRenderer",
                  "type": "codeVoice"
                },
                {
                  "text": " displays a placeholder image, similar to the behavior of",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View/drawingGroup(opaque:colorMode:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        },
        {
          "anchor": "Rendering-to-a-PDF-context",
          "level": 3,
          "text": "Rendering to a PDF context",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer/render(rasterizationScale:renderer:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method renders the specified",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "view to any",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/coregraphics/cgcontext",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". That",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "means you aren’t limited to creating a rasterized ",
              "type": "text"
            },
            {
              "code": "CGImage",
              "type": "codeVoice"
            },
            {
              "text": ". For",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "example, you can generate PDF data by rendering to a PDF context. The",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "resulting PDF maintains resolution-independence for supported members of the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "view hierarchy, such as text, symbol images, lines, shapes, and fills.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The following example uses the ",
              "type": "text"
            },
            {
              "code": "createAwardView(forUser:date:)",
              "type": "codeVoice"
            },
            {
              "text": " method from",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the previous example, and exports its contents as an 800-by-600 point PDF to",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "the file URL ",
              "type": "text"
            },
            {
              "code": "renderURL",
              "type": "codeVoice"
            },
            {
              "text": ". It uses the ",
              "type": "text"
            },
            {
              "code": "size",
              "type": "codeVoice"
            },
            {
              "text": " parameter sent to the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "rendering closure to center the ",
              "type": "text"
            },
            {
              "code": "trophyAndDate",
              "type": "codeVoice"
            },
            {
              "text": " view vertically and",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "horizontally on the page.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "var body: some View {",
            "    let trophyAndDate = createAwardView(forUser: playerName,",
            "                                        date: achievementDate)",
            "    VStack {",
            "        trophyAndDate",
            "        Button(\"Save Achievement\") {",
            "            let renderer = ImageRenderer(content: trophyAndDate)",
            "            renderer.render { size, renderer in",
            "                var mediaBox = CGRect(origin: .zero,",
            "                                      size: CGSize(width: 800, height: 600))",
            "                guard let consumer = CGDataConsumer(url: renderURL as CFURL),",
            "                      let pdfContext =  CGContext(consumer: consumer,",
            "                                                  mediaBox: &mediaBox, nil)",
            "                else {",
            "                    return",
            "                }",
            "                pdfContext.beginPDFPage(nil)",
            "                pdfContext.translateBy(x: mediaBox.size.width / 2 - size.width / 2,",
            "                                       y: mediaBox.size.height / 2 - size.height / 2)",
            "                renderer(pdfContext)",
            "                pdfContext.endPDFPage()",
            "                pdfContext.closePDF()",
            "            }",
            "        }",
            "    }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "anchor": "Creating-an-image-from-drawing-instructions",
          "level": 3,
          "text": "Creating an image from drawing instructions",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "code": "ImageRenderer",
              "type": "codeVoice"
            },
            {
              "text": " makes it possible to create a custom image by drawing into a",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/Canvas",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", rendering a ",
              "type": "text"
            },
            {
              "code": "CGImage",
              "type": "codeVoice"
            },
            {
              "text": " from it, and using that to initialize an",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/Image",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". To simplify this process, use the ",
              "type": "text"
            },
            {
              "code": "Image",
              "type": "codeVoice"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "initializer ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/Image/init(size:label:opaque:colorMode:renderer:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", which",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "takes a closure whose argument is a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/GraphicsContext",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " that you can",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "directly draw into.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "ImageRenderer-1": {
      "alt": "A large trophy symbol, drawn with a mint-colored shadow. Below this, a",
      "identifier": "ImageRenderer-1",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/a3dc31cb9f305a02b0b44e7d8e4693e8/ImageRenderer-1@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/adf9ab2d011929a4254c001a4b4c3762/ImageRenderer-1~dark@2x.png"
        }
      ]
    },
    "SwiftUI-PageImage-card.png": {
      "alt": "A black Swift logo on a swirly blue and purple background.",
      "identifier": "SwiftUI-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/b1de0de086f81a5d0eac3839a0af6e6f/SwiftUI-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/1450d0b30a6b024e10c148e3f31dafe9/SwiftUI-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI": {
      "abstract": [
        {
          "text": "Declare the user interface and behavior for your app on every platform.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI",
      "images": [
        {
          "identifier": "SwiftUI-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "SwiftUI",
      "type": "topic",
      "url": "/documentation/swiftui"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/Button": {
      "abstract": [
        {
          "text": "A control that initiates an action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Button"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/Button",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Button"
        }
      ],
      "role": "symbol",
      "title": "Button",
      "type": "topic",
      "url": "/documentation/swiftui/button"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/Canvas": {
      "abstract": [
        {
          "text": "A view type that supports immediate mode drawing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Canvas"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/Canvas",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Canvas"
        }
      ],
      "role": "symbol",
      "title": "Canvas",
      "type": "topic",
      "url": "/documentation/swiftui/canvas"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/GraphicsContext": {
      "abstract": [
        {
          "text": "An immediate mode drawing destination, and its current state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GraphicsContext"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/GraphicsContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GraphicsContext"
        }
      ],
      "role": "symbol",
      "title": "GraphicsContext",
      "type": "topic",
      "url": "/documentation/swiftui/graphicscontext"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/Image": {
      "abstract": [
        {
          "text": "A view that displays an image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Image"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/Image",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Image"
        }
      ],
      "role": "symbol",
      "title": "Image",
      "type": "topic",
      "url": "/documentation/swiftui/image"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/Image/init(size:label:opaque:colorMode:renderer:)": {
      "abstract": [
        {
          "text": "Initializes an image of the given size, with contents provided by a",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "custom rendering closure.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "size"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "label"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4TextV",
          "text": "Text"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "externalParam",
          "text": "opaque"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "colorMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI18ColorRenderingModeO",
          "text": "ColorRenderingMode"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "renderer"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "keyword",
          "text": "inout"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI15GraphicsContextV",
          "text": "GraphicsContext"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/Image/init(size:label:opaque:colorMode:renderer:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(size:label:opaque:colorMode:renderer:)",
      "type": "topic",
      "url": "/documentation/swiftui/image/init(size:label:opaque:colormode:renderer:)"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer": {
      "abstract": [
        {
          "text": "An object that creates images from SwiftUI views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ImageRenderer"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ImageRenderer"
        }
      ],
      "role": "symbol",
      "title": "ImageRenderer",
      "type": "topic",
      "url": "/documentation/swiftui/imagerenderer"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer/cgImage": {
      "abstract": [
        {
          "text": "The current contents of the view, rasterized as a Core Graphics image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cgImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGImageRef",
          "text": "CGImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer/cgImage",
      "kind": "symbol",
      "role": "symbol",
      "title": "cgImage",
      "type": "topic",
      "url": "/documentation/swiftui/imagerenderer/cgimage"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer/colorMode": {
      "abstract": [
        {
          "text": "The working color space and storage format of the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "colorMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI18ColorRenderingModeO",
          "text": "ColorRenderingMode"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer/colorMode",
      "kind": "symbol",
      "role": "symbol",
      "title": "colorMode",
      "type": "topic",
      "url": "/documentation/swiftui/imagerenderer/colormode"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer/content": {
      "abstract": [
        {
          "text": "The root view rendered by this image renderer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "content"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer/content",
      "kind": "symbol",
      "role": "symbol",
      "title": "content",
      "type": "topic",
      "url": "/documentation/swiftui/imagerenderer/content"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer/init(content:)": {
      "abstract": [
        {
          "text": "Creates a renderer object with a source content view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "content"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer/init(content:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(content:)",
      "type": "topic",
      "url": "/documentation/swiftui/imagerenderer/init(content:)"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer/isObservationEnabled": {
      "abstract": [
        {
          "text": "If observers of this observed object should be notified when the",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "produced image changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isObservationEnabled"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer/isObservationEnabled",
      "kind": "symbol",
      "role": "symbol",
      "title": "isObservationEnabled",
      "type": "topic",
      "url": "/documentation/swiftui/imagerenderer/isobservationenabled"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer/isOpaque": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the alpha channel of the image is",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "fully opaque.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isOpaque"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer/isOpaque",
      "kind": "symbol",
      "role": "symbol",
      "title": "isOpaque",
      "type": "topic",
      "url": "/documentation/swiftui/imagerenderer/isopaque"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer/nsImage": {
      "abstract": [
        {
          "text": "The current contents of the view, rasterized as an AppKit image.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Content",
            "type": "codeVoice"
          },
          {
            "text": " conforms to ",
            "type": "text"
          },
          {
            "code": "View",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "nsImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSImage",
          "text": "NSImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer/nsImage",
      "kind": "symbol",
      "role": "symbol",
      "title": "nsImage",
      "type": "topic",
      "url": "/documentation/swiftui/imagerenderer/nsimage"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer/objectWillChange": {
      "abstract": [
        {
          "text": "A publisher that informs subscribers of changes to the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "objectWillChange"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7Combine18PassthroughSubjectC",
          "text": "PassthroughSubject"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5NeverO",
          "text": "Never"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer/objectWillChange",
      "kind": "symbol",
      "role": "symbol",
      "title": "objectWillChange",
      "type": "topic",
      "url": "/documentation/swiftui/imagerenderer/objectwillchange"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer/proposedSize": {
      "abstract": [
        {
          "text": "The size proposed to the root view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "proposedSize"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI16ProposedViewSizeV",
          "text": "ProposedViewSize"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer/proposedSize",
      "kind": "symbol",
      "role": "symbol",
      "title": "proposedSize",
      "type": "topic",
      "url": "/documentation/swiftui/imagerenderer/proposedsize"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer/render(rasterizationScale:renderer:)": {
      "abstract": [
        {
          "text": "Draws the renderer’s current contents to an arbitrary Core Graphics",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "render"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rasterizationScale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "renderer"
        },
        {
          "kind": "text",
          "text": ": ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": ", ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGContextRef",
          "text": "CGContext"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer/render(rasterizationScale:renderer:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "render(rasterizationScale:renderer:)",
      "type": "topic",
      "url": "/documentation/swiftui/imagerenderer/render(rasterizationscale:renderer:)"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer/scale": {
      "abstract": [
        {
          "text": "The scale at which to render the image.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scale"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer/scale",
      "kind": "symbol",
      "role": "symbol",
      "title": "scale",
      "type": "topic",
      "url": "/documentation/swiftui/imagerenderer/scale"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer/uiImage": {
      "abstract": [
        {
          "text": "The current contents of the view, rasterized as a UIKit image.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Content",
            "type": "codeVoice"
          },
          {
            "text": " conforms to ",
            "type": "text"
          },
          {
            "code": "View",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uiImage"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIImage",
          "text": "UIImage"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer/uiImage",
      "kind": "symbol",
      "role": "symbol",
      "title": "uiImage",
      "type": "topic",
      "url": "/documentation/swiftui/imagerenderer/uiimage"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/Text": {
      "abstract": [
        {
          "text": "A view that displays one or more lines of read-only text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Text"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/Text",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Text"
        }
      ],
      "role": "symbol",
      "title": "Text",
      "type": "topic",
      "url": "/documentation/swiftui/text"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/VStack": {
      "abstract": [
        {
          "text": "A view that arranges its subviews in a vertical line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "VStack"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/VStack",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "VStack"
        }
      ],
      "role": "symbol",
      "title": "VStack",
      "type": "topic",
      "url": "/documentation/swiftui/vstack"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/View": {
      "abstract": [
        {
          "text": "A type that represents part of your app’s user interface and provides",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "modifiers that you use to configure views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "View"
        }
      ],
      "role": "symbol",
      "title": "View",
      "type": "topic",
      "url": "/documentation/swiftui/view"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/View/drawingGroup(opaque:colorMode:)": {
      "abstract": [
        {
          "text": "Composites this view’s contents into an offscreen image before final",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "drawingGroup"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "opaque"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "colorMode"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI18ColorRenderingModeO",
          "text": "ColorRenderingMode"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "keyword",
          "text": "some"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View/drawingGroup(opaque:colorMode:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "drawingGroup(opaque:colorMode:)",
      "type": "topic",
      "url": "/documentation/swiftui/view/drawinggroup(opaque:colormode:)"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSImage": {
      "abstract": [
        {
          "text": "A high-level interface for manipulating image data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSImage"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSImage",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSImage",
      "type": "topic",
      "url": "/documentation/AppKit/NSImage"
    },
    "doc://com.apple.documentation/documentation/Combine/ObservableObject": {
      "abstract": [
        {
          "text": "A type of object with a publisher that emits before the object has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ObservableObject"
        },
        {
          "kind": "text",
          "text": " : AnyObject"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/Combine/ObservableObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "ObservableObject",
      "type": "topic",
      "url": "/documentation/Combine/ObservableObject"
    },
    "doc://com.apple.documentation/documentation/UIKit/UIImage": {
      "abstract": [
        {
          "text": "An object that manages image data in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIImage"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/UIImage",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIImage",
      "type": "topic",
      "url": "/documentation/UIKit/UIImage"
    },
    "doc://com.apple.documentation/documentation/coregraphics/cgcontext": {
      "abstract": [
        {
          "text": "A Quartz 2D drawing environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CGContext"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/coregraphics/cgcontext",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGContext",
      "type": "topic",
      "url": "/documentation/coregraphics/cgcontext"
    },
    "doc://com.apple.documentation/documentation/coregraphics/cgimage": {
      "abstract": [
        {
          "text": "A bitmap image or image mask.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CGImage"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/coregraphics/cgimage",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGImage",
      "type": "topic",
      "url": "/documentation/coregraphics/cgimage"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:11Observation10ObservableP": {
      "abstract": [
        {
          "text": "A type that emits notifications to observers when underlying data changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Observable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:11Observation10ObservableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Observable",
      "type": "topic",
      "url": "/documentation/Observation/Observable"
    },
    "doc://com.externally.resolved.symbol/s:7Combine16ObservableObjectP": {
      "abstract": [
        {
          "text": "A type of object with a publisher that emits before the object has changed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ObservableObject"
        },
        {
          "kind": "text",
          "text": " : AnyObject"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:7Combine16ObservableObjectP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ObservableObject",
      "type": "topic",
      "url": "/documentation/Combine/ObservableObject"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:11Observation10ObservableP",
        "doc://com.externally.resolved.symbol/s:7Combine16ObservableObjectP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Creating-an-image-renderer",
      "identifiers": [
        "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer/init(content:)"
      ],
      "title": "Creating an image renderer"
    },
    {
      "anchor": "Providing-the-source-view",
      "identifiers": [
        "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer/content"
      ],
      "title": "Providing the source view"
    },
    {
      "anchor": "Accessing-renderer-properties",
      "identifiers": [
        "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer/proposedSize",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer/scale",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer/isOpaque",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer/colorMode"
      ],
      "title": "Accessing renderer properties"
    },
    {
      "anchor": "Rendering-images",
      "identifiers": [
        "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer/render(rasterizationScale:renderer:)",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer/cgImage",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer/nsImage",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer/uiImage"
      ],
      "title": "Rendering images"
    },
    {
      "anchor": "Producing-a-stream-of-images",
      "identifiers": [
        "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer/objectWillChange"
      ],
      "title": "Producing a stream of images"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.SwiftUI/documentation/SwiftUI/ImageRenderer/isObservationEnabled"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1coregraphics~1cgimage/title",
          "value": "CGImageRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1coregraphics~1cgcontext/title",
          "value": "CGContextRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1UIKit~1UIImage/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIImage"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSImage/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSImage"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/swiftui/imagerenderer"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
