{
  "abstract": [
    {
      "text": "A wrapper that you use to integrate an AppKit view into your SwiftUI view",
      "type": "text"
    },
    {
      "text": " ",
      "type": "text"
    },
    {
      "text": "hierarchy.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.SwiftUI/documentation/SwiftUI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewRepresentable"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:7SwiftUI19NSViewRepresentableP",
    "fragments": [
      {
        "kind": "keyword",
        "text": "protocol"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "NSViewRepresentable"
      }
    ],
    "modules": [
      {
        "name": "SwiftUI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "NSViewRepresentable"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.15",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Protocol",
    "symbolKind": "protocol",
    "title": "NSViewRepresentable"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "attribute",
              "text": "@preconcurrency"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSViewRepresentable"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:7SwiftUI4ViewP",
              "text": "View"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "where"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "text": "Self"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View/Body-swift.associatedtype",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:7SwiftUI4ViewP4BodyQa",
              "text": "Body"
            },
            {
              "kind": "text",
              "text": " == "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5NeverO",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5NeverO",
              "text": "Never"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use an ",
              "type": "text"
            },
            {
              "code": "NSViewRepresentable",
              "type": "codeVoice"
            },
            {
              "text": " instance to create and manage an",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/AppKit/NSView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object in your SwiftUI",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "interface. Adopt this protocol in one of your app’s custom instances, and",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "use its methods to create, update, and tear down your view. The creation and",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "update processes parallel the behavior of SwiftUI views, and you use them to",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "configure your view with your app’s current state information. Use the",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "teardown process to remove your view cleanly from your SwiftUI. For example,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "you might use the teardown process to notify other objects that the view is",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "disappearing.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "To add your view into your SwiftUI interface, create your",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewRepresentable",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " instance and add it to your SwiftUI interface. The",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "system calls the methods of your representable instance at appropriate times",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "to create and update the view. The following example shows the inclusion of",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "a custom ",
              "type": "text"
            },
            {
              "code": "MyRepresentedCustomView",
              "type": "codeVoice"
            },
            {
              "text": " struct in the view hierarchy.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "code": [
            "struct ContentView: View {",
            "   var body: some View {",
            "      VStack {",
            "         Text(\"Global Sales\")",
            "         MyRepresentedCustomView()",
            "      }",
            "   }",
            "}"
          ],
          "syntax": "swift",
          "type": "codeListing"
        },
        {
          "inlineContent": [
            {
              "text": "The system doesn’t automatically communicate changes occurring within your",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "view controller to other parts of your SwiftUI interface. When you want your",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "view controller to coordinate with other SwiftUI views, you must provide a",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewControllerRepresentable/Coordinator",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object to facilitate those",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "interactions. For example, you use a coordinator to forward target-action",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and delegate messages from your view controller to any SwiftUI views.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "SwiftUI fully controls the layout of the AppKit view using the view’s",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/AppKit/NSView/frame",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " and",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/AppKit/NSView/bounds",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "properties. Don’t directly set these layout-related properties on the view",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "managed by an ",
                  "type": "text"
                },
                {
                  "code": "NSViewRepresentable",
                  "type": "codeVoice"
                },
                {
                  "text": " instance from your own",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "code because that conflicts with SwiftUI and results in undefined behavior.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Warning",
          "style": "warning",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "SwiftUI-PageImage-card.png": {
      "alt": "A black Swift logo on a swirly blue and purple background.",
      "identifier": "SwiftUI-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/b1de0de086f81a5d0eac3839a0af6e6f/SwiftUI-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/1450d0b30a6b024e10c148e3f31dafe9/SwiftUI-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI": {
      "abstract": [
        {
          "text": "Declare the user interface and behavior for your app on every platform.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI",
      "images": [
        {
          "identifier": "SwiftUI-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "SwiftUI",
      "type": "topic",
      "url": "/documentation/swiftui"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewControllerRepresentable": {
      "abstract": [
        {
          "text": "A wrapper that you use to integrate an AppKit view controller into your",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "SwiftUI interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSViewControllerRepresentable"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewControllerRepresentable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSViewControllerRepresentable"
        }
      ],
      "role": "symbol",
      "title": "NSViewControllerRepresentable",
      "type": "topic",
      "url": "/documentation/swiftui/nsviewcontrollerrepresentable"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewControllerRepresentable/Coordinator": {
      "abstract": [
        {
          "text": "A type to coordinate with the view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "associatedtype"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Coordinator"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewControllerRepresentable/Coordinator",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "Coordinator",
      "type": "topic",
      "url": "/documentation/swiftui/nsviewcontrollerrepresentable/coordinator"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewControllerRepresentableContext": {
      "abstract": [
        {
          "text": "Contextual information about the state of the system that you use to create",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "and update your AppKit view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSViewControllerRepresentableContext"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewControllerRepresentableContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSViewControllerRepresentableContext"
        }
      ],
      "role": "symbol",
      "title": "NSViewControllerRepresentableContext",
      "type": "topic",
      "url": "/documentation/swiftui/nsviewcontrollerrepresentablecontext"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewRepresentable": {
      "abstract": [
        {
          "text": "A wrapper that you use to integrate an AppKit view into your SwiftUI view",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSViewRepresentable"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewRepresentable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSViewRepresentable"
        }
      ],
      "role": "symbol",
      "title": "NSViewRepresentable",
      "type": "topic",
      "url": "/documentation/swiftui/nsviewrepresentable"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewRepresentable/Context": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Context"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewRepresentable/Context",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Context"
        }
      ],
      "role": "symbol",
      "title": "NSViewRepresentable.Context",
      "type": "topic",
      "url": "/documentation/swiftui/nsviewrepresentable/context"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewRepresentable/Coordinator": {
      "abstract": [
        {
          "text": "A type to coordinate with the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "associatedtype"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Coordinator"
        },
        {
          "kind": "text",
          "text": " = "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewRepresentable/Coordinator",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "Coordinator",
      "type": "topic",
      "url": "/documentation/swiftui/nsviewrepresentable/coordinator"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewRepresentable/LayoutOptions": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LayoutOptions"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewRepresentable/LayoutOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LayoutOptions"
        }
      ],
      "role": "symbol",
      "title": "NSViewRepresentable.LayoutOptions",
      "type": "topic",
      "url": "/documentation/swiftui/nsviewrepresentable/layoutoptions"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewRepresentable/NSViewType": {
      "abstract": [
        {
          "text": "The type of view to present.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "associatedtype"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSViewType"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSView",
          "text": "NSView"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewRepresentable/NSViewType",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "NSViewType",
      "type": "topic",
      "url": "/documentation/swiftui/nsviewrepresentable/nsviewtype"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewRepresentable/dismantleNSView(_:coordinator:)": {
      "abstract": [
        {
          "text": "Cleans up the presented AppKit view (and coordinator) in anticipation of",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "their removal.",
          "type": "text"
        }
      ],
      "defaultImplementations": 1,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dismantleNSView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI19NSViewRepresentableP0C4TypeQa",
          "text": "NSViewType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "coordinator"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI19NSViewRepresentableP11CoordinatorQa",
          "text": "Coordinator"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewRepresentable/dismantleNSView(_:coordinator:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "dismantleNSView(_:coordinator:)",
      "type": "topic",
      "url": "/documentation/swiftui/nsviewrepresentable/dismantlensview(_:coordinator:)"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewRepresentable/makeCoordinator()": {
      "abstract": [
        {
          "text": "Creates the custom instance that you use to communicate changes from",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "your view to other parts of your SwiftUI interface.",
          "type": "text"
        }
      ],
      "defaultImplementations": 1,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeCoordinator"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI19NSViewRepresentableP11CoordinatorQa",
          "text": "Coordinator"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewRepresentable/makeCoordinator()",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "makeCoordinator()",
      "type": "topic",
      "url": "/documentation/swiftui/nsviewrepresentable/makecoordinator()"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewRepresentable/makeNSView(context:)": {
      "abstract": [
        {
          "text": "Creates the view object and configures its initial state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "makeNSView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "context"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI19NSViewRepresentableP7Contexta",
          "text": "Context"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI19NSViewRepresentableP0C4TypeQa",
          "text": "NSViewType"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewRepresentable/makeNSView(context:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "makeNSView(context:)",
      "type": "topic",
      "url": "/documentation/swiftui/nsviewrepresentable/makensview(context:)"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewRepresentable/sizeThatFits(_:nsView:context:)": {
      "abstract": [
        {
          "text": "Given a proposed size, returns the preferred size of the composite view.",
          "type": "text"
        }
      ],
      "defaultImplementations": 1,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sizeThatFits"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI16ProposedViewSizeV",
          "text": "ProposedViewSize"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "nsView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI19NSViewRepresentableP0C4TypeQa",
          "text": "NSViewType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "context"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI19NSViewRepresentableP7Contexta",
          "text": "Context"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewRepresentable/sizeThatFits(_:nsView:context:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "sizeThatFits(_:nsView:context:)",
      "type": "topic",
      "url": "/documentation/swiftui/nsviewrepresentable/sizethatfits(_:nsview:context:)"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewRepresentable/updateNSView(_:context:)": {
      "abstract": [
        {
          "text": "Updates the state of the specified view with new information from",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "SwiftUI.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "updateNSView"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI19NSViewRepresentableP0C4TypeQa",
          "text": "NSViewType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "context"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI19NSViewRepresentableP7Contexta",
          "text": "Context"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewRepresentable/updateNSView(_:context:)",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "updateNSView(_:context:)",
      "type": "topic",
      "url": "/documentation/swiftui/nsviewrepresentable/updatensview(_:context:)"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewRepresentableContext": {
      "abstract": [
        {
          "text": "Contextual information about the state of the system that you use to create",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "and update your AppKit view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSViewRepresentableContext"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewRepresentableContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSViewRepresentableContext"
        }
      ],
      "role": "symbol",
      "title": "NSViewRepresentableContext",
      "type": "topic",
      "url": "/documentation/swiftui/nsviewrepresentablecontext"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/View": {
      "abstract": [
        {
          "text": "A type that represents part of your app’s user interface and provides",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "modifiers that you use to configure views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "View"
        }
      ],
      "role": "symbol",
      "title": "View",
      "type": "topic",
      "url": "/documentation/swiftui/view"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/View/Body-swift.associatedtype": {
      "abstract": [
        {
          "text": "The type of view representing the body of this view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "associatedtype"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Body"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4ViewP",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View/Body-swift.associatedtype",
      "kind": "symbol",
      "required": true,
      "role": "symbol",
      "title": "Body",
      "type": "topic",
      "url": "/documentation/swiftui/view/body-swift.associatedtype"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSView": {
      "abstract": [
        {
          "text": "The infrastructure for drawing, printing, and handling events in an app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSView"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSView",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSView",
      "type": "topic",
      "url": "/documentation/AppKit/NSView"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSView/bounds": {
      "abstract": [
        {
          "text": "The view’s bounds rectangle, which expresses its location and size in its own coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bounds"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSView/bounds",
      "kind": "symbol",
      "role": "symbol",
      "title": "bounds",
      "type": "topic",
      "url": "/documentation/AppKit/NSView/bounds"
    },
    "doc://com.apple.documentation/documentation/AppKit/NSView/frame": {
      "abstract": [
        {
          "text": "The view’s frame rectangle, which defines its position and size in its superview’s coordinate system.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frame"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@NSRect",
          "text": "NSRect"
        },
        {
          "kind": "text",
          "text": " { "
        },
        {
          "kind": "keyword",
          "text": "get"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "set"
        },
        {
          "kind": "text",
          "text": " }"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/AppKit/NSView/frame",
      "kind": "symbol",
      "role": "symbol",
      "title": "frame",
      "type": "topic",
      "url": "/documentation/AppKit/NSView/frame"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s5NeverO": {
      "abstract": [
        {
          "text": "A type that has no values and can’t be constructed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Never"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5NeverO",
      "kind": "symbol",
      "role": "symbol",
      "title": "Never",
      "type": "topic",
      "url": "/documentation/Swift/Never"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.apple.SwiftUI/documentation/SwiftUI/View"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Adding-AppKit-views-to-SwiftUI-view-hierarchies",
      "generated": true,
      "identifiers": [
        "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewRepresentableContext",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewControllerRepresentable",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewControllerRepresentableContext"
      ],
      "title": "Adding AppKit views to SwiftUI view hierarchies"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-and-updating-the-view",
      "identifiers": [
        "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewRepresentable/makeNSView(context:)",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewRepresentable/updateNSView(_:context:)",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewRepresentable/Context",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewRepresentable/NSViewType"
      ],
      "title": "Creating and updating the view"
    },
    {
      "anchor": "Specifying-a-size",
      "identifiers": [
        "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewRepresentable/sizeThatFits(_:nsView:context:)"
      ],
      "title": "Specifying a size"
    },
    {
      "anchor": "Cleaning-up-the-view",
      "identifiers": [
        "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewRepresentable/dismantleNSView(_:coordinator:)"
      ],
      "title": "Cleaning up the view"
    },
    {
      "anchor": "Providing-a-custom-coordinator-object",
      "identifiers": [
        "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewRepresentable/makeCoordinator()",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewRepresentable/Coordinator"
      ],
      "title": "Providing a custom coordinator object"
    },
    {
      "anchor": "Performing-layout",
      "identifiers": [
        "doc://com.apple.SwiftUI/documentation/SwiftUI/NSViewRepresentable/LayoutOptions"
      ],
      "title": "Performing layout"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSView~1frame/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSRect",
              "text": "NSRect"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "frame"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSView/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSView"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSResponder",
              "text": "NSResponder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1AppKit~1NSView~1bounds/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@property"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSRect",
              "text": "NSRect"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "bounds"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/swiftui/nsviewrepresentable"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
