{
  "abstract": [
    {
      "text": "A UIKit view controller that manages a SwiftUI view hierarchy.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.SwiftUI/documentation/SwiftUI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:7SwiftUI19UIHostingControllerC",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "UIHostingController"
      }
    ],
    "modules": [
      {
        "name": "SwiftUI"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UIHostingController"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "UIHostingController"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "attribute",
              "text": "@preconcurrency"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIHostingController"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "kind": "genericParameter",
              "text": "Content"
            },
            {
              "kind": "text",
              "text": "> "
            },
            {
              "kind": "keyword",
              "text": "where"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "text": "Content"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:7SwiftUI4ViewP",
              "text": "View"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Create a ",
              "type": "text"
            },
            {
              "code": "UIHostingController",
              "type": "codeVoice"
            },
            {
              "text": " object when you want to integrate SwiftUI",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "views into a UIKit view hierarchy. At creation time, specify the SwiftUI",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "view you want to use as the root view for this view controller; you can",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "change that view later using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/rootView",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "property. Use the hosting controller like you would any other view",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "controller, by presenting it or embedding it as a child view controller",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "in your interface.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "SwiftUI-PageImage-card.png": {
      "alt": "A black Swift logo on a swirly blue and purple background.",
      "identifier": "SwiftUI-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/b1de0de086f81a5d0eac3839a0af6e6f/SwiftUI-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/1450d0b30a6b024e10c148e3f31dafe9/SwiftUI-PageImage-card~dark@2x.png"
        }
      ]
    },
    "Unifying-your-app-s-animations-PageImage-card.png": {
      "alt": "A conceptual illustration of a disclosure indicator, shown animating frame by frame from its collapsed position to its expanded position.",
      "identifier": "Unifying-your-app-s-animations-PageImage-card.png",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/db26bd6bfe171a450c126a68c3bd92d4/Unifying-your-app-s-animations-PageImage-card@2x.png"
        },
        {
          "traits": [
            "2x",
            "dark"
          ],
          "url": "https://docs-assets.developer.apple.com/published/3559438f813d2163ecacac3918dbff5f/Unifying-your-app-s-animations-PageImage-card~dark@2x.png"
        }
      ]
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI": {
      "abstract": [
        {
          "text": "Declare the user interface and behavior for your app on every platform.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI",
      "images": [
        {
          "identifier": "SwiftUI-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "symbol",
      "role": "collection",
      "title": "SwiftUI",
      "type": "topic",
      "url": "/documentation/swiftui"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingConfiguration": {
      "abstract": [
        {
          "text": "A content configuration suitable for hosting a hierarchy of SwiftUI views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIHostingConfiguration"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingConfiguration",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIHostingConfiguration"
        }
      ],
      "role": "symbol",
      "title": "UIHostingConfiguration",
      "type": "topic",
      "url": "/documentation/swiftui/uihostingconfiguration"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController": {
      "abstract": [
        {
          "text": "A UIKit view controller that manages a SwiftUI view hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIHostingController"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIHostingController"
        }
      ],
      "role": "symbol",
      "title": "UIHostingController",
      "type": "topic",
      "url": "/documentation/swiftui/uihostingcontroller"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/addChild(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "addChild"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/addChild(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "addChild(_:)",
      "type": "topic",
      "url": "/documentation/swiftui/uihostingcontroller/addchild(_:)"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/childForHomeIndicatorAutoHidden": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "childForHomeIndicatorAutoHidden"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/childForHomeIndicatorAutoHidden",
      "kind": "symbol",
      "role": "symbol",
      "title": "childForHomeIndicatorAutoHidden",
      "type": "topic",
      "url": "/documentation/swiftui/uihostingcontroller/childforhomeindicatorautohidden"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/childForScreenEdgesDeferringSystemGestures": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "childForScreenEdgesDeferringSystemGestures"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/childForScreenEdgesDeferringSystemGestures",
      "kind": "symbol",
      "role": "symbol",
      "title": "childForScreenEdgesDeferringSystemGestures",
      "type": "topic",
      "url": "/documentation/swiftui/uihostingcontroller/childforscreenedgesdeferringsystemgestures"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/childForStatusBarHidden": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "childForStatusBarHidden"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/childForStatusBarHidden",
      "kind": "symbol",
      "role": "symbol",
      "title": "childForStatusBarHidden",
      "type": "topic",
      "url": "/documentation/swiftui/uihostingcontroller/childforstatusbarhidden"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/childForStatusBarStyle": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "childForStatusBarStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/childForStatusBarStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "childForStatusBarStyle",
      "type": "topic",
      "url": "/documentation/swiftui/uihostingcontroller/childforstatusbarstyle"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/childViewControllerForPreferredContainerBackgroundStyle": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "childViewControllerForPreferredContainerBackgroundStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/childViewControllerForPreferredContainerBackgroundStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "childViewControllerForPreferredContainerBackgroundStyle",
      "type": "topic",
      "url": "/documentation/swiftui/uihostingcontroller/childviewcontrollerforpreferredcontainerbackgroundstyle"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/didMove(toParent:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "didMove"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "toParent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/didMove(toParent:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "didMove(toParent:)",
      "type": "topic",
      "url": "/documentation/swiftui/uihostingcontroller/didmove(toparent:)"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/init(coder:)": {
      "abstract": [
        {
          "text": "Creates a hosting controller object from the contents of the specified",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "archive.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "coder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCoder",
          "text": "NSCoder"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/init(coder:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(coder:)",
      "type": "topic",
      "url": "/documentation/swiftui/uihostingcontroller/init(coder:)"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/init(coder:rootView:)": {
      "abstract": [
        {
          "text": "Creates a hosting controller object from an archive and the specified",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "SwiftUI view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "coder"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCoder",
          "text": "NSCoder"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "rootView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/init(coder:rootView:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(coder:rootView:)",
      "type": "topic",
      "url": "/documentation/swiftui/uihostingcontroller/init(coder:rootview:)"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/init(rootView:)": {
      "abstract": [
        {
          "text": "Creates a hosting controller object that wraps the specified SwiftUI",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rootView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/init(rootView:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rootView:)",
      "type": "topic",
      "url": "/documentation/swiftui/uihostingcontroller/init(rootview:)"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/isModalInPresentation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "isModalInPresentation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/isModalInPresentation",
      "kind": "symbol",
      "role": "symbol",
      "title": "isModalInPresentation",
      "type": "topic",
      "url": "/documentation/swiftui/uihostingcontroller/ismodalinpresentation"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/keyCommands": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "keyCommands"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIKeyCommand",
          "text": "UIKeyCommand"
        },
        {
          "kind": "text",
          "text": "]?"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/keyCommands",
      "kind": "symbol",
      "role": "symbol",
      "title": "keyCommands",
      "type": "topic",
      "url": "/documentation/swiftui/uihostingcontroller/keycommands"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/loadView()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "loadView"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/loadView()",
      "kind": "symbol",
      "role": "symbol",
      "title": "loadView()",
      "type": "topic",
      "url": "/documentation/swiftui/uihostingcontroller/loadview()"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/preferredContainerBackgroundStyle": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredContainerBackgroundStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIContainerBackgroundStyle",
          "text": "UIContainerBackgroundStyle"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/preferredContainerBackgroundStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "preferredContainerBackgroundStyle",
      "type": "topic",
      "url": "/documentation/swiftui/uihostingcontroller/preferredcontainerbackgroundstyle"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/preferredContentSizeDidChange(forChildContentContainer:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredContentSizeDidChange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forChildContentContainer"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIContentContainer",
          "text": "UIContentContainer"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/preferredContentSizeDidChange(forChildContentContainer:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "preferredContentSizeDidChange(forChildContentContainer:)",
      "type": "topic",
      "url": "/documentation/swiftui/uihostingcontroller/preferredcontentsizedidchange(forchildcontentcontainer:)"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/preferredScreenEdgesDeferringSystemGestures": {
      "abstract": [
        {
          "text": "Sets the screen edge from which you want your gesture to take",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "precedence over the system gesture.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredScreenEdgesDeferringSystemGestures"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIRectEdge",
          "text": "UIRectEdge"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/preferredScreenEdgesDeferringSystemGestures",
      "kind": "symbol",
      "role": "symbol",
      "title": "preferredScreenEdgesDeferringSystemGestures",
      "type": "topic",
      "url": "/documentation/swiftui/uihostingcontroller/preferredscreenedgesdeferringsystemgestures"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/preferredStatusBarStyle": {
      "abstract": [
        {
          "text": "The preferred status bar style for the view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredStatusBarStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIStatusBarStyle",
          "text": "UIStatusBarStyle"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/preferredStatusBarStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "preferredStatusBarStyle",
      "type": "topic",
      "url": "/documentation/swiftui/uihostingcontroller/preferredstatusbarstyle"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/preferredStatusBarUpdateAnimation": {
      "abstract": [
        {
          "text": "The animation style to use when hiding or showing the status bar for",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "this view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredStatusBarUpdateAnimation"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIStatusBarAnimation",
          "text": "UIStatusBarAnimation"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/preferredStatusBarUpdateAnimation",
      "kind": "symbol",
      "role": "symbol",
      "title": "preferredStatusBarUpdateAnimation",
      "type": "topic",
      "url": "/documentation/swiftui/uihostingcontroller/preferredstatusbarupdateanimation"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/preferredUserInterfaceStyle": {
      "abstract": [
        {
          "text": "The preferred interface style for this view controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "preferredUserInterfaceStyle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIUserInterfaceStyle",
          "text": "UIUserInterfaceStyle"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/preferredUserInterfaceStyle",
      "kind": "symbol",
      "role": "symbol",
      "title": "preferredUserInterfaceStyle",
      "type": "topic",
      "url": "/documentation/swiftui/uihostingcontroller/preferreduserinterfacestyle"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/prefersHomeIndicatorAutoHidden": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the view controller prefers the",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "home indicator to be hidden or shown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prefersHomeIndicatorAutoHidden"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/prefersHomeIndicatorAutoHidden",
      "kind": "symbol",
      "role": "symbol",
      "title": "prefersHomeIndicatorAutoHidden",
      "type": "topic",
      "url": "/documentation/swiftui/uihostingcontroller/prefershomeindicatorautohidden"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/prefersStatusBarHidden": {
      "abstract": [
        {
          "text": "A Boolean value that indicates whether the view controller prefers the",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "status bar to be hidden or shown.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "prefersStatusBarHidden"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/prefersStatusBarHidden",
      "kind": "symbol",
      "role": "symbol",
      "title": "prefersStatusBarHidden",
      "type": "topic",
      "url": "/documentation/swiftui/uihostingcontroller/prefersstatusbarhidden"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/rootView": {
      "abstract": [
        {
          "text": "The root view of the SwiftUI view hierarchy managed by this view",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "controller.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rootView"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "text": "Content"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/rootView",
      "kind": "symbol",
      "role": "symbol",
      "title": "rootView",
      "type": "topic",
      "url": "/documentation/swiftui/uihostingcontroller/rootview"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/safeAreaRegions": {
      "abstract": [
        {
          "text": "The safe area regions that this view controller adds to its view.",
          "type": "text"
        }
      ],
      "conformance": {
        "availabilityPrefix": [
          {
            "text": "Available when",
            "type": "text"
          }
        ],
        "conformancePrefix": [
          {
            "text": "Conforms when",
            "type": "text"
          }
        ],
        "constraints": [
          {
            "code": "Content",
            "type": "codeVoice"
          },
          {
            "text": " conforms to ",
            "type": "text"
          },
          {
            "code": "View",
            "type": "codeVoice"
          },
          {
            "text": ".",
            "type": "text"
          }
        ]
      },
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "safeAreaRegions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI15SafeAreaRegionsV",
          "text": "SafeAreaRegions"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/safeAreaRegions",
      "kind": "symbol",
      "role": "symbol",
      "title": "safeAreaRegions",
      "type": "topic",
      "url": "/documentation/swiftui/uihostingcontroller/safearearegions"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/sizeThatFits(in:)": {
      "abstract": [
        {
          "text": "Calculates and returns the most appropriate size for the current view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sizeThatFits"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/sizeThatFits(in:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "sizeThatFits(in:)",
      "type": "topic",
      "url": "/documentation/swiftui/uihostingcontroller/sizethatfits(in:)"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/sizingOptions": {
      "abstract": [
        {
          "text": "The options for how the hosting controller tracks changes to the size",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "of its SwiftUI content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sizingOptions"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI32UIHostingControllerSizingOptionsV",
          "text": "UIHostingControllerSizingOptions"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/sizingOptions",
      "kind": "symbol",
      "role": "symbol",
      "title": "sizingOptions",
      "type": "topic",
      "url": "/documentation/swiftui/uihostingcontroller/sizingoptions"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/target(forAction:withSender:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "target"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "forAction"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10ObjectiveC8SelectorV",
          "text": "Selector"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "withSender"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "keyword",
          "text": "Any"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/target(forAction:withSender:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "target(forAction:withSender:)",
      "type": "topic",
      "url": "/documentation/swiftui/uihostingcontroller/target(foraction:withsender:)"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/undoManager": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "undoManager"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSUndoManager",
          "text": "UndoManager"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/undoManager",
      "kind": "symbol",
      "role": "symbol",
      "title": "undoManager",
      "type": "topic",
      "url": "/documentation/swiftui/uihostingcontroller/undomanager"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/viewDidAppear(_:)": {
      "abstract": [
        {
          "text": "Notifies the view controller that its view has been added to a",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "view hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "viewDidAppear"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/viewDidAppear(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "viewDidAppear(_:)",
      "type": "topic",
      "url": "/documentation/swiftui/uihostingcontroller/viewdidappear(_:)"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/viewDidDisappear(_:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "viewDidDisappear"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/viewDidDisappear(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "viewDidDisappear(_:)",
      "type": "topic",
      "url": "/documentation/swiftui/uihostingcontroller/viewdiddisappear(_:)"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/viewWillAppear(_:)": {
      "abstract": [
        {
          "text": "Notifies the view controller that its view is about to be added to a",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "view hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "viewWillAppear"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/viewWillAppear(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "viewWillAppear(_:)",
      "type": "topic",
      "url": "/documentation/swiftui/uihostingcontroller/viewwillappear(_:)"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/viewWillDisappear(_:)": {
      "abstract": [
        {
          "text": "Notifies the view controller that its view will be removed from a",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "view hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "viewWillDisappear"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/viewWillDisappear(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "viewWillDisappear(_:)",
      "type": "topic",
      "url": "/documentation/swiftui/uihostingcontroller/viewwilldisappear(_:)"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/viewWillLayoutSubviews()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "viewWillLayoutSubviews"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/viewWillLayoutSubviews()",
      "kind": "symbol",
      "role": "symbol",
      "title": "viewWillLayoutSubviews()",
      "type": "topic",
      "url": "/documentation/swiftui/uihostingcontroller/viewwilllayoutsubviews()"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/viewWillTransition(to:with:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "viewWillTransition"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "to"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": any "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)UIViewControllerTransitionCoordinator",
          "text": "UIViewControllerTransitionCoordinator"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/viewWillTransition(to:with:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "viewWillTransition(to:with:)",
      "type": "topic",
      "url": "/documentation/swiftui/uihostingcontroller/viewwilltransition(to:with:)"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/willMove(toParent:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "willMove"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "toParent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": "?)"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/willMove(toParent:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "willMove(toParent:)",
      "type": "topic",
      "url": "/documentation/swiftui/uihostingcontroller/willmove(toparent:)"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingControllerSizingOptions": {
      "abstract": [
        {
          "text": "Options for how a hosting controller tracks its content’s size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIHostingControllerSizingOptions"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingControllerSizingOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIHostingControllerSizingOptions"
        }
      ],
      "role": "symbol",
      "title": "UIHostingControllerSizingOptions",
      "type": "topic",
      "url": "/documentation/swiftui/uihostingcontrollersizingoptions"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/Unifying-your-app-s-animations": {
      "abstract": [
        {
          "text": "Create a consistent UI animation experience across SwiftUI, UIKit, and AppKit.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/Unifying-your-app-s-animations",
      "images": [
        {
          "identifier": "Unifying-your-app-s-animations-PageImage-card.png",
          "type": "card"
        }
      ],
      "kind": "article",
      "role": "article",
      "title": "Unifying your app’s animations",
      "type": "topic",
      "url": "/documentation/swiftui/unifying-your-app-s-animations"
    },
    "doc://com.apple.SwiftUI/documentation/SwiftUI/View": {
      "abstract": [
        {
          "text": "A type that represents part of your app’s user interface and provides",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "modifiers that you use to configure views.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "View"
        }
      ],
      "identifier": "doc://com.apple.SwiftUI/documentation/SwiftUI/View",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "View"
        }
      ],
      "role": "symbol",
      "title": "View",
      "type": "topic",
      "url": "/documentation/swiftui/view"
    },
    "doc://com.apple.documentation/documentation/UIKit/using-swiftui-with-uikit": {
      "abstract": [
        {
          "text": "Learn how to incorporate SwiftUI views into a UIKit app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/UIKit/using-swiftui-with-uikit",
      "kind": "article",
      "role": "sampleCode",
      "title": "Using SwiftUI with UIKit",
      "type": "topic",
      "url": "/documentation/UIKit/using-swiftui-with-uikit"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)UIViewController": {
      "abstract": [
        {
          "text": "An object that manages a view hierarchy for your UIKit app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewController"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)UIViewController",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIViewController",
      "type": "topic",
      "url": "/documentation/UIKit/UIViewController"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding": {
      "abstract": [
        {
          "text": "A protocol that enables an object to be encoded and decoded for archiving and distribution.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSCoding"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCoding",
      "type": "topic",
      "url": "/documentation/foundation/nscoding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSExtensionRequestHandling": {
      "abstract": [
        {
          "text": "The interface an app extension uses to respond to a request from a host app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSExtensionRequestHandling"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSExtensionRequestHandling",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSExtensionRequestHandling",
      "type": "topic",
      "url": "/documentation/foundation/nsextensionrequesthandling"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSObject": {
      "abstract": [
        {
          "text": "The group of methods that are fundamental to all Objective-C objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "protocol "
        },
        {
          "kind": "identifier",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSObjectProtocol",
      "type": "topic",
      "url": "/documentation/objectivec/nsobjectprotocol"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)NSTouchBarProvider": {
      "abstract": [
        {
          "text": "A protocol that an object adopts to create a bar object in your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTouchBarProvider"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)NSTouchBarProvider",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSTouchBarProvider",
      "type": "topic",
      "url": "/documentation/AppKit/NSTouchBarProvider"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIActivityItemsConfigurationProviding": {
      "abstract": [
        {
          "text": "An interface that provides a source for shareable content to fulfill user requests to share current content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIActivityItemsConfigurationProviding"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIActivityItemsConfigurationProviding",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIActivityItemsConfigurationProviding",
      "type": "topic",
      "url": "/documentation/UIKit/UIActivityItemsConfigurationProviding"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIAppearanceContainer": {
      "abstract": [
        {
          "text": "A protocol that a class must adopt to allow appearance customization using the [`UIAppearance`](doc://com.apple.uikit/documentation/UIKit/UIAppearance) API.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIAppearanceContainer"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIAppearanceContainer",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIAppearanceContainer",
      "type": "topic",
      "url": "/documentation/UIKit/UIAppearanceContainer"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIContentContainer": {
      "abstract": [
        {
          "text": "A set of methods for adapting the contents of your view controllers to size and trait changes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIContentContainer"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIContentContainer",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIContentContainer",
      "type": "topic",
      "url": "/documentation/UIKit/UIContentContainer"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIFocusEnvironment": {
      "abstract": [
        {
          "text": "A set of methods that define the focus behavior for a branch of the view hierarchy.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIFocusEnvironment"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIFocusEnvironment",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIFocusEnvironment",
      "type": "topic",
      "url": "/documentation/UIKit/UIFocusEnvironment"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIPasteConfigurationSupporting": {
      "abstract": [
        {
          "text": "The interface that determines whether a responder object supports paste configuration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPasteConfigurationSupporting"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIPasteConfigurationSupporting",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIPasteConfigurationSupporting",
      "type": "topic",
      "url": "/documentation/UIKit/UIPasteConfigurationSupporting"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIResponderStandardEditActions": {
      "abstract": [
        {
          "text": "A set of standard methods that apps can adopt to support editing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIResponderStandardEditActions"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIResponderStandardEditActions",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIResponderStandardEditActions",
      "type": "topic",
      "url": "/documentation/UIKit/UIResponderStandardEditActions"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIStateRestoring": {
      "abstract": [
        {
          "text": "Methods for adding objects to your state restoration archives.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIStateRestoring"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIStateRestoring",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIStateRestoring",
      "type": "topic",
      "url": "/documentation/UIKit/UIStateRestoring"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UITraitEnvironment": {
      "abstract": [
        {
          "text": "A set of methods that makes the iOS interface environment available to your app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITraitEnvironment"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UITraitEnvironment",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitEnvironment",
      "type": "topic",
      "url": "/documentation/UIKit/UITraitEnvironment"
    },
    "doc://com.externally.resolved.symbol/c:objc(pl)UIUserActivityRestoring": {
      "abstract": [
        {
          "text": "The protocol you adopt to restore an object’s state from a user activity.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIUserActivityRestoring"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(pl)NSObject",
          "text": "NSObjectProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(pl)UIUserActivityRestoring",
      "kind": "symbol",
      "role": "symbol",
      "title": "UIUserActivityRestoring",
      "type": "topic",
      "url": "/documentation/UIKit/UIUserActivityRestoring"
    },
    "doc://com.externally.resolved.symbol/s:5UIKit23UITraitChangeObservableP": {
      "abstract": [
        {
          "text": "A type that calls your code in reaction to changes in the trait environment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@"
        },
        {
          "kind": "attribute",
          "preciseIdentifier": "s:ScM",
          "text": "MainActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UITraitChangeObservable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:5UIKit23UITraitChangeObservableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "UITraitChangeObservable",
      "type": "topic",
      "url": "/documentation/UIKit/UITraitChangeObservable-67e94"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    },
    "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP": {
      "abstract": [
        {
          "text": "A type with a customized textual representation suitable for debugging purposes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CustomDebugStringConvertible"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CustomDebugStringConvertible",
      "type": "topic",
      "url": "/documentation/Swift/CustomDebugStringConvertible"
    },
    "doc://com.externally.resolved.symbol/s:s7CVarArgP": {
      "abstract": [
        {
          "text": "A type whose instances can be encoded, and appropriately passed, as elements of a C `va_list`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CVarArg"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s7CVarArgP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CVarArg",
      "type": "topic",
      "url": "/documentation/Swift/CVarArg"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/c:objc(cs)UIViewController"
      ],
      "kind": "relationships",
      "title": "Inherits From",
      "type": "inheritsFrom"
    },
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s7CVarArgP",
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:s28CustomDebugStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:s23CustomStringConvertibleP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSCoding",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSExtensionRequestHandling",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSObject",
        "doc://com.externally.resolved.symbol/c:objc(pl)NSTouchBarProvider",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIActivityItemsConfigurationProviding",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIAppearanceContainer",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIContentContainer",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIFocusEnvironment",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIPasteConfigurationSupporting",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIResponderStandardEditActions",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIStateRestoring",
        "doc://com.externally.resolved.symbol/s:5UIKit23UITraitChangeObservableP",
        "doc://com.externally.resolved.symbol/c:objc(pl)UITraitEnvironment",
        "doc://com.externally.resolved.symbol/c:objc(pl)UIUserActivityRestoring"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Displaying-SwiftUI-views-in-UIKit",
      "generated": true,
      "identifiers": [
        "doc://com.apple.documentation/documentation/UIKit/using-swiftui-with-uikit",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/Unifying-your-app-s-animations",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingControllerSizingOptions",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingConfiguration"
      ],
      "title": "Displaying SwiftUI views in UIKit"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-a-hosting-controller-object",
      "identifiers": [
        "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/init(rootView:)",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/init(coder:rootView:)",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/init(coder:)"
      ],
      "title": "Creating a hosting controller object"
    },
    {
      "anchor": "Responding-to-view-related-events",
      "identifiers": [
        "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/loadView()",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/viewWillAppear(_:)",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/viewDidAppear(_:)",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/viewWillDisappear(_:)",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/viewDidDisappear(_:)",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/willMove(toParent:)",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/didMove(toParent:)",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/viewWillTransition(to:with:)",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/viewWillLayoutSubviews()",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/target(forAction:withSender:)",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/rootView"
      ],
      "title": "Responding to view-related events"
    },
    {
      "anchor": "Checking-for-modality",
      "identifiers": [
        "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/isModalInPresentation"
      ],
      "title": "Checking for modality"
    },
    {
      "anchor": "Managing-the-size",
      "identifiers": [
        "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/sizingOptions",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/preferredContentSizeDidChange(forChildContentContainer:)",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/sizeThatFits(in:)",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/safeAreaRegions"
      ],
      "title": "Managing the size"
    },
    {
      "anchor": "Configuring-the-status-bar",
      "identifiers": [
        "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/preferredStatusBarStyle",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/preferredStatusBarUpdateAnimation",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/prefersStatusBarHidden",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/childForStatusBarStyle",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/childForStatusBarHidden"
      ],
      "title": "Configuring the status bar"
    },
    {
      "anchor": "Configuring-the-home-indicator",
      "identifiers": [
        "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/prefersHomeIndicatorAutoHidden",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/childForHomeIndicatorAutoHidden"
      ],
      "title": "Configuring the home indicator"
    },
    {
      "anchor": "Configuring-the-interface-appearance",
      "identifiers": [
        "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/preferredUserInterfaceStyle",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/preferredScreenEdgesDeferringSystemGestures",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/childForScreenEdgesDeferringSystemGestures"
      ],
      "title": "Configuring the interface appearance"
    },
    {
      "anchor": "Accessing-the-available-key-commands",
      "identifiers": [
        "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/keyCommands"
      ],
      "title": "Accessing the available key commands"
    },
    {
      "anchor": "Managing-undo",
      "identifiers": [
        "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/undoManager"
      ],
      "title": "Managing undo"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/childViewControllerForPreferredContainerBackgroundStyle",
        "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/preferredContainerBackgroundStyle"
      ],
      "title": "Instance Properties"
    },
    {
      "anchor": "Instance-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.SwiftUI/documentation/SwiftUI/UIHostingController/addChild(_:)"
      ],
      "title": "Instance Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIContentContainer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIContentContainer"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSObject/title",
          "value": "NSObject"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIResponderStandardEditActions/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIResponderStandardEditActions"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UITraitEnvironment/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UITraitEnvironment"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIPasteConfigurationSupporting/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIPasteConfigurationSupporting"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIAppearanceContainer/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIAppearanceContainer"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIStateRestoring/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIStateRestoring"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIUserActivityRestoring/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIUserActivityRestoring"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIActivityItemsConfigurationProviding/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIActivityItemsConfigurationProviding"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)NSTouchBarProvider/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "NSTouchBarProvider"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)UIViewController/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIViewController"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIResponder",
              "text": "UIResponder"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(pl)UIFocusEnvironment/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@protocol"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "UIFocusEnvironment"
            },
            {
              "kind": "text",
              "text": " <"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(pl)NSObject",
              "text": "NSObject"
            },
            {
              "kind": "text",
              "text": ">"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/swiftui/uihostingcontroller"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
