{
  "abstract": [
    {
      "text": "The user’s display name, email address, or other identifier in a streaming media service.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediasetup/documentation/MediaSetup",
        "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount/accountName"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MSServiceAccount(py)accountName",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "accountName"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SS",
        "text": "String"
      }
    ],
    "modules": [
      {
        "name": "Media Setup"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "accountName"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "accountName"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "accountName"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SS",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SS",
              "text": "String"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediasetup/documentation/MediaSetup": {
      "abstract": [
        {
          "text": "Enable users to configure HomePod speakers to stream music directly from your media service.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediasetup/documentation/MediaSetup",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Setup",
      "type": "topic",
      "url": "/documentation/mediasetup"
    },
    "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount": {
      "abstract": [
        {
          "text": "Account details for accessing a streaming media service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSServiceAccount"
        }
      ],
      "identifier": "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSServiceAccount"
        }
      ],
      "role": "symbol",
      "title": "MSServiceAccount",
      "type": "topic",
      "url": "/documentation/mediasetup/msserviceaccount"
    },
    "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount/accountName": {
      "abstract": [
        {
          "text": "The user’s display name, email address, or other identifier in a streaming media service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accountName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount/accountName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "accountName"
        }
      ],
      "role": "symbol",
      "title": "accountName",
      "type": "topic",
      "url": "/documentation/mediasetup/msserviceaccount/accountname"
    },
    "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount/init(serviceName:accountName:)": {
      "abstract": [
        {
          "text": "Creates a new account.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "serviceName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "accountName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount/init(serviceName:accountName:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "initWithServiceName:accountName:"
        }
      ],
      "role": "symbol",
      "title": "init(serviceName:accountName:)",
      "type": "topic",
      "url": "/documentation/mediasetup/msserviceaccount/init(servicename:accountname:)"
    },
    "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount/serviceName": {
      "abstract": [
        {
          "text": "The localized name of the streaming media service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "serviceName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        }
      ],
      "identifier": "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount/serviceName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "serviceName"
        }
      ],
      "role": "symbol",
      "title": "serviceName",
      "type": "topic",
      "url": "/documentation/mediasetup/msserviceaccount/servicename"
    },
    "doc://com.externally.resolved.symbol/s:SS": {
      "abstract": [
        {
          "text": "A Unicode string value that is a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "String"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SS",
      "kind": "symbol",
      "role": "symbol",
      "title": "String",
      "type": "topic",
      "url": "/documentation/Swift/String"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Presenting-Account-Information-to-the-User",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount/init(serviceName:accountName:)",
        "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount/serviceName"
      ],
      "title": "Presenting Account Information to the User"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "accountName"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "accountName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediasetup/documentation/MediaSetup",
                "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Presenting-Account-Information-to-the-User",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount/init(serviceName:accountName:)",
                "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount/serviceName"
              ],
              "title": "Presenting Account Information to the User"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSString",
                    "text": "NSString"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "accountName"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSServiceAccount/title",
          "value": "MSServiceAccount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSServiceAccount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSServiceAccount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSServiceAccount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSServiceAccount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSServiceAccount~1init(serviceName:accountName:)/title",
          "value": "initWithServiceName:accountName:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSServiceAccount~1init(serviceName:accountName:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "initWithServiceName:accountName:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSServiceAccount~1accountName/title",
          "value": "accountName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSServiceAccount~1accountName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "accountName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSServiceAccount~1serviceName/title",
          "value": "serviceName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSServiceAccount~1serviceName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "serviceName"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediasetup/msserviceaccount/accountname"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediasetup/msserviceaccount/accountname"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
