{
  "abstract": [
    {
      "text": "The path to access the configuration endpoint of your streaming media service for HomePod.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mediasetup/documentation/MediaSetup",
        "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount/configurationURL"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)MSServiceAccount(py)configurationURL",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "configurationURL"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:10Foundation3URLV",
        "text": "URL"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Media Setup"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "configurationURL"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "configurationURL"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "configurationURL"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:10Foundation3URLV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:10Foundation3URLV",
              "text": "URL"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "set"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mediasetup/documentation/MediaSetup": {
      "abstract": [
        {
          "text": "Enable users to configure HomePod speakers to stream music directly from your media service.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.mediasetup/documentation/MediaSetup",
      "kind": "symbol",
      "role": "collection",
      "title": "Media Setup",
      "type": "topic",
      "url": "/documentation/mediasetup"
    },
    "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount": {
      "abstract": [
        {
          "text": "Account details for accessing a streaming media service.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MSServiceAccount"
        }
      ],
      "identifier": "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MSServiceAccount"
        }
      ],
      "role": "symbol",
      "title": "MSServiceAccount",
      "type": "topic",
      "url": "/documentation/mediasetup/msserviceaccount"
    },
    "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount/authorizationScope": {
      "abstract": [
        {
          "text": "A list of permissions for the token request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorizationScope"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount/authorizationScope",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "authorizationScope"
        }
      ],
      "role": "symbol",
      "title": "authorizationScope",
      "type": "topic",
      "url": "/documentation/mediasetup/msserviceaccount/authorizationscope"
    },
    "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount/authorizationTokenURL": {
      "abstract": [
        {
          "text": "A URL the system can access to request an OAuth token for the user’s HomePod speakers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "authorizationTokenURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount/authorizationTokenURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "authorizationTokenURL"
        }
      ],
      "role": "symbol",
      "title": "authorizationTokenURL",
      "type": "topic",
      "url": "/documentation/mediasetup/msserviceaccount/authorizationtokenurl"
    },
    "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount/clientID": {
      "abstract": [
        {
          "text": "A user identifier for the token request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clientID"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount/clientID",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clientID"
        }
      ],
      "role": "symbol",
      "title": "clientID",
      "type": "topic",
      "url": "/documentation/mediasetup/msserviceaccount/clientid"
    },
    "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount/clientSecret": {
      "abstract": [
        {
          "text": "A string that authenticates the user’s setup request.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clientSecret"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount/clientSecret",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "clientSecret"
        }
      ],
      "role": "symbol",
      "title": "clientSecret",
      "type": "topic",
      "url": "/documentation/mediasetup/msserviceaccount/clientsecret"
    },
    "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount/configurationURL": {
      "abstract": [
        {
          "text": "The path to access the configuration endpoint of your streaming media service for HomePod.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "configurationURL"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:10Foundation3URLV",
          "text": "URL"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount/configurationURL",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "configurationURL"
        }
      ],
      "role": "symbol",
      "title": "configurationURL",
      "type": "topic",
      "url": "/documentation/mediasetup/msserviceaccount/configurationurl"
    },
    "doc://com.externally.resolved.symbol/s:10Foundation3URLV": {
      "abstract": [
        {
          "text": "A value that identifies the location of a resource, such as an item on a remote server or the path to a local file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "URL"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:10Foundation3URLV",
      "kind": "symbol",
      "role": "symbol",
      "title": "URL",
      "type": "topic",
      "url": "/documentation/foundation/url"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Providing-Parameters-for-an-OAuth-Request",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount/authorizationTokenURL",
        "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount/authorizationScope",
        "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount/clientID",
        "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount/clientSecret"
      ],
      "title": "Providing Parameters for an OAuth Request"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "configurationURL"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "configurationURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mediasetup/documentation/MediaSetup",
                "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Providing-Parameters-for-an-OAuth-Request",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount/authorizationTokenURL",
                "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount/authorizationScope",
                "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount/clientID",
                "doc://com.apple.mediasetup/documentation/MediaSetup/MSServiceAccount/clientSecret"
              ],
              "title": "Providing Parameters for an OAuth Request"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "copy"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readwrite"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSURL",
                    "text": "NSURL"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "configurationURL"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSServiceAccount~1configurationURL/title",
          "value": "configurationURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSServiceAccount~1configurationURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "configurationURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSServiceAccount~1authorizationScope/title",
          "value": "authorizationScope"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSServiceAccount~1authorizationScope/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "authorizationScope"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSServiceAccount/title",
          "value": "MSServiceAccount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSServiceAccount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MSServiceAccount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSServiceAccount/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MSServiceAccount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSServiceAccount~1authorizationTokenURL/title",
          "value": "authorizationTokenURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSServiceAccount~1authorizationTokenURL/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "authorizationTokenURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSServiceAccount~1clientSecret/title",
          "value": "clientSecret"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSServiceAccount~1clientSecret/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "clientSecret"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSServiceAccount~1clientID/title",
          "value": "clientID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mediasetup~1documentation~1MediaSetup~1MSServiceAccount~1clientID/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "clientID"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mediasetup/msserviceaccount/configurationurl"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mediasetup/msserviceaccount/configurationurl"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
