{"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSCursor/columnResize","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSCursor"]]},"abstract":[{"text":"Returns the cursor for resizing a column (vertical divider) in either direction.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"columnResize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSCursor","preciseIdentifier":"c:objc(cs)NSCursor","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["Mac Catalyst","macOS"]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nscursor/columnresize"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nscursor/columnresize"]}],"metadata":{"roleHeading":"Type Property","navigatorTitle":[{"text":"columnResizeCursor","kind":"identifier"}],"role":"symbol","externalID":"c:objc(cs)NSCursor(cpy)columnResizeCursor","symbolKind":"property","modules":[{"name":"AppKit"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"columnResize"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSCursor","text":"NSCursor","kind":"typeIdentifier"}],"platforms":[{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"13.0","name":"iOS"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"13.0","name":"iPadOS"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"18.0","name":"Mac Catalyst"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"15.0","name":"macOS"}],"title":"columnResize"},"sections":[],"references":{"doc://com.apple.appkit/documentation/AppKit/NSCursor/columnResize":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"columnResize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSCursor","preciseIdentifier":"c:objc(cs)NSCursor","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"columnResizeCursor","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/columnResize","abstract":[{"type":"text","text":"Returns the cursor for resizing a column (vertical divider) in either direction."}],"role":"symbol","kind":"symbol","title":"columnResize","url":"/documentation/appkit/nscursor/columnresize","type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSCursor":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSCursor"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor","navigatorTitle":[{"kind":"identifier","text":"NSCursor"}],"abstract":[{"text":"A pointer (also called a cursor).","type":"text"}],"type":"topic","title":"NSCursor","url":"/documentation/appkit/nscursor"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"18.0","name":"Mac Catalyst"},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"15.0","name":"macOS"}],"path":"/metadata/platforms","op":"replace"},{"value":"Type Property","path":"/metadata/roleHeading","op":"replace"},{"value":"columnResizeCursor","path":"/metadata/title","op":"replace"},{"value":"property","path":"/metadata/symbolKind","op":"replace"},{"value":[{"text":"columnResizeCursor","kind":"identifier"}],"path":"/metadata/fragments","op":"replace"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSCursor"]]},"path":"/hierarchy","op":"replace"},{"value":null,"path":"/topicSections","op":"add"},{"value":null,"path":"/relationshipsSections","op":"add"},{"value":null,"path":"/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSCursor","kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor","text":"NSCursor"},{"kind":"text","text":" * "},{"kind":"identifier","text":"columnResizeCursor"},{"kind":"text","text":";"}]}]},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","value":"columnResizeCursor","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1columnResize/title"},{"op":"replace","value":[{"text":"columnResizeCursor","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1columnResize/fragments"},{"op":"replace","value":"NSCursor","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSCursor"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSCursor"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor/navigatorTitle"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}