{"metadata":{"roleHeading":"Type Property","modules":[{"name":"AppKit"}],"navigatorTitle":[{"kind":"identifier","text":"currentCursor"}],"platforms":[{"introducedAt":"13.0","name":"iOS","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"13.0","name":"iPadOS","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"13.1","name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"10.0","name":"macOS","deprecated":false,"unavailable":false,"beta":false}],"role":"symbol","title":"current","symbolKind":"property","externalID":"c:objc(cs)NSCursor(cpy)currentCursor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"current"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSCursor","kind":"typeIdentifier","text":"NSCursor"}]},"variants":[{"paths":["/documentation/appkit/nscursor/current"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nscursor/current"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSCursor/current","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSCursor"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"anchor":"Related-Documentation","title":"Related Documentation","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCursor/mouseEntered(with:)","doc://com.apple.appkit/documentation/AppKit/NSCursor/pop()-swift.method","doc://com.apple.appkit/documentation/AppKit/NSCursor/push()","doc://com.apple.appkit/documentation/AppKit/NSCursor/set()","doc://com.apple.appkit/documentation/AppKit/NSCursor/mouseExited(with:)"]},{"generated":true,"anchor":"Retrieving-Cursor-Instances","title":"Retrieving Cursor Instances","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCursor/currentSystem","doc://com.apple.appkit/documentation/AppKit/NSCursor/arrow","doc://com.apple.appkit/documentation/AppKit/NSCursor/contextualMenu","doc://com.apple.appkit/documentation/AppKit/NSCursor/closedHand","doc://com.apple.appkit/documentation/AppKit/NSCursor/crosshair","doc://com.apple.appkit/documentation/AppKit/NSCursor/disappearingItem","doc://com.apple.appkit/documentation/AppKit/NSCursor/dragCopy","doc://com.apple.appkit/documentation/AppKit/NSCursor/dragLink","doc://com.apple.appkit/documentation/AppKit/NSCursor/iBeam","doc://com.apple.appkit/documentation/AppKit/NSCursor/openHand","doc://com.apple.appkit/documentation/AppKit/NSCursor/operationNotAllowed","doc://com.apple.appkit/documentation/AppKit/NSCursor/pointingHand","doc://com.apple.appkit/documentation/AppKit/NSCursor/resizeDown","doc://com.apple.appkit/documentation/AppKit/NSCursor/resizeLeft","doc://com.apple.appkit/documentation/AppKit/NSCursor/resizeLeftRight"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"current"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCursor","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor","preciseIdentifier":"c:objc(cs)NSCursor"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["Mac Catalyst","macOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The top cursor on the application’s cursor stack. This cursor may not be the visible cursor on the screen if a different application is currently active."}]}],"kind":"content"},{"content":[{"level":2,"anchor":"Discussion","text":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"The method only returns the cursor set by your application using "},{"type":"codeVoice","code":"NSCursor"},{"type":"text","text":" methods. It does not return cursors set by other applications or cursors set by your application using Carbon APIs."}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","abstract":[{"type":"text","text":"Returns the application’s current cursor."}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSCursor/current":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"current","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSCursor","preciseIdentifier":"c:objc(cs)NSCursor","kind":"typeIdentifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/current","navigatorTitle":[{"text":"currentCursor","kind":"identifier"}],"abstract":[{"type":"text","text":"Returns the application’s current cursor."}],"type":"topic","title":"current","url":"/documentation/appkit/nscursor/current"},"doc://com.apple.appkit/documentation/AppKit/NSCursor":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSCursor"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor","navigatorTitle":[{"kind":"identifier","text":"NSCursor"}],"abstract":[{"text":"A pointer (also called a cursor).","type":"text"}],"type":"topic","title":"NSCursor","url":"/documentation/appkit/nscursor"},"doc://com.apple.appkit/documentation/AppKit/NSCursor/operationNotAllowed":{"role":"symbol","type":"topic","title":"operationNotAllowed","url":"/documentation/appkit/nscursor/operationnotallowed","navigatorTitle":[{"kind":"identifier","text":"operationNotAllowedCursor"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/operationNotAllowed","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"operationNotAllowed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCursor","preciseIdentifier":"c:objc(cs)NSCursor"}],"abstract":[{"type":"text","text":"Returns the operation not allowed cursor."}]},"doc://com.apple.appkit/documentation/AppKit/NSCursor/push()":{"url":"/documentation/appkit/nscursor/push()","title":"push()","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"push","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"push","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/push()","abstract":[{"text":"Puts the receiver on top of the cursor stack and makes it the current cursor.","type":"text"}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSCursor/resizeLeftRight":{"abstract":[{"text":"Returns the resize-left-and-right system cursor.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"resizeLeftRight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCursor","preciseIdentifier":"c:objc(cs)NSCursor"}],"url":"/documentation/appkit/nscursor/resizeleftright","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/resizeLeftRight","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"resizeLeftRightCursor"}],"type":"topic","kind":"symbol","title":"resizeLeftRight"},"doc://com.apple.appkit/documentation/AppKit/NSCursor/resizeLeft":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/resizeLeft","navigatorTitle":[{"text":"resizeLeftCursor","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resizeLeft","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSCursor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCursor"}],"title":"resizeLeft","role":"symbol","abstract":[{"type":"text","text":"Returns the resize-left system cursor."}],"kind":"symbol","type":"topic","url":"/documentation/appkit/nscursor/resizeleft"},"doc://com.apple.appkit/documentation/AppKit/NSCursor/dragLink":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/dragLink","navigatorTitle":[{"kind":"identifier","text":"dragLinkCursor"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dragLink"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCursor","text":"NSCursor"}],"title":"dragLink","role":"symbol","abstract":[{"type":"text","text":"Returns a cursor indicating that the current operation will result in a link action."}],"kind":"symbol","type":"topic","url":"/documentation/appkit/nscursor/draglink"},"doc://com.apple.appkit/documentation/AppKit/NSCursor/mouseExited(with:)":{"url":"/documentation/appkit/nscursor/mouseexited(with:)","title":"mouseExited(with:)","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"mouseExited:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mouseExited","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSEvent","preciseIdentifier":"c:objc(cs)NSEvent","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/mouseExited(with:)","deprecated":true,"abstract":[{"text":"Automatically sent to the receiver when the cursor exits a cursor rectangle owned by the receiver.","type":"text"}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSCursor/resizeDown":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/resizeDown","role":"symbol","type":"topic","url":"/documentation/appkit/nscursor/resizedown","navigatorTitle":[{"kind":"identifier","text":"resizeDownCursor"}],"abstract":[{"type":"text","text":"Returns the resize-down system cursor."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"resizeDown"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCursor","text":"NSCursor"}],"title":"resizeDown","kind":"symbol"},"doc://com.apple.appkit/documentation/AppKit/NSCursor/disappearingItem":{"abstract":[{"text":"Returns a cursor indicating that the current operation will result in a disappearing item.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disappearingItem","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCursor","text":"NSCursor","kind":"typeIdentifier"}],"url":"/documentation/appkit/nscursor/disappearingitem","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/disappearingItem","role":"symbol","navigatorTitle":[{"text":"disappearingItemCursor","kind":"identifier"}],"type":"topic","kind":"symbol","title":"disappearingItem"},"doc://com.apple.appkit/documentation/AppKit/NSCursor/arrow":{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/arrow","navigatorTitle":[{"kind":"identifier","text":"arrowCursor"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"arrow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCursor","text":"NSCursor"}],"title":"arrow","role":"symbol","abstract":[{"text":"Returns the default cursor, the arrow cursor.","type":"text"}],"kind":"symbol","type":"topic","url":"/documentation/appkit/nscursor/arrow"},"doc://com.apple.appkit/documentation/AppKit/NSCursor/crosshair":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"crosshair","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSCursor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCursor"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/crosshair","navigatorTitle":[{"text":"crosshairCursor","kind":"identifier"}],"abstract":[{"text":"Returns the cross-hair system cursor.","type":"text"}],"type":"topic","title":"crosshair","url":"/documentation/appkit/nscursor/crosshair"},"doc://com.apple.appkit/documentation/AppKit/NSCursor/mouseEntered(with:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mouseEntered","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSEvent"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"mouseEntered:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/mouseEntered(with:)","url":"/documentation/appkit/nscursor/mouseentered(with:)","kind":"symbol","title":"mouseEntered(with:)","abstract":[{"text":"Automatically sent to the receiver when the cursor enters a cursor rectangle owned by the receiver.","type":"text"}],"deprecated":true,"role":"symbol","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSCursor/pop()-swift.type.method":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pop","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"pop","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/pop()-swift.type.method","url":"/documentation/appkit/nscursor/pop()-swift.type.method","kind":"symbol","title":"pop()","abstract":[{"text":"Pops the current cursor off the top of the stack.","type":"text"}],"role":"symbol","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSCursor/dragCopy":{"kind":"symbol","url":"/documentation/appkit/nscursor/dragcopy","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"dragCopyCursor"}],"abstract":[{"type":"text","text":"Returns a cursor indicating that the current operation will result in a copy action."}],"title":"dragCopy","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dragCopy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCursor","preciseIdentifier":"c:objc(cs)NSCursor"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/dragCopy","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSCursor/set()":{"url":"/documentation/appkit/nscursor/set()","title":"set()","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"set","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/set()","abstract":[{"text":"Makes the receiver the current cursor.","type":"text"}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSCursor/pointingHand":{"kind":"symbol","url":"/documentation/appkit/nscursor/pointinghand","role":"symbol","navigatorTitle":[{"text":"pointingHandCursor","kind":"identifier"}],"abstract":[{"type":"text","text":"Returns the pointing-hand system cursor."}],"title":"pointingHand","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pointingHand","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSCursor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCursor"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/pointingHand","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSCursor/currentSystem":{"title":"currentSystem","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/currentSystem","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentSystem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCursor","preciseIdentifier":"c:objc(cs)NSCursor"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Returns the current system cursor."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"currentSystemCursor"}],"url":"/documentation/appkit/nscursor/currentsystem"},"doc://com.apple.appkit/documentation/AppKit/NSCursor/contextualMenu":{"kind":"symbol","url":"/documentation/appkit/nscursor/contextualmenu","role":"symbol","navigatorTitle":[{"text":"contextualMenuCursor","kind":"identifier"}],"abstract":[{"type":"text","text":"Returns the contextual menu system cursor."}],"title":"contextualMenu","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contextualMenu","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSCursor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCursor"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/contextualMenu","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSCursor/closedHand":{"kind":"symbol","url":"/documentation/appkit/nscursor/closedhand","role":"symbol","navigatorTitle":[{"text":"closedHandCursor","kind":"identifier"}],"abstract":[{"text":"Returns the closed-hand system cursor.","type":"text"}],"title":"closedHand","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"closedHand","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSCursor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCursor"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/closedHand","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSCursor/openHand":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"openHand","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSCursor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCursor"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/openHand","navigatorTitle":[{"text":"openHandCursor","kind":"identifier"}],"abstract":[{"text":"Returns the open-hand system cursor.","type":"text"}],"type":"topic","title":"openHand","url":"/documentation/appkit/nscursor/openhand"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSCursor/pop()-swift.method":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pop","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"pop","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/pop()-swift.method","url":"/documentation/appkit/nscursor/pop()-swift.method","kind":"symbol","title":"pop()","abstract":[{"text":"Sends a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/pop()-swift.type.method"},{"text":" message to the receiver’s class.","type":"text"}],"role":"symbol","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSCursor/iBeam":{"role":"symbol","abstract":[{"type":"text","text":"Returns a cursor that looks like a capital I with a tiny crossbeam at its middle."}],"title":"iBeam","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"IBeamCursor"}],"url":"/documentation/appkit/nscursor/ibeam","type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/iBeam","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"iBeam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCursor","preciseIdentifier":"c:objc(cs)NSCursor"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"name":"Mac Catalyst","beta":false,"introducedAt":"13.1","deprecated":false,"unavailable":false},{"name":"macOS","beta":false,"introducedAt":"10.0","deprecated":false,"unavailable":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Type Property"},{"op":"replace","path":"/metadata/title","value":"currentCursor"},{"op":"replace","path":"/metadata/symbolKind","value":"property"},{"op":"replace","path":"/metadata/fragments","value":[{"text":"currentCursor","kind":"identifier"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSCursor"]]}},{"op":"add","path":"/topicSections","value":null},{"op":"add","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCursor/mouseEntered(with:)","doc://com.apple.appkit/documentation/AppKit/NSCursor/pop()-swift.method","doc://com.apple.appkit/documentation/AppKit/NSCursor/push()","doc://com.apple.appkit/documentation/AppKit/NSCursor/set()","doc://com.apple.appkit/documentation/AppKit/NSCursor/mouseExited(with:)"],"anchor":"Related-Documentation","title":"Related Documentation"},{"anchor":"Retrieving-Cursor-Instances","generated":true,"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCursor/currentSystem","doc://com.apple.appkit/documentation/AppKit/NSCursor/arrow","doc://com.apple.appkit/documentation/AppKit/NSCursor/contextualMenu","doc://com.apple.appkit/documentation/AppKit/NSCursor/closedHand","doc://com.apple.appkit/documentation/AppKit/NSCursor/crosshair","doc://com.apple.appkit/documentation/AppKit/NSCursor/disappearingItem","doc://com.apple.appkit/documentation/AppKit/NSCursor/dragCopy","doc://com.apple.appkit/documentation/AppKit/NSCursor/dragLink","doc://com.apple.appkit/documentation/AppKit/NSCursor/iBeam","doc://com.apple.appkit/documentation/AppKit/NSCursor/openHand","doc://com.apple.appkit/documentation/AppKit/NSCursor/operationNotAllowed","doc://com.apple.appkit/documentation/AppKit/NSCursor/pointingHand","doc://com.apple.appkit/documentation/AppKit/NSCursor/resizeDown","doc://com.apple.appkit/documentation/AppKit/NSCursor/resizeLeft","doc://com.apple.appkit/documentation/AppKit/NSCursor/resizeLeftRight"],"title":"Retrieving Cursor Instances"}]},{"op":"replace","path":"/primaryContentSections/0","value":{"declarations":[{"languages":["occ"],"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSCursor","kind":"typeIdentifier","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor","text":"NSCursor"},{"kind":"text","text":" * "},{"kind":"identifier","text":"currentCursor"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1current/title","value":"currentCursor","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1current/fragments","value":[{"kind":"identifier","text":"currentCursor"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor/title","value":"NSCursor","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor/fragments","value":[{"kind":"identifier","text":"NSCursor"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor/navigatorTitle","value":[{"kind":"identifier","text":"NSCursor"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1operationNotAllowed/title","value":"operationNotAllowedCursor","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1operationNotAllowed/fragments","value":[{"text":"operationNotAllowedCursor","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1push()/title","value":"push","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1push()/fragments","value":[{"text":"- ","kind":"text"},{"text":"push","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1resizeLeftRight/title","value":"resizeLeftRightCursor","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1resizeLeftRight/fragments","value":[{"kind":"identifier","text":"resizeLeftRightCursor"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1resizeLeft/title","value":"resizeLeftCursor","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1resizeLeft/fragments","value":[{"text":"resizeLeftCursor","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1dragLink/title","value":"dragLinkCursor","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1dragLink/fragments","value":[{"text":"dragLinkCursor","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1mouseExited(with:)/title","value":"mouseExited:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1mouseExited(with:)/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mouseExited:"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1resizeDown/title","value":"resizeDownCursor","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1resizeDown/fragments","value":[{"kind":"identifier","text":"resizeDownCursor"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1disappearingItem/title","value":"disappearingItemCursor","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1disappearingItem/fragments","value":[{"text":"disappearingItemCursor","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1arrow/title","value":"arrowCursor","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1arrow/fragments","value":[{"text":"arrowCursor","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1crosshair/title","value":"crosshairCursor","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1crosshair/fragments","value":[{"text":"crosshairCursor","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1mouseEntered(with:)/title","value":"mouseEntered:","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1mouseEntered(with:)/fragments","value":[{"text":"- ","kind":"text"},{"text":"mouseEntered:","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1pop()-swift.type.method/title","value":"pop","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1pop()-swift.type.method/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"pop"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1dragCopy/title","value":"dragCopyCursor","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1dragCopy/fragments","value":[{"text":"dragCopyCursor","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1set()/title","value":"set","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1set()/fragments","value":[{"text":"- ","kind":"text"},{"text":"set","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1pointingHand/title","value":"pointingHandCursor","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1pointingHand/fragments","value":[{"kind":"identifier","text":"pointingHandCursor"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1currentSystem/title","value":"currentSystemCursor","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1currentSystem/fragments","value":[{"text":"currentSystemCursor","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1contextualMenu/title","value":"contextualMenuCursor","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1contextualMenu/fragments","value":[{"kind":"identifier","text":"contextualMenuCursor"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1closedHand/title","value":"closedHandCursor","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1closedHand/fragments","value":[{"text":"closedHandCursor","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1openHand/title","value":"openHandCursor","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1openHand/fragments","value":[{"kind":"identifier","text":"openHandCursor"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1pop()-swift.method/title","value":"pop","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1pop()-swift.method/fragments","value":[{"text":"- ","kind":"text"},{"text":"pop","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1iBeam/title","value":"IBeamCursor","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1iBeam/fragments","value":[{"text":"IBeamCursor","kind":"identifier"}],"op":"replace"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}