{
  "abstract": [
    {
      "text": "The position along the perimeter of a rectangular frame (its edges and corners) from which it’s resized.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.appkit/documentation/AppKit",
        "doc://com.apple.appkit/documentation/AppKit/NSCursor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "AppKit",
    "externalID": "c:@E@NSCursorFrameResizePosition",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "FrameResizePosition"
      }
    ],
    "modules": [
      {
        "name": "AppKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "FrameResizePosition"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "18.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "NSCursor.FrameResizePosition"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "Mac Catalyst",
            "macOS"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@frozen"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "FrameResizePosition"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.appkit/documentation/AppKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your macOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit",
      "kind": "symbol",
      "role": "collection",
      "title": "AppKit",
      "type": "topic",
      "url": "/documentation/appkit"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCursor": {
      "abstract": [
        {
          "text": "A pointer (also called a cursor).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSCursor"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCursor"
        }
      ],
      "role": "symbol",
      "title": "NSCursor",
      "type": "topic",
      "url": "/documentation/appkit/nscursor"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition": {
      "abstract": [
        {
          "text": "The position along the perimeter of a rectangular frame (its edges and corners) from which it’s resized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FrameResizePosition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FrameResizePosition"
        }
      ],
      "role": "symbol",
      "title": "NSCursor.FrameResizePosition",
      "type": "topic",
      "url": "/documentation/appkit/nscursor/frameresizeposition"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/bottom": {
      "abstract": [
        {
          "text": "The bottom edge of the frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottom"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/bottom",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCursorFrameResizePositionBottom"
        }
      ],
      "role": "symbol",
      "title": "NSCursor.FrameResizePosition.bottom",
      "type": "topic",
      "url": "/documentation/appkit/nscursor/frameresizeposition/bottom"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/bottomLeading(relativeTo:)": {
      "abstract": [
        {
          "text": "The bottom leading corner of the frame, in the given user interface layout direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottomLeading"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "relativeTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSUserInterfaceLayoutDirection",
          "text": "NSUserInterfaceLayoutDirection"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCursor",
          "text": "NSCursor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSCursorFrameResizePosition",
          "text": "FrameResizePosition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/bottomLeading(relativeTo:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "bottomLeading(relativeTo:)",
      "type": "topic",
      "url": "/documentation/appkit/nscursor/frameresizeposition/bottomleading(relativeto:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/bottomLeft": {
      "abstract": [
        {
          "text": "The bottom left corner of the frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottomLeft"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/bottomLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCursorFrameResizePositionBottomLeft"
        }
      ],
      "role": "symbol",
      "title": "NSCursor.FrameResizePosition.bottomLeft",
      "type": "topic",
      "url": "/documentation/appkit/nscursor/frameresizeposition/bottomleft"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/bottomRight": {
      "abstract": [
        {
          "text": "The bottom right corner of the frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottomRight"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/bottomRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCursorFrameResizePositionBottomRight"
        }
      ],
      "role": "symbol",
      "title": "NSCursor.FrameResizePosition.bottomRight",
      "type": "topic",
      "url": "/documentation/appkit/nscursor/frameresizeposition/bottomright"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/bottomTrailing(relativeTo:)": {
      "abstract": [
        {
          "text": "The bottom trailing corner of the frame, in the given user interface layout direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bottomTrailing"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "relativeTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSUserInterfaceLayoutDirection",
          "text": "NSUserInterfaceLayoutDirection"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCursor",
          "text": "NSCursor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSCursorFrameResizePosition",
          "text": "FrameResizePosition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/bottomTrailing(relativeTo:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "bottomTrailing(relativeTo:)",
      "type": "topic",
      "url": "/documentation/appkit/nscursor/frameresizeposition/bottomtrailing(relativeto:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Su",
          "text": "UInt"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/appkit/nscursor/frameresizeposition/init(rawvalue:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/leading(relativeTo:)": {
      "abstract": [
        {
          "text": "The leading edge of the frame, in the given user interface layout direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leading"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "relativeTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSUserInterfaceLayoutDirection",
          "text": "NSUserInterfaceLayoutDirection"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCursor",
          "text": "NSCursor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSCursorFrameResizePosition",
          "text": "FrameResizePosition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/leading(relativeTo:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "leading(relativeTo:)",
      "type": "topic",
      "url": "/documentation/appkit/nscursor/frameresizeposition/leading(relativeto:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/left": {
      "abstract": [
        {
          "text": "The left edge of the frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "left"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/left",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCursorFrameResizePositionLeft"
        }
      ],
      "role": "symbol",
      "title": "NSCursor.FrameResizePosition.left",
      "type": "topic",
      "url": "/documentation/appkit/nscursor/frameresizeposition/left"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/right": {
      "abstract": [
        {
          "text": "The right edge of the frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "right"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/right",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCursorFrameResizePositionRight"
        }
      ],
      "role": "symbol",
      "title": "NSCursor.FrameResizePosition.right",
      "type": "topic",
      "url": "/documentation/appkit/nscursor/frameresizeposition/right"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/top": {
      "abstract": [
        {
          "text": "The top edge of the frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "top"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/top",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCursorFrameResizePositionTop"
        }
      ],
      "role": "symbol",
      "title": "NSCursor.FrameResizePosition.top",
      "type": "topic",
      "url": "/documentation/appkit/nscursor/frameresizeposition/top"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/topLeading(relativeTo:)": {
      "abstract": [
        {
          "text": "The top leading corner of the frame, in the given user interface layout direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topLeading"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "relativeTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSUserInterfaceLayoutDirection",
          "text": "NSUserInterfaceLayoutDirection"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCursor",
          "text": "NSCursor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSCursorFrameResizePosition",
          "text": "FrameResizePosition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/topLeading(relativeTo:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "topLeading(relativeTo:)",
      "type": "topic",
      "url": "/documentation/appkit/nscursor/frameresizeposition/topleading(relativeto:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/topLeft": {
      "abstract": [
        {
          "text": "The top left corner of the frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topLeft"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/topLeft",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCursorFrameResizePositionTopLeft"
        }
      ],
      "role": "symbol",
      "title": "NSCursor.FrameResizePosition.topLeft",
      "type": "topic",
      "url": "/documentation/appkit/nscursor/frameresizeposition/topleft"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/topRight": {
      "abstract": [
        {
          "text": "The top right corner of the frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topRight"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/topRight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSCursorFrameResizePositionTopRight"
        }
      ],
      "role": "symbol",
      "title": "NSCursor.FrameResizePosition.topRight",
      "type": "topic",
      "url": "/documentation/appkit/nscursor/frameresizeposition/topright"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/topTrailing(relativeTo:)": {
      "abstract": [
        {
          "text": "The top trailing corner of the frame, in the given user interface layout direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "topTrailing"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "relativeTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSUserInterfaceLayoutDirection",
          "text": "NSUserInterfaceLayoutDirection"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCursor",
          "text": "NSCursor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSCursorFrameResizePosition",
          "text": "FrameResizePosition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/topTrailing(relativeTo:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "topTrailing(relativeTo:)",
      "type": "topic",
      "url": "/documentation/appkit/nscursor/frameresizeposition/toptrailing(relativeto:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/trailing(relativeTo:)": {
      "abstract": [
        {
          "text": "The trailing edge of the frame, in the given user interface layout direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trailing"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "relativeTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSUserInterfaceLayoutDirection",
          "text": "NSUserInterfaceLayoutDirection"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSCursor",
          "text": "NSCursor"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSCursorFrameResizePosition",
          "text": "FrameResizePosition"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/trailing(relativeTo:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "trailing(relativeTo:)",
      "type": "topic",
      "url": "/documentation/appkit/nscursor/frameresizeposition/trailing(relativeto:)"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSCursorFrameResizeDirections": {
      "abstract": [
        {
          "text": "The directions in which a rectangular frame can be resized.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSCursorFrameResizeDirections"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSCursorFrameResizeDirections",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSCursorFrameResizeDirections",
      "type": "topic",
      "url": "/documentation/appkit/nscursorframeresizedirections"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSHorizontalDirection": {
      "abstract": [
        {
          "text": "An absolute direction on the horizontal axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSHorizontalDirection"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHorizontalDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSHorizontalDirection"
        }
      ],
      "role": "symbol",
      "title": "NSHorizontalDirection",
      "type": "topic",
      "url": "/documentation/appkit/nshorizontaldirection"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSHorizontalDirections": {
      "abstract": [
        {
          "text": "The absolute directions on the horizontal axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSHorizontalDirections"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSHorizontalDirections",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSHorizontalDirections",
      "type": "topic",
      "url": "/documentation/appkit/nshorizontaldirections"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSImage/DynamicRange": {
      "abstract": [
        {
          "text": "Describes how High Dynamic Range (HDR) image content displays.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "DynamicRange"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSImage/DynamicRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "DynamicRange"
        }
      ],
      "role": "symbol",
      "title": "NSImage.DynamicRange",
      "type": "topic",
      "url": "/documentation/appkit/nsimage/dynamicrange"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSSharingCollaborationMode": {
      "abstract": [
        {
          "text": "Represents the types of sharing (collaborating on an item vs. sending a copy of the item)",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "The share picker supports up to two modes, each of which corresponds to one of these types",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSSharingCollaborationMode"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSSharingCollaborationMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSSharingCollaborationMode"
        }
      ],
      "role": "symbol",
      "title": "NSSharingCollaborationMode",
      "type": "topic",
      "url": "/documentation/appkit/nssharingcollaborationmode"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSTextCursorAccessoryPlacement"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSTextCursorAccessoryPlacement"
        }
      ],
      "role": "symbol",
      "title": "NSTextCursorAccessoryPlacement",
      "type": "topic",
      "url": "/documentation/appkit/nstextcursoraccessoryplacement"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVerticalDirection": {
      "abstract": [
        {
          "text": "A direction on the vertical axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSVerticalDirection"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVerticalDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSVerticalDirection"
        }
      ],
      "role": "symbol",
      "title": "NSVerticalDirection",
      "type": "topic",
      "url": "/documentation/appkit/nsverticaldirection"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSVerticalDirections": {
      "abstract": [
        {
          "text": "The directions on the vertical axis.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "NSVerticalDirections"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSVerticalDirections",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSVerticalDirections",
      "type": "topic",
      "url": "/documentation/appkit/nsverticaldirections"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior": {
      "abstract": [
        {
          "text": "Constants that specify the Writing Tools experience for the underlying view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWritingToolsBehavior"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingToolsBehavior"
        }
      ],
      "role": "symbol",
      "title": "NSWritingToolsBehavior",
      "type": "topic",
      "url": "/documentation/appkit/nswritingtoolsbehavior"
    },
    "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsResultOptions": {
      "abstract": [
        {
          "text": "Constants to specify what type of content to allow in Writing Tools",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "suggestions or rewrites.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "NSWritingToolsResultOptions"
        }
      ],
      "identifier": "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsResultOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "NSWritingToolsResultOptions"
        }
      ],
      "role": "symbol",
      "title": "NSWritingToolsResultOptions",
      "type": "topic",
      "url": "/documentation/appkit/nswritingtoolsresultoptions"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@NSUInteger": {
      "abstract": [
        {
          "text": "Describes an unsigned integer.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
      "kind": "symbol",
      "role": "symbol",
      "title": "NSUInteger",
      "type": "topic",
      "url": "/documentation/objectivec/nsuinteger"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s12CaseIterableP": {
      "abstract": [
        {
          "text": "A type that provides a collection of all of its values.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CaseIterable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s12CaseIterableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "CaseIterable",
      "type": "topic",
      "url": "/documentation/Swift/CaseIterable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8CopyableP": {
      "abstract": [
        {
          "text": "A type whose values can be implicitly or explicitly copied.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8CopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Copyable",
      "type": "topic",
      "url": "/documentation/Swift/Copyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s12CaseIterableP",
        "doc://com.externally.resolved.symbol/s:s8CopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSHorizontalDirection",
        "doc://com.apple.appkit/documentation/AppKit/NSSharingCollaborationMode",
        "doc://com.apple.appkit/documentation/AppKit/NSImage/DynamicRange",
        "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement",
        "doc://com.apple.appkit/documentation/AppKit/NSVerticalDirection",
        "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior",
        "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsResultOptions"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Enumeration-Cases",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/bottom",
        "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/bottomLeft",
        "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/bottomRight",
        "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/left",
        "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/right",
        "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/top",
        "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/topLeft",
        "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/topRight"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Type-Methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/bottomLeading(relativeTo:)",
        "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/bottomTrailing(relativeTo:)",
        "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/leading(relativeTo:)",
        "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/topLeading(relativeTo:)",
        "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/topTrailing(relativeTo:)",
        "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/trailing(relativeTo:)"
      ],
      "title": "Type Methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "18.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "15.0",
              "name": "macOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "NSCursorFrameResizePosition"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCursorFrameResizePosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCursorFrameResizePosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.appkit/documentation/AppKit"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Enumeration-Cases",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/bottom",
                "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/bottomLeft",
                "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/bottomRight",
                "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/left",
                "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/right",
                "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/top",
                "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/topLeft",
                "doc://com.apple.appkit/documentation/AppKit/NSCursor/FrameResizePosition/topRight"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.appkit/documentation/AppKit/NSCursorFrameResizeDirections",
                "doc://com.apple.appkit/documentation/AppKit/NSHorizontalDirections",
                "doc://com.apple.appkit/documentation/AppKit/NSSharingCollaborationMode",
                "doc://com.apple.appkit/documentation/AppKit/NSImage/DynamicRange",
                "doc://com.apple.appkit/documentation/AppKit/NSTextCursorAccessoryPlacement",
                "doc://com.apple.appkit/documentation/AppKit/NSVerticalDirections",
                "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsBehavior",
                "doc://com.apple.appkit/documentation/AppKit/NSWritingToolsResultOptions"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "Mac Catalyst",
                  "macOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "NSCursorFrameResizePosition"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@NSUInteger",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@NSUInteger",
                    "text": "NSUInteger"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1FrameResizePosition~1left/title",
          "value": "NSCursorFrameResizePositionLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1FrameResizePosition~1left/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCursorFrameResizePositionLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextCursorAccessoryPlacement/title",
          "value": "NSTextCursorAccessoryPlacement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextCursorAccessoryPlacement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextCursorAccessoryPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSTextCursorAccessoryPlacement/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSTextCursorAccessoryPlacement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor/title",
          "value": "NSCursor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCursor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCursor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingCollaborationMode/title",
          "value": "NSSharingCollaborationMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingCollaborationMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingCollaborationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSSharingCollaborationMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSSharingCollaborationMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1FrameResizePosition~1topRight/title",
          "value": "NSCursorFrameResizePositionTopRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1FrameResizePosition~1topRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCursorFrameResizePositionTopRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1FrameResizePosition~1topLeft/title",
          "value": "NSCursorFrameResizePositionTopLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1FrameResizePosition~1topLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCursorFrameResizePositionTopLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1DynamicRange/title",
          "value": "NSImageDynamicRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1DynamicRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageDynamicRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSImage~1DynamicRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSImageDynamicRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1FrameResizePosition~1top/title",
          "value": "NSCursorFrameResizePositionTop"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1FrameResizePosition~1top/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCursorFrameResizePositionTop"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1FrameResizePosition/title",
          "value": "NSCursorFrameResizePosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1FrameResizePosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCursorFrameResizePosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1FrameResizePosition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCursorFrameResizePosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsResultOptions/title",
          "value": "NSWritingToolsResultOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsResultOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsResultOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsResultOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsResultOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1FrameResizePosition~1right/title",
          "value": "NSCursorFrameResizePositionRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1FrameResizePosition~1right/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCursorFrameResizePositionRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1FrameResizePosition~1bottomRight/title",
          "value": "NSCursorFrameResizePositionBottomRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1FrameResizePosition~1bottomRight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCursorFrameResizePositionBottomRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1FrameResizePosition~1bottom/title",
          "value": "NSCursorFrameResizePositionBottom"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1FrameResizePosition~1bottom/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCursorFrameResizePositionBottom"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1FrameResizePosition~1bottomLeft/title",
          "value": "NSCursorFrameResizePositionBottomLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1FrameResizePosition~1bottomLeft/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSCursorFrameResizePositionBottomLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsBehavior/title",
          "value": "NSWritingToolsBehavior"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsBehavior/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsBehavior"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSWritingToolsBehavior/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "NSWritingToolsBehavior"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/appkit/nscursor/frameresizeposition"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/appkit/nscursor/frameresizeposition"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
