{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nscursor/pop()-swift.type.method"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nscursor/pop()-swift.type.method"]}],"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSCursor/pop()-swift.type.method","interfaceLanguage":"swift"},"sections":[],"metadata":{"externalID":"c:objc(cs)NSCursor(cm)pop","navigatorTitle":[{"text":"pop","kind":"identifier"}],"platforms":[{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"13.0","name":"iOS"},{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"13.0","name":"iPadOS"},{"introducedAt":"13.1","deprecated":false,"beta":false,"name":"Mac Catalyst","unavailable":false},{"introducedAt":"10.0","deprecated":false,"beta":false,"name":"macOS","unavailable":false}],"roleHeading":"Type Method","symbolKind":"method","title":"pop()","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pop","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","modules":[{"name":"AppKit"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pop","kind":"identifier"},{"text":"()","kind":"text"}]}]},{"content":[{"level":2,"type":"heading","anchor":"Discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The new object on the top of the stack becomes the current cursor. If the current cursor is the only cursor on the stack, this method does nothing."}]}],"kind":"content"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSCursor"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Pops the current cursor off the top of the stack.","type":"text"}],"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCursor/pop()-swift.method","doc://com.apple.appkit/documentation/AppKit/NSCursor/push()","doc://com.apple.appkit/documentation/AppKit/NSCursor/set()","doc://com.apple.appkit/documentation/AppKit/NSCursor/mouseEntered(with:)","doc://com.apple.appkit/documentation/AppKit/NSCursor/setOnMouseEntered(_:)","doc://com.apple.appkit/documentation/AppKit/NSCursor/isSetOnMouseEntered","doc://com.apple.appkit/documentation/AppKit/NSCursor/mouseExited(with:)","doc://com.apple.appkit/documentation/AppKit/NSCursor/setOnMouseExited(_:)","doc://com.apple.appkit/documentation/AppKit/NSCursor/isSetOnMouseExited"],"generated":true,"anchor":"Controlling-Which-Cursor-Is-Current","title":"Controlling Which Cursor Is Current"}],"kind":"symbol","references":{"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSCursor/mouseEntered(with:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mouseEntered","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSEvent"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"mouseEntered:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/mouseEntered(with:)","url":"/documentation/appkit/nscursor/mouseentered(with:)","kind":"symbol","title":"mouseEntered(with:)","abstract":[{"text":"Automatically sent to the receiver when the cursor enters a cursor rectangle owned by the receiver.","type":"text"}],"deprecated":true,"role":"symbol","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSCursor/pop()-swift.type.method":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pop","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"pop","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/pop()-swift.type.method","url":"/documentation/appkit/nscursor/pop()-swift.type.method","kind":"symbol","title":"pop()","abstract":[{"text":"Pops the current cursor off the top of the stack.","type":"text"}],"role":"symbol","type":"topic"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSCursor/setOnMouseExited(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setOnMouseExited","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setOnMouseExited:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/setOnMouseExited(_:)","url":"/documentation/appkit/nscursor/setonmouseexited(_:)","kind":"symbol","title":"setOnMouseExited(_:)","abstract":[{"text":"Sets whether the receiver accepts ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/mouseExited(with:)"},{"text":" events.","type":"text"}],"deprecated":true,"role":"symbol","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSCursor/isSetOnMouseExited":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isSetOnMouseExited","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"setOnMouseExited","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/isSetOnMouseExited","url":"/documentation/appkit/nscursor/issetonmouseexited","kind":"symbol","title":"isSetOnMouseExited","abstract":[{"text":"A Boolean value indicating whether the receiver becomes current when it receives a ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/mouseExited(with:)","type":"reference","isActive":true},{"text":" message.","type":"text"}],"deprecated":true,"role":"symbol","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSCursor/pop()-swift.method":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pop","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"pop","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/pop()-swift.method","url":"/documentation/appkit/nscursor/pop()-swift.method","kind":"symbol","title":"pop()","abstract":[{"text":"Sends a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/pop()-swift.type.method"},{"text":" message to the receiver’s class.","type":"text"}],"role":"symbol","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSCursor/setOnMouseEntered(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setOnMouseEntered","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setOnMouseEntered:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/setOnMouseEntered(_:)","url":"/documentation/appkit/nscursor/setonmouseentered(_:)","kind":"symbol","title":"setOnMouseEntered(_:)","abstract":[{"text":"Specifies whether the receiver accepts ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/mouseEntered(with:)"},{"text":" events.","type":"text"}],"deprecated":true,"role":"symbol","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSCursor/set()":{"url":"/documentation/appkit/nscursor/set()","title":"set()","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"set","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/set()","abstract":[{"text":"Makes the receiver the current cursor.","type":"text"}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSCursor/isSetOnMouseEntered":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isSetOnMouseEntered","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"setOnMouseEntered","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/isSetOnMouseEntered","url":"/documentation/appkit/nscursor/issetonmouseentered","kind":"symbol","title":"isSetOnMouseEntered","abstract":[{"text":"A Boolean value indicating whether the receiver becomes current on receiving a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/mouseEntered(with:)"},{"text":" message.","type":"text"}],"deprecated":true,"role":"symbol","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSCursor/mouseExited(with:)":{"url":"/documentation/appkit/nscursor/mouseexited(with:)","title":"mouseExited(with:)","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"mouseExited:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mouseExited","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSEvent","preciseIdentifier":"c:objc(cs)NSEvent","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/mouseExited(with:)","deprecated":true,"abstract":[{"text":"Automatically sent to the receiver when the cursor exits a cursor rectangle owned by the receiver.","type":"text"}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSCursor/push()":{"url":"/documentation/appkit/nscursor/push()","title":"push()","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"push","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"push","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/push()","abstract":[{"text":"Puts the receiver on top of the cursor stack and makes it the current cursor.","type":"text"}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSCursor":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSCursor"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor","navigatorTitle":[{"kind":"identifier","text":"NSCursor"}],"abstract":[{"text":"A pointer (also called a cursor).","type":"text"}],"type":"topic","title":"NSCursor","url":"/documentation/appkit/nscursor"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","op":"replace","value":"occ"},{"path":"/metadata/platforms","op":"replace","value":[{"name":"Mac Catalyst","deprecated":false,"unavailable":false,"introducedAt":"13.1","beta":false},{"name":"macOS","deprecated":false,"unavailable":false,"introducedAt":"10.0","beta":false}]},{"path":"/metadata/roleHeading","op":"replace","value":"Type Method"},{"path":"/metadata/title","op":"replace","value":"pop"},{"value":"method","op":"replace","path":"/metadata/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"pop"}],"op":"replace","path":"/metadata/fragments"},{"value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSCursor"]]},"op":"replace","path":"/hierarchy"},{"value":null,"op":"add","path":"/topicSections"},{"op":"add","value":null,"path":"/relationshipsSections"},{"op":"replace","value":[{"generated":true,"anchor":"Controlling-Which-Cursor-Is-Current","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCursor/pop()-swift.method","doc://com.apple.appkit/documentation/AppKit/NSCursor/push()","doc://com.apple.appkit/documentation/AppKit/NSCursor/set()","doc://com.apple.appkit/documentation/AppKit/NSCursor/mouseEntered(with:)","doc://com.apple.appkit/documentation/AppKit/NSCursor/setOnMouseEntered(_:)","doc://com.apple.appkit/documentation/AppKit/NSCursor/isSetOnMouseEntered","doc://com.apple.appkit/documentation/AppKit/NSCursor/mouseExited(with:)","doc://com.apple.appkit/documentation/AppKit/NSCursor/setOnMouseExited(_:)","doc://com.apple.appkit/documentation/AppKit/NSCursor/isSetOnMouseExited"],"title":"Controlling Which Cursor Is Current"}],"path":"/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"pop","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst","macOS"],"languages":["occ"]}],"kind":"declarations"},"path":"/primaryContentSections/0"},{"value":"mouseEntered:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1mouseEntered(with:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mouseEntered:"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1mouseEntered(with:)/fragments"},{"value":"pop","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1pop()-swift.type.method/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"pop"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1pop()-swift.type.method/fragments"},{"value":"setOnMouseExited:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1setOnMouseExited(_:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setOnMouseExited:"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1setOnMouseExited(_:)/fragments"},{"value":"setOnMouseExited","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1isSetOnMouseExited/title"},{"value":[{"kind":"identifier","text":"setOnMouseExited"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1isSetOnMouseExited/fragments"},{"value":"pop","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1pop()-swift.method/title"},{"value":[{"text":"- ","kind":"text"},{"text":"pop","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1pop()-swift.method/fragments"},{"value":"setOnMouseEntered:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1setOnMouseEntered(_:)/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setOnMouseEntered:"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1setOnMouseEntered(_:)/fragments"},{"value":"set","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1set()/title"},{"value":[{"text":"- ","kind":"text"},{"text":"set","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1set()/fragments"},{"value":"setOnMouseEntered","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1isSetOnMouseEntered/title"},{"value":[{"text":"setOnMouseEntered","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1isSetOnMouseEntered/fragments"},{"value":"mouseExited:","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1mouseExited(with:)/title"},{"value":[{"text":"- ","kind":"text"},{"text":"mouseExited:","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1mouseExited(with:)/fragments"},{"value":"push","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1push()/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"push"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1push()/fragments"},{"value":"NSCursor","op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor/title"},{"value":[{"text":"NSCursor","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor/fragments"},{"value":[{"text":"NSCursor","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}