{"identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSCursor/push()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSCursor"]]},"primaryContentSections":[{"declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"push","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Puts the receiver on top of the cursor stack and makes it the current cursor."}],"metadata":{"role":"symbol","externalID":"c:objc(cs)NSCursor(im)push","platforms":[{"introducedAt":"13.0","deprecated":false,"beta":false,"name":"iOS","unavailable":false},{"introducedAt":"13.0","deprecated":false,"beta":false,"name":"iPadOS","unavailable":false},{"beta":false,"unavailable":false,"introducedAt":"13.1","deprecated":false,"name":"Mac Catalyst"},{"beta":false,"unavailable":false,"introducedAt":"10.0","deprecated":false,"name":"macOS"}],"title":"push()","navigatorTitle":[{"text":"push","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"AppKit"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"push","kind":"identifier"},{"text":"()","kind":"text"}]},"sections":[],"seeAlsoSections":[{"identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCursor/pop()-swift.type.method","doc://com.apple.appkit/documentation/AppKit/NSCursor/pop()-swift.method","doc://com.apple.appkit/documentation/AppKit/NSCursor/set()","doc://com.apple.appkit/documentation/AppKit/NSCursor/mouseEntered(with:)","doc://com.apple.appkit/documentation/AppKit/NSCursor/setOnMouseEntered(_:)","doc://com.apple.appkit/documentation/AppKit/NSCursor/isSetOnMouseEntered","doc://com.apple.appkit/documentation/AppKit/NSCursor/mouseExited(with:)","doc://com.apple.appkit/documentation/AppKit/NSCursor/setOnMouseExited(_:)","doc://com.apple.appkit/documentation/AppKit/NSCursor/isSetOnMouseExited"],"anchor":"Controlling-Which-Cursor-Is-Current","generated":true,"title":"Controlling Which Cursor Is Current"}],"variants":[{"paths":["/documentation/appkit/nscursor/push()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/appkit/nscursor/push()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.apple.appkit/documentation/AppKit/NSCursor/mouseEntered(with:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mouseEntered","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSEvent"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"mouseEntered:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/mouseEntered(with:)","url":"/documentation/appkit/nscursor/mouseentered(with:)","kind":"symbol","title":"mouseEntered(with:)","abstract":[{"text":"Automatically sent to the receiver when the cursor enters a cursor rectangle owned by the receiver.","type":"text"}],"deprecated":true,"role":"symbol","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSCursor/setOnMouseExited(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setOnMouseExited","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setOnMouseExited:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/setOnMouseExited(_:)","url":"/documentation/appkit/nscursor/setonmouseexited(_:)","kind":"symbol","title":"setOnMouseExited(_:)","abstract":[{"text":"Sets whether the receiver accepts ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/mouseExited(with:)"},{"text":" events.","type":"text"}],"deprecated":true,"role":"symbol","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSCursor/isSetOnMouseEntered":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isSetOnMouseEntered","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"setOnMouseEntered","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/isSetOnMouseEntered","url":"/documentation/appkit/nscursor/issetonmouseentered","kind":"symbol","title":"isSetOnMouseEntered","abstract":[{"text":"A Boolean value indicating whether the receiver becomes current on receiving a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/mouseEntered(with:)"},{"text":" message.","type":"text"}],"deprecated":true,"role":"symbol","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSCursor/mouseExited(with:)":{"url":"/documentation/appkit/nscursor/mouseexited(with:)","title":"mouseExited(with:)","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"mouseExited:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mouseExited","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSEvent","preciseIdentifier":"c:objc(cs)NSEvent","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/mouseExited(with:)","deprecated":true,"abstract":[{"text":"Automatically sent to the receiver when the cursor exits a cursor rectangle owned by the receiver.","type":"text"}],"type":"topic"},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSCursor/push()":{"url":"/documentation/appkit/nscursor/push()","title":"push()","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"push","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"push","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/push()","abstract":[{"text":"Puts the receiver on top of the cursor stack and makes it the current cursor.","type":"text"}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSCursor/set()":{"url":"/documentation/appkit/nscursor/set()","title":"set()","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"set","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/set()","abstract":[{"text":"Makes the receiver the current cursor.","type":"text"}],"type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSCursor/pop()-swift.type.method":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pop","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"pop","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/pop()-swift.type.method","url":"/documentation/appkit/nscursor/pop()-swift.type.method","kind":"symbol","title":"pop()","abstract":[{"text":"Pops the current cursor off the top of the stack.","type":"text"}],"role":"symbol","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSCursor":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSCursor"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor","navigatorTitle":[{"kind":"identifier","text":"NSCursor"}],"abstract":[{"text":"A pointer (also called a cursor).","type":"text"}],"type":"topic","title":"NSCursor","url":"/documentation/appkit/nscursor"},"doc://com.apple.appkit/documentation/AppKit/NSCursor/setOnMouseEntered(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setOnMouseEntered","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setOnMouseEntered:","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/setOnMouseEntered(_:)","url":"/documentation/appkit/nscursor/setonmouseentered(_:)","kind":"symbol","title":"setOnMouseEntered(_:)","abstract":[{"text":"Specifies whether the receiver accepts ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/mouseEntered(with:)"},{"text":" events.","type":"text"}],"deprecated":true,"role":"symbol","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSCursor/isSetOnMouseExited":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isSetOnMouseExited","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"setOnMouseExited","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/isSetOnMouseExited","url":"/documentation/appkit/nscursor/issetonmouseexited","kind":"symbol","title":"isSetOnMouseExited","abstract":[{"text":"A Boolean value indicating whether the receiver becomes current when it receives a ","type":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/mouseExited(with:)","type":"reference","isActive":true},{"text":" message.","type":"text"}],"deprecated":true,"role":"symbol","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSCursor/pop()-swift.method":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pop","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"pop","kind":"identifier"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/pop()-swift.method","url":"/documentation/appkit/nscursor/pop()-swift.method","kind":"symbol","title":"pop()","abstract":[{"text":"Sends a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/pop()-swift.type.method"},{"text":" message to the receiver’s class.","type":"text"}],"role":"symbol","type":"topic"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"path":"/metadata/platforms","value":[{"beta":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"13.1","unavailable":false},{"beta":false,"deprecated":false,"name":"macOS","introducedAt":"10.0","unavailable":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Instance Method","op":"replace"},{"path":"/metadata/title","value":"push","op":"replace"},{"path":"/metadata/symbolKind","value":"method","op":"replace"},{"path":"/metadata/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"push"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSCursor"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":[{"title":"Controlling Which Cursor Is Current","anchor":"Controlling-Which-Cursor-Is-Current","identifiers":["doc://com.apple.appkit/documentation/AppKit/NSCursor/pop()-swift.type.method","doc://com.apple.appkit/documentation/AppKit/NSCursor/pop()-swift.method","doc://com.apple.appkit/documentation/AppKit/NSCursor/set()","doc://com.apple.appkit/documentation/AppKit/NSCursor/mouseEntered(with:)","doc://com.apple.appkit/documentation/AppKit/NSCursor/setOnMouseEntered(_:)","doc://com.apple.appkit/documentation/AppKit/NSCursor/isSetOnMouseEntered","doc://com.apple.appkit/documentation/AppKit/NSCursor/mouseExited(with:)","doc://com.apple.appkit/documentation/AppKit/NSCursor/setOnMouseExited(_:)","doc://com.apple.appkit/documentation/AppKit/NSCursor/isSetOnMouseExited"],"generated":true}],"op":"replace"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"push"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["Mac Catalyst","macOS"]}]},"op":"replace"},{"value":"mouseEntered:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1mouseEntered(with:)/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"mouseEntered:","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1mouseEntered(with:)/fragments","op":"replace"},{"value":"setOnMouseExited:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1setOnMouseExited(_:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setOnMouseExited:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1setOnMouseExited(_:)/fragments","op":"replace"},{"value":"setOnMouseEntered","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1isSetOnMouseEntered/title","op":"replace"},{"value":[{"kind":"identifier","text":"setOnMouseEntered"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1isSetOnMouseEntered/fragments","op":"replace"},{"value":"mouseExited:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1mouseExited(with:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mouseExited:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1mouseExited(with:)/fragments","op":"replace"},{"value":"push","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1push()/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"push","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1push()/fragments","op":"replace"},{"value":"set","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1set()/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"set","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1set()/fragments","op":"replace"},{"value":"pop","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1pop()-swift.type.method/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"pop","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1pop()-swift.type.method/fragments","op":"replace"},{"value":"NSCursor","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor/title","op":"replace"},{"value":[{"text":"NSCursor","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NSCursor"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor/navigatorTitle","op":"replace"},{"value":"setOnMouseEntered:","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1setOnMouseEntered(_:)/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setOnMouseEntered:"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1setOnMouseEntered(_:)/fragments","op":"replace"},{"value":"setOnMouseExited","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1isSetOnMouseExited/title","op":"replace"},{"value":[{"kind":"identifier","text":"setOnMouseExited"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1isSetOnMouseExited/fragments","op":"replace"},{"value":"pop","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1pop()-swift.method/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"pop","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1pop()-swift.method/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}