{"abstract":[{"text":"Returns the cursor for resizing a row (horizontal divider) in the specified direction.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst","macOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rowResize","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"directions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:6AppKit19NSVerticalDirectionO","text":"NSVerticalDirection","identifier":"doc://com.apple.appkit/documentation/AppKit/NSVerticalDirection"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:6AppKit19NSVerticalDirectionO3SetV","text":"Set","identifier":"doc://com.apple.appkit/documentation/AppKit/NSVerticalDirection/Set"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCursor","text":"NSCursor","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The directions in which a row can be resized. This must not be empty."}]}],"name":"directions"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.appkit/documentation/AppKit/NSCursor/rowResize(directions:)"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSCursor"]]},"metadata":{"role":"symbol","symbolKind":"method","title":"rowResize(directions:)","roleHeading":"Type Method","extendedModule":"AppKit","externalID":"s:So8NSCursorC6AppKitE9rowResize10directionsAbC19NSVerticalDirectionO3SetV_tFZ","platforms":[{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"18.0"},{"name":"macOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"15.0"}],"modules":[{"name":"AppKit"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rowResize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"directions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:6AppKit19NSVerticalDirectionO","text":"NSVerticalDirection"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:6AppKit19NSVerticalDirectionO3SetV","text":"Set"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCursor","text":"NSCursor"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nscursor/rowresize(directions:)"]}],"references":{"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit/NSVerticalDirection":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSVerticalDirection","kind":"identifier"}],"url":"/documentation/appkit/nsverticaldirection","identifier":"doc://com.apple.appkit/documentation/AppKit/NSVerticalDirection","role":"symbol","title":"NSVerticalDirection","kind":"symbol","abstract":[{"text":"A direction on the vertical axis.","type":"text"}],"navigatorTitle":[{"text":"NSVerticalDirection","kind":"identifier"}]},"doc://com.apple.appkit/documentation/AppKit/NSVerticalDirection/Set":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Set"}],"title":"NSVerticalDirection.Set","abstract":[{"type":"text","text":"An efficient set of vertical directions."}],"url":"/documentation/appkit/nsverticaldirection/set","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Set"}],"type":"topic","identifier":"doc://com.apple.appkit/documentation/AppKit/NSVerticalDirection/Set"},"doc://com.apple.appkit/documentation/AppKit/NSCursor/rowResize(directions:)":{"kind":"symbol","abstract":[{"type":"text","text":"Returns the cursor for resizing a row (horizontal divider) in the specified direction."}],"url":"/documentation/appkit/nscursor/rowresize(directions:)","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rowResize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"directions","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:6AppKit19NSVerticalDirectionO","text":"NSVerticalDirection","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:6AppKit19NSVerticalDirectionO3SetV","text":"Set","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCursor","text":"NSCursor","kind":"typeIdentifier"}],"title":"rowResize(directions:)","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/rowResize(directions:)","type":"topic"},"doc://com.apple.appkit/documentation/AppKit/NSCursor":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSCursor"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor","navigatorTitle":[{"kind":"identifier","text":"NSCursor"}],"abstract":[{"text":"A pointer (also called a cursor).","type":"text"}],"type":"topic","title":"NSCursor","url":"/documentation/appkit/nscursor"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor/title","value":"NSCursor"},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor/fragments","value":[{"kind":"identifier","text":"NSCursor"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor/navigatorTitle","value":[{"kind":"identifier","text":"NSCursor"}]}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}