{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/appkit/nscursor/rowresize"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["/documentation/appkit/nscursor/rowresize"]}],"kind":"symbol","identifier":{"url":"doc://com.apple.appkit/documentation/AppKit/NSCursor/rowResize","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSCursor"]]},"abstract":[{"text":"Returns the cursor for resizing a row (horizontal divider) in either direction.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["Mac Catalyst","macOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"rowResize","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor","preciseIdentifier":"c:objc(cs)NSCursor","text":"NSCursor","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"metadata":{"modules":[{"name":"AppKit"}],"role":"symbol","roleHeading":"Type Property","externalID":"c:objc(cs)NSCursor(cpy)rowResizeCursor","platforms":[{"unavailable":false,"name":"iOS","deprecated":false,"introducedAt":"13.0","beta":false},{"unavailable":false,"name":"iPadOS","deprecated":false,"introducedAt":"13.0","beta":false},{"unavailable":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"18.0","beta":false},{"unavailable":false,"name":"macOS","deprecated":false,"introducedAt":"15.0","beta":false}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rowResize","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCursor","text":"NSCursor","kind":"typeIdentifier"}],"title":"rowResize","navigatorTitle":[{"text":"rowResizeCursor","kind":"identifier"}],"symbolKind":"property"},"references":{"doc://com.apple.appkit/documentation/AppKit/NSCursor/rowResize":{"url":"/documentation/appkit/nscursor/rowresize","title":"rowResize","kind":"symbol","identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor/rowResize","abstract":[{"text":"Returns the cursor for resizing a row (horizontal divider) in either direction.","type":"text"}],"navigatorTitle":[{"text":"rowResizeCursor","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rowResize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSCursor","preciseIdentifier":"c:objc(cs)NSCursor","kind":"typeIdentifier"}]},"doc://com.apple.documentation/documentation/technologies":{"identifier":"doc://com.apple.documentation/documentation/technologies","role":"overview","type":"topic","url":"/documentation/technologies","abstract":[{"type":"text","text":""}],"title":"Technologies","kind":"technologies"},"doc://com.apple.appkit/documentation/AppKit":{"kind":"symbol","url":"/documentation/appkit","title":"AppKit","type":"topic","abstract":[{"text":"Construct and manage a graphical, event-driven user interface for your macOS app.","type":"text"}],"identifier":"doc://com.apple.appkit/documentation/AppKit","role":"collection"},"doc://com.apple.appkit/documentation/AppKit/NSCursor":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSCursor"}],"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor","navigatorTitle":[{"kind":"identifier","text":"NSCursor"}],"abstract":[{"text":"A pointer (also called a cursor).","type":"text"}],"type":"topic","title":"NSCursor","url":"/documentation/appkit/nscursor"}},"variantOverrides":[{"patch":[{"path":"/identifier/interfaceLanguage","value":"occ","op":"replace"},{"path":"/metadata/platforms","value":[{"unavailable":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"18.0","beta":false},{"unavailable":false,"name":"macOS","deprecated":false,"introducedAt":"15.0","beta":false}],"op":"replace"},{"path":"/metadata/roleHeading","value":"Type Property","op":"replace"},{"path":"/metadata/title","value":"rowResizeCursor","op":"replace"},{"path":"/metadata/symbolKind","value":"property","op":"replace"},{"path":"/metadata/fragments","value":[{"text":"rowResizeCursor","kind":"identifier"}],"op":"replace"},{"path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.appkit/documentation/AppKit","doc://com.apple.appkit/documentation/AppKit/NSCursor"]]},"op":"replace"},{"path":"/topicSections","value":null,"op":"add"},{"path":"/relationshipsSections","value":null,"op":"add"},{"path":"/seeAlsoSections","value":null,"op":"add"},{"path":"/primaryContentSections/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["Mac Catalyst","macOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc://com.apple.appkit/documentation/AppKit/NSCursor","preciseIdentifier":"c:objc(cs)NSCursor","text":"NSCursor","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"rowResizeCursor","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1rowResize/title","value":"rowResizeCursor","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor~1rowResize/fragments","value":[{"text":"rowResizeCursor","kind":"identifier"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor/title","value":"NSCursor","op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor/fragments","value":[{"kind":"identifier","text":"NSCursor"}],"op":"replace"},{"path":"/references/doc:~1~1com.apple.appkit~1documentation~1AppKit~1NSCursor/navigatorTitle","value":[{"kind":"identifier","text":"NSCursor"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}