{
  "abstract": [
    {
      "text": "Perform operations on vectors that contain signed 16-bit integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/simd-library"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/16-bit-signed-integer-vectors"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "16-Bit Signed Integer Vectors"
  },
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/32-bit-signed-integer-vectors": {
      "abstract": [
        {
          "text": "Perform operations on vectors that contain signed 32-bit integer elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/32-bit-signed-integer-vectors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "32-Bit Signed Integer Vectors",
      "type": "topic",
      "url": "/documentation/accelerate/32-bit-signed-integer-vectors"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/64-bit-signed-integer-vectors": {
      "abstract": [
        {
          "text": "Perform operations on vectors that contain signed 64-bit integer elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/64-bit-signed-integer-vectors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "64-Bit Signed Integer Vectors",
      "type": "topic",
      "url": "/documentation/accelerate/64-bit-signed-integer-vectors"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/8-bit-signed-integer-vectors": {
      "abstract": [
        {
          "text": "Perform operations on vectors that contain signed 8-bit integer elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/8-bit-signed-integer-vectors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "8-Bit Signed Integer Vectors",
      "type": "topic",
      "url": "/documentation/accelerate/8-bit-signed-integer-vectors"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/simd-library": {
      "abstract": [
        {
          "text": "Perform computations on small vectors and matrices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/simd-library",
      "kind": "article",
      "role": "collectionGroup",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/accelerate/simd-library"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_packed_short16": {
      "abstract": [
        {
          "text": "A packed vector of sixteen 16-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_packed_short16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_packed_short16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_packed_short16"
        }
      ],
      "role": "symbol",
      "title": "simd_packed_short16",
      "type": "topic",
      "url": "/documentation/simd/simd_packed_short16"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_packed_short2": {
      "abstract": [
        {
          "text": "A packed vector of two 16-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_packed_short2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_packed_short2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_packed_short2"
        }
      ],
      "role": "symbol",
      "title": "simd_packed_short2",
      "type": "topic",
      "url": "/documentation/simd/simd_packed_short2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_packed_short32": {
      "abstract": [
        {
          "text": "A packed vector of thirty-two 16-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_packed_short32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_packed_short32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_packed_short32"
        }
      ],
      "role": "symbol",
      "title": "simd_packed_short32",
      "type": "topic",
      "url": "/documentation/simd/simd_packed_short32"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_packed_short4": {
      "abstract": [
        {
          "text": "A packed vector of four 16-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_packed_short4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_packed_short4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_packed_short4"
        }
      ],
      "role": "symbol",
      "title": "simd_packed_short4",
      "type": "topic",
      "url": "/documentation/simd/simd_packed_short4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_packed_short8": {
      "abstract": [
        {
          "text": "A packed vector of eight 16-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_packed_short8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_packed_short8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_packed_short8"
        }
      ],
      "role": "symbol",
      "title": "simd_packed_short8",
      "type": "topic",
      "url": "/documentation/simd/simd_packed_short8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short1": {
      "abstract": [
        {
          "text": "A vector of one 16-bit signed integer element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_short1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_short1"
        }
      ],
      "role": "symbol",
      "title": "simd_short1",
      "type": "topic",
      "url": "/documentation/simd/simd_short1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short16": {
      "abstract": [
        {
          "text": "A vector of sixteen 16-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_short16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_short16"
        }
      ],
      "role": "symbol",
      "title": "simd_short16",
      "type": "topic",
      "url": "/documentation/simd/simd_short16"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short2": {
      "abstract": [
        {
          "text": "A vector of two 16-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_short2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_short2"
        }
      ],
      "role": "symbol",
      "title": "simd_short2",
      "type": "topic",
      "url": "/documentation/simd/simd_short2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short3": {
      "abstract": [
        {
          "text": "A vector of three 16-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_short3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_short3"
        }
      ],
      "role": "symbol",
      "title": "simd_short3",
      "type": "topic",
      "url": "/documentation/simd/simd_short3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short32": {
      "abstract": [
        {
          "text": "A vector of thirty-two 16-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_short32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_short32"
        }
      ],
      "role": "symbol",
      "title": "simd_short32",
      "type": "topic",
      "url": "/documentation/simd/simd_short32"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short4": {
      "abstract": [
        {
          "text": "A vector of four 16-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_short4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_short4"
        }
      ],
      "role": "symbol",
      "title": "simd_short4",
      "type": "topic",
      "url": "/documentation/simd/simd_short4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_short8": {
      "abstract": [
        {
          "text": "A vector of eight 16-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_short8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_short8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_short8"
        }
      ],
      "role": "symbol",
      "title": "simd_short8",
      "type": "topic",
      "url": "/documentation/simd/simd_short8"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Signed-Integer-Vectors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/8-bit-signed-integer-vectors",
        "doc://com.apple.accelerate/documentation/Accelerate/32-bit-signed-integer-vectors",
        "doc://com.apple.accelerate/documentation/Accelerate/64-bit-signed-integer-vectors"
      ],
      "title": "Signed Integer Vectors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Vector-Data-Types",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_short1",
        "doc://com.apple.accelerate/documentation/simd/simd_short2",
        "doc://com.apple.accelerate/documentation/simd/simd_short3",
        "doc://com.apple.accelerate/documentation/simd/simd_short4",
        "doc://com.apple.accelerate/documentation/simd/simd_short8",
        "doc://com.apple.accelerate/documentation/simd/simd_short16",
        "doc://com.apple.accelerate/documentation/simd/simd_short32"
      ],
      "title": "Vector Data Types"
    },
    {
      "anchor": "Packed-Vector-Data-Types",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_packed_short2",
        "doc://com.apple.accelerate/documentation/simd/simd_packed_short4",
        "doc://com.apple.accelerate/documentation/simd/simd_packed_short8",
        "doc://com.apple.accelerate/documentation/simd/simd_packed_short16",
        "doc://com.apple.accelerate/documentation/simd/simd_packed_short32"
      ],
      "title": "Packed Vector Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_short2/title",
          "value": "simd_packed_short2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_short2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_packed_short2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_short2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_packed_short2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_short32/title",
          "value": "simd_packed_short32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_short32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_packed_short32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_short32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_packed_short32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short4/title",
          "value": "simd_short4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short2/title",
          "value": "simd_short2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_short16/title",
          "value": "simd_packed_short16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_short16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_packed_short16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_short16/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_packed_short16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short3/title",
          "value": "simd_short3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short16/title",
          "value": "simd_short16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short16/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_short4/title",
          "value": "simd_packed_short4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_short4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_packed_short4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_short4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_packed_short4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short1/title",
          "value": "simd_short1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short1/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short8/title",
          "value": "simd_short8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short32/title",
          "value": "simd_short32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_short32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_short32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_short8/title",
          "value": "simd_packed_short8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_short8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_packed_short8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_short8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_packed_short8"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
