{
  "abstract": [
    {
      "text": "Perform operations on vectors that contain unsigned 64-bit integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/simd-library"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/64-bit-unsigned-integer-vectors"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "64-Bit Unsigned Integer Vectors"
  },
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/16-bit-unsigned-integer-vectors": {
      "abstract": [
        {
          "text": "Perform operations on vectors that contain unsigned 16-bit integer elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/16-bit-unsigned-integer-vectors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "16-Bit Unsigned Integer Vectors",
      "type": "topic",
      "url": "/documentation/accelerate/16-bit-unsigned-integer-vectors"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/32-bit-unsigned-integer-vectors": {
      "abstract": [
        {
          "text": "Perform operations on vectors that contain unsigned 32-bit integer elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/32-bit-unsigned-integer-vectors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "32-Bit Unsigned Integer Vectors",
      "type": "topic",
      "url": "/documentation/accelerate/32-bit-unsigned-integer-vectors"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/8-bit-unsigned-integer-vectors": {
      "abstract": [
        {
          "text": "Perform operations on vectors that contain unsigned 8-bit integer elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/8-bit-unsigned-integer-vectors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "8-Bit Unsigned Integer Vectors",
      "type": "topic",
      "url": "/documentation/accelerate/8-bit-unsigned-integer-vectors"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/simd-library": {
      "abstract": [
        {
          "text": "Perform computations on small vectors and matrices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/simd-library",
      "kind": "article",
      "role": "collectionGroup",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/accelerate/simd-library"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_packed_ulong2": {
      "abstract": [
        {
          "text": "A packed vector of two 64-bit unsigned integer element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_packed_ulong2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_packed_ulong2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_packed_ulong2"
        }
      ],
      "role": "symbol",
      "title": "simd_packed_ulong2",
      "type": "topic",
      "url": "/documentation/simd/simd_packed_ulong2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_packed_ulong4": {
      "abstract": [
        {
          "text": "A packed vector of four 64-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_packed_ulong4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_packed_ulong4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_packed_ulong4"
        }
      ],
      "role": "symbol",
      "title": "simd_packed_ulong4",
      "type": "topic",
      "url": "/documentation/simd/simd_packed_ulong4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_packed_ulong8": {
      "abstract": [
        {
          "text": "A packed vector of eight 64-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_packed_ulong8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_packed_ulong8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_packed_ulong8"
        }
      ],
      "role": "symbol",
      "title": "simd_packed_ulong8",
      "type": "topic",
      "url": "/documentation/simd/simd_packed_ulong8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong1": {
      "abstract": [
        {
          "text": "A vector of one 64-bit unsigned integer element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ulong1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ulong1"
        }
      ],
      "role": "symbol",
      "title": "simd_ulong1",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong2": {
      "abstract": [
        {
          "text": "A vector of two 64-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ulong2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ulong2"
        }
      ],
      "role": "symbol",
      "title": "simd_ulong2",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong3": {
      "abstract": [
        {
          "text": "A vector of three 64-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ulong3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ulong3"
        }
      ],
      "role": "symbol",
      "title": "simd_ulong3",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong4": {
      "abstract": [
        {
          "text": "A vector of four 64-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ulong4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ulong4"
        }
      ],
      "role": "symbol",
      "title": "simd_ulong4",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_ulong8": {
      "abstract": [
        {
          "text": "A vector of eight 64-bit unsigned integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_ulong8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_ulong8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_ulong8"
        }
      ],
      "role": "symbol",
      "title": "simd_ulong8",
      "type": "topic",
      "url": "/documentation/simd/simd_ulong8"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Unsigned-Integer-Vectors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/8-bit-unsigned-integer-vectors",
        "doc://com.apple.accelerate/documentation/Accelerate/16-bit-unsigned-integer-vectors",
        "doc://com.apple.accelerate/documentation/Accelerate/32-bit-unsigned-integer-vectors"
      ],
      "title": "Unsigned Integer Vectors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Vector-Data-Types",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_ulong1",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong2",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong3",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong4",
        "doc://com.apple.accelerate/documentation/simd/simd_ulong8"
      ],
      "title": "Vector Data Types"
    },
    {
      "anchor": "Packed-Vector-Data-Types",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_packed_ulong2",
        "doc://com.apple.accelerate/documentation/simd/simd_packed_ulong4",
        "doc://com.apple.accelerate/documentation/simd/simd_packed_ulong8"
      ],
      "title": "Packed Vector Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong2/title",
          "value": "simd_ulong2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_ulong2/title",
          "value": "simd_packed_ulong2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_ulong2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_packed_ulong2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_ulong2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_packed_ulong2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong3/title",
          "value": "simd_ulong3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong1/title",
          "value": "simd_ulong1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong1/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong4/title",
          "value": "simd_ulong4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong8/title",
          "value": "simd_ulong8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_ulong8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_ulong8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_ulong4/title",
          "value": "simd_packed_ulong4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_ulong4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_packed_ulong4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_ulong4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_packed_ulong4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_ulong8/title",
          "value": "simd_packed_ulong8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_ulong8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_packed_ulong8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_ulong8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_packed_ulong8"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
