{
  "abstract": [
    {
      "text": "Perform operations on vectors that contain signed 8-bit integer elements.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.accelerate/documentation/Accelerate",
        "doc://com.apple.accelerate/documentation/Accelerate/simd-library"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.accelerate/documentation/Accelerate/8-bit-signed-integer-vectors"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Accelerate"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "8-Bit Signed Integer Vectors"
  },
  "references": {
    "doc://com.apple.accelerate/documentation/Accelerate": {
      "abstract": [
        {
          "text": "Make large-scale mathematical computations and image calculations, optimized for high performance and low energy consumption.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate",
      "kind": "symbol",
      "role": "collection",
      "title": "Accelerate",
      "type": "topic",
      "url": "/documentation/accelerate"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/16-bit-signed-integer-vectors": {
      "abstract": [
        {
          "text": "Perform operations on vectors that contain signed 16-bit integer elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/16-bit-signed-integer-vectors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "16-Bit Signed Integer Vectors",
      "type": "topic",
      "url": "/documentation/accelerate/16-bit-signed-integer-vectors"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/32-bit-signed-integer-vectors": {
      "abstract": [
        {
          "text": "Perform operations on vectors that contain signed 32-bit integer elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/32-bit-signed-integer-vectors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "32-Bit Signed Integer Vectors",
      "type": "topic",
      "url": "/documentation/accelerate/32-bit-signed-integer-vectors"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/64-bit-signed-integer-vectors": {
      "abstract": [
        {
          "text": "Perform operations on vectors that contain signed 64-bit integer elements.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/64-bit-signed-integer-vectors",
      "kind": "article",
      "role": "collectionGroup",
      "title": "64-Bit Signed Integer Vectors",
      "type": "topic",
      "url": "/documentation/accelerate/64-bit-signed-integer-vectors"
    },
    "doc://com.apple.accelerate/documentation/Accelerate/simd-library": {
      "abstract": [
        {
          "text": "Perform computations on small vectors and matrices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/Accelerate/simd-library",
      "kind": "article",
      "role": "collectionGroup",
      "title": "simd",
      "type": "topic",
      "url": "/documentation/accelerate/simd-library"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char1": {
      "abstract": [
        {
          "text": "A vector of one 8-bit signed integer element.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char1"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char1"
        }
      ],
      "role": "symbol",
      "title": "simd_char1",
      "type": "topic",
      "url": "/documentation/simd/simd_char1"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char16": {
      "abstract": [
        {
          "text": "A vector of sixteen 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char16"
        }
      ],
      "role": "symbol",
      "title": "simd_char16",
      "type": "topic",
      "url": "/documentation/simd/simd_char16"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char2": {
      "abstract": [
        {
          "text": "A vector of two 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char2"
        }
      ],
      "role": "symbol",
      "title": "simd_char2",
      "type": "topic",
      "url": "/documentation/simd/simd_char2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char3": {
      "abstract": [
        {
          "text": "A vector of three 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char3"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char3",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char3"
        }
      ],
      "role": "symbol",
      "title": "simd_char3",
      "type": "topic",
      "url": "/documentation/simd/simd_char3"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char32": {
      "abstract": [
        {
          "text": "A vector of thirty-two 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char32"
        }
      ],
      "role": "symbol",
      "title": "simd_char32",
      "type": "topic",
      "url": "/documentation/simd/simd_char32"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char4": {
      "abstract": [
        {
          "text": "A vector of four 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char4"
        }
      ],
      "role": "symbol",
      "title": "simd_char4",
      "type": "topic",
      "url": "/documentation/simd/simd_char4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char64": {
      "abstract": [
        {
          "text": "A vector of sixty-four 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char64"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char64",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char64"
        }
      ],
      "role": "symbol",
      "title": "simd_char64",
      "type": "topic",
      "url": "/documentation/simd/simd_char64"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_char8": {
      "abstract": [
        {
          "text": "A vector of eight 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_char8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_char8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_char8"
        }
      ],
      "role": "symbol",
      "title": "simd_char8",
      "type": "topic",
      "url": "/documentation/simd/simd_char8"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_packed_char16": {
      "abstract": [
        {
          "text": "A packed vector of sixteen 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_packed_char16"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_packed_char16",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_packed_char16"
        }
      ],
      "role": "symbol",
      "title": "simd_packed_char16",
      "type": "topic",
      "url": "/documentation/simd/simd_packed_char16"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_packed_char2": {
      "abstract": [
        {
          "text": "A packed vector of two 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_packed_char2"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_packed_char2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_packed_char2"
        }
      ],
      "role": "symbol",
      "title": "simd_packed_char2",
      "type": "topic",
      "url": "/documentation/simd/simd_packed_char2"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_packed_char32": {
      "abstract": [
        {
          "text": "A packed vector of thirty-two 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_packed_char32"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_packed_char32",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_packed_char32"
        }
      ],
      "role": "symbol",
      "title": "simd_packed_char32",
      "type": "topic",
      "url": "/documentation/simd/simd_packed_char32"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_packed_char4": {
      "abstract": [
        {
          "text": "A packed vector of four 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_packed_char4"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_packed_char4",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_packed_char4"
        }
      ],
      "role": "symbol",
      "title": "simd_packed_char4",
      "type": "topic",
      "url": "/documentation/simd/simd_packed_char4"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_packed_char64": {
      "abstract": [
        {
          "text": "A packed vector of sixty-four 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_packed_char64"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_packed_char64",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_packed_char64"
        }
      ],
      "role": "symbol",
      "title": "simd_packed_char64",
      "type": "topic",
      "url": "/documentation/simd/simd_packed_char64"
    },
    "doc://com.apple.accelerate/documentation/simd/simd_packed_char8": {
      "abstract": [
        {
          "text": "A packed vector of eight 8-bit signed integer elements.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "simd_packed_char8"
        }
      ],
      "identifier": "doc://com.apple.accelerate/documentation/simd/simd_packed_char8",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "simd_packed_char8"
        }
      ],
      "role": "symbol",
      "title": "simd_packed_char8",
      "type": "topic",
      "url": "/documentation/simd/simd_packed_char8"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Signed-Integer-Vectors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.accelerate/documentation/Accelerate/16-bit-signed-integer-vectors",
        "doc://com.apple.accelerate/documentation/Accelerate/32-bit-signed-integer-vectors",
        "doc://com.apple.accelerate/documentation/Accelerate/64-bit-signed-integer-vectors"
      ],
      "title": "Signed Integer Vectors"
    }
  ],
  "topicSections": [
    {
      "anchor": "Vector-Data-Types",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_char1",
        "doc://com.apple.accelerate/documentation/simd/simd_char2",
        "doc://com.apple.accelerate/documentation/simd/simd_char3",
        "doc://com.apple.accelerate/documentation/simd/simd_char4",
        "doc://com.apple.accelerate/documentation/simd/simd_char8",
        "doc://com.apple.accelerate/documentation/simd/simd_char16",
        "doc://com.apple.accelerate/documentation/simd/simd_char32",
        "doc://com.apple.accelerate/documentation/simd/simd_char64"
      ],
      "title": "Vector Data Types"
    },
    {
      "anchor": "Packed-Vector-Data-Types",
      "identifiers": [
        "doc://com.apple.accelerate/documentation/simd/simd_packed_char2",
        "doc://com.apple.accelerate/documentation/simd/simd_packed_char4",
        "doc://com.apple.accelerate/documentation/simd/simd_packed_char8",
        "doc://com.apple.accelerate/documentation/simd/simd_packed_char16",
        "doc://com.apple.accelerate/documentation/simd/simd_packed_char32",
        "doc://com.apple.accelerate/documentation/simd/simd_packed_char64"
      ],
      "title": "Packed Vector Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char4/title",
          "value": "simd_char4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char16/title",
          "value": "simd_char16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char16/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_char8/title",
          "value": "simd_packed_char8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_char8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_packed_char8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_char8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_packed_char8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_char4/title",
          "value": "simd_packed_char4"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_char4/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_packed_char4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_char4/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_packed_char4"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char8/title",
          "value": "simd_char8"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char8/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char8/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char8"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_char32/title",
          "value": "simd_packed_char32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_char32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_packed_char32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_char32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_packed_char32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char32/title",
          "value": "simd_char32"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char32/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char32/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char32"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char64/title",
          "value": "simd_char64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char64/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char64/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_char2/title",
          "value": "simd_packed_char2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_char2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_packed_char2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_char2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_packed_char2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char3/title",
          "value": "simd_char3"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char3/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char3/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char3"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_char64/title",
          "value": "simd_packed_char64"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_char64/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_packed_char64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_char64/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_packed_char64"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_char16/title",
          "value": "simd_packed_char16"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_char16/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_packed_char16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_packed_char16/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_packed_char16"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char2/title",
          "value": "simd_char2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char2/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char1/title",
          "value": "simd_char1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.accelerate~1documentation~1simd~1simd_char1/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "simd_char1"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
