{
  "abstract": [
    {
      "text": "Replaces values in the noise field by applying a randomized distortion effect.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.gameplaykit/documentation/GameplayKit",
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoise"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoise/applyTurbulence(frequency:power:roughness:seed:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)GKNoise(im)applyTurbulenceWithFrequency:power:roughness:seed:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "applyTurbulence"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "frequency"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sd",
        "text": "Double"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "power"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sd",
        "text": "Double"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "roughness"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int32V",
        "text": "Int32"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "seed"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s5Int32V",
        "text": "Int32"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "GameplayKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "applyTurbulenceWithFrequency:power:roughness:seed:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "applyTurbulence(frequency:power:roughness:seed:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "applyTurbulence"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "frequency"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sd",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sd",
              "text": "Double"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "power"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sd",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sd",
              "text": "Double"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "roughness"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int32V",
              "text": "Int32"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "seed"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s5Int32V",
              "text": "Int32"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A value that determines how often (per unit area) the amount of distortion changes.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "frequency"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A value that determines the magnitude of distortion applied.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "power"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A value that determines the rate of change in distortion amounts over the noise field. Lower values result in smooth transitions between more-distorted and less-distorted regions; higher values result in rapid, rough transitions.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "roughness"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A value that governs the randomization of the turbulence effect. Passing the same seed value for multiple calls to this method results in the same general structure of turbulence (modulated by the other parameters).",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "seed"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Applying turbulence randomly distorts areas of the noise field, resulting in more natural-looking textures. This method is equivalent to using the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoise/displaceWithNoises(x:y:z:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " method with three noise fields generated by the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKPerlinNoiseSource",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " class.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "identifier": "media-2556422",
              "type": "image"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The ",
              "type": "text"
            },
            {
              "code": "frequency",
              "type": "codeVoice"
            },
            {
              "text": " and ",
              "type": "text"
            },
            {
              "code": "power",
              "type": "codeVoice"
            },
            {
              "text": " parameters are closely related:",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "items": [
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Low frequency and low power results in very minor changes to the original noise field.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "Low frequency and high power adds elongated, twisting features to the original noise field.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "High frequency and low power results in a rougher version of the original noise field.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            },
            {
              "content": [
                {
                  "inlineContent": [
                    {
                      "text": "High frequency and high power tend toward completely random noise.",
                      "type": "text"
                    }
                  ],
                  "type": "paragraph"
                }
              ]
            }
          ],
          "type": "unorderedList"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "For natural-looking results when applying turbulence to ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCoherentNoiseSource",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " output, start with a ",
                  "type": "text"
                },
                {
                  "code": "frequency",
                  "type": "codeVoice"
                },
                {
                  "text": " parameter 2-4 times the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCoherentNoiseSource/frequency",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " value of the noise source and a ",
                  "type": "text"
                },
                {
                  "code": "power",
                  "type": "codeVoice"
                },
                {
                  "text": " parameter that is the reciprocal of that frequency. Then experiment with slight variations to each parameter to find a desired effect.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Tip",
          "style": "tip",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit": {
      "abstract": [
        {
          "text": "Architect and organize your game logic. Incorporate common gameplay behaviors such as random number generation, artificial intelligence, pathfinding, and agent behavior.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit",
      "kind": "symbol",
      "role": "collection",
      "title": "GameplayKit",
      "type": "topic",
      "url": "/documentation/gameplaykit"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCoherentNoiseSource": {
      "abstract": [
        {
          "text": "The abstract superclass for procedural noise generators that create coherent noise.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKCoherentNoiseSource"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCoherentNoiseSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKCoherentNoiseSource"
        }
      ],
      "role": "symbol",
      "title": "GKCoherentNoiseSource",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkcoherentnoisesource"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCoherentNoiseSource/frequency": {
      "abstract": [
        {
          "text": "A value that determines the size and spacing of features in generated noise.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "frequency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKCoherentNoiseSource/frequency",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "frequency"
        }
      ],
      "role": "symbol",
      "title": "frequency",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkcoherentnoisesource/frequency"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoise": {
      "abstract": [
        {
          "text": "A representation of procedural noise, generated by a noise source, that you can use to process, transform, or combine noise.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKNoise"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoise",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKNoise"
        }
      ],
      "role": "symbol",
      "title": "GKNoise",
      "type": "topic",
      "url": "/documentation/gameplaykit/gknoise"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoise/applyTurbulence(frequency:power:roughness:seed:)": {
      "abstract": [
        {
          "text": "Replaces values in the noise field by applying a randomized distortion effect.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "applyTurbulence"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "frequency"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "power"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "roughness"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "seed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoise/applyTurbulence(frequency:power:roughness:seed:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "applyTurbulenceWithFrequency:power:roughness:seed:"
        }
      ],
      "role": "symbol",
      "title": "applyTurbulence(frequency:power:roughness:seed:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gknoise/applyturbulence(frequency:power:roughness:seed:)"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoise/displaceWithNoises(x:y:z:)": {
      "abstract": [
        {
          "text": "Replaces values in the noise field by shifting each value along a vector whose x-, y-, and z-components are based on the specified noise objects.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "displaceWithNoises"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "x"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKNoise",
          "text": "GKNoise"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "y"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKNoise",
          "text": "GKNoise"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "z"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)GKNoise",
          "text": "GKNoise"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoise/displaceWithNoises(x:y:z:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "displaceXWithNoise:yWithNoise:zWithNoise:"
        }
      ],
      "role": "symbol",
      "title": "displaceWithNoises(x:y:z:)",
      "type": "topic",
      "url": "/documentation/gameplaykit/gknoise/displacewithnoises(x:y:z:)"
    },
    "doc://com.apple.gameplaykit/documentation/GameplayKit/GKPerlinNoiseSource": {
      "abstract": [
        {
          "text": "A procedural noise generator whose output is a type of fractal coherent noise resembling natural phenomena such as clouds and terrain.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "GKPerlinNoiseSource"
        }
      ],
      "identifier": "doc://com.apple.gameplaykit/documentation/GameplayKit/GKPerlinNoiseSource",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "GKPerlinNoiseSource"
        }
      ],
      "role": "symbol",
      "title": "GKPerlinNoiseSource",
      "type": "topic",
      "url": "/documentation/gameplaykit/gkperlinnoisesource"
    },
    "doc://com.externally.resolved.symbol/c:@T@int32_t": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@int32_t",
      "kind": "symbol",
      "role": "symbol",
      "title": "int32_t",
      "type": "topic",
      "url": "/documentation/kernel/int32_t"
    },
    "doc://com.externally.resolved.symbol/s:Sd": {
      "abstract": [
        {
          "text": "A double-precision, floating-point value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sd",
      "kind": "symbol",
      "role": "symbol",
      "title": "Double",
      "type": "topic",
      "url": "/documentation/Swift/Double"
    },
    "doc://com.externally.resolved.symbol/s:s5Int32V": {
      "abstract": [
        {
          "text": "A 32-bit signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s5Int32V",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int32",
      "type": "topic",
      "url": "/documentation/Swift/Int32"
    },
    "media-2556422": {
      "alt": null,
      "identifier": "media-2556422",
      "type": "image",
      "variants": [
        {
          "traits": [
            "2x",
            "light"
          ],
          "url": "https://docs-assets.developer.apple.com/published/6d77c5b670ed4503998961a256c676a2/media-2556422@2x.png"
        }
      ]
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Applying-Operations-that-Distort-Noise",
      "generated": true,
      "identifiers": [
        "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoise/displaceWithNoises(x:y:z:)"
      ],
      "title": "Applying Operations that Distort Noise"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "applyTurbulenceWithFrequency:power:roughness:seed:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "applyTurbulenceWithFrequency:power:roughness:seed:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.gameplaykit/documentation/GameplayKit",
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoise"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Applying-Operations-that-Distort-Noise",
              "generated": true,
              "identifiers": [
                "doc://com.apple.gameplaykit/documentation/GameplayKit/GKNoise/displaceWithNoises(x:y:z:)"
              ],
              "title": "Applying Operations that Distort Noise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "applyTurbulenceWithFrequency:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:d",
                    "text": "double"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "frequency"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "power:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:d",
                    "text": "double"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "power"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "roughness:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:I",
                    "text": "int"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "roughness"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "seed:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@int32_t",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@int32_t",
                    "text": "int32_t"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "internalParam",
                    "text": "seed"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A value that determines how often (per unit area) the amount of distortion changes.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "frequency"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A value that determines the magnitude of distortion applied.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "power"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A value that determines the rate of change in distortion amounts over the noise field. Lower values result in smooth transitions between more-distorted and less-distorted regions; higher values result in rapid, rough transitions.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "roughness"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A value that governs the randomization of the turbulence effect. Passing the same seed value for multiple calls to this method results in the same general structure of turbulence (modulated by the other parameters).",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "seed"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKCoherentNoiseSource/title",
          "value": "GKCoherentNoiseSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKCoherentNoiseSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKCoherentNoiseSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKCoherentNoiseSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKCoherentNoiseSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKCoherentNoiseSource~1frequency/title",
          "value": "frequency"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKCoherentNoiseSource~1frequency/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "frequency"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKNoise/title",
          "value": "GKNoise"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKNoise/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKNoise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKNoise/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKNoise"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKNoise~1displaceWithNoises(x:y:z:)/title",
          "value": "displaceXWithNoise:yWithNoise:zWithNoise:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKNoise~1displaceWithNoises(x:y:z:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "displaceXWithNoise:yWithNoise:zWithNoise:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKNoise~1applyTurbulence(frequency:power:roughness:seed:)/title",
          "value": "applyTurbulenceWithFrequency:power:roughness:seed:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKNoise~1applyTurbulence(frequency:power:roughness:seed:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "applyTurbulenceWithFrequency:power:roughness:seed:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKPerlinNoiseSource/title",
          "value": "GKPerlinNoiseSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKPerlinNoiseSource/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "GKPerlinNoiseSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.gameplaykit~1documentation~1GameplayKit~1GKPerlinNoiseSource/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "GKPerlinNoiseSource"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/gameplaykit/gknoise/applyturbulence(frequency:power:roughness:seed:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/gameplaykit/gknoise/applyturbulence(frequency:power:roughness:seed:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
