{
  "abstract": [
    {
      "text": "Add additional accessibility information to the view.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Using non-localized strings for labels is not directly supported. Instead, wrap both the label and the value in a Text struct.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.FamilyControls/documentation/FamilyControls",
        "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker/accessibilityCustomContent(_:_:importance:)-8480d"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "extendedModule": "SwiftUI",
    "externalID": "s:7SwiftUI4ViewPAAE26accessibilityCustomContent__10importanceAA08ModifiedF0VyxAA31AccessibilityAttachmentModifierVGqd___qd_0_So08AXCustomF10ImportanceVtSyRd__SyRd_0_r0_lF::SYNTHESIZED::s:14FamilyControls0A14ActivityPickerV",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "accessibilityCustomContent"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "genericParameter",
        "text": "L"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "genericParameter",
        "text": "V"
      },
      {
        "kind": "text",
        "text": ">("
      },
      {
        "kind": "typeIdentifier",
        "text": "L"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "text": "V"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "importance"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)AXCustomContent",
        "text": "AXCustomContent"
      },
      {
        "kind": "text",
        "text": "."
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@AXCustomContentImportance",
        "text": "Importance"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:7SwiftUI15ModifiedContentV",
        "text": "ModifiedContent"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "text": "Self"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:7SwiftUI31AccessibilityAttachmentModifierV",
        "text": "AccessibilityAttachmentModifier"
      },
      {
        "kind": "text",
        "text": ">"
      }
    ],
    "modules": [
      {
        "name": "FamilyControls",
        "relatedModules": [
          "SwiftUI"
        ]
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "15.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "accessibilityCustomContent(_:_:importance:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "nonisolated"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "accessibilityCustomContent"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "kind": "genericParameter",
              "text": "L"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "genericParameter",
              "text": "V"
            },
            {
              "kind": "text",
              "text": ">("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "label"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "text": "L"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "value"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "typeIdentifier",
              "text": "V"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "importance"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)AXCustomContent",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)AXCustomContent",
              "text": "AXCustomContent"
            },
            {
              "kind": "text",
              "text": "."
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@E@AXCustomContentImportance",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@AXCustomContentImportance",
              "text": "Importance"
            },
            {
              "kind": "text",
              "text": " = .default) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:7SwiftUI15ModifiedContentV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:7SwiftUI15ModifiedContentV",
              "text": "ModifiedContent"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "kind": "typeIdentifier",
              "text": "Self"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:7SwiftUI31AccessibilityAttachmentModifierV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:7SwiftUI31AccessibilityAttachmentModifierV",
              "text": "AccessibilityAttachmentModifier"
            },
            {
              "kind": "text",
              "text": "> "
            },
            {
              "kind": "keyword",
              "text": "where"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "typeIdentifier",
              "text": "L"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sy",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sy",
              "text": "StringProtocol"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "typeIdentifier",
              "text": "V"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sy",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sy",
              "text": "StringProtocol"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Localized text describing to the user what",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "is contained in this additional information entry. For example:",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "“orientation”.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "label"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Text value for the additional accessibility",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "information. For example: “landscape.”",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "value"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Importance of the accessibility information.",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "High-importance information gets read out immediately, while",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "default-importance information must be explicitly asked for by the",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "user.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "importance"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use this method to add information you want accessibility users to be",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "able to access about this element, beyond the basics of label, value,",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "and hint. For example, ",
              "type": "text"
            },
            {
              "code": "accessibilityCustomContent",
              "type": "codeVoice"
            },
            {
              "text": " can be used to add",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "information about the orientation of a photograph, or the number of",
              "type": "text"
            },
            {
              "text": " ",
              "type": "text"
            },
            {
              "text": "people found in the picture.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "Repeated calls of ",
                  "type": "text"
                },
                {
                  "code": "accessibilityCustomContent",
                  "type": "codeVoice"
                },
                {
                  "text": " with different",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "labels will create new entries of additional information. Calling",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "code": "accessibilityAdditionalContent",
                  "type": "codeVoice"
                },
                {
                  "text": " repeatedly with the same label will",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "instead replace the previous value and importance.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Note",
          "style": "note",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.FamilyControls/documentation/FamilyControls": {
      "abstract": [
        {
          "text": "Authorize your app to provide parental controls on a device.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.FamilyControls/documentation/FamilyControls",
      "kind": "symbol",
      "role": "collection",
      "title": "FamilyControls",
      "type": "topic",
      "url": "/documentation/familycontrols"
    },
    "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker": {
      "abstract": [
        {
          "text": "A view in which users specify applications, web domains,",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "and categories without revealing their choices to the app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FamilyActivityPicker"
        }
      ],
      "identifier": "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FamilyActivityPicker"
        }
      ],
      "role": "symbol",
      "title": "FamilyActivityPicker",
      "type": "topic",
      "url": "/documentation/familycontrols/familyactivitypicker"
    },
    "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker/accessibility(activationPoint:)-34miz": {
      "abstract": [
        {
          "text": "Specifies the point where activations occur in the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibility"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "activationPoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI15ModifiedContentV",
          "text": "ModifiedContent"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI31AccessibilityAttachmentModifierV",
          "text": "AccessibilityAttachmentModifier"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker/accessibility(activationPoint:)-34miz",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibility(activationPoint:)",
      "type": "topic",
      "url": "/documentation/familycontrols/familyactivitypicker/accessibility(activationpoint:)-34miz"
    },
    "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker/accessibility(activationPoint:)-ci2b": {
      "abstract": [
        {
          "text": "Specifies the unit point where activations occur in the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibility"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "activationPoint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI9UnitPointV",
          "text": "UnitPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI15ModifiedContentV",
          "text": "ModifiedContent"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI31AccessibilityAttachmentModifierV",
          "text": "AccessibilityAttachmentModifier"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker/accessibility(activationPoint:)-ci2b",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibility(activationPoint:)",
      "type": "topic",
      "url": "/documentation/familycontrols/familyactivitypicker/accessibility(activationpoint:)-ci2b"
    },
    "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker/accessibility(addTraits:)": {
      "abstract": [
        {
          "text": "Adds the given traits to the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibility"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "addTraits"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI19AccessibilityTraitsV",
          "text": "AccessibilityTraits"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI15ModifiedContentV",
          "text": "ModifiedContent"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI31AccessibilityAttachmentModifierV",
          "text": "AccessibilityAttachmentModifier"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker/accessibility(addTraits:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibility(addTraits:)",
      "type": "topic",
      "url": "/documentation/familycontrols/familyactivitypicker/accessibility(addtraits:)"
    },
    "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker/accessibility(hidden:)": {
      "abstract": [
        {
          "text": "Specifies whether to hide this view from system accessibility features.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibility"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "hidden"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI15ModifiedContentV",
          "text": "ModifiedContent"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI31AccessibilityAttachmentModifierV",
          "text": "AccessibilityAttachmentModifier"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker/accessibility(hidden:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibility(hidden:)",
      "type": "topic",
      "url": "/documentation/familycontrols/familyactivitypicker/accessibility(hidden:)"
    },
    "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker/accessibility(hint:)": {
      "abstract": [
        {
          "text": "Communicates to the user what happens after performing the view’s",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "action.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibility"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "hint"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4TextV",
          "text": "Text"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI15ModifiedContentV",
          "text": "ModifiedContent"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI31AccessibilityAttachmentModifierV",
          "text": "AccessibilityAttachmentModifier"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker/accessibility(hint:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibility(hint:)",
      "type": "topic",
      "url": "/documentation/familycontrols/familyactivitypicker/accessibility(hint:)"
    },
    "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker/accessibility(identifier:)": {
      "abstract": [
        {
          "text": "Uses the specified string to identify the view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibility"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "identifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI15ModifiedContentV",
          "text": "ModifiedContent"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI31AccessibilityAttachmentModifierV",
          "text": "AccessibilityAttachmentModifier"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker/accessibility(identifier:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibility(identifier:)",
      "type": "topic",
      "url": "/documentation/familycontrols/familyactivitypicker/accessibility(identifier:)"
    },
    "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker/accessibility(inputLabels:)": {
      "abstract": [
        {
          "text": "Sets alternate input labels with which users identify a view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibility"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "inputLabels"
        },
        {
          "kind": "text",
          "text": ": ["
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4TextV",
          "text": "Text"
        },
        {
          "kind": "text",
          "text": "]) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI15ModifiedContentV",
          "text": "ModifiedContent"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI31AccessibilityAttachmentModifierV",
          "text": "AccessibilityAttachmentModifier"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker/accessibility(inputLabels:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibility(inputLabels:)",
      "type": "topic",
      "url": "/documentation/familycontrols/familyactivitypicker/accessibility(inputlabels:)"
    },
    "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker/accessibility(label:)": {
      "abstract": [
        {
          "text": "Adds a label to the view that describes its contents.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibility"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "label"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4TextV",
          "text": "Text"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI15ModifiedContentV",
          "text": "ModifiedContent"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI31AccessibilityAttachmentModifierV",
          "text": "AccessibilityAttachmentModifier"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker/accessibility(label:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibility(label:)",
      "type": "topic",
      "url": "/documentation/familycontrols/familyactivitypicker/accessibility(label:)"
    },
    "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker/accessibility(removeTraits:)": {
      "abstract": [
        {
          "text": "Removes the given traits from this view.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibility"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "removeTraits"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI19AccessibilityTraitsV",
          "text": "AccessibilityTraits"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI15ModifiedContentV",
          "text": "ModifiedContent"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI31AccessibilityAttachmentModifierV",
          "text": "AccessibilityAttachmentModifier"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker/accessibility(removeTraits:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibility(removeTraits:)",
      "type": "topic",
      "url": "/documentation/familycontrols/familyactivitypicker/accessibility(removetraits:)"
    },
    "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker/accessibility(selectionIdentifier:)": {
      "abstract": [
        {
          "text": "Sets a selection identifier for this view’s accessibility element.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibility"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "selectionIdentifier"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s11AnyHashableV",
          "text": "AnyHashable"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI15ModifiedContentV",
          "text": "ModifiedContent"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI31AccessibilityAttachmentModifierV",
          "text": "AccessibilityAttachmentModifier"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker/accessibility(selectionIdentifier:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibility(selectionIdentifier:)",
      "type": "topic",
      "url": "/documentation/familycontrols/familyactivitypicker/accessibility(selectionidentifier:)"
    },
    "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker/accessibility(sortPriority:)": {
      "abstract": [
        {
          "text": "Sets the sort priority order for this view’s accessibility element,",
          "type": "text"
        },
        {
          "text": " ",
          "type": "text"
        },
        {
          "text": "relative to other elements at the same level.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibility"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "sortPriority"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI15ModifiedContentV",
          "text": "ModifiedContent"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI31AccessibilityAttachmentModifierV",
          "text": "AccessibilityAttachmentModifier"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker/accessibility(sortPriority:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibility(sortPriority:)",
      "type": "topic",
      "url": "/documentation/familycontrols/familyactivitypicker/accessibility(sortpriority:)"
    },
    "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker/accessibility(value:)": {
      "abstract": [
        {
          "text": "Adds a textual description of the value that the view contains.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibility"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "value"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI4TextV",
          "text": "Text"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI15ModifiedContentV",
          "text": "ModifiedContent"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI31AccessibilityAttachmentModifierV",
          "text": "AccessibilityAttachmentModifier"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker/accessibility(value:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibility(value:)",
      "type": "topic",
      "url": "/documentation/familycontrols/familyactivitypicker/accessibility(value:)"
    },
    "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker/accessibilityCustomContent(_:_:importance:)-8480d": {
      "abstract": [
        {
          "text": "Add additional accessibility information to the view.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "accessibilityCustomContent"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "L"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "V"
        },
        {
          "kind": "text",
          "text": ">("
        },
        {
          "kind": "typeIdentifier",
          "text": "L"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "V"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "importance"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)AXCustomContent",
          "text": "AXCustomContent"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@AXCustomContentImportance",
          "text": "Importance"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI15ModifiedContentV",
          "text": "ModifiedContent"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:7SwiftUI31AccessibilityAttachmentModifierV",
          "text": "AccessibilityAttachmentModifier"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker/accessibilityCustomContent(_:_:importance:)-8480d",
      "kind": "symbol",
      "role": "symbol",
      "title": "accessibilityCustomContent(_:_:importance:)",
      "type": "topic",
      "url": "/documentation/familycontrols/familyactivitypicker/accessibilitycustomcontent(_:_:importance:)-8480d"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@E@AXCustomContentImportance": {
      "abstract": [
        {
          "text": "Objects that control the timing of content output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Importance"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@E@AXCustomContentImportance",
      "kind": "symbol",
      "role": "symbol",
      "title": "AXCustomContent.Importance",
      "type": "topic",
      "url": "/documentation/Accessibility/AXCustomContent/Importance-swift.enum"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)AXCustomContent": {
      "abstract": [
        {
          "text": "Objects that define custom content and the timing of its output.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AXCustomContent"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)AXCustomContent",
      "kind": "symbol",
      "role": "symbol",
      "title": "AXCustomContent",
      "type": "topic",
      "url": "/documentation/Accessibility/AXCustomContent"
    },
    "doc://com.externally.resolved.symbol/s:7SwiftUI15ModifiedContentV": {
      "abstract": [
        {
          "text": "A value with a modifier applied to it.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ModifiedContent"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Content"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "genericParameter",
          "text": "Modifier"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:7SwiftUI15ModifiedContentV",
      "kind": "symbol",
      "role": "symbol",
      "title": "ModifiedContent",
      "type": "topic",
      "url": "/documentation/SwiftUI/ModifiedContent"
    },
    "doc://com.externally.resolved.symbol/s:7SwiftUI31AccessibilityAttachmentModifierV": {
      "abstract": [
        {
          "text": "A view modifier that adds accessibility properties to the view",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AccessibilityAttachmentModifier"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:7SwiftUI31AccessibilityAttachmentModifierV",
      "kind": "symbol",
      "role": "symbol",
      "title": "AccessibilityAttachmentModifier",
      "type": "topic",
      "url": "/documentation/SwiftUI/AccessibilityAttachmentModifier"
    },
    "doc://com.externally.resolved.symbol/s:Sy": {
      "abstract": [
        {
          "text": "A type that can represent a string as a collection of characters.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "StringProtocol"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SK",
          "text": "BidirectionalCollection"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SL",
          "text": "Comparable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s32ExpressibleByStringInterpolationP",
          "text": "ExpressibleByStringInterpolation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SH",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25LosslessStringConvertibleP",
          "text": "LosslessStringConvertible"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s16TextOutputStreamP",
          "text": "TextOutputStream"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s20TextOutputStreamableP",
          "text": "TextOutputStreamable"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:ST7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": " == "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SJ",
          "text": "Character"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sl5IndexQa",
          "text": "Index"
        },
        {
          "kind": "text",
          "text": " == "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS",
          "text": "String"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SS5IndexV",
          "text": "Index"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s32ExpressibleByStringInterpolationP0cD0Qa",
          "text": "StringInterpolation"
        },
        {
          "kind": "text",
          "text": " == "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s26DefaultStringInterpolationV",
          "text": "DefaultStringInterpolation"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "text": "Self"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sl11SubSequenceQa",
          "text": "SubSequence"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sy",
          "text": "StringProtocol"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sy",
      "kind": "symbol",
      "role": "symbol",
      "title": "StringProtocol",
      "type": "topic",
      "url": "/documentation/Swift/StringProtocol"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-Accessibility-Modifiers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker/accessibility(label:)",
        "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker/accessibility(value:)",
        "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker/accessibility(hidden:)",
        "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker/accessibility(identifier:)",
        "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker/accessibility(selectionIdentifier:)",
        "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker/accessibility(hint:)",
        "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker/accessibility(activationPoint:)-34miz",
        "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker/accessibility(activationPoint:)-ci2b",
        "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker/accessibility(inputLabels:)",
        "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker/accessibility(addTraits:)",
        "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker/accessibility(removeTraits:)",
        "doc://com.apple.FamilyControls/documentation/FamilyControls/FamilyActivityPicker/accessibility(sortPriority:)"
      ],
      "title": "Deprecated Accessibility Modifiers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@E@AXCustomContentImportance/title",
          "value": "AXCustomContentImportance"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@E@AXCustomContentImportance/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AXCustomContentImportance"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@NSUInteger",
              "text": "NSUInteger"
            },
            {
              "kind": "text",
              "text": ";"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)AXCustomContent/fragments",
          "value": [
            {
              "kind": "keyword",
              "text": "@interface"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "AXCustomContent"
            },
            {
              "kind": "text",
              "text": " : "
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSObject",
              "text": "NSObject"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/familycontrols/familyactivitypicker/accessibilitycustomcontent(_:_:importance:)-8480d"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
