{
  "abstract": [
    {
      "text": "Tells the delegate that the specified view controller is about to be hidden.",
      "type": "text"
    }
  ],
  "deprecationSummary": [
    {
      "inlineContent": [
        {
          "text": "Implement the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:willChangeTo:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " method instead.",
          "type": "text"
        }
      ],
      "type": "paragraph"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:willHide:with:for:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(pl)UISplitViewControllerDelegate(im)splitViewController:willHideViewController:withBarButtonItem:forPopoverController:",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "splitViewController"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UISplitViewController",
        "text": "UISplitViewController"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "willHide"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UIViewController",
        "text": "UIViewController"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "with"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UIBarButtonItem",
        "text": "UIBarButtonItem"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "for"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)UIPopoverController",
        "text": "UIPopoverController"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "splitViewController:willHideViewController:withBarButtonItem:forPopoverController:"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "8.0",
        "introducedAt": "2.0",
        "message": "Use splitViewController:willChangeToDisplayMode: and displayModeButtonItem instead",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "8.0",
        "introducedAt": "2.0",
        "message": "Use splitViewController:willChangeToDisplayMode: and displayModeButtonItem instead",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "13.1",
        "introducedAt": "13.1",
        "message": "Use splitViewController:willChangeToDisplayMode: and displayModeButtonItem instead",
        "name": "Mac Catalyst",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Method",
    "symbolKind": "method",
    "title": "splitViewController(_:willHide:with:for:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst"
          ],
          "tokens": [
            {
              "kind": "attribute",
              "text": "@"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:ScM",
              "kind": "attribute",
              "preciseIdentifier": "s:ScM",
              "text": "MainActor"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "optional"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "splitViewController"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "svc"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UISplitViewController",
              "text": "UISplitViewController"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "willHide"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "aViewController"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIViewController",
              "text": "UIViewController"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "with"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "barButtonItem"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIBarButtonItem",
              "text": "UIBarButtonItem"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "for"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "pc"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPopoverController",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)UIPopoverController",
              "text": "UIPopoverController"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The split view controller that owns the specified view controller.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "svc"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The view controller being hidden.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "aViewController"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A button you can add to your toolbar.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "barButtonItem"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The popover controller that uses taps in ",
                  "type": "text"
                },
                {
                  "code": "barButtonItem",
                  "type": "codeVoice"
                },
                {
                  "text": " to display the specified view controller.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "pc"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "When the split view controller rotates from a landscape to portrait orientation, it typically hides one of its view controllers. When that happens, it calls this method to coordinate the addition of a button to the toolbar (or navigation bar) of the remaining custom view controller. If you want the soon-to-be hidden view controller to be displayed in a popover, you must implement this method and use it to add the specified button to your interface.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem": {
      "abstract": [
        {
          "text": "A specialized button for placement on a toolbar, navigation bar, or shortcuts bar.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIBarButtonItem"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIBarButtonItem"
        }
      ],
      "role": "symbol",
      "title": "UIBarButtonItem",
      "type": "topic",
      "url": "/documentation/uikit/uibarbuttonitem"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIPopoverController": {
      "abstract": [
        {
          "text": "An object that manages the presentation of content in a popover.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIPopoverController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPopoverController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIPopoverController"
        }
      ],
      "role": "symbol",
      "title": "UIPopoverController",
      "type": "topic",
      "url": "/documentation/uikit/uipopovercontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewController": {
      "abstract": [
        {
          "text": "A container view controller that implements a hierarchical interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISplitViewController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISplitViewController"
        }
      ],
      "role": "symbol",
      "title": "UISplitViewController",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontroller"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate": {
      "abstract": [
        {
          "text": "The methods adopted by the object you use to manage changes to a split view interface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISplitViewControllerDelegate"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISplitViewControllerDelegate"
        }
      ],
      "role": "symbol",
      "title": "UISplitViewControllerDelegate",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontrollerdelegate"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:popoverController:willPresent:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the hidden view controller is about to be displayed in a popover.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "splitViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "popoverController"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPopoverController",
          "text": "UIPopoverController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willPresent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:popoverController:willPresent:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "splitViewController:popoverController:willPresentViewController:"
        }
      ],
      "role": "symbol",
      "title": "splitViewController(_:popoverController:willPresent:)",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontrollerdelegate/splitviewcontroller(_:popovercontroller:willpresent:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:shouldHide:in:)": {
      "abstract": [
        {
          "text": "Asks the delegate whether the first view controller should be hidden for the specified orientation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "splitViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "shouldHide"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "in"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UIInterfaceOrientation",
          "text": "UIInterfaceOrientation"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:shouldHide:in:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "splitViewController:shouldHideViewController:inOrientation:"
        }
      ],
      "role": "symbol",
      "title": "splitViewController(_:shouldHide:in:)",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontrollerdelegate/splitviewcontroller(_:shouldhide:in:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:willChangeTo:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the display mode for the split view controller is about to change.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "splitViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willChangeTo"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": "."
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@UISplitViewControllerDisplayMode",
          "text": "DisplayMode"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:willChangeTo:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "splitViewController:willChangeToDisplayMode:"
        }
      ],
      "role": "symbol",
      "title": "splitViewController(_:willChangeTo:)",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontrollerdelegate/splitviewcontroller(_:willchangeto:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:willHide:with:for:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the specified view controller is about to be hidden.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "splitViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willHide"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "with"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIBarButtonItem",
          "text": "UIBarButtonItem"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "for"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIPopoverController",
          "text": "UIPopoverController"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:willHide:with:for:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "splitViewController:willHideViewController:withBarButtonItem:forPopoverController:"
        }
      ],
      "role": "symbol",
      "title": "splitViewController(_:willHide:with:for:)",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontrollerdelegate/splitviewcontroller(_:willhide:with:for:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:willShow:invalidating:)": {
      "abstract": [
        {
          "text": "Tells the delegate that the specified view controller is about to be shown again.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "splitViewController"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UISplitViewController",
          "text": "UISplitViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "willShow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIViewController",
          "text": "UIViewController"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "invalidating"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)UIBarButtonItem",
          "text": "UIBarButtonItem"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:willShow:invalidating:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "splitViewController:willShowViewController:invalidatingBarButtonItem:"
        }
      ],
      "role": "symbol",
      "title": "splitViewController(_:willShow:invalidating:)",
      "type": "topic",
      "url": "/documentation/uikit/uisplitviewcontrollerdelegate/splitviewcontroller(_:willshow:invalidating:)"
    },
    "doc://com.apple.uikit/documentation/UIKit/UIViewController": {
      "abstract": [
        {
          "text": "An object that manages a view hierarchy for your UIKit app.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UIViewController"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UIViewController"
        }
      ],
      "role": "symbol",
      "title": "UIViewController",
      "type": "topic",
      "url": "/documentation/uikit/uiviewcontroller"
    },
    "doc://com.externally.resolved.symbol/s:ScM": {
      "abstract": [
        {
          "text": "A singleton actor whose executor is equivalent to the main dispatch queue.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@globalActor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "final"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "actor"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MainActor"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:ScM",
      "kind": "symbol",
      "role": "symbol",
      "title": "MainActor",
      "type": "topic",
      "url": "/documentation/Swift/MainActor"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Deprecated-methods",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:shouldHide:in:)",
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:willShow:invalidating:)",
        "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:popoverController:willPresent:)"
      ],
      "title": "Deprecated methods"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "8.0",
              "introducedAt": "2.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "8.0",
              "introducedAt": "2.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "deprecatedAt": "13.1",
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Method"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "splitViewController:willHideViewController:withBarButtonItem:forPopoverController:"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "method"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "splitViewController:willHideViewController:withBarButtonItem:forPopoverController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Deprecated-methods",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:shouldHide:in:)",
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:willShow:invalidating:)",
                "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:popoverController:willPresent:)"
              ],
              "title": "Deprecated methods"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "text",
                    "text": "- ("
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "kind": "identifier",
                    "text": "splitViewController:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewController",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UISplitViewController",
                    "text": "UISplitViewController"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "svc"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "willHideViewController:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIViewController",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UIViewController",
                    "text": "UIViewController"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "aViewController"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "withBarButtonItem:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIBarButtonItem",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UIBarButtonItem",
                    "text": "UIBarButtonItem"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "barButtonItem"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "forPopoverController:"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.uikit/documentation/UIKit/UIPopoverController",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)UIPopoverController",
                    "text": "UIPopoverController"
                  },
                  {
                    "kind": "text",
                    "text": " *) "
                  },
                  {
                    "kind": "internalParam",
                    "text": "pc"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The split view controller that owns the specified view controller.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "svc"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The view controller being hidden.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "aViewController"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A button you can add to your toolbar.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "barButtonItem"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The popover controller that uses taps in ",
                        "type": "text"
                      },
                      {
                        "code": "barButtonItem",
                        "type": "codeVoice"
                      },
                      {
                        "text": " to display the specified view controller.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "pc"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/deprecationSummary",
          "value": [
            {
              "inlineContent": [
                {
                  "text": "Implement the ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.uikit/documentation/UIKit/UISplitViewControllerDelegate/splitViewController(_:willChangeTo:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " method instead.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate/title",
          "value": "UISplitViewControllerDelegate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISplitViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISplitViewControllerDelegate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController/title",
          "value": "UIViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController/title",
          "value": "UISplitViewController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISplitViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISplitViewController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewController(_:willHide:with:for:)/title",
          "value": "splitViewController:willHideViewController:withBarButtonItem:forPopoverController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewController(_:willHide:with:for:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "splitViewController:willHideViewController:withBarButtonItem:forPopoverController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverController/title",
          "value": "UIPopoverController"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverController/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPopoverController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIPopoverController/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIPopoverController"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewController(_:willShow:invalidating:)/title",
          "value": "splitViewController:willShowViewController:invalidatingBarButtonItem:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewController(_:willShow:invalidating:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "splitViewController:willShowViewController:invalidatingBarButtonItem:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewController(_:shouldHide:in:)/title",
          "value": "splitViewController:shouldHideViewController:inOrientation:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewController(_:shouldHide:in:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "splitViewController:shouldHideViewController:inOrientation:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewController(_:popoverController:willPresent:)/title",
          "value": "splitViewController:popoverController:willPresentViewController:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewController(_:popoverController:willPresent:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "splitViewController:popoverController:willPresentViewController:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewController(_:willChangeTo:)/title",
          "value": "splitViewController:willChangeToDisplayMode:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISplitViewControllerDelegate~1splitViewController(_:willChangeTo:)/fragments",
          "value": [
            {
              "kind": "text",
              "text": "- "
            },
            {
              "kind": "identifier",
              "text": "splitViewController:willChangeToDisplayMode:"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem/title",
          "value": "UIBarButtonItem"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonItem"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIBarButtonItem/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UIBarButtonItem"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uisplitviewcontrollerdelegate/splitviewcontroller(_:willhide:with:for:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uisplitviewcontrollerdelegate/splitviewcontroller(_:willhide:with:for:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
