{
  "abstract": [
    {
      "text": "Calculates the element-wise inverse sine of the input.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/asin"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MLCArithmeticOperation@MLCArithmeticOperationAsin",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "asin"
      }
    ],
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLCArithmeticOperationAsin"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.3",
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MLCArithmeticOperation.asin"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "asin"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation": {
      "abstract": [
        {
          "text": "Constants that describe an arithmetic operation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperation"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperation"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/acos": {
      "abstract": [
        {
          "text": "Calculates the element-wise inverse cosine of the input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "acos"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/acos",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationAcos"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.acos",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/acos"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/acosh": {
      "abstract": [
        {
          "text": "Calculates the element-wise inverse hyperbolic cosine of the input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "acosh"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/acosh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationAcosh"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.acosh",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/acosh"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/asin": {
      "abstract": [
        {
          "text": "Calculates the element-wise inverse sine of the input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "asin"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/asin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationAsin"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.asin",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/asin"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/asinh": {
      "abstract": [
        {
          "text": "Calculates the element-wise inverse hyperbolic sine of the input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "asinh"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/asinh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationAsinh"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.asinh",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/asinh"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/atan": {
      "abstract": [
        {
          "text": "Calculates the element-wise inverse tangent of the input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "atan"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/atan",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationAtan"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.atan",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/atan"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/atanh": {
      "abstract": [
        {
          "text": "Calculates the element-wise inverse hyperbolic tangent of the input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "atanh"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/atanh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationAtanh"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.atanh",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/atanh"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/cos": {
      "abstract": [
        {
          "text": "Calculates the element-wise cosine of the input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cos"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/cos",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationCos"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.cos",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/cos"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/cosh": {
      "abstract": [
        {
          "text": "Calculates the element-wise hyperbolic cosine of the input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cosh"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/cosh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationCosh"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.cosh",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/cosh"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/sin": {
      "abstract": [
        {
          "text": "Calculates the element-wise sine of the input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sin"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/sin",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationSin"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.sin",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/sin"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/sinh": {
      "abstract": [
        {
          "text": "Calculates the element-wise hyperbolic sine of the input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sinh"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/sinh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationSinh"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.sinh",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/sinh"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/tan": {
      "abstract": [
        {
          "text": "Calculates the element-wise tangent of the input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tan"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/tan",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationTan"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.tan",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/tan"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/tanh": {
      "abstract": [
        {
          "text": "Calculates the element-wise hyperbolic tangent of the input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tanh"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/tanh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationTanh"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.tanh",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/tanh"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Trigonometric-Operations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/sin",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/cos",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/tan",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/acos",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/atan",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/sinh",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/cosh",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/tanh",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/asinh",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/acosh",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/atanh"
      ],
      "title": "Trigonometric Operations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MLCArithmeticOperationAsin"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationAsin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mlcompute/documentation/MLCompute",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Trigonometric-Operations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/sin",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/cos",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/tan",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/acos",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/atan",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/sinh",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/cosh",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/tanh",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/asinh",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/acosh",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/atanh"
              ],
              "title": "Trigonometric Operations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MLCArithmeticOperationAsin"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "add",
          "path": "/deprecationSummary",
          "value": []
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1tanh/title",
          "value": "MLCArithmeticOperationTanh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1tanh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationTanh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1tan/title",
          "value": "MLCArithmeticOperationTan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1tan/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationTan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1asinh/title",
          "value": "MLCArithmeticOperationAsinh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1asinh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationAsinh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1atan/title",
          "value": "MLCArithmeticOperationAtan"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1atan/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationAtan"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation/title",
          "value": "MLCArithmeticOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1acosh/title",
          "value": "MLCArithmeticOperationAcosh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1acosh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationAcosh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1cosh/title",
          "value": "MLCArithmeticOperationCosh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1cosh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationCosh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1sinh/title",
          "value": "MLCArithmeticOperationSinh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1sinh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationSinh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1acos/title",
          "value": "MLCArithmeticOperationAcos"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1acos/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationAcos"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1asin/title",
          "value": "MLCArithmeticOperationAsin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1asin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationAsin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1atanh/title",
          "value": "MLCArithmeticOperationAtanh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1atanh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationAtanh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1sin/title",
          "value": "MLCArithmeticOperationSin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1sin/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationSin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1cos/title",
          "value": "MLCArithmeticOperationCos"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1cos/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationCos"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/mlcarithmeticoperation/asin"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mlcompute/mlcarithmeticoperation/asin"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
