{
  "abstract": [
    {
      "text": "Calculates the element-wise division of the inputs.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/divide"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MLCArithmeticOperation@MLCArithmeticOperationDivide",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "divide"
      }
    ],
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLCArithmeticOperationDivide"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.3",
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MLCArithmeticOperation.divide"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "divide"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation": {
      "abstract": [
        {
          "text": "Constants that describe an arithmetic operation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperation"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperation"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/add": {
      "abstract": [
        {
          "text": "Calculates the element-wise sum of the inputs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "add"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/add",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationAdd"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.add",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/add"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/divide": {
      "abstract": [
        {
          "text": "Calculates the element-wise division of the inputs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "divide"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/divide",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationDivide"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.divide",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/divide"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/divideNoNaN": {
      "abstract": [
        {
          "text": "Calculates the element-wise division of the inputs, and returns ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": " if the denominator is ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "divideNoNaN"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/divideNoNaN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationDivideNoNaN"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.divideNoNaN",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/dividenonan"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/max": {
      "abstract": [
        {
          "text": "Calculates the element-wise maximum the inputs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "max"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/max",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationMax"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.max",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/max"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/min": {
      "abstract": [
        {
          "text": "Calculates the element-wise minimum of the inputs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "min"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/min",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationMin"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.min",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/min"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/multiply": {
      "abstract": [
        {
          "text": "Calculates the element-wise product of the inputs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multiply"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/multiply",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationMultiply"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.multiply",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/multiply"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/multiplyNoNaN": {
      "abstract": [
        {
          "text": "Calculates the element-wise product of the inputs, and returns ",
          "type": "text"
        },
        {
          "code": "0",
          "type": "codeVoice"
        },
        {
          "text": " when the result isn’t a number or infinity.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "multiplyNoNaN"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/multiplyNoNaN",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationMultiplyNoNaN"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.multiplyNoNaN",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/multiplynonan"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/subtract": {
      "abstract": [
        {
          "text": "Calculates the element-wise difference between the inputs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "subtract"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/subtract",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationSubtract"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.subtract",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/subtract"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Basic-Operations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/add",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/subtract",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/multiply",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/multiplyNoNaN",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/divideNoNaN",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/min",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/max"
      ],
      "title": "Basic Operations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MLCArithmeticOperationDivide"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationDivide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mlcompute/documentation/MLCompute",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Basic-Operations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/add",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/subtract",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/multiply",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/multiplyNoNaN",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/divideNoNaN",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/min",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/max"
              ],
              "title": "Basic Operations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MLCArithmeticOperationDivide"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "add",
          "path": "/deprecationSummary",
          "value": []
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1add/title",
          "value": "MLCArithmeticOperationAdd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1add/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationAdd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1multiplyNoNaN/title",
          "value": "MLCArithmeticOperationMultiplyNoNaN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1multiplyNoNaN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationMultiplyNoNaN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1min/title",
          "value": "MLCArithmeticOperationMin"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1min/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationMin"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1divide/title",
          "value": "MLCArithmeticOperationDivide"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1divide/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationDivide"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation/title",
          "value": "MLCArithmeticOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1multiply/title",
          "value": "MLCArithmeticOperationMultiply"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1multiply/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationMultiply"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1divideNoNaN/title",
          "value": "MLCArithmeticOperationDivideNoNaN"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1divideNoNaN/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationDivideNoNaN"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1max/title",
          "value": "MLCArithmeticOperationMax"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1max/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationMax"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1subtract/title",
          "value": "MLCArithmeticOperationSubtract"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1subtract/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationSubtract"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/mlcarithmeticoperation/divide"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mlcompute/mlcarithmeticoperation/divide"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
