{
  "abstract": [
    {
      "text": "Calculates the element-wise reciprocal of the square root of the input.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.mlcompute/documentation/MLCompute",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/rsqrt"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@MLCArithmeticOperation@MLCArithmeticOperationRsqrt",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "rsqrt"
      }
    ],
    "modules": [
      {
        "name": "ML Compute"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "MLCArithmeticOperationRsqrt"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "14.3",
        "introducedAt": "11.0",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "deprecatedAt": "17.4",
        "introducedAt": "14.0",
        "name": "tvOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "MLCArithmeticOperation.rsqrt"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "rsqrt"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute": {
      "abstract": [
        {
          "text": "Accelerate training and validation of neural networks across the CPU and one or more GPUs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute",
      "kind": "symbol",
      "role": "collection",
      "title": "ML Compute",
      "type": "topic",
      "url": "/documentation/mlcompute"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation": {
      "abstract": [
        {
          "text": "Constants that describe an arithmetic operation.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperation"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperation"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/exp": {
      "abstract": [
        {
          "text": "Calculates the element-wise result of the exponent raised to the power of the input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exp"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/exp",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationExp"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.exp",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/exp"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/exp2": {
      "abstract": [
        {
          "text": "Calculates the element-wise result of the number 2 raised to the power of the input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exp2"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/exp2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationExp2"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.exp2",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/exp2"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/log": {
      "abstract": [
        {
          "text": "Calculates the element-wise natural logarithm of the input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "log"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/log",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationLog"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.log",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/log"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/log2": {
      "abstract": [
        {
          "text": "Calculates the element-wise base 2 logarithm of the input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "log2"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/log2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationLog2"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.log2",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/log2"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/pow": {
      "abstract": [
        {
          "text": "Calculates the element-wise first input raised to the power of the second input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "pow"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/pow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationPow"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.pow",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/pow"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/rsqrt": {
      "abstract": [
        {
          "text": "Calculates the element-wise reciprocal of the square root of the input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rsqrt"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/rsqrt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationRsqrt"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.rsqrt",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/rsqrt"
    },
    "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/sqrt": {
      "abstract": [
        {
          "text": "Calculates the element-wise square root of the input.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sqrt"
        }
      ],
      "identifier": "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/sqrt",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "MLCArithmeticOperationSqrt"
        }
      ],
      "role": "symbol",
      "title": "MLCArithmeticOperation.sqrt",
      "type": "topic",
      "url": "/documentation/mlcompute/mlcarithmeticoperation/sqrt"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Advanced-Operations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/sqrt",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/pow",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/exp",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/exp2",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/log",
        "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/log2"
      ],
      "title": "Advanced Operations"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "11.0",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "tvOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "MLCArithmeticOperationRsqrt"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationRsqrt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.mlcompute/documentation/MLCompute",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Advanced-Operations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/sqrt",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/pow",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/exp",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/exp2",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/log",
                "doc://com.apple.mlcompute/documentation/MLCompute/MLCArithmeticOperation/log2"
              ],
              "title": "Advanced Operations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "MLCArithmeticOperationRsqrt"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "add",
          "path": "/deprecationSummary",
          "value": []
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1pow/title",
          "value": "MLCArithmeticOperationPow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1pow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationPow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1exp2/title",
          "value": "MLCArithmeticOperationExp2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1exp2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationExp2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1log/title",
          "value": "MLCArithmeticOperationLog"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1log/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationLog"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1sqrt/title",
          "value": "MLCArithmeticOperationSqrt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1sqrt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationSqrt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1exp/title",
          "value": "MLCArithmeticOperationExp"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1exp/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationExp"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1rsqrt/title",
          "value": "MLCArithmeticOperationRsqrt"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1rsqrt/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationRsqrt"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation/title",
          "value": "MLCArithmeticOperation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1log2/title",
          "value": "MLCArithmeticOperationLog2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.mlcompute~1documentation~1MLCompute~1MLCArithmeticOperation~1log2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "MLCArithmeticOperationLog2"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/mlcompute/mlcarithmeticoperation/rsqrt"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/mlcompute/mlcarithmeticoperation/rsqrt"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
