{
  "abstract": [
    {
      "text": "The stream to use for sending data to the accessory.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.externalaccessory/documentation/ExternalAccessory",
        "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EASession"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EASession/outputStream"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:objc(cs)EASession(py)outputStream",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "outputStream"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:objc(cs)NSOutputStream",
        "text": "OutputStream"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "External Accessory"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "outputStream"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.13",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Instance Property",
    "symbolKind": "property",
    "title": "outputStream"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "outputStream"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSOutputStream",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:objc(cs)NSOutputStream",
              "text": "OutputStream"
            },
            {
              "kind": "text",
              "text": "? { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "This stream is provided for you automatically by the session object but you must configure it if you want to receive any associated stream events. You do this by assigning a delegate object to the stream that implements the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/foundation/streamdelegate/1410079-stream",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " delegate method. You must then schedule the stream in a run loop so that it can send data asynchronously from one of your application’s threads.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "For more information on how to schedule an output stream in a run loop and use it to send data, see ",
              "type": "text"
            },
            {
              "identifier": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Streams/Streams.html#//apple_ref/doc/uid/10000188i",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/foundation/streamdelegate/1410079-stream": {
      "abstract": [
        {
          "text": "The delegate receives this message when a given event has occurred on a given stream.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "func "
        },
        {
          "kind": "identifier",
          "text": "stream"
        },
        {
          "kind": "text",
          "text": "(Stream, "
        },
        {
          "kind": "identifier",
          "text": "handle"
        },
        {
          "kind": "text",
          "text": ": Stream.Event)"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/foundation/streamdelegate/1410079-stream",
      "kind": "symbol",
      "role": "symbol",
      "title": "stream(_:handle:)",
      "type": "topic",
      "url": "/documentation/foundation/streamdelegate/1410079-stream"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.externalaccessory/documentation/ExternalAccessory": {
      "abstract": [
        {
          "text": "Communicate with accessories that connect to a device with the Apple Lightning connector, or with Bluetooth wireless technology.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory",
      "kind": "symbol",
      "role": "collection",
      "title": "External Accessory",
      "type": "topic",
      "url": "/documentation/externalaccessory"
    },
    "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EASession": {
      "abstract": [
        {
          "text": "The object you use to manage communications between your app and a connected hardware accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "EASession"
        }
      ],
      "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EASession",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "EASession"
        }
      ],
      "role": "symbol",
      "title": "EASession",
      "type": "topic",
      "url": "/documentation/externalaccessory/easession"
    },
    "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EASession/inputStream": {
      "abstract": [
        {
          "text": "The stream to use for receiving data from the accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inputStream"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSInputStream",
          "text": "InputStream"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EASession/inputStream",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "inputStream"
        }
      ],
      "role": "symbol",
      "title": "inputStream",
      "type": "topic",
      "url": "/documentation/externalaccessory/easession/inputstream"
    },
    "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EASession/outputStream": {
      "abstract": [
        {
          "text": "The stream to use for sending data to the accessory.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "outputStream"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:objc(cs)NSOutputStream",
          "text": "OutputStream"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EASession/outputStream",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "outputStream"
        }
      ],
      "role": "symbol",
      "title": "outputStream",
      "type": "topic",
      "url": "/documentation/externalaccessory/easession/outputstream"
    },
    "doc://com.externally.resolved.symbol/c:objc(cs)NSOutputStream": {
      "abstract": [
        {
          "text": "A stream that provides write-only stream functionality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "OutputStream"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSOutputStream",
      "kind": "symbol",
      "role": "symbol",
      "title": "OutputStream",
      "type": "topic",
      "url": "/documentation/foundation/outputstream"
    },
    "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Streams/Streams.html#//apple_ref/doc/uid/10000188i": {
      "identifier": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Streams/Streams.html#//apple_ref/doc/uid/10000188i",
      "title": "Stream Programming Guide",
      "titleInlineContent": [
        {
          "text": "Stream Programming Guide",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Streams/Streams.html#//apple_ref/doc/uid/10000188i"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-the-Communication-Streams",
      "generated": true,
      "identifiers": [
        "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EASession/inputStream"
      ],
      "title": "Getting the Communication Streams"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.13",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Instance Property"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "outputStream"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "property"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputStream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.externalaccessory/documentation/ExternalAccessory",
                "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EASession"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-the-Communication-Streams",
              "generated": true,
              "identifiers": [
                "doc://com.apple.externalaccessory/documentation/ExternalAccessory/EASession/inputStream"
              ],
              "title": "Getting the Communication Streams"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "@property"
                  },
                  {
                    "kind": "text",
                    "text": " ("
                  },
                  {
                    "kind": "keyword",
                    "text": "nonatomic"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "readonly"
                  },
                  {
                    "kind": "text",
                    "text": ") "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:objc(cs)NSOutputStream",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:objc(cs)NSOutputStream",
                    "text": "NSOutputStream"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "outputStream"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:objc(cs)NSOutputStream/title",
          "value": "NSOutputStream"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EASession/title",
          "value": "EASession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EASession/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "EASession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EASession/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "EASession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EASession~1outputStream/title",
          "value": "outputStream"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EASession~1outputStream/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "outputStream"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.documentation~1documentation~1foundation~1streamdelegate~11410079-stream/title",
          "value": "stream:handleEvent:"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EASession~1inputStream/title",
          "value": "inputStream"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.externalaccessory~1documentation~1ExternalAccessory~1EASession~1inputStream/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "inputStream"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/externalaccessory/easession/outputstream"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/externalaccessory/easession/outputstream"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
