{"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/activeAppearance"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"seeAlsoSections":[{"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/accessibilityContrast","doc://com.apple.uikit/documentation/UIKit/UITraitAccessibilityContrast-swift.struct","doc://com.apple.uikit/documentation/UIKit/UITraitActiveAppearance-swift.struct","doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/displayGamut","doc://com.apple.uikit/documentation/UIKit/UITraitDisplayGamut-swift.struct","doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/displayScale","doc://com.apple.uikit/documentation/UIKit/UITraitDisplayScale-swift.struct","doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/forceTouchCapability","doc://com.apple.uikit/documentation/UIKit/UITraitForceTouchCapability-swift.struct","doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/horizontalSizeClass","doc://com.apple.uikit/documentation/UIKit/UITraitHorizontalSizeClass-swift.struct","doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/imageDynamicRange","doc://com.apple.uikit/documentation/UIKit/UITraitImageDynamicRange-swift.struct","doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/layoutDirection","doc://com.apple.uikit/documentation/UIKit/UITraitLayoutDirection-swift.struct"],"anchor":"Defining-custom-traits","generated":true,"title":"Defining custom traits"}],"variants":[{"paths":["/documentation/uikit/uimutabletraits-13ja5/activeappearance"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5"]]},"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"activeAppearance","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@UIUserInterfaceActiveAppearance","text":"UIUserInterfaceActiveAppearance","kind":"typeIdentifier"}],"modules":[{"name":"UIKit"}],"externalID":"s:5UIKit15UIMutableTraitsPAAE16activeAppearanceSo021UIUserInterfaceActiveE0Vvp","title":"activeAppearance","platforms":[{"unavailable":false,"beta":false,"introducedAt":"17.0","name":"iOS","deprecated":false},{"unavailable":false,"beta":false,"introducedAt":"17.0","name":"iPadOS","deprecated":false},{"unavailable":false,"beta":false,"name":"Mac Catalyst","deprecated":false},{"unavailable":false,"beta":false,"introducedAt":"17.0","name":"tvOS","deprecated":false},{"unavailable":false,"beta":false,"name":"visionOS","deprecated":false}],"roleHeading":"Instance Property","extendedModule":"UIKit","symbolKind":"property"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"activeAppearance"},{"kind":"text","text":": "},{"identifier":"doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceActiveAppearance","text":"UIUserInterfaceActiveAppearance","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIUserInterfaceActiveAppearance"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"]}],"kind":"declarations"}],"references":{"doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceActiveAppearance":{"abstract":[{"text":"Constants that indicate whether the user interface has an active appearance.","type":"text"}],"url":"/documentation/uikit/uiuserinterfaceactiveappearance","identifier":"doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceActiveAppearance","title":"UIUserInterfaceActiveAppearance","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIUserInterfaceActiveAppearance","kind":"identifier"}],"navigatorTitle":[{"text":"UIUserInterfaceActiveAppearance","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/horizontalSizeClass":{"title":"horizontalSizeClass","url":"/documentation/uikit/uimutabletraits-13ja5/horizontalsizeclass","abstract":[],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"horizontalSizeClass"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIUserInterfaceSizeClass","preciseIdentifier":"c:@E@UIUserInterfaceSizeClass"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/horizontalSizeClass"},"doc://com.apple.uikit/documentation/UIKit/UITraitForceTouchCapability-swift.struct":{"abstract":[],"type":"topic","title":"UITraitForceTouchCapability","kind":"symbol","navigatorTitle":[{"text":"UITraitForceTouchCapability","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITraitForceTouchCapability","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITraitForceTouchCapability-swift.struct","url":"/documentation/uikit/uitraitforcetouchcapability-swift.struct","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITraitDisplayGamut-swift.struct":{"abstract":[],"role":"symbol","url":"/documentation/uikit/uitraitdisplaygamut-swift.struct","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITraitDisplayGamut-swift.struct","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITraitDisplayGamut","kind":"identifier"}],"navigatorTitle":[{"text":"UITraitDisplayGamut","kind":"identifier"}],"title":"UITraitDisplayGamut"},"doc://com.apple.uikit/documentation/UIKit/UITraitAccessibilityContrast-swift.struct":{"type":"topic","navigatorTitle":[{"text":"UITraitAccessibilityContrast","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITraitAccessibilityContrast","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITraitAccessibilityContrast-swift.struct","abstract":[],"url":"/documentation/uikit/uitraitaccessibilitycontrast-swift.struct","title":"UITraitAccessibilityContrast"},"doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5":{"role":"symbol","abstract":[{"text":"A mutable container of traits.","type":"text"}],"url":"/documentation/uikit/uimutabletraits-13ja5","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"UIMutableTraits","kind":"identifier"}],"title":"UIMutableTraits","navigatorTitle":[{"kind":"identifier","text":"UIMutableTraits"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UITraitHorizontalSizeClass-swift.struct":{"abstract":[],"role":"symbol","url":"/documentation/uikit/uitraithorizontalsizeclass-swift.struct","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITraitHorizontalSizeClass-swift.struct","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITraitHorizontalSizeClass","kind":"identifier"}],"navigatorTitle":[{"text":"UITraitHorizontalSizeClass","kind":"identifier"}],"title":"UITraitHorizontalSizeClass"},"doc://com.apple.uikit/documentation/UIKit/UITraitImageDynamicRange-swift.struct":{"navigatorTitle":[{"kind":"identifier","text":"UITraitImageDynamicRange"}],"title":"UITraitImageDynamicRange","url":"/documentation/uikit/uitraitimagedynamicrange-swift.struct","abstract":[],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITraitImageDynamicRange"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITraitImageDynamicRange-swift.struct"},"doc://com.apple.uikit/documentation/UIKit/UITraitActiveAppearance-swift.struct":{"url":"/documentation/uikit/uitraitactiveappearance-swift.struct","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITraitActiveAppearance-swift.struct","navigatorTitle":[{"kind":"identifier","text":"UITraitActiveAppearance"}],"abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITraitActiveAppearance"}],"title":"UITraitActiveAppearance"},"doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/imageDynamicRange":{"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/imageDynamicRange","type":"topic","url":"/documentation/uikit/uimutabletraits-13ja5/imagedynamicrange","title":"imageDynamicRange","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageDynamicRange","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@UIImageDynamicRange","text":"DynamicRange","kind":"typeIdentifier"}],"abstract":[]},"doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/accessibilityContrast":{"abstract":[],"type":"topic","title":"accessibilityContrast","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityContrast","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@UIAccessibilityContrast","text":"UIAccessibilityContrast","kind":"typeIdentifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/accessibilityContrast","url":"/documentation/uikit/uimutabletraits-13ja5/accessibilitycontrast","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/activeAppearance":{"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/activeAppearance","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activeAppearance","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@UIUserInterfaceActiveAppearance","text":"UIUserInterfaceActiveAppearance","kind":"typeIdentifier"}],"abstract":[],"type":"topic","url":"/documentation/uikit/uimutabletraits-13ja5/activeappearance","title":"activeAppearance"},"doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/layoutDirection":{"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/layoutDirection","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layoutDirection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UITraitEnvironmentLayoutDirection","kind":"typeIdentifier","preciseIdentifier":"c:@E@UITraitEnvironmentLayoutDirection"}],"abstract":[],"type":"topic","url":"/documentation/uikit/uimutabletraits-13ja5/layoutdirection","title":"layoutDirection"},"doc://com.apple.uikit/documentation/UIKit/UITraitLayoutDirection-swift.struct":{"role":"symbol","kind":"symbol","url":"/documentation/uikit/uitraitlayoutdirection-swift.struct","title":"UITraitLayoutDirection","identifier":"doc://com.apple.uikit/documentation/UIKit/UITraitLayoutDirection-swift.struct","navigatorTitle":[{"kind":"identifier","text":"UITraitLayoutDirection"}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITraitLayoutDirection"}],"abstract":[]},"doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/displayGamut":{"title":"displayGamut","url":"/documentation/uikit/uimutabletraits-13ja5/displaygamut","abstract":[],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"displayGamut","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@UIDisplayGamut","text":"UIDisplayGamut","kind":"typeIdentifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/displayGamut"},"doc://com.apple.uikit/documentation/UIKit/UITraitDisplayScale-swift.struct":{"url":"/documentation/uikit/uitraitdisplayscale-swift.struct","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITraitDisplayScale-swift.struct","navigatorTitle":[{"kind":"identifier","text":"UITraitDisplayScale"}],"abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITraitDisplayScale"}],"title":"UITraitDisplayScale"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/displayScale":{"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/displayScale","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"displayScale","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"abstract":[],"type":"topic","url":"/documentation/uikit/uimutabletraits-13ja5/displayscale","title":"displayScale"},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/forceTouchCapability":{"role":"symbol","abstract":[],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/forceTouchCapability","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"forceTouchCapability"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIForceTouchCapability","text":"UIForceTouchCapability"}],"type":"topic","title":"forceTouchCapability","url":"/documentation/uikit/uimutabletraits-13ja5/forcetouchcapability","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceActiveAppearance/title","value":"UIUserInterfaceActiveAppearance"},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceActiveAppearance/fragments","value":[{"kind":"identifier","text":"UIUserInterfaceActiveAppearance"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceActiveAppearance/navigatorTitle","value":[{"text":"UIUserInterfaceActiveAppearance","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}