{"kind":"symbol","variants":[{"paths":["/documentation/uikit/uimutabletraits-13ja5/horizontalsizeclass"],"traits":[{"interfaceLanguage":"swift"}]}],"seeAlsoSections":[{"title":"Defining custom traits","generated":true,"identifiers":["doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/accessibilityContrast","doc://com.apple.uikit/documentation/UIKit/UITraitAccessibilityContrast-swift.struct","doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/activeAppearance","doc://com.apple.uikit/documentation/UIKit/UITraitActiveAppearance-swift.struct","doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/displayGamut","doc://com.apple.uikit/documentation/UIKit/UITraitDisplayGamut-swift.struct","doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/displayScale","doc://com.apple.uikit/documentation/UIKit/UITraitDisplayScale-swift.struct","doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/forceTouchCapability","doc://com.apple.uikit/documentation/UIKit/UITraitForceTouchCapability-swift.struct","doc://com.apple.uikit/documentation/UIKit/UITraitHorizontalSizeClass-swift.struct","doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/imageDynamicRange","doc://com.apple.uikit/documentation/UIKit/UITraitImageDynamicRange-swift.struct","doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/layoutDirection","doc://com.apple.uikit/documentation/UIKit/UITraitLayoutDirection-swift.struct"],"anchor":"Defining-custom-traits"}],"identifier":{"url":"doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/horizontalSizeClass","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5"]]},"metadata":{"platforms":[{"name":"iOS","introducedAt":"17.0","deprecated":false,"beta":false,"unavailable":false},{"name":"iPadOS","introducedAt":"17.0","deprecated":false,"beta":false,"unavailable":false},{"name":"Mac Catalyst","deprecated":false,"beta":false,"unavailable":false},{"name":"tvOS","introducedAt":"17.0","deprecated":false,"beta":false,"unavailable":false},{"name":"visionOS","deprecated":false,"beta":false,"unavailable":false}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"horizontalSizeClass","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIUserInterfaceSizeClass","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIUserInterfaceSizeClass"}],"symbolKind":"property","title":"horizontalSizeClass","modules":[{"name":"UIKit"}],"roleHeading":"Instance Property","role":"symbol","extendedModule":"UIKit","externalID":"s:5UIKit15UIMutableTraitsPAAE19horizontalSizeClassSo015UIUserInterfaceeF0Vvp"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst","tvOS","visionOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"horizontalSizeClass","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@UIUserInterfaceSizeClass","text":"UIUserInterfaceSizeClass","identifier":"doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceSizeClass","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"references":{"doc://com.apple.uikit/documentation/UIKit/UITraitDisplayGamut-swift.struct":{"abstract":[],"role":"symbol","url":"/documentation/uikit/uitraitdisplaygamut-swift.struct","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITraitDisplayGamut-swift.struct","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITraitDisplayGamut","kind":"identifier"}],"navigatorTitle":[{"text":"UITraitDisplayGamut","kind":"identifier"}],"title":"UITraitDisplayGamut"},"doc://com.apple.uikit/documentation/UIKit/UITraitActiveAppearance-swift.struct":{"url":"/documentation/uikit/uitraitactiveappearance-swift.struct","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITraitActiveAppearance-swift.struct","navigatorTitle":[{"kind":"identifier","text":"UITraitActiveAppearance"}],"abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITraitActiveAppearance"}],"title":"UITraitActiveAppearance"},"doc://com.apple.uikit/documentation/UIKit/UITraitForceTouchCapability-swift.struct":{"abstract":[],"type":"topic","title":"UITraitForceTouchCapability","kind":"symbol","navigatorTitle":[{"text":"UITraitForceTouchCapability","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITraitForceTouchCapability","kind":"identifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITraitForceTouchCapability-swift.struct","url":"/documentation/uikit/uitraitforcetouchcapability-swift.struct","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/layoutDirection":{"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/layoutDirection","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layoutDirection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UITraitEnvironmentLayoutDirection","kind":"typeIdentifier","preciseIdentifier":"c:@E@UITraitEnvironmentLayoutDirection"}],"abstract":[],"type":"topic","url":"/documentation/uikit/uimutabletraits-13ja5/layoutdirection","title":"layoutDirection"},"doc://com.apple.uikit/documentation/UIKit/UITraitLayoutDirection-swift.struct":{"role":"symbol","kind":"symbol","url":"/documentation/uikit/uitraitlayoutdirection-swift.struct","title":"UITraitLayoutDirection","identifier":"doc://com.apple.uikit/documentation/UIKit/UITraitLayoutDirection-swift.struct","navigatorTitle":[{"kind":"identifier","text":"UITraitLayoutDirection"}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITraitLayoutDirection"}],"abstract":[]},"doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/displayScale":{"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/displayScale","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"displayScale","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"abstract":[],"type":"topic","url":"/documentation/uikit/uimutabletraits-13ja5/displayscale","title":"displayScale"},"doc://com.apple.uikit/documentation/UIKit/UITraitHorizontalSizeClass-swift.struct":{"abstract":[],"role":"symbol","url":"/documentation/uikit/uitraithorizontalsizeclass-swift.struct","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITraitHorizontalSizeClass-swift.struct","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITraitHorizontalSizeClass","kind":"identifier"}],"navigatorTitle":[{"text":"UITraitHorizontalSizeClass","kind":"identifier"}],"title":"UITraitHorizontalSizeClass"},"doc://com.apple.uikit/documentation/UIKit/UITraitAccessibilityContrast-swift.struct":{"type":"topic","navigatorTitle":[{"text":"UITraitAccessibilityContrast","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UITraitAccessibilityContrast","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UITraitAccessibilityContrast-swift.struct","abstract":[],"url":"/documentation/uikit/uitraitaccessibilitycontrast-swift.struct","title":"UITraitAccessibilityContrast"},"doc://com.apple.uikit/documentation/UIKit/UITraitDisplayScale-swift.struct":{"url":"/documentation/uikit/uitraitdisplayscale-swift.struct","type":"topic","identifier":"doc://com.apple.uikit/documentation/UIKit/UITraitDisplayScale-swift.struct","navigatorTitle":[{"kind":"identifier","text":"UITraitDisplayScale"}],"abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITraitDisplayScale"}],"title":"UITraitDisplayScale"},"doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/activeAppearance":{"role":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/activeAppearance","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activeAppearance","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@UIUserInterfaceActiveAppearance","text":"UIUserInterfaceActiveAppearance","kind":"typeIdentifier"}],"abstract":[],"type":"topic","url":"/documentation/uikit/uimutabletraits-13ja5/activeappearance","title":"activeAppearance"},"doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/displayGamut":{"title":"displayGamut","url":"/documentation/uikit/uimutabletraits-13ja5/displaygamut","abstract":[],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"displayGamut","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@UIDisplayGamut","text":"UIDisplayGamut","kind":"typeIdentifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/displayGamut"},"doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/horizontalSizeClass":{"title":"horizontalSizeClass","url":"/documentation/uikit/uimutabletraits-13ja5/horizontalsizeclass","abstract":[],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"horizontalSizeClass"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIUserInterfaceSizeClass","preciseIdentifier":"c:@E@UIUserInterfaceSizeClass"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/horizontalSizeClass"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/accessibilityContrast":{"abstract":[],"type":"topic","title":"accessibilityContrast","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityContrast","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@UIAccessibilityContrast","text":"UIAccessibilityContrast","kind":"typeIdentifier"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/accessibilityContrast","url":"/documentation/uikit/uimutabletraits-13ja5/accessibilitycontrast","role":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceSizeClass":{"role":"symbol","kind":"symbol","url":"/documentation/uikit/uiuserinterfacesizeclass","title":"UIUserInterfaceSizeClass","identifier":"doc://com.apple.uikit/documentation/UIKit/UIUserInterfaceSizeClass","navigatorTitle":[{"text":"UIUserInterfaceSizeClass","kind":"identifier"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"UIUserInterfaceSizeClass","kind":"identifier"}],"abstract":[{"type":"text","text":"Constants that indicate the size class of a view."}]},"doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/forceTouchCapability":{"role":"symbol","abstract":[],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/forceTouchCapability","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"forceTouchCapability"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIForceTouchCapability","text":"UIForceTouchCapability"}],"type":"topic","title":"forceTouchCapability","url":"/documentation/uikit/uimutabletraits-13ja5/forcetouchcapability","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5":{"role":"symbol","abstract":[{"text":"A mutable container of traits.","type":"text"}],"url":"/documentation/uikit/uimutabletraits-13ja5","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"UIMutableTraits","kind":"identifier"}],"title":"UIMutableTraits","navigatorTitle":[{"kind":"identifier","text":"UIMutableTraits"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/imageDynamicRange":{"kind":"symbol","identifier":"doc://com.apple.uikit/documentation/UIKit/UIMutableTraits-13ja5/imageDynamicRange","type":"topic","url":"/documentation/uikit/uimutabletraits-13ja5/imagedynamicrange","title":"imageDynamicRange","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageDynamicRange","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@UIImageDynamicRange","text":"DynamicRange","kind":"typeIdentifier"}],"abstract":[]},"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UITraitImageDynamicRange-swift.struct":{"navigatorTitle":[{"kind":"identifier","text":"UITraitImageDynamicRange"}],"title":"UITraitImageDynamicRange","url":"/documentation/uikit/uitraitimagedynamicrange-swift.struct","abstract":[],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UITraitImageDynamicRange"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UITraitImageDynamicRange-swift.struct"}},"variantOverrides":[{"patch":[{"op":"replace","value":"UIUserInterfaceSizeClass","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceSizeClass/title"},{"value":[{"text":"UIUserInterfaceSizeClass","kind":"identifier"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceSizeClass/fragments"},{"value":[{"kind":"identifier","text":"UIUserInterfaceSizeClass"}],"op":"replace","path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UIUserInterfaceSizeClass/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}