{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.Local-Authentication-Embedded-UI/documentation/LocalAuthenticationEmbeddedUI"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.Local-Authentication-Embedded-UI/documentation/LocalAuthenticationEmbeddedUI/local-authentication-embedded-ui-data-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Local Authentication Embedded UI"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Local Authentication Embedded UI Data Types"
  },
  "references": {
    "doc://com.apple.Local-Authentication-Embedded-UI/documentation/LocalAuthenticationEmbeddedUI": {
      "abstract": [
        {
          "text": "Present a standard local authentication view icon in a custom authentication view.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.Local-Authentication-Embedded-UI/documentation/LocalAuthenticationEmbeddedUI",
      "kind": "symbol",
      "role": "collection",
      "title": "Local Authentication Embedded UI",
      "type": "topic",
      "url": "/documentation/localauthenticationembeddedui"
    },
    "doc://com.apple.Local-Authentication-Embedded-UI/documentation/LocalAuthenticationEmbeddedUI/LAPresentationContext": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LAPresentationContext"
        }
      ],
      "identifier": "doc://com.apple.Local-Authentication-Embedded-UI/documentation/LocalAuthenticationEmbeddedUI/LAPresentationContext",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LAPresentationContext"
        }
      ],
      "role": "symbol",
      "title": "LAPresentationContext",
      "type": "topic",
      "url": "/documentation/localauthenticationembeddedui/lapresentationcontext"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.Local-Authentication-Embedded-UI/documentation/LocalAuthenticationEmbeddedUI/LAPresentationContext"
      ],
      "title": "Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.Local-Authentication-Embedded-UI/documentation/LocalAuthenticationEmbeddedUI/LAPresentationContext"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Local-Authentication-Embedded-UI~1documentation~1LocalAuthenticationEmbeddedUI~1LAPresentationContext/title",
          "value": "LAPresentationContext"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Local-Authentication-Embedded-UI~1documentation~1LocalAuthenticationEmbeddedUI~1LAPresentationContext/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LAPresentationContext"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.Local-Authentication-Embedded-UI~1documentation~1LocalAuthenticationEmbeddedUI~1LAPresentationContext/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LAPresentationContext"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/localauthenticationembeddedui/local-authentication-embedded-ui-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/localauthenticationembeddedui/local-authentication-embedded-ui-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
