{"sections":[],"metadata":{"role":"symbol","title":"init(rawValue:)","symbolKind":"init","roleHeading":"Initializer","platforms":[{"deprecated":false,"beta":false,"introducedAt":"14.0","name":"iOS","unavailable":false},{"deprecated":false,"beta":false,"introducedAt":"14.0","name":"iPadOS","unavailable":false},{"deprecated":false,"beta":false,"introducedAt":"14.0","name":"Mac Catalyst","unavailable":false},{"deprecated":false,"beta":false,"introducedAt":"1.0","name":"visionOS","unavailable":false}],"modules":[{"name":"UIKit"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"externalID":"s:So13UISwitchStyleV8rawValueABSgSi_tcfc"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"identifier":"doc://com.externally.resolved.symbol/s:Si","kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"platforms":["iOS","iPadOS","Mac Catalyst","visionOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.uikit/documentation/UIKit/UISwitch/Style-swift.enum/init(rawValue:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.uikit/documentation/UIKit","doc://com.apple.uikit/documentation/UIKit/UISwitch","doc://com.apple.uikit/documentation/UIKit/UISwitch/Style-swift.enum"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["/documentation/uikit/uiswitch/style-swift.enum/init(rawvalue:)"]}],"kind":"symbol","references":{"doc://com.apple.documentation/documentation/technologies":{"role":"overview","url":"/documentation/technologies","title":"Technologies","identifier":"doc://com.apple.documentation/documentation/technologies","abstract":[{"text":"","type":"text"}],"kind":"technologies","type":"topic"},"doc://com.apple.uikit/documentation/UIKit/UISwitch/Style-swift.enum":{"title":"UISwitch.Style","kind":"symbol","role":"symbol","type":"topic","url":"/documentation/uikit/uiswitch/style-swift.enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Style","kind":"identifier"}],"abstract":[{"type":"text","text":"Styles that determine the appearance of the switch."}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISwitch/Style-swift.enum","navigatorTitle":[{"text":"Style","kind":"identifier"}]},"doc://com.externally.resolved.symbol/s:Si":{"url":"/documentation/Swift/Int","identifier":"doc://com.externally.resolved.symbol/s:Si","role":"symbol","fragments":[{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Int"}],"type":"topic","title":"Int","kind":"symbol","abstract":[{"type":"text","text":"A signed integer value type."}]},"doc://com.apple.uikit/documentation/UIKit/UISwitch/Style-swift.enum/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISwitch/Style-swift.enum/init(rawValue:)","kind":"symbol","type":"topic","url":"/documentation/uikit/uiswitch/style-swift.enum/init(rawvalue:)","abstract":[],"role":"symbol","title":"init(rawValue:)"},"doc://com.apple.uikit/documentation/UIKit/UISwitch":{"abstract":[{"type":"text","text":"A control that offers a binary choice, such as on/off."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UISwitch"}],"role":"symbol","url":"/documentation/uikit/uiswitch","navigatorTitle":[{"kind":"identifier","text":"UISwitch"}],"identifier":"doc://com.apple.uikit/documentation/UIKit/UISwitch","type":"topic","title":"UISwitch","kind":"symbol"},"doc://com.apple.uikit/documentation/UIKit":{"kind":"symbol","role":"collection","title":"UIKit","identifier":"doc://com.apple.uikit/documentation/UIKit","url":"/documentation/uikit","abstract":[{"type":"text","text":"Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app."}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISwitch~1Style-swift.enum/title","op":"replace","value":"UISwitchStyle"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISwitch~1Style-swift.enum/fragments","op":"replace","value":[{"text":"UISwitchStyle","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISwitch~1Style-swift.enum/navigatorTitle","op":"replace","value":[{"text":"UISwitchStyle","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISwitch/title","op":"replace","value":"UISwitch"},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISwitch/fragments","op":"replace","value":[{"text":"UISwitch","kind":"identifier"}]},{"path":"/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISwitch/navigatorTitle","op":"replace","value":[{"text":"UISwitch","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}