{
  "abstract": [
    {
      "text": "A style indicating that the switch appears as an on/off slider.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.uikit/documentation/UIKit",
        "doc://com.apple.uikit/documentation/UIKit/UISwitch",
        "doc://com.apple.uikit/documentation/UIKit/UISwitch/Style-swift.enum"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.uikit/documentation/UIKit/UISwitch/Style-swift.enum/sliding"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@UISwitchStyle@UISwitchStyleSliding",
    "fragments": [
      {
        "kind": "keyword",
        "text": "case"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "sliding"
      }
    ],
    "modules": [
      {
        "name": "UIKit"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "UISwitchStyleSliding"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "14.0",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Case",
    "symbolKind": "case",
    "title": "UISwitch.Style.sliding"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "case"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "sliding"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.uikit/documentation/UIKit": {
      "abstract": [
        {
          "text": "Construct and manage a graphical, event-driven user interface for your iOS, iPadOS, or tvOS app.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit",
      "kind": "symbol",
      "role": "collection",
      "title": "UIKit",
      "type": "topic",
      "url": "/documentation/uikit"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISwitch": {
      "abstract": [
        {
          "text": "A control that offers a binary choice, such as on/off.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UISwitch"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISwitch",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISwitch"
        }
      ],
      "role": "symbol",
      "title": "UISwitch",
      "type": "topic",
      "url": "/documentation/uikit/uiswitch"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISwitch/Style-swift.enum": {
      "abstract": [
        {
          "text": "Styles that determine the appearance of the switch.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Style"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISwitch/Style-swift.enum",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "Style"
        }
      ],
      "role": "symbol",
      "title": "UISwitch.Style",
      "type": "topic",
      "url": "/documentation/uikit/uiswitch/style-swift.enum"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISwitch/Style-swift.enum/automatic": {
      "abstract": [
        {
          "text": "A style indicating that the system chooses the appearance of the switch according to the current user interface idiom.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "automatic"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISwitch/Style-swift.enum/automatic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISwitchStyleAutomatic"
        }
      ],
      "role": "symbol",
      "title": "UISwitch.Style.automatic",
      "type": "topic",
      "url": "/documentation/uikit/uiswitch/style-swift.enum/automatic"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISwitch/Style-swift.enum/checkbox": {
      "abstract": [
        {
          "text": "A style indicating that the switch appears as a Mac-style checkbox.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "checkbox"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISwitch/Style-swift.enum/checkbox",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISwitchStyleCheckbox"
        }
      ],
      "role": "symbol",
      "title": "UISwitch.Style.checkbox",
      "type": "topic",
      "url": "/documentation/uikit/uiswitch/style-swift.enum/checkbox"
    },
    "doc://com.apple.uikit/documentation/UIKit/UISwitch/Style-swift.enum/sliding": {
      "abstract": [
        {
          "text": "A style indicating that the switch appears as an on/off slider.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sliding"
        }
      ],
      "identifier": "doc://com.apple.uikit/documentation/UIKit/UISwitch/Style-swift.enum/sliding",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "UISwitchStyleSliding"
        }
      ],
      "role": "symbol",
      "title": "UISwitch.Style.sliding",
      "type": "topic",
      "url": "/documentation/uikit/uiswitch/style-swift.enum/sliding"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Styles",
      "generated": true,
      "identifiers": [
        "doc://com.apple.uikit/documentation/UIKit/UISwitch/Style-swift.enum/automatic",
        "doc://com.apple.uikit/documentation/UIKit/UISwitch/Style-swift.enum/checkbox"
      ],
      "title": "Styles"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "14.0",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "UISwitchStyleSliding"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISwitchStyleSliding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.uikit/documentation/UIKit",
                "doc://com.apple.uikit/documentation/UIKit/UISwitch/Style-swift.enum"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Styles",
              "generated": true,
              "identifiers": [
                "doc://com.apple.uikit/documentation/UIKit/UISwitch/Style-swift.enum/automatic",
                "doc://com.apple.uikit/documentation/UIKit/UISwitch/Style-swift.enum/checkbox"
              ],
              "title": "Styles"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "tvOS",
                  "visionOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "UISwitchStyleSliding"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISwitch~1Style-swift.enum/title",
          "value": "UISwitchStyle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISwitch~1Style-swift.enum/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISwitchStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISwitch~1Style-swift.enum/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISwitchStyle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISwitch~1Style-swift.enum~1automatic/title",
          "value": "UISwitchStyleAutomatic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISwitch~1Style-swift.enum~1automatic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISwitchStyleAutomatic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISwitch~1Style-swift.enum~1checkbox/title",
          "value": "UISwitchStyleCheckbox"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISwitch~1Style-swift.enum~1checkbox/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISwitchStyleCheckbox"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISwitch~1Style-swift.enum~1sliding/title",
          "value": "UISwitchStyleSliding"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISwitch~1Style-swift.enum~1sliding/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISwitchStyleSliding"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISwitch/title",
          "value": "UISwitch"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISwitch/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "UISwitch"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.uikit~1documentation~1UIKit~1UISwitch/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "UISwitch"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/uikit/uiswitch/style-swift.enum/sliding"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/uikit/uiswitch/style-swift.enum/sliding"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
