{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth",
        "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCILinkSupervisionTimeout"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCILinkSupervisionTimeout/init(handle:timeout:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "s:So34BluetoothHCILinkSupervisionTimeoutV6handle7timeoutABs6UInt16V_AFtcfc",
    "fragments": [
      {
        "kind": "identifier",
        "text": "init"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "externalParam",
        "text": "handle"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@BluetoothConnectionHandle",
        "text": "BluetoothConnectionHandle"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "externalParam",
        "text": "timeout"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s6UInt16V",
        "text": "UInt16"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "IOBluetooth"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Initializer",
    "symbolKind": "init",
    "title": "init(handle:timeout:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "macOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "init"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "handle"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothConnectionHandle",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@BluetoothConnectionHandle",
              "text": "BluetoothConnectionHandle"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "timeout"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s6UInt16V",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s6UInt16V",
              "text": "UInt16"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth": {
      "abstract": [
        {
          "text": "Gain user-space access to Bluetooth devices.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth",
      "kind": "symbol",
      "role": "collection",
      "title": "IOBluetooth",
      "type": "topic",
      "url": "/documentation/iobluetooth"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothConnectionHandle": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothConnectionHandle"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothConnectionHandle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothConnectionHandle"
        }
      ],
      "role": "symbol",
      "title": "BluetoothConnectionHandle",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothconnectionhandle"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCILinkSupervisionTimeout": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BluetoothHCILinkSupervisionTimeout"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCILinkSupervisionTimeout",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BluetoothHCILinkSupervisionTimeout"
        }
      ],
      "role": "symbol",
      "title": "BluetoothHCILinkSupervisionTimeout",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcilinksupervisiontimeout"
    },
    "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCILinkSupervisionTimeout/init(handle:timeout:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "handle"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@BluetoothConnectionHandle",
          "text": "BluetoothConnectionHandle"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "timeout"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.iobluetooth/documentation/IOBluetooth/BluetoothHCILinkSupervisionTimeout/init(handle:timeout:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(handle:timeout:)",
      "type": "topic",
      "url": "/documentation/iobluetooth/bluetoothhcilinksupervisiontimeout/init(handle:timeout:)"
    },
    "doc://com.externally.resolved.symbol/s:s6UInt16V": {
      "abstract": [
        {
          "text": "A 16-bit unsigned integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UInt16"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s6UInt16V",
      "kind": "symbol",
      "role": "symbol",
      "title": "UInt16",
      "type": "topic",
      "url": "/documentation/Swift/UInt16"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothConnectionHandle/title",
          "value": "BluetoothConnectionHandle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothConnectionHandle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothConnectionHandle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothConnectionHandle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothConnectionHandle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCILinkSupervisionTimeout/title",
          "value": "BluetoothHCILinkSupervisionTimeout"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCILinkSupervisionTimeout/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCILinkSupervisionTimeout"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.iobluetooth~1documentation~1IOBluetooth~1BluetoothHCILinkSupervisionTimeout/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BluetoothHCILinkSupervisionTimeout"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/iobluetooth/bluetoothhcilinksupervisiontimeout/init(handle:timeout:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    }
  ]
}
