{
  "diffAvailability": {
    "major": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.0",
        "16.3 beta 2"
      ]
    },
    "minor": {
      "change": "modified",
      "platform": "Xcode",
      "versions": [
        "16.2",
        "16.3 beta 2"
      ]
    }
  },
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/core-text-structures"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Core Text Structures"
  },
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions": {
      "abstract": [
        {
          "text": "Options for getting the bounds of a line of text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTLineBoundsOptions"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTLineBoundsOptions"
        }
      ],
      "role": "symbol",
      "title": "CTLineBoundsOptions",
      "type": "topic",
      "url": "/documentation/coretext/ctlineboundsoptions"
    },
    "doc://com.apple.coretext/documentation/CoreText/LtagStringRange": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LtagStringRange"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/LtagStringRange",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LtagStringRange"
        }
      ],
      "role": "symbol",
      "title": "LtagStringRange",
      "type": "topic",
      "url": "/documentation/coretext/ltagstringrange"
    },
    "doc://com.apple.coretext/documentation/CoreText/LtagTable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "LtagTable"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/LtagTable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "LtagTable"
        }
      ],
      "role": "symbol",
      "title": "LtagTable",
      "type": "topic",
      "url": "/documentation/coretext/ltagtable"
    },
    "doc://com.apple.coretext/documentation/CoreText/SFNTLookupVectorHeader": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SFNTLookupVectorHeader"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/SFNTLookupVectorHeader",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "SFNTLookupVectorHeader"
        }
      ],
      "role": "symbol",
      "title": "SFNTLookupVectorHeader",
      "type": "topic",
      "url": "/documentation/coretext/sfntlookupvectorheader"
    },
    "doc://com.apple.coretext/documentation/CoreText/core-text-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/core-text-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Text Constants",
      "type": "topic",
      "url": "/documentation/coretext/core-text-constants"
    },
    "doc://com.apple.coretext/documentation/CoreText/core-text-data-types": {
      "abstract": [],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/core-text-data-types",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Text Data Types",
      "type": "topic",
      "url": "/documentation/coretext/core-text-data-types"
    },
    "doc://com.apple.coretext/documentation/CoreText/core-text-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/core-text-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Text Enumerations",
      "type": "topic",
      "url": "/documentation/coretext/core-text-enumerations"
    },
    "doc://com.apple.coretext/documentation/CoreText/core-text-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/core-text-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Text Functions",
      "type": "topic",
      "url": "/documentation/coretext/core-text-functions"
    },
    "doc://com.apple.coretext/documentation/CoreText/sfnt-support": {
      "abstract": [],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/sfnt-support",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SFNT Support",
      "type": "topic",
      "url": "/documentation/coretext/sfnt-support"
    },
    "doc://com.apple.coretext/documentation/CoreText/styling-attributed-strings": {
      "abstract": [
        {
          "text": "Attributes to which Core Text responds when placed in a ",
          "type": "text"
        },
        {
          "code": "CFAttributedString",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/styling-attributed-strings",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Styling Attributed Strings",
      "type": "topic",
      "url": "/documentation/coretext/styling-attributed-strings"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/styling-attributed-strings",
        "doc://com.apple.coretext/documentation/CoreText/core-text-enumerations",
        "doc://com.apple.coretext/documentation/CoreText/core-text-constants",
        "doc://com.apple.coretext/documentation/CoreText/core-text-functions",
        "doc://com.apple.coretext/documentation/CoreText/core-text-data-types",
        "doc://com.apple.coretext/documentation/CoreText/sfnt-support"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Structures",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions",
        "doc://com.apple.coretext/documentation/CoreText/LtagStringRange",
        "doc://com.apple.coretext/documentation/CoreText/LtagTable",
        "doc://com.apple.coretext/documentation/CoreText/SFNTLookupVectorHeader"
      ],
      "title": "Structures"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Structures",
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions",
                "doc://com.apple.coretext/documentation/CoreText/LtagStringRange",
                "doc://com.apple.coretext/documentation/CoreText/LtagTable",
                "doc://com.apple.coretext/documentation/CoreText/SFNTLookupVectorHeader"
              ],
              "title": "Structures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/styling-attributed-strings",
                "doc://com.apple.coretext/documentation/CoreText/core-text-enumerations",
                "doc://com.apple.coretext/documentation/CoreText/core-text-constants",
                "doc://com.apple.coretext/documentation/CoreText/core-text-functions",
                "doc://com.apple.coretext/documentation/CoreText/core-text-data-types",
                "doc://com.apple.coretext/documentation/CoreText/sfnt-support"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1SFNTLookupVectorHeader/title",
          "value": "SFNTLookupVectorHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1SFNTLookupVectorHeader/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "SFNTLookupVectorHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1SFNTLookupVectorHeader/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "SFNTLookupVectorHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1LtagTable/title",
          "value": "LtagTable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1LtagTable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LtagTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1LtagTable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LtagTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBoundsOptions/title",
          "value": "CTLineBoundsOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBoundsOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineBoundsOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBoundsOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineBoundsOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1LtagStringRange/title",
          "value": "LtagStringRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1LtagStringRange/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "LtagStringRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1LtagStringRange/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "LtagStringRange"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/core-text-structures"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/core-text-structures"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
