{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CoreText-macros"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Macros"
  },
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CT_AVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CT_AVAILABLE"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CT_AVAILABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "CT_AVAILABLE",
      "type": "topic",
      "url": "/documentation/coretext/ct_available"
    },
    "doc://com.apple.coretext/documentation/CoreText/CT_DEPRECATED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CT_DEPRECATED"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CT_DEPRECATED",
      "kind": "symbol",
      "role": "symbol",
      "title": "CT_DEPRECATED",
      "type": "topic",
      "url": "/documentation/coretext/ct_deprecated"
    },
    "doc://com.apple.coretext/documentation/CoreText/CT_DEPRECATED_WITH_REPLACEMENT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CT_DEPRECATED_WITH_REPLACEMENT"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CT_DEPRECATED_WITH_REPLACEMENT",
      "kind": "symbol",
      "role": "symbol",
      "title": "CT_DEPRECATED_WITH_REPLACEMENT",
      "type": "topic",
      "url": "/documentation/coretext/ct_deprecated_with_replacement"
    },
    "doc://com.apple.coretext/documentation/CoreText/CT_ENUM_AVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CT_ENUM_AVAILABLE"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CT_ENUM_AVAILABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "CT_ENUM_AVAILABLE",
      "type": "topic",
      "url": "/documentation/coretext/ct_enum_available"
    },
    "doc://com.apple.coretext/documentation/CoreText/CT_ENUM_DEPRECATED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CT_ENUM_DEPRECATED"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CT_ENUM_DEPRECATED",
      "kind": "symbol",
      "role": "symbol",
      "title": "CT_ENUM_DEPRECATED",
      "type": "topic",
      "url": "/documentation/coretext/ct_enum_deprecated"
    },
    "doc://com.apple.coretext/documentation/CoreText/CT_ENUM_UNAVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CT_ENUM_UNAVAILABLE"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CT_ENUM_UNAVAILABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "CT_ENUM_UNAVAILABLE",
      "type": "topic",
      "url": "/documentation/coretext/ct_enum_unavailable"
    },
    "doc://com.apple.coretext/documentation/CoreText/CT_EXPORT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CT_EXPORT"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CT_EXPORT",
      "kind": "symbol",
      "role": "symbol",
      "title": "CT_EXPORT",
      "type": "topic",
      "url": "/documentation/coretext/ct_export"
    },
    "doc://com.apple.coretext/documentation/CoreText/CT_SWIFT_SENDABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CT_SWIFT_SENDABLE"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CT_SWIFT_SENDABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "CT_SWIFT_SENDABLE",
      "type": "topic",
      "url": "/documentation/coretext/ct_swift_sendable"
    },
    "doc://com.apple.coretext/documentation/CoreText/CT_UNAVAILABLE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "CT_UNAVAILABLE"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CT_UNAVAILABLE",
      "kind": "symbol",
      "role": "symbol",
      "title": "CT_UNAVAILABLE",
      "type": "topic",
      "url": "/documentation/coretext/ct_unavailable"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Macros",
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CT_AVAILABLE",
                "doc://com.apple.coretext/documentation/CoreText/CT_DEPRECATED",
                "doc://com.apple.coretext/documentation/CoreText/CT_DEPRECATED_WITH_REPLACEMENT",
                "doc://com.apple.coretext/documentation/CoreText/CT_ENUM_AVAILABLE",
                "doc://com.apple.coretext/documentation/CoreText/CT_ENUM_DEPRECATED",
                "doc://com.apple.coretext/documentation/CoreText/CT_ENUM_UNAVAILABLE",
                "doc://com.apple.coretext/documentation/CoreText/CT_EXPORT",
                "doc://com.apple.coretext/documentation/CoreText/CT_SWIFT_SENDABLE",
                "doc://com.apple.coretext/documentation/CoreText/CT_UNAVAILABLE"
              ],
              "title": "Macros"
            }
          ]
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/coretext-macros"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/coretext-macros"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
