{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/core-text-data-types"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Core Text Data Types"
  },
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/ATSFontRef": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ATSFontRef"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/ATSFontRef",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ATSFontRef"
        }
      ],
      "role": "symbol",
      "title": "ATSFontRef",
      "type": "topic",
      "url": "/documentation/coretext/atsfontref"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontCollectionSortDescriptorsCallback": {
      "abstract": [
        {
          "text": "The collection sorting callback type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontCollectionSortDescriptorsCallback"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontCollectionSortDescriptorsCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontCollectionSortDescriptorsCallback"
        }
      ],
      "role": "symbol",
      "title": "CTFontCollectionSortDescriptorsCallback",
      "type": "topic",
      "url": "/documentation/coretext/ctfontcollectionsortdescriptorscallback"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorProgressHandler": {
      "abstract": [
        {
          "text": "The progress callback type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontDescriptorProgressHandler"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorProgressHandler",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontDescriptorProgressHandler"
        }
      ],
      "role": "symbol",
      "title": "CTFontDescriptorProgressHandler",
      "type": "topic",
      "url": "/documentation/coretext/ctfontdescriptorprogresshandler"
    },
    "doc://com.apple.coretext/documentation/CoreText/core-text-constants": {
      "abstract": [],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/core-text-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Text Constants",
      "type": "topic",
      "url": "/documentation/coretext/core-text-constants"
    },
    "doc://com.apple.coretext/documentation/CoreText/core-text-enumerations": {
      "abstract": [],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/core-text-enumerations",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Text Enumerations",
      "type": "topic",
      "url": "/documentation/coretext/core-text-enumerations"
    },
    "doc://com.apple.coretext/documentation/CoreText/core-text-functions": {
      "abstract": [],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/core-text-functions",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Text Functions",
      "type": "topic",
      "url": "/documentation/coretext/core-text-functions"
    },
    "doc://com.apple.coretext/documentation/CoreText/core-text-structures": {
      "abstract": [],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/core-text-structures",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Core Text Structures",
      "type": "topic",
      "url": "/documentation/coretext/core-text-structures"
    },
    "doc://com.apple.coretext/documentation/CoreText/sfnt-support": {
      "abstract": [],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/sfnt-support",
      "kind": "article",
      "role": "collectionGroup",
      "title": "SFNT Support",
      "type": "topic",
      "url": "/documentation/coretext/sfnt-support"
    },
    "doc://com.apple.coretext/documentation/CoreText/styling-attributed-strings": {
      "abstract": [
        {
          "text": "Attributes to which Core Text responds when placed in a ",
          "type": "text"
        },
        {
          "code": "CFAttributedString",
          "type": "codeVoice"
        },
        {
          "text": " object.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/styling-attributed-strings",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Styling Attributed Strings",
      "type": "topic",
      "url": "/documentation/coretext/styling-attributed-strings"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Reference",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/styling-attributed-strings",
        "doc://com.apple.coretext/documentation/CoreText/core-text-structures",
        "doc://com.apple.coretext/documentation/CoreText/core-text-enumerations",
        "doc://com.apple.coretext/documentation/CoreText/core-text-constants",
        "doc://com.apple.coretext/documentation/CoreText/core-text-functions",
        "doc://com.apple.coretext/documentation/CoreText/sfnt-support"
      ],
      "title": "Reference"
    }
  ],
  "topicSections": [
    {
      "anchor": "Data-Types",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/ATSFontRef",
        "doc://com.apple.coretext/documentation/CoreText/CTFontCollectionSortDescriptorsCallback",
        "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorProgressHandler"
      ],
      "title": "Data Types"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Data-Types",
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/ATSFontRef",
                "doc://com.apple.coretext/documentation/CoreText/CTFontCollectionSortDescriptorsCallback",
                "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorProgressHandler"
              ],
              "title": "Data Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Reference",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/styling-attributed-strings",
                "doc://com.apple.coretext/documentation/CoreText/core-text-structures",
                "doc://com.apple.coretext/documentation/CoreText/core-text-enumerations",
                "doc://com.apple.coretext/documentation/CoreText/core-text-constants",
                "doc://com.apple.coretext/documentation/CoreText/core-text-functions",
                "doc://com.apple.coretext/documentation/CoreText/sfnt-support"
              ],
              "title": "Reference"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1ATSFontRef/title",
          "value": "ATSFontRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1ATSFontRef/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ATSFontRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1ATSFontRef/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "ATSFontRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCollectionSortDescriptorsCallback/title",
          "value": "CTFontCollectionSortDescriptorsCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCollectionSortDescriptorsCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontCollectionSortDescriptorsCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCollectionSortDescriptorsCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontCollectionSortDescriptorsCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptorProgressHandler/title",
          "value": "CTFontDescriptorProgressHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptorProgressHandler/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontDescriptorProgressHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptorProgressHandler/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontDescriptorProgressHandler"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/core-text-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/core-text-data-types"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
