{
  "abstract": [
    {
      "text": "Constants that specify character collections.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CTCharacterCollection",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CTCharacterCollection"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CTCharacterCollection"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CTCharacterCollection"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CTCharacterCollection"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection": {
      "abstract": [
        {
          "text": "Constants that specify character collections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTCharacterCollection"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTCharacterCollection"
        }
      ],
      "role": "symbol",
      "title": "CTCharacterCollection",
      "type": "topic",
      "url": "/documentation/coretext/ctcharactercollection"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/adobeCNS1": {
      "abstract": [
        {
          "text": "The Adobe-CNS1 mapping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adobeCNS1"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/adobeCNS1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTCharacterCollectionAdobeCNS1"
        }
      ],
      "role": "symbol",
      "title": "CTCharacterCollection.adobeCNS1",
      "type": "topic",
      "url": "/documentation/coretext/ctcharactercollection/adobecns1"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/adobeGB1": {
      "abstract": [
        {
          "text": "The Adobe-GB1 mapping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adobeGB1"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/adobeGB1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTCharacterCollectionAdobeGB1"
        }
      ],
      "role": "symbol",
      "title": "CTCharacterCollection.adobeGB1",
      "type": "topic",
      "url": "/documentation/coretext/ctcharactercollection/adobegb1"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/adobeJapan1": {
      "abstract": [
        {
          "text": "The Adobe-Japan1 mapping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adobeJapan1"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/adobeJapan1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTCharacterCollectionAdobeJapan1"
        }
      ],
      "role": "symbol",
      "title": "CTCharacterCollection.adobeJapan1",
      "type": "topic",
      "url": "/documentation/coretext/ctcharactercollection/adobejapan1"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/adobeJapan2": {
      "abstract": [
        {
          "text": "The Adobe-Japan2 mapping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adobeJapan2"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/adobeJapan2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTCharacterCollectionAdobeJapan2"
        }
      ],
      "role": "symbol",
      "title": "CTCharacterCollection.adobeJapan2",
      "type": "topic",
      "url": "/documentation/coretext/ctcharactercollection/adobejapan2"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/adobeKorea1": {
      "abstract": [
        {
          "text": "The Adobe-Korea1 mapping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "adobeKorea1"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/adobeKorea1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTCharacterCollectionAdobeKorea1"
        }
      ],
      "role": "symbol",
      "title": "CTCharacterCollection.adobeKorea1",
      "type": "topic",
      "url": "/documentation/coretext/ctcharactercollection/adobekorea1"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/identityMapping": {
      "abstract": [
        {
          "text": "The character identifier is equal to the glyph index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "identityMapping"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/identityMapping",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTCharacterCollectionIdentityMapping"
        }
      ],
      "role": "symbol",
      "title": "CTCharacterCollection.identityMapping",
      "type": "topic",
      "url": "/documentation/coretext/ctcharactercollection/identitymapping"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/coretext/ctcharactercollection/init(rawvalue:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTAdobeCNS1CharacterCollection": {
      "abstract": [
        {
          "text": "The Adobe-CNS1 mapping.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTAdobeCNS1CharacterCollection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTCharacterCollection",
          "text": "CTCharacterCollection"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTAdobeCNS1CharacterCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTAdobeCNS1CharacterCollection"
        }
      ],
      "role": "symbol",
      "title": "kCTAdobeCNS1CharacterCollection",
      "type": "topic",
      "url": "/documentation/coretext/ctcharactercollection/kctadobecns1charactercollection"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTAdobeGB1CharacterCollection": {
      "abstract": [
        {
          "text": "The Adobe-GB1 mapping.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTAdobeGB1CharacterCollection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTCharacterCollection",
          "text": "CTCharacterCollection"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTAdobeGB1CharacterCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTAdobeGB1CharacterCollection"
        }
      ],
      "role": "symbol",
      "title": "kCTAdobeGB1CharacterCollection",
      "type": "topic",
      "url": "/documentation/coretext/ctcharactercollection/kctadobegb1charactercollection"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTAdobeJapan1CharacterCollection": {
      "abstract": [
        {
          "text": "The Adobe-Japan1 mapping.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTAdobeJapan1CharacterCollection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTCharacterCollection",
          "text": "CTCharacterCollection"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTAdobeJapan1CharacterCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTAdobeJapan1CharacterCollection"
        }
      ],
      "role": "symbol",
      "title": "kCTAdobeJapan1CharacterCollection",
      "type": "topic",
      "url": "/documentation/coretext/ctcharactercollection/kctadobejapan1charactercollection"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTAdobeJapan2CharacterCollection": {
      "abstract": [
        {
          "text": "The Adobe-Japan2 mapping.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTAdobeJapan2CharacterCollection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTCharacterCollection",
          "text": "CTCharacterCollection"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTAdobeJapan2CharacterCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTAdobeJapan2CharacterCollection"
        }
      ],
      "role": "symbol",
      "title": "kCTAdobeJapan2CharacterCollection",
      "type": "topic",
      "url": "/documentation/coretext/ctcharactercollection/kctadobejapan2charactercollection"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTAdobeKorea1CharacterCollection": {
      "abstract": [
        {
          "text": "The Adobe-Korea1 mapping.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTAdobeKorea1CharacterCollection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTCharacterCollection",
          "text": "CTCharacterCollection"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTAdobeKorea1CharacterCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTAdobeKorea1CharacterCollection"
        }
      ],
      "role": "symbol",
      "title": "kCTAdobeKorea1CharacterCollection",
      "type": "topic",
      "url": "/documentation/coretext/ctcharactercollection/kctadobekorea1charactercollection"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTIdentityMappingCharacterCollection": {
      "abstract": [
        {
          "text": "The character identifier is equal to the glyph index.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTIdentityMappingCharacterCollection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTCharacterCollection",
          "text": "CTCharacterCollection"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTIdentityMappingCharacterCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTIdentityMappingCharacterCollection"
        }
      ],
      "role": "symbol",
      "title": "kCTIdentityMappingCharacterCollection",
      "type": "topic",
      "url": "/documentation/coretext/ctcharactercollection/kctidentitymappingcharactercollection"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/identityMapping",
        "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/adobeCNS1",
        "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/adobeGB1",
        "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/adobeJapan1",
        "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/adobeJapan2",
        "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/adobeKorea1"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTIdentityMappingCharacterCollection",
        "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTAdobeCNS1CharacterCollection",
        "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTAdobeGB1CharacterCollection",
        "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTAdobeJapan1CharacterCollection",
        "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTAdobeJapan2CharacterCollection",
        "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTAdobeKorea1CharacterCollection"
      ],
      "title": "Deprecated"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CTCharacterCollection"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCharacterCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCharacterCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/identityMapping",
                "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/adobeCNS1",
                "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/adobeGB1",
                "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/adobeJapan1",
                "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/adobeJapan2",
                "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/adobeKorea1"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTIdentityMappingCharacterCollection",
                "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTAdobeCNS1CharacterCollection",
                "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTAdobeGB1CharacterCollection",
                "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTAdobeJapan1CharacterCollection",
                "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTAdobeJapan2CharacterCollection",
                "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTAdobeKorea1CharacterCollection"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CTCharacterCollection"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint16_t",
                    "text": "uint16_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1kCTAdobeCNS1CharacterCollection/title",
          "value": "kCTAdobeCNS1CharacterCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1kCTAdobeCNS1CharacterCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTAdobeCNS1CharacterCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection/title",
          "value": "CTCharacterCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCharacterCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCharacterCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1kCTIdentityMappingCharacterCollection/title",
          "value": "kCTIdentityMappingCharacterCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1kCTIdentityMappingCharacterCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTIdentityMappingCharacterCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1adobeJapan1/title",
          "value": "kCTCharacterCollectionAdobeJapan1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1adobeJapan1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTCharacterCollectionAdobeJapan1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1kCTAdobeGB1CharacterCollection/title",
          "value": "kCTAdobeGB1CharacterCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1kCTAdobeGB1CharacterCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTAdobeGB1CharacterCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1identityMapping/title",
          "value": "kCTCharacterCollectionIdentityMapping"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1identityMapping/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTCharacterCollectionIdentityMapping"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1adobeCNS1/title",
          "value": "kCTCharacterCollectionAdobeCNS1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1adobeCNS1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTCharacterCollectionAdobeCNS1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1kCTAdobeJapan1CharacterCollection/title",
          "value": "kCTAdobeJapan1CharacterCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1kCTAdobeJapan1CharacterCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTAdobeJapan1CharacterCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1adobeKorea1/title",
          "value": "kCTCharacterCollectionAdobeKorea1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1adobeKorea1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTCharacterCollectionAdobeKorea1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1adobeJapan2/title",
          "value": "kCTCharacterCollectionAdobeJapan2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1adobeJapan2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTCharacterCollectionAdobeJapan2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1kCTAdobeJapan2CharacterCollection/title",
          "value": "kCTAdobeJapan2CharacterCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1kCTAdobeJapan2CharacterCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTAdobeJapan2CharacterCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1adobeGB1/title",
          "value": "kCTCharacterCollectionAdobeGB1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1adobeGB1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTCharacterCollectionAdobeGB1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1kCTAdobeKorea1CharacterCollection/title",
          "value": "kCTAdobeKorea1CharacterCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1kCTAdobeKorea1CharacterCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTAdobeKorea1CharacterCollection"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/ctcharactercollection"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/ctcharactercollection"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
