{
  "abstract": [
    {
      "text": "Creates an array of font descriptors that match the specified collection.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTFontCollectionCreateMatchingFontDescriptorsWithOptions(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CTFontCollectionCreateMatchingFontDescriptorsWithOptions",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CTFontCollectionCreateMatchingFontDescriptorsWithOptions"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CTFontCollectionRef",
        "text": "CTFontCollection"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFDictionaryRef",
        "text": "CFDictionary"
      },
      {
        "kind": "text",
        "text": "?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFArrayRef",
        "text": "CFArray"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CTFontCollectionCreateMatchingFontDescriptorsWithOptions"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.7",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "12.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "5.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CTFontCollectionCreateMatchingFontDescriptorsWithOptions(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CTFontCollectionCreateMatchingFontDescriptorsWithOptions"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "collection"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontCollection",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CTFontCollectionRef",
              "text": "CTFontCollection"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "options"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFDictionaryRef",
              "text": "CFDictionary"
            },
            {
              "kind": "text",
              "text": "?) -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFArrayRef",
              "text": "CFArray"
            },
            {
              "kind": "text",
              "text": "?"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The font collection reference.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "collection"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The options dictionary. Passing in ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": " returns the same results as calling ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontCollectionCreateMatchingFontDescriptors(_:)",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", which uses the options specified during the collection’s creation.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "options"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "An array of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptor",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " objects that match the collection definition, or ",
              "type": "text"
            },
            {
              "code": "NULL",
              "type": "codeVoice"
            },
            {
              "text": " if there are none.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontCollection": {
      "abstract": [
        {
          "text": "A font collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontCollection"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontCollection"
        }
      ],
      "role": "symbol",
      "title": "CTFontCollection",
      "type": "topic",
      "url": "/documentation/coretext/ctfontcollection"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontCollectionCreateMatchingFontDescriptors(_:)": {
      "abstract": [
        {
          "text": "Returns an array of font descriptors matching the collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontCollectionCreateMatchingFontDescriptors"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontCollectionRef",
          "text": "CTFontCollection"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontCollectionCreateMatchingFontDescriptors(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontCollectionCreateMatchingFontDescriptors"
        }
      ],
      "role": "symbol",
      "title": "CTFontCollectionCreateMatchingFontDescriptors(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontcollectioncreatematchingfontdescriptors(_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontCollectionCreateMatchingFontDescriptorsForFamily(_:_:_:)": {
      "abstract": [
        {
          "text": "Retrieves an array of font descriptors that match the specified family, one descriptor for each style in the collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontCollectionCreateMatchingFontDescriptorsForFamily"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontCollectionRef",
          "text": "CTFontCollection"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontCollectionCreateMatchingFontDescriptorsForFamily(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontCollectionCreateMatchingFontDescriptorsForFamily"
        }
      ],
      "role": "symbol",
      "title": "CTFontCollectionCreateMatchingFontDescriptorsForFamily(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontcollectioncreatematchingfontdescriptorsforfamily(_:_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontCollectionCreateMatchingFontDescriptorsSortedWithCallback(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns the array of matching font descriptors sorted with the callback function.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontCollectionCreateMatchingFontDescriptorsSortedWithCallback"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontCollectionRef",
          "text": "CTFontCollection"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontCollectionSortDescriptorsCallback",
          "text": "CTFontCollectionSortDescriptorsCallback"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontCollectionCreateMatchingFontDescriptorsSortedWithCallback(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontCollectionCreateMatchingFontDescriptorsSortedWithCallback"
        }
      ],
      "role": "symbol",
      "title": "CTFontCollectionCreateMatchingFontDescriptorsSortedWithCallback(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontcollectioncreatematchingfontdescriptorssortedwithcallback(_:_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontCollectionCreateMatchingFontDescriptorsWithOptions(_:_:)": {
      "abstract": [
        {
          "text": "Creates an array of font descriptors that match the specified collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontCollectionCreateMatchingFontDescriptorsWithOptions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontCollectionRef",
          "text": "CTFontCollection"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontCollectionCreateMatchingFontDescriptorsWithOptions(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontCollectionCreateMatchingFontDescriptorsWithOptions"
        }
      ],
      "role": "symbol",
      "title": "CTFontCollectionCreateMatchingFontDescriptorsWithOptions(_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontcollectioncreatematchingfontdescriptorswithoptions(_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontCollectionSortDescriptorsCallback": {
      "abstract": [
        {
          "text": "The collection sorting callback type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontCollectionSortDescriptorsCallback"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontCollectionSortDescriptorsCallback",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontCollectionSortDescriptorsCallback"
        }
      ],
      "role": "symbol",
      "title": "CTFontCollectionSortDescriptorsCallback",
      "type": "topic",
      "url": "/documentation/coretext/ctfontcollectionsortdescriptorscallback"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptor": {
      "abstract": [
        {
          "text": "A font descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontDescriptor"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontDescriptor"
        }
      ],
      "role": "symbol",
      "title": "CTFontDescriptor",
      "type": "topic",
      "url": "/documentation/coretext/ctfontdescriptor"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFArrayRef": {
      "abstract": [
        {
          "text": "A reference to an immutable array object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFArray"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFArray",
      "type": "topic",
      "url": "/documentation/corefoundation/cfarray"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef": {
      "abstract": [
        {
          "text": "A reference to an immutable dictionary object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFDictionary"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFDictionary",
      "type": "topic",
      "url": "/documentation/corefoundation/cfdictionary"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Font-Descriptors",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTFontCollectionCreateMatchingFontDescriptors(_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTFontCollectionCreateMatchingFontDescriptorsSortedWithCallback(_:_:_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTFontCollectionCreateMatchingFontDescriptorsForFamily(_:_:_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTFontCollectionSortDescriptorsCallback"
      ],
      "title": "Getting Font Descriptors"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.7",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "12.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "5.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CTFontCollectionCreateMatchingFontDescriptorsWithOptions"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontCollectionCreateMatchingFontDescriptorsWithOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-Font-Descriptors",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTFontCollectionCreateMatchingFontDescriptors(_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTFontCollectionCreateMatchingFontDescriptorsSortedWithCallback(_:_:_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTFontCollectionCreateMatchingFontDescriptorsForFamily(_:_:_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTFontCollectionSortDescriptorsCallback"
              ],
              "title": "Getting Font Descriptors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFArrayRef",
                    "text": "CFArrayRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CTFontCollectionCreateMatchingFontDescriptorsWithOptions"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontCollection",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CTFontCollectionRef",
                    "text": "CTFontCollectionRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "collection"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFDictionaryRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFDictionaryRef",
                    "text": "CFDictionaryRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "options"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The font collection reference.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "collection"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The options dictionary. Passing in ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": " returns the same results as calling ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontCollectionCreateMatchingFontDescriptors(_:)",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ", which uses the options specified during the collection’s creation.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "options"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "An array of ",
                    "type": "text"
                  },
                  {
                    "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptor",
                    "isActive": true,
                    "type": "reference"
                  },
                  {
                    "text": " objects that match the collection definition, or ",
                    "type": "text"
                  },
                  {
                    "code": "NULL",
                    "type": "codeVoice"
                  },
                  {
                    "text": " if there are none.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCollectionCreateMatchingFontDescriptorsForFamily(_:_:_:)/title",
          "value": "CTFontCollectionCreateMatchingFontDescriptorsForFamily"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCollectionCreateMatchingFontDescriptorsForFamily(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontCollectionCreateMatchingFontDescriptorsForFamily"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFArrayRef/title",
          "value": "CFArrayRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCollectionCreateMatchingFontDescriptors(_:)/title",
          "value": "CTFontCollectionCreateMatchingFontDescriptors"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCollectionCreateMatchingFontDescriptors(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontCollectionCreateMatchingFontDescriptors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFDictionaryRef/title",
          "value": "CFDictionaryRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCollectionSortDescriptorsCallback/title",
          "value": "CTFontCollectionSortDescriptorsCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCollectionSortDescriptorsCallback/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontCollectionSortDescriptorsCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCollectionSortDescriptorsCallback/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontCollectionSortDescriptorsCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCollectionCreateMatchingFontDescriptorsSortedWithCallback(_:_:_:)/title",
          "value": "CTFontCollectionCreateMatchingFontDescriptorsSortedWithCallback"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCollectionCreateMatchingFontDescriptorsSortedWithCallback(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontCollectionCreateMatchingFontDescriptorsSortedWithCallback"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCollection/title",
          "value": "CTFontCollectionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontCollectionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCollection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontCollectionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptor/title",
          "value": "CTFontDescriptorRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontDescriptorRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontDescriptorRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCollectionCreateMatchingFontDescriptorsWithOptions(_:_:)/title",
          "value": "CTFontCollectionCreateMatchingFontDescriptorsWithOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCollectionCreateMatchingFontDescriptorsWithOptions(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontCollectionCreateMatchingFontDescriptorsWithOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/ctfontcollectioncreatematchingfontdescriptorswithoptions(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/ctfontcollectioncreatematchingfontdescriptorswithoptions(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
