{
  "abstract": [
    {
      "text": "Errors that prevent unregistration of fonts for a specified font file URL.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CTFontManagerError",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CTFontManagerError"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CTFontManagerError"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CTFontManagerError"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CTFontManagerError"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState": {
      "abstract": [
        {
          "text": "Constants that track the progress of font descriptor matching.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontDescriptorMatchingState"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontDescriptorMatchingState"
        }
      ],
      "role": "symbol",
      "title": "CTFontDescriptorMatchingState",
      "type": "topic",
      "url": "/documentation/coretext/ctfontdescriptormatchingstate"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerAutoActivationSetting": {
      "abstract": [
        {
          "text": "Sets the auto-activation for the specified bundle identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontManagerAutoActivationSetting"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerAutoActivationSetting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontManagerAutoActivationSetting"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerAutoActivationSetting",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagerautoactivationsetting"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError": {
      "abstract": [
        {
          "text": "Errors that prevent unregistration of fonts for a specified font file URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontManagerError"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontManagerError"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerError",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagererror"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/alreadyRegistered": {
      "abstract": [
        {
          "text": "An error that indicates the file is already registered in the specified scope.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alreadyRegistered"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/alreadyRegistered",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManagerErrorAlreadyRegistered"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerError.alreadyRegistered",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagererror/alreadyregistered"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/assetNotFound": {
      "abstract": [
        {
          "text": "An error that indicates the asset isn’t found.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "assetNotFound"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/assetNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManagerErrorAssetNotFound"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerError.assetNotFound",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagererror/assetnotfound"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/cancelledByUser": {
      "abstract": [
        {
          "text": "An error that indicates the user cancelled the operation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cancelledByUser"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/cancelledByUser",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManagerErrorCancelledByUser"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerError.cancelledByUser",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagererror/cancelledbyuser"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/duplicatedName": {
      "abstract": [
        {
          "text": "An error that indicates the file can’t register because of a duplicate font name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "duplicatedName"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/duplicatedName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManagerErrorDuplicatedName"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerError.duplicatedName",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagererror/duplicatedname"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/exceededResourceLimit": {
      "abstract": [
        {
          "text": "An error that indicates an operation failure due to a system limitation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "exceededResourceLimit"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/exceededResourceLimit",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManagerErrorExceededResourceLimit"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerError.exceededResourceLimit",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagererror/exceededresourcelimit"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/fileNotFound": {
      "abstract": [
        {
          "text": "An error that indicates the file doesn’t exist at the specified URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "fileNotFound"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/fileNotFound",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManagerErrorFileNotFound"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerError.fileNotFound",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagererror/filenotfound"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/inUse": {
      "abstract": [
        {
          "text": "An error that indicates the font file is actively in use and can’t be unregistered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "inUse"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/inUse",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManagerErrorInUse"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerError.inUse",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagererror/inuse"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagererror/init(rawvalue:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/insufficientInfo": {
      "abstract": [
        {
          "text": "An error that indicates the font descriptor doesn’t have the necessary information to specify a font file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insufficientInfo"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/insufficientInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManagerErrorInsufficientInfo"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerError.insufficientInfo",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagererror/insufficientinfo"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/insufficientPermissions": {
      "abstract": [
        {
          "text": "An error that indicates insufficient permissions to access the file.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "insufficientPermissions"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/insufficientPermissions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManagerErrorInsufficientPermissions"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerError.insufficientPermissions",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagererror/insufficientpermissions"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/invalidFilePath": {
      "abstract": [
        {
          "text": "An error that indicates the file isn’t in an allowed location, which must be either in the app’s bundle or an on-demand resource.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidFilePath"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/invalidFilePath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManagerErrorInvalidFilePath"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerError.invalidFilePath",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagererror/invalidfilepath"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/invalidFontData": {
      "abstract": [
        {
          "text": "An error that indicates the file contains invalid font data that could cause system problems.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalidFontData"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/invalidFontData",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManagerErrorInvalidFontData"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerError.invalidFontData",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagererror/invalidfontdata"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/missingEntitlement": {
      "abstract": [
        {
          "text": "An error that indicates the file can’t be processed because the provider doesn’t have a necessary entitlement.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "missingEntitlement"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/missingEntitlement",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManagerErrorMissingEntitlement"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerError.missingEntitlement",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagererror/missingentitlement"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/notRegistered": {
      "abstract": [
        {
          "text": "An error that indicates the file isn’t registered in the specified scope.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "notRegistered"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/notRegistered",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManagerErrorNotRegistered"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerError.notRegistered",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagererror/notregistered"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/registrationFailed": {
      "abstract": [
        {
          "text": "An error that indicates the file can’t be processed due to an unexpected FontProvider error.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "registrationFailed"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/registrationFailed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManagerErrorRegistrationFailed"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerError.registrationFailed",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagererror/registrationfailed"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/systemRequired": {
      "abstract": [
        {
          "text": "An error that indicates the file is required by the system and can’t be unregistered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "systemRequired"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/systemRequired",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManagerErrorSystemRequired"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerError.systemRequired",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagererror/systemrequired"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/unrecognizedFormat": {
      "abstract": [
        {
          "text": "An error that indicates the file’s format is unrecognized or unsupported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unrecognizedFormat"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/unrecognizedFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManagerErrorUnrecognizedFormat"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerError.unrecognizedFormat",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagererror/unrecognizedformat"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/unsupportedScope": {
      "abstract": [
        {
          "text": "An error that indicates the specified scope isn’t supported.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unsupportedScope"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/unsupportedScope",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManagerErrorUnsupportedScope"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerError.unsupportedScope",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagererror/unsupportedscope"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerScope": {
      "abstract": [
        {
          "text": "Constants that define the scope for font registration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontManagerScope"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerScope",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontManagerScope"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerScope",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagerscope"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions": {
      "abstract": [
        {
          "text": "Options for getting the bounds of a line of text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTLineBoundsOptions"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTLineBoundsOptions"
        }
      ],
      "role": "symbol",
      "title": "CTLineBoundsOptions",
      "type": "topic",
      "url": "/documentation/coretext/ctlineboundsoptions"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment": {
      "abstract": [
        {
          "text": "Constants that specify how to align the ruby text and the base text relative to each other when they have different lengths.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRubyAlignment"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRubyAlignment"
        }
      ],
      "role": "symbol",
      "title": "CTRubyAlignment",
      "type": "topic",
      "url": "/documentation/coretext/ctrubyalignment"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRubyOverhang": {
      "abstract": [
        {
          "text": "Constants that specify whether, and on which side, ruby text can overhang adjacent text if it’s wider than the base text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRubyOverhang"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRubyOverhang",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRubyOverhang"
        }
      ],
      "role": "symbol",
      "title": "CTRubyOverhang",
      "type": "topic",
      "url": "/documentation/coretext/ctrubyoverhang"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRubyPosition": {
      "abstract": [
        {
          "text": "Constants that specify the position of the ruby text relative to to the base text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRubyPosition"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRubyPosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRubyPosition"
        }
      ],
      "role": "symbol",
      "title": "CTRubyPosition",
      "type": "topic",
      "url": "/documentation/coretext/ctrubyposition"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFIndex": {
      "abstract": [
        {
          "text": "Priority values used for kAXPriorityKey",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFIndex",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFIndex",
      "type": "topic",
      "url": "/documentation/corefoundation/cfindex"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerAutoActivationSetting",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerScope",
        "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions",
        "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment",
        "doc://com.apple.coretext/documentation/CoreText/CTRubyOverhang",
        "doc://com.apple.coretext/documentation/CoreText/CTRubyPosition"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/fileNotFound",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/insufficientPermissions",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/unrecognizedFormat",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/invalidFontData",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/alreadyRegistered",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/exceededResourceLimit",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/assetNotFound",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/notRegistered",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/inUse",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/systemRequired",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/registrationFailed",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/missingEntitlement",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/insufficientInfo",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/cancelledByUser",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/duplicatedName",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/invalidFilePath",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/unsupportedScope"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CTFontManagerError"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontManagerError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontManagerError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/fileNotFound",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/insufficientPermissions",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/unrecognizedFormat",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/invalidFontData",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/alreadyRegistered",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/exceededResourceLimit",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/assetNotFound",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/notRegistered",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/inUse",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/systemRequired",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/registrationFailed",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/missingEntitlement",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/insufficientInfo",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/cancelledByUser",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/duplicatedName",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/invalidFilePath",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError/unsupportedScope"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerAutoActivationSetting",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerScope",
                "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions",
                "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment",
                "doc://com.apple.coretext/documentation/CoreText/CTRubyOverhang",
                "doc://com.apple.coretext/documentation/CoreText/CTRubyPosition"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CTFontManagerError"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFIndex",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFIndex",
                    "text": "CFIndex"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1cancelledByUser/title",
          "value": "kCTFontManagerErrorCancelledByUser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1cancelledByUser/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManagerErrorCancelledByUser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1systemRequired/title",
          "value": "kCTFontManagerErrorSystemRequired"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1systemRequired/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManagerErrorSystemRequired"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1invalidFontData/title",
          "value": "kCTFontManagerErrorInvalidFontData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1invalidFontData/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManagerErrorInvalidFontData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1missingEntitlement/title",
          "value": "kCTFontManagerErrorMissingEntitlement"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1missingEntitlement/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManagerErrorMissingEntitlement"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBoundsOptions/title",
          "value": "CTLineBoundsOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBoundsOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineBoundsOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBoundsOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineBoundsOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1fileNotFound/title",
          "value": "kCTFontManagerErrorFileNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1fileNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManagerErrorFileNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1insufficientPermissions/title",
          "value": "kCTFontManagerErrorInsufficientPermissions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1insufficientPermissions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManagerErrorInsufficientPermissions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1duplicatedName/title",
          "value": "kCTFontManagerErrorDuplicatedName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1duplicatedName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManagerErrorDuplicatedName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1alreadyRegistered/title",
          "value": "kCTFontManagerErrorAlreadyRegistered"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1alreadyRegistered/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManagerErrorAlreadyRegistered"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1notRegistered/title",
          "value": "kCTFontManagerErrorNotRegistered"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1notRegistered/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManagerErrorNotRegistered"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1registrationFailed/title",
          "value": "kCTFontManagerErrorRegistrationFailed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1registrationFailed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManagerErrorRegistrationFailed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1exceededResourceLimit/title",
          "value": "kCTFontManagerErrorExceededResourceLimit"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1exceededResourceLimit/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManagerErrorExceededResourceLimit"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment/title",
          "value": "CTRubyAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRubyAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRubyAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1insufficientInfo/title",
          "value": "kCTFontManagerErrorInsufficientInfo"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1insufficientInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManagerErrorInsufficientInfo"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1inUse/title",
          "value": "kCTFontManagerErrorInUse"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1inUse/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManagerErrorInUse"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyOverhang/title",
          "value": "CTRubyOverhang"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyOverhang/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRubyOverhang"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyOverhang/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRubyOverhang"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerScope/title",
          "value": "CTFontManagerScope"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerScope/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontManagerScope"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerScope/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontManagerScope"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1unsupportedScope/title",
          "value": "kCTFontManagerErrorUnsupportedScope"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1unsupportedScope/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManagerErrorUnsupportedScope"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError/title",
          "value": "CTFontManagerError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontManagerError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontManagerError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1assetNotFound/title",
          "value": "kCTFontManagerErrorAssetNotFound"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1assetNotFound/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManagerErrorAssetNotFound"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1unrecognizedFormat/title",
          "value": "kCTFontManagerErrorUnrecognizedFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1unrecognizedFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManagerErrorUnrecognizedFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1invalidFilePath/title",
          "value": "kCTFontManagerErrorInvalidFilePath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError~1invalidFilePath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManagerErrorInvalidFilePath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerAutoActivationSetting/title",
          "value": "CTFontManagerAutoActivationSetting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerAutoActivationSetting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontManagerAutoActivationSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerAutoActivationSetting/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontManagerAutoActivationSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptorMatchingState/title",
          "value": "CTFontDescriptorMatchingState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptorMatchingState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontDescriptorMatchingState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptorMatchingState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontDescriptorMatchingState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyPosition/title",
          "value": "CTRubyPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyPosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRubyPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyPosition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRubyPosition"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/ctfontmanagererror"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/ctfontmanagererror"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
