{
  "abstract": [
    {
      "text": "Resolves font descriptors specified on input.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerRequestFonts(_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CTFontManagerRequestFonts",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CTFontManagerRequestFonts"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFArrayRef",
        "text": "CFArray"
      },
      {
        "kind": "text",
        "text": ", ("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFArrayRef",
        "text": "CFArray"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:s4Voida",
        "text": "Void"
      },
      {
        "kind": "text",
        "text": ")"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CTFontManagerRequestFonts"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CTFontManagerRequestFonts(_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "visionOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CTFontManagerRequestFonts"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "fontDescriptors"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFArrayRef",
              "text": "CFArray"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "completionHandler"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "kind": "keyword",
              "text": "@escaping"
            },
            {
              "kind": "text",
              "text": " ("
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFArrayRef",
              "text": "CFArray"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:s4Voida",
              "text": "Void"
            },
            {
              "kind": "text",
              "text": ")"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array of font descriptors to make available to the process.  The keys for describing the fonts may be a combination of ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontNameAttribute",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontFamilyNameAttribute",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", or ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontRegistrationUserInfoAttribute",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "fontDescriptors"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A block called after the request operation completes. This block takes a ",
                  "type": "text"
                },
                {
                  "code": "unresolvedFontDescriptors",
                  "type": "codeVoice"
                },
                {
                  "text": " parameter that contains an array of descriptors that couldn’t be resolved or found. The array can be empty if all descriptors resolved.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "completionHandler"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "On iOS, fonts registered by font provider apps in the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerScope/persistent",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " scope aren’t automatically available to other apps. Other apps must call this function to make the fonts available for font descriptor matching.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "On iOS, if the font descriptors can’t be found, the system presents the user with a dialog that indicates which fonts couldn’t be resolved. The system may provide the user with a way to resolve the missing fonts, if the font manager has a way to enable them.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchFontDescriptorsWithProgressHandler(_:_:_:)": {
      "abstract": [
        {
          "text": "Matches font descriptors and tracks progress with a progress handler.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontDescriptorMatchFontDescriptorsWithProgressHandler"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFSetRef",
          "text": "CFSet"
        },
        {
          "kind": "text",
          "text": "?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontDescriptorProgressHandler",
          "text": "CTFontDescriptorProgressHandler"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchFontDescriptorsWithProgressHandler(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontDescriptorMatchFontDescriptorsWithProgressHandler"
        }
      ],
      "role": "symbol",
      "title": "CTFontDescriptorMatchFontDescriptorsWithProgressHandler(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontdescriptormatchfontdescriptorswithprogresshandler(_:_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerCompareFontFamilyNames(_:_:_:)": {
      "abstract": [
        {
          "text": "A comparator function to compare font family names and sort them according to Apple guidelines.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontManagerCompareFontFamilyNames"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SV",
          "text": "UnsafeRawPointer"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CFComparisonResult",
          "text": "CFComparisonResult"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerCompareFontFamilyNames(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontManagerCompareFontFamilyNames"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerCompareFontFamilyNames(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagercomparefontfamilynames(_:_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerCopyAvailableFontFamilyNames()": {
      "abstract": [
        {
          "text": "Returns an array of visible font family names sorted for user interface display.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontManagerCopyAvailableFontFamilyNames"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerCopyAvailableFontFamilyNames()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontManagerCopyAvailableFontFamilyNames"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerCopyAvailableFontFamilyNames()",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagercopyavailablefontfamilynames()"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerCopyAvailableFontURLs()": {
      "abstract": [
        {
          "text": "Returns an array of font URLs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontManagerCopyAvailableFontURLs"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerCopyAvailableFontURLs()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontManagerCopyAvailableFontURLs"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerCopyAvailableFontURLs()",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagercopyavailablefonturls()"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerCopyAvailablePostScriptNames()": {
      "abstract": [
        {
          "text": "Returns an array of unique PostScript font names for the fonts.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontManagerCopyAvailablePostScriptNames"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerCopyAvailablePostScriptNames()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontManagerCopyAvailablePostScriptNames"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerCopyAvailablePostScriptNames()",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagercopyavailablepostscriptnames()"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerCreateFontDescriptorFromData(_:)": {
      "abstract": [
        {
          "text": "Creates a font descriptor representing the font in the supplied data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontManagerCreateFontDescriptorFromData"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDataRef",
          "text": "CFData"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontDescriptorRef",
          "text": "CTFontDescriptor"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerCreateFontDescriptorFromData(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontManagerCreateFontDescriptorFromData"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerCreateFontDescriptorFromData(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagercreatefontdescriptorfromdata(_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerCreateFontDescriptorsFromURL(_:)": {
      "abstract": [
        {
          "text": "Returns an array of font descriptors representing each of the fonts in the specified URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontManagerCreateFontDescriptorsFromURL"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerCreateFontDescriptorsFromURL(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontManagerCreateFontDescriptorsFromURL"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerCreateFontDescriptorsFromURL(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagercreatefontdescriptorsfromurl(_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerCreateFontRequestRunLoopSource(_:_:)": {
      "abstract": [
        {
          "text": "Creates a reference to a run loop source used to convey font requests from the Font Manager.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontManagerCreateFontRequestRunLoopSource"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        },
        {
          "kind": "text",
          "text": ", ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@pid_t",
          "text": "pid_t"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFRunLoopSourceRef",
          "text": "CFRunLoopSource"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerCreateFontRequestRunLoopSource(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontManagerCreateFontRequestRunLoopSource"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerCreateFontRequestRunLoopSource(_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagercreatefontrequestrunloopsource(_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerEnableFontDescriptors(_:_:)": {
      "abstract": [
        {
          "text": "Enables or disables the matching font descriptors for font descriptor matching.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontManagerEnableFontDescriptors"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerEnableFontDescriptors(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontManagerEnableFontDescriptors"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerEnableFontDescriptors(_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagerenablefontdescriptors(_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerGetAutoActivationSetting(_:)": {
      "abstract": [
        {
          "text": "Gets the auto-activation setting for the specified bundle identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontManagerGetAutoActivationSetting"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontManagerAutoActivationSetting",
          "text": "CTFontManagerAutoActivationSetting"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerGetAutoActivationSetting(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontManagerGetAutoActivationSetting"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerGetAutoActivationSetting(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagergetautoactivationsetting(_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerGetScopeForURL(_:)": {
      "abstract": [
        {
          "text": "Returns the registration scope of the specified URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontManagerGetScopeForURL"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontManagerScope",
          "text": "CTFontManagerScope"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerGetScopeForURL(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontManagerGetScopeForURL"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerGetScopeForURL(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagergetscopeforurl(_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerIsSupportedFont(_:)": {
      "abstract": [
        {
          "text": "Determines whether a file is in a supported font format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontManagerIsSupportedFont"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerIsSupportedFont(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontManagerIsSupportedFont"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerIsSupportedFont(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagerissupportedfont(_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerRegisterFontsForURL(_:_:_:)": {
      "abstract": [
        {
          "text": "Registers fonts from the specified font URL with the Font Manager. Registered fonts are discoverable through font descriptor matching.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontManagerRegisterFontsForURL"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFURLRef",
          "text": "CFURL"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontManagerScope",
          "text": "CTFontManagerScope"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": ">?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerRegisterFontsForURL(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontManagerRegisterFontsForURL"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerRegisterFontsForURL(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagerregisterfontsforurl(_:_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerRegisterFontsForURLs(_:_:_:)": {
      "abstract": [
        {
          "text": "Registers fonts from the specified array of font URLs with the Font Manager. Registered fonts are discoverable through font descriptor matching.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontManagerRegisterFontsForURLs"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontManagerScope",
          "text": "CTFontManagerScope"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ">?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerRegisterFontsForURLs(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontManagerRegisterFontsForURLs"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerRegisterFontsForURLs(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagerregisterfontsforurls(_:_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerRegisterGraphicsFont(_:_:)": {
      "abstract": [
        {
          "text": "Registers the specified graphics font with the font manager.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontManagerRegisterGraphicsFont"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGFontRef",
          "text": "CGFont"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s9UnmanagedV",
          "text": "Unmanaged"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFErrorRef",
          "text": "CFError"
        },
        {
          "kind": "text",
          "text": ">?>?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerRegisterGraphicsFont(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontManagerRegisterGraphicsFont"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerRegisterGraphicsFont(_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagerregistergraphicsfont(_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerRequestFonts(_:_:)": {
      "abstract": [
        {
          "text": "Resolves font descriptors specified on input.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontManagerRequestFonts"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ", ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerRequestFonts(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontManagerRequestFonts"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerRequestFonts(_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagerrequestfonts(_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerScope/persistent": {
      "abstract": [
        {
          "text": "The font is available to all processes for the current user session and will be available in subsequent sessions unless unregistered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "persistent"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerScope/persistent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManagerScopePersistent"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerScope.persistent",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagerscope/persistent"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontFamilyNameAttribute": {
      "abstract": [
        {
          "text": "The font family name from the font descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontFamilyNameAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontFamilyNameAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFamilyNameAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontFamilyNameAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontfamilynameattribute"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontNameAttribute": {
      "abstract": [
        {
          "text": "The PostScript name from the font descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontNameAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontNameAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontNameAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontNameAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontnameattribute"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontRegistrationUserInfoAttribute": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontRegistrationUserInfoAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontRegistrationUserInfoAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontRegistrationUserInfoAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontRegistrationUserInfoAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontregistrationuserinfoattribute"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFArrayRef": {
      "abstract": [
        {
          "text": "A reference to an immutable array object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFArray"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFArray",
      "type": "topic",
      "url": "/documentation/corefoundation/cfarray"
    },
    "doc://com.externally.resolved.symbol/s:s4Voida": {
      "abstract": [
        {
          "text": "The return type of functions that don’t explicitly specify a return type, that is, an empty tuple `()`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": " = ()"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s4Voida",
      "kind": "symbol",
      "role": "symbol",
      "title": "Void",
      "type": "topic",
      "url": "/documentation/Swift/Void"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Functions",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchFontDescriptorsWithProgressHandler(_:_:_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerCompareFontFamilyNames(_:_:_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerCopyAvailableFontFamilyNames()",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerCopyAvailableFontURLs()",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerCopyAvailablePostScriptNames()",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerCreateFontDescriptorFromData(_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerCreateFontDescriptorsFromURL(_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerCreateFontRequestRunLoopSource(_:_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerEnableFontDescriptors(_:_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerGetAutoActivationSetting(_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerGetScopeForURL(_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerIsSupportedFont(_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerRegisterFontsForURL(_:_:_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerRegisterFontsForURLs(_:_:_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerRegisterGraphicsFont(_:_:)"
      ],
      "title": "Functions"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CTFontManagerRequestFonts"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontManagerRequestFonts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Functions",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchFontDescriptorsWithProgressHandler(_:_:_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerCompareFontFamilyNames(_:_:_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerCopyAvailableFontFamilyNames()",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerCopyAvailableFontURLs()",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerCopyAvailablePostScriptNames()",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerCreateFontDescriptorFromData(_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerCreateFontDescriptorsFromURL(_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerCreateFontRequestRunLoopSource(_:_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerEnableFontDescriptors(_:_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerGetAutoActivationSetting(_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerGetScopeForURL(_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerIsSupportedFont(_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerRegisterFontsForURL(_:_:_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerRegisterFontsForURLs(_:_:_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerRegisterGraphicsFont(_:_:)"
              ],
              "title": "Functions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CTFontManagerRequestFonts"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFArrayRef",
                    "text": "CFArrayRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "fontDescriptors"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:v",
                    "text": "void"
                  },
                  {
                    "kind": "text",
                    "text": " (^"
                  },
                  {
                    "kind": "internalParam",
                    "text": "completionHandler"
                  },
                  {
                    "kind": "text",
                    "text": ")("
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFArrayRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFArrayRef",
                    "text": "CFArrayRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "unresolvedFontDescriptors"
                  },
                  {
                    "kind": "text",
                    "text": "));"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An array of font descriptors to make available to the process.  The keys for describing the fonts may be a combination of ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontNameAttribute",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ", ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontFamilyNameAttribute",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ", or ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontRegistrationUserInfoAttribute",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "fontDescriptors"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A block called after the request operation completes. This block takes a ",
                        "type": "text"
                      },
                      {
                        "code": "unresolvedFontDescriptors",
                        "type": "codeVoice"
                      },
                      {
                        "text": " parameter that contains an array of descriptors that couldn’t be resolved or found. The array can be empty if all descriptors resolved.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "completionHandler"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerCopyAvailableFontURLs()/title",
          "value": "CTFontManagerCopyAvailableFontURLs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerCopyAvailableFontURLs()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontManagerCopyAvailableFontURLs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerEnableFontDescriptors(_:_:)/title",
          "value": "CTFontManagerEnableFontDescriptors"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerEnableFontDescriptors(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontManagerEnableFontDescriptors"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerRegisterFontsForURL(_:_:_:)/title",
          "value": "CTFontManagerRegisterFontsForURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerRegisterFontsForURL(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontManagerRegisterFontsForURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontRegistrationUserInfoAttribute/title",
          "value": "kCTFontRegistrationUserInfoAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontRegistrationUserInfoAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontRegistrationUserInfoAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerRequestFonts(_:_:)/title",
          "value": "CTFontManagerRequestFonts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerRequestFonts(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontManagerRequestFonts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerGetScopeForURL(_:)/title",
          "value": "CTFontManagerGetScopeForURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerGetScopeForURL(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontManagerGetScopeForURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerCreateFontDescriptorFromData(_:)/title",
          "value": "CTFontManagerCreateFontDescriptorFromData"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerCreateFontDescriptorFromData(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontManagerCreateFontDescriptorFromData"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerCreateFontDescriptorsFromURL(_:)/title",
          "value": "CTFontManagerCreateFontDescriptorsFromURL"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerCreateFontDescriptorsFromURL(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontManagerCreateFontDescriptorsFromURL"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerCopyAvailablePostScriptNames()/title",
          "value": "CTFontManagerCopyAvailablePostScriptNames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerCopyAvailablePostScriptNames()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontManagerCopyAvailablePostScriptNames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptorMatchFontDescriptorsWithProgressHandler(_:_:_:)/title",
          "value": "CTFontDescriptorMatchFontDescriptorsWithProgressHandler"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptorMatchFontDescriptorsWithProgressHandler(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontDescriptorMatchFontDescriptorsWithProgressHandler"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerGetAutoActivationSetting(_:)/title",
          "value": "CTFontManagerGetAutoActivationSetting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerGetAutoActivationSetting(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontManagerGetAutoActivationSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerIsSupportedFont(_:)/title",
          "value": "CTFontManagerIsSupportedFont"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerIsSupportedFont(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontManagerIsSupportedFont"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFamilyNameAttribute/title",
          "value": "kCTFontFamilyNameAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFamilyNameAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFamilyNameAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerScope~1persistent/title",
          "value": "kCTFontManagerScopePersistent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerScope~1persistent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManagerScopePersistent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerRegisterFontsForURLs(_:_:_:)/title",
          "value": "CTFontManagerRegisterFontsForURLs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerRegisterFontsForURLs(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontManagerRegisterFontsForURLs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerRegisterGraphicsFont(_:_:)/title",
          "value": "CTFontManagerRegisterGraphicsFont"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerRegisterGraphicsFont(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontManagerRegisterGraphicsFont"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerCompareFontFamilyNames(_:_:_:)/title",
          "value": "CTFontManagerCompareFontFamilyNames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerCompareFontFamilyNames(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontManagerCompareFontFamilyNames"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontNameAttribute/title",
          "value": "kCTFontNameAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontNameAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontNameAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerCreateFontRequestRunLoopSource(_:_:)/title",
          "value": "CTFontManagerCreateFontRequestRunLoopSource"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerCreateFontRequestRunLoopSource(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontManagerCreateFontRequestRunLoopSource"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFArrayRef/title",
          "value": "CFArrayRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerCopyAvailableFontFamilyNames()/title",
          "value": "CTFontManagerCopyAvailableFontFamilyNames"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerCopyAvailableFontFamilyNames()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontManagerCopyAvailableFontFamilyNames"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/ctfontmanagerrequestfonts(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/ctfontmanagerrequestfonts(_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
