{
  "abstract": [
    {
      "text": "Constants that define the scope for font registration.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerScope"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CTFontManagerScope",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CTFontManagerScope"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CTFontManagerScope"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CTFontManagerScope"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CTFontManagerScope"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "On macOS, a user session refers to a login session. On iOS, a user session refers to the current booted session.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState": {
      "abstract": [
        {
          "text": "Constants that track the progress of font descriptor matching.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontDescriptorMatchingState"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontDescriptorMatchingState"
        }
      ],
      "role": "symbol",
      "title": "CTFontDescriptorMatchingState",
      "type": "topic",
      "url": "/documentation/coretext/ctfontdescriptormatchingstate"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerAutoActivationSetting": {
      "abstract": [
        {
          "text": "Sets the auto-activation for the specified bundle identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontManagerAutoActivationSetting"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerAutoActivationSetting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontManagerAutoActivationSetting"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerAutoActivationSetting",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagerautoactivationsetting"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError": {
      "abstract": [
        {
          "text": "Errors that prevent unregistration of fonts for a specified font file URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontManagerError"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontManagerError"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerError",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagererror"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerScope": {
      "abstract": [
        {
          "text": "Constants that define the scope for font registration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontManagerScope"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerScope",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontManagerScope"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerScope",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagerscope"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerScope/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerScope/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagerscope/init(rawvalue:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerScope/none": {
      "abstract": [
        {
          "text": "No scope is defined.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "none"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerScope/none",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManagerScopeNone"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerScope.none",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagerscope/none"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerScope/persistent": {
      "abstract": [
        {
          "text": "The font is available to all processes for the current user session and will be available in subsequent sessions unless unregistered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "persistent"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerScope/persistent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManagerScopePersistent"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerScope.persistent",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagerscope/persistent"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerScope/process": {
      "abstract": [
        {
          "text": "The font is available to the current process for the duration of the process unless directly unregistered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "process"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerScope/process",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManagerScopeProcess"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerScope.process",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagerscope/process"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerScope/session": {
      "abstract": [
        {
          "text": "The font is available to the current user session but won’t be available in subsequent sessions.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "session"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerScope/session",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManagerScopeSession"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerScope.session",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagerscope/session"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerScope/user": {
      "abstract": [
        {
          "text": "The font is available to all processes for the current user session and will be available in subsequent sessions unless unregistered.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "user"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontManagerScope",
          "text": "CTFontManagerScope"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerScope/user",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManagerScopeUser"
        }
      ],
      "role": "symbol",
      "title": "user",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagerscope/user"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions": {
      "abstract": [
        {
          "text": "Options for getting the bounds of a line of text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTLineBoundsOptions"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTLineBoundsOptions"
        }
      ],
      "role": "symbol",
      "title": "CTLineBoundsOptions",
      "type": "topic",
      "url": "/documentation/coretext/ctlineboundsoptions"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment": {
      "abstract": [
        {
          "text": "Constants that specify how to align the ruby text and the base text relative to each other when they have different lengths.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRubyAlignment"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRubyAlignment"
        }
      ],
      "role": "symbol",
      "title": "CTRubyAlignment",
      "type": "topic",
      "url": "/documentation/coretext/ctrubyalignment"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRubyOverhang": {
      "abstract": [
        {
          "text": "Constants that specify whether, and on which side, ruby text can overhang adjacent text if it’s wider than the base text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRubyOverhang"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRubyOverhang",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRubyOverhang"
        }
      ],
      "role": "symbol",
      "title": "CTRubyOverhang",
      "type": "topic",
      "url": "/documentation/coretext/ctrubyoverhang"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRubyPosition": {
      "abstract": [
        {
          "text": "Constants that specify the position of the ruby text relative to to the base text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRubyPosition"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRubyPosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRubyPosition"
        }
      ],
      "role": "symbol",
      "title": "CTRubyPosition",
      "type": "topic",
      "url": "/documentation/coretext/ctrubyposition"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerAutoActivationSetting",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError",
        "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions",
        "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment",
        "doc://com.apple.coretext/documentation/CoreText/CTRubyOverhang",
        "doc://com.apple.coretext/documentation/CoreText/CTRubyPosition"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerScope/none",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerScope/process",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerScope/persistent",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerScope/session",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerScope/user"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerScope/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CTFontManagerScope"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontManagerScope"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontManagerScope"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerScope/none",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerScope/process",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerScope/persistent",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerScope/session",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerScope/user"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerAutoActivationSetting",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError",
                "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions",
                "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment",
                "doc://com.apple.coretext/documentation/CoreText/CTRubyOverhang",
                "doc://com.apple.coretext/documentation/CoreText/CTRubyPosition"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CTFontManagerScope"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint32_t",
                    "text": "uint32_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerScope~1process/title",
          "value": "kCTFontManagerScopeProcess"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerScope~1process/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManagerScopeProcess"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptorMatchingState/title",
          "value": "CTFontDescriptorMatchingState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptorMatchingState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontDescriptorMatchingState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptorMatchingState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontDescriptorMatchingState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment/title",
          "value": "CTRubyAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRubyAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRubyAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerScope/title",
          "value": "CTFontManagerScope"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerScope/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontManagerScope"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerScope/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontManagerScope"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBoundsOptions/title",
          "value": "CTLineBoundsOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBoundsOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineBoundsOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBoundsOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineBoundsOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyOverhang/title",
          "value": "CTRubyOverhang"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyOverhang/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRubyOverhang"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyOverhang/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRubyOverhang"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerScope~1none/title",
          "value": "kCTFontManagerScopeNone"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerScope~1none/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManagerScopeNone"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerScope~1session/title",
          "value": "kCTFontManagerScopeSession"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerScope~1session/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManagerScopeSession"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError/title",
          "value": "CTFontManagerError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontManagerError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontManagerError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerScope~1user/title",
          "value": "kCTFontManagerScopeUser"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerScope~1user/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManagerScopeUser"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyPosition/title",
          "value": "CTRubyPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyPosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRubyPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyPosition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRubyPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerAutoActivationSetting/title",
          "value": "CTFontManagerAutoActivationSetting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerAutoActivationSetting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontManagerAutoActivationSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerAutoActivationSetting/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontManagerAutoActivationSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerScope~1persistent/title",
          "value": "kCTFontManagerScopePersistent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerScope~1persistent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManagerScopePersistent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/ctfontmanagerscope"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/ctfontmanagerscope"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
