{
  "abstract": [
    {
      "text": "Returns the scaled font-ascent metric of the given font.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTFontGetAscent(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CTFontGetAscent",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CTFontGetAscent"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CTFontRef",
        "text": "CTFont"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
        "text": "CGFloat"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CTFontGetAscent"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CTFontGetAscent(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CTFontGetAscent"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "font"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFont",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CTFontRef",
              "text": "CTFont"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
              "text": "CGFloat"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The font reference.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "font"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The font-ascent metric scaled according to the point size and matrix of the font reference.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFont": {
      "abstract": [
        {
          "text": "A font object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFont"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFont",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFont"
        }
      ],
      "role": "symbol",
      "title": "CTFont",
      "type": "topic",
      "url": "/documentation/coretext/ctfont"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontGetAscent(_:)": {
      "abstract": [
        {
          "text": "Returns the scaled font-ascent metric of the given font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontGetAscent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontRef",
          "text": "CTFont"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontGetAscent(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontGetAscent"
        }
      ],
      "role": "symbol",
      "title": "CTFontGetAscent(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontgetascent(_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontGetBoundingBox(_:)": {
      "abstract": [
        {
          "text": "Returns the scaled bounding box of the given font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontGetBoundingBox"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontRef",
          "text": "CTFont"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontGetBoundingBox(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontGetBoundingBox"
        }
      ],
      "role": "symbol",
      "title": "CTFontGetBoundingBox(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontgetboundingbox(_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontGetCapHeight(_:)": {
      "abstract": [
        {
          "text": "Returns the cap-height metric of the given font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontGetCapHeight"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontRef",
          "text": "CTFont"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontGetCapHeight(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontGetCapHeight"
        }
      ],
      "role": "symbol",
      "title": "CTFontGetCapHeight(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontgetcapheight(_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontGetDescent(_:)": {
      "abstract": [
        {
          "text": "Returns the scaled font-descent metric of the given font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontGetDescent"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontRef",
          "text": "CTFont"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontGetDescent(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontGetDescent"
        }
      ],
      "role": "symbol",
      "title": "CTFontGetDescent(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontgetdescent(_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontGetGlyphCount(_:)": {
      "abstract": [
        {
          "text": "Returns the number of glyphs of the given font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontGetGlyphCount"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontRef",
          "text": "CTFont"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontGetGlyphCount(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontGetGlyphCount"
        }
      ],
      "role": "symbol",
      "title": "CTFontGetGlyphCount(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontgetglyphcount(_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontGetLeading(_:)": {
      "abstract": [
        {
          "text": "Returns the scaled font-leading metric of the given font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontGetLeading"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontRef",
          "text": "CTFont"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontGetLeading(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontGetLeading"
        }
      ],
      "role": "symbol",
      "title": "CTFontGetLeading(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontgetleading(_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontGetSlantAngle(_:)": {
      "abstract": [
        {
          "text": "Returns the slant angle of the given font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontGetSlantAngle"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontRef",
          "text": "CTFont"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontGetSlantAngle(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontGetSlantAngle"
        }
      ],
      "role": "symbol",
      "title": "CTFontGetSlantAngle(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontgetslantangle(_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontGetUnderlinePosition(_:)": {
      "abstract": [
        {
          "text": "Returns the scaled underline position of the given font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontGetUnderlinePosition"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontRef",
          "text": "CTFont"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontGetUnderlinePosition(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontGetUnderlinePosition"
        }
      ],
      "role": "symbol",
      "title": "CTFontGetUnderlinePosition(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontgetunderlineposition(_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontGetUnderlineThickness(_:)": {
      "abstract": [
        {
          "text": "Returns the scaled underline-thickness metric of the given font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontGetUnderlineThickness"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontRef",
          "text": "CTFont"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontGetUnderlineThickness(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontGetUnderlineThickness"
        }
      ],
      "role": "symbol",
      "title": "CTFontGetUnderlineThickness(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontgetunderlinethickness(_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontGetUnitsPerEm(_:)": {
      "abstract": [
        {
          "text": "Returns the units-per-em metric of the given font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontGetUnitsPerEm"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontRef",
          "text": "CTFont"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontGetUnitsPerEm(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontGetUnitsPerEm"
        }
      ],
      "role": "symbol",
      "title": "CTFontGetUnitsPerEm(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontgetunitsperem(_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontGetXHeight(_:)": {
      "abstract": [
        {
          "text": "Returns the x-height metric of the given font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontGetXHeight"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontRef",
          "text": "CTFont"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontGetXHeight(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontGetXHeight"
        }
      ],
      "role": "symbol",
      "title": "CTFontGetXHeight(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontgetxheight(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV": {
      "abstract": [
        {
          "text": "The basic type for floating-point scalar values in Core Graphics and related frameworks.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:14CoreFoundation7CGFloatV",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGFloat",
      "type": "topic",
      "url": "/documentation/corefoundation/cgfloat"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Font-Metrics",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTFontGetDescent(_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTFontGetLeading(_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTFontGetUnitsPerEm(_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTFontGetGlyphCount(_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTFontGetBoundingBox(_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTFontGetUnderlinePosition(_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTFontGetUnderlineThickness(_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTFontGetSlantAngle(_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTFontGetCapHeight(_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTFontGetXHeight(_:)"
      ],
      "title": "Getting Font Metrics"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CTFontGetAscent"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontGetAscent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-Font-Metrics",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTFontGetDescent(_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTFontGetLeading(_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTFontGetUnitsPerEm(_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTFontGetGlyphCount(_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTFontGetBoundingBox(_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTFontGetUnderlinePosition(_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTFontGetUnderlineThickness(_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTFontGetSlantAngle(_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTFontGetCapHeight(_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTFontGetXHeight(_:)"
              ],
              "title": "Getting Font Metrics"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CGFloat",
                    "text": "CGFloat"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CTFontGetAscent"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFont",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CTFontRef",
                    "text": "CTFontRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "font"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The font reference.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "font"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The font-ascent metric scaled according to the point size and matrix of the font reference.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontGetLeading(_:)/title",
          "value": "CTFontGetLeading"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontGetLeading(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontGetLeading"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontGetXHeight(_:)/title",
          "value": "CTFontGetXHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontGetXHeight(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontGetXHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontGetUnderlinePosition(_:)/title",
          "value": "CTFontGetUnderlinePosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontGetUnderlinePosition(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontGetUnderlinePosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontGetCapHeight(_:)/title",
          "value": "CTFontGetCapHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontGetCapHeight(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontGetCapHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontGetBoundingBox(_:)/title",
          "value": "CTFontGetBoundingBox"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontGetBoundingBox(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontGetBoundingBox"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontGetDescent(_:)/title",
          "value": "CTFontGetDescent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontGetDescent(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontGetDescent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontGetUnderlineThickness(_:)/title",
          "value": "CTFontGetUnderlineThickness"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontGetUnderlineThickness(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontGetUnderlineThickness"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontGetSlantAngle(_:)/title",
          "value": "CTFontGetSlantAngle"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontGetSlantAngle(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontGetSlantAngle"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontGetUnitsPerEm(_:)/title",
          "value": "CTFontGetUnitsPerEm"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontGetUnitsPerEm(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontGetUnitsPerEm"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontGetGlyphCount(_:)/title",
          "value": "CTFontGetGlyphCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontGetGlyphCount(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontGetGlyphCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFont/title",
          "value": "CTFontRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFont/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFont/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontGetAscent(_:)/title",
          "value": "CTFontGetAscent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontGetAscent(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontGetAscent"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/ctfontgetascent(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/ctfontgetascent(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
