{
  "abstract": [
    {
      "text": "The recognized format of the font.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTFontFormat"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CTFontFormat",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CTFontFormat"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CTFontFormat"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CTFontFormat"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CTFontFormat"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Use the values of this enumeration for ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontFormatAttribute",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontFormat": {
      "abstract": [
        {
          "text": "The recognized format of the font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontFormat"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontFormat"
        }
      ],
      "role": "symbol",
      "title": "CTFontFormat",
      "type": "topic",
      "url": "/documentation/coretext/ctfontformat"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/bitmap": {
      "abstract": [
        {
          "text": "The font is a bitmap-only format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "bitmap"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/bitmap",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFormatBitmap"
        }
      ],
      "role": "symbol",
      "title": "CTFontFormat.bitmap",
      "type": "topic",
      "url": "/documentation/coretext/ctfontformat/bitmap"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontformat/init(rawvalue:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/openTypePostScript": {
      "abstract": [
        {
          "text": "The font is an OpenType format containing PostScript data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openTypePostScript"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/openTypePostScript",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFormatOpenTypePostScript"
        }
      ],
      "role": "symbol",
      "title": "CTFontFormat.openTypePostScript",
      "type": "topic",
      "url": "/documentation/coretext/ctfontformat/opentypepostscript"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/openTypeTrueType": {
      "abstract": [
        {
          "text": "The font is an OpenType format containing TrueType data.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "openTypeTrueType"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/openTypeTrueType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFormatOpenTypeTrueType"
        }
      ],
      "role": "symbol",
      "title": "CTFontFormat.openTypeTrueType",
      "type": "topic",
      "url": "/documentation/coretext/ctfontformat/opentypetruetype"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/postScript": {
      "abstract": [
        {
          "text": "The font is a recognized PostScript format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "postScript"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/postScript",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFormatPostScript"
        }
      ],
      "role": "symbol",
      "title": "CTFontFormat.postScript",
      "type": "topic",
      "url": "/documentation/coretext/ctfontformat/postscript"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/trueType": {
      "abstract": [
        {
          "text": "The font is a recognized TrueType format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "trueType"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/trueType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFormatTrueType"
        }
      ],
      "role": "symbol",
      "title": "CTFontFormat.trueType",
      "type": "topic",
      "url": "/documentation/coretext/ctfontformat/truetype"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/unrecognized": {
      "abstract": [
        {
          "text": "The font is not a recognized format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "unrecognized"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/unrecognized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFormatUnrecognized"
        }
      ],
      "role": "symbol",
      "title": "CTFontFormat.unrecognized",
      "type": "topic",
      "url": "/documentation/coretext/ctfontformat/unrecognized"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontOrientation": {
      "abstract": [
        {
          "text": "The intended rendering orientation of the font for obtaining glyph metrics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontOrientation"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontOrientation"
        }
      ],
      "role": "symbol",
      "title": "CTFontOrientation",
      "type": "topic",
      "url": "/documentation/coretext/ctfontorientation"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontPriority": {
      "abstract": [
        {
          "text": "The priority of font descriptors when resolving duplicates and sorting match results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontPriority"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontPriority",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontPriority"
        }
      ],
      "role": "symbol",
      "title": "CTFontPriority",
      "type": "topic",
      "url": "/documentation/coretext/ctfontpriority"
    },
    "doc://com.apple.coretext/documentation/CoreText/font-attributes": {
      "abstract": [
        {
          "text": "The keys for accessing font attributes from a font descriptor.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/font-attributes",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Font Attributes",
      "type": "topic",
      "url": "/documentation/coretext/font-attributes"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontFormatAttribute": {
      "abstract": [
        {
          "text": "The recognized format of the font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontFormatAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontFormatAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFormatAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontFormatAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontformatattribute"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/kCTFontFormatAttribute"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Accessing-Font-Attributes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/font-attributes",
        "doc://com.apple.coretext/documentation/CoreText/CTFontOrientation",
        "doc://com.apple.coretext/documentation/CoreText/CTFontPriority"
      ],
      "title": "Accessing Font Attributes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Font-Formats",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/unrecognized",
        "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/openTypePostScript",
        "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/openTypeTrueType",
        "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/trueType",
        "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/postScript",
        "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/bitmap"
      ],
      "title": "Font Formats"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CTFontFormat"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Font-Formats",
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/unrecognized",
                "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/openTypePostScript",
                "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/openTypeTrueType",
                "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/trueType",
                "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/postScript",
                "doc://com.apple.coretext/documentation/CoreText/CTFontFormat/bitmap"
              ],
              "title": "Font Formats"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/kCTFontFormatAttribute"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Accessing-Font-Attributes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/font-attributes",
                "doc://com.apple.coretext/documentation/CoreText/CTFontOrientation",
                "doc://com.apple.coretext/documentation/CoreText/CTFontPriority"
              ],
              "title": "Accessing Font Attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CTFontFormat"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint32_t",
                    "text": "uint32_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontFormat~1openTypeTrueType/title",
          "value": "kCTFontFormatOpenTypeTrueType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontFormat~1openTypeTrueType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFormatOpenTypeTrueType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontFormat~1bitmap/title",
          "value": "kCTFontFormatBitmap"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontFormat~1bitmap/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFormatBitmap"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontFormat~1trueType/title",
          "value": "kCTFontFormatTrueType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontFormat~1trueType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFormatTrueType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontFormat~1postScript/title",
          "value": "kCTFontFormatPostScript"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontFormat~1postScript/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFormatPostScript"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontFormat/title",
          "value": "CTFontFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontFormat~1unrecognized/title",
          "value": "kCTFontFormatUnrecognized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontFormat~1unrecognized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFormatUnrecognized"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontFormat~1openTypePostScript/title",
          "value": "kCTFontFormatOpenTypePostScript"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontFormat~1openTypePostScript/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFormatOpenTypePostScript"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontOrientation/title",
          "value": "CTFontOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontOrientation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontPriority/title",
          "value": "CTFontPriority"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontPriority/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontPriority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontPriority/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontPriority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFormatAttribute/title",
          "value": "kCTFontFormatAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFormatAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFormatAttribute"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/ctfontformat"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/ctfontformat"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
