{
  "abstract": [
    {
      "text": "The symbolic representation of stylistic font attributes.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CTFontSymbolicTraits",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CTFontSymbolicTraits"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CTFontSymbolicTraits"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "CTFontSymbolicTraits"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CTFontSymbolicTraits"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "code": "CTFontSymbolicTraits",
              "type": "codeVoice"
            },
            {
              "text": " symbolically describes stylistic aspects of a font. The upper 16 bits are used to describe appearance of the font, whereas the lower 16 bits are for typeface information. The font appearance information represented by the upper 16 bits can be used for stylistic font matching.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass": {
      "abstract": [
        {
          "text": "The stylistic class values of the font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontStylisticClass"
        }
      ],
      "role": "symbol",
      "title": "CTFontStylisticClass",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits": {
      "abstract": [
        {
          "text": "The symbolic representation of stylistic font attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "role": "symbol",
      "title": "CTFontSymbolicTraits",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/boldTrait": {
      "abstract": [
        {
          "text": "The font typestyle is boldface.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "boldTrait"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/boldTrait",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontBoldTrait"
        }
      ],
      "role": "symbol",
      "title": "boldTrait",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/boldtrait"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/classMaskTrait": {
      "abstract": [
        {
          "text": "Mask for the font class.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classMaskTrait"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/classMaskTrait",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontClassMaskTrait"
        }
      ],
      "role": "symbol",
      "title": "classMaskTrait",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/classmasktrait"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/colorGlyphsTrait": {
      "abstract": [
        {
          "text": "The font contains color glyphs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "colorGlyphsTrait"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/colorGlyphsTrait",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontColorGlyphsTrait"
        }
      ],
      "role": "symbol",
      "title": "colorGlyphsTrait",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/colorglyphstrait"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/compositeTrait": {
      "abstract": [
        {
          "text": "The font is in Composite Font Reference format.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "compositeTrait"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/compositeTrait",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontCompositeTrait"
        }
      ],
      "role": "symbol",
      "title": "compositeTrait",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/compositetrait"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/condensedTrait": {
      "abstract": [
        {
          "text": "The font typestyle is condensed.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "condensedTrait"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/condensedTrait",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontCondensedTrait"
        }
      ],
      "role": "symbol",
      "title": "condensedTrait",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/condensedtrait"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/expandedTrait": {
      "abstract": [
        {
          "text": "The font typestyle is expanded.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "expandedTrait"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/expandedTrait",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontExpandedTrait"
        }
      ],
      "role": "symbol",
      "title": "expandedTrait",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/expandedtrait"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a symbolic traits structure with the specified raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/init(rawvalue:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/italicTrait": {
      "abstract": [
        {
          "text": "The font typestyle is italic.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "italicTrait"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/italicTrait",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontItalicTrait"
        }
      ],
      "role": "symbol",
      "title": "italicTrait",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/italictrait"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/monoSpaceTrait": {
      "abstract": [
        {
          "text": "The font uses fixed-pitch glyphs if available.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "monoSpaceTrait"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/monoSpaceTrait",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontMonoSpaceTrait"
        }
      ],
      "role": "symbol",
      "title": "monoSpaceTrait",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/monospacetrait"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitBold": {
      "abstract": [
        {
          "text": "The font typestyle is boldface.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "traitBold"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitBold",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTraitBold"
        }
      ],
      "role": "symbol",
      "title": "traitBold",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/traitbold"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitClassMask": {
      "abstract": [
        {
          "text": "Mask for the font class.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "traitClassMask"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitClassMask",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTraitClassMask"
        }
      ],
      "role": "symbol",
      "title": "traitClassMask",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/traitclassmask"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitColorGlyphs": {
      "abstract": [
        {
          "text": "The font contains color glyphs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "traitColorGlyphs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitColorGlyphs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTraitColorGlyphs"
        }
      ],
      "role": "symbol",
      "title": "traitColorGlyphs",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/traitcolorglyphs"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitComposite": {
      "abstract": [
        {
          "text": "The font is in Composite Font Reference format.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "traitComposite"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitComposite",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTraitComposite"
        }
      ],
      "role": "symbol",
      "title": "traitComposite",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/traitcomposite"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitCondensed": {
      "abstract": [
        {
          "text": "The font typestyle is condensed.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "traitCondensed"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitCondensed",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTraitCondensed"
        }
      ],
      "role": "symbol",
      "title": "traitCondensed",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/traitcondensed"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitExpanded": {
      "abstract": [
        {
          "text": "The font typestyle is expanded.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "traitExpanded"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitExpanded",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTraitExpanded"
        }
      ],
      "role": "symbol",
      "title": "traitExpanded",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/traitexpanded"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitItalic": {
      "abstract": [
        {
          "text": "The font typestyle is italic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "traitItalic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitItalic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTraitItalic"
        }
      ],
      "role": "symbol",
      "title": "traitItalic",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/traititalic"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitMonoSpace": {
      "abstract": [
        {
          "text": "The font uses fixed-pitch glyphs if available.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "traitMonoSpace"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitMonoSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTraitMonoSpace"
        }
      ],
      "role": "symbol",
      "title": "traitMonoSpace",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/traitmonospace"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitUIOptimized": {
      "abstract": [
        {
          "text": "The font synthesizes appropriate attributes for user interface rendering, such as control titles, if necessary.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "traitUIOptimized"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitUIOptimized",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTraitUIOptimized"
        }
      ],
      "role": "symbol",
      "title": "traitUIOptimized",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/traituioptimized"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitVertical": {
      "abstract": [
        {
          "text": "The font uses vertical glyph variants and metrics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "traitVertical"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitVertical",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTraitVertical"
        }
      ],
      "role": "symbol",
      "title": "traitVertical",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/traitvertical"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/uiOptimizedTrait": {
      "abstract": [
        {
          "text": "The font synthesizes appropriate attributes for user interface rendering, such as control titles, if necessary.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "uiOptimizedTrait"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/uiOptimizedTrait",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontUIOptimizedTrait"
        }
      ],
      "role": "symbol",
      "title": "uiOptimizedTrait",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/uioptimizedtrait"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/verticalTrait": {
      "abstract": [
        {
          "text": "The font uses vertical glyph variants and metrics.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "verticalTrait"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/verticalTrait",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontVerticalTrait"
        }
      ],
      "role": "symbol",
      "title": "verticalTrait",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/verticaltrait"
    },
    "doc://com.apple.coretext/documentation/CoreText/font-class-mask-shift-constants": {
      "abstract": [
        {
          "text": "These constants represent the font class mask shift.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/font-class-mask-shift-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Font Class Mask Shift Constants",
      "type": "topic",
      "url": "/documentation/coretext/font-class-mask-shift-constants"
    },
    "doc://com.apple.coretext/documentation/CoreText/font-traits": {
      "abstract": [
        {
          "text": "The keys for accessing font traits from a font descriptor.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/font-traits",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Font Traits",
      "type": "topic",
      "url": "/documentation/coretext/font-traits"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-Font-Traits",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/font-traits",
        "doc://com.apple.coretext/documentation/CoreText/font-class-mask-shift-constants",
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass"
      ],
      "title": "Accessing Font Traits"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Symbolic-Traits",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitItalic",
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitBold",
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitExpanded",
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitCondensed",
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitMonoSpace",
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitVertical",
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitUIOptimized",
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitColorGlyphs",
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitComposite",
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitClassMask"
      ],
      "title": "Symbolic Traits"
    },
    {
      "anchor": "Deprecated-Constants",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/italicTrait",
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/boldTrait",
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/expandedTrait",
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/condensedTrait",
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/monoSpaceTrait",
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/verticalTrait",
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/uiOptimizedTrait",
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/colorGlyphsTrait",
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/compositeTrait",
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/classMaskTrait"
      ],
      "title": "Deprecated Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CTFontSymbolicTraits"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontSymbolicTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontSymbolicTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Symbolic-Traits",
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitItalic",
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitBold",
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitExpanded",
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitCondensed",
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitMonoSpace",
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitVertical",
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitUIOptimized",
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitColorGlyphs",
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitComposite",
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/traitClassMask"
              ],
              "title": "Symbolic Traits"
            },
            {
              "anchor": "Deprecated-Constants",
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/italicTrait",
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/boldTrait",
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/expandedTrait",
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/condensedTrait",
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/monoSpaceTrait",
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/verticalTrait",
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/uiOptimizedTrait",
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/colorGlyphsTrait",
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/compositeTrait",
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/classMaskTrait"
              ],
              "title": "Deprecated Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-Font-Traits",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/font-traits",
                "doc://com.apple.coretext/documentation/CoreText/font-class-mask-shift-constants",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass"
              ],
              "title": "Accessing Font Traits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CTFontSymbolicTraits"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint32_t",
                    "text": "uint32_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1condensedTrait/title",
          "value": "kCTFontCondensedTrait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1condensedTrait/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontCondensedTrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitClassMask/title",
          "value": "kCTFontTraitClassMask"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitClassMask/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTraitClassMask"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitColorGlyphs/title",
          "value": "kCTFontTraitColorGlyphs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitColorGlyphs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTraitColorGlyphs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1classMaskTrait/title",
          "value": "kCTFontClassMaskTrait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1classMaskTrait/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontClassMaskTrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass/title",
          "value": "CTFontStylisticClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontStylisticClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontStylisticClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1verticalTrait/title",
          "value": "kCTFontVerticalTrait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1verticalTrait/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontVerticalTrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitVertical/title",
          "value": "kCTFontTraitVertical"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitVertical/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTraitVertical"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1uiOptimizedTrait/title",
          "value": "kCTFontUIOptimizedTrait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1uiOptimizedTrait/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontUIOptimizedTrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits/title",
          "value": "CTFontSymbolicTraits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontSymbolicTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontSymbolicTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitComposite/title",
          "value": "kCTFontTraitComposite"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitComposite/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTraitComposite"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1compositeTrait/title",
          "value": "kCTFontCompositeTrait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1compositeTrait/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontCompositeTrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1monoSpaceTrait/title",
          "value": "kCTFontMonoSpaceTrait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1monoSpaceTrait/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontMonoSpaceTrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitCondensed/title",
          "value": "kCTFontTraitCondensed"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitCondensed/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTraitCondensed"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitBold/title",
          "value": "kCTFontTraitBold"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitBold/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTraitBold"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1colorGlyphsTrait/title",
          "value": "kCTFontColorGlyphsTrait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1colorGlyphsTrait/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontColorGlyphsTrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1expandedTrait/title",
          "value": "kCTFontExpandedTrait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1expandedTrait/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontExpandedTrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1boldTrait/title",
          "value": "kCTFontBoldTrait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1boldTrait/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontBoldTrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitItalic/title",
          "value": "kCTFontTraitItalic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitItalic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTraitItalic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitExpanded/title",
          "value": "kCTFontTraitExpanded"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitExpanded/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTraitExpanded"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitMonoSpace/title",
          "value": "kCTFontTraitMonoSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitMonoSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTraitMonoSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1italicTrait/title",
          "value": "kCTFontItalicTrait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1italicTrait/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontItalicTrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitUIOptimized/title",
          "value": "kCTFontTraitUIOptimized"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1traitUIOptimized/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTraitUIOptimized"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/ctfontsymbolictraits"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/ctfontsymbolictraits"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
