{
  "abstract": [
    {
      "text": "The stylistic class values of the font.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CTFontStylisticClass",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CTFontStylisticClass"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CTFontStylisticClass"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "CTFontStylisticClass"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CTFontStylisticClass"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "code": "CTFontStylisticClass",
              "type": "codeVoice"
            },
            {
              "text": " identifies certain stylistic qualities of the font. These values correspond closely to the font class values in the OpenType OS/2 table. The class values are bundled in the upper four bits of the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " and can be obtained via ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/classMaskTrait",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass": {
      "abstract": [
        {
          "text": "The stylistic class values of the font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontStylisticClass"
        }
      ],
      "role": "symbol",
      "title": "CTFontStylisticClass",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/clarendonSerifsClass": {
      "abstract": [
        {
          "text": "The font’s style is a variation of the Oldstyle Serifs and the Transitional Serifs.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "clarendonSerifsClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/clarendonSerifsClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontClarendonSerifsClass"
        }
      ],
      "role": "symbol",
      "title": "clarendonSerifsClass",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/clarendonserifsclass"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classClarendonSerifs": {
      "abstract": [
        {
          "text": "A font style variation of the Oldstyle Serifs and the Transitional Serifs.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classClarendonSerifs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classClarendonSerifs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontClassClarendonSerifs"
        }
      ],
      "role": "symbol",
      "title": "classClarendonSerifs",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/classclarendonserifs"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classFreeformSerifs": {
      "abstract": [
        {
          "text": "A font style that includes serifs but expresses a design freedom that doesn’t generally fit within the other serif design classifications.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classFreeformSerifs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classFreeformSerifs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontClassFreeformSerifs"
        }
      ],
      "role": "symbol",
      "title": "classFreeformSerifs",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/classfreeformserifs"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classModernSerifs": {
      "abstract": [
        {
          "text": "A font style based on the Latin printing style of the 20th century.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classModernSerifs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classModernSerifs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontClassModernSerifs"
        }
      ],
      "role": "symbol",
      "title": "classModernSerifs",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/classmodernserifs"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classOldStyleSerifs": {
      "abstract": [
        {
          "text": "A font style based on the Latin printing style of the 15th to 17th century.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classOldStyleSerifs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classOldStyleSerifs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontClassOldStyleSerifs"
        }
      ],
      "role": "symbol",
      "title": "classOldStyleSerifs",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/classoldstyleserifs"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classOrnamentals": {
      "abstract": [
        {
          "text": "A font style that includes highly decorated or stylized character shapes such as those typically used in headlines.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classOrnamentals"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classOrnamentals",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontClassOrnamentals"
        }
      ],
      "role": "symbol",
      "title": "classOrnamentals",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/classornamentals"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classSansSerif": {
      "abstract": [
        {
          "text": "A font style that includes most basic letter forms (excluding Scripts and Ornamentals) that do not have serifs on the strokes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classSansSerif"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classSansSerif",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontClassSansSerif"
        }
      ],
      "role": "symbol",
      "title": "classSansSerif",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/classsansserif"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classScripts": {
      "abstract": [
        {
          "text": "A font style among those typefaces designed to simulate handwriting.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classScripts"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classScripts",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontClassScripts"
        }
      ],
      "role": "symbol",
      "title": "classScripts",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/classscripts"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classSlabSerifs": {
      "abstract": [
        {
          "text": "A font style characterized by serifs with a square transition between the strokes and the serifs (no brackets).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classSlabSerifs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classSlabSerifs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontClassSlabSerifs"
        }
      ],
      "role": "symbol",
      "title": "classSlabSerifs",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/classslabserifs"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classSymbolic": {
      "abstract": [
        {
          "text": "A generally design-independent font style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classSymbolic"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classSymbolic",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontClassSymbolic"
        }
      ],
      "role": "symbol",
      "title": "classSymbolic",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/classsymbolic"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classTransitionalSerifs": {
      "abstract": [
        {
          "text": "A font style based on the Latin printing style of the 18th to 19th century.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classTransitionalSerifs"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classTransitionalSerifs",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontClassTransitionalSerifs"
        }
      ],
      "role": "symbol",
      "title": "classTransitionalSerifs",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/classtransitionalserifs"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/freeformSerifsClass": {
      "abstract": [
        {
          "text": "The font’s style includes serifs but expresses a design freedom that doesn’t generally fit within the other serif design classifications.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "freeformSerifsClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/freeformSerifsClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFreeformSerifsClass"
        }
      ],
      "role": "symbol",
      "title": "freeformSerifsClass",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/freeformserifsclass"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/init(rawValue:)": {
      "abstract": [
        {
          "text": "Creates a stylistic class structure with the specified raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/init(rawvalue:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/kCTFontClassUnknown": {
      "abstract": [
        {
          "text": "The font has no design classification.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCTFontClassUnknown"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/kCTFontClassUnknown",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCTFontClassUnknown",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/kctfontclassunknown"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/kCTFontUnknownClass": {
      "abstract": [
        {
          "text": "The font has no design classification.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "identifier",
          "text": "kCTFontUnknownClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/kCTFontUnknownClass",
      "kind": "symbol",
      "role": "symbol",
      "title": "kCTFontUnknownClass",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/kctfontunknownclass"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/modernSerifsClass": {
      "abstract": [
        {
          "text": "The font’s style is based on the Latin printing style of the 20th century.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "modernSerifsClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/modernSerifsClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontModernSerifsClass"
        }
      ],
      "role": "symbol",
      "title": "modernSerifsClass",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/modernserifsclass"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/oldStyleSerifsClass": {
      "abstract": [
        {
          "text": "The font’s style is based on the Latin printing style of the 15th to 17th century.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "oldStyleSerifsClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/oldStyleSerifsClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontOldStyleSerifsClass"
        }
      ],
      "role": "symbol",
      "title": "oldStyleSerifsClass",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/oldstyleserifsclass"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/ornamentalsClass": {
      "abstract": [
        {
          "text": "The font’s style includes highly decorated or stylized character shapes such as those typically used in headlines.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ornamentalsClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/ornamentalsClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontOrnamentalsClass"
        }
      ],
      "role": "symbol",
      "title": "ornamentalsClass",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/ornamentalsclass"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/sansSerifClass": {
      "abstract": [
        {
          "text": "The font’s style includes most basic letter forms (excluding Scripts and Ornamentals) that do not have serifs on the strokes.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "sansSerifClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/sansSerifClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontSansSerifClass"
        }
      ],
      "role": "symbol",
      "title": "sansSerifClass",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/sansserifclass"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/scriptsClass": {
      "abstract": [
        {
          "text": "The font’s style is among those typefaces designed to simulate handwriting.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "scriptsClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/scriptsClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontScriptsClass"
        }
      ],
      "role": "symbol",
      "title": "scriptsClass",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/scriptsclass"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/slabSerifsClass": {
      "abstract": [
        {
          "text": "The font’s style is characterized by serifs with a square transition between the strokes and the serifs (no brackets).",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "slabSerifsClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/slabSerifsClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontSlabSerifsClass"
        }
      ],
      "role": "symbol",
      "title": "slabSerifsClass",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/slabserifsclass"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/symbolicClass": {
      "abstract": [
        {
          "text": "The font’s style is generally design independent.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "symbolicClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/symbolicClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontSymbolicClass"
        }
      ],
      "role": "symbol",
      "title": "symbolicClass",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/symbolicclass"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/transitionalSerifsClass": {
      "abstract": [
        {
          "text": "The font’s style is based on the Latin printing style of the 18th to 19th century.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "transitionalSerifsClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontStylisticClass",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/transitionalSerifsClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTransitionalSerifsClass"
        }
      ],
      "role": "symbol",
      "title": "transitionalSerifsClass",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass/transitionalserifsclass"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits": {
      "abstract": [
        {
          "text": "The symbolic representation of stylistic font attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "role": "symbol",
      "title": "CTFontSymbolicTraits",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/classMaskTrait": {
      "abstract": [
        {
          "text": "Mask for the font class.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "classMaskTrait"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits/classMaskTrait",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontClassMaskTrait"
        }
      ],
      "role": "symbol",
      "title": "classMaskTrait",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits/classmasktrait"
    },
    "doc://com.apple.coretext/documentation/CoreText/font-class-mask-shift-constants": {
      "abstract": [
        {
          "text": "These constants represent the font class mask shift.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/font-class-mask-shift-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Font Class Mask Shift Constants",
      "type": "topic",
      "url": "/documentation/coretext/font-class-mask-shift-constants"
    },
    "doc://com.apple.coretext/documentation/CoreText/font-traits": {
      "abstract": [
        {
          "text": "The keys for accessing font traits from a font descriptor.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/font-traits",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Font Traits",
      "type": "topic",
      "url": "/documentation/coretext/font-traits"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s10SetAlgebraP": {
      "abstract": [
        {
          "text": "A type that provides mathematical set operations.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "SetAlgebra"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP7ElementQa",
          "text": "Element"
        },
        {
          "kind": "text",
          "text": "> : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s25ExpressibleByArrayLiteralP",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s10SetAlgebraP",
      "kind": "symbol",
      "role": "symbol",
      "title": "SetAlgebra",
      "type": "topic",
      "url": "/documentation/Swift/SetAlgebra"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP": {
      "abstract": [
        {
          "text": "A type that can be initialized using an array literal.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ExpressibleByArrayLiteral"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
      "kind": "symbol",
      "role": "symbol",
      "title": "ExpressibleByArrayLiteral",
      "type": "topic",
      "url": "/documentation/Swift/ExpressibleByArrayLiteral"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    },
    "doc://com.externally.resolved.symbol/s:s9OptionSetP": {
      "abstract": [
        {
          "text": "A type that presents a mathematical set interface to a bit set.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "OptionSet"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s10SetAlgebraP",
          "text": "SetAlgebra"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s9OptionSetP",
      "kind": "symbol",
      "role": "symbol",
      "title": "OptionSet",
      "type": "topic",
      "url": "/documentation/Swift/OptionSet"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:s25ExpressibleByArrayLiteralP",
        "doc://com.externally.resolved.symbol/s:s9OptionSetP",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP",
        "doc://com.externally.resolved.symbol/s:s10SetAlgebraP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-Font-Traits",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/font-traits",
        "doc://com.apple.coretext/documentation/CoreText/font-class-mask-shift-constants",
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits"
      ],
      "title": "Accessing Font Traits"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Stylistic-Classes",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classOldStyleSerifs",
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classTransitionalSerifs",
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classModernSerifs",
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classClarendonSerifs",
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classSlabSerifs",
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classFreeformSerifs",
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classSansSerif",
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classOrnamentals",
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classScripts",
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classSymbolic"
      ],
      "title": "Stylistic Classes"
    },
    {
      "anchor": "Deprecated-Constants",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/oldStyleSerifsClass",
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/transitionalSerifsClass",
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/modernSerifsClass",
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/clarendonSerifsClass",
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/slabSerifsClass",
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/freeformSerifsClass",
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/sansSerifClass",
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/ornamentalsClass",
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/scriptsClass",
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/symbolicClass"
      ],
      "title": "Deprecated Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CTFontStylisticClass"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontStylisticClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontStylisticClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Stylistic-Classes",
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/kCTFontClassUnknown",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classOldStyleSerifs",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classTransitionalSerifs",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classModernSerifs",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classClarendonSerifs",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classSlabSerifs",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classFreeformSerifs",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classSansSerif",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classOrnamentals",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classScripts",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/classSymbolic"
              ],
              "title": "Stylistic Classes"
            },
            {
              "anchor": "Deprecated-Constants",
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/kCTFontUnknownClass",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/oldStyleSerifsClass",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/transitionalSerifsClass",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/modernSerifsClass",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/clarendonSerifsClass",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/slabSerifsClass",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/freeformSerifsClass",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/sansSerifClass",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/ornamentalsClass",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/scriptsClass",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass/symbolicClass"
              ],
              "title": "Deprecated Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-Font-Traits",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/font-traits",
                "doc://com.apple.coretext/documentation/CoreText/font-class-mask-shift-constants",
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits"
              ],
              "title": "Accessing Font Traits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CTFontStylisticClass"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint32_t",
                    "text": "uint32_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1sansSerifClass/title",
          "value": "kCTFontSansSerifClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1sansSerifClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontSansSerifClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1freeformSerifsClass/title",
          "value": "kCTFontFreeformSerifsClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1freeformSerifsClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFreeformSerifsClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classSymbolic/title",
          "value": "kCTFontClassSymbolic"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classSymbolic/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontClassSymbolic"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1modernSerifsClass/title",
          "value": "kCTFontModernSerifsClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1modernSerifsClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontModernSerifsClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1slabSerifsClass/title",
          "value": "kCTFontSlabSerifsClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1slabSerifsClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontSlabSerifsClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1oldStyleSerifsClass/title",
          "value": "kCTFontOldStyleSerifsClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1oldStyleSerifsClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontOldStyleSerifsClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1transitionalSerifsClass/title",
          "value": "kCTFontTransitionalSerifsClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1transitionalSerifsClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTransitionalSerifsClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1symbolicClass/title",
          "value": "kCTFontSymbolicClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1symbolicClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontSymbolicClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classSlabSerifs/title",
          "value": "kCTFontClassSlabSerifs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classSlabSerifs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontClassSlabSerifs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classSansSerif/title",
          "value": "kCTFontClassSansSerif"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classSansSerif/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontClassSansSerif"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classScripts/title",
          "value": "kCTFontClassScripts"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classScripts/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontClassScripts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1ornamentalsClass/title",
          "value": "kCTFontOrnamentalsClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1ornamentalsClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontOrnamentalsClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass/title",
          "value": "CTFontStylisticClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontStylisticClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontStylisticClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classFreeformSerifs/title",
          "value": "kCTFontClassFreeformSerifs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classFreeformSerifs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontClassFreeformSerifs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classTransitionalSerifs/title",
          "value": "kCTFontClassTransitionalSerifs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classTransitionalSerifs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontClassTransitionalSerifs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1clarendonSerifsClass/title",
          "value": "kCTFontClarendonSerifsClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1clarendonSerifsClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontClarendonSerifsClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits/title",
          "value": "CTFontSymbolicTraits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontSymbolicTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontSymbolicTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classModernSerifs/title",
          "value": "kCTFontClassModernSerifs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classModernSerifs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontClassModernSerifs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classOldStyleSerifs/title",
          "value": "kCTFontClassOldStyleSerifs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classOldStyleSerifs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontClassOldStyleSerifs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classOrnamentals/title",
          "value": "kCTFontClassOrnamentals"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classOrnamentals/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontClassOrnamentals"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1classMaskTrait/title",
          "value": "kCTFontClassMaskTrait"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits~1classMaskTrait/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontClassMaskTrait"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1scriptsClass/title",
          "value": "kCTFontScriptsClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1scriptsClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontScriptsClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classClarendonSerifs/title",
          "value": "kCTFontClassClarendonSerifs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass~1classClarendonSerifs/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontClassClarendonSerifs"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/ctfontstylisticclass"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/ctfontstylisticclass"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
