{
  "abstract": [
    {
      "text": "Returns a font reference that most accurately maps the string range based on the current font and language.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTFontCreateForStringWithLanguage(_:_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CTFontCreateForStringWithLanguage",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CTFontCreateForStringWithLanguage"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CTFontRef",
        "text": "CTFont"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@CFRange",
        "text": "CFRange"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      },
      {
        "kind": "text",
        "text": "?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CTFontRef",
        "text": "CTFont"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CTFontCreateForStringWithLanguage"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "7.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.9",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CTFontCreateForStringWithLanguage(_:_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CTFontCreateForStringWithLanguage"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "currentFont"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFont",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CTFontRef",
              "text": "CTFont"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "string"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "range"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@SA@CFRange",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@CFRange",
              "text": "CFRange"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "language"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            },
            {
              "kind": "text",
              "text": "?) -> "
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFont",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CTFontRef",
              "text": "CTFont"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The current font that contains a valid cascade list.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "currentFont"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A Unicode string containing characters that can’t be encoded by the current font.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "string"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfrange",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " specifying the range of the string to map.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "range"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "A language identifier to select a font for a particular localization.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "language"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The best substitute font that can encode the specified string range.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The current font itself can be returned if it covers the string provided. If the caller does not specify the language parameter, the function uses the current system language. The format of the language identifier should conform to ",
              "type": "text"
            },
            {
              "identifier": "http://unicode.org/reports/tr35/",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFont": {
      "abstract": [
        {
          "text": "A font object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFont"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFont",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFont"
        }
      ],
      "role": "symbol",
      "title": "CTFont",
      "type": "topic",
      "url": "/documentation/coretext/ctfont"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontCopyCharacterSet(_:)": {
      "abstract": [
        {
          "text": "Returns the Unicode character set of the font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontCopyCharacterSet"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontRef",
          "text": "CTFont"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFCharacterSetRef",
          "text": "CFCharacterSet"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontCopyCharacterSet(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontCopyCharacterSet"
        }
      ],
      "role": "symbol",
      "title": "CTFontCopyCharacterSet(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontcopycharacterset(_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontCreateCopyWithAttributes(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new font with additional attributes based on the original font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontCreateCopyWithAttributes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontRef",
          "text": "CTFont"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGAffineTransform",
          "text": "CGAffineTransform"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontDescriptorRef",
          "text": "CTFontDescriptor"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontRef",
          "text": "CTFont"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontCreateCopyWithAttributes(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontCreateCopyWithAttributes"
        }
      ],
      "role": "symbol",
      "title": "CTFontCreateCopyWithAttributes(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontcreatecopywithattributes(_:_:_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontCreateCopyWithFamily(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new font in the specified family based on the traits of the original font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontCreateCopyWithFamily"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontRef",
          "text": "CTFont"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGAffineTransform",
          "text": "CGAffineTransform"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontRef",
          "text": "CTFont"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontCreateCopyWithFamily(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontCreateCopyWithFamily"
        }
      ],
      "role": "symbol",
      "title": "CTFontCreateCopyWithFamily(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontcreatecopywithfamily(_:_:_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontCreateCopyWithSymbolicTraits(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new font in the same font family as the original with the specified symbolic traits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontCreateCopyWithSymbolicTraits"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontRef",
          "text": "CTFont"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGAffineTransform",
          "text": "CGAffineTransform"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontSymbolicTraits",
          "text": "CTFontSymbolicTraits"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontRef",
          "text": "CTFont"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontCreateCopyWithSymbolicTraits(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontCreateCopyWithSymbolicTraits"
        }
      ],
      "role": "symbol",
      "title": "CTFontCreateCopyWithSymbolicTraits(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontcreatecopywithsymbolictraits(_:_:_:_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontCreateForString(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a font reference that most accurately maps the string range based on the current font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontCreateForString"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontRef",
          "text": "CTFont"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CFRange",
          "text": "CFRange"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontRef",
          "text": "CTFont"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontCreateForString(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontCreateForString"
        }
      ],
      "role": "symbol",
      "title": "CTFontCreateForString(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontcreateforstring(_:_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontCreateForStringWithLanguage(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a font reference that most accurately maps the string range based on the current font and language.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontCreateForStringWithLanguage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontRef",
          "text": "CTFont"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CFRange",
          "text": "CFRange"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontRef",
          "text": "CTFont"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontCreateForStringWithLanguage(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontCreateForStringWithLanguage"
        }
      ],
      "role": "symbol",
      "title": "CTFontCreateForStringWithLanguage(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontcreateforstringwithlanguage(_:_:_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontCreateUIFontForLanguage(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns the special user-interface font for the given language and user-interface type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontCreateUIFontForLanguage"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontUIFontType",
          "text": "CTFontUIFontType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontRef",
          "text": "CTFont"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontCreateUIFontForLanguage(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontCreateUIFontForLanguage"
        }
      ],
      "role": "symbol",
      "title": "CTFontCreateUIFontForLanguage(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontcreateuifontforlanguage(_:_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontCreateWithFontDescriptor(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new font reference that best matches the given font descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontCreateWithFontDescriptor"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontDescriptorRef",
          "text": "CTFontDescriptor"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGAffineTransform",
          "text": "CGAffineTransform"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontRef",
          "text": "CTFont"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontCreateWithFontDescriptor(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontCreateWithFontDescriptor"
        }
      ],
      "role": "symbol",
      "title": "CTFontCreateWithFontDescriptor(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontcreatewithfontdescriptor(_:_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontCreateWithFontDescriptorAndOptions(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new font reference that best matches the given font descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontCreateWithFontDescriptorAndOptions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontDescriptorRef",
          "text": "CTFontDescriptor"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGAffineTransform",
          "text": "CGAffineTransform"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontOptions",
          "text": "CTFontOptions"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontRef",
          "text": "CTFont"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontCreateWithFontDescriptorAndOptions(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontCreateWithFontDescriptorAndOptions"
        }
      ],
      "role": "symbol",
      "title": "CTFontCreateWithFontDescriptorAndOptions(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontcreatewithfontdescriptorandoptions(_:_:_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontCreateWithName(_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new font reference for the given name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontCreateWithName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGAffineTransform",
          "text": "CGAffineTransform"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontRef",
          "text": "CTFont"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontCreateWithName(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontCreateWithName"
        }
      ],
      "role": "symbol",
      "title": "CTFontCreateWithName(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontcreatewithname(_:_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontCreateWithNameAndOptions(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns a new font reference for the given name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontCreateWithNameAndOptions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGAffineTransform",
          "text": "CGAffineTransform"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTFontOptions",
          "text": "CTFontOptions"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontRef",
          "text": "CTFont"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontCreateWithNameAndOptions(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontCreateWithNameAndOptions"
        }
      ],
      "role": "symbol",
      "title": "CTFontCreateWithNameAndOptions(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontcreatewithnameandoptions(_:_:_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontGetGlyphsForCharacters(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Performs basic character-to-glyph mapping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontGetGlyphsForCharacters"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontRef",
          "text": "CTFont"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UniChar",
          "text": "UniChar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGGlyph",
          "text": "CGGlyph"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontGetGlyphsForCharacters(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontGetGlyphsForCharacters"
        }
      ],
      "role": "symbol",
      "title": "CTFontGetGlyphsForCharacters(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontgetglyphsforcharacters(_:_:_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontCascadeListAttribute": {
      "abstract": [
        {
          "text": "The cascade list used for a font reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontCascadeListAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontCascadeListAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontCascadeListAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontCascadeListAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontcascadelistattribute"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cfrange": {
      "abstract": [
        {
          "text": "A structure representing a range of sequential items in a container, such as characters in a buffer or elements in a collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CFRange"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfrange",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFRange",
      "type": "topic",
      "url": "/documentation/corefoundation/cfrange"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@SA@CFRange": {
      "abstract": [
        {
          "text": "A structure representing a range of sequential items in a container, such as characters in a buffer or elements in a collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CFRange"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@SA@CFRange",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFRange",
      "type": "topic",
      "url": "/documentation/corefoundation/cfrange"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    },
    "http://unicode.org/reports/tr35/": {
      "identifier": "http://unicode.org/reports/tr35/",
      "title": "UTS #35",
      "titleInlineContent": [
        {
          "text": "UTS #35",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "http://unicode.org/reports/tr35/"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTFontCopyCharacterSet(_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTFontGetGlyphsForCharacters(_:_:_:_:)",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontCascadeListAttribute"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Creating-Fonts",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTFontCreateWithName(_:_:_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTFontCreateWithNameAndOptions(_:_:_:_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTFontCreateWithFontDescriptor(_:_:_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTFontCreateWithFontDescriptorAndOptions(_:_:_:_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTFontCreateUIFontForLanguage(_:_:_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTFontCreateCopyWithAttributes(_:_:_:_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTFontCreateCopyWithSymbolicTraits(_:_:_:_:_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTFontCreateCopyWithFamily(_:_:_:_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTFontCreateForString(_:_:_:)"
      ],
      "title": "Creating Fonts"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "7.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.9",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CTFontCreateForStringWithLanguage"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontCreateForStringWithLanguage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTFontCopyCharacterSet(_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTFontGetGlyphsForCharacters(_:_:_:_:)",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontCascadeListAttribute"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Creating-Fonts",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTFontCreateWithName(_:_:_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTFontCreateWithNameAndOptions(_:_:_:_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTFontCreateWithFontDescriptor(_:_:_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTFontCreateWithFontDescriptorAndOptions(_:_:_:_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTFontCreateUIFontForLanguage(_:_:_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTFontCreateCopyWithAttributes(_:_:_:_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTFontCreateCopyWithSymbolicTraits(_:_:_:_:_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTFontCreateCopyWithFamily(_:_:_:_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTFontCreateForString(_:_:_:)"
              ],
              "title": "Creating Fonts"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFont",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CTFontRef",
                    "text": "CTFontRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CTFontCreateForStringWithLanguage"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFont",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CTFontRef",
                    "text": "CTFontRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "currentFont"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "string"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@SA@CFRange",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@SA@CFRange",
                    "text": "CFRange"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "range"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "language"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The current font that contains a valid cascade list.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "currentFont"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A Unicode string containing characters that can’t be encoded by the current font.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "string"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfrange",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " specifying the range of the string to map.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "range"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "A language identifier to select a font for a particular localization.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "language"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The best substitute font that can encode the specified string range.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontCascadeListAttribute/title",
          "value": "kCTFontCascadeListAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontCascadeListAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontCascadeListAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCreateWithFontDescriptor(_:_:_:)/title",
          "value": "CTFontCreateWithFontDescriptor"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCreateWithFontDescriptor(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontCreateWithFontDescriptor"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontGetGlyphsForCharacters(_:_:_:_:)/title",
          "value": "CTFontGetGlyphsForCharacters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontGetGlyphsForCharacters(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontGetGlyphsForCharacters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCreateCopyWithFamily(_:_:_:_:)/title",
          "value": "CTFontCreateCopyWithFamily"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCreateCopyWithFamily(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontCreateCopyWithFamily"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCreateWithNameAndOptions(_:_:_:_:)/title",
          "value": "CTFontCreateWithNameAndOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCreateWithNameAndOptions(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontCreateWithNameAndOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCreateWithName(_:_:_:)/title",
          "value": "CTFontCreateWithName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCreateWithName(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontCreateWithName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCreateCopyWithSymbolicTraits(_:_:_:_:_:)/title",
          "value": "CTFontCreateCopyWithSymbolicTraits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCreateCopyWithSymbolicTraits(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontCreateCopyWithSymbolicTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCreateUIFontForLanguage(_:_:_:)/title",
          "value": "CTFontCreateUIFontForLanguage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCreateUIFontForLanguage(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontCreateUIFontForLanguage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCreateForStringWithLanguage(_:_:_:_:)/title",
          "value": "CTFontCreateForStringWithLanguage"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCreateForStringWithLanguage(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontCreateForStringWithLanguage"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCopyCharacterSet(_:)/title",
          "value": "CTFontCopyCharacterSet"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCopyCharacterSet(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontCopyCharacterSet"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCreateCopyWithAttributes(_:_:_:_:)/title",
          "value": "CTFontCreateCopyWithAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCreateCopyWithAttributes(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontCreateCopyWithAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCreateForString(_:_:_:)/title",
          "value": "CTFontCreateForString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCreateForString(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontCreateForString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFont/title",
          "value": "CTFontRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFont/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFont/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCreateWithFontDescriptorAndOptions(_:_:_:_:)/title",
          "value": "CTFontCreateWithFontDescriptorAndOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCreateWithFontDescriptorAndOptions(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontCreateWithFontDescriptorAndOptions"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/ctfontcreateforstringwithlanguage(_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/ctfontcreateforstringwithlanguage(_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
