{
  "abstract": [
    {
      "text": "Performs basic character-to-glyph mapping.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTFontGetGlyphsForCharacters(_:_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CTFontGetGlyphsForCharacters",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CTFontGetGlyphsForCharacters"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CTFontRef",
        "text": "CTFont"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:SP",
        "text": "UnsafePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@UniChar",
        "text": "UniChar"
      },
      {
        "kind": "text",
        "text": ">, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sp",
        "text": "UnsafeMutablePointer"
      },
      {
        "kind": "text",
        "text": "<"
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CGGlyph",
        "text": "CGGlyph"
      },
      {
        "kind": "text",
        "text": ">, "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFIndex",
        "text": "CFIndex"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sb",
        "text": "Bool"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CTFontGetGlyphsForCharacters"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CTFontGetGlyphsForCharacters(_:_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CTFontGetGlyphsForCharacters"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "font"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFont",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CTFontRef",
              "text": "CTFont"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "characters"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:SP",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:SP",
              "text": "UnsafePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@UniChar",
              "text": "UniChar"
            },
            {
              "kind": "text",
              "text": ">, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "glyphs"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sp",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sp",
              "text": "UnsafeMutablePointer"
            },
            {
              "kind": "text",
              "text": "<"
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CGGlyph",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CGGlyph",
              "text": "CGGlyph"
            },
            {
              "kind": "text",
              "text": ">, "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "count"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFIndex",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFIndex",
              "text": "CFIndex"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sb",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sb",
              "text": "Bool"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The font reference.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "font"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "An array of Unicode characters.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "characters"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "On output, points to an array of glyph values.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "glyphs"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The capacity of the character and glyph arrays.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "count"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "",
              "type": "text"
            },
            {
              "code": "True",
              "type": "codeVoice"
            },
            {
              "text": " if the font could encode all Unicode characters; otherwise ",
              "type": "text"
            },
            {
              "code": "False",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Provides basic Unicode encoding for the given font, returning by reference an array of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/coregraphics/cgglyph",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " values corresponding to a given array of Unicode characters for the given font.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "If a glyph could not be encoded, a value of ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": " is passed back at the corresponding index in the ",
              "type": "text"
            },
            {
              "code": "glyphs",
              "type": "codeVoice"
            },
            {
              "text": " array and the function returns ",
              "type": "text"
            },
            {
              "code": "False",
              "type": "codeVoice"
            },
            {
              "text": ". It is the responsibility of the caller to handle the Unicode properties of the input characters.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFont": {
      "abstract": [
        {
          "text": "A font object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFont"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFont",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFont"
        }
      ],
      "role": "symbol",
      "title": "CTFont",
      "type": "topic",
      "url": "/documentation/coretext/ctfont"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontDrawGlyphs(_:_:_:_:_:)": {
      "abstract": [
        {
          "text": "Renders the given glyphs of a font at the specified positions in the supplied graphics context.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontDrawGlyphs"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontRef",
          "text": "CTFont"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGGlyph",
          "text": "CGGlyph"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGContextRef",
          "text": "CGContext"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontDrawGlyphs(_:_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontDrawGlyphs"
        }
      ],
      "role": "symbol",
      "title": "CTFontDrawGlyphs(_:_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontdrawglyphs(_:_:_:_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontGetGlyphsForCharacters(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Performs basic character-to-glyph mapping.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontGetGlyphsForCharacters"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontRef",
          "text": "CTFont"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@UniChar",
          "text": "UniChar"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGGlyph",
          "text": "CGGlyph"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontGetGlyphsForCharacters(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontGetGlyphsForCharacters"
        }
      ],
      "role": "symbol",
      "title": "CTFontGetGlyphsForCharacters(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontgetglyphsforcharacters(_:_:_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontGetLigatureCaretPositions(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Returns caret positions within a glyph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontGetLigatureCaretPositions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontRef",
          "text": "CTFont"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGGlyph",
          "text": "CGGlyph"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontGetLigatureCaretPositions(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontGetLigatureCaretPositions"
        }
      ],
      "role": "symbol",
      "title": "CTFontGetLigatureCaretPositions(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontgetligaturecaretpositions(_:_:_:_:)"
    },
    "doc://com.apple.documentation/documentation/coregraphics/cgglyph": {
      "abstract": [
        {
          "text": "An index into the internal glyph table of a font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "CGGlyph"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/coregraphics/cgglyph",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGGlyph",
      "type": "topic",
      "url": "/documentation/coregraphics/cgglyph"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFIndex": {
      "abstract": [
        {
          "text": "Priority values used for kAXPriorityKey",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFIndex",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFIndex",
      "type": "topic",
      "url": "/documentation/corefoundation/cfindex"
    },
    "doc://com.externally.resolved.symbol/c:@T@CGGlyph": {
      "abstract": [
        {
          "text": "An index into the internal glyph table of a font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "typealias "
        },
        {
          "kind": "identifier",
          "text": "CGGlyph"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CGGlyph",
      "kind": "symbol",
      "role": "symbol",
      "title": "CGGlyph",
      "type": "topic",
      "url": "/documentation/coregraphics/cgglyph"
    },
    "doc://com.externally.resolved.symbol/s:SP": {
      "abstract": [
        {
          "text": "A pointer for accessing data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SP",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafePointer"
    },
    "doc://com.externally.resolved.symbol/s:Sb": {
      "abstract": [
        {
          "text": "A value type whose instances are either `true` or `false`.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Bool"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sb",
      "kind": "symbol",
      "role": "symbol",
      "title": "Bool",
      "type": "topic",
      "url": "/documentation/Swift/Bool"
    },
    "doc://com.externally.resolved.symbol/s:Sp": {
      "abstract": [
        {
          "text": "A pointer for accessing and manipulating data of a specific type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "genericParameter",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": "> "
        },
        {
          "kind": "keyword",
          "text": "where"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "typeIdentifier",
          "text": "Pointee"
        },
        {
          "kind": "text",
          "text": " : ~Copyable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sp",
      "kind": "symbol",
      "role": "symbol",
      "title": "UnsafeMutablePointer",
      "type": "topic",
      "url": "/documentation/Swift/UnsafeMutablePointer"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Working-with-Glyphs",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTFontDrawGlyphs(_:_:_:_:_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTFontGetLigatureCaretPositions(_:_:_:_:)"
      ],
      "title": "Working with Glyphs"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CTFontGetGlyphsForCharacters"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontGetGlyphsForCharacters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Working-with-Glyphs",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTFontDrawGlyphs(_:_:_:_:_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTFontGetLigatureCaretPositions(_:_:_:_:)"
              ],
              "title": "Working with Glyphs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:b",
                    "text": "bool"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CTFontGetGlyphsForCharacters"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFont",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CTFontRef",
                    "text": "CTFontRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "font"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@UniChar",
                    "text": "UniChar"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "characters"
                  },
                  {
                    "kind": "text",
                    "text": "[], "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CGGlyph",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CGGlyph",
                    "text": "CGGlyph"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "glyphs"
                  },
                  {
                    "kind": "text",
                    "text": "[], "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFIndex",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFIndex",
                    "text": "CFIndex"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "count"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The font reference.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "font"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "An array of Unicode characters.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "characters"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "On output, points to an array of glyph values.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "glyphs"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The capacity of the character and glyph arrays.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "count"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "",
                    "type": "text"
                  },
                  {
                    "code": "True",
                    "type": "codeVoice"
                  },
                  {
                    "text": " if the font could encode all Unicode characters; otherwise ",
                    "type": "text"
                  },
                  {
                    "code": "False",
                    "type": "codeVoice"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFont/title",
          "value": "CTFontRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFont/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFont/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontGetLigatureCaretPositions(_:_:_:_:)/title",
          "value": "CTFontGetLigatureCaretPositions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontGetLigatureCaretPositions(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontGetLigatureCaretPositions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontGetGlyphsForCharacters(_:_:_:_:)/title",
          "value": "CTFontGetGlyphsForCharacters"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontGetGlyphsForCharacters(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontGetGlyphsForCharacters"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDrawGlyphs(_:_:_:_:_:)/title",
          "value": "CTFontDrawGlyphs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDrawGlyphs(_:_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontDrawGlyphs"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/ctfontgetglyphsforcharacters(_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/ctfontgetglyphsforcharacters(_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
