{
  "abstract": [
    {
      "text": "Gets the character collection for a glyph info object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoGetCharacterCollection(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CTGlyphInfoGetCharacterCollection",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CTGlyphInfoGetCharacterCollection"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CTGlyphInfoRef",
        "text": "CTGlyphInfo"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@CTCharacterCollection",
        "text": "CTCharacterCollection"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CTGlyphInfoGetCharacterCollection"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CTGlyphInfoGetCharacterCollection(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CTGlyphInfoGetCharacterCollection"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "glyphInfo"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfo",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CTGlyphInfoRef",
              "text": "CTGlyphInfo"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CTCharacterCollection",
              "text": "CTCharacterCollection"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The glyph info from which to get the character collection. May not be ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "glyphInfo"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The character collection of the given glyph info object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "If the glyph info object was created with a glyph name or a glyph index, its character collection is ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTIdentityMappingCharacterCollection",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection": {
      "abstract": [
        {
          "text": "Constants that specify character collections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTCharacterCollection"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTCharacterCollection"
        }
      ],
      "role": "symbol",
      "title": "CTCharacterCollection",
      "type": "topic",
      "url": "/documentation/coretext/ctcharactercollection"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTIdentityMappingCharacterCollection": {
      "abstract": [
        {
          "text": "The character identifier is equal to the glyph index.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTIdentityMappingCharacterCollection"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTCharacterCollection",
          "text": "CTCharacterCollection"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection/kCTIdentityMappingCharacterCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTIdentityMappingCharacterCollection"
        }
      ],
      "role": "symbol",
      "title": "kCTIdentityMappingCharacterCollection",
      "type": "topic",
      "url": "/documentation/coretext/ctcharactercollection/kctidentitymappingcharactercollection"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfo": {
      "abstract": [
        {
          "text": "Override a font’s specified mapping from Unicode to the glyph ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTGlyphInfo"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTGlyphInfo"
        }
      ],
      "role": "symbol",
      "title": "CTGlyphInfo",
      "type": "topic",
      "url": "/documentation/coretext/ctglyphinfo"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoGetCharacterCollection(_:)": {
      "abstract": [
        {
          "text": "Gets the character collection for a glyph info object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTGlyphInfoGetCharacterCollection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTGlyphInfoRef",
          "text": "CTGlyphInfo"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTCharacterCollection",
          "text": "CTCharacterCollection"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoGetCharacterCollection(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTGlyphInfoGetCharacterCollection"
        }
      ],
      "role": "symbol",
      "title": "CTGlyphInfoGetCharacterCollection(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctglyphinfogetcharactercollection(_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoGetCharacterIdentifier(_:)": {
      "abstract": [
        {
          "text": "Gets the character identifier for a glyph info object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTGlyphInfoGetCharacterIdentifier"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTGlyphInfoRef",
          "text": "CTGlyphInfo"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGFontIndex",
          "text": "CGFontIndex"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoGetCharacterIdentifier(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTGlyphInfoGetCharacterIdentifier"
        }
      ],
      "role": "symbol",
      "title": "CTGlyphInfoGetCharacterIdentifier(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctglyphinfogetcharacteridentifier(_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoGetGlyph(_:)": {
      "abstract": [
        {
          "text": "Retrieves the glyph for a glyph info, if that object exists.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTGlyphInfoGetGlyph"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTGlyphInfoRef",
          "text": "CTGlyphInfo"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGGlyph",
          "text": "CGGlyph"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoGetGlyph(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTGlyphInfoGetGlyph"
        }
      ],
      "role": "symbol",
      "title": "CTGlyphInfoGetGlyph(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctglyphinfogetglyph(_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoGetGlyphName(_:)": {
      "abstract": [
        {
          "text": "Retrieves the glyph name for a glyph info object, if that object exists.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTGlyphInfoGetGlyphName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTGlyphInfoRef",
          "text": "CTGlyphInfo"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoGetGlyphName(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTGlyphInfoGetGlyphName"
        }
      ],
      "role": "symbol",
      "title": "CTGlyphInfoGetGlyphName(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctglyphinfogetglyphname(_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-GlyphInfo-Data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoGetGlyphName(_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoGetCharacterIdentifier(_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoGetGlyph(_:)"
      ],
      "title": "Getting GlyphInfo Data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CTGlyphInfoGetCharacterCollection"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTGlyphInfoGetCharacterCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-GlyphInfo-Data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoGetGlyphName(_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoGetCharacterIdentifier(_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoGetGlyph(_:)"
              ],
              "title": "Getting GlyphInfo Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@CTCharacterCollection",
                    "text": "CTCharacterCollection"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CTGlyphInfoGetCharacterCollection"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfo",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CTGlyphInfoRef",
                    "text": "CTGlyphInfoRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "glyphInfo"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The glyph info from which to get the character collection. May not be ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "glyphInfo"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The character collection of the given glyph info object.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTGlyphInfoGetCharacterIdentifier(_:)/title",
          "value": "CTGlyphInfoGetCharacterIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTGlyphInfoGetCharacterIdentifier(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTGlyphInfoGetCharacterIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTGlyphInfoGetGlyph(_:)/title",
          "value": "CTGlyphInfoGetGlyph"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTGlyphInfoGetGlyph(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTGlyphInfoGetGlyph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1kCTIdentityMappingCharacterCollection/title",
          "value": "kCTIdentityMappingCharacterCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection~1kCTIdentityMappingCharacterCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTIdentityMappingCharacterCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTGlyphInfo/title",
          "value": "CTGlyphInfoRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTGlyphInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTGlyphInfoRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTGlyphInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTGlyphInfoRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTGlyphInfoGetCharacterCollection(_:)/title",
          "value": "CTGlyphInfoGetCharacterCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTGlyphInfoGetCharacterCollection(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTGlyphInfoGetCharacterCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection/title",
          "value": "CTCharacterCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCharacterCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCharacterCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTGlyphInfoGetGlyphName(_:)/title",
          "value": "CTGlyphInfoGetGlyphName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTGlyphInfoGetGlyphName(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTGlyphInfoGetGlyphName"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/ctglyphinfogetcharactercollection(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/ctglyphinfogetcharactercollection(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
