{
  "abstract": [
    {
      "text": "Override a font’s specified mapping from Unicode to the glyph ID.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfo"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@CTGlyphInfoRef",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CTGlyphInfo"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CTGlyphInfo"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CTGlyphInfo"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CTGlyphInfo"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection": {
      "abstract": [
        {
          "text": "Constants that specify character collections.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTCharacterCollection"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTCharacterCollection"
        }
      ],
      "role": "symbol",
      "title": "CTCharacterCollection",
      "type": "topic",
      "url": "/documentation/coretext/ctcharactercollection"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFont": {
      "abstract": [
        {
          "text": "A font object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFont"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFont",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFont"
        }
      ],
      "role": "symbol",
      "title": "CTFont",
      "type": "topic",
      "url": "/documentation/coretext/ctfont"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontCollection": {
      "abstract": [
        {
          "text": "A font collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontCollection"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontCollection"
        }
      ],
      "role": "symbol",
      "title": "CTFontCollection",
      "type": "topic",
      "url": "/documentation/coretext/ctfontcollection"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptor": {
      "abstract": [
        {
          "text": "A font descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontDescriptor"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontDescriptor"
        }
      ],
      "role": "symbol",
      "title": "CTFontDescriptor",
      "type": "topic",
      "url": "/documentation/coretext/ctfontdescriptor"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFrame": {
      "abstract": [
        {
          "text": "A frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFrame"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFrame"
        }
      ],
      "role": "symbol",
      "title": "CTFrame",
      "type": "topic",
      "url": "/documentation/coretext/ctframe"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFramesetter": {
      "abstract": [
        {
          "text": "Generate text frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFramesetter"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFramesetter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFramesetter"
        }
      ],
      "role": "symbol",
      "title": "CTFramesetter",
      "type": "topic",
      "url": "/documentation/coretext/ctframesetter"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfo": {
      "abstract": [
        {
          "text": "Override a font’s specified mapping from Unicode to the glyph ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTGlyphInfo"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTGlyphInfo"
        }
      ],
      "role": "symbol",
      "title": "CTGlyphInfo",
      "type": "topic",
      "url": "/documentation/coretext/ctglyphinfo"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoCreateWithCharacterIdentifier(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates an immutable glyph info object with a character identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTGlyphInfoCreateWithCharacterIdentifier"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGFontIndex",
          "text": "CGFontIndex"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTCharacterCollection",
          "text": "CTCharacterCollection"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTGlyphInfoRef",
          "text": "CTGlyphInfo"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoCreateWithCharacterIdentifier(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTGlyphInfoCreateWithCharacterIdentifier"
        }
      ],
      "role": "symbol",
      "title": "CTGlyphInfoCreateWithCharacterIdentifier(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctglyphinfocreatewithcharacteridentifier(_:_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoCreateWithGlyph(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates an immutable glyph info object with a glyph index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTGlyphInfoCreateWithGlyph"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGGlyph",
          "text": "CGGlyph"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontRef",
          "text": "CTFont"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTGlyphInfoRef",
          "text": "CTGlyphInfo"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoCreateWithGlyph(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTGlyphInfoCreateWithGlyph"
        }
      ],
      "role": "symbol",
      "title": "CTGlyphInfoCreateWithGlyph(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctglyphinfocreatewithglyph(_:_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoCreateWithGlyphName(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates an immutable glyph info object with a glyph name.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTGlyphInfoCreateWithGlyphName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontRef",
          "text": "CTFont"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTGlyphInfoRef",
          "text": "CTGlyphInfo"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoCreateWithGlyphName(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTGlyphInfoCreateWithGlyphName"
        }
      ],
      "role": "symbol",
      "title": "CTGlyphInfoCreateWithGlyphName(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctglyphinfocreatewithglyphname(_:_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoGetCharacterCollection(_:)": {
      "abstract": [
        {
          "text": "Gets the character collection for a glyph info object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTGlyphInfoGetCharacterCollection"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTGlyphInfoRef",
          "text": "CTGlyphInfo"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTCharacterCollection",
          "text": "CTCharacterCollection"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoGetCharacterCollection(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTGlyphInfoGetCharacterCollection"
        }
      ],
      "role": "symbol",
      "title": "CTGlyphInfoGetCharacterCollection(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctglyphinfogetcharactercollection(_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoGetCharacterIdentifier(_:)": {
      "abstract": [
        {
          "text": "Gets the character identifier for a glyph info object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTGlyphInfoGetCharacterIdentifier"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTGlyphInfoRef",
          "text": "CTGlyphInfo"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGFontIndex",
          "text": "CGFontIndex"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoGetCharacterIdentifier(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTGlyphInfoGetCharacterIdentifier"
        }
      ],
      "role": "symbol",
      "title": "CTGlyphInfoGetCharacterIdentifier(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctglyphinfogetcharacteridentifier(_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoGetGlyph(_:)": {
      "abstract": [
        {
          "text": "Retrieves the glyph for a glyph info, if that object exists.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTGlyphInfoGetGlyph"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTGlyphInfoRef",
          "text": "CTGlyphInfo"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGGlyph",
          "text": "CGGlyph"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoGetGlyph(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTGlyphInfoGetGlyph"
        }
      ],
      "role": "symbol",
      "title": "CTGlyphInfoGetGlyph(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctglyphinfogetglyph(_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoGetGlyphName(_:)": {
      "abstract": [
        {
          "text": "Retrieves the glyph name for a glyph info object, if that object exists.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTGlyphInfoGetGlyphName"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTGlyphInfoRef",
          "text": "CTGlyphInfo"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoGetGlyphName(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTGlyphInfoGetGlyphName"
        }
      ],
      "role": "symbol",
      "title": "CTGlyphInfoGetGlyphName(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctglyphinfogetglyphname(_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoGetTypeID()": {
      "abstract": [
        {
          "text": "Returns the Core Foundation type identifier of the glyph info object",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTGlyphInfoGetTypeID"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoGetTypeID()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTGlyphInfoGetTypeID"
        }
      ],
      "role": "symbol",
      "title": "CTGlyphInfoGetTypeID()",
      "type": "topic",
      "url": "/documentation/coretext/ctglyphinfogettypeid()"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLine": {
      "abstract": [
        {
          "text": "A line of text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTLine"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTLine"
        }
      ],
      "role": "symbol",
      "title": "CTLine",
      "type": "topic",
      "url": "/documentation/coretext/ctline"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyle": {
      "abstract": [
        {
          "text": "Paragraph or ruler attributes in an attributed string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTParagraphStyle"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTParagraphStyle"
        }
      ],
      "role": "symbol",
      "title": "CTParagraphStyle",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstyle"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRun": {
      "abstract": [
        {
          "text": "A glyph run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRun"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRun",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRun"
        }
      ],
      "role": "symbol",
      "title": "CTRun",
      "type": "topic",
      "url": "/documentation/coretext/ctrun"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRunDelegate": {
      "abstract": [
        {
          "text": "A run delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRunDelegate"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRunDelegate"
        }
      ],
      "role": "symbol",
      "title": "CTRunDelegate",
      "type": "topic",
      "url": "/documentation/coretext/ctrundelegate"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTTextTab": {
      "abstract": [
        {
          "text": "A tab in a paragraph style, storing an alignment type and location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTTextTab"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTTextTab",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTTextTab"
        }
      ],
      "role": "symbol",
      "title": "CTTextTab",
      "type": "topic",
      "url": "/documentation/coretext/cttexttab"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTTypesetter": {
      "abstract": [
        {
          "text": "A typesetter which performs line layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTTypesetter"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTTypesetter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTTypesetter"
        }
      ],
      "role": "symbol",
      "title": "CTTypesetter",
      "type": "topic",
      "url": "/documentation/coretext/cttypesetter"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Opaque-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTFont",
        "doc://com.apple.coretext/documentation/CoreText/CTFontCollection",
        "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptor",
        "doc://com.apple.coretext/documentation/CoreText/CTFrame",
        "doc://com.apple.coretext/documentation/CoreText/CTFramesetter",
        "doc://com.apple.coretext/documentation/CoreText/CTLine",
        "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyle",
        "doc://com.apple.coretext/documentation/CoreText/CTRun",
        "doc://com.apple.coretext/documentation/CoreText/CTRunDelegate",
        "doc://com.apple.coretext/documentation/CoreText/CTTextTab",
        "doc://com.apple.coretext/documentation/CoreText/CTTypesetter"
      ],
      "title": "Opaque Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Getting-the-GlyphInfo-Type",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoGetTypeID()"
      ],
      "title": "Getting the GlyphInfo Type"
    },
    {
      "anchor": "Creating-GlyphInfo-Objects",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoCreateWithGlyphName(_:_:_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoCreateWithGlyph(_:_:_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoCreateWithCharacterIdentifier(_:_:_:)"
      ],
      "title": "Creating GlyphInfo Objects"
    },
    {
      "anchor": "Getting-GlyphInfo-Data",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoGetGlyphName(_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoGetCharacterIdentifier(_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoGetCharacterCollection(_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoGetGlyph(_:)"
      ],
      "title": "Getting GlyphInfo Data"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CTGlyphInfoRef"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTGlyphInfoRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTGlyphInfoRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Getting-the-GlyphInfo-Type",
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoGetTypeID()"
              ],
              "title": "Getting the GlyphInfo Type"
            },
            {
              "anchor": "Creating-GlyphInfo-Objects",
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoCreateWithGlyphName(_:_:_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoCreateWithGlyph(_:_:_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoCreateWithCharacterIdentifier(_:_:_:)"
              ],
              "title": "Creating GlyphInfo Objects"
            },
            {
              "anchor": "Getting-GlyphInfo-Data",
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoGetGlyphName(_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoGetCharacterIdentifier(_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoGetCharacterCollection(_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfoGetGlyph(_:)"
              ],
              "title": "Getting GlyphInfo Data"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTCharacterCollection"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Opaque-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTFont",
                "doc://com.apple.coretext/documentation/CoreText/CTFontCollection",
                "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptor",
                "doc://com.apple.coretext/documentation/CoreText/CTFrame",
                "doc://com.apple.coretext/documentation/CoreText/CTFramesetter",
                "doc://com.apple.coretext/documentation/CoreText/CTLine",
                "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyle",
                "doc://com.apple.coretext/documentation/CoreText/CTRun",
                "doc://com.apple.coretext/documentation/CoreText/CTRunDelegate",
                "doc://com.apple.coretext/documentation/CoreText/CTTextTab",
                "doc://com.apple.coretext/documentation/CoreText/CTTypesetter"
              ],
              "title": "Opaque Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@__CTGlyphInfo",
                    "text": "__CTGlyphInfo"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "CTGlyphInfoRef"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTGlyphInfoGetCharacterIdentifier(_:)/title",
          "value": "CTGlyphInfoGetCharacterIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTGlyphInfoGetCharacterIdentifier(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTGlyphInfoGetCharacterIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTGlyphInfoCreateWithCharacterIdentifier(_:_:_:)/title",
          "value": "CTGlyphInfoCreateWithCharacterIdentifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTGlyphInfoCreateWithCharacterIdentifier(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTGlyphInfoCreateWithCharacterIdentifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTGlyphInfoGetGlyph(_:)/title",
          "value": "CTGlyphInfoGetGlyph"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTGlyphInfoGetGlyph(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTGlyphInfoGetGlyph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLine/title",
          "value": "CTLineRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLine/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFramesetter/title",
          "value": "CTFramesetterRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFramesetter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFramesetterRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFramesetter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFramesetterRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptor/title",
          "value": "CTFontDescriptorRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontDescriptorRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontDescriptorRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTGlyphInfoGetGlyphName(_:)/title",
          "value": "CTGlyphInfoGetGlyphName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTGlyphInfoGetGlyphName(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTGlyphInfoGetGlyphName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTGlyphInfoGetCharacterCollection(_:)/title",
          "value": "CTGlyphInfoGetCharacterCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTGlyphInfoGetCharacterCollection(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTGlyphInfoGetCharacterCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection/title",
          "value": "CTCharacterCollection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCharacterCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTCharacterCollection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTCharacterCollection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRun/title",
          "value": "CTRunRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRun/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRun/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegate/title",
          "value": "CTRunDelegateRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunDelegateRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunDelegateRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTypesetter/title",
          "value": "CTTypesetterRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTypesetter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTTypesetterRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTypesetter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTTypesetterRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextTab/title",
          "value": "CTTextTabRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextTab/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTTextTabRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextTab/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTTextTabRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTGlyphInfoCreateWithGlyph(_:_:_:)/title",
          "value": "CTGlyphInfoCreateWithGlyph"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTGlyphInfoCreateWithGlyph(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTGlyphInfoCreateWithGlyph"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyle/title",
          "value": "CTParagraphStyleRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTParagraphStyleRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTParagraphStyleRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTGlyphInfoGetTypeID()/title",
          "value": "CTGlyphInfoGetTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTGlyphInfoGetTypeID()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTGlyphInfoGetTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFont/title",
          "value": "CTFontRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFont/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFont/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFrame/title",
          "value": "CTFrameRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFrameRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFrame/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFrameRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTGlyphInfo/title",
          "value": "CTGlyphInfoRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTGlyphInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTGlyphInfoRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTGlyphInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTGlyphInfoRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTGlyphInfoCreateWithGlyphName(_:_:_:)/title",
          "value": "CTGlyphInfoCreateWithGlyphName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTGlyphInfoCreateWithGlyphName(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTGlyphInfoCreateWithGlyphName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCollection/title",
          "value": "CTFontCollectionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontCollectionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCollection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontCollectionRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/ctglyphinfo"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/ctglyphinfo"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
