{
  "abstract": [
    {
      "text": "Creates a truncated line from an existing line.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTLineCreateTruncatedLine(_:_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CTLineCreateTruncatedLine",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CTLineCreateTruncatedLine"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CTLineRef",
        "text": "CTLine"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sd",
        "text": "Double"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@CTLineTruncationType",
        "text": "CTLineTruncationType"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CTLineRef",
        "text": "CTLine"
      },
      {
        "kind": "text",
        "text": "?) -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CTLineRef",
        "text": "CTLine"
      },
      {
        "kind": "text",
        "text": "?"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CTLineCreateTruncatedLine"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CTLineCreateTruncatedLine(_:_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CTLineCreateTruncatedLine"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "line"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLine",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CTLineRef",
              "text": "CTLine"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "width"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sd",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sd",
              "text": "Double"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "truncationType"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineTruncationType",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CTLineTruncationType",
              "text": "CTLineTruncationType"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "truncationToken"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLine",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CTLineRef",
              "text": "CTLine"
            },
            {
              "kind": "text",
              "text": "?) -> "
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLine",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CTLineRef",
              "text": "CTLine"
            },
            {
              "kind": "text",
              "text": "?"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The line from which to create a truncated line.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "line"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The width at which truncation begins. The line is truncated if its width is greater than the width passed in this parameter.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "width"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The type of truncation to perform if needed. See ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineTruncationType",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " for possible values.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "truncationType"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "This token is added at the point where truncation took place, to indicate that the line was truncated. Usually, the truncation token is the ellipsis character (",
                  "type": "text"
                },
                {
                  "code": "U+2026",
                  "type": "codeVoice"
                },
                {
                  "text": "). If this parameter is set to ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": ", then no truncation token is used and the line is simply cut off.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "truncationToken"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A reference to a truncated CTLine object if the call was successful; otherwise, ",
              "type": "text"
            },
            {
              "code": "NULL",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The line specified in ",
              "type": "text"
            },
            {
              "code": "truncationToken",
              "type": "codeVoice"
            },
            {
              "text": " should have a width less than the width specified by the ",
              "type": "text"
            },
            {
              "code": "width",
              "type": "codeVoice"
            },
            {
              "text": " parameter. If the width of the line specified in ",
              "type": "text"
            },
            {
              "code": "truncationToken",
              "type": "codeVoice"
            },
            {
              "text": " is greater than ",
              "type": "text"
            },
            {
              "code": "width",
              "type": "codeVoice"
            },
            {
              "text": " and truncation is needed, the function returns ",
              "type": "text"
            },
            {
              "code": "NULL",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLine": {
      "abstract": [
        {
          "text": "A line of text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTLine"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTLine"
        }
      ],
      "role": "symbol",
      "title": "CTLine",
      "type": "topic",
      "url": "/documentation/coretext/ctline"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLineCreateJustifiedLine(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a justified line from an existing line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTLineCreateJustifiedLine"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTLineRef",
          "text": "CTLine"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTLineRef",
          "text": "CTLine"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineCreateJustifiedLine(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTLineCreateJustifiedLine"
        }
      ],
      "role": "symbol",
      "title": "CTLineCreateJustifiedLine(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctlinecreatejustifiedline(_:_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLineCreateTruncatedLine(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a truncated line from an existing line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTLineCreateTruncatedLine"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTLineRef",
          "text": "CTLine"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTLineTruncationType",
          "text": "CTLineTruncationType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTLineRef",
          "text": "CTLine"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTLineRef",
          "text": "CTLine"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineCreateTruncatedLine(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTLineCreateTruncatedLine"
        }
      ],
      "role": "symbol",
      "title": "CTLineCreateTruncatedLine(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctlinecreatetruncatedline(_:_:_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLineCreateWithAttributedString(_:)": {
      "abstract": [
        {
          "text": "Creates a single immutable line object from an attributed string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTLineCreateWithAttributedString"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAttributedStringRef",
          "text": "CFAttributedString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTLineRef",
          "text": "CTLine"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineCreateWithAttributedString(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTLineCreateWithAttributedString"
        }
      ],
      "role": "symbol",
      "title": "CTLineCreateWithAttributedString(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctlinecreatewithattributedstring(_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLineTruncationType": {
      "abstract": [
        {
          "text": "Truncation types required by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineCreateTruncatedLine(_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function to tell the truncation engine which type of truncation is being requested.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTLineTruncationType"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineTruncationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTLineTruncationType"
        }
      ],
      "role": "symbol",
      "title": "CTLineTruncationType",
      "type": "topic",
      "url": "/documentation/coretext/ctlinetruncationtype"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Sd": {
      "abstract": [
        {
          "text": "A double-precision, floating-point value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sd",
      "kind": "symbol",
      "role": "symbol",
      "title": "Double",
      "type": "topic",
      "url": "/documentation/Swift/Double"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-Lines",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTLineCreateWithAttributedString(_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTLineCreateJustifiedLine(_:_:_:)"
      ],
      "title": "Creating Lines"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CTLineCreateTruncatedLine"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineCreateTruncatedLine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-Lines",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTLineCreateWithAttributedString(_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTLineCreateJustifiedLine(_:_:_:)"
              ],
              "title": "Creating Lines"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLine",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CTLineRef",
                    "text": "CTLineRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CTLineCreateTruncatedLine"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLine",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CTLineRef",
                    "text": "CTLineRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "line"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:d",
                    "text": "double"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "width"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineTruncationType",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@CTLineTruncationType",
                    "text": "CTLineTruncationType"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "truncationType"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLine",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CTLineRef",
                    "text": "CTLineRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "truncationToken"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The line from which to create a truncated line.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "line"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The width at which truncation begins. The line is truncated if its width is greater than the width passed in this parameter.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "width"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The type of truncation to perform if needed. See ",
                        "type": "text"
                      },
                      {
                        "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineTruncationType",
                        "isActive": true,
                        "type": "reference"
                      },
                      {
                        "text": " for possible values.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "truncationType"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "This token is added at the point where truncation took place, to indicate that the line was truncated. Usually, the truncation token is the ellipsis character (",
                        "type": "text"
                      },
                      {
                        "code": "U+2026",
                        "type": "codeVoice"
                      },
                      {
                        "text": "). If this parameter is set to ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": ", then no truncation token is used and the line is simply cut off.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "truncationToken"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A reference to a truncated CTLine object if the call was successful; otherwise, ",
                    "type": "text"
                  },
                  {
                    "code": "NULL",
                    "type": "codeVoice"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineTruncationType/title",
          "value": "CTLineTruncationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineTruncationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineTruncationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineTruncationType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineTruncationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineCreateJustifiedLine(_:_:_:)/title",
          "value": "CTLineCreateJustifiedLine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineCreateJustifiedLine(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineCreateJustifiedLine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLine/title",
          "value": "CTLineRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLine/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineCreateTruncatedLine(_:_:_:_:)/title",
          "value": "CTLineCreateTruncatedLine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineCreateTruncatedLine(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineCreateTruncatedLine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineCreateWithAttributedString(_:)/title",
          "value": "CTLineCreateWithAttributedString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineCreateWithAttributedString(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineCreateWithAttributedString"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/ctlinecreatetruncatedline(_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/ctlinecreatetruncatedline(_:_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
