{
  "abstract": [
    {
      "text": "A line of text.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTLine"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@T@CTLineRef",
    "fragments": [
      {
        "kind": "keyword",
        "text": "class"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CTLine"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CTLine"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Class",
    "symbolKind": "class",
    "title": "CTLine"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "class"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CTLine"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A ",
              "type": "text"
            },
            {
              "code": "CTLine",
              "type": "codeVoice"
            },
            {
              "text": " object contains an array of glyph runs. Line objects are created by the typesetter during a framesetting operation and can draw themselves directly into a graphics context.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFont": {
      "abstract": [
        {
          "text": "A font object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFont"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFont",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFont"
        }
      ],
      "role": "symbol",
      "title": "CTFont",
      "type": "topic",
      "url": "/documentation/coretext/ctfont"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontCollection": {
      "abstract": [
        {
          "text": "A font collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontCollection"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontCollection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontCollection"
        }
      ],
      "role": "symbol",
      "title": "CTFontCollection",
      "type": "topic",
      "url": "/documentation/coretext/ctfontcollection"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptor": {
      "abstract": [
        {
          "text": "A font descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontDescriptor"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontDescriptor"
        }
      ],
      "role": "symbol",
      "title": "CTFontDescriptor",
      "type": "topic",
      "url": "/documentation/coretext/ctfontdescriptor"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFrame": {
      "abstract": [
        {
          "text": "A frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFrame"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFrame",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFrame"
        }
      ],
      "role": "symbol",
      "title": "CTFrame",
      "type": "topic",
      "url": "/documentation/coretext/ctframe"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFramesetter": {
      "abstract": [
        {
          "text": "Generate text frames.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFramesetter"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFramesetter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFramesetter"
        }
      ],
      "role": "symbol",
      "title": "CTFramesetter",
      "type": "topic",
      "url": "/documentation/coretext/ctframesetter"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfo": {
      "abstract": [
        {
          "text": "Override a font’s specified mapping from Unicode to the glyph ID.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTGlyphInfo"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfo",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTGlyphInfo"
        }
      ],
      "role": "symbol",
      "title": "CTGlyphInfo",
      "type": "topic",
      "url": "/documentation/coretext/ctglyphinfo"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLine": {
      "abstract": [
        {
          "text": "A line of text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTLine"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTLine"
        }
      ],
      "role": "symbol",
      "title": "CTLine",
      "type": "topic",
      "url": "/documentation/coretext/ctline"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLineCreateJustifiedLine(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a justified line from an existing line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTLineCreateJustifiedLine"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTLineRef",
          "text": "CTLine"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTLineRef",
          "text": "CTLine"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineCreateJustifiedLine(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTLineCreateJustifiedLine"
        }
      ],
      "role": "symbol",
      "title": "CTLineCreateJustifiedLine(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctlinecreatejustifiedline(_:_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLineCreateTruncatedLine(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Creates a truncated line from an existing line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTLineCreateTruncatedLine"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTLineRef",
          "text": "CTLine"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTLineTruncationType",
          "text": "CTLineTruncationType"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTLineRef",
          "text": "CTLine"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTLineRef",
          "text": "CTLine"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineCreateTruncatedLine(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTLineCreateTruncatedLine"
        }
      ],
      "role": "symbol",
      "title": "CTLineCreateTruncatedLine(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctlinecreatetruncatedline(_:_:_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLineCreateWithAttributedString(_:)": {
      "abstract": [
        {
          "text": "Creates a single immutable line object from an attributed string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTLineCreateWithAttributedString"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFAttributedStringRef",
          "text": "CFAttributedString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTLineRef",
          "text": "CTLine"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineCreateWithAttributedString(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTLineCreateWithAttributedString"
        }
      ],
      "role": "symbol",
      "title": "CTLineCreateWithAttributedString(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctlinecreatewithattributedstring(_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLineDraw(_:_:)": {
      "abstract": [
        {
          "text": "Draws a complete line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTLineDraw"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTLineRef",
          "text": "CTLine"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGContextRef",
          "text": "CGContext"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineDraw(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTLineDraw"
        }
      ],
      "role": "symbol",
      "title": "CTLineDraw(_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctlinedraw(_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLineEnumerateCaretOffsets(_:_:)": {
      "abstract": [
        {
          "text": "Enumerates caret offsets for characters in a line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTLineEnumerateCaretOffsets"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTLineRef",
          "text": "CTLine"
        },
        {
          "kind": "text",
          "text": ", ("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sb",
          "text": "Bool"
        },
        {
          "kind": "text",
          "text": ">) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s4Voida",
          "text": "Void"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineEnumerateCaretOffsets(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTLineEnumerateCaretOffsets"
        }
      ],
      "role": "symbol",
      "title": "CTLineEnumerateCaretOffsets(_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctlineenumeratecaretoffsets(_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLineGetGlyphCount(_:)": {
      "abstract": [
        {
          "text": "Returns the total glyph count for the line object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTLineGetGlyphCount"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTLineRef",
          "text": "CTLine"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineGetGlyphCount(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTLineGetGlyphCount"
        }
      ],
      "role": "symbol",
      "title": "CTLineGetGlyphCount(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctlinegetglyphcount(_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLineGetGlyphRuns(_:)": {
      "abstract": [
        {
          "text": "Returns the array of glyph runs that make up the line object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTLineGetGlyphRuns"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTLineRef",
          "text": "CTLine"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFArrayRef",
          "text": "CFArray"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineGetGlyphRuns(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTLineGetGlyphRuns"
        }
      ],
      "role": "symbol",
      "title": "CTLineGetGlyphRuns(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctlinegetglyphruns(_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLineGetImageBounds(_:_:)": {
      "abstract": [
        {
          "text": "Calculates the image bounds for a line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTLineGetImageBounds"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTLineRef",
          "text": "CTLine"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGContextRef",
          "text": "CGContext"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGRect",
          "text": "CGRect"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineGetImageBounds(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTLineGetImageBounds"
        }
      ],
      "role": "symbol",
      "title": "CTLineGetImageBounds(_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctlinegetimagebounds(_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLineGetOffsetForStringIndex(_:_:_:)": {
      "abstract": [
        {
          "text": "Determines the graphical offset or offsets for a string index.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTLineGetOffsetForStringIndex"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTLineRef",
          "text": "CTLine"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineGetOffsetForStringIndex(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTLineGetOffsetForStringIndex"
        }
      ],
      "role": "symbol",
      "title": "CTLineGetOffsetForStringIndex(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctlinegetoffsetforstringindex(_:_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLineGetPenOffsetForFlush(_:_:_:)": {
      "abstract": [
        {
          "text": "Gets the pen offset required to draw flush text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTLineGetPenOffsetForFlush"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTLineRef",
          "text": "CTLine"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineGetPenOffsetForFlush(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTLineGetPenOffsetForFlush"
        }
      ],
      "role": "symbol",
      "title": "CTLineGetPenOffsetForFlush(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctlinegetpenoffsetforflush(_:_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLineGetStringIndexForPosition(_:_:)": {
      "abstract": [
        {
          "text": "Performs hit testing.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTLineGetStringIndexForPosition"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTLineRef",
          "text": "CTLine"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineGetStringIndexForPosition(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTLineGetStringIndexForPosition"
        }
      ],
      "role": "symbol",
      "title": "CTLineGetStringIndexForPosition(_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctlinegetstringindexforposition(_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLineGetStringRange(_:)": {
      "abstract": [
        {
          "text": "Gets the range of characters that originally spawned the glyphs in the line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTLineGetStringRange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTLineRef",
          "text": "CTLine"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CFRange",
          "text": "CFRange"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineGetStringRange(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTLineGetStringRange"
        }
      ],
      "role": "symbol",
      "title": "CTLineGetStringRange(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctlinegetstringrange(_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLineGetTrailingWhitespaceWidth(_:)": {
      "abstract": [
        {
          "text": "Returns the trailing whitespace width for a line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTLineGetTrailingWhitespaceWidth"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTLineRef",
          "text": "CTLine"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineGetTrailingWhitespaceWidth(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTLineGetTrailingWhitespaceWidth"
        }
      ],
      "role": "symbol",
      "title": "CTLineGetTrailingWhitespaceWidth(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctlinegettrailingwhitespacewidth(_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLineGetTypeID()": {
      "abstract": [
        {
          "text": "Returns the Core Foundation type identifier of the line object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTLineGetTypeID"
        },
        {
          "kind": "text",
          "text": "() -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeID",
          "text": "CFTypeID"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineGetTypeID()",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTLineGetTypeID"
        }
      ],
      "role": "symbol",
      "title": "CTLineGetTypeID()",
      "type": "topic",
      "url": "/documentation/coretext/ctlinegettypeid()"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLineGetTypographicBounds(_:_:_:_:)": {
      "abstract": [
        {
          "text": "Calculates the typographic bounds of a line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTLineGetTypographicBounds"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTLineRef",
          "text": "CTLine"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ">?, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:14CoreFoundation7CGFloatV",
          "text": "CGFloat"
        },
        {
          "kind": "text",
          "text": ">?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineGetTypographicBounds(_:_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTLineGetTypographicBounds"
        }
      ],
      "role": "symbol",
      "title": "CTLineGetTypographicBounds(_:_:_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctlinegettypographicbounds(_:_:_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLineTruncationType": {
      "abstract": [
        {
          "text": "Truncation types required by the ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineCreateTruncatedLine(_:_:_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": " function to tell the truncation engine which type of truncation is being requested.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTLineTruncationType"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineTruncationType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTLineTruncationType"
        }
      ],
      "role": "symbol",
      "title": "CTLineTruncationType",
      "type": "topic",
      "url": "/documentation/coretext/ctlinetruncationtype"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyle": {
      "abstract": [
        {
          "text": "Paragraph or ruler attributes in an attributed string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTParagraphStyle"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyle",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTParagraphStyle"
        }
      ],
      "role": "symbol",
      "title": "CTParagraphStyle",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstyle"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRun": {
      "abstract": [
        {
          "text": "A glyph run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRun"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRun",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRun"
        }
      ],
      "role": "symbol",
      "title": "CTRun",
      "type": "topic",
      "url": "/documentation/coretext/ctrun"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRunDelegate": {
      "abstract": [
        {
          "text": "A run delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRunDelegate"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRunDelegate"
        }
      ],
      "role": "symbol",
      "title": "CTRunDelegate",
      "type": "topic",
      "url": "/documentation/coretext/ctrundelegate"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTTextTab": {
      "abstract": [
        {
          "text": "A tab in a paragraph style, storing an alignment type and location.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTTextTab"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTTextTab",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTTextTab"
        }
      ],
      "role": "symbol",
      "title": "CTTextTab",
      "type": "topic",
      "url": "/documentation/coretext/cttexttab"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTTypesetter": {
      "abstract": [
        {
          "text": "A typesetter which performs line layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTTypesetter"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTTypesetter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTTypesetter"
        }
      ],
      "role": "symbol",
      "title": "CTTypesetter",
      "type": "topic",
      "url": "/documentation/coretext/cttypesetter"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Opaque-Types",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTFont",
        "doc://com.apple.coretext/documentation/CoreText/CTFontCollection",
        "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptor",
        "doc://com.apple.coretext/documentation/CoreText/CTFrame",
        "doc://com.apple.coretext/documentation/CoreText/CTFramesetter",
        "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfo",
        "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyle",
        "doc://com.apple.coretext/documentation/CoreText/CTRun",
        "doc://com.apple.coretext/documentation/CoreText/CTRunDelegate",
        "doc://com.apple.coretext/documentation/CoreText/CTTextTab",
        "doc://com.apple.coretext/documentation/CoreText/CTTypesetter"
      ],
      "title": "Opaque Types"
    }
  ],
  "topicSections": [
    {
      "anchor": "Creating-Lines",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTLineCreateWithAttributedString(_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTLineCreateTruncatedLine(_:_:_:_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTLineCreateJustifiedLine(_:_:_:)"
      ],
      "title": "Creating Lines"
    },
    {
      "anchor": "Drawing-the-Line",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTLineDraw(_:_:)"
      ],
      "title": "Drawing the Line"
    },
    {
      "anchor": "Getting-Line-Data",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTLineGetGlyphCount(_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTLineGetGlyphRuns(_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTLineGetStringRange(_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTLineGetPenOffsetForFlush(_:_:_:)"
      ],
      "title": "Getting Line Data"
    },
    {
      "anchor": "Measuring-Lines",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTLineGetImageBounds(_:_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTLineGetTypographicBounds(_:_:_:_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTLineGetTrailingWhitespaceWidth(_:)"
      ],
      "title": "Measuring Lines"
    },
    {
      "anchor": "Getting-Line-Positioning",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTLineGetStringIndexForPosition(_:_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTLineGetOffsetForStringIndex(_:_:_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTLineEnumerateCaretOffsets(_:_:)"
      ],
      "title": "Getting Line Positioning"
    },
    {
      "anchor": "Getting-the-Type-Identifier",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTLineGetTypeID()"
      ],
      "title": "Getting the Type Identifier"
    },
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTLineTruncationType"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Type Alias"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CTLineRef"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "typealias"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Creating-Lines",
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTLineCreateWithAttributedString(_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTLineCreateTruncatedLine(_:_:_:_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTLineCreateJustifiedLine(_:_:_:)"
              ],
              "title": "Creating Lines"
            },
            {
              "anchor": "Drawing-the-Line",
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTLineDraw(_:_:)"
              ],
              "title": "Drawing the Line"
            },
            {
              "anchor": "Getting-Line-Data",
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTLineGetGlyphCount(_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTLineGetGlyphRuns(_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTLineGetStringRange(_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTLineGetPenOffsetForFlush(_:_:_:)"
              ],
              "title": "Getting Line Data"
            },
            {
              "anchor": "Measuring-Lines",
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTLineGetImageBounds(_:_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTLineGetTypographicBounds(_:_:_:_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTLineGetTrailingWhitespaceWidth(_:)"
              ],
              "title": "Measuring Lines"
            },
            {
              "anchor": "Getting-Line-Positioning",
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTLineGetStringIndexForPosition(_:_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTLineGetOffsetForStringIndex(_:_:_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTLineEnumerateCaretOffsets(_:_:)"
              ],
              "title": "Getting Line Positioning"
            },
            {
              "anchor": "Getting-the-Type-Identifier",
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTLineGetTypeID()"
              ],
              "title": "Getting the Type Identifier"
            },
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTLineTruncationType"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Opaque-Types",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTFont",
                "doc://com.apple.coretext/documentation/CoreText/CTFontCollection",
                "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptor",
                "doc://com.apple.coretext/documentation/CoreText/CTFrame",
                "doc://com.apple.coretext/documentation/CoreText/CTFramesetter",
                "doc://com.apple.coretext/documentation/CoreText/CTGlyphInfo",
                "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyle",
                "doc://com.apple.coretext/documentation/CoreText/CTRun",
                "doc://com.apple.coretext/documentation/CoreText/CTRunDelegate",
                "doc://com.apple.coretext/documentation/CoreText/CTTextTab",
                "doc://com.apple.coretext/documentation/CoreText/CTTypesetter"
              ],
              "title": "Opaque Types"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@S@__CTLine",
                    "text": "__CTLine"
                  },
                  {
                    "kind": "text",
                    "text": " * "
                  },
                  {
                    "kind": "identifier",
                    "text": "CTLineRef"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFont/title",
          "value": "CTFontRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFont/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFont/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineGetGlyphRuns(_:)/title",
          "value": "CTLineGetGlyphRuns"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineGetGlyphRuns(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineGetGlyphRuns"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineGetOffsetForStringIndex(_:_:_:)/title",
          "value": "CTLineGetOffsetForStringIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineGetOffsetForStringIndex(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineGetOffsetForStringIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineEnumerateCaretOffsets(_:_:)/title",
          "value": "CTLineEnumerateCaretOffsets"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineEnumerateCaretOffsets(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineEnumerateCaretOffsets"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineDraw(_:_:)/title",
          "value": "CTLineDraw"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineDraw(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineDraw"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineGetTypeID()/title",
          "value": "CTLineGetTypeID"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineGetTypeID()/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineGetTypeID"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTGlyphInfo/title",
          "value": "CTGlyphInfoRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTGlyphInfo/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTGlyphInfoRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTGlyphInfo/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTGlyphInfoRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineGetStringIndexForPosition(_:_:)/title",
          "value": "CTLineGetStringIndexForPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineGetStringIndexForPosition(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineGetStringIndexForPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineGetGlyphCount(_:)/title",
          "value": "CTLineGetGlyphCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineGetGlyphCount(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineGetGlyphCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineGetTrailingWhitespaceWidth(_:)/title",
          "value": "CTLineGetTrailingWhitespaceWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineGetTrailingWhitespaceWidth(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineGetTrailingWhitespaceWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLine/title",
          "value": "CTLineRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLine/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFrame/title",
          "value": "CTFrameRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFrame/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFrameRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFrame/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFrameRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineCreateJustifiedLine(_:_:_:)/title",
          "value": "CTLineCreateJustifiedLine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineCreateJustifiedLine(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineCreateJustifiedLine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineGetStringRange(_:)/title",
          "value": "CTLineGetStringRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineGetStringRange(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineGetStringRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineCreateWithAttributedString(_:)/title",
          "value": "CTLineCreateWithAttributedString"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineCreateWithAttributedString(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineCreateWithAttributedString"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineGetPenOffsetForFlush(_:_:_:)/title",
          "value": "CTLineGetPenOffsetForFlush"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineGetPenOffsetForFlush(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineGetPenOffsetForFlush"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptor/title",
          "value": "CTFontDescriptorRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontDescriptorRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontDescriptorRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCollection/title",
          "value": "CTFontCollectionRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCollection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontCollectionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCollection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontCollectionRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyle/title",
          "value": "CTParagraphStyleRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyle/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTParagraphStyleRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyle/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTParagraphStyleRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextTab/title",
          "value": "CTTextTabRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextTab/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTTextTabRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextTab/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTTextTabRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineGetTypographicBounds(_:_:_:_:)/title",
          "value": "CTLineGetTypographicBounds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineGetTypographicBounds(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineGetTypographicBounds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineGetImageBounds(_:_:)/title",
          "value": "CTLineGetImageBounds"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineGetImageBounds(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineGetImageBounds"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTypesetter/title",
          "value": "CTTypesetterRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTypesetter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTTypesetterRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTypesetter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTTypesetterRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineTruncationType/title",
          "value": "CTLineTruncationType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineTruncationType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineTruncationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineTruncationType/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineTruncationType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFramesetter/title",
          "value": "CTFramesetterRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFramesetter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFramesetterRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFramesetter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFramesetterRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRun/title",
          "value": "CTRunRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRun/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRun/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineCreateTruncatedLine(_:_:_:_:)/title",
          "value": "CTLineCreateTruncatedLine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineCreateTruncatedLine(_:_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineCreateTruncatedLine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegate/title",
          "value": "CTRunDelegateRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunDelegateRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunDelegateRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/ctline"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/ctline"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
