{
  "abstract": [
    {
      "text": "Constants used to query and modify a paragraph style object.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CTParagraphStyleSpecifier",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CTParagraphStyleSpecifier"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CTParagraphStyleSpecifier"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CTParagraphStyleSpecifier"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CTParagraphStyleSpecifier"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Each specifier has a type and a default value associated with it. The type must always be observed when setting or fetching the value from the ",
              "type": "text"
            },
            {
              "code": "CTParagraphStyle",
              "type": "codeVoice"
            },
            {
              "text": " object. In addition, some specifiers affect the behavior of both the framesetter and the typesetter, and others affect the behavior of only the framesetter, as noted in the constant descriptions.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLineBreakMode": {
      "abstract": [
        {
          "text": "These constants specify what happens when a line is too long for its frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTLineBreakMode"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineBreakMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTLineBreakMode"
        }
      ],
      "role": "symbol",
      "title": "CTLineBreakMode",
      "type": "topic",
      "url": "/documentation/coretext/ctlinebreakmode"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier": {
      "abstract": [
        {
          "text": "Constants used to query and modify a paragraph style object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTParagraphStyleSpecifier"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTParagraphStyleSpecifier"
        }
      ],
      "role": "symbol",
      "title": "CTParagraphStyleSpecifier",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstylespecifier"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/alignment": {
      "abstract": [
        {
          "text": "The text alignment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "alignment"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/alignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTParagraphStyleSpecifierAlignment"
        }
      ],
      "role": "symbol",
      "title": "CTParagraphStyleSpecifier.alignment",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstylespecifier/alignment"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/baseWritingDirection": {
      "abstract": [
        {
          "text": "The base writing direction of the lines.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "baseWritingDirection"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/baseWritingDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTParagraphStyleSpecifierBaseWritingDirection"
        }
      ],
      "role": "symbol",
      "title": "CTParagraphStyleSpecifier.baseWritingDirection",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstylespecifier/basewritingdirection"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/count": {
      "abstract": [
        {
          "text": "The number of style specifiers.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "count"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/count",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTParagraphStyleSpecifierCount"
        }
      ],
      "role": "symbol",
      "title": "CTParagraphStyleSpecifier.count",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstylespecifier/count"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/defaultTabInterval": {
      "abstract": [
        {
          "text": "The document-wide default tab interval.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "defaultTabInterval"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/defaultTabInterval",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTParagraphStyleSpecifierDefaultTabInterval"
        }
      ],
      "role": "symbol",
      "title": "CTParagraphStyleSpecifier.defaultTabInterval",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstylespecifier/defaulttabinterval"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/firstLineHeadIndent": {
      "abstract": [
        {
          "text": "The distance, in points, from the leading margin of a frame to the beginning of the paragraph’s first line.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "firstLineHeadIndent"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/firstLineHeadIndent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTParagraphStyleSpecifierFirstLineHeadIndent"
        }
      ],
      "role": "symbol",
      "title": "CTParagraphStyleSpecifier.firstLineHeadIndent",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstylespecifier/firstlineheadindent"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/headIndent": {
      "abstract": [
        {
          "text": "The distance, in points, from the leading margin of a text container to the beginning of lines other than the first.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "headIndent"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/headIndent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTParagraphStyleSpecifierHeadIndent"
        }
      ],
      "role": "symbol",
      "title": "CTParagraphStyleSpecifier.headIndent",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstylespecifier/headindent"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt32V",
          "text": "UInt32"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstylespecifier/init(rawvalue:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/lineBoundsOptions": {
      "abstract": [
        {
          "text": "Options that control the alignment of the line edges with the leading and trailing margins.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineBoundsOptions"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/lineBoundsOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTParagraphStyleSpecifierLineBoundsOptions"
        }
      ],
      "role": "symbol",
      "title": "CTParagraphStyleSpecifier.lineBoundsOptions",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstylespecifier/lineboundsoptions"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/lineBreakMode": {
      "abstract": [
        {
          "text": "The mode that should be used to break lines when laying out the paragraph’s text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineBreakMode"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/lineBreakMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTParagraphStyleSpecifierLineBreakMode"
        }
      ],
      "role": "symbol",
      "title": "CTParagraphStyleSpecifier.lineBreakMode",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstylespecifier/linebreakmode"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/lineHeightMultiple": {
      "abstract": [
        {
          "text": "The line height multiple.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineHeightMultiple"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/lineHeightMultiple",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTParagraphStyleSpecifierLineHeightMultiple"
        }
      ],
      "role": "symbol",
      "title": "CTParagraphStyleSpecifier.lineHeightMultiple",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstylespecifier/lineheightmultiple"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/lineSpacing": {
      "abstract": [
        {
          "text": "The space in points added between lines within the paragraph (commonly known as leading).",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineSpacing"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/lineSpacing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTParagraphStyleSpecifierLineSpacing"
        }
      ],
      "role": "symbol",
      "title": "CTParagraphStyleSpecifier.lineSpacing",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstylespecifier/linespacing"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/lineSpacingAdjustment": {
      "abstract": [
        {
          "text": "The space in points added between lines within the paragraph (commonly known as leading).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineSpacingAdjustment"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/lineSpacingAdjustment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTParagraphStyleSpecifierLineSpacingAdjustment"
        }
      ],
      "role": "symbol",
      "title": "CTParagraphStyleSpecifier.lineSpacingAdjustment",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstylespecifier/linespacingadjustment"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/maximumLineHeight": {
      "abstract": [
        {
          "text": "The maximum height that any line in the frame will occupy, regardless of the font size or size of any attached graphic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumLineHeight"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/maximumLineHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTParagraphStyleSpecifierMaximumLineHeight"
        }
      ],
      "role": "symbol",
      "title": "CTParagraphStyleSpecifier.maximumLineHeight",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstylespecifier/maximumlineheight"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/maximumLineSpacing": {
      "abstract": [
        {
          "text": "The maximum space in points between lines within the paragraph (commonly known as leading).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "maximumLineSpacing"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/maximumLineSpacing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTParagraphStyleSpecifierMaximumLineSpacing"
        }
      ],
      "role": "symbol",
      "title": "CTParagraphStyleSpecifier.maximumLineSpacing",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstylespecifier/maximumlinespacing"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/minimumLineHeight": {
      "abstract": [
        {
          "text": "The minimum height that any line in the frame will occupy, regardless of the font size or size of any attached graphic.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minimumLineHeight"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/minimumLineHeight",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTParagraphStyleSpecifierMinimumLineHeight"
        }
      ],
      "role": "symbol",
      "title": "CTParagraphStyleSpecifier.minimumLineHeight",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstylespecifier/minimumlineheight"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/minimumLineSpacing": {
      "abstract": [
        {
          "text": "The minimum space in points between lines within the paragraph (commonly known as leading).",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "minimumLineSpacing"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/minimumLineSpacing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTParagraphStyleSpecifierMinimumLineSpacing"
        }
      ],
      "role": "symbol",
      "title": "CTParagraphStyleSpecifier.minimumLineSpacing",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstylespecifier/minimumlinespacing"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/paragraphSpacing": {
      "abstract": [
        {
          "text": "The space added at the end of the paragraph to separate it from the following paragraph.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paragraphSpacing"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/paragraphSpacing",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTParagraphStyleSpecifierParagraphSpacing"
        }
      ],
      "role": "symbol",
      "title": "CTParagraphStyleSpecifier.paragraphSpacing",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstylespecifier/paragraphspacing"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/paragraphSpacingBefore": {
      "abstract": [
        {
          "text": "The distance between the paragraph’s top and the beginning of its text content.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "paragraphSpacingBefore"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/paragraphSpacingBefore",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTParagraphStyleSpecifierParagraphSpacingBefore"
        }
      ],
      "role": "symbol",
      "title": "CTParagraphStyleSpecifier.paragraphSpacingBefore",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstylespecifier/paragraphspacingbefore"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/tabStops": {
      "abstract": [
        {
          "text": "The text tab objects, sorted by location, that define the tab stops for the paragraph style.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tabStops"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/tabStops",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTParagraphStyleSpecifierTabStops"
        }
      ],
      "role": "symbol",
      "title": "CTParagraphStyleSpecifier.tabStops",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstylespecifier/tabstops"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/tailIndent": {
      "abstract": [
        {
          "text": "The distance, in points, from the margin of a frame to the end of lines.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "tailIndent"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/tailIndent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTParagraphStyleSpecifierTailIndent"
        }
      ],
      "role": "symbol",
      "title": "CTParagraphStyleSpecifier.tailIndent",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstylespecifier/tailindent"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment": {
      "abstract": [
        {
          "text": "Constants that specify text alignment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTTextAlignment"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTTextAlignment"
        }
      ],
      "role": "symbol",
      "title": "CTTextAlignment",
      "type": "topic",
      "url": "/documentation/coretext/cttextalignment"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTWritingDirection": {
      "abstract": [
        {
          "text": "These constants specify the writing direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTWritingDirection"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTWritingDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTWritingDirection"
        }
      ],
      "role": "symbol",
      "title": "CTWritingDirection",
      "type": "topic",
      "url": "/documentation/coretext/ctwritingdirection"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment",
        "doc://com.apple.coretext/documentation/CoreText/CTLineBreakMode",
        "doc://com.apple.coretext/documentation/CoreText/CTWritingDirection"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/alignment",
        "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/firstLineHeadIndent",
        "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/headIndent",
        "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/tailIndent",
        "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/tabStops",
        "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/defaultTabInterval",
        "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/lineBreakMode",
        "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/lineHeightMultiple",
        "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/maximumLineHeight",
        "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/minimumLineHeight",
        "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/lineSpacing",
        "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/paragraphSpacing",
        "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/paragraphSpacingBefore",
        "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/baseWritingDirection",
        "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/maximumLineSpacing",
        "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/minimumLineSpacing",
        "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/lineSpacingAdjustment",
        "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/count"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Enumeration-Cases",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/lineBoundsOptions"
      ],
      "title": "Enumeration Cases"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CTParagraphStyleSpecifier"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTParagraphStyleSpecifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTParagraphStyleSpecifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/alignment",
                "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/firstLineHeadIndent",
                "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/headIndent",
                "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/tailIndent",
                "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/tabStops",
                "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/defaultTabInterval",
                "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/lineBreakMode",
                "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/lineHeightMultiple",
                "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/maximumLineHeight",
                "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/minimumLineHeight",
                "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/lineSpacing",
                "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/paragraphSpacing",
                "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/paragraphSpacingBefore",
                "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/baseWritingDirection",
                "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/maximumLineSpacing",
                "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/minimumLineSpacing",
                "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/lineSpacingAdjustment",
                "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/count"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Enumeration-Cases",
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier/lineBoundsOptions"
              ],
              "title": "Enumeration Cases"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment",
                "doc://com.apple.coretext/documentation/CoreText/CTLineBreakMode",
                "doc://com.apple.coretext/documentation/CoreText/CTWritingDirection"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CTParagraphStyleSpecifier"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint32_t",
                    "text": "uint32_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1lineHeightMultiple/title",
          "value": "kCTParagraphStyleSpecifierLineHeightMultiple"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1lineHeightMultiple/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTParagraphStyleSpecifierLineHeightMultiple"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextAlignment/title",
          "value": "CTTextAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextAlignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTTextAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextAlignment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTTextAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1lineBreakMode/title",
          "value": "kCTParagraphStyleSpecifierLineBreakMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1lineBreakMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTParagraphStyleSpecifierLineBreakMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1minimumLineHeight/title",
          "value": "kCTParagraphStyleSpecifierMinimumLineHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1minimumLineHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTParagraphStyleSpecifierMinimumLineHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1lineSpacingAdjustment/title",
          "value": "kCTParagraphStyleSpecifierLineSpacingAdjustment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1lineSpacingAdjustment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTParagraphStyleSpecifierLineSpacingAdjustment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1paragraphSpacing/title",
          "value": "kCTParagraphStyleSpecifierParagraphSpacing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1paragraphSpacing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTParagraphStyleSpecifierParagraphSpacing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1lineSpacing/title",
          "value": "kCTParagraphStyleSpecifierLineSpacing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1lineSpacing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTParagraphStyleSpecifierLineSpacing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1tabStops/title",
          "value": "kCTParagraphStyleSpecifierTabStops"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1tabStops/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTParagraphStyleSpecifierTabStops"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBreakMode/title",
          "value": "CTLineBreakMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBreakMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineBreakMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBreakMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineBreakMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1headIndent/title",
          "value": "kCTParagraphStyleSpecifierHeadIndent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1headIndent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTParagraphStyleSpecifierHeadIndent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1alignment/title",
          "value": "kCTParagraphStyleSpecifierAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1alignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTParagraphStyleSpecifierAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1paragraphSpacingBefore/title",
          "value": "kCTParagraphStyleSpecifierParagraphSpacingBefore"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1paragraphSpacingBefore/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTParagraphStyleSpecifierParagraphSpacingBefore"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1minimumLineSpacing/title",
          "value": "kCTParagraphStyleSpecifierMinimumLineSpacing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1minimumLineSpacing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTParagraphStyleSpecifierMinimumLineSpacing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1tailIndent/title",
          "value": "kCTParagraphStyleSpecifierTailIndent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1tailIndent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTParagraphStyleSpecifierTailIndent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier/title",
          "value": "CTParagraphStyleSpecifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTParagraphStyleSpecifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTParagraphStyleSpecifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1maximumLineHeight/title",
          "value": "kCTParagraphStyleSpecifierMaximumLineHeight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1maximumLineHeight/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTParagraphStyleSpecifierMaximumLineHeight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1lineBoundsOptions/title",
          "value": "kCTParagraphStyleSpecifierLineBoundsOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1lineBoundsOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTParagraphStyleSpecifierLineBoundsOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1maximumLineSpacing/title",
          "value": "kCTParagraphStyleSpecifierMaximumLineSpacing"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1maximumLineSpacing/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTParagraphStyleSpecifierMaximumLineSpacing"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1count/title",
          "value": "kCTParagraphStyleSpecifierCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1count/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTParagraphStyleSpecifierCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1firstLineHeadIndent/title",
          "value": "kCTParagraphStyleSpecifierFirstLineHeadIndent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1firstLineHeadIndent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTParagraphStyleSpecifierFirstLineHeadIndent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1defaultTabInterval/title",
          "value": "kCTParagraphStyleSpecifierDefaultTabInterval"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1defaultTabInterval/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTParagraphStyleSpecifierDefaultTabInterval"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTWritingDirection/title",
          "value": "CTWritingDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTWritingDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTWritingDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTWritingDirection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTWritingDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1baseWritingDirection/title",
          "value": "kCTParagraphStyleSpecifierBaseWritingDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier~1baseWritingDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTParagraphStyleSpecifierBaseWritingDirection"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/ctparagraphstylespecifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/ctparagraphstylespecifier"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
