{
  "abstract": [
    {
      "text": "A structure holding pointers to callbacks implemented by the run delegate.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@SA@CTRunDelegateCallbacks",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CTRunDelegateCallbacks"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CTRunDelegateCallbacks"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "CTRunDelegateCallbacks"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CTRunDelegateCallbacks"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "overview",
          "level": 2,
          "text": "Overview",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "You pass in a pointer to this structure when you create a CTRunDelegate object with the ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCreate(_:_:)",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " function. The callbacks defined in this structure are provided by the owner of a run delegate and are used to modify glyph metrics during layout. The values returned by the delegate are applied to each glyph in the run or runs corresponding to the attribute containing that delegate.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "See ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunDelegate",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " for a discussion of the function-pointer types associated with these callbacks.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRunDelegate": {
      "abstract": [
        {
          "text": "A run delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRunDelegate"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunDelegate",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRunDelegate"
        }
      ],
      "role": "symbol",
      "title": "CTRunDelegate",
      "type": "topic",
      "url": "/documentation/coretext/ctrundelegate"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks": {
      "abstract": [
        {
          "text": "A structure holding pointers to callbacks implemented by the run delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRunDelegateCallbacks"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRunDelegateCallbacks"
        }
      ],
      "role": "symbol",
      "title": "CTRunDelegateCallbacks",
      "type": "topic",
      "url": "/documentation/coretext/ctrundelegatecallbacks"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/dealloc": {
      "abstract": [
        {
          "text": "The callback invoked when the retain count of a CTRunDelegate reaches 0 and the CTRunDelegate is deallocated. This callback may be ",
          "type": "text"
        },
        {
          "code": "NULL",
          "type": "codeVoice"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "dealloc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTRunDelegateDeallocateCallback",
          "text": "CTRunDelegateDeallocateCallback"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/dealloc",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "dealloc"
        }
      ],
      "role": "symbol",
      "title": "dealloc",
      "type": "topic",
      "url": "/documentation/coretext/ctrundelegatecallbacks/dealloc"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/getAscent": {
      "abstract": [
        {
          "text": "The callback invoked to request the run delegate to determine and return the typographic ascent of glyphs in the run. This callback may be ",
          "type": "text"
        },
        {
          "code": "NULL",
          "type": "codeVoice"
        },
        {
          "text": ", which is equivalent to a ",
          "type": "text"
        },
        {
          "code": "getAscent",
          "type": "codeVoice"
        },
        {
          "text": " callback that always returns 0.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getAscent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTRunDelegateGetAscentCallback",
          "text": "CTRunDelegateGetAscentCallback"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/getAscent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getAscent"
        }
      ],
      "role": "symbol",
      "title": "getAscent",
      "type": "topic",
      "url": "/documentation/coretext/ctrundelegatecallbacks/getascent"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/getDescent": {
      "abstract": [
        {
          "text": "The callback invoked to request the run delegate to determine and return the typographic descent of glyphs in the run. This callback may be ",
          "type": "text"
        },
        {
          "code": "NULL",
          "type": "codeVoice"
        },
        {
          "text": ", which is equivalent to a ",
          "type": "text"
        },
        {
          "code": "getDescent",
          "type": "codeVoice"
        },
        {
          "text": " callback that always returns 0.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getDescent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTRunDelegateGetDescentCallback",
          "text": "CTRunDelegateGetDescentCallback"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/getDescent",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getDescent"
        }
      ],
      "role": "symbol",
      "title": "getDescent",
      "type": "topic",
      "url": "/documentation/coretext/ctrundelegatecallbacks/getdescent"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/getWidth": {
      "abstract": [
        {
          "text": "The callback invoked to request the run delegate to determine and return the typographic width of glyphs in the run. This callback may be ",
          "type": "text"
        },
        {
          "code": "NULL",
          "type": "codeVoice"
        },
        {
          "text": ", which is equivalent to a ",
          "type": "text"
        },
        {
          "code": "getWidth",
          "type": "codeVoice"
        },
        {
          "text": " callback that always returns 0.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "getWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTRunDelegateGetWidthCallback",
          "text": "CTRunDelegateGetWidthCallback"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/getWidth",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "getWidth"
        }
      ],
      "role": "symbol",
      "title": "getWidth",
      "type": "topic",
      "url": "/documentation/coretext/ctrundelegatecallbacks/getwidth"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/init(version:dealloc:getAscent:getDescent:getWidth:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "dealloc"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTRunDelegateDeallocateCallback",
          "text": "CTRunDelegateDeallocateCallback"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "getAscent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTRunDelegateGetAscentCallback",
          "text": "CTRunDelegateGetAscentCallback"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "getDescent"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTRunDelegateGetDescentCallback",
          "text": "CTRunDelegateGetDescentCallback"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "getWidth"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTRunDelegateGetWidthCallback",
          "text": "CTRunDelegateGetWidthCallback"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/init(version:dealloc:getAscent:getDescent:getWidth:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(version:dealloc:getAscent:getDescent:getWidth:)",
      "type": "topic",
      "url": "/documentation/coretext/ctrundelegatecallbacks/init(version:dealloc:getascent:getdescent:getwidth:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/version": {
      "abstract": [
        {
          "text": "The version number of the callbacks being passed in as a parameter to ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCreate(_:_:)",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ". The initial version is ",
          "type": "text"
        },
        {
          "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTRunDelegateVersion1",
          "isActive": true,
          "type": "reference"
        },
        {
          "text": ".",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "version"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/version",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "version"
        }
      ],
      "role": "symbol",
      "title": "version",
      "type": "topic",
      "url": "/documentation/coretext/ctrundelegatecallbacks/version"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCreate(_:_:)": {
      "abstract": [
        {
          "text": "Creates an immutable instance of a run delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRunDelegateCreate"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CTRunDelegateCallbacks",
          "text": "CTRunDelegateCallbacks"
        },
        {
          "kind": "text",
          "text": ">, "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sv",
          "text": "UnsafeMutableRawPointer"
        },
        {
          "kind": "text",
          "text": "?) -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTRunDelegateRef",
          "text": "CTRunDelegate"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCreate(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRunDelegateCreate"
        }
      ],
      "role": "symbol",
      "title": "CTRunDelegateCreate(_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctrundelegatecreate(_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTRunDelegateVersion1": {
      "abstract": [
        {
          "text": "Version 1 of the run delegate.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTRunDelegateVersion1"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTRunDelegateVersion1",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTRunDelegateVersion1"
        }
      ],
      "role": "symbol",
      "title": "kCTRunDelegateVersion1",
      "type": "topic",
      "url": "/documentation/coretext/kctrundelegateversion1"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "topicSections": [
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/init(version:dealloc:getAscent:getDescent:getWidth:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/dealloc",
        "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/getAscent",
        "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/getDescent",
        "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/getWidth",
        "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/version"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CTRunDelegateCallbacks"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunDelegateCallbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunDelegateCallbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/dealloc",
                "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/getAscent",
                "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/getDescent",
                "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/getWidth",
                "doc://com.apple.coretext/documentation/CoreText/CTRunDelegateCallbacks/version"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/seeAlsoSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "typedef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " { ... } "
                  },
                  {
                    "kind": "identifier",
                    "text": "CTRunDelegateCallbacks"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateCallbacks~1getWidth/title",
          "value": "getWidth"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateCallbacks~1getWidth/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "getWidth"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateCallbacks~1getDescent/title",
          "value": "getDescent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateCallbacks~1getDescent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "getDescent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateCallbacks~1getAscent/title",
          "value": "getAscent"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateCallbacks~1getAscent/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "getAscent"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegate/title",
          "value": "CTRunDelegateRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegate/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunDelegateRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegate/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunDelegateRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTRunDelegateVersion1/title",
          "value": "kCTRunDelegateVersion1"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTRunDelegateVersion1/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTRunDelegateVersion1"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateCallbacks~1dealloc/title",
          "value": "dealloc"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateCallbacks~1dealloc/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "dealloc"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateCreate(_:_:)/title",
          "value": "CTRunDelegateCreate"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateCreate(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunDelegateCreate"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateCallbacks/title",
          "value": "CTRunDelegateCallbacks"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateCallbacks/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunDelegateCallbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateCallbacks/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunDelegateCallbacks"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateCallbacks~1version/title",
          "value": "version"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunDelegateCallbacks~1version/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "version"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/ctrundelegatecallbacks"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/ctrundelegatecallbacks"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
