{
  "abstract": [
    {
      "text": "Returns the run’s status.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTRunGetStatus(_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CTRunGetStatus",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CTRunGetStatus"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CTRunRef",
        "text": "CTRun"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@E@CTRunStatus",
        "text": "CTRunStatus"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CTRunGetStatus"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CTRunGetStatus(_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CTRunGetStatus"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "run"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRun",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CTRunRef",
              "text": "CTRun"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunStatus",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@E@CTRunStatus",
              "text": "CTRunStatus"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The run for which to return the status.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "run"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The run’s status.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Runs have status that can be used to expedite certain operations. Knowing the direction and ordering of a run’s glyphs can aid in string index analysis, whereas knowing whether the positions reference the identity text matrix can avoid expensive comparisons. This status is provided as a convenience, because this information is not strictly necessary but can be helpful in some circumstances.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRun": {
      "abstract": [
        {
          "text": "A glyph run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRun"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRun",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRun"
        }
      ],
      "role": "symbol",
      "title": "CTRun",
      "type": "topic",
      "url": "/documentation/coretext/ctrun"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRunGetAdvances(_:_:_:)": {
      "abstract": [
        {
          "text": "Copies a range of glyph advances into a user-provided buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRunGetAdvances"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTRunRef",
          "text": "CTRun"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CFRange",
          "text": "CFRange"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunGetAdvances(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRunGetAdvances"
        }
      ],
      "role": "symbol",
      "title": "CTRunGetAdvances(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctrungetadvances(_:_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRunGetAdvancesPtr(_:)": {
      "abstract": [
        {
          "text": "Returns a direct pointer for the glyph advance array stored in the run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRunGetAdvancesPtr"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTRunRef",
          "text": "CTRun"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGSize",
          "text": "CGSize"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunGetAdvancesPtr(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRunGetAdvancesPtr"
        }
      ],
      "role": "symbol",
      "title": "CTRunGetAdvancesPtr(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctrungetadvancesptr(_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRunGetAttributes(_:)": {
      "abstract": [
        {
          "text": "Returns the attribute dictionary that was used to create the glyph run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRunGetAttributes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTRunRef",
          "text": "CTRun"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunGetAttributes(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRunGetAttributes"
        }
      ],
      "role": "symbol",
      "title": "CTRunGetAttributes(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctrungetattributes(_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRunGetGlyphCount(_:)": {
      "abstract": [
        {
          "text": "Gets the glyph count for the run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRunGetGlyphCount"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTRunRef",
          "text": "CTRun"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunGetGlyphCount(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRunGetGlyphCount"
        }
      ],
      "role": "symbol",
      "title": "CTRunGetGlyphCount(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctrungetglyphcount(_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRunGetGlyphs(_:_:_:)": {
      "abstract": [
        {
          "text": "Copies a range of glyphs into a user-provided buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRunGetGlyphs"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTRunRef",
          "text": "CTRun"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CFRange",
          "text": "CFRange"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGGlyph",
          "text": "CGGlyph"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunGetGlyphs(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRunGetGlyphs"
        }
      ],
      "role": "symbol",
      "title": "CTRunGetGlyphs(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctrungetglyphs(_:_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRunGetGlyphsPtr(_:)": {
      "abstract": [
        {
          "text": "Returns a direct pointer for the glyph array stored in the run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRunGetGlyphsPtr"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTRunRef",
          "text": "CTRun"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CGGlyph",
          "text": "CGGlyph"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunGetGlyphsPtr(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRunGetGlyphsPtr"
        }
      ],
      "role": "symbol",
      "title": "CTRunGetGlyphsPtr(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctrungetglyphsptr(_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRunGetPositions(_:_:_:)": {
      "abstract": [
        {
          "text": "Copies a range of glyph positions into a user-provided buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRunGetPositions"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTRunRef",
          "text": "CTRun"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CFRange",
          "text": "CFRange"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunGetPositions(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRunGetPositions"
        }
      ],
      "role": "symbol",
      "title": "CTRunGetPositions(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctrungetpositions(_:_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRunGetPositionsPtr(_:)": {
      "abstract": [
        {
          "text": "Returns a direct pointer for the glyph position array stored in the run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRunGetPositionsPtr"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTRunRef",
          "text": "CTRun"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@S@CGPoint",
          "text": "CGPoint"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunGetPositionsPtr(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRunGetPositionsPtr"
        }
      ],
      "role": "symbol",
      "title": "CTRunGetPositionsPtr(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctrungetpositionsptr(_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRunGetStatus(_:)": {
      "abstract": [
        {
          "text": "Returns the run’s status.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRunGetStatus"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTRunRef",
          "text": "CTRun"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTRunStatus",
          "text": "CTRunStatus"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunGetStatus(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRunGetStatus"
        }
      ],
      "role": "symbol",
      "title": "CTRunGetStatus(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctrungetstatus(_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRunGetStringIndices(_:_:_:)": {
      "abstract": [
        {
          "text": "Copies a range of string indices into a user-provided buffer.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRunGetStringIndices"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTRunRef",
          "text": "CTRun"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CFRange",
          "text": "CFRange"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sp",
          "text": "UnsafeMutablePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        },
        {
          "kind": "text",
          "text": ">)"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunGetStringIndices(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRunGetStringIndices"
        }
      ],
      "role": "symbol",
      "title": "CTRunGetStringIndices(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctrungetstringindices(_:_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRunGetStringIndicesPtr(_:)": {
      "abstract": [
        {
          "text": "Returns a direct pointer for the string indices stored in the run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRunGetStringIndicesPtr"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTRunRef",
          "text": "CTRun"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SP",
          "text": "UnsafePointer"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFIndex",
          "text": "CFIndex"
        },
        {
          "kind": "text",
          "text": ">?"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunGetStringIndicesPtr(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRunGetStringIndicesPtr"
        }
      ],
      "role": "symbol",
      "title": "CTRunGetStringIndicesPtr(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctrungetstringindicesptr(_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRunGetStringRange(_:)": {
      "abstract": [
        {
          "text": "Gets the range of characters that originally spawned the glyphs in the run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRunGetStringRange"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTRunRef",
          "text": "CTRun"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CFRange",
          "text": "CFRange"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunGetStringRange(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRunGetStringRange"
        }
      ],
      "role": "symbol",
      "title": "CTRunGetStringRange(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctrungetstringrange(_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRunStatus": {
      "abstract": [
        {
          "text": "A bitfield that represents the disposition of the run.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRunStatus"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunStatus",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRunStatus"
        }
      ],
      "role": "symbol",
      "title": "CTRunStatus",
      "type": "topic",
      "url": "/documentation/coretext/ctrunstatus"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Getting-Glyph-Run-Data",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTRunGetGlyphCount(_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTRunGetAttributes(_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTRunGetGlyphsPtr(_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTRunGetGlyphs(_:_:_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTRunGetPositionsPtr(_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTRunGetPositions(_:_:_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTRunGetAdvancesPtr(_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTRunGetAdvances(_:_:_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTRunGetStringIndicesPtr(_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTRunGetStringIndices(_:_:_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTRunGetStringRange(_:)"
      ],
      "title": "Getting Glyph Run Data"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CTRunGetStatus"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunGetStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Getting-Glyph-Run-Data",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTRunGetGlyphCount(_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTRunGetAttributes(_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTRunGetGlyphsPtr(_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTRunGetGlyphs(_:_:_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTRunGetPositionsPtr(_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTRunGetPositions(_:_:_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTRunGetAdvancesPtr(_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTRunGetAdvances(_:_:_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTRunGetStringIndicesPtr(_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTRunGetStringIndices(_:_:_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTRunGetStringRange(_:)"
              ],
              "title": "Getting Glyph Run Data"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRunStatus",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@E@CTRunStatus",
                    "text": "CTRunStatus"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CTRunGetStatus"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRun",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CTRunRef",
                    "text": "CTRunRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "run"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The run for which to return the status.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "run"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "The run’s status.",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunGetStringRange(_:)/title",
          "value": "CTRunGetStringRange"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunGetStringRange(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunGetStringRange"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunGetPositionsPtr(_:)/title",
          "value": "CTRunGetPositionsPtr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunGetPositionsPtr(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunGetPositionsPtr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunGetAttributes(_:)/title",
          "value": "CTRunGetAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunGetAttributes(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunGetAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunGetAdvances(_:_:_:)/title",
          "value": "CTRunGetAdvances"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunGetAdvances(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunGetAdvances"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunGetAdvancesPtr(_:)/title",
          "value": "CTRunGetAdvancesPtr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunGetAdvancesPtr(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunGetAdvancesPtr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunGetGlyphCount(_:)/title",
          "value": "CTRunGetGlyphCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunGetGlyphCount(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunGetGlyphCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunGetStringIndicesPtr(_:)/title",
          "value": "CTRunGetStringIndicesPtr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunGetStringIndicesPtr(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunGetStringIndicesPtr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunStatus/title",
          "value": "CTRunStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunStatus/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunStatus/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunGetStatus(_:)/title",
          "value": "CTRunGetStatus"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunGetStatus(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunGetStatus"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunGetGlyphs(_:_:_:)/title",
          "value": "CTRunGetGlyphs"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunGetGlyphs(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunGetGlyphs"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunGetGlyphsPtr(_:)/title",
          "value": "CTRunGetGlyphsPtr"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunGetGlyphsPtr(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunGetGlyphsPtr"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRun/title",
          "value": "CTRunRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRun/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRun/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunGetPositions(_:_:_:)/title",
          "value": "CTRunGetPositions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunGetPositions(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunGetPositions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunGetStringIndices(_:_:_:)/title",
          "value": "CTRunGetStringIndices"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRunGetStringIndices(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRunGetStringIndices"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/ctrungetstatus(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/ctrungetstatus(_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
