{
  "abstract": [
    {
      "text": "Constants that specify how to align the ruby text and the base text relative to each other when they have different lengths.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CTRubyAlignment",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CTRubyAlignment"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CTRubyAlignment"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "8.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.10",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CTRubyAlignment"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CTRubyAlignment"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState": {
      "abstract": [
        {
          "text": "Constants that track the progress of font descriptor matching.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontDescriptorMatchingState"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontDescriptorMatchingState"
        }
      ],
      "role": "symbol",
      "title": "CTFontDescriptorMatchingState",
      "type": "topic",
      "url": "/documentation/coretext/ctfontdescriptormatchingstate"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerAutoActivationSetting": {
      "abstract": [
        {
          "text": "Sets the auto-activation for the specified bundle identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontManagerAutoActivationSetting"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerAutoActivationSetting",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontManagerAutoActivationSetting"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerAutoActivationSetting",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagerautoactivationsetting"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError": {
      "abstract": [
        {
          "text": "Errors that prevent unregistration of fonts for a specified font file URL.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontManagerError"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontManagerError"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerError",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagererror"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontManagerScope": {
      "abstract": [
        {
          "text": "Constants that define the scope for font registration.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontManagerScope"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontManagerScope",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontManagerScope"
        }
      ],
      "role": "symbol",
      "title": "CTFontManagerScope",
      "type": "topic",
      "url": "/documentation/coretext/ctfontmanagerscope"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions": {
      "abstract": [
        {
          "text": "Options for getting the bounds of a line of text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTLineBoundsOptions"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTLineBoundsOptions"
        }
      ],
      "role": "symbol",
      "title": "CTLineBoundsOptions",
      "type": "topic",
      "url": "/documentation/coretext/ctlineboundsoptions"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment": {
      "abstract": [
        {
          "text": "Constants that specify how to align the ruby text and the base text relative to each other when they have different lengths.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRubyAlignment"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRubyAlignment"
        }
      ],
      "role": "symbol",
      "title": "CTRubyAlignment",
      "type": "topic",
      "url": "/documentation/coretext/ctrubyalignment"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/auto": {
      "abstract": [
        {
          "text": "Core Text automatically determines the alignment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "auto"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/auto",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTRubyAlignmentAuto"
        }
      ],
      "role": "symbol",
      "title": "CTRubyAlignment.auto",
      "type": "topic",
      "url": "/documentation/coretext/ctrubyalignment/auto"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/center": {
      "abstract": [
        {
          "text": "Centers the ruby text within the width of the base text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "center"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/center",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTRubyAlignmentCenter"
        }
      ],
      "role": "symbol",
      "title": "CTRubyAlignment.center",
      "type": "topic",
      "url": "/documentation/coretext/ctrubyalignment/center"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/distributeLetter": {
      "abstract": [
        {
          "text": "Distributes the ruby text evenly over the width of the base text, aligning the first and last characters of the ruby text with the first and last characters of the base text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "distributeLetter"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/distributeLetter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTRubyAlignmentDistributeLetter"
        }
      ],
      "role": "symbol",
      "title": "CTRubyAlignment.distributeLetter",
      "type": "topic",
      "url": "/documentation/coretext/ctrubyalignment/distributeletter"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/distributeSpace": {
      "abstract": [
        {
          "text": "Distributes the ruby text evenly over the width of the base text, adding space before the first and after the last character.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "distributeSpace"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/distributeSpace",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTRubyAlignmentDistributeSpace"
        }
      ],
      "role": "symbol",
      "title": "CTRubyAlignment.distributeSpace",
      "type": "topic",
      "url": "/documentation/coretext/ctrubyalignment/distributespace"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/end": {
      "abstract": [
        {
          "text": "Aligns the ruby text with the ending edge of the base text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "end"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/end",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTRubyAlignmentEnd"
        }
      ],
      "role": "symbol",
      "title": "CTRubyAlignment.end",
      "type": "topic",
      "url": "/documentation/coretext/ctrubyalignment/end"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/coretext/ctrubyalignment/init(rawvalue:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/invalid": {
      "abstract": [
        {
          "text": "The alignment is invalid.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "invalid"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/invalid",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTRubyAlignmentInvalid"
        }
      ],
      "role": "symbol",
      "title": "CTRubyAlignment.invalid",
      "type": "topic",
      "url": "/documentation/coretext/ctrubyalignment/invalid"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/lineEdge": {
      "abstract": [
        {
          "text": "Aligns the ruby text to an adjacent line edge.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "lineEdge"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/lineEdge",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTRubyAlignmentLineEdge"
        }
      ],
      "role": "symbol",
      "title": "CTRubyAlignment.lineEdge",
      "type": "topic",
      "url": "/documentation/coretext/ctrubyalignment/lineedge"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/start": {
      "abstract": [
        {
          "text": "Aligns the ruby text with the starting edge of the base text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "start"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/start",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTRubyAlignmentStart"
        }
      ],
      "role": "symbol",
      "title": "CTRubyAlignment.start",
      "type": "topic",
      "url": "/documentation/coretext/ctrubyalignment/start"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRubyOverhang": {
      "abstract": [
        {
          "text": "Constants that specify whether, and on which side, ruby text can overhang adjacent text if it’s wider than the base text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRubyOverhang"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRubyOverhang",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRubyOverhang"
        }
      ],
      "role": "symbol",
      "title": "CTRubyOverhang",
      "type": "topic",
      "url": "/documentation/coretext/ctrubyoverhang"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTRubyPosition": {
      "abstract": [
        {
          "text": "Constants that specify the position of the ruby text relative to to the base text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTRubyPosition"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTRubyPosition",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTRubyPosition"
        }
      ],
      "role": "symbol",
      "title": "CTRubyPosition",
      "type": "topic",
      "url": "/documentation/coretext/ctrubyposition"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Enumerations",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerAutoActivationSetting",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError",
        "doc://com.apple.coretext/documentation/CoreText/CTFontManagerScope",
        "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions",
        "doc://com.apple.coretext/documentation/CoreText/CTRubyOverhang",
        "doc://com.apple.coretext/documentation/CoreText/CTRubyPosition"
      ],
      "title": "Enumerations"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/auto",
        "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/start",
        "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/center",
        "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/end",
        "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/distributeLetter",
        "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/distributeSpace",
        "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/lineEdge",
        "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/invalid"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/init(rawValue:)"
      ],
      "title": "Initializers"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "8.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.10",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CTRubyAlignment"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRubyAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRubyAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/auto",
                "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/start",
                "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/center",
                "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/end",
                "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/distributeLetter",
                "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/distributeSpace",
                "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/lineEdge",
                "doc://com.apple.coretext/documentation/CoreText/CTRubyAlignment/invalid"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Enumerations",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorMatchingState",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerAutoActivationSetting",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerError",
                "doc://com.apple.coretext/documentation/CoreText/CTFontManagerScope",
                "doc://com.apple.coretext/documentation/CoreText/CTLineBoundsOptions",
                "doc://com.apple.coretext/documentation/CoreText/CTRubyOverhang",
                "doc://com.apple.coretext/documentation/CoreText/CTRubyPosition"
              ],
              "title": "Enumerations"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CTRubyAlignment"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment~1invalid/title",
          "value": "kCTRubyAlignmentInvalid"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment~1invalid/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTRubyAlignmentInvalid"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerScope/title",
          "value": "CTFontManagerScope"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerScope/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontManagerScope"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerScope/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontManagerScope"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptorMatchingState/title",
          "value": "CTFontDescriptorMatchingState"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptorMatchingState/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontDescriptorMatchingState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptorMatchingState/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontDescriptorMatchingState"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment/title",
          "value": "CTRubyAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRubyAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRubyAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment~1end/title",
          "value": "kCTRubyAlignmentEnd"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment~1end/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTRubyAlignmentEnd"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment~1auto/title",
          "value": "kCTRubyAlignmentAuto"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment~1auto/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTRubyAlignmentAuto"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment~1center/title",
          "value": "kCTRubyAlignmentCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment~1center/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTRubyAlignmentCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError/title",
          "value": "CTFontManagerError"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontManagerError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerError/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontManagerError"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment~1lineEdge/title",
          "value": "kCTRubyAlignmentLineEdge"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment~1lineEdge/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTRubyAlignmentLineEdge"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment~1distributeLetter/title",
          "value": "kCTRubyAlignmentDistributeLetter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment~1distributeLetter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTRubyAlignmentDistributeLetter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyPosition/title",
          "value": "CTRubyPosition"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyPosition/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRubyPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyPosition/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRubyPosition"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment~1distributeSpace/title",
          "value": "kCTRubyAlignmentDistributeSpace"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment~1distributeSpace/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTRubyAlignmentDistributeSpace"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBoundsOptions/title",
          "value": "CTLineBoundsOptions"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBoundsOptions/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineBoundsOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBoundsOptions/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineBoundsOptions"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment~1start/title",
          "value": "kCTRubyAlignmentStart"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyAlignment~1start/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTRubyAlignmentStart"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerAutoActivationSetting/title",
          "value": "CTFontManagerAutoActivationSetting"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerAutoActivationSetting/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontManagerAutoActivationSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontManagerAutoActivationSetting/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontManagerAutoActivationSetting"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyOverhang/title",
          "value": "CTRubyOverhang"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyOverhang/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRubyOverhang"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTRubyOverhang/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTRubyOverhang"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/ctrubyalignment"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/ctrubyalignment"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
