{
  "abstract": [
    {
      "text": "Constants that specify text alignment.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@E@CTTextAlignment",
    "fragments": [
      {
        "kind": "keyword",
        "text": "enum"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CTTextAlignment"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CTTextAlignment"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Enumeration",
    "symbolKind": "enum",
    "title": "CTTextAlignment"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "enum"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CTTextAlignment"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLineBreakMode": {
      "abstract": [
        {
          "text": "These constants specify what happens when a line is too long for its frame.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTLineBreakMode"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLineBreakMode",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTLineBreakMode"
        }
      ],
      "role": "symbol",
      "title": "CTLineBreakMode",
      "type": "topic",
      "url": "/documentation/coretext/ctlinebreakmode"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier": {
      "abstract": [
        {
          "text": "Constants used to query and modify a paragraph style object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTParagraphStyleSpecifier"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTParagraphStyleSpecifier"
        }
      ],
      "role": "symbol",
      "title": "CTParagraphStyleSpecifier",
      "type": "topic",
      "url": "/documentation/coretext/ctparagraphstylespecifier"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment": {
      "abstract": [
        {
          "text": "Constants that specify text alignment.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTTextAlignment"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTTextAlignment"
        }
      ],
      "role": "symbol",
      "title": "CTTextAlignment",
      "type": "topic",
      "url": "/documentation/coretext/cttextalignment"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/center": {
      "abstract": [
        {
          "text": "Text is visually center-aligned.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "center"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/center",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTTextAlignmentCenter"
        }
      ],
      "role": "symbol",
      "title": "CTTextAlignment.center",
      "type": "topic",
      "url": "/documentation/coretext/cttextalignment/center"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/init(_:)": {
      "abstract": [
        {
          "text": "Converts a UIKit text alignment constant value to the matching constant value that Core Text uses.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@NSTextAlignment",
          "text": "NSTextAlignment"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/init(_:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(_:)",
      "type": "topic",
      "url": "/documentation/coretext/cttextalignment/init(_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/init(rawValue:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "?("
        },
        {
          "kind": "externalParam",
          "text": "rawValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/init(rawValue:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(rawValue:)",
      "type": "topic",
      "url": "/documentation/coretext/cttextalignment/init(rawvalue:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/justified": {
      "abstract": [
        {
          "text": "Text is fully justified.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "justified"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/justified",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTTextAlignmentJustified"
        }
      ],
      "role": "symbol",
      "title": "CTTextAlignment.justified",
      "type": "topic",
      "url": "/documentation/coretext/cttextalignment/justified"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/kCTCenterTextAlignment": {
      "abstract": [
        {
          "text": "Text is visually center-aligned.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTCenterTextAlignment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTTextAlignment",
          "text": "CTTextAlignment"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/kCTCenterTextAlignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTCenterTextAlignment"
        }
      ],
      "role": "symbol",
      "title": "kCTCenterTextAlignment",
      "type": "topic",
      "url": "/documentation/coretext/cttextalignment/kctcentertextalignment"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/kCTJustifiedTextAlignment": {
      "abstract": [
        {
          "text": "Text is fully justified.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTJustifiedTextAlignment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTTextAlignment",
          "text": "CTTextAlignment"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/kCTJustifiedTextAlignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTJustifiedTextAlignment"
        }
      ],
      "role": "symbol",
      "title": "kCTJustifiedTextAlignment",
      "type": "topic",
      "url": "/documentation/coretext/cttextalignment/kctjustifiedtextalignment"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/kCTLeftTextAlignment": {
      "abstract": [
        {
          "text": "Text is visually left-aligned.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTLeftTextAlignment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTTextAlignment",
          "text": "CTTextAlignment"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/kCTLeftTextAlignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTLeftTextAlignment"
        }
      ],
      "role": "symbol",
      "title": "kCTLeftTextAlignment",
      "type": "topic",
      "url": "/documentation/coretext/cttextalignment/kctlefttextalignment"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/kCTNaturalTextAlignment": {
      "abstract": [
        {
          "text": "Text uses the natural alignment of the text’s script.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTNaturalTextAlignment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTTextAlignment",
          "text": "CTTextAlignment"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/kCTNaturalTextAlignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTNaturalTextAlignment"
        }
      ],
      "role": "symbol",
      "title": "kCTNaturalTextAlignment",
      "type": "topic",
      "url": "/documentation/coretext/cttextalignment/kctnaturaltextalignment"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/kCTRightTextAlignment": {
      "abstract": [
        {
          "text": "Text is visually right-aligned.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "static"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTRightTextAlignment"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@E@CTTextAlignment",
          "text": "CTTextAlignment"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/kCTRightTextAlignment",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTRightTextAlignment"
        }
      ],
      "role": "symbol",
      "title": "kCTRightTextAlignment",
      "type": "topic",
      "url": "/documentation/coretext/cttextalignment/kctrighttextalignment"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/left": {
      "abstract": [
        {
          "text": "Text is visually left-aligned.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "left"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/left",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTTextAlignmentLeft"
        }
      ],
      "role": "symbol",
      "title": "CTTextAlignment.left",
      "type": "topic",
      "url": "/documentation/coretext/cttextalignment/left"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/natural": {
      "abstract": [
        {
          "text": "Text uses the natural alignment of the text’s script.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "natural"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/natural",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTTextAlignmentNatural"
        }
      ],
      "role": "symbol",
      "title": "CTTextAlignment.natural",
      "type": "topic",
      "url": "/documentation/coretext/cttextalignment/natural"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/right": {
      "abstract": [
        {
          "text": "Text is visually right-aligned.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "case"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "right"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/right",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTTextAlignmentRight"
        }
      ],
      "role": "symbol",
      "title": "CTTextAlignment.right",
      "type": "topic",
      "url": "/documentation/coretext/cttextalignment/right"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTWritingDirection": {
      "abstract": [
        {
          "text": "These constants specify the writing direction.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTWritingDirection"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTWritingDirection",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTWritingDirection"
        }
      ],
      "role": "symbol",
      "title": "CTWritingDirection",
      "type": "topic",
      "url": "/documentation/coretext/ctwritingdirection"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:SH": {
      "abstract": [
        {
          "text": "A type that can be hashed into a `Hasher` to produce an integer hash value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Hashable"
        },
        {
          "kind": "text",
          "text": " : "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SQ",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SH",
      "kind": "symbol",
      "role": "symbol",
      "title": "Hashable",
      "type": "topic",
      "url": "/documentation/Swift/Hashable"
    },
    "doc://com.externally.resolved.symbol/s:SQ": {
      "abstract": [
        {
          "text": "A type that can be compared for value equality.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Equatable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SQ",
      "kind": "symbol",
      "role": "symbol",
      "title": "Equatable",
      "type": "topic",
      "url": "/documentation/Swift/Equatable"
    },
    "doc://com.externally.resolved.symbol/s:SY": {
      "abstract": [
        {
          "text": "A type that can be converted to and from an associated raw value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "RawRepresentable"
        },
        {
          "kind": "text",
          "text": "<"
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:SY8RawValueQa",
          "text": "RawValue"
        },
        {
          "kind": "text",
          "text": ">"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:SY",
      "kind": "symbol",
      "role": "symbol",
      "title": "RawRepresentable",
      "type": "topic",
      "url": "/documentation/Swift/RawRepresentable"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:SQ",
        "doc://com.externally.resolved.symbol/s:SH",
        "doc://com.externally.resolved.symbol/s:SY",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTLineBreakMode",
        "doc://com.apple.coretext/documentation/CoreText/CTWritingDirection",
        "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier"
      ],
      "title": "Constants"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/left",
        "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/right",
        "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/center",
        "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/justified",
        "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/natural"
      ],
      "title": "Constants"
    },
    {
      "anchor": "Initializers",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/init(_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/init(rawValue:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Deprecated",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/kCTLeftTextAlignment",
        "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/kCTRightTextAlignment",
        "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/kCTCenterTextAlignment",
        "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/kCTJustifiedTextAlignment",
        "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/kCTNaturalTextAlignment"
      ],
      "title": "Deprecated"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CTTextAlignment"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "enum"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTTextAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTTextAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/left",
                "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/right",
                "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/center",
                "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/justified",
                "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/natural"
              ],
              "title": "Constants"
            },
            {
              "anchor": "Deprecated",
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/kCTLeftTextAlignment",
                "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/kCTRightTextAlignment",
                "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/kCTCenterTextAlignment",
                "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/kCTJustifiedTextAlignment",
                "doc://com.apple.coretext/documentation/CoreText/CTTextAlignment/kCTNaturalTextAlignment"
              ],
              "title": "Deprecated"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTLineBreakMode",
                "doc://com.apple.coretext/documentation/CoreText/CTWritingDirection",
                "doc://com.apple.coretext/documentation/CoreText/CTParagraphStyleSpecifier"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "enum"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CTTextAlignment"
                  },
                  {
                    "kind": "text",
                    "text": " : "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@uint8_t",
                    "text": "uint8_t"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextAlignment~1kCTCenterTextAlignment/title",
          "value": "kCTCenterTextAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextAlignment~1kCTCenterTextAlignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTCenterTextAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTWritingDirection/title",
          "value": "CTWritingDirection"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTWritingDirection/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTWritingDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTWritingDirection/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTWritingDirection"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextAlignment~1kCTNaturalTextAlignment/title",
          "value": "kCTNaturalTextAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextAlignment~1kCTNaturalTextAlignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTNaturalTextAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextAlignment~1left/title",
          "value": "kCTTextAlignmentLeft"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextAlignment~1left/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTTextAlignmentLeft"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextAlignment~1kCTJustifiedTextAlignment/title",
          "value": "kCTJustifiedTextAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextAlignment~1kCTJustifiedTextAlignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTJustifiedTextAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextAlignment~1center/title",
          "value": "kCTTextAlignmentCenter"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextAlignment~1center/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTTextAlignmentCenter"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextAlignment~1right/title",
          "value": "kCTTextAlignmentRight"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextAlignment~1right/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTTextAlignmentRight"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextAlignment~1kCTRightTextAlignment/title",
          "value": "kCTRightTextAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextAlignment~1kCTRightTextAlignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTRightTextAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextAlignment/title",
          "value": "CTTextAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextAlignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTTextAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextAlignment/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTTextAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextAlignment~1justified/title",
          "value": "kCTTextAlignmentJustified"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextAlignment~1justified/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTTextAlignmentJustified"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextAlignment~1natural/title",
          "value": "kCTTextAlignmentNatural"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextAlignment~1natural/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTTextAlignmentNatural"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBreakMode/title",
          "value": "CTLineBreakMode"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBreakMode/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineBreakMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLineBreakMode/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineBreakMode"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextAlignment~1kCTLeftTextAlignment/title",
          "value": "kCTLeftTextAlignment"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTextAlignment~1kCTLeftTextAlignment/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTLeftTextAlignment"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier/title",
          "value": "CTParagraphStyleSpecifier"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTParagraphStyleSpecifier"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTParagraphStyleSpecifier/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTParagraphStyleSpecifier"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/cttextalignment"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/cttextalignment"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
