{
  "abstract": [
    {
      "text": "Creates an immutable line from the typesetter at a specified line offset.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/CTTypesetterCreateLineWithOffset(_:_:_:)"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@F@CTTypesetterCreateLineWithOffset",
    "fragments": [
      {
        "kind": "keyword",
        "text": "func"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "CTTypesetterCreateLineWithOffset"
      },
      {
        "kind": "text",
        "text": "("
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CTTypesetterRef",
        "text": "CTTypesetter"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@SA@CFRange",
        "text": "CFRange"
      },
      {
        "kind": "text",
        "text": ", "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Sd",
        "text": "Double"
      },
      {
        "kind": "text",
        "text": ") -> "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CTLineRef",
        "text": "CTLine"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "CTTypesetterCreateLineWithOffset"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Function",
    "symbolKind": "func",
    "title": "CTTypesetterCreateLineWithOffset(_:_:_:)"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "func"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "CTTypesetterCreateLineWithOffset"
            },
            {
              "kind": "text",
              "text": "("
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "typesetter"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/CTTypesetter",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CTTypesetterRef",
              "text": "CTTypesetter"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "stringRange"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@SA@CFRange",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@SA@CFRange",
              "text": "CFRange"
            },
            {
              "kind": "text",
              "text": ", "
            },
            {
              "kind": "externalParam",
              "text": "_"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "internalParam",
              "text": "offset"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Sd",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Sd",
              "text": "Double"
            },
            {
              "kind": "text",
              "text": ") -> "
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLine",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CTLineRef",
              "text": "CTLine"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "kind": "parameters",
      "parameters": [
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The typesetter that creates the line. This parameter is required and cannot be set to ",
                  "type": "text"
                },
                {
                  "code": "NULL",
                  "type": "codeVoice"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "typesetter"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The string range on which the line is based. If the length portion of range is set to ",
                  "type": "text"
                },
                {
                  "code": "0",
                  "type": "codeVoice"
                },
                {
                  "text": ", then the typesetter continues to add glyphs to the line until it runs out of characters in the string. The location and length of the range must be within the bounds of the string, or the call will fail.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "stringRange"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "The line position offset.",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "offset"
        }
      ]
    },
    {
      "content": [
        {
          "anchor": "return-value",
          "level": 2,
          "text": "Return Value",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "A reference to a CTLine object if the call was successful; otherwise, ",
              "type": "text"
            },
            {
              "code": "NULL",
              "type": "codeVoice"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The resultant line consists of glyphs in the correct visual order, ready to draw.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTLine": {
      "abstract": [
        {
          "text": "A line of text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTLine"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLine",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTLine"
        }
      ],
      "role": "symbol",
      "title": "CTLine",
      "type": "topic",
      "url": "/documentation/coretext/ctline"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTTypesetter": {
      "abstract": [
        {
          "text": "A typesetter which performs line layout.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTTypesetter"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTTypesetter",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTTypesetter"
        }
      ],
      "role": "symbol",
      "title": "CTTypesetter",
      "type": "topic",
      "url": "/documentation/coretext/cttypesetter"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTTypesetterCreateLine(_:_:)": {
      "abstract": [
        {
          "text": "Creates an immutable line from the typesetter.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTTypesetterCreateLine"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTTypesetterRef",
          "text": "CTTypesetter"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CFRange",
          "text": "CFRange"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTLineRef",
          "text": "CTLine"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTTypesetterCreateLine(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTTypesetterCreateLine"
        }
      ],
      "role": "symbol",
      "title": "CTTypesetterCreateLine(_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/cttypesettercreateline(_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTTypesetterCreateLineWithOffset(_:_:_:)": {
      "abstract": [
        {
          "text": "Creates an immutable line from the typesetter at a specified line offset.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTTypesetterCreateLineWithOffset"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTTypesetterRef",
          "text": "CTTypesetter"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@SA@CFRange",
          "text": "CFRange"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Sd",
          "text": "Double"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTLineRef",
          "text": "CTLine"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTTypesetterCreateLineWithOffset(_:_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTTypesetterCreateLineWithOffset"
        }
      ],
      "role": "symbol",
      "title": "CTTypesetterCreateLineWithOffset(_:_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/cttypesettercreatelinewithoffset(_:_:_:)"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@SA@CFRange": {
      "abstract": [
        {
          "text": "A structure representing a range of sequential items in a container, such as characters in a buffer or elements in a collection.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "struct "
        },
        {
          "kind": "identifier",
          "text": "CFRange"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@SA@CFRange",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFRange",
      "type": "topic",
      "url": "/documentation/corefoundation/cfrange"
    },
    "doc://com.externally.resolved.symbol/s:Sd": {
      "abstract": [
        {
          "text": "A double-precision, floating-point value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Double"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Sd",
      "kind": "symbol",
      "role": "symbol",
      "title": "Double",
      "type": "topic",
      "url": "/documentation/Swift/Double"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Creating-Lines",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTTypesetterCreateLine(_:_:)"
      ],
      "title": "Creating Lines"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Function"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "CTTypesetterCreateLineWithOffset"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "func"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTTypesetterCreateLineWithOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Creating-Lines",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTTypesetterCreateLine(_:_:)"
              ],
              "title": "Creating Lines"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.apple.coretext/documentation/CoreText/CTLine",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CTLineRef",
                    "text": "CTLineRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "CTTypesetterCreateLineWithOffset"
                  },
                  {
                    "kind": "text",
                    "text": "("
                  },
                  {
                    "identifier": "doc://com.apple.coretext/documentation/CoreText/CTTypesetter",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CTTypesetterRef",
                    "text": "CTTypesetterRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "typesetter"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@SA@CFRange",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@SA@CFRange",
                    "text": "CFRange"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "stringRange"
                  },
                  {
                    "kind": "text",
                    "text": ", "
                  },
                  {
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:d",
                    "text": "double"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "internalParam",
                    "text": "offset"
                  },
                  {
                    "kind": "text",
                    "text": ");"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/1",
          "value": {
            "kind": "parameters",
            "parameters": [
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The typesetter that creates the line. This parameter is required and cannot be set to ",
                        "type": "text"
                      },
                      {
                        "code": "NULL",
                        "type": "codeVoice"
                      },
                      {
                        "text": ".",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "typesetter"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The string range on which the line is based. If the length portion of range is set to ",
                        "type": "text"
                      },
                      {
                        "code": "0",
                        "type": "codeVoice"
                      },
                      {
                        "text": ", then the typesetter continues to add glyphs to the line until it runs out of characters in the string. The location and length of the range must be within the bounds of the string, or the call will fail.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "stringRange"
              },
              {
                "content": [
                  {
                    "inlineContent": [
                      {
                        "text": "The line position offset.",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "name": "offset"
              }
            ]
          }
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/2",
          "value": {
            "content": [
              {
                "anchor": "return-value",
                "level": 2,
                "text": "Return Value",
                "type": "heading"
              },
              {
                "inlineContent": [
                  {
                    "text": "A reference to a CTLine object if the call was successful; otherwise, ",
                    "type": "text"
                  },
                  {
                    "code": "NULL",
                    "type": "codeVoice"
                  },
                  {
                    "text": ".",
                    "type": "text"
                  }
                ],
                "type": "paragraph"
              }
            ],
            "kind": "content"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTypesetterCreateLineWithOffset(_:_:_:)/title",
          "value": "CTTypesetterCreateLineWithOffset"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTypesetterCreateLineWithOffset(_:_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTTypesetterCreateLineWithOffset"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLine/title",
          "value": "CTLineRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLine/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTLine/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTLineRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTypesetterCreateLine(_:_:)/title",
          "value": "CTTypesetterCreateLine"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTypesetterCreateLine(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTTypesetterCreateLine"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTypesetter/title",
          "value": "CTTypesetterRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTypesetter/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTTypesetterRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTTypesetter/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTTypesetterRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/cttypesettercreatelinewithoffset(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/cttypesettercreatelinewithoffset(_:_:_:)"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
