{
  "abstract": [
    {
      "text": "These constants represent the font class mask shift.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText",
        "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/font-class-mask-shift-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Font Class Mask Shift Constants"
  },
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptor": {
      "abstract": [
        {
          "text": "A font descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontDescriptor"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontDescriptor"
        }
      ],
      "role": "symbol",
      "title": "CTFontDescriptor",
      "type": "topic",
      "url": "/documentation/coretext/ctfontdescriptor"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass": {
      "abstract": [
        {
          "text": "The stylistic class values of the font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontStylisticClass"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontStylisticClass"
        }
      ],
      "role": "symbol",
      "title": "CTFontStylisticClass",
      "type": "topic",
      "url": "/documentation/coretext/ctfontstylisticclass"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits": {
      "abstract": [
        {
          "text": "The symbolic representation of stylistic font attributes.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontSymbolicTraits"
        }
      ],
      "role": "symbol",
      "title": "CTFontSymbolicTraits",
      "type": "topic",
      "url": "/documentation/coretext/ctfontsymbolictraits"
    },
    "doc://com.apple.coretext/documentation/CoreText/font-traits": {
      "abstract": [
        {
          "text": "The keys for accessing font traits from a font descriptor.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/font-traits",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Font Traits",
      "type": "topic",
      "url": "/documentation/coretext/font-traits"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontClassMaskShift": {
      "abstract": [
        {
          "text": "Value used to shift the font class to the uppermost four bits of the symbolic traits.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontClassMaskShift"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontClassMaskShift",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontClassMaskShift"
        }
      ],
      "role": "symbol",
      "title": "kCTFontClassMaskShift",
      "type": "topic",
      "url": "/documentation/coretext/kctfontclassmaskshift"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Accessing-Font-Traits",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/font-traits",
        "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits",
        "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass"
      ],
      "title": "Accessing Font Traits"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/kCTFontClassMaskShift"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/kCTFontClassMaskShift"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Accessing-Font-Traits",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/font-traits",
                "doc://com.apple.coretext/documentation/CoreText/CTFontSymbolicTraits",
                "doc://com.apple.coretext/documentation/CoreText/CTFontStylisticClass"
              ],
              "title": "Accessing Font Traits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass/title",
          "value": "CTFontStylisticClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontStylisticClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontStylisticClass/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontStylisticClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontClassMaskShift/title",
          "value": "kCTFontClassMaskShift"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontClassMaskShift/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontClassMaskShift"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits/title",
          "value": "CTFontSymbolicTraits"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontSymbolicTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontSymbolicTraits/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontSymbolicTraits"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptor/title",
          "value": "CTFontDescriptorRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontDescriptorRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontDescriptorRef"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/font-class-mask-shift-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/font-class-mask-shift-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
