{
  "abstract": [
    {
      "text": "These constants provide keys to font feature dictionary values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText",
        "doc://com.apple.coretext/documentation/CoreText/CTFont"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/font-feature-constants"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Font Feature Constants"
  },
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFont": {
      "abstract": [
        {
          "text": "A font object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFont"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFont",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFont"
        }
      ],
      "role": "symbol",
      "title": "CTFont",
      "type": "topic",
      "url": "/documentation/coretext/ctfont"
    },
    "doc://com.apple.coretext/documentation/CoreText/font-variation-axis-dictionary-keys": {
      "abstract": [
        {
          "text": "These constants provide keys to font variation axis dictionary values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/font-variation-axis-dictionary-keys",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Font Variation Axis Dictionary Keys",
      "type": "topic",
      "url": "/documentation/coretext/font-variation-axis-dictionary-keys"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSampleTextKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontFeatureSampleTextKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSampleTextKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFeatureSampleTextKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontFeatureSampleTextKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontfeaturesampletextkey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSelectorDefaultKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontFeatureSelectorDefaultKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSelectorDefaultKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFeatureSelectorDefaultKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontFeatureSelectorDefaultKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontfeatureselectordefaultkey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSelectorIdentifierKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontFeatureSelectorIdentifierKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSelectorIdentifierKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFeatureSelectorIdentifierKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontFeatureSelectorIdentifierKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontfeatureselectoridentifierkey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSelectorNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontFeatureSelectorNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSelectorNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFeatureSelectorNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontFeatureSelectorNameKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontfeatureselectornamekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSelectorSettingKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontFeatureSelectorSettingKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSelectorSettingKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFeatureSelectorSettingKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontFeatureSelectorSettingKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontfeatureselectorsettingkey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureTooltipTextKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontFeatureTooltipTextKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureTooltipTextKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFeatureTooltipTextKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontFeatureTooltipTextKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontfeaturetooltiptextkey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureTypeExclusiveKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontFeatureTypeExclusiveKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureTypeExclusiveKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFeatureTypeExclusiveKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontFeatureTypeExclusiveKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontfeaturetypeexclusivekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureTypeIdentifierKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontFeatureTypeIdentifierKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureTypeIdentifierKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFeatureTypeIdentifierKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontFeatureTypeIdentifierKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontfeaturetypeidentifierkey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureTypeNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontFeatureTypeNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureTypeNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFeatureTypeNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontFeatureTypeNameKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontfeaturetypenamekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureTypeSelectorsKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontFeatureTypeSelectorsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureTypeSelectorsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFeatureTypeSelectorsKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontFeatureTypeSelectorsKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontfeaturetypeselectorskey"
    },
    "doc://com.apple.coretext/documentation/CoreText/name-specifier-constants": {
      "abstract": [
        {
          "text": "Name specifier constants provide access to the different names associated with a font.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/name-specifier-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Name Specifier Constants",
      "type": "topic",
      "url": "/documentation/coretext/name-specifier-constants"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Global-Variables",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/name-specifier-constants",
        "doc://com.apple.coretext/documentation/CoreText/font-variation-axis-dictionary-keys"
      ],
      "title": "Global Variables"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureTypeIdentifierKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureTypeNameKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureTypeExclusiveKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureTypeSelectorsKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSelectorIdentifierKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSelectorNameKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSelectorDefaultKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSelectorSettingKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSampleTextKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureTooltipTextKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureTypeIdentifierKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureTypeNameKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureTypeExclusiveKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureTypeSelectorsKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSelectorIdentifierKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSelectorNameKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSelectorDefaultKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSelectorSettingKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSampleTextKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureTooltipTextKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Global-Variables",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/name-specifier-constants",
                "doc://com.apple.coretext/documentation/CoreText/font-variation-axis-dictionary-keys"
              ],
              "title": "Global Variables"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureSelectorNameKey/title",
          "value": "kCTFontFeatureSelectorNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureSelectorNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFeatureSelectorNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureSelectorIdentifierKey/title",
          "value": "kCTFontFeatureSelectorIdentifierKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureSelectorIdentifierKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFeatureSelectorIdentifierKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureTypeExclusiveKey/title",
          "value": "kCTFontFeatureTypeExclusiveKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureTypeExclusiveKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFeatureTypeExclusiveKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFont/title",
          "value": "CTFontRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFont/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFont/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureTooltipTextKey/title",
          "value": "kCTFontFeatureTooltipTextKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureTooltipTextKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFeatureTooltipTextKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureSelectorDefaultKey/title",
          "value": "kCTFontFeatureSelectorDefaultKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureSelectorDefaultKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFeatureSelectorDefaultKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureSampleTextKey/title",
          "value": "kCTFontFeatureSampleTextKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureSampleTextKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFeatureSampleTextKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureTypeNameKey/title",
          "value": "kCTFontFeatureTypeNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureTypeNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFeatureTypeNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureTypeIdentifierKey/title",
          "value": "kCTFontFeatureTypeIdentifierKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureTypeIdentifierKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFeatureTypeIdentifierKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureTypeSelectorsKey/title",
          "value": "kCTFontFeatureTypeSelectorsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureTypeSelectorsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFeatureTypeSelectorsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureSelectorSettingKey/title",
          "value": "kCTFontFeatureSelectorSettingKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureSelectorSettingKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFeatureSelectorSettingKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/font-feature-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/font-feature-constants"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
