{
  "abstract": [
    {
      "text": "These constants provide keys to font variation axis dictionary values.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText",
        "doc://com.apple.coretext/documentation/CoreText/CTFont"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/font-variation-axis-dictionary-keys"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Font Variation Axis Dictionary Keys"
  },
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFont": {
      "abstract": [
        {
          "text": "A font object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFont"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFont",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFont"
        }
      ],
      "role": "symbol",
      "title": "CTFont",
      "type": "topic",
      "url": "/documentation/coretext/ctfont"
    },
    "doc://com.apple.coretext/documentation/CoreText/font-feature-constants": {
      "abstract": [
        {
          "text": "These constants provide keys to font feature dictionary values.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/font-feature-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Font Feature Constants",
      "type": "topic",
      "url": "/documentation/coretext/font-feature-constants"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontVariationAxisDefaultValueKey": {
      "abstract": [
        {
          "text": "Key to get the variation axis default value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontVariationAxisDefaultValueKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontVariationAxisDefaultValueKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontVariationAxisDefaultValueKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontVariationAxisDefaultValueKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontvariationaxisdefaultvaluekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontVariationAxisHiddenKey": {
      "abstract": [
        {
          "text": "The key to find out if the axis is hidden.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontVariationAxisHiddenKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontVariationAxisHiddenKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontVariationAxisHiddenKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontVariationAxisHiddenKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontvariationaxishiddenkey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontVariationAxisIdentifierKey": {
      "abstract": [
        {
          "text": "Key to get the variation axis identifier.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontVariationAxisIdentifierKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontVariationAxisIdentifierKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontVariationAxisIdentifierKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontVariationAxisIdentifierKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontvariationaxisidentifierkey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontVariationAxisMaximumValueKey": {
      "abstract": [
        {
          "text": "Key to get the variation axis maximum value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontVariationAxisMaximumValueKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontVariationAxisMaximumValueKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontVariationAxisMaximumValueKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontVariationAxisMaximumValueKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontvariationaxismaximumvaluekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontVariationAxisMinimumValueKey": {
      "abstract": [
        {
          "text": "Key to get the variation axis minimum value.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontVariationAxisMinimumValueKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontVariationAxisMinimumValueKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontVariationAxisMinimumValueKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontVariationAxisMinimumValueKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontvariationaxisminimumvaluekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontVariationAxisNameKey": {
      "abstract": [
        {
          "text": "Key to get the localized variation axis name string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontVariationAxisNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontVariationAxisNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontVariationAxisNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontVariationAxisNameKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontvariationaxisnamekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/name-specifier-constants": {
      "abstract": [
        {
          "text": "Name specifier constants provide access to the different names associated with a font.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/name-specifier-constants",
      "kind": "article",
      "role": "collectionGroup",
      "title": "Name Specifier Constants",
      "type": "topic",
      "url": "/documentation/coretext/name-specifier-constants"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Global-Variables",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/name-specifier-constants",
        "doc://com.apple.coretext/documentation/CoreText/font-feature-constants"
      ],
      "title": "Global Variables"
    }
  ],
  "topicSections": [
    {
      "anchor": "Constants",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/kCTFontVariationAxisIdentifierKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontVariationAxisMinimumValueKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontVariationAxisMaximumValueKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontVariationAxisDefaultValueKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontVariationAxisNameKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontVariationAxisHiddenKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Constants",
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/kCTFontVariationAxisIdentifierKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontVariationAxisMinimumValueKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontVariationAxisMaximumValueKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontVariationAxisDefaultValueKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontVariationAxisNameKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontVariationAxisHiddenKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Global-Variables",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/name-specifier-constants",
                "doc://com.apple.coretext/documentation/CoreText/font-feature-constants"
              ],
              "title": "Global Variables"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontVariationAxisMinimumValueKey/title",
          "value": "kCTFontVariationAxisMinimumValueKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontVariationAxisMinimumValueKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontVariationAxisMinimumValueKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontVariationAxisIdentifierKey/title",
          "value": "kCTFontVariationAxisIdentifierKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontVariationAxisIdentifierKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontVariationAxisIdentifierKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontVariationAxisHiddenKey/title",
          "value": "kCTFontVariationAxisHiddenKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontVariationAxisHiddenKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontVariationAxisHiddenKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFont/title",
          "value": "CTFontRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFont/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFont/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontVariationAxisMaximumValueKey/title",
          "value": "kCTFontVariationAxisMaximumValueKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontVariationAxisMaximumValueKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontVariationAxisMaximumValueKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontVariationAxisDefaultValueKey/title",
          "value": "kCTFontVariationAxisDefaultValueKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontVariationAxisDefaultValueKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontVariationAxisDefaultValueKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontVariationAxisNameKey/title",
          "value": "kCTFontVariationAxisNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontVariationAxisNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontVariationAxisNameKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/font-variation-axis-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/font-variation-axis-dictionary-keys"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
