{
  "abstract": [
    {
      "text": "The keys for accessing font attributes from a font descriptor.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText",
        "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptor"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/font-attributes"
  },
  "kind": "article",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "role": "collectionGroup",
    "roleHeading": "API Collection",
    "title": "Font Attributes"
  },
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontCopyAttribute(_:_:)": {
      "abstract": [
        {
          "text": "Returns the value associated with an arbitrary attribute of the given font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontCopyAttribute"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontRef",
          "text": "CTFont"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontCopyAttribute(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontCopyAttribute"
        }
      ],
      "role": "symbol",
      "title": "CTFontCopyAttribute(_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontcopyattribute(_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptor": {
      "abstract": [
        {
          "text": "A font descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "class"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontDescriptor"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptor",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontDescriptor"
        }
      ],
      "role": "symbol",
      "title": "CTFontDescriptor",
      "type": "topic",
      "url": "/documentation/coretext/ctfontdescriptor"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorCopyAttribute(_:_:)": {
      "abstract": [
        {
          "text": "Returns the value associated with an arbitrary attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontDescriptorCopyAttribute"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontDescriptorRef",
          "text": "CTFontDescriptor"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFTypeRef",
          "text": "CFTypeRef"
        },
        {
          "kind": "text",
          "text": "?"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorCopyAttribute(_:_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontDescriptorCopyAttribute"
        }
      ],
      "role": "symbol",
      "title": "CTFontDescriptorCopyAttribute(_:_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontdescriptorcopyattribute(_:_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorCopyAttributes(_:)": {
      "abstract": [
        {
          "text": "Returns the attributes dictionary of the font descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "func"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontDescriptorCopyAttributes"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CTFontDescriptorRef",
          "text": "CTFontDescriptor"
        },
        {
          "kind": "text",
          "text": ") -> "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFDictionaryRef",
          "text": "CFDictionary"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorCopyAttributes(_:)",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontDescriptorCopyAttributes"
        }
      ],
      "role": "symbol",
      "title": "CTFontDescriptorCopyAttributes(_:)",
      "type": "topic",
      "url": "/documentation/coretext/ctfontdescriptorcopyattributes(_:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontFormat": {
      "abstract": [
        {
          "text": "The recognized format of the font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontFormat"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontFormat",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontFormat"
        }
      ],
      "role": "symbol",
      "title": "CTFontFormat",
      "type": "topic",
      "url": "/documentation/coretext/ctfontformat"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontOrientation": {
      "abstract": [
        {
          "text": "The intended rendering orientation of the font for obtaining glyph metrics.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "enum"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontOrientation"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontOrientation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontOrientation"
        }
      ],
      "role": "symbol",
      "title": "CTFontOrientation",
      "type": "topic",
      "url": "/documentation/coretext/ctfontorientation"
    },
    "doc://com.apple.coretext/documentation/CoreText/CTFontPriority": {
      "abstract": [
        {
          "text": "The priority of font descriptors when resolving duplicates and sorting match results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "typealias"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "CTFontPriority"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/CTFontPriority",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "CTFontPriority"
        }
      ],
      "role": "symbol",
      "title": "CTFontPriority",
      "type": "topic",
      "url": "/documentation/coretext/ctfontpriority"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontBaselineAdjustAttribute": {
      "abstract": [
        {
          "text": "The baseline adjustment for a font reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontBaselineAdjustAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontBaselineAdjustAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontBaselineAdjustAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontBaselineAdjustAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontbaselineadjustattribute"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontCascadeListAttribute": {
      "abstract": [
        {
          "text": "The cascade list used for a font reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontCascadeListAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontCascadeListAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontCascadeListAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontCascadeListAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontcascadelistattribute"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontCharacterSetAttribute": {
      "abstract": [
        {
          "text": "The Unicode character coverage set for a font reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontCharacterSetAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontCharacterSetAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontCharacterSetAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontCharacterSetAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontcharactersetattribute"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontDisplayNameAttribute": {
      "abstract": [
        {
          "text": "The name used to display the font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontDisplayNameAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontDisplayNameAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontDisplayNameAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontDisplayNameAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontdisplaynameattribute"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontDownloadableAttribute": {
      "abstract": [
        {
          "text": "The font downloadable state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontDownloadableAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontDownloadableAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontDownloadableAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontDownloadableAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontdownloadableattribute"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontDownloadedAttribute": {
      "abstract": [
        {
          "text": "The download state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontDownloadedAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontDownloadedAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontDownloadedAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontDownloadedAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontdownloadedattribute"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontEnabledAttribute": {
      "abstract": [
        {
          "text": "The font enabled state.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontEnabledAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontEnabledAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontEnabledAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontEnabledAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontenabledattribute"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontFamilyNameAttribute": {
      "abstract": [
        {
          "text": "The font family name from the font descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontFamilyNameAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontFamilyNameAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFamilyNameAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontFamilyNameAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontfamilynameattribute"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSettingsAttribute": {
      "abstract": [
        {
          "text": "The font features settings for a font reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontFeatureSettingsAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSettingsAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFeatureSettingsAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontFeatureSettingsAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontfeaturesettingsattribute"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontFeaturesAttribute": {
      "abstract": [
        {
          "text": "The font features for a font reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontFeaturesAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontFeaturesAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFeaturesAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontFeaturesAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontfeaturesattribute"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontFixedAdvanceAttribute": {
      "abstract": [
        {
          "text": "A fixed advance to be used for a font reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontFixedAdvanceAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontFixedAdvanceAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFixedAdvanceAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontFixedAdvanceAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontfixedadvanceattribute"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontFormatAttribute": {
      "abstract": [
        {
          "text": "The recognized format of the font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontFormatAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontFormatAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFormatAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontFormatAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontformatattribute"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontLanguagesAttribute": {
      "abstract": [
        {
          "text": "A list of covered languages for a font reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontLanguagesAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontLanguagesAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontLanguagesAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontLanguagesAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontlanguagesattribute"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontMacintoshEncodingsAttribute": {
      "abstract": [
        {
          "text": "The Macintosh encodings for a font reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontMacintoshEncodingsAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontMacintoshEncodingsAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontMacintoshEncodingsAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontMacintoshEncodingsAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontmacintoshencodingsattribute"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontMatrixAttribute": {
      "abstract": [
        {
          "text": "The font transformation matrix when creating a font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontMatrixAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontMatrixAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontMatrixAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontMatrixAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontmatrixattribute"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontNameAttribute": {
      "abstract": [
        {
          "text": "The PostScript name from the font descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontNameAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontNameAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontNameAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontNameAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontnameattribute"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontOrientationAttribute": {
      "abstract": [
        {
          "text": "The orientation for the glyphs of the font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontOrientationAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontOrientationAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontOrientationAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontOrientationAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontorientationattribute"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontPriorityAttribute": {
      "abstract": [
        {
          "text": "The font priority used by font descriptors when resolving duplicates and sorting match results.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontPriorityAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontPriorityAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontPriorityAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontPriorityAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontpriorityattribute"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontRegistrationScopeAttribute": {
      "abstract": [
        {
          "text": "The font descriptor’s registration scope.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontRegistrationScopeAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontRegistrationScopeAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontRegistrationScopeAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontRegistrationScopeAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontregistrationscopeattribute"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontSizeAttribute": {
      "abstract": [
        {
          "text": "The font point size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontSizeAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontSizeAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontSizeAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontSizeAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontsizeattribute"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontStyleNameAttribute": {
      "abstract": [
        {
          "text": "The style name of the font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontStyleNameAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontStyleNameAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontStyleNameAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontStyleNameAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontstylenameattribute"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontTraitsAttribute": {
      "abstract": [
        {
          "text": "The dictionary of font traits for stylistic information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontTraitsAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontTraitsAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTraitsAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontTraitsAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfonttraitsattribute"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontURLAttribute": {
      "abstract": [
        {
          "text": "The font URL from the font descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontURLAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontURLAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontURLAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontURLAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfonturlattribute"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontVariationAttribute": {
      "abstract": [
        {
          "text": "The dictionary of font variation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontVariationAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontVariationAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontVariationAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontVariationAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontvariationattribute"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorCopyAttribute(_:_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorCopyAttributes(_:)",
        "doc://com.apple.coretext/documentation/CoreText/CTFontCopyAttribute(_:_:)"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Accessing-Font-Attributes",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/CTFontOrientation",
        "doc://com.apple.coretext/documentation/CoreText/CTFontFormat",
        "doc://com.apple.coretext/documentation/CoreText/CTFontPriority"
      ],
      "title": "Accessing Font Attributes"
    }
  ],
  "topicSections": [
    {
      "anchor": "Font-Attribute-Keys",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/kCTFontURLAttribute",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontNameAttribute",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontDisplayNameAttribute",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontFamilyNameAttribute",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontStyleNameAttribute",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontTraitsAttribute",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontVariationAttribute",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontSizeAttribute",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontMatrixAttribute",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontCascadeListAttribute",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontCharacterSetAttribute",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontLanguagesAttribute",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontBaselineAdjustAttribute",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontMacintoshEncodingsAttribute",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontFeaturesAttribute",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSettingsAttribute",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontFixedAdvanceAttribute",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontOrientationAttribute",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontFormatAttribute",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontRegistrationScopeAttribute",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontPriorityAttribute",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontEnabledAttribute",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontDownloadableAttribute",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontDownloadedAttribute"
      ],
      "title": "Font Attribute Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Font-Attribute-Keys",
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/kCTFontURLAttribute",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontNameAttribute",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontDisplayNameAttribute",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontFamilyNameAttribute",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontStyleNameAttribute",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontTraitsAttribute",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontVariationAttribute",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontSizeAttribute",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontMatrixAttribute",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontCascadeListAttribute",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontCharacterSetAttribute",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontLanguagesAttribute",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontBaselineAdjustAttribute",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontMacintoshEncodingsAttribute",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontFeaturesAttribute",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSettingsAttribute",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontFixedAdvanceAttribute",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontOrientationAttribute",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontFormatAttribute",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontRegistrationScopeAttribute",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontPriorityAttribute",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontEnabledAttribute",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontDownloadableAttribute",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontDownloadedAttribute"
              ],
              "title": "Font Attribute Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorCopyAttribute(_:_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTFontDescriptorCopyAttributes(_:)",
                "doc://com.apple.coretext/documentation/CoreText/CTFontCopyAttribute(_:_:)"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Accessing-Font-Attributes",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/CTFontOrientation",
                "doc://com.apple.coretext/documentation/CoreText/CTFontFormat",
                "doc://com.apple.coretext/documentation/CoreText/CTFontPriority"
              ],
              "title": "Accessing Font Attributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFamilyNameAttribute/title",
          "value": "kCTFontFamilyNameAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFamilyNameAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFamilyNameAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontEnabledAttribute/title",
          "value": "kCTFontEnabledAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontEnabledAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontEnabledAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontURLAttribute/title",
          "value": "kCTFontURLAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontURLAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontURLAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontMacintoshEncodingsAttribute/title",
          "value": "kCTFontMacintoshEncodingsAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontMacintoshEncodingsAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontMacintoshEncodingsAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontOrientation/title",
          "value": "CTFontOrientation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontOrientation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontOrientation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontOrientation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontSizeAttribute/title",
          "value": "kCTFontSizeAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontSizeAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontSizeAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontDownloadedAttribute/title",
          "value": "kCTFontDownloadedAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontDownloadedAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontDownloadedAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFormatAttribute/title",
          "value": "kCTFontFormatAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFormatAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFormatAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontLanguagesAttribute/title",
          "value": "kCTFontLanguagesAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontLanguagesAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontLanguagesAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontVariationAttribute/title",
          "value": "kCTFontVariationAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontVariationAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontVariationAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontCascadeListAttribute/title",
          "value": "kCTFontCascadeListAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontCascadeListAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontCascadeListAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontCharacterSetAttribute/title",
          "value": "kCTFontCharacterSetAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontCharacterSetAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontCharacterSetAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeaturesAttribute/title",
          "value": "kCTFontFeaturesAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeaturesAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFeaturesAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontOrientationAttribute/title",
          "value": "kCTFontOrientationAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontOrientationAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontOrientationAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFixedAdvanceAttribute/title",
          "value": "kCTFontFixedAdvanceAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFixedAdvanceAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFixedAdvanceAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptor/title",
          "value": "CTFontDescriptorRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptor/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontDescriptorRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptor/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontDescriptorRef"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontRegistrationScopeAttribute/title",
          "value": "kCTFontRegistrationScopeAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontRegistrationScopeAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontRegistrationScopeAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptorCopyAttributes(_:)/title",
          "value": "CTFontDescriptorCopyAttributes"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptorCopyAttributes(_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontDescriptorCopyAttributes"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontBaselineAdjustAttribute/title",
          "value": "kCTFontBaselineAdjustAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontBaselineAdjustAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontBaselineAdjustAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontDownloadableAttribute/title",
          "value": "kCTFontDownloadableAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontDownloadableAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontDownloadableAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCopyAttribute(_:_:)/title",
          "value": "CTFontCopyAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontCopyAttribute(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontCopyAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptorCopyAttribute(_:_:)/title",
          "value": "CTFontDescriptorCopyAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontDescriptorCopyAttribute(_:_:)/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontDescriptorCopyAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontPriority/title",
          "value": "CTFontPriority"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontPriority/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontPriority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontPriority/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontPriority"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontNameAttribute/title",
          "value": "kCTFontNameAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontNameAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontNameAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontStyleNameAttribute/title",
          "value": "kCTFontStyleNameAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontStyleNameAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontStyleNameAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontPriorityAttribute/title",
          "value": "kCTFontPriorityAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontPriorityAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontPriorityAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontTraitsAttribute/title",
          "value": "kCTFontTraitsAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontTraitsAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTraitsAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureSettingsAttribute/title",
          "value": "kCTFontFeatureSettingsAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureSettingsAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFeatureSettingsAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontDisplayNameAttribute/title",
          "value": "kCTFontDisplayNameAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontDisplayNameAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontDisplayNameAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontFormat/title",
          "value": "CTFontFormat"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontFormat/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1CTFontFormat/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "CTFontFormat"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontMatrixAttribute/title",
          "value": "kCTFontMatrixAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontMatrixAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontMatrixAttribute"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/font-attributes"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/font-attributes"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
