{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/kCTBaselineReferenceInfoAttributeName"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCTBaselineReferenceInfoAttributeName",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCTBaselineReferenceInfoAttributeName"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCTBaselineReferenceInfoAttributeName"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "6.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.8",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCTBaselineReferenceInfoAttributeName"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCTBaselineReferenceInfoAttributeName"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/ATSFONTREF_DEFINED": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "ATSFONTREF_DEFINED"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int32V",
          "text": "Int32"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/ATSFONTREF_DEFINED",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "ATSFONTREF_DEFINED"
        }
      ],
      "role": "symbol",
      "title": "ATSFONTREF_DEFINED",
      "type": "topic",
      "url": "/documentation/coretext/atsfontref_defined"
    },
    "doc://com.apple.coretext/documentation/CoreText/kBSLNIdeographicHighBaseline": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kBSLNIdeographicHighBaseline"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kBSLNIdeographicHighBaseline",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kBSLNIdeographicHighBaseline"
        }
      ],
      "role": "symbol",
      "title": "kBSLNIdeographicHighBaseline",
      "type": "topic",
      "url": "/documentation/coretext/kbslnideographichighbaseline"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTAdaptiveImageProviderAttributeName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTAdaptiveImageProviderAttributeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTAdaptiveImageProviderAttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTAdaptiveImageProviderAttributeName"
        }
      ],
      "role": "symbol",
      "title": "kCTAdaptiveImageProviderAttributeName",
      "type": "topic",
      "url": "/documentation/coretext/kctadaptiveimageproviderattributename"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTBackgroundColorAttributeName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTBackgroundColorAttributeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTBackgroundColorAttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTBackgroundColorAttributeName"
        }
      ],
      "role": "symbol",
      "title": "kCTBackgroundColorAttributeName",
      "type": "topic",
      "url": "/documentation/coretext/kctbackgroundcolorattributename"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTBaselineClassAttributeName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTBaselineClassAttributeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTBaselineClassAttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTBaselineClassAttributeName"
        }
      ],
      "role": "symbol",
      "title": "kCTBaselineClassAttributeName",
      "type": "topic",
      "url": "/documentation/coretext/kctbaselineclassattributename"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTBaselineClassHanging": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTBaselineClassHanging"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTBaselineClassHanging",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTBaselineClassHanging"
        }
      ],
      "role": "symbol",
      "title": "kCTBaselineClassHanging",
      "type": "topic",
      "url": "/documentation/coretext/kctbaselineclasshanging"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTBaselineClassIdeographicCentered": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTBaselineClassIdeographicCentered"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTBaselineClassIdeographicCentered",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTBaselineClassIdeographicCentered"
        }
      ],
      "role": "symbol",
      "title": "kCTBaselineClassIdeographicCentered",
      "type": "topic",
      "url": "/documentation/coretext/kctbaselineclassideographiccentered"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTBaselineClassIdeographicHigh": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTBaselineClassIdeographicHigh"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTBaselineClassIdeographicHigh",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTBaselineClassIdeographicHigh"
        }
      ],
      "role": "symbol",
      "title": "kCTBaselineClassIdeographicHigh",
      "type": "topic",
      "url": "/documentation/coretext/kctbaselineclassideographichigh"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTBaselineClassIdeographicLow": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTBaselineClassIdeographicLow"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTBaselineClassIdeographicLow",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTBaselineClassIdeographicLow"
        }
      ],
      "role": "symbol",
      "title": "kCTBaselineClassIdeographicLow",
      "type": "topic",
      "url": "/documentation/coretext/kctbaselineclassideographiclow"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTBaselineClassMath": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTBaselineClassMath"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTBaselineClassMath",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTBaselineClassMath"
        }
      ],
      "role": "symbol",
      "title": "kCTBaselineClassMath",
      "type": "topic",
      "url": "/documentation/coretext/kctbaselineclassmath"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTBaselineClassRoman": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTBaselineClassRoman"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTBaselineClassRoman",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTBaselineClassRoman"
        }
      ],
      "role": "symbol",
      "title": "kCTBaselineClassRoman",
      "type": "topic",
      "url": "/documentation/coretext/kctbaselineclassroman"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTBaselineInfoAttributeName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTBaselineInfoAttributeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTBaselineInfoAttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTBaselineInfoAttributeName"
        }
      ],
      "role": "symbol",
      "title": "kCTBaselineInfoAttributeName",
      "type": "topic",
      "url": "/documentation/coretext/kctbaselineinfoattributename"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTBaselineOriginalFont": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTBaselineOriginalFont"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTBaselineOriginalFont",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTBaselineOriginalFont"
        }
      ],
      "role": "symbol",
      "title": "kCTBaselineOriginalFont",
      "type": "topic",
      "url": "/documentation/coretext/kctbaselineoriginalfont"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTBaselineReferenceFont": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTBaselineReferenceFont"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTBaselineReferenceFont",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTBaselineReferenceFont"
        }
      ],
      "role": "symbol",
      "title": "kCTBaselineReferenceFont",
      "type": "topic",
      "url": "/documentation/coretext/kctbaselinereferencefont"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTBaselineReferenceInfoAttributeName": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTBaselineReferenceInfoAttributeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTBaselineReferenceInfoAttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTBaselineReferenceInfoAttributeName"
        }
      ],
      "role": "symbol",
      "title": "kCTBaselineReferenceInfoAttributeName",
      "type": "topic",
      "url": "/documentation/coretext/kctbaselinereferenceinfoattributename"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontCollectionDisallowAutoActivationOption": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontCollectionDisallowAutoActivationOption"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontCollectionDisallowAutoActivationOption",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontCollectionDisallowAutoActivationOption"
        }
      ],
      "role": "symbol",
      "title": "kCTFontCollectionDisallowAutoActivationOption",
      "type": "topic",
      "url": "/documentation/coretext/kctfontcollectiondisallowautoactivationoption"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/ATSFONTREF_DEFINED",
        "doc://com.apple.coretext/documentation/CoreText/kBSLNIdeographicHighBaseline",
        "doc://com.apple.coretext/documentation/CoreText/kCTAdaptiveImageProviderAttributeName",
        "doc://com.apple.coretext/documentation/CoreText/kCTBackgroundColorAttributeName",
        "doc://com.apple.coretext/documentation/CoreText/kCTBaselineClassAttributeName",
        "doc://com.apple.coretext/documentation/CoreText/kCTBaselineClassHanging",
        "doc://com.apple.coretext/documentation/CoreText/kCTBaselineClassIdeographicCentered",
        "doc://com.apple.coretext/documentation/CoreText/kCTBaselineClassIdeographicHigh",
        "doc://com.apple.coretext/documentation/CoreText/kCTBaselineClassIdeographicLow",
        "doc://com.apple.coretext/documentation/CoreText/kCTBaselineClassMath",
        "doc://com.apple.coretext/documentation/CoreText/kCTBaselineClassRoman",
        "doc://com.apple.coretext/documentation/CoreText/kCTBaselineInfoAttributeName",
        "doc://com.apple.coretext/documentation/CoreText/kCTBaselineOriginalFont",
        "doc://com.apple.coretext/documentation/CoreText/kCTBaselineReferenceFont",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontCollectionDisallowAutoActivationOption"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "6.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.8",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCTBaselineReferenceInfoAttributeName"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTBaselineReferenceInfoAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/ATSFONTREF_DEFINED",
                "doc://com.apple.coretext/documentation/CoreText/kBSLNIdeographicHighBaseline",
                "doc://com.apple.coretext/documentation/CoreText/kCTAdaptiveImageProviderAttributeName",
                "doc://com.apple.coretext/documentation/CoreText/kCTBackgroundColorAttributeName",
                "doc://com.apple.coretext/documentation/CoreText/kCTBaselineClassAttributeName",
                "doc://com.apple.coretext/documentation/CoreText/kCTBaselineClassHanging",
                "doc://com.apple.coretext/documentation/CoreText/kCTBaselineClassIdeographicCentered",
                "doc://com.apple.coretext/documentation/CoreText/kCTBaselineClassIdeographicHigh",
                "doc://com.apple.coretext/documentation/CoreText/kCTBaselineClassIdeographicLow",
                "doc://com.apple.coretext/documentation/CoreText/kCTBaselineClassMath",
                "doc://com.apple.coretext/documentation/CoreText/kCTBaselineClassRoman",
                "doc://com.apple.coretext/documentation/CoreText/kCTBaselineInfoAttributeName",
                "doc://com.apple.coretext/documentation/CoreText/kCTBaselineOriginalFont",
                "doc://com.apple.coretext/documentation/CoreText/kCTBaselineReferenceFont",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontCollectionDisallowAutoActivationOption"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCTBaselineReferenceInfoAttributeName"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTBaselineReferenceInfoAttributeName/title",
          "value": "kCTBaselineReferenceInfoAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTBaselineReferenceInfoAttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTBaselineReferenceInfoAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTBaselineClassIdeographicLow/title",
          "value": "kCTBaselineClassIdeographicLow"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTBaselineClassIdeographicLow/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTBaselineClassIdeographicLow"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontCollectionDisallowAutoActivationOption/title",
          "value": "kCTFontCollectionDisallowAutoActivationOption"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontCollectionDisallowAutoActivationOption/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontCollectionDisallowAutoActivationOption"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTBaselineOriginalFont/title",
          "value": "kCTBaselineOriginalFont"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTBaselineOriginalFont/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTBaselineOriginalFont"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTBackgroundColorAttributeName/title",
          "value": "kCTBackgroundColorAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTBackgroundColorAttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTBackgroundColorAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kBSLNIdeographicHighBaseline/title",
          "value": "kBSLNIdeographicHighBaseline"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kBSLNIdeographicHighBaseline/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kBSLNIdeographicHighBaseline"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1ATSFONTREF_DEFINED/title",
          "value": "ATSFONTREF_DEFINED"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1ATSFONTREF_DEFINED/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "ATSFONTREF_DEFINED"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTBaselineClassIdeographicCentered/title",
          "value": "kCTBaselineClassIdeographicCentered"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTBaselineClassIdeographicCentered/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTBaselineClassIdeographicCentered"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTBaselineClassHanging/title",
          "value": "kCTBaselineClassHanging"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTBaselineClassHanging/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTBaselineClassHanging"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTBaselineClassAttributeName/title",
          "value": "kCTBaselineClassAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTBaselineClassAttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTBaselineClassAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTBaselineInfoAttributeName/title",
          "value": "kCTBaselineInfoAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTBaselineInfoAttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTBaselineInfoAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTBaselineClassMath/title",
          "value": "kCTBaselineClassMath"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTBaselineClassMath/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTBaselineClassMath"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTAdaptiveImageProviderAttributeName/title",
          "value": "kCTAdaptiveImageProviderAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTAdaptiveImageProviderAttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTAdaptiveImageProviderAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTBaselineClassIdeographicHigh/title",
          "value": "kCTBaselineClassIdeographicHigh"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTBaselineClassIdeographicHigh/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTBaselineClassIdeographicHigh"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTBaselineClassRoman/title",
          "value": "kCTBaselineClassRoman"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTBaselineClassRoman/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTBaselineClassRoman"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTBaselineReferenceFont/title",
          "value": "kCTBaselineReferenceFont"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTBaselineReferenceFont/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTBaselineReferenceFont"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/kctbaselinereferenceinfoattributename"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/kctbaselinereferenceinfoattributename"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
