{
  "abstract": [
    {
      "text": "The font URL from the font descriptor.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/kCTFontURLAttribute"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCTFontURLAttribute",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCTFontURLAttribute"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCTFontURLAttribute"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.6",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCTFontURLAttribute"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCTFontURLAttribute"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The value associated with this key is a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfurl-rd7",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " object.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontBaselineAdjustAttribute": {
      "abstract": [
        {
          "text": "The baseline adjustment for a font reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontBaselineAdjustAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontBaselineAdjustAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontBaselineAdjustAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontBaselineAdjustAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontbaselineadjustattribute"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontCascadeListAttribute": {
      "abstract": [
        {
          "text": "The cascade list used for a font reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontCascadeListAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontCascadeListAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontCascadeListAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontCascadeListAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontcascadelistattribute"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontCharacterSetAttribute": {
      "abstract": [
        {
          "text": "The Unicode character coverage set for a font reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontCharacterSetAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontCharacterSetAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontCharacterSetAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontCharacterSetAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontcharactersetattribute"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontDisplayNameAttribute": {
      "abstract": [
        {
          "text": "The name used to display the font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontDisplayNameAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontDisplayNameAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontDisplayNameAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontDisplayNameAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontdisplaynameattribute"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontFamilyNameAttribute": {
      "abstract": [
        {
          "text": "The font family name from the font descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontFamilyNameAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontFamilyNameAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFamilyNameAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontFamilyNameAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontfamilynameattribute"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSettingsAttribute": {
      "abstract": [
        {
          "text": "The font features settings for a font reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontFeatureSettingsAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSettingsAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFeatureSettingsAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontFeatureSettingsAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontfeaturesettingsattribute"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontFeaturesAttribute": {
      "abstract": [
        {
          "text": "The font features for a font reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontFeaturesAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontFeaturesAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFeaturesAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontFeaturesAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontfeaturesattribute"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontLanguagesAttribute": {
      "abstract": [
        {
          "text": "A list of covered languages for a font reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontLanguagesAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontLanguagesAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontLanguagesAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontLanguagesAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontlanguagesattribute"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontMacintoshEncodingsAttribute": {
      "abstract": [
        {
          "text": "The Macintosh encodings for a font reference.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontMacintoshEncodingsAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontMacintoshEncodingsAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontMacintoshEncodingsAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontMacintoshEncodingsAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontmacintoshencodingsattribute"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontMatrixAttribute": {
      "abstract": [
        {
          "text": "The font transformation matrix when creating a font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontMatrixAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontMatrixAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontMatrixAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontMatrixAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontmatrixattribute"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontNameAttribute": {
      "abstract": [
        {
          "text": "The PostScript name from the font descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontNameAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontNameAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontNameAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontNameAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontnameattribute"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontSizeAttribute": {
      "abstract": [
        {
          "text": "The font point size.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontSizeAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontSizeAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontSizeAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontSizeAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontsizeattribute"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontStyleNameAttribute": {
      "abstract": [
        {
          "text": "The style name of the font.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontStyleNameAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontStyleNameAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontStyleNameAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontStyleNameAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontstylenameattribute"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontTraitsAttribute": {
      "abstract": [
        {
          "text": "The dictionary of font traits for stylistic information.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontTraitsAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontTraitsAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTraitsAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontTraitsAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfonttraitsattribute"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontURLAttribute": {
      "abstract": [
        {
          "text": "The font URL from the font descriptor.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontURLAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontURLAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontURLAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontURLAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfonturlattribute"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontVariationAttribute": {
      "abstract": [
        {
          "text": "The dictionary of font variation.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontVariationAttribute"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontVariationAttribute",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontVariationAttribute"
        }
      ],
      "role": "symbol",
      "title": "kCTFontVariationAttribute",
      "type": "topic",
      "url": "/documentation/coretext/kctfontvariationattribute"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cfurl-rd7": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfurl-rd7",
      "kind": "article",
      "role": "article",
      "title": "CFURL",
      "type": "topic",
      "url": "/documentation/corefoundation/cfurl-rd7"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Font-Attribute-Keys",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/kCTFontNameAttribute",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontDisplayNameAttribute",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontFamilyNameAttribute",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontStyleNameAttribute",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontTraitsAttribute",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontVariationAttribute",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontSizeAttribute",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontMatrixAttribute",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontCascadeListAttribute",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontCharacterSetAttribute",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontLanguagesAttribute",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontBaselineAdjustAttribute",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontMacintoshEncodingsAttribute",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontFeaturesAttribute",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSettingsAttribute"
      ],
      "title": "Font Attribute Keys"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.6",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCTFontURLAttribute"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontURLAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Font-Attribute-Keys",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/kCTFontNameAttribute",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontDisplayNameAttribute",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontFamilyNameAttribute",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontStyleNameAttribute",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontTraitsAttribute",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontVariationAttribute",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontSizeAttribute",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontMatrixAttribute",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontCascadeListAttribute",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontCharacterSetAttribute",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontLanguagesAttribute",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontBaselineAdjustAttribute",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontMacintoshEncodingsAttribute",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontFeaturesAttribute",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSettingsAttribute"
              ],
              "title": "Font Attribute Keys"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCTFontURLAttribute"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureSettingsAttribute/title",
          "value": "kCTFontFeatureSettingsAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureSettingsAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFeatureSettingsAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontNameAttribute/title",
          "value": "kCTFontNameAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontNameAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontNameAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontTraitsAttribute/title",
          "value": "kCTFontTraitsAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontTraitsAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTraitsAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontBaselineAdjustAttribute/title",
          "value": "kCTFontBaselineAdjustAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontBaselineAdjustAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontBaselineAdjustAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontCharacterSetAttribute/title",
          "value": "kCTFontCharacterSetAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontCharacterSetAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontCharacterSetAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontCascadeListAttribute/title",
          "value": "kCTFontCascadeListAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontCascadeListAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontCascadeListAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontSizeAttribute/title",
          "value": "kCTFontSizeAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontSizeAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontSizeAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontMacintoshEncodingsAttribute/title",
          "value": "kCTFontMacintoshEncodingsAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontMacintoshEncodingsAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontMacintoshEncodingsAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontDisplayNameAttribute/title",
          "value": "kCTFontDisplayNameAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontDisplayNameAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontDisplayNameAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontURLAttribute/title",
          "value": "kCTFontURLAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontURLAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontURLAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontMatrixAttribute/title",
          "value": "kCTFontMatrixAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontMatrixAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontMatrixAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontVariationAttribute/title",
          "value": "kCTFontVariationAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontVariationAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontVariationAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeaturesAttribute/title",
          "value": "kCTFontFeaturesAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeaturesAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFeaturesAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontStyleNameAttribute/title",
          "value": "kCTFontStyleNameAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontStyleNameAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontStyleNameAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFamilyNameAttribute/title",
          "value": "kCTFontFamilyNameAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFamilyNameAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFamilyNameAttribute"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontLanguagesAttribute/title",
          "value": "kCTFontLanguagesAttribute"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontLanguagesAttribute/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontLanguagesAttribute"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/kctfonturlattribute"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/kctfonturlattribute"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
