{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/kCTFontSubFamilyNameKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCTFontSubFamilyNameKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCTFontSubFamilyNameKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCTFontSubFamilyNameKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCTFontSubFamilyNameKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCTFontSubFamilyNameKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The name specifier for the subfamily name.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontCopyrightNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontCopyrightNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontCopyrightNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontCopyrightNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontCopyrightNameKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontcopyrightnamekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontDescriptionNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontDescriptionNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontDescriptionNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontDescriptionNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontDescriptionNameKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontdescriptionnamekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontDesignerNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontDesignerNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontDesignerNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontDesignerNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontDesignerNameKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontdesignernamekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontDesignerURLNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontDesignerURLNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontDesignerURLNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontDesignerURLNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontDesignerURLNameKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontdesignerurlnamekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontFamilyNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontFamilyNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontFamilyNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFamilyNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontFamilyNameKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontfamilynamekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontFullNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontFullNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontFullNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFullNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontFullNameKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontfullnamekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontLicenseNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontLicenseNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontLicenseNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontLicenseNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontLicenseNameKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontlicensenamekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontLicenseURLNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontLicenseURLNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontLicenseURLNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontLicenseURLNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontLicenseURLNameKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontlicenseurlnamekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontManufacturerNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontManufacturerNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontManufacturerNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontManufacturerNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontManufacturerNameKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontmanufacturernamekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontPostScriptNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontPostScriptNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontPostScriptNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontPostScriptNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontPostScriptNameKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontpostscriptnamekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontStyleNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontStyleNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontStyleNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontStyleNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontStyleNameKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontstylenamekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontSubFamilyNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontSubFamilyNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontSubFamilyNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontSubFamilyNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontSubFamilyNameKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontsubfamilynamekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontTrademarkNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontTrademarkNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontTrademarkNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTrademarkNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontTrademarkNameKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfonttrademarknamekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontUniqueNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontUniqueNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontUniqueNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontUniqueNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontUniqueNameKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontuniquenamekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontVendorURLNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontVendorURLNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontVendorURLNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontVendorURLNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontVendorURLNameKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontvendorurlnamekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontVersionNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontVersionNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontVersionNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontVersionNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontVersionNameKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontversionnamekey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/kCTFontCopyrightNameKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontFamilyNameKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontStyleNameKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontUniqueNameKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontFullNameKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontVersionNameKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontPostScriptNameKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontTrademarkNameKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontManufacturerNameKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontDesignerNameKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontDescriptionNameKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontVendorURLNameKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontDesignerURLNameKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontLicenseNameKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontLicenseURLNameKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCTFontSubFamilyNameKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontSubFamilyNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/kCTFontCopyrightNameKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontFamilyNameKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontStyleNameKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontUniqueNameKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontFullNameKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontVersionNameKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontPostScriptNameKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontTrademarkNameKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontManufacturerNameKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontDesignerNameKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontDescriptionNameKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontVendorURLNameKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontDesignerURLNameKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontLicenseNameKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontLicenseURLNameKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCTFontSubFamilyNameKey"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFullNameKey/title",
          "value": "kCTFontFullNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFullNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFullNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontSubFamilyNameKey/title",
          "value": "kCTFontSubFamilyNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontSubFamilyNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontSubFamilyNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontPostScriptNameKey/title",
          "value": "kCTFontPostScriptNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontPostScriptNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontPostScriptNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontManufacturerNameKey/title",
          "value": "kCTFontManufacturerNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontManufacturerNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontManufacturerNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontLicenseURLNameKey/title",
          "value": "kCTFontLicenseURLNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontLicenseURLNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontLicenseURLNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontTrademarkNameKey/title",
          "value": "kCTFontTrademarkNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontTrademarkNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTrademarkNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontStyleNameKey/title",
          "value": "kCTFontStyleNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontStyleNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontStyleNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontDesignerURLNameKey/title",
          "value": "kCTFontDesignerURLNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontDesignerURLNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontDesignerURLNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontVersionNameKey/title",
          "value": "kCTFontVersionNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontVersionNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontVersionNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontUniqueNameKey/title",
          "value": "kCTFontUniqueNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontUniqueNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontUniqueNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontLicenseNameKey/title",
          "value": "kCTFontLicenseNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontLicenseNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontLicenseNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontDescriptionNameKey/title",
          "value": "kCTFontDescriptionNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontDescriptionNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontDescriptionNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontCopyrightNameKey/title",
          "value": "kCTFontCopyrightNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontCopyrightNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontCopyrightNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontDesignerNameKey/title",
          "value": "kCTFontDesignerNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontDesignerNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontDesignerNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFamilyNameKey/title",
          "value": "kCTFontFamilyNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFamilyNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFamilyNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontVendorURLNameKey/title",
          "value": "kCTFontVendorURLNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontVendorURLNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontVendorURLNameKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/kctfontsubfamilynamekey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/kctfontsubfamilynamekey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
