{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/kCTFontTableTrak"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kCTFontTableBASE@kCTFontTableTrak",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCTFontTableTrak"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCTFontTableTrak"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCTFontTableTrak"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCTFontTableTrak"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Font table tag for tracking.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontTableBASE": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontTableBASE"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontTableBASE",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTableBASE"
        }
      ],
      "role": "symbol",
      "title": "kCTFontTableBASE",
      "type": "topic",
      "url": "/documentation/coretext/kctfonttablebase"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontTableCFF": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontTableCFF"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontTableCFF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTableCFF"
        }
      ],
      "role": "symbol",
      "title": "kCTFontTableCFF",
      "type": "topic",
      "url": "/documentation/coretext/kctfonttablecff"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontTableDSIG": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontTableDSIG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontTableDSIG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTableDSIG"
        }
      ],
      "role": "symbol",
      "title": "kCTFontTableDSIG",
      "type": "topic",
      "url": "/documentation/coretext/kctfonttabledsig"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontTableEBDT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontTableEBDT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontTableEBDT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTableEBDT"
        }
      ],
      "role": "symbol",
      "title": "kCTFontTableEBDT",
      "type": "topic",
      "url": "/documentation/coretext/kctfonttableebdt"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontTableEBLC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontTableEBLC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontTableEBLC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTableEBLC"
        }
      ],
      "role": "symbol",
      "title": "kCTFontTableEBLC",
      "type": "topic",
      "url": "/documentation/coretext/kctfonttableeblc"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontTableEBSC": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontTableEBSC"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontTableEBSC",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTableEBSC"
        }
      ],
      "role": "symbol",
      "title": "kCTFontTableEBSC",
      "type": "topic",
      "url": "/documentation/coretext/kctfonttableebsc"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontTableGDEF": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontTableGDEF"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontTableGDEF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTableGDEF"
        }
      ],
      "role": "symbol",
      "title": "kCTFontTableGDEF",
      "type": "topic",
      "url": "/documentation/coretext/kctfonttablegdef"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontTableGPOS": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontTableGPOS"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontTableGPOS",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTableGPOS"
        }
      ],
      "role": "symbol",
      "title": "kCTFontTableGPOS",
      "type": "topic",
      "url": "/documentation/coretext/kctfonttablegpos"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontTableGSUB": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontTableGSUB"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontTableGSUB",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTableGSUB"
        }
      ],
      "role": "symbol",
      "title": "kCTFontTableGSUB",
      "type": "topic",
      "url": "/documentation/coretext/kctfonttablegsub"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontTableJSTF": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontTableJSTF"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontTableJSTF",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTableJSTF"
        }
      ],
      "role": "symbol",
      "title": "kCTFontTableJSTF",
      "type": "topic",
      "url": "/documentation/coretext/kctfonttablejstf"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontTableLTSH": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontTableLTSH"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontTableLTSH",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTableLTSH"
        }
      ],
      "role": "symbol",
      "title": "kCTFontTableLTSH",
      "type": "topic",
      "url": "/documentation/coretext/kctfonttableltsh"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontTableOS2": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontTableOS2"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontTableOS2",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTableOS2"
        }
      ],
      "role": "symbol",
      "title": "kCTFontTableOS2",
      "type": "topic",
      "url": "/documentation/coretext/kctfonttableos2"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontTablePCLT": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontTablePCLT"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontTablePCLT",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTablePCLT"
        }
      ],
      "role": "symbol",
      "title": "kCTFontTablePCLT",
      "type": "topic",
      "url": "/documentation/coretext/kctfonttablepclt"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontTableTrak": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontTableTrak"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontTableTrak",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTableTrak"
        }
      ],
      "role": "symbol",
      "title": "kCTFontTableTrak",
      "type": "topic",
      "url": "/documentation/coretext/kctfonttabletrak"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontTableVDMX": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontTableVDMX"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontTableVDMX",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTableVDMX"
        }
      ],
      "role": "symbol",
      "title": "kCTFontTableVDMX",
      "type": "topic",
      "url": "/documentation/coretext/kctfonttablevdmx"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontTableVORG": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontTableVORG"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontTableVORG",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontTableVORG"
        }
      ],
      "role": "symbol",
      "title": "kCTFontTableVORG",
      "type": "topic",
      "url": "/documentation/coretext/kctfonttablevorg"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/kCTFontTableBASE",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontTableCFF",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontTableDSIG",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontTableEBDT",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontTableEBLC",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontTableEBSC",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontTableGDEF",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontTableGPOS",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontTableGSUB",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontTableJSTF",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontTableLTSH",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontTableOS2",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontTablePCLT",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontTableVDMX",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontTableVORG"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCTFontTableTrak"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTableTrak"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/kCTFontTableBASE",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontTableCFF",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontTableDSIG",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontTableEBDT",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontTableEBLC",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontTableEBSC",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontTableGDEF",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontTableGPOS",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontTableGSUB",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontTableJSTF",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontTableLTSH",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontTableOS2",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontTablePCLT",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontTableVDMX",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontTableVORG"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kCTFontTableTrak"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontTableVDMX/title",
          "value": "kCTFontTableVDMX"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontTableVDMX/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTableVDMX"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontTableGDEF/title",
          "value": "kCTFontTableGDEF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontTableGDEF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTableGDEF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontTableCFF/title",
          "value": "kCTFontTableCFF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontTableCFF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTableCFF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontTableOS2/title",
          "value": "kCTFontTableOS2"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontTableOS2/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTableOS2"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontTableEBLC/title",
          "value": "kCTFontTableEBLC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontTableEBLC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTableEBLC"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontTableEBDT/title",
          "value": "kCTFontTableEBDT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontTableEBDT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTableEBDT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontTableGSUB/title",
          "value": "kCTFontTableGSUB"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontTableGSUB/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTableGSUB"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontTableLTSH/title",
          "value": "kCTFontTableLTSH"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontTableLTSH/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTableLTSH"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontTableTrak/title",
          "value": "kCTFontTableTrak"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontTableTrak/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTableTrak"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontTableJSTF/title",
          "value": "kCTFontTableJSTF"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontTableJSTF/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTableJSTF"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontTableGPOS/title",
          "value": "kCTFontTableGPOS"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontTableGPOS/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTableGPOS"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontTablePCLT/title",
          "value": "kCTFontTablePCLT"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontTablePCLT/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTablePCLT"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontTableBASE/title",
          "value": "kCTFontTableBASE"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontTableBASE/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTableBASE"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontTableVORG/title",
          "value": "kCTFontTableVORG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontTableVORG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTableVORG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontTableDSIG/title",
          "value": "kCTFontTableDSIG"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontTableDSIG/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTableDSIG"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontTableEBSC/title",
          "value": "kCTFontTableEBSC"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontTableEBSC/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontTableEBSC"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/kctfonttabletrak"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/kctfonttabletrak"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
