{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSelectorSettingKey"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCTFontFeatureSelectorSettingKey",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCTFontFeatureSelectorSettingKey"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCTFontFeatureSelectorSettingKey"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.2",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.5",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "9.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "2.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCTFontFeatureSelectorSettingKey"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCTFontFeatureSelectorSettingKey"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "Key to be used with a selector dictionary to get or specify the current setting for the selector. This value is a ",
              "type": "text"
            },
            {
              "code": "CFBooleanRef",
              "type": "codeVoice"
            },
            {
              "text": " object to indicate whether this selector is on or off. If this key is not present, the default setting is used.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSampleTextKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontFeatureSampleTextKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSampleTextKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFeatureSampleTextKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontFeatureSampleTextKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontfeaturesampletextkey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSelectorDefaultKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontFeatureSelectorDefaultKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSelectorDefaultKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFeatureSelectorDefaultKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontFeatureSelectorDefaultKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontfeatureselectordefaultkey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSelectorIdentifierKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontFeatureSelectorIdentifierKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSelectorIdentifierKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFeatureSelectorIdentifierKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontFeatureSelectorIdentifierKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontfeatureselectoridentifierkey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSelectorNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontFeatureSelectorNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSelectorNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFeatureSelectorNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontFeatureSelectorNameKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontfeatureselectornamekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSelectorSettingKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontFeatureSelectorSettingKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSelectorSettingKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFeatureSelectorSettingKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontFeatureSelectorSettingKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontfeatureselectorsettingkey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureTooltipTextKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontFeatureTooltipTextKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureTooltipTextKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFeatureTooltipTextKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontFeatureTooltipTextKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontfeaturetooltiptextkey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureTypeExclusiveKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontFeatureTypeExclusiveKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureTypeExclusiveKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFeatureTypeExclusiveKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontFeatureTypeExclusiveKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontfeaturetypeexclusivekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureTypeIdentifierKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontFeatureTypeIdentifierKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureTypeIdentifierKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFeatureTypeIdentifierKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontFeatureTypeIdentifierKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontfeaturetypeidentifierkey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureTypeNameKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontFeatureTypeNameKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureTypeNameKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFeatureTypeNameKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontFeatureTypeNameKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontfeaturetypenamekey"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureTypeSelectorsKey": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontFeatureTypeSelectorsKey"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureTypeSelectorsKey",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontFeatureTypeSelectorsKey"
        }
      ],
      "role": "symbol",
      "title": "kCTFontFeatureTypeSelectorsKey",
      "type": "topic",
      "url": "/documentation/coretext/kctfontfeaturetypeselectorskey"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureTypeIdentifierKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureTypeNameKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureTypeExclusiveKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureTypeSelectorsKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSelectorIdentifierKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSelectorNameKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSelectorDefaultKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSampleTextKey",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureTooltipTextKey"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.2",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.5",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "9.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "2.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCTFontFeatureSelectorSettingKey"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFeatureSelectorSettingKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureTypeIdentifierKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureTypeNameKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureTypeExclusiveKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureTypeSelectorsKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSelectorIdentifierKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSelectorNameKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSelectorDefaultKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureSampleTextKey",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontFeatureTooltipTextKey"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCTFontFeatureSelectorSettingKey"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureTypeIdentifierKey/title",
          "value": "kCTFontFeatureTypeIdentifierKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureTypeIdentifierKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFeatureTypeIdentifierKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureSelectorIdentifierKey/title",
          "value": "kCTFontFeatureSelectorIdentifierKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureSelectorIdentifierKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFeatureSelectorIdentifierKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureSelectorNameKey/title",
          "value": "kCTFontFeatureSelectorNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureSelectorNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFeatureSelectorNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureSampleTextKey/title",
          "value": "kCTFontFeatureSampleTextKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureSampleTextKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFeatureSampleTextKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureTypeExclusiveKey/title",
          "value": "kCTFontFeatureTypeExclusiveKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureTypeExclusiveKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFeatureTypeExclusiveKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureSelectorDefaultKey/title",
          "value": "kCTFontFeatureSelectorDefaultKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureSelectorDefaultKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFeatureSelectorDefaultKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureTooltipTextKey/title",
          "value": "kCTFontFeatureTooltipTextKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureTooltipTextKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFeatureTooltipTextKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureTypeSelectorsKey/title",
          "value": "kCTFontFeatureTypeSelectorsKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureTypeSelectorsKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFeatureTypeSelectorsKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureTypeNameKey/title",
          "value": "kCTFontFeatureTypeNameKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureTypeNameKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFeatureTypeNameKey"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureSelectorSettingKey/title",
          "value": "kCTFontFeatureSelectorSettingKey"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontFeatureSelectorSettingKey/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontFeatureSelectorSettingKey"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/kctfontfeatureselectorsettingkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/kctfontfeatureselectorsettingkey"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
