{
  "abstract": [
    {
      "text": "The tracking for the text.",
      "type": "text"
    }
  ],
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/kCTTrackingAttributeName"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@kCTTrackingAttributeName",
    "fragments": [
      {
        "kind": "keyword",
        "text": "let"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kCTTrackingAttributeName"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "c:@T@CFStringRef",
        "text": "CFString"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kCTTrackingAttributeName"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "13.1",
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.12",
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "10.0",
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "1.0",
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "introducedAt": "3.0",
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kCTTrackingAttributeName"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "let"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kCTTrackingAttributeName"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
              "kind": "typeIdentifier",
              "preciseIdentifier": "c:@T@CFStringRef",
              "text": "CFString"
            }
          ]
        }
      ],
      "kind": "declarations"
    },
    {
      "content": [
        {
          "anchor": "Discussion",
          "level": 2,
          "text": "Discussion",
          "type": "heading"
        },
        {
          "inlineContent": [
            {
              "text": "The value associated with this attribute must be a ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfnumber-rjd",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " float. The default is ",
              "type": "text"
            },
            {
              "code": "0",
              "type": "codeVoice"
            },
            {
              "text": " (no tracking).",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "Tracking adds space, in points, between the specified ",
              "type": "text"
            },
            {
              "identifier": "https://unicode.org/reports/tr29/#Grapheme_Cluster_Boundaries",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ". A positive value increases the spacing between characters, while a negative value brings the characters closer together. For example, setting ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTTrackingAttributeName",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": " to 0.1 adds 0.1 point of spacing between each character of the text.",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "inlineContent": [
            {
              "text": "The effect of this attribute is similar to ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTKernAttributeName",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ", but it treats tracking as trailing whitespace and a nonzero amount disables nonessential ligatures, unless overridden by the presence of ",
              "type": "text"
            },
            {
              "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTLigatureAttributeName",
              "isActive": true,
              "type": "reference"
            },
            {
              "text": ".",
              "type": "text"
            }
          ],
          "type": "paragraph"
        },
        {
          "content": [
            {
              "inlineContent": [
                {
                  "text": "",
                  "type": "text"
                },
                {
                  "text": " ",
                  "type": "text"
                },
                {
                  "text": "If you apply both ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTTrackingAttributeName",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " and ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTKernAttributeName",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ", ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTTrackingAttributeName",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": " supersedes ",
                  "type": "text"
                },
                {
                  "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTKernAttributeName",
                  "isActive": true,
                  "type": "reference"
                },
                {
                  "text": ".",
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "name": "Important",
          "style": "important",
          "type": "aside"
        }
      ],
      "kind": "content"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTCharacterShapeAttributeName": {
      "abstract": [
        {
          "text": "Controls glyph selection.",
          "type": "text"
        }
      ],
      "deprecated": true,
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTCharacterShapeAttributeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTCharacterShapeAttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTCharacterShapeAttributeName"
        }
      ],
      "role": "symbol",
      "title": "kCTCharacterShapeAttributeName",
      "type": "topic",
      "url": "/documentation/coretext/kctcharactershapeattributename"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTFontAttributeName": {
      "abstract": [
        {
          "text": "The font of the text to which this attribute applies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTFontAttributeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTFontAttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTFontAttributeName"
        }
      ],
      "role": "symbol",
      "title": "kCTFontAttributeName",
      "type": "topic",
      "url": "/documentation/coretext/kctfontattributename"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTForegroundColorAttributeName": {
      "abstract": [
        {
          "text": "The foreground color of the text to which this attribute applies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTForegroundColorAttributeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTForegroundColorAttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTForegroundColorAttributeName"
        }
      ],
      "role": "symbol",
      "title": "kCTForegroundColorAttributeName",
      "type": "topic",
      "url": "/documentation/coretext/kctforegroundcolorattributename"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTForegroundColorFromContextAttributeName": {
      "abstract": [
        {
          "text": "Sets a foreground color using the context’s fill color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTForegroundColorFromContextAttributeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTForegroundColorFromContextAttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTForegroundColorFromContextAttributeName"
        }
      ],
      "role": "symbol",
      "title": "kCTForegroundColorFromContextAttributeName",
      "type": "topic",
      "url": "/documentation/coretext/kctforegroundcolorfromcontextattributename"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTGlyphInfoAttributeName": {
      "abstract": [
        {
          "text": "The glyph info object to apply to the text associated with this attribute.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTGlyphInfoAttributeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTGlyphInfoAttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTGlyphInfoAttributeName"
        }
      ],
      "role": "symbol",
      "title": "kCTGlyphInfoAttributeName",
      "type": "topic",
      "url": "/documentation/coretext/kctglyphinfoattributename"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTKernAttributeName": {
      "abstract": [
        {
          "text": "The amount to kern the next character.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTKernAttributeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTKernAttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTKernAttributeName"
        }
      ],
      "role": "symbol",
      "title": "kCTKernAttributeName",
      "type": "topic",
      "url": "/documentation/coretext/kctkernattributename"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTLigatureAttributeName": {
      "abstract": [
        {
          "text": "The type of ligatures to use.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTLigatureAttributeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTLigatureAttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTLigatureAttributeName"
        }
      ],
      "role": "symbol",
      "title": "kCTLigatureAttributeName",
      "type": "topic",
      "url": "/documentation/coretext/kctligatureattributename"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTParagraphStyleAttributeName": {
      "abstract": [
        {
          "text": "The paragraph style of the text to which this attribute applies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTParagraphStyleAttributeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTParagraphStyleAttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTParagraphStyleAttributeName"
        }
      ],
      "role": "symbol",
      "title": "kCTParagraphStyleAttributeName",
      "type": "topic",
      "url": "/documentation/coretext/kctparagraphstyleattributename"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTRunDelegateAttributeName": {
      "abstract": [
        {
          "text": "The run-delegate object to apply to an attribute range of the string.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTRunDelegateAttributeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTRunDelegateAttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTRunDelegateAttributeName"
        }
      ],
      "role": "symbol",
      "title": "kCTRunDelegateAttributeName",
      "type": "topic",
      "url": "/documentation/coretext/kctrundelegateattributename"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTStrokeColorAttributeName": {
      "abstract": [
        {
          "text": "The stroke color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTStrokeColorAttributeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTStrokeColorAttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTStrokeColorAttributeName"
        }
      ],
      "role": "symbol",
      "title": "kCTStrokeColorAttributeName",
      "type": "topic",
      "url": "/documentation/coretext/kctstrokecolorattributename"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTStrokeWidthAttributeName": {
      "abstract": [
        {
          "text": "The stroke width.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTStrokeWidthAttributeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTStrokeWidthAttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTStrokeWidthAttributeName"
        }
      ],
      "role": "symbol",
      "title": "kCTStrokeWidthAttributeName",
      "type": "topic",
      "url": "/documentation/coretext/kctstrokewidthattributename"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTSuperscriptAttributeName": {
      "abstract": [
        {
          "text": "Controls vertical text positioning.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTSuperscriptAttributeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTSuperscriptAttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTSuperscriptAttributeName"
        }
      ],
      "role": "symbol",
      "title": "kCTSuperscriptAttributeName",
      "type": "topic",
      "url": "/documentation/coretext/kctsuperscriptattributename"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTTrackingAttributeName": {
      "abstract": [
        {
          "text": "The tracking for the text.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTTrackingAttributeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTTrackingAttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTTrackingAttributeName"
        }
      ],
      "role": "symbol",
      "title": "kCTTrackingAttributeName",
      "type": "topic",
      "url": "/documentation/coretext/kcttrackingattributename"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTUnderlineColorAttributeName": {
      "abstract": [
        {
          "text": "The underline color.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTUnderlineColorAttributeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTUnderlineColorAttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTUnderlineColorAttributeName"
        }
      ],
      "role": "symbol",
      "title": "kCTUnderlineColorAttributeName",
      "type": "topic",
      "url": "/documentation/coretext/kctunderlinecolorattributename"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTUnderlineStyleAttributeName": {
      "abstract": [
        {
          "text": "The style of underlining, to be applied at render time, for the text to which this attribute applies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTUnderlineStyleAttributeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTUnderlineStyleAttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTUnderlineStyleAttributeName"
        }
      ],
      "role": "symbol",
      "title": "kCTUnderlineStyleAttributeName",
      "type": "topic",
      "url": "/documentation/coretext/kctunderlinestyleattributename"
    },
    "doc://com.apple.coretext/documentation/CoreText/kCTVerticalFormsAttributeName": {
      "abstract": [
        {
          "text": "The orientation of the glyphs in the text to which this attribute applies.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "let"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kCTVerticalFormsAttributeName"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "c:@T@CFStringRef",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kCTVerticalFormsAttributeName",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kCTVerticalFormsAttributeName"
        }
      ],
      "role": "symbol",
      "title": "kCTVerticalFormsAttributeName",
      "type": "topic",
      "url": "/documentation/coretext/kctverticalformsattributename"
    },
    "doc://com.apple.documentation/documentation/corefoundation/cfnumber-rjd": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/corefoundation/cfnumber-rjd",
      "kind": "article",
      "role": "article",
      "title": "CFNumber",
      "type": "topic",
      "url": "/documentation/corefoundation/cfnumber-rjd"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/c:@T@CFStringRef": {
      "abstract": [
        {
          "text": "A reference to a CFString object.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "text",
          "text": "class "
        },
        {
          "kind": "identifier",
          "text": "CFString"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
      "kind": "symbol",
      "role": "symbol",
      "title": "CFString",
      "type": "topic",
      "url": "/documentation/corefoundation/cfstring"
    },
    "https://unicode.org/reports/tr29/#Grapheme_Cluster_Boundaries": {
      "identifier": "https://unicode.org/reports/tr29/#Grapheme_Cluster_Boundaries",
      "title": "character cluster",
      "titleInlineContent": [
        {
          "text": "character cluster",
          "type": "text"
        }
      ],
      "type": "link",
      "url": "https://unicode.org/reports/tr29/#Grapheme_Cluster_Boundaries"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Related-Documentation",
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/kCTKernAttributeName",
        "doc://com.apple.coretext/documentation/CoreText/kCTLigatureAttributeName"
      ],
      "title": "Related Documentation"
    },
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/kCTCharacterShapeAttributeName",
        "doc://com.apple.coretext/documentation/CoreText/kCTFontAttributeName",
        "doc://com.apple.coretext/documentation/CoreText/kCTKernAttributeName",
        "doc://com.apple.coretext/documentation/CoreText/kCTLigatureAttributeName",
        "doc://com.apple.coretext/documentation/CoreText/kCTForegroundColorAttributeName",
        "doc://com.apple.coretext/documentation/CoreText/kCTForegroundColorFromContextAttributeName",
        "doc://com.apple.coretext/documentation/CoreText/kCTParagraphStyleAttributeName",
        "doc://com.apple.coretext/documentation/CoreText/kCTStrokeWidthAttributeName",
        "doc://com.apple.coretext/documentation/CoreText/kCTStrokeColorAttributeName",
        "doc://com.apple.coretext/documentation/CoreText/kCTSuperscriptAttributeName",
        "doc://com.apple.coretext/documentation/CoreText/kCTUnderlineColorAttributeName",
        "doc://com.apple.coretext/documentation/CoreText/kCTUnderlineStyleAttributeName",
        "doc://com.apple.coretext/documentation/CoreText/kCTVerticalFormsAttributeName",
        "doc://com.apple.coretext/documentation/CoreText/kCTGlyphInfoAttributeName",
        "doc://com.apple.coretext/documentation/CoreText/kCTRunDelegateAttributeName"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "13.1",
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.12",
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "10.0",
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "1.0",
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "introducedAt": "3.0",
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Global Variable"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kCTTrackingAttributeName"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "var"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTTrackingAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Related-Documentation",
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/kCTKernAttributeName",
                "doc://com.apple.coretext/documentation/CoreText/kCTLigatureAttributeName"
              ],
              "title": "Related Documentation"
            },
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/kCTCharacterShapeAttributeName",
                "doc://com.apple.coretext/documentation/CoreText/kCTFontAttributeName",
                "doc://com.apple.coretext/documentation/CoreText/kCTKernAttributeName",
                "doc://com.apple.coretext/documentation/CoreText/kCTLigatureAttributeName",
                "doc://com.apple.coretext/documentation/CoreText/kCTForegroundColorAttributeName",
                "doc://com.apple.coretext/documentation/CoreText/kCTForegroundColorFromContextAttributeName",
                "doc://com.apple.coretext/documentation/CoreText/kCTParagraphStyleAttributeName",
                "doc://com.apple.coretext/documentation/CoreText/kCTStrokeWidthAttributeName",
                "doc://com.apple.coretext/documentation/CoreText/kCTStrokeColorAttributeName",
                "doc://com.apple.coretext/documentation/CoreText/kCTSuperscriptAttributeName",
                "doc://com.apple.coretext/documentation/CoreText/kCTUnderlineColorAttributeName",
                "doc://com.apple.coretext/documentation/CoreText/kCTUnderlineStyleAttributeName",
                "doc://com.apple.coretext/documentation/CoreText/kCTVerticalFormsAttributeName",
                "doc://com.apple.coretext/documentation/CoreText/kCTGlyphInfoAttributeName",
                "doc://com.apple.coretext/documentation/CoreText/kCTRunDelegateAttributeName"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "extern"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "identifier": "doc://com.externally.resolved.symbol/c:@T@CFStringRef",
                    "kind": "typeIdentifier",
                    "preciseIdentifier": "c:@T@CFStringRef",
                    "text": "CFStringRef"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "keyword",
                    "text": "const"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "kCTTrackingAttributeName"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTStrokeWidthAttributeName/title",
          "value": "kCTStrokeWidthAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTStrokeWidthAttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTStrokeWidthAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTUnderlineStyleAttributeName/title",
          "value": "kCTUnderlineStyleAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTUnderlineStyleAttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTUnderlineStyleAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTCharacterShapeAttributeName/title",
          "value": "kCTCharacterShapeAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTCharacterShapeAttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTCharacterShapeAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTRunDelegateAttributeName/title",
          "value": "kCTRunDelegateAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTRunDelegateAttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTRunDelegateAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTParagraphStyleAttributeName/title",
          "value": "kCTParagraphStyleAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTParagraphStyleAttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTParagraphStyleAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.externally.resolved.symbol~1c:@T@CFStringRef/title",
          "value": "CFStringRef"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTLigatureAttributeName/title",
          "value": "kCTLigatureAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTLigatureAttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTLigatureAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTTrackingAttributeName/title",
          "value": "kCTTrackingAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTTrackingAttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTTrackingAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTSuperscriptAttributeName/title",
          "value": "kCTSuperscriptAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTSuperscriptAttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTSuperscriptAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTStrokeColorAttributeName/title",
          "value": "kCTStrokeColorAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTStrokeColorAttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTStrokeColorAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTForegroundColorAttributeName/title",
          "value": "kCTForegroundColorAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTForegroundColorAttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTForegroundColorAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTForegroundColorFromContextAttributeName/title",
          "value": "kCTForegroundColorFromContextAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTForegroundColorFromContextAttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTForegroundColorFromContextAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontAttributeName/title",
          "value": "kCTFontAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTFontAttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTFontAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTVerticalFormsAttributeName/title",
          "value": "kCTVerticalFormsAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTVerticalFormsAttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTVerticalFormsAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTKernAttributeName/title",
          "value": "kCTKernAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTKernAttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTKernAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTGlyphInfoAttributeName/title",
          "value": "kCTGlyphInfoAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTGlyphInfoAttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTGlyphInfoAttributeName"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTUnderlineColorAttributeName/title",
          "value": "kCTUnderlineColorAttributeName"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kCTUnderlineColorAttributeName/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kCTUnderlineColorAttributeName"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/kcttrackingattributename"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/kcttrackingattributename"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
