{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@S@KernIndexArrayHeader",
    "fragments": [
      {
        "kind": "keyword",
        "text": "struct"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "KernIndexArrayHeader"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "KernIndexArrayHeader"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Structure",
    "symbolKind": "struct",
    "title": "KernIndexArrayHeader"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "struct"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "KernIndexArrayHeader"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/AnchorPoint": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AnchorPoint"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/AnchorPoint",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AnchorPoint"
        }
      ],
      "role": "symbol",
      "title": "AnchorPoint",
      "type": "topic",
      "url": "/documentation/coretext/anchorpoint"
    },
    "doc://com.apple.coretext/documentation/CoreText/AnchorPointTable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AnchorPointTable"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/AnchorPointTable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AnchorPointTable"
        }
      ],
      "role": "symbol",
      "title": "AnchorPointTable",
      "type": "topic",
      "url": "/documentation/coretext/anchorpointtable"
    },
    "doc://com.apple.coretext/documentation/CoreText/AnkrTable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "AnkrTable"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/AnkrTable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "AnkrTable"
        }
      ],
      "role": "symbol",
      "title": "AnkrTable",
      "type": "topic",
      "url": "/documentation/coretext/ankrtable"
    },
    "doc://com.apple.coretext/documentation/CoreText/BslnFormat0Part": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BslnFormat0Part"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/BslnFormat0Part",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BslnFormat0Part"
        }
      ],
      "role": "symbol",
      "title": "BslnFormat0Part",
      "type": "topic",
      "url": "/documentation/coretext/bslnformat0part"
    },
    "doc://com.apple.coretext/documentation/CoreText/BslnFormat1Part": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BslnFormat1Part"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/BslnFormat1Part",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BslnFormat1Part"
        }
      ],
      "role": "symbol",
      "title": "BslnFormat1Part",
      "type": "topic",
      "url": "/documentation/coretext/bslnformat1part"
    },
    "doc://com.apple.coretext/documentation/CoreText/BslnFormat2Part": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BslnFormat2Part"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/BslnFormat2Part",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BslnFormat2Part"
        }
      ],
      "role": "symbol",
      "title": "BslnFormat2Part",
      "type": "topic",
      "url": "/documentation/coretext/bslnformat2part"
    },
    "doc://com.apple.coretext/documentation/CoreText/BslnFormat3Part": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BslnFormat3Part"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/BslnFormat3Part",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BslnFormat3Part"
        }
      ],
      "role": "symbol",
      "title": "BslnFormat3Part",
      "type": "topic",
      "url": "/documentation/coretext/bslnformat3part"
    },
    "doc://com.apple.coretext/documentation/CoreText/BslnFormatUnion": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BslnFormatUnion"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/BslnFormatUnion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BslnFormatUnion"
        }
      ],
      "role": "symbol",
      "title": "BslnFormatUnion",
      "type": "topic",
      "url": "/documentation/coretext/bslnformatunion"
    },
    "doc://com.apple.coretext/documentation/CoreText/BslnTable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BslnTable"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/BslnTable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "BslnTable"
        }
      ],
      "role": "symbol",
      "title": "BslnTable",
      "type": "topic",
      "url": "/documentation/coretext/bslntable"
    },
    "doc://com.apple.coretext/documentation/CoreText/FontVariation": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "FontVariation"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/FontVariation",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "FontVariation"
        }
      ],
      "role": "symbol",
      "title": "FontVariation",
      "type": "topic",
      "url": "/documentation/coretext/fontvariation"
    },
    "doc://com.apple.coretext/documentation/CoreText/JustDirectionTable": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JustDirectionTable"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/JustDirectionTable",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JustDirectionTable"
        }
      ],
      "role": "symbol",
      "title": "JustDirectionTable",
      "type": "topic",
      "url": "/documentation/coretext/justdirectiontable"
    },
    "doc://com.apple.coretext/documentation/CoreText/JustPCAction": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JustPCAction"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/JustPCAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JustPCAction"
        }
      ],
      "role": "symbol",
      "title": "JustPCAction",
      "type": "topic",
      "url": "/documentation/coretext/justpcaction"
    },
    "doc://com.apple.coretext/documentation/CoreText/JustPCActionSubrecord": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JustPCActionSubrecord"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/JustPCActionSubrecord",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JustPCActionSubrecord"
        }
      ],
      "role": "symbol",
      "title": "JustPCActionSubrecord",
      "type": "topic",
      "url": "/documentation/coretext/justpcactionsubrecord"
    },
    "doc://com.apple.coretext/documentation/CoreText/JustPCConditionalAddAction": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JustPCConditionalAddAction"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/JustPCConditionalAddAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JustPCConditionalAddAction"
        }
      ],
      "role": "symbol",
      "title": "JustPCConditionalAddAction",
      "type": "topic",
      "url": "/documentation/coretext/justpcconditionaladdaction"
    },
    "doc://com.apple.coretext/documentation/CoreText/JustPCDecompositionAction": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "JustPCDecompositionAction"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/JustPCDecompositionAction",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "JustPCDecompositionAction"
        }
      ],
      "role": "symbol",
      "title": "JustPCDecompositionAction",
      "type": "topic",
      "url": "/documentation/coretext/justpcdecompositionaction"
    },
    "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "KernIndexArrayHeader"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "KernIndexArrayHeader"
        }
      ],
      "role": "symbol",
      "title": "KernIndexArrayHeader",
      "type": "topic",
      "url": "/documentation/coretext/kernindexarrayheader"
    },
    "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/flags": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/flags",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "flags"
        }
      ],
      "role": "symbol",
      "title": "flags",
      "type": "topic",
      "url": "/documentation/coretext/kernindexarrayheader/flags"
    },
    "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/glyphCount": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "glyphCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/glyphCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "glyphCount"
        }
      ],
      "role": "symbol",
      "title": "glyphCount",
      "type": "topic",
      "url": "/documentation/coretext/kernindexarrayheader/glyphcount"
    },
    "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/init()": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "()"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/init()",
      "kind": "symbol",
      "role": "symbol",
      "title": "init()",
      "type": "topic",
      "url": "/documentation/coretext/kernindexarrayheader/init()"
    },
    "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/init(glyphCount:kernValueCount:leftClassCount:rightClassCount:flags:kernValue:leftClass:rightClass:kernIndex:)": {
      "abstract": [],
      "fragments": [
        {
          "kind": "identifier",
          "text": "init"
        },
        {
          "kind": "text",
          "text": "("
        },
        {
          "kind": "externalParam",
          "text": "glyphCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s6UInt16V",
          "text": "UInt16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "kernValueCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "leftClassCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "rightClassCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "flags"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "kernValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "leftClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "rightClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ", "
        },
        {
          "kind": "externalParam",
          "text": "kernIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        },
        {
          "kind": "text",
          "text": ")"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/init(glyphCount:kernValueCount:leftClassCount:rightClassCount:flags:kernValue:leftClass:rightClass:kernIndex:)",
      "kind": "symbol",
      "role": "symbol",
      "title": "init(glyphCount:kernValueCount:leftClassCount:rightClassCount:flags:kernValue:leftClass:rightClass:kernIndex:)",
      "type": "topic",
      "url": "/documentation/coretext/kernindexarrayheader/init(glyphcount:kernvaluecount:leftclasscount:rightclasscount:flags:kernvalue:leftclass:rightclass:kernindex:)"
    },
    "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/kernIndex": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kernIndex"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/kernIndex",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kernIndex"
        }
      ],
      "role": "symbol",
      "title": "kernIndex",
      "type": "topic",
      "url": "/documentation/coretext/kernindexarrayheader/kernindex"
    },
    "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/kernValue": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kernValue"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5Int16V",
          "text": "Int16"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/kernValue",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kernValue"
        }
      ],
      "role": "symbol",
      "title": "kernValue",
      "type": "topic",
      "url": "/documentation/coretext/kernindexarrayheader/kernvalue"
    },
    "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/kernValueCount": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kernValueCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/kernValueCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kernValueCount"
        }
      ],
      "role": "symbol",
      "title": "kernValueCount",
      "type": "topic",
      "url": "/documentation/coretext/kernindexarrayheader/kernvaluecount"
    },
    "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/leftClass": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/leftClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "leftClass"
        }
      ],
      "role": "symbol",
      "title": "leftClass",
      "type": "topic",
      "url": "/documentation/coretext/kernindexarrayheader/leftclass"
    },
    "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/leftClassCount": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "leftClassCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/leftClassCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "leftClassCount"
        }
      ],
      "role": "symbol",
      "title": "leftClassCount",
      "type": "topic",
      "url": "/documentation/coretext/kernindexarrayheader/leftclasscount"
    },
    "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/rightClass": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightClass"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/rightClass",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rightClass"
        }
      ],
      "role": "symbol",
      "title": "rightClass",
      "type": "topic",
      "url": "/documentation/coretext/kernindexarrayheader/rightclass"
    },
    "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/rightClassCount": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "rightClassCount"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:s5UInt8V",
          "text": "UInt8"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/rightClassCount",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "rightClassCount"
        }
      ],
      "role": "symbol",
      "title": "rightClassCount",
      "type": "topic",
      "url": "/documentation/coretext/kernindexarrayheader/rightclasscount"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "BitwiseCopyable"
        },
        {
          "kind": "text",
          "text": " : ~Escapable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "BitwiseCopyable",
      "type": "topic",
      "url": "/documentation/Swift/BitwiseCopyable"
    },
    "doc://com.externally.resolved.symbol/s:s8SendableP": {
      "abstract": [
        {
          "text": "A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "keyword",
          "text": "protocol"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Sendable"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:s8SendableP",
      "kind": "symbol",
      "role": "symbol",
      "title": "Sendable",
      "type": "topic",
      "url": "/documentation/Swift/Sendable"
    }
  },
  "relationshipsSections": [
    {
      "identifiers": [
        "doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP",
        "doc://com.externally.resolved.symbol/s:s8SendableP"
      ],
      "kind": "relationships",
      "title": "Conforms To",
      "type": "conformsTo"
    }
  ],
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Structures",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/AnchorPoint",
        "doc://com.apple.coretext/documentation/CoreText/AnchorPointTable",
        "doc://com.apple.coretext/documentation/CoreText/AnkrTable",
        "doc://com.apple.coretext/documentation/CoreText/BslnFormat0Part",
        "doc://com.apple.coretext/documentation/CoreText/BslnFormat1Part",
        "doc://com.apple.coretext/documentation/CoreText/BslnFormat2Part",
        "doc://com.apple.coretext/documentation/CoreText/BslnFormat3Part",
        "doc://com.apple.coretext/documentation/CoreText/BslnFormatUnion",
        "doc://com.apple.coretext/documentation/CoreText/BslnTable",
        "doc://com.apple.coretext/documentation/CoreText/FontVariation",
        "doc://com.apple.coretext/documentation/CoreText/JustDirectionTable",
        "doc://com.apple.coretext/documentation/CoreText/JustPCAction",
        "doc://com.apple.coretext/documentation/CoreText/JustPCActionSubrecord",
        "doc://com.apple.coretext/documentation/CoreText/JustPCConditionalAddAction",
        "doc://com.apple.coretext/documentation/CoreText/JustPCDecompositionAction"
      ],
      "title": "Structures"
    }
  ],
  "topicSections": [
    {
      "anchor": "Initializers",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/init()",
        "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/init(glyphCount:kernValueCount:leftClassCount:rightClassCount:flags:kernValue:leftClass:rightClass:kernIndex:)"
      ],
      "title": "Initializers"
    },
    {
      "anchor": "Instance-Properties",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/flags",
        "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/glyphCount",
        "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/kernIndex",
        "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/kernValue",
        "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/kernValueCount",
        "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/leftClass",
        "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/leftClassCount",
        "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/rightClass",
        "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/rightClassCount"
      ],
      "title": "Instance Properties"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Structure"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "KernIndexArrayHeader"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "struct"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "KernIndexArrayHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "KernIndexArrayHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText"
              ]
            ]
          }
        },
        {
          "op": "replace",
          "path": "/topicSections",
          "value": [
            {
              "anchor": "Instance-Properties",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/flags",
                "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/glyphCount",
                "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/kernIndex",
                "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/kernValue",
                "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/kernValueCount",
                "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/leftClass",
                "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/leftClassCount",
                "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/rightClass",
                "doc://com.apple.coretext/documentation/CoreText/KernIndexArrayHeader/rightClassCount"
              ],
              "title": "Instance Properties"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Structures",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/AnchorPoint",
                "doc://com.apple.coretext/documentation/CoreText/AnchorPointTable",
                "doc://com.apple.coretext/documentation/CoreText/AnkrTable",
                "doc://com.apple.coretext/documentation/CoreText/BslnFormat0Part",
                "doc://com.apple.coretext/documentation/CoreText/BslnFormat1Part",
                "doc://com.apple.coretext/documentation/CoreText/BslnFormat2Part",
                "doc://com.apple.coretext/documentation/CoreText/BslnFormat3Part",
                "doc://com.apple.coretext/documentation/CoreText/BslnFormatUnion",
                "doc://com.apple.coretext/documentation/CoreText/BslnTable",
                "doc://com.apple.coretext/documentation/CoreText/FontVariation",
                "doc://com.apple.coretext/documentation/CoreText/JustDirectionTable",
                "doc://com.apple.coretext/documentation/CoreText/JustPCAction",
                "doc://com.apple.coretext/documentation/CoreText/JustPCActionSubrecord",
                "doc://com.apple.coretext/documentation/CoreText/JustPCConditionalAddAction",
                "doc://com.apple.coretext/documentation/CoreText/JustPCDecompositionAction"
              ],
              "title": "Structures"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "keyword",
                    "text": "struct"
                  },
                  {
                    "kind": "text",
                    "text": " "
                  },
                  {
                    "kind": "identifier",
                    "text": "KernIndexArrayHeader"
                  },
                  {
                    "kind": "text",
                    "text": ";"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1JustPCAction/title",
          "value": "JustPCAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1JustPCAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JustPCAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1JustPCAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JustPCAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernIndexArrayHeader~1kernIndex/title",
          "value": "kernIndex"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernIndexArrayHeader~1kernIndex/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kernIndex"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1AnkrTable/title",
          "value": "AnkrTable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1AnkrTable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AnkrTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1AnkrTable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AnkrTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1BslnFormatUnion/title",
          "value": "BslnFormatUnion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1BslnFormatUnion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BslnFormatUnion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1BslnFormatUnion/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BslnFormatUnion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1AnchorPoint/title",
          "value": "AnchorPoint"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1AnchorPoint/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AnchorPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1AnchorPoint/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AnchorPoint"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1AnchorPointTable/title",
          "value": "AnchorPointTable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1AnchorPointTable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "AnchorPointTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1AnchorPointTable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "AnchorPointTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1BslnFormat0Part/title",
          "value": "BslnFormat0Part"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1BslnFormat0Part/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BslnFormat0Part"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1BslnFormat0Part/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BslnFormat0Part"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1JustPCDecompositionAction/title",
          "value": "JustPCDecompositionAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1JustPCDecompositionAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JustPCDecompositionAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1JustPCDecompositionAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JustPCDecompositionAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernIndexArrayHeader/title",
          "value": "KernIndexArrayHeader"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernIndexArrayHeader/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "KernIndexArrayHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernIndexArrayHeader/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "KernIndexArrayHeader"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernIndexArrayHeader~1leftClassCount/title",
          "value": "leftClassCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernIndexArrayHeader~1leftClassCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "leftClassCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1BslnTable/title",
          "value": "BslnTable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1BslnTable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BslnTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1BslnTable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BslnTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernIndexArrayHeader~1kernValue/title",
          "value": "kernValue"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernIndexArrayHeader~1kernValue/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kernValue"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernIndexArrayHeader~1kernValueCount/title",
          "value": "kernValueCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernIndexArrayHeader~1kernValueCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kernValueCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1BslnFormat2Part/title",
          "value": "BslnFormat2Part"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1BslnFormat2Part/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BslnFormat2Part"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1BslnFormat2Part/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BslnFormat2Part"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1JustPCActionSubrecord/title",
          "value": "JustPCActionSubrecord"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1JustPCActionSubrecord/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JustPCActionSubrecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1JustPCActionSubrecord/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JustPCActionSubrecord"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1JustPCConditionalAddAction/title",
          "value": "JustPCConditionalAddAction"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1JustPCConditionalAddAction/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JustPCConditionalAddAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1JustPCConditionalAddAction/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JustPCConditionalAddAction"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernIndexArrayHeader~1leftClass/title",
          "value": "leftClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernIndexArrayHeader~1leftClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "leftClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernIndexArrayHeader~1rightClassCount/title",
          "value": "rightClassCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernIndexArrayHeader~1rightClassCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rightClassCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernIndexArrayHeader~1rightClass/title",
          "value": "rightClass"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernIndexArrayHeader~1rightClass/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "rightClass"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1BslnFormat1Part/title",
          "value": "BslnFormat1Part"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1BslnFormat1Part/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BslnFormat1Part"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1BslnFormat1Part/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BslnFormat1Part"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1BslnFormat3Part/title",
          "value": "BslnFormat3Part"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1BslnFormat3Part/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "BslnFormat3Part"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1BslnFormat3Part/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "BslnFormat3Part"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1FontVariation/title",
          "value": "FontVariation"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1FontVariation/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "FontVariation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1FontVariation/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "FontVariation"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernIndexArrayHeader~1glyphCount/title",
          "value": "glyphCount"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernIndexArrayHeader~1glyphCount/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "glyphCount"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernIndexArrayHeader~1flags/title",
          "value": "flags"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1KernIndexArrayHeader~1flags/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "flags"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1JustDirectionTable/title",
          "value": "JustDirectionTable"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1JustDirectionTable/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "JustDirectionTable"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1JustDirectionTable/navigatorTitle",
          "value": [
            {
              "kind": "identifier",
              "text": "JustDirectionTable"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/kernindexarrayheader"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/kernindexarrayheader"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
