{
  "hierarchy": {
    "paths": [
      [
        "doc://com.apple.documentation/documentation/technologies",
        "doc://com.apple.coretext/documentation/CoreText"
      ]
    ]
  },
  "identifier": {
    "interfaceLanguage": "swift",
    "url": "doc://com.apple.coretext/documentation/CoreText/kHojoCharactersSelector"
  },
  "kind": "symbol",
  "legalNotices": {
    "copyright": "Copyright &copy; 2025 Apple Inc. All rights reserved.",
    "privacyPolicy": "https://www.apple.com/privacy/privacy-policy",
    "termsOfUse": "https://www.apple.com/legal/internet-services/terms/site.html"
  },
  "metadata": {
    "externalID": "c:@Ea@kTraditionalCharactersSelector@kHojoCharactersSelector",
    "fragments": [
      {
        "kind": "keyword",
        "text": "var"
      },
      {
        "kind": "text",
        "text": " "
      },
      {
        "kind": "identifier",
        "text": "kHojoCharactersSelector"
      },
      {
        "kind": "text",
        "text": ": "
      },
      {
        "kind": "typeIdentifier",
        "preciseIdentifier": "s:Si",
        "text": "Int"
      }
    ],
    "modules": [
      {
        "name": "Core Text"
      }
    ],
    "navigatorTitle": [
      {
        "kind": "identifier",
        "text": "kHojoCharactersSelector"
      }
    ],
    "platforms": [
      {
        "beta": false,
        "deprecated": false,
        "name": "iOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "iPadOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "Mac Catalyst",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "macOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "tvOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "visionOS",
        "unavailable": false
      },
      {
        "beta": false,
        "deprecated": false,
        "name": "watchOS",
        "unavailable": false
      }
    ],
    "role": "symbol",
    "roleHeading": "Global Variable",
    "symbolKind": "var",
    "title": "kHojoCharactersSelector"
  },
  "primaryContentSections": [
    {
      "declarations": [
        {
          "languages": [
            "swift"
          ],
          "platforms": [
            "iOS",
            "iPadOS",
            "Mac Catalyst",
            "macOS",
            "tvOS",
            "visionOS",
            "watchOS"
          ],
          "tokens": [
            {
              "kind": "keyword",
              "text": "var"
            },
            {
              "kind": "text",
              "text": " "
            },
            {
              "kind": "identifier",
              "text": "kHojoCharactersSelector"
            },
            {
              "kind": "text",
              "text": ": "
            },
            {
              "identifier": "doc://com.externally.resolved.symbol/s:Si",
              "kind": "typeIdentifier",
              "preciseIdentifier": "s:Si",
              "text": "Int"
            },
            {
              "kind": "text",
              "text": " { "
            },
            {
              "kind": "keyword",
              "text": "get"
            },
            {
              "kind": "text",
              "text": " }"
            }
          ]
        }
      ],
      "kind": "declarations"
    }
  ],
  "references": {
    "doc://com.apple.coretext/documentation/CoreText": {
      "abstract": [
        {
          "text": "Create text layouts, optimize font handling, and access font metrics and glyph data.",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText",
      "kind": "symbol",
      "role": "collection",
      "title": "Core Text",
      "type": "topic",
      "url": "/documentation/coretext"
    },
    "doc://com.apple.coretext/documentation/CoreText/cmapFontTableTag": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "cmapFontTableTag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/cmapFontTableTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "cmapFontTableTag"
        }
      ],
      "role": "symbol",
      "title": "cmapFontTableTag",
      "type": "topic",
      "url": "/documentation/coretext/cmapfonttabletag"
    },
    "doc://com.apple.coretext/documentation/CoreText/descriptorFontTableTag": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "descriptorFontTableTag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/descriptorFontTableTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "descriptorFontTableTag"
        }
      ],
      "role": "symbol",
      "title": "descriptorFontTableTag",
      "type": "topic",
      "url": "/documentation/coretext/descriptorfonttabletag"
    },
    "doc://com.apple.coretext/documentation/CoreText/featureFontTableTag": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "featureFontTableTag"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/featureFontTableTag",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "featureFontTableTag"
        }
      ],
      "role": "symbol",
      "title": "featureFontTableTag",
      "type": "topic",
      "url": "/documentation/coretext/featurefonttabletag"
    },
    "doc://com.apple.coretext/documentation/CoreText/kANKRCurrentVersion": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kANKRCurrentVersion"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kANKRCurrentVersion",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kANKRCurrentVersion"
        }
      ],
      "role": "symbol",
      "title": "kANKRCurrentVersion",
      "type": "topic",
      "url": "/documentation/coretext/kankrcurrentversion"
    },
    "doc://com.apple.coretext/documentation/CoreText/kAbbrevSquaredLigaturesOffSelector": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAbbrevSquaredLigaturesOffSelector"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kAbbrevSquaredLigaturesOffSelector",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAbbrevSquaredLigaturesOffSelector"
        }
      ],
      "role": "symbol",
      "title": "kAbbrevSquaredLigaturesOffSelector",
      "type": "topic",
      "url": "/documentation/coretext/kabbrevsquaredligaturesoffselector"
    },
    "doc://com.apple.coretext/documentation/CoreText/kAbbrevSquaredLigaturesOnSelector": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAbbrevSquaredLigaturesOnSelector"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kAbbrevSquaredLigaturesOnSelector",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAbbrevSquaredLigaturesOnSelector"
        }
      ],
      "role": "symbol",
      "title": "kAbbrevSquaredLigaturesOnSelector",
      "type": "topic",
      "url": "/documentation/coretext/kabbrevsquaredligaturesonselector"
    },
    "doc://com.apple.coretext/documentation/CoreText/kAllCapsSelector": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAllCapsSelector"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kAllCapsSelector",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAllCapsSelector"
        }
      ],
      "role": "symbol",
      "title": "kAllCapsSelector",
      "type": "topic",
      "url": "/documentation/coretext/kallcapsselector"
    },
    "doc://com.apple.coretext/documentation/CoreText/kAllLowerCaseSelector": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAllLowerCaseSelector"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kAllLowerCaseSelector",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAllLowerCaseSelector"
        }
      ],
      "role": "symbol",
      "title": "kAllLowerCaseSelector",
      "type": "topic",
      "url": "/documentation/coretext/kalllowercaseselector"
    },
    "doc://com.apple.coretext/documentation/CoreText/kAllTypeFeaturesOffSelector": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAllTypeFeaturesOffSelector"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kAllTypeFeaturesOffSelector",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAllTypeFeaturesOffSelector"
        }
      ],
      "role": "symbol",
      "title": "kAllTypeFeaturesOffSelector",
      "type": "topic",
      "url": "/documentation/coretext/kalltypefeaturesoffselector"
    },
    "doc://com.apple.coretext/documentation/CoreText/kAllTypeFeaturesOnSelector": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAllTypeFeaturesOnSelector"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kAllTypeFeaturesOnSelector",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAllTypeFeaturesOnSelector"
        }
      ],
      "role": "symbol",
      "title": "kAllTypeFeaturesOnSelector",
      "type": "topic",
      "url": "/documentation/coretext/kalltypefeaturesonselector"
    },
    "doc://com.apple.coretext/documentation/CoreText/kAllTypographicFeaturesType": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAllTypographicFeaturesType"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kAllTypographicFeaturesType",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAllTypographicFeaturesType"
        }
      ],
      "role": "symbol",
      "title": "kAllTypographicFeaturesType",
      "type": "topic",
      "url": "/documentation/coretext/kalltypographicfeaturestype"
    },
    "doc://com.apple.coretext/documentation/CoreText/kAltHalfWidthTextSelector": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAltHalfWidthTextSelector"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kAltHalfWidthTextSelector",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAltHalfWidthTextSelector"
        }
      ],
      "role": "symbol",
      "title": "kAltHalfWidthTextSelector",
      "type": "topic",
      "url": "/documentation/coretext/kalthalfwidthtextselector"
    },
    "doc://com.apple.coretext/documentation/CoreText/kAltProportionalTextSelector": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAltProportionalTextSelector"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kAltProportionalTextSelector",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAltProportionalTextSelector"
        }
      ],
      "role": "symbol",
      "title": "kAltProportionalTextSelector",
      "type": "topic",
      "url": "/documentation/coretext/kaltproportionaltextselector"
    },
    "doc://com.apple.coretext/documentation/CoreText/kAlternateHorizKanaOffSelector": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAlternateHorizKanaOffSelector"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kAlternateHorizKanaOffSelector",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAlternateHorizKanaOffSelector"
        }
      ],
      "role": "symbol",
      "title": "kAlternateHorizKanaOffSelector",
      "type": "topic",
      "url": "/documentation/coretext/kalternatehorizkanaoffselector"
    },
    "doc://com.apple.coretext/documentation/CoreText/kAlternateHorizKanaOnSelector": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kAlternateHorizKanaOnSelector"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kAlternateHorizKanaOnSelector",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kAlternateHorizKanaOnSelector"
        }
      ],
      "role": "symbol",
      "title": "kAlternateHorizKanaOnSelector",
      "type": "topic",
      "url": "/documentation/coretext/kalternatehorizkanaonselector"
    },
    "doc://com.apple.coretext/documentation/CoreText/kHojoCharactersSelector": {
      "abstract": [],
      "fragments": [
        {
          "kind": "keyword",
          "text": "var"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "kHojoCharactersSelector"
        },
        {
          "kind": "text",
          "text": ": "
        },
        {
          "kind": "typeIdentifier",
          "preciseIdentifier": "s:Si",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.apple.coretext/documentation/CoreText/kHojoCharactersSelector",
      "kind": "symbol",
      "navigatorTitle": [
        {
          "kind": "identifier",
          "text": "kHojoCharactersSelector"
        }
      ],
      "role": "symbol",
      "title": "kHojoCharactersSelector",
      "type": "topic",
      "url": "/documentation/coretext/khojocharactersselector"
    },
    "doc://com.apple.documentation/documentation/technologies": {
      "abstract": [
        {
          "text": "",
          "type": "text"
        }
      ],
      "identifier": "doc://com.apple.documentation/documentation/technologies",
      "kind": "technologies",
      "role": "overview",
      "title": "Technologies",
      "type": "topic",
      "url": "/documentation/technologies"
    },
    "doc://com.externally.resolved.symbol/s:Si": {
      "abstract": [
        {
          "text": "A signed integer value type.",
          "type": "text"
        }
      ],
      "fragments": [
        {
          "kind": "attribute",
          "text": "@frozen"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "keyword",
          "text": "struct"
        },
        {
          "kind": "text",
          "text": " "
        },
        {
          "kind": "identifier",
          "text": "Int"
        }
      ],
      "identifier": "doc://com.externally.resolved.symbol/s:Si",
      "kind": "symbol",
      "role": "symbol",
      "title": "Int",
      "type": "topic",
      "url": "/documentation/Swift/Int"
    }
  },
  "schemaVersion": {
    "major": 0,
    "minor": 3,
    "patch": 0
  },
  "sections": [],
  "seeAlsoSections": [
    {
      "anchor": "Constants",
      "generated": true,
      "identifiers": [
        "doc://com.apple.coretext/documentation/CoreText/cmapFontTableTag",
        "doc://com.apple.coretext/documentation/CoreText/descriptorFontTableTag",
        "doc://com.apple.coretext/documentation/CoreText/featureFontTableTag",
        "doc://com.apple.coretext/documentation/CoreText/kANKRCurrentVersion",
        "doc://com.apple.coretext/documentation/CoreText/kAbbrevSquaredLigaturesOffSelector",
        "doc://com.apple.coretext/documentation/CoreText/kAbbrevSquaredLigaturesOnSelector",
        "doc://com.apple.coretext/documentation/CoreText/kAllCapsSelector",
        "doc://com.apple.coretext/documentation/CoreText/kAllLowerCaseSelector",
        "doc://com.apple.coretext/documentation/CoreText/kAllTypeFeaturesOffSelector",
        "doc://com.apple.coretext/documentation/CoreText/kAllTypeFeaturesOnSelector",
        "doc://com.apple.coretext/documentation/CoreText/kAllTypographicFeaturesType",
        "doc://com.apple.coretext/documentation/CoreText/kAltHalfWidthTextSelector",
        "doc://com.apple.coretext/documentation/CoreText/kAltProportionalTextSelector",
        "doc://com.apple.coretext/documentation/CoreText/kAlternateHorizKanaOffSelector",
        "doc://com.apple.coretext/documentation/CoreText/kAlternateHorizKanaOnSelector"
      ],
      "title": "Constants"
    }
  ],
  "variantOverrides": [
    {
      "patch": [
        {
          "op": "replace",
          "path": "/identifier/interfaceLanguage",
          "value": "occ"
        },
        {
          "op": "replace",
          "path": "/metadata/platforms",
          "value": [
            {
              "beta": false,
              "deprecated": false,
              "name": "iOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "iPadOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "Mac Catalyst",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "macOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "tvOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "visionOS",
              "unavailable": false
            },
            {
              "beta": false,
              "deprecated": false,
              "name": "watchOS",
              "unavailable": false
            }
          ]
        },
        {
          "op": "replace",
          "path": "/metadata/roleHeading",
          "value": "Enumeration Case"
        },
        {
          "op": "replace",
          "path": "/metadata/title",
          "value": "kHojoCharactersSelector"
        },
        {
          "op": "replace",
          "path": "/metadata/symbolKind",
          "value": "case"
        },
        {
          "op": "replace",
          "path": "/metadata/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kHojoCharactersSelector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/hierarchy",
          "value": {
            "paths": [
              [
                "doc://com.apple.documentation/documentation/technologies",
                "doc://com.apple.coretext/documentation/CoreText"
              ]
            ]
          }
        },
        {
          "op": "add",
          "path": "/topicSections",
          "value": null
        },
        {
          "op": "add",
          "path": "/relationshipsSections",
          "value": null
        },
        {
          "op": "replace",
          "path": "/seeAlsoSections",
          "value": [
            {
              "anchor": "Constants",
              "generated": true,
              "identifiers": [
                "doc://com.apple.coretext/documentation/CoreText/cmapFontTableTag",
                "doc://com.apple.coretext/documentation/CoreText/descriptorFontTableTag",
                "doc://com.apple.coretext/documentation/CoreText/featureFontTableTag",
                "doc://com.apple.coretext/documentation/CoreText/kANKRCurrentVersion",
                "doc://com.apple.coretext/documentation/CoreText/kAbbrevSquaredLigaturesOffSelector",
                "doc://com.apple.coretext/documentation/CoreText/kAbbrevSquaredLigaturesOnSelector",
                "doc://com.apple.coretext/documentation/CoreText/kAllCapsSelector",
                "doc://com.apple.coretext/documentation/CoreText/kAllLowerCaseSelector",
                "doc://com.apple.coretext/documentation/CoreText/kAllTypeFeaturesOffSelector",
                "doc://com.apple.coretext/documentation/CoreText/kAllTypeFeaturesOnSelector",
                "doc://com.apple.coretext/documentation/CoreText/kAllTypographicFeaturesType",
                "doc://com.apple.coretext/documentation/CoreText/kAltHalfWidthTextSelector",
                "doc://com.apple.coretext/documentation/CoreText/kAltProportionalTextSelector",
                "doc://com.apple.coretext/documentation/CoreText/kAlternateHorizKanaOffSelector",
                "doc://com.apple.coretext/documentation/CoreText/kAlternateHorizKanaOnSelector"
              ],
              "title": "Constants"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/primaryContentSections/0",
          "value": {
            "declarations": [
              {
                "languages": [
                  "occ"
                ],
                "platforms": [
                  "iOS",
                  "iPadOS",
                  "Mac Catalyst",
                  "macOS",
                  "tvOS",
                  "visionOS",
                  "watchOS"
                ],
                "tokens": [
                  {
                    "kind": "identifier",
                    "text": "kHojoCharactersSelector"
                  }
                ]
              }
            ],
            "kind": "declarations"
          }
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kAllLowerCaseSelector/title",
          "value": "kAllLowerCaseSelector"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kAllLowerCaseSelector/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAllLowerCaseSelector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kHojoCharactersSelector/title",
          "value": "kHojoCharactersSelector"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kHojoCharactersSelector/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kHojoCharactersSelector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kAllCapsSelector/title",
          "value": "kAllCapsSelector"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kAllCapsSelector/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAllCapsSelector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1featureFontTableTag/title",
          "value": "featureFontTableTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1featureFontTableTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "featureFontTableTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kAltHalfWidthTextSelector/title",
          "value": "kAltHalfWidthTextSelector"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kAltHalfWidthTextSelector/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAltHalfWidthTextSelector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kAltProportionalTextSelector/title",
          "value": "kAltProportionalTextSelector"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kAltProportionalTextSelector/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAltProportionalTextSelector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1descriptorFontTableTag/title",
          "value": "descriptorFontTableTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1descriptorFontTableTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "descriptorFontTableTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kAbbrevSquaredLigaturesOffSelector/title",
          "value": "kAbbrevSquaredLigaturesOffSelector"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kAbbrevSquaredLigaturesOffSelector/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAbbrevSquaredLigaturesOffSelector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1cmapFontTableTag/title",
          "value": "cmapFontTableTag"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1cmapFontTableTag/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "cmapFontTableTag"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kAlternateHorizKanaOffSelector/title",
          "value": "kAlternateHorizKanaOffSelector"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kAlternateHorizKanaOffSelector/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAlternateHorizKanaOffSelector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kAllTypeFeaturesOnSelector/title",
          "value": "kAllTypeFeaturesOnSelector"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kAllTypeFeaturesOnSelector/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAllTypeFeaturesOnSelector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kAllTypographicFeaturesType/title",
          "value": "kAllTypographicFeaturesType"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kAllTypographicFeaturesType/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAllTypographicFeaturesType"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kANKRCurrentVersion/title",
          "value": "kANKRCurrentVersion"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kANKRCurrentVersion/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kANKRCurrentVersion"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kAlternateHorizKanaOnSelector/title",
          "value": "kAlternateHorizKanaOnSelector"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kAlternateHorizKanaOnSelector/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAlternateHorizKanaOnSelector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kAbbrevSquaredLigaturesOnSelector/title",
          "value": "kAbbrevSquaredLigaturesOnSelector"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kAbbrevSquaredLigaturesOnSelector/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAbbrevSquaredLigaturesOnSelector"
            }
          ]
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kAllTypeFeaturesOffSelector/title",
          "value": "kAllTypeFeaturesOffSelector"
        },
        {
          "op": "replace",
          "path": "/references/doc:~1~1com.apple.coretext~1documentation~1CoreText~1kAllTypeFeaturesOffSelector/fragments",
          "value": [
            {
              "kind": "identifier",
              "text": "kAllTypeFeaturesOffSelector"
            }
          ]
        }
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ],
  "variants": [
    {
      "paths": [
        "/documentation/coretext/khojocharactersselector"
      ],
      "traits": [
        {
          "interfaceLanguage": "swift"
        }
      ]
    },
    {
      "paths": [
        "/documentation/coretext/khojocharactersselector"
      ],
      "traits": [
        {
          "interfaceLanguage": "occ"
        }
      ]
    }
  ]
}
